### ISSUE TITLE
Suggestion : choose which dictionary/dictionaries to use with a specific book?

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2120] opened 2016-07-01 08:59 UTC
* KOReader version: v2015.11-505-g30a9f73
* Device: Kobo Glo HD

I have several dictionaries installed on my Kobo.
Presently, Koreader searches the terms in all dictionaries. This can be annoying, specifically if you read books in several languages and if you have dictionaries in several languages too.

Could it be possible to decide which dictionary you want to use for one specific book or generally in Koreader?

**Comment by houqp** [comment] 2016-07-01 09:00
Good suggestion, we should be able to save this preference into book settings.

**Comment by Brnoch** [comment] 2016-07-01 09:04
Well, I just discovered that you can define the default dictionary to use for one specific book by pressing the dictionary name. But it seems that it doesn't work: after defining the default dictionary, the choosen dictionary doesn't show up before the other ones.

**Comment by houqp** [comment] 2016-07-01 09:06
Right... I forgot this feature is already implemented. I am marking this as a bug that needs to be fixed before the next stable release. Thanks!

**Comment by chrox** [comment] 2016-07-01 14:04
I cannot reproduce what you described neither on Kindle nor on Android. After setting the default dictionary for the document by tapping the dictionary title, the default dictionary will be used *if it has a definition of the word*. Are you sure you can select the default dictionary with "<<" and ">>" but it's not shown as the default dictionary?

**Comment by Brnoch** [comment] 2016-07-01 14:28
You're right. I made a test on a word in plural form ("félicitations"). This plural form didn't exist in the default dictionary, so that the one containing it appeared first. And as the default dictionary had "félicitation", it appeared next. There is no bug!
By the way, "félicitations" (congratulations) for the excellent koreader :-)

**Comment by chrox** [comment] 2016-07-01 14:31
Thanks for your report.

**Closed by chrox** 2016-07-01 14:31 UTC
Labels: bug

**Comment by inokani** [comment] 2024-07-15 11:27
Koreader: 2024.4
Reader: Pocketbook 632, U632.6.8.2102

1. I have two Stardict dictionaries downloaded on Koreader (de-de and de-en) and both are working fine. However, I can't change the default dictionary from de-de to de-en. I can switch between these two (if both have the searched word) by pressing the dictionary name but even though I select the translation from the de-en dictionary it does not change the default dictionary. Couldn't find any other means to change the dictionary either.

2. Also Koreader now and then offers entries from en-en dictionary even thought the book (and searched word) is in German.

3. And sometimes Koreader offers some other, similar like word instead of telling that it cannot find the searched word from dictionary (as it should).

**Comment by poire-z** [comment] 2024-07-15 11:43
> 1.

If you tap on the title bar, that dict will be made the "first" dict shown for that document:
![image](https://github.com/user-attachments/assets/b8ae1494-db6f-4548-a170-d2cc04e63f7e)
I guess that's what you mean with "by pressing the dictionary name", but if not, there's the info.
Not sure what you mean otherwise.

> 2. Also Koreader now and then offers entries from en-en dictionary even thought the book (and searched word) is in German.

There is no notion of dictionary language in stardict dicts/specs - so we can't implement anything like "use only German dicts when this book language is German".
I don't think this is a problem: if your German book contains Italian or English words, you'll be happy that results from any Italian or English dict are found.

> 3. And sometimes Koreader offers some other, similar like word instead of telling that it cannot find the searched word from dictionary (as it should).

That's probably "Fuzzy search" (that you can disable in the Dict settings menu). It's a feature :) better give you something approximate for you to analyze, than just telling you "bug off" :)

**Comment by inokani** [comment] 2024-07-15 12:17
1. Yes, I tap the title bar, but do not get info that the default dictionary is changed. The dictionary window changes to some what seethrough, that's all (see picture).
![image](https://github.com/user-attachments/assets/003e1e1f-f2ef-4d36-aa4d-e406e3fc0c2d)

2. & 3. ok. However, the searched word is in Germain and found dictionary item is in English, so probably the nro 3. fuzzy search has kicked in here too :)

**Comment by poire-z** [comment] 2024-07-15 12:22
> 1. Yes, I tap the title bar, but do not get info that the default dictionary is changed. The dictionary window changes to some what seethrough, that's all (see picture).

That means you did "long-press" (which on most widgets not having any specific handling of long-press, make them translucent).
You need to just "short tap" :)

**Comment by inokani** [comment] 2024-07-15 12:30
Now works as it should! Thank you for your immediate answers :)
