### ISSUE TITLE
Nightmode bug

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#6845] opened 2020-11-03 08:57 UTC
* KOReader version: v2020.10.1-28-g74c1813_2020-10-31/ 
* Device: Pocketbook InkPad 3

#### Issue
Images in books are shown in nightmode (inverted black & white) while text is shown normally, when book is reopened after closing it with nightmode activated.

#### Steps to reproduce
Open book with KOReader.
Activate nightmode (done via gesture). Text and images are shown inverted.
Close book.
Open same or other book. Splash screen is shown inverted, but book opens with black text on white background, i.e. like in normal mode. In the menu (gear) nightmode is shown as activated (checkbox). Images in the book, including the cover, are shown inverted.
Deactivating the checkbox or applying the nightmode gesture inverts text and background as in nightmode, but nightmode is shown as "off" in the menu.

In previous versions, images were not shown inverted at all with nightmode activated.

**Comment by NiLuJe** [comment] 2020-11-03 14:35
Define "previous version" :).

**Comment by LucyOne** [comment] 2020-11-03 15:19
I think this bug started with 2020.10.1-26, so any version before that.

**Comment by NiLuJe** [comment] 2020-11-03 16:05
Absolutely *nothing* nightmode related has changed in the last few days, so, if you could pinpoint that more accurately, that'd be helpful ;).

The last two PB-related changes were #6814 and #6794, and they both predate 2020.10.1-26 ;).

**Comment by LucyOne** [comment] 2020-11-03 16:52
I have 2020.10.1-14 on my other Inkpad 3 and on my Touch HD3. No sign of this bug there. Would you like me to test the versions inbetween?

**Comment by NiLuJe** [comment] 2020-11-03 21:21
If you have time and no-one chimes in with any bright ideas in between, yeah, that'd be helpful ;).

**Comment by pazos** [comment] 2020-11-03 23:40
> Would you like me to test the versions inbetween?

> If you have time and no-one chimes in with any bright ideas in between, yeah, that'd be helpful ;).

I would do that too, but first you can check a couple of things.

1. The files `applications/koreader.app` and `system/bin/koreader.app` are equal (check on the affected device and the other, unaffected, Inkpad 3.
2. Try to reproduce the issue with both methods:

    * using KO filemanager
    * using PB library

**Comment by LucyOne** [comment] 2020-11-04 09:38
I downgraded one-by-one from version 25 down to 14, which really is the last one without this bug. The bug appeared in books opened using the PB library and the KO filemanager, no difference. 
I didn't check whether the files are equal on both devices, but they both show the same behaviour now with v2020.10.1-14. 
However, I noticed something else related to nightmode. When activating nightmode via gesture, images in the book are not inverted. When activating and deactivating nightmode via menu, images are inverted.

I've found this pattern (closing the menu inbetween and viewing the page):
Activate NM via menu --> images are shown inverted
Deactivate NM via menu --> images stay inverted until going forth and back one page
Acivate NM via gesture --> images are not inverted
Deactivate NM via gesture --> images are not inverted
Acivate NM via gesture --> images are not inverted
Deactivate NM via menu --> images stay inverted until going forth and back one page

**Comment by NiLuJe** [comment] 2020-11-04 13:09
Does the image + gesture thing get better if you supply switch to the next page and then go back? What about cover thumbnails in the FM?

**Comment by LucyOne** [comment] 2020-11-04 13:24
As soon as I switch to the next page and back, the images are shown in their original, not inverted.
Cover thumbnails in the file manager stay the same, the original is shown always.
This is the behaviour in v2020.10.1-14. All my devices are on this version now. Let me know if you want me to test another version.

**Comment by NiLuJe** [comment] 2020-11-04 15:13
That would hint at #6794...

Can you post a *verbose debug* log from an affected (i.e., up-to-date) version?

**Comment by LucyOne** [comment] 2020-11-04 15:22
How do I create the verbose log?

**Comment by NiLuJe** [comment] 2020-11-04 15:24
Top menu, Gear > More tools > Developer options

Restart KOReader after toggling both options ;).

**Comment by NiLuJe** [comment] 2020-11-04 15:27
Also, because it's getting confusing, can you defined "normally" and "inverted".

i.e., use "Black on white" or "White on black" for text, and "mismatched" when images don't match what they ought to look like.

**Comment by NiLuJe** [comment] 2020-11-04 15:37
FWIW, the only thing I can confirm on a sane device (i.e., NXP, HW inversion, HW blitter) is that toggling NM via gesture while in CRe leads to mismatched images until pagination (while this is handled just fine via the menu, even before closing the menu).

You may be hitting even weirder corners cases because PB/B288/SW invert, but I'm not at my dev box, so I can't fake SW invert to check right now.

**Comment by LucyOne** [comment] 2020-11-04 16:56
I've updated one of my Inkpads to v2020.10.1-28 again. Sorry, but I can't find any developer options, neither in "Gear" nor in "Tools - More tools".
I did change the following setting: Gear - Screen - E-ink settings - Refresh speed/fidelity from Level 0 to Level 3. This took care of the nightmode bug described in my first post and the other weird behaviour with mismatched images. If I activate levels 0, 1, and 2, the nightmode bug returns.

BTW, how are images supposed to look in nightmode? Should they stay as they are or also invert colors?

**Comment by NiLuJe** [comment] 2020-11-04 17:06
It's in More tools, but only in the FM ;).

Okay, level 3 being buggy was kind of expected on a B288, so, at least that's another list of crappy B288 behavior we can add to the pile ^^.

----

We're supposed to keep images "readable" in night mode (which actually involves inverting them on our end, so that NM then inverts them *back*, which is why I asked for more precise wording than "inverted" ^^).

**Comment by LucyOne** [comment] 2020-11-04 17:27
Actually, Level 3 is the only one without the bug.

**Comment by NiLuJe** [comment] 2020-11-04 17:29
Just to confirm that it's indeed a B288 and detected properly as such, yeah ;).

**Comment by NiLuJe** [comment] 2020-11-04 17:30
> Actually, Level 3 is the only one without the bug.

Oops, slip of the tongue, my bad ;p.

**Comment by LucyOne** [comment] 2020-11-04 18:37
[crash.log](https://github.com/koreader/koreader/files/5489861/crash.log)

**Comment by NiLuJe** [comment] 2020-11-04 18:52
Okay, so it's indeed a B288, with HW inversion disabled.

Which means I have no idea why changing waveform modes would actually affect nightmode. Oh, well. :D.

**Closed** 2020-11-08 01:18 UTC
Labels: PocketBook, bug

**Comment by ploum** [comment] 2020-12-13 18:55
On pocketbook, it looks like closing koreader keeps the "nightmode" option checked while, in reality, going back to default. It means that the behaviour is now inversed : (you have to uncheck the option to have nightmode).

The only way to get out of the bug is to uncheck nightmode then exit koreader.
