### ISSUE TITLE
about recent list style change in CRE

### ISSUE THREAD

**Issue by frankyifei** [koreader/koreader#2107] opened 2016-06-26 13:47 UTC
recent changes to crengine caused several problems.  [#59](https://github.com/koreader/crengine/pull/59) did not fix it and created other problems.
I think best way is to revert  [#54](https://github.com/koreader/crengine/pull/54) , because it really breaks normal features and last commit  [#59](https://github.com/koreader/crengine/pull/59)  changes many things that we need to test. The cost / benefit ratio seems not so economical here for a small feature(negative x). 
For example, list-000-ordered.epub in test suite. 
it was normal 
![reader_2016-jun-26_223627](https://cloud.githubusercontent.com/assets/8104251/16362474/0272837c-3bef-11e6-98c1-0877a11058d3.png)
After negative x change
![reader_2016-jun-26_223746](https://cloud.githubusercontent.com/assets/8104251/16362479/11727260-3bef-11e6-91b5-266850773ddf.png)
After latest change
![reader_2016-jun-26_223451](https://cloud.githubusercontent.com/assets/8104251/16362488/292fb34a-3bef-11e6-8f62-212fd82aa4c6.png)

And @bbgordon @chrox @houqp if you have time, can you guys have a look?

**Comment by chrox** [comment] 2016-06-26 14:12
It does have serious degeneration of list rendering. I agree with @frankyifei that we should first revert those changes.

**Comment by houqp** [comment] 2016-06-26 19:34
Thanks @frankyifei for catching this regression, we should definitely include those tests in our unit test suite :)

**Comment by bbgordon** [comment] 2016-06-27 01:48
I agree this wasn't ready for prime time. Thanks for pointing out a good test case and reverting it!

I do need to get negative indent working for my own use. I've reproduced one problem but there are more. If I can produce something that survives more test cases than I used previously is there interest in reviewing it?

**Comment by houqp** [comment] 2016-06-27 02:02
@bbgordon definitely. The negative indent is also a bug that we should fix. we just need to make sure the fix is implemented correctly so it won't cause other bugs. You are also welcome to include the negative indent as a test case when your patch is ready ;)

**Comment by bbgordon** [comment] 2016-09-05 20:58
I've published a [list_item branch](/bbgordon/crengine/tree/list_item) with my changes against master for the hanging indent and list item fixes if anyone is interested in the work in progress. There's still at least one bug with list items that span pages so it's not ready to be pulled! However, I've tested it with a wide variety of other documents and believe it to be otherwise an improvement.

**Comment by houqp** [comment] 2016-09-06 07:11
That's awesome news. Thanks for keep working on this issue :) I just got back from a long vacation, should be able to help test it this weekend :)

**Comment by poire-z** [comment] 2018-03-23 21:12
I've been trying to solve a little problem with list items: I often meet books where the list item text is in a div, like `<li><div>References</div><li>`, and they are currently badly rendered: the bullet is standalone, the text in the `<div>` is on a line of its own:

<kbd>![my_bad](https://user-images.githubusercontent.com/24273478/37852160-e06bc9cc-2ee1-11e8-9a6a-e18085caedc9.png)</kbd>

After a few hours looking at lvtinydom, lvrend, i found a few possible ugly hacks to have my problem solved. Later, I realized I can workaround it by just adding to some css:  `li > div { display: inline }`.

But after reading the code and printf'ing and playing with some sample HTML with list items, I realized there is something fundamentally wrong in the way list items are rendered. They are rendered as _final_, that is, they are considered a final block, where only text rendering is done, with some inline elements, style changes, etc...
We usually don't notice it, as our EPUB are quite simple, and the way it is done is most often enough.

But I think they should be rendered as `block`:
- if `list-style-position=outside`, the bullet should be on a block of its own on the left, and the whole list item content in a block on the rigth (think 1 table with 1 row of 2 cells, one cell with the bullet, one cell with the content).
- if `list-style-position=inside`, it should be a single block, and the bullet should just be prepended to the first child text.

I wouldn't have dared modifying crengine to do it that way, but looking around and finding this issue, I realize that this is exactly what @bbgordon has done in https://github.com/koreader/crengine/compare/master...bbgordon:list_item . This diff applies cleanly over current master, and the results it gives are amazing.

Some comparisons before/after (with `#define DEBUG_TREE_DRAW 1` in `src/lvrend.cpp`).

My home made test file [test-li2.html.txt](https://github.com/koreader/koreader/files/1843432/test-li2.html.txt)

Before, with epub.css applied:
<kbd>![my_before_epubcss](https://user-images.githubusercontent.com/24273478/37852642-ab8fcd1e-2ee3-11e8-90db-95565d577c12.png)</kbd>

After, with epub.css applied:
<kbd>![my_after_epubcss](https://user-images.githubusercontent.com/24273478/37852664-b895098e-2ee3-11e8-8578-93d9ebcdb1d3.png)</kbd>

...

Before, with external css cleared:
<kbd>![my_before_stylescleared](https://user-images.githubusercontent.com/24273478/37852708-e885c9f8-2ee3-11e8-8169-daaa42c54ec9.png)</kbd>

After, with external css cleared:
<kbd>![my_after_stylescleared](https://user-images.githubusercontent.com/24273478/37852713-ebf47e36-2ee3-11e8-933c-33ad56750ed0.png)</kbd>

....

With @a-kohout document from https://github.com/koreader/koreader/issues/2715 :

Before, with epub.css applied:
<kbd>![akohout_before_epubcss](https://user-images.githubusercontent.com/24273478/37852866-86dab848-2ee4-11e8-887a-88464f5627ab.png)</kbd>

After, with epub.css applied:
<kbd>![akohout_after_epubcss](https://user-images.githubusercontent.com/24273478/37852872-8d16763e-2ee4-11e8-9723-6b9b734736cf.png)</kbd>

...

Before, with external css cleared:
<kbd>![akohout_before_stylescleared](https://user-images.githubusercontent.com/24273478/37852882-9675a164-2ee4-11e8-9cf9-37c9ea03c098.png)</kbd>

After, with external css cleared:
<kbd>![akohout_after_stylescleared](https://user-images.githubusercontent.com/24273478/37852890-9c6f402a-2ee4-11e8-8688-8b1b8f0bdace.png)</kbd>

I had a look at @bbgordon code, and it looks fine and logical to me. I may have a 2nd more proper look, looking at possible side effects elsewhere.

We may need to tweak data/epub.css and co, and decide if `<p>` in `<li>` should have no ident, and things like that.

@frankyifei : any comments about this @bbgordon work ? It looks fine to me with the test suite, similar as before when it fails, and not failing on `css2.1/s12.6.2/list-015-nested.epub`.

> There's still at least one bug with list items that span pages so it's not ready to be pulled!

@bbgordon : have u made any more work on this? Have you been using it in some personal build?
What about this bug? Is it something that wasn't happening before? Or just something minor and itchy that you wanted to solve before it is merged ?

**Comment by frankyifei** [comment] 2018-03-24 00:18
maybe you can change the buildin css in lvdocview.cpp and see how it goes. it is not touched before. The buildin and external css file may not work well for current code base.

**Comment by Frenzie** [comment] 2018-03-24 07:03
@poire-z 

> But I think they should be rendered as block:

Yup. Quoting from the [CSS1 spec](https://www.w3.org/TR/CSS1/#display) for the sake of simplicity:

> A value of 'list-item' is similar to 'block' except that a list-item marker is added.

[2](https://www.w3.org/TR/CSS2/visuren.html#display-prop) and [3](https://drafts.csswg.org/css-display/#valdef-display-list-item) say effectively the same thing except because they define it better they're harder to comprehend.

> We may need to tweak data/epub.css and co, and decide if `<p>` in `<li>` should have no ident, and things like that.

There are two superior solutions if you're interested in really getting your hands dirty:

```css
/*
* Just don't indent the first freaking paragraph.
* This'll take care of basically each and every edge case.
* This is the superior solution. */
p+p {text-indent:1em}
```

```css
/*
* Only override for lists… conceptually worse unless
* first-paragraph indent is considered desirable elsewhere
* (it's not). But this might be easier since there seem to be
* a few firstChild DOM functions and no previousChild. */
li > p:first-child {text-indent:0}
```

**Comment by Frenzie** [comment] 2018-03-24 10:49
So I just noticed that `LVCssSelectorRule::check` already supports a variety of fancy selectors. As far as I'm concerned, change all the paragraph indent stuff to `p + p`. No effort required.

**Comment by dengste** [comment] 2018-05-19 08:12
The way crengine has rendered lists with div containers has bothered me for a long time. I just found this issue and rebased the branch by @bbgordon as suggested by @poire-z onto current master and I'm just delighted with the result. Lists render perfectly fine now, and as of yet I haven't seen any negative impact. I'm going to skim a few more books, but in any case I'd much appreciate if some version of this fix could be applied.

**Comment by poire-z** [comment] 2018-05-19 08:41
I've worked these last days into integrating @bbgordon way of handling list items into crengine, as an alternate style for list items, that should be toggable with a Style tweak.
I'll push a PR later today.

**Comment by dengste** [comment] 2018-05-19 09:28
Thanks, @poire-z. Much appreciated!
I've now noticed one case that is still not rendered correctly with the list_item branch: In the following ordered list, there's still a linebreak between the list number "1." and the paragraph text:

    <ol class="calibre7">
      <li class="listitem">
        <span class="itemnumber">1.</span>
        <div class="itemcontent">
          <div class="calibre8">
            <div id="par155" class="bookfrontmatter">
                  ... paragraph text ....
            </div>
          </div>
        </div>
        <div class="clearboth2">&nbsp;</div>
      </li>

**Comment by poire-z** [comment] 2018-05-19 09:53
> there's still a linebreak between the list number "1." and the paragraph text

I'd say it's normal, with current code and list_item branch: in your LI block, there is a SPAN which starts some inline text, and then a DIV, which starts a new block, and so needs a linebreak to separate from previous content (the SPAN) (unless class=itemcontent makes it displays as inline, or use some other css trick to make it not line-breaking).
Firefox renders your snippet (without any style) as:
<kbd>![image](https://user-images.githubusercontent.com/24273478/40267310-24f20250-5b5b-11e8-899f-b9f7dc8840ad.png)</kbd>

**Comment by dengste** [comment] 2018-05-19 10:13
You're right, this does not make sense without looking at the styles. In this case, with these two here this should be rendered as one line:

    <style>
      .listitem { display: table-row; }
      .itemcontent { display: table-cell; }
    </style>

**Comment by poire-z** [comment] 2018-05-19 10:28
OK, so that makes this being managed by the table rendering code :)
And I don't know how crengine would deal with this mix of LI / TABLE, and this somehow bad TABLE code (the LI becoming a TR, the SPAN being in the TR (no TD for it!), the DIV in a TD...)
That's a bit twisted...

**Comment by poire-z** [comment] 2018-05-19 11:10
@dengste : can you give https://github.com/koreader/crengine/pull/188 a try?

**Comment by dengste** [comment] 2018-05-19 13:07
OK, I've added

    li {display: -cr-list-item-block !important; }

to epub.css and cleared the cache. Unordered lists look fine, but the example above now not only has a newline but also a second list number prefixed:

![paragraph_ex](https://user-images.githubusercontent.com/1818708/40268845-90e093b8-5b75-11e8-9109-2e857ba4bf56.png)

Here's the example epub I'm using to test this (text is on the 2nd page!):

[ol_paragraph_test.epub.gz](https://github.com/koreader/koreader/files/2019445/ol_paragraph_test.epub.gz)

**Comment by poire-z** [comment] 2018-05-19 13:37
What you get looks logical given your sample (and my PR won't fix it):
```css
/* This defines styles and classes used in the book */
body { margin: 5%; text-align: justify; font-size: medium; }
code { font-family: monospace; }
h1 { text-align: left; }
h2 { text-align: left; }
h3 { text-align: left; }
h4 { text-align: left; }
h5 { text-align: left; }
h6 { text-align: left; }
h1.title { }
h2.author { }
h3.date { }
ol.toc { padding: 0; margin-left: 1em; }
ol.toc li { list-style-type: none; margin: 0; padding: 0; }
a.footnoteRef { vertical-align: super; }
em, em em em, em em em em em { font-style: italic;}
em em, em em em em { font-style: normal; }
.listitem {display: table-row; }
.itemcontent {display: table-cell; }
```
```html
<body>
<section id="section" class="level1 unnumbered">
<h1></h1>
<ol>
<li class="listitem"><span class="itemnumber">1.</span>
<div class="itemcontent">
<div class="calibre8">
<div id="par155" class="bookfrontmatter">&#160;This is an example paragraph.</div>
</div>
</div>
<div class="clearboth2">
&#160;
</div></li>
</ol>
</section>
</body>
```



OL brings the first number `1` (styles don't say it shoud not). If you add `class=toc` to your li (`<ol class=toc>` - you probably forgot it), as you have `ol.toc li { list-style-type: none; margin: 0; padding: 0; }` in the CSS, this first number is not shown, as the toc class wants.

`<li class="listitem"><span class="itemnumber">1.</span>` brings the `1.` . Your `li {display: -cr-list-item-block !important; }` overrides the embedded style ` .listitem {display: table-row; }`, so it correctly displays as a list item-block with the PR new code.
Then this:
```html
<div class="itemcontent"> <!-- display: table-cell -->
<div class="calibre8"> <!-- no style, so block -->
<div id="par155" class="bookfrontmatter">&#160;This is an example paragraph.</div> <!-- no style, so block again -->
```
brings a new display block, which displays below.

Again, this sample book has twisted styles (ol/li with table-* styles), so please don't use it to validate the new stuff :)
It there's a need to support that kind of twisted stuff (should a div style=table-cell inside a LI be displayed inline?), that would be for another PR.
If calibre makes that kind of twisted styles, and the old list-item method is better at it than the new one, it's ok to use the old one.

**Comment by dengste** [comment] 2018-05-19 13:59
> Again, this sample book has twisted styles (ol/li with table-* styles), so please don't use it to validate the new stuff :)

Understood. As I've written, the "normal" lists now look fine with the PR, so this is big improvement for me. Thanks for working on this!

**Comment by poire-z** [comment] 2018-05-25 13:06
Closing, as implemented (I think correctly) for new documents after https://github.com/koreader/crengine/pull/188, https://github.com/koreader/crengine/pull/192, https://github.com/koreader/koreader/pull/3976, so in a next nightly.

**Closed by poire-z** 2018-05-25 13:06 UTC
