### ISSUE TITLE
Translation by the Internet sometimes doesn't work

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#10489] opened 2023-05-26 06:33 UTC
* KOReader version: Latest 2023.04
* Device: PocketBook Color 633

#### When I'm trying to translate sentence by button "Translate" by the Internet - it's don't working right. It's shows "Turn on the WiFi" button (but my WiFi is already turned on), so I push this button and... nothing happens, the translation doesn't appear. And I do it again and by this time it's all the same. But before it's worked when i pushed the button turn on WiFi.
I don't know why it doesn't working now. 

Please fix that issue in the new version. I adore your app! Thank you for always helping me

**Comment by hius07** [comment] 2023-05-26 08:07
Sorry, what's your location? Is https://github.com/koreader/koreader/issues/9574 or something related?

**Comment by ZHANYLone** [comment] 2023-05-26 08:13
> Sorry, what's your location? Is https://github.com/koreader/koreader/issues/9574 or something related?

Kazakhstan

But in time settings it is set like Ashgabat, Turkmenistan. Cause it hasn't my time zone city Aqtobe

**Comment by ZHANYLone** [comment] 2023-05-26 08:15
> Sorry, what's your location? Is https://github.com/koreader/koreader/issues/9574 or something related?

Maybe it's because (I don't really know) my WiFi when not used, as on every PocketBook, automatically stops for saving battery energy (but i still have WiFi icon on)? But maybe it's not. I don't really know

**Comment by ZHANYLone** [comment] 2023-05-26 11:07
> Sorry, what's your location? Is https://github.com/koreader/koreader/issues/9574 or something related?

But about 4 days ago it worked
Now not
How strange

**Comment by pazos** [comment] 2023-05-26 11:23
Duplicate of https://github.com/koreader/koreader/issues/10183

**Closed by pazos** 2023-05-26 11:23 UTC
