### ISSUE TITLE
Can't exit from menu!

### ISSUE THREAD

**Issue by aosfan** [koreader/koreader#8596] opened 2021-12-27 12:27 UTC
* KOReader version: it's OTA updated yesterday, so I think it's the latest 2021.12.1, see details below
* Device: Kindle 5 non-touch

#### Issue
I got into a ridiculous situation. I explored the settings and somehow got into a menu that I can't get out of. I just can't click on that big "CLOSE" button because the left and right arrows just don't work in this menu. But they work in text area. Is there a way to exit from this menu?
Please help. I feel so stupid.
![IMG_20211227_151117](https://user-images.githubusercontent.com/29099263/147470797-97833b42-aeb1-4342-a8b7-adf38d764f57.jpg)

Sorry for my English.

**Comment by hius07** [comment] 2021-12-27 13:13
Duplicate of https://github.com/koreader/koreader/issues/7356.

**Comment by aosfan** [comment] 2021-12-27 13:38
I'm not a programmer, but as far as I understand, there is already fix for this issue: https://github.com/koreader/koreader/commit/a31d9446849b3864ecf425127e49dbe6b5a8a9a8
Then why did it happen again?

**Comment by Frenzie** [comment] 2021-12-27 14:05
You said you can't click on it, which suggests you have a touch device?

**Comment by Frenzie** [comment] 2021-12-27 14:08
Are you saying you have the elusive B012?

https://wiki.mobileread.com/wiki/Kindle_Serial_Numbers

**Comment by hius07** [comment] 2021-12-27 14:45
> Then why did it happen again?

That fix removes Text editor from the main menu (plugins).
You have fired it in another way (not blocked yet).

**Comment by aosfan** [comment] 2021-12-27 17:10
> But what did you do to get here?

As **hius07** already said, I get there through Tools→Tweak documents settings
> Are you saying you have the elusive B012?

No, I have B023 device. There is some kind of misunderstang I think. Wiki says is is 5th gen Kindle, but looks like it is Kindle 4 just black. But anyway I somehow managed to reboot my Kindle to original firmware and restart Koreader, so everything is fine now. Until I accidentally click on the wrong menu item again.

> not blocked yet

But it will be, right?
This looks like a pretty serious issue to me that, fortunately, as far as I can understand, it can be fixed fairly easily

**Comment by Frenzie** [comment] 2021-12-27 19:39
@hius07 
> That fix removes Text editor from the main menu (plugins).
You have fired it in another way - Tweak documents settings (not blocked yet).

What makes you say that? It's either disabled or it's not.

**Comment by Frenzie** [comment] 2021-12-27 19:44
I see, it's just an InputDialog widget. Unclear "it". ;-)

**Comment by hius07** [comment] 2021-12-27 20:23
One more trap: Typeset - Style tweaks - Book-specific tweak.

(There is another entry of `add_nav_bar = true` in Newsdownloader plugin, but I couldn't call it)

**Comment by Frenzie** [comment] 2021-12-27 20:42
Well, adding a back handler was always a good idea. :-)

**Closed** 2022-01-02 10:58 UTC
Labels: duplicate, help-wanted, NT
