### ISSUE TITLE
FR: Non-fullscreen mode on Android to show soft navigation buttons and system-status bar

### ISSUE THREAD

**Issue by hklene** [koreader/koreader#11419] opened 2024-01-29 07:22 UTC
Android Smartphones usually support running multiple apps. But accessing something else is cumbersome. E.g. switching from KO-Reader to show the travel-ticket on control or just to check the trains progress and switch to the other app. Usually it is only a double click on the square away, only the square is not there.

The best I came up so far is turning one of the corners into exiting KO-Reader, to go back to my system. But then picking up to read later is still a pain, as KO-Reader can be started from my file-manager, but it doesn't adhere the clicked file and instead asks me with it's own file-browser to open the file again.

Also fiddling with the KO-internal status-bar I wouldn't need it to show me battery and clock, if I had access to the Android status bar. In addition highjacking the swipe into-screen gestures is obtrusive to me.

**Comment by Frenzie** [comment] 2024-01-29 09:53
You can set start with last file.

**Comment by hklene** [comment] 2024-01-30 07:53
I didn't realize the file-browser has a different set of settings - thanks one papercut healed ...

**Comment by pazos** [comment] 2024-12-09 18:27
Duplicate of  https://github.com/koreader/koreader/issues/8532

**Closed by pazos** 2024-12-09 18:27 UTC
Labels: enhancement, Android
