### ISSUE TITLE
Touch screen does not respond on Hanvon E960 plus

### ISSUE THREAD

**Issue by OSIMLY** [koreader/koreader#4630] opened 2019-02-21 02:26 UTC
* KOReader version: KOReader 2019.02
* Device: Hanvon E960 plus

#### Issue

It can be installed and started normally, but the touch screen of the device does not respond.

#### Steps to reproduce

Start app, touch screen to operate.

#### Eink test

- Manufacturer: Freescale
- Brand: Freescale
- Model: EVK_MX6SL
- Product: evk_6sl_eink
- Hardware: freescale

**Comment by Frenzie** [comment] 2019-02-21 07:05
Cross-ref #4551.

Since the eInktest utility presumably showed no results I'm afraid there's nothing that can be done for now.

**Comment by OSIMLY** [comment] 2019-02-21 08:30
@Frenzie Thank you for your help. I am sorry to trouble you but would you mind provide a fault-tolerant mode on Android devices?

**Comment by Frenzie** [comment] 2019-02-21 10:41
That's the default, if "fault-tolerant" is the right term. The fact that it's not working basically means that neither should any other app without special adaptations. It's just a regular Android app.

On the Onyx devices, for example, the app works either way, but a lack of dedicated support just means you don't get support for special E Ink settings (e.g., full screen refresh after x page turns).

**Comment by pazos** [comment] 2019-02-21 12:42
Duplicate of #3517 and probably of #3567. A freescale device that doesn't respond to touch events. (In fact it responds but the e-ink driver doesn't draw the updates in the framebuffer).

> The fact that it's not working basically means that neither should any other app without special adaptations. It's just a regular Android app.

It depends on how the driver is implemented. Normally the driver knows which view is active (a ScrollView, a TextView..) and make changes in the screen accordly (ie: enters in a2 mode when scroll starts and does a full refresh when scroll stops).

KOReader is using the NativeActivity api, but einkTest is using the normal android view hierarchy. That means that the eink activity seems to work (and to respond to touches) but KOReader doesn't.

**Comment by Frenzie** [comment] 2019-02-21 15:07
> It depends on how the driver is implemented. Normally the driver knows which view is active (a ScrollView, a TextView..) and make changes in the screen accordly (ie: enters in a2 mode when scroll starts and does a full refresh when scroll stops).

A lack of explicit support, whether in the app or in the driver, should mean inefficient or possibly inappropriate updates. Doing nothing instead is so inane it boggles the mind.

To be fair, we're probably looking at a situation where it's a miracle that the programmers were able to put out a halfway functional hack job at all.

**Comment by OSIMLY** [comment] 2019-02-22 02:02
@Frenzie @pazos Thank you. I really like this application, simple interface and powerful function. It would be great to get Koreader working on the Hanvon devices.

**Comment by pazos** [comment] 2019-02-22 17:05
@OSIMLY: closing this issue, you can track progress in #3517

**Closed by pazos** 2019-02-22 17:05 UTC
Labels: Android, duplicate

**Comment by pazos** [comment] 2019-06-14 00:10
@OSIMLY : we added a driver for freescale. Please follow https://github.com/koreader/koreader/issues/4551#issue-406883935 and report. 

If the tests don't work you can try https://github.com/koreader/koreader/issues/4881#issuecomment-480611804
