### ISSUE TITLE
epub CSS only works correct after turning the "Embedded Style" option off and on again

### ISSUE THREAD

**Issue by trekk2810** [koreader/koreader#3411] opened 2017-10-23 19:31 UTC
* KOReader version: v2015.11-1370-g5ee6c01
* Device: Kindle Oasis (happens also on Kobo Aura One)

#### Toggling the "Embedded Style" option from "on" to "off" to "on" makes the frame around the image disappear and sets the CSS as it is intended (see Pic 2)
Pic 1: no page-break, ugly frame around image ================================================================
![reader_2017-oct-23_193134_first_open](https://user-images.githubusercontent.com/8217193/31907868-67f7b67c-b835-11e7-828b-06ac08d4afb5.png)
 
 

Pic 2: with page-break, no ugly frame around image ================================================================
![reader_2017-oct-23_193221_toggle_offandon](https://user-images.githubusercontent.com/8217193/31907875-6f84e6b2-b835-11e7-9c58-f80ebe062781.png)

**Comment by poire-z** [comment] 2018-03-10 21:52
It may be better with a recent nightly >= v2015.11-1553-gc0687ef_2018-03-09 (available at http://build.koreader.rocks/download/nightly/), could you check ?

**Comment by trekk2810** [comment] 2018-03-11 11:41
Checked with v2015.11-1554-gdb31bd4_2018-03-10, but I can't see any changes. Still as described above.

**Comment by frankyifei** [comment] 2018-03-12 03:24
is it possible koreader's external css styles being used? the ugly border around image seems familar

**Comment by cramoisi** [comment] 2018-03-15 08:16
@trekk2810 could you share a book ? I made the "Embedded Style" option as the default one on my KA1 and I never had this problem. Thus I remember having a problem similar a long time ago with my gloHD and found it was linked with the style I chose from the menu (doc => style => disable auto (if i remember correctly and it seems to be what @frankyifei  suggests). I could try to reproduce it if you want.

**Comment by trekk2810** [comment] 2018-03-15 19:25
@cramoisi BINGO! Setting the style to auto fixed the problem and also the ugly border around some images. It should work without auto and other css though ... Thank you for the hint! :)

If you like to play with the file, here is a sample book https://www.dropbox.com/s/58mtcxhlwcqk8bo/CSS_test.epub?dl=0

**Comment by Frenzie** [comment] 2018-03-15 19:32
If you stick .zip at the end you can also upload it on GitHub. That's better for posterity. ;-)

**Comment by trekk2810** [comment] 2018-03-15 21:14
You are so right :) Here it is [CSS_test.epub.zip](https://github.com/koreader/koreader/files/1817110/CSS_test.epub.zip)

**Comment by cramoisi** [comment] 2018-03-16 07:37
@Frenzie : what is the purpose of "Auto" in the Styles menu ? Choosing the right internal css to apply with the open document format ? (so if I open a html file, it's html.css which will be selected ?)

**Comment by Frenzie** [comment] 2018-03-16 08:56
I think "Auto" is just a convoluted way of saying `data/cr3.css` but @poire-z probably knows more about it than me. :-)

**Comment by cramoisi** [comment] 2018-03-16 11:11
@trekk2810 before, you set "clear all external style to default" ? I can't reproduce the problem even if I'm sure I had it in my koreader first days of use.

**Comment by poire-z** [comment] 2018-03-16 11:22
> what is the purpose of "Auto" in the Styles menu ? Choosing the right internal css to apply with the open document format ? 

Yes, exactly that (and fallback to data/cr3.css if no _file_extension_.css exists):

https://github.com/koreader/koreader/blob/0a4fb89239864dbf9e76ba4f5f28967706cd01aa/frontend/apps/reader/modules/readertypeset.lua#L99-L102

https://github.com/koreader/koreader/blob/0a4fb89239864dbf9e76ba4f5f28967706cd01aa/frontend/document/credocument.lua#L96-L110

**Comment by Frenzie** [comment] 2018-03-16 11:55
I get that FB2 needs a different CSS, but why is there a distinction between, say, EPUB and HTML?

**Comment by poire-z** [comment] 2018-03-16 12:14
I guess these come from coolreader. The html.css and epub.css are different (formatting prevent comparing), and there are at least styles related to DocFragment that make sense only for epub.

**Comment by Frenzie** [comment] 2018-03-16 14:37
I don't think `DocFragment` in a "gobal" style is much of an issue tbh. You could still get a nice separation with @import base-style.css.

Also, just at a quick skim, these things from htm.css are most definitely not HTML elements. They're some kind of pollution from FB2 I imagine.
```css
v { 
   text-align: left; 
   text-align-last: left; 
   text-indent: 1em hanging 
  }

annotation { 
   margin-left: 5%; 
   margin-right: 5%; 
   font-size: 100%; 
   font-style: italic; 
   text-align: justify; 
   text-indent: 1em 
   }

epigraph { 
   margin-left: 15%; 
   margin-right: 1em; 
   text-align: left; 
   text-indent: 1em; 
   font-style: italic; 
   margin-top: 15px; 
   margin-bottom: 25px 
   }
```

The CSS setup strikes me as overcomplicated in the wrong way.

(Not that I care too much for the most part. It seems to work alright.)

**Comment by trekk2810** [comment] 2018-03-16 17:17
@cramoisi  In the menu only epub.css is checked. After purging the sdr I can reproduce the problem every time. If I check auto the problem disappears.

**Comment by cramoisi** [comment] 2018-03-17 07:27
@trekk2810  sorry, but could you do me a step by step to reproduce ? when I check epub.css , auto option enable itself automatically. the only way I can enable a css without auto autocheck is to choose another css (but not the epub one) and even so it seems it applies correctly. And when I switch embedded style on/off ; the external style reset itself to auto / epub.css

**Comment by trekk2810** [comment] 2018-03-17 09:21
Sorry, I misled you. I used a modified css as default, not epub.css. Guess I shouldn't write anything when it's late in the evening ;)

Maybe you can check again with the attached trekk.css. I embedded this lines in the css, so we have definitely borders around images to make the effect more obvious.

`img { 
	text-align: center; 
	text-indent: 0px; 
	display: block; 
	margin: 0.5em; 
   	border-style: solid; 
   	border-width: medium; 
}` 

- Set embedded style as default.
- Set trekk.css as default (long pressing in the style menu).
- In the file manager purge sdr of CSS_test.epub.

Now if you open the book, you can see the ugly borders around images (not the cover).

Only after turning emdedded styles off and on again, the embedded styles of the book are used and the borders go away. 
[trekk.css.zip](https://github.com/koreader/koreader/files/1821454/trekk.css.zip)

**Comment by cramoisi** [comment] 2018-03-17 09:57
thanks !

**Comment by cramoisi** [comment] 2018-03-17 13:43
@trekk2810 did you delete the original epub.css in the directory ? Cause when all goes according you said but when I switch from embedded style to off  koreader automatically sets auto + epub.css so, when I toggle embedded style to on again the inner css is applied on top of the epub.css without any problem.

**Comment by trekk2810** [comment] 2018-03-17 13:46
No I didn't delete the original epub.css.

**Comment by cramoisi** [comment] 2018-03-17 14:07
@trekk2810  
ok, I don't think there is a bug. The way css are applied is the following : defaut external css (from menu style). The one you put by default or the autoselect one (following the file's extension or cr3.css for the fallback). On top of the external css is applied the embedded css (the one in the book, if "on") which takes priority over the internal only for classes which are defined in it. In our case, if the border of images are not defined in the internal css, the external takes the priority, so you have border to your image (which are not defined in internal but are in external).

So setting the embedded to off automatically set the style to "auto + css according to file - here, epub.css) but now obviously ignore the embedded css (so the layout is still messed up because it doesn't rely on the embedded css designed specifically for it). Thus, switching embedded to on reapply the inner css but epub.css is stil on so your epub is ok.

So, It's the way the thing is running... In my case I would prefer the external css be applied after the inner css (to give people more control over layout without caring much of the inner css and override some stupid rules you could find inside them) but I'm not sure it's enough a reason to call it a bug (pinging @Frenzie  @poire-z on this point ?)

**Comment by trekk2810** [comment] 2018-03-17 17:05
No, It's not too muddled. ;) Thanks for making this transparent. If the way css is applied is intended behaviour, I still don't like it.

**Comment by cramoisi** [comment] 2018-03-17 17:14
In a perfect world, editor will all follow the same rules for their layout and thus everybody could customize their css without pain... But let's wait for feedback to really know if it's intended or not ;)

**Comment by poire-z** [comment] 2018-03-17 17:26
I think what would be a bug is the situation described in this issue's 1st post: non consistent behaviour.
But I can't reproduce anythink like that with the above book.

About the styles priority, and even if I understand how you would prefer things (and I sometimes wished the same), I think it's kind of normal, and it's the same in our usual web browsers.

The default (or auto, epub.css) defines how the browser should render things by default. Without this, everything is flat (try it with a wikipedia epub: embedded styles off > only epub.css is used, and it's still beautiful - clear all external styles > everything is flat and the same size: no header, no bold, links not underlined and not dinstinguishible from plain text...
So, this default just tells the _dumb_ crengine how at least `<h1>, <h2>, <a>` should look.

Then, embedded styles are applied other this, just like stylesheets are applied on a web page, over the defaults `<h1>, <h2>, <a>` that our browser has hardcoded'ly defined (without giving us the option to changed that, except may be for the color of links and visited links).

So, I guess it's the expected behaviour, or at least the most common behaviour :)

After that, there could be a place for _user styles_ (never looked at them, but I think there's something like that very popular with Firefox), that could be applied after all the others. We don't have that.
But I guess what would be preferable would be a way to edit (mostly disable) some parts of the embedded styles (and often, you don't need to disable much, I sometimes did that to the embedded styles and rezip the epub) - but there's no obvious hook about how we could do that with a widget from koreader itself.

**Comment by Frenzie** [comment] 2018-03-17 17:32
Opera and Otter have built-in user CSS. Firefox has GreaseMonkey. Chromio have an equivalent called Tampermonkey.

I've always considered the fact that you need `!important` in your user styles a borderline bug, meaning higher specificity doesn't work, but it's per spec. I can't be bothered to find the part of the spec that says it atm. I'll do so if you really want to know.

**Comment by cramoisi** [comment] 2018-03-17 17:41
Got my answer. Not a bug :) The non-consistent behaviour on the first post was identified like this because trekk2810 thought it has to be different but was mislead by the hidden content of his own custom css and the on/off procedure which change the applied style on the document.

**Comment by poire-z** [comment] 2018-10-16 20:18
There's been many update and fixes to crengine stylesheet handling since this issue is open, and I still haven't experimented that issue.
So closing. Re-open if it still happens.

**Closed by poire-z** 2018-10-16 20:18 UTC
Labels: bug, crengine
