### ISSUE TITLE
PocketBook: Crash when connecting to an OPDS server via HTTPS

### ISSUE THREAD

**Issue by vimalaguti** [koreader/koreader#9422] opened 2022-08-09 13:13 UTC
* KOReader version: 2022.07
* Device: pocketbook touch lux 4 PB627

#### Issue

Koreader crashes when I try to open any ODPS library.
But it works with local odps-calibre library.

#### Steps to reproduce

open the ODPS menu and select eg. standard ebooks

[crash.log](https://github.com/koreader/koreader/files/9290870/crash.log)

**Comment by NiLuJe** [comment] 2022-08-09 15:34
Pleas enable verbose debugging to discriminate properly, because there's a lot of noise in there, and I can't tell what's OPDS and what isn't.

I *am* seeing a good old SIGILL from inkview shenanigans in there, so, I don't necessarily have high hopes...

**Comment by NiLuJe** [comment] 2022-08-10 14:40
Random musings about said InkView issues for interested parties:

The issue is that InkView pulls in a *lot* of crap via DT_NEEDED, and, *worse*, *might* be unilaterally initializing somee stuff in `.init` and./or `.ctors`, as, IIRC, we've tried patching out the offending dependencies via patchelf, and stuff blew up in fun and interesting ways...

The main culprit here is *probably* OpenSSL, because having two copies of OpenSSL in the same program space is already a terrible idea, but having two *different* version (possibly w/ a major difference or two) will *absolutely* break your shit.

So, two ideas:

* Try the patchelf approach again, with a recent patchelf build, which might be less prone to breakign random binaries:
** That involves pulling the system inkview, moving it somewhere our LD_LIBRARY_PATH setup will prefer it over the system's (i.e., our libs folder), and patching the offending DT_NEEDED entries out (basically, anything that we ourselves will load, e.g., zlib, openssl, curl, ...).

If that still breaks horribly on load, I had a random stupid idea:

* Feed inkview minimal shims of its offending DT_NEEDED entries, that basically just provide the empty symbols it expects on load/unload. *Hopefully*, that works, and it doesn't actually rely on OpenSSL for stuff we rely on.
** That would involve creating said minimal C shims, putting 'em somewhere different, and make LD_LIBRARY_PATH point to 'em *just* for loading inkview. (Or giving 'em custom names, and patching the DT_NEEDED entries with patchelf, which would avoid the need for extra loader shenanigans, assuming patchelf doesn't break the binary).

Since I do not have a PB device, this is an exercise left to the reader ;).

**Comment by Frenzie** [comment] 2022-08-10 14:48
As to the shim, also see the one I added in https://github.com/koreader/koreader-base/blob/7fb47e46054ebf0499131db8f6fc006729795f3e/libxss-dummy.c

**Comment by rjd22** [comment] 2022-08-20 18:05
When l'm reading @NiLuJe musings, I notice how little I still understand about Koreader development. ^^°

**Comment by vimalaguti** [comment] 2022-08-31 09:58
Hi @NiLuJe thanks for the reply, but I don't understand half of your tech words :) if it has to do with building the source code, I give up: for me having local calibre is enough as I can download from pc.
I can try to enable verbose logging, if someone explain me how to do it

**Comment by NiLuJe** [comment] 2022-08-31 11:38
The second comment was mostly aimed at potential PB contributors ;).

You can enable verbose logging in [Tools] > More tools > developer settings.

**Closed** 2024-12-29 10:57 UTC
Labels: need more info, PocketBook, firmware, help-wanted
