### ISSUE TITLE
Koreader turns off frontlight at its startup.

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3324] opened 2017-10-08 17:58 UTC
* KOReader version: nightly 1287
* Device: Inkbook Prime (Android)

#### Issue
Koreader turns off frontlight at its startup.
Is it an issue in existing code, or we lack function checking if frontlight is enabled on android?

#### Steps to reproduce
Turn on frontlight on device, start Koreader.

**Comment by Frenzie** [comment] 2017-10-08 18:09
Closing as duplicate of #3118 and #3004, should be fixed by #3319 (i.e., don't mess with the frontlight on startup) although the behavior you describe is very different than what I'm seeing.

**Closed** 2017-10-08 18:10 UTC

**Comment by gerroon** [comment] 2017-10-08 19:12
@Frenzie 
One thing that happens with 1303 is that not just it opens koreader with no light, when I quit koreader, it sets the system light to %50 which is very annoying. I hope that this is not a planned behaviour.

**Comment by Frenzie** [comment] 2017-10-08 19:28
With #3319 it should be possible to start KOReader on Android without it ever touching the frontlight one way or another (i.e., the way it should be). What happens when you do set it through KOReader is a slightly different question, but for me it only disables adaptive brightness (if enabled). It doesn't change anything on exit nor is it intended to, but perhaps your device automatically re-enables adaptive brightness or some such?

**Comment by gerroon** [comment] 2017-10-08 23:10
@Frenzie 

This is only happening with recent builds from last couple days. It is not in 1254.

Also my device does not have ambient sensors, or auto light. And I always set my light to %5.

**Comment by Frenzie** [comment] 2017-10-09 07:00
@gerroon Today's nightly (v2015.11-1312-ga710d2c) should leave the frontlight entirely alone unless you touch the frontlight setting from the menu.

**Comment by gerroon** [comment] 2017-10-09 20:10
@Frenzie 

The light is fine now except that it is not quite there. Koreader opens with the system light and it does not mess with the system light. However I have to do couple up and downs with 2 fingers to change the light in Koreader. Initial drags turns off the light then I can change the light after couple tries. This is same with changing the light via the menu item.

**Comment by Frenzie** [comment] 2017-10-09 21:05
Odd, I can confirm that the gesture seems to work somewhat awkwardly (perhaps more of a gesture than a frontlight problem?) but the frontlight control widget works well for me.
