### ISSUE TITLE
Update wiki page about the frontlight gesture

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#3527] opened 2017-12-01 18:04 UTC
* KOReader version: koreader-nightly-20171023
* Device: eink screen

Sliding two fingers up/down the screen seem to interact with frontlight (somewhat). I discovered this accidentally. Could you please document the intended behaviour in the wiki page?

**Comment by Frenzie** [comment] 2017-12-01 18:10
You know more than me. :-P

**Comment by ersi-dnd** [comment] 2017-12-01 18:14
@Frenzie 
> You know more than me. :-P

This one does not count. It's fool's luck.

**Comment by Frenzie** [comment] 2017-12-02 10:40
It's a partial duplicate of https://github.com/koreader/koreader/issues/3484 btw.

**Comment by Frenzie** [comment] 2018-03-07 20:14
Closing since @chrox added this to the wiki.

https://github.com/koreader/koreader/wiki/KOReader-Gestures

**Closed by Frenzie** 2018-03-07 20:14 UTC
Labels: documentation
