### ISSUE TITLE
App freezes when changing a text appearance setting

### ISSUE THREAD

**Issue by KurisuAndo** [koreader/koreader#12198] opened 2024-07-21 09:33 UTC
* KOReader version: 2024.07
* Device: Samsung A50s (android 11, one ui 3.1)

#### Issue
App becomes unresponsive when changing a text appearance setting (e.g., line spacing). There was a symbol on the top left corner that indicates reloading of the whole document (as stated in the user guide), however I've been waiting for 30 minutes straight and it still haven't finished. I tried to test this on Bluestacks (android 11) with the same book but it works totally fine there. This doesn't happen if I immediately close the book after changing a setting then launching it again.

#### Steps to reproduce
Change an option (like line spacing or font size) then wait for a few seconds.

##### `crash.log` (if applicable)
[crash.log](https://github.com/user-attachments/files/16323665/crash.log)

**Comment by pazos** [comment] 2024-07-21 11:14
Duplicate of #12099

**Closed by pazos** 2024-07-21 11:14 UTC
