### ISSUE TITLE
Android - DJVU with Russian names don't work

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2044] opened 2016-05-25 02:15 UTC
* KOReader version: Latest nightly
* Device: Android

#### Issue
People from [4pda](http://4pda.ru/forum/index.php?showtopic=734837) report that djvu's with Russian filenames have this issue of 'no engine' on Android.
KOReader also creates a .lua file with book parameters.
Example file is [attached](https://yadi.sk/d/sFrorXNSrxQdX).

On my Kinde Touch however such files are opened correctly.

**Comment by chrox** [comment] 2016-05-26 23:55
Yes, currently DJVU is not supported on Android no matter what the file name is. The problem is we didn't have a straightforward way to compile the same Djvulibre for Android and the other platforms. Although there are other projects like EBookdroid that have succeeded to run Djvulibre on Android, they may have done major refactoring to the original Djvulibre lib and the patches are not available in the upstream Djvulibre repo. So in order to support DJVU on Koreader for Android we either need to maintain a bunch of platform-specific patches or waiting for the upstream Djvulibre to support Android. And we prefer the latter option. But if someone send a pull request of the first option it's sweet too.

**Comment by chrox** [comment] 2016-05-27 00:12
Close this as it's duplicated to #1534.

**Closed** 2016-05-27 00:13 UTC

**Comment by mergen3107** [comment] 2016-05-27 18:50
@chrox 
OK, I got the point!
Do you think it is a good idea that we should try to contact [author of Orion Viewer](https://github.com/max-kammerer)?
Although KOReader will be a djvu-competitor on Android for his solution, Orion Viewer is free anyway.
He speaks Russian and so do I, so probably we could get in a good touch.
What do you think?

**Comment by chrox** [comment] 2016-05-28 00:21
That will be great. Orion Viewer also maintains a list of patches to djvulibre.

**Comment by mergen3107** [comment] 2016-05-28 05:00
@chrox 
OK! I'll him on the 4pda forum and let you know then

**Comment by mergen3107** [comment] 2016-05-28 19:20
@chrox 
I have some interesting news!
While I am waiting for the reply from Mr. Michail Bogdanov (Orion Viewer's author), Ebook Droid authors are [telling](http://4pda.ru/forum/index.php?showtopic=734837&view=findpost&p=49953277) me that they have all the sources and binaries of each release version publicly available according to GPL.
So they attached the sources of the latest ones [here](https://drive.google.com/file/d/0B6y-A-HTzyBiOGNUZVp3RTc0ejQ/view).
Also, they say that there is no actual need to patch anything in djvulibre, but it is required to accelerate image decoders (if I translated that correctly, may be there is a dedicated term for that).

**Comment by max-kammerer** [comment] 2016-06-17 11:24
Orion Viewer patch for russian file names support in djvulibre- https://github.com/max-kammerer/orion-viewer/tree/master/orion-viewer/jni/djvu/libdjvu
