### ISSUE TITLE
Feature request: Night mode - option for inverting pictures

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#4403] opened 2018-12-15 10:21 UTC
* KOReader version: v2018.12-14-ge044093_2018-12-13
* Device: PB626

#### Issue
If the night mode is enabled, the document (I tested PDFs and EPUBs) whole document is shown as a negative (inverted black/white "colors"). It would be fine to have an option to select whether the pictures in document are shown as the negative or "normal" ones.

#### Steps to reproduce
1. Open document e.g. some PDF with some text and pictures
2. Switch on the night mode
3. Browse the opened document to see pictures in it

**Comment by Frenzie** [comment] 2018-12-15 12:09
Duplicate of #2571, so closing in favor of that one. But yeah, that'd be nice.

**Closed by Frenzie** 2018-12-15 12:09 UTC
