### ISSUE TITLE
Evernote log in error 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#6551] opened 2020-08-23 18:37 UTC
![Screenshot_2020-08-23-21-32-06](https://user-images.githubusercontent.com/70109540/90985976-23f82780-e588-11ea-9c31-3c62676ae7ea.png)
* KOReader version: 2020.8
* Device: SM-T285

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by NiLuJe** [comment] 2020-08-23 18:52
Duplicate of #6281

**Closed by NiLuJe** 2020-08-23 18:52 UTC
