### ISSUE TITLE
Pocketbook Inkpad Color 3 Wi-Fi issues

### ISSUE THREAD

**Issue by runningman84** [koreader/koreader#11096] opened 2023-11-11 15:23 UTC
* KOReader version: v2023.10-15-g082ef9b54_2023-11-11
* Device: Pocketbook Inkpad Color 3

#### Steps to reproduce
Try to lookup some word on wikipedia. Koreader asks for enable wifi. Koreader says "turning on wi-fi" Nothing happens. If you click on wikipedia again koreader does not do anything.

A similar issue happens if you do any other network stuff like downloading dicts.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/11/23-15:57:07
 [*] Version: v2023.10-15-g082ef9b54_2023-11-11

ffi.load: libs/libutf8proc.so.3
ffi.load: blitbuffer
ffi.load: inkview
11/11/23-15:57:07 INFO  SoftwareVersion:  U743k3.6.8.2193 
ffi.load: inkview
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
Atached mp shm: id 0 addr a6f8d000 size 17624
attach_shm: mtfb key=251388250 size=8409872
Atached mtfb shm: id 348008 addr a3a5f000 size 8409872
-------------------------
Starting task - koreader.app
flags: 0x00100080
gpid: 8538
fb=0xa3a5f000 xres=1404 yres=1872 scanline=4224 vdepth=24 orient=0
-------------------------
attach_shm: mttempfb key=251308714 size=2665728
Atached mttempfb shm: id 8001 addr a37d4000 size 2665728
Atached mqueue: id 8001
[hw_setglobalkeymask] gka0 = 4000000; gka1 = c800002; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 0 10000 18720000 -10000 0
attach_shm: mtfb key=251388250 size=8409872
Atached mtfb shm: id 348008 addr a1c6c000 size 8409872
ffi.load: librt.so
ffi.load: inkview
[8544 : ./luajit] (hw_nextevent)mq_receive ret -1 (Resource temporarily unavailable)
ffi.load: inkview
11/11/23-15:57:07 INFO  initializing for device PBInkPadColor3 
11/11/23-15:57:07 INFO  framebuffer resolution: {
  h = 1872,
  w = 1404
} --[[table: 0xa6c301c8]] 
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: sqlite3
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
11/11/23-15:57:08 INFO  opening file /mnt/ext1/applications/koreader/data/dict/ebook-reader-dict-en/res/130279ec.gif 
[8544 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[8544 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
ffi.load: libs/libgif.so.7
11/11/23-15:57:08 INFO  Inhibiting user input 
[8544 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
11/11/23-15:57:08 INFO  Loading plugins from directory: plugins 
[8544 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[8544 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[8544 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted

[8544 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
11/11/23-15:57:10 INFO  Restoring user input handling 
[8544 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
11/11/23-15:57:12 ERROR failed to call event handler onSaveSettings plugins/statistics.koplugin/main.lua:929: attempt to index field 'page_stat' (a nil value) 
11/11/23-15:57:12 ERROR failed to call event handler onSaveSettings plugins/statistics.koplugin/main.lua:929: attempt to index field 'page_stat' (a nil value) 
11/11/23-15:57:12 ERROR failed to call event handler onSuspend plugins/statistics.koplugin/main.lua:929: attempt to index field 'page_stat' (a nil value) 
11/11/23-15:57:12 INFO  Inhibiting user input 
11/11/23-15:57:45 INFO  Restoring user input handling 
11/11/23-15:57:45 ERROR failed to call event handler onReadingResumed plugins/statistics.koplugin/main.lua:207: attempt to index field 'settings' (a nil value) 
11/11/23-15:58:10 ERROR failed to call event handler onPageUpdate plugins/statistics.koplugin/main.lua:207: attempt to index field 'settings' (a nil value) 
11/11/23-15:58:10 ERROR failed to call event handler onCloseDocument plugins/statistics.koplugin/main.lua:929: attempt to index field 'page_stat' (a nil value) 
11/11/23-15:58:10 ERROR failed to call event handler onSaveSettings plugins/statistics.koplugin/main.lua:929: attempt to index field 'page_stat' (a nil value) 
11/11/23-15:58:31 INFO  opening file /mnt/ext1/Dropbox PocketBook/mybook.epub 
11/11/23-15:58:31 INFO  Inhibiting user input 
11/11/23-15:58:32 INFO  Restoring user input handling 
g_mkdir failed: No such file or directory
g_mkdir failed: No such file or directory
g_mkdir failed: No such file or directory
[8613:11/11/23 16:01:05] netagent called with parameters < wifi on >
[8613:11/11/23 16:01:05] bringing up wifi
int NetConnect(const char *)
[8544 : ./luajit] (hw_net_connect)enter[8544 : ./luajit] (hw_ban_suspend)BAN SUSPEND sec[5]
[8813:11/11/23 16:01:07] netagent called with parameters < connect >
Time To Connect [2058][8828:11/11/23 16:01:09] netagent called with parameters < net info >
[8833:11/11/23 16:01:09] netagent called with parameters < ping >
11/11/23-16:01:30 WARN  NetworkMgr:promptWifiOn: A previous connection attempt is still ongoing! 
11/11/23-16:01:30 INFO  Wi-Fi successfully restored (after 0.25 seconds)! 
[9021:11/11/23 16:01:55] netagent called with parameters < ping >
[9027:11/11/23 16:02:25] netagent called with parameters < ping >
[9031:11/11/23 16:02:56] netagent called with parameters < ping >
[9038:11/11/23 16:03:32] netagent called with parameters < ping >
11/11/23-16:03:32 INFO  Inhibiting user input 
[9268:11/11/23 16:04:02] netagent called with parameters < ping >
```
</details>

**Comment by NiLuJe** [comment] 2023-11-11 17:00
QUite likely a duplicate of any of the numerous Wi-Fi + PB issues (e.g., at random, #10183)

**Closed by NiLuJe** 2023-11-11 17:00 UTC
Labels: PocketBook
