### ISSUE TITLE
WiFi issues

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#6429] opened 2020-07-25 14:38 UTC
* KOReader version: 2020.07.1
* Device: Kobo Forma

#### Issue
It seems that most of the time after connecting to Wi-Fi and then going to News RSS/Atom and tap on Download News, a box appears that says Activating Wi-Fi. Waiting for Wi-Fi connection... Timeout 30 secs and the reader hangs.

This is weird in the first place because I am already connected to Wi-Fi. Secondly, the timeout does not work as my reader freezes.

My guess is that this is a WiFi issue not a news downloader issue. Maybe related to #6430.

#### Steps to reproduce

Activate Wi-fi, connect to wi-fi
Goto news downloader and download news.
happens most of the time to me.

**Comment by pazos** [comment] 2020-07-25 15:02
Crash.log?

**Comment by Galunid** [comment] 2020-07-25 15:47
Perhaps this is related to #6422 and probably #6421? #6422 was "fixed" by restarting device. `crash.log` will definitely help, and info whether your Kobo recently updated itself can be useful too.
> Okay, I _seem_ to have tracked it down to our use of `udhcpc`... (Incidentally, it's from busybox, and they updated busybox in FW 4.22... And there's been quite a few changes between the before/after versions (as well as in newer versions, still), so, who knows).
> 
> Switching to `dhcpcd` (like Nickel itself did, probably a while back) magically fixes all the things.

@NiLuJe Mentioned this in https://github.com/koreader/koreader/issues/6421#issuecomment-663790380, perhaps it also applies here?

**Comment by NiLuJe** [comment] 2020-07-25 17:17
Yep, duplicate of #6421.

**Closed by NiLuJe** 2020-07-25 17:17 UTC
Labels: Kobo, duplicate, need more info
