### ISSUE TITLE
muPDF: "Page Overlap" cannot be set by default

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7885] opened 2021-06-24 21:15 UTC
* KOReader version: 2021-05.104
* Device: Kindle PW3 (FW 5.9.7)

#### Issue
Currently, `Page Overlap` option from the top menu cannot be set by default. Neither with or without tick. 

#### Steps to reproduce
Open a pdf/djvu file, go to top menu, Page Overlap Menu - long press `Page Overlap` : nothing happens.

I was able to set it `true` in the `default.persistent.lua` though.

**Comment by poire-z** [comment] 2021-06-24 21:43
Duplicate of recent #7757, see there for some discussion :)

**Closed by poire-z** 2021-06-24 21:43 UTC
