### ISSUE TITLE
Koreader for Android cannot be controlled by Xbox Bluetooth controller

### ISSUE THREAD

**Issue by isPoto** [koreader/koreader#6544] opened 2020-08-22 22:59 UTC
* KOReader version:2020.08.1
* Device: Moaan inkPad X

#### Issue
My Ebook reader is connected to the Xbox wireless controller via Bluetooth. 
In other readers, page turning and applications can be controlled normally via Bluetooth.

But I cannot control Koreader with the handle. 
Please be compatible with Bluetooth page turner control function

You can understand what I want to express by browsing the video I recorded:
https://www.youtube.com/watch?v=J6-YQFLgznc

#### Steps to reproduce
Connect the Xbox controller via Bluetooth on Android. My E-book reader can control other readers with the Xbox bluetooth grip, not the Koreader.

**Comment by isPoto** [comment] 2022-03-04 21:05
@pazos  I'm not find developer options in  tools menu at version 2022.01

I clicked on almost all of the buttons, but I didn't find any that contained the word developer

My E-ink Reader is open Android based, which means that what I can do on my phone, I can do on my reader.

I can control the Vivaldi browser and Moon+ Reader and Tachiyomi with the Xbox Controller in my E-ink Reader or my phone OnePlus 3

I can turn pages in Moon+ reader on my phone with Xbox Controller, which means that I want Koreader to support Xbox Controller control on phone.

I think it's a matter of app support, since both Vivaldi Browser and Moon+ Reader apps support Xbox Controller control, so it's not a very complicated issue, just that Koreader supports joystick mapping on Android.

**Comment by Frenzie** [comment] 2022-03-04 21:21
The developer menu is in the file browser → tools, likely on page 2.

**Comment by isPoto** [comment] 2022-03-05 07:02
> The developer menu is in the file browser → tools, likely on page 2.

I can't find it, can you take a screenshot? I know this is abrupt, but I really can't find it.

![image](https://user-images.githubusercontent.com/59009389/156872496-d6834e3a-8a02-469c-9954-eff9730b51f8.png)

**Comment by Frenzie** [comment] 2022-03-05 07:17
Sorry, and then more tools.

**Comment by poire-z** [comment] 2022-03-05 07:46
And on your screenshot, you are in the "reader". You should exit the book and be in "file browser" (the menu are different whether you're in a book or in the file browser).

**Comment by mergen3107** [comment] 2022-03-05 08:39
I have an Xbox Controller too. Let me try to find its keycodes later this weekend using my Onyx :D

**Comment by mergen3107** [comment] 2022-03-06 07:44
Here are the codes I was able to obtained through KOReader's verbose logs via `logcat KOReader:* *:S | grep "key event =>"` and SSH:
```
Button             | Code     | Action   |
-------------------|----------|----------|
Xbox button        | 0        | (nil)    |
Left stick move    | (ignore) | (nil)    |
Left stick button  | 106      | (nil)    |
Right stick move   | (ignore) | (nil)    |
Right stick button | 103      | (nil)    |
A                  | 96       | (nil)    |
B                  | 97       | (nil)    |
X                  | 99       | (nil)    |
Y                  | 100      | (nil)    |
Dpad: left         | (ignore) | (nil)    |
Dpad: right        | (ignore) | (nil)    |
Dpad: up           | (ignore) | (nil)    |
Dpad: down         | (ignore) | (nil)    |
Menu left          | 109      | (LPgFwd) |
Menu right         | 108      | (nil)    |
LB                 | 102      | (nil)    |
LT                 | (ignore) | (nil)    |
RB                 | 103      | (nil)    |
RT                 | (ignore) | (nil)    |
```

An example catching of a button in logcat looks like this:
```
03-06 13:38:57.212  8148  8179 V KOReader:  key event => code: 109 (LPgFwd), value: 1, time: 1968.751000
03-06 13:38:57.407  8148  8179 V KOReader:  key event => code: 109 (LPgFwd), value: 0, time: 1968.946000
```

Sadly, D-pad and both sticks are ignored, so they can't be reassigned. In Android 10 itself Left stick and D-pad are used as directional moves (in Total Commander, for example). In KOReader they do nothing in FM because I think KOReader doesn't have highlights to select files.

**Comment by Frenzie** [comment] 2022-03-06 09:02
The d-pad I find surprising; the sticks not necessarily since axis events might be of a slightly different type requiring special handling. But I have a 1537 (pre-Bluetooth) so I can't play around with it in Android. (Nor do I feel particularly compelled to, but it's a great excuse, isn't it. ;-P)

https://developer.android.com/training/game-controllers/controller-input

For reference, for SDL I wrote this function to translate stick movement into dumb keypresses.

https://github.com/koreader/koreader-base/blob/5ac0b049192ae68fc8809de44ed7c2741c64836f/ffi/SDL2_0.lua#L205-L254

**Comment by Frenzie** [comment] 2022-03-06 09:15
With my 8bitdo M30 I can confirm the same results.

d-pad does nothing

A = 96
B = 97
C = 103

X = 99
Y = 100
Z = 102

L = 104
R = 105

star does nothing
- = 109
beehive = 98

select = 108

**Comment by isPoto** [comment] 2023-09-28 07:02
Please support the Xbox joystick Koreader by default, and provide a setting to specify the key functions

**Comment by pazos** [comment] 2024-09-22 21:44
I cannot help here as I don't have a controller and I don't plan to buy one.

But, following the documentation above, we already support both KeyEvents and MotionEvents in https://github.com/koreader/koreader-base/blob/master/ffi/input_android.lua. So it should be possible to hack on that code.

Also, if somebody writes a sample app in kotlin/java that showcases how to get input events from a controller, I'm willing to rewrite that in our messy glue code :)

**Comment by pazos** [comment] 2024-09-23 01:51
> Also, if somebody writes a sample app in kotlin/java that showcases how to get input events from a controller, I'm willing to rewrite that in our messy glue code :)

It is way easier than that! (help still welcome for analog inputs)

Almost every button produces a key event. We just seem to miss a bunch of those.

Could you try again with https://github.com/koreader/android-luajit-launcher/pull/512, @mergen3107 @Frenzie ?

**Comment by mergen3107** [comment] 2024-09-23 03:27
@pazos 
I won't have access to Android device with KOReader in a week or so. 

Will see then

**Comment by Frenzie** [comment] 2024-09-23 06:20
I don't think I have the time this week, but I do have an 8bitdo controller that can presumably connect using BT.

**Comment by pazos** [comment] 2024-10-02 12:31
@isPoto: please follow https://github.com/koreader/koreader/issues/12541#issuecomment-2388522276 if you want to remap your bluetooth controller.

All digital inputs (dpad and buttons) should work. Analog inputs such are z-triggers and joysticks won't be supported.

**Closed by pazos** 2024-10-02 12:31 UTC
Labels: enhancement, wontfix, Android
