### ISSUE TITLE
wrong orientation after firmware upgrade

### ISSUE THREAD

**Issue by Dorifer** [koreader/koreader#7614] opened 2021-04-28 13:34 UTC
* KOReader version: 2021.04
* Device: Pocketbook lux 4

#### Issue
after the last firmware upgrade of the reader (U627.6.3.569) the screen orientation switches to landscape after stating the koreader app. Touch inputs are recognized as if the device was still in portrait mode though. The problem persists after resetting the device to factory defaults. 

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by Dorifer** [comment] 2021-04-28 14:54
>  I just downgraded the firmware.

@Nathoufresh how did you do the downgrade?

**Comment by NiLuJe** [comment] 2021-04-28 15:48
Quite likely a duplicate of https://github.com/koreader/koreader/issues/7376

See there for a ix, and a possible (or not) way forward, which needs actual testers.

**Comment by Nathoufresh** [comment] 2021-04-28 16:52
> > I just downgraded the firmware.
> 
> @Nathoufresh how did you do the downgrade?

You go to this website https://www.pocketbook-int.com/int/support/pocketbook-touch-lux-4# , download thé 5.20 firmware, extract the zip and copy the file to the device root. Then poweroff and you hold next and previous buttons while powering on. Its gonna upgrade

**Comment by Dorifer** [comment] 2021-04-29 07:42
the fix in #7376 worked in my case too, thx for the pointer @NiLuJe

**Comment by NiLuJe** [comment] 2021-05-24 22:34
Duplicated in #7747

**Closed by NiLuJe** 2021-05-24 22:34 UTC
Labels: PocketBook, firmware, help-wanted
