### ISSUE TITLE
Suggest function : Word wise function for Koreader

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#4980] opened 2019-04-29 11:08 UTC
* KOReader version:all version
* Device: all device
I don't know if it is possible to add "word wise" function to Koreader app.
I love Koreader, however, there is one missing function that make me sometimes switch to original reader of kindle, it is word wise.
Hope pro. will find ways to add that function

**Comment by pepefil** [comment] 2019-04-29 11:27
I like this feature too. Maybe this scripts can help KOReader developpers: https://www.mobileread.com/forums/showthread.php?t=294777

**Comment by Frenzie** [comment] 2019-04-29 11:40
Duplicate of #3044.

**Closed** 2019-04-29 16:33 UTC
Labels: duplicate
