### ISSUE TITLE
Dictionary lookup broken

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#3081] opened 2017-08-12 21:34 UTC
* KOReader version:v2015.11-1113-g16dd517
* Device: Kindle 7th Generation

#### Issue
Dictionary lookup yields no results
#### Steps to reproduce
Open a PDF document in KOReader, look up a word in dictionary either by clicking a word or through menu. Message appears saying definition not found even though it should have been.

**Comment by Frenzie** [comment] 2017-08-12 21:57
Duplicate of #3075.

**Closed by Frenzie** 2017-08-12 21:57 UTC
