### ISSUE TITLE
Local calibre OPDS response code 400

### ISSUE THREAD

**Issue by sat3ll** [koreader/koreader#5703] opened 2019-12-22 23:37 UTC
* KOReader version: 2019.11
* Device: Android | Kindle Fire HD (2nd Generation) (2012)

#### Issue
Attempting to use a Local calibre catalog results in "Cannot get catalog. Server response code 400"

#### Steps to reproduce
- Have calibre start a OPDS server (with user/pass config)
     - Tested on localhost and another device in the same LAN via web-browser
- Set host/port/user/pass in KOReader.
- Attempt to connect

I've also tried to "Add new OPDS catalog" with almost the same settings but appended '/opds/' in the
catalog URL.

Calibre server logs indicate that there are attempts to retrieve/access it but with error 400.
```
192.168.0.143 port-51127 - 22/Dec/2019:23:14:09 +0000 "HEAD /opds HTTP/1.1" 400 126
192.168.0.143 port-51128 - 22/Dec/2019:23:14:09 +0000 "GET /opds HTTP/1.1" 400 159
```

**Comment by NiLuJe** [comment] 2019-12-23 00:08
Quite possibly a duplicate of #3953

**Comment by sat3ll** [comment] 2019-12-23 00:22
#3953 mentions no error message but I decided to try some settings based on that ticket:
- Disabling user/password auth = Works
- Enabling user/pass auth with auth=auto = Error 400 (even with no user/pass specified)
- Enabling user/pass auth with auth=digest = Error 400 (even with no user/pass specified)
- Enabling user/pass auth with auth=basic = Works

It's likely that this issue is actually a "progress" of the issue #3953 that you mentioned.

**Comment by pazos** [comment] 2019-12-23 15:07
> #3953 mentions no error message but I decided to try some settings based on that ticket:
> 
> * Disabling user/password auth = Works
> * Enabling user/pass auth with auth=auto = Error 400 (even with no user/pass specified)
> * Enabling user/pass auth with auth=digest = Error 400 (even with no user/pass specified)
> * Enabling user/pass auth with auth=basic = Works
> 
> It's likely that this issue is actually a "progress" of the issue #3953 that you mentioned.

@sat3ll: that info is quite relevant. Lets move converstation to #3953.

**Closed by pazos** 2019-12-23 15:07 UTC
