### ISSUE TITLE
warm-light for Android devices. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7298] opened 2021-02-16 11:47 UTC
Generally I use (twilight pro) a blue light filter app for reading in the dark, it's so flexible and adjustable (I'm using an android tablet with LCD screen) but it works on the whole device (background and all apps) till you pause it.
Can we have an (in koreader) warm light (blue light filter) for Android devices? 

The app link on Google play for more information https://play.google.com/store/apps/details?id=com.urbandroid.lux

**Comment by Frenzie** [comment] 2021-02-16 12:56
It sounds like a great app, but it's not clear to me where KOReader comes in?

**Comment by pazos** [comment] 2021-02-16 13:03
Duplicate of #5768

**Closed by pazos** 2021-02-16 13:03 UTC
Labels: enhancement
