### ISSUE TITLE
Dismiss Wi-Fi scan popup doesn't work

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#4227] opened 2018-09-14 07:03 UTC
* KOReader version: latest (updated today) but the issue has been there for previous versions as well
* Device: kobo glo hd

#### Issue
Wi-Fi scan pop up window is still shown after connection. I need to tap twice (to close "Connected to network" and to close Wifi scan window) to get rid of it.
This is only on the Kobo Glo HD on my Kobo Mini the scan pop-up is closed automatically if "Dismiss Wi-FI scan popup after connection" is marked. 
Another difference is that on the GloHD when turning on Wi-Fi, after the 'Do you want to turn on Wi-Fi?' popup, when the Wi-Fi scan window first pops up there is an edit field on the right and it doesn't connect automatically. I have to tap on the name of the Wi-Fi router to select it before it connects. On the Mini it connects automatically after tapping 'turn on' in the 'Do you want to turn on Wi-Fi?' pop-up.

**Comment by NiLuJe** [comment] 2018-09-14 16:45
If it's running on a recent FW, that's probably a side-effect of the weird things we've seen happen with wifi on the Glo HD only... @poire-z has one, he'll probably be able to say more about that ;).

**Comment by poire-z** [comment] 2018-09-14 17:01
On newer firmwares, the wifi scan list was always empty, so I coudn't connect at all and do as much as the original poster seems to be able to do. So, I guess @alex125 has an older firmware (<4.8.11073): can you confirm?

I can't say how it works on older firmwares, as I don't/can't use our wifi UI and co (I have my own hack to uimanager & friends, details at https://github.com/koreader/koreader/pull/3395#issuecomment-357796949, mostly because I need a script to do much more: static ip on my main SSID, dhcp on some occasional others...).

But I know one who does :) throwing the hot potatoping to @cramoisi ! (and he has an Aura One to compare behaviours and confirm any difference.)

**Comment by alex125** [comment] 2018-09-14 17:09
Yes, I have an old firmware (3.19.5761)

**Comment by NiLuJe** [comment] 2018-09-19 16:54
Then random stupid question, just in case: is the network you're connecting to saved in Nickel? (i.e., is it one Nickel will also auto-connects to).

**Comment by cramoisi** [comment] 2018-09-19 17:19
@poire-z : on the last firmware, no list on first try (it only displays a little empty and small rectangle I screenshoted on the first issue opened about this problem). The second try is always successful on KA1. (But I won't be able to test it before friday as I don't have a proper internet connexion right now (they will come to install it tomorrow)). @NiLuJe  : yes.

**Comment by alex125** [comment] 2018-09-20 18:16
The network used to be saved in Nickel but I just tried it and it did not auto-connect anymore. After re-entering the WiFi password in Nickel, everything works fine in koreader for the Glo HD. Koreader auto-connects and the WiFi scan pop-up closes automatically after connection. Thanks, NiLuJe, for the "random stupid question".

**Comment by cramoisi** [comment] 2018-09-21 04:42
@alex125 : I will try to remove and re-add everything. thanks for the tip !

**Comment by NiLuJe** [comment] 2018-09-21 04:52
@alex125: That, at least, is the expected behavior in these specific circumstances, so, yay ;).

**Comment by cramoisi** [comment] 2018-10-15 06:10
Late but confirmed. When everything is set right in nickel (as it should) everything goes smooth in koreader. (the popup is not empty, and is correctly dismissed). Tested on gloHD and KA1 (@NiLuJe  I don't have access to an Aura anymore). So there is no issue :-)

**Comment by NiLuJe** [comment] 2018-10-15 16:01
@cramoisi : Thanks for testing this again ;).

Closing this for now, there are already a few issues open about pending network manager enhancements ;).

**Closed by NiLuJe** 2018-10-15 16:01 UTC
Labels: Kobo, bug, firmware
