### ISSUE TITLE
Pages from other books get displayed when turning page in pdf

### ISSUE THREAD

**Issue by RCoeurjoly** [koreader/koreader#6070] opened 2020-04-18 22:44 UTC
* KOReader version: v2020.03.2-39-gea9a2fd_2020-04-17 (with the changes of https://github.com/koreader/koreader/pull/6067)
* Device: Onyx Max Boox Carta

#### Issue
When opening a certain pdf, pages from other books appear.
When turning a page forward either the same page remains.
One thing that remains good is that the page number on the bottom right changes correctly when turning a page.
The behavior is really strange so it is difficult to describe.
I am willing to debug this myself, but I would need some pointers for what to look for.

#### Steps to reproduce
Open pdf.
Turn page forward by clicking on the right hand side.

**Comment by poire-z** [comment] 2020-04-18 22:59
Possibly related: #5878.
With PDFs, the bitmap/blitbuffer of the rendered page are cached. I'd suspect some cache issue, https://github.com/koreader/koreader/issues/5878#issuecomment-588409953

**Comment by RCoeurjoly** [comment] 2020-04-19 07:38
> Possibly related: #5878.
> With PDFs, the bitmap/blitbuffer of the rendered page are cached. I'd suspect some cache issue, [#5878 (comment)](https://github.com/koreader/koreader/issues/5878#issuecomment-588409953)

How do you clear the cache?

**Comment by poire-z** [comment] 2020-04-19 07:53
I think some of the things are cached in memory (those with long hash), so just restart koreader.
Other things are cached in koreader/cache/, so just empty that directory manually (or in File browser, top menu, tools > Developer options > Clear reader's cache.

**Comment by RCoeurjoly** [comment] 2020-04-19 08:33
> I think some of the things are cached in memory (those with long hash), so just restart koreader.
> Other things are cached in koreader/cache/, so just empty that directory manually (or in File browser, top menu, tools > Developer options > Clear reader's cache.

I confirm that clearing cache (by following the last steps you mentioned) solves the issue, so that confirms that it is a cache issue.

Any thoughts on how we could approach the solution in the codebase?

**Comment by yuanshuai0217** [comment] 2020-04-19 08:37
I'm having similar problems (KOReader version: v2020.04, device: Xiaomi Moaan W7).
I tend to agree that this is caused by bitmap cache, because:

- functions such as dictionary and search remain normal, indicating that there is no problem in text displaying.

- After changing the screen orientation, the page that appears abnormally remains in the same screen orientation, causing it to exceed the screen boundary.

this problem doesn't appear again after rolling back to 2020.03.

**Comment by poire-z** [comment] 2020-04-19 08:55
> Any thoughts on how we could approach the solution in the codebase?

Probably by trying to make sense of frontend/document/koptinterface.lua (I think none of us active devs is really confortable with how that works :)
Adding some print()/logger.warn() around hash used/returned by `KoptInterface:getContextHash()` and if cache hit/miss, see if there's a wrong hit, if something is missing in how the hash is built...

**Comment by NiLuJe** [comment] 2020-04-19 16:06
Weren't there reports of this *before* 2020.03? I thought so, but it might have been nightlies.

In which case, @yuanshuai0217's observation might come in handy to bisect this to begin with.

**Comment by Frenzie** [comment] 2020-04-19 16:51
@ersidnd wrote:

> I'm forced to skip the April update of Koreader. After updating to it on Kobo H2O I opened a PDF that was formatted in a way so as to require me to crop manually, and after cropping manually, to orientate into landscape.
> 
> Maybe because of this, but at any rate after this, Koreader April update did not know anymore what I had cropped. Moreover, it did not know anymore where the content edges were, where the page edges were. The different zoom settings did not have any of their ordinary effect.

Not sure if it's related or what to make of it.

**Comment by NiLuJe** [comment] 2020-04-19 17:14
What's strange is that I don't really see anything PDF related in the [diff](https://github.com/koreader/koreader/compare/v2020.03...v2020.04.1)...

**Comment by Frenzie** [comment] 2020-04-19 17:18
That's what I said. The stuff in base also has decidedly nothing to do with PDF.

**Comment by poire-z** [comment] 2020-04-19 17:29
Unless it's (also) related to the [md5 thingie](https://github.com/koreader/koreader-base/pull/1077), that should be fixed in 2020.04.1.

**Comment by NiLuJe** [comment] 2020-04-19 17:34
That's more likely, yeah, pdfdocument is using Cache, which depends on MD5.

**Comment by Frenzie** [comment] 2020-04-19 17:35
Yeah, I said that too. :-P

Which actually looks quite likely:
https://github.com/koreader/koreader/blob/587758939eb7696d680ed27032343d585c041e4d/frontend/cache.lua#L42-L54

**Comment by poire-z** [comment] 2020-04-19 17:37
@RCoeurjoly @yuanshuai0217 : before you upgrade to 2020.04.1 to check again if this happens, can you look in your koreader/cache when you have the issue, and see if you have files named 0000000... of FFFFFFFFF... ?

**Comment by cramoisi** [comment] 2020-04-19 21:35
Got it too. It happens between pdf (a page of previously opened books (more than one) are displayed in place of the page of the actual pdf). But it also happen with cbz files(pages of the previously opened pdf are displayed in cbz file). Temporary fixe with "clear cache"  but happens again if I open more than one pdf/cbz file

**Comment by cramoisi** [comment] 2020-04-19 21:44
Doesn't seem to happen on 2020.04.1 :-)

**Comment by yuanshuai0217** [comment] 2020-04-20 06:27
@poire-z Yes, there are several files with name of 32 digit hex. After deleting these files, the problem 
doesn't happens, and copying these files back can make the problem happen again.
However, after rolling back to version 2020.03 or upgrading to 2020.04.1, these files still exist, but the problem doesn't appear.

**Comment by poire-z** [comment] 2020-04-20 06:38
> Yes, there are several files with name of 32 digit hex

But was there such files named with _only_ 0 (zero) and F hex digits ? Just curious.
But good if you can't reproduce it with 2020.04.1, thanks.

**Comment by yuanshuai0217** [comment] 2020-04-20 06:51
@poire-z Yes. Two files with name of only 0 and f, and also two files with name that first 16 digits are all 0 and f.

**Comment by poire-z** [comment] 2020-04-20 06:57
Thanks. So that confirms it was that md5 issue, and that it's already fixed :)

**Closed by poire-z** 2020-04-20 06:57 UTC

**Comment by NiLuJe** [comment] 2020-04-20 15:20
Sorry about that, I could have sworn I'd initially checked the MD5 changes on a real device :/.
