### ISSUE TITLE
Evernote is not working

### ISSUE THREAD

**Issue by Geniusssmit** [koreader/koreader#6284] opened 2020-06-20 07:26 UTC
* KOReader version: v2020.06-8-ga9d4e97_2020-06-19
* Device: Pocketbook 740

#### Issue
Can't login into evernote
![IMG_20200620_101919](https://user-images.githubusercontent.com/24941285/85196077-46e43200-b2e0-11ea-89d0-3f4ecb1ffb77.jpg)

#### Steps to reproduce
Try to log in

**Comment by Frenzie** [comment] 2020-06-20 07:31
Duplicate of https://github.com/koreader/koreader/issues/6281, apparently it's some temporary issue because Evernote rolled out a patch.

**Closed by Frenzie** 2020-06-20 07:31 UTC
Labels: Plugin, duplicate
