### ISSUE TITLE
[Kindle NT] Cannot auto-detect style for a fb2 book

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12741] opened 2024-11-16 21:56 UTC
* KOReader version: 2024.07-285-gfd3727274 (legacy)
* Device: Kindle 4 Non-Touch (FW 4.1.4)

#### Issue
When opening a fb2.zip book, KOReader didn't recognize the style and needed `fb2.css` is grayed out.
![Reader_2024-11-16_003313](https://github.com/user-attachments/assets/e8b41481-a928-4790-859e-3be66ae131ae)

I only noticed this issue because I saw missing Chapter titles when jumping between Chapters.

Here is the book render:
![Reader_2024-11-16_001934](https://github.com/user-attachments/assets/692f925b-9800-481f-91e2-e2354c188fbf)

Here is what it actually has underneath:
![Reader_2024-11-16_001908](https://github.com/user-attachments/assets/6f576643-b372-433c-bbca-6ebb02e96bf9)

#### Steps to reproduce
Open a book and jump to any chapter.
Title sentences will be missing (and maybe something else due to missing styles).

##### `crash.log` (if applicable)
Here are crash log (verbose, but not really useful) and book examples.

[crash_K4NT_hidden_titles.log.txt](https://github.com/user-attachments/files/17788029/crash_K4NT_hidden_titles.log.txt)

This is the book that has the issue:
[bad_style.zip](https://github.com/user-attachments/files/17788058/bad_style.zip)
FWIW, it was downloaded over Cloud Storage directly from KOReader on Kindle 4 NT.

This is another fb2.zip book, but it doesn't have the same issue:
[good_style.zip](https://github.com/user-attachments/files/17788057/good_style.zip)

Both should be the same - the have Cyrillic letters inside `zip` (which is uncommon) and reminds me of this issue: https://github.com/koreader/koreader/issues/8074#issuecomment-899468112
I just don't know why it worked on one book, but not the other.

**Comment by mergen3107** [comment] 2024-11-16 21:57
As a workaround, I just made a duplicate ofr `fb2.css` in `data/` folder (e.g., `fb2_bak.css`) and was able to manually select it in the Style menu. I will need to do this for other problematic books.

**Comment by hius07** [comment] 2024-11-17 15:29
Can you open these zipped books with ArchiveViewer plugin? It uses the same unzip output.

**Comment by mergen3107** [comment] 2024-11-17 16:59
I tried that. 

Both fb2.zip opened OK as archives, although fb2 files themselves are shown as unknown bunch of symbols.

**Comment by mergen3107** [comment] 2024-11-18 18:36
I tried to use Kindle's own `unzip`:
Good archive unzipped to `  - ⢥ .fb2`
Bad one unzipped to `૮ ⠭ - 3 - ⢨  ⫠.fb2`

Does KOReader rely on local `unzip`?

**Comment by mergen3107** [comment] 2024-11-18 18:37
> Does KOReader rely on local `unzip`?

OK, yes:
https://github.com/koreader/koreader/blob/1a526a33c2ddad2e8f0553826a3c333f0d02e6cc/frontend/document/credocument.lua#L71-L80

**Comment by mergen3107** [comment] 2024-11-18 18:51
> Problematic unzipping is needed to determine the type of the book only (for css purpose).

Do you know why one of these files worked OK for css detection? Clearly, both of them have weird characters :D

**Comment by hius07** [comment] 2024-11-18 18:54
Some characters not allowed in the OS filepath, I guess.

**Comment by mergen3107** [comment] 2024-11-18 19:01
> _**Some**_ characters not allowed

OK, thank you! That might explain it.

**Comment by mergen3107** [comment] 2024-11-18 20:17
So, it seems there are now two `unzip`s:
- original one from `busybox`
- new one that I put as `/bin/unzip` (with chmod 0755 to be able to execute) and symlinked it to `/usr/bin/unzip`

If I rename my newly created `/usr/bin/unzip` to, say, `/usr/bin/unzip3`, I can run `unzip3` alright.

How do I remove the busybox link to `unzip`?

**Comment by mergen3107** [comment] 2024-11-18 20:43
The problem is, even without a symlink to unzip in /usr/bin/ it `unzip` command referring to the busybox old unzip still works! :D

**Comment by benoit-pierre** [comment] 2024-11-18 20:45
Then you're not replacing the right symlink, or you don't have permission to do so, or you're not doing in the right PATH directory.

**Comment by mergen3107** [comment] 2024-11-18 20:49
```
[root@kindle koreader]# find / -name "unzip"
/mnt/us/koreader/unzip
/mnt/base-us/koreader/unzip
/bin/unzip
/usr/bin/unzip
/usr/local/bin/unzip
```
`/bin/unzip`, and `/usr/bin/unzip` and my new unzip and its symlink that points to it.
`/usr/local/bin/unzip` is new unzip in a different folder (to test). There is only `usbnetwork` in that folder, so it must be in path :D

**Comment by mergen3107** [comment] 2024-11-18 20:49
Here is the `$PATH`:
```
[root@kindle koreader]# echo $PATH
/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin
```

So, there is no other place for unzip to exists except inside archaic busybox...

**Comment by mergen3107** [comment] 2024-11-18 20:51
I tried newer `busybox`es from debian pool, but they complain about too old kernel.
The latests one that worked still has the old unzip, so replacing busybox is not an option (unless I re-compile it, that is)

**Comment by benoit-pierre** [comment] 2024-11-18 20:51
And `/usr/local/bin/unzip` has execute rights?

**Comment by mergen3107** [comment] 2024-11-18 20:52
Yes, `0755`

**Comment by benoit-pierre** [comment] 2024-11-18 20:54
From Busybox FAQ:
> Busybox has a feature called the "standalone shell", where the Busybox shell runs any built-in applets before checking the command path.

What if you run `command unzip …`?

**Comment by mergen3107** [comment] 2024-11-18 20:55
```
[root@kindle koreader]# command unzip
sh: command: not found
```

**Comment by benoit-pierre** [comment] 2024-11-18 21:01
So not even a POSIX shell… Game over. ¯\\_(ツ)_/¯

**Comment by mergen3107** [comment] 2024-11-18 21:02
Thank you @benoit-pierre for helping me along the way!

Welp, the only option left is to... ship a proper unzip with KOReader :D

**Comment by benoit-pierre** [comment] 2024-11-18 21:18
No, the problem is using unzip in the first place.

**Comment by mergen3107** [comment] 2024-11-18 21:29
> Or better yet, switch to libarchive and its bsdtar.

@benoit-pierre 
Why `bsdtar` and not `bsdunzip`?
https://github.com/libarchive/libarchive

**Comment by benoit-pierre** [comment] 2024-11-18 21:34
Because `bsdunzip` only support ZIP archives.

But that's not what I meant: that piece of code that detect the format when CREngine already does it better should be removed.

**Comment by mergen3107** [comment] 2024-11-21 23:22
> **that piece of code that detect the format** when CREngine already does it better should be removed

Can someone please point out where to find this?

**Comment by mergen3107** [comment] 2024-11-21 23:22
> I think, at least for *.fb2.zip, we can skip unzipping and assume the book is fb2.
@hius07 
Can you please show how to do this?

**Comment by benoit-pierre** [comment] 2024-11-21 23:49
Here's how the Crengine's API is set up:
- you call [`LVDocView::LoadDocument(const lChar32 * fname, bool metadataOnly)`](https://github.com/koreader/crengine/blob/master/crengine/src/lvdocview.cpp#L4135C1-L4135C73) to load a file
- which will call [`LVDocView::LoadDocument(LVStreamRef stream, bool metadataOnly)`](https://github.com/koreader/crengine/blob/master/crengine/src/lvdocview.cpp#L4385)

Probing the file format is done in the later, and if you've setup a progress callback, your first notification will be about said format (e.g. https://github.com/koreader/crengine/blob/master/crengine/src/lvdocview.cpp#L4457).

The problem is the Lua code expect to know the format before CREngine is actually called to load the file… Like in `ReaderTypeset:onReadSettings`: https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readertypeset.lua#L30.

So I don't think the progress callback mechanism can be used.

One way around this could be to add an additional `bool only_probe_format` argument to `LVDocView::LoadDocument`, to stop loading after the format is detected. And add another function to allow continuing loading from there (automatically called by `LoadDocument` when `only_probe_format` is false).

**Comment by poire-z** [comment] 2024-11-21 23:56
Currently, we don't need to load libcrengine when ones reads PDF.
I think having to load it early/always just to guess if a file is a fb2.zip is excessive, I'd rather find another solution (or just not care).

**Comment by benoit-pierre** [comment] 2024-11-21 23:58
That would be done in `CreDocument:init()`, at that point, the decision to use crengine has already been made, the library is loaded first things.

I'm not advocating for probing to select the document provider.

**Comment by benoit-pierre** [comment] 2024-11-22 00:01
Quick "dirty" fix, duplicate `CreDocument:register`:
```
    registry:addProvider("fb2", "application/fb2", self, 90)
    registry:addProvider("fb2", "text/fb2+xml", self, 90) -- Alternative mimetype for OPDS.
    registry:addProvider("fb2.zip", "application/zip", self, 90)
    registry:addProvider("fb2.zip", "application/fb2+zip", self, 90) -- Alternative mimetype for OPDS.
```
Which is what @hius07 was suggesting: just look at the extension(s): if the filename ends with `.fb2` or `.fb2.zip`, it's a FB2 document.

**Comment by benoit-pierre** [comment] 2024-11-22 00:03
Also, get rid of those misleading ` -- Alternative mimetype for OPDS` comments? :P

**Comment by benoit-pierre** [comment] 2024-11-22 00:04
Never mind that last comment.

**Comment by mergen3107** [comment] 2024-11-22 22:53
> Quick "dirty" fix, duplicate CreDocument:register:
Duplicate where?

**Comment by benoit-pierre** [comment] 2024-11-22 22:58
In `CreDocument:init`: drop the use of `self:zipContentExt` in favor of just looking at the filename extension(s).

**Comment by mergen3107** [comment] 2024-11-22 23:02
Like this?
```
    if file_type == "zip" then
        -- NuPogodi, 20.05.12: read the content of zip-file
        -- and return extension of the 1st file
        -- file_type = self:zipContentExt(self.file) or "unknown"
        registry:addProvider("fb2", "application/fb2", self, 90)
        registry:addProvider("fb2", "text/fb2+xml", self, 90) -- Alternative mimetype for OPDS.
        registry:addProvider("fb2.zip", "application/zip", self, 90)
        registry:addProvider("fb2.zip", "application/fb2+zip", self, 90) -- Alternative mimetype for OPDS.
    end
```

**Comment by mergen3107** [comment] 2024-11-22 23:08
ah, sorry, that's how it adds to registry.
Something like this would be better?
```
    if file_type == "zip" then
        -- NuPogodi, 20.05.12: read the content of zip-file
        -- and return extension of the 1st file
        -- file_type = self:zipContentExt(self.file) or "unknown"
        file_type = DocumentRegistry:getProvider(self.file) or "unknown"
    end
```

**Comment by benoit-pierre** [comment] 2024-11-22 23:31
Something like this:
```diff
 frontend/document/credocument.lua | 7 +++----
 1 file changed, 3 insertions(+), 4 deletions(-)

diff --git i/frontend/document/credocument.lua w/frontend/document/credocument.lua
index d15a3c6c8..f073431ee 100644
--- i/frontend/document/credocument.lua
+++ w/frontend/document/credocument.lua
@@ -8,6 +8,7 @@ local RenderImage = require("ui/renderimage")
 local Screen = require("device").screen
 local buffer = require("string.buffer")
 local ffi = require("ffi")
+local util = require("frontend/util")
 local C = ffi.C
 local cre -- Delayed loading
 local lfs = require("libs/libkoreader-lfs")
@@ -166,11 +167,9 @@ function CreDocument:init()
     self.flows = {}
     self.page_in_flow = {}
 
-    local file_type = string.lower(string.match(self.file, ".+%.([^.]+)") or "")
+    local file_type = util.getFileNameSuffix(self.file)
     if file_type == "zip" then
-        -- NuPogodi, 20.05.12: read the content of zip-file
-        -- and return extension of the 1st file
-        file_type = self:zipContentExt(self.file) or "unknown"
+        file_type = util.getFileNameSuffix(self.file:sub(1, -5))
     end
 
     -- June 2018: epub.css has been cleaned to be more conforming to HTML specs
```

**Comment by mergen3107** [comment] 2024-11-23 03:41
Thank you! This works!

Any downsides of this method?

Can I PR?

**Comment by mergen3107** [comment] 2024-11-23 03:51
Can this 
`if file_type == "zip" then` 
be changed to 
`if file_type == "fb2.zip" then`?

**Comment by benoit-pierre** [comment] 2024-11-23 03:52
Why?

**Comment by mergen3107** [comment] 2024-11-23 03:53
So, fb2 books, if zipped, are 99% inside an archive with `.fb2.zip` in the end.
I am not sure if that's an actual spec, or just a tradition.
So, I don't have problems with letting KOReader assume that `.fb2.zip` has `.fb2` books inside.

**Comment by mergen3107** [comment] 2024-11-23 03:53
Also, what does this `:sub(1, -5)` do?

**Comment by benoit-pierre** [comment] 2024-11-23 03:55
Strip the `.zip` suffix.

**Comment by mergen3107** [comment] 2024-11-23 03:55
> so if your zipped FB2 file is named `book.zip`

I didn't understand this part. Did you mean "non FB2 file"?

**Comment by benoit-pierre** [comment] 2024-11-23 03:56
I was more focused on the false negatives, but you're more focused on the false positives.

**Comment by mergen3107** [comment] 2024-11-23 03:57
> Strip the `.zip` suffix.

Ah, I see now.
It takes `abc.fb2.zip`, then `if` checks for `zip` and then function inside finds the extension of `abc.fb2` and takes the book inside as fb2

**Comment by mergen3107** [comment] 2024-11-23 03:58
OK, so if I have just `abc.zip`, it won't find the second to last extension and ... apply what style? `None`?

**Comment by mergen3107** [comment] 2024-11-23 04:05
OK, tested it. 
Same book, but named just `_ks.zip`.
1) FM couldn't parse it to extract cover.
2) However, I was able to right-click open-with CRE, and it applied `epub` style.

**Comment by benoit-pierre** [comment] 2024-11-23 04:05
The default style for all non-FB[23] formats.

It might be clearer if that extension / file type check is moved:
```diff
 frontend/document/credocument.lua | 31 +++++++++----------------------
 1 file changed, 9 insertions(+), 22 deletions(-)

diff --git i/frontend/document/credocument.lua w/frontend/document/credocument.lua
index d15a3c6c8..481c4aa8e 100644
--- i/frontend/document/credocument.lua
+++ w/frontend/document/credocument.lua
@@ -8,6 +8,7 @@ local RenderImage = require("ui/renderimage")
 local Screen = require("device").screen
 local buffer = require("string.buffer")
 local ffi = require("ffi")
+local util = require("frontend/util")
 local C = ffi.C
 local cre -- Delayed loading
 local lfs = require("libs/libkoreader-lfs")
@@ -77,20 +78,6 @@ local CreDocument = Document:extend{
     last_linear_page = nil,
 }
 
--- NuPogodi, 20.05.12: inspect the zipfile content
-function CreDocument:zipContentExt(fname)
-    local std_out = io.popen("unzip ".."-qql \""..fname.."\"")
-    if std_out then
-        local size, ext
-        for line in std_out:lines() do
-            size, ext = string.match(line, "%s+(%d+)%s+.+%.([^.]+)")
-            if size and ext then break end
-        end
-        std_out:close()
-        if ext then return string.lower(ext) end
-    end
-end
-
 function CreDocument:cacheInit()
     -- remove legacy cr3cache directory
     if lfs.attributes("./cr3cache", "mode") == "directory" then
@@ -166,13 +153,6 @@ function CreDocument:init()
     self.flows = {}
     self.page_in_flow = {}
 
-    local file_type = string.lower(string.match(self.file, ".+%.([^.]+)") or "")
-    if file_type == "zip" then
-        -- NuPogodi, 20.05.12: read the content of zip-file
-        -- and return extension of the 1st file
-        file_type = self:zipContentExt(self.file) or "unknown"
-    end
-
     -- June 2018: epub.css has been cleaned to be more conforming to HTML specs
     -- and to not include class name based styles (with conditional compatibility
     -- styles for previously opened documents). It should be usable on all
@@ -181,9 +161,16 @@ function CreDocument:init()
     -- same way, and are kept as-is for when a previously opened document
     -- requests one of them.
     self.default_css = "./data/epub.css"
+    local file_type = util.getFileNameSuffix(self.file)
+    if file_type == "zip" then
+        -- Look for another extension after striping `.zip`
+        -- (e.g. detect `book.fb2.zip` → `book.fb2` as FB2).
+        file_type = util.getFileNameSuffix(self.file:sub(1, -5))
+    end
     if file_type == "fb2" or file_type == "fb3" then
+        -- FB2 won't look good with any html-oriented stylesheet.
         self.default_css = "./data/fb2.css"
-        self.is_fb2 = true -- FB2 won't look good with any html-oriented stylesheet
+        self.is_fb2 = true
     end
 
     -- This mode must be the same as the default one set as ReaderView.view_mode
```

**Comment by mergen3107** [comment] 2024-11-23 04:07
> 1. FM couldn't parse it to extract cover.

I undid the fix, and it seems this has been the case with `.zip` before as well. So the fix didn't break it.

**Comment by benoit-pierre** [comment] 2024-11-23 04:12
No funny business with the cover file name? (like #12656)

**Comment by mergen3107** [comment] 2024-11-23 04:13
Looks good!
I tried to refresh cache information from FM, recached fine.
Cover on page 1 looks OK too

**Comment by mergen3107** [comment] 2024-11-23 04:16
Yeah, I realized that I might have never tried to open just a `.zip` file in KOReader, so I don't what to expect.
I only did `.fb2.zip`s and `.cbz`s as zip archives

**Comment by mergen3107** [comment] 2024-11-24 03:39
@hius07 
1) Do you have any `fb2` books in archives with just `.zip` in the end (not `.fb2.zip`)?
2) It turns out KOReader doesn't know how to process just `.zip` archives. It has no cover extracted and when trying to open it, it says there is no render engine for it. Do you think it worth to default its opening to `Archive Viewer` plugin (if it enabled)? And if it not enabled, put an Info Message that suggests enabling it?

**Comment by hius07** [comment] 2024-11-24 04:16
zip files are opened with muPDF by default.
https://github.com/koreader/koreader/blob/980b50b3705c7f7d5fb4aded5358014103db6ea3/frontend/document/credocument.lua#L1596
https://github.com/koreader/koreader/blob/980b50b3705c7f7d5fb4aded5358014103db6ea3/frontend/document/pdfdocument.lua#L380

**Comment by hius07** [comment] 2024-11-24 04:22
You can set the default provider for a file type in the Open with... dialog.

**Comment by mergen3107** [comment] 2024-11-24 04:24
@hius07 
Got it! Tried to put a png image inside an archive, it got opened with muPDF alright.
So only "incorrect" fb2 books in zip got "no engine".

Do you have any objection to this solution? https://github.com/koreader/koreader/issues/12741#issuecomment-2495287345

**Comment by mergen3107** [comment] 2024-11-24 04:24
> You can set the default provider for a file type in the Open with... dialog.

So, can it distinguish between "image file in a zip" vs "fb2 file in a zip"?

**Comment by hius07** [comment] 2024-11-24 04:27
Nope, the provider is chosen according to the file extension only.

**Comment by mergen3107** [comment] 2024-11-24 05:04
> Nope, the provider is chosen according to the file extension only.

Interesting. I couldn't confirm this.

Here is a screenshot with two zip archives:
- `_ks.zip` with `fb2` book inside - does not get an engine assigned.
- (last file) an archive with image inside - gets muPDF as engine and even cover.

![FileManager_2024-11-24_000143](https://github.com/user-attachments/assets/a5d4e24f-c940-4997-b7c3-ceeedd131a05)

This is with or without the fix above.

**Comment by hius07** [comment] 2024-11-24 05:11
muPDF can open fb2 but cannot open zipped fb2.

**Comment by hius07** [comment] 2024-12-19 07:41
Fixed in https://github.com/koreader/koreader/pull/12902.

**Closed by hius07** 2024-12-19 07:41 UTC
Labels: need more info
