### ISSUE TITLE
Kobo Aura One is not supported (unrecognised model)

### ISSUE THREAD

**Issue by MMihelic** [koreader/koreader#2235] opened 2016-09-01 05:59 UTC
* KOReader version: latest beta
* Device: Kobo Aura One

#### Issue

./luajit: frontend/device/kobo/device.lua:309: unrecognized Kobo model daylight
stack traceback:
	[C]: in function 'error'
	frontend/device/kobo/device.lua:309: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:38: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:1: in main chunk
	[C]: in function 'require'
	./reader.lua:99: in main chunk
	[C]: at 0x0000bea5

**Comment by houqp** [comment] 2016-09-01 07:09
Yup, I don't think any of the developers has this device yet. Did you order it online? I am actually temping to buy one...

**Comment by Frenzie** [comment] 2016-09-01 07:14
I'd love one because it's bigger and has a higher DPI than my H2O but the cost is definitely unjustifiable. Maybe I could try pandering the old one to see how much people are willing to pay. :-P

**Comment by MMihelic** [comment] 2016-09-01 07:18
Yes, I did order it on-line from a French retailer FNAC.

I am afraid there are more differences in the device than I thought initially.
I tried to define a new device in the LUA files, but I was not successful:

- as soon as I try to set the viewport size and bezel (using Aura H2O as an example) I get error that viewport was invalid.
- without viewport definition in the device setup the KOReader starts up but the touch interface is messed up. In file manager when I touch an entry it is apparently triggered, however, the menu for rename/cut/delete comes on instead of opening the folder I touched. At this point, the device freezes.
- KSM08 did install but usb storage doesn't work and usbnet, which does work, is useless because of the build in firewall preventing access. Of course, I am only guessing about the firewall - it could be that the Dropbear  SSHD is not working correctly.

**Comment by Markismus** [comment] 2016-09-03 15:43
Still, it shouldn't crash on it.

**Comment by KenMaltby** [comment] 2016-09-03 17:11
As I understand it, it has no internal SD card.

**Comment by MMihelic** [comment] 2016-09-03 18:54
I'll definitely try to help as much as I can. The Aura One is completely useless for PDF reading with supplied software. I have Aura HD and I know how bad it is there, but it is a lot worse with the One because of the higher pixel count - at least I suppose this is the reason for extreme slowness of repaint. 

Please, send me the Excel sheet. However, do take a look at my comment about the USBNET and the SSHD. It's possible that I will not be able to get shell access. I hope I'll manage to add logging to a file if necessary. I've never worked with LUA before. 

## Now about...
- the viewport: I did try to use the Aura H2O definition as an example. Unfortunately, I had no success. I get an error if I define the viewport with an exact number of pixels as given in the specification, or if I decrease the y axis by one as in Aura H2O definition. It does seem to work if I don't specify anything. Could it be that the specification contains an error? Is there a way for me to directly detect the screen dimensions from a LUA script?
On a side note: Vlastovsoft launcher does seem to work correctly! I haven't tested it much though.

- the touch interface: I find it weird that it does seem to work correctly for a first touch in the file manager (it seems to respond to the correct coordinates). It could be that it is detecting a wrong kind of event. We will see when and if I manage to capture events.
Here it is also worth noting that the touch (and screen dimensions) seems to be correctly interpreted by the KSM and by the Vlastovsoft launcher.

-- Regards, Matej.

**Comment by Markismus** [comment] 2016-09-03 22:22
Just enable telnet and access it over WiFi. The how to is on MobileRead.org and I think I posted the link somewhere in koreaders issues.

**Comment by Markismus** [comment] 2016-09-03 22:28
This is the link: http://www.mobileread.com/forums/showthread.php?p=2681553#post2681553

**Comment by Markismus** [comment] 2016-09-04 16:12
[Event log.xlsx.zip](https://github.com/koreader/koreader/files/453984/Event.log.xlsx.zip)

The sheet makes use of text data files (ev.log files, especially) So click the Data tab in excel and look at the data connections. Modify those to connect the sheet to your ev,log file.

**Comment by MMihelic** [comment] 2016-09-05 07:25
Step 1.: Capture logs - two logs: one is an attempt to get min&max values - visible screen/touch area and the second ones tries gestures in order given in the excel sheet.

Step 2.: Excel analysis (not yet done)

Perhaps of an interest:
Recorded values:			
```
Recorded values:			
min-x	9	min-y	1
max-x	1870	max-y	1402
```

[AuraOne-ev-logs.zip](https://github.com/koreader/koreader/files/454541/AuraOne-ev-logs.zip)

**Comment by Markismus** [comment] 2016-09-05 07:53
Excel analysis is not useful anymore. The format of the ev.log has changed drastically into something human readable. Event codes 53-54 also show Max values of 1872 and 1404. Are those your screen dimensions?

**Comment by MMihelic** [comment] 2016-09-05 08:07
It looks like the firmware update to v4 actually solved some of the problems! I didn't expect that. ;)
Dropbear SSHD over USBNET is now working.

The koreader still crashes in FileManager on touch but I've managed to capture full debug logs. I hope it will help.

With regard to your ev.log format comment: this was not the koreader output. It was output of evtest utility. Were you referring to the output of the evtest?

In the attached file you will find full debug logs from koreader (./reader.lua -d /mnt/onboard > koreader.log.`date +%s` 2>&1) including the ev.log in the *expected* format.

What I did was start koreader from shell in KSM and touch one of the directory names in the FileManager. Wen the touch interface stopped responding I then pressed briefly the poweroff button which was correctly interpreted as suspend command. I unsuspended the device by pressing it again and then killed the luajit.

This was the definition of the kobo_Daylite device during the test:
-- Kobo Aura One:
local KoboDaylight = Kobo:new{
    model = "Kobo_daylight",
    hasFrontlight = yes,
    touch_phoenix_protocol = true,
    display_dpi = 300,
    -- the bezel covers the top 11 pixels:
    viewport = Geom:new{x=0, y=0, w=1404, h=1872},
}

[koreader-ev-crash.zip](https://github.com/koreader/koreader/files/454585/koreader-ev-crash.zip)

**Comment by MMihelic** [comment] 2016-09-05 08:12
Good news!
After disabling the phoenix protocol I managed to start koreader and open the book!
The problem is in the reaction time for touch. It seems to be extremely sensitive and a "normal" length touch is interpreted as long touch or perhaps a double touch!
If i touch an entry just briefly (really short touch) **it works**.

**Comment by Markismus** [comment] 2016-09-05 09:18
Very nice! The "normal" length touch is interpreted as a "hold" gesture, that's why you originally got the rename-move-etc-dialog in filemanager. 
Speculating further: You fiddle around with the "time delay" for the hold gesture to make it a bit less sensitive. I am speculating that due to increased polling speed (whether it is the touch screen or the processor) the delay for an ordinary tap gesture to go over into a hold gesture is not realistic anymore.

**Comment by MMihelic** [comment] 2016-09-05 10:50
I think that the "touch_probe_ev_epoch_time = true" is required. I've tried playing with the tap time delay and it didn't help.

This is my now, more or less, working configuration:
```
-- Kobo Aura One:
local KoboDaylight = Kobo:new{
    model = "Kobo_daylight",
    hasFrontlight = yes,
    touch_probe_ev_epoch_time = true,
    touch_phoenix_protocol = true,
    display_dpi = 300,
    -- the bezel covers the top 11 pixels:
    viewport = Geom:new{x=0, y=0, w=1404, h=1872},
}
```

I am unable to verify the viewport dimensions. Do you have a test image or something that would serve as a ruler to verify that the entire viewport is indeed visible?

**Comment by Markismus** [comment] 2016-09-05 11:11
Quick&Dirty: Turn on nightmode, flip to an near empty page, do you see the edges of the black? 

There used to be a testing script that allowed you to draw a grid on screen, but it seems to be removed from the code. (At least I can't find it anymore!)

**Comment by KenMaltby** [comment] 2016-09-05 13:23
Tshering added a function/script to KSM that let you find the proper screen dimensions for display, in response to the Aura, I think.

**Comment by dagrim1** [comment] 2016-09-05 14:49
Awesome to read about this, should be receiving my Aura One tomorrow so can't wait to try all this out (and perhaps help out more where needed). I actually read pdf's quite a bit, so would be great if it works :)

Thanks for the information and work ppl!

**Comment by MMihelic** [comment] 2016-09-05 15:04
- The KSM function reports the same resolution as I have in my definition above: 1872x1404.
- The night-mode does seem to covert the entire screen.
- It looks to me that the Aura One screen is not covered by bezel on any size. At least I am unable to see it.

I am at work so I haven't yet tried to read any PDF book but quick tests worked just great. I am really happy with the response time etc. There are some quirks that show that not everything is working in the KSM but it is usable. I still need to see how fast the battery will discharge when running KSM and Koreader.

**Comment by Markismus** [comment] 2016-09-05 16:53
The classic WiFi fix was to start Nickel>connect to router>go to KSM>enable WiFi.

**Comment by MMihelic** [comment] 2016-09-05 17:11
This is the output of wbuilder.sh was:
`x_min=4 x_max=1400
y_min=3 y_max=1857
Visible Screen Size: 1396x1854`

**Comment by KenMaltby** [comment] 2016-09-05 23:51
The current KOReader Turn on WiFi process includes a search for active WiFi access points.

**Comment by MMihelic** [comment] 2016-09-06 05:58
:( The battery went nearly flat in 12 hours in suspend mode within Koreader. I don't know whether its KSM or Koreader at fault. Based on my experience from a couple of days ago I'd say it was the KSM. However, one thing to note is, that this battery drainage happened while still on the original v3 firmware.

**Comment by MMihelic** [comment] 2016-09-06 08:34
I think that the following definition is correct or at least close to correct:
```
-- Kobo Aura One:
local KoboDaylight = Kobo:new{
    model = "Kobo_daylight",
    hasFrontlight = yes,
    touch_probe_ev_epoch_time = true,
    touch_phoenix_protocol = true,
    display_dpi = 300,
    viewport = Geom:new{x=4, y=3, w=1396, h=1866},
}
```

**Comment by dagrim1** [comment] 2016-09-07 08:28
Just to be sure, as I just received the Aura One as well, installation is done the standard kobo way? (Installing KSM08 and then KoReader?)

Btw, last night my Aura One drained the battery from 97% to some 37% while being asleep so the above mentioned drain might not be caused by KSM or Koreader at all but be more a general issue.

I disabled autosync and wifi in the meanwhile to see how that goes...

**Comment by MMihelic** [comment] 2016-09-07 08:39
@dagrim1: Have you upgraded the firmware to v4? Do this first.

Yes, install the KSM in the usual way and then add Koreader as you normally would.

After installation you need to manually add the definition for "daylight" device to the file "/koreader/frontend/device/kobo/device.lua" as it is not yet in the repository. Search for the occurrence of the word "dahlia" for an example. There are two sections that you need to add. Just copy both mentioning the "dahlia" and change the device identifier "dahlia" to "daylight".

[b]WARNING: I am writing the following part from memory. I don't have the source at hand![/b]

[h]1st section[/h]
[code]
-- Kobo Aura One:
local KoboDaylight = Kobo:new{
    model = "Kobo_daylight",
    hasFrontlight = yes,
    touch_probe_ev_epoch_time = true,
    touch_phoenix_protocol = true,
    display_dpi = 300,
    viewport = Geom:new{x=4, y=3, w=1396, h=1866},
}
[/code]
[h]2st section[/h]
[code]
if codename == "daylight" then
    return KoboDaylight
elseif codename == "dahlia" then
    return KoboDahlia
[/code]
[/code]

**Comment by dagrim1** [comment] 2016-09-07 08:43
@MMihelic 

Indeed on firmware v4 now and read about needing to add the Aura One to the files manually. Thanks! Not sure if I dare to try right away, but temptation is big.

If another fw-update is released by kobo, will I be able to perform it safely (and perhaps loosing ksm and koreader in the process) or is that really not adviced? I don't mind having to go through the process again, but I would like to be able to get updates while I expect Kobo to release them regularly for their new product...

**Comment by MMihelic** [comment] 2016-09-07 08:56
@dagrim1 
I never had any problems in the past and I was upgrading in two ways: through KSM as per instructions and by simply manually copying the new firmware package to the device. The former method keeps the KSM configuration whereas the later one does not.
Since Koreader installation is not touched by the firmware install even if you use the access to it because the KSM gets overwritten, you'll get it back after reinstalling the KSM.
I think I've never used the Kobo software to make the upgrade either of-the-air of through the desktop software.
The links to the new firmware as well as the instructions on how to apply it are regularly posted tot he [http://www.mobileread.com/forums/forumdisplay.php?f=223](url).

If you wait for a couple of days after each firmware release and browse occasionally through the forum I've just mentioned to spot any complaints about compatibility than you should be pretty safe,

But I have to admit that I was very nervous about upgrading KoboOne as it has no external card or anything. :( Unfortunately I need the PDF support and what Kobo software provides does not even qualify as a bad joke.

Good luck, Matej.

**Comment by dagrim1** [comment] 2016-09-07 09:07
Excellent, just installed it all and works like a charm so far... Decent pdf reading actually possible now ;)

**Comment by dagrim1** [comment] 2016-09-07 12:34
About drainage, as mentioned above this night my battery drained a lot as well. But after applying this fix for autosync (unchecking auto sync wouldn't stick):

Add line:

PeriodicAutoSync=false

in the \.kobo\Kobo\Kobo eReader.conf file under [ApplicationPreferences]

And disabling wifi, it seems I have no more drain (1% in 30 mins with KoReader in suspend mode which is perfectly possible. Will keep an eye on it for a longer period though).

**Comment by AlanSP1** [comment] 2016-09-07 15:05
This last battery drain you're talking about is something from koreader, which is not same as the one you mention in first part of the post, which comes from nickel. Replacing suspend script with CoolReader one will only (maybe) affect koreader suspend.

Still best way is to totally shut reader off if you don't plan to read it for long period of time.

**Comment by dagrim1** [comment] 2016-09-07 15:15
@AlanSP1 

Yeah, I figured as much. But the combined tweaks seemed to have eliminated both so thought that might interest others as well :)

**Comment by AlanSP1** [comment] 2016-09-07 16:59
Sadly, this looks a bit temporarily, as I and others noticed some drain even with CoolReader's script. :(

Hopefully, problems with suspend may be finally resolved as result from this https://github.com/koreader/koreader/issues/2239

**Comment by dalamario** [comment] 2016-09-08 17:43
Nickel wifi stop working after installing KSM08. Even uninstalling it does not solve the problem until kobo aura one firmware is reinstalled. Clearly the installation of KSM overwrite some files that are needed to let wifi work.

**Comment by dagrim1** [comment] 2016-09-09 09:31
@dalamario 

Hmmm, hadn't noticed that one yet. You mean it scans but doesn't find any wifi networks? That's what I'm seeing at least...

**Comment by dalamario** [comment] 2016-09-09 10:01
@dagrim1 

Yes, it doesn't find any network when scanning for it. Not only in koreader / KSM, but also when going back to nickel. 
The only way to have networks back when scanning for networks is disinstall KSM and reinstall kobo firmware.
Now I'm running koreader without KSM and it still working fine and WIFI is OK.

**Comment by dagrim1** [comment] 2016-09-09 10:03
@dalamario 

Thanks, I experience the same issue indeed. Good to hear the other (FileReader) method does work. About reinstalling kobo firmware, you mean factory reset? (Would have to check how to do that though and perhaps first see if some fix is possible...)

**Comment by dalamario** [comment] 2016-09-09 10:08
@dagrim1 

For reinstalling kobo firmware I mean to take the firmware offline update zip (the firmware zip containing the koboroot.tgz) and extract it on .kobo folder to update kobo firmware.
No need for a factory reset.
Only Uninstalling KSM do not solve the WIFI problem, BTW this issue do not seems related to koreader.

**Comment by dagrim1** [comment] 2016-09-09 10:38
@dalamario 

Ah great, just did it like that now (missed that the fw was already available for download). Thanks for the info!

**Comment by AlanSP1** [comment] 2016-09-09 13:25
@dalamario it would be best if you report issue to tshering, author of KSM. He surely would want to know about this problem.

**Comment by KenMaltby** [comment] 2016-09-10 13:53
Tshering has released a patch for the new devices. http://www.mobileread.com/forums/showpost.php?p=3389190&postcount=221

Luck;
Ken

**Comment by houqp** [comment] 2016-09-11 05:42
Thanks everyone for the great work! @MMihelic, do you mind sending out a pull request for your changes?

The output from wbuilder.lua is currently hardcoded. So the proper way to use it is to manually tweak x_min, x_max, y_min and y_max[1] to see if the final result fits on the screen.

Regrads to battery usage: unfortunately, AFAIK, KSM runs alongside with KOReader, so KOReader will consume battery as fast as KSM does.

[1]: https://github.com/koreader/koreader/blob/master/tools/wbuilder.lua#L83

**Comment by houqp** [comment] 2016-09-11 06:02
@dagrim1 , were you using the suspend script from the latest build? It's doing basically the same thing as the one from pbchess. So it's very weird that switching to pbchess's suspend makes a difference.

**Comment by dagrim1** [comment] 2016-09-11 07:53
@houqp : Used the latest one yeah. But after reinstalling firmware and installing koreader the filemonitor way it doesn't seem to work so that's confusing. 

What also might have been the case is that the battery percentage wasn't correctly updating or something. I noticed yesterday when charging the a1 that the percentage stayed the same in koreader. Exiting and going back to nickel showd an actual increase..

So now I just exit koreader when done there, it's easily runnable now anyway :)

**Comment by houqp** [comment] 2016-09-11 21:19
> @houqp : Used the latest one yeah. But after reinstalling firmware and installing koreader the filemonitor way it doesn't seem to work so that's confusing.

By does work you mean koreader was not able to put the device into suspend?

KOReader does not actively update battery status in the background. So you will need to turns some pages or toggle menu on/off many times to trigger the refresh.

**Comment by dagrim1** [comment] 2016-09-11 22:29
@houqp : Well, before it seemed to suspend fine (battery didn't drain while being in sleep mode, not after an hour or so). While now it drained pretty fast.

But as the percentage updated now when I woke up the device (hence me noticing the drain) I don't think that was an issue before.

**Comment by houqp** [comment] 2016-09-11 22:46
And the fast drain happens both for KSM and fmon right?

**Comment by dagrim1** [comment] 2016-09-11 23:02
At first I had both KSM and KoReader installed, copying the pbchess suspend.sh seemed to fix the battery drain. Now with filemonitor it doesn't fix it... But something else might be going on. I only used KSM for 1 or 2 days I think. Perhaps I missed something...

**Comment by AlanSP1** [comment] 2016-09-12 20:04
For problems with suspending device (even Aura One), please check this issue: https://github.com/koreader/koreader/issues/2239

I think that there's something in software that causes this, and that CoolReader's suspend script (you call it pbchess, which is also correct, or maybe even more correct than calling it CoolReader's) works better for some reason, unknown to me.

Anyway, this happens not only for Aura One and I thing that it shouldn't be treated as such. At least H2O also has problems with suspending device, maybe all Kobos have it also.

**Comment by dagrim1** [comment] 2016-09-13 12:10
So I enabled logging on the kobo to see what's going on, but there's not too much going on as far as I can see... (Only suspended for 15mins though. Dropped by 1% but could be accidental and normal of course. Will try longer).

This is what shows up in the log:
# 09/13/16-13:47:21  key ev {
    ["type"] = 1,
    ["time"] = {
        ["usec"] = 946979,
        ["sec"] = 1473767241
    },
    ["code"] = 116,
    ["value"] = 0
}
# 09/13/16-13:47:21  save default dictionary
# 09/13/16-13:47:21  Suspending...
# 09/13/16-13:47:21  show screensaver
# 09/13/16-13:47:22  loading tile cache from ./cache/75ded25e6407a3e21bd6551f77252bc9 {
    ["pageno"] = 1,
    ["excerpt"] = {
        ["y"] = 0,
        ["x"] = 0,
        ["h"] = 1807,
        ["w"] = 1396
    },
    ["size"] = 2522636,
    ["bb"] = 
}
# 09/13/16-13:47:22  show widget unknown
# 09/13/16-13:47:22  refresh: full
# 09/13/16-13:47:22  assigned marker 1 to update: {
    ["refreshtype"] = 1,
    ["time"] = 1473767242034,
    ["rect"] = {
        ["y"] = 0,
        ["x"] = 0,
        ["h"] = 1872,
        ["w"] = 1404
    },
    ["waveform_mode"] = 2
}
# 09/13/16-13:47:24  refresh: full 3 2 1398 1868
# 09/13/16-13:47:24  update area conflicts with active update 1
# 09/13/16-13:47:24  waiting for completion of update 1
# 09/13/16-13:47:24  duration: 0
# 09/13/16-13:47:24  assigned marker 1 to update: {
    ["refreshtype"] = 1,
    ["time"] = 1473767244523.1,
    ["rect"] = {
        ["y"] = 2,
        ["x"] = 3,
        ["h"] = 1868,
        ["w"] = 1398
    },
    ["waveform_mode"] = 2
}
[09/13/16 @ 13:47:32] Kobo Suspend: Going to sleep . . .
[09/13/16 @ 13:47:32] Kobo Suspend: Asked the kernel to put subsystems to sleep
[09/13/16 @ 13:47:34] Kobo Suspend: Waited for 2s because of reasons...
[09/13/16 @ 13:47:34] Kobo Suspend: Synced FS
[09/13/16 @ 13:47:34] Kobo Suspend: Asking for a suspend to RAM . . .
sh: write error: Operation not permitted
[09/13/16 @ 13:47:34] Kobo Suspend: ZzZ ZzZ ZzZ? (1)
[09/13/16 @ 13:47:34] Kobo Suspend: Woke up!
# 09/13/16-14:02:15  key ev {
    ["type"] = 1,
    ["time"] = {
        ["usec"] = 477072,
        ["sec"] = 1473768135
    },
    ["code"] = 116,
    ["value"] = 1
}
# 09/13/16-14:02:15  key ev {
    ["type"] = 1,
    ["time"] = {
        ["usec"] = 667004,
        ["sec"] = 1473768135
    },
    ["code"] = 116,
    ["value"] = 0
}
# 09/13/16-14:02:15  Resuming...

The only issue I can see is it the line:
sh: write error: Operation not permitted

Which seems to be this line: 
echo mem > /sys/power/state

But between sleep (13:47) and wakeup (14:02) there are no visible activities from the log...

Meh, will try with a 1 hour suspend if I can come up with the patience ;)

**Comment by gogolo2** [comment] 2016-10-07 21:16
Is there any progress with koreader for aura one? Thx for your work!

**Comment by AlanSP1** [comment] 2016-10-07 23:18
Koreader now supports KA1, but you still can't download "official" version from here, but you can use version from @houqp linked here: https://github.com/koreader/koreader/issues/2239#issuecomment-249783992 (build 622).

I'm using this version, it works just fine (I have H2O), but users on MobileRead forum confirm that with this version koreader works also without problems on KA1.

**Comment by pickx** [comment] 2016-10-21 16:07
First, thanks @houqp for your build!
On my Aura One I've noticed the brightness levels in KOReader are much dimmer than their Nickel equivalents. This is apparent when switching back and forth from Nickel to KOReader using fmon.

**Comment by houqp** [comment] 2016-10-23 05:15
FYI, future new builds will be available in http://build.koreader.rocks/download/nightly

Unfortunately, I haven't had time to play with my Aura one yet. The new frontlight support will definitely need some work.

**Comment by misakiw** [comment] 2016-10-27 09:17
Hi @houqp, I will get my KA1 tonight. May I know which nightly build is good at this moment?

**Comment by angelmic** [comment] 2016-10-27 09:39
I use build 654, it works just fine on my KA1.

**Comment by houqp** [comment] 2016-10-28 05:00
any build 622 should work :)

**Comment by misakiw** [comment] 2016-10-28 06:27
Thanks for the reply. I am not sure I should ask this question here, I am using KSM to launch Koreader and it provides options to exit to Nickel directly. It works! 

but any option I can do it reversely . i.e. exit to Koreader from Nickel?

**Comment by houqp** [comment] 2016-10-28 06:43
I am not familiar with the switch feature in KSM. But you should be able to click the exit nickel png to exit from nickel to KSM. From there, you can launch KOReader with one click.

**Comment by misakiw** [comment] 2016-10-28 06:52
@houqp I am a newbie to KSM. 
I found another png "swithtokoreader" can launch KOReader from nickel~!!

**Comment by houqp** [comment] 2016-10-28 07:14
Haha, that's even better ;)

**Comment by Frenzie** [comment] 2016-10-29 13:40
I'll add a quick reference to #2251 here (since I don't think it was mentioned yet) before closing this issue because it's fixed.

**Closed by Frenzie** 2016-10-29 13:40 UTC
