### ISSUE TITLE
settings.reader.lua options

### ISSUE THREAD

**Issue by boriar** [koreader/koreader#5565] opened 2019-11-03 19:49 UTC
Is it posible to put somewhere (may be wiki?) all available options for settings.reader.lua?
I found some uncommon options [here](https://github.com/koreader/koreader/issues/2589#issuecomment-323927682), but nether couldn't find a full list of options anywhere.

**Comment by Frenzie** [comment] 2019-11-03 19:54
There are extremely few settings that can't be reached through the GUI and probably no useful ones.

**Comment by poire-z** [comment] 2019-11-03 19:56
That would be a pain to maintain (but you can issue the `grep` command from the first post you linked to get that list). Updating and documenting them would be much work and not really useful, as @Frenzie said, as they are all available and better documented in the UI.
The list you mentionned indeed lists the one that are not settable via the menus (I may have forgotten to update it lately) - and should be enough to discover what else from menus is tweakable.

**Comment by Frenzie** [comment] 2019-11-03 19:57
That comment is currently linked from https://github.com/koreader/koreader/wiki/Change-defaults#advanced btw.

**Comment by Frenzie** [comment] 2019-11-03 20:00
What I didn't notice at a glance is that this is in fact a duplicate of the linked #2589.

**Closed by Frenzie** 2019-11-03 20:00 UTC
Labels: documentation

**Comment by boriar** [comment] 2019-11-03 20:29
Thanks for a very fast reaply!
