### ISSUE TITLE
"Page overlap" submenu should not be disabled while reflow is enabled

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#4937] opened 2019-04-18 04:10 UTC
While reflow is enabled, the "page overlap" submenu is disabled and the thus the setting cannot be changed. However, this setting does affect the display of the document even in reflow mode.

**Comment by NiLuJe** [comment] 2019-04-18 05:11
There's a few old mentions about this in old, old, old issues. I don't remember what came out of it OTOH though ;/.

**Comment by Frenzie** [comment] 2019-11-30 15:23
Closing as a duplicate of #4383.

**Closed by Frenzie** 2019-11-30 15:23 UTC
Labels: UX, bug
