### ISSUE TITLE
Bug: OPDS-PSE doesn't work with Komga

### ISSUE THREAD

**Issue by darthmooguy** [koreader/koreader#8978] opened 2022-04-07 13:18 UTC
* KOReader version: 2022.03.1
* Device: Kobo Libra h2o

#### Issue

When I try to stream a manga from Komga, only the first page is displayed. I suspect this is because Komga doesn't put the page count in the `pse:count` property, but in different namespaces. Here is a sample of the OPDS feed that Komga generates:

```xml
<feed xmlns="http://www.w3.org/2005/Atom">
    <id>ondeck</id>
    <title>On Deck</title>
    <updated>2022-04-07T10:23:11.22933-04:00</updated>
    <author>
        <name>Komga</name>
        <uri>https://github.com/gotson/komga</uri>
    </author>
    <link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="self" href="/opds/v1.2/ondeck" />
    <link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="start" href="/opds/v1.2/catalog" />
    <entry>
        <title>Haikyu!! v13</title>
        <updated>2022-04-02T00:26:04.632-04:00</updated>
        <id>088M61VNQB58W</id>
        <content>cbz - 282.9 MiB</content>
        <link type="image/jpeg" rel="http://opds-spec.org/image/thumbnail" href="/opds/v1.2/books/088M61VNQB58W/thumbnail" />
        <link type="image/jpeg" rel="http://opds-spec.org/image" href="/opds/v1.2/books/088M61VNQB58W/pages/1" />
        <link type="application/zip" rel="http://opds-spec.org/acquisition" href="/opds/v1.2/books/088M61VNQB58W/file/Haikyu!!%20v13.cbz" />
        <link href="/opds/v1.2/books/088M61VNQB58W/pages/{pageNumber}?zero_based=true" xmlns:wstxns1="http://vaemendis.net/opds-pse/ns" wstxns1:count="206" type="image/jpeg" rel="http://vaemendis.net/opds-pse/stream" />
    </entry>
    <entry>
        <title>Naruto v02</title>
        <updated>2022-04-05T19:28:22.307-04:00</updated>
        <id>089V4G7NZB3Q5</id>
        <content>cbz - 234.2 MiB</content>
        <link type="image/jpeg" rel="http://opds-spec.org/image/thumbnail" href="/opds/v1.2/books/089V4G7NZB3Q5/thumbnail" />
        <link type="image/jpeg" rel="http://opds-spec.org/image" href="/opds/v1.2/books/089V4G7NZB3Q5/pages/1" />
        <link type="application/zip" rel="http://opds-spec.org/acquisition" href="/opds/v1.2/books/089V4G7NZB3Q5/file/Naruto%20v02.cbz" />
        <link href="/opds/v1.2/books/089V4G7NZB3Q5/pages/{pageNumber}?zero_based=true" xmlns:wstxns2="http://vaemendis.net/opds-pse/ns" wstxns2:count="201" type="image/jpeg" rel="http://vaemendis.net/opds-pse/stream" />
    </entry>
    <entry>
        <title>One Piece v098</title>
        <updated>2022-04-05T10:34:59.516-04:00</updated>
        <id>088M61VFFB8HG</id>
        <content>cbz - 183.5 MiB</content>
        <link type="image/jpeg" rel="http://opds-spec.org/image/thumbnail" href="/opds/v1.2/books/088M61VFFB8HG/thumbnail" />
        <link type="image/jpeg" rel="http://opds-spec.org/image" href="/opds/v1.2/books/088M61VFFB8HG/pages/1" />
        <link type="application/zip" rel="http://opds-spec.org/acquisition" href="/opds/v1.2/books/088M61VFFB8HG/file/One%20Piece%20v098.cbz" />
        <link href="/opds/v1.2/books/088M61VFFB8HG/pages/{pageNumber}?convert=jpeg&amp;zero_based=true" xmlns:wstxns3="http://vaemendis.net/opds-pse/ns" wstxns3:count="164" type="image/jpeg" rel="http://vaemendis.net/opds-pse/stream" />
    </entry>
</feed>
```

#### Steps to reproduce

1. Have a komga server with some comics/manga in it
2. Add it as a OPDS server in Koreader
3. Try to stream a comic/manga
4. Only the first page is displayed

I'll tag @TesseractCat since they did the implementation!

**Comment by joao945** [comment] 2022-06-19 04:04
I'm having the same issue. I tried changing opdsbrowser.lua to read xmlns:count rather than pse:count, but it crashed. I've reproduced the issue on updated versions of Kavita and Komga, and have yet to see this feature work.

**Comment by gotson** [comment] 2022-06-19 04:12
One way of doing it would be to ignore the namespace and search for `*:count`

**Comment by joao945** [comment] 2022-06-19 12:52
> One way of doing it would be to ignore the namespace and search for `*:count`

Hmm,tried that and no change, still just shows the cover. Very strange issue, I'm actually curious to see if OPDS-PSE works for *anyone*, because I haven't seen it work so far.

**Comment by darthmooguy** [comment] 2022-06-19 13:16
Just putting `*:count` won't work, it'll look for that exact key. For it to ignore the namespace, you would have to loop through all the keys of the link object map to find the one that contains `:count` and use that key instead. (`link[foundCountKey]`)

**Comment by pazos** [comment] 2022-07-14 09:13
Closing in favor of #9103

**Closed by pazos** 2022-07-14 09:13 UTC
