### ISSUE TITLE
wallabg plugin return annotation and highlight of book to server

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#9152] opened 2022-05-31 14:23 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
if you read an article (get from wallabag server) in koreader and take note or highlight on them, you lost your note when sync them with server.
wallabag has annotation feature. it is good if you can send back your note and highlights to wallabag server

**Describe the solution you'd like**
while sync with wallabag sync annotation too. it

**Comment by pazos** [comment] 2022-05-31 21:51
Duplicate of https://github.com/koreader/koreader/issues/7143

Please check open FR before submitting new ones :)

**Closed by pazos** 2022-05-31 21:51 UTC
Labels: enhancement
