### ISSUE TITLE
Sort by last read doesn't work, sorts by last modified instead

### ISSUE THREAD

**Issue by melyux** [koreader/koreader#5590] opened 2019-11-13 03:43 UTC
* KOReader version: 2019.11
* Device: Android (Likebook Alita)

#### Issue
Sorting books by "last read" doesn't actually sort them by last date. The order is identical to that of sort by "last modified". The "History" view however shows the correct last read order.

#### Steps to reproduce
Sort books by "last read" in the browser.

**Comment by NiLuJe** [comment] 2019-11-13 05:19
That vaguely sounds familiar. `noatime` shenanigans or something?

**Comment by pazos** [comment] 2019-11-13 17:31
Can't reproduce. The only place where sorting is granted to work is in the primary storage. Primary storage itself doesn't imply internal storage or sdcard. Most firmwares offer the user to setup an external sdcard as the primary storage. Once the sdcard is configured to work as the primary storage it should be granted rw permissions and it should work as any other ereader.

So my guess is that you're trying to sort books on a storage outside the primary storage.

You can see your primary storage on the hamburguer menu -> system statics -> mountpoint. If you don't see any mountpoint then /sdcard is used and will point to the internal/phone partition.

**Comment by pazos** [comment] 2019-11-13 17:33
@melikyuksel probably want to setup the sdcard as the primary storage and try to reproduce there, or just store books inside a path where we can grant rw permissions.

**Comment by melikyuksel** [comment] 2019-11-15 12:12
So I don’t have a mountpoint under system statistics, so this must mean I am using internal storage. I tried putting a book into the current directory, and deleting it through koreader, and it indeed deleted it, so KOReader does seem to have r/w access. Yet it cannot sort by last read.

**Comment by pazos** [comment] 2019-11-15 16:51
> So I don’t have a mountpoint under system statistics, so this must mean I am using internal storage. I tried putting a book into the current directory, and deleting it through koreader, and it indeed deleted it, so KOReader does seem to have r/w access. Yet it cannot sort by last read.

Mmmh, please contact your vendor. We can't solve this as this isn't reproducible on the emulator/test devices. Probably related to @NiLuJe guesses and the volume manager is mounting internal partition with `noatime` or `relatime`.

**Comment by melikyuksel** [comment] 2019-11-16 07:43
@pazos I ran `cat /proc/mount` on the device, and found the culprit line:

```
/dev/fuse /storage/emulated fuse rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
```

So looks like `noatime` is on for this system, giving the same thing as #3988. Is there a way to enable the same solution as #3990 here for this non-Kobo device?

**Comment by Frenzie** [comment] 2019-11-16 08:14
That PR isn't for Kobos. Note my rewording which explicitly references Android: https://github.com/koreader/koreader/pull/3990/commits/0f5c5d9982bdc6f5000c8a35aaff1ae2b9628950

**Comment by melikyuksel** [comment] 2019-11-16 08:34
My bad, misread that comment. So it’s supposed to be manually updating the `atime` anyway regardless of noatime, but is for some reason not doing that for me?

**Comment by Frenzie** [comment] 2019-11-16 08:54
mtime, can't update atime of course. ;-)

**Comment by pazos** [comment] 2019-11-16 23:57
@melikyuksel: on my tablet, a Huawei MediaPad T5, I have two partitions mounted if a few places. To simplify I append just sdcardfs file systems, but remember that `/data/media` points to the root of internal storage partition and `/mnt/media_rw/3837-3661` to an exfat partition with that UUID.

```adb shell cat /proc/mounts | grep sdcardfs

/data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,reserved_mb=20 0 0
/data/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,reserved_mb=20 0 0
/data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,reserved_mb=20 0 0
/data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,reserved_mb=20 0 0
/mnt/media_rw/3837-3661 /mnt/runtime/default/3837-3661 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/media_rw/3837-3661 /storage/3837-3661 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/media_rw/3837-3661 /mnt/runtime/read/3837-3661 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=23 0 0
/mnt/media_rw/3837-3661 /mnt/runtime/write/3837-3661 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7 0 0
```

Because I configured the exfat partition to be used as the main storage I have a new mountpoint mounted with `relatime` (file access timestamp is updated on file modification).

```adb shell cat /proc/mounts | grep public
/dev/block/vold/public:179:193 /mnt/media_rw/3837-3661 exfat rw,dirsync,nosuid,nodev,noexec,relatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,iocharset=utf8,namecase=0,errors=remount-ro 0 0
```

I guess this specific implementation is just for huawei and you would need to experiment a bit with different setups on your device. I would suggest installing an external sdcard and using that as the main storage, if that's available on your rom.

Sadly, from the point of view of this program, we cannot do nothing more than disable sorting options that aren't available on a specific device.

**Comment by melikyuksel** [comment] 2019-11-17 00:54
@pazos Unfortunately, it’s not just an Android device but a reader from Boyue, so customization is limited.

Was the PR’s title “Fix sort-by-last-read when partition is mounted noatime“ inaccurate in that the workaround by modifying the file and restoring the old modification date only works with relatime, not noatime?

**Comment by pazos** [comment] 2019-11-17 02:18
atime, relatime and noatime are related to last access timestamp written to disk.

There are **no a** ccess **time**stamps on `noatime`.

With `relatime` access timestamps are updated each time the file is modified
With `atime` access timestamps are updated each time the file is accessed.

**Comment by melikyuksel** [comment] 2019-11-17 02:32
Yep, got it. So this being mounted as noatime makes it impossible for KOReader to track the last read, unless the manufacturer (or me, rooting the device) changes the attribute to relatime or atime. I’ll try to contact Boyue and see what they say.

But the question stands: was that PR #3990 titled incorrectly? Its workaround seems to be to modify the file (thus also updating the access time) and then revert the modification time back to the original, leaving behind just the access time change. This is a good strategy for relatime, but wouldn’t work on noatime. Correct?

**Comment by Frenzie** [comment] 2019-11-17 09:21
I think you misunderstand what noatime does (or I do). With noatime, the access time isn't implicitly updated if you just view it (with cat or vi or KOReader). It doesn't disable explicitly updating atime at your desire with `touch -a` or `lfs.touch(file, new_atime, mtime)`.

**Comment by melikyuksel** [comment] 2019-11-17 10:36
@Frenzie You’re correct. In that case, #3990 should have enabled explicitly updating atime with the line `lfs.touch(file, now, mtime)` even in `noatime`. But if that’s true, and the partition is writable, then sorting by last read should work on even the most stubborn of filesystems. Then what could be causing sort by last read to sort by modification date on my device?

**Comment by Frenzie** [comment] 2019-11-17 10:57
I'm not familiar (otoh) with the sorting code. My first guess would be that FAT32 simply doesn't support a particular attribute (much like it doesn't have permissions) but the Kobo example clearly contradicts such a hypothesis.

That doesn't necessarily discount the hypothesis itself. Just because a filesystem supports something doesn't mean the particular implementation used to access it does.

I can confirm that the functionality doesn't seem to work on Android for me either (in a quick test on the Android 6 emulator), so my explicit reference to Android may have naively assumed that it would work there or perhaps it was different on Android 2/4/5.

**Comment by melikyuksel** [comment] 2019-11-17 11:05
Yay, a reproduction! The Likebook is also running Android 6, btw.

**Comment by Frenzie** [comment] 2019-11-17 11:13
Curiously, it works on Android 9. Hold on, let me grab my real Android 6 phone…

**Comment by pazos** [comment] 2020-02-07 15:59
Closing this issue as we cannot workaround firmware limitations.

**Closed by pazos** 2020-02-07 15:59 UTC
Labels: Android, firmware, wontfix
