### ISSUE TITLE
Highlight and Annotation sync similar to Kindle app.

### ISSUE THREAD

**Issue by uncharted-user** [koreader/koreader#9658] opened 2022-10-20 21:52 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
Sorry, got no idea about the level of difficulty. Is it implemented yet or any workaround besides KOHighlight or listed in Roadmap?

**Describe the solution you'd like**
Highlight, bookmark, and annotation syncing over Wi-Fi or USB.

**Describe alternatives you've considered**
Right now I am forced to use Kindle app.

**Additional context**
Thank you for the good work.

**Comment by hius07** [comment] 2022-10-21 00:48
Duplicate of https://github.com/koreader/koreader/issues/4587, https://github.com/koreader/koreader/issues/7058 and somehow https://github.com/koreader/koreader/issues/4866.

**Comment by uncharted-user** [comment] 2022-10-21 09:14
Thank you for the reply. I checked all of those issues or feature request earlier, but those are 2+ years old. Could you please tell me what is the current status or roadmap for that?

[**#4587**](https://github.com/koreader/koreader/issues/4587) is similar to what I was looking for, but not the same. KOHighlight has no feature to sync like e.g. if I highlight on kindle automatically sync to my pc and those are clickable bookmarks as far as I experienced.

**Comment by hius07** [comment] 2022-10-21 09:43
Maybe the Exporter plugin can be helpful for you.
It exports highlights in Text, html, Jason, Joplin, Markdown and Readwise formats.

**Comment by uncharted-user** [comment] 2022-10-21 10:31
Thank you for the prompt reply. Yes it works great but couldn't find bookmark sync feature or am I missing something?

**Comment by hius07** [comment] 2022-10-21 11:02
Page bookmarks (without highlighted text) are not exported.

**Comment by uncharted-user** [comment] 2022-10-21 11:11
Could please tell me how can I import bookmarks + highlights (previously exported) from linux app image to android app or vice versa.

**Comment by pazos** [comment] 2022-10-21 11:13
Hi. There's no roadmap AFAIK.

Contributors work on what they find interesting.

Having duplicates makes harder to keep track of tickets as the feedback/info is in different places.

> Could please tell me how can I import bookmarks + highlights (previously exported) from linux app image to android app or vice versa.

You can't. Export means **export** and it isn't intended to be imported by other KO instances.

Closing this ticket as duplicate.

**Closed by pazos** 2022-10-21 11:13 UTC
Labels: enhancement, duplicate

**Comment by uncharted-user** [comment] 2022-10-21 11:16
So the summary is, **bookmark with highlight sync** is not available for multiple devices.

**Comment by pazos** [comment] 2022-10-21 11:42
> So the summary is, **bookmark with highlight sync** is not available for multiple devices.

You're right. Highlight sync is not available, with or without bookmarks.
You can watch https://github.com/koreader/koreader/issues/4587, as that the ticket that covers the feature request.

But don't hold your breath.

**Comment by uncharted-user** [comment] 2022-10-21 12:47
Thanks.

**Comment by noembryo** [comment] 2022-10-21 13:08
>You're right. Highlight sync is not available, with or without bookmarks.

Actually, _you can_ manually sync highlights using KOHighlights.. :smirk:
