### ISSUE TITLE
FR: highlight should include period / punctuation 

### ISSUE THREAD

**Issue by derekvan** [koreader/koreader#8857] opened 2022-02-27 22:41 UTC
When I try to highlight a complete sentence on my Onyx Boox device, the highlight typically stops before the period. If I bring up the highlight menu (to extend or contract the highlight by a word) this tool also skips the period. 

I’d like the period included with the highlight so that when I export my highlights to notes, I know that I have grabbed a complete sentence rather than a fragment.

**Comment by poire-z** [comment] 2022-02-27 22:58
See the how at https://github.com/koreader/koreader/issues/6473#issuecomment-668606042 and the why at https://github.com/koreader/koreader/issues/6217#issuecomment-636513399.

**Comment by derekvan** [comment] 2022-02-27 23:19
@poire-z fair enough. For my purposes, I want the punctuation nearly every time, but I can see that may not be the case with others. I will say that Readwise users (and you may get more now because this app, in my view, has the best Readwise support out there) probably also prefer to grab the punctuation since Readwise downgrades (so to speak) highlights that don't end with a period. If it's viable, a setting here would really be appreciated (e.g., prefer highlight to include punctuation: yes/no)

**Comment by dgarrett** [comment] 2022-04-18 01:07
I just took a look at how my Kindle handles this, and it doesn't really do anything intelligent. Highlighting a word that is prefixed with a `(` or `"` just includes the prefixed punctuation. And highlighting a word that is suffixed with a `)`, `"`", `.`, or `?` (or any combination of them) just includes the suffixed punctuation.
Dashes are not included in this.

The lookup functionality then drops the punctuation prefix/suffix. Meaning that the prefix/suffix appears in the highlight, but not in the "Vocabulary Builder" history of words that have been looked up in the dictionary.

This seems like it should be a bit easier than described. I've also been frustrated by the current behavior. I'm going to look into this at least a little bit, but no promises since it seems to require Crengine changes, which is something I'm not familiar with.

**Comment by poire-z** [comment] 2022-04-18 07:45
> Highlighting a word that is prefixed with a ( or " just includes the prefixed punctuation
> [...]
> The lookup functionality then drops the punctuation prefix/suffix

Not sure how this looks then on a Kindle.
But the way we do it, there are different things/steps:
A) Visual text selection: this is done by the engine
B) What you do with text selection: lookup, translation, highlight, view HTML
C) The text selection becoming a highlight

I don't think you should touch anything about A) and B): the engines (at least crengine) is "intelligent" enough to stop at word boundaries and grab real words, which is what is best for A) and B). (ie. if I select two words followed by a period or a comma or a `»`, I don't want it in my text selection and lookup input and have the need to have them cleaned up - I also don't want to see it in the gray selected text below my dict lookup result window (this would look ugly).

Then, maybe, for C) only, you might want to see if it makes sense extending start and end pos to grab any starting or ending punctuation - that is, at the time you hit the Highlight button (or release your finger if you have highlighting by default).
(And may be this could be done on Translation too, dunno how this could be better for Google translate - but people use Translate as a dictionary tool too.)

> it seems to require Crengine changes

So, I'd rather not to :)
At most, you could add helpers in crengine so it can tell you if prev/next chars are opening/closing punctuations (which might depend on the text node language, ie. `»` being an opening punctuation in German, but a closing one in French).
(crengine has some VislbleSentenceEnd(), isSentenceStart() xpointers methods, that KOReader doesn't use - I think they are not perfect - and they are used by CoolReader for Text-to-speech sentence fragmentation I think - that we'd rather not mess with.)

Or you can work it all in frontend, using ffi/utf8proc to categorize next/prev chars (without text node support) and decide if you want to include it in the highlight.
And should you grab a end punctuation if your highlight doesn't start with a sentence start?

**Comment by arooni** [comment] 2022-06-10 01:56
As someone who highlights things fairly often (I really need to figure out to synchronize these highlights across the few devices I read on and how to get them off of my mobile device to my computer), I would say this is a welcome improvement.  

I suppose some edge cases would be also to check of if it was the last sentence of a chapter or section.

**Closed** 2022-06-11 18:58 UTC
Labels: enhancement

**Comment by dgarrett** [comment] 2022-06-12 07:04
The screenshots look great to me and seem to cover my typical cases. I'll have to try a build out soon. Thanks for working on this.

**Comment by poire-z** [comment] 2022-06-12 07:13
No need to build, it should in in today's nightly: https://build.koreader.rocks/download/nightly/.
Please have a quick check, to be sure it's ok enough as it will be in the coming soon v2022.06.

**Comment by dgarrett** [comment] 2022-06-17 02:42
I've been running a nightly build for a few days and the new highlight behavior is great, and so far has resulted in exactly what I wanted. Thanks for implementing this!

**Comment by mergen3107** [comment] 2023-12-25 01:57
@poire-z 
https://github.com/koreader/koreader/issues/8857#issuecomment-1151198923
Sorry for digging the old stuff, wanted to ask a quick question.
So I have copied (using QR from Clipboard) a short sentence from a book:
`...asked. "I'm packing it down tight, father. Salt, hazel, and flour!" Father...`.
Here, If I highlight words `I'm packing it down tight, father. Salt, hazel, and flour` and then hit Highlight, it highlights and saves `I'm packing it down tight, father. Salt, hazel, and flour!"`, without the first `"`. Is this expected behavior in the current setup?

**Comment by poire-z** [comment] 2023-12-28 19:05
> Is this expected behavior in the current setup?

I guess it would be the expected behaviour.
And it works if the text was using a proper opening quote like U+201C.
So, probably something with the classic `"` which is ambiguous and can be both opening or closing. And indeed, it seems `"` is flagged as just "PUNCT", like `, ' !`.
(Dunno - don't really want to know :) - if we could look for a space after or before to consider it opening if stuck to something on its right but not on its left, or heuristics like that, but I guess it may get complicated depending on what the stuff on both sides is...)

**Comment by mergen3107** [comment] 2023-12-28 19:27
Thanks!

No, I don't think it is worth something about it :D 

It is not a bug deal to deselect the last `"` or select up the first `"` with these great sliders and long-taps on them :D
