### ISSUE TITLE
[bug?] On PW4 zsync crashes when trying to share 

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4683] opened 2019-02-28 22:51 UTC
* KOReader version:
* Device:

#### Steps to reproduce

0) set up book share
1) Click "ZSync" then "Share this Document"
2) At some point it seems to crash

Crash log:
https://gist.github.com/arooni/0d63ddc022a1c5da234e9feba58560de

TO be quite honest I'm not sure how zsync is supposed to work.  I read https://github.com/koreader/koreader/wiki/Zsync-transport 

But it seems like once I go to 'subscribe to book share', and then open another book, the option to 'subscribe to book share' is re-eanbled, making it seem like I Have to do this PER BOOK.  

Also and perhaps more importantly I can't seem to get the zsync to work from my Paperwhite 4 to my kindle fire tablet.  I have set folders for each book sharing, but can't see them depositing any books to the folder

**Comment by Frenzie** [comment] 2019-02-28 22:57
I don't think "crashes" can ever be bug *question mark*. :-D

However, it's also a duplicate of #3880.

**Comment by arooni** [comment] 2019-02-28 23:11
Fair point!  I was just unsure how exactly I could reproduce the error so I was a little reticent to write bug.

I take it with zsync I have to manually export each book to be shared per device?  There's no dropbox type thing where if the book ends up in a given synced folder on one device that it would end up on all devices opted in to sync?

**Closed** 2019-03-01 00:26 UTC
Labels: Plugin, bug, duplicate

**Comment by Frenzie** [comment] 2019-03-01 08:21
I believe so, yes. For something like Dropbox one could use Syncthing.

https://github.com/koreader/koreader/issues/3630#issuecomment-360988434
