### ISSUE TITLE
[Android 4.x]: Bottom of Screen being cut-off by navigation bar.

### ISSUE THREAD

**Issue by calverb** [koreader/koreader#4794] opened 2019-03-14 17:54 UTC
#####KOreader version
KoReader 2019.03

######Device Information
Energy Sistems Ereader Pro Plus
Model Number : Energy_eReaderProP
Android Version : 4.2.2
Kernel Version : Energy_ereaderProP_2016011214
Build No : Energy_ereaderProP_V2.0.0_2016011214
Energy Version : 3.0.0B

####### Other Information :
Running the e-Ink Test returns :
Manufacturer : Energy_Sistem
Brand : Energy_Sistem
Model : eReaderProPlus
Product : Energy_eReaderProP
Hardware : rk30board

fake update = does nothing
rk30xx normal update = screen refresh
rk30xx forced update = screen refresh

#### Issue
The lowest part of the screen is used by Android for the "Home", "Back" etc buttons. This obscures the lowest part of KoReader's display and it is impossible to see all of the bottom menu and dependant on font size, margins etc the bottom lines of text in a book are also obscured.

There is no "Full Screen" option visible in the KoReader settings menu.

Two photo's of the screen are attached - one shows the display with the Android System Menu (Back, Home, Frontlight etc) as a hidden (Black) display attempting to display the KOreader bottom menu The other a menu screen where "Full Screen " option would be expected and with the Android System Menu (visible this time) cutting off the lowest lines of the book text.

#### Illustrations
![KoReader-1](https://user-images.githubusercontent.com/4508319/54379253-f879c980-4680-11e9-939a-2a3738bdb2c8.jpg)

![KoReader2](https://user-images.githubusercontent.com/4508319/54379300-0fb8b700-4681-11e9-8230-c7fc0b7acf30.jpg)

##### `crash.log` (if applicable)
`N/A

**Comment by pazos** [comment] 2019-03-14 18:41
@calverb: looking at the first image it seems that the 3 buttons are clickable (there are three white dots onscreen). What happens if you click home and then return to KOReader? Can you still reproduce the issue?.

If you can reproduce the issue after returning home then I would need logs (`adb logcat luajit-launcher:V *:S`). We rely on non broken activity cycles and some devices won't report state changes just on time :p 

> There is no "Full Screen" option visible in the KoReader settings menu.

Yes, I did that when I fixed the fullscreen toggle on 14/15. On API16 and newer the fullscreen toggle is disabled since it was borked (the method used to get the statusbar height reports 0).

**Comment by pazos** [comment] 2019-03-14 20:49
Ok, I found the reason and can reproduce on a 4.2.2 emulator (tablet):

https://stackoverflow.com/questions/12605266/how-to-hide-system-navigation-bar-in-tablets/12605313#12605313

Short story: navigation bar can't be hidden on tablets running 4.0.3 - 4.3. You can hide it but any user interaction will show it again. The best possible solution is what we're doing (dimming controls like you see in your first picture).

To understand what's a tablet I must say that any device *without* physical home button can be considered as a tablet. So other devices, even running the same android version, with a hardware button will switch to fullscreen.

If you were able to run koreader at fullscreen on the same device please ping me again. If you never run KOReader fullscreen on that device you'll need to do this workaround: https://github.com/koreader/koreader/issues/4769#issuecomment-471364494

**Comment by calverb** [comment] 2019-03-14 20:56
The three buttons are shown on a black bar, if you click on the bar it changes colour to white and the buttons can be clicked.  If I then select "Home" and then re-open KoReader it returns to exactly where it was with the bar now black again.

I don't know how to get at the logs you need. The device is not rooted and I don't think anyone has rooted one.   In addition I am running Windows 8.1 on my PC and am unsure how to proceed.   Any advice would be welcome.

I don't know if it tells you anything but I have a copy of ALReader on the device and that appears to handle the issue correctly - the bottom bar disappears once a book page is displayed and only reappears when the bottom of the screen is touched.

**Comment by calverb** [comment] 2019-03-14 21:12
@pazos,
Our comments crossed - just to explain about the reader, it has a physical "back" button, a physical button that refreshes the screen and two sets of "back" and "forward" buttons.

The reader has two "stock" reading apps - one based on FB2, the other on Adobe, both these and the ALReader I mentioned previously.   All these manage to dismiss the navigation bar and allow all the screen to be used for the book page.
It seems I'll have to look into creating the "notch patch" you mention and see how that pans out.

**Comment by Cellaris** [comment] 2019-03-14 21:13
You can hide the status bar by installing a full-screen application.

**Comment by pazos** [comment] 2019-03-14 21:24
It should be possible to make it work for one specific device on one specific way, but there are no ways to get reliable results across devices, vendors (samsung's touchwiz ignores some ui flags) and versions.

Right now we get screen height and width at launch and use these values during the entire life of the activity. For really old devices on Ice *Scream* Sandwitch we set a viewport of screen height - status bar height, but that's it. 

@Cellaris: that's interesting, could you please provide more info? In which devices is this neccesary?. The only device I tried w/ an old android version is an energy pro 4 and things work here without any special application

**Comment by Cellaris** [comment] 2019-03-14 21:59
> @Cellaris: that's interesting, could you please provide more info? In which devices is this neccesary?. The only device I tried w/ an old android version is an energy pro 4 and things work here without any special application

It is only necessary in the Energy eReader Pro and Pro+ (Boyue T62C and T62D clones). On the original Boyue, Onyx Boox C67 and modern inkBook (Boyue clones) you do not need to install the full screen application. From other models I have no direct experience.

**Comment by pazos** [comment] 2019-03-15 00:27
Thanks a lot for your feedback, it is really useful :+1: 

> It is only necessary in the Energy eReader Pro and Pro+ (Boyue T62C and T62D clones)

Cool, which app are you using?

> On the original Boyue, Onyx Boox C67 and modern inkBook (Boyue clones) you do not need to install the full screen application. From other models I have no direct experience

The same is expected on most 4-0-4.3 phones/ereaders. Tablets are expected to behave as @calverb reports. AFAICT only root apps are able to get rid of the system UI navigation bar on tablets.

**Comment by Cellaris** [comment] 2019-03-15 00:46
> which app are you using?

full!screen+ (requires root).

**Comment by calverb** [comment] 2019-03-15 10:27
I couldn't locate a "full-screen" app that would work on my non-rooted  Android 4.2.2 based device so I have tried the patch.lua workround suggested earlier.
 A value of 79 px gives an acceptable result - the KOReader effective screen height is reduced and the Android Navigation Bar is always visible.  
Not ideal but it allows me to use KOReader on the device.
None of the other reader apps I have used that dismiss the Nav Bar use touching the screen bottom to activate a menu and I wonder if this would cause a conflict with touching the screen bottom to summon the Nav Bar.   However I gather this does work on other Boyue based readers with KOReader.

**Comment by pazos** [comment] 2019-03-15 12:22
We can do nothing to fix that I'm afraid.

You can blame google for designing android so badly or you can blame boyue/energy for shipping a ereader with a bunch of hardware buttons but no home button.

That said the behaviour of KOReader should be:

![legacy](https://user-images.githubusercontent.com/975883/54430777-e487a380-4724-11e9-91c5-f25986de2f4b.png)

we set screen.height based on real height instead of height. This is because there's no way to differenciate between devices which are allowed to hide the navigation bar and devices which are not allowed. Pinging @Frenzie for opinions...

**Comment by Frenzie** [comment] 2019-03-15 12:39
@pazos My opinion on what precisely? Device-specific workarounds? I think those would probably be fine in principle (e.g., a bit like on Kobo?).

**Comment by pazos** [comment] 2019-03-15 21:27
> My opinion on what precisely? Device-specific workarounds?

yeah, in particular about getting framebuffer height. we get screen real height, which works ok on api19+ and should work on most api18/17. On devices that cannot hide the navigation bar (api17-18) we have two options:

1 - let stuff as is and use a patch per user/device
2 - get screen height minus navigation bar.

2 requires:
- start in normal mode instead of fullscreen
- provide a fullscreen switch like in 14/15 and resize framebuffer accordly
- a quick patch:

```diff

+ if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
+     // immersive mode - report real width and height
+     display.getRealMetrics(metrics);
+ } else {
+     // report real width and height minus navigation bar
+     display.getMetrics(metrics);
+ }
```

**Comment by Frenzie** [comment] 2019-03-15 21:35
The second seems nicer to me, if you don't think it's too much effort.

**Comment by pazos** [comment] 2019-03-15 21:50
> The second seems nicer to me, if you don't think it's too much effort.

Too much effort no but it can break a few setups out there. Right now the patch.lua works overwritting the height value. If we make the framebuffer size dynamic then we will use android.getHeight() instead of android.screen.height.

Also I have no idea how to resize the framebuffer from KOReader pov :/

**Comment by Frenzie** [comment] 2019-03-15 22:28
Probably something very similar in principle to how I did it for SDL?

**Comment by calverb** [comment] 2019-03-19 10:30
I kicked this one off and am happy with the "patch" approach which also allowed me to get KOReader working on an old 9.7inch colour tablet running Android 4.1.1 (great in landscape mode) as well as on the ES E-Ink device that was my original problem.
I'm not sure of the protocol here - is it up to me to close the issue or is someone looking at an alternative to the patch ?

**Comment by Frenzie** [comment] 2019-03-19 10:37
It sounds like @pazos is looking into it, so I'd say it's best to keep it open for now. (And otherwise @pazos can close it.)

**Comment by pazos** [comment] 2019-03-19 12:55
Yes, I will look for alternatives to the patch method. Since I don't have any "special" android device I will need help testing the changes.

**Comment by zeroheure** [comment] 2019-03-28 12:34
FYI, on my Energy Ereader Pro HD, two apps works well with the bottom bar (while KO don't) :
- CoolReader resize the page to fit between top of the screen and the botttom bar. I don't know if it detect the size or not, but there is options to change the page size.
- Youboox manage to hide it

People from EnergySistem has told me that "the navigation bar is managed by the Launcher and it's available to developers that should disable or hide while App is running, because there is no option to hide this bar in the eReader's settings."

**Comment by pazos** [comment] 2019-03-28 16:48
@zeroheure  thanks for the info!!!

> Youboox manage to hide it

It should be possible via some custom "system wide" setting, but it is not standard and I have no idea how to implement that. A PR would be great!! (or even a working example).

> People from EnergySistem has told me that "the navigation bar is managed by the Launcher and it's available to developers that should disable or hide while App is running, because there is no option to hide this bar in the eReader's settings."

People from EnergySistem are clueless. I doubt they're able to rebuild the rom they ship to fix some upstream bug (like leaving the home button unimplemented). Probably the only app they "developed" is the OTA updater, so lol.

> - CoolReader resize the page to fit between top of the screen and the botttom bar. I don't know if it detect the size or not, but there is options to change the page size.
> - BookReader does the same, without options

This is the real deal. But seems harder to me than I though. Help would be great since I don't have any android device below 7.1 and I have no special interest in fixing corning cases.

**Comment by zeroheure** [comment] 2019-03-28 18:49
@pazos  the home button work on the Ereader Pro HD

> Help would be great 

Coming from Perl, I will try to explore Lua world

> I don't have any android device below 7.1 

Did you asked EnergySistem for one ?

**Comment by pazos** [comment] 2019-03-28 19:03
@zeroheure: If you want to help in this specific issue you won't need lua at all. You can build yourself a sample android application (in java or kotlin) which has (working) fullscreen methods and some buttons in the ui to trigger those methods.

development of the luajit loader happens in https://github.com/koreader/android-luajit-launcher and writting a new test app for testing screen things can be done using the [eink-test](https://github.com/koreader/android-luajit-launcher/tree/master/eink-test) as a base.

> home button work on the Ereader Pro HD

Other users reported there's no physical home button on that device.

> Did you asked EnergySistem for one ?

I've got in my hands an energy pro 4, where I started to tinker with android. I touched that device because it was for a friend of mine but have 0 interest in touching other energy sistem devices myself. I'm happy to help others with their devices if I can.

**Comment by calverb** [comment] 2019-03-28 21:10
@pazos 
It was me that said there was no physical home button on my ES reader, however mine is a EReader Pro Plus,  @zeroheure has a EReader Pro HD.  

FWIW I now have the right USB driver on my Win 8.1 box to connect using ADB to the ES reader and to my Android 4.1.1 tablet (no home button but it is rooted).   I'll help if I can but I know nothing about Android etc - my last serious programming was under CP/M  - 8080 assembly language in the 1970's.

Your comments on the ES folk certainly remind me of my dealings with them on the issue of their stock reading apps which either crash (the Adobe based one) or don't understand anything other than very simple CSS (the FB2 based one).   They were singularly unhelpful.

**Comment by pazos** [comment] 2019-03-29 00:06
> It was me that said there was no physical home button on my ES reader, however mine is a EReader Pro Plus, @zeroheure has a EReader Pro HD.

> FWIW I now have the right USB driver on my Win 8.1 box to connect using ADB to the ES reader and to my Android 4.1.1 tablet (no home button but it is rooted). I'll help if I can but I know nothing about Android etc - my last serious programming was under CP/M - 8080 assembly language in the 1970's.

> Your comments on the ES folk certainly remind me of my dealings with them on the issue of their stock reading apps which either crash (the Adobe based one) or don't understand anything other than very simple CSS (the FB2 based one). They were singularly unhelpful.

Great! Now that you rooted your device you should be able to install full!screen+ from the app store, like @Cellaris did. If you disable the navigation bar please remove your patch.lua file to use the entire screen.

I'm interested in feedback (and logs) with and without the navigation bar visible but I need some time to find the best approach because android fullscreen is damn broken on apis 14-17 and the best we can do is workarounding.

Regarding energy sistem (and other boyue clones). Devices with Android 4.x have a bunch of activities (fbreader, adobe and a lot of plugins) and a daemon that updates the database shared by the launcher and both readers and based on fbreader library. The custom launcher just hide some of the activities, like ComicReader and Adobe, from the app drawer.

New 6.0+ devices seem to have an all-in-one launcher/reader ~~based on~~ **stealing** FBReader and MuPDF. This is fine for the Chinese market where Adobe DRM is not a thing.

**Comment by keverets** [comment] 2019-06-07 15:17
I tripped over this today reading an epub on my tablet running Android 5.0.2 and KOReader v2019.05 from F-Droid. When first starting KOReader I can see the entire page, but leaving and then coming back results in the bottom line of text being hidden behind the soft navigation buttons. That makes reading very frustrating.

I was hunting around the menus for a work-around of adding additional bottom margin but couldn't find one. Changing the font size or other style temporarily lets me read the last line, but doing that every page is too tedious.

If an automated fix is too much effort, would something like a setting to increase margins/padding be possible (or is it already present and just difficult to find)?

**Comment by NiLuJe** [comment] 2019-06-07 15:21
Margins settings are ... in the bottom menu, which might be a bit of a catch-22 here ^^.

**Comment by keverets** [comment] 2019-06-07 15:26
@NiLuJe good to know, thanks!

For now I used the workaround of the patch.lua from https://github.com/koreader/koreader/issues/4769 to drop the last 64 px from the screen height.

That let me access the bottom bar where I can change the bottom margin (though that doesn't affect the location of that bar).

**Comment by pazos** [comment] 2019-06-07 15:49
@keverets: your issue is #4996 and probably related to a change made on the underlying android window system in https://github.com/koreader/koreader/commit/4515a360597c987f4675dc4312fd33b5ec712ea6.

If you can't reproduce in v2019.04 that's it. Probably easier to fix than this specific issue (which affects badly designed tablets/phones/ereaders). If you can reproduce in v2019.04 then I have no idea. Still seems easy fixable with love and time :+1:

**Comment by keverets** [comment] 2019-06-07 17:07
@pazos I uninstalled, removed the patch.lua, installed v2019.04 and the issue is still present. So, seems it may need that love & time :wink: . I can follow up in #4996 if that's preferred (it just wasn't clear if that was going to be closed as duplicate).

**Comment by calverb** [comment] 2019-06-18 16:20
An observation - I'm using the patch.lua approach and it seems to work well while reading.   However I recently noticed that if I go to the book info page in order to update the status the bottom of that screen (Book Status) is not visible.

It's ok on the old 9.7inch colour tablet running Android 4.1.1 but not on the Energy Sistems Ereader Pro Plus running Android Version : 4.2.2

**Comment by pazos** [comment] 2019-06-19 16:54
@calverb @keverets @Cellaris: I'm uploading an apk for you to test (for 4.2.2 onwards). -> https://www.dropbox.com/s/4z2upk641c87c6t/koreader-android-arm-linux-androideabi-debug-v2019.04-115-g1d6d4b1d_2019-06-19.apk?dl=0

It should fix the issues switching to fullscreen on resume and (for apis 17 and 18) it should allow you to switch to/from fullscreen in "settings->screen->fullscreen". 

The way to test the fullscreen switch is: (it always start enabled) go to settings and disable fullscreen. Go to history, see if the entire page is displayed, enable fullscreen again, compare the history page between fullscreen/normal modes.

Apis 14, 15 and 16 (anything lower than 4.2.2) are expected to be broken but a confirmation is always cool.

Currently it just a hacked and messy code but we can turn it on something better if things work fine :+1:

**Comment by calverb** [comment] 2019-06-20 08:51
I installed it on my ES EReader (4.2.2)  and it is pretty well untestable as it runs so slowly that it can take up to three minutes to respond to a "keypress".   On startup a blank screen for 5 or more minutes before the "History" page appears is about average.
Sorry can't comment further, other than at no point could I get rid if the navigation bar.

**Comment by pazos** [comment] 2019-06-20 12:57
@calverb: thanks for testing. Well, that is slow even for a debug build. I do expect debug builds being 2x-3x slower than release builds but no more. Hopefully the new build will work fine in terms of speed.

 > Sorry can't comment further, other than at no point could I get rid if the navigation bar.

The navigation bar cannot be hidden without root, that's sure. What I want in this issue is to fit the interface on the region of the screen available to KOReader:

### interface hidden by navigation bar (what you expect on fullscreen)

![1](https://user-images.githubusercontent.com/975883/59850228-06b74000-936a-11e9-866d-2acc5e903dbe.png)

### interface not hidden by navigation bar (what you expect on normal mode)

![2](https://user-images.githubusercontent.com/975883/59850236-0b7bf400-936a-11e9-837a-3cd8031029ad.png)

That's the behaviour of the fullscreen toggle in Jelly Bean. Please check again (this time with a non-debug build -> https://www.dropbox.com/s/890f0dy2oft3mc6/koreader-android-arm-linux-androideabi-v2019.04-115-g1d6d4b1d_2019-06-19.apk?dl=0). I fixed behaviour in older android versions and now fullscreen setting will be stored and the last setting will be reload on program launch.

**Comment by calverb** [comment] 2019-06-20 16:55
O.K - I've installed the non-debug build you provided and checked it out with Fulscreen selected and not selected.   The result is the same in both cases:

![IMGP0119](https://user-images.githubusercontent.com/4508319/59866360-4c343700-9383-11e9-967b-c7fd4c396eca.JPG)

I have removed the patch.lua for the test but it is clearly needed still as when reading a book the bottom of each page is overwritten.

This is the book status page I mentioned earlier : 
![IMGP0120](https://user-images.githubusercontent.com/4508319/59866792-59055a80-9384-11e9-9a2d-985ecfa4098b.JPG)

As you can see the bit at the bottom where I should be able to mark a book as finished is not accessible.

If I have misunderstood what you wanted or if you want anything more checking just ask.   I can't though root the ES reader.

**Comment by pazos** [comment] 2019-06-20 17:45
> O.K - I've installed the non-debug build you provided and checked it out with Fulscreen selected and not selected. The result is the same in both cases

impossible, but changes don't happen without reloading. So, to see changes, you need to go file explorer -> reader -> file explorer (to check changes on the file explorer) and reader -> file explorer -> reader (to check changes on the reader)

> I have removed the patch.lua for the test but it is clearly needed still as when reading a book the bottom of each page is overwritten.

Are you sure?. Check that **fullscreen** is disabled and (to be entirely sure) exit KOReader and launch again. Last setting will be marked (non fullscreen in your case). Could you still reproduce? In that case, could you please take a screenshot/picture?

> As you can see the bit at the bottom where I should be able to mark a book as finished is not accessible.

That's a separate issue since you can reproduce even with the patch.lua. I'm interested too but it is not entirely related.

**Comment by calverb** [comment] 2019-06-20 20:20
O.K I've checked again and it seems I was being fooled after disabling 
fullscreen, then exiting and restarting Koreader.   If I do this then 
when I restart fullscreen still appeared to be disabled, but if I then 
go to the file browser and select a book then when I open it fullscreen 
has been re-enabled.

The situation now is that with fullscreen enabled when I use the reader 
the bottom of the screen is "missing" i.e. overlaid by the nav bar.   
With fullscreen disabled there is a difference - the bottom of the page 
is not overlaid.    So disabling fullscreen does work to give me the 
same effect as I go with the patch when reading a book.   If, once 
disabled it didn't re-enable itself at some point after a restart then 
all would seem fine to me.

Does this accord with what you were trying to check or have I 
misunderstood once again.

**Comment by pazos** [comment] 2019-06-20 22:27
> The situation now is that with fullscreen enabled when I use the reader the bottom of the screen is "missing" i.e. overlaid by the nav bar. With fullscreen disabled there is a difference - the bottom of the page is not overlaid. So disabling fullscreen does work to give me the same effect as I go with the patch when reading a book.

That's exactly the expected result. Even more, book info page / history page / opds page, etc are now displayed entirely in the screen area above the navigation bar.

> if I then go to the file browser and select a book then when I open it fullscreen has been re-enabled. // If, once disabled it didn't re-enable itself at some point after a restart then all would seem fine to me.

That is not expected at all!!. For toggling fullscreen you need one of two conditions:

- it auto-toggles at launch, if non-fullscreen was saved
- it toggles when you press the menu entry "fullscreen"

I think you're talking about the "navigation bar dimming" that happens each time the application is paused/resumed. That's ok and a valid report but has nothing to do with "all contents fit on available size"

**Comment by calverb** [comment] 2019-06-21 09:16
Regarding my last point which you say was not expected.   I don't know now how I came to write this - I was probably getting mixed up with the auto toggle on launch.   Sorry for the confusion.

As far as I can see, providing fullscreen is unselected, then apart from the status page  "all contents fit on available size" if you do not include in "available size" the area taken by the navigation bar either in its dimmed or undimmed state.

P.S.  Regarding the "status page" problem - I think I have overcome this by changing the screen DPI from "auto" to "medium (160).   I thought I had tried this on an earlier version but perhaps not.   I'll see if the change of DPI has any other downside.

**Closed** 2019-07-06 15:09 UTC
Labels: Android, bug, firmware, low-hanging-fruit
