### ISSUE TITLE
[USBMS]: Settings get reset when connecting Android device to PC

### ISSUE THREAD

**Issue by outlogic** [koreader/koreader#9295] opened 2022-07-04 13:47 UTC
* KOReader version: 2022-06
* Device: Likebook Plus (Android 4.2.2)

#### Issue
Settings get reset when I connect to PC via a USB cable and then disconnect an Android device. Not sure whether this affects my device because of the old Android version or this is a more common problem. But when koreader is an active app and I connect my device to PC and then disconnect it, the koreader resets all the settings (disabling the external dictionary app that I use) and launches the guide like it's the first launch of the app. If koreader is in the background, no settings are affected.

#### Steps to reproduce
1. Launch koreader android app with any ebook. Leave the app active.
2. Connect the device to PC via a USB cable
3. Disconnect from PC

**Comment by pazos** [comment] 2022-07-04 14:05
> Settings get reset when I connect to PC via a USB cable and then disconnect an Android device.

All settings or just the settings that we're not saved in the session.

ie: tweak all the settings as you want, exit the program (or put it in the background, settings will be flushed in both ways). Open the program again and try to reproduce. Do all the settings get wiped? (like language, home dir, ...)

If that doesn't happen and you lost only the settings that are not flushed when you connect to PC I'm afraid there's no easy way to solve it.

The program should save settings when it is paused or exited but if a crash happens all non flushed settings get lost. That happens on all platforms. In the case of android your device vendor might decide to kill the app during MTP sessions.

**Comment by outlogic** [comment] 2022-07-04 14:20
I tried to tweak several settings as you suggested (chose an external dictionary, turned on the Night mode,...) and then rebooted the device. Then launched koreader and connected the device to my PC. If I disconnect from PC within a couple of seconds, the settings are OK. When I see the message that the USB storage mode is on and then disconnect, then I get all the settings wiped out and get the Quick Start Guide.

If I connect to the PC with koreader active, then disable the USB Storage on the device, change the settings in korreader and then disconnect from PC, then all the settings are preserved.

**Comment by pazos** [comment] 2022-07-04 15:13
Wait.

> When I see the message that the **USB storage mode** ...

USB Storage mode is deprecated since Gingerbread (android 2.3) and currently **very**, **very**, **very** unsupported. The behaviour you see is expected and cannot be fixed.

We currently require android 4.0 and expect all android devices to use MTP. Please close KOReader to connect to your computer. There's no way to prevent data loss.

**Comment by pazos** [comment] 2022-07-05 09:05
I'm going to close this ticket as there's nothing we can do.

> Please close KOReader to connect to your computer. There's no way to prevent data loss.

Even with KO in the background you might have issues, so the recommendation still stands.

**Closed by pazos** 2022-07-05 09:05 UTC
Labels: Android, firmware, can't fix
