### ISSUE TITLE
Appimage crash

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#4107] opened 2018-07-25 16:58 UTC
Trying to load a pdf file.

* KOReader version:
koreader-appimage-x86_64-linux-gnu-v2015.11-1735-g14e7730_2018-06-02.AppImage

* Device:
Debian x64

#### Issue
```
 [*] Version: v2015.11-1735-g14e7730_2018-06-02

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
07/25/18-11:56:12 WARN  ./ffi/SDL2_0.lua:386: /tmp/.mount_koreadGZIBDy/libs/libSDL2.so: undefined symbol: SDL_CreateRGBSurfaceWithFormatFrom
ffi.load: gtk-3
ffi.load: gtk-3
07/25/18-11:56:12 INFO  initializing for device SDL
07/25/18-11:56:12 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
07/25/18-11:56:12 INFO  Loading plugins from directory: plugins
07/25/18-11:56:12 INFO  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
07/25/18-11:56:12 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
07/25/18-11:56:12 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
07/25/18-11:56:12 INFO  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
07/25/18-11:56:12 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin perception_expander at plugins/perceptionexpander.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
./luajit: frontend/util.lua:176: attempt to index local 'text' (a nil value)
stack traceback:
	frontend/util.lua:176: in function 'utf8Reverse'
	frontend/apps/filemanager/filemanager.lua:52: in function 'truncatePath'
	frontend/apps/filemanager/filemanager.lua:162: in function 'onPathChanged'
	frontend/ui/widget/filechooser.lua:290: in function 'changeToPath'
	plugins/coverbrowser.koplugin/main.lua:415: in function 'refreshFileManagerInstance'
	plugins/coverbrowser.koplugin/main.lua:505: in function 'action'
	frontend/ui/uimanager.lua:597: in function '_checkTasks'
	frontend/ui/uimanager.lua:818: in function 'handleInput'
	frontend/ui/uimanager.lua:904: in function 'run'
	./reader.lua:195: in main chunk
	[C]: at 0x00404fe0

```

**Comment by Frenzie** [comment] 2018-07-25 18:19
Is there any more info you could supply, perhaps with `-d` for debug mode? It probably wouldn't give anything useful, in which case the fastest way to potentially get some info would be to stick a `print(text)` here to see what's passed into the function.

https://github.com/koreader/koreader/blob/9e67c5a614121cf6e787f47eca4905f442d5915e/frontend/util.lua#L175-L178

I.e., like this:

```lua
function util.utf8Reverse(text)
print(text)
    text = text:gsub('[%z\1-\127\194-\244][\128-\191]*', function (c) return #c > 1 and c:reverse() end)
    return text:reverse()
end
```

Do you have any fancy folder names?

**Comment by poire-z** [comment] 2018-07-25 18:35
Same exception, so probably same bug as in #3861 then? (we discussed a few things, not sure what we ended up doing).

**Comment by Frenzie** [comment] 2018-07-25 18:44
I fixed that specific issue by making the AppImage start in `pwd` in absense of other options, which I figure to be a nicer user experience crash or no crash. But you're right that it didn't address the root cause as such. It should do something similar on the Lua side (or at least not crash).

**Comment by gerroon** [comment] 2018-07-25 23:21
Do you still need more info from me?

**Comment by Frenzie** [comment] 2018-07-26 04:42
You could confirm it's exactly the same issue by sharing your last path from the settings file and whether it exists. :)

**Comment by gerroon** [comment] 2018-07-26 14:19
Well It seems to create the .sdr folder but there is no sdr in it, this is for the crashing pdf files.

**Comment by gerroon** [comment] 2018-07-26 19:58
This is what I have as last dir, I obfuscated the names a bit but the format is equal.

["lastdir"] = "/media/BOOKS/Calibre/WRITER/BOOK (6474)",

**Comment by NiLuJe** [comment] 2018-07-26 20:42
If they're really long, how long, and on what filesystem is that? (some FS only actually support path elements of up to 255 bytes (I'm looking at you, FAT32)).

**Comment by gerroon** [comment] 2018-07-26 21:15
I am on Linux x64 Btrfs.

No theya re not deleted, I am not sure where you are tying to go with this? Why would the original file location should be moved or deleted? I am opening them in their original pdf location. It would be terrible if they are moved or deleted. Maybe I am not getting it?

**Comment by Frenzie** [comment] 2018-07-27 04:56
Well, that's why the issue asks to include steps to reproduce the issue. :-) What steps do you take to trigger the issue? And like I initially wrote, anything special about your folder or filenames? Permissions maybe?

Where I'm going with the moved or deleted is that that's what @poire-z is talking about. If you delete a folder in your filemanager and try to go there in our program it will crash with this exact error message.

**Comment by gerroon** [comment] 2018-07-27 15:22
See yourself , this is the only and exact step. 


As far as the folder stuff goes. I am in the folder and running the command below, no folder is deleted, files and folders in the settings exists etc.


/media/BOOKS/Calibre/Wheeler M. Thackston/A Millennium of Classical Persian Poetry (6376)$ koreader "A Millennium of Classical Persian Poetry - Wheeler M. Thackston.pdf" 
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 07/27/18-10:20:27
 [*] Version: v2015.11-1735-g14e7730_2018-06-02

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
07/27/18-10:20:28 WARN  ./ffi/SDL2_0.lua:386: /tmp/.mount_koreadEQoIp0/libs/libSDL2.so: undefined symbol: SDL_CreateRGBSurfaceWithFormatFrom
ffi.load: gtk-3
ffi.load: gtk-3
07/27/18-10:20:28 INFO  initializing for device SDL
07/27/18-10:20:28 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
07/27/18-10:20:28 INFO  Loading plugins from directory: plugins
07/27/18-10:20:28 INFO  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
07/27/18-10:20:28 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
07/27/18-10:20:28 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
07/27/18-10:20:28 INFO  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
07/27/18-10:20:28 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin perception_expander at plugins/perceptionexpander.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
07/27/18-10:20:28 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
./luajit: frontend/util.lua:176: attempt to index local 'text' (a nil value)
stack traceback:
	frontend/util.lua:176: in function 'utf8Reverse'
	frontend/apps/filemanager/filemanager.lua:52: in function 'truncatePath'
	frontend/apps/filemanager/filemanager.lua:162: in function 'onPathChanged'
	frontend/ui/widget/filechooser.lua:290: in function 'changeToPath'
	plugins/coverbrowser.koplugin/main.lua:415: in function 'refreshFileManagerInstance'
	plugins/coverbrowser.koplugin/main.lua:505: in function 'action'
	frontend/ui/uimanager.lua:597: in function '_checkTasks'
	frontend/ui/uimanager.lua:818: in function 'handleInput'
	frontend/ui/uimanager.lua:904: in function 'run'
	./reader.lua:195: in main chunk
	[C]: at 0x00404fe0

**Comment by gerroon** [comment] 2018-07-27 15:31
Yes, it works for some pdfs, not for others I cant tell the difference really.

**Comment by Frenzie** [comment] 2018-07-28 18:45
This shouldn't be fixed though, unfortunately.

**Comment by Frenzie** [comment] 2019-02-21 22:08
@gerroon Could you please see if it's still an issue with v2019.02?

**Comment by Frenzie** [comment] 2019-08-30 09:08
I'll close this issue. Please feel free to (re)open with more information if it's still an issue.

**Closed by Frenzie** 2019-08-30 09:08 UTC
Labels: AppImage, bug, need more info
