### ISSUE TITLE
FR: Tap to exit

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#3243] opened 2017-09-21 15:30 UTC
* KOReader version:
* Device:

#### Steps to reproduce
Recent bug fixes in ko reader is really commendable.I would really appreciate the developers.Is it possible to exit the ko reader simply by tapping a particular space on the display as it happens in case of turning the light on off by simlply tapping the bottom left of the screen ?

**Comment by Frenzie** [comment] 2017-09-21 15:46
Someone could always write a plugin to that effect if they wanted to, but I'm not sure if it'd get much traction. Note that you can also long-press exit instead of using the submenu. :-)

**Comment by chenxingqun** [comment] 2017-09-29 11:32
I remember that once you just need to tap twice to exit. But now you have to tap 3 times. It would be much convenient to customize the way to exit.

**Comment by Frenzie** [comment] 2017-09-29 11:47
Like I said you can hold on exit, which is what I usually do ;-), but note that you can also customize the menus as described here: https://github.com/koreader/koreader/pull/2601#issuecomment-283677041

**Comment by tigran123** [comment] 2017-09-30 10:52
Oh, wonderful --- can you @Frenzie please clarify what you mean by "hold"? Hold where? Accessing "Exit" via submenu is a bit inconvenient, so I would also be interested in learning about a shorter way to exit Koreader. Thanks. Also, I'll look at menu customization you suggested.

**Comment by tigran123** [comment] 2017-09-30 11:27
I tried the user customisation method, but it doesn't work --- all the removed entries appear in the first menu tab like this:

NEW: Reboot the device
NEW: OTA update
NEW: Power off
NEW: Restart KOReader
....

So, how to make this "NEW:" entries disappear? All I did was to copy frontend/ui/elements/reader_menu_order.lua to settings/reader_menu_order.lua and deleted the lines I didn't want to appear in the rightmost menu tab. They disappeared from there and re-appeared in the first tab prefixed with "NEW:".

Then I tried to explicitly disable those entries like this:

```
    ["KOMenu:disabled"] = {
        "ota_update", --[[ if Device:isKindle() or Device:isKobo() or
                           Device:isPocketBook() or Device:isAndroid() ]]--
        "restart_koreader",
        "poweroff", -- if Device:isKobo()
        "reboot",   -- if Device:isKobo()
    }
```
That was inside the `order` variable which is returned. This also didn't work. So, how do we disable those  entries to make space for the most important entry --- Exit?

**Comment by tigran123** [comment] 2017-09-30 11:43
Actually, there is more stuff here going on here, namely: I edited only the `settings/reader_menu_order.lua` but the "NEW:" entries appeared also in the filemaneger. Ah, presumably because they are mentioned in `frontend/ui/elements/filemanager_menu_order` as well. I think this is very counter-intuitive --- the orphan menu entries shouldn't re-appear anywhere, i.e. there should be no "NEW:" elements anywhere at all. If the user removed an entry, then it should be gone, full stop.

**Comment by Frenzie** [comment] 2017-09-30 20:21
Hold on exit. I'm not really sure how else to explain it. :-P (Okay, that's not entirely true. But holding on exit _in_ the exit submenu wouldn't make much sense as an exit shortcut. ;-))

![screenshot_2017-09-30_21-54-04](https://user-images.githubusercontent.com/202757/31048972-f9c0df8e-a629-11e7-8033-637496dd1a5a.png)

> Ah, presumably because they are mentioned in frontend/ui/elements/filemanager_menu_order as well.

No, the menus are completely independent.

> If the user removed an entry, then it should be gone, full stop.

That could be added as an option, but there was a consensus that it's better to be notified of new features and to have to explicitly disable them than to be left out in the dust. But yes, this is currently a hidden power user feature.

> But in any case, the intended ["KOMenu:disabled"] functionality does not seem to work.

It works exactly as it should for me. Could you share your full custom reader_menu_order?

**Comment by tigran123** [comment] 2017-10-01 08:58
Thank you. Here is my entire `settings/reader_menu_order.lua` file. Please let me know what I have done wrong.

```
local order = {
    ["KOMenu:menu_buttons"] = {
        "navi",
        "typeset",
        "setting",
        "tools",
        "search",
        "filemanager",
        "main",
    },
    navi = {
        "table_of_contents",
        "bookmarks",
        "go_to",
        "skim_to",
        "follow_links",
    },
    typeset = {
        "page_overlap",
        "switch_zoom_mode",
        "set_render_style",
        "highlight_options",
        "floating_punctuation",
        "change_font",
        "hyphenation",
        "speed_reading_module_perception_expander",
    },
    setting = {
        "read_from_right_to_left",
        -- common settings
        -- those that don't exist will simply be skipped during menu gen
        "frontlight", -- if Device:hasFrontlight()
        "night_mode",
        "network",
        "screen",
        "screensaver",
        "save_document",
        "language",
        "time",
        "djvu_render_mode",
        "status_bar",
    },
    tools = {
        "read_timer",
        "statistics",
        "progress_sync",
        "zsync",
        "news_downloader",
        "----------------------------",
        "more_plugins",
    },
    more_plugins = {
        "auto_frontlight",
        "frontlight_gesture_controller",
        "battery_statistics",
        "synchronize_time",
        "keep_alive",
        "terminal",
        "storage_stat",
    },
    search = {
        "dictionary_lookup",
        "disable_fuzzy_search",
        "----------------------------",
        "wikipedia_lookup",
        "----------------------------",
        "goodreads",
        "----------------------------",
        "fulltext_search",
    },
    filemanager = {},
    main = {
        "history",
        "book_status",
        "book_info",
        "version",
        "help",
        "system_statistics",
        "exit",
    },
    help = {
        "quickstart_guide",
        "----------------------------",
        "report_bug",
        "----------------------------",
        "about",
    },
    ["KOMenu:disabled"] = {
        "evernote",
        "calibre_wireless_connection",
        "ota_update", --[[ if Device:isKindle() or Device:isKobo() or
                           Device:isPocketBook() or Device:isAndroid() ]]--
        "restart_koreader",
        "poweroff", -- if Device:isKobo()
        "reboot",   -- if Device:isKobo()
    },
}

return order
```

**Comment by Frenzie** [comment] 2017-10-01 09:25
I'd advise you to only override those specific items you wish to override (unless you wish to completely overhaul the menu). It really complicates things otherwise imo. :-)

You stumbled across a scenario I probably didn't anticipate or test sufficiently (but like I said, this is a service to power users that was an easy side effect of revamping the menu; more polish is desirable in the future). If I understand your intent correctly it should be something like this:

```lua
local order = {
    tools = {
        "read_timer",
        "statistics",
        "progress_sync",
        "zsync",
        "news_downloader",
        "----------------------------",
        "more_plugins",
    },
    search = {
        "dictionary_lookup",
        "disable_fuzzy_search",
        "----------------------------",
        "wikipedia_lookup",
        "----------------------------",
        "goodreads",
        "----------------------------",
        "fulltext_search",
    },
    main = {
        "history",
        "book_status",
        "book_info",
        "version",
        "help",
        "system_statistics",
        "exit", -- doesn't show up if you don't override exit_menu
    },
    -- Issue of sorts: the menu needs to be overridden to nothing to make
    -- subitems show up elsewhere or the entire thing is disabled.
    --
    -- However, I'm not sure if there's an immediate obvious solution because
    -- I suspect you wouldn't want to have to disable *all* subitems for *all*
    -- disabled submenus.
    exit_menu = {},
    ["KOMenu:disabled"] = {
        "evernote",
        "calibre_wireless_connection",
        "ota_update",
        "exit_menu",
        "wikipedia_settings",
        "dictionary_settings",
    },
}

return order
```

**Comment by tigran123** [comment] 2017-10-01 09:54
I tried the above, but it still doesn't work, i.e. I still get the "NEW:" entries appended to the first tab.

Btw, in the original `reader_menu_order.lua` there was nothing about `exit_menu`, so there was no way for me to guess that I need to set `exit_menu = {}` and also add `exit_menu` (rather than `exit`) to the disabled list. So, the existing scheme is very counter-intuitive. However, before criticising it, let's get it working first. My current `settings/reader_menu_order.lua` is identical to what you show above and it still doesn't work.

**Comment by tigran123** [comment] 2017-10-01 10:00
I forgot to mention that the version of Koreader I am running is is `v2015.11-1152-gabaa699`, i.e. the latest nightly release you have made this year.

**Comment by Frenzie** [comment] 2017-10-01 10:12
In that version there is no exit menu yet. I suppose I could just put a new nightly on the GH release page with broken Android brightness since overall it would still fix a whole bunch of stuff.

**Comment by tigran123** [comment] 2017-10-01 10:13
Also, you said that filemanager menu and reader menu are completely independent, but then why do I get the two entries "NEW: Power off" and "NEW: Reboot the device" in the filemanager menu now?

**Comment by tigran123** [comment] 2017-10-01 10:14
Yes, the Android version does not work anyway (i.e. it crashes on start on any Android version I tried).

**Comment by Frenzie** [comment] 2017-10-01 10:16
If you have an Android version that worked prior to April it'll be fixed now. If you have one that doesn't then it'll probably make no difference. But compared to prior to April there's a frontlight regression on Android.

In any case, you can just OTA update within the program or download manually from e.g. http://build.koreader.rocks/download/nightly/v2015.11-1270-g180f575/

**Comment by tigran123** [comment] 2017-10-01 10:17
Thank you, I'll do it manually. (The "OTA" thing I explicitly disable --- my koreader.sh script is only 3-4 lines of code --- I always remove all that nickel/shmickel junk from there :)

**Comment by Frenzie** [comment] 2017-10-01 10:19
> Also, you said that filemanager menu and reader menu are completely independent, but then why do I get the two entries "NEW: Power off" and "NEW: Reboot the device" in the filemanager menu now?

I'm not seeing that. You could've hit upon a bug, or it could just be something in your custom filemanager menu.

**Comment by tigran123** [comment] 2017-10-01 10:20
I don't have any custom filemanager menu, only the reader menu.

Anyway, I'll try the 1270 release right now and will let you know if it works.

**Comment by tigran123** [comment] 2017-10-01 12:08
Thank you, yes, in 1270 the custom `settings/read_menu_order.lua` works fine. And the custom `settings/filemanager_menu_order.lua` works fine as well.

So, now I will just have to re-test the cloud storage/WiFi stuff (with my fix to not check for isOnline() in cloudstorage.lua) to make sure it still works in 1270 and I will be happy....

**Comment by Frenzie** [comment] 2019-08-29 17:47
Implemented by <https://github.com/koreader/koreader/pull/5202>, available for various corners and multiswipes through the gesture manager.

**Closed by Frenzie** 2019-08-29 17:47 UTC
Labels: UX
