### ISSUE TITLE
Koreader does not work on Samsung Galaxy SIII Neo

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#1904] opened 2016-03-18 21:05 UTC
- KOReader version:
  koreader-stable-v2015.11
- Device:
  Samsung Galaxy SIII Neo GT-I9301I Android 4.4.2 firmware I9301IXXUAOD2
#### Issue

black screen on start
#### Steps to reproduce

Download and install stable .apk, then start koreader. Black screen appears, no reaction to touches or buttons.

**Comment by houqp** [comment] 2016-03-18 21:27
Likely a duplicate of https://github.com/koreader/koreader/issues/1782#issuecomment-198535990.

**Comment by Frenzie** [comment] 2017-10-09 11:35
@ilyats Is this still an issue?

**Comment by ilyats** [comment] 2017-10-12 00:34
@Frenzie I don't know, I don't have that phone anymore

**Comment by Frenzie** [comment] 2017-10-12 06:04
I'll close this then. :-)

**Closed by Frenzie** 2017-10-12 06:04 UTC
Labels: Android, bug
