### ISSUE TITLE
2023.04 crashing on android (Fdroid build 05/05/2023)

### ISSUE THREAD

**Issue by rogalian** [koreader/koreader#10396] opened 2023-05-06 06:03 UTC
LineageOS 20 on a POCO X3 NFC

The 02/05/2023 build works fine, latest build just dies on startup

--------- beginning of main
05-06 06:58:14.464 D/CompatibilityChangeReporter(26980): Compat change id reported: 171979766; UID 10007; state: DISABLED
05-06 06:58:14.480 V/GraphicsEnvironment(26980): ANGLE Developer option for 'org.koreader.launcher.fdroid' set to: 'default'
05-06 06:58:14.481 V/GraphicsEnvironment(26980): ANGLE GameManagerService for org.koreader.launcher.fdroid: false
05-06 06:58:14.481 V/GraphicsEnvironment(26980): Neither updatable production driver nor prerelease driver is supported.
05-06 06:58:14.483 D/NetworkSecurityConfig(26980): No Network Security Config specified, using platform default
05-06 06:58:14.483 D/NetworkSecurityConfig(26980): No Network Security Config specified, using platform default
05-06 06:58:14.484 I/MultiDex(26980): VM with version 2.1.0 has multidex support
05-06 06:58:14.484 I/MultiDex(26980): Installing application
05-06 06:58:14.484 I/MultiDex(26980): VM has multidex support, MultiDex support library is disabled.
05-06 06:58:14.500 W/launcher.fdroid(26980): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
05-06 06:58:14.500 W/launcher.fdroid(26980): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
05-06 06:58:14.500 W/launcher.fdroid(26980): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
05-06 06:58:14.514 D/CompatibilityChangeReporter(26980): Compat change id reported: 210923482; UID 10007; state: DISABLED
05-06 06:58:14.514 D/CompatibilityChangeReporter(26980): Compat change id reported: 37756858; UID 10007; state: ENABLED
05-06 06:58:14.516 D/CompatibilityChangeReporter(26980): Compat change id reported: 171228096; UID 10007; state: ENABLED
05-06 06:58:14.553 I/AdrenoGLES-0(26980): QUALCOMM build                   : 820d4a4028, I5580630f49
05-06 06:58:14.553 I/AdrenoGLES-0(26980): Build Date                       : 11/04/21
05-06 06:58:14.553 I/AdrenoGLES-0(26980): OpenGL ES Shader Compiler Version: EV031.32.02.16
05-06 06:58:14.553 I/AdrenoGLES-0(26980): Local Branch                     : 
05-06 06:58:14.553 I/AdrenoGLES-0(26980): Remote Branch                    : 
05-06 06:58:14.553 I/AdrenoGLES-0(26980): Remote Branch                    : 
05-06 06:58:14.553 I/AdrenoGLES-0(26980): Reconstruct Branch               : 
05-06 06:58:14.553 I/AdrenoGLES-0(26980): Build Config                     : S P 10.0.7 AArch64
05-06 06:58:14.553 I/AdrenoGLES-0(26980): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
05-06 06:58:14.559 I/AdrenoGLES-0(26980): PFP: 0x016ee190, ME: 0x00000000
05-06 06:58:14.574 E/OpenGLRenderer(26980): Unable to match the desired swap behavior.
05-06 06:58:14.580 I/Gralloc4(26980): Adding additional valid usage bits: 0x8202000
05-06 06:58:14.599 W/Parcel  (26980): Expecting binder but got null!
05-06 06:58:32.811 W/launcher.fdroid(26980): Cleared Reference was only reachable from finalizer (only reported once)

**Comment by pazos** [comment] 2023-05-06 12:16
Duplicate of #10395

Lets move conversation there

**Closed by pazos** 2023-05-06 12:16 UTC
