### ISSUE TITLE
FR: More control over long lines of text in detailed lists in File Browser

### ISSUE THREAD

**Issue by mickeydeagle** [koreader/koreader#12590] opened 2024-10-03 23:42 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
This doesn't involve resolving difficulty with a task; it is a request for a visual enhancement. Currently, when viewing any of the "detailed list" modes in the File Browser, lines of text that are very long get automatically scaled down to fit the space. I assume at some point (although I have not tested this), the text overflows and is truncated with ellipsis (`…`). This is a robust solution and serves well to show a meaningful amount of information — even for long lines of text. However the tradeoff is that the list looks, in my opinion, a little shabby when the text is scaled to various sizes, depending on the length of each line. I would prefer to see more consistently sized text in my list views.

**Describe the solution you'd like**
I would like to see an option in "Mosaic and detailed list settings" to allow text to overflow and be truncated with ellipsis, and not try to be resized first. The option could be a checkbox labeled "Do not shrink text to fit" or something similar.

**Describe alternatives you've considered**
Aside from renaming long book titles and fiddling with the number of items per page, I don't think there's any workaround here.

**Additional context**
I have attached screenshots of the current display, and then my rough suggestion for implementation of my proposed solution. While I don't know the logic that goes into adjusting content to fit (or even all of the permutations of lines of information that can be shown), I would hope the solution simply avoids the scaling part and keeps the other layout logic more or less intact.

![detailed-list-current](https://github.com/user-attachments/assets/1fd67bd8-fbb8-4e44-8e2a-55970d9a45ac)
![detailed-list-proposed](https://github.com/user-attachments/assets/b1aeb313-009a-4953-a485-9de306d40609)

**Comment by benoit-pierre** [comment] 2024-10-03 23:51
Duplicate of #9094.

**Closed by benoit-pierre** 2024-10-03 23:51 UTC
Labels: enhancement
