### ISSUE TITLE
Translation crashes koreader on Android 4.4 x86

### ISSUE THREAD

**Issue by BorisNA** [koreader/koreader#7891] opened 2021-06-26 09:30 UTC
* KOReader version: 2021.06 
* Device: Android x86 4.4 tablet (Teclast X98 Air 3G)

#### Issue
Koreader crashes when trying to translate a word
Clean install, no previous koreader settings

#### Steps to reproduce
* Open a book
* Long tap on a word
* Select "pen" icon near the word in the dictionary lookup window
* Select "translate" 
* Crash

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/6719880/crash.log)

**Comment by mergen3107** [comment] 2021-06-26 14:19
I can confirm on
KOReader version: 2021.06
Device: Blackberry Priv (Android 6.0.1, no root)

Here are two crash logs from two attempts to translate:
In a fb2 book, long-press a single word, hit Translate - KOReader crashes.

Second time I tried to change input-output languages first. KOReader showed a crash window with a bomb icon and something about exception #439, or something (can't remember it).


<details>
  <summary>crash.log files</summary>

```
[crash_PRIV1.log](https://github.com/koreader/koreader/files/6720220/crash_PRIV1.log)
[crash_PRIV2.log](https://github.com/koreader/koreader/files/6720221/crash_PRIV2.log)
```
</details>

**Comment by Cellaris** [comment] 2021-06-26 17:49
On Tolino devices (I have really only tested it on the Tolino Vision 4 HD) the dictionary window opens, but does not show any results.

**Comment by pazos** [comment] 2021-06-26 20:30
@mergen3107: none of your crash.logs contain a crash. It could be an issue with your device. Please look at OP `crash.log` to see how a crash and the associated stacktrace looks like :)

@BorisNA: Thanks, I cannot reproduce here (unless you're trying to translate the entire book, in that case yep, the string to be translated is limited to 1MB, which is fairly big for plain text). Could you attach a test case? does it happen on every word?.

@Cellaris: that looks like a different issue with a different root cause. Anyways, pinging  @zwim as our chief Tolino contributor :).

**Comment by BorisNA** [comment] 2021-06-26 21:14
@pazos , yes it happens on every word, every book. For example, "Koreader quickstart guide".

And it cannot be the whole text, since the dictionary window opens Ok with the correct word in the heading.

**Comment by poire-z** [comment] 2021-06-26 21:27
Can reproduce on my Android 6 ARM phone:
- highlight a word => dict ok
- long-highlight same word > highlight dialog => Wikipedia: OK
- long-highlight same word > highlight dialog => Translate => your "uncaught exception in thread" screen (first time I see it :), with not much info, it ends with the clocksource line like all the above crash.log :/

**Comment by pazos** [comment] 2021-06-26 21:57
@poire-z @BorisNA: still cannot reproduce here :/

There's nothing android specific in the translate action until https://github.com/koreader/koreader/pull/7855. I guess you can reproduce it with the copy action/button.

**Comment by mergen3107** [comment] 2021-06-26 22:19
@pazos, it looks like similar behavior is observed when trying to Copy selected text. Something with clipboard then.
I have set up adb connection, can I help to track the issue somehow?

**Comment by poire-z** [comment] 2021-06-26 22:55
> I guess you can reproduce it with the copy action/button.

Indeed, same crash when long-highlight same word > highlight dialog => Copy.

Not much more info looking at logs via CatLog:
```
Timeline: Activity_launch_request id:orgkoreader.laucher time:31296668
ActivityManager: START u0 [flg=0x50804000 cmp=org.koreader.launcher/.CrashReportActibity...
art System.exit called, status: 1
AndroidRuntime: VM existing with result code 1, cleanup skipped.
```

**Comment by pazos** [comment] 2021-06-26 23:28
Yup, that makes more sense.

> Not much more info looking at logs via CatLog:

I'm afraid I designed the crash handler mostly to report errors within the lua VM. Those will get a stacktrace.  The other case I tested was throwing a `RuntimeException` from kotlin and that got a stacktrace too.

I guess we need to do a minor change to see what happens

```diff
 diff --git a/app/src/main/java/org/koreader/launcher/MainApp.kt b/app/src/main/java/org/koreader/launcher/MainApp.kt
index 1544688..9ddd5a0 100644
--- a/app/src/main/java/org/koreader/launcher/MainApp.kt
+++ b/app/src/main/java/org/koreader/launcher/MainApp.kt
@@ -101,8 +101,9 @@ class MainApp : MultiDexApplication() {
         app_storage_path = String.format("%s/%s", storage_path, name.lowercase())
         targetSdk = applicationContext.applicationInfo.targetSdkVersion

-        Thread.setDefaultUncaughtExceptionHandler { thread, _ ->
+        Thread.setDefaultUncaughtExceptionHandler { thread, e ->
             val msg = "Uncaught exception in thread #${thread.id} (${thread.name})"
+            e.printStackTrace()
             crashReport(applicationContext, msg)
             kotlin.system.exitProcess(1)
         }
```

> Please look at OP crash.log to see how a crash and the associated stacktrace looks like :)

It looks that the original stacktrace was caused by filling the Intent extras with more than 1MB. So competely unrelated, but needs a fix too :)

Exceptions caught by the DefaultUncaughtExceptionHandler that are not thrown by us are indeed silent. Print the stacktrace will point us in the right direction of what happens under the hood. Sadly I cannot repro here.

Please test this version: (uninstall->install first): https://www.dropbox.com/s/75stb9wnupw2ywv/ko-clip.apk?dl=0

It should crash the same way but should provide a stacktrace of what happens on thread11

**Comment by mergen3107** [comment] 2021-06-26 23:41
@pazos 
Here you are:
[crashlog4.txt](https://github.com/koreader/koreader/files/6720830/crashlog4.txt)

**Comment by mergen3107** [comment] 2021-06-27 02:59
This build also crashes when long pressing any text input field (dictionary lookup, fulltext search, text editor) with the `Unfortunately, KOReader has stopped` message. crash.log does not contain anything useful. Here is the adb logcat of last 500 lines:
[logcat3.txt](https://github.com/koreader/koreader/files/6720956/logcat3.txt)

**Comment by hius07** [comment] 2021-06-27 03:03
> crashes when long pressing any text input field

This should call the Clipboard dialog.
Also has been recently added https://github.com/koreader/koreader/pull/7855, copying the translation input to the clipboard.

**Comment by pazos** [comment] 2021-06-27 09:28
@mergen3107: this build should fix the issue copying text to the clipboard: https://www.dropbox.com/s/ecrtmveguswzrtk/ko-clip2.apk?dl=0

Please check that.

> This build also crashes when long pressing any text input field

Maybe the same workaround is needed for pasting text. It's not included in the build I attached.
t

**Comment by mergen3107** [comment] 2021-06-27 13:44
@pazos 
In this build all previous issues are gone! Translate works, text is copied and appropriate notification is shown. I can even paste into a text field via long tap - usual clipboard dialog appears. 
Should I test something else to make sure?

**Comment by BorisNA** [comment] 2021-06-27 15:02
@pazos , thanks for the build, but I believe it is the ARM package, since it refuses to launch on my x86 tablet.

**Comment by pazos** [comment] 2021-06-27 15:37
@BorisNA: It is the arm apk. Was meant to test. I will submit the changes soon :)

> In this build all previous issues are gone! Translate works, text is copied and appropriate notification is shown. I can even paste into a text field via long tap - usual clipboard dialog appears.
Should I test something else to make sure?

@mergen3107: that's a bit weird. The issues pasting text from the clipboard weren't fixed on that build. Just the copy to clipboard was changed. Please double check that pasting works. Extra points if you test the condition in https://github.com/koreader/koreader/issues/7865#issuecomment-864547414  :)

**Comment by mergen3107** [comment] 2021-06-27 15:58
@pazos 
Yes, I double checked - pasting works fine, but only if there was something in the clipboard (copied in the KOReader or outside). I also tried to paste  an asterisk, with and without quotation marks, as in the issue you mentioned - pastes fine. In the text editor as well.
I manually cleared the clipboard through Blackberry Keyboard, and when I tried to paste KOReader crashed with "Unfortunately, KOReader has stopped." and no bomb log window (as in the same #7865 I suppose).

**Comment by pazos** [comment] 2021-06-28 12:59
> I manually cleared the clipboard through Blackberry Keyboard, and when I tried to paste KOReader crashed with "Unfortunately, KOReader has stopped." and no bomb log window (as in the same #7865 I suppose).

It isn't the same case as in the original report there was *something* copied to clipboard that wasn't plain text and here it is an empty clipboard. It shouldn't crash, just paste an empty string.

Please check if you can reproduce the same crash (or any other crash in any other scenario) with this build: https://www.dropbox.com/s/8lac8rm4pxvpd3h/ko-clip3.apk?dl=0

**Comment by mergen3107** [comment] 2021-06-28 16:10
@pazos
It works! 
Paste works for empty and non-empty clipboard. Copy, Translate both work.

**Closed** 2021-06-30 04:54 UTC
Labels: Android
