### ISSUE TITLE
As a user, i should not have to edit input.lua file to have proper touchscreen on my Kobo Touch

### ISSUE THREAD

**Issue by michaelhaaf** [koreader/koreader#1666] opened 2015-10-06 00:36 UTC
I'm a new user of Koreader. Just today I installed the latest stable release (v2014.11) on the latest stable firmware (3.18.0) of my Kobo Touch N905C.

Forgive me if this issue is known, I could not find a similar issue by searching.

Upon install, following the instructions [here](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices) using "start menu", I was finding the Filemanager page of koreader unusable. None of my touches did anything, which I mistook for koreader crashing. Eventually I found the solution in [this forum post (see user tshering post #414)] (http://www.mobileread.mobi/forums/showthread.php?t=255978&page=42), which I'll paraphrase below

Change the code in koreader\frontend\ui\input.lua from
    
    -- For single-touch events (ABS.code).
    local ABS_X = 00
    local ABS_Y = 01

to
    
    -- For single-touch events (ABS.code).
    local ABS_X = 01
    local ABS_Y = 00

After this change I have been able to use the filemanager as normal.

The issue being, i should not have to edit input.lua to use the file manager properly upon install.

**Comment by KenMaltby** [comment] 2015-10-06 01:13
As I remember it this issue only appears on certain of the Kobo Touch model numbers, and it has not been easy finding a way to identify which exact model of the three "Touch" models that the device is, when you are looking for it by software. The koreader install software would have to know if the device was one of those affected by the problem and not one of the other "Touch" models.  

The MR thread you mention also seems to indicate that your taps/pokes on the touchscreen were all being returned as "long presses".  Was that corrected?

**Comment by michaelhaaf** [comment] 2015-10-06 01:19
Hi Ken, thanks for the response.

Yes, the issue of my taps/pokes being returned as long presses was corrected by making this switch.

I suppose we could record that I've had issue with the N905, and see what models others have had issues with?

Another fix could be to add a button saying "having issues tapping?" upon install, then the user could long press to activate it. The button could then make the change to input.lua for the user.

**Comment by chrox** [comment] 2015-10-06 01:26
Yes this issue will be addressed in the next stable release. And at the first launch of koreader kobo touch users will see a "tap on me" indication on the lower left of the screen, once the user touch the screen koreader would know if the coordinate x is smaller than y, if not it should be swapped. And the swapped imput flag will be written to global config file.

**Comment by chrox** [comment] 2015-10-06 01:29
Since this issue is a duplicate of #1608, I will close this one in favor of #1608. And you can keep an eye on the progress of this fix here https://github.com/koreader/koreader/milestones/v2015.10-stable

**Comment by michaelhaaf** [comment] 2015-10-06 01:29
Great, thanks chrox. sorry for not picking up on the duplicate.

**Closed** 2015-10-06 01:29 UTC
