### ISSUE TITLE
FR: Multi abi for F-Droid build

### ISSUE THREAD

**Issue by linsui** [koreader/koreader#9687] opened 2022-10-26 04:33 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
Since arm 64 is supported now, I'd like to have it in F-Droid build. Currently we only have arm32 build.

**Describe the solution you'd like**
We can build a universal apk but it will be very large. Now we can auto update multi abi apks so we should build 2 or 4 abis for every version. We need a version code scheme for every abi.

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by pazos** [comment] 2022-10-26 07:50
A prefix with a different number per abi should do the job.

For instance:

1 arm
2 arm64
3 x86
4 x86_64

@linsui: would be possible to keep https://ota.koreader.rocks/koreader-android-fdroid-latest as is (single version code without prefix)?  then the recipe can compute the right version code for a given abi prepending the prefix

**Comment by linsui** [comment] 2022-10-26 08:09
> A prefix with a different number per abi should do the job.

F-Droid keeps the apks with the highest version code. With prefix only the x86-64 apks are kept in the main repo and others are moved to the archive repo. We need to make all abis of the new version have higher version code than old version.

> would be possible to keep https://ota.koreader.rocks/koreader-android-fdroid-latest as is (single version code without prefix)?

Yes, this is how our auto update work.

**Comment by pazos** [comment] 2022-10-26 08:22
current version code is the number of commits in this repo. Adding a single digit prefix makes all the new versions higher than current version.

For instance, if 2022.10 was released with this scheme version codes would be

19317
29317
39317
49317

this is the prefix + the number of commits (9317)

Is that ok or am I misssing something?

**Comment by linsui** [comment] 2022-10-26 08:29
After we have 4 versions the version codes will become something like

```
19317 19320 19326 19330
29317 29320 29326 29330
39317 39320 39326 39330
49317 49320 49326 49330
```

Since we have 4 abis we'll keep 12 apks with the highest version code and `19317 19320 19326 19330` will be moved to archive repo so there is no armv7 abis in the main repo. Finally only x86-64 apks are kept in the main repo.

**Comment by linsui** [comment] 2022-10-26 08:30
Basically we need something like suffix.

**Comment by pazos** [comment] 2022-10-26 09:09
Great!

I will take care of it as soon as my internet provider fixes its stuff. I'm on 2G since the sunday :/

**Comment by Frenzie** [comment] 2022-10-26 09:14
Mine should be fixed on Friday, fingers crossed. Don't tell my wife this is the speed where I'm working today though. :-P

![image](https://user-images.githubusercontent.com/202757/197986386-aa36aa05-4787-44f1-88c6-f5f2c2da6919.png)

**Comment by pazos** [comment] 2022-10-26 10:36
Well, that's 50x the speed of my connection when it works

Now I'm on the 80-200KB range :(

**Comment by Frenzie** [comment] 2022-10-26 10:44
Ouch, that's not great. My home connection will be 150/50, assuming they'll actually fix it for real this time. >_> On 4g my speed is generally at least 50 Mbit but the problem is the lack of volume.

**Comment by Frenzie** [comment] 2022-10-27 19:42
Annnd my internet won't be fixed this Friday yet. You can't make this up. x.x

I think I might also be able to continue browsing at 2g speeds since I'm out of all 12 GB of data now. Argh!

**Comment by pazos** [comment] 2022-11-02 20:59
![2022-11-02_21-57](https://user-images.githubusercontent.com/975883/199601327-c3eb37a3-a88d-439a-be34-101d12e6b7be.png)

:cry: :cry: :cry: :cry: :cry: :cry: :cry:

**Comment by Frenzie** [comment] 2022-11-03 07:54
For a second there I was going to say nice, same here. :-(

![image](https://user-images.githubusercontent.com/202757/199670655-4fe138b2-74a8-43d9-a646-cbe9b6af0223.png)

**Comment by pazos** [comment] 2022-11-20 22:18
Got my internet fixed! And fiber!

Sadly I won't be able to deliver for 2022.11, so I'm going to move the milestone :p

**Comment by Frenzie** [comment] 2022-11-21 09:46
Hooray!

**Comment by pazos** [comment] 2022-12-05 18:27
@linsui: I'm doing the changes now.

Here's the diff

```diff
diff --git a/app/build.gradle b/app/build.gradle
diff --git a/app/build.gradle b/app/build.gradle
index 94a4b6e..638c749 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -5,9 +5,10 @@ android {
     ndkPath ndkCustomPath
     compileSdkVersion rootProject.ext.compileSdk

+    def baseVersionCode = versCode as Integer
+
     defaultConfig {
         applicationId "org.koreader.launcher"
-        versionCode versCode as Integer
         versionName versName
         minSdkVersion rootProject.ext.minSdk
         targetSdkVersion rootProject.ext.targetSdk
@@ -57,21 +58,25 @@ android {

     flavorDimensions 'ABI', 'CHANNEL'
     productFlavors {
-        x86 {
-            ndk { abiFilters "x86" }
-            dimension = 'ABI'
-        }
-        x86_64 {
-            ndk { abiFilters "x86_64" }
-            dimension = 'ABI'
-        }
         arm {
             ndk { abiFilters "armeabi-v7a" }
             dimension = 'ABI'
+            versionCode = baseVersionCode * 10 + 1
         }
         arm64 {
             ndk { abiFilters "arm64-v8a" }
             dimension = 'ABI'
+            versionCode = baseVersionCode * 10 + 2
+        }
+        x86 {
+            ndk { abiFilters "x86" }
+            dimension = 'ABI'
+            versionCode = baseVersionCode * 10 + 3
+        }
+        x86_64 {
+            ndk { abiFilters "x86_64" }
+            dimension = 'ABI'
+            versionCode = baseVersionCode * 10 + 4
         }

         fdroid {
```

As you can see we cannot use splits directly. We use productFlavors paired with abiFilters and pass a the `ANDROID_ARCH` as a build time environment variable.

So, it is expected that the script that runs on FDroid's build server executes `ANDROID_ARCH=x ./kodev release android` once per arch.

The `x86_64` ABI isn't working yet, so for the time being the script should call

`./kodev release android`   # arm
`ANDROID_ARCH=arm64 ./kodev release android` #arm64
`ANDROID_ARCH=x86 ./kodev release android` #x86

Currently the script we use to build LuaJIT as a shared library fails if we try to build for another arch without cleaning previous arch first, but hopefully that can be fixed and you won't need to issue extra commands (pinging @NiLuJe about this particular point)

Let me know if something like that  can be integrated in Fdroid without extra steps on our end :)

**Comment by NiLuJe** [comment] 2022-12-05 18:30
> Currently the script we use to build LuaJIT as a shared library fails if we try to build for another arch without cleaning previous arch first

The android-luajit-launcher one, or base?

**Comment by linsui** [comment] 2022-12-05 18:40
This is what we need, thanks! F-Droid doesn't support abi split so we need to build them one by one anyway and for every build we create a new VM.

**Comment by pazos** [comment] 2022-12-05 19:28
@NiLuJe: the android-luajit-launcher one

@linsui: do you create a new VM for each APK within the same version or for each new version?. If the former then we're good as is, as no leftovers of previous archs are present. If the later then we need to address the issue here.

**Closed** 2023-01-22 18:52 UTC
Labels: enhancement, Android

**Comment by pazos** [comment] 2023-02-01 20:32
@linsui: I see the new version [got picked by F-Droid checkupdates](https://gitlab.com/fdroid/fdroiddata/-/commit/e89815ffcaa48932e3bba115199e5c9061b92774). Remember to tweak it as required and comment the x86_64 build until it is fixed here :)

**Comment by linsui** [comment] 2023-02-02 04:59
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12534 Updated, thanks!
