### ISSUE TITLE
Invert screen orientation notification does not disappear automatically 

### ISSUE THREAD

**Issue by jjrrw174** [koreader/koreader#10836] opened 2023-08-22 01:34 UTC
* KOReader version: Latest
* Device: PocketBook Era (PB700)

#### Issue
When using the geasture for invert screen orientation, the "Screen roated 180°" notification doesn't seem to disappear on its own like others. You must use an input to remove it.

#### Steps to reproduce
Bind the invert screen orientation gesture and use it

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment] 2023-08-22 01:53
Probably a duplicate of the PB + autostandby + <insert random UI element here> issues.

**Comment by jjrrw174** [comment] 2023-09-12 14:18
Since this is a known issue. Is there a way to disable notifications?

**Comment by NiLuJe** [comment] 2023-09-12 15:59
Yes. [Gear] > Screen > Notifications

**Comment by pazos** [comment] 2024-04-07 20:37
Closing in favor of #9493

**Closed by pazos** 2024-04-07 20:37 UTC
Labels: bug, PocketBook, firmware
