### ISSUE TITLE
Cannot restore progress some of the pages in crengine

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2015] opened 2016-05-09 07:36 UTC
Reported by @Frenzie at https://github.com/koreader/koreader/issues/2006.

> So I was looking at this and I noticed something odd.
> 
> I tested with this EPUB
> http://www.gutenberg.org/ebooks/17489
> 
> Close on page 2 → opens on page 1
> Close on page 12 → opens on page 1
> Close on page 13 → opens on page 13
> Close on page 19 → opens on page 1
> 
> The problem seems to be in the last_xpointer setting.
> 
> For page 12:
> 
> ```
> ["last_xpointer"] = "/body/DocFragment[1]/body.0",
> […]
> ["percent_finished"] = 0.012257405515832,
> ```
> 
> For page 13:
> 
> ```
> ["last_xpointer"] = "/body/DocFragment[1]/body/p[3]/text().678",
> […]
> ["percent_finished"] = 0.013278855975485,
> ```
> 
> So I suspect the problem might be in crengine. For instance, it might've been introduced in the suspiciously relevant looking koreader/crengine@159bcb3. However, I won't bother trying to understand the code over there since obviously @houqp already should.
> 
> That's it for now. =P

**Comment by houqp** [comment] 2016-05-09 07:36
Multiple pages are reporting its xpointer as "/body/DocFragment[1]/body.0"

**Comment by houqp** [comment] 2016-05-09 08:56
After some bisects, I found the bug is introduced in https://github.com/koreader/crengine/commit/d232091ad6f36c76a17e74858a97fcc4261084c1. @frankyifei thoughts? I will take a closer look this week too.

**Comment by frankyifei** [comment] 2016-05-09 15:05
I did not touch anything that will change xpointer. the patch did change something related to page split.

**Comment by frankyifei** [comment] 2016-05-09 15:19
Looks like it can not restore a position if that position is at a compulsory page-break.

**Comment by djalma2k** [comment] 2016-05-09 18:26
I was going to open a ticket regarding a similar problem (related with this?):
With versions ~ 37x or 38x, in some books (epub) appears the "book status" page when you turn the initial pages (for example: page 4 to 5, in a book with ~2000 pages). Not only appears in the end of the book but it randomly appears in this pages ( 4 or 20, etc) also.

**Comment by Frenzie** [comment] 2016-05-09 19:41
I think that should be fixed already?

**Comment by houqp** [comment] 2016-05-09 20:21
@djalma2k your issue is not related to this one and should have been fixed. If you are still experiencing this in the latest version, please open an issue for it, I will take a look.

**Comment by djalma2k** [comment] 2016-05-09 20:21
Well, if you are meaning #1831, yes, it was fixed but this one I related It's a new problem, at least to me :P :/

**Comment by houqp** [comment] 2016-05-09 20:26
@frankyifei that's what confuses me too. The commit doesn't seem to touch the xpointer logic at all. https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerrolling.lua#L382 returns the same xpointer for multiple pages.

**Comment by frankyifei** [comment] 2016-05-10 01:17
I think the reason is that I added a line for margin and padding to keep the style and the line for this purpose can not be used to create xpointer. I will do more test to confirm. 
The first line of a page's top margin and padding were ignored in CRE.

**Comment by frankyifei** [comment] 2016-05-10 01:47
I think I found reason for this.
getBookmark() will call ldomNode::elementFromPoint( lvPoint pt, int direction ) to find the node at the split point, but the point passed is the start point of the page, which can be in margin or padding or border of that first node of the page. RenderRectAccessor does not consider top margin, padding or border. 
So it will always return the rootnode of that document if it can not find a text node at the given point.

**Comment by frankyifei** [comment] 2016-05-10 02:46
Edit epub.css and set margins to 0 for h1,h2,h3 should fix this temporarily. 
The page splitting mechanism is so hard to deal with. It was designed to handle text only.

**Comment by robert00s** [comment] 2017-10-07 16:30
@Frenzie 
Is that problem still exist? I cannot reproduce it.

**Comment by Frenzie** [comment] 2017-10-08 11:14
@robert00s Correct. Looks like @frankyifei fixed it in https://github.com/koreader/crengine/commit/ce60a900a5031a88dda80118d16f3083422d8db4 but forgot to close this issue.

PS A plain number only auto-references within repos. Across repos you need to use the full URL like `https://github.com/koreader/crengine/pull/49` https://github.com/koreader/crengine/pull/49

**Closed by Frenzie** 2017-10-08 11:14 UTC
Labels: bug
