### ISSUE TITLE
Turn off device asks activate wifi

### ISSUE THREAD

**Issue by doctoralvarez** [koreader/koreader#10790] opened 2023-08-06 20:30 UTC
* KOReader version: 20230601
* Device: Kindle Oasis 2

#### Issue
Turning to sleep my device shows alert/box asking to activate Wi-Fi, and it keeps the alert on my screen (above my screensaver/cover of my book) and turning it on my device it appears same box for activate wifi, and I select cancel, and keeps happening every time I turn screen off/sleep my kindle oasis (very annoying)

#### Steps to reproduce
Using power button (turn off / sleep device)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment] 2023-08-06 20:57
This ought to be fixed in current nightlies ;).

**Comment by zenminimalist** [comment] 2023-08-10 10:22
@NiLuJe I have the same issue. It started to happened with the latest update. Before that didn't have any issues' life this. And haven't changed anything in the setting or setup either. Keeps asking me "Do you want to connect to Wifi?" even though it's off. And then remains unresponsive for quite a bit.

"Do you want to connect to Wifi?" No! "Do you want to connect to Wifi?" "Do you want to connect to Wifi?" No, leave me alone! 

Here's my crash.log (Just don't sell it on Amazon as a Triller)
[crash.log](https://github.com/koreader/koreader/files/12311684/crash.log)

**Comment by NiLuJe** [comment] 2023-08-10 21:00
> This ought to be fixed in current nightlies ;).

Is still true ;).

**Comment by zenminimalist** [comment] 2023-08-10 21:21
OK, I'll have try that. So I assume for my device (currently Kindle PW Signature Edition ) it would be this [here](https://build.koreader.rocks/download/nightly/v2023.06.1-62-gac143ca9d_2023-08-09/koreader-kindlepw2-v2023.06.1-62-gac143ca9d_2023-08-09.zip)?

If so, do I just pull the files over and overwrite, or is it a different installation method for nightlies?

**Comment by NiLuJe** [comment] 2023-08-10 21:22
Yup. Or switching to the Dev channel and doing an in-app OTA update.

**Comment by zenminimalist** [comment] 2023-08-10 21:28
> Or switching to the Dev channel and doing an in-app OTA update.

Didn't think about that : ) 
And do I update the other things such as KUAL, MR Package Installer with the normal instruction posted on Mobiread?

**Comment by NiLuJe** [comment] 2023-08-10 21:28
Nope.

**Comment by zenminimalist** [comment] 2023-08-10 21:40
Ok, can confirm that seems to have fixed the issue with the 10th Aug. version. You guys rock - not just KOReader!

**Comment by zenminimalist** [comment] 2023-08-30 13:22
The nightly build fixed my issue right away. Not sure what your issue is related to, TBH.

**Comment by NiLuJe** [comment] 2023-08-30 13:28
Fixed via #10697

**Closed by NiLuJe** 2023-08-30 13:28 UTC
Labels: bug, out-of-date

**Comment by dlgoodr** [comment] 2023-08-30 13:58
> Note that, the best I can do is just ignore the wifi state and push through, so, if wifi's not up, you'll get a block for 2s instead, which is not necessarily much better. Prompt is a no-go, for reasons described in the PR.

I don't understand lua, sorry, but it seems like you're checking for a complete network stack - the query to msftncsi.com - but is there way to get state of the wifi adapter? If it's up and looking for a network, wait some time or for the connection to complete. I think the normal case for a device would be reconnecting to a known network, not needing to connect to a new SSID.

**Comment by NiLuJe** [comment] 2023-08-30 14:25
That's already what Android does.

The issue isn't in there, it's simply that Android is flagged as hasWifiToggle while that's not entirely true in the sense that we usually assume.
