### ISSUE TITLE
Can't login to Evernote on Kindle 

### ISSUE THREAD

**Issue by ollihd** [koreader/koreader#7247] opened 2021-02-05 21:11 UTC
* KOReader version: KOReader 2021.01.1 for Kindle
* Device: Kindle PW 4 (JB)

Issue: When trying to login to Evernote, the following error message appears: 

"An error occurred while logging in:
plugins/evernote.koplugin/
EvernoteOAuth.lua:332: OAuth
verifier not found"

Tried with two different Evernote accounts. One I have used forever and one fresh. Both with manual login (not Google login). Both without two-factor-authentication.

Steps to reproduce: trying to login to Evernote from the Koreader menu

**Comment by Frenzie** [comment] 2021-02-05 22:28
I'm afraid the answer is we'll probably drop it. See https://github.com/koreader/koreader/discussions/7215

**Comment by Galunid** [comment] 2021-02-06 08:20
Duplicate of https://github.com/koreader/koreader/issues/6281

**Closed by Galunid** 2021-02-06 08:20 UTC
Labels: Plugin, bug
