### ISSUE TITLE
statistics plugin failed to sync 

### ISSUE THREAD

**Issue by boypt** [koreader/koreader#10507] opened 2023-05-30 07:36 UTC
* KOReader version: 2023.05 "Azalea"
* Device: Poke4 Android

#### Issue

The Reading statistics failed to synchronize.

A dialog showing "Something went wrong when syncing, please check network ...". But the network condition is fine, if I delete the `statistics.sqlite3` file in the webdav folder and sync, the sync show OK, and I press the `Synchronize now` again , the same error occured.

#### Steps to reproduce

`Reading statistics` -> press `Synchronize now`

##### `crash.log` (if applicable)
```
05-30 15:22:22.190 E/KOReader(15296): failed to call event handler onSync common/lua-ljsqlite3/init.lua:60: ljsqlite3[misuse] not an error
05-30 15:22:22.190 E/KOReader(15296): stack traceback:
05-30 15:22:22.190 E/KOReader(15296): 	common/lua-ljsqlite3/init.lua:60: in function 'err'
05-30 15:22:22.190 E/KOReader(15296): 	common/lua-ljsqlite3/init.lua:236: in function 'E_conn'
05-30 15:22:22.190 E/KOReader(15296): 	common/lua-ljsqlite3/init.lua:607: in function '_step'
05-30 15:22:22.190 E/KOReader(15296): 	common/lua-ljsqlite3/init.lua:623: in function 'resultset'
05-30 15:22:22.190 E/KOReader(15296): 	common/lua-ljsqlite3/init.lua:388: in function 'exec'
05-30 15:22:22.190 E/KOReader(15296): 	plugins/statistics.koplugin/main.lua:3117: in function <plugins/statistics.koplugin/main.lua:2991>
05-30 15:22:22.190 E/KOReader(15296): 	[C]: in function 'pcall'
05-30 15:22:22.190 E/KOReader(15296): 	frontend/pluginloader.lua:32: in function <frontend/pluginloader.lua:31>
05-30 15:22:22.190 E/KOReader(15296): 	[C]: in function 'pcall'
05-30 15:22:22.190 E/KOReader(15296): 	frontend/apps/cloudstorage/syncservice.lua:162: in function 'sync'
05-30 15:22:22.190 E/KOReader(15296): 	plugins/statistics.koplugin/main.lua:2987: in function 'action'
05-30 15:22:22.190 E/KOReader(15296): 	frontend/ui/uimanager.lua:991: in function '_checkTasks'
05-30 15:22:22.190 E/KOReader(15296): 	frontend/ui/uimanager.lua:1437: in function 'handleInput'
05-30 15:22:22.190 E/KOReader(15296): 	frontend/ui/uimanager.lua:1557: in function 'run'
05-30 15:22:22.190 E/KOReader(15296): 	/data/user/0/org.koreader.launcher/files/reader.lua:319: in main chunk
05-30 15:22:22.190 E/KOReader(15296): 	[C]: in function 'dofile
```

**Comment by ptrm** [comment] 2023-05-30 14:49
Same occurs for me on Kobos and android on post #10498 builds. Maybe the added query causes issues

**Comment by Frenzie** [comment] 2023-05-30 16:26
Duplicate of https://github.com/koreader/koreader/pull/10503

**Closed as completed by Frenzie** 2023-05-30 16:26 UTC
Labels: bug, duplicate, Plugin

**Comment by ptrm** [comment] 2023-05-31 07:45
This error still appears after installing today's build with #10503. Not sure how I can get sqlote errors to display, tried removing the temp sqlite files from settings/ dir, without luck.

**Comment by Frenzie** [comment] 2023-05-31 09:04
Pinging @snelg

**Comment by boypt** [comment] 2023-05-31 14:39
> This error still appears after installing today's build with #10503. Not sure how I can get sqlite errors to display, tried removing the temp sqlite files from settings/ dir, without luck.

But in my device the problem is fixed in the latest nightly build.

Confirmed fixed on: 

- Poke4 android 11
- Kindle Pw3

Meybe you're facing another problem, check the crush.log for detailed info.

**Comment by snelg** [comment] 2023-05-31 15:02
> This error still appears after installing today's build with #10503. Not sure how I can get sqlite errors to display, tried removing the temp sqlite files from settings/ dir, without luck.

Works for me if I install the latest dev build via KOReader's internal menu
 - Update > Settings > Update channel > check "Development"
 - Update > Check for updates
 - Install version 202305000001

**Comment by ptrm** [comment] 2023-05-31 17:21
> Works for me if I install the latest dev build via KOReader's internal menu

@snelg apologies, I was using 202305000001, but only just looked into the logs and today it's Dropbox refusing my auth tokens ;)
