### ISSUE TITLE
Landscape has garbled text on the right in Night Mode, works fine in day mode or portrait (Android / Nook3)

### ISSUE THREAD

**Issue by alpha-k** [koreader/koreader#4231] opened 2018-09-17 18:22 UTC
* KOReader version: arm-linux-androideabi-v2015.11-1800-g0924b57_2018-07-29.apk
* Device: Nook 3 Glowlight (Android Kitkat)

#### Issue

![image](https://user-images.githubusercontent.com/17247087/45642032-b65a3b80-bad4-11e8-9c93-6e77096a2c9f.png)

In Landscape mode, when night mode is on, my Nook 3 Glowlight (Android Kitkat) shows garbled text on the right side as seen above. 

When night mode is off, the text is normal.

#### Steps to reproduce

Any epub/txt file, switch to landscape and turn on night mode, text appears garbled on the right side and doesn't fill the screen correctly. No crashes, just garbled text.

If i turn off night mode, or turn off landscape (change to portrait), the issue goes away.

**Comment by ilyats** [comment] 2018-09-24 05:06
![img_20180924_080127 1](https://user-images.githubusercontent.com/11670320/45938225-8200e680-bfd0-11e8-86be-9d8ccf1084eb.jpg)
 I also saw it on my android-based boyue likebook plus T80s

**Comment by poire-z** [comment] 2018-09-24 06:28
Duplicate of #3945

**Comment by jlaplana** [comment] 2018-12-13 09:53
Can comfirm that boyue Likebook Mars also has this trouble. Running android 6.0.1. I installed from the list of available apps in the device,  so i guess maybe it is a problem of their version of Koreader App??

**Comment by Frenzie** [comment] 2018-12-13 10:03
I don't know anything about that list you mention. Unless it's very outdated, it's more likely to be something incorrect in the logic I wrote or a bug in some versions of Android. You could always download the latest release [here](https://github.com/koreader/koreader/releases/tag/v2018.12) to make sure? :-)

Like I showed in the other issue, I can't reproduce this on any of my emulators[1] or real devices.

[1] I've got most version from 2.3 to 9 for (unfortunately manual, so infrequent) testing.

**Comment by Frenzie** [comment] 2018-12-13 10:04
Did I accidentally reopen this or was it still open? Closing since it's a duplicate of #3945.

**Closed** 2018-12-13 10:03 UTC
Labels: Android, bug

**Comment by Frenzie** [comment] 2018-12-13 19:44
This should be fixed in tomorrow's nightly.
