### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by rayman3003** [koreader/koreader#10063] opened 2023-01-31 21:57 UTC
Can we have a Windows version already?

KOreader has some good potentials & I'm sure Windows users gonna love this good full-featured ebook reader.

So why not?

Please make the KOreader more popular.

**Comment by NiLuJe** [comment] 2023-01-31 22:00
Because it runs under WSL2 ;o).

It used to possibly run when built via a MinGW TC, but this hasn't been tested in years (due to lack of developer interest, mainly due to the above point).

**Comment by rayman3003** [comment] 2023-02-01 07:49
> Because it runs under WSL2 ;o).

But it is not user-friendly for a normal windows user, to install a DISTRO on windows, to run just an ebook reader! 😅 Don't u think so?

> due to lack of developer interest

So bad. 😢

**Comment by pazos** [comment] 2023-02-01 09:32
Duplicate of #7653

**Closed by pazos** 2023-02-01 09:32 UTC
Labels: enhancement

**Comment by pazos** [comment] 2023-02-01 10:12
Yes. Please don't open duplicates. 

You can comment there if you wish.
