### ISSUE TITLE
Progress Tracking in Academic Books

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#8254] opened 2021-09-24 11:19 UTC
This is not exactly a feature request but more like a probe to see if other people would prefer a solution to this (smallish) problem.

In KOReader we have: 
- Progress bar
- Progress percentage
- Pages left in book
- Book time to read

to help a user see how much left in a book.

**But there is a problem with non-fiction, especially academic books:** 
After the last chapter there are many extra sections like acknowledgements, appendixes, chapter notes, keywords index, bibliography etc. These sections are not read linearly in the usual sense, they are more like references. But they add to the book page count (of course). This makes progress tracking features useless.

**For example:** 
I am currently reading a book which is **355** pages. But last chapter actually ends at page **243**. 
When my progress percentage shows **50%**, I am at **72%** actually. 
Currently I have **186** pages left according to the status bar. But it is actually **74** pages.

Of course there is nothing wrong with how KOReader is calculating these stats, but with these kind of books these stats become meaningless.

**Solution I thought:**
Maybe ability to mark a chapter as **EXTRA** (or something like that) so KOReader pretends book ends there.

**Example:**
...
CONCLUSIONS...184
APPENDIX...243
NOTES...284

In the example above, user can mark **APPENDIX** chapter as **EXTRA** so KOReader calculates all stats like the book is 243 pages.

**Comment by hius07** [comment] 2021-09-24 11:47
Per document setting `Number of pages in the book`.

**Comment by offset-torque** [comment] 2021-09-24 12:05
Where is this option exactly ? Can you write exact menu location. I just checked and couldn't find.

**Comment by hius07** [comment] 2021-09-24 12:22
It's a proposition based on your idea.

**Comment by offset-torque** [comment] 2021-09-24 12:28
Sorry, I thought we already have something like that deep inside STYLE TWEAKS or ToC settings that I am not aware of.

**Comment by hius07** [comment] 2021-09-24 12:37
It might be something similar to https://github.com/koreader/koreader/issues/6809 implemented in https://github.com/koreader/koreader/pull/6847.

**Comment by poire-z** [comment] 2021-09-24 12:37
Duplicate of / previous discussions about this in #7729.

**Comment by offset-torque** [comment] 2021-09-24 12:56
QUOTES ARE FROM OTHER ISSUE>

> I've seen myself sometimes note in my head the book content ends at 92% page 867, and do some substraction to get how many % or real pages I still have to read

This is what I am doing now yes.

> I agree it's not worth the possibly added complexity and risks in the many little places that deal with total_pages

I see it might break things so not feasible.

Another solution might depend on **PROGRESS BAR**:
- Different style for extra chapters
- A different chapter mark for the first extra chapter
- Or maybe darker background like thay are already read

So we will have at least a visual approximation of how much left. And total page count won't be touched in the code.

**Comment by Zeyadas** [comment] 2021-09-24 12:59
That's happening to me in a similar way, I usually read pdfs (500 to +1500 pages).
The index might be (50 to +100) pages at the end of the book and I always skip it, this way it affects the book status and my reading progress, and I don't know how to solve this using koreader.

**Comment by NiLuJe** [comment] 2021-09-24 16:17
The non linear flow stuff is kinda aimed at this sort of stuff as far as ePub is concerned, right?

**Comment by poire-z** [comment] 2021-09-24 16:28
Only if the publisher has done the work of flagging some chapters as non-linear in the EPUB itself - which amount for less than 1% of the EPUBs I had seen around...
And even then, the choice of what would be non-linear (in most cases: just the cover...) may be different from what the user think what will be the end of its real reading of the book.

So, no, non-linear flow stuff is not the solution to this user request :)
(And trying to solve it by hacking/injecting some elements of non-linear flow support is technically a bad idea & nightmare - and would not work with PDFs.)

**Comment by hius07** [comment] 2021-09-26 09:09
@offset-torque, look at https://github.com/koreader/koreader/pull/8265 please.

**Closed** 2023-10-08 22:15 UTC
Labels: enhancement
