### ISSUE TITLE
Justify txt

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8216] opened 2021-09-14 15:44 UTC
**v2021.08-77-g0af6500c_2021-09-14**
After updating to the latest nightly build (I've skipped several versions) have lost justifying of txt files.
No issue in the 08 release. Maybe after https://github.com/koreader/crengine/pull/454?

<kbd>![1](https://user-images.githubusercontent.com/62179190/133288561-0deaf426-1278-4df5-b279-33df4e93f6e3.png)</kbd>

<kbd>![2](https://user-images.githubusercontent.com/62179190/133288570-42e831e9-f463-438e-8c4a-cf9b0d6ffd5e.png)</kbd>

<kbd>![3](https://user-images.githubusercontent.com/62179190/133288573-704fb1d2-db3f-40ed-8821-bfb09a4d5370.png)</kbd>

<kbd>![4](https://user-images.githubusercontent.com/62179190/133288574-007dce2a-d4af-456b-90c4-be69cc97d049.png)</kbd>

**Comment by poire-z** [comment] 2021-09-14 16:19
Do I get it right: ?
1) normal rendering of text files has not changed
2) PRE is not justified by default (and I think there's some hard coded rule to force `text-align: left` on PRE)
3) you have some user style tweak that set `text-align: justify` on PRE (because crengine wraps plain text files lines into PRE when building its internal HTML document)

Your issue is probably caused by the first bit of https://github.com/koreader/crengine/pull/454/commits/a187f951b8be67ca91904733c3b873e9927c8128 that prevents any space to change width (so, nothing to extend when trying to justify) which made some sense when I added it (looking around in the code, not that I have ever experienced the issue in real books with PRE, but may be it triggered some issue in what I tried to fix, cf the screenshots).

Anyway, it's not so much PRE (the HTML tag) that I had fixed/tweaked, it's anything with `white-space: pre`, which is the default for PRE.
So, you can probably solve your issue (plain text wrapped in PRE by crengine that should really not, or that you don't want, shown as `white-space:pre`) by just adding to your style tweak: `white-space: normal`.
Is this addition enough ?
And is this something that you can/should just fix in your user tweaks - or do you think it's still some new issue with text files with a default KOReader ?

**Comment by poire-z** [comment] 2021-09-14 16:30
"Justify all elements" on v2021.08 looks odd with PRE (and txt files): there's some bits of justification/stretching of spaces happening, but some trailing space char is kept (because we don't collapse spaces when white-space: pre), so killing a bit the justification.
With current master, "Justify all elements" has no effect on txt files.
Does this need some fixing?

Should "Justify all elements" kill any white-space:pre for all elements to be allowed to be justified ?
Assuming I got the right idea to prevent `white-space:pre` to get stretched ? But I guess I was right, testing:
```
<div style="font-size: 300%; white-space: pre-wrap; text-align: justify">
some long text
```
in Firefox has it not justified. Kill the white-space and it becomes justified.

Should we add there another tweak to set `* { white-space: normal }` to allow unlocking this behaviour of PRE ?

**Comment by hius07** [comment] 2021-09-14 16:31
> Do I get it right: ?

Exactly.



> adding to your style tweak: `white-space: normal`

Fixed.

<kbd>![5](https://user-images.githubusercontent.com/62179190/133296990-5cb0d52b-ac98-4b44-b3d7-8cfee53eae60.png)</kbd>

**Comment by hius07** [comment] 2021-09-14 16:33
Thank you.
I need to think over your questions, as I always read txt with my style tweak only.

**Comment by hius07** [comment] 2021-09-14 19:01
I've looked into epub.css and specifications and believe that the current behaviour of the program is absolutely correct.

As for me, user style tweaks are enough, and no additional built-in tweaks are needed in menu.

**Comment by poire-z** [comment] 2021-09-15 05:42
OK, thank, so we can close this issue?

You made your own style tweaks, but may be we can have some to make it easier for all users with txt files?
I know there can be various kind of txt files (long line for each paragraph, or fit to 80 or 72 cols with not real line breaks), not familiar with how crengine deals with each kind of them and what's the result. But may be tweaks like yours can be of help to make it better in some cases ?
Also see #7293, https://github.com/koreader/koreader/issues/3646#issuecomment-652493561.

**Comment by hius07** [comment] 2021-09-15 06:01
> long line for each paragraph, or fit to 80 or 72 cols with not real line breaks

http://lib.ru/ is full of such txt books, but I do not use it preferring fb2.

I thought of making the UI settting of `txt_preformatted` and found no much sense for myself, rare txt.

**Comment by hius07** [comment] 2021-09-15 06:10
> the current behaviour of the program is absolutely correct

As I understand, `text-align: justify` should not justify the text with `white-space: pre`.
But it did so before https://github.com/koreader/crengine/commit/a187f951b8be67ca91904733c3b873e9927c8128, that was incorrect, as we have `white-space: pre` in epub.css.

**Comment by poire-z** [comment] 2021-09-15 06:51
^ Yes, I'm also sure we do now the right things - we're similar to how Firefox does it.

Well, let's not think much more about TXT, or we'll be entering hell :)

**Closed by poire-z** 2021-09-15 06:51 UTC

**Comment by poire-z** [comment] 2021-11-27 17:11
The "Justify most/all text" tweak should work now on txt documents with #8487.

**Comment by hius07** [comment] 2021-11-27 17:14
I've noticed, thanks a lot.

**Comment by liskin** [comment] 2024-01-05 17:24
> Should "Justify all elements" kill any white-space:pre for all elements to be allowed to be justified ? Assuming I got the right idea to prevent `white-space:pre` to get stretched ? But I guess I was right, testing:
> 
> ```
> <div style="font-size: 300%; white-space: pre-wrap; text-align: justify">
> some long text
> ```
> 
> in Firefox has it not justified. Kill the white-space and it becomes justified.

This doesn't seem to be the case any more. The following is justified in both Firefox and Chrome, and also in the epub editor that ships with Calibre (which uses QtWebEngine):

```html
<html><head>
<style type="text/css">body {
  white-space: pre-wrap;
  text-align: justify;
  font-size: 200%;
}</style></head>
<body>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi augue, pulvinar eget iaculis blandit, finibus eu lacus. Maecenas non elit vitae quam ullamcorper iaculis. Fusce nec purus porttitor, fermentum turpis at, consectetur ante. Integer commodo lacus eu venenatis ornare. Suspendisse eget rutrum magna, vitae ultrices odio. Donec egestas felis nec venenatis congue. Aliquam erat volutpat. In hac habitasse platea dictumst. Cras ullamcorper ultrices tortor eu dictum. Nullam urna lectus, accumsan non sem in, faucibus aliquet justo. Suspendisse potenti. Integer at libero quis metus accumsan facilisis. Sed pharetra eros eu rhoncus consectetur. Donec dapibus tincidunt pretium. Donec imperdiet risus quis condimentum viverra. Donec eleifend vel nibh at iaculis.</body></html>
```

Therefore I believe that crengine's handling of `white-space: pre-wrap` may be incorrect.

(I stumbled upon [an epub file](https://news.ycombinator.com/item?id=38766068) that has `white-space: pre-wrap` in its body's style attribute, and koreader refuses to justify the text no matter what style tweaks I enable. I've narrowed the issue down to this difference in handling of `white-space: pre-wrap`.)

**Comment by Frenzie** [comment] 2024-01-05 18:30
It's correct. But so is current Firefox.

https://www.w3.org/TR/css-text-3/#text-align
> In the case of [justify](https://www.w3.org/TR/css-text-3/#valdef-text-align-justify), the UA may stretch or shrink any inline boxes by [adjusting](https://www.w3.org/TR/css-text-3/#text-justify-property) their text. (See [text-justify](https://www.w3.org/TR/css-text-3/#propdef-text-justify).) _If an element’s [white space](https://www.w3.org/TR/css-text-3/#white-space) is not [collapsible](https://www.w3.org/TR/css-text-3/#collapsible-white-space), then the UA is not required to adjust its text for the purpose of justification and may instead treat the text as having no [justification opportunities](https://www.w3.org/TR/css-text-3/#justification-opportunity)_. If the UA chooses to adjust the text, then it must ensure that [tab stops](https://www.w3.org/TR/css-text-3/#tab-stop) continue to line up as required by the [white space processing rules](https://www.w3.org/TR/css-text-3/#white-space-rules).

**Comment by liskin** [comment] 2024-01-05 19:11
> It's correct. But so is current Firefox.
> […]

Oh, right, that makes sense. Thanks for clarifying this!

**Comment by poire-z** [comment] 2024-01-05 19:23
I also can see that current Firefox does justify it - but an old Firefox-56-clone I got lying around does not justify it.
KOReader does not justify it.

> It's correct. But so is current Firefox.

You mean that both, despite doing different things, are correct, as the specs allows for both behaviour ("not required"), right ?
And so no need to think about that anymore ? :Phew :)

> koreader refuses to justify the text no matter what style tweaks I enable

OK, probably not worth to ship another style tweak to allow that. But you can make your own when needed with Book style tweaks, and you would solve your wish. Right?

**Comment by Frenzie** [comment] 2024-01-05 19:34
> You mean that both, despite doing different things, are correct, as the specs allows for both behaviour ("not required"), right ?
> And so no need to think about that anymore ? :Phew :)

Yup. I'm slightly surprised the alternative is per spec tbh, but since it's purposefully overriding things I suppose it does make sense too.

**Comment by liskin** [comment] 2024-01-05 20:22
> OK, probably not worth to ship another style tweak to allow that. But you can make your own when needed with Book style tweaks, and you would solve your wish. Right?

Yes, now that I know what to look for, I believe I can make a tweak that forces `white-space` to not be `pre-wrap`.
