### ISSUE TITLE
Crash on PocketBook Touch HD with Firmware U5.16.136

### ISSUE THREAD

**Issue by Taranchul** [koreader/koreader#2276] opened 2016-10-03 15:54 UTC
- KOReader version: v2016.08.23-nightly
- Device: PocketBook Touch HD with Firmware U5.16.136

I installed all files from the zip in their respective places on the PocketBook. Starting Koreader results in this crash.log:

```
mkfifo: /var/dev/shm/emu_events: No such file or directory
./luajit: frontend/device/input.lua:162: error opening input device </var/dev/shm/emu_events>: 2
stack traceback:
    [C]: in function 'open'
    frontend/device/input.lua:162: in function 'open'
    frontend/device/pocketbook/device.lua:77: in function 'init'
    frontend/device/pocketbook/device.lua:109: in function 'init'
    frontend/device.lua:39: in main chunk
    [C]: in function 'require'
    frontend/ui/uimanager.lua:1: in main chunk
    [C]: in function 'require'
    ./reader.lua:99: in main chunk
    [C]: at 0x0000be01
Atached mp shm: id 0 addr 2cd61000 size 21616
----------------> USING A2PLUS MODE <-----------------
attach_shm: mtfb key=251331828 size=1657612
Atached mtfb shm: id 13000d addr 2cf62000 size 1657612
-------------------------
The task - koreader.app have
 xres=1072 yres=1448 bpp=4 vdepth=8
-------------------------
ndepth:4 hqdepth:4 orientation:0
attach_shm: ref key=2130378752 size=1552256
Atached ref shm: id 8001 addr 2d130000 size 1552256
Atached mqueue: id 8001
```

**Comment by fluffymadness** [comment] 2016-12-22 18:32
Does any version of koreader work on the pocketbook touch hd? I tried a few already...but not a single one starts on my device :/ 
When I click the @Koreader icon in the appdrawer nothing happens. Same when opening a book from the pocketbook library.
Hopefully this will be fixed in the future

**Comment by fluffymadness** [comment] 2016-12-23 13:41
fix for the crash in the device lua:
the path /var/dev/shm/ is completely empty on the new pocketbook hd
changing it to /dev/shm/ allows me to start koreader successfully

local PocketBook840 = PocketBook:new{
    isTouchDevice = yes,
    hasKeys = yes,
    display_dpi = 300,
    emu_events_dev = "/dev/shm/emu_events",
}

**Comment by houqp** [comment] 2016-12-23 17:25
Nice! Now all we need to do is to load different device setting based on the model. Do you know if there is any file on the device that we can read to determine the model?

**Comment by fluffymadness** [comment] 2016-12-23 17:42
I'd have to dig a bit, when I have some time again, maybe I'll find anything.
Sadly koreader crashes from time to time when navigating through a pdf, I tested 3 versions, the latest stable and two nightlys. It justs closes when switching to the next/prev pages after 20-30 pages or so. Its mostly random.

**Comment by houqp** [comment] 2016-12-25 08:01
What's in the crash.log? If it's random segfaults, the it might be related to toolchain issues. Currently, we are using https://github.com/pocketbook-free/SDK_481 for all the pocketbook builds, which might be out of date.

> Btw, is there any possibility to map the menu key of the pocketbook reader to the same event when I touch the top of the screen, to open the koreader menu?

Yes, absolutely. You need to first find out the key code for the menu key. Then map that key code to the `Menu` key in `event_map`: 
https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L103

For example, the menu keycode for kindle3 is 139: https://github.com/koreader/koreader/blob/master/frontend/device/kindle/event_map_keyboard.lua#L33

To find the keycode, you can run koreader in debug mode by setting `debug` to true in `settings.reader.lua`, then watch the crash.log content while pressing buttons on your device.

**Comment by fluffymadness** [comment] 2016-12-26 14:29
Hehe, found something

cat /etc/devicename
PocketBook631

The menu key is 23, but one small thing...the Menu options only opens the upper part of the menu.
When I press on the top of the screen, I see the upper and the lower part.
Is there an event where I can trigger the menu with the upper and lower part?
Thanks.

function PocketBook840:init()
    self.screen = require("ffi/framebuffer_mxcfb"):new{device = self, debug = DEBUG}
    self.powerd = require("device/pocketbook/powerd"):new{device = self}
    self.input = require("device/input"):new{
        device = self,
        event_map = {
            [23] = "Menu",
            [24] = "LPgBack",
            [25] = "LPgFwd",
            [1002] = "Power",
        }
    }
    PocketBook.init(self)
end

**Comment by fluffymadness** [comment] 2016-12-26 14:32
As for the crashes, just had a segmentation fault when pressing on the top of the screen when I tried to open the menu.
I think the menu appeared for a second or so and then the app was gone

**Comment by fluffymadness** [comment] 2016-12-26 14:38
Hmm. I tried different version, and all had some crashes, but the log is from the latest nightly.
Is koreader running completely stable on kindle and kobo ?

**Comment by fluffymadness** [comment] 2016-12-26 14:46
Another one when just pressing the page down button a few time to switch between pages

```
# 12/26/16-15:44:17  promote refresh to full refresh
# 12/26/16-15:44:17  set page position 0.022697742050169
# 12/26/16-15:44:17  refresh: full -1 -1 1450 1074
# 12/26/16-15:44:17  update area conflicts with active update 1
# 12/26/16-15:44:17  waiting for completion of update 1
# 12/26/16-15:44:17  duration: 0
# 12/26/16-15:44:17  assigned marker 1 to update: {
    ["refreshtype"] = 1,
    ["time"] = 1482763457801.3,
    ["rect"] = {
        ["y"] = 0,
        ["x"] = 0,
        ["h"] = 1448,
        ["w"] = 1072
    },
    ["waveform_mode"] = 2
}
# 12/26/16-15:44:17  hinting page 23
# 12/26/16-15:44:17  key ev {
    ["type"] = 1,
    ["time"] = {
        ["usec"] = 569967,
        ["sec"] = 1482763457
    },
    ["code"] = 24,
    ["value"] = 0
}
Segmentation fault
```

**Comment by fluffymadness** [comment] 2016-12-26 14:59
Is this normal O.o
# 12/26/16-15:50:36  refresh: full -1 -1 1450 1074

but the framebuffer resolution is
# 12/26/16-15:50:35  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}

**Comment by houqp** [comment] 2016-12-26 22:26
> Hehe, found something
>
>cat /etc/devicename
>PocketBook631

That's awesome, we can use this info to initialize the device module like what we did for kobo: https://github.com/koreader/koreader/blob/master/frontend/device/kobo/device.lua#L348

> The menu key is 23, but one small thing...the Menu options only opens the upper part of the menu.

I can submit a patch later to enable bottom menu for touch devices.

> Is koreader running completely stable on kindle and kobo, without any random crashes?

Yes, there is no random segfaults on kindle and kobo.

> Is this normal O.o
> `# 12/26/16-15:50:36 refresh: full -1 -1 1450 1074`

It's definitely a bug. But if I recall correctly, we have boundary check in framebuffer code to guard agains out of bound memory access too. So it's hard to tell right now. I will have to double check on my kobo's log. It does look like a out of bound memory access bug.

Can you confirm that all the Segmentation fault happens after `# 12/26/16-15:50:37  hinting page XX`?

If you have gdb on the device to get the stack trace that would help debugging this issue too.

**Comment by houqp** [comment] 2016-12-27 07:12
You should get the full menu with menu key after https://github.com/koreader/koreader/pull/2457 is merged.

**Comment by fluffymadness** [comment] 2016-12-27 09:11
I have indeed gdb on the device. I just have to find out how to attach it to it.
Another thing I've noticed.
Right now, when I open the pdf from the stock pocketbooklauncher (via extensions.cfg) it shows page 17. When I press the page down button to go to page 18 it always crashes. I can reproduce this an infinite amount of time.
The funny thing is, if I open the koreader app from the app drawer, manually navigate to the pdf document via the koreader filemanager and open it, I'm on the exact same page of the document where I was when I opened it via the pocketbooklauncher, but with one difference. Pressing the page down button doesn't crash koreader

**Comment by houqp** [comment] 2016-12-28 03:32
> I have indeed gdb on the device. I just have to find out how to attach it to it.

Tips for attaching to a running process with gdb: http://stackoverflow.com/questions/2308653/can-i-use-gdb-to-debug-a-running-process

You also don't have to attach to a running instance. Even a coredump generated by the segfault will help. You can load coredump into gdb and get the stacktrace out of it.

> Right now, when I open the pdf from the stock pocketbooklauncher (via extensions.cfg) it shows page 17. When I press the page down button to go to page 18 it always crashes. I can reproduce this an infinite amount of time.

Reproducible bugs are the best bugs!

> The funny thing is, if I open the koreader app from the app drawer, manually navigate to the pdf document via the koreader filemanager and open it, I'm on the exact same page of the document where I was when I opened it via the pocketbooklauncher, but with one difference. Pressing the page down button doesn't crash koreader

You still get random crashes when launching koreader from app drawer right?

**Comment by houqp** [comment] 2016-12-28 06:17
I checked the log from my kobo, the refresh area dimension is also off by 2 in height and width. So this is likely not the cause for your segfults.

**Comment by ersi-dnd** [comment] 2017-03-24 23:24
I also have Pocketbook Touch HD. I have tried the edits suggested in this thread in device.lua (assuming the right one is in `applications/koreader/frontend/device/pocketbook/` ) but no result. With or without the edits, Koreader does not open. In that device.lua I also tried to change the word PocketBook840 to PockeBook631 and back.

My firmware version number ends in 361.

**Comment by houqp** [comment] 2017-03-25 02:31
it would help narrow down the issue if anyone can help get a stacktrace for the segfault. it's really hard for us to debug given that no developer owns this device.

**Comment by ersi-dnd** [comment] 2017-03-25 07:15
What is a stacktrace? Something else than crash.log?

**Comment by Taranchul** [comment] 2017-03-25 08:36
I found this about debugging on a PocketBook:

https://www.mobileread.com/forums/showthread.php?t=222077

The last post describes saving a stack trace into a file. So it seems doable but kinda complex, although I have Kubuntu Linux so the Debian part is native for my system. I will see into it but I can't make promises, being an absolute layman at debugging.

@houqp: Or do you know a simpler way to do it? Thanks for dealing with this.

**Comment by Taranchul** [comment] 2017-03-25 15:10
Or would the SDK help with this?

https://github.com/blchinezu/pocketbook-sdk/

**Comment by houqp** [comment] 2017-03-27 03:57
@Taranchul @ersi-dnd yes, I am referring to the stack trace obtained from gdb. You don't have to do a remote gdb attach like what's described in the mobileread post. If you have ssh access to the device, you can just run gdb in the shell and attach to the running koreader process. Then try to trigger a segfault crash in reader and print the stack trace in gdb using `bt` command.

**Comment by ersi-dnd** [comment] 2017-03-27 15:31
I am too noob to help in this, but I am willing to donate my Touch HD until a developer can make Koreader work on it. Koreader deserves it.

**Comment by Taranchul** [comment] 2017-03-27 21:08
Okay, I spent two hours trying to run the Debian Sid armel gdb on my PocketBook using utelnetd as a terminal. Gdb demanded library after library which I gave it only to have it segfault at the end. 

@houqp, Du you have any advice how to get gdb running on the PB?

**Comment by ersi-dnd** [comment] 2017-05-03 17:07
I can somewhat happily report that modifications as described here https://github.com/koreader/koreader/issues/2276#issuecomment-268991273
made koreader-nightly-20170430 work for me on Pocketbook Touch HD. 

However, the result is a bit shaky. It often takes multiple attempts to start and sometimes crashes in the middle of some random gesture. It seems that when 

1. I lock the device on Koreader and 
2. Koreader fails to put out its own screenlock image (the file's first page) and 
3. I unlock the device and
4. Koreader crashes

then Koreader quite consistently fails to start next time. Sometimes I restart the device and even then it's not guaranteed to get back into Koreader easily. Then again, sometimes Koreader works just fine when I unlock the device even after it failed to put out its own screenlock image. 

Something's not quite alright, but works about 2/3 of the time and no other problems besides these crashes and start failures.

**Comment by danton9** [comment] 2017-06-02 15:17
crash.log 

05/31/17-21:14:28 ERROR cannot open translation file: l10n/en_US/koreader.po
Segmentation fault

**Comment by Maradar** [comment] 2017-10-05 12:21
I have a quick question.

Are there any plans to make this app optimized and working on Touch HD right out off the bat?

**Comment by Frenzie** [comment] 2017-10-05 14:06
@mk-f might know more about Pocketbook.

**Comment by mk-f** [comment] 2017-10-06 10:29
I only own the Inkpad2. I'll try to help if someone provides a full ``gdb backtrace``, but without the device and / or a reliable way to reproduce an error this will not be easy. Generally, I think it would be wise to rely  on ``libinkview`` instead of  hardcoded /sys-path and alike - one could look into [CoolReader](https://github.com/blchinezu/pocketbook-coolreader) for this purpose. Generally it might be a good idea to test CoolReader on your device - if it works there, it is at least possible to implement here.

**Comment by Maradar** [comment] 2017-10-06 13:23
CoolReader works great on the device but still it would be nice to have this app working as well

**Closed** 2020-08-19 19:57 UTC
Labels: PocketBook, bug, firmware, out-of-date
