### ISSUE TITLE
„Find a book in calibre catalog” can’t find files

### ISSUE THREAD

**Issue by Havner** [koreader/koreader#4082] opened 2018-07-16 12:30 UTC
* KOReader version: Today’s nightly (16.07.2018)
* Device: Kobo Aura H2O

#### Issue
I’m syncing Kobo with Calibre letting it handle directory structure on the Kobo. It puts its metadata file and books to the /mnt/onboard directory. I have:

/mnt/onboard/metadata.calibre
/mnt/onboard/books/AUTHOR/BOOK.epub

When I click: „Find a book in calibre catalog” and then choose either series or tags it shows the database content 100% correctly. I can find what I’m looking for. But when I click on some book I get:

File ‚/books/AUTHOR/BOOK.epub’ does not exist.

Granted, such a file does not exist, but if you’d prefix the path with /mnt/onboard it would. KOReader can find the metadata properly, but it cannot find the books from the paths read from it. 

I’ve tried setting SEARCH_LIBRARY_PATH to /mnt/onboard in the defaults.persistent.lua (using KOReader’s UI) but it didn’t change anything.

**Comment by NiLuJe** [comment] 2018-07-16 15:42
Can't reproduce, it behaves as expected on my end. (funnily enough, a H2O, with the exact same Calibre setup ^^).

```
cat koreader/defaults.persistent.lua

-- Set a path to a folder that is filled by Calibre (must contain the file metadata.calibre)
-- e.g.
-- "/mnt/sd/.hidden" for Kobo with files in ".hidden" on the SD card
-- "/mnt/onboard/MyPath" for Kobo with files in "MyPath" on the device itself
-- "/mnt/us/documents/" for Kindle files in folder "documents"
SEARCH_LIBRARY_PATH  = "/mnt/onboard"
SEARCH_LIBRARY_PATH2 = ""
```

**Comment by NiLuJe** [comment] 2018-07-16 15:46
It's only having moderate troubles with kePubs downloaded from the device, possibly because they're in a hidden folder .kobo/kepub and have a shitty filename.

But the search itself was unreliable for those already.

**Comment by Havner** [comment] 2018-07-16 16:25
It never worked for me. Since I’ve noticed the functionality. I recently started to use KOReader more and more and it started to bother me. 

How it detects the metadata file then? Even without the SEARCH_LIBRARY_PATH set? Is the procedure different for metadata and the books?

Are your paths in the metadata file relative? E.g. /books/SOMETHING, rather then /mnt/onboard/books/SOMETHING? Maybe it’s calibre’s configuration and with my DB it would’t work for tou as well. 

Also, can you point me to the code that calculates those paths? I’m a programmer by occupation, I’d have a look at it when I get home from vacation.

**Comment by Havner** [comment] 2018-07-16 16:30
I’ve worked around it by making a symlink for now:

/books -> /mnt/onboard/books

**Comment by Frenzie** [comment] 2018-07-16 16:30
Should probably be here: https://github.com/koreader/koreader/blob/e502bf04d3369b422a17d7e298684e5981cbd7dd/frontend/apps/filemanager/filemanagersearch.lua

**Comment by NiLuJe** [comment] 2018-07-16 17:13
Paths are relative in metadata.calibre on my end, FWIW.

**Comment by NiLuJe** [comment] 2018-07-16 17:17
https://github.com/koreader/koreader/blob/e502bf04d3369b422a17d7e298684e5981cbd7dd/frontend/apps/filemanager/filemanagersearch.lua#L434-L437

It properly prefixes the right LIBRARY_PATH when set, but doesn't when it's unset, which might be your issue.

**Comment by Havner** [comment] 2018-07-16 17:54
kobo koreader # pwd
/mnt/onboard/.adds/koreader
kobo koreader # grep PATH defaults.persistent.lua 
SEARCH_LIBRARY_PATH = "/mnt/onboard"

**Comment by NiLuJe** [comment] 2018-07-16 18:06
Hmm, got a couple crappy ideas then:

* Check that there's no syntax error in your defaults.persistent.lua, it's basically fed as-is to the Lua parser
* Set SEARCH_LIBRARY_PATH2 too, in case there's a weird mishap with the first pass

**Comment by Havner** [comment] 2018-07-16 18:16
* I don’t think there is as I’ve got tap regions set there as well and they do work properly. I never modified this file by hand, only using koreader’s UI
* I’ve tried that already

I suppose I’ll have to debug that when I get home :-)

**Comment by NiLuJe** [comment] 2018-07-16 20:12
This should fix the "half functional" issue with the defaults unset.

**Comment by Havner** [comment] 2018-07-16 21:03
I did a clean install of koreader June version, the only thing I could do having just my mobile. Moved the defaults.persistance.lua from old installation to the new one, launched it and the issue is not there. I’ve updated to the latest nightly and it still works.

My previous installation was pretty old, it was very old stable version that has been updated at some point to the nightlys. The only explanation I can find is that the existance of some files that were later removed might have caused some issues. Still strange. I’ll diff both trees when I get to my conputer.

But the issue seems to have been caused by my installation so if you don’t care about the root cause (I’ll try to get to the bottom of it) it can be closed.

**Comment by NiLuJe** [comment] 2018-07-16 21:08
Well, at least the behavior with the defaults unset was somewhat broken, so at least that uncovered that ;).

I'll link closing this w/ the PR in question, but yeah, figuring out what went wrong in your previous setup might be interesting :).

**Comment by Havner** [comment] 2018-07-16 21:16
Is your new PR already in nightlys? Just for the sake of it I removed the LIB_PATH from defaults.persistent.lua and it still finds books properly. The same way as it always found the database for me regardless of the LIB_PATH. I’m just not sure whether this is due to your commit or it worked like that before. After all it was always able to find the calibre db by itself.

**Comment by Havner** [comment] 2018-07-16 21:20
I did the update to the latest nightly like 20 minutes ago. Not sure when are the nightlys built.

**Comment by NiLuJe** [comment] 2018-07-16 22:08
It's not in yet, no. I suspect relative path shenanigans, meaning if it works, it's fragile ;).

**Comment by cramoisi** [comment] 2018-07-17 05:45
@Havner how do you add the files on koreader? do you export them to a folder on your computer and then move this folder on you device or do you directly open your device folder within koreader to add the doc. Long time ago I add issues with the first method ; the second is ok for me.

**Comment by Havner** [comment] 2018-07-17 10:12
I use Calibre directly. The decice is detected and synced. Then I select a book and „Send to device”.

**Comment by cramoisi** [comment] 2018-07-17 14:15
> The decice is detected and synced 

I don't understand. Calibre doesn't detect koreader itself, you must go with the folder device plugin and disable the kobo device plugin and mount a folder in calibre. It's this folder which is recognize as a device... Or do yo put your books at the root of the storage so they are seen by both nickel and koreader ? (if it is the case, it's not a great thing to do)

**Comment by cramoisi** [comment] 2018-07-17 17:41
it's not a problem if nickel is running, but it's a problem if calibre recognizes it. You have to disable the kobo plugins in calibre and use the folder plugin instead. Then you choose "connect to a folder", you choose a hidden folder inside your kobo for koreader to use your book and you send them as usual.

**Comment by Havner** [comment] 2018-07-18 02:11
Back to the issue at hand.

(all of this is done after I connected my KOBO to the calibre, which seems is important later on)

1. I've diffed both trees and the only significant difference was the koreader metadata file. In the new installation it had paths properly prefixed with /mnt/onboard, while the old one was just /books...

2. Additionally the old installation had files in koreader metadata that didn't exist anymore.

3. I've set LIB_PATH in the old installation, removed the metadata and the issue is not there anymore.

4. I've restored the old/broken koreader DB to the old installation and the issue is not there as well

Additionally I've noticed that what I said earlier is no longer true. In the new installation (or old for that matter, as they started to behave the same) when I unset the LIB_PATH, Koreader is no longer able to find the books. It is again when I set it back.

All of this combined makes me believe that there was some issue in regenerating the koreader's metadata file. The old installation had it broken (without the prefix), the new one generated it once after installation, and refused to regenerate it afterwards (unsetting LIB_PATH did not render it inoperable as it consistently does now). The only thing that changed is that I connected Kobo to calibre beforehand that made it update its own DB.

FURTHER INVESTIGATION and the **FINAL ANSWER**:
After I wrote all this I had a look at the code. Koreader chooses its own DB over regenerating it from Calibre's if its own is newer. And there are 2 serious issues here:

1. If someone doesn't set the LIB_PATH or sets it wrong Koreader won't try the new LIB_PATH unless you modify the Calibre's DB or delete koreader metadata manually. **And this was my original issue. I had koreader metadata wrong (generated with LIB_PATH="") and setting new LIB_PATH had completely no effect until I reconnected to my PC.**

2. For some awkward reason metadata file written by Koreader has file date in UTC, while Calibre sets file date (when Kobo is connected to my computer) in local time. I'm on UTC+2. So for 2 hour window Calibre's metadata is always newer then Koreader's. That's why unsetting LIB_PATH now (for that 2 hour window) makes it regenerate Koreader's DB at every chance while it didn't yesterday.

Date/time/timezone on my Kobo is set properly.
"date" shows local time (UTC+2)
"date -u" shows UTC (local-2)

As to why Koreader saves files with UTC I have no idea.

**Comment by Havner** [comment] 2018-07-18 02:44
The file save time shift seems to be caused by mounting the Kobo. No idea what is happening here, but it doesn't seem to be Koreader's fault. I see completely different file dates when I ssh onto Kobo and when it's mounted.

E.g.:
```
drwxr-xr-x    3 root     root          4096 Jul 16 03:22 .PDF
drwxr-xr-x    8 root     root          4096 Jul 18 02:05 .adds
drwxr-xr-x    8 root     root          4096 Jul 18 04:34 .kobo
drwxr-xr-x  162 root     root          8192 Apr  6 05:01 .kobo-images
drwxr-xr-x   37 root     root          4096 Jul 17 00:06 books
drwxr-xr-x    2 root     root          4096 Jan 24  2017 fonts
drwxr-xr-x    2 root     root          4096 Jul 18 04:00 icons
```

```
drwxrwxrwx  1 havner  staff    4096 30 Jun  2017 .PDF
drwxrwxrwx  1 havner  staff    4096 18 Jul 04:34 .adds
drwxrwxrwx  1 havner  staff    4096 18 Jul 02:53 .kobo
drwxrwxrwx  1 havner  staff    8192 30 Jun  2017 .kobo-images
drwxrwxrwx  1 havner  staff    4096 17 Jul 23:43 books
drwxrwxrwx  1 havner  staff    4096 30 Jun  2017 fonts
drwxrwxrwx  1 havner  staff    4096 18 Jul 01:40 icons
```

Some of them are shifter by exactly two hours, some are way off. Anyway, first issue from my previous post still remains.

**Comment by NiLuJe** [comment] 2018-07-18 03:05
@Havner : By `LIB_PATH` you mean `SEARCH_LIBRARY_PATH`, right?

And yeah, good catch, I'd forgotten about our own metadata db >_<".

I'll see how mine looks, the H2O isn't near me right now.

And I'll look at the TZ thing, because that's interesting if something wonly's going on there... LFS basically just exposes stat's fields, but I'm not familiar with how those are stored in vfat (because I doubt that's simply a goolg old Epoch timestamp like on any decent FS, which may leave some room for trickery of that sort...).

**Comment by NiLuJe** [comment] 2018-07-18 03:07
Yeah, a quick glance at https://github.com/torvalds/linux/blob/master/Documentation/filesystems/vfat.txt appears to confirm the possibility of timestamp trickery of the sort... ;).

**Comment by NiLuJe** [comment] 2018-07-18 03:08
So that probably depends on how macOS handle that when mounting FAT32 volumes, too...

**Comment by Havner** [comment] 2018-07-18 09:17
Yes, by `LIB_PATH` I mean `SEARCH_LIBRARY_PATH`.
I'll check today or tomorrow if the modification dates are as unreliable when mounting on Linux.

About the koreader temp db, is there any performance gained from it? I noticed it is created when hitting "Find a book in calibre catalog", and never noticed any performance difference when I knew it is recreated for sure and when I knew it's not. Although I imagine that might be subjective and device dependent. Recreating it every time though or just using Calibre's directly would solve both issues.

**Comment by Havner** [comment] 2018-07-18 09:42
Yes, by `LIB_PATH` I mean `SEARCH_LIBRARY_PATH`.
I'll check today or tomorrow if the modification dates are as unreliable when mounting on Linux.

About the koreader temp db, is there any performance gained from it? I noticed it is created when hitting "Find a book in calibre catalog", and never noticed any performance difference when I knew it is recreated for sure and when I knew it's not. Although I imagine that might be subjective and device dependent. Recreating it every time though or just using Calibre's directly would solve both issues.

I would imagine that my use case should be pretty common. Someone tries to use the calibre's db function, it doesn't work, sets the SEARCH_LIBRARY_PATH after googling, still doesn't work (as the DB is not recreated assuming no shenanigans with time stamps).

**Comment by NiLuJe** [comment] 2018-07-18 15:09
Yeah, I was asking myself the same question... ;).

**Comment by NiLuJe** [comment] 2018-07-21 19:30
Okay, apparently, the local metadata file made things faster for the guy that implemented it, so, yeah, why not ;).

Haven't seen any noticeable difference here on a ~500 book library, but, okay, I'll buy it nonetheless.

It has the added quirk of skipping stuff we supposedly can't open, kePubs downloaded by Nickel being some of them, because they don't have any file extension. Documented it, because that doesn't bother me much, and I get the idea behind the check.
That's it's done with one metadata file type and not the other is weirder, though, but that might be because doing it w/ a calibre metadat with broken paths would essentially break the thing entirely.

**Comment by NiLuJe** [comment] 2018-07-21 19:32
In any case, barring timestamp shenanigans, the PR should fix the original issue, by making sure stuff is working with an autodetected calibre metadata file and no SEARCH_LIBRARY_PATH set (which should be common, as it's the default state of KOReader).

**Closed** 2018-07-21 19:51 UTC

**Comment by Havner** [comment] 2018-07-21 19:53
Smaller issue, but still, changing the SEARCH_LIBRARY_PATH afterwards will require touching Calibre's DB or removal of metadata. So this only fixes the initial state, not the core of the issue.

**Comment by NiLuJe** [comment] 2018-07-21 19:58
Yeah, my rationale for not handling this was that, you only change SEARCH_LIBRARY_PATH when you actually move your library, which implies timestamp changes.

With this in, if the library hasn't moved, setting SEARCH_LIBRARY_PATH won't change a thing because it'd already have been found without it set.

That indeed potentially leaves corner-cases where fucked up timestamps will ensure a stale koreader metadata file getting picked up over an up-to-date Calibre one, ever after a Calibre connection.
