### ISSUE TITLE
Crash when logging evernote(yinxiang)

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#4509] opened 2019-01-25 01:13 UTC
* KOReader version:2019.1
* Device:h2o,aura one

#### Issue
I can log the Evernote，but can't log the Yinxiang(Evernote chinese version).
That's the crash log below.

./luajit: plugins/evernote.koplugin/main.lua:257: attempt to call method 'find' (a nil value)
stack traceback:
	plugins/evernote.koplugin/main.lua:257: in function 'doLogin'
	plugins/evernote.koplugin/main.lua:204: in function 'action'
	frontend/ui/uimanager.lua:669: in function '_checkTasks'
	frontend/ui/uimanager.lua:893: in function 'handleInput'
	frontend/ui/uimanager.lua:979: in function 'run'
	./reader.lua:210: in main chunk
	[C]: at 0x000139c1

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment] 2019-01-25 08:20
Closing as a duplicate of #4509.

Did you try if the workaround there results in desired behavior?

**Comment by seacatwu** [comment] 2019-01-25 13:38
Two devices, same bug. I only opened a epub book...

**Closed** 2019-01-25 14:19 UTC
