### ISSUE TITLE
Koreader crashes since 2024.07

### ISSUE THREAD

**Issue by sonderzug** [koreader/koreader#12512] opened 2024-09-13 13:16 UTC
* KOReader version:2024.07
* Device: tolino / android 4.4.2

#### Issue
Crash at start
##### `crash.log` (if applicable)

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
--------- beginning of /dev/log/main
09-13 14:32:30.304 V/NativeGlue( 7437): Pause: 0x59c34758
09-13 14:32:30.844 I/MultiDex( 7455): VM with version 1.6.0 does not have multidex support
09-13 14:32:30.844 I/MultiDex( 7455): Installing application
09-13 14:32:30.844 I/MultiDex( 7455): MultiDexExtractor(/data/app/org.koreader.launcher.fdroid-2.apk, /data/data/org.koreader.launcher.fdroid/code_cache/secondary-dexes)
09-13 14:32:30.844 I/MultiDex( 7455): Blocking on lock /data/data/org.koreader.launcher.fdroid/code_cache/secondary-dexes/MultiDex.lock
09-13 14:32:30.854 I/MultiDex( 7455): /data/data/org.koreader.launcher.fdroid/code_cache/secondary-dexes/MultiDex.lock locked
09-13 14:32:30.854 I/MultiDex( 7455): MultiDexExtractor.load(/data/app/org.koreader.launcher.fdroid-2.apk, false, )
09-13 14:32:30.884 I/MultiDex( 7455): loading existing secondary dex files
09-13 14:32:30.884 I/MultiDex( 7455): load found 0 secondary dex files
09-13 14:32:30.884 I/MultiDex( 7455): install done
09-13 14:32:30.964 I/dalvikvm( 7455): Could not find method android.app.Activity.onRequestPermissionsResult, referenced from method androidx.activity.ComponentActivity.onRequestPermissionsResult
09-13 14:32:30.964 W/dalvikvm( 7455): VFY: unable to resolve virtual method 91: Landroid/app/Activity;.onRequestPermissionsResult (I[Ljava/lang/String;[I)V
09-13 14:32:30.964 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0020
09-13 14:32:31.214 I/dalvikvm( 7455): Could not find method android.widget.TextView.getAutoSizeMaxTextSize, referenced from method androidx.appcompat.widget.AppCompatTextView.getAutoSizeMaxTextSize
09-13 14:32:31.214 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1980: Landroid/widget/TextView;.getAutoSizeMaxTextSize ()I
09-13 14:32:31.214 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.214 I/dalvikvm( 7455): Could not find method android.widget.TextView.getAutoSizeMinTextSize, referenced from method androidx.appcompat.widget.AppCompatTextView.getAutoSizeMinTextSize
09-13 14:32:31.214 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1981: Landroid/widget/TextView;.getAutoSizeMinTextSize ()I
09-13 14:32:31.214 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.214 I/dalvikvm( 7455): Could not find method android.widget.TextView.getAutoSizeStepGranularity, referenced from method androidx.appcompat.widget.AppCompatTextView.getAutoSizeStepGranularity
09-13 14:32:31.214 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1982: Landroid/widget/TextView;.getAutoSizeStepGranularity ()I
09-13 14:32:31.214 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.214 I/dalvikvm( 7455): Could not find method android.widget.TextView.getAutoSizeTextAvailableSizes, referenced from method androidx.appcompat.widget.AppCompatTextView.getAutoSizeTextAvailableSizes
09-13 14:32:31.214 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1983: Landroid/widget/TextView;.getAutoSizeTextAvailableSizes ()[I
09-13 14:32:31.214 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.214 I/dalvikvm( 7455): Could not find method android.widget.TextView.getAutoSizeTextType, referenced from method androidx.appcompat.widget.AppCompatTextView.getAutoSizeTextType
09-13 14:32:31.214 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1984: Landroid/widget/TextView;.getAutoSizeTextType ()I
09-13 14:32:31.214 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0005
09-13 14:32:31.214 I/dalvikvm( 7455): Could not find method android.widget.TextView.getTextClassifier, referenced from method androidx.appcompat.widget.AppCompatTextView.getTextClassifier
09-13 14:32:31.214 W/dalvikvm( 7455): VFY: unable to resolve virtual method 2001: Landroid/widget/TextView;.getTextClassifier ()Landroid/view/textclassifier/TextClassifier;
09-13 14:32:31.214 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0031
09-13 14:32:31.254 E/dalvikvm( 7455): Could not find class 'android.view.textclassifier.TextClassifier', referenced from method androidx.appcompat.widget.AppCompatTextView.getTextClassifier
09-13 14:32:31.254 W/dalvikvm( 7455): VFY: unable to resolve check-cast 343 (Landroid/view/textclassifier/TextClassifier;) in Landroidx/appcompat/widget/AppCompatTextView;
09-13 14:32:31.254 D/dalvikvm( 7455): VFY: replacing opcode 0x1f at 0x000d
09-13 14:32:31.254 I/dalvikvm( 7455): Could not find method android.widget.TextView.setAutoSizeTextTypeUniformWithConfiguration, referenced from method androidx.appcompat.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithConfiguration
09-13 14:32:31.254 W/dalvikvm( 7455): VFY: unable to resolve virtual method 2021: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V
09-13 14:32:31.254 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.254 I/dalvikvm( 7455): Could not find method android.widget.TextView.setAutoSizeTextTypeUniformWithPresetSizes, referenced from method androidx.appcompat.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithPresetSizes
09-13 14:32:31.254 W/dalvikvm( 7455): VFY: unable to resolve virtual method 2022: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V
09-13 14:32:31.254 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.254 I/dalvikvm( 7455): Could not find method android.widget.TextView.setAutoSizeTextTypeWithDefaults, referenced from method androidx.appcompat.widget.AppCompatTextView.setAutoSizeTextTypeWithDefaults
09-13 14:32:31.254 W/dalvikvm( 7455): VFY: unable to resolve virtual method 2023: Landroid/widget/TextView;.setAutoSizeTextTypeWithDefaults (I)V
09-13 14:32:31.254 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.254 I/dalvikvm( 7455): Could not find method android.widget.TextView.setFirstBaselineToTopHeight, referenced from method androidx.appcompat.widget.AppCompatTextView.setFirstBaselineToTopHeight
09-13 14:32:31.254 W/dalvikvm( 7455): VFY: unable to resolve virtual method 2035: Landroid/widget/TextView;.setFirstBaselineToTopHeight (I)V
09-13 14:32:31.254 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0006
09-13 14:32:31.254 I/dalvikvm( 7455): Could not find method android.widget.TextView.setLastBaselineToBottomHeight, referenced from method androidx.appcompat.widget.AppCompatTextView.setLastBaselineToBottomHeight
09-13 14:32:31.254 W/dalvikvm( 7455): VFY: unable to resolve virtual method 2043: Landroid/widget/TextView;.setLastBaselineToBottomHeight (I)V
09-13 14:32:31.254 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0006
09-13 14:32:31.254 W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/textclassifier/TextClassifier;)
09-13 14:32:31.254 I/dalvikvm( 7455): Could not find method android.widget.TextView.setTextClassifier, referenced from method androidx.appcompat.widget.AppCompatTextView.setTextClassifier
09-13 14:32:31.254 W/dalvikvm( 7455): VFY: unable to resolve virtual method 2056: Landroid/widget/TextView;.setTextClassifier (Landroid/view/textclassifier/TextClassifier;)V
09-13 14:32:31.254 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x000e
09-13 14:32:31.474 I/dalvikvm( 7455): Could not find method android.widget.Button.getAutoSizeMaxTextSize, referenced from method androidx.appcompat.widget.AppCompatButton.getAutoSizeMaxTextSize
09-13 14:32:31.474 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1705: Landroid/widget/Button;.getAutoSizeMaxTextSize ()I
09-13 14:32:31.474 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.474 I/dalvikvm( 7455): Could not find method android.widget.Button.getAutoSizeMinTextSize, referenced from method androidx.appcompat.widget.AppCompatButton.getAutoSizeMinTextSize
09-13 14:32:31.474 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1706: Landroid/widget/Button;.getAutoSizeMinTextSize ()I
09-13 14:32:31.474 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.474 I/dalvikvm( 7455): Could not find method android.widget.Button.getAutoSizeStepGranularity, referenced from method androidx.appcompat.widget.AppCompatButton.getAutoSizeStepGranularity
09-13 14:32:31.474 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1707: Landroid/widget/Button;.getAutoSizeStepGranularity ()I
09-13 14:32:31.474 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.474 I/dalvikvm( 7455): Could not find method android.widget.Button.getAutoSizeTextAvailableSizes, referenced from method androidx.appcompat.widget.AppCompatButton.getAutoSizeTextAvailableSizes
09-13 14:32:31.474 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1708: Landroid/widget/Button;.getAutoSizeTextAvailableSizes ()[I
09-13 14:32:31.474 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.474 I/dalvikvm( 7455): Could not find method android.widget.Button.getAutoSizeTextType, referenced from method androidx.appcompat.widget.AppCompatButton.getAutoSizeTextType
09-13 14:32:31.474 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1709: Landroid/widget/Button;.getAutoSizeTextType ()I
09-13 14:32:31.474 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0005
09-13 14:32:31.474 I/dalvikvm( 7455): Could not find method android.widget.Button.setAutoSizeTextTypeUniformWithConfiguration, referenced from method androidx.appcompat.widget.AppCompatButton.setAutoSizeTextTypeUniformWithConfiguration
09-13 14:32:31.474 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1714: Landroid/widget/Button;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V
09-13 14:32:31.474 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.474 I/dalvikvm( 7455): Could not find method android.widget.Button.setAutoSizeTextTypeUniformWithPresetSizes, referenced from method androidx.appcompat.widget.AppCompatButton.setAutoSizeTextTypeUniformWithPresetSizes
09-13 14:32:31.474 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1715: Landroid/widget/Button;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V
09-13 14:32:31.474 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:32:31.474 I/dalvikvm( 7455): Could not find method android.widget.Button.setAutoSizeTextTypeWithDefaults, referenced from method androidx.appcompat.widget.AppCompatButton.setAutoSizeTextTypeWithDefaults
09-13 14:32:31.474 W/dalvikvm( 7455): VFY: unable to resolve virtual method 1716: Landroid/widget/Button;.setAutoSizeTextTypeWithDefaults (I)V
09-13 14:32:31.474 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x0004
09-13 14:54:18.784 W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/DisplayCutout;)
09-13 14:54:18.784 W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/DisplayCutout;)
09-13 14:54:18.784 W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/WindowInsets;)
09-13 14:54:18.794 W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/WindowInsets;)
09-13 14:54:18.794 W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/DisplayCutout;)
09-13 14:54:18.794 W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/DisplayCutout;)
09-13 14:54:18.794 I/dalvikvm( 7455): Could not find method android.app.NativeActivity.onRequestPermissionsResult, referenced from method org.koreader.launcher.MainActivity.onRequestPermissionsResult
09-13 14:54:18.794 W/dalvikvm( 7455): VFY: unable to resolve virtual method 178: Landroid/app/NativeActivity;.onRequestPermissionsResult (I[Ljava/lang/String;[I)V
09-13 14:54:18.794 D/dalvikvm( 7455): VFY: replacing opcode 0x6f at 0x000a
09-13 14:54:18.794 I/MainActivity( 7455): loading libluajit
09-13 14:54:18.834 D/dalvikvm( 7455): Trying to load lib /data/app-lib/org.koreader.launcher.fdroid-2/libluajit.so 0x41119478
09-13 14:54:18.834 D/dalvikvm( 7455): Added shared lib /data/app-lib/org.koreader.launcher.fdroid-2/libluajit.so 0x41119478
09-13 14:54:18.834 D/dalvikvm( 7455): No JNI_OnLoad found in /data/app-lib/org.koreader.launcher.fdroid-2/libluajit.so 0x41119478, skipping init
09-13 14:54:18.884 I/Assets  ( 7455): loading lib7z
09-13 14:54:18.884 D/dalvikvm( 7455): Trying to load lib /data/app-lib/org.koreader.launcher.fdroid-2/lib7z.so 0x41119478
09-13 14:54:18.884 D/dalvikvm( 7455): Added shared lib /data/app-lib/org.koreader.launcher.fdroid-2/lib7z.so 0x41119478
09-13 14:54:18.884 D/dalvikvm( 7455): No JNI_OnLoad found in /data/app-lib/org.koreader.launcher.fdroid-2/lib7z.so 0x41119478, skipping init
09-13 14:54:18.894 V/NativeGlue( 7455): User FIFO created at `/data/data/org.koreader.launcher.fdroid/files/alooper.fifo`
09-13 14:54:18.894 V/NativeThread( 7455): waiting for activity
09-13 14:54:18.904 I/EPD     ( 7455): Using Tolino/NTX driver
09-13 14:54:18.904 I/Lights  ( 7455): Using TolinoNTX driver
09-13 14:54:18.904 I/TolinoNtxController( 7455): loading libioctl
09-13 14:54:18.904 D/dalvikvm( 7455): Trying to load lib /data/app-lib/org.koreader.launcher.fdroid-2/libioctl.so 0x41119478
09-13 14:54:18.904 D/dalvikvm( 7455): Added shared lib /data/app-lib/org.koreader.launcher.fdroid-2/libioctl.so 0x41119478
09-13 14:54:18.904 D/dalvikvm( 7455): No JNI_OnLoad found in /data/app-lib/org.koreader.launcher.fdroid-2/libioctl.so 0x41119478, skipping init
09-13 14:54:18.904 V/Surface ( 7455): Using SurfaceView implementation
09-13 14:54:18.904 V/MainActivity( 7455): native orientation: portrait
09-13 14:54:18.914 V/EventReceiver( 7455): Filtering 3 events: 
09-13 14:54:18.914 V/EventReceiver( 7455): android.intent.action.DOWNLOAD_COMPLETE
09-13 14:54:18.914 V/EventReceiver( 7455): android.intent.action.ACTION_POWER_CONNECTED
09-13 14:54:18.914 V/EventReceiver( 7455): android.intent.action.ACTION_POWER_DISCONNECTED
09-13 14:54:18.914 V/NativeGlue( 7455): Start: 0x67d40e68
09-13 14:54:18.914 V/NativeGlue( 7455): Resume: 0x67d40e68
09-13 14:54:18.914 V/Timeout ( 7455): onResume: updating system timeout: 30
09-13 14:54:18.914 V/Timeout ( 7455): onResume
09-13 14:54:18.914 V/NativeGlue( 7455): InputQueueCreated: 0x67d40e68 -- 0x68217d08
09-13 14:54:18.934 D/Surface ( 7455): onAttachedToWindow()
09-13 14:54:19.174 V/NativeGlue( 7455): NativeWindowCreated: 0x67d40e68 -- 0x681fffe0
09-13 14:54:19.174 V/NativeThread( 7455): Activity window ready.
09-13 14:54:19.254 V/Surface ( 7455): surface changed {
09-13 14:54:19.254 V/Surface ( 7455):   width:  1072
09-13 14:54:19.254 V/Surface ( 7455):   height: 1448
09-13 14:54:19.254 V/Surface ( 7455):  format: TRANSPARENT
09-13 14:54:19.254 V/Surface ( 7455): }
09-13 14:54:19.264 V/NativeGlue( 7455): NativeWindowResized: 0x67d40e68 -- 0x681fffe0
09-13 14:54:19.344 V/NativeGlue( 7455): NativeWindowRedrawNeeded: 0x67d40e68 -- 0x681fffe0
09-13 14:54:19.364 V/NativeGlue( 7455): NativeWindowRedrawNeeded: 0x67d40e68 -- 0x681fffe0
09-13 14:54:19.484 V/NativeGlue( 7455): WindowFocusChanged: 0x67d40e68 -- 1
09-13 14:54:19.484 V/NativeThread( 7455): Activity gained focus.
09-13 14:54:19.484 V/NativeThread( 7455): Launching LuaJIT assets
09-13 14:54:19.894 I/Assets  ( 7455): Skip installation for revision v2024.07
09-13 14:54:19.984 I/dlopen  ( 7455): dl.dlopen - libs/libkoreader-lfs.so => /data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
09-13 14:54:19.984 V/dlopen  ( 7455):     dl.dlopen - needed => libluajit.so (1 of 2) <= /data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
09-13 14:54:19.984 V/dlopen  ( 7455):     dl.dlopen - libluajit.so => /data/app-lib/org.koreader.launcher.fdroid-2/libluajit.so
09-13 14:54:19.984 V/dlopen  ( 7455):         dl.dlopen - needed => libm.so (1 of 3) <= /data/app-lib/org.koreader.launcher.fdroid-2/libluajit.so
09-13 14:54:19.984 V/dlopen  ( 7455):         dl.dlopen - libm.so => /system/lib/libm.so
09-13 14:54:19.984 V/dlopen  ( 7455):         dl.dlopen - skipping /system/lib/libm.so (system lib)
09-13 14:54:19.984 V/dlopen  ( 7455):         dl.dlopen - needed => libdl.so (2 of 3) <= /data/app-lib/org.koreader.launcher.fdroid-2/libluajit.so
09-13 14:54:20.054 V/dlopen  ( 7455):         dl.dlopen - libdl.so => /system/lib/libdl.so
09-13 14:54:20.054 V/dlopen  ( 7455):         dl.dlopen - skipping /system/lib/libdl.so (system lib)
09-13 14:54:20.054 V/dlopen  ( 7455):         dl.dlopen - needed => libc.so (3 of 3) <= /data/app-lib/org.koreader.launcher.fdroid-2/libluajit.so
09-13 14:54:20.054 V/dlopen  ( 7455):         dl.dlopen - libc.so => /system/lib/libc.so
09-13 14:54:20.054 V/dlopen  ( 7455):         dl.dlopen - skipping /system/lib/libc.so (system lib)
09-13 14:54:20.054 V/dlopen  ( 7455):     sys_dlopen - loading library /data/app-lib/org.koreader.launcher.fdroid-2/libluajit.so (in local namespace)
09-13 14:54:20.054 V/dlopen  ( 7455):     dl.dlopen - needed => libc.so (2 of 2) <= /data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
09-13 14:54:20.054 V/dlopen  ( 7455):     dl.dlopen - libc.so => /system/lib/libc.so
09-13 14:54:20.054 V/dlopen  ( 7455):     dl.dlopen - skipping /system/lib/libc.so (system lib)
09-13 14:54:20.054 V/dlopen  ( 7455): sys_dlopen - loading library /data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so (in local namespace)
09-13 14:54:20.094 W/dlopen  ( 7455): could not find library rt.so.1
09-13 14:54:20.094 I/MainActivity( 7455): New intent: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher.fdroid/org.koreader.launcher.MainActivity bnds=[220,871][431,1145] (has extras) }.action
09-13 14:54:20.134 I/dlopen  ( 7455): dl.dlopen - libs/libutf8proc.so.3 => /data/data/org.koreader.launcher.fdroid/files/libs/libutf8proc.so.3
09-13 14:54:20.134 V/dlopen  ( 7455):     dl.dlopen - needed => libc.so (1 of 1) <= /data/data/org.koreader.launcher.fdroid/files/libs/libutf8proc.so.3
09-13 14:54:20.134 V/dlopen  ( 7455):     dl.dlopen - libc.so => /system/lib/libc.so
09-13 14:54:20.134 V/dlopen  ( 7455):     dl.dlopen - skipping /system/lib/libc.so (system lib)
09-13 14:54:20.134 V/dlopen  ( 7455): dl.dlopen - load_func -> /data/data/org.koreader.launcher.fdroid/files/libs/libutf8proc.so.3
09-13 14:54:20.224 W/dlopen  ( 7455): could not find library blitbuffer
09-13 14:56:56.184 V/NativeGlue( 7455): WindowFocusChanged: 0x67d40e68 -- 0
```
</details>

**Comment by pazos** [comment] 2024-09-15 21:48
duplicate of #12348

**Closed by pazos** 2024-09-15 21:48 UTC
Labels: Android
