### ISSUE TITLE
Missing text in Weblate 

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11767] opened 2024-05-07 11:09 UTC
* KOReader version: v. 2024.04-15
* Device: PB 628

#### Issue
I can't find the text "Show in items" and the options "highlighted text and note", "highlighted text" and "note, or highlighted text" in Weblate.

**Comment by Frenzie** [comment] 2024-05-07 11:29
It's caused by https://github.com/koreader/koreader/pull/11563#issuecomment-2094970832

**Comment by Frenzie** [comment] 2024-05-09 12:26
Fixed by https://github.com/koreader/koreader/pull/11784.

**Closed by Frenzie** 2024-05-09 12:26 UTC
Labels: i18n
