### ISSUE TITLE
Full screen refresh is not available in the screen settings

### ISSUE THREAD

**Issue by roaminghawk** [koreader/koreader#9282] opened 2022-07-02 16:52 UTC
* KOReader version: 2022.06
Device info:
Manufacturer: onyx
Brand: magicbook
Model: rk30sdk
Device: russia-magicbook-t62d
Product: magicbook a6lhd
Hardware: rk30board
Platform: rk3026

#### Issue
Hi,
I have an old [Buyoue] T62d flashed with an onyx firmware. eink full screen refresh is not available in the screen settings. I tried the compatibility test in developers options and the full screen refresh works fine when I select rk3026.

How do I enable the screen refresh options in the screen settings menu?

Thanks.

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by pazos** [comment] 2022-07-02 17:16
Duplicate of https://github.com/koreader/koreader/issues/8482

**Closed by pazos** 2022-07-02 17:16 UTC

**Comment by roaminghawk** [comment] 2022-07-02 18:58
I have root access to the device.
I can edit the build.prop file so KO can recognize the device as supported.
What should I change these values to:
ro.product.model=rk30sdk
ro.product.brand=Magicbook
ro.product.name=Magicbook A6LHD
ro.product.device=Russia-Magicbook-T62D
ro.product.board=Boyue T62D

Thanks

**Comment by pazos** [comment] 2022-07-02 19:55
wait a couple of days and support will come in a nightly.

In the mean time you're free to get that info yourself:

https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt
https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
