### ISSUE TITLE
FR: [zoom clicked area in comics to read text]

### ISSUE THREAD

**Issue by msh2050** [koreader/koreader#6406] opened 2020-07-20 12:17 UTC
It will be a great enhancement if we can show a box of a zoomed image from the clicked area.
I'm not a Lua developer (although it seems easy to learn) I need help to find these codes in the app to make my widget. 
1- handle touch (event and location)
2- crop the image
3- display the image from the buffer

I complete the development environment and find som good starting stuff.
any hit will be appreciated

regards

**Comment by poire-z** [comment] 2020-07-20 15:59
Can you explain your use case, and why it would be a great enhancement ?
With PDF only, or also with EPUBs ? (because in EPUBs, you can zoom on image, and increase the font size).
On PDF I understand it could be needed, but we have Reflow mode that usually helps when it's needed.

Anyway, no real code location to give to you. It depends on how you would like it to work, and how you would go at avoiding conflicts with the existing stuff that happens on touch :)
[For now](https://github.com/koreader/koreader/blob/201d3d8ad1c9e6432283439e3c14abfd9569bc2f/frontend/apps/reader/modules/readerhighlight.lua#L57-L84), touching a screen location, or drawing a rectangle would select the text (for dict lookup or for text highlighting). So, you'd have to make that an option to get that alternative behaviour - and find a way to toggle easily between the behaviours - or find an alternative yet not used gesture.
Nothing obvious comes to my mind that would avoid conflict - and code complexity :/

**Comment by msh2050** [comment] 2020-07-20 18:22
@poire-z thanks for replay
I attached two images to explain my use case... 
It will be great because reading CBZ files(manga/comics)  is difficult even with rotation/reflow... 

<img src="https://user-images.githubusercontent.com/9201213/87970780-e73e9980-cacc-11ea-9d8a-dcb8634afc17.jpg" width="300" />


<img src="https://user-images.githubusercontent.com/9201213/87970812-f6bde280-cacc-11ea-8486-1f9753ea1991.jpg" width="300" />

**Comment by Galunid** [comment] 2020-07-20 18:23
Perhaps `bottom menu -> page crop -> manual` may work for this purpose?

**Comment by poire-z** [comment] 2020-07-20 18:39
Thanks for the illustrative pictures :)

So I guess one option would be to have it done a bit like for EPUBs. In a PDF/PIC/CBZ...:
- detect if the Hold (long press) is on some text or some non text area (dunno if MuPDF/Kopt provides some API for that)
- if on text: dict lookup, or show the highlight dialog
- if on non-text, grab the whole page image and show it in the same ImageViewer widget that is used with EPUBs - possibly zooming x2 or x3 by default and centering it on the finger location in the original page: from there, you can Pan and zoom in/out to show more of it without the need to get back to the original page.

As detection might not be easy, and some users might want to zoom in text too, and to avoid having to change Page Crop, have it as an option in the `Highlight>` menu: highlight/dict/translate/zoom page for those only reading comics without much need for dicts.

All that might be just happening in there: https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerhighlight.lua

**Comment by msh2050** [comment] 2020-07-21 02:29
OK it is good starting I faced many issues but I get what i want
first:- the self.ui.document:getImageFromPosition(self.hold_pos, true) will only work with epub (not cbz) 
so I used screenshoter as a work around .. 

if I get help on how to get the image from the diplayed page it will be better
also if I have to go with screenshoter it will be better to shot to buffer  rather than save and load from file..

finally I add option on the menu to that will disable highlight if the zoom activated

it need some tweaks like specifying the image widget dimensions and add the save option for the menu and so on... butthis will be done after fix the above mentioned issues..
regards
  

original screen
<img src="https://user-images.githubusercontent.com/9201213/88004597-07437c80-cb10-11ea-934e-a8fc723c6144.png" width="300" />

zoomed screen:
<img src="https://user-images.githubusercontent.com/9201213/88004604-0ad70380-cb10-11ea-8f97-edc2bb196446.png" width="300" />

<img src="https://user-images.githubusercontent.com/9201213/88005466-23e0b400-cb12-11ea-9f92-5c784d992ac1.png" width="300" />

**Comment by poire-z** [comment] 2020-07-21 07:25
Pretty impressive how you got to get something working that quickly :)
Following up discussion in #6408 .

**Comment by Frenzie** [comment] 2020-07-21 14:32
Closing as a duplicate of #5524. Please feel free to copy anything pertinent over if desired. That being said, I think it's probably mostly covered by what's written in there.

**Closed by Frenzie** 2020-07-21 14:32 UTC
Labels: enhancement
