### ISSUE TITLE
[FR] Koreader reading statistics sync.

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#8245] opened 2021-09-22 19:41 UTC
I'm sorry but I didn't know where to suggest this.
I was wondering if you can make a plugin to sync the reading statistics on two or more devices, something like the progress sync in koreader.
Thank you.

**Comment by Zeyadas** [comment] 2021-09-26 08:36
Thanks.

**Comment by poire-z** [comment] 2022-01-21 21:55
Duplicate of #7058

**Closed by poire-z** 2022-01-21 21:55 UTC
Labels: enhancement

**Comment by myrxhw** [comment] 2024-07-25 08:09
+1

**Comment by poire-z** [comment] 2024-07-25 18:53
As it is said in the duplicated issue, this has been implemented by #9709 (via some cloud storage, not directly), and is available since v2022.11.
