### ISSUE TITLE
Integration in pocketbook menu

### ISSUE THREAD

**Issue by vimalaguti** [koreader/koreader#6415] opened 2020-07-22 10:24 UTC
Hi, with the latest pocketbook update there is a new menu. When you hold press a book from the pocketbook library, you can now select an "open with" submenu, from where you can choose pbreader 2 or reader 3. 
Would be nice if koreader can be added in this list too.
However I'm not sure where to look for, guess there is a documentation for the pocketbook SDK but I couldn't find it

**Comment by roshavagarga** [comment] 2020-07-29 13:00
@vimalaguti Which pocketbook? Which firmware?

**Comment by Galunid** [comment] 2020-07-29 13:23
This is a polish blog I came across that described something like this. It may be a bit outdated, so you can only **try this at your own risk**: http://cyfranek.booklikes.com/post/1862057/koreader-dla-czytnikow-pocketbook-rozszerza-mozliwosci
I assume you already have the firmware for your device downloaded and extracted:
> - copy contents of "applications" directory to "applications" directory on the ereader

> copy `koreader.app` file from "system/bin" directory to ereader's "system/bin" directory

> edit `extensions.cfg` file on ereader(in `system/config`). Change `epub:@EPUB_file:1:eink-reader.app:ICON_EPUB` to `epub:@EPUB_file:1:eink-reader.app,koreader.app:ICON_EPUB`; - important note: it's worth making a backup of this file, to edit it use Notepad++, or similar software(not MS Word/Libre office/etc.)

> save changed `extensions.cfg` file

> disconnect ereader

**Please remember, that I never owned Pocketbook nor do I plan to. Official installation guide is here:** https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices

**Comment by LucyOne** [comment] 2020-08-04 19:50
Galunid's plan should work. Any external reading software like KoReader and CoolReader needs to be listed in "extensionx.cfg". If the file doesn't exist, you can create it with Notepad++.

**Comment by vimalaguti** [comment] 2020-08-09 17:08
That works!
After the april Pocketbook update, I've found (in handlers.cfg) the new names of the default reader apps:
- "eink-reader_with_blink.app" which I suppose is the new pbreader3
- "eink-reader_with_epub2.app"

Because I don't know how to find the names of all the default apps, I've just added the epub line to "extensions.cfg":
epub:@EPUB_file:1:koreader.app,eink-reader_with_blink.app,eink-reader_with_epub2.app:ICON_EPUB

Now there is just a new "koreader.app" line in the menu and all 3 choices works fine. I think this info can be added to the wiki

**Comment by pazos** [comment] 2020-08-19 20:03
Duplicate of #3544

**Closed by pazos** 2020-08-19 20:03 UTC
Labels: PocketBook, firmware, help-wanted
