### ISSUE TITLE
Up to 36 seconds to open KOReader from KSM8

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2791] opened 2017-04-19 14:47 UTC
* KOReader version: last nightly versions
* Device: Kobo Mini

#### Issue
Since some weeks ago KOReader needs a lot of time to load from KSM. 
If I turn on the device, KSM loads in around 10 to 12 seconds, then it waits for 3 seconds (chosen delay in KSM configuration options), and needs around 27 to 36 seconds more to open KOReader. It opens on the file manager.
Before, KOReader could load much, much faster.
I haven't loaded more books, typefonts or anything like that. The only change in the contents of the device in these last weeks has been the OTA updates.

**Comment by liyiecho** [comment] 2017-04-19 15:05
Me too. After I delete KOReader and reinstall it, KOReader launch faster than before.

**Comment by Frenzie** [comment] 2017-04-19 15:27
I can confirm that it seems to take a few seconds in between between tapping KOReader and the first showing of the "loading blablabla" dialog whereas that used to be near-instantaneous. The quickstart guide (89099e2c940847442925d0f771f2ce95f133123e) would be the most logical culprit except I didn't notice that in testing.

Another possibility is the revised System Stats which seem to include a bunch of blocking `io.open`s (https://github.com/koreader/koreader/commit/999898fa69892ffa58da6b2458c3b7766cbee0df) except I assume those aren't executed until you start the dialog.

**Comment by Frenzie** [comment] 2017-04-19 15:35
@liyiecho Do you mean reinstall the latest nightly or an older one?

**Comment by retrue** [comment] 2017-04-19 16:33
I have just made a couple of tests.

# I just installed latest release (koreader-nightly-20170308).
- From turned off to KSM around 10 to 12 seconds, 3 seconds of programmed delay and then **4** seconds to load KOReader. 
- Exit KOReader, go back to KSM, and launch KOReader by pushing "start koreader". It loads in **1** second.

But now, I have an entirely new problem. 
I installed latest release, from March 3, just overwriting the current directory. Time loads are normal again, but whenever I tried to launch the menu, by tapping on the upper half on the device, it doesn't anything. If I do a short south swipe, KOReader crashes. I get a KSM error saying "KOReader exited irregularly".
So, I installed again the latest nighly (v2015.11-994) and firstly, it loads KOReader in 4 seconds and secondly, I get the same KSM error saying "KOReader exited irregularly" when trying to launch the menu with a swipe.
HELP!

**Comment by Frenzie** [comment] 2017-04-19 17:59
Tagging @Hzj-jie as this looks relates to  #2764

**Comment by retrue** [comment] 2017-04-19 18:04
The crash when swipping down could be the same as #2790
What about how to make work KOReader again in my device? Now neither the latest nightly build nor the latest relase work, when they worked before

**Comment by Frenzie** [comment] 2017-04-19 18:13
At a closer look, deleting the storagestat plugin dir should work.

**Comment by retrue** [comment] 2017-04-19 19:14
@Frenzie Thanks, that did the trick. KOReader doesn't crash now when triggering the menu, and for some reason, KOReader loads now as fast as before: in 1 second.
Well, I manually extracted one release on top of another, but that is the normal way of updating manually KOReader, so something should be done to prevent this problem.
Should I open a new ticket?

**Comment by AlanSP1** [comment] 2017-04-19 20:42
Just to mention, I always update koreader by manually copying new files over old ones. So far, this was good way of upgrading. But if we always need to delete storagestat dir, this should be added in upgrade info.

**Comment by Frenzie** [comment] 2017-04-19 20:45
If you manually overwrite one release with another (as opposed to using the built-in OTA update system) then stray files might get left behind. Usually that'll be nothing but a harmless, negligible waste of space but on rare occasions it could have unintended consequences. I'd say the recommended way for manual upgrades is to toss everything but your settings and data and the normal way is to use OTA.

**Comment by Hzj-jie** [comment] 2017-04-20 05:53
SystemStat plugin should be OK: its initialization function contains only a string assignment.

**Comment by houqp** [comment] 2017-04-21 11:11
Can anyone help briefly summarize how to reproduce this bug? We need to make sure things like this won't happen again in the future. I would like to get a proper fix for this.

**Comment by retrue** [comment] 2017-04-21 12:14
There are two bugs here:
- These 30 seconds or more to launch KOReader (when it should be around 1 to 4 seconds). I had done only OTA updates from previous versions.
- Crash after manual installation of a different version or even OTA update for some people. Same as 2790.

Both problems disappeared when deleting the storagestat plugin.

**Comment by Frenzie** [comment] 2017-04-21 13:11
Unfortunately I was wrong about the OTA update (it doesn't delete anything) and OTA vs manual should not make a difference. I still have that directory on my device yet it's not crashing.

**Comment by liyiecho** [comment] 2017-04-21 14:15
@Frenzie  @houqp 
My device is Kobo Aura One. When I used OTA update from v2015.11-988-g6542382 to v2015.11-995-gd6c81f5, some problems was happened. So I record it , here is the video [https://goo.gl/photos/PbBuM1XGWc4xWsb8A](url) and here is the crash.log [https://drive.google.com/open?id=0B6mjOyfMm6ZCbEI0UkdRcWNMdG8](url) .
But when I delete  the folder of KOReader and install the version >= v2015.11-994-ga1ec64b, KOReader can launch normally.

**Comment by retrue** [comment] 2017-04-22 11:00
The delay in launching KOReader is back.
I have done an OTA update from version 2015-11.994 to 2015-11.995.
The launching time has gone from 1 second to almost **20** seconds.
The plugin storagestat is disabled (i renamed it 2 days ago from main.lua to main.lua.old) and it solved the delay and crash problems. But now, with the storagestat plugin disabled, delay is back.

Crash.log:

---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 04/22/17-12:54:58

04/22/17-12:54:58 ERROR cannot open translation file: l10n/en_US/koreader.po
04/22/17-12:54:58 INFO  initializing for device Kobo_pixie
04/22/17-12:54:58 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
[ko-input] Forked off fake event generator(pid:888).
04/22/17-12:54:59 INFO  Loading plugins from directory: plugins
04/22/17-12:54:59 INFO  Plugin  plugins/kobolight.koplugin/main.lua  has been disabled.
04/22/17-12:54:59 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/22/17-12:54:59 WARN  Error when loading plugins/storagestat.koplugin/main.lua cannot open plugins/storagestat.koplugin/main.lua: No such file or directory
04/22/17-12:54:59 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin kosync at plugins/kosync.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
04/22/17-12:54:59 INFO  FM loaded plugin zsync at plugins/zsync.koplugin
04/22/17-12:56:38 INFO  no dialog left to show
04/22/17-12:56:38 INFO  quitting uimanager

**Comment by a-kohout** [comment] 2017-04-22 21:11
I noticed a 4 second delay with 994, then 10 seconds with 995.
It turns out that my patch #2752 is the culprit.
GNU tar wants to extract permissions if they're present in the archive.
Since FAT32 doesn't support them, it returns exit code 2.
Thus, the OTA package doesn't get renamed to `koreader-installed.tar` and `koreader.sh` applies the last OTA package at every launch. Clean installs aren't affected because no OTA package is present yet.
Simply ignoring the return code of tar should fix it.
Why there was no noticeable speed loss with the versions I tested the patch with is beyond me...
Can you try this?
```
--- koreader.sh	2017-04-21 08:12:49.000000000 +0200
+++ koreader_patched.sh	2017-04-22 23:05:03.000000000 +0200
@@ -12,7 +12,8 @@
 INSTALLED="${KOREADER_DIR}/ota/koreader.installed.tar"
 if [ -f "${NEWUPDATE}" ]; then
     # TODO: any graphic indication for the updating progress?
-    ./tar xf "${NEWUPDATE}" --strip-components=1 && mv "${NEWUPDATE}" "${INSTALLED}"
+    ./tar xf "${NEWUPDATE}" --strip-components=1
+    mv "${NEWUPDATE}" "${INSTALLED}"
 fi
 
 # load our own shared libraries if possible
```

**Comment by Frenzie** [comment] 2017-04-22 21:39
Yes, I'd noticed the same thing earlier today. It took me a while before I realized my SD card wasn't dying or some such, but the OTA update file didn't move and thus overwrote my changes.

Surely --no-same-permissions would be better?

**Comment by a-kohout** [comment] 2017-04-22 22:10
I stupidly looked at the man page of tar on os x which of course is the BSD flavor.
`--no-same-permissions --no-same-owner` seems to do the trick

**Closed** 2017-04-22 23:27 UTC
