### ISSUE TITLE
Koreader crashes when sharing highlights to markdown

### ISSUE THREAD

**Issue by 672493** [koreader/koreader#10072] opened 2023-02-03 10:18 UTC
* KOReader version: 2023.1
* Device: Samsung Galaxy note 10 plus, Android 12

#### Koreader always crashes when sharing highlights to markdown via Share all notes in this book menu.

<details>
  <summary>crash.log</summary>

```
--------- beginning of main
02-03 13:11:22.316 V/NativeGlue( 7047): Pause: 0x730aec8b90
02-03 13:11:22.510 E/reader.launche( 7316): Not starting debugger since process cannot load the jdwp agent.
02-03 13:11:22.513 E/USNET   ( 7316): USNET: appName: org.koreader.launcher
02-03 13:11:22.514 D/ProcessState( 7316): Binder ioctl to enable oneway spam detection failed: Invalid argument
02-03 13:11:22.520 D/ActivityThread( 7316): setConscryptValidator
02-03 13:11:22.520 D/ActivityThread( 7316): setConscryptValidator - put
--------- beginning of system
02-03 13:11:22.539 D/ActivityThread( 7316): handleBindApplication()++ app=org.koreader.launcher
02-03 13:11:22.540 D/CompatibilityChangeReporter( 7316): Compat change id reported: 171979766; UID 10594; state: DISABLED
02-03 13:11:22.567 V/GraphicsEnvironment( 7316): ANGLE Developer option for 'org.koreader.launcher' set to: 'default'
02-03 13:11:22.567 V/GraphicsEnvironment( 7316): App is not on the allowlist for updatable production driver.
02-03 13:11:22.574 D/LoadedApk( 7316): LoadedApk::makeApplication() appContext.mOpPackageName=org.koreader.launcher appContext.mBasePackageName=org.koreader.launcher
02-03 13:11:22.574 D/NetworkSecurityConfig( 7316): No Network Security Config specified, using platform default
02-03 13:11:22.581 D/NetworkSecurityConfig( 7316): No Network Security Config specified, using platform default
02-03 13:11:22.582 I/MultiDex( 7316): VM with version 2.1.0 has multidex support
02-03 13:11:22.582 I/MultiDex( 7316): Installing application
02-03 13:11:22.582 I/MultiDex( 7316): VM has multidex support, MultiDex support library is disabled.
02-03 13:11:22.600 D/ActivityThread( 7316): handleBindApplication() --
02-03 13:11:22.743 D/OpenGLRenderer( 7316): RenderThread::requireGlContext()
02-03 13:11:22.748 W/reader.launche( 7316): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
02-03 13:11:22.748 W/reader.launche( 7316): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
02-03 13:11:22.748 W/reader.launche( 7316): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
02-03 13:11:22.754 I/libEGL  ( 7316): EGL_ANDROID_blob_cache_path advertised, but unable to get eglSetBlobCachePathANDROID
02-03 13:11:22.760 D/OpenGLRenderer( 7316): RenderThread::setGrContext()
02-03 13:11:22.789 D/CompatibilityChangeReporter( 7316): Compat change id reported: 171228096; UID 10594; state: ENABLED
02-03 13:11:22.790 D/ScrollView( 7316): initGoToTop
02-03 13:11:22.797 I/DecorView( 7316): [INFO] isPopOver=false, config=true
02-03 13:11:22.797 I/DecorView( 7316): updateCaptionType >> DecorView@cad3d61[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
02-03 13:11:22.797 D/DecorView( 7316): setCaptionType = 0, this = DecorView@cad3d61[]
02-03 13:11:22.799 I/DecorView( 7316): getCurrentDensityDpi: from real metrics. densityDpi=560 msg=resources_loaded
02-03 13:11:22.810 I/MSHandlerLifeCycle( 7316): isMultiSplitHandlerRequested: ignored. pkg=org.koreader.launcher parent=null callers=com.android.internal.policy.DecorView.setVisibility:4294 android.app.ActivityThread.handleResumeActivity:5301 android.app.servertransaction.ResumeActivityItem.execute:54 android.app.servertransaction.ActivityTransactionItem.execute:45 android.app.servertransaction.TransactionExecutor.executeLifecycleState:176 
02-03 13:11:22.810 I/MSHandlerLifeCycle( 7316): removeMultiSplitHandler: no exist. decor=DecorView@cad3d61[]
02-03 13:11:22.826 I/ViewRootImpl@e5ede6a[CrashReportActivity]( 7316): setView = com.android.internal.policy.DecorView@cad3d61 TM=true
02-03 13:11:22.828 I/MSHandlerLifeCycle( 7316): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@cad3d61[CrashReportActivity]
02-03 13:11:22.829 I/MSHandlerLifeCycle( 7316): removeMultiSplitHandler: no exist. decor=DecorView@cad3d61[CrashReportActivity]
02-03 13:11:22.854 I/ViewRootImpl@e5ede6a[CrashReportActivity]( 7316): Relayout returned: old=(0,0,1440,3040) new=(0,0,1440,3040) req=(1440,3040)0 dur=12 res=0x200007 s={true 497325475248} ch=true fn=-1
02-03 13:11:22.855 D/ScrollView( 7316):  onsize change changed 
02-03 13:11:22.856 I/ViewRootImpl@e5ede6a[CrashReportActivity]( 7316): [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11387 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
02-03 13:11:22.856 D/hw-ProcessState( 7316): Binder ioctl to enable oneway spam detection failed: Invalid argument
02-03 13:11:22.861 D/OpenGLRenderer( 7316): eglCreateWindowSurface
02-03 13:11:22.863 I/Gralloc4( 7316): mapper 4.x is not supported
02-03 13:11:22.864 W/Gralloc3( 7316): mapper 3.x is not supported
02-03 13:11:22.868 I/gralloc ( 7316): Arm Module v1.0
02-03 13:11:22.869 W/Gralloc4( 7316): allocator 4.x is not supported
02-03 13:11:22.870 W/Gralloc3( 7316): allocator 3.x is not supported
02-03 13:11:22.990 I/ViewRootImpl@e5ede6a[CrashReportActivity]( 7316): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4987 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
02-03 13:11:22.990 I/ViewRootImpl@e5ede6a[CrashReportActivity]( 7316): [DP] rdf()
02-03 13:11:22.990 D/ViewRootImpl@e5ede6a[CrashReportActivity]( 7316): reportDrawFinished (fn: -1) 
02-03 13:11:23.010 I/ViewRootImpl@e5ede6a[CrashReportActivity]( 7316): MSG_WINDOW_FOCUS_CHANGED 1 1
02-03 13:11:23.010 D/InputMethodManager( 7316): startInputInner - Id : 0
02-03 13:11:23.010 I/InputMethodManager( 7316): startInputInner - mService.startInputOrWindowGainedFocus
02-03 13:11:23.018 D/InputMethodManager( 7316): startInputInner - Id : 0
02-03 13:13:03.165 I/ViewRootImpl@e5ede6a[CrashReportActivity]( 7316): ViewPostIme pointer 0

```
</details>

**Comment by hius07** [comment] 2023-02-03 10:54
Maybe duplicate of https://github.com/koreader/koreader/issues/10070.

**Comment by 672493** [comment] 2023-02-03 11:01
Export all notes in this book to markdown file works absolutely fine.

**Comment by NiLuJe** [comment] 2023-02-03 18:39
Then we're probably going to need an actual crash log, because that one is useless ;o).

(I *assume* this should be caught and displayed by the crash handler, but Android being what it is, you may have to resort to manual logcat'ing).

**Comment by 672493** [comment] 2023-02-06 18:18
I recorded a log (with matlog) while crashing. 
[2023-02-06-21-10-48.txt](https://github.com/koreader/koreader/files/10667893/2023-02-06-21-10-48.txt)

**Comment by NiLuJe** [comment] 2023-02-06 18:26
Nope, still nothing relevant :/.

**Comment by 672493** [comment] 2023-02-06 18:41
> Nope, still nothing relevant :/.

Is it possible to fix it somehow? Maybe change some settings in matlog? Or something else?

**Comment by 672493** [comment] 2023-04-20 09:08
Unfortunately sharing to markdown (as well as to other formats) still doesn't work, app crashes

**Closed** 2023-04-28 23:37 UTC
Labels: need more info, Android, Plugin
