### ISSUE TITLE
KOReader freezes after sleeping due to horizontal placement

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#7633] opened 2021-05-05 11:20 UTC
* KOReader version: 2021.04-15 (but with possible vestiges of an earlier debug version)
However, I have noticed this happen for a long time, on many versions, including before I installed the debug versions.
* Device: Kobo Aura One

#### Issue
When I lay my Kobo on a perfectly horizontal surface, it often goes to sleep within a minute.  In that case, after I pick it up again, close and re-open the flap to wake it, and touch the screen (I have the setting "Keep screen saver on screen after waking - I tap"), the document reappears (I happens with e-pubs, and I think with pdfs too), the system often freezes after about a minute.  If the backlight were on it goes off, so maybe it goes to sleep without changing the image.  Often I need to go through the waking ritual (closing flap, opening flap, touching screen) several times before KOReader decides to remain alert.

#### Steps to reproduce
See above.
1. Depose the Kobo, with the cover open, on a perfectly horizontal surface.
2. It may go to sleep within a minute.  If not, retry.
3. Pick up the Kobo, close the flap, reopen the flap, and touch the screen.
4. The document will appear; any backlight will already have appeared after reopening the flap.
5. Start reading, and wait.  One can turn some pages in the meantime, or open a menu.
6. After about a minute, the device may apparently go to sleep, but without showing the screen saver image.  If not, retry.

It is intermittent, unfortunately, and not extremely frequent either, so it may require a lot of retries.  Strangely enough the going to sleep (and hence the subsequent freezing) seems to happen more on some surfaces than on others..

##### `crash.log` (if applicable)
No crash appears, and right now I can't reproduce it.
[Here is the crash.log, though](https://github.com/koreader/koreader/files/6426672/crash.log).  From 12:41 on I tried, using different types of documents.  It was with the epub that it fell asleep. - at the very end, around 13:05 there was a quick sleep after putting on a horizontal surface, but it didn't freeze upon wake-up.  I know the log covers earlier instances where it did, though, so maybe you can find them.

**Comment by Biep** [comment] 2021-05-05 13:43
Funny - trying to massage KOReader into freezing, I must have triggered something.  While I was in the dictionary - long-pressing a word to get a second dictionary pop-up open, it suddenly went to sleep.  And shortly after reawakening it froze.  No horizontal surface - I had the reader in my hand.
Now the log seems to show something going on:
```
05/05/21-15:09:13 INFO  opening file /mnt/onboard/D/Vasileiadis, Pavlos D_/Aspects of rendering the sacred Tetragrammaton in Greek.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
05/05/21-15:09:14 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin calibre at plugins/calibre.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin gestures at plugins/gestures.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin movetoarchive at plugins/movetoarchive.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin opds at plugins/opds.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin profiles at plugins/profiles.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin qrclipboard at plugins/qrclipboard.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
05/05/21-15:09:14 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
05/05/21-15:09:14 INFO  setting zoom mode to contentwidth
05/05/21-15:33:29 INFO  WakeupMgr: scheduling wakeup in 86400
05/05/21-15:33:33 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_MONOTONIC
05/05/21-15:33:38 INFO  Kobo resume: clean up after wakeup
05/05/21-15:33:38 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
05/05/21-15:33:41 INFO  WakeupMgr: scheduling wakeup in 86400
05/05/21-15:33:43 INFO  Kobo resume: clean up after wakeup
05/05/21-15:33:43 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
05/05/21-15:33:43 INFO  GestureDetector:probeClockSource: Touch event clock source detection was inconclusive
05/05/21-15:33:58 INFO  Kobo suspend: going to sleep . . .
05/05/21-15:33:58 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
05/05/21-15:34:00 INFO  Kobo suspend: waited for 2s because of reasons...
05/05/21-15:34:00 INFO  Kobo suspend: synced FS
05/05/21-15:34:00 INFO  Kobo suspend: asking for a suspend to RAM . . .
05/05/21-15:34:00 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
05/05/21-15:34:01 INFO  Kobo suspend: woke up!
05/05/21-15:34:16 ERROR Kobo suspend: putting device back to sleep. Unexpected wakeups: 1
05/05/21-15:34:16 INFO  Kobo suspend: going to sleep . . .
05/05/21-15:34:16 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
05/05/21-15:34:18 INFO  Kobo suspend: waited for 2s because of reasons...
05/05/21-15:34:18 INFO  Kobo suspend: synced FS
05/05/21-15:34:18 INFO  Kobo suspend: asking for a suspend to RAM . . .
05/05/21-15:34:18 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
05/05/21-15:34:19 INFO  Kobo suspend: woke up!
05/05/21-15:34:34 ERROR Kobo suspend: putting device back to sleep. Unexpected wakeups: 2
05/05/21-15:34:34 INFO  Kobo suspend: going to sleep . . .
05/05/21-15:34:34 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
05/05/21-15:34:36 INFO  Kobo suspend: waited for 2s because of reasons...
05/05/21-15:34:36 INFO  Kobo suspend: synced FS
05/05/21-15:34:36 INFO  Kobo suspend: asking for a suspend to RAM . . .
05/05/21-15:34:36 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
05/05/21-15:34:36 INFO  Kobo suspend: woke up!
05/05/21-15:34:51 ERROR Kobo suspend: putting device back to sleep. Unexpected wakeups: 3
05/05/21-15:34:51 INFO  Kobo suspend: going to sleep . . .
05/05/21-15:34:51 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
05/05/21-15:34:53 INFO  Kobo suspend: waited for 2s because of reasons...
05/05/21-15:34:53 INFO  Kobo suspend: synced FS
05/05/21-15:34:53 INFO  Kobo suspend: asking for a suspend to RAM . . .
05/05/21-15:34:53 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
05/05/21-15:34:53 INFO  Kobo suspend: woke up!
05/05/21-15:35:08 ERROR Kobo suspend: putting device back to sleep. Unexpected wakeups: 4
05/05/21-15:35:08 INFO  Kobo suspend: going to sleep . . .
05/05/21-15:35:08 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
05/05/21-15:35:10 INFO  Kobo suspend: waited for 2s because of reasons...
05/05/21-15:35:10 INFO  Kobo suspend: synced FS
05/05/21-15:35:10 INFO  Kobo suspend: asking for a suspend to RAM . . .
05/05/21-15:35:10 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
05/05/21-15:35:10 INFO  Kobo suspend: woke up!
05/05/21-15:35:25 ERROR Kobo suspend: putting device back to sleep. Unexpected wakeups: 5
05/05/21-15:35:25 INFO  Kobo suspend: going to sleep . . .
05/05/21-15:35:25 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
05/05/21-15:35:27 INFO  Kobo suspend: waited for 2s because of reasons...
05/05/21-15:35:27 INFO  Kobo suspend: synced FS
05/05/21-15:35:27 INFO  Kobo suspend: asking for a suspend to RAM . . .
05/05/21-15:35:27 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
05/05/21-15:39:12 INFO  Kobo suspend: woke up!
05/05/21-15:39:12 INFO  WakeupMgr: scheduling wakeup in 86400
05/05/21-15:39:15 INFO  Kobo resume: clean up after wakeup
05/05/21-15:39:15 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
05/05/21-15:39:16 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_MONOTONIC
05/05/21-15:39:58 INFO  quitting uimanager
```

**Comment by NiLuJe** [comment] 2021-05-05 16:23
Can't tell you anything without *verbose* debug logs, but that very much smells like the hall sensor tripping, possibly because the smart cover is folded to the *back* of the device, and trips the sensor from the back?

**Comment by NiLuJe** [comment] 2021-05-05 16:23
(Bacuse after highly scientific examination, approximately 147% of "my Kobo is doing wonky sleep things" issues are due to "Smart" covers ;)).

**Comment by Biep** [comment] 2021-05-06 15:16
Sounds not improbable.  The next time it freezes, I'll see whether taking the flap from the back helps prevent sleeping disease.

**Comment by Biep** [comment] 2021-05-06 18:44
Yep, seems to be it.
It seems still a bug that KOReader goes to sleep without showing the screen saver image.

Also - I did an update today (development), so that may be it too, but suddenly the light goes off a few seconds after I switch it on.  It doesn't know it - toggling again says "Light off", and the light indicator also shows it is on - but it isn't.
This is consistently repeatable (for me, swiping down at the left of the screen toggles the light.)

**Comment by NiLuJe** [comment] 2021-05-06 22:32
Again, hard to say without verbose debug logs, but if it's a sleep tripped during a "I should be asleep because SleepCover" session, then it will sleep with no feedback, because it assumes that it's not a user-triggered sleep, and a such the sleep screen is *already* shown (i.e., that was an unexpected wakeup).

**Comment by Frenzie** [comment] 2021-05-07 09:47
A user might opt to disable the screensaver with leave screen as is. (I use that plus a little message myself.)

**Comment by Biep** [comment] 2021-05-07 10:04
But the reader works for a minute or so, so it ought to know it is not sleeping..?

**Comment by Biep** [comment] 2021-05-07 11:33
Then this issue would already have proven its usefulness.  Freezing *feels* worse than sleeping, even if in reality it is less than sleeping..

**Comment by NiLuJe** [comment] 2021-05-07 12:42
Again, can't tell you without logs, but it feels like you were actually "mistakenly" using the reader in-between unexpected wakeups.

**Comment by Frenzie** [comment] 2021-05-07 12:51
> Again, can't tell you without logs, but it feels like you were actually "mistakenly" using the reader in-between unexpected wakeups.

But in that case shouldn't the system decide it's properly woken up?

**Comment by Biep** [comment] 2021-05-07 13:22
Well, I gave logs, though probably not as verbose as you'd want.  Would that require installing a debug version again?
Is there a verbosity setting?

**Comment by Frenzie** [comment] 2021-05-07 15:23
Plain debug logs can be enabled in developer options (that's file manager → tools → dev options)

**Comment by Biep** [comment] 2021-05-07 15:35
Just read this now, when coming here to provide more data - with plain logs still.
[Crash.log](https://github.com/koreader/koreader/files/6442738/Crash.log)
I put the Aura on the flat surface again, simply in normal usage, and it went in sleep mode.  Maybe this is because of the flap being folded back, though apart from once I have never been able to trigger this by pressing the folded-back flap against the device.
After waking, I switched on the light, and soon it froze, the light going out again of course.  Upon waking again, the light stayed off (though the system thought it was on).  Then it froze again, and I woke it again.  All the time I have been careful to keep the flap well away from the device, so none of this latter behaviour could be sleep cover interference.
Have enabled verbose debug logs now, so I am hoping it will happen again.

**Comment by NiLuJe** [comment] 2021-05-07 16:42
Okay, you have BackgroundRunner running, so, I assume it's because of the autowarmth thingy. That could very well explain the lights aspect of things, at least.

I'm seeing a few possibly spurious SleepCover event, hard to say which are user-triggered or not, but the sleep at 05/07/21-17:43:23 looks super shady.

The final crash is your usual weird segfault that I can't tell much about without a backtrace from a debug build ;p.

----

So, I'd try without Backgroundrunner (and/or whatever uses it, which i think is the warmth stuff), that should hopefully deal with the light.

And without the SleepCover for the other thing ;p.

I'll be playing with magnets to see if I can reproduce any of that...

**Comment by Biep** [comment] 2021-05-07 16:49
It basically only happens at one spot, and I see I tend to drop the reader with some force on the corner of the surface, such that at the first moment of impact only the centre third of the right hand side hits the surface.  So that bit of the flap gets a push towards the Aura itself.  That only lasts a fraction of a second, though, as the reader falls flat and the pressure divides evenly over a large surface.  So if the sleep is triggered by a very short magnet action, building in a second or so of delay before deciding to go to sleep might solve it.

Those segfaults have become truly rare - so the fact I created one now made me think the issues might be related.

So you tell me to switch warmth off, and see whether that solves it?  It will be hard to say anyway, given the intermittence of the event, which already requires a somewhat rare quick sleep.

**Comment by NiLuJe** [comment] 2021-05-07 16:53
The Cover events I can see here all last between 2 to 10s (between the "in proximity" to "not in proximity" events), so, depends on any of those were meant to be that way or not at all ^^.

We already delay actual sleep by a significant amount of time to deal with such nonsense, but there's no silver bullet.

**Comment by NiLuJe** [comment] 2021-05-07 16:54
There's also an existing option to ignore the "out of proximity" events to alleviate some of that when it's truly too erratic to deal with heuristically. But that involves waking the device via power button.

**Comment by Biep** [comment] 2021-05-07 16:55
You are not in the Netherlands, or western Germany, by the way?  I am not far from Nijmegen, so if so I might be able to give you physical access to my Aura.

**Comment by NiLuJe** [comment] 2021-05-07 16:55
Nope, Paris suburbs ;).

**Comment by Biep** [comment] 2021-05-07 16:56
Dommage.  Deux frontières à passer, pendant le (la?) covid..  C'est trop.

**Comment by Biep** [comment] 2021-05-07 16:59
I haven't been able to get the quick sleep on any other surface, so physical access to the Aura might not be enough - you'd also need physical access to the corner of my bathtub. 🛁

**Comment by NiLuJe** [comment] 2021-05-07 17:00
(*la* for the disease, *le* for the virus, which, err, rattled some folks back in the day ^^).

**Comment by Biep** [comment] 2021-05-07 17:00
Le covid cause la covid.  D'accord.

**Comment by NiLuJe** [comment] 2021-05-07 17:14
Stupid question: was Wi-Fi on at the time? It doesn't look like it from the logs, but that could add potentially random delays in the mix that might make the race weirder to deal with...

**Comment by Biep** [comment] 2021-05-07 20:31
No, I am sure it wasn't.  Just to make sure, I checked just now, and it was off.  If anything X done between my last log and now did switch it off, since I have done all those things many times since the update (i.e. when I switched it on the last time), even if I had forgotten to switch it off again, that off-switching thing X would would have done it well before that log.

And my battery lasts only two or three days with WiFi off - despite the publicity claiming a month.  I'd certainly have noticed the extra drain.

**Comment by Biep** [comment] 2021-05-07 20:39
The weird thing is that the back-folded sleepcover may well cause the sleep - but why is the awakening different depending on whether the sleep was caused by a closed or an back-folded cover?  I only get the freezing after a quick sleep, i.e. one that happens with a back-folded cover.

**Comment by NiLuJe** [comment] 2021-05-07 21:32
Because we know whether the cover is (supposedly) opened or closed.

**Comment by NiLuJe** [comment] 2023-03-08 17:59
Closing this one, many many things have changed since the original report.

Re-open if necessary.

**Closed by NiLuJe** 2023-03-08 17:59 UTC
Labels: need more info
