### ISSUE TITLE
KOReader emulator build and run errors in macOS Mojave 10.14.1

### ISSUE THREAD

**Issue by pdrygas** [koreader/koreader#4448] opened 2019-01-05 12:58 UTC
* KOReader version: master - ee673b1e101832a0e122b820c87d178739d24765
* Device: macOS Mojave 10.14.1

#### Issue
I ran into numerous issues while trying to build and run KOReader emulator on ma Mac strictly following the instructions in README. I managed to find workarounds for some of them but others still prevent me from a successful build. I've run through other macOS-related KOReader issues but didn't find any similar to the errors occurring to me.

#### Steps to reproduce
- clone the repo
- execute (as mentioned in README)
`brew install nasm binutils libtool autoconf automake cmake makedepend sdl2 lua@5.1 luarocks gettext pkg-config wget md5sha1sum
echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> "$HOME"/.bash_profile`
- set MACOSX_DEPLOYMENT_TARGET to 10.09 (as mentioned in README)
- `cd koreader && ./kodev build` _(some errors occur at this stage)_
-  `./kodev run` _(while other happens when trying to run the emulator,)_

#### Expected behaviour
KOReader emulator is built without any errors, running it results 

##### Firstly

clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "_dewarpBuildPageModel_ex", referenced from:
      _wlept_bmp_dewarp in wleptonica_dyn.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [libk2pdfopt.2.dylib] Error 1
make[4]: *** [libk2pdfopt-prefix/src/libk2pdfopt-stamp/libk2pdfopt-build] Error 2
make[3]: *** [CMakeFiles/libk2pdfopt.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build/x86_64-apple-darwin18.2.0-debug/libs/libk2pdfopt.2.dylib] Error 2
make: *** [base/build/-debug/luajit] Error 2
Failed to build emulator! Try run with -v for more information.

##### Workaround
I've found out that k2pdfopt has been recently upgraded. I then reverted the bump which let the build progress further

##### Then
[*] Install plugins
cp -R plugins/. koreader-emulator--debug/koreader/plugins/.
cp: koreader-emulator--debug/koreader/plugins/.: No such file or directory
cp: plugins/.: unable to copy extended attributes to koreader-emulator--debug/koreader/plugins/.: No such file or directory
cp: koreader-emulator--debug/koreader/plugins/./systemstat.koplugin: No such file or directory
cp: plugins/./systemstat.koplugin: unable to copy extended attributes to koreader-emulator--debug/koreader/plugins/./systemstat.koplugin: No such file or directory
cp: koreader-emulator--debug/koreader/plugins/./systemstat.koplugin/_meta.lua: No such file or directory
_(more of similar no such file errors)_
make: *** [all] Error 1
Failed to build emulator! Try run with -v for more information.

##### Workaround
I created koreader-emulator--debug/koreader/plugins directory with mkdir which let the build progress further

##### Then
[*] Installresources
cp -R -pL resources/fonts/. koreader-emulator--debug/koreader/fonts/.
cp: koreader-emulator--debug/koreader/fonts/.: No such file or directory
cp: resources/fonts/.: unable to copy extended attributes to koreader-emulator--debug/koreader/fonts/.: No such file or directory
cp: koreader-emulator--debug/koreader/fonts/./droid: No such file or directory
cp: resources/fonts/./droid: unable to copy extended attributes to koreader-emulator--debug/koreader/fonts/./droid: No such file or directory
cp: koreader-emulator--debug/koreader/fonts/./droid/DroidSansMono.ttf: No such file or directory
cp: koreader-emulator--debug/koreader/fonts/./droid/NOTICE: No such file or directory
cp: utimes: koreader-emulator--debug/koreader/fonts/./droid: No such file or directory
cp: chown: koreader-emulator--debug/koreader/fonts/./droid: No such file or directory
cp: chmod: koreader-emulator--debug/koreader/fonts/./droid: No such file or directory
cp: chflags: koreader-emulator--debug/koreader/fonts/./droid: No such file or directory
cp: resources/fonts/./droid: unable to copy ACL to koreader-emulator--debug/koreader/fonts/./droid: No such file or directory
cp: koreader-emulator--debug/koreader/fonts/./freefont: No such file or directory
-- mkdir koreader-emulator--debug/koreader/fonts
_(more of similar no such file errors)_

##### Workaround
I created koreader-emulator--debug/koreader/fonts directory with mkdir which let the build progress further

##### Then
[*] Install plugins
cp -R plugins/. koreader-emulator--debug/koreader/plugins/.
for d in $(ls koreader-emulator--debug/koreader/plugins); do \
		test -d plugins/$d || rm -rf koreader-emulator--debug/koreader/plugins/$d ; done
[*] Installresources
cp -R -pL resources/fonts/. koreader-emulator--debug/koreader/fonts/.
install -d koreader-emulator--debug/koreader/{screenshots,data/{dict,tessdata},fonts/host,ota}
[*] Running KOReader with arguments: ...
~/sources/koreader/koreader-emulator--debug/koreader ~/sources/koreader
./kodev: ./reader.lua: ./luajit: bad interpreter: No such file or directory
~/sources/koreader

##### Stuck
I checked the ./reader.lua and found out that what follows shebang was `#!./luajit`. I tried substituting `/.luajit` with `luajit` and made sure that `luajit` is in my PATH but it did not helped. At this point I gave up reckoning that some of you guys must've ran into this problem before and could land a helping hand.

**Comment by Frenzie** [comment] 2019-01-05 13:52
Oh yeah, it's actually shown correctly higher up:

> make[1]: *** [build/x86_64-apple-darwin18.2.0-debug/libs/libk2pdfopt.2.dylib] Error 2

So `clang -dumpversion` returns `x86_64-apple-darwin18.2.0`.

You didn't specify how you reverted the bump exactly. That might be key to where things went wrong for you. For example, fonts were moved into a separate repo at some point, so you'd have to `git submodule init` (./kodev fetch-thirdparty), etc. My guess is you introduced some problem there. You could delete files selectively or just `./kodev clean` it all.

**Comment by NiLuJe** [comment] 2019-01-05 17:49
There *might* be some case-sensitivity FS shenanigans, possibly?

On which FS was the build run, and is it in a non-default configuration as far as case sensitivity is concerned?

**Comment by pazos** [comment] 2019-01-05 18:46
I'm not at home  right now but built last week (or maybe two weeks ago) without problems on APFS.

./kodev clean && ./kodev fetch-thirdparty maybe?

**Comment by pazos** [comment] 2019-01-05 22:42
Ok, I got this error too:
```
Undefined symbols for architecture x86_64:
"_dewarpBuildPageModel_ex", referenced from:
_wlept_bmp_dewarp in wleptonica_dyn.o
ld: symbol(s) not found for architecture x86_64
```
I had to revert to libk2pdfopt commit 9aec09f52bf72bd7b747172c446d462c8b88f6b4 to be able to build. (I edited base/thirdparty/libk2pdfopt/CMakeLists.txt)

I can't reproduce the other issues mentioned by OP. Emulator runs fine here! (typing ./kodev run performs the build step for openssl each time).

**Comment by NiLuJe** [comment] 2019-01-06 00:10
Actually a bug everywhere, otool's probably being a tad more stringent regarding undefined symbol here for some reason.

(That symbol's from leptonica_mod/dewarp2.c, which we do not currently build)

**Comment by NiLuJe** [comment] 2019-01-06 00:15
Not quite motivated enough to look into it, as newer k2pdfopt versions are out, and have moved to Tesseract 4 & up-do-date leptonica/mupdf, which might be a giant mess to update on our end, for features I'ver never ever used.

**Comment by NiLuJe** [comment] 2019-01-06 17:45
In the meantime, it *might* be possible to paper it over by convincing the linker that we don't care about leaving this symbol undefined (as that doesn't seem to be an issue in practice), but I'm not quite familiar enough with macOS's linker to come up with a solution OTOH ;).

**Comment by NiLuJe** [comment] 2019-01-06 17:48
A quick google trip yields two possible solutions:

Generic, Linux-style linking:
```-undefined dynamic_lookup```

Per-symbol override:
```-U _dewarpBuildPageModel_ex```

**Comment by pdrygas** [comment] 2019-01-06 20:05
Wow, thank you guys for the numerous and helpful answers. And indeed were the helpful as I finally managed to build and run the emulator.

For that the first problem describes by me has already been reproduced and confirmed to be a bug I guess there's more I can help here with. Just to answer your question @Frenzie about how I had worked around it - I did exactly the same thing pazos did which was reverting (_git revert_) the commit which introduced the library bump. Also, I believe the issue might have not reproduced for you because of the different architecture - you mentioned` x86_64-apple-darwin17.0.0`
 in your code snippet, was that executed on the VM you used to reproduce my problem? It's `x86_64-apple-darwin18.2.0` on my machine and given the nature of this bug I believe this may be a key difference which rendered your attempt at triggering the bug incomplete.

@NiLuJe if by FS you mean filesystem then it's APFS.

The input from @poire-z was the game changer for me here. The double dash in` koreader-emulator--debug` started looking odd now that you mentioned it. I traced down the origin of this the variable holding it and found this https://github.com/koreader/koreader-base/blob/59cc50185842f3e04341af17f0c8a380cbf4f971/Makefile.defs#L504

**Once I changed** `OUTPUT_DIR?=build/$(MACHINE)` **to**  `OUTPUT_DIR?=build/x86_64-apple-darwin18.2.0-debug` **and ran the build again it completed successfully.**

Now here's the interesting part: I decided to investigate a bit more, reverted my change (back to `OUTPUT_DIR?=build/$(MACHINE)`) and added some logging to Makefile in base, i.e. `$(info ************ OUTPUT: "$(OUTPUT_DIR)" **********)` at the top of it and `	@echo $(OUTPUT_DIR)` further down, around the area where the build was failing at first. And to my surprise `build/x86_64-apple-darwin18.2.0-debug` was logged both times ... To make it even weirder, further down the log OUTPUT_DIR is still evaluated to `koreader-emulator--debug`. See it for yourselves guys

#### with Makefile.defs untouched 
<img width="1065" alt="screenshot 2019-01-06 at 19 49 49" src="https://user-images.githubusercontent.com/24194701/50740345-6fac6080-11ed-11e9-9e31-b5771855d7be.png">

##### gives
<img width="1399" alt="screenshot 2019-01-06 at 21 02 05" src="https://user-images.githubusercontent.com/24194701/50740900-65429480-11f6-11e9-9ba0-a3d52ce201a7.png">


 Have no idea what to make of it, is there some preprocessing magic going on here which substitutes `@echo $(OUTPUT_DIR)` with `build/x86_64-apple-darwin18.2.0-debug` but omits occurrences of `$(OUTPUT_DIR)` which are then being rendered to `koreader-emulator--debug`?

**Comment by NiLuJe** [comment] 2019-01-06 20:47
That *might* be a bsdmake vs. gnu make artefact?

I don't recall what we do on macOS, and wether the default on the OS side is actually still bsdmake, but that'd be one thing worth looking inot for weird stuff like that ;).

**Comment by pdrygas** [comment] 2019-01-09 16:52
I had no luck with investigating the issue further. Given the workaround is fine for me I'll probably rely on it, at least for the time being. 

@NiLuJe I have a quick question about KOReader plugin development, I thought I'll ask it here rather than create a new ticket: is there a way to reload a plugin quickly without the need to stop the emulator and run it again?

**Comment by Frenzie** [comment] 2019-01-09 17:35
I don't think there is. Personally I often find it easier to just quickly close the program even when it's not strictly necessary. It takes about a second. :-)

**Comment by pdrygas** [comment] 2019-01-09 22:07
Got it, thanks for the prompt response guys.

**Comment by pazos** [comment] 2019-08-18 22:41
@NiLuJe: In order to build the master branch I needed to enter into the leptonica build dir and enter the command `autoreconf -i`. The rest of the build went fine.

**Comment by NiLuJe** [comment] 2019-08-18 23:05
Huh. Good to know, that's easy enough to fix, we already have a number of things doing an |autoreconf -fi` pass (basically, anything git, or that patches autotools, so, err, a lot :D).

**Comment by pazos** [comment] 2019-11-04 19:32
Fixed by @NiLuJe in https://github.com/koreader/koreader/pull/5549

**Closed by pazos** 2019-11-04 19:32 UTC
Labels: bug, out-of-date
