### ISSUE TITLE
Screen sizing on Pixel 2 XL: nav bar cuts off bottom.

### ISSUE THREAD

**Issue by curiousclinician** [koreader/koreader#3628] opened 2018-01-25 19:02 UTC
* KOReader version: all of them (android .apk)
* Device: Pixel 2 XL fully updated

As has been the case for many apps, my newer android phone nav bar cuts off the bottom of the app display area.  The fix is apparently quite simple, but I don't have the skill to implement it:

https://developer.android.com/training/system-ui/navigation.html

This is a brilliant app! Thank you.

**Comment by Frenzie** [comment] 2018-01-25 19:43
What version of Android is that? On Android 6 I think I can reproduce some odd issues in this regard but on Android 8 it looks like all you need is a tap.

**Comment by curiousclinician** [comment] 2018-01-25 20:20
8.1.0 android

From what I've read the pixel phones are particularly bad for this problem. Tapping does not fix the problem for me, it just lights up the navigation bar buttons.

**Comment by Frenzie** [comment] 2018-01-25 20:32
I meant a tap as in forcing KOReader to draw more stuff. (Page change, open book, that kind of thing.)

What I'm seeing on Android 8:

1. When starting KOReader, there's a brief time when the navbar and statusbar are on screen.
2. They fade out.
3. There's a weird black bar at the bottom of KOReader (not navbar; just leftover black of some sort).

**Comment by curiousclinician** [comment] 2018-01-25 20:36
Nope, definitely no effect. The bottom half of the lower menu is unusable and pages are missing the bottom of every page regardless of page turns.

**Comment by curiousclinician** [comment] 2018-01-25 20:37
And by missing I mean text is actually truncated mid way through a line in reflow.

**Comment by Frenzie** [comment] 2018-01-25 20:37
As a workaround you can play around a little with Settings → Display → Fullscreen. Unfortunately you'll have to do it every time you start the program.

Just to make absolutely sure, the text is missing due to the full navbar, not a weird black bar artifact the size of the navbar?

**Comment by curiousclinician** [comment] 2018-01-26 17:25
I'm not sure... I know the nav bar pops up in that space... Here is a capture (after setting to fullscreen, which changes nothing) before and after I swipe up for the navbar buttons.

![screenshot_20180126-122302](https://user-images.githubusercontent.com/8451988/35452241-e5fe53fc-0293-11e8-8e1e-34529e80cdbb.png)
![screenshot_20180126-122324](https://user-images.githubusercontent.com/8451988/35452242-e621963c-0293-11e8-99d8-2344d46d03ef.png)

Google really screwed up when they made this phone... so sad.

**Comment by Frenzie** [comment] 2018-01-26 17:39
Hm, that's pretty bizarre. Unfortunately I'm somewhat out of space for the 8.1 emulator, though I wouldn't really expect it to differ much from 7 and 8.

**Comment by Frenzie** [comment] 2018-03-06 19:49
@curiousclinician Might be fixed by https://github.com/koreader/koreader/pull/3721

Could you please check the latest nightly?

http://build.koreader.rocks/download/nightly/

**Comment by curiousclinician** [comment] 2018-03-07 01:29
Crashes on load. :(

Running Android 8.1.0

I was running an older version with partial success.

Thanks for looking at this!

Nathan

**Comment by Frenzie** [comment] 2018-03-07 06:24
Given your screenshot that might be because of night mode. #3529

**Comment by curiousclinician** [comment] 2018-03-07 06:27
Crashes with night mode disabled...  Hmm.

I guess I should just go back to an old version?  By installing tray-hiding
apps I've managed to be able to read without losing a line every screen.

**Comment by Frenzie** [comment] 2018-03-07 06:41
If you want to keep on using the program right now and it crashes then of course. :-P

But before you do, are you able to get an adb logcat out of the crash?

**Comment by Frenzie** [comment] 2018-03-07 07:17
Btw, here are some screenshots from my Android 8.1 emulator. The bottom navigation bar having an odd effect is something I was able to reproduce but no crashes. Note that you'd have to disable night mode in `koreader/settings.reader.lua`. I'm not talking about something in Android itself, should that be a thing.

![screenshot_1520406503](https://user-images.githubusercontent.com/202757/37078372-447ed18a-21df-11e8-8286-e224ae6c3aea.png)
![screenshot_1520406785](https://user-images.githubusercontent.com/202757/37078387-6049e936-21df-11e8-8087-a3c89d7e2486.png)

**Comment by marek-embiq** [comment] 2018-04-06 11:09
Hi @Frenzie, You need to build app with targetSdkVersion 27 in your build.gradle app module I guess ;)

**Comment by AsukaLangleyfag** [comment] 2018-08-19 14:37
Have 18:9 android device with 8.1 Oreo that is almost stock (ZB602), same issue. Disabling night mode ([`"night_mode"] = false,` right?) didn't helped.

**Comment by scsmartt** [comment] 2018-09-02 03:04
Having the same issue on the latest nightly. Any plans to fix?

**Comment by Frenzie** [comment] 2018-09-02 05:04
Like I showed on the screenshots I don't see this issue on my Pixel 2 emulator, so I'm afraid only someone with the device could.

**Comment by scsmartt** [comment] 2018-09-02 10:43
Not sure if it makes a difference but I have the Pixel 2 XL.

**Comment by scsmartt** [comment] 2018-09-23 12:41
I've been doing more research on this issue and it seems to be a common issue with the Pixel 2 XL and the problem is derived from the aspect rati0 (18:9) used by the phone. I don't know how to remedy this but from everything I have read it seems like this is the problem and it is fixable.

**Comment by scsmartt** [comment] 2018-09-23 12:44
> Like I showed on the screenshots I don't see this issue on my Pixel 2 emulator, so I'm afraid only someone with the device could.

I've been doing more research on this issue and it seems to be a common issue with the Pixel 2 XL. The problem is derived from the aspect ratio (18:9) used by the phone. It is specific to the XL so that is why you don't see the issue on the Pixel 2 emulator. I don't know how to remedy this but from everything I have read it seems like this is the problem and it is fixable.

Still wondering what @curiousclinician did for a workaround.

**Comment by thallian** [comment] 2018-10-26 16:28
If you are still looking for a solution @scsmartt

I had this problem on a OnePlus 5T (same aspect ratio afaik). 

Worked around it by forcing KOReader to use the full screen aspect ratio.

The setting is here: Settings: Display: Advanced: Full Screen Apps

**Comment by pazos** [comment] 2019-01-21 22:00
@curiousclinician: Is this still an issue for you?, could you try lastest nightlies?

**Comment by pazos** [comment] 2019-01-31 14:00
Closing this as it should be fixed in https://github.com/koreader/android-luajit-launcher/pull/85

**Closed by pazos** 2019-01-31 14:00 UTC
Labels: Android, bug, out-of-date
