### ISSUE TITLE
Swipe to control light is not real time

### ISSUE THREAD

**Issue by pblasi** [koreader/koreader#5313] opened 2019-09-04 08:49 UTC
Kobo Clara HD

Frontlight changes only occur when you finish swiping. They are not in real time like in nickel or coolreader. It has no-sense the way it works in koreader. Can this feature be implemented?

Thanks!

**Comment by Frenzie** [comment] 2019-09-04 10:01
So you're saying there's a regression in https://github.com/koreader/koreader/pull/5179?

**Comment by pblasi** [comment] 2019-09-04 10:43
I don't know. Sorry for my bad english...
I'm saying brightness (or warmth) does not change WHILE you are swiping up and down, only when swiping is finished. Changes will be big or small depending on the swipe lenght but you will not see them until finishing the swipe. In other words, brightness does not follow your finger swipe in real time (like it does in nickel). Even in the frontlight dialog, you can not swipe left/right over the brightness bar to see brightness changes following the swipe (as you can in coolreader)
I hope I made myself clear now... Thanks!

**Comment by Frenzie** [comment] 2019-09-04 11:22
I mean that's exactly how it used to work, presumably until a few weeks ago.

**Comment by pblasi** [comment] 2019-09-04 11:30
Oh, Ok. So yes, I can confirm it's not working in Kobo Clara HD.

**Comment by pblasi** [comment] 2019-09-05 06:41
So, is the issue kobo related? or it affects only Clara HD? I cannot code, but I can test on my device.
Thanks!

**Comment by Frenzie** [comment] 2019-09-05 06:43
No, it should be the same on any device unless swipe detection itself were broken on one of them.

**Comment by pblasi** [comment] 2019-09-05 06:44
Can you check on your devices and confirm the issue?

**Comment by Frenzie** [comment] 2019-09-05 06:53
Yes, it works that way on my H2O. But I don't have time to test 2019.07 atm.

**Comment by pblasi** [comment] 2019-09-05 07:06
Just tested 2019.07 and works the same way: brightness/warmth don't change while swiping, only when swipe ends.

**Comment by Frenzie** [comment] 2019-09-05 07:39
I guess it wouldn't be a regression then, or at least not a particularly recent one.

PS I meant <https://github.com/koreader/koreader/pull/5156> instead of the follow-up I referred to previously, though it makes no difference to the stables involved.

**Comment by robert00s** [comment] 2019-09-05 08:21
I have an idea. I try use pan instead of swipe but I need some time to test.

**Comment by pblasi** [comment] 2019-09-05 11:44
Thanks! I can test on my Clara HD if you need.

**Comment by Frenzie** [comment] 2019-09-05 11:49
Btw, here's an easy link to the frontlight controller plugin history: https://github.com/koreader/koreader/commits/91b2faae6a40e220de7bb2766990012694068f39/plugins/kobolight.koplugin

Of course I might simply misremember. It''s not functionality I care for.

**Comment by poire-z** [comment] 2019-09-05 12:22
If we always just handled the `swipe` event only, it must never have been dynamic: the code is notified of the `swipe` event only at the end of the swipe gesture.
So, if we go with over events, here's my reference about them:
https://github.com/koreader/koreader/blob/2d95a09e93fc481f3b1647eed691dafb2b7af87a/frontend/ui/widget/container/movablecontainer.lua#L65-L81

I guess addtionally handling `pan` should work: you start your swipe, and as soon as you pause in the move (without releasing the finger), it becomes a pan and then you get the intermediate pan event/distance.

**Comment by Frenzie** [comment] 2019-09-05 12:26
I guess I must be confused with Nickel. Even the two-finger swipe doesn't seem to work that way. Although that too was recently transferred to the gesture manager. :-P

**Comment by LucyOne** [comment] 2019-09-06 09:02
I can confirm the lag on Pocketbook devices. One of the reasons I used Coolreader for so long and why I don't swipe  so often in KoReader.

**Comment by thedward** [comment] 2019-09-14 18:16
I also see no brightness or warmth change until the gesture is complete — v2019.09 on a Kobo Forma.

**Closed** 2020-12-18 19:12 UTC
Labels: UX, wontfix
