### ISSUE TITLE
FR: Save screensaver image to file

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#6635] opened 2020-09-06 17:11 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
Since the screensaver for Android devices is not supported (see #5732), this would be a solution so that you can use the screensaver for rooted devices after all.

**Describe the solution you'd like**
Option to save the screensaver image to a file in a certain format (jpg or png) in a user defined directory.
jpg is used with tolino e-readers, with other Android readers possibly the png format.

**Describe alternatives you've considered**
Provision of functions in the API to save images in jpg or png format.

**Comment by pazos** [comment] 2020-09-06 17:35
Open multiple issues won't help. Also mixing concepts usually don't help.

> Since the screensaver for Android devices is not supported

Will never be supported. Period. It is actually **imposible** to do. Can't fix

You'll need a hack. In the best case scenario this hack can become a plugin and work in a few e-ink devices. Won't fix, patches welcome

> Option to save the screensaver image to a file in a certain format (jpg or png) in a user defined directory.
jpg is used with tolino e-readers, with other Android readers possibly the png format.

For tolinos you'll need to implement part of the work in the backend. See https://github.com/koreader/koreader/issues/5732#issuecomment-586305386. Won't fix but patches welcome.

> Provision of functions in the API to save images in jpg or png format.

That makes sense. They need to be implemented as part of blitbuffer methods. They can be repurposed by hacks and plugins. Also bmp format is useful to use it on pocketbooks.

**Comment by pazos** [comment] 2020-09-06 17:37
Partial duplicate of #6630 and #5732

**Comment by pazos** [comment] 2020-09-09 18:55
@elvvis: I've opened a ticket in https://github.com/koreader/koreader-base/issues/1182.

Feel free to open a ticket in https://github.com/koreader/android-luajit-launcher for the Tolino specifics, but please don't open new feature requests here for the same topic :)

**Closed by pazos** 2020-09-09 18:55 UTC
Labels: can't fix, duplicate, invalid, wontfix

**Comment by elvvis** [comment] 2020-09-09 19:03
> @elvvis: I've opened a ticket in [koreader/koreader-base#1182](https://github.com/koreader/koreader-base/issues/1182).

This is great, thanks, then I can use the functions in the frontend to write a Tolino hack for the screensaver.
