### ISSUE TITLE
How to use WebDAV on Kindle koreader?

### ISSUE THREAD

**Issue by tiandongxv** [koreader/koreader#4956] opened 2019-04-22 01:58 UTC
* KOReader version: v2019.04
* Device: Kindle voyage

#### Issue
I want use the WebDAV to upload or download files on Kindle koreader, but I cannot find this function, I only can find ftp plugin (Sent2Ebook), so could anyone tell me how to use WebDAV?

**Comment by Frenzie** [comment] 2019-04-22 06:46
If you're in a document, open the top menu and press the file manager icon.

![Screenshot_2019-04-22_08-44-51](https://user-images.githubusercontent.com/202757/56487313-0e2daa80-64db-11e9-861f-1050fe67ebed.png)
![Screenshot_2019-04-22_08-45-02](https://user-images.githubusercontent.com/202757/56487314-0e2daa80-64db-11e9-9972-a8f22cc5a9fb.png)
![Screenshot_2019-04-22_08-45-10](https://user-images.githubusercontent.com/202757/56487315-0ec64100-64db-11e9-9531-cc988220d0ef.png)

(Duplicate of https://github.com/koreader/koreader/issues/4879#issuecomment-485307497 and https://www.mobileread.com/forums/showthread.php?p=3833987#post3833987.)

**Closed by Frenzie** 2019-04-22 06:46 UTC
Labels: question

**Comment by tiandongxv** [comment] 2019-04-22 07:13
> If you're in a document, open the top menu and press the file manager icon.
> 
> ![Screenshot_2019-04-22_08-44-51](https://user-images.githubusercontent.com/202757/56487313-0e2daa80-64db-11e9-861f-1050fe67ebed.png)
> ![Screenshot_2019-04-22_08-45-02](https://user-images.githubusercontent.com/202757/56487314-0e2daa80-64db-11e9-9972-a8f22cc5a9fb.png)
> ![Screenshot_2019-04-22_08-45-10](https://user-images.githubusercontent.com/202757/56487315-0ec64100-64db-11e9-9531-cc988220d0ef.png)
> 
> (Duplicate of [#4879 (comment)](https://github.com/koreader/koreader/issues/4879#issuecomment-485307497) and https://www.mobileread.com/forums/showthread.php?p=3833987#post3833987.)

Thanks, It’s hide so deeply, when I press the file manager icon, it’s always show my books, I never thought to click this interface top, thanks a lot, and please ignore my poor English!
