### ISSUE TITLE
document settings and reading position for epub or mobi are no longer persistent

### ISSUE THREAD

**Issue by squiresque** [koreader/koreader#8420] opened 2021-11-04 18:58 UTC
* KOReader version: 2021-10.1-50
* Device: Likebook Alita 

#### Steps to reproduce  - Open a PDF, then open a book in history, or the previous document.  Then change the font and the line spacing.  Read a few pages.  Then switch back to the PDF document.  Then switch back to the epub or mobi document.  KO Reader opens at the cover page of the mobi or epub document and has not remembered font size changes or line spacing changes. 

I don't remember exactly when this started since I update KO Reader often.  However, switching between books is my normal behavior so this must have happened recently. 

I tried changing from saving the status every five minutes to saving status upon exit, then exiting KO reader, then opening KO reader again, to find that my font changes, current reading location, line spacing changes, were not saved.  

However, my reading position in the PDF document is still updated and saved across reopenings.

**Comment by poire-z** [comment] 2021-11-04 19:23
Is this running Android ? No recent FW update?
We've meet something possibly similar recently at #8328 and in at least one other place I can't find.
Your setting might be saved/used from koreader/history/ instead of the .sdr/ subdirectory alongside the book file.
Strange that many SDCard becomes read-only in a few weeks... or did we mess something ? I don't remember we touched something related to settings saving recently... Your crash.log might tell you/us more. And may be even more in debug mode (File browser > Tools > More tools > Dev options > Enable debug logging, for a short time only).

**Comment by squiresque** [comment] 2021-11-04 20:08
Thank you.  I have Android 8.1, and no recent firmware update.  Following up on your suggestion, I changed the location of the books to the internal drive instead of the SD Card, and confirmed that changes to the document and reading position are persistent.  I have not been able to readily identify a setting that would allow me to change the directory in which document history is stored.  Nor have I been able to confirm that the SD Card has become "read only" since I appear to be able to read from and write to the SD Card Books directory, and the native Boyue reader is not having any difficulty with books stored on the SD Card.

**Comment by poire-z** [comment] 2021-11-04 20:44
> I have not been able to readily identify a setting that would allow me to change the directory in which document history is stored

There is none: if we can read from the .sdr/metadata.epub.lua, we attempt to write there (so, we may fail, and keep reusing this obsolete setting file). If we can't read it and can't create the .sdr directory, we write into koreader/history/. Is your koreader/history/ empty ? Or do you have some files in there (which could mean that at some point, we couldn't write in the SDCard).

@pazos: just asking, but I guess on the SDCard, files get generic owner/group persmissions IDs, and there's no issue if one uninstall and reinstall KOReader, and it gets a new uid u_12345, right ?

**Comment by squiresque** [comment] 2021-11-04 21:11
On my internal drive Books directory, there are .sdr folders containing the metadata.epub.lua files, but none with a modified date after October 24, 2021.  On my external disk SD Card there are no .sdr folders in the Books directory.  My koreader history folder contains many entries, most recently dated (modified) October 5, 2021.

**Comment by poire-z** [comment] 2021-11-04 21:28
That sounds really weird :/ Anything happened on these 2 dates ?
The files in the history folder may have the path encoded (with / replaced with # if I remember right), so you can guess to which disk these files/settings are related to. Might give you some idea, because I haven't any :)

**Comment by pazos** [comment] 2021-11-04 23:28
> just asking, but I guess on the SDCard, files get generic owner/group persmissions IDs, and there's no issue if one uninstall and reinstall KOReader, and it gets a new uid u_12345, right ?

Yup. No issues uninstalling/reinstalling. The only writable path on volumes other than the primary partition are placed in Android/data/org.koreader.launcher.

There's no way to have filesystem RW access in non primary partitions (other than the path above).

**Comment by squiresque** [comment] 2021-11-05 05:32
From my download directory it would appear that on 10/24/2021 I downloaded and installed the update KO Reader 2021 10.1-28.

**Comment by squiresque** [comment] 2021-11-05 05:42
And checking other KO Reader files, statistics, battery etc, the last modify date is 10/24/2021 and within minutes of the 10.1-28 update.

**Comment by squiresque** [comment] 2021-11-05 05:59
I'm willing to try backing up to a prior KO Reader version to confirm that the issue is related to an update.  A straightforward attempt to run the prior update failed.

**Comment by squiresque** [comment] 2021-11-05 06:43
I uninstalled KO Reader 10.1-28, and reinstalled Version 2021.10.1, and tested it with books from the SD card and it appears to now be functioning normally.  That is, there is persistence of book page position, font changes, etcetera.

**Comment by poire-z** [comment] 2021-11-05 06:43
Anything in your crash.log - and if nothing, what if with debug mode on - when exiting or switching books ? Ok, it's Android so not easy to get, but there's a procedure described in the issue template:
> Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

10.1-28 have brought the Japanese plugin support, which touched many things:
https://github.com/koreader/koreader/commits/db215219686a970a80d9579bba9f767d6a27476b

What could have been the previous "working" version ?

**Comment by poire-z** [comment] 2021-11-05 06:48
The only thing I see that could be a bit related are my changes:
https://github.com/koreader/koreader/commit/37eb53f6e4b995cd8b3dc5a8fa6bc5c28d839a95#diff-e8930dfe3beade539965223b8d896677cae3de5ea9f57717fe02a02a1a579930
Mostly the 3 `pairs` > `ipairs` changes. Just to rule this off, you could try on 10.1-28 to edit this file and make these 3 ipairs become pairs (dunno if you can do this on Android).

**Comment by squiresque** [comment] 2021-11-05 07:19
I was not able to readily identify a "debug mode" setting.  There was no crash.log associated with the file switching in 10.1-28, but I was able to make KO reader crash by choosing an apparently unsupported end-of-book action, and that created a crash.log file limited to that event.   My reinstall of the 10.1 release (koreader-android-arm-v2021.10.1.apk) continues to behave normally.

**Comment by squiresque** [comment] 2021-11-05 08:21
Well, except that now attempting to reflow a two column pdf causes a crash, with a crash.log with a message about a FIFO user already existing.  Hopefully my uninstall/install did not break something.

**Comment by pazos** [comment] 2021-11-05 18:42
> I was not able to readily identify a "debug mode" setting. There was no crash.log associated with the file switching in 10.1-28, but I was able to make KO reader crash by choosing an apparently unsupported end-of-book action, and that created a crash.log file limited to that event. My reinstall of the 10.1 release (koreader-android-arm-v2021.10.1.apk) continues to behave normally.

You're mixing two different things. The "crash.log" requested is a file. @poire-z explained how to get one in android (reread https://github.com/koreader/koreader/issues/8420#issuecomment-961661542)

The other thing you talk about is the crash reporter, that's a message with a bomb that happens when the device crashes. Crash reports are useful for understanding why the app crashed. Crash.log contains info useful **even** when the app doesn't crash at all!!!

> Well, except that now attempting to reflow a two column pdf causes a crash, with a crash.log with a message about a FIFO user already existing. Hopefully my uninstall/install did not break something.

Totally unrelated to your issue here.

@squiresque: since you can't reproduce the original issue anymore I'm closing this ticket. Feel free to open a new one if you can reproduce it again. Please follow the bug template and attach a crash.log.

Feel free to open all issues you find (please check first if they're already reported as we want to avoid duplicates). If you find a crash then please attach the crash message. If you don't find a crash, but a certain bug, please attach the "crash.log" as instructed in the template.

Please keep each ticket focused on a single issue. That makes things a lot easier :)

**Comment by poire-z** [comment] 2021-11-05 18:48
> since you can't reproduce the original issue anymore 

I understand @squiresque does not get the original issue anymore when he installs v2021.10.1 - but he can reproduce it when reinstalling v2021.10.1-28.
The original issue being that settings are not saved/loaded and that current position is lost.

**Comment by squiresque** [comment] 2021-11-05 19:15
Well, I did the uninstall and reinstall of the older release just to confirm that the new release caused the problem.  Since I can't tolerate the complete loss of reflow capability -- the primary reason I am enamored with KO Reader -- I will be reinstalling the newer release to see if I can get that functionality back.  Thank you for your remarks about the crash log file - I was not immediately able to turn debug mode on or find a log file related to the original issue, even after consulting the referenced issue.  You are correct that the crash file I was able to easily locate was generated after a bomb - including an actual picture of a bomb.  If you can point me to something intelligible, even if more elementary, perhaps I will be able to provide you with more helpful feedback on your excellent application going forward.

**Comment by squiresque** [comment] 2021-11-06 08:22
I'd like to add that in Likebook Boyue Alita Android 8.1, there are two formatting options for the SD Card - portability so that the SD Card can be read and written on another device, and internal to Alita.  This SD Card was formatted for portability.

**Comment by squiresque** [comment] 2021-11-07 06:36
Q: Is there way within KO Reader to request that it be restarted in a "debug mode" for the purpose of creating an informative trace when there is an issue?  If not, is there an application launcher for Android 8.1 that permits the specification of a "debug mode" for KO Reader?   Thank you for any information you may be able to provide.

**Comment by Frenzie** [comment] 2021-11-07 07:54
If you go to the file browser, you can find developer options in the tools
menu.

**Comment by Frenzie** [comment] 2021-11-07 09:17
The logging information will be written alongside the settings (Help -> Report a bug). How that's shown to the user in a file manager can differ greatly per device. It could be displayed as Internal/koreader, /sdcard/koreader, and so on. That dialog will also show you the exact location, but a path like `/storage/emulated/0` will often be displayed as simply `Internal` for example.

**Comment by Frenzie** [comment] 2021-11-07 09:19
In the folder that's mentioned in Help -> Report a bug (where you also have to go to generate a crash.log file). But a folder like `/storage/emulated/0/koreader` might be displayed as something like `Internal/koreader` or `/sdcard/koreader` in your file manager.

**Comment by Frenzie** [comment] 2021-11-07 09:19
In the folder that's mentioned in Help -> Report a bug (where you also have to go to generate a crash.log file). But a folder like `/storage/emulated/0/koreader` might be displayed as something like `Internal/koreader` or `/sdcard/koreader` in your file manager.

**Comment by Frenzie** [comment] 2021-11-07 09:19
In the folder that's mentioned in Help -> Report a bug (where you also have to go to generate a crash.log file). But a folder like `/storage/emulated/0/koreader` might be displayed as something like `Internal/koreader` or `/sdcard/koreader` in your file manager.

**Comment by squiresque** [comment] 2021-11-07 09:52
Thank you!  And now that I have enabled verbose logging in the developer options of the KO file browser, where can I find that logging information for the purpose of providing it to the developers when an error occurs?  Also, should I "clear the cache" before reproducing the error to minimize extraneous logging?

**Comment by pazos** [comment] 2021-11-08 19:40
> > since you can't reproduce the original issue anymore
> 
> I understand @squiresque does not get the original issue anymore when he installs v2021.10.1 - but he can reproduce it when reinstalling v2021.10.1-28. The original issue being that settings are not saved/loaded and that current position is lost.

My bad. I didn't notice that. 

Unlikely to be related with android-luajit-launcher, as there're no relevant changes there

**Comment by poire-z** [comment] 2021-11-08 19:49
There are quite a few such reports, mostly for Likebook.
And one about some Onyx device dated Aug 26 on the russian forum:
> Koreader does not save the position in the book on Onyx Book Darwin 3, it always opens somewhere from the third page.
Does anyone have this? 

I'm still a bit worried about this change of mine, which looks harmless and right, but who knows...:

> The only thing I see that could be a bit related are my changes: [37eb53f#diff-e8930dfe3beade539965223b8d896677cae3de5ea9f57717fe02a02a1a579930](https://github.com/koreader/koreader/commit/37eb53f6e4b995cd8b3dc5a8fa6bc5c28d839a95#diff-e8930dfe3beade539965223b8d896677cae3de5ea9f57717fe02a02a1a579930) Mostly the 3 `pairs` > `ipairs` changes. Just to rule this off, you could try on 10.1-28 to edit this file and make these 3 ipairs become pairs (dunno if you can do this on Android).

@NiLuJe : can you have a quick look at this patch, in case you see something I didn't ?

**Comment by pazos** [comment] 2021-11-08 19:58
The russian Onyx models are all very broken. The same could happen to other android eink devices: the only way to be sure changes are saved is 1) by exiting the program from the document (in hamburguer -> exit) or 2) by returning to the FM from the document.

The usual android workflow of leaving the app opened until I kill it from recents (or let the system kill it when it wants) works fine on emulators, real android devices and a handful of e-ink devices (I'm aware it **still** works on Boyue running 6.x android)

**Comment by NiLuJe** [comment] 2021-11-08 20:58
> > The only thing I see that could be a bit related are my changes: [37eb53f#diff-e8930dfe3beade539965223b8d896677cae3de5ea9f57717fe02a02a1a579930](https://github.com/koreader/koreader/commit/37eb53f6e4b995cd8b3dc5a8fa6bc5c28d839a95#diff-e8930dfe3beade539965223b8d896677cae3de5ea9f57717fe02a02a1a579930) Mostly the 3 `pairs` > `ipairs` changes. Just to rule this off, you could try on 10.1-28 to edit this file and make these 3 ipairs become pairs (dunno if you can do this on Android).
> 
> @NiLuJe : can you have a quick look at this patch, in case you see something I didn't ?

Looks okay at a quick glance, those are indeed arrays ;).

**Comment by squiresque** [comment] 2021-11-15 22:57
Well, this is labeled as "needs more info."  If this is directed at me, I'd like to point out that there is no debugging file produced by KOReader when the error occurs - just a silent failure to save any information about the reading session.   Perhaps in a future update you can change this aspect of KOReader so that it actually creates a log when it is unable to store settings and book information?   If your emulator makes identifying and testing the fix for my device impossible, please just let me know. Thank you.

**Comment by poire-z** [comment] 2021-11-15 23:13
Android being Android, we don't get a log file - all goes to Android's own log system - that you can inspect with some Apps like CatLog or LogCat (or adb Android stuff, that I'm not familiar with). Or Help → Bug Report to save these logs to a file (never tried it).

To turn on KOReader's debug logs:` File browser (only) > Tools > More tools > Developper options > Enable debug logging`.
You should then get in Android's logs:
https://github.com/koreader/koreader/blob/6d40c7c7ea8abe2e12e9897ee7d6ed0dbc5c8712/frontend/docsettings.lua#L150
https://github.com/koreader/koreader/blob/6d40c7c7ea8abe2e12e9897ee7d6ed0dbc5c8712/frontend/docsettings.lua#L155
https://github.com/koreader/koreader/blob/6d40c7c7ea8abe2e12e9897ee7d6ed0dbc5c8712/frontend/docsettings.lua#L326
https://github.com/koreader/koreader/blob/6d40c7c7ea8abe2e12e9897ee7d6ed0dbc5c8712/frontend/docsettings.lua#L331
https://github.com/koreader/koreader/blob/6d40c7c7ea8abe2e12e9897ee7d6ed0dbc5c8712/frontend/docsettings.lua#L344
which may give you/us a bit more info about what's happening on (only) your device - because most don't have any issue on their Android based devices :/
I would expect you don't read and write to the same file - but if you do, you should look at this file if it has the current info or not, and then, we'll think.

**Comment by squiresque** [comment] 2021-11-16 01:16
Thank you.  I have enabled verbose logging.  I installed a log cat app from the google play store but it is unusable apparently in an e-ink device (black screen).  There is no "koreader/frontend" directory on my device, and no docsettings lua file that I can readily identify.

**Comment by squiresque** [comment] 2021-11-16 01:54
Well, actually now the crash log is quite voluminous with the verbose setting but I can't tell if any of it is related to the issue.  I'll try to get in and out of a book file on the SD card, and attach the file.

**Comment by poire-z** [comment] 2021-11-16 07:15
>  There is no "koreader/frontend" directory on my device, and no docsettings lua file that I can readily identify

There are kept in the not visible parts of the Android file system where applications are installed - so, on Android, you can't hack these files (to add more logging, fix stuff....) directly.

> the crash log

So, you got one !

>  is quite voluminous with the verbose setting 

Yes, once you're done, you should disable debug logging, as it makes indeed voluminous logs and may slow things.

**Comment by squiresque** [comment] 2021-11-16 11:15
Is there a command I can execute in KOReader's terminal window that will cat/pipe the Android log file to a file that I can access?

**Comment by Frenzie** [comment] 2021-11-16 11:18
KOReader will generate a log file through Help → Report a bug.

**Comment by squiresque** [comment] 2021-11-16 12:02
At last I understand you - that when I hit report a bug in help, KO Reader generates the log file automatically without my having to do anything else.  I tried to make the log file focus on switching between an internal disk book and an SD Card book repeatedly, experiencing repeated failure to remember page location and settings for the SD Card book.  Unfortunately KO Reader actually crashed twice when I tried to get the KO Reader file browser to come up so I could check if a crash log had been generated by that action alone.  So that bug might be reflected in the log.   
[crash[2].log](https://github.com/koreader/koreader/files/7546084/crash.2.log)

**Comment by poire-z** [comment] 2021-11-16 12:14
```
11-16 06:44:02.835 V/KOReader( 1816):  creating coroutine for showing reader
11-16 06:44:02.835 I/KOReader( 1816):  opening file /storage/9C33-6BBD/Books/Fischer2019.pdf
11-16 06:44:03.121 W/Thread-842( 1816): type=1400 audit(0.0:55): avc: denied { setattr } for name="Fischer2019.pdf" dev="mmcblk0p1" ino=5701 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=0
[....]
11-16 06:44:03.330 V/KOReader( 1816):  RD loaded plugin gestures at plugins/gestures.koplugin
11-16 06:44:03.330 V/KOReader( 1816):  language support: overriding existing japanese plugin
11-16 06:44:03.330 V/KOReader( 1816):  RD loaded plugin japanese at plugins/japanese.koplugin
[...]
11-16 06:44:03.344 I/KOReader( 1816):  setting zoom mode to pagewidth
11-16 06:44:03.344 V/KOReader( 1816):  _refresh: Enqueued partial update for region 0 0 1404 1872
11-16 06:44:03.344 V/KOReader( 1816):  setDirty partial from widget ReaderUI w/ NO region
```
In this chunk, we SHOULD have seen something like:
`11/16/21-13:07:01 DEBUG data is read from  koreader_stuff/test/626372.sdr/metadata.pdf.lua`
which I don't see.
Did you get on page 1 as it it was a never opened book ?

We should have seen something like this (that I found in your log, but for another book, so it can happen :):
```
11-16 06:44:02.582 V/KOReader( 1816):  Rename  /storage/emulated/0/Books/Informant-10CBAq26.sdr/metadata.pdf.lua  to  /storage/emulated/0/Books/Informant-10CBAq26.sdr/metadata.pdf.lua.old
11-16 06:44:02.583 V/KOReader( 1816):  Write to  /storage/emulated/0/Books/Informant-10CBAq26.sdr/metadata.pdf.lua
```
Re-opening this book should have a log saying
`data is read from  /storage/emulated/0/Books/Informant-10CBAq26.sdr/metadata.pdf.lua`
You should try to open/close these books and see if you get some combinations of read/write, and what/why things happen or don't.

Also, I don't know if this is a hint of some permission problem:
`Thread-842( 1816): type=1400 audit(0.0:55): avc: denied { setattr } for name="Fischer2019.pdf" dev="mmcblk0p1" ino=5701 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=0`

**Comment by poire-z** [comment] 2021-11-16 12:17
But if all is good on the internal SDCard, and stuff goes wrong only on the external SDCard, I guess this might be a known issue with Android - and I don't remember what are the solutions/workarounds.

**Comment by squiresque** [comment] 2021-11-16 12:25
Thank you.  I generated more log without using the file browser to avoid that crash issue (attached).  The SD Card books used to work, and then stopped working this month.  I was able to get SD Card books to work again by uninstalling KO Reader and reverting to an older KO Reader version, but updated to the more recent version so I could 
[crash_1[1].log](https://github.com/koreader/koreader/files/7546210/crash_1.1.log)
reproduce the error.   I am going to try a new SD Card to see if that changes anything, perhaps formatting it to be android internal instead of portable also.

**Comment by poire-z** [comment] 2021-11-16 12:37
OK, we may have something:

If I make the directory containing the book read only (with no existing .sdr/), I don't get any setting written anywhere with current master.
With v2021.06 appimage, I get to see:
`11/16/21-13:33:18 DEBUG Write to  ./history/[#koreader_stuff#test#] 626372.pdf.lua`
With v2021.09 and v2021.08, I don't see that.

So, something between v2021.06 and v2021.08 must have impacted this.

**Comment by poire-z** [comment] 2021-11-16 12:46
Damned, I don't get it with v2021.06 anymore !
Also not getting it with v2021.07 or v2021.02...

**Comment by poire-z** [comment] 2021-11-16 12:57
And if I revert my 3 `ipairs` to their original `pairs` on current master, I get the `Write to ./history` !

> > > The only thing I see that could be a bit related are my changes: [37eb53f#diff-e8930dfe3beade539965223b8d896677cae3de5ea9f57717fe02a02a1a579930](https://github.com/koreader/koreader/commit/37eb53f6e4b995cd8b3dc5a8fa6bc5c28d839a95#diff-e8930dfe3beade539965223b8d896677cae3de5ea9f57717fe02a02a1a579930) Mostly the 3 `pairs` > `ipairs` changes. Just to rule this off, you could try on 10.1-28 to edit this file and make these 3 ipairs become pairs (dunno if you can do this on Android).
> > 
> Looks okay at a quick glance, those are indeed arrays ;).

Puzzled :/

**Comment by poire-z** [comment] 2021-11-16 13:00
```
> z = { nil, "abc" }
> for i, v in pairs(z) do print(v) end
abc
> for i, v in ipairs(z) do print(v) end
>
```
https://github.com/koreader/koreader/blob/6d40c7c7ea8abe2e12e9897ee7d6ed0dbc5c8712/frontend/docsettings.lua#L310-L316

**Comment by poire-z** [comment] 2021-11-16 13:06
This should fix it, I'll PR it later today.
```diff
--- a/frontend/docsettings.lua
+++ b/frontend/docsettings.lua
@@ -310,5 +310,11 @@ function DocSettings:flush()
     -- If we can write to sidecar_file, we do not need to write to history_file
     -- anymore.
-    local serials = { self.sidecar_file, self.history_file }
+    local serials = {}
+    if self.sidecar_file then
+        table.insert(serials, self.sidecar_file)
+    end
+    if self.history_file then
+        table.insert(serials, self.history_file)
+    end
     self:ensureSidecar(self.sidecar)
     local s_out = dump(self.data)
```
(This file would deserve a full rewrite... but well, I'm not hungry for that...)

**Comment by NiLuJe** [comment] 2021-11-16 13:29
Oh right, can't have nils in arrays without extra trickery...

**Comment by squiresque** [comment] 2021-11-16 14:29
Thank you! While you were doing all of that useful forensic work, I uselessly reformatted another SD card to internal and learned absolutely nothing, having to just reformat it back to portable so it would be seen by apps.  No surprise that the anomaly appears in two different SD cards of two different sizes.  

Q: Is there any way for me to change the permissions on my SD card filesystem to RWX if some "read only" property is causing the issue?  (lamentably or not, nothing on my SD card merits that kind of protection)

**Comment by poire-z** [comment] 2021-11-16 14:46
> Q: Is there any way for me to change the permissions on my SD card filesystem to RWX if some "read only" property is causing the issue? (lamentably or not, nothing on my SD card merits that kind of protection)

I don't think so. In the Android world, Google knows better than you and us how protected and annoying to access the data on your SDCard should be :/ And there's nothing you or we can do (unless your device is rooted, and even then, there will still be bits of the permissions/selinux stuff that is going to bite us...)

**Comment by pazos** [comment] 2021-11-16 15:16
> And there's nothing you or we can do (unless your device is rooted, and even then, there will still be bits of the permissions/selinux stuff that is going to bite us...)

Exactly. There's no filesystem API **at all** on Android 6.0+, thanks to SELinux enforcement, which your device has, as stated in 
> Thread-842( 1816): type=1400 audit(0.0:55): avc: denied { setattr } for name="Fischer2019.pdf" dev="mmcblk0p1" ino=5701 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=0

That means that even rooting your device won't give RW access to untrusted apps. (Untrusted apps = all apps installed by the user). Open any file there to write will fail with `EACCES (Permission denied)`

From our PoV is not easily fixable. We use `luafilesystem` in all platforms.  The only workaround would be creating a stub `lfs` module that uses luafilesystem everywhere except on android, outside the primary partition, where it would need to use SAF: https://developer.android.com/training/data-storage/shared/documents-files

**Closed** 2021-11-16 18:02 UTC
Labels: need more info

**Comment by squiresque** [comment] 2021-11-17 08:14
Book status and setting persistence is functioning again on my Alita SD Card after the update.  Thank you!
