### ISSUE TITLE
The guesture for light on kobo h2o is too sensitive.

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#2605] opened 2017-03-03 02:50 UTC
The guesture for light on kobo h2o is too sensitive.
Only can be the On/OFF...

**Comment by houqp** [comment] 2017-03-03 08:00
@Hzj-jie can you help take a look? I probably won't have time to dig into this until weekends.

**Comment by Hzj-jie** [comment] 2017-03-03 08:59
I have recently updated this module. Now swiping up from bottom to the top will increase 50% of the intensity. Before my change, it impacts only 10%. But swiping less distance increase less. I.e. from 1% to 50%.
If this behavior does not match what you see, it is definitely a bug we should fix. Otherwise, it's intential.
We cannot confirm which is the best exerience. Personally I think swiping up 10 times to fully turn on the light seems incorrect. But we would hear your opinion.

**Comment by houqp** [comment] 2017-03-03 09:46
@seacatwu if it's too sensitive, we can help tune the threshold. If you can only set it to on and off, then it's a bug that we need to fix. Can you help confirm which case it is?

**Comment by seacatwu** [comment] 2017-03-03 12:34
after the ota tomorrow, I'll try the new module. Wish it'll be OK.

**Comment by seacatwu** [comment] 2017-03-03 12:38
@houqp mostly, it became a switch.

**Comment by seacatwu** [comment] 2017-03-03 15:38
@houqp @Hzj-jie After reboot  koreader, the bug came again. 
I swiped a few distance , it increase to 100%.

**Comment by Hzj-jie** [comment] 2017-03-04 16:09
When I tried it on Kindle, after a rebooting, the font light cannot be retrieved correctly from the system, and may cause the similar behavior. I.e. at the very beginning, the front light intensity in KOReader is 100, a swiping up will set the front light to 100%.
I do not have an H2O, @houqp, would you mind to confirm if there is a similar issue on H2O?

**Comment by Frenzie** [comment] 2017-03-04 16:21
How do you activate (and also important, disable) this gesture? I kept
activating the light instead of scrolling in Nickel.

**Comment by Hzj-jie** [comment] 2017-03-04 17:23
Or @seacatwu, would you mind to confirm, after restarted, whether the front light intensity is correct? You may set it to, say, 50, in settings -> front light. Restart KOReader. Read the value in settings -> front light. If it's still 50, something else may be wrong.

**Comment by seacatwu** [comment] 2017-03-05 05:25
@Hzj-jie In latest version 882, this problem is solved, and worked pretty well.

**Comment by Hzj-jie** [comment] 2017-03-05 07:02
Glad to know that. I will close this issue. Feel free to open another one if you have been encountered the issue again.

**Comment by seacatwu** [comment] 2017-03-06 13:56
@Hzj-jie I found that bug again! When I open a pdf,  the guesture only can be the switch.

**Comment by houqp** [comment] 2017-03-08 08:43
@seacatwu is it only happening to PDFs?

**Comment by seacatwu** [comment] 2017-03-08 13:03
@houqp And also zip.

**Comment by Frenzie** [comment] 2017-03-08 13:52
So basically all MuPDF documents? That's pdf, cbz, zip, and xps.

https://github.com/koreader/koreader/blob/f95ad00b9e4a1e3bed1f00b0c93afc3efa308b3f/frontend/document/pdfdocument.lua#L221-L224

**Comment by seacatwu** [comment] 2017-03-08 14:23
@Frenzie Maybe.

**Comment by poire-z** [comment] 2017-03-11 19:12
Just witnessed that (Kobo Glo HD), it was fine some days ago, switched reading between a few documents (epubs only I think), and I realize today that sensitivity is only 0 or 100%.

The sensitivity gets higher each time one opens a document.
Easy to reproduce : launch koreader, open a doc, test sensitivity, open another doc, re-test sensitivity. After 3 or 4, you only get 0 or 100%

It may be because of the added `KoboLight:init()` at https://github.com/koreader/koreader/commit/7fb2dc8d5ca7c6e8ca605fa6fc8372042b3e01be#diff-9cf37ee7352547f3ecc054072ae290d6R24 which gets called at each document opening by a new Reader instance, but the KoboLight object is permanent and gets its self.steps re-scaled each time with:
  `self.steps[i] = math.ceil(self.steps[i] * scale)`
Moving the `steps = { 0.1, 0.1...` from WidgetContainer:new to KoboLight:init() , so it gets reset each time init() is called, solves the problem.

**Closed** 2017-03-11 20:10 UTC
Labels: bug

**Comment by Hzj-jie** [comment] 2017-03-15 11:01
It's weird, I thought init will only be called in new. Is there anything I haved missed?

**Comment by Hzj-jie** [comment] 2017-03-16 03:04
Got the trace. It's really hidden.
