### ISSUE TITLE
FR: A library view option.

### ISSUE THREAD

**Issue by avijitb129** [koreader/koreader#10018] opened 2023-01-11 09:08 UTC
In moon+ reader pro application, there's a shelf view where you can import books and read directly, rather than going to the book directory folder
It looks like this
![Screenshot_20230111-145749](https://user-images.githubusercontent.com/62600282/211762761-12ba3f12-226c-4904-ba39-d68887b9d964.png)
![Screenshot_20230111-145749~2](https://user-images.githubusercontent.com/62600282/211762789-e0660cf9-5273-4962-9f44-34932ebccb9c.png)
There's an option to chose book from folders, authors, tags and series
![Screenshot_20230111-150245](https://user-images.githubusercontent.com/62600282/211763388-56d529a5-1bf5-4e0d-b2c4-5c7fbb740094.png)
Size of the book covers can be changed as well and the shelf columns and rows can be changed
![Screenshot_20230111-150600](https://user-images.githubusercontent.com/62600282/211764001-50a19a37-4a25-449b-ac8d-56a7c6375f60.png)
So, i think the homescreen view similar to moon+ would be a cool feature that should be added to Koreader. Thanks in advance.
![Screenshot_20230111-145739](https://user-images.githubusercontent.com/62600282/211764664-615860c4-f126-4a89-8d8d-2f9817c00eeb.png)

**Comment by hius07** [comment] 2023-01-11 09:24
Favorites with "Display mode: Mozaic with cover images" are pretty much the same.

**Comment by avijitb129** [comment] 2023-01-11 09:28
> Favorites with "Display mode: Mozaic with cover images" are pretty much the same.

But i would have to manually chose all my books into favorites. And in that case all my books would have to be 'favorited'.

**Comment by poire-z** [comment] 2023-01-11 09:31
Duplicate of #8472

**Closed** 2023-01-12 21:46 UTC
Labels: enhancement, duplicate
