### ISSUE TITLE
Freescale e-ink devices don't draw properly (Tolino, Onyx Boox Note, Hanvon E960 plus)

### ISSUE THREAD

**Issue by michaelachmann** [koreader/koreader#3517] opened 2017-11-24 14:09 UTC
* KOReader version: 1.4 cdd8055e28e3cf52b62adbd534e72ffcc048b81d and 5ee6c0122348c4f9873332cae77676103ef002d4
* Device: Tolino Epos (Android 4.4.2)

#### Issue
KOReader does not respond to touch gestures. Drawing the menu from the top of the page works, but nothing is clickable, not the items in the file manager nor the items in the menu

#### Steps to reproduce
Install the .apk on a Tolino Epos and open the app. Nothing happens.

**Comment by Frenzie** [comment] 2017-11-24 15:25
Can you just install apps on one of these Tolino devices or does that require some kind of rooting?

It's very odd that something Android-based wouldn't just work as far as tapping or swiping goes. I'm especially confused by the fact that you say you can get the menu to appear. When you say "touch gestures", do you simply mean tapping?

**Comment by michaelachmann** [comment] 2017-11-24 15:34
touch gestures equals tapping, I lacked the right word, since I'm not native.

The Tolino devices need to be booted with fastboot into debug mode in order to install apps via adb. Once this is applied an alternative launcher can be install on the device, so no root is required. I could only find one source of information in a German forum [1] since these devices are mostly sold in German speaking countries (Germany, Austria, Switzerland). The members of the forum seem to have trouble using KOReader on this device as well, some of them argued the actual problem might be the display not refreshing. 
There might be some truth in this statement (I'm fairly new to this technology, so I really can't judge whether this is a possibility from the technical point of view) since the "Home" button on the device seems to be invoking "Back" rather then "Home". Once I tapped away on the Start Screen of KOReader I need to push the Home button more often, which might be a sign that the app invoked different Intents upon tapping but the display does not show the invoked intent..

[1] https://forum.alles-ebook.de/showthread.php/6516-Tolino-Epos-Anderen-Launcher-und-eigene-Apps-installieren-(Anleitung)

**Comment by Frenzie** [comment] 2017-11-24 16:11
If KOReader doesn't refresh the screen then presumably neither should any other Android app that hasn't been especially modified for Tolino (which would be… super annoying to put it mildly).

It should be easy to see whether the program is detecting user input or not by checking the `adb logcat` output.

If it outputs some stuff like this when you tap then it's registering and painting to the virtual screen. It'd look slightly different on Android but it's the same principle:

```
11/24/17-17:00:28 DEBUG single tap detected in slot 0 {
    ["y"] = 74,
    ["x"] = 174,
    ["h"] = 0,
    ["w"] = 0
}
11/24/17-17:00:28 DEBUG AutoSuspend: onInputEvent
11/24/17-17:00:28 DEBUG blitFrom 15 9 0 0 36 36
11/24/17-17:00:28 DEBUG blitFrom 83 9 0 0 36 36
11/24/17-17:00:28 DEBUG blitFrom 151 9 0 0 36 36
11/24/17-17:00:28 DEBUG blitFrom 489 9 0 0 36 36
11/24/17-17:00:28 DEBUG blitFrom 7 324 0 0 48 48
```

If, on the contrary, it's not displaying any messages about detecting taps or swipes (or holds) then the problem is in touch detection.

Note that this will only help pinpoint where the problem lies, but it wouldn't bring us any closer to a solution. I can't find any documentation about any special Tolino APIs.

**Comment by michaelachmann** [comment] 2017-11-24 16:18
Logcat output looks like this:
```
I/KOReader( 3068): DEBUG input event => type: 3, code: 57(nil), value: 0, time: 1511540185.408097
I/KOReader( 3068): DEBUG input event => type: 3, code: 53(Y), value: 83, time: 1511540185.408106
I/KOReader( 3068): DEBUG input event => type: 3, code: 54(Z), value: 480, time: 1511540185.408112
I/KOReader( 3068): DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1511540185.408118
I/KOReader( 3068): DEBUG in tap state...
I/KOReader( 3068): DEBUG set up hold timer
I/KOReader( 3068): DEBUG input event => type: 3, code: 47(S), value: 0, time: 1511540185.489975
I/KOReader( 3068): DEBUG input event => type: 3, code: 57(nil), value: -1, time: 1511540185.489993
I/KOReader( 3068): DEBUG input event => type: 3, code: 53(Y), value: 83, time: 1511540185.489999
I/KOReader( 3068): DEBUG input event => type: 3, code: 54(Z), value: 480, time: 1511540185.490005
I/KOReader( 3068): DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1511540185.490011
I/KOReader( 3068): DEBUG in tap state...
I/KOReader( 3068): DEBUG set up tap timer
I/KOReader( 3068): DEBUG in tap timer true
I/KOReader( 3068): DEBUG single tap detected in slot 0 {
I/KOReader( 3068):     ["y"] = 480.74319458008,
I/KOReader( 3068):     ["x"] = 83.940216064453,
I/KOReader( 3068):     ["h"] = 0,
I/KOReader( 3068):     ["w"] = 0
I/KOReader( 3068): }
```
Infact I installed also other apks like F-Droid and Amaze, both of which work perfectly well...

**Comment by Frenzie** [comment] 2017-11-24 19:14
Presuming that those detected taps keep coming then it'd indeed be some kind of screen refresh issue.

> Infact I installed also other apks like F-Droid and Amaze, both of which work perfectly well...

Well, that's quite peculiar. Is it possible that the Tolino drivers expect "bad" behavior (i.e., lots of animations) and therefore optimizes KOReader's "good" behavior (i.e., very few screen updates) away?

Really this whole menu thing makes no sense. :-( Why would screen updates be ignored with the sole exception of showing the menu?

**Comment by kareliot** [comment] 2018-01-06 08:38
I can confirm this issue on the Tolino Epos.
I’ll by happy to help diagnose and/or test.
Would love to get Koreader working on the Epos

**Comment by KrasK** [comment] 2018-01-11 07:39
I can confirm too that Koreader not working well on Tolino Epos. I have tried different versions of Koreader including the last one (koreader-nightly-20180110). I think that the program is detecting user input but does not refresh the screen. If I use Nook clear screen program to force refreshing the screen the right page is displaying. Coolreader has the same problem.
It would be great to find a solution to this problem and get Koreader working on Tolino Epos. I really like this application.

**Comment by chenxingqun** [comment] 2018-01-20 18:27
The same here, not refresh on Boox Note.

**Comment by chenxingqun** [comment] 2018-01-21 09:07
I found that after changing the display mode to A2, koreader refreshed as normal on my Boox Note. You may try to see if it works.

**Comment by kareliot** [comment] 2018-01-21 11:01
I could not find the display mode setting. How can I access it from the menu?
(it is very difficult to try to move around in the menu as I have to force a screen refresh after every tap)

**Comment by Frenzie** [comment] 2018-01-21 14:18
That would be somewhere in the system settings for the Boox Note. Whatever A2 display mode means, it's unrelated to KOReader.

**Comment by chenxingqun** [comment] 2018-01-21 18:20
Here is a video for A2 effect: 
https://www.youtube.com/watch?v=M7ArqOM7sIk
Every eink device can switch between A2 mode and greyscale mode. Some devices may do it very easy, some may very difficult.
In Boox Note there is a button on top to switch. And I found an app for Nook to switch. Sorry that not sure how it works on your device.
https://github.com/marspeople/NoRefreshToggle
And I noticed the not refresh problem happened already for some other devices, for example #1155 #1949 #1955 #3419

**Comment by Frenzie** [comment] 2018-01-21 20:21
#1155 is completely unrelated. That was just about the info dialog staying on the screen a bit long, which was fixed by changing the timeout for the `Opening…` popup:

https://github.com/koreader/koreader/blob/7797c2369e23337534050efc1113b98f993cfe9a/frontend/apps/reader/readerui.lua#L394

#1949 and #3419 have a different underlying (Pocketbook) cause that's hopefully close to being fixed in https://github.com/koreader/koreader/pull/3540

#1955 could be a duplicate of sorts if the issue I fixed was unrelated, I suppose. I never held that particular device in my hands, but it does sound a lot like the issue I fixed.

Anyway, I didn't realize you were talking about one of the waveform modes, sorry. :-) You can see the definitions here: https://github.com/koreader/koreader-base/blob/fa50167ac0529e90bb478057a95f07882cdd3ad4/ffi/framebuffer_mxcfb.lua

It looks like we use A2 for fast updates on Kindle, Kobo as well as Pocketbook, which in practice iirc is only scrolling through dragging. None of that is relevant for Android devices, mind you. If there is an API to tap into that could be investigated. However, the only problem you should normally encounter from a lack of sophistication in that area is that something might be drawn somewhat slower than you might like in situations where speed matters more than quality.

**Comment by mirh** [comment] 2018-01-25 12:37
I guess like it shouldn't be \*too\* hard to download [latest firmware](http://mytolino.de/updates/tolino-epos/), then check if `/system/app/EPubProd.apk` does anything special.

**Comment by KrasK** [comment] 2018-02-13 07:23
Is there any progress whit this issue?

**Comment by Frenzie** [comment] 2018-02-13 10:51
Not that I know of.

**Comment by taosxx** [comment] 2018-05-25 22:16
Just to add some additional information I came across concerning Tolino devices:
Some weeks ago I got my hands on a Tolino Vision 4 HD which was still running a 10.x firmware based on Android 4.0.4. I could install and run KOReader without any issues then (e.g. refresh worked fine).
Today, the Vision 4 HD was handed to me again to update its firmware to 11.2.2 based on Android 4.4.2 (same Android version Tolino Epos was running from the beginning). While KOReader can still be installed and started without a problem, it can't really be used for reading since it now doesn't refresh the screen (an exception are buttons that are pressed where you see a partial refresh). A refresh can be triggered by swiping a side-panel from the side (this is another app I had installed on the device the first time I got it).

**Comment by NiLuJe** [comment] 2018-05-26 13:14
That's... interesting, to say the least.

As was mentioned, on Android, we use a somewhat higher-level API than on pure Linux eInk devices, so, we have *no* control whatsoever on how the devices decides to handle our framebuffer updates...

So, yeah, that feels like a firmware trying to be smart about how to handle a system that's usually very busy in term of screen refreshes, and failing miserably in our case, because we don't.

**Comment by arbu** [comment] 2018-09-22 03:58
I have the same problem on my Tolino Vision 2. I took a look into the preinstalled reader apk and apparently there is a class called `ScreenHelper` which loads `libepd.so` and `libwmsex.so`. The `libepd.so` contains functions such as `EPDUpdate`, `FullRefresh`, `FullRefreshFull`, `RegionalRefresh`, `PartialRefresh`, `getFBDoneRender`, `BlankFullRefresh` and `PostFB`. This looks to me like they are directly addressing the display driver from the application. I'm not sure if it would be acceptable to implement this in KOReader for this specific devices?
Still it is strange that other apps work fine and only KOReader has issues.

**Comment by Frenzie** [comment] 2018-11-26 19:19
@arbu Coincidentally I may have come across the solution to the problem just yet, cf. https://github.com/koreader/crengine/issues/242.

There's this file:
https://github.com/buggins/coolreader/blob/a39b917f8806cbc2cb442d3ee3460ed871038297/android/src/org/coolreader/crengine/EinkScreen.java

With notably Tolino in https://github.com/buggins/coolreader/commit/d3a57ae9492a7142bc444beedb5c62ba5bd1f9ec#diff-eb9f41308b9e99ff125b58e91f174d31

I don't really have time or desire to atm myself, but it may be relatively simple to add some ability to call that stuff to https://github.com/koreader/android-luajit-launcher and to abstract it away in base.

**Comment by mirh** [comment] 2018-12-09 16:31
Also of relevance. 
https://github.com/buggins/coolreader/pull/25
https://github.com/buggins/coolreader/issues/23

**Comment by pazos** [comment] 2019-01-09 16:21
@michaelachmann @kareliot @KrasK @arbu @taosxx @mirh could you please try #4430 (comment).

**Comment by char11** [comment] 2019-03-21 20:31
Can anyone test this on tolino with new firmware (11.2.3)? On 10.1.0 works fine with full refreshes. https://ufile.io/ay18z

**Comment by Frenzie** [comment] 2019-03-21 20:48
@char11 Did you change something about that file?

**Comment by char11** [comment] 2019-03-21 21:33
Yes. I built this file.

**Comment by pazos** [comment] 2019-03-22 00:34
@char11: thanks for your time!!!

Did you implemented a new driver based on libepd.so? In that case did you implemented update methods for partial/auto/fast in the frontend?. I think that on fw11 we need to take care of all screen refreshes.

In your device with your FW, does nightlies/releases show the same behaviour as OP or it works but without full screen refreshes?

libepd might be unavailable as a system library on recent FW. I would go for using java reflection capabilities to request updates.

**Comment by char11** [comment] 2019-03-22 07:15
It requires libepd.so and wmsex.so to work properly on my device. All update methods are  implemented.
I will check in a few hours how the new release works.
On recent firmware the libepd and wmsex are still available.

**Comment by char11** [comment] 2019-03-22 18:17
New nightly build doesn't work at all. Previous release works ok but without full refreshes.

**Comment by pazos** [comment] 2019-03-22 18:52
> New nightly build doesn't work at all. Previous release works ok but without full refreshes.

That doesn't make sense to me. If a firmware works it should still work on a newer version.

Could you please make a PR with your changes?

Without source and without device I'm completely clueless about what you are talking about.

**Comment by char11** [comment] 2019-03-25 14:25
I checked with the new firmware. Refresh doesn't work (no screen at all). I noticed that the new firmware uses graphics hw acceleration...

**Comment by pazos** [comment] 2019-03-28 16:51
@char11: please, sources. In particular diffs for https://github.com/koreader/koreader-base/blob/master/ffi/framebuffer_android.lua and https://github.com/koreader/android-luajit-launcher.

If libepd.so is present as a system library (and not embedded on some apk) It should be possible to interrupt the powersaver thingy by calling some function.

**Comment by mrhrzg** [comment] 2019-04-03 15:08
> Can anyone test this on tolino with new firmware (11.2.3)? On tolino shine 2 hd with 10.1.0 works fine with full refreshes. https://ufile.io/ay18z

I tried the apk on an Tolino Shine 2HD with Firmware 11.2.3 as well. I came to the same conclusion as @char11 (https://github.com/koreader/koreader/issues/3517#issuecomment-476219719):
The screen does not refresh on changes.
It's a shame, because otherwise it seems to work very nicely. But triggering screen refreshes *by hand* is a deal breaker.

**Comment by pazos** [comment] 2019-04-03 16:52
> The screen does not refresh on changes.

We need somebody with the device, with FW11.x and some motivation to dig into system apks and figure out how the system is issuing the updates. Even if the updates are triggered by some "native" library/bin there should be a jni interface available and we can use it, like we did in #4595

**Comment by m4st3rP** [comment] 2019-04-03 17:16
> We need somebody with the device, with FW11.x and some motivation to dig into system apks and figure out how the system is issuing the updates. Even if the updates are triggered by some "native" library/bin there should be a jni interface available and we can use it, like we did in #4595
I will try that but I cannot guarantee that I will figure it out, since I have not much experience with Android.

**Comment by mrhrzg** [comment] 2019-04-03 18:21
> > The screen does not refresh on changes.
> 
> We need somebody with the device, with FW11.x and some motivation to dig into system apks and figure out how the system is issuing the updates. Even if the updates are triggered by some "native" library/bin there should be a jni interface available and we can use it, like we did in #4595

I will have a look here: https://opensource.mytolino.com/open_source/tolino-shine-2-hd/

**Comment by pazos** [comment] 2019-04-03 20:30
> Found this, does it help?: https://ufile.io/55bva
The refresh function in ScreenHelper.java (in my link above) is invoked in a lot of places. I suck at java, so I can't say if that is something you guys can invoke.
Can't find a lower level call right now (like a jni interface? noob here.)

@mrhrzg: that's exactly the JNI: a java class that load some native lib and set some native methods. I'm not sure if libepd.so is available outside the apk or bundled inside. If libepd is available outside the app then Coolreader should work on newer firmware, but apparently it doesn't work https://github.com/buggins/coolreader/issues/23

On open android ereaders normally the interface to manage the epd driver is stored in the android framework. That makes possible that all the apps work without knowing they're used on a eink device. On the tolino I'm not sure if this applies. You can search for other apks on /system/app and /system/priv-apps. In particular a Browser.apk or Settings.apk and see what they're doing to refresh the screen.

The fact that other android apps work on that device/fw makes me think that should be possible to trigger an update without interfacing directly with libepd, but maybe I'm wrong.

**Comment by mrhrzg** [comment] 2019-04-03 21:10
I did not find any relevant reference to 'refresh' or epd in the settings apk (com.android.settings_4.4.2-89.apk).
But in the man interface apk I found the following:
```
$ grep -rnw . -e epd                                                                                                           
./de/telekom/epub/ui/activities/BasicViewerActivity.java:2587:                intent.setComponent(new ComponentName("ntx.epd", "ntx.epd.EPDRefreshActivity"));
./de/telekom/epub/utils/ScreenHelper.java:137:            System.loadLibrary("epd");
./de/telekom/epub/utils/reflection/ReflectionUtil.java:186:            Class.forName("com.koobe.android.lib.epd.EPDWrapper").getMethod("enableAutoWaveformMode", Boolean.TYPE).invoke(null, bl);
./de/telekom/epub/utils/reflection/ReflectionUtil.java:228:            GenericDeclaration genericDeclaration = Class.forName("com.koobe.android.lib.epd.EPDWrapper");
```

**Comment by pazos** [comment] 2019-04-03 23:18
> I remembered that the program nookclearscreen.apk can be used to force a full refresh.

yeah, invalidating a view works too for standard android applications (based on android view hierarchy)

Did you install einkTest.apk from https://github.com/koreader/koreader/releases ? It should report some info about your device. This is an example of an application that just works because it is based on android view hierarchy.

>  Class.forName("com.koobe.android.lib.epd.EPDWrapper").getMethod("enableAutoWaveformMode", Boolean.TYPE).invoke(null, bl);

That's exactly the kind of stuff we need, but with some context. We need to know the name of the class and the name of the method used to update the screen.

If you want to add support for the driver I would recommend using https://github.com/koreader/android-luajit-launcher/blob/master/src/org/koreader/device/rockchip/RK33xxEPDController.java as a template, with a valid name for class and method and with valid method parameters. In that sense the tolino should be similar to a nook since both are based on freescale mx platform.

**Comment by mrhrzg** [comment] 2019-04-04 07:34
einktest.apk gives me the following infos:
Manucafturer: Rakuten Kobo Inc.
brand: RakutenKobo
Model: tolino
Product: ntx_6sl
Hardware: E60QF0

neither rk30xx button works, as is to be expected.

the rest I'll look into later, @pazos

**Comment by pazos** [comment] 2019-04-04 10:24
```
Manucafturer: Rakuten Kobo Inc.
brand: RakutenKobo
```

Woooot !?¿!, awesome

**Comment by Frenzie** [comment] 2019-04-04 12:20
You didn't know they bought Tolino? Still interesting to hear that it's made it into the hardware now, of course. :-)

https://the-digital-reader.com/2017/01/01/rakuten-kobo-deal-acquire-tolino-deutsche-telecom-wait/

**Comment by mrhrzg** [comment] 2019-04-04 15:39
Is this relevant? from EPubProd.apk: de/telekom/epub/application/UIConstants.java
```
    public static final String BROADCAST_ACTION_EINK_APPLICATON_REFRESH = "android.intent.action.EINK_APPLICATION_REFRESH";
    public static final String BROADCAST_ACTION_EINK_REFRESH = "android.intent.action.EINK_REFRESH";
```

**Comment by pazos** [comment] 2019-04-07 23:23
@mrhrzg: Do you have adb available?. Since you rooted your device, do you have adb as persistent setting (aka available on boot) ?

I think it is better to discuss some of these things in private, can we have a conversation on gitter?

**Comment by pazos** [comment] 2019-04-07 23:30
> can we have a conversation on gitter?

The same for other people with android eink devices based on freescale, who want to help providing logs and testing stuff via einkTest.

The idea is implementing a driver using a [clean room design](https://en.wikipedia.org/wiki/Clean_room_design)

**Comment by mrhrzg** [comment] 2019-04-09 11:37
@pazos sure. Can you invite me on gitter, please?

**Comment by saturn-hh** [comment] 2019-04-13 21:52
Hi, this is my first post and I want to say thank you for your work and the great effort.

I have a tolino shine 2 HD with the same symptoms and want to support the process. I'm not a developer but I have some knowledge about adb and cli.

How can I help?

**Comment by Frenzie** [comment] 2019-04-14 07:08
For starters just grab the eInkTest from https://github.com/koreader/koreader/releases/tag/v2019.04 to see if it does anything.

**Comment by char11** [comment] 2019-04-14 16:42
After adding this code to eink-test, tolino full refreshes the page after pressing the "fake update". This method doesn't work on koreader. I don't now why. I'm not a Java programmer. I am not a programmer at all. There are more invalidate methods (post, delayed)... Any suggestions? I'm digging, trying...

`import java.lang.reflect.InvocationTargetException;`

    public static void view_invalidate(View view, int updateMode) {
        try {
            Log.d(TAG, "view_invalidate");
            Class cls = view.getClass();
            cls.getMethod("invalidate", new Class[]{Integer.TYPE}).invoke(view, new Object[]{Integer.valueOf(updateMode)});
            Log.d(TAG, "invoked class method: " + cls);
        } catch (SecurityException e) {
            Log.e(TAG, e.getMessage(), e);
        } catch (NoSuchMethodException e2) {
            Log.e(TAG, e2.getMessage(), e2);
        } catch (IllegalArgumentException e3) {
            Log.e(TAG, e3.getMessage(), e3);
        } catch (IllegalAccessException e4) {
            Log.e(TAG, e4.getMessage(), e4);
        } catch (InvocationTargetException e5) {
            Log.e(TAG, e5.getMessage(), e5);
        }
    }
```
.
.
.
            } else if (test == FAKE) {
                Log.i(TAG, "fake update");
				view_postInvalidate(v, 34);
            } else {


```

**Comment by char11** [comment] 2019-04-15 05:53
Of course, it should be:

            } else if (test == FAKE) {
                Log.i(TAG, "fake update");
	            view_invalidate(v, 34);
            } else {

**Comment by char11** [comment] 2019-04-15 19:16
This method doesn't work on nativeactivity.

**Comment by pazos** [comment] 2019-04-17 14:55
@char11 

> yeah, invalidating a view works too for standard android applications (based on android view hierarchy)

And a possible solution for this limitation on https://github.com/koreader/koreader-base/issues/796#issue-401045402


But, again, invalidating a view just forces the driver to issue a screen refresh. So a shortcut to request the screen refresh might be available for us to invoke.

**Comment by char11** [comment] 2019-04-18 14:26
It look's like the refreshing is done by the addEPDC native function (libgui library) in surface.java. How to get surface from nativeactivity? Is it posibble at all?

**Comment by pazos** [comment] 2019-04-18 22:37
> It look's like the refreshing is done by the addEPDC native function (libgui library) in surface.java. How to get surface from nativeactivity? Is it posibble at all?

Errr, yes. It should be possible but not as easy as talking to the epd.

For @char11 and other people interested in helping (@saturn-hh, @mrhrzg...)

You need a few steps to provide info. I know, I know, that's not nice, but, in order to understand whats happening we need to:

1 - get a full logcat of the system issuing a full eink update (using the vendor app is recommended)
2 - get a full logcat of a 3rd party app issuing a full eink update
3 - get a full logcat of KOReader running on the device
4 - find libepd.so and libwmsex.so in system libraries (or inside app bundles)

There are a lot of system "apps" in android which can be in charge so the best method is just running `adb logcat -c` followed by `adb logcat *:I`

For discussion I would recommend https://gitter.im/koreader/koreader. Please ping me there. I would love to add support to android freescale socs since IMHO they're waaay better than rockchip ones.

**Comment by char11** [comment] 2019-04-20 18:49
It's working! I tried Opengl - the refresh did not work. Native functions did not work due to lack of permissions (original apps run on system permissions). A little more tests and the code I will give after Easter.

**Comment by mirh** [comment] 2019-04-21 12:24
If there aren't specific blocks, system permissions are a command away from being available to every app:
`adb shell pm grant org.koreader.test.eink com.example.permission.SUPER_REFRESH`

**Comment by pazos** [comment] 2019-04-21 16:37
> It's working! I tried Opengl - the refresh did not work. Native functions did not work due to lack of permissions (original apps run on system permissions). A little more tests and the code I will give after Easter.

Cool. We can wait then!. 

> If there aren't specific blocks, system permissions are a command away from being available to every app: `adb shell pm grant org.koreader.test.eink com.example.permission.SUPER_REFRESH`

I'm not sure, but I understand that installing the app in /system/priv-app (or /system in general) is a prerrequisite to being able to request some permissions. In that case we need to fix #4770 first.

**Comment by char11** [comment] 2019-04-22 07:13
Here is patch to v2019.4 https://pastebin.com/ieUPqVvc . I think that this method should work on other devices using default refreshes. Do not judge my code - I'm not a developer.

**Comment by pazos** [comment] 2019-04-22 14:25
@char11: your diff is great and seems generic enough to be used in a lot of freescale eink devices!!. Thanks!!!

Also, I don't have any android eink device but it seems possible that common view methods invalidate() and postInvalidate() work now.

Just tested the override NativeActivity surfaces stuff and works great on emulator. BTW, nice catch w/ `surface.setWillNotDraw(false);` I will try to find time this week to build a common package for testing in both tolinos-freescale and rockchip devices, but AFAIK it should work almost as is.

Again, thanks!

**Comment by char11** [comment] 2019-04-22 19:28
You're welcome. I just wanted to use Koreader on my new reader. Thanks for your work..

**Comment by rola25** [comment] 2019-04-27 07:50
@char11  Do you have an APK for test? I have a rootet Tolino Epos where I could make some tests ...

Thanks!

**Comment by Frenzie** [comment] 2019-04-27 07:56
@rola25 A test APK has been attached [here](https://github.com/koreader/android-luajit-launcher/pull/143#issuecomment-487107387). That code will soon make it into a KOReader nightly build as well.

**Comment by rola25** [comment] 2019-04-27 08:47
I already tried this one but it doesn't work on my Tolino Epos, still no refresh

**Comment by char11** [comment] 2019-04-27 11:06
@rola25 https://ufile.io/9h9zw3dg 
Are you rooted 11.2.3 firmware (I just noticed that there is a new 12.2.0 firmware - must try it)? How did you do that? Any info, links?

**Comment by char11** [comment] 2019-04-27 11:21
With the new firmware (12.2.0) it works too.

**Comment by rola25** [comment] 2019-04-27 11:29
Hi I tested it with 11.2.3 -> works superb, thanks!
Regarding Rooting: I used https://www.mobileread.com/forums/showthread.php?t=280106&page=3.
In principle it works like:
- boot the tolino in fastboot mode
- make a custom boot image which starts adb as root (script is also mentioned in the article - you have to extract the boot.img from the update.zip an patch it)
- flash this new boot.img via fastboot
- then you can use all adb commands as root an transfer su, supersu and so on

**Comment by fuero** [comment] 2019-04-27 12:07
Tolino Vision 4 HD, FW Version 12.2.0.

Patch works fine.

Furthermore, to make the Tap2Flip thing (keycode 195, scancode 248 according to key event viewer) work, I've added this event map:

```
return {
  [195] = "LPgFwd",
  [248] = "LPgFwd"
}
```

Why one value isn't sufficient I don't know.  How would double tapping a button to go back a page work?

**Comment by char11** [comment] 2019-04-27 12:07
Thanks. I knew it but I can't transfer su on new firmware (permission error). Sorry for offtopic.

**Comment by pazos** [comment] 2019-04-29 23:18
> I think we should wait for the official release from pazos.

@char11, sorry I was busy last week. My idea is to integrate your patch for tolino/freescale like [the rockchip ones](https://github.com/koreader/android-luajit-launcher/tree/master/src/org/koreader/device/rockchip) to be used as is in einkTest.

I need a few free hours to tinker with it and push some build for you to test and I think I won't get that free time until friday.

I think that the following static method will work to invoke updates, but I won't be able to test it.

```java
    public static boolean requestEpdMode(long delay, int x, int y, int width, int height, int mode) {
        try {
            Class.forName("android.view.View").getMethod("postInvalidateDelayed", new Class[] {
                Long.TYPE,
                Integer.TYPE,
                Integer.TYPE,
                Integer.TYPE,
                Integer.TYPE,
                Integer.TYPE
            }).invoke(null, new Object[] {
                Long.valueOf(delay),
                Integer.valueOf(x),
                Integer.valueOf(y),
                Integer.valueOf(width),
                Integer.valueOf(height),
                Integer.valueOf(mode)
            });
            return true;
        } catch (Exception e) {
            Log.e(TAG, e.toString());
            return false;
        }
    }
```

Also, I will need some time to rework the EPD interface, since it is pretty basic right.

**Comment by char11** [comment] 2019-05-01 14:43
For this method should be left, top, right, bottom parameters. Why you not pass created surface to the function but calling class.forname? Are you postInvalidate surfaceview in your testing apk (in the merged code I didn't find this method)? This should refresh screen also on tolinos and not doing it.

**Comment by pazos** [comment] 2019-05-01 17:49
> For this method should be left, top, right, bottom parameters

Yeah, I know, NTX hardware is capable of updating only a region of the screen. This region needs to be a rect. left = x, top = y, right = width and bottom = height.

> Why you not pass created surface to the function but call class.forname?

To be able to repurpose the abstract class as is in other contexts (like in einkTest activity). If this doesn't work we can feed the View as a parameter, but should work as is since SurfaceView extends the View class.

> Are you postInvalidate surfaceview in your testing apk (in the merged code I didn't find this method)? This should refresh screen also on tolinos but it doesn't.

EinkTest is generated based on current code. I will implement a few methods, but need the proper abstract classes first. But yeah, postInvalidate should work on other devices too

**Comment by char11** [comment] 2019-05-01 18:56
Ok. Now I understand. 
I mean test apk from https://github.com/koreader/android-luajit-launcher/pull/143

**Comment by pazos** [comment] 2019-05-01 19:35
oh, the test apk was for people using a currently supported rockchip android eink device. I cannot test it myself. But yeah that version don't have support for tolino/freescale.

**Comment by flintpaper** [comment] 2019-05-05 09:09
I've tried the [apk](https://github.com/koreader/android-luajit-launcher/pull/143) on a tolino vision hd 4 with 12.1.0 firmware and Android 4.4.2. Koreader still doesn't refresh. I have tried the recent nightlies as well and had no luck. Any progress yet?

**Comment by hiworld3** [comment] 2019-05-24 19:49
please add support to Freescale, koreader is excellent but it crashes everytime on my gear (freescale single core, Android 4) thanks a lot

eink.apk shows
Manufacturer: Onyx
Brand: Onyx
Model: MaxCarta
Product: MaxCarta
Hardware: Freescale
Platform: imx6

behaviors are like these
1, while reading one book, and enter the file manager and select another book, it fails, often open the last-read book instead of the selected book. Even press the file manager on the top bar (haven't enter the file manager), it suddenly reopen the last-read book. Sometime press the screen to next page or press the toolbar at bottom will reopen the last-read book.

2, can't exit. I only use fullscreen mode, and I hit the exit button it only opens the last-read book or reopen the current book, only 1 out of 10 it could exit. The gear has no HW home button so I can't fast jump to home page like that.

3, can't open Djvu files, saying no engine found...

thanks.. (I don't have the gear on my hands so I can't upload the log, I tried many versions including nighty betas)

**Comment by pazos** [comment] 2019-05-24 20:16
@hiworld3: the bugs you found have nothing in common with this specific issue. Please open one issue per bug (you already opened a bug for 3.) and report a working log reproducing each bug. Without logs nothing can be done and even with logs probably we cannot fix things we can't reproduce (like 3, since I can repro on Jelly Bean because the "pow" bug, but not on Ice Scream Sandwitch).

**Comment by Frenzie** [comment] 2019-05-24 20:17
@hiworld3 You didn't say what the behavior of the buttons in the EInkTest app is.

> while reading one book, and enter the file manager and select another book, it fails, often open the last-read book instead of the selected book.

By the file manager, do you mean a built-in Onyx file manager app?

> 2, can't exit.

Same as above. This sounds like an issue with your file manager app.

> 3, can't open Djvu files, saying no engine found...

I was going to say at least one issue already exists, but curiously it's your own: #5014.

In any event, none of this has anything to do with this issue. Please open separate issues.

**Comment by hiworld3** [comment] 2019-05-25 05:37
hi, I will open the new issue but I'm sure I understand your meaning that you mean, but I will describe it here first

> 
> 
> @hiworld3 You didn't say what the behavior of the buttons in the EInkTest app is.
> 
actually I don't understand you what mean about behavior of "buttons", what is normal behavior? as I posted about "behavior of the buttons", I already said there're three buttons in eink.apk,  none of these three button happen to have any "behavior", I clicked these three buttons, it just nothing happens.
click "fake update", it shows "fake update" in there,
click "rk update", it shows "rk update" in there, that's that
alth during reading it can refresh, like 5 page per refresh, i don't know what is normal.


> 
> By the file manager, do you mean a built-in Onyx file manager app?
> 
all I'm talking about it is within the koreader, in koreader top tool bar right side, you can enter a "thing", you can browse the files, right? I don't know what is it call, so I called it file manager. It's a funtion within koreader, not outside 

> 
> > 2, can't exit.
> 
> Same as above. This sounds like an issue with your file manager app.
> 
it's within koreader, not another app.

> 
> > 3, can't open Djvu files, saying no engine found...
> 
> I was going to say at least one issue already exists, but curiously it's your own: #5014.
> 
> In any event, none of this has anything to do with this issue. Could you please open separate issues?

All these're all complicated twisted, the gear isn't here but I found the SD card with koreader in it, I can't found "log" files in the folder, sorry, maybe there's another "koreader" folder on the gear ifself, I don't know, I installed it on sd card

**Comment by Frenzie** [comment] 2019-05-25 06:39
> I already said there're three buttons in eink.apk

Somewhere maybe, but definitely not here. ;-)

Nothing's necessarily "normal". It's just that an incomplete report isn't all that useful.

> all I'm talking about it is within the koreader, in koreader top tool bar right side, you can enter a "thing", you can browse the files, right? I don't know what is it call, so I called it file manager. It's a funtion within koreader, not outside

A book "suddenly" opening within KOReader doesn't make any sense. Is it possible that you bound reopening the last document to one of the corners or a gesture and forgot about it?

**Comment by hiworld3** [comment] 2019-05-27 09:59
update about the refresh: my gear is back I did some tests, I use touch screen koreader could not refresh, only I use page button it will force refresh every 5 page. the page button using system's own driver, and using page button to turn page is much slower than using touch screen to turn the pages, I don't know why the speed are so different

looks like Freescale still doesn't get proper driver, if Freescale devices don't have page button, it will not refresh at all

ps. I think all the weird behaviors are related to Freescale as the OP posted in this thread 1#, his Freescale gear having more trouble than mine, at least mine can touch the menu normally most of the times and has normal response

> Issue
>
> KOReader does not respond to touch gestures. Drawing the menu from the top of the page works, but nothing is clickable, not the items in the file manager nor the items in the menu

**Comment by Frenzie** [comment] 2019-05-27 10:48
> weird behaviors = "don't draw properly", at least that's my understanding

Okay, that makes a lot more sense. So there's no random opening or reopening of files, just semi-random screen updates.

**Comment by pazos** [comment] 2019-06-05 18:44
@char11: could you please upload your diff again? thanks!

**Comment by char11** [comment] 2019-06-06 19:39
https://pastebin.com/rXgYYpaS

**Comment by pazos** [comment] 2019-06-07 14:19
@char11: thanks! Initial implementation is live on https://github.com/koreader/android-luajit-launcher/commit/c2d7ce13dd4272866e2b287b735dd0442348aade

I tried to repurpose most of your code there. I will upload a debug build, so you (and others) can report if that build works

**Comment by pazos** [comment] 2019-06-07 15:44
@char11 @fuero @rola25: here is the debug build -> https://www.dropbox.com/s/c71waksctotlxyq/koreader-android-arm-freescale.apk?dl=0

Steps:

1 - uninstall KOReader
2 - install this build
3 - run KOReader and test if it works like char11 build.

if it works good, if no I would need the following log `adb logcat KOReader:D epd:* *:F`

**Comment by char11** [comment] 2019-06-07 18:07
On my reader it works fine.

**Comment by pazos** [comment] 2019-06-07 18:27
great! pinging @carlinux @Cellaris @hugleo. Could you guys test this build on your likebooks? I want to make sure I didn't break anything and things still work on other devices

**Comment by hugleo** [comment] 2019-06-08 00:13
fine here too

**Comment by pazos** [comment] 2019-06-08 12:41
Updated the einkTest apk. It has a new test for Tolinos -> https://www.dropbox.com/s/mp5wpi35g09unjy/einkTest.apk?dl=0

It should work on compatible devices and that means we're done :smile:

@char11: could you test it? thanks!

**Comment by char11** [comment] 2019-06-08 14:11
It's works with full refresh.

**Comment by Cellaris** [comment] 2019-06-08 15:38
It works on all my devices, including the Tolino Shine 3. Great job. Thank you.

(EinkTest also works on Tolino Shine 3).

**Closed** 2019-06-10 13:26 UTC
Labels: Android, bug, firmware, help-wanted, low-hanging-fruit

**Comment by nbngoc93** [comment] 2020-10-24 08:12
My device is unable to refresh screen although I did choose setting -> Screen Timeout -> Keep screen on? My device is Onyx Boox Viking. @pazos

**Comment by pazos** [comment] 2020-10-24 11:33
@nbngoc93: I don't understand :(. If you're able to see the menus then the screen is refreshing. If you're talking about "full refresh each n pages" please look at https://github.com/koreader/koreader/issues/4551

If you're using a modern KO version you can open the EPD test from the application in the Filemanager -> tools -> more tools -> developer options -> start epd test activity.

Please comment on the other ticket if you find that your device works with one of the supported routines.

**Comment by nbngoc93** [comment] 2020-10-24 11:40
Sorry my English is bad. I mean app only work with A2 mode, Normal refresh mode doesn't work. @pazos

**Comment by pazos** [comment] 2020-10-24 11:52
In that case see https://github.com/koreader/koreader/issues/5073. It was solved on *some FW upgrades* for *some* devices.
It is a won't fix, so patches welcome.

**Comment by nbngoc93** [comment] 2020-10-24 11:53
@pazos thank you
