### ISSUE TITLE
Tolino Epos 3 - Screen Refresh not working

### ISSUE THREAD

**Issue by Anenden** [koreader/koreader#12357] opened 2024-08-15 11:14 UTC
Tolino Epos 3
KOReader arm 2024 07 version

The Screen Refresh feature does not work on the Tolino Epos 3. 

The setting is not visible for the device under the E-Ink Settings. Furthermore, the setting is invisible under the gestures setting but does not do anything.

Would it be possible to add Screen Refresh to the Tolino Epos 3 on KOReader? I would be so glad, it is essential for manga!

I now downloaded the latest nightly and the Full Screen Refresh setting is present but does not work

**Comment by pazos** [comment] 2024-08-15 12:58
Duplicate of #8482

**Closed by pazos** 2024-08-15 12:58 UTC
Labels: enhancement
