### ISSUE TITLE
FR: add notification for "invert page turn buttons" gesture

### ISSUE THREAD

**Issue by benasocj** [koreader/koreader#12542] opened 2024-09-22 14:05 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
When applying the "invert page turn buttons" gesture, no notification is shown informing one that the setting has been changed (as is the case for other gestures such as "toggle page turn direction").

**Describe the solution you'd like**
Add a notification such as "Inverted/Default page turn buttons".

**Comment by Commodore64user** [comment] 2024-09-22 14:43
Duplicate of #12239.

Already has been solved. Should go live with next release.

**Closed** 2024-09-22 14:47 UTC
Labels: enhancement

**Comment by benasocj** [comment] 2024-09-22 15:44
Oh, I'm sorry :frowning_face:. Usually, I'm always checking for duplicates but this time I forgot to check.

Thanks for linking the duplicate issue.
