### ISSUE TITLE
Koreader crashing on Pocketbook Touch Lux 4 with FW 6.0.1118

### ISSUE THREAD

**Issue by newwolf** [koreader/koreader#6412] opened 2020-07-21 20:04 UTC
* KOReader version: 6.0.1118
* Device: PB627 

I'm totally new in the e-book world so please don't blame me.

I would love to install Koreader on my new PB627 with FW 6.0.1118, but when I start the program it's crashing instandly.
Could anyone tell what's wrong?

##### `crash.log` (if applicable)

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 07/21/20-20:58:53
 [*] Version: v2020.07.1

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
07/21/20-20:58:53 INFO  SoftwareVersion:  U627.6.0.1118
07/21/20-20:58:53 INFO  Blacklisting the C BB on this device
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
PB FB: smem_len    : 786432
PB FB: line_length : 768
PB FB: xres        : 758
PB FB: xres_virtual: 758
PB FB: yres        : 1024
PB FB: yres_virtual: 1024
PB FB: bpp         : 8
PB FB: xres_virtual -> 768
PB FB: line_length -> 768
FB: computed size: 786432
FB: id           : 
FB: smem_len     : 786432
FB: line_length  : 768
FB: xres         : 758
FB: xres_virtual : 768
FB: yres         : 1024
FB: yres_virtual : 1024
FB: bpp          : 8
Atached mp shm: id 0 addr 403de000 size 17608
epdc_default_init
attach_shm: mtfb key=251330812 size=843924
Atached mtfb shm: id 78009 addr 42921000 size 843924
-------------------------
The task - koreader.app fb 0x42921000
 xres=758 yres=1024 scanline=768 vdepth=8 orient=0
-------------------------
attach_shm: ref key=2130378752 size=786432
Atached ref shm: id 8001 addr 42ad9000 size 786432
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800002; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 10000 0 0 0 10000
ffi.load: inkview
07/21/20-20:58:54 INFO  initializing for device PBLux4
07/21/20-20:58:54 INFO  framebuffer resolution: {
    ["h"] = 1024,
    ["w"] = 758
}
[260 : ./luajit] (hw_nextevent)mq_receive ret -1 (Resource temporarily unavailable)
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
```

**Comment by pazos** [comment] 2020-07-21 20:10
Probably a duplicate of #6000

**Closed** 2020-07-25 13:19 UTC
Labels: PocketBook, bug, duplicate
