### ISSUE TITLE
Screenshot in Image viewer

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#6699] opened 2020-09-23 14:28 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
There is no way (I think ;o) to have a part of an image (zoomed in par example) as screensaver.
In pdf you can change the cropping to manual, take a screenshot and then return to your original cropping, but in epub, this is not possible.
So I had to use a sub par screenshot :o(

**Describe the solution you'd like**
Either enable the screenshot capturing gesture in image viewer, or add a screenshot button (along with the others of the image viewer) that can take a screenshot (without the buttons been visible of course)

**Additional context**
Two different scenarios I encountered this summer:

- I was reading an omnibus that had covers for every book it contained, but they were smaller then the screen and at the top-left corner.
- I had a series of books that the publisher somehow forgot to mark the cover image as cover and although it existed, KOReader didn't recognize it.. Cover image was also smaller than my screen and at the top-left corner.

**Comment by poire-z** [comment] 2020-10-02 19:53
Duplicate of #1914 .
But might be hope, see https://github.com/koreader/koreader/issues/1914#issuecomment-702927965

**Closed** 2020-10-03 16:12 UTC
Labels: UX, enhancement
