### ISSUE TITLE
Blank title page - Cover is not displayed

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#7227] opened 2021-02-02 08:14 UTC
* KOReader version: v2021.01.1-16-ga192a33_2021-01-31 and v2021.01.1-16-ga192a33_2021-01-31 
* Device: Pocketbook InkPad 3

#### Issue
I noticed in the two nightlies mentioned above that the title page in EPUB files stays blank. The cover image is not displayed. This bug is not present in the current stable version 20210101.

#### Steps to reproduce
Open any EPUB to page 1. 
Page stays blank, even though cover image is built into the file.

**Comment by poire-z** [comment] 2021-02-02 08:29
> Open any EPUB to page 1.

Not _any_, I got some that work :)
But I got one that does not anymore. On its first xhtml fragment, it has:
```xhtml
    <body>
        <div>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                width="100%" height="100%" viewBox="0 0 509 800"
                preserveAspectRatio="xMidYMid meet">
                <image width="509" height="800" xlink:href="Cover-NB.jpg"/>
            </svg>
        </div>
    </body>
```
If you can check a few of yours that do not work, if they all have this SVG > IMAGE wrapping.

Probably caused by this bunch of changes of https://github.com/koreader/koreader/commit/3c123bf119d1e7d2f3439cb0b246e4d76f589713
Looks like my above case is solved with just:
```diff
--- a/crengine/src/lvrend.cpp
+++ b/crengine/src/lvrend.cpp
@@ -2513,3 +2513,3 @@ bool is_length_relative_unit(css_length_t val)
 bool getStyledImageSize( ldomNode * enode, int & img_width, int & img_height, int container_width, int container_height ) {
-    if ( enode->getNodeId() != el_img )
+    if ( enode->getNodeId() != el_img && enode->getNodeId() != el_image )
         return false;
```

**Comment by Frenzie** [comment] 2021-02-02 08:30
> If you can check a few of yours that do not work, if they all have this SVG > IMAGE wrapping.

I think that might be at least somewhat common due to the aspect ratio thing.

**Comment by LucyOne** [comment] 2021-02-02 08:37
Yes, my EPUBs have this SVG > IMAGE wrapping.
I run all my files through Calibre EPUB -> EPUB conversion.

**Comment by Frenzie** [comment] 2021-02-02 08:38
Haha, that's a pretty important extra point to mention. So all calibre EPUBs have it. ;-)

**Comment by poire-z** [comment] 2021-02-02 12:31
The same but (ignoring `<image>`) also affects images in FB2 documents.

I wonder if we should add a hack there to handle this very common SVG wrapping (we don't currently handle such embedded SVG at all) - because previously (and with this bug fixed), we get the image drawn with its native image size, so usually quite small on our devices.

I had saved some [insertSVGImage.py](https://github.com/koreader/koreader/files/5911040/insertSVGImage.py.txt) I got from calibre or a calibre plugin (that I can't find online anymore :/) which does:
```python
width, height = self.img.size
strWidth=str(width)
strHeight=str(height)
print ("EPUB Version: " + self.epubver)
xml  = '<?xml version="1.0" encoding="UTF-8" standalone="no" ?>\n'
if self.epubver.startswith('2'):
        xml += '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">\n'
else:
        xml += '<!DOCTYPE html>\n'

xml += '<html xmlns="http://www.w3.org/1999/xhtml">\n'
xml += '<head>\n'
xml += '  <title></title>\n'
xml += '<style type="text/css">\n'
xml += '@page {padding: 0; margin:0}\n'
xml += 'body  {text-align: center; padding:0; margin: 0; }\n'
xml += '</style>\n'
xml += '</head>\n'
xml += '\n'
xml += '<body>\n'
xml += '  <div>\n'
xml += '        <svg \n'
xml += '        xmlns="http://www.w3.org/2000/svg"\n'
xml += '        height="100%"  width="100%"\n'
xml += '        preserveAspectRatio="xMidYMid meet" version="1.1"\n'
xml += '        viewBox="0 0 ' + strWidth + ' ' + strHeight + '"\n'
xml += '        xmlns:xlink="http://www.w3.org/1999/xlink">\n'
xml += '        <image width="' + strWidth + '" height="' + strHeight + '" xlink:href="../Images/' + self.pictureName + '"/>\n'
xml += '        </svg>\n'
xml += '  </div>\n'
xml += '</body>\n'
xml += '</html>\n'
```

like:
if node is el_image and its parent is el_svg (and its parent or grandparent is el_body?), just do as if it had `style="width: 100%"` - crengine will naturally ensure its height does not exceed the page height.
(I'd rather not have to parse svg's width= and height=, although that might be doable - but I'd really rather not have to parse and handle [preserveAspectRatio](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio) ... :)

**Comment by poire-z** [comment] 2021-02-02 14:29
Btw, in the above snippets:
```svg
<svg width="100%" height="100%" viewBox="0 0 509 800" preserveAspectRatio="xMidYMid meet">
     <image width="509" height="800" xlink:href="Cover-NB.jpg"/>
</svg>
```
How is that supposed to work:

**A** - the image gets its fixed 509x800 size (actually, its native size in my sample book), and it is just centered in a screen_w x screen_h container (so, somehow, that container makes a page and makes sure the next content is in a next page)

**B** - the image is scaled larger than 509x800 to fit in the container (but keeping its aspect ratio)

How does Calibre do it? Native image size or scaled image ?

If **A**, we might already do it just fine, and no hack needed !

**Comment by Frenzie** [comment] 2021-02-02 15:00
There would be no point to this hack if it were A. ;-)

The difference between this SVG and a regular `<img width=100% height=100%>` is that the SVG will keep its aspect ratio.

These are fairly well known tricks, see for example https://css-tricks.com/scale-svg/ :-)

**Comment by poire-z** [comment] 2021-02-02 20:20
Fix for this and proposed SVG wrapper hack in https://github.com/koreader/crengine/pull/416.

**Comment by poire-z** [comment] 2021-02-02 20:22
> Yes, my EPUBs have this SVG > IMAGE wrapping.
I run all my files through Calibre EPUB -> EPUB conversion.

Can you post an example of the generated HMTL from this process (assuming it's the same in all your books, except for the native image size), to see if what I did is valid for your books? (I just look at one sample book to do that.)

**Comment by poire-z** [comment] 2021-02-03 13:44
Pinging @LucyOne : https://github.com/koreader/koreader/issues/7227#issuecomment-771954088

**Comment by LucyOne** [comment] 2021-02-03 13:45
I will tonight.

**Comment by poire-z** [comment] 2021-02-03 14:09
Yes, like this snippet, even the full xhtml page, with the possible CSS at the start.
"Looked the same" but I want to be sure of that, all the little details and attribute values (viewBox, width and height, preserveAspectRatio...) matter :)

**Comment by LucyOne** [comment] 2021-02-03 17:04
Here's a title page that appeared blank:

<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="calibre:cover" content="true"/>
        <title>Cover</title>
        <style type="text/css" title="override_css">
            @page {padding: 0pt; margin:0pt}
            body { text-align: center; padding:0pt; margin: 0pt; }
        </style>
    </head>
    <body>
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" viewBox="0 0 887 1352" preserveAspectRatio="xMidYMid meet">
                <image width="887" height="1352" xlink:href="cover1.jpeg"/>
            </svg>
        </div>
    </body>
</html>

**Comment by LucyOne** [comment] 2021-02-03 17:06
Here's a title page that appeared blank:

`
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="calibre:cover" content="true"/>
        <title>Cover</title>
        <style type="text/css" title="override_css">
            @page {padding: 0pt; margin:0pt}
            body { text-align: center; padding:0pt; margin: 0pt; }
        </style>
    </head>
    <body>
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" viewBox="0 0 887 1352" preserveAspectRatio="xMidYMid meet">
                <image width="887" height="1352" xlink:href="cover1.jpeg"/>
            </svg>
        </div>
    </body>
</html>`

**Comment by LucyOne** [comment] 2021-02-03 17:07
Here's a title page that appeared blank:
 
```
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="calibre:cover" content="true"/>
        <title>Cover</title>
        <style type="text/css" title="override_css">
            @page {padding: 0pt; margin:0pt}
            body { text-align: center; padding:0pt; margin: 0pt; }
        </style>
    </head>
    <body>
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" viewBox="0 0 887 1352" preserveAspectRatio="xMidYMid meet">
                <image width="887" height="1352" xlink:href="cover1.jpeg"/>
            </svg>
        </div>
    </body>
</html>

**Comment by poire-z** [comment] 2021-02-03 17:14
Thank you, really similar indeed. So, my hack to display them scaled to full screen should work.

**Closed** 2021-02-03 20:31 UTC
Labels: CREngine, bug
