### ISSUE TITLE
Crash entering file manager on Kobo Aura

### ISSUE THREAD

**Issue by mwhdc** [koreader/koreader#6790] opened 2020-10-13 15:23 UTC
* KOReader version: 2020.10
* Device: Kobo Aura N514 with firmware 4.24.15676

#### Issue
Invoking the file manager crashes KOReader

#### Steps to reproduce
- Clean install of KOReader
- Launch KOReader via NickelMenu
- Tap file manager icon in KOReader menu bar
- Bomb screen appears, KOReader restarts

##### `crash.log` (if applicable)
./luajit: ./ffi/blitbuffer.lua:987: bad argument #1 to 'sethook' (function expected, got number)
stack traceback:
        [C]: in function 'sethook'
        ./ffi/blitbuffer.lua:987: in function <./ffi/blitbuffer.lua:974>
        ./ffi/blitbuffer.lua:1068: in function 'blitFrom'
        ./ffi/blitbuffer.lua:1176: in function 'colorblitFrom'
        frontend/ui/widget/textboxwidget.lua:800: in function '_renderText'
        frontend/ui/widget/textboxwidget.lua:170: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        frontend/ui/widget/menu.lua:361: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        frontend/ui/widget/menu.lua:1010: in function 'updateItems'
        frontend/ui/widget/filechooser.lua:297: in function 'updateItems'
        ...
        frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
        frontend/ui/uimanager.lua:781: in function 'sendEvent'
        frontend/ui/uimanager.lua:195: in function '__default__'
        frontend/ui/uimanager.lua:1170: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:1238: in function 'handleInput'
        frontend/ui/uimanager.lua:1282: in function 'run'
        ./reader.lua:300: in main chunk
        [C]: at 0x00014131
!!!!
Uh oh, something went awry... (Crash n°1: 10/13/20 @ 11:04:28)
Running FW 4.24.15676 on Linux 2.6.35.3-850-gbc67621+ (#2049 PREEMPT Mon Jan 9 13:33:11 CST 2017)
Attempting to restart KOReader . . .
!!!!

**Comment by Galunid** [comment] 2020-10-13 15:59
Most likely duplicate of #6787 
It should be fixed in the most recent nightly
Please reopen if it's still not fixed.

**Closed by Galunid** 2020-10-13 15:59 UTC
Labels: duplicate

**Comment by mwhdc** [comment] 2020-10-13 22:18
Confirmed, working in latest nightly. Apologies for the dupe.
