### ISSUE TITLE
Calibre wireless connection in eduroam network

### ISSUE THREAD

**Issue by hugomilan** [koreader/koreader#2698] opened 2017-03-31 02:19 UTC
* KOReader version: v2015.11-894-gd168db9
* Device: Kobo Aura H2O

#### Issue
I never was able to connect to my Calibre using KOReader in the eduroam network (educational network). This is the network in my university (in many others was well) and in my home. I never tried to connect using another network.

I'm sure that my device is properly connected to the internet.

#### Steps to reproduce
Set up the wireless server in Calibre (as indicated in the [wiki](https://github.com/koreader/koreader/wiki/Calibre-wireless-connection)).
Start the Calibre wireless connection in KOReader.
Get "Cannot connect to calibre server."

Any help?

**Comment by Frenzie** [comment] 2017-03-31 10:10
That could be a duplicate of #2540. You could try an older release like https://github.com/koreader/koreader/releases/tag/v2015.11-stable to see if it makes a difference.

**Comment by lgeek** [comment] 2017-03-31 14:14
Hmm, at least my University uses AP isolation and also drops all incoming connections. The calibre wireless protocol wouldn't work in that setup.

**Comment by hugomilan** [comment] 2017-04-01 02:41
I tested with the stable released and I got the same issue.
@lgeek, is there a way to overcome this limitation?

**Comment by KenMaltby** [comment] 2017-04-01 13:30
Is the PC that you run calibre on connected to a wireless router?  Can your H2O connect to that same wireless router?  Can you use calibre's content server and the KOReader OPDS calibre catalog to "download" ebook files?

**Comment by hugomilan** [comment] 2017-10-14 02:07
H2O and my PC are connected to the same wireless router. I could use calibre's content server as described in #2540. In addition, I tried to connecting to another wireless network (actually a hotspot from my smartphone) and observed what was described in #2540.

**Comment by robert00s** [comment] 2018-10-01 19:17
@hugomilan 
You can check again for the latest version. You can also try set manual server address in `calibre wireless connection -> Server address`

**Comment by hugomilan** [comment] 2018-10-05 18:29
Hi,
Thanks for working on this!

I could get my device connected to calibre after manually configuring the server. I noted some issues when doing this though. First, when I was typing the port number, the first character would just be ignore. To give more detail, the cursor would start on the far right of the input text box. Adding the first character would shift the cursor to the far left side of the input box. Text would be accepted after that. Second, after setting up the server manually, koreader became unstable and would just exit irregularly after a few seconds. So, I set the server and restarted koreader so that my server configuration would be saved in the configuration files. After restarting, I did not observe issues with koreader. And, lastly, I also observe the same irregular exiting when I set my home calibre home folder in koreader.

Besides this minor issues, things appear to be working great. Thanks!

**Comment by pazos** [comment] 2020-06-09 14:48
Can't fix the original issue. Closing this ticket.

**Closed by pazos** 2020-06-09 14:48 UTC
Labels: can't fix, question

**Comment by mirh** [comment] 2020-06-09 16:30
Mh? OP identified that ap isolation wasn't a problem, and that there must have been something going on with "automatic discovery".

**Comment by NiLuJe** [comment] 2020-06-09 16:36
Which we can't do anything about on that kind of network infra. What you can do is setup the server:port manually, which, apparently, works.

**Comment by pazos** [comment] 2020-06-09 17:23
> there must have been something going on with "automatic discovery".

Automatic discovery works **just fine** :tm: on the same subnet. Believe me I've been testing this stuff for more than a week. If your AP and calibre are in different subnets and your AP doesn't route the broadcasted "hello" package we can't do anything to fix the setup.
