### ISSUE TITLE
Cut text on bottom menu tab on Aura HD

### ISSUE THREAD

**Issue by hombretranquilo** [koreader/koreader#2538] opened 2017-02-12 00:09 UTC
* KOReader version:  since v2015.11-816 
* Device: Kobo Aura HD

Since version 2015.11-816 this menu looks wrong in some languagues:

![reader_2017-feb-11_235825](https://cloud.githubusercontent.com/assets/8158703/22858466/94760710-f0be-11e6-8830-e6598f498354.png)
![reader_2017-feb-11_235940es](https://cloud.githubusercontent.com/assets/8158703/22858465/94762d58-f0be-11e6-8bd7-46e8bb7835a5.png)

In others languages (French, English), however, looks well:

![reader_2017-feb-12_005251en](https://cloud.githubusercontent.com/assets/8158703/22858486/5f425d86-f0bf-11e6-8354-83fe4a42754e.png)

Last version working fine on Aura HD is v2015.11-814.

**Comment by houqp** [comment] 2017-02-12 03:16
two new commits in 816:
529d1b3d33007c697ab8f0d731fee8abd67c17c5
642cb8871bdcf01fd892a59a0e789b180f0f9287

I can't tell which one causes the bug by just looking at the commit message. We will have to dig into this.

**Comment by Hzj-jie** [comment] 2017-02-12 17:06
The first change regards to the DocSettings, which should not impact rendering.

**Comment by poire-z** [comment] 2017-02-19 11:49
The second change is only about crengine, so again, no impact.
I checked by chosing Spanish language, and I can confirm this happens, it's really ugly.
I tracked it down to some string in es/koreader.po (from my installed version 835-g3ea1820):
```
#: frontend/ui/data/strings.lua:20
msgid "Reflow Speckle Ignore Size"
msgstr "Ignorar el tamaÃ±o de las manchas causadas por la redistribuciÃ³n de texto"
```
If you remove this block, or shorten the msgstr, the display is fine (and i dont think this string is even used in the display :)
I dont know anything about the translation process (is there some tracked history of changes?), and how this should be fixed:
- limit length for some strings when length can have an impact (like there).
- make the code truncate oversized stringts that can impact display.

So, quickest fix would be to find and shorten these long strings in some languages .po.
Hardest fix would be to have the code (configdialog.lua ?) check rendered text size vs available space, and truncate too long text.

**Comment by Frenzie** [comment] 2017-02-19 11:53
History is on Transifex: https://www.transifex.com/houqp/koreader/translate/#es/koreader/108232633?q=speckle

Looks like until 7 days ago it wasn't translated.

**Comment by retrue** [comment] 2017-02-19 12:00
msgstr "Ignorar el tamaÃ±o de las manchas causadas por la redistribuciÃ³n de texto"
a shorter version would be:
msgstr "Ignorar manchas causadas por la redistribución de texto"
an even shorter version:
msgstr "Ignorar manchas por redistribución de texto"
I would prefer "Ignorar manchas causadas por la redistribución de texto" if there is space enough.

**Comment by Frenzie** [comment] 2017-02-19 12:09
Btw, I don't know what text editor you use but the string is encoded properly as "Ignorar el tamaño de las manchas causadas por la redistribución de texto" :-)

Unfortunately it looks like even your shorter option is too long, at least on a low-res device.

![screenshot_2017-02-19_13-08-28](https://cloud.githubusercontent.com/assets/202757/23102175/90e5fc5e-f6a4-11e6-9b40-4d4d0f055cc4.png)

**Comment by retrue** [comment] 2017-02-19 13:00
"Ignorar manchas por reflujo" or "Ignorar manchas por reflujo de texto".
Spanish is wordier than English. English books when translated to Spanish have around a 10% or 20% more pages.

**Comment by Frenzie** [comment] 2017-02-19 13:23
"Ignorar manchas por reflujo de texto" may be acceptable:
![screenshot_2017-02-19_14-07-25](https://cloud.githubusercontent.com/assets/202757/23102623/d6610352-f6ac-11e6-9424-ddb19a14349c.png)
I changed it to that in Transifex for now. The next nightly will automatically pull it in.

"Ignorar manchas por reflujo" is perfect:
![screenshot_2017-02-19_14-07-55](https://cloud.githubusercontent.com/assets/202757/23102622/d65794b6-f6ac-11e6-9e73-b1465bbe00dc.png)

> Spanish is wordier than English.

Eh, the English sentence would also gain clarity from being wordier. It used to be "Defect Size" (cf. https://github.com/koreader/koreader/commit/6091378bc62ae67f8874f5c02087dd9c8a7ab3ed) but literally only three or four people knew what it meant. It's taken from [k2pdfoptlib](https://github.com/koreader/libk2pdfopt/blob/31966bc92757db3dddada20ac35b0248a63a035c/k2pdfoptlib/k2usage.c#L222-L225). It took a while to come up with this replacement text, but I hope I succeeded at keeping it short yet also clear.

**Comment by retrue** [comment] 2017-02-19 13:37
@Frenzie Would you explain what means or what does "Reflow Speckle Ignore Size"?
I reworded the long Spanish text "Ignorar el tamaño de las manchas causadas por la redistribución de texto" with a shorter version but I don't know what the English text really means, so maybe the translation is wrong.

**Comment by Frenzie** [comment] 2017-02-19 15:30
Speckles are dots ("defects") that aren't characters. Scanning artifacts.

**Comment by Frenzie** [comment] 2017-02-19 15:32
It's called speckling/speckles in PS, ScanTailor etc. and I think it's
clearer than defects.

**Comment by retrue** [comment] 2017-02-19 16:38
Then, "manchas" is a wrong translation in this context. Motas is better here. So, it would be "Ignorar motas por reflujo de texto."
Other options would be artefactos, puntos, moteado, defectos.

**Comment by Frenzie** [comment] 2017-02-19 19:25
They don't need to be dots, of course. They're just small blemishes that tend to look like little dots. A speckle that isn't sufficiently like a small (!) dot is more of a blotch and can't be automatically ignored without having (parts of) letters and punctuation disappear as well. I'm not sure if that changes anything, but I felt my phone e-mail message might've been a tad imprecise.

**Comment by hombretranquilo** [comment] 2017-02-19 22:25
Firstly, @houqp, @Hzj-jie, @poire-z, @Frenzie, @retrue, thak you for your time.
Moreover, I cannot find the menu item «Reflow Speckle Ignore Size». Where this menu item is?. The only way I can find to configure this «Defect Size» attribute is to modify the defaults.lua file. If this is, really, the only way to configure this, translations are unnecesary. I think.

**Comment by retrue** [comment] 2017-02-19 22:33
@hombretranquilo If you have activated "Show advanced options" you will be able to see some more options when a pdf is open.
I don't know if it will show this Speckle Ignore thingie because I don't use pdfs, but you can try. Maybe it is there, maybe not.

**Closed** 2017-10-28 19:28 UTC
Labels: bug, UX
