### ISSUE TITLE
PDF reflow with increased font size is slooow, or freezes completely.

### ISSUE THREAD

**Issue by sourdoughpablo** [koreader/koreader#1672] opened 2015-10-12 03:58 UTC
Resolution of Issue #501 may solve this for me with two column PDF's but the problem will remain with one column PDF's.  I'm using a Kobo aura H2O.  My goal is to enlarge the apparent font size enough that I can read it with my old eyes.  Default font size on reflow seems to work efficiently, page turns are crisp, but the font size isn't big enough for me to read.  When I enlarge the font size, the page turns are very very slow.  If I go to landscape mode, it slows to an apparent freeze.
I got an eReader so that I could enlarge font sizes enough to see them easily, and with ePubs this is of course a breeze.  I was hoping that Koreader would allow me to solve the same problem with PDF's.  Is there a way to get the same crisp reflow function with larger font sizes?  It seems like the primary utility of reflow would be to enable an increase in the font size . . .

**Comment by chrox** [comment] 2015-10-12 13:39
Could you post the screenshot of your configuration? I would like to check the font size you choose for reflowing.

**Comment by gerroon** [comment] 2015-10-12 15:59
@sourdoughpablo 

Did you try with other pdfs? I use reflow alot with different font sizes, I do not associate a slow down with font size. There could be crashes sometimes (although not on Kobo devices) due to reflows but no real slowdowns for me.

**Comment by sourdoughpablo** [comment] 2015-10-12 21:19
I am using the KSM 8 install that is linked from and recommended on the KSM 7 Install page, since I am using Calibre to load books onto nickel.

I updated the firmware on my Kobo Aura H20 to version 3.18.  Then I reinstalled KSM 8 and KoReader.  This improved functionality a a lot with the reflow.

With single column pdf text I'm now getting good functionality in both portrait and landscape modes, using font size selections up to about the level of the third font size from the right Aa:

![img_4204](https://cloud.githubusercontent.com/assets/15082631/10438698/0d310a16-70ea-11e5-8f8d-87b3d10f914b.JPG)

About every third or fourth page turn is a "hiccup" that lags behind the rest.

But if I bump fonts up to the middle of the second level, or to the first level on the right, page writes start to slow down a lot.

![img_4206](https://cloud.githubusercontent.com/assets/15082631/10438827/d028ff10-70ea-11e5-8edd-744a6470b617.JPG)

With two column text I get more functionality than I did before in portrait mode, but if I switch to landscape mode, screen re-writes are markedly slower, even with font sizes at third size from the right end.  Column reflow doesn't seem to like landscape mode very much at all.

Both of these observations are made in multiple pdf documents.

**Comment by chrox** [comment] 2015-10-18 03:26
I'm sure the koreader cache system was running out of memory in your case when you selected the second largest font in landscape. Let's do a simple calculation. The Kobo H2O has a resolution of 1430×1080. In landscape mode it has a screen width of 1430 pixels. The reflowed page should have the same total pixels of a page with a width of 2*1430*1.8 that's 5148 pixels. Suppose your page has an aspect ratio of 1.414:1 (as for A4 paper), the page height would be around 7280 pixels. And the reflowing engine will use 5148 * 7280 = 37.5MB of memory to reflow just one page. But unfortunately the maximum total cache size is set 30MB that's to say there will be no cache for another page thus slow page turns.

One workaround is setting a larger cache size [in the defaults.lua](https://github.com/koreader/koreader/blob/master/defaults.lua#L32):
and changing
```
DGLOBAL_CACHE_SIZE_MAXIMUM = 1024*1024*30
```
to 
```
DGLOBAL_CACHE_SIZE_MAXIMUM = 1024*1024*80
```
.

**Comment by chrox** [comment] 2015-10-18 03:42
As a comparison, on Kobo H2O when using the default font size for reflowing the size of a reflowed page is around 6.5 MB in portrait and 11.4 MB in landscape. And on Kindle Paperwhite, the same reflowed page will be 3.2 MB in portrait and 5.8 MB in landscape.

**Comment by sourdoughpablo** [comment] 2015-10-19 05:10
Is there any downside to increasing the cache maximum to *80?

**Comment by houqp** [comment] 2015-10-19 06:39
Only down side i can think of is koreader might take up 50M extra memory at runtime.

**Comment by NiLuJe** [comment] 2015-10-19 11:46
The H2O (at least) ships with a crapload (i.e., 512MB, IIRC) on RAM, so that shouldn't be an issue there.

**Comment by chrox** [comment] 2015-10-19 15:26
We did have some calculation of the free RAM on a specific device at run time here https://github.com/koreader/koreader/blob/master/frontend/cache.lua#L30. It's a little too conservative though, probably it's time to enlarge the default values considering new devices have much more RAM than devices of several years ago.

**Comment by chrox** [comment] 2015-10-19 15:29
80 MB of cache should do no harm on Kobo H2O but it may crash a Kindle Paperwhite.

**Comment by sourdoughpablo** [comment] 2015-10-20 06:14
This effectively solved the problem in portrait mode, consistently quick screen rewrites at quite large font sizes.  

In landscape mode there is still a slight lag during the shift to a new actual page in the pdf.  The screen rewrite after the bottom of a pdf page (with the page numbers) is perceptibly slower than the previous few rewrites were.  This occurs in some PDF files, not in all of them, and the delay is not extreme.

Thanks a lot!

**Comment by gerroon** [comment] 2015-10-20 14:11
Can this also help with Android crash and performance issues?

**Comment by Frenzie** [comment] 2015-10-20 14:19
Crash? I doubt it. Performance — well, probably not performance in general, but I'd point out that my 2011 Xperia Ray is significantly faster than the outdated hardware on the H2O so I'm hardly sure how performance could be an issue in the first place. In fact I wish @NiLuJe wouldn't say things like "crapload of RAM" in case any manufacturers are looking. I want a *proper* tablet-like device with a non-emitting screen, and that means it should have regular 2014/2015 hardware with a perfectly normal but not at all excessive amount of RAM of at least 2 GB so it can deal with 600+ DPI documents no problem. (Yeah, yeah — in a decade, perhaps).

**Comment by chrox** [comment] 2015-10-21 01:44
@gerroon No, not a bit. The poor performance on some Android devices is caused by failure of JIT compiling, which means the computation extensive part like blitbuffering will be interpreted line by line for millions of time in order to just show a menu which in normal case is done in several millions of CPU instructions usually in less than 100 milliseconds. The performance degeneration is over 100x which is by no means like the OP's situation.

**Comment by chrox** [comment] 2015-10-21 14:58
@sourdoughpablo 

> In landscape mode there is still a slight lag during the shift to a new actual page in the pdf.  The screen rewrite after the bottom of a pdf page (with the page numbers) is perceptibly slower than the previous few rewrites were.  This occurs in some PDF files, not in all of them, and the delay is not extreme.

You probably also need to set the `DGLOBAL_CACHE_FREE_PROPORTION` with a reasonable higher value like 0.3 or 0.4 in order to increase the maximum cache size.

**Comment by sourdoughpablo** [comment] 2015-10-22 18:55
I did this, to 0.4, with no ill effects.

Things are quite crisp now with the page turns.

In landscape mode, one cause of the hesitation at the end of the document page seemed to be that the software does a final refresh of the screen to include the very bottom of the page.  When I put it in scrolling mode, this inconsequential re-write is eliminated.

**Closed** 2015-10-23 04:59 UTC
Labels: wontfix
