### ISSUE TITLE
Skipping Xochitl and going straight to KOReader on boot: Wi-Fi not working

### ISSUE THREAD

**Issue by gabyhk** [koreader/koreader#6688] opened 2020-09-20 15:42 UTC
* KOReader version: 2020.09
* Device: reMarkable (RM102)

#### Issue
Wi-Fi services are not loading properly unless the device loads Xochitl first and then KOReader.

#### Steps
If you never use xochitl and want to use KOReader immediately after powering on the device:
1. ssh into your device
2. `systemctl disable xochitl`
3. `systemctl enable koreader`

**Drawback:** You will lose Wi-Fi access `SSID:wlan0 IEEE 802.11 ESSID:off/any | No default gateway to ping`. I have compared the `systemctl status` from both scenarios: (1) loading xochitl and then KOReader versus (2) skipping xochitl and loading KOReader. The only difference is that the former loads `wpa_supplicant.service` while the latter does not. Additionally, manually running `systemctl start wpa_supplicant` and `systemctl daemon-reload` from the Terminal Emulator does **not** restore Wi-Fi for some reason.

#### Workaround
1. Make sure Xochitl is enabled on startup
2. Make sure KOReader is disabled on startup
3. Create a `koreader.timer` under `/etc/systemd/system` with the following content:
```
[Unit]
Description="Load KOReader 10 seconds after Xochitl"

[Timer]
OnStartupSec=10

[Install]
WantedBy=default.target
```
KOReader should load automatically right after Xochitl and Wi-Fi should work as well. This is by no means an elegant solution.

**Question:** Is there a way to make sure KOReader starts the wpa_supplicant independently?

**Comment by Galunid** [comment] 2020-09-20 16:06
I don't really have a device, but have you tried `systemctl status wpa_supplicant` and `dmesg`? Perhaps it'll point you in the right direction as to why it doesn't start properly.

**Comment by pazos** [comment] 2020-09-20 16:17
> Question: Is there a way to make sure KOReader starts the wpa_supplicant independently?

KOReader doesn't handle wifi **at all** on ReMarkable. #6681 is a fix for that but requires `oxide` launcher. My suggestion still stands: runtime check to see if oxide is installed, if not fallback to a standalone wpa_supplicant version, like https://github.com/koreader/koreader/issues/6677#issuecomment-695097661

**Comment by gabyhk** [comment] 2020-09-21 00:56
@pazos I guess when you mentioned that it was not implemented, I mistakenly assumed it was merely not added to the interface. Thank you for clarifying that. I will give `oxide` a try!

**Comment by pazos** [comment] 2020-09-21 19:20
Duplicate of #6677

**Closed by pazos** 2020-09-21 19:20 UTC
Labels: reMarkable
