### ISSUE TITLE
Failed Wallabag downloads

### ISSUE THREAD

**Issue by mredaelli** [koreader/koreader#7650] opened 2021-05-08 18:34 UTC
* KOReader version: 2021.04
* Device: Kobo Libra H2O

#### Issue

When downloading articles from Wallabag (selfhosted, v. 2.4.1), I often get failed ones.

#### Steps to reproduce

One example is attaching [this](https://acoup.blog/2020/06/19/collections-the-battle-of-helms-deep-part-viii-the-mind-of-saruman/) and fetching from Koreader

**Comment by Frenzie** [comment] 2021-05-08 19:17
Does it fail and/or how long does it take if you just download the EPUB?

**Comment by Frenzie** [comment] 2021-05-08 19:19
Concretely, if the response takes more than 30 seconds, it'll time out.

**Comment by mredaelli** [comment] 2021-05-08 20:58
Indeed, exporting the epub takes more than 30 seconds. Must be all those pictures.

Any way I can tweak that constant?

**Comment by Frenzie** [comment] 2021-05-08 21:02
You can edit that line.

**Comment by mredaelli** [comment] 2021-05-08 21:04
Thanks!

**Comment by NiLuJe** [comment] 2021-05-08 21:52
I wouldn't think so? That bit of code probably could simply use switching to a larger timeout and call it a day?

(Note that *very* few things actually honor TOTAL_TIMEOUT (IIRC, that's pretty much only Wikipedia)).

**Comment by mredaelli** [comment] 2021-05-08 22:31
For reference, there is an issue open on wallabag too: https://github.com/wallabag/wallabag/issues/4043

**Comment by Frenzie** [comment] 2021-05-09 06:13
> That bit of code probably could simply use switching to a larger timeout and call it a day?

But I don't want a larger timeout. ;-)

**Comment by matejdro** [comment] 2021-05-12 14:26
> But I don't want a larger timeout. ;-)

What would the solution be?

Also, since this is still an issue, can this be reopened?

**Comment by Frenzie** [comment] 2021-05-12 14:40
I proposed above to make them configurable. But actually there's a smarter default compromise. Use `FILE_XXX_TIMEOUT` when dealing with files, and keep using `LARGE_XXX_TIMEOUT` by default for the API requests.

**Comment by Frenzie** [comment] 2021-05-12 14:41
> Also, since this is still an issue, can this be reopened?

No need.

**Comment by matejdro** [comment] 2021-05-12 14:41
I can confirm that issue is resolved by manually editing the files. But it would be nice to have a solution that does not requires re-applying every update.

**Comment by Frenzie** [comment] 2021-05-12 14:45
Fine, I'll reopen it in order to close it a few hours from now, but be wary what you ask for since that removes the pressure.

**Closed** 2021-05-13 08:15 UTC
Labels: Plugin

**Comment by Tally** [comment] 2023-03-14 18:07
Kobo Libra 2 running 2023.01-103 connecting to Wallabag 2.5.4 running on a personal Raspberry Pi.
My first 5 article downloads to Kobo went flawlessly; attempting several times to download four new articles since then have failed in this fashion (i.e. producing un-openable hidden files named as above) every time. Downloading EPUB from the browser works as expected.
I see a commit was merged re. this but do not see if or what corrective action it recommends for the end user.

**Comment by Frenzie** [comment] 2023-03-14 18:55
None, it simply raised the timeout from 15 to 60 seconds.

**Comment by NiLuJe** [comment] 2023-03-14 22:01
Wasn't there an issue about Wallabag itself being extremely slow at generating an ePub in some cases that was tripping a timeout somewhere?

**Comment by Frenzie** [comment] 2023-03-14 22:50
That's this one, yes. (Btw, I meant 30 to 60, not 15 to 60.)

**Comment by Tally** [comment] 2023-03-14 23:23
> Wasn't there an issue about Wallabag itself being extremely slow at generating an ePub in some cases that was tripping a timeout somewhere?

Yes. I resolved the problem elsewhere (Having miniflux pass the URL to wallabag to generate articles from nytimes.com instead of using its own content resolved the issue.) but interestingly, renaming the hidden and unexpectedly large files downloaded to KOReader to have the EPUB extension made them readable, and, since generating and downloading EPUB's from the web wallabag client functioned as expected, it seems a little more complicated that I imagined.

**Comment by Tally** [comment] 2023-04-10 00:19
Recurrent issues. Strangely, downloading ePubs from Wallabag produces functional files.
Test URL's:
 * https://www.nytimes.com/2023/03/31/arts/music/tao-of-glass-skirball-review.html - KOReader download fails, produces 240 kb file with no extension and incorrect content and format when opened. No hypothesis.
 * https://www.theatlantic.com/magazine/archive/2023/05/holocaust-student-education-jewish-anti-semitism/673488/ - KOReader downloads an empty file. Hypothesis, it is too large; the web download is ~6 MB.

Attached files for comparison. Happy to place my Wallabag server at your disposal.
[KOReader Wallabag Failed Downloads.zip](https://github.com/koreader/koreader/files/11186649/KOReader.Wallabag.Failed.Downloads.zip)

**Comment by Frenzie** [comment] 2023-04-10 09:58
You haven't mentioned how long any of those actions take. A quick test suggests it takes about 6 seconds for me but if your server is very slow that's expected. You can increase the amount of time spent waiting for a server reply through a [user patch](https://github.com/koreader/koreader/wiki/User-patches).

```lua
$ cat 2-enormous-file-timout.lua 
local socketutil = require("socketutil")

-- set socketutil.FILE_BLOCK_TIMEOUT to an extremely large value that'll lock you out of the UI forever and ever
socketutil.FILE_BLOCK_TIMEOUT = 30
```

**Comment by matejdro** [comment] 2023-04-10 13:37
I just want to mention that I have kinda given up on wallabag at that point. While it works fine on many websites, list of edge cases, where it breaks is getting bigger and bigger (they are at [650+ issues](https://github.com/wallabag/wallabag/issues) by now, with nobody looking at them).

I've switched to an alternative system now: I have a folder on my server exposed via WebDAV. Then I use [Save as Ebook](https://github.com/alexadam/save-as-ebook) extension to use Browser's reader mode (which seems to work more reliably and it works automatically on all paywalls you have access with the browser) to generate epubs, which I place into that shared folder. Then I use Koreader's "Cloud Storage" function to access that folder via WebDAV and download the article.

It's a bit more involved process, but it has higher success rate for me.
