### ISSUE TITLE
Can't login to Evernote on Kobo using Kobo Clara HD

### ISSUE THREAD

**Issue by stanvv** [koreader/koreader#6342] opened 2020-07-02 14:33 UTC
* KOReader version: v2020.06
* Device: Kobo Clara HD

#### Issue
Exactly the same issue as #6281 : can't login to Evernote. When I try to login I got the following error message:
An error occurred while loggin in: plugins/evernote.koplugin/EvernoteOAuth.lua:351: OAuth verifier not found.
I do not use 2fa.

#### Steps to reproduce
Access Evernote menu -> Login to Evernote -> Insert user and password and click to login.

##### `crash.log` (if applicable)
Cannot find anything relevant, but here we go:
[crash.log](https://github.com/koreader/koreader/files/4864952/crash.log)

**Comment by wilsonrljr** [comment] 2020-07-02 16:36
Were you using two-factor authentication before trying to use the plugin? In my case (#6281), I was using 2fa before and I disabled it to use Evernote plugin. I have this problem when I tried to login in the same day, but after waiting a while I managed to login normally.

**Comment by pazos** [comment] 2020-07-02 17:34
Duplicate of #6281. (Please don't open duplicates. Closed issues are still watched)

**Closed by pazos** 2020-07-02 17:34 UTC
