### ISSUE TITLE
KR not starting from KA1 w FW 4.2.8283

### ISSUE THREAD

**Issue by trekk2810** [koreader/koreader#2502] opened 2017-01-18 14:29 UTC
* KOReader version: 2015.11-793-gf95ad00
* Device: Kobo Aura One

With the new FW 4.2.8283 Koreader can't be started from KSM after exiting nickel. If I reboot the device manually, I can start Koreader again.

Here's the excerpt from the crash.log.

```
01/18/17-11:20:53 ERROR cannot open translation file: l10n/en_US/koreader.po
./luajit: ./ffi/framebuffer_linux.lua:60: unknown bpp value for the eink driver
stack traceback:
	[C]: in function 'error'
	./ffi/framebuffer_linux.lua:60: in function 'init'
	./ffi/framebuffer_mxcfb.lua:290: in function 'init'
	./ffi/framebuffer.lua:59: in function 'new'
	frontend/device/kobo/device.lua:127: in function 'init'
	frontend/device.lua:39: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:1: in main chunk
	[C]: in function 'require'
	./reader.lua:93: in main chunk
	[C]: at 0x00013e85
```

There is already a discussion on mobileread, [here](https://www.mobileread.com/forums/showpost.php?p=3460113&postcount=379.)

Possible reason: In the new FW have been kernel changes for 32bpp support

**Comment by houqp** [comment] 2017-01-18 15:14
It's very strange that they only update the bpp value after nickel is launched :( Do you notice any quality improvement from nickel after update?

**Comment by trekk2810** [comment] 2017-01-18 15:23
No, I can absolutely see no improvement. The refresh seems to look more grainy, but maybe it's just my eyes. :)

**Comment by AlanSP1** [comment] 2017-01-19 00:46
It seems that patch posted here solved problem: https://www.mobileread.com/forums/showpost.php?p=3460449&postcount=387

I'm not owning KA1 (I own H2O) and also I'm not very much into new Kobo firmwares as I only use KSM+koreader, so I can't confirm it myself.

**Comment by trekk2810** [comment] 2017-01-19 17:25
@AlanSP1 : The patch did not solve the problem on my KA1. After exiting Koreader I still get the "KOReader exited irregularly" message from tsherings _emergency poweroff for Koreader_ script.

**Comment by trekk2810** [comment] 2017-01-19 20:41
tshering provided an updated script, which seems to work. No more problems on my KA1.

**Comment by houqp** [comment] 2017-01-20 11:02
Did he mention what's the change? I am curious in the root cause ;)

**Comment by trekk2810** [comment] 2017-01-20 17:30
You can see his modifications [here](https://www.mobileread.com/forums/showpost.php?p=3458767&postcount=366)

**Comment by baskerville** [comment] 2017-02-03 15:59
Here's an excerpt from the related [MR thread](https://www.mobileread.com/forums/showthread.php?t=282758):

> 4.2.8283 and beyond will be switching the framebuffer to 32 bit depth. Modifications/code that assume 16 bit will be broken. Kernels will be patched for each generation of device that the update goes out to.

**Comment by baskerville** [comment] 2017-02-03 17:53
This naive patch:
```diff
diff --git a/ffi/framebuffer_linux.lua b/ffi/framebuffer_linux.lua
index b841d45..77fe5a9 100644
--- a/ffi/framebuffer_linux.lua
+++ b/ffi/framebuffer_linux.lua
@@ -50,7 +50,9 @@ function framebuffer:init()
 
     self.data = ffi.C.mmap(nil, self.fb_size, bit.bor(ffi.C.PROT_READ, ffi.C.PROT_WRITE), ffi.C.MAP_SHARED, self.fd, 0)
     assert(self.data ~= ffi.C.MAP_FAILED, "can not mmap() framebuffer")
-    if vinfo.bits_per_pixel == 16 then
+    if vinfo.bits_per_pixel == 32 then
+        self.bb = BB.new(vinfo.xres, vinfo.yres, BB.TYPE_BBRGB32, self.data, finfo.line_length)
+    elseif vinfo.bits_per_pixel == 16 then
         self.bb = BB.new(vinfo.xres, vinfo.yres, BB.TYPE_BBRGB16, self.data, finfo.line_length)
     elseif vinfo.bits_per_pixel == 8 then
         self.bb = BB.new(vinfo.xres, vinfo.yres, BB.TYPE_BB8, self.data, finfo.line_length)
```
leads to a segmentation fault.

**Comment by Frenzie** [comment] 2017-02-03 19:37
Odd, BB.TYPE_BBRGB32 works in the SDL emulator.

**Comment by baskerville** [comment] 2017-02-05 10:32
I've enabled verbose debug messages but the resulting`ev.log` is empty.

`crash.log` contains this:
```
02/05/17-11:19:00 ERROR cannot open translation file: l10n/en_US/koreader.po
Segmentation fault
```

**Comment by Frenzie** [comment] 2017-02-05 10:35
Juxtaposed like that it looks pretty funny. Surely there's no relation between the two error messages though? :-)

**Comment by baskerville** [comment] 2017-02-05 10:45
No, there isn't, the first line appears at the beginning of every crash report…

**Comment by baskerville** [comment] 2017-02-05 11:26
By using `logger.info`, I was able to find where the segfault happens: line 68 in `base/ffi/framebuffer_linux.lua`:
```
    self.bb:fill(BB.COLOR_WHITE)
```

**Comment by Frenzie** [comment] 2017-02-05 12:08
Have you tried using something like `ColorRGB32(0xFF, 0xFF, 0xFF, 0xFF)` (or should that be `ColorRGB32(0xFF, 0xFF, 0xFF, 1)`)?

https://github.com/koreader/koreader-base/blob/3e9b63f5cafc12335e18ea8ed313aa01c004b745/ffi/blitbuffer.lua#L1316-L1319

**Comment by baskerville** [comment] 2017-02-05 13:49
I will try your suggestion, but first I'd like to refine the location: the first call to `setPixel` in `base/ffi/blitbuffer.lua`, on line 810 crashes. And more precisely, the segmentation fault occurs on line 150, when resolving `self.r` (`c.r` is ok):
```
function ColorRGB32_mt.__index:set(color)
    local c = color:getColorRGB32()
    self.r = c.r
    self.g = c.g
    self.b = c.b
    self.alpha = c.alpha
end
```

**Comment by baskerville** [comment] 2017-02-05 13:55
The suggestion doesn't have any effect.

**Comment by houqp** [comment] 2017-02-05 14:42
What did you get as the values for `self.fb_sizer`, `vinfo.xres`, vinfo.yres` and `finfo.line_length` in framebuffer_linux.lua? Looks like out of bound memory access to me.

The SDL driver uses it like the following (in framebuffer_SDL2_0.lua):

```lua
local bb = BB.new(SDL.w, SDL.h, BB.TYPE_BBRGB32)
```

If you only pass in the first 3 arguments, blitbuffer will automatically allocate the memory for you so you will get the correct memory size.

For framebuffer_linux.lua, we need to pass extra arguments because we need to write directly to framebuffer memory space, which will be picked up by the eink driver on refresh.

**Comment by baskerville** [comment] 2017-02-05 15:43
```
self.fb_size 21626880, vinfo.xres 1404, finfo.line_length 5632
```

**Comment by baskerville** [comment] 2017-02-06 09:54
I've added two lines in `framebuffer_linux.lua`:
```lua
self.data = ffi.C.mmap(nil, self.fb_size, bit.bor(ffi.C.PROT_READ, ffi.C.PROT_WRITE),
                       ffi.C.MAP_SHARED, self.fd, 0)
assert(self.data ~= ffi.C.MAP_FAILED, "can not mmap() framebuffer")
logger.info("fb linux: sizeof(self.data)", ffi.sizeof(self.data))
logger.info("fb linux: self.data", ffi.string(self.data, ffi.sizeof(self.data)))
```
And the output for those lines is:
```
02/06/17-10:33:44 INFO  fb linux: sizeof(self.data) 4
Segmentation fault
```

**Comment by houqp** [comment] 2017-02-06 15:21
Depends on the actual value in `self.data`, if there is no `\x00`, `ffi.string(self.data, ffi.sizeof(self.data))` might lead to segfault. You can test reading and writing of the memory with:

```lua
local p = ffi.cast("char*", self.data)
p[0] = 0xff
print(p[3])

print(self.bb:getPixel(0, 0).r)
print(self.bb:getPixel(1407, vinfo.yres-1).r)
```

Here is how the math works:

`finfo.line_length` specifies the actual size of each row in the blitbuffer in unit of bytes. The actual framebuffer memory region size should be `vinfo.yres * finfo.line_length`. based on the info you collected, `5632/4` = `1408`, which is not `1404`. As a dirty check, what happens if you pass in `1408` as the first argument to `BB.new()`?

Also, what's the value of `vinfo.yres`, `ffi.string(finfo.id, 11)`, ` ffi.string(finfo.id, 7)` and `string.byte(ffi.string(finfo.id, 16), 1, 1)`?

**Comment by baskerville** [comment] 2017-02-06 16:37
> Depends on the actual value in `self.data`, if there is no `\x00`,
> `ffi.string(self.data, ffi.sizeof(self.data))` might lead to segfault. You
> can test reading and writing of the memory with:

`self.data` is a pointer, right? So why can't its value be read?

And since I'm specifying the size, there's no terminating char to search for…

> As a dirty check, what happens if you pass in `1408` as the first argument to `BB.new()`?

Nothing.

> Also, what's the value of `vinfo.yres`, `ffi.string(finfo.id, 11)`, `
> ffi.string(finfo.id, 7)` and `string.byte(ffi.string(finfo.id, 16), 1, 1)`? 

```
                                 vinfo.yres    1872
                   ffi.string(finfo.id, 11)    mxc_epdc_fb
string.byte(ffi.string(finfo.id, 16), 1, 1)    109
```

I've said it before but maybe I should repeat myself: the segfault happens on the **first** call to `setPixel`, i.e. when `x = 0` and `y = 0`…

So, for example, this expression: `self.bb:getPixel(0, 0).r` generates a segfault.

**Comment by houqp** [comment] 2017-02-07 15:59
> self.data is a pointer, right? So why can't its value be read?

Yes, this is indeed the weird part. You can do `print(self.data)` to obtain the memory address to see if it's in the expected range. Although if mmap didn't fail, we really should be getting a valid memory address.

Have you tried the following code?

```lua
local p = ffi.cast("char*", self.data)
print(p[3])
p[0] = 0xff
```

To rule out the possibility of bug in LuaJIT, we can write a dummy test program in C that does just the mmap call with framebuffer file (/dev/fb0) and see if reading from the memory address causes the same segfault.

> I've said it before but maybe I should repeat myself: the segfault happens on the first call to setPixel, i.e. when x = 0 and y = 0…

Sorry, I missed this part in your previous comment.

Another possible cause of segfault is the `self.fb_size` we used for mmap is larger than the actual framebuffer size. To test this, try replace `vinfo.xres_virtual` with `vinfo.xres` around line 41:

```lua
self.fb_size = vinfo.xres_virtual * vinfo.yres_virtual
```

**Comment by hwhw** [comment] 2017-02-17 08:34
Hi everyone! Since I'm done with my exams (have a law degree now), having successfully found a job (IT project management in university library) and almost being done with rectifying my flat and other living circumstances, I think I ought to get back on track with this project again :-) And this bug sounds like a job for me! (Sorry, this adds nothing substantial to the discussion, just wanted to let you know that I'm slowling getting on pace again.)

**Comment by Frenzie** [comment] 2017-02-17 08:39
Congratulations!

**Comment by houqp** [comment] 2017-02-18 08:36
OMG, this is possibly one of the biggest news in KOReader community. Welcome back @hwhw !!! For some reason I thought you already got your law degree awhile ago ;) 

Well, I was planning to take a look at it this weekend since I left my Aura HD at my home town 12000KM away and finally has an excuse to play with my Aura One. But since you are at it, I will switch back to the suspend issue and possibly some more reverse engineering on the frontlight.

**Comment by powyginanachochla** [comment] 2017-03-27 18:28
I just decided to give it a try and see if I can trace the bug further. I applied the "naive patch" posted by @baskerville – and surprisingly koreader is working for me.
Tested with nightly build v2015.11-911-g00cf81f against kobo 4.3.8945 firmware.

**Comment by baskerville** [comment] 2017-03-28 21:04
That's interesting, and I haven't tried it yet but I've noticed that the section of the output of `fbset` that gives the offset and length of each color component has changed:
```
rgba 8/16,8/8,8/0,8/24
```
And I can clearly remember that it returned:
```
rgba 5/11,6/5,5/0,0/0
```
When this issue was created (and yet the bit depth was already 32…).

**Comment by baskerville** [comment] 2017-03-29 09:34
I tried *v2015.11-930-g0318a04* on my *Glo HD* with firmware *4.3.8966* and got a segfault.

**Comment by baskerville** [comment] 2017-04-05 12:29
I've run *fbgrab* while *nickel* was displaying the following image on my *Aura ONE*:

![kobo-aura_one-grid](https://cloud.githubusercontent.com/assets/159419/24705280/75e39404-1a0b-11e7-92b1-00c0458fa0fb.png)

Here's the *fbgrab* invocation and output:
```
# ./fbgrab fb.png
Skipping 0 bytes
Resolution: 1404x1872 @ depth 32
Converting image from 32bpp
Now writing PNG file (compression -1)
```

And the resulting image:

![fb](https://cloud.githubusercontent.com/assets/159419/24705314/a25aeea6-1a0b-11e7-8b4c-e0694625dee0.png)

**Comment by NiLuJe** [comment] 2017-04-06 04:12
@baskerville : See [this customized FBGrab build](https://www.mobileread.com/forums/showpost.php?p=2854326&postcount=20) for a proper output on Kobo/Kindles.

**Comment by baskerville** [comment] 2017-04-06 08:52
@NiLuJe Thanks but I'm using the *fbgrab* build from your *KoboStuff* archive.
 
Furthermore, it works fine in 16-bit mode within *KOReader*:

```
Skipping 0 bytes
Resolution: 1408x1872 -> 1404x1872 (cropping: 4 rightmost pixels) @ depth 16
Converting image from 16bpp
Now writing PNG file (compression -1)
```

**Comment by NiLuJe** [comment] 2017-04-06 15:12
I updated that post I linked to handle FW 4.x, but not KoboStuff yet ;).

On Apr 6, 2017 10:52 AM, "Bastien Dejean" <notifications@github.com> wrote:

@NiLuJe <https://github.com/NiLuJe> Thanks but I'm using the *fbgrab* build
from your *KoboStuff* archive.

Furthermore, it works fine in 16-bit mode within *KOReader*:

Skipping 0 bytes
Resolution: 1408x1872 -> 1404x1872 (cropping: 4 rightmost pixels) @ depth 16
Converting image from 16bpp
Now writing PNG file (compression -1)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/koreader/koreader/issues/2502#issuecomment-292110326>,
or mute the thread

**Comment by baskerville** [comment] 2017-04-06 15:51
Indeed. False alarm.

**Comment by taosxx** [comment] 2017-04-13 19:53
Since an update to firmware 4.3.9084 (probably unrelated) on my Kobo Glo HD, I see again the following error when I start koreader (v2015.11-976-ge8c0127) from KSM 8 after exiting nickel: 
04/13/17-21:33:55 ERROR cannot open translation file: l10n/en_US/koreader.po
./luajit: ./ffi/framebuffer_linux.lua:60: unknown bpp value for the eink driver
stack traceback:
	[C]: in function 'error'
	./ffi/framebuffer_linux.lua:60: in function 'init'
	./ffi/framebuffer_mxcfb.lua:290: in function 'init'
	./ffi/framebuffer.lua:59: in function 'new'
	frontend/device/kobo/device.lua:127: in function 'init'
	frontend/device.lua:39: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:5: in main chunk
	[C]: in function 'require'
	./reader.lua:93: in main chunk
	[C]: at 0x00013e85

Going back to koreader v2015.11-963-g3a75b6d resolves the issue. It seems to be a recent regression.

**Comment by Frenzie** [comment] 2017-04-13 20:08
Have you installed [the KSM 8 patch for newer firmwares](https://www.mobileread.com/forums/showpost.php?p=3389190&postcount=221)?

**Comment by taosxx** [comment] 2017-04-13 20:56
Yes. Revision 4e (KSM08_ext_aura_one_04e).

**Comment by taosxx** [comment] 2017-04-13 22:00
Among the nightlies from http://build.koreader.rocks/download/nightly/:
v2015.11-963-g3a75b6d is the last (and probably only) one that works for me (with patch from pazos merged:  see #2731 - btw I don't see any strange rotations neither in koreader nor in KSM with my GloHD).
v2015.11-971-gf1c0b4b, the next one, does no longer work for me.

**Comment by Frenzie** [comment] 2017-04-14 16:29
> v2015.11-963-g3a75b6d is the last (and probably only) one that works for me

That would make sense if your bit depth is set to 32, but the patch is specifically geared toward non-KSM devices.

Are you absolutely sure that you processed the update? It doesn't suffice to just put it in the `.kobo` directory, but you have to use **Handle update** → **Install full update** within KSM.

**Comment by taosxx** [comment] 2017-04-14 18:38
Yes, I'm sure I processed the update. I always sideload the KoboRoot.tgz from kobo and install the full update (incl. the upgrade folder) when going to a newer firmware revision. That means no KSM after the restart (believe me, I would notice if it would still start - KSM is set to start always). Then I install KSM + KSM update (in this case 4e - and I actually overwrite the old KSM files) + nightmode (to be precise only root/screenInv.so is added) - this time I also updated Koreader by copying the koreader folder from the latest nightly tgz to onboard/.adds/koreader (usually, I only do this after the first reboot). After rebooting, I was in KSM again (changed the setting to boot into KSM everytime), tried to start koreader which obviously worked since bit depth had not yet changed to 32, started nickel and made sure that nightmode via fmon still worked, exited nickel via fmon, was back in KSM and tried to start koreader again which didn't work because bit depth was 32 due to running nickel before. Rebooting let me start koreader (again bit depth was probably 16), I exited koreader, started nickel, connected the device to my computer, renamed koreader to _koreader and did a fresh install of the same koreader version, exited nickel, and had the same problem starting koreader. Then I went back to the first koreader version (963) that used to work with firmware 4.3.8066(?) after exiting nickel and checked if it also stll worked with the new 4.3.9084 which it does.

**Comment by Frenzie** [comment] 2017-04-14 19:18
I'll have to run some more tests with this rotation issue. In the meantime I've also asked about it on MR.

**Comment by houqp** [comment] 2017-04-16 06:13
@taosxx can you try running 971 with 963's koreader.sh file? There was a format refactor for koreader.sh between 953 and 971: e5bcdee85e78424b844386d2fcf4d719ee8762c9.

**Comment by taosxx** [comment] 2017-04-16 08:42
971 works with koreader.sh from 963.

**Comment by Frenzie** [comment] 2017-04-16 09:07
@houqp Nothing else in the script relates to the bit depth, as confirmed by the fact that 963 is the only version that works (and not earlier and later). :-)

Anyway, I'll do some extra testing because it's possible that I may have accidentally been using the 4d update myself. I saw a forum post about someone doing that because of a previously outdated link in the KSM OP or some such.

**Comment by baskerville** [comment] 2017-04-16 13:13
Here's the fixed and variable screen info for the [i]Aura ONE[/i]:
```
FixScreeninfo { id: [109, 120, 99, 95, 101, 112, 100, 99, 95, 102, 98, 0, 0, 0, 0, 0], smem_start: 2281701376, smem_len: 10813440, fb_type: 0, type_aux: 0, visual: 2, xpanstep: 1, ypanstep: 1, ywrapstep: 0, line_length: 5632, mmio_start: 0, mmio_len: 0, accel: 0, capabilities: 0, reserved: [0, 0] }
VarScreeninfo { xres: 1404, yres: 1872, xres_virtual: 1408, yres_virtual: 3840, xoffset: 0, yoffset: 0, bits_per_pixel: 32, grayscale: 0, red: Bitfield { offset: 16, length: 8, msb_right: 0 }, green: Bitfield { offset: 8, length: 8, msb_right: 0 }, blue: Bitfield { offset: 0, length: 8, msb_right: 0 }, transp: Bitfield { offset: 24, length: 8, msb_right: 0 }, nonstd: 0, activate: 128, height: 157, width: 118, accel_flags: 0, pixclock: 7496, left_margin: 44, right_margin: 89, upper_margin: 4, lower_margin: 5, hsync_len: 44, vsync_len: 1, sync: 0, vmode: 0, rotate: 3, colorspace: 0, reserved: [0, 0, 0, 0] }
```

And this might be helpful:
```
# grep /dev/fb0 /proc/$(pidof nickel)/maps
2e936000-2f386000 rw-s 88000000 00:0b 632        /dev/fb0
```

**Comment by baskerville** [comment] 2017-04-19 09:50
@Frenzie Shouldn't `"${ksmroot+x:?}"` just be `"$ksmroot"`?

**Comment by Frenzie** [comment] 2017-04-19 10:25
If the check were wrong then removing it wouldn't be what causes issues. ;-) But you're right that it can probably be simplified to ${ksmroot:?} and then there'd be no need for the shellcheck disable flag.

**Comment by baskerville** [comment] 2017-04-19 10:31
So `+x` has something to do with `shellcheck`?

**Comment by Frenzie** [comment] 2017-04-19 10:52
Perhaps. :? Ensures failure when not set, +x ensures no empty string. Long
story short it avoids false positives in edge cases.

**Comment by baskerville** [comment] 2017-04-19 11:44
> :? Ensures failure when not set,

I known but why would you require `ksmroot` to be set?

> +x ensures no empty string.

I'm not sure I'm following you here:
```sh
$ abc=123
$ echo "${abc+x:?}"
x:?
```

> it avoids false positives in edge cases.

That's interesting: could you provide an edge case for `[ -z "$ksmroot" ]`?

**Comment by Frenzie** [comment] 2017-04-19 13:31
I don't think there should be an edge case here because of the nature of -n and -z, but it evaluates the same so it doesn't change the outcome of the test.

```bash
# $ksmroot is unset
$ if [ -z "$ksmroot" ]; then echo "bla"; fi
bla
$ if [ -z "${ksmroot+x:?}" ]; then echo "bla"; fi
bla
$ if [ -z "${ksmroot+x}" ]; then echo "bla"; fi
bla
# the +x avoids killing the script in this case
$ if [ -z "${ksmroot:?}" ]; then echo "bla"; fi
bash: ksmroot: parameter null or not set
# now set it
$ ksmroot="something"
$ if [ -z "$ksmroot" ]; then echo "bla"; else echo "set"; fi
set
$ if [ -z "${ksmroot+x:?}" ]; then echo "bla"; else echo "set"; fi
set
$ if [ -z "${ksmroot+x}" ]; then echo "bla"; else echo "set"; fi
set
$ if [ -z "${ksmroot:?}" ]; then echo "bla"; else echo "set"; fi
set
```

But with edge cases I'm talking more about different things, like:

```bash
$ echo "$bla"

# not set? we want failure
$ echo "${bla:?}"
bash: bla: parameter null or not set
```

So yes, I must've added that because of ShellCheck. The bigger mystery is why I [disabled the check](https://github.com/koreader/koreader/blob/a1ec64b3ed44dd58e0cd6f6676e1ce75f40d146e/platform/kobo/koreader.sh#L121) yet still wrote that. :-P Because `${var+x:?}` and `# shellcheck disable=2154` are effectively synonyms here.

More to the point, the test should probably simply rely on `[ "${FB_BPP}" -gt 16 ]` instead of the over-engineered `ksmroot` check. It's just a convoluted way of assuming that `[ $FB_BPP = 16 ]`.

**Comment by baskerville** [comment] 2017-04-19 19:47
I've been working on [*Sketch*](https://github.com/baskerville/sketch) lately and I tried one last thing to solve the 32-bit issue.

It turns out that the solution to this problem is given by [my last outputs](https://github.com/koreader/koreader/issues/2502#issuecomment-294351163): use `fix_info.smem_len` as the `len` argument to `mmap`!

**Comment by Frenzie** [comment] 2017-04-23 10:55
@baskerville Slightly off topic, but you might be interested in this blog post about `-z` that showed up in my FreshRSS this morning:

> There is a subreddit /r/nononoyes for videos of things that look like they’ll go horribly wrong, but amazingly turn out ok.
> 
> `[ -z $var ]` would belong there.

http://www.vidarholen.net/contents/blog/?p=576

**Comment by houqp** [comment] 2017-04-24 07:55
Thanks to @baskerville , this issue is resolved now :)

**Closed by houqp** 2017-04-24 07:55 UTC
Labels: bug, Kobo

**Comment by taosxx** [comment] 2017-04-26 20:27
No problems with 1012 on the Glo HD. Thanks!
