### ISSUE TITLE
Tap to wake up from sleep shouldn't move page

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#5253] opened 2019-08-24 08:48 UTC
* KOReader version: all
* Device: Pocketbook

When waking up the device, the screensaver is shown. I have the blank screen activated as screensaver because it works best with Pocketbook. However, when I tap to get back to the text again, this is interpreted as page forward (or backward depending on the zone). I have to tap again to get to the page where I was before.
The first tap after waking up the device should therefore not move the page, but just deactivate the screensaver.

**Comment by Frenzie** [comment] 2019-08-24 09:16
Duplicate of #5140 and/or #4201. The issue is basically that there's no such thing as having to tap to do anything after waking up, but on PB you have to as a workaround.

**Closed by Frenzie** 2019-08-24 09:16 UTC
Labels: PocketBook, bug, duplicate, firmware
