### ISSUE TITLE
Android crashes after 1051

### ISSUE THREAD

**Issue by chenxingqun** [koreader/koreader#3238] opened 2017-09-19 12:57 UTC
* KOReader version: after 1051
* Device: Onyx Max Carta, firmware 1.8.2, android 4.04

#### Issue
The last working apk for me is koreader-android-arm-linux-androideabi-v2015.11-1051-gfef18ec.apk.
Koreader newer than 1051 hangs when launching. Then I have to manually close it.
I've try these versions with the same result.
koreader-android-arm-linux-androideabi-v2015.11-1054-g6870bc2
koreader-android-arm-linux-androideabi-v2015.11-1152-gabaa699
koreader-android-arm-linux-androideabi-v2015.11-1163-gefac272
koreader-android-arm-linux-androideabi-v2015.11-1200-g9dee6c0
koreader-android-arm-linux-androideabi-v2015.11-1211-g161cae6
koreader-android-arm-linux-androideabi-v2015.11-1227-gae66a36
koreader-android-arm-linux-androideabi-v2015.11-1229-g019513f

#### Steps to reproduce
upgrade from 1051, open it, and wait.

**Comment by Frenzie** [comment] 2017-09-19 13:16
Thank you for the report! We're aware that there are some issues on some devices, but we haven't been able to get at the bottom of it.

Closing as a duplicate of #3214. It might help if you could post a log with the build from this comment: https://github.com/koreader/koreader/issues/3214#issuecomment-330202103

**Closed** 2017-09-19 13:16 UTC
