### ISSUE TITLE
Auto front-light off option

### ISSUE THREAD

**Issue by akamaus** [koreader/koreader#1814] opened 2016-02-13 17:31 UTC
I experienced rapid battery discharges on my Kobo Aura HD for several times. After some experiments I found an antidote. You should press that white button to disable the front-light before closing the book case. Looks like the magnetic latch is unreliable and device sometimes powers on while the case is closed. If light is on awakening almost certainly would be fatal and you would discover a discharged brick next time you decided to read something.

I propose to implement an option to disable light after a short period of inactivity (a minute or so). It would be unnoticeable during normal reading and would save the battery in case of spurious wakeups.

**Comment by AlanSP1** [comment] 2016-02-15 12:55
I don't think this is correct.

I tested it and having light on (I tested exclusively with light on) doesn't affect battery discharge. Also, having light on would be seen and I didn't saw any light on. Also, testing with light on gives you good Idea how much having light on affects battery. Well, it doesn't affect it as much as battery is drained.

You can take a look at this thread for more info: http://www.mobileread.com/forums/showthread.php?t=270306

**Comment by akamaus** [comment] 2016-02-18 05:31
@AlanSP1 Well, I looks like a different issue is discussed in the thread you gave link to.

All I have are the following observations:
1. If I close the case with light turned on and put it to bag I have high probability to get a discharged device next day.
2. After I got a habit of turning light off I have no more such surprises.
3. I observed light turns on if you slide top-cover a bit (that's what I called spurious wake-up), for me it explains points 1 and 2.

**Comment by AlanSP1** [comment] 2016-02-18 11:16
I think that all this issues with higher than normal battery drainage are a bit related.

You can find instructions how to disable magnetic sleep cover here: http://www.mobileread.com/forums/showpost.php?p=3205282&postcount=2480

If you implement this change, your sleep cover wouldn't have effect on device. But you would need to implement it each time you update koreader.

I shut off device when I not read for a longer time: http://www.mobileread.com/forums/showpost.php?p=3209463&postcount=2491

And in previously mentioned thread you can see that for me (but not for all) using CR suspend script worked pretty good. And I always used light on for testing purposes.

**Comment by Hzj-jie** [comment] 2016-03-04 06:04
If I understand it correctly, your cover cannot make your device in suspend mode correctly. I have no cover myself, but the cover may act exactly as power button (Are you sure the keycode is "Power_SleepCover"?)
In that case, you may prefer to have a 'suspend the device after idle for ?? minutes' function in koreader, instead of  'turn off front light after idle for ?? minutes' function.

What do you think?

**Comment by AlanSP1** [comment] 2016-03-04 12:49
I'm not sure if cover has any connection with strange battery drain. When I tested with CoolReader's suspend script, I used only cover for suspending device on/off and there wasn't battery drain, as battery lasted 50 days before I needed to recharge. At that time I also used light on all the time to speed normal battery drain up.

But, I'd still like to have option to disable sleep cover. I just prefer to solely use power button, in a way it makes me sure if in bag sleep cover wouldn't cause any problems, as it can be opened, or something.

Also, option to have automatically suspended device after x minutes sounds good, just in case if we leave device unattended for some time.

Turning off light after x minutes isn't something that appeals me, but for someone it can be useful.

**Comment by Hzj-jie** [comment] 2016-03-04 14:27
'Turning off light after x minutes' should be covered by 'Suspending device after x minutes', we always shutdown front light for Kobo when suspending in a koreader way. i.e. Send 'Suspend' signal to UIManager (https://github.com/koreader/koreader/blob/58e7103c34ffa3b5c47df97d77c68d4d169c56d7/frontend/ui/uimanager.lua#L44)

**Comment by AlanSP1** [comment] 2016-03-04 16:27
Yes, light on my H2O is also very economical, I don't see it impacts battery in bad way.

**Comment by houqp** [comment] 2016-03-05 20:50
I just set my HD's frontlight level to 20 and left it open right now. Let's see if how my battery goes tonight ;)

**Comment by houqp** [comment] 2016-03-06 07:09
So leaving the device on 12 hours with frontlight level set to 20 consumes less than 20% battery for me. I suspect something else is killing the battery. @akamaus, were you able to reliably reproduce the issue with frontlight on?

**Comment by AlanSP1** [comment] 2016-03-06 13:17
I think that for some reason processor goes in overdrive, because it looks like when suspending doesn't work, it drains battery like reader worked overtime, but there wasn't any light emitting from device, so it isn't related with light.

Turning light off for @akamaus maybe affects something else, not just light. I mean, some code, something like that.

**Comment by houqp** [comment] 2016-03-06 23:25
I wonder whether it's because the cover keeps sliding around in the bag, which causes KOReader constantly suspending and resuming during the day and drained the battery...

**Comment by Hzj-jie** [comment] 2016-03-09 00:23
@akamaus Are you still working on the 'Suspend device after X minute' feature? If not, I may help.

**Comment by akamaus** [comment] 2016-03-09 06:28
hello @houqp
I tried to reproduce the issue (it had been long time since I made a habit of turning light off manually).
I turned light on to 50%, waited for some time, then checked the battery.
Here is the data:
21:50 - 66% battery
00:00 - 62%
10:00 - 49%
11:50 - 47%

So looks like there is stable 1% drain per hour. So I have to agree with @AlanSP1, probably I observed some other issue in the past.

But I observed another strange thing. battery indicator wasn't updated until I reboot the device. I tried scrolling pages, restarting koreader, I even launched checkbattery.sh script from start_menu. The number remained constant. So I had to reboot the device each time to get the number. That's, I guess, explains why I saw 4% drain in first two hours - probably actual battery level was less than 66% then I started the experiment.

**Comment by houqp** [comment] 2016-03-09 07:50
@akamaus if you need to reboot the device to get a new battery value each time, then there is probably something wrong with the kernel, i.e. the stock firmware. In the worst case, restarting KOReader should get the uptodate value. In your cause, it looks like KOReader just keeps reading the same value from the kernel (so is checkbattery.sh).

Also do you use the autoRefreshTime feature at all? It's really strange that the issue went away after you turn the light off while we all know even leaving the light on all the time will not consume much battery.

**Comment by Hzj-jie** [comment] 2016-03-18 23:42
A prototype of auto-suspend function for kobo is @ https://github.com/hzj-jie/koreader, I am testing it on my Kobo Aura HD.

**Comment by Frenzie** [comment] 2016-03-19 08:42
Nice! I'd been thinking of writing something similar for fun, but
unfortunately it's of no practical interest to me so I never did. =)

**Comment by Frenzie** [comment] 2016-03-19 09:31
I just realized that no one mentioned #1356 yet, so hereby.

**Comment by Hzj-jie** [comment] 2016-03-21 18:31
It looks like a very heavy feature requirement. :)
I believe my patch is ready to review, go on pulling request.

**Comment by houqp** [comment] 2016-03-29 01:16
fixed by #1917

**Closed by houqp** 2016-03-29 01:16 UTC
