### ISSUE TITLE
Kobo Clara 2E randomly reboot itself .

### ISSUE THREAD

**Issue by Thamone** [koreader/koreader#9944] opened 2022-12-24 03:53 UTC
* KOReader version: v2022.11.53-g788ccac5_2022-12-21
* Device: Kobo Clara 2E

#### Issue
 Device randomly reboot while reading.
#### Steps to reproduce
 Just reading with Koreader. 
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

```
<Paste crash.log content here>
[crash.log](https://github.com/koreader/koreader/files/10297936/crash.log)

```
</details>
First it is just freeze like this post (https://github.com/koreader/koreader/issues/9806) but with latest update, it's change to freeze and then reboot.

**Comment by NiLuJe** [comment] 2022-12-24 15:15
The Libra 2/Clara 2E/Nia boards are unreliable, nothing much we can do about it. The reboot is the watchdog actually doing its job, which is kind of a good news ;).

(Duplicate of #8414, #9806).

**Closed by NiLuJe** 2022-12-24 15:15 UTC
