### ISSUE TITLE
PDF reader inverts colors in images and makes text unreadable

### ISSUE THREAD

**Issue by brndd** [koreader/koreader#9673] opened 2022-10-23 14:34 UTC
* KOReader version: 2022.10
* Device: Kobo Aura H2O

### Issue

When reading a PDF with lots of graphics embedded in and around text, pages with graphics on them appear with the colours inverted and the text unreadable. The same PDF renders fine with the (awful and slow) stock Kobo PDF reader.

### Steps to reproduce

1. Open [this PDF](https://github.com/koreader/koreader/files/9846778/sample.pdf) (two pages extracted from the full PDF to create a minimum reproducer) with KOReader.
2. The second page will have unreadable text and inverted colour pictures.

<details>
  <summary><h3>Photos</h3></summary>

#### KOReader

![0znVqJl](https://user-images.githubusercontent.com/5822375/197397814-35cb1334-c593-4c1c-aec6-eb429b4e3375.jpg)

#### Stock Kobo reader

![g701atV](https://user-images.githubusercontent.com/5822375/197397836-459bebaa-81ac-4d79-8792-ff0ed021df13.jpg)
</details>

**Comment by Frenzie** [comment] 2022-10-23 15:15
Duplicate of #5422.

**Closed by Frenzie** 2022-10-23 15:15 UTC
