### ISSUE TITLE
[FR] A menu item to temporarily keep device on

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2204] opened 2016-08-02 07:59 UTC
- KOReader version: Up to c0cc3b6
- Device: independent
#### Issue

When I am using sftp to communicate with kindle or kobo, the device must keep alive to avoid to drop connection. I know this is not part of koreader's responsibility, but it would be great if we have this functionality. The UI could be a dialog, showing 'Device won't sleep when this dialog shows up.' The implementation is simple for kobo, as we control the auto suspend in UIManager. But I have no idea how to keep kindle on.
Do you happen to have any thoughts?

**Comment by tigran123** [comment] 2016-08-02 09:42
I think there is a better way --- the way it is done in CoolReader. Namely, if there is a network connection (works for ssh, not sure about sftp, must test it to confirm) then the sleep is ignored, that is the device remains awake.

I suspect that is what the SIGTERM trap handler is doing in CoolReader's `suspend.sh` script, but not 100% sure. But the fact is --- the problem you describe is easily avoidable without modifying the source code of Koreader.

**Comment by tigran123** [comment] 2016-08-02 09:52
Correction: it works via USBNET, but now via WiFi --- obviously, because `suspend.sh` (in both CR and Koreader) unloads WiFi drivers.

But the good news is that it works in Koreader as well, not just CoolReader. Namely, I have just put my Kobo Touch to sleep via Koreader and the ssh connection (vis USBNET) is undisturbed.

I will test whether this can be done via WiFi also. I.e. maybe we can just avoid unloading WiFi drivers and it will magically "just work"? Let's see...

**Comment by tigran123** [comment] 2016-08-02 10:04
Yes, it does work --- if we don't unload WiFi drivers in `suspend.sh` then WiFi ssh connection is also undisturbed, i.e. the suspend request is simply ignored with this in `crash.log`:

```
sh: write error: Device or resource busy
```

The problem with this approach is that someone may have enabled WiFi for reasons other than connecting to Kobo from outside. E.g. I know there are some features of Koreader that use WiFi (though I don't use them). So, if WiFi is enabled from within Koreader, then suspend request will be ignored.

But maybe this is good? If someone has enabled WiFi and left it ON, then it is clear that the user intends for the device to remain connected to the network and suspend shouldn't interfere? It is displaying the screensaver and blocking the touch screen, but obviously continuing to consume the battery because all network connection (and all processes) are alive.

I think, the best solution would be to provide a configurable setting, like it is done in Android:

Terminate WiFi connection on suspend?

If the user chooses to terminate WiFi connection on suspend, then `suspend.sh` should behave like it currently does. If the user chooses NOT to terminate WiFi connection on suspend, then `suspend.sh` does not unload WiFi drivers and no actual suspend is done --- just the display of screensaver and ignoring touch events.

What do you all think?

**Comment by tigran123** [comment] 2016-08-02 10:13
Btw, let me add one detail that proves that your suggestion actually will NOT work.

Namely, if USBNET is enabled --- even if there are NO active ssh connection --- then invoking `suspend.sh` script fails anyway.

So, if the user enabled USBNET and, let' say you implemented your suggested menu option to avoid suspend. (Btw, you spoke of auto-suspend --- is there really such a feature in Koreader? It is an utterly dangerous (and imho useless) feature if it exists --- please tell me how to disable it.) Now, your menu option would not change anything --- the `suspend.sh` would simply generate an error like this in `crash.log`:

```
sh: write error: Device or resource busy
```

In order for `suspend.sh` to really work you should also unload the drivers responsible for USBNET (and kill the corresponding user processes first).

So, the option you suggest will not always work, but the option I suggest should be reworded as:

"Keep network connections on suspend?"

And treat _both_ WiFi and USBNET cases.

**Comment by Hzj-jie** [comment] 2016-08-03 06:37
I believe you are talking about kobo. In kobo, the suspension is controlled in UIManager, we can simply disable it by setting some flags in UIManager. i.e. do not call suspend.sh automatically. But in kindle, we do not have any logic to control the suspension. Kindle stock software handles it. So what I want is a way to avoid Kindle stock software to suspend the device.

So I cannot quite understand what do you mean by actually will NOT work here.

**Comment by tigran123** [comment] 2016-08-03 09:23
As I explained above, calling `suspend.sh` will be ignored (on Kobo) if USBNET drivers are loaded. I have tested it and confirmed it yesterday.

**Comment by Hzj-jie** [comment] 2016-08-03 20:20
Then what information do you want to provide here?
I have a kobo aura hd myself, with usbnet enabled, but device suspension works well. And this issue is talking about a way to keep device, more specific, keep kindle on, to achieve this feature request, as a simple device independent menu item to keep device on.
But most of your comments here are simply out of topic.

**Comment by tigran123** [comment] 2016-08-04 08:30
You are saying that if you enable usbnet on your Kobo Aura HD then device suspension works. That contradicts to what I am seeing on my devices. Are you sure you have tested this?

**Comment by tigran123** [comment] 2016-08-04 08:56
@Hzj-jie I made many comments and provided an amount of information that may be overwhelming for anyone at first reading. Please just study them carefully and slowly --- there is no rush, brother. And, of course, I will gladly clarify anything that is still not clear.

**Comment by Hzj-jie** [comment] 2016-08-05 22:15
Have you ever read what I am talking about in this issue? I am talking about to provide a functionality to *block* the device from suspending. But none of your comments here is really related to this issue.
To be more clear, for the Kobo, the stock software does not have the feature to auto suspend the device. So we implemented this feature in KoReader, and we can simply disable it if we need. For the Kindle, the stock software has an internal timer to suspend the device after some 10 minutes. What I have asked in the issue is whether there is a way to disable this timer to prevent the device from sleeping.
This is an open source project, you have your right to comment anything here. But please, read others' comments, or even better, read some code before providing out of topic comments.

**Comment by KenMaltby** [comment] 2016-08-05 22:53
To be accurate; the stock Kobo software (Nickel) does include Sleep & Power timers, but they don't effect KOReader, if Nickel isn't running.

**Comment by Frenzie** [comment] 2016-08-06 10:07
I don't have a Kindle and I'm sure you've already thought of some variation of this off-hand thought, but would it be possible to simulate activity by piping something to e.g. `/proc/touch` or `/proc/keypad`? (I got that from a quick peek on Google.)

**Comment by houqp** [comment] 2016-08-08 02:12
Fake key event is a good approach. I remember `/proc/keypad` works for my K3. Not sure what's available in the new kindles.

Have you also tried refreshing the screen periodically?

**Comment by tigran123** [comment] 2016-08-08 09:29
Has anyone actually tested that on Kindle my objection does not apply? Namely: with the network drivers loaded the suspend request is ignored anyway (this is the case on ALL Kobo devices --- I tested this), so it is silly to design an infrastructure "to temporarily disable suspend request" when it will be ignored anyway.

I suspect that this is the case on Kindle also (I just don't have modern Kindles to test, only Kindle 3 Keyboard and KindleDX which run kindlepdfviewer, not Koreader).

**Comment by tigran123** [comment] 2016-08-08 10:15
Actually, there was one non-trivial point which I originally thought was clear enough not to warrant a special clarification, but it appears that I should have explained it from the beginning.

Namely, the reason why @Hzj-jie said that "suspend works on Kobo Aura HD even with usbnet loaded" was because he probably tested it by simply looking at the screen and seeing the correct image (screensaver, book cover, whatever) was shown when he pressed the power button or closed the magnetic cover. But this proves ABSOLUTELY NOTHING at all. (well, other than the obvious fact that the code displaying the book's cover works fine :)

The proper way to test it is either:

a) login via ssh over USBNET and then try to suspend and observe that nothing happened (except the error message printed in `crash.log` file)

b) don't even bother logging in via USBNET. Just try to suspend and _after_ that connect the USB cable (or leave it if it was already connected) and login via ssh over USBNET and observe that your suspend request failed (and error message printed in `crash.log`).

Only if the above two methods actually fail (i.e. your login session is frozen in case a) or you can't login in case b) ) then it would mean that my objection does not stand.

As I said, on Kobo Aura HD, Kobo Aura H2O, Kobo Mini and Kobo Touch the above tests succeed, i.e. prove that the suspend request is ignored.

So, someone needs to thoroughly test it on Kindle. If the tests succeed then this whole approach is flawed. If they fail then what @Hzj-jie suggests is a good idea and should be implemented for Kindle only.

However, even though the tests succeed on Kobo I still agree with @Hzj-jie that it is a good idea to provide a GUI way of "disabling auto-suspend" on Kobos. Now, as I have explained (three times already) doing this would NOT actually "disable suspend", but it would disable screensaver (plus an attempt to suspend which would fail). This is still a very useful feature as I mentioned in #2207 .

**Comment by Hzj-jie** [comment] 2016-08-08 16:24
@tigran123 I have a look at your previous comments again, and believe you have found suspend.sh. This script is used to suspend Kobo devices, through hardware switch or UIManager auto suspension feature for Kobo. And we do unload wifi in this script. So I cannot quite tell why you always think suspension won't work for Kobo. If you believe USBnet would block suspend.sh to correctly suspend the devices, though I cannot reproduce on my device, as this script itself will be paused after "Kobo suspend: zzz". We can add commands to unload USBnet. But this topic does not relate to this issue. This issue is talking about a way to avoid device suspension. We can simply block suspension happens on Kobo by NOT execute suspend.sh.

**Comment by Hzj-jie** [comment] 2016-08-08 16:29
Thank you @Frenzie and @houqp for the comments. I will give a shot.

**Comment by houqp** [comment] 2016-08-09 09:02
@tigran123 I am concerning about battery consumption when maintaining WIFI connection in suspend mode. Ideally, I would like my device to be completely idle in suspend mode for maximum energy efficiency.

**Comment by tigran123** [comment] 2016-08-09 09:43
@houqp Yes, I completely agree with you --- if the user chooses to suspend, then the system should really be suspended rather than just showing the screensaver and disabling touch screen. What I keep repeating here is that if the network interfaces are up (we knew that for WiFi always, because `suspend.sh` handled this) then the real suspend (i.e. kernel-level event of actually freezing the system, all processes etc) will NOT happen and the system will continue to drain the battery as in normal usage. Also an error message will be printed in `crash.log` signifying the failure of the echo command which asks the kernel to put the system to sleep.

So, since the original reason why this issue was raised was to maintain the network connections despite user choosing to suspend (or auto-suspend timer triggering this) I am saying that the proposed "temporary disable of suspend" will be a "noop". It will do ABSOLUTELY NOTHING to network connections (via USBNET) because the mere fact of USBNET drivers being loaded (more precisely usb0 interface being up and running) prevents suspend in the first place. This is the Linux kernel behaviour and it has nothing with Koreader or any scripts infrastructure. It has to be the same on Kindle as well as Kobo, unless Amazon so heavily patched their kernel as to differ from the standard behaviour significantly. But I only tested this on Kobo devices, so I can't say anything about modern Kindles.

And I very frequently rely on this functionality (every day when I rsync the library on the device with the master repository on the desktop --- and my library does grow daily). Namely, when I enable USBNET via KSM I always touch "info" button so as to prevent accidental touch of "usbnet disable" and then I close the magnetic cover. This would ordinarily trigger suspend, but because usb0 interface is up, nothing happens. I then happily run rsync (or ssh) and the system is running as normal. But if usb0 interface is not up, then closing magnetic cover actually suspends the system (and no error message is printed in `crash.log`).

**Comment by tigran123** [comment] 2016-08-09 10:13
To be absolutely 200% sure I have re-tested it just now in Koreader and not just via magnetic cover, but also pressing the power button to cause it to suspend. I always (with no exception) get the same result, namely: when usb0 interface is up the suspend is ignored and this error message is printed in `crash.log`:

```sh: write error: Device or resource busy```

But when usb0 interface is not up, the system is suspended correctly and no error messages are printed. Everything works exactly as I described above.

**Comment by NiLuJe** [comment] 2016-08-09 12:01
Yep, same here, usbnet inhibits suspend on the Kobo ;).

It also does so on the Kindle, at least while plugged In, FWIW.

**Comment by tigran123** [comment] 2016-08-09 12:10
Thank you, @NiLuJe for confirming that my guess about Kindles was correct. It makes perfect sense.

**Comment by NiLuJe** [comment] 2016-08-09 22:25
I do mean 'only while plugged in' though ;). Once unplugged, they go into deep sleep properly.

My Kindles have been sitting in my shelves in USBNet mode for most of their lives, so, I should know ;p.

**Comment by houqp** [comment] 2016-08-10 08:28
@tigran123 I see, I misunderstood your previous comments. I thought you were talking about removing the kernel module unload call in suspend script to keep the wireless connection alive ;)

So to recap:
* if connection is established through usbnet, then suspend will not drop the connection
* if connection is established through wifi, then suspend will drop the connection (which can be addressed by this feature request)

I was thinking about the wifi scenario the whole time. Having to plug and unplug the devices all the time is definitely not fun :) I am hoping to go full wireless soon.

**Comment by chrox** [comment] 2016-08-10 08:51
I think this feature request is some kind of over-engineering especially considering the OP tries to add this feature as a reader menu entry. And I'm sure 99 percent of KOReader users won't use this no-suspend feature. How about implementing this feature as a KUAL extension or koreader launching option in KUAL config?

**Comment by Hzj-jie** [comment] 2016-08-10 09:04
The scenario is,
- I am always running KoReader on my devices.
- The device is fully wireless, i.e. I have enabled WIFI & USBNet.
- I am using sftp to sync books across different devices.
- Sftp is not fast enough, usually it needs 1 hour or even longer to compare and sync all books.
- Since the device will suspend in around 10 minutes. I need to touch the screen every several minutes.

Usually I do not want to shutdown KoReader, since I may still read during syncing, but may not.

I happen to have an old kindle 4 with Duokan installed. When the FTP server is enabled on Duokan, the device won't sleep, which is pretty convenient.

I agree 99% of users won't use this feature, so I am OK to add an optional plugin for this feature. i.e. Users can decide to install this plugin separately if he / she thought this feature was useful.

What do you think?

**Comment by houqp** [comment] 2016-08-10 09:05
That's true, it's mostly a developer only feature. Problem with KUAL is it only works for kindle. Thoughts about a developer only hidden menu? Other features like system resource information can go into that too.

**Comment by tigran123** [comment] 2016-08-10 09:46
@Hzj-jie You are saying sftp is slow and needs 1 hour or so. Why not use rsync? It usually takes a couple of seconds to sync a 100GB library via USBNet or 5-10 seconds via WiFi. Of course you have to use this special invocation thereof:

```
rsync --delete --size-only -rvW . root@usbnet:/mnt/onboard/.Books/
```

(with `usbnet` set to 192.168.2.101 in `/etc/hosts`). Please note the switches `--size-only` and `-W` without which the rsync to VFAT filesystem is meaningless (and would take about 1 hour just as you describe).

Btw, you are saying that 99% of users won't need this feature. Well, if my devices were behaving in the way you describe then I would definitely need this feature. But, fortunately, they do not and rsync of my enormous library takes a couple of seconds anyway.

**Comment by tigran123** [comment] 2016-08-10 10:09
@NiLuJe Yes, you are correct. I've just tested it and confirm that in one specific respect I was wrong --- the mere loading of USBNET drivers does not in itself inhibit suspend. Only the fact that the cable was plugged in does. Once the cable is unplugged the system can go to sleep. But as soon as you plugin the cable again --- it is woken up instantly and even your existing tcp sessions (e.g. ssh) can continue seamlessly as if nothing happened. So, we don't really need to unload USBNET drivers in `suspend.sh` --- as long as the USB cable is not plugged, the request to suspend the system will succeed.

Just like you I use USBNET all the time and would have preferred dropbear, KSM etc to be loaded from the root filesystem so that /mnt/onboard could be unmounted, fsck'd and generally administered via ssh session over USBNET. That would speed up the boot process enormously because fsck on boot could be commented out and the system would still come up (and instantly too!) and if there are problems accessing /mnt/onboard then the user would login via ssh over usbnet and check what is going on. That would be more to my liking as it is hacker-friendly (though utterly "user-unfriendly" but who cares --- I believe that the whole concept of "user" is a wicked invention of this dying age based on lies and deceptions. Computer can only be used by programming it, so if one is really "using" it then one is a programmer. Remember how in Star Trek every crew member, even a psychologist, is a user of the ship's systems precisely to such degree to which one can program them).

**Comment by NiLuJe** [comment] 2016-08-10 11:36
My usbnet/drobear setup (KoboStuff) lives in the rootfs for somewhat
related reasons, FWIW ;).

**Comment by tigran123** [comment] 2016-08-10 11:38
@NiLuJe Yes, I am going to migrate it there as well, if I have a spare minute :)

**Comment by Hzj-jie** [comment] 2016-08-11 04:46
@tigran123 Thank you for sharing your rsync script. I believe it should be extremely faster than regular file comparison. But this may not always work for me, i.e. I may not always copy files from one device to another. I may change some files in one device, and some others in another, according to which device I was using at the very moment. Note, I do not always add files, but also modify some.

So I agree most of users won't have my scenario, so I would prefer to add an optional plugin. So I am looking for a solution to support optional / document-less plugins now.

**Comment by Hzj-jie** [comment] 2017-01-16 13:40
The keepalive.koplugin has been submitted.

**Closed** 2017-01-16 13:40 UTC
