### ISSUE TITLE
[bug] Koreader crashes when switching Night Mode

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#6398] opened 2020-07-19 17:13 UTC
* KOReader version: 2020.07
* Device: PW4

#### Issue
Koreader crashing.

#### Steps to reproduce

1) Create a new profile
2) Apply it.  It seems to apply without a problem
3) Very soon thereafter Koreader seems to crash.  See error logs portions below

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

```
07/19/20-12:02:23 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
./luajit: frontend/ui/uimanager.lua:929: attempt to perform arithmetic on field 'FULL_REFRESH_COUNT' (a nil value)
stack traceback:
        frontend/ui/uimanager.lua:929: in function '_refresh'
        frontend/ui/uimanager.lua:1038: in function '_repaint'
        frontend/ui/uimanager.lua:1155: in function 'handleInput'
        frontend/ui/uimanager.lua:1227: in function 'run'
        ./reader.lua:305: in main chunk
        [C]: at 0x00013ef9
lipc-wait-event exited normally with status: 0
tail: read error: No such file or directory


and 
./luajit: frontend/ui/uimanager.lua:929: attempt to perform arithmetic on field 'FULL_REFRESH_COUNT' (a nil value)
stack traceback:
        frontend/ui/uimanager.lua:929: in function '_refresh'
        frontend/ui/uimanager.lua:638: in function 'setDirty'
        frontend/ui/widget/menu.lua:943: in function 'onCloseWidget'
        plugins/coverbrowser.koplugin/covermenu.lua:670: in function 'handleEvent'
        frontend/ui/uimanager.lua:402: in function 'close'
        frontend/apps/filemanager/filemanagerhistory.lua:143: in function 'action'
        frontend/ui/uimanager.lua:821: in function '_checkTasks'
        frontend/ui/uimanager.lua:1141: in function 'handleInput'
        frontend/ui/uimanager.lua:1227: in function 'run'
        ./reader.lua:305: in main chunk
        [C]: at 0x00013ef9
lipc-wait-event exited normally with status: 0

```

Profile was "Night Mode" which set the following: 
1) Turn night mode on
2) -18 brightness 
3) Show history screen
4) Show frontlight view

PS: Is there anyway to enable these profiles without long pressing on them?  Many thanks!  Would be nice if they could be invoked on a time schedule automatically and or via gesture manager.  Ideally both.

**Comment by Frenzie** [comment] 2020-07-19 19:31
Does your settings.reader.lua have a night_full_refresh_count? I wonder if it might be something unexpected.

**Comment by Frenzie** [comment] 2020-07-19 19:59
Oh, never mind. I didn't read through your replication closely enough. It's just about steps 3 & 4.

**Comment by arooni** [comment] 2020-07-19 22:40
Was also able to reproduce the error with the following settings:

Create a profile called "Night"
under Devices choose
1)  History
2)  Set Night Mode ==> On
3) Decrease frontlight brightness by 16.  (I normally leave it at 24 on the kindle)

Produces
```
07/19/20-17:36:22 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
./luajit: frontend/ui/uimanager.lua:929: attempt to perform arithmetic on field 'FULL_REFRESH_COUNT' (a nil value)
stack traceback:
        frontend/ui/uimanager.lua:929: in function '_refresh'
        frontend/ui/uimanager.lua:638: in function 'setDirty'
        frontend/ui/widget/menu.lua:943: in function 'onCloseWidget'
        plugins/coverbrowser.koplugin/covermenu.lua:670: in function 'handleEvent'
        frontend/ui/uimanager.lua:402: in function 'close'
        frontend/apps/filemanager/filemanagerhistory.lua:143: in function 'action'
        frontend/ui/uimanager.lua:821: in function '_checkTasks'
        frontend/ui/uimanager.lua:1141: in function 'handleInput'
        frontend/ui/uimanager.lua:1227: in function 'run'
        ./reader.lua:305: in main chunk
        [C]: at 0x00013ef9
lipc-wait-event exited normally with status: 0

```

**Comment by yparitcher** [comment] 2020-07-19 23:09
probably caused by ##6386 Am investigating.
@arooni 
have you changed `Screen -> E-ink settings -> Full refresh rate` at all?

**Comment by yparitcher** [comment] 2020-07-19 23:24
fixed in #6400

**Comment by arooni** [comment] 2020-07-20 00:57
@yparitcher  I don't appear to have a custom refresh count on screen, e ink settings, full refresh rate.

**Comment by yparitcher** [comment] 2020-07-20 01:00
if you go that menu and select `every 6 pages` (the default) it will work around. The proper fix is in #6400

**Comment by arooni** [comment] 2020-07-20 01:01
Ok neato!  Pesky nulls always messing things up :).  

As of now there is no way to trigger great feature of yours on a schedule or via a gesture correct?  Would love to see this added in the future.

**Comment by yparitcher** [comment] 2020-07-20 01:06
not yet.

I am in middle of work to refactor the gestures as a plugin using the dispatcher module (what powers profiles) so anything that can be done by a profile will be able to be done via a gesture, hopefully in the next few weeks.

This is what actually motivated me to do this whole thing. I wanted to be able to use one gesture to toggle NightMode & brightness. I just had to take a little of a roundabout route :)

**Comment by arooni** [comment] 2020-07-20 01:10
I had the idea for this awhile ago but glad that you're actually doing the work to turn it into reality :).  Many thanks!

**Closed** 2020-07-20 06:48 UTC
Labels: bug
