### ISSUE TITLE
FR: Time to Read

### ISSUE THREAD

**Issue by Yaretzki** [koreader/koreader#1707] opened 2015-11-06 10:45 UTC
Hello,
I wonder if it's possible or how difficult it would be to implement additional feature in statistics section: time to read.
There is already everything to calculate it:
- average time per page
- pages left in book
By combination of above it is easy to get rough estimation of time left to read book.
But I don't know how difficult it would be to implement it in statistic - current, and into status bar as additional information on top of already existing ones.

After a while I did some tests trying to get what I wrote above. Here is what I was able to get:
- edit file main.lua in statistic folder (under plugins folder of koreader)
- add additional line below line #238
- text of additional line:

table.insert(stats, { text = _("Time to read"), mandatory = self:secondsToClock((self.data.pages - tableutil.tablelength(self.data.details)) * (self.data.total_time / tableutil.tablelength(self.data.details))) })

As a result I see additional information in Statistic menu -> Current: Time to Read"

I'm really surprised I was able to do it because my "programming" skills are 0 or even less!
FR:
- I have no idea how to put it on status bar?
- Maybe it is also possible to make such feature for Time to Read Chapter?

**Comment by apletnev** [comment] 2015-11-06 11:15
I will add this feature in to statisitcs plugin.

**Comment by KenMaltby** [comment] 2015-11-06 13:08
Now imagine if you were trying to do this kind of thing, by talking to the "Customer Service" at any major  software company.  Would anyone have listened?  How long would it have taken them?  Can you believe that I still get people posting that they are afraid of, or reluctant to try any software not provided by the device makers.  

Luck;
Ken

**Comment by apletnev** [comment] 2015-11-06 22:46
@Yaretzki 
I've just added new behaviour in the Statistics plugin, but i slightly changed a formula of calculation time to read. You propose calculate difference between total pages - details, but details is not a current page. For example you can start read a new book on page 200 and the following, in this case details shows you only one item. Also you can re read the same page and in this case the details array will contain duplicate of the page but with different read time and date.
So currently i use total pages - actual read page.

If you have some proposals, suggestions or bugs, feels free to create new tickets. 
Thanks

**Comment by Yaretzki** [comment] 2015-11-07 13:32
That's great! I'm glad to hear it.
As I wrote I have no programming skills and I was not 100% sure what this additional line of code is going to bring. Thanks for making adjustments and corrections.
How about to move forward? I mean to implement such feature for "time to read chapter"? And how about to have one or both of them on status bar at the bottom of the page together with already existing? Should I open another FR/ticket?
Once again thank you very much for quick reply and implementation of Time to read into statistics section.
Y.

**Comment by apletnev** [comment] 2015-11-30 12:01
Implemented in #1723 and in #1718

**Comment by chrox** [comment] 2016-02-04 04:46
Closing this now since it's already implemented.

**Closed by chrox** 2016-02-04 04:46 UTC
