### ISSUE TITLE
Crash on higlight (attempt to get length of local 'boxes')

### ISSUE THREAD

**Issue by sr1920** [koreader/koreader#6825] opened 2020-10-25 10:25 UTC
* KOReader version: 2020.10.1
* Device: reMarkable

#### Issue

Sometimes I observe crashes when highlighting on a PDF file.

#### Steps to reproduce

I have not identified a clear pattern for reproduction. It seems to depend on the PDF file and the specific part the user wants to highlight.

##### `crash.log` (if applicable)

Example of crash:

10/25/20-10:10:11 ERROR failed to call event handler onAddHighlight plugins/statistics.koplugin/main.lua:1923: attempt to perform arithmetic on field 'highlights' (a nil value)
Error in pixWordMaskByDilation: imin = 2 is too small
Error in pixConnComp: pixs not defined
Error in boxaSelectBySize: boxas not defined
Error in boxaSelectBySize: boxas not defined
Error in pixaCreateFromBoxa: boxa not defined
Error in boxaSort2d: boxas not defined
Error in pixaSort2dByIndex: pixas not defined
Error in pixaaFlattenToPixa: paa not defined
Error in pixaGetBoxa: pixa not defined
./luajit: frontend/document/koptinterface.lua:802: attempt to get length of local 'boxes' (a nil value)
stack traceback:
	frontend/document/koptinterface.lua:802: in function 'getWordFromBoxes'
	frontend/document/koptinterface.lua:1036: in function 'getTextFromPositions'
	frontend/apps/reader/modules/readerhighlight.lua:824: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:255: in function 'handleEvent'
	frontend/ui/uimanager.lua:781: in function 'sendEvent'
	frontend/ui/uimanager.lua:241: in function '__default__'
	frontend/ui/uimanager.lua:1170: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1238: in function 'handleInput'
	frontend/ui/uimanager.lua:1282: in function 'run'
	./reader.lua:300: in main chunk
	[C]: at 0x0001415d
!!!!
Uh oh, something went awry... (Crash n°1: 10/25/20 @ 10:10:19)
Running on Linux 4.9.84-zero-gravitas (#1 Fri Jun 26 08:19:19 UTC 2020)
Attempting to restart KOReader . . .
!!!!

**Comment by sr1920** [comment] 2020-10-25 10:31
The previous problem seems to happen when the "reflow" option for PDF files is on. I tried highlighting "a problematic text" (trying to highlight this text leads to consistent/repeatable crashes when the reflow is on) with the reflow off and this time it did not crash.

**Comment by pazos** [comment] 2020-10-25 10:37
No idea about the stats plugin but https://github.com/koreader/koreader/blob/master/frontend/document/koptinterface.lua#L802 should guard against nil boxes.

Something like `if not pos or not boxes or #boxes == 0 then return {} end`

**Comment by NiLuJe** [comment] 2020-10-25 11:12
I think there's an old issue with a similar backtrace, possibly CJK-related at the time.

**Comment by NiLuJe** [comment] 2020-10-25 11:13
Or not, I completely missed the stats bit :D (on mobile right now).

**Comment by poire-z** [comment] 2020-10-25 11:29
> ERROR failed to call event handler onAddHighlight plugins/statistics.koplugin/main.lua:1923: attempt to perform arithmetic on field 'highlights' (a nil value)

is really similar to https://github.com/koreader/koreader/pull/6052#issuecomment-629610275 , that was fixed in #6173 .
`self.data.highlights` should be init'ed on load, except if Reading statistics are not enabled (but the plugin is enabled). Can you check if that's the case? We might get onAddHighlight called in all cased, and it shouldn't do stuff if not is_enabled.

**Comment by poire-z** [comment] 2020-10-25 11:32
Ok, reproduced when stats not enabled, on a PDF (no issue with EPUB):
`10/25/20-12:31:10 ERROR failed to call event handler onAddHighlight plugins/statistics.koplugin/main.lua:2206: attempt to perform arithmetic on field 'highlights' (a nil value)`

**Comment by sr1920** [comment] 2020-10-25 14:22
Yes, in my case I have the "Reading statistics" disabled, as I don't need that functionality (should I enable them?).

**Comment by poire-z** [comment] 2020-10-25 14:29
No. It's just that you get this error logged, but it cause no harm. It's something for us to fix, just to avoid this to be logged.

But you may try to enable reading statistics, exit, restart, and do your highlighting again - just to be sure it fails as before and that this small issue with statistics is not the cause of your more serious issue.

**Comment by sr1920** [comment] 2020-10-25 15:44
I did as indicated. The crash also happens with the readability statistics enabled.

**Comment by pazos** [comment] 2020-10-25 15:50
> I did as indicated. The crash also happens with the readability statistics enabled.

Yup, the error you see is `./luajit: frontend/document/koptinterface.lua:802: attempt to get length of local 'boxes' (a nil value)` and the solution for that specific bug is to guard against nil boxes before trying to get the length of the boxes table.

Try to reproduce the crash after applying https://github.com/koreader/koreader/issues/6825#issuecomment-716125421

**Comment by sr1920** [comment] 2020-10-25 17:55
After applying the modification suggested, I have not been able to reproduce the crash so far. So this modification could be a solution.

**Closed** 2020-10-26 11:26 UTC
