### ISSUE TITLE
Page randomly turning blank

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#4435] opened 2018-12-30 18:50 UTC
* KOReader version: v2018.11.1
* Device: Kindle Paperwhite 3

#### Issue
While reading page randomly turns blank, I need to move to next page, and then go back in order to get page content back.
#### Steps to reproduce
Read a book(I'm reading EPUB, but possibly occurs with other formats?)

**Comment by NiLuJe** [comment] 2018-12-30 19:06
Duplicate of #3287 

TL;DR: Weird side-effect of KPVBooklet + newer FW. Does not happen when launched from KUAL.

**Closed by NiLuJe** 2018-12-30 19:06 UTC
Labels: Kindle, bug, duplicate, firmware
