### ISSUE TITLE
Not refresh of battery status

### ISSUE THREAD

**Issue by albare** [koreader/koreader#4576] opened 2019-02-10 09:16 UTC
Kobo H2O.
The % of battery is not refresh. In the status bar.
Restarting koreader is not refreshing too.

The only way yo refresh is restarting kobo at all and start koreader again.

I am starting koreader with fmon. Is frustrating becouse i need to restarting kobo yo ser how is the battery every day or two days

Sorry for  my english...

**Comment by Frenzie** [comment] 2019-02-10 09:57
Pinging @NiLuJe

**Comment by NiLuJe** [comment] 2019-02-10 12:54
Err, I'm fairly sure that's working on my end, will double check though ;).

**Comment by NiLuJe** [comment] 2019-02-10 16:09
Yep, definitely can't reproduce.

Which status bar are you talking about?

**Comment by albare** [comment] 2019-02-10 16:26
The minibar at the botton. I configure to see  time, Pages, Pages to end chapter and the battery.
Could be a problem with fmon?.
Could be a problem with latest firmware of kobo?
I am at 44% from yesterday. I try to restarting koreader and not refreshing.
If i restart the device and  start again koreader the % is refreshing.

**Comment by albare** [comment] 2019-02-10 16:42
For extra information fmon is Baskerville fmon.
And Kobo Firmware 4.12.12111.

**Comment by albare** [comment] 2019-02-10 17:40
The menu has the same problem is not refreshing the battery status. (i dont know if the solution is the same).

**Comment by NiLuJe** [comment] 2019-02-10 17:40
Nope, definitely working properly on my end ;).

What may be happening is that the system is reporting bogus battery status.
I've seen some fairly stupid jumps triggered and/or fixed by a reboot. That's usually accompanied by a bogus decay, which may look like it's "frozen".

**Comment by NiLuJe** [comment] 2019-02-10 17:42
One way to be sure: check what happens in Nickel.

**Comment by NiLuJe** [comment] 2019-02-10 17:44
Also: check what happens if you charge the device, because that should definitely register, even if those bogus states.

**Comment by AlanSP1** [comment] 2019-02-10 18:49
I also noticed that if I have live time option checked (i.e. I don't need to turn page to see accurate time, it refreshes as time goes by), it affects battery also, i.e. battery reading is also changed when time is changed, without need for page turn.

But yes, I also noticed that battery sometimes is "stuck" too long on some value, only later to have some bigger drop. That is just how it works, battery info is almost never linear and accurate, on all my devices I don't have really linear battery readings.

**Comment by NiLuJe** [comment] 2019-02-10 18:51
@AlanSP1 : Yep, that's perfectly normal, the full footer is updated ;).

**Comment by albare** [comment] 2019-02-10 18:54
Yes!!! If i put kobo in  charge "+" is show  and the % is refresh. 
I unplug the device and now is working!!. After some time and Pages the %reduces 1%.
Could be the system only refresh if you charge the device under koreader one time?. I always charge the device where is off.

**Comment by NiLuJe** [comment] 2019-02-10 18:56
Closing, as this definitely doesn't have anything to do with KOReader, and everything to do with how the battery is handled by the HW ;).

**Closed by NiLuJe** 2019-02-10 18:56 UTC
Labels: Kobo

**Comment by Frenzie** [comment] 2019-02-10 19:28
Yes, the battery indication on my H2O tends to change in values of 10 to 20, except it sometimes returns oddly specific values (e.g., currently 51 %). That has nothing to do with KOReader and it's just how the hardware works. It's the same in Nickel.

It works well enough as a rough indication. The biggest problem is that you'd expect 20 % to mean many hours remaining, seeing how it takes a very long time to go from 50 % down to 20 %, but it actually means you've got to turn it off ASAP. Something very similar applies to any value it might display over 80, but that's more of a curiosity than something that tries to sabotage you. On any other device I own 30 % battery means I could charge it if I wanted to, not that I should.

**Comment by albare** [comment] 2019-02-11 18:29
After charge without restart the device all is working perfetct. Battery percent is modified with 1% steps.
If i restart the device and not charge It with koreader active one time the battery is not refreshing.
Is a Big mistery.
