### ISSUE TITLE
'Empty folder' with online webdav service

### ISSUE THREAD

**Issue by Australian-Infomaniac** [koreader/koreader#7452] opened 2021-03-28 04:46 UTC
* KOReader version: v2021.02
* Device: Kobo Libra H20

#### Issue
No files show and then "Empty folder"

#### Steps to reproduce

Cloud Storage > Add new Cloud storage > webdav > fill out the form:
Server display name: anything i want
Webdav address: https://webdav.cloudme.com/[my user name for this service, as advised on their site]
Username: my username for CloudMe
Pw: The pw I use for CloudMe

##### Other info:
I did successfully set up Dropbox, FWIW.
I am hoping though that Webdav will show a more information-rich file list: for example, allowing KOReader to even show covers? Feel free to disabuse me of this hope if this is not the case.

##### `crash.log` (if applicable): 
```
Original fb rotation is set @ 2
Original fb bitdepth is set @ 32bpp
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Detected a Kobo Libra H2O (384 => Storm @ Mark 7)
Variable fb info: 1264x1680 (1280x1792), 32bpp @ rotation: 2 (Upside Down, 180°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 5120 bytes
Device's expected Portrait orientation should be: 0 (Upright, 0°)!

Switching fb to 8bpp @ rotation 0 . . .
Setting bitdepth to 8bpp
Setting grayscale to 1
Setting rotate to 0 (Upright, 0°)
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 0 (Upright, 0°)

Variable fb info: 1264x1680 (1280x3584), 8bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 1280 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/28/21-15:44:00
 [*] Version: v2021.02

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
03/28/21-15:44:01 INFO  initializing for device Kobo_storm
03/28/21-15:44:01 INFO  framebuffer resolution: {
    ["w"] = 1264,
    ["h"] = 1680,
}
[ko-input] Forked off fake event generator(pid:4723).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=3.142 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 3.142/3.142/3.142 ms
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=2.031 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 2.031/2.031/2.031 ms
03/28/21-15:44:02 INFO  Loading plugins from directory: plugins
03/28/21-15:44:02 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
03/28/21-15:44:02 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: libs/libzstd.so.1
03/28/21-15:44:02 INFO  Plugin  plugins/coverimage.koplugin/main.lua  has been disabled.
03/28/21-15:44:02 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
03/28/21-15:44:02 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin calibre at plugins/calibre.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin opds at plugins/opds.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin profiles at plugins/profiles.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin qrclipboard at plugins/qrclipboard.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
03/28/21-15:44:02 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
03/28/21-15:44:09 INFO  event times are real clock time: no adjustment needed
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=5.381 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 5.381/5.381/5.381 ms
03/28/21-15:45:30 INFO  no dialog left to show
03/28/21-15:45:30 INFO  quitting uimanager
Restoring original fb bitdepth @ 32bpp & rotation @ 2
[FBInk] Detected a Kobo Libra H2O (384 => Storm @ Mark 7)
Variable fb info: 1264x1680 (1280x3584), 8bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 1280 bytes

Switching fb to 32bpp @ rotation 2 . . .
Setting bitdepth to 32bpp
Setting grayscale to 0
Setting rotate to 2 (Upside Down, 180°)
Bitdepth is now 32bpp (grayscale: 0) @ rotate: 2 (Upside Down, 180°)

Variable fb info: 1264x1680 (1280x1792), 32bpp @ rotation: 2 (Upside Down, 180°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 5120 bytes
```

**Comment by Frenzie** [comment] 2021-03-28 10:50
Probably fixed by https://github.com/koreader/koreader/pull/7425.

> I am hoping though that Webdav will show a more information-rich file list: for example, allowing KOReader to even show covers? Feel free to disabuse me of this hope if this is not the case.

That'd be extremely unlikely.

**Comment by Australian-Infomaniac** [comment] 2021-03-28 18:38
Hey Frenzie, what does it look like? 
I was also wondering if anyone has any ideas how to fix this issue

**Comment by NiLuJe** [comment] 2021-03-28 18:54
Update to the latest stable first, then if it still fails, enable verbose debug logging (In the FM: Tools > More Tools > Developer options)

**Comment by Australian-Infomaniac** [comment] 2021-03-28 19:15
BTW the Zoom functionality you created is very clever - one of the best things I noticed about KR. 
By setting it once on a particular PDF, you can read the whole PDF smoothly.
Compared to the default interface which doesn't even remember the font settings for each book!

**Comment by Australian-Infomaniac** [comment] 2021-03-28 19:21
Pls correct me if the following isn't correct:
To get the latest stable, I go to the home page of this project then:
CODE > Download zip
I originally got this in a package that included Plato and a script to avoid the deadly Nickel-scrapes-non-ebooks problem.

Actually, how do I install the update without re-creating that problem?
Can I just copy-paste the new stuff?
Or should I inject the new stuff into the previous package I used and run the script?

**Comment by Australian-Infomaniac** [comment] 2021-03-28 19:23
Note: I am using v2021.02

**Comment by Frenzie** [comment] 2021-03-28 19:53
You can copy-paste the new files over the old ones. You can also pick update in the top rightmost menu to do it within the program itself.

You could also always use the updated package from https://www.mobileread.com/forums/showthread.php?t=314220

**Comment by Australian-Infomaniac** [comment] 2021-03-28 20:49
Thanks so much! So much easier!

**Comment by Australian-Infomaniac** [comment] 2021-03-28 20:50
Y'all created a beautiful thing here - esp the aspects that make pdfs easier to read !

**Comment by Australian-Infomaniac** [comment] 2021-03-28 20:59
I was HOPING that the online service im using (MeCloud) might be able to show a html file (unlike Dropbox and Google Drive now), enabling me to use Calibre2Opds to make a nice list of files with covers, like this:

http://vaemendis.net/ubooquity/data/images/screenshots/books_library.jpg

"Cannot fetch list of folder contents..." "check configuration"

1. Is it essential to put the start folder?
2. I assume I can put anything I want in  'Server display name'

This is mystifying cos I know everything is correct.
Will send verbose log shortly

**Comment by Australian-Infomaniac** [comment] 2021-03-28 21:01
I just saw 'open random book' - that's something I always wanted ! Never seen it on any Android book reader. You guys must be real bibliomaniacs !

**Comment by Australian-Infomaniac** [comment] 2021-03-28 21:07
The cloud support was how I discovered KoReader - that's what I needed.

**Comment by Australian-Infomaniac** [comment] 2021-03-28 21:09
Oh nice - the USB connection works now ! :)

**Comment by Australian-Infomaniac** [comment] 2021-03-28 21:12
Here's the log - I hope its ok to put it on drive. Too long for pasting

https://drive.google.com/file/d/1WxPgblmxHamFro3t1E4ZYA4Z3bzFHrRM/view?usp=sharing

**Comment by NiLuJe** [comment] 2021-03-28 21:35
Well, it throws a 401.

Not familiar with the code and/or the service, but one thing to know is that we only support *Basic* auth. if the host is expecting Digest or something fancier, that won't work.

**Comment by Australian-Infomaniac** [comment] 2021-03-29 00:47
Thanks...

1. Do you know of a decent webdav service I could use? CloudMe don't seem to offer much support. All they have is a forum, which has alot of spam posts - so it can't be checked much

**2. I should mention that my main aim is to be able to see (and download) bunch of books I have on my own PC or in the cloud, with an interface that is as information rich as possible**, as I described [here](https://www.mobileread.com/forums/showthread.php?t=338295): 

...because I only have a little bit of space left on my Kobo, so I am going to have to swap books in and out

**a) The ideal would be to see covers
b) and/or be able to navigate through categories**

3. Options and results:

a) Using your dropbox interface (which I got working) and just having a PDF on my Kobo with my books listed with cover pictures (not as good as a dynamic html list obviously, which would allow me to navigate easily through various parameters such as different categories, priority-to-read and so on...)

b) someone in the above post recommended "calibre-web+kepubify with the Kobo sync option" but it looked overwhelming to set up so I haven't really tried that

c) Using calibre2opds to produce a rich html index as shown here:
http://vaemendis.net/ubooquity/data/images/screenshots/books_library.jpg
and then accessing it on a cloud service 
**I know Dropbox and Google dropped this - does this mean other providers are less likely to offer it? Am I wasting my time hoping for this?**

**4. I tried to put a catalogue created by Calibre2opds on the Kobo and open it in KOreader, but the html came out quite poorly- with no covers. Is there another way to do it than opening it like a book?**

**Comment by NiLuJe** [comment] 2021-03-29 01:33
That's going to be a no on covers (at least on the *device* side of things) for pretty much every solution out there.

The rest is covered by a plain Calibre instance that you can reach via OPDS (from the device), or a plain Calibre instance that you can connect to wirelessly via the Smart Device driver (i.e., what you already setup w/ UNCaGED and/or the KOReader Calibre plugin).

**Comment by Galunid** [comment] 2021-03-29 08:57
Best you can get is probably using Calibre-web with OPDS browser in KOReader (if you don't want to use computer), or like NiLuJe pointed out, Calibre plugin.

**Comment by NiLuJe** [comment] 2021-03-29 14:56
You don't need Calibre-web to get OPDS support, Calibre's stock OPDS server works out just fine.

**Comment by NiLuJe** [comment] 2021-03-30 15:08
1.

> That's going to be a no on covers (at least on the _device_ side of things) for pretty much every solution out there.

2. No idea what this is from?

**Comment by Australian-Infomaniac** [comment] 2021-03-30 21:28
2. On Calibre on Win 10, while sharing is on, and KOReader is connected, you hit the KOReader button on the toolbar. This error comes up in Calibre:

https://drive.google.com/file/d/1oNry5myP6lWqNIowUezbC15EdmBrEQX6/view?usp=sharing

**Comment by Australian-Infomaniac** [comment] 2021-03-30 21:29
3. In KOReader after I'm connected, what do I do (if all is working well) to see the books?

**Comment by NiLuJe** [comment] 2021-03-30 23:11
I have no idea what you're talking about?

You appear to be mixing everything together, which means I can't tell you what's happening or why.

**Comment by Australian-Infomaniac** [comment] 2021-03-30 23:15
Sorry about the confusion ! :) 

1. Maybe I'm using the wrong plugin: KoReader Sync. It was the only plugin on the repository with 'koreader' in the name

2. Should I instead install this?
https://github.com/koreader/koreader/tree/master/plugins/calibre.koplugin

3. Most importantly, once connected, what do I do on the Kobo device?

**Comment by Australian-Infomaniac** [comment] 2021-03-30 23:16
2a) If I did install that, is it for KOReader or Calibre?

**Comment by NiLuJe** [comment] 2021-03-30 23:22
1. Most definitely not. I never mentioned *anything* about Calibre plugins.
2. No, because it's already part of KOreader?
3. How/when/what/whay.

**Comment by Australian-Infomaniac** [comment] 2021-03-31 02:09
WOW ! 

I managed to get the 'OPDS Catalogue' working - even on my (main) XP machine.
That will save me ALOT of trouble - I have almost too many books to fit on Dropbox - I just deleted everything on it to fit them.
Thanks so much for implementing this!

B1. Is that the main method of accessing cloud books from KOReader?
 (I see you mentioned "browser" so Im wondering if there is even another tool as well)

B2. The list of parameters (tags, titles etc) is INCREDIBLY useful - better than what I could do on Dropbox I think**.
Absolutely key question: is there a way to add an item to this list? 
I really want to be able to list one of my custom calibre columns I created: PRIORITY.
I have alot of books so I have arranged them into into three categories for "Read now" (r1, r2 and r3) and three for "Check out to consider reading" (c1, c2...)

**Comment by Australian-Infomaniac** [comment] 2021-03-31 02:15
FOOTNOTE 
** Re "Trying to get a visual representation of your books to browse in the cloud", using KoReader and Dropbox:

To help others, I will let you know that I did find one potentially useful way:
* Use Koreader to download your books from Dropbox to your Kobo (or other)
* But BROWSE Dropbox folders on your phone, which DOES show covers of the books
This isn't perfect but it's the closest thing I've come to my ideal, without alot of mucking around.

(Though I haven't tried [this](https://www.mobileread.com/forums/showthread.php?t=338295) Calibre-web -based potential solution from Geek1011 yet, cos CW looks complicated to install - at least when I looked at it late one night while tired! :)

**Comment by NiLuJe** [comment] 2021-03-31 02:20
B1. OPDS, Calibre, whatever providers the Cloud thingy supports, and, of course, whipping up a custom script and running that.

B2. You've lost me again. I assume you're talking about the Calibre metadata search, which has nothing to do with this, since it's for *on device* content. And, no, that doesn't support custom columns, for various UX & technical reasons.

**Comment by Australian-Infomaniac** [comment] 2021-03-31 02:22
B1.A) The OPDS module seemed to work just fine with only starting "content server" in Calibre. It seemed unrelated to
-  'Wireless device connection" on calibre
- on KoReader: Tools > Calibre > Connect

So does the latter have a different function?

**Comment by NiLuJe** [comment] 2021-03-31 02:26
Yep, Calibre's Content Server is essentially a web interface, that also happens to implement an OPDS catalog.

The other thing implements a client for Calibre's Smart Device driver (e.g., exactly like UNCaGED).

**Comment by Australian-Infomaniac** [comment] 2021-03-31 02:26
B2. Oh wait ! It's already doing what I want. BLOODY MARVELOUS !

Just to help others I meant this:

On KOreader you can go:
 Search (maginifying glass) > OPDS Catalogue > Local Calibre Library

There is a list there of various parameters for showing you your books:
- By Newest
- By Title
- By Tag
[- By your own custom column - YAY!]

**Comment by NiLuJe** [comment] 2021-03-31 02:34
Oh, right, that works, yeah.

**Comment by Australian-Infomaniac** [comment] 2021-03-31 03:17
To help out other dummies like me, I added this wiki entry. Hope that's ok

https://github.com/koreader/koreader/wiki/OPDS-support

**Comment by Australian-Infomaniac** [comment] 2021-03-31 03:19
"The other thing implements a client for Calibre's Smart Device driver (e.g., exactly like UNCaGED)."
Oh so correct me if Im wrong that this is what 'Tools > Calibre > Connect' is for

**Comment by NiLuJe** [comment] 2021-03-31 15:28
Yep, and that requires the Wireless device connection "server", to be running in Calibre.

**Comment by Frenzie** [comment] 2021-07-22 10:25
I wrote something about Syncthing on the forums a couple of years ago when I gave it a quick go but here's the same thing with a few more words (and therefore presumably slightly clearer).
https://anarc.at/hardware/tablet/kobo-clara-hd/

**Comment by pazos** [comment] 2021-07-27 10:53
Duplicate of https://github.com/koreader/koreader/issues/7331

**Closed by pazos** 2021-07-27 10:53 UTC
Labels: bug
