### ISSUE TITLE
FR: Jump to Random Page(for fixed layout docs) or Paragragh(for reflowable docs) with Taps or Gestures

### ISSUE THREAD

**Issue by vyaus** [koreader/koreader#11718] opened 2024-04-26 02:31 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
I don't think the "*jump to random page*" feature is available in any e-reader.

I'm reading a very long book on my e-reader, but I can't jump to a random page or paragraph easily when I find something boring. Physical books are better than e-readers in this respect.

The following link is mobileread's discussion on this issue in 2017:

["Go to random page in book" button in e-reader](https://www.mobileread.com/forums/showthread.php?t=284834)

**Describe the solution you'd like**
I hope koreader can add "*jump to random page*" feature, so we can *read books like using Tiktok*.

Think you very much.

**Comment by hius07** [comment] 2024-04-26 06:40
Duplicate of https://github.com/koreader/koreader/issues/10744.

**Comment by vyaus** [comment] 2024-04-26 07:18
There are many non-fiction books out there that are not suitable to read page after page for readers with different backgrounds. Especially the classic books written several hundred years ago by foreign writers.

**Book Map** is great for books that you are familiar with, but when I was reading a difficult book, using **Book Map** to jump back and forth was really slow, I'll get out of flow state.

I want to swipe left to the next page, swipe right to the last page, swipe down to a random page, and swipe up to the previous page.

It seems #6036 might be of help.

Thank you any way!

**Comment by jonnyl2** [comment] 2024-04-26 09:15
>I want to swipe left to the next page, swipe right to the last page, swipe down to a random page, and swipe up to the previous page.

Note that you can't freely define swipe up and down (unless you mean on either edge of the screen or using two fingers).

**Comment by vyaus** [comment] 2024-04-27 00:30
> Note that you can't freely define swipe up and down (unless you mean on either edge of the screen or using two fingers).

I learned about this limit from the source code, swipe edge of the screen or two finger swipe is acceptable to me.

But the code in #6036 doesn't work on my device, I will try my best to fix it.

I think *jump to random page* is really important. Suppose there is a book with 20% of pages that you might be interested in, but you don't know where they are, when you swipe 5 pages randomly, there are $1-0.8^5=0.67$ rate that you will find at least 1 page that is interesting.

**Comment by poire-z** [comment] 2024-04-27 07:22
> I think _jump to random page_ is really important.

> > [...] has no occasion to exert his understanding, or to _exercise his invention_ in finding out _expedients for removing difficulties which never occur_

Looks like we are now way past the situation described in that old book :) 

> I don't know if there is any possibility that I will read the following paragraph in my lifetime.

Your trust in randomness is impressive :)

**Comment by vyaus** [comment] 2024-04-27 08:10
>Looks like we are now way past the situation described in that old book :)

We are just passing the costs on to developing countries, and there are many people in China working 12 hours a day, 6 days a week. India is next... Hopefully, we will have AI robots doing most of our jobs in the near future.

>Your trust in randomness is impressive :)

Even Tiktok's AI algorithm can't guess my mind, I have to dig information from classic books myself. If you have any better ideas, please tell me.

"Life is like a box of chocolates, you never know what you're going to get", randomness make us happy.

**Closed** 2024-04-28 15:04 UTC
Labels: enhancement
