### ISSUE TITLE
Add desktop version

### ISSUE THREAD

**Issue by leiserfg** [koreader/koreader#2624] opened 2017-03-10 04:42 UTC
There is not an ebook reader as fast and as good as this one on any desktop OS.

**Comment by KenMaltby** [comment] 2017-03-10 13:49
And, as you can use WiFi zsync between KOReader devices, having your PC as one could come in handy.

**Comment by Frenzie** [comment] 2017-09-26 15:15
Duplicate of #1417, so closing now. :-)

**Closed by Frenzie** 2017-09-26 15:15 UTC
Labels: enhancement
