### ISSUE TITLE
Crash upon closing any file and returning to File Manager

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6787] opened 2020-10-12 18:45 UTC
* KOReader version: v2020.10-2-gd2f533e_2020-10-11
* Device: remarkable

#### Steps to reproduce
1. Open epub
2. Return to File Manager
3. Crash screen with the log below is displayed

##### `crash.log` (if applicable)
```
10/12/20-13:30:39 INFO  opening file /home/root/mybooks/publicdomain_gnu.epub
10/12/20-13:30:39 ERROR failed to register crengine font: cannot register font </usr/share/fonts/ttf/noto/NotoSans-Bold.ttf>
10/12/20-13:30:39 ERROR failed to register crengine font: cannot register font </usr/share/fonts/ttf/noto/NotoSans-BoldItalic.ttf>
10/12/20-13:30:39 ERROR failed to register crengine font: cannot register font </usr/share/fonts/ttf/noto/NotoSans-Italic.ttf>
10/12/20-13:30:39 ERROR failed to register crengine font: cannot register font </usr/share/fonts/ttf/noto/NotoSans-Regular.ttf>
10/12/20-13:30:39 ERROR failed to register crengine font: cannot register font </usr/share/fonts/ttf/noto/NotoSerif-Bold.ttf>
10/12/20-13:30:39 ERROR failed to register crengine font: cannot register font </usr/share/fonts/ttf/noto/NotoSerif-BoldItalic.ttf>
10/12/20-13:30:39 ERROR failed to register crengine font: cannot register font </usr/share/fonts/ttf/noto/NotoSerif-Italic.ttf>
10/12/20-13:30:39 ERROR failed to register crengine font: cannot register font </usr/share/fonts/ttf/noto/NotoSerif-Regular.ttf>
10/12/20-13:30:42 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
./luajit: ./ffi/blitbuffer.lua:1402: bad argument #1 to 'sethook' (function expected, got number)
stack traceback:
	[C]: in function 'sethook'
	./ffi/blitbuffer.lua:1402: in function 'paintRect'
	./ffi/blitbuffer.lua:1629: in function 'paintRoundedRect'
	frontend/ui/widget/container/framecontainer.lua:78: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
	frontend/ui/uimanager.lua:1064: in function '_repaint'
	frontend/ui/uimanager.lua:1205: in function 'handleInput'
	frontend/ui/uimanager.lua:1282: in function 'run'
	./reader.lua:300: in main chunk
	[C]: at 0x0001415d
!!!!
Uh oh, something went awry... (Crash n°1: 10/12/20 @ 13:30:42)
```

**Comment by NiLuJe** [comment] 2020-10-12 18:56
Huh, being able to reproduce that on an actual device would be...a first.

Fun, fun, fun.

In any case, should be "fixed" via #6783 

And then I'll bump LuaJIT, because a fix for a possibly-related nasty issue landed today.

**Closed** 2020-10-12 18:59 UTC

**Comment by gbyl** [comment] 2020-10-13 12:09
@NiLuJe Thought you would like to know that the latest nightly fixed the issue just as you predicted. Only those `ERROR failed to register crengine font: cannot register font` remain, but they only show silently on the log, KOReader does not crash anymore. Thank you!

**Comment by NiLuJe** [comment] 2020-10-13 12:27
Those are completely normal, that's just CRe rejecting fonts once it already has four styles for a family: we happen to ship both Noto Sans & Nerif, so the bundled version wins ;).
