### ISSUE TITLE
Reflow: Crash on highlight

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#10854] opened 2023-08-28 14:04 UTC
![20230828_152350.jpg](https://github.com/koreader/koreader/assets/84848802/a53e5f12-2dba-4d13-905d-b9ac25374360)
Welp - hightling in Reflow isn't working as it should...

_Originally posted by @Knut0730 in https://github.com/koreader/koreader/issues/10719#issuecomment-1695696876_

**Comment by NiLuJe** [comment] 2023-08-28 14:09
Definitely need a repro testcase for this one, as a random test on my usual test PDF works just fine.

Also, annual reminder that reflow is an abomination you probably shouldn't rely on.

**Comment by Knut0730** [comment] 2023-08-28 14:28
This is the PDF I am currently reading: https://file.io/LHEXnF5fkggM
To be fair, it doesn't work to highlight this PDF at all, probably a bad scan by my library... hope you can reproduce it with this one.

**Comment by NiLuJe** [comment] 2023-08-28 14:46
That link is dead ;).

**Comment by benoit-pierre** [comment] 2023-08-28 15:08
Sorry, that might be because of me! ;( I downloaded the link to test with my version.

Anyway, I get some crashes with the AppImage, but no crash with MuPDF 1.22.2 (so far). The selection behavior is buggy in both cases: the selection is not updated, and start/end do not match the cursor coordinates.

**Comment by Knut0730** [comment] 2023-08-28 15:09
Here is a new link: https://file.io/ohgQFSt5penK ;) The link is purged after one download

**Comment by benoit-pierre** [comment] 2023-08-28 15:12
> Sorry, that might be because of me! ;( I downloaded the link to test with my version.
> 
> Anyway, I get some crashes with the official AppImage, but no crash with MuPDF 1.22.2 (so far). The selection behavior is buggy in both cases: the selection is not updated, and start/end do not match the cursor coordinates.

**Comment by ryanwwest** [comment] 2023-08-29 16:55
It seems like reflow is unfortunately pretty unstable right now (https://github.com/koreader/koreader/issues/10150, https://github.com/koreader/koreader/issues/10533, https://github.com/koreader/koreader/issues/9272, and on MacOS too)—it usually crashes for me on any platform so I just do not use it (but would like to).

I know it's not a 'new' feature, but I wonder if, until it becomes more stable, it might be worth putting some sort of qualifier like "(experimental)" in the UI or user guide until it's stable cross-platform? Sorry, I know this is more general than the specific issue brought up.

**Comment by Frenzie** [comment] 2023-08-29 17:31
I've read entire books with it on occasion fwiw.

> until it's stable cross-platform?

I'll quickly point out there's no such thing as an official macOS package, just an automated build. ;-)

**Comment by ryanwwest** [comment] 2023-08-29 17:33
Lol, knew you were gonna say that. I should've qualified it.

**Comment by jonnyl2** [comment] 2024-04-24 13:40
Also have encountered multiple crashes on highlighting with reflowed PDFs recently. 

Tested with this copyright-free PDF and it crashes as well when Reflow is on, both on Kobo and Android:

[the-adventures-of-huckleberry-finn.pdf](https://github.com/koreader/koreader/files/15095049/the-adventures-of-huckleberry-finn.pdf)

Here is the Kobo crash.log:

[crash.log](https://github.com/koreader/koreader/files/15095066/crash.log)

**Comment by jonnyl2** [comment] 2024-05-03 17:48
Unfortunately, the crashes still occur on v.2024.04-8. I've also noticed that Reflow mode doesn't necessarily have to be on; it also crashes when set to Continuous mode and text is being selected while more than one page is displayed on screen (it doesn't seem to happen on every page, though).

**Comment by Galunid** [comment] 2024-05-03 18:52
Could you share crash log? It's hard to tell what's going on without logs.

**Comment by jonnyl2** [comment] 2024-05-03 20:26
>Could you share crash log? It's hard to tell what's going on without logs.

[crash.log](https://github.com/koreader/koreader/files/15204711/crash.log)

Log file contains two crashes. 

First crash:
1. Set documen to Reflow On via bottom menu
2. Attempt to start selecting text
3. KOReader crashes immediately (no text is being selected)

Second crash:
1. Set document to Continuous mode via bottom menu
2. Start selecting text
3. KOreader selects text while panning on the text but crashes immediately on release of finger

**Comment by hius07** [comment] 2024-05-04 03:23
The first crash is by purpose, it occurs when debug mode is on only.
The second one must be fixed, to avoid it right now set the Highlight dialog position to anything other than the gesture position.

**Comment by jonnyl2** [comment] 2024-05-05 20:03
I ran into another crash (on a different book) involving ReaderHighlight today. Not sure if it's related (I can open a separate issue if need be).

It happened on very-long-press on "Index". I extracted the offending page from the PDF and am attaching it here, as well as the log file:

[PDFsam_Book.pdf](https://github.com/koreader/koreader/files/15214302/PDFsam_Book.pdf)

[crash.log](https://github.com/koreader/koreader/files/15214301/crash.log)

**Comment by hius07** [comment] 2024-05-07 16:55
Anchored dialog position issue fixed in https://github.com/koreader/koreader/pull/11761.

**Closed by hius07** 2024-05-07 16:55 UTC
Labels: bug, K2pdfopt
