### ISSUE TITLE
PocketBook Touch HD 631 - reader is unstable

### ISSUE THREAD

**Issue by Maradar** [koreader/koreader#3454] opened 2017-10-31 16:28 UTC
* KOReader version: koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-1393-gdbd9348

* Device: PocketBook Touch HD 631

#### Issue
No matter which book I open. It always crashes shortly after that or when I try do something like open the application menu. It seems the bigger the epub file the sooner the app crashes.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/1431452/crash.log)

**Comment by mk-f** [comment] 2017-11-01 19:47
The ``crash.log`` seems fine to me. Do you have shell-access on the device? If so, an ``strace`` could reveal more.

**Comment by Maradar** [comment] 2017-11-02 09:03
@mk-f sorry to say but I do not have shell-access

**Comment by schmittlauch** [comment] 2018-08-01 23:49
I'm also affected by this on my Touch HD2 (631) with Firmware U631.5.18.463 .
I also have no shell access on the device (is this even trivially possible?). But would it make sense to build KOreader with debug symbols for getting a richer crash log?

[crash.log](https://github.com/koreader/koreader/files/2251514/crash.log)

**Comment by Frenzie** [comment] 2018-08-02 16:19
Unless you want to get into gdb I doubt that makes much of a difference. You could try strace though. :)

**Comment by pazos** [comment] 2020-08-19 19:56
Duplicate of #3561

**Closed by pazos** 2020-08-19 19:56 UTC
Labels: PocketBook, bug, duplicate, firmware
