### ISSUE TITLE
A stand-alone Setting screen?

### ISSUE THREAD

**Issue by nagyation** [koreader/koreader#3602] opened 2018-01-13 22:06 UTC
Well, it's just a suggestion, I think that the reader screen should only contain settings that is relevant to reading itself, and others should all be collected in a stand-alone setting screen, I think that will make more room for the relevant settings 🤔 ?

**Comment by Frenzie** [comment] 2018-01-15 20:01
Could you please be a little more concrete about what the problem is? Sure, the Language and Time & Date could go into a submenu if there *were* a lack of space, but there isn't.

**Comment by nagyation** [comment] 2018-01-15 21:01
I'm not saying that space is the concern, my suggestion is migrating the unrelated settings, like network and all others, that doesn't have direct relation to reading to another "setting" screen specific for that, and leave the reader UI to things that have direct connection with reading itself, like bookmarking and contents, front-light, dictionary lookup etc..  
I think this will give more better UX, like mmm say kobo/kindle.
but that's for enhancement, not really an "issue"

**Comment by Frenzie** [comment] 2018-01-15 21:21
Frontlight, night mode, and DjVu render mode could migrate over one tab to the left if that's what you mean?

**Comment by nagyation** [comment] 2018-01-15 21:22
What I mean is a whole different screen not a tab

**Comment by Frenzie** [comment] 2018-01-15 21:48
Network definitely can't be in a separate window. It's basically the same as frontlight, except I actually use it. :-P (Of course you could say network can be a simple toggle, like night mode.)

**Comment by nagyation** [comment] 2018-01-15 23:06
yes exactly some of them is really needed, I'm saying to filter out the things that are needed the most to be there, that will reduce the menu & sub menus headache in the tray and will give simple UX, "Still that's just a suggestion because I think it will take time refactoring"

**Comment by Frenzie** [comment] 2019-08-30 13:34
I'll close this now because the settings menu is in effect a separate window. Please refer to <https://github.com/koreader/koreader/issues/3578#issuecomment-362308061> for my full argument. Thanks for the suggestions!

**Closed by Frenzie** 2019-08-30 13:34 UTC
Labels: UX
