### ISSUE TITLE
SVG formulae don't show in EPUBs

### ISSUE THREAD

**Issue by inductiveload** [koreader/koreader#7026] opened 2020-12-22 14:51 UTC
* KOReader version: 2020.12 (stable)
* Device: Kobo

#### Issue

SVGs for math formulae in WMF exports don't show in Koreader. E.g.:

* https://wsexport.wmflabs.org/book.php?lang=en&format=epub-3&page=The_Michelson-Morley_Experiment_and_the_Dimensions_of_Moving_Bodies

Original: https://en.wikisource.org/wiki/The_Michelson-Morley_Experiment_and_the_Dimensions_of_Moving_Bodies

#### Steps to reproduce

Open the linked file. See all the formulae are empty white boxes (of about the right size).

Should look something like: 
![2020-12-22_145020_883x134_screenshot](https://user-images.githubusercontent.com/466649/102901051-10d96380-4465-11eb-951e-23d544477eeb.png)

**Comment by Frenzie** [comment] 2020-12-22 14:59
Duplicate of https://github.com/koreader/koreader/issues/6757.

**Closed** 2020-12-22 14:59 UTC
Labels: duplicate

**Comment by johnbeard** [comment] 2020-12-22 15:45
See also: https://github.com/memononen/nanosvg/issues/129

**Comment by johnbeard** [comment] 2020-12-26 20:31
By the way, do we know what Nickel uses for an SVG library, because it works nicely there.

**Comment by Frenzie** [comment] 2020-12-26 20:56
Since they use Qt for the GUI, Qt SVG might make sense.

**Comment by NiLuJe** [comment] 2020-12-26 22:25
Yup, Qt5 ;).

**Comment by poire-z** [comment] 2022-09-11 18:41
With #9510 , the first post document now renders perfectly:
![image](https://user-images.githubusercontent.com/24273478/189543782-3f9fdbec-f2f3-4ac7-ad67-16142f9b6b41.png)
