### ISSUE TITLE
Question / feature request to import/export settings:  how to export settings from koreader (paperwhite) ==> new android device?

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#6925] opened 2020-11-29 22:25 UTC
* KOReader version: latest 
* Device: Paperwhite 4

#### Issue
During the BlackFriday (buy too much american ridiculous concept) I acquired a fancy new android tablet.  In order not to duplicate all my existing koreader settings, how can I move all my existing settings over to the new android tablet?   I was able to rsync my whole koreader over to my computer via rsync but not sure where to put the files on the tablet?

 I see 

```
gts6lwifi:/sdcard/Android/data/org.koreader.launcher/files $ ls

```

but there's nothing there.  

Perhaps a feature request would be a way to export/import settings when moving from different devices?  Would aid very much in getting the optimized reading experience wherever you go :)

EDIT: Apparently the koreader directory is /sdcard/koreader ;; but not sure which files to throw there?
EDIT2 : Just guessing , but I'm thinking the only files to throw on are settings.reader.lua and everything in /settings/ ?

**Comment by NiLuJe** [comment] 2020-11-29 22:56
There are only a few things on KOReader's side, mostly around the settings folder (c.f., [this](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Kobo_Hacks/Scripts/backup_koreader.sh) for inspiration).

The rest is alongside the books, in the sidecar folder (which'll also be full of Kindle stuff in your case).

**Comment by pazos** [comment] 2020-11-30 11:46
Duplicate of #4780

**Closed by pazos** 2020-11-30 11:46 UTC
