### ISSUE TITLE
Dictionary window doesn't show up until a manual refresh (Pocketbook 740)

### ISSUE THREAD

**Issue by evgenybf** [koreader/koreader#5139] opened 2019-07-23 10:24 UTC
* KOReader version:
koreader-pocketbook-arm-obreey-linux-gnueabi-v2019.07.zip

* Device:
Pocketbook 740 (InkPad 3)
Firmware: sw_20190709_U740_5.20.1010_user.zip

#### Issue
Sometimes dictionary window doesn't show up until a manual refresh. It seems it happens more often if the window is in the 'large' mode.

#### Steps to reproduce
Select a word by doing a long press on the screen. A message appears indicating that a dictionary is going to open. From time to time the message stays on the screen and the dictionary doesn't appear. Touch the screen or refresh it with a swipe. Dictionary will appear like it was on the screen but just wasn't painted..

**Comment by NiLuJe** [comment] 2019-07-23 14:41
Having a look at a verbose debug log might be helpful to see if a refresh is actually requested, and, if so, what kind ;).

(You can enable verbose logging from the "Developer options" menu, the last entry in the "Tools" tab of the FM's top menu).

**Comment by evgenybf** [comment] 2019-07-23 17:50
Here you are.. Perhaps, the logs are too detailed...
[crash.log.20190723.zip](https://github.com/koreader/koreader/files/3423373/crash.log.20190723.zip)
At the end, when it was reproduced, I tapped on the dictionary, closed it and exited Koreader.

**Comment by evgenybf** [comment] 2019-07-23 17:59
Reproduced when I selected "through"
[crash.log.20190723-through.zip](https://github.com/koreader/koreader/files/3423422/crash.log.20190723-through.zip)

Device froze when I selected "leads"
[crash.log.20190723-leads-frozen.zip](https://github.com/koreader/koreader/files/3423426/crash.log.20190723-leads-frozen.zip)

**Comment by tob1az** [comment] 2019-07-23 18:42
This is most probably the well-known issue with lack of auto-suspension support (#3561). Any actions taking more than 1.5 seconds like opening a book, looking up into a dictionary may lead to a freeze that is cured with tapping/clicking.

**Comment by pazos** [comment] 2020-08-19 19:55
Duplicate of #3561

**Closed by pazos** 2020-08-19 19:55 UTC
Labels: PocketBook, duplicate, firmware
