### ISSUE TITLE
v2019.01 fails to recognize CBZ

### ISSUE THREAD

**Issue by didierm** [koreader/koreader#4467] opened 2019-01-09 16:28 UTC
* KOReader version: 2019.01
* Device: Icarus E785BK (= Boyue LikeBook T80s)

#### Issue

After updating from v2018.12 to v2019.01, KOReader fails to recognize .cbz files.

#### Error messages

* In the file browser : _"(no book information: not readable by engine)"_
* When opening a file : _"No reader engine for this file or invalid file."_

#### Note

As a related note (probably warranting a separate issue) : 
The performance of KOReader when manipulating .cbz files (e.g. page swiping or page turning) is quite below par (chunky and slow swipes), compared with both **_FBReader_** (good performance) and **_MuPDF viewer_** (excellent performance) on the same device.

I was under the impression KOReader lets mupdf handle CBZ (and PDF), but I may be wrong.

**Comment by pazos** [comment] 2019-01-09 16:41
> After updating from v2018.12 to v2019.01, KOReader fails to recognize .cbz files.

I noticed the same on android with pdf files. "No reader engine"

> The performance of KOReader when manipulating .cbz files (e.g. page swiping or page turning) is quite below par (chunky and slow swipes), compared with both FBReader (good performance) and MuPDF viewer (excellent performance) on the same device.

Probably android specific. My phone (quad-core, a lot of  ram) is slower that my linux e-ink ereader. Hopefully https://github.com/koreader/android-luajit-launcher/pull/90 will help a little bit with that on some devices (It just did that with my moto G5S on general KOReader performance, but didn't test specifically w/ muPDF yet)

**Comment by didierm** [comment] 2019-01-09 18:24
@Frenzie 
> Depending on what you're talking about exactly KOReader still limits the refresh rate to something more E Ink friendly, cf. #3486.

I test CBZ on a Samsung TM-813 (Lineage 7.1.2), hence plenty of performance.

I failed to locate the "E-ink optimization" option in the "Screen" config section in v2019.01, but enabling/disabling the **Screen > E-ink settings > Use smaller panning rate** does not seem to make any noticable difference when scrolling epub text with **View Mode = [scroll]** instead of [page].
(unable to test with comics pages, as .cbz is not recognized).

**Comment by Frenzie** [comment] 2019-01-09 19:51
Sorry, I accidentally linked to another issue than the one I meant. It might be a duplicate of sorts since it's about the same issue though.

Scrolling performance isn't really considered an issue because on E Ink KOReader scrolls like a champ (if you feel so inclined) and on non-E Ink I'd say the USP is mostly in easy previous/next page. Not that it wouldn't be nice to have of course. I have toyed with the idea of experimenting with using textures which would allow for much faster rendering performance on capable platforms (i.e., Android and desktop) but I never seem to find the time. ;-)

**Comment by NiLuJe** [comment] 2019-01-09 21:55
Random lightbulb moment: Why the hell would a CBZ go through kopt? Isn't that handled by MµPDF?

**Comment by didierm** [comment] 2019-01-09 21:56
@Frenzie 
Diverging somewhat from the issue subject, but : 

Comics (and PDF publications) are quite commonly A4/Letter-sized, and usually too large to read on a tablet/eReader screen. Zoom (in portrait or landscape) is more of a requirement than a nice-to-have, and fluent panning is an essential part of the reading experience, as demonstrated in FBReader and MuPDF.
From your explanation, I gather we should currently refrain from using KOReader for these types of reading material, at least until A4 tablets/eInk become available ?
No problem, just hoping one (excellent !) app as KOReader would be a fit-for-all (especially as FBReader seems to be able to handle this).

**Comment by poire-z** [comment] 2019-01-09 22:03
> Random lightbulb moment: Why the hell would a CBZ go through kopt? Isn't that handled by MµPDF?

I understand MuPDF opens, parse, and render pages, and then koreader uses kopt to crop/zoom/dewatermark... these pages. So, I guess we always _use_ kopt when opening MuPDF files. (Except may be in the Zoom to fit page ?)

**Comment by didierm** [comment] 2019-01-09 22:06
@poire-z Me being blessed with technical ignorance, does this imply an issue concerning lacking zoom/pan performance for pdf/cbz document types should reference the kopt implementation rather than mupdf ?

**Closed** 2019-01-09 22:17 UTC
Labels: Android, bug

**Comment by poire-z** [comment] 2019-01-09 22:19
I don't know :)
@NiLuJe should have just fixed the _No reader engine for this file or invalid file_, so you can check tomorrow how scroll does
- with a real PDF, in full page mode and in fit to width mode
- with your CBZ, in full page mode and in fit to width mode, and with various options toggle like crop manual vs auto, dewatermark vs no dewatermark...

May be there's some of these options that triggers slowness or smoothness...

Just tested with a magazine PDF on my phone, and scroll mode is quite ok (a small 0.5 second pause when reaching a new page).
Also, I think we keep pages (rendered, croped) in cache, so scrolling inside a page (moving it a bit so to not bring any new page in the rendering process) should be quite fast. It is really not?
(I dunno how less powerfull these android reader are compared to a 2016+ phone.)

**Comment by didierm** [comment] 2019-01-09 22:21
Thanks, I'll test performance with the new version, and will file a new issue if/when appropriate.

**Comment by Frenzie** [comment] 2019-01-10 07:44
@didierm 

> Comics (and PDF publications) are quite commonly A4/Letter-sized, and usually too large to read on a tablet/eReader screen. Zoom (in portrait or landscape) is more of a requirement than a nice-to-have, and fluent panning is an essential part of the reading experience, as demonstrated in FBReader and MuPDF.
From your explanation, I gather we should currently refrain from using KOReader for these types of reading material, at least until A4 tablets/eInk become available ?

For me fit to width is an excellent default, with landscape taking care of the remaining few cases. In the rare case I might read a comic on my phone Bubble seemed to offer the best experience. Btw, fit to width is a lovely MuPDF feature, but I don't see a way to activate it in the Android app.

I'll add a video of the roughly expected panning performance.

* Smaller panning rate enabled:
[2019-01-10 08.13.37.mp4.tar.gz](https://github.com/koreader/koreader/files/2744082/2019-01-10.08.13.37.mp4.tar.gz)
* Smaller panning rate disabled:
[2019-01-10 08.35.49.mp4.tar.gz](https://github.com/koreader/koreader/files/2744140/2019-01-10.08.35.49.mp4.tar.gz)
