### ISSUE TITLE
Problem opening PDFs with nightly 1017

### ISSUE THREAD

**Issue by ko2017** [koreader/koreader#2826] opened 2017-04-29 12:59 UTC
* KOReader version: v2015.11-1017-gbb70ae9
* Device: Kobo Aura H2O

I run nightly versions.

When I load KOReader and try to open any PDF file via the directory file browser, history and open last document, it restarts and jumps to StartMenu. EPUBs however open normally.

**Comment by Frenzie** [comment] 2017-04-29 13:05
I can't confirm on my H2O with the same version. Could you share the relevant part of your crash.log?

**Comment by ko2017** [comment] 2017-04-29 13:25
Beg pardon, here seems to be the relevant part of the crash log:

04/29/17-14:15:22 ERROR cannot open translation file: l10n/en_US/koreader.po

**Comment by Frenzie** [comment] 2017-04-29 13:35
Unfortunately that's just some harmless noise. There's nothing following that?

**Comment by ko2017** [comment] 2017-04-29 13:37
An update on this: it seems that the PDF file was corrupted, it now works after I reloaded onto the Kobo! But what made me think it was a general error was that it was doing it for every PDF file, not just this corrupted one. And it only happened just after I updated to 1017. I was trying for quite a while with no success.

Sorry about that, so there is no issue after all.

By the way, thanks for all your effort with KOreader - it's a great piece of software.

**Comment by Frenzie** [comment] 2017-04-29 13:39
You're welcome! Does that mean your other PDFs are okay now?

**Comment by ko2017** [comment] 2017-04-29 13:41
Yes, all seems to be back to normal! Thanks very much

**Comment by Frenzie** [comment] 2017-04-29 13:45
Crashing on a corrupt PDF is a duplicate of #2335, so I'll close this now then.

**Closed by Frenzie** 2017-04-29 13:45 UTC
Labels: need more info
