### ISSUE TITLE
the lower menu does not appear in k4

### ISSUE THREAD

**Issue by carmelocotonto** [koreader/koreader#3910] opened 2018-04-24 07:11 UTC
* KOReader version: from 1654 to last one
* Device: kindle 4NT

#### Issue
We open an ebook and then we push the fisical menu button. Only the menu above appears. I didn't change any option. Later I have changed the view options and nothing, I can only see the above one. I have pushed twice the button but nothing. 
Maybe there is a combination of keys, but I can not find it
Regards

#### Steps to reproduce
Open a ebook

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment] 2018-04-24 07:18
Duplicate of #3909. Press enter. ;-)

I wonder if there's a way to make it easier to discover.

**Closed** 2018-04-24 10:26 UTC
Labels: Kobo, documentation, duplicate
