### ISSUE TITLE
Evernote Crashes on Login

### ISSUE THREAD

**Issue by pr0fsmith** [koreader/koreader#7761] opened 2021-05-25 20:57 UTC
* KOReader version: 2020.12
* Device: rM2

#### Issue
Crashes when i log into evernote

#### Steps to reproduce
login to english evernote

**Comment by Galunid** [comment] 2021-08-20 10:09
Duplicate of https://github.com/koreader/koreader/issues/6281

**Closed by Galunid** 2021-08-20 10:09 UTC
Labels: duplicate, Plugin
