### ISSUE TITLE
Upgrading ZeroMQ libraries

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1788] opened 2016-02-04 04:07 UTC
I am on Linux 64 Debian. I was able to build KR on this pc in the same folder (before the ./kodev stuff). Now it is throwing this error. I am trying to build it for Linux

Makefile:52: recipe for target 'all' failed
make: **\* [all] Error 2
[_] Running KOReader...
./kodev: line 210: pushd: ./koreader-emulator-_/koreader: No such file or directory
./kodev: ./reader.lua: ./luajit: bad interpreter: No such file or directory
./kodev: line 220: popd: directory stack empty

**Comment by houqp** [comment] 2016-02-04 04:20
Can you try `make all` manually and see what's the actual error?

**Comment by gerroon** [comment] 2016-02-15 23:52
I am still not able to build it properly


_unused_result [-Werror=unused-result]
     sodium_init();
                  ^
  CXX      libzmq_la-gssapi_server.lo
  CXX      libzmq_la-io_thread.lo
  CXX      libzmq_la-io_object.lo
cc1plus: all warnings being treated as errors
Makefile:815: recipe for target 'libzmq_la-curve_client.lo' failed
make[7]: *** [libzmq_la-curve_client.lo] Error 1
make[7]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
Makefile:822: recipe for target 'libzmq_la-curve_server.lo' failed
make[7]: *** [libzmq_la-curve_server.lo] Error 1
make[7]: Leaving directory '/media/DRIVE/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu/libzmq-prefix/src/libzmq-build/src'
Makefile:600: recipe for target 'all' failed
make[6]: *** [all] Error 2
make[6]: Leaving directory '/media/DRIVE/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu/libzmq-prefix/src/libzmq-build/src'
Makefile:424: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/media/DRIVE/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu/libzmq-prefix/src/libzmq-build'
CMakeFiles/libzmq.dir/build.make:114: recipe for target 'libzmq-prefix/src/libzmq-stamp/libzmq-build' failed
make[4]: *** [libzmq-prefix/src/libzmq-stamp/libzmq-build] Error 2
make[4]: Leaving directory '/media/DRIVE/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libzmq.dir/all' failed
make[3]: *** [CMakeFiles/libzmq.dir/all] Error 2
make[3]: Leaving directory '/media/DRIVE/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu'
Makefile:83: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/media/DRIVE/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu'
third.Makefile:392: recipe for target 'build/x86_64-linux-gnu/libs/libzmq.so.4' failed
make[1]: *** [build/x86_64-linux-gnu/libs/libzmq.so.4] Error 2
make[1]: Leaving directory '/media/DRIVE/BUILD/koreader/base'
Makefile:91: recipe for target 'base/build/x86_64-linux-gnu/luajit' failed
make: *** [base/build/x86_64-linux-gnu/luajit] Error 2
./kodev: line 7: [: too many arguments

**Comment by houqp** [comment] 2016-02-16 00:20
According to https://github.com/zeromq/libzmq/issues/1637, it's caused by a update in sodium. We should be able to fix it by updating libzmq. What Linux distribution are you using?

**Comment by gerroon** [comment] 2016-02-16 00:52
Hi

I am on Debian

**Comment by houqp** [comment] 2016-02-16 01:41
Which version of debian? What's the version of the libsodium-dev pakcage installed on your system? It will take sometime for me to update libzmq and verify everything still works given the fact that we are lagging behind upstream quiet a bit. 

If you need to get a build now, give https://github.com/koreader/virdevenv a try ;)

**Comment by gerroon** [comment] 2016-02-16 05:02
I am on sid

I will see if I have an update for libsodium. I have not updated for a while.

**Comment by gerroon** [comment] 2016-02-16 05:07
Ok I will try the virdenenv. Does it provide Android builds?

**Comment by houqp** [comment] 2016-02-16 05:13
Not yet, it only builds kindle, kobo and the emulator for now. I am planning to add android build support after I the command in kodev to help fetch android SDKs.

**Comment by houqp** [comment] 2016-02-16 05:15
So yeah, 1.0.5 is the last known working version for libsodium. We will need to update libzmq. @chrox , anything we need to watch out for the update? Do we need to bump the version for other libs like filemq, czmq, etc?

**Comment by gerroon** [comment] 2016-02-16 05:15
It would be very nice if it has android and x86 android. 

Is the Linux version statically compiled? if not how do I compile statically? So that I can move it to other linux boxes.

**Comment by gerroon** [comment] 2016-02-16 05:17
I personally do not care if the lizmq is fixed as long as I have a way to compile like using this virtdev stuff. However it is probably good idea to have it in place so that people do not waste time when trying to build this stuff.

**Comment by houqp** [comment] 2016-02-16 07:17
@gerroon most of the libraries are either statically compiled or shipped with the reader as dynamic libraries. After you compiled it inside the VM, you can give it a try with `./kodev run` from the host machine (assuming the host is also 64bit).

**Comment by gerroon** [comment] 2016-02-16 16:08
I tested the dev env and it works. I am hoping to see the other platforms support in it.


thanks

**Comment by houqp** [comment] 2016-02-16 17:51
Nice, I am also planning to migrate it to a docker image, which will hopefully drastically improve the build speed :)

**Comment by gerroon** [comment] 2016-02-16 20:47
Sounds good. 

How hard would it be to add x86 Android support?

**Comment by chrox** [comment] 2016-02-17 14:26
@houqp I'm afraid we need to bump all zeromq libraries used in Koreader. I will look into this later.

**Comment by houqp** [comment] 2016-02-17 23:29
I honestly have no idea how x86 android build system works...

**Comment by Markismus** [comment] 2016-02-18 11:59
I had the same problem on 4.4.1-2-ARCH. Downgraded libsodium from package version 1.0.8-1 to 1.0.5-1 as suggested in [the link given above](https://github.com/zeromq/libzmq/issues/1637). Compiles again. Thanks!

**Comment by NiLuJe** [comment] 2018-07-08 00:43
Yup, we're roughly two whole API versions behind :D.

**Comment by Frenzie** [comment] 2023-02-23 18:07
Closing, not really worth tracking separately.

**Closed by Frenzie** 2023-02-23 18:07 UTC
Labels: enhancement
