### ISSUE TITLE
Koreader not starting on a ddkv patched Remarkable one 

### ISSUE THREAD

**Issue by manuelinux67** [koreader/koreader#6393] opened 2020-07-19 07:11 UTC
Hello
I can’t start koreader on the remarkable one with the ddkv patch on it. The three seconds move only brings the list of recent files up and this belongs to the ddkv hack. So... is there any other way to start the koreader??

**Comment by pazos** [comment] 2020-07-19 08:29
Duplicate of #6042

**Closed by pazos** 2020-07-19 08:29 UTC

**Comment by manuelinux67** [comment] 2020-07-19 11:52
Well. Duplicate closed? Is my first request still open? Where can I find my answers then?

**Comment by manuelinux67** [comment] 2020-07-19 12:01
Hi. 
The first thread was in the wrong place. Now that U closed the duplicate, I will never receive answers to that question. 
Why r U doing this?
Manu

**Comment by pazos** [comment] 2020-07-19 12:31
@manuelinux67: There's a ticket opened by other user that asked the same question you asked. You can see the question and answers there: #6042 

Please do a look before opening tickets. All issues that your platform has are labeled as "ReMarkable". If you find an issue that's not reported feel free to open a new ticket. As a rule of thumb opening two or more tickets for the same issue is a bad habit and too much work to answer.

**Comment by poire-z** [comment] 2020-07-19 12:53
> Now that U closed the duplicate, I will never receive answers to that question.

Yes, we don't want answers and discussions mixed in 2 issues. As there are already more discussion in #6042, we closed yours.
You can subscribe to the other issue, and you will receive mails when discussion happens in it, by going to it and clicking (on the right side): 
<kbd>![image](https://user-images.githubusercontent.com/24273478/87875117-40280800-c9cf-11ea-8f26-6ec5c2f294e2.png)</kbd>

**Comment by manuelinux67** [comment] 2020-07-20 05:26
Oh!!
Now I get it!! 
Thank U. 
That is exactly what I was looking for! 

Sorry for bothering U before. 

Greetz 
Manu

**Comment by manuelinux67** [comment] 2020-07-20 06:33
Hi Martin

I get it now. Thank U for the right link. That is exactly what I was looking for. 

Greetz. 
Manu

**Comment by pazos** [comment] 2020-07-20 20:23
@manuelinux67: Hi Manu. Good to know. Don't hesitate to update the wiki with other launcher methods: https://github.com/koreader/koreader/wiki/Installation-on-ReMarkable
