### ISSUE TITLE
Exporting highlights from PDF - problem with the newlines

### ISSUE THREAD

**Issue by sr1920** [koreader/koreader#6045] opened 2020-04-12 18:07 UTC
* KOReader version: the last one (2020.03.2)
* Device: (reMarkable; I remember a similar issue with a Kindle in the past )

#### Issue

When I highlight text in a PDF file, it seems that the break lines are ignored and so the word ending each line and the one starting the next line are recorded as a single word with no blank space between them. 

This error can be noticed already in the metadata.pdf.lua file within the .sdr directory.
The error is also shown when exporting the notes with the Evernote plugin (no matter if you use the option to export as HTML or as a text file, in both cases the error can be seen).

At first I thought that the problem could be the way the newline was encoded in the output file, but it seems that this is not the case (I cannot see any special character between the two words).
The problem is not either related to the PDF formatting, as copying and pasting from the PDF to a text file keeps the break lines as expected.

To reproduce the problem: this seems to happen with any PDF file. As an example, you can try with the one available at http://ceur-ws.org/Vol-1756/paper06.pdf. For example try to highlight the first paragraph of the Introduction section and then export the notes.

The problem seems to arise in any condition (no zoom, no reflow, etc.).

**Comment by NiLuJe** [comment] 2020-04-12 18:09
That very, very, very vaguely rings a bell, you might want to do a deep dive in (old, possibly closed) issues, see if anyone had any bright ideas ;).

**Comment by sr1920** [comment] 2020-04-13 08:26
Thank you for the suggestion. I tried but couldn't find anything related in past issues. 

Looking at the code, I arrived at koreader/frontend/document/koptinterface.lua, where function KoptInterface:getTextFromBoxes(...) might be the responsible for getting the text in the PDF and not interpreting the newlines correctly.

In that function, the following code is found:

[...]
if word then
                -- if last character of this word is an ascii char then append a space
[...]

Maybe something similar needs to be added to detect newlines and append a space instead? Just an idea, but it is not clear to me...

**Comment by sr1920** [comment] 2020-05-23 15:28
I tested again with the new release 2020.05 "May Storm", but unfortunately the problem with the newlines is still there. For me this issue is critical, as it makes highlights in PDF files quite useless.

**Comment by pazos** [comment] 2020-05-23 15:40
> I tested again with the new release 2020.05 "May Storm", but unfortunately the problem with the newlines is still there. For me this issue is critical, as it makes highlights in PDF files quite useless.

It won't be fixed automatically. The problem is to figure out if a (word in a)box is the last one in a given line and append a space to it.

**Comment by Frenzie** [comment] 2020-05-23 21:21
@pazos A quick peek suggests this suffices to fix the issue, at least in the sample document.

```diff
diff --git a/frontend/document/koptinterface.lua b/frontend/document/koptinterface.lua
index 9930aa3b..b9e6160e 100644
--- a/frontend/document/koptinterface.lua
+++ b/frontend/document/koptinterface.lua
@@ -826,6 +826,8 @@ function KoptInterface:getTextFromBoxes(boxes, pos0, pos1)
                 line_text = line_text..word..space
             end
         end
+        line_text = line_text .. "\n"
+
         -- insert line box
         local lb = boxes[i]
         if i > i_start and i < i_stop then
```

That way these two look the same:
[paper06.html.zip](https://github.com/koreader/koreader/files/4672533/paper06.html.zip) (KOReader export)
[paper06.txt.zip](https://github.com/koreader/koreader/files/4672534/paper06.txt.zip) (pdftotext)

**Comment by sr1920** [comment] 2020-05-24 11:14
This solution works perfectly! Thank you very much!!!

After testing it, I am currently applying a small variation (adding a whitespace rather than a newline, and replacing "- " by nothing just in case there is hyphenation):

        line_text = line_text .. " "
        line_text = line_text:gsub( "- ", "")

**Closed** 2020-06-09 15:07 UTC
Labels: K2pdfopt, bug, help-wanted
