### ISSUE TITLE
Attempting to log in to Evernote causes KOREADER to crash

### ISSUE THREAD

**Issue by kobohobo** [koreader/koreader#4020] opened 2018-06-22 01:38 UTC
* KOReader version: v2015.11-1735-g14e7730_2018-06-02
* Device: Kobo Aura One Limited Edition

#### Issue
Attempting to log into Evernote causes KOREADER to crash (KOReader exited irregularly) 

#### Steps to reproduce
Open the Evernote plug-in and attempt to log in 

##### `crash.log` 
[crash.log](https://github.com/koreader/koreader/files/2125862/crash.log)

**Comment by NiLuJe** [comment] 2018-06-22 02:13
Duplicate of #3600 (re #4000 & re #3991)

**Closed by NiLuJe** 2018-06-22 02:13 UTC
