### ISSUE TITLE
Crashed while open a epub(Segmentation fault)

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#2756] opened 2017-04-11 14:14 UTC
* KOReader version:971
* Device:Kobo aura h2o

#### Steps to reproduce
 crash.log
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 04/11/17-21:28:56

04/11/17-21:28:56 ERROR cannot open translation file: l10n/en_US/koreader.po
04/11/17-21:28:56 INFO  initializing for device Kobo_dahlia
04/11/17-21:28:56 INFO  framebuffer resolution: {
    ["h"] = 1440,
    ["w"] = 1080
}
[ko-input] Forked off fake event generator(pid:818).
04/11/17-21:28:59 INFO  Loading plugins from directory: plugins
04/11/17-21:29:00 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/11/17-21:29:00 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin kosync at plugins/kosync.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin storagestat at plugins/storagestat.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
04/11/17-21:29:00 INFO  FM loaded plugin zsync at plugins/zsync.koplugin
04/11/17-21:29:33 INFO  opening file /mnt/onboard/书籍/失控.epub
04/11/17-21:29:35 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin storagestat at plugins/storagestat.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
04/11/17-21:29:35 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
Segmentation fault
```

**Comment by seacatwu** [comment] 2017-04-11 14:15
In the early version, the epub is OK

**Comment by Frenzie** [comment] 2017-04-11 20:02
Would it be possible to share this EPUB?

**Comment by seacatwu** [comment] 2017-04-12 01:10
@Frenzie  How can I upload a epub?

**Comment by Frenzie** [comment] 2017-04-12 06:21
You can add .zip at the end.

**Comment by seacatwu** [comment] 2017-04-12 13:43
I upload a zip,but it say that:
We don’t support that file type.  选择文件 Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

**Comment by seacatwu** [comment] 2017-04-12 14:01
@Frenzie I have sent a email to you :)

**Comment by Frenzie** [comment] 2017-04-12 18:29
I'm not able to reproduce the crash in the emulator or on my H2O with 972 (5bc19fa).

![2017-04-12 19 12 29-crop](https://cloud.githubusercontent.com/assets/202757/24973218/4ca3667e-1fbe-11e7-9507-2d2e7b6e1c4f.jpg)

If you don't have anything important in there (bookmarks, highlights, notes), could you try:

1. backup the .sdr folder to a zipfile
2. upload it here for analysis
3. use the "Purge .sdr" option in the file manager (long press on filename)

That should hopefully work around the problem.

**Comment by seacatwu** [comment] 2017-04-13 03:42
@Frenzie OK，maybe I changed the default CSS styles.

**Comment by retrue** [comment] 2017-04-13 07:18
It could be the same as #2386

**Comment by Frenzie** [comment] 2017-04-13 07:23
I haven't been able to reproduce, but that's probably helpful. :-)

**Comment by houqp** [comment] 2017-04-13 08:16
Might be another one of those crengine cache issue. @seacatwu can you try go into `koreader/cache` directory and rename `cr3cache` to another name and see if fixes the issue? If so, it would be very helpful if you can compress and send us the content in `cr3cache` folder.

**Comment by houqp** [comment] 2017-04-13 08:19
I also tested the file and was not able to reproduce the crash FWIW.

**Comment by seacatwu** [comment] 2017-04-14 10:07
@houqp  I have renamed the cr3cache folder, and it not crash.
I can't upload the cr3cache.zip here. So maybe I can send Frenzie by email. OK? @Frenzie

**Comment by seacatwu** [comment] 2017-04-14 10:12
![image](https://cloud.githubusercontent.com/assets/9783549/25040720/b862edf0-213d-11e7-912e-062de02da522.png)
Maybe these files.

**Comment by seacatwu** [comment] 2017-04-14 10:20
I have reproduced the crash.
1. Open the book.
2.Embedded Style set to OFF.
3.Set render style->Clear all external styles.
4. Choose a CSS styles
And then crashed.

**Comment by houqp** [comment] 2017-04-14 18:16
That's awesome! I can reproduce the crash now. Will take a look into that.

**Comment by seacatwu** [comment] 2017-04-15 04:35
:)

**Comment by frankyifei** [comment] 2017-06-02 10:18
can anyone share this book? I found a possible fix for #2386 so I want to test with this book.

**Comment by Frenzie** [comment] 2017-06-02 10:26
E-mail sent to your listed GitHub e-mail.

**Comment by poire-z** [comment] 2018-03-07 17:18
I'm confident this was fixed by @frankyifei in https://github.com/koreader/crengine/pull/73 and https://github.com/koreader/crengine/pull/86

**Comment by Frenzie** [comment] 2018-03-07 17:32
Alright, closing then.

**Closed by Frenzie** 2018-03-07 17:32 UTC
Labels: bug, crengine
