### ISSUE TITLE
Read timer not working in Boox Palma

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#11510] opened 2024-03-03 15:29 UTC
* KOReader version: Last release from today, 2024.03 "Read 'n Relax", but also in previous ones
* Device: Boox Palma

#### Issue
When setting the read timer with an interval, when the time runs out, there is no message of Time is up.
This works properly in my phone with Android 14 and I have noticed it also works fine in the Palma if the palma is connected to the computer or charging.

It is the same if you put timeouts bigger than 6 seconds in the Notification widget.

#### Steps to reproduce
Set the read timer with an interval of 1 minute
Wait 1 minute and see there is no message

**Comment by pazos** [comment] 2024-03-03 18:29
It looks like the system turns off your cpu cores after a few seconds of inactivity. While connected to usb the cpu isn't turned off.

I'm afraid it isn't our bug and can't be fixed. At least not without an affected device and some time lurking into the whole mess onyx is.

You could try using "settings->screen->timeout->keep screen on", which in fact sets a wakelock, so, if implemented properly, your device shouldn't be able to sleep. That should fix timeouts and any other things that rely on the cpu ticking (like auto* plugins)

Keep in mind that your device won't be able to sleep while "keep screen on" is enabled and KOReader is on the foreground. So, if that works for you, remember to press the power button to send your device to sleep or return to your device's home app. Otherwise you'll end up draining the battery.

**Comment by pazos** [comment] 2024-03-03 18:30
Pinging @hugleo, in case some device of yours is affected and you want to take a look :)

**Comment by hugleo** [comment] 2024-03-04 00:04
> Pinging @hugleo, in case some device of yours is affected and you want to take a look :)

I think it failed the first tests (or I didn't have the patience to wait that much), keeping the screen on, then off again. Specifying a specific time instead of setting an interval worked. Well, now everything is working.

The dialogue here is in minutes, not seconds like the OP said.

**Comment by jospalau** [comment] 2024-03-04 05:41
"settings->screen->timeout->keep screen on"

This made it work. Many thanks!

**Comment by offset-torque** [comment] 2024-03-04 06:11
> **pazos** - You could try using "settings->screen->timeout->keep screen on" . . . That should fix timeouts and any other things that rely on the cpu ticking (like auto* plugins)

Adding this to the guide's troubleshooting section

**Comment by pazos** [comment] 2024-03-05 12:58
@offset-torque: thanks!

The same issue also affects Pocketbooks, which also turn off cpu cores when they're not used.
In the case of Android eink not all devices are affected but every single Pocketbook is.

Fortunately we ship the autostandby plugin that let users tweak various related parameters, see https://github.com/koreader/koreader/blob/master/plugins/autostandby.koplugin/main.lua#L32-L39

The entry point for the plugin is in "Settings->device", most users would want to tweak `min` and `win` and leave `forbidden` as is. If users experience problems tunning these parameters it could be nice to verify they cannot be reproduced with `forbidden = true`, to give them hope to still tweak those paramaters until they met their expectations.

Disabling the autostanby on pocketbook (by `forbidden` it) would increment the battery consumption by 3-10x or even more based on the actual task, being sequential reading the most affected task :/

**Comment by jospalau** [comment] 2024-04-28 17:54
This is not working again even though it worked when I tried after activating:
"settings->screen->timeout->keep screen on"

Maybe something changed in the last firmware update end of March.

**Comment by pazos** [comment] 2024-06-01 16:13
Sad to hear that. Closing this ticket since it is an issue with the FW.

**Closed by pazos** 2024-06-01 16:13 UTC
Labels: Android, firmware

**Comment by offset-torque** [comment] 2024-08-13 07:41
@pazos

I am processing the guide and I saw that I marked this issue for inclusion. Now I see that the solution stopped working at least for the Boox device. I guess it is still working for Pocketbook devices. Should I still add autostandby solution to the guide (your 5 Mar comment specifically)?
