### ISSUE TITLE
Koreader doesn't reuse existing running instances

### ISSUE THREAD

**Issue by xahon** [koreader/koreader#6321] opened 2020-06-27 13:48 UTC
* KOReader version: 2020.06
* Device: Pocketbook 740 pro

#### Issue

When I open book, then go to home screen and open the same book again, then there are two tasks with the same name in task manager (both with title of my book). I can open lots of instances of koreader
Expected behaviour: When I open the same book koreader reuses existing instance of it. Like in iOs or android, when you open application that is still present in RAM it reopens again without extra instances

#### Steps to reproduce
1. Open book 'a'
2. Go home screen
3. Repeat 1 one or more times
4. Open up task manager

**Comment by pazos** [comment] 2020-06-27 14:48
Good catch!

> Expected behaviour: When I open the same book koreader reuses existing instance of it. Like in iOs or android, when you open application that is still present in RAM it reopens again without extra instances

That is exactly what I would expect in a mobile device (and what happens on android). On the desktop I think we're not aim at a single instance app, as having few instances is actually cool and useful (and not too resource hungry).

A proper single-instance implementation for pocketbook would mean:

- check that we can, in fact, repurpose the running instance. It is trivial on desktop but I have no idea how to do that on pocketbook (mechanism to raise a window?, some inkview api call?)
- on startup script check if other instances are running
- if an instance is already running forward messages to it using some IPC mechanism.

I would suggest a named pipe as a way to do chepo IPC and check if running instances exist.

Given that nobody has a pocketbook I would suggest a simpler solution: `killall`. Or, if you value current position, annotations, etc in the previous document opened, use a named pipe to tell it to close saving settings first. That should work without having to research how to raise the window and other things that are platform specific and noboby can answer without the device in hand.

**Comment by pazos** [comment] 2020-08-19 19:52
Can't reproduce. Maybe is something of old FW or specific to a device?

**Comment by roshavagarga** [comment] 2020-08-20 20:57
@xahon Are you running firmware 5.20 or firmware 6 that released in May 2020?

**Comment by tastytea** [comment] 2020-08-20 21:11
I can reproduce the issue with a PB632 (PocketBook Touch HD 3) running FW U632.6.0.926, released 2020-04-06 and KOReader 2020.08.

**Comment by pazos** [comment] 2020-08-20 23:17
@tastytea: thank you. Just to see if I understand correctly:

You can reproduce it following:

```
Open book 'a' (from PB library)
Go home screen
Repeat 1 one or more times
Open up task manager
```

But is not reproducible by starting the KOReader icon under applications n times. Is that correct?. If so please attach the extensions.cfg used to open books from PB system. Thanks!

**Comment by tastytea** [comment] 2020-08-20 23:35
> You can reproduce it following:
>
> Open book 'a' (from PB library)
> Go home screen
> Repeat 1 one or more times
> Open up task manager

Yes.

> But is not reproducible by starting the KOReader icon under applications n times. Is that correct?

Correct. Tapping on the KOReader icon brings the backgrounded program to the foreground.

> please attach the extensions.cfg used to open books from PB system.

[/system/config/extensions.cfg](https://github.com/koreader/koreader/files/5105949/extensions.cfg.txt)

**Closed** 2020-09-01 19:43 UTC
Labels: PocketBook, firmware
