### ISSUE TITLE
Horizontal rule section with image embedded in CSS is displayed with gray background

### ISSUE THREAD

**Issue by wanders78746** [koreader/koreader#6632] opened 2020-09-04 21:40 UTC
* KOReader version: 2020.08.1
* Device: Likebook Mars with Android 8.1

#### Issue
Horizontal rule section with image embedded in CSS is displayed with ugly gray background. Image associated with hr section is overlaid.

#### Steps to reproduce
See attached file Foo.epub in attached .zip file.

##### `crash.log` (if applicable)
N/A

##### Attachments
[Foo.zip](https://github.com/koreader/koreader/files/5177054/Foo.zip)

**Comment by pazos** [comment] 2020-09-04 23:19
Can reproduce in Auto -> epub.css, but not with html5.css

![2020-09-05_01-17](https://user-images.githubusercontent.com/975883/92290795-b77d1100-ef15-11ea-8dfa-5245a0277856.png)
![2020-09-05_01-17_1](https://user-images.githubusercontent.com/975883/92290797-b946d480-ef15-11ea-9458-036470672728.png)

**Comment by poire-z** [comment] 2020-09-11 20:37
In this book:
```css
hr.transition {
        background: url(../Images/image00083.jpeg) no-repeat center;
        height: 1em;
        border: none;
        margin: 1em 0em 0.50em 0em;
}
```
In our epub.css:
```css
hr {
    height: 2px;
    background-color: #808080;
    margin: 0.5em auto;
}
```
In our html5.css:
```css
hr {
  color: gray;
  border-style: inset;
  border-width: 1px;
  margin: 0.5em auto;
}
```
So it's our `background-color: #808080` that gets added to the image.

https://www.w3.org/TR/CSS2/sample.html :
```css
hr              { border: 1px inset }
```
Most browsers have `border: 1px inset`, some of them have additionally `color: gray`.

I don't like much border inset. With Zoom/DPI: 300:
With epub.css:
<kbd>![image](https://user-images.githubusercontent.com/24273478/92970536-1f37dc80-f47f-11ea-8392-30e2ced45b66.png)</kbd>
With html5.css:
<kbd>![image](https://user-images.githubusercontent.com/24273478/92970567-2d85f880-f47f-11ea-9a3c-b193e8d17f46.png)</kbd>

So, what should we go with instead in our epub.css ?

**Comment by Frenzie** [comment] 2020-09-11 21:04
background-color is just a different way of saying solid border (in this specific case)?

**Comment by poire-z** [comment] 2020-09-11 21:51
Right. So, I guess this will do:
```diff
 hr {
-    height: 2px;
-    background-color: #808080;
+    border: 1px solid #808080;
     margin: 0.5em auto;
 }
```
Only if a publisher adds a `height: 1px`, we will see a bordered box (which we wouldn't before) - but that's as it would look with browsers.

**Comment by hius07** [comment] 2020-09-12 04:28
Can you check `<hr>` in fb2 please. It gives no line, just a grey background to all the text after it.

**Comment by poire-z** [comment] 2020-09-12 05:27
fb2.css has the same as current epub.css:
`hr { height: 1px; background-color: #808080; margin-top: 0.5em; margin-bottom: 0.5em; }`

But:
- fb2props/FictionBook2.2.xsd doesn't mention anything about HR
- if you get its grey backgroung applied to the text after it, it's because the `<HR>` has not been closed. FB2 is XML, so no HTML self-closing: one should use `<HR/>` or `<HR></HR>`.

**Comment by hius07** [comment] 2020-09-12 06:31
Clear, thanks.

**Closed** 2020-09-18 17:34 UTC
Labels: bug
