### ISSUE TITLE
FR: Solarized Dark and Light for Linux Laptop and Android

### ISSUE THREAD

**Issue by lamyergeier** [koreader/koreader#8503] opened 2021-12-02 12:38 UTC
**Describe the solution you'd like**
I use Koreader on my Ubuntu 20.04 Laptop. Can you please add low contrast Solarized Dark and Light themes?

**Comment by NiLuJe** [comment] 2021-12-02 16:02
That would imply having theme support to begin with ;o).

**Comment by Frenzie** [comment] 2021-12-02 16:48
Did you try night mode?

**Comment by anishmittal2020** [comment] 2021-12-02 17:05
@Frenzie Yes, that's very high contrast. I would mainly  like to use Solarized light theme.

**Comment by pazos** [comment] 2022-07-14 09:17
Duplicate of #3871

**Closed by pazos** 2022-07-14 09:17 UTC
Labels: enhancement, help-wanted
