### ISSUE TITLE
v2021.01-amd64 crashes on startup

### ISSUE THREAD

**Issue by everdred** [koreader/koreader#7195] opened 2021-01-24 08:05 UTC
* KOReader version: v2021.01
* Device: Debian Testing amd64

#### Issue
KOReader displays a window for a fraction of a second before crashing.

#### Steps to reproduce
Update to v2021.01 from previous stable
Launch KOReader

##### `crash.log` (if applicable)

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 01/24/21-03:01:14
 [*] Version: v2021.01

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
01/24/21-03:01:14 INFO  platform thirdparty apps
-> Goldendict (goldendict), role: dict, available: true

Starting SDL in /usr/lib/koreader/
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
01/24/21-03:01:14 INFO  initializing for device Linux
01/24/21-03:01:14 INFO  framebuffer resolution: {
    ["h"] = 712,
    ["w"] = 830,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
/usr/lib/koreader/luajit: error loading module 'libs/libkoreader-nnsvg' from file './libs/libkoreader-nnsvg.so':
	./libs/libkoreader-nnsvg.so: undefined symbol: __pow_finite
stack traceback:
	[C]: at 0x00452810
	[C]: in function 'require'
	frontend/ui/renderimage.lua:215: in function 'renderSVGImageFile'
	frontend/ui/widget/imagewidget.lua:173: in function '_loadfile'
	frontend/ui/widget/imagewidget.lua:247: in function '_render'
	frontend/ui/widget/imagewidget.lua:352: in function 'getSize'
	frontend/ui/widget/iconbutton.lua:63: in function 'update'
	frontend/ui/widget/iconbutton.lua:52: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:111: in function 'setupLayout'
	frontend/apps/filemanager/filemanager.lua:481: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:1105: in function 'showFiles'
	./reader.lua:298: in function 'action'
	frontend/ui/uimanager.lua:975: in function '_checkTasks'
	frontend/ui/uimanager.lua:1326: in function 'handleInput'
	frontend/ui/uimanager.lua:1419: in function 'run'
	./reader.lua:322: in main chunk
	[C]: at 0x00405020
```

**Comment by everdred** [comment] 2021-01-24 08:06
In case it matters I installed the .deb file and not the AppImage.

**Comment by Frenzie** [comment] 2021-01-24 08:37
Duplicate of #7190. Today's nightly should fix it.

**Comment by everdred** [comment] 2021-01-24 20:26
@Frenzie Thanks! Confirming the nightly AppImage works.

**Comment by Frenzie** [comment] 2021-01-24 20:40
Great! I'll wait a couple more days to tag a point release since there's a small thing on some Android devices too.

**Closed by Frenzie** 2021-01-24 20:40 UTC
Labels: Desktop, bug, duplicate
