### ISSUE TITLE
Automatic Wi-Fi resume sometimes does not resume properly

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2274] opened 2016-10-01 23:39 UTC
- KOReader version: laster master
- Device: kobo hura hd
#### Issue

If I put device to sleep for too long, the wifi menu will show the device is not online. Not sure if it's because the wifi is not resumed properly or it's because there is a bug in connectivity checking logic.
#### Steps to reproduce
1. turn on auto wifi restore feature
2. turn on wifi from within koreader
3. put device to sleep for 10min
4. resume device, the check mark on wifi connection is missing

**Comment by Hzj-jie** [comment] 2016-10-12 00:12
The wifi resume logic won't block regular resume procedure, so it may take a while, usually less than 10 seconds. Would you mind to confirm?

**Comment by houqp** [comment] 2016-10-12 05:31
I waited for couple minutes and it's still not connected to internet. Looks like I can reliably reproduce this when the device goes into true sleep mode.

**Comment by Hzj-jie** [comment] 2016-10-13 01:11
That's weird. Are you using HD or H2O? I tested it only on HD. Is there anything else we need to do besides enable-wifi and obtain-ip?

**Comment by houqp** [comment] 2016-10-16 00:14
Haven't actually spent time digging into it yet, so a note to myself or anyone else who is interested in fixing it.

Following is a snippet from my crash.log that looks suspicious:

```
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
Sending discover...
No lease, forking to background
[Mon Feb 25 11:36:19 EST 2013] restore-wifi-async.sh: Restarted WiFi
```

The fact that this blob of log is followed by a lot of \x00 bytes is also weird.

**Comment by houqp** [comment] 2016-10-18 06:24
Ha, I know what's causing this issue. I think you probably has the wifi credential saved once in the kobo system. Because koreader does not change any of the system settings, it maintains its own network settings in a lua file. So if we only enable wpa_supplicant on resume, it won't be able to find the available network settings. The kobo reader on the other hand actually saves the network settings into /etc/wap_supplication/wpa_supplicant.conf.

I see two possible fixes:
1. Also call authenticateNetiwork on device resume. The bad news is authenticateNetwork is a blocking call. So we need to add an async version of this call that just add and enable the saved network without the event attach call.
2. maintain our own wpa_supplicant.conf file within kroeader folder. this means we need to make sure wpa_supplicant is launched with our own config.

**Comment by Hzj-jie** [comment] 2016-11-12 04:14
Oh, that's an interesting finding, I have not noticed it.
I believe we change frontlight setting, why cannot we change the wifi?

**Comment by houqp** [comment] 2016-11-13 00:13
Just trying to be less intrusive to the system. I personally prefer KOReader to be a 100% green software so it can be installed/uninstalled cleanly. I think the proper way to fix this is to introduce background worker into the UI framework, which will help solve many other issues we have right now.

**Comment by Hzj-jie** [comment] 2016-12-23 23:09
After I updated my AuraHD, the wifi auto resume function won't work any more. :(

**Comment by houqp** [comment] 2016-12-24 01:09
You mean after a kobo firmware upgrade? You can still connect to the wifi manually from KOReader right?

**Comment by Hzj-jie** [comment] 2016-12-26 01:26
No, I mean Koreader update. Yes, the 'wifi-connection' function works well, but it won't connect automatically after resuming from suspension. The log shows 'sending discover'.

**Comment by Hzj-jie** [comment] 2016-12-26 01:38
I doubt whether changes to https://github.com/koreader/koreader/blob/master/platform/kobo/disable-wifi.sh impact the behavior. Maybe the disable-wifi.sh cannot really disable wifi before, the WPA was not removed correctly. I remember we have talked about the 'connect' won't work after suspension before the automatically reconnect function has been implemented. I always needed to disconnect then connect. Now the issue has been resolved. So as a side effect, automatically reconnect won't work, as we need to reconnect WPA manually, which was not implemented in restore-wifi-async.sh.

**Comment by houqp** [comment] 2016-12-26 01:54
Interesting, I have tried reverting the disable-wifi script to the old version and see if the resume works again?

Based on the log, looks like it was failing at DHCP step. I wonder if it was able to authenticate with the router at all. If your router displays list of authenticated clients, that's another thing you can check.

What we really should be doing though is to bring preemptive tasks to the UI framework. I am really tempting to rewrite the main event loop in rust and expose it's task API to LuaJIT :(

**Comment by Hzj-jie** [comment] 2016-12-27 09:57
Yes, I really agree multi-threading is a must-have now. Since most linux commands are blocking.

**Comment by Hzj-jie** [comment] 2016-12-29 09:40
Sorry for the false alarm, after restarting my Kobo, the function now works well.

**Comment by houqp** [comment] 2016-12-29 23:10
I wonder if it's because DHCP client went into a weird state where it still tried to acquire the previous lease but was not able to?

**Comment by Frenzie** [comment] 2019-02-21 15:22
@NiLuJe You've touched the wifi code a fair bit recently. Do you know if this could still be an issue?

**Comment by NiLuJe** [comment] 2019-02-21 16:28
I've personally never experienced it, but I *have* my usual network saved in Nickel, which may be a factor here, according to @houqp's comments ;).

**Comment by Frenzie** [comment] 2019-11-11 17:35
Since KSM is no longer actively maintained (;_;) and we've already switched to recommending the one-click install method for KFMon a long time ago, I'll close this for now. Please feel free to add more info/reopen/etc. if desired.

**Closed by Frenzie** 2019-11-11 17:35 UTC
Labels: Kobo, bug

**Comment by doozan** [comment] 2020-04-03 20:41
I can confirm this issue still exists: restore-wifi-async.sh will only restore connections to networks that are in /etc/wpa_supplicant/wpa_supplicant.conf, which koreader doesn't touch.  I don't know if any progress has been made on threading since this was first reported, but if it's possible to call authenticateNetwork in the background now this would be pretty easy to fix.
