### ISSUE TITLE
build.koreader.rocks is down - Connection timed out Error code 522

### ISSUE THREAD

**Issue by kyxap** [koreader/koreader#12073] opened 2024-06-22 17:59 UTC
Not sure if this something related to my region but https://build.koreader.rocks/download/nightly/ does not work for me since this morning.

<img width="842" alt="image" src="https://github.com/koreader/koreader/assets/3080529/f026bf03-356d-4ab5-9ddb-1d618ddc52c9">

I'm wandering is there reason to use another external resource for nightly build if it seems can be done with existing ci?

**Comment by jonnyl2** [comment] 2024-06-22 18:52
This happens occasionally when the monthly bandwidth has been exceeded. I believe it resets on the 26th or 27th. So just be patient :)

**Comment by kyxap** [comment] 2024-06-22 19:00
5 days with no nightly build? wow

**Comment by pazos** [comment] 2024-06-22 19:22
The source code is available. You can build from there and pass the FOMO ;)

**Comment by pazos** [comment] 2024-06-22 19:23
Duplicate of #10615

**Closed by pazos** 2024-06-22 19:23 UTC

**Comment by Frenzie** [comment] 2024-06-22 21:33
There are mirrors and the actual builds are at https://gitlab.com/koreader/nightly-builds/-/jobs (but note, the Android packages there are not signed)
