### ISSUE TITLE
cannot delete highlights in pdf

### ISSUE THREAD

**Issue by khariche** [koreader/koreader#5994] opened 2020-03-21 18:09 UTC
* KOReader version:2020.03.2
* Device:Cervantes

#### Issue
Deleted highlights in pdf files reappear after reopening the file and cannot be interacted with.
#### Steps to reproduce
Both with reflow on and off, when I delete a highlight in a pdf file and reopen the file, one of two things happen:
- the highlight reappears exactly the same
- the text formerly highlighted is "dimmed" or greyed out, but without the darkened background around.
Whatever the case, I cannot interact with the highlight. When clicking on the highlighted words, I just get a page turn.
Going to the bookmark list doesn't help either, the highlight doesn't appear there (which is to be expected, as it has already been deleted).
The only solution is to open the file with a desktop pdf reader, and then the highlight is selectable and can thus be deleted.
I have also mentioned the problem here: https://www.mobileread.com/forums/showthread.php?t=321191

**Comment by pazos** [comment] 2020-03-27 21:04
Duplicate of #3113

**Closed by pazos** 2020-03-27 21:04 UTC
Labels: K2pdfopt, help-wanted
