### ISSUE TITLE
Release `2023.06.1` crashes when trying to go back to filebrowser from open document

### ISSUE THREAD

**Issue by hasezoey** [koreader/koreader#10704] opened 2023-07-16 13:23 UTC
* KOReader version: 2023.06.1
* Device: Tolino Vision 5 (android 4.4, arm)

#### Issue

KoReader crashes once trying to go back to the filebrowser from a open document

#### Steps to reproduce

- open koreader `2023.06.1`, open a file from the filebrowser
- try to go back to the filebrowser
- observe crash

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/12064134/crash.log)
[logcat.log](https://github.com/koreader/koreader/files/12064135/logcat.log)

---

last good version where this does not happen: `2023.06`

download source: https://github.com/koreader/koreader/releases `-arm-.apk`
manual install through `adb install file.apk`

also i dont know if this is related, but somehow tolino opens the "(android) Wifi Settings" app after the crash

**Comment by pazos** [comment] 2023-07-16 13:32
probably https://github.com/koreader/koreader/commit/08dd97384c9011004fd52eba2c559be5337838d5

Try to reproduce with kosync plugin disabled

**Comment by hasezoey** [comment] 2023-07-16 13:37
cannot reproduce with `Progress sync` (`kosync`) disabled on `2023.06.1`

**Comment by NiLuJe** [comment] 2023-07-16 16:51
It *should* be fixed in current nightlies, FWIW.

**Comment by pazos** [comment] 2023-07-16 17:37
> if it is not apparent from the logs, my device is always in airplane mode, almost never on some kind of internet access (wifi only, dont really needed it there), also never used kosync explicitly

Thanks for the feedback.

> cannot reproduce with Progress sync (kosync) disabled on 2023.06.1

Good to know. I'm not able to reproduce your original test case on my devices (both w/ wifi off and airplane on). Just get a prompt that asks me to enable wifi, but no crash at all. It might be firmware dependant.

Anyhow, I'm going to document the issue in https://github.com/koreader/koreader/wiki/deprecated-devices

**Comment by NiLuJe** [comment] 2023-07-16 17:43
Oh, FWIW, for people who *are* on deprecated devices, 2023.06 *should* be unaffected (... but it won't prevent you from upgrading to an unsupported version ;o). Decisions, decisions... ;)).

**Comment by hasezoey** [comment] 2023-07-16 17:52
> Good to know. I'm not able to reproduce your original test case on my devices (both w/ wifi off and airplane on). Just get a prompt that asks me to enable wifi, but no crash at all. It might be firmware dependant.

thanks for this info, i have now tired it again (kosync enabled) and done the exact same steps (this time waiting), then the system wifi page shows up (where i had assumed koreader crashed weirdly) but now going back (backspace or selecting in the open apps) to koreader it has a alert of `Error connecting to the network` and below it `Do you want to turn on Wi-Fi?`

i had assumed koreader crashed at those points because of some tolino notices (`Your tolino is experiencing problems, please wait`, basically tolinos note of "not responding" or "app has crashed" notice) and koreader being stuck for quite some time (and doing things it didnt do in previous releases), then the actual crashes i had experienced before were likely not related to this issue (i wont go into further detail, because i cannot reproduce them)

just as a note again, the device i have `Tolino Vision 5` is currently android 4.4, above the new minimal of 4.3

**Comment by pazos** [comment] 2023-07-16 20:44
>  [...] then the system wifi page shows up [...] going back to koreader it has a alert of Error connecting to the network and below it Do you want to turn on Wi-Fi?

even on v2023.06.1 the app shouldn't push you to wifi settings before you press enable in the checkbox asking for wifi.
I *think* most users will experience something like @Zeyadas or I did.

Not sure if your particular issue happens because it is an old version and can be reproduced on other brands or is just another tolino oddity. IIRC they left some parts of the framework unimplemented.

**Comment by pazos** [comment] 2023-07-16 20:47
> Oh, FWIW, for people who are on deprecated devices, 2023.06 should be unaffected (... but it won't prevent you from upgrading to an unsupported version ;o). Decisions, decisions... ;)).

They're fine. They have the issues and the workarounds documented **and** the source code still available. We're not Red Hat :p

**Comment by NiLuJe** [comment] 2023-07-16 21:06
> even on v2023.06.1 the app shouldn't push you to wifi settings before you press enable in the checkbox asking for wifi.
> I _think_ most users will experience something like @Zeyadas or I did.

Yeah, that probably requires a device where getting the state of the network is broken/unreliable (i.e., `Activity.networkInfo`).

But on those, I'm afraid *anything* that asks for network connectivity might be broken: it's pretty easy to reproduce with kosync because it also defaulted to auto_sync, meaning opening/closing a book would do that, but, technically stuff like Wikipedia or OPDS *should* be affected.

**Comment by hasezoey** [comment] 2023-07-16 21:19
> But on those, I'm afraid anything that asks for network connectivity might be broken

i just tried calibres `Connect` option, but that only brings up the `Do you want to start wifi` dialog from koreader, no wifi settings page, the same for the `News downloader` `Sync news feeds`, the same for `Update -> Check for Updates`

but using `Network -> Wifi settings` brings me to the systems wifi settings (which i would expect and think is intended), `Network -> Network info` does also not bring up the systems wifi settings

guessing by my testing, kosync is doing something differently than those plugins / updater

**Comment by NiLuJe** [comment] 2023-07-16 21:23
It's doing something... *slightly* different, but technically nearly identical, the main difference lies in the chronology, and especially in how it actually blocks for real on close (because of the chronology constraints).

**Comment by hasezoey** [comment] 2023-07-17 09:42
can confirm that the latest master (8a240dd635d188b1e4178b89d8d109ea9577722e) with the plugin `kosync` enabled does not ask for wifi anymore and does not take long to time-out

i also did some digging and no it does not seem to be a firmware bug, somehow `koreader/platform/android/luajit-launcher/app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt`'s `Activity.openWifi` is called, which is opening the WIFI_SETTINGS app

if i attach a stacktrace from `android.lua`'s `openWifiSettings`, then the following gets printed:
```txt
W/KOReader( 4528): TESTY
W/KOReader( 4528): stack traceback:
W/KOReader( 4528):      [string "android.lua"]:2384: in function 'openWifiSettings'
W/KOReader( 4528):      frontend/device/android/device.lua:294: in function 'turnOffWifi'
W/KOReader( 4528):      frontend/ui/network/manager.lua:539: in function 'goOnlineToRun'
W/KOReader( 4528):      plugins/calibre.koplugin/wireless.lua:237: in function 'connect'
W/KOReader( 4528):      plugins/calibre.koplugin/main.lua:90: in function 'callback'
W/KOReader( 4528):      frontend/ui/widget/touchmenu.lua:921: in function 'onMenuSelect'
W/KOReader( 4528):      frontend/ui/widget/touchmenu.lua:216: in function 'handleEvent'
W/KOReader( 4528):      frontend/ui/widget/container/inputcontainer.lua:261: in function 'handleEvent'
W/KOReader( 4528):      frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
W/KOReader( 4528):      frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
W/KOReader( 4528):      frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
W/KOReader( 4528):      ...
W/KOReader( 4528):      frontend/ui/uimanager.lua:1415: in function 'handleInputEvent'
W/KOReader( 4528):      frontend/ui/uimanager.lua:1513: in function 'handleInput'
W/KOReader( 4528):      frontend/ui/uimanager.lua:1557: in function 'run'
W/KOReader( 4528):      /data/data/org.koreader.launcher/files/reader.
```
(where `calibre` is just the plugin i test with, hijacking the `Connect` button for testing)

and if my guess is correct, it is because of the following lines, because they are "device" specific:
https://github.com/koreader/koreader/blob/8a240dd635d188b1e4178b89d8d109ea9577722e/frontend/device/android/device.lua#L291-L293

**Comment by jperon** [comment] 2023-07-21 15:17
I have the same symptoms on a Clara HD; crash.log below. Should I open another issue or stay on this one?
[crash.log](https://github.com/koreader/koreader/files/12130091/crash.log)

**Comment by hasezoey** [comment] 2023-07-21 15:23
> I have the same symptoms on a Clara HD; crash.log below. Should I open another issue or stay on this one?

with same symptoms i assume you mean a ~30 second timeout after going back from some document (or anything kosync)?
when yes, then i dont think it is necessary because the next release has that reworked, if that is not the issue then maybe open another issue (because this one here is mostly about android, which a kobo device does (to my knowledge) not use)

**Comment by hasezoey** [comment] 2023-07-21 15:41
> Disabling kosync doesn’t change anything.

then likely you should create a new issue - this does not sound like this issue at all

**Comment by newpavlov** [comment] 2023-07-31 16:56
Relevant issue: #7931

**Closed** 2023-10-01 12:25 UTC
Labels: bug, Android, out-of-date, firmware
