### ISSUE TITLE
FR: Configurable tap zones

### ISSUE THREAD

**Issue by agaAdams** [koreader/koreader#2292] opened 2016-10-18 07:16 UTC
#### Issue
Would it be possible to implement configurable tap zones as in CoolReader for kobo?
I find it much easier to remember tap zones than going through all the menus.

**Comment by houqp** [comment] 2016-10-18 07:26
We have this in advanced setting. See defaults.lua. You can persist the setting through advanced setting menu in filemanager.

Right now, it's only designed for power user so it's not easy to change. We will need a better UI to handle this.

**Comment by agaAdams** [comment] 2016-10-18 07:36
I understand in defaults.lua I can change the tap zones for menu, config, forward, etc. But I would like to assign e.g. fulltext search, closing a document and other functions to tap zones, double tap zones or "hold zones".
Or am I missing some setting variables in defaults.lua?

**Comment by houqp** [comment] 2016-10-18 07:38
Oh i see. You mean extra functionality mapping to tap zone. This is not supported right now. But not very difficult to support.

**Comment by Frenzie** [comment] 2016-10-18 14:05
Basically a duplicate of #1008?

**Comment by houqp** [comment] 2016-10-19 06:33
Good call @Frenzie , let's move the discussion to #1008

**Closed by houqp** 2016-10-19 06:33 UTC
Labels: enhancement
