### ISSUE TITLE
KOReader crashes due to httpinspector when port is already in use

### ISSUE THREAD

**Issue by arpanghosh8453** [koreader/koreader#12043] opened 2024-06-17 12:07 UTC
* KOReader version: 2024.04 (latest)
* Device: Kobo Libra 2

Koreader crashes when using [httpinspector plugin](https://github.com/koreader/koreader/pull/11457)

1. Turn on her httpinspector plugin server ( under more tools )
2. Press the power button to sleep the device
3. Press the power button to wake up
4. try to go to the file browser menu from the top panel
--- CRASH ---

##### `crash.log` 
```
06/17/24-16:19:06 DEBUG HttpInspector: Starting server... 
./luajit: frontend/ui/message/simpletcpserver.lua:27: attempt to index field 'server' (a nil value)
stack traceback:
	frontend/ui/message/simpletcpserver.lua:27: in function 'start'
	plugins/httpinspector.koplugin/main.lua:103: in function 'start'
	plugins/httpinspector.koplugin/main.lua:29: in function 'action'
	frontend/ui/uimanager.lua:1012: in function '_checkTasks'
	frontend/ui/uimanager.lua:1460: in function 'handleInput'
	frontend/ui/uimanager.lua:1580: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x000140cd
!!!!
Uh oh, something went awry... (Crash n°1: 06/17/24 @ 16:19:07)
Running FW 4.38.21908 on Linux 4.1.15-00866-g3a75628c73c (#96 SMP PREEMPT Thu Nov 17 14:25:47 CST 2022)
Attempting to restart KOReader . . .
```

**Comment by Frenzie** [comment] 2024-06-17 13:41
Discussion in https://github.com/koreader/koreader/pull/11457#issuecomment-2173126081 but let's move it here.

Port already in use is fairly self-explanatory. You can set a different port in the menu.

**Comment by arpanghosh8453** [comment] 2024-06-17 13:54
No, this is not another application occupying that port. It's not terminating itself properly, so that port is occupied by ghost process. 

when I restart the system, the same start server button works fine.

**Comment by poire-z** [comment] 2024-06-17 13:57
I guess it works after koreader launch - so the port is not used by something else.
But when suspend (where we should release the socket & port), and after resume, it happens that the port is not fully released/available and this happens.
So, probably some (timing?) issue in the :stop() part, either not done (so, add a logger.warn() before it to see), or done too near the kernel suspend action that it's not properly closed (or I forgot some call/option to properly close it there.)

**Comment by poire-z** [comment] 2024-06-17 13:58
And when you Stop / Start via the menu, all is well?

**Comment by arpanghosh8453** [comment] 2024-06-17 14:13
Thank you all for quick response. 

I do see the following in logs, so I think it stops it but the address is not being released. 

```
06/17/24-19:17:38 DEBUG HttpInspector: Stopping server... 
06/17/24-19:17:38 DEBUG HttpInspector: Server stopped. 
```

When I use the menu on/off without suspending in the middle, it turns on and off fine

but it throws the same error if the device is suspended in the middle ( while the server was on ) when trying to turn on afterward

if I turn it off manually, suspend, and then turn on the server, it works fine.

**Comment by poire-z** [comment] 2024-06-17 14:24
May be try:
```diff
function SimpleTCPServer:stop()
    self.server:close()
+   require("ffi/util").sleep(3)
end
```
The suspend screensaver should happen after 3 seconds, may be we'll see if it's enough to properly free the port. If yes, try to decrease it to find a minimal value, you can use `usleep(300000)` to sleep 300ms.

**Comment by arpanghosh8453** [comment] 2024-06-17 14:29
I also think it's not shutting down because when I suspend, it should stop if ( I don't have the auto start server enabled ), but I see the stop server button when it wakes up.

**Comment by arpanghosh8453** [comment] 2024-06-17 14:38
> May be try:
> 
> ```diff
> function SimpleTCPServer:stop()
>     self.server:close()
> +   require("ffi/util").sleep(3)
> end
> ```
> 
> The suspend screensaver should happen after 3 seconds, may be we'll see if it's enough to properly free the port. If yes, try to decrease it to find a minimal value, you can use `usleep(300000)` to sleep 300ms.

That did not solve the problem, the system immediately went to suspend without the delay. Is there any better way to debug, because I need to reboot the whole device for every test.

**Comment by arpanghosh8453** [comment] 2024-06-17 14:39
I am wondering if there is a way to check the port availability before starting and clearing the port pre-start. That might solve the problem for good.

**Comment by poire-z** [comment] 2024-06-17 14:47
I don't know of any way to clean a port (except by properly closing it).

Have you tried previously logging in there?
```diff
function SimpleTCPServer:stop()
+   logger.warn("closing 1")
    self.server:close()
+   logger.warn("closing 2")
+   require("ffi/util").sleep(3)
+   logger.warn("closing 3")
end
```

> Is there any better way to debug, because I need to reboot the whole device for every test.

Why  need to reboot ? Can't you just close & restart KOReader? (Closing the process that was listning on a port should clear the port).

Also, does this happen if you haven't connected to the http server ?

**Comment by arpanghosh8453** [comment] 2024-06-17 14:55
Restarting KOReader does not solve the issue, it crashes again when I try to start the server. 

And yes, it happens regardless.

**Comment by poire-z** [comment] 2024-06-17 14:57
Other things to try:
```
function SimpleTCPServer:start()
    self.server = socket.bind(self.host, self.port)
    self.server:setoption("reuseaddr", true)
    self.server:setoption("reuseport", true)
    self.server:settimeout(0.01) -- set timeout (10ms)
    logger.dbg("SimpleTCPServer: Server listening on port " .. self.port)
end
```
(It's a bit late to set these options AFTER the bind() - but who knows, may be it will affect the next :start()?)

Still looking around how to set these before bind().

**Comment by arpanghosh8453** [comment] 2024-06-17 14:58
I am wondering if there is any way to flip page with curl or ssh in Koreader without this server. I don't need any other features it offers.

**Comment by arpanghosh8453** [comment] 2024-06-17 15:08
As it stands now, 

start server -> stop server -> start server works fine

start server -> suspend/sleep -> wake up -> stop server (it shows it's running) -> start server (crashes!)

Start server -> stop server -> suspend/sleep -> wake up -> start server works fine

**Comment by poire-z** [comment] 2024-06-17 15:25
Another one to try:
```lua
function SimpleTCPServer:start()
    self.server = socket.tcp4()
    logger.warn("self.server", self.server)
    self.server:setoption("reuseaddr", true)
    self.server:setoption("reuseport", true)
    logger.warn("bind", self.server:bind(self.host, self.port))
    logger.warn("listen", self.server:listen(5))
    self.server:settimeout(0.01) -- set timeout (10ms)
    self.server:setoption("reuseaddr", true)
    self.server:setoption("reuseport", true)
    logger.dbg("SimpleTCPServer: Server listening on port " .. self.port)
end
```

**Comment by pazos** [comment] 2024-06-17 15:28
@poire-z: I do remember an issue like that on the calibre plugin if the device went to sleep while the wireless client is still connected.

I can't recall but I think this was solved by closing the socket before suspending, inplementing an `onSuspend` method. Maybe you could do the same here with an extra attempt to reconnect `onResume`?

**Comment by poire-z** [comment] 2024-06-17 16:08
We already do that (not sure how I came to think about doing that :)) - just tested with F2 on the emulator:
```
06/17/24-18:06:48 DEBUG HttpInspector: onSuspend
06/17/24-18:06:48 DEBUG HttpInspector: Stopping server...
06/17/24-18:06:48 WARN  closing
06/17/24-18:06:48 DEBUG HttpInspector: Server stopped.
06/17/24-18:06:48 INFO  Inhibiting user input


06/17/24-18:07:13 DEBUG HttpInspector: onResume
06/17/24-18:07:13 DEBUG HttpInspector: Starting server...
06/17/24-18:07:13 WARN  self.server tcp{master}: 0x7f3340caa870
06/17/24-18:07:13 WARN  bind 1
06/17/24-18:07:13 WARN  listen 1
06/17/24-18:07:13 DEBUG SimpleTCPServer: Server listening on port 8080
06/17/24-18:07:13 DEBUG HttpInspector: Server listening on port 8080
```

**Comment by Frenzie** [comment] 2024-06-17 16:19
I can't reproduce with the steps in the OP btw, Kobo Libra 2. There must be some additional aspect to triggering it.

**Comment by Frenzie** [comment] 2024-06-17 16:22
Unless it happens to be coincidentally fixed in current nightlies, although I don't see how anything could've changed in this regard.

**Comment by arpanghosh8453** [comment] 2024-06-17 16:49
> I can't reproduce with the steps in the OP btw, Kobo Libra 2. There must be some additional aspect to triggering it.
> 
> Edit: nor the steps in [#12043 (comment)](https://github.com/koreader/koreader/issues/12043#issuecomment-2173669482)

I need to look into that. I am not sure what else might be using that address?

**Comment by poire-z** [comment] 2024-06-17 16:51
Have you tried my latest suggestion ? And please show the logs (similar to my latest sample with the few ARN).

**Comment by Frenzie** [comment] 2024-06-17 17:00
> I need to look into that. I am not sure what else might be using that address?

Something like `netstat -ltp` will tell you (-l for listen -t for tcp and -p for PID/program name)

**Comment by jospalau** [comment] 2024-06-17 17:11
I tried to reproduced it since I was using it yesterday and was working fine.

It worked a few times after reconnecting. The port remains opened and the menu says Start HTTP server. If I try to start it, it crashes:
![17186439876813157648655124778474](https://github.com/koreader/koreader/assets/85340/011bd8c7-6632-42cc-94c5-9c4ca398e5f8)

Isn't there wpa_supplicant listening on that port too?
![Screenshot_2024-06-17-20-08-45-291_com termux](https://github.com/koreader/koreader/assets/85340/2bd101de-8651-46da-9b99-db3fff4e65f4)

**Comment by arpanghosh8453** [comment] 2024-06-17 17:15
> Another one to try:
> 
> ```lua
> function SimpleTCPServer:start()
>     self.server = socket.tcp4()
>     logger.warn("self.server", self.server)
>     self.server:setoption("reuseaddr", true)
>     self.server:setoption("reuseport", true)
>     logger.warn("bind", self.server:bind(self.host, self.port))
>     logger.warn("listen", self.server:listen(5))
>     self.server:settimeout(0.01) -- set timeout (10ms)
>     self.server:setoption("reuseaddr", true)
>     self.server:setoption("reuseport", true)
>     logger.dbg("SimpleTCPServer: Server listening on port " .. self.port)
> end
> ```

Hey @poire-z I am not sure what it did, but the issue is gone with this settings, it does not crash anymore!!! Yah! You are a lifesaver. Thank you so much! You are so quick too!

I was facing the exact same issue as @jospalau, do you mind trying the above settings and see if it fixes the problem too?

**Comment by Frenzie** [comment] 2024-06-17 17:21
> Isn't there wpa_supplicant listening on that port too?

Not for me, no. That's either:

```
[root@kobo ~]# netstat -tlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN      4152/dropbear
netstat: /proc/net/tcp6: No such file or directory
```

Or after `Start HTTP server`:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN      4152/dropbear
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      20824/luajit
```

**Comment by jospalau** [comment] 2024-06-17 17:31
Killing wpa_supplicant lets the service start again.

I reproduced it again after a few tries suspending/resuming/reconnecting. The wpa_supplicant launches a service on the same port for some reason.

I got a different crash this time I think before this happening:
![Uploading IMG_20240617_202858.jpg…]()

**Comment by poire-z** [comment] 2024-06-17 17:42
@arpanghosh8453 : thank you.

I didn't know about the wpa_supplicant, so may be there's something transient with it where it listens on port 8080.
I guess if that was the case, the solution @arpanghosh8453 just tried would not work.
Anyway, @arpanghosh8453 , if you still have some little bit of courage to support a few crashes and reboots, could you try WITHOUT my patch (with the original code), and choose another port than our default of 8080, let's say 44444 - and see if the same issues happen.

**Comment by jospalau** [comment] 2024-06-17 17:49
wpa_supplicant is a port hog :)

![Screenshot_2024-06-17-20-48-06-074_com termux](https://github.com/koreader/koreader/assets/85340/bff6ea2b-bac5-42fd-ba76-5c56aa05bbb1)

**Comment by Frenzie** [comment] 2024-06-17 17:51
@jospalau Could you run something like
```
ps | grep 26672
```

To see if it'll show the command?

**Comment by jospalau** [comment] 2024-06-17 17:53
wpa_supplicant -D nl80211 -s -i mlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -C /var/run/wpa_supplicant -B

**Comment by NiLuJe** [comment] 2024-06-17 17:59
It would appear that your Clara 2E device is haunted.

```
┌─(ROOT@goldfinch:pts/0)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(1.53:23%:19:58:72%:#)── netstat -lutp                                                                                                                                                                                                                                                                                                               ──(Mon, Jun 17)─┘
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      733/inetd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      779/dropbear
tcp        0      0 0.0.0.0:23              0.0.0.0:*               LISTEN      733/inetd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1400/dhcpcd
┌─(ROOT@goldfinch:pts/0)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(1.49:23%:19:58:72%:#)── ps faux | ag wpa_sup                                                                                                                                                                                                                                                                                                        ──(Mon, Jun 17)─┘
 1388 admin     0:00 wpa_supplicant -D nl80211 -s -i mlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -C /var/run/wpa_supplicant -B
```

**Comment by Frenzie** [comment] 2024-06-17 18:00
Mine (that may not be hogging any TCP ports) is slightly different. But that's probably a natural difference between the Libra 2 and the Clara 2E.
```
wpa_supplicant -D wext -s -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -C /var/run/wpa_supplicant -B
```

**Comment by NiLuJe** [comment] 2024-06-17 18:05
Ohkay, reproduced.

What happens is... interesting.

If you *stop* the server *while* wpa_supplicant is running, wpa_supplican tinherits it for... some fucking reason.

Going to try again while stracing wpa.

**Comment by Frenzie** [comment] 2024-06-17 18:08
> If you _stop_ the server _while_ wpa_supplicant is running, wpa_supplicant inherits its port for... some fucking reason.

Oh, indeed!

**Comment by jospalau** [comment] 2024-06-17 18:08
So, no haunted after all. Report your findings please because never saw anything like that

**Comment by Frenzie** [comment] 2024-06-17 18:11
First search result: https://stackoverflow.com/a/73951332 (you probably saw it already)

**Comment by NiLuJe** [comment] 2024-06-17 18:11
I can't reproduce it when I start the server manually, FWIW.

**Comment by NiLuJe** [comment] 2024-06-17 18:12
But, yes, some CLOEXEC shenanigans missing somewhere make sense.

**Comment by NiLuJe** [comment] 2024-06-17 18:31
> I can't reproduce it when I start the server manually, FWIW.

Besides the above catchall in LuaSocket, I'm going to double-check the existing "close all the things" that's implemented in the kobo wifi scripts, because obviously that one slipped through ;).

**Comment by NiLuJe** [comment] 2024-06-17 18:48
Welp, crap stock busboix build strikes again.

```
┌─(ROOT@goldfinch:pts/0)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(1.04:18%:20:47:64%:#)── readlink -f /proc/4509/fd/9                                                                                                                                                                                                                                                                                                 ──(Mon, Jun 17)─┘
/tmp/root/socket:[25296]
┌─(ROOT@goldfinch:pts/0)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(1.04:18%:20:47:64%:#)── /usr/bin/readlink -f /proc/4509/fd/9                                                                                                                                                                                                                                                                                        ──(Mon, Jun 17)─┘
/proc/4509/fd/9
```

**Comment by arpanghosh8453** [comment] 2024-06-18 02:14
@poire-z I was checking this with the new code, although it does not crash anymore, but the server fails to start if the wpa_supplicant is occupying the port 

```
06/17/24-22:42:14 DEBUG HttpInspector: Starting server... 
06/17/24-22:42:14 WARN  self.server tcp{master}: 0x724de228 
06/17/24-22:42:14 WARN  bind nil address already in use 
06/17/24-22:42:14 WARN  listen 1 
06/17/24-22:42:14 DEBUG SimpleTCPServer: Server listening on port 8080 
06/17/24-22:42:14 DEBUG HttpInspector: Server listening on port 8080 
```
the port status 

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8453            0.0.0.0:*               LISTEN      4358/dropbear
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      1377/nc
tcp        0      0 0.0.0.0:5001            0.0.0.0:*               LISTEN      1380/nc
tcp        2      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      4043/wpa_supplicant
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2319/HTTPServerARM
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      1388/tcpsvd
tcp        0      0 0.0.0.0:23              0.0.0.0:*               LISTEN      1390/tcpsvd
```

Any thoughts how this can be fixed?

**Comment by arpanghosh8453** [comment] 2024-06-18 03:06
@NiLuJe and @poire-z, I tested with #12045 ( replaced the 2 changed files in .adds/koreader directory ) and it seems to fix the problem with the port hijacking by wpa_supplicant. So I think that can be merged. 

Also, I think the following should be the default (given by @poire-z ) in the `simpletcpserver.lua` file because it prevents crashing ( it launches the http server in a new random port if the given port is blocked, but the system do not crash ). I think you can open a pull request and add this change too.

```
function SimpleTCPServer:start()
    self.server = socket.tcp4()
    logger.warn("self.server", self.server)
    self.server:setoption("reuseaddr", true)
    self.server:setoption("reuseport", true)
    logger.warn("bind", self.server:bind(self.host, self.port))
    logger.warn("listen", self.server:listen(5))
    self.server:settimeout(0.01) -- set timeout (10ms)
    self.server:setoption("reuseaddr", true)
    self.server:setoption("reuseport", true)
    logger.dbg("SimpleTCPServer: Server listening on port " .. self.port)
end
```

Again, thanks a lot @NiLuJe and @poire-z for working on this issue so passionately. I really appreciate it.

**Comment by arpanghosh8453** [comment] 2024-06-18 05:47
@poire-z I was wondering if it's possible to reset the autostandby and autosuspend timer using the http endpoint? I am using it to remotely flip pages, but it does not register as an event and so the system suspends after a while if I keep that setting on.

**Comment by Frenzie** [comment] 2024-06-18 05:50
If it doesn't do that it probably makes more sense to replicate this.
https://github.com/koreader/koreader/pull/11984

**Comment by arpanghosh8453** [comment] 2024-06-18 05:59
@Frenzie  Can the same be done for autosuspend and autostandby plugins? Thank you.

**Comment by poire-z** [comment] 2024-06-18 09:03
I understand no change to SimpleTCPServer:start() is needed after @NiLuJe fixes? And better wait to see if crashes can still happen after them.

I also think there should be no random port picked if we can't bind, as you don't want to reconfigure any remote script/gadget each time a new random port is picked. We just shouldn't crash, and if we can't bind, we should just stay in a "stopped" state.

> I was wondering if it's possible to reset the autostandby and autosuspend timer using the http endpoint? I am using it to remotely flip pages, but it does not register as an event and so the system suspends after a while if I keep that setting on.

There was a few points that I let in a unfinished state, bits in https://github.com/koreader/koreader/pull/10223#issuecomment-1928233249 https://github.com/koreader/koreader/pull/11457#discussion_r1514848716 https://github.com/koreader/koreader/pull/11457#issuecomment-1936280157 

Looks like we don't fake an input event when processing a request.
But even if we don't, and you have autostandby/suspend enabled, at some point, it may suspend, and then you can't accept requests, so one would need to physically touch the device to awaken it.
There's no solution to that (except Wake on Lan ? :)) but preventing autostandby/suspend when the httpinspector is started...

**Comment by Frenzie** [comment] 2024-06-18 09:19
> I understand no change to SimpleTCPServer:start() is needed after @NiLuJe fixes? And better wait to see if crashes can still happen after them.

They'd still happen if something is listening on the configured port of course; server can be nil. That's separate from us somehow triggering that condition ourselves. But the correct behavior is simply to inform, and ideally even to say which process but that might be challenging.

**Comment by arpanghosh8453** [comment] 2024-06-18 14:27
@Frenzie @poire-z @NiLuJe Your arguments makes sense. I have reverted the changes in `simpletcpserver.lua` and it's working great just with the changes from #12045. Thank you so mcuh! Is #12045 getting merged anytime soon? 2024.06?

#11984 also helped me to get rid of the autostandby and autosuspend issue ( I modified those files with the proper variable name accordingly ). I think it's worth putting those changes in the autostandby and autosuspend plugins. 

I am so happy you addressed my issue! Thanks a lot again for being patient with me and helping me out.

**Comment by NiLuJe** [comment] 2024-06-18 18:49
> If it doesn't do that it probably makes more sense to replicate this.
> #11984

That was probably not done because we used to do a real syscall to get the time; since we now pull a cached value from UIManager, that's no longer a concern, so, sure, it doesn't sound like a bad idea ;).

**Closed** 2024-06-18 19:20 UTC
Labels: bug, Plugin

**Comment by arpanghosh8453** [comment] 2024-06-19 02:57
> > If it doesn't do that it probably makes more sense to replicate this.
> > #11984
> 
> That was probably not done because we used to do a real syscall to get the time; since we now pull a cached value from UIManager, that's no longer a concern, so, sure, it doesn't sound like a bad idea ;).

@NiLuJe I have opened a pull request on this #12050
