### ISSUE TITLE
FR: PocketBook - add turn 10 pages by long pressing the Prev/Next buttons

### ISSUE THREAD

**Issue by kaznelson** [koreader/koreader#10266] opened 2023-03-29 12:39 UTC
_**Does your feature request involve difficulty completing a task? Please describe.**_
When you press the hardware **Prev** or **Next** button on PocketBook - turned 1 page. With a long press - another 1 page.

_**Describe the solution you'd like**_
Is it possible to add handling of long pressing Prev/Next - turn 10 pages?

_**Describe alternatives you've considered**_
Gesture along the top edge of the screen. Not very convenient - can be confused with swipe page turning.

_**Additional context**_
Too much pseudo-literary shit (sorry). Turning 10 pages allows you to make a digest - to understand whether to read or not. ("Skim document" - not convenient menu for this).

**Comment by offset-torque** [comment] 2023-03-29 14:39
> Gesture along the top edge of the screen. Not very convenient - can be confused with swipe page turning.

Just checking kaznelson: 
**Are you are aware that you are not limited to this gesture ?**

For example, as an equivalent to your idea, you can assign `Long press on corner` to **Turn 10 pages**.
There are other gestures that you can use for this purpose:
- Two finger tap on corner 
- Double tap 
- Two finger swipe

These are even faster because there is no long-press delay with them like a button, so you can skip quicker.

**Comment by xIUPITERx** [comment] 2023-03-29 14:44
Dupe of ##9488

**Comment by kaznelson** [comment] 2023-03-29 17:28
**offset-torque**
1. Two fingers tap/swipe on PocketBook Era works very badly.
2. Double tap - additional delays on a weird PocketBook touch screen... I turned it off wherever I found it.

**xIUPITERx**
O-ops... And from here you can take the processing of long taps?
Old port of CoolReader for PocketBook (still works on the latest firmware 6.7, albeit with cuts due to the old SDK):
https://github.com/blchinezu/pocketbook-coolreader

**Comment by offset-torque** [comment] 2023-03-29 18:27
Sorry to hear that. Specs of that device looks impressive so I didn't expect the touch screen to work that badly.
If this is not solved by hardware maybe you can try QuickMenu. Currently I have it on single swipe so it takes one swipe+one tap for any function (assuming swipe and tap works correctly on your device).

**Comment by kaznelson** [comment] 2023-03-29 19:04
The PocketBook Era's touchscreen works well, but...
When PocketBook puts the touchscreen into power saving mode and then turns it on with your gesture - this gesture will most likely be perceived by the device as a single tap. Any gesture.
For example, a swipe "with a guarantee" should not be done too quickly, but at the end of the gesture, hold your finger...

**Comment by NiLuJe** [comment] 2023-03-29 21:36
We currently process key events on *press*, not on *release*, so this isn't technically feasible at the moment.

**Comment by NiLuJe** [comment] 2023-03-29 21:36
(And I would be *vehemently* opposed to changing that fact, FWIW :D).

**Comment by kaznelson** [comment] 2023-03-30 05:12
**NiLuJe**
However, KOReader somehow reacts to long presses of the hardware page turning buttons: when Prev/Next is hold, 1 page turns, and after ~0.5 seconds - another 1 page ...

**Comment by NiLuJe** [comment] 2023-03-30 16:06
In an evdev world, that would be KEY_REPEAT, which we do indeed handle, but it goes PRESS -> REPEAT... -> RELEASE, so we still have an initial press event handled.

However, this is PB, where we have to reinvent the wheel everywhere, so I have no idea how it actually happens there ;o). For all I know, they could very well be buffering key events until release, and/or sending a completely different key code for long press or repeats, in which case something like this *could* be less painfully implemented on that platform.

**Closed** 2023-03-31 08:17 UTC
Labels: enhancement, wontfix
