### ISSUE TITLE
Android 10 file permission system doesn't allow for saving progress

### ISSUE THREAD

**Issue by rezackacz** [koreader/koreader#8789] opened 2022-02-08 11:46 UTC
* KOReader version: 2022.1
* Device: Android 10 on Nokia 5.3

#### Issue
Due to privacy updates in Android 10 which requires the app to request access and the user must set folder that he wants to the app to have access to. KOReader fails to copy, write, or just to do about anything with the filesystem. There has to be a call for the user to grant the permission (https://developer.android.com/training/data-storage#scoped-storage).
#### Steps to reproduce
Try to do just about anything with the filesystem.

**Comment by pazos** [comment] 2022-02-08 12:39
I think you're talking about sdcard. Then yup and that's not fixable. There're no permissions in Android to grant an app permissions to the underlying filesystem outside the primary partition.

Places where **is possible** to have **filesystem RW** are already requested and work fine in any android version. Please fill a bug if you find an issue with them.

Duplicate of #4872, #5784

**Closed by pazos** 2022-02-08 12:39 UTC
Labels: Android, duplicate
