### ISSUE TITLE
Errors compiling crengine under macOS 10.15 for MACOSX_DEPLOYMENT_TARGET=10.14

### ISSUE THREAD

**Issue by rfog** [koreader/koreader#6355] opened 2020-07-07 18:09 UTC
* KOReader version: Building emulator
* Device: N/A

#### Issue
Compiler error in ./kodev build under macOS 10.15

/Users/rfog/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:26: error: implicit instantiation of
      undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strbuff) + std::string(": ") + std::string(errorText);

#### Steps to reproduce

Follow steps in page https://github.com/koreader/koreader/blob/master/doc/Building.md to compile emulator for a macOS 10.15 machine.

##### `crash.log` (if applicable)
Scanning dependencies of target crengine
[ 57%] Building CXX object CMakeFiles/crengine.dir/crengine/crengine/qimagescale/qimagescale.cpp.o
[ 58%] Building CXX object CMakeFiles/crengine.dir/crengine/crengine/src/cp_stats.cpp.o
[ 59%] Building CXX object CMakeFiles/crengine.dir/crengine/crengine/src/lvstring.cpp.o
[ 60%] Building CXX object CMakeFiles/crengine.dir/crengine/crengine/src/props.cpp.o
[ 61%] Building CXX object CMakeFiles/crengine.dir/crengine/crengine/src/lstridmap.cpp.o
[ 63%] Building CXX object CMakeFiles/crengine.dir/crengine/crengine/src/rtfimp.cpp.o
[ 64%] Building CXX object CMakeFiles/crengine.dir/crengine/crengine/src/lvmemman.cpp.o
/Users/rfog/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:26: error: implicit instantiation of
      undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strbuff) + std::string(": ") + std::string(errorText);
                         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:209:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/Users/rfog/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:57: error: implicit instantiation of
      undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strbuff) + std::string(": ") + std::string(errorText);
                                                        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:209:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/Users/rfog/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:80: error: implicit instantiation of
      undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strbuff) + std::string(": ") + std::string(errorText);
                                                                               ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:209:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/Users/rfog/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:100: error: implicit instantiation of
      undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strbuff) + std::string(": ") + std::string(errorText);
                                                                                                   ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:209:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/Users/rfog/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:17: error: implicit instantiation of
      undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strbuff) + std::string(": ") + std::string(errorText);
                ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:209:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
5 errors generated.
make[4]: *** [CMakeFiles/crengine.dir/crengine/crengine/src/lvmemman.cpp.o] Error 1
make[3]: *** [CMakeFiles/crengine.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build/x86_64-apple-darwin19.5.0-debug/libs/libcrengine.dylib] Error 2
make: *** [base/build/x86_64-apple-darwin19.5.0-debug/luajit] Error 2

**Comment by poire-z** [comment] 2020-07-07 18:14
Duplicate of #6351

**Closed by poire-z** 2020-07-07 18:14 UTC
