### ISSUE TITLE
FR: Allow for % read on history view with cover mode

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5035] opened 2019-05-21 19:50 UTC
* KOReader version: 2019.05
* Device: everything

#### Issue
So I like the history view and love the cover image view, but it seems not to have the % read.  I know there is a list view that has that information but I do like looking at the covers of my book.  

FR would be to add a % read on bottom right or left of each cover image.  Please comment if you agree!

**Comment by poire-z** [comment] 2021-02-10 00:17
Duplicate of #4858.

**Closed by poire-z** 2021-02-10 00:17 UTC
Labels: enhancement
