### ISSUE TITLE
Blank screen after waking up on new Pocketbook firmware 6.5

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#8187] opened 2021-09-07 08:40 UTC
* KOReader version: v2021.08-42 & 45
* Device: Pocketbook InkPad 3

#### Issue
Yesterday, I installed Pocketbook firmware 6.5.339, which is a beta version. It seems like something has changed in how the page refresh is done. The following issue occurs now: When I wake up the device with KOReader open, the screen flashes, the text is shown for a second and then the screen turns blank. The same happens when I open the PB task manager in KOReader and then return to KOReader. I need to tap the screen to show the text again, but this is also registered as a page turn.
Edit: A similar behaviour used to occur when KOReader still had a screensaver built in, with the device waking up to a blank screen and only showing the text after a tap.

The blank page does not come up on other devices running FW 5.x (Touch Lux 3) or 6.4 (Touch HD 3). The desired behaviour is that the screen flashes after waking up the device or showing the task manager, without a blank page appearing.

[crash.log](https://github.com/koreader/koreader/files/7120146/crash.log)

**Comment by LucyOne** [comment] 2021-09-25 07:13
Would it be possible to build in an extra screen refresh after those instances of the device waking up or returning to KOReader? The Pocketbook system seems to do a screen refresh to prevent ghosting, which then causes the blank screen in KOReader.

**Comment by ReaLx3m** [comment] 2021-12-10 21:35
Same issue present also on Inkpad 3 Pro for me, with koreader 2021.11

**Comment by RTyp3r** [comment] 2021-12-13 13:53
Same issue for me after updating to latest firmware v6.5.765 for my Pocketbok Inkpad 3. Using KOReader 2021.11.

**Comment by mh67** [comment] 2021-12-30 10:36
Exactly the same behaviour after update to the newest firmware on PocketBook 740 InkPad 3.
Annoying bug, because this reader without KOReader application is almost unusable (wrong fonts contrast etc....). :-(
Tried several workarounds, but without success - for example I tried to change the _needsScreenRefreshAfterResume_ in the _frontend/device/pocketbook/device.lua_ 
`local PocketBook = Generic:new{
    model = "PocketBook",
    isPocketBook = yes,
    hasOTAUpdates = yes,
    hasWifiToggle = yes,
    isTouchDevice = yes,
    hasKeys = yes,
    hasFrontlight = yes,
    hasSystemFonts = yes,
    canSuspend = no,
    canReboot = yes,
    canPowerOff = yes,
    needsScreenRefreshAfterResume = no,`

**Comment by hudowski** [comment] 2021-12-30 14:43
The same issue using the newest 
6.5.1379
firmware. 
Could anybody fix that, please? It is really annoying.

**Comment by hudowski** [comment] 2022-01-05 09:42
This issue is 4 months old and there are no volunteers to fix that. I am a Java dev with no experience with C but maybe I could help you somehow in that?

**Comment by Frenzie** [comment] 2022-01-05 09:50
There is the apparently completely unused needsScreenRefreshAfterResume:

https://github.com/koreader/koreader/blob/ec280f874f0cfce660bdb4d396589939503d3c8b/frontend/device/pocketbook/device.lua#L35

You could always try setting that to yes as a dumb workaround.

**Comment by hudowski** [comment] 2022-01-05 10:56
> There is the apparently completely unused needsScreenRefreshAfterResume:
> 
> https://github.com/koreader/koreader/blob/ec280f874f0cfce660bdb4d396589939503d3c8b/frontend/device/pocketbook/device.lua#L35
> 
> You could always try setting that to yes as a dumb workaround.

mh67 user said above that he/she tested it and it does not work.

**Comment by ReaLx3m** [comment] 2022-01-05 10:59
> There is the apparently completely unused needsScreenRefreshAfterResume:
> 
> https://github.com/koreader/koreader/blob/ec280f874f0cfce660bdb4d396589939503d3c8b/frontend/device/pocketbook/device.lua#L35
> 
> You could always try setting that to yes as a dumb workaround.

Can also confirm that it doesnt work. 
Even using a gesture to manually refresh the page still doesnt display anything on mine(tried with cbz). Though after manual refresh only the status bar becomes visible.
Only way to get display back is to go page forward or back.

**Comment by hudowski** [comment] 2022-01-05 11:01
> Only way to get display back is to go page forward or back.

The same for me.

**Comment by rjd22** [comment] 2022-01-27 15:16
You can find tests files that you can unpack right over the files on the pocketbook here: https://github.com/koreader/koreader/pull/8727#issuecomment-1023019728

**Comment by ReaLx3m** [comment] 2022-01-27 18:35
> @LucyOne, @ReaLx3m, @RTyp3r, @mh67, @hudowski, @ichnilatis-gr it seems that this PR: #8727, solves the issue. At least on my InkPad3. And they are requesting testers...

Thanks for pinging, will try it out and share my results in the thread.

**Comment by Danar435** [comment] 2022-01-27 18:49
My PB would always show a white screen after sleep, which could be fixed with page turns. I thought it was a quirk with KOReader at the time, but I can confirm that the new PR fixed it.

**Comment by ReaLx3m** [comment] 2022-01-27 18:59
Yup, solved the issue on Inkpad 3 Pro for me. And page turns(tried with cbz comic book) are now faster as an added bonus.

**Comment by mh67** [comment] 2022-01-27 19:41
Nice to see info about existing fix of this bug. My InkPad 3 will be usable again :-). Thanks!

**Closed** 2022-01-28 15:17 UTC
Labels: PocketBook, firmware, help-wanted

**Comment by ichnilatis-gr** [comment] 2022-01-28 15:23
> @LucyOne, @ReaLx3m, @RTyp3r, @mh67, @hudowski, @ichnilatis-gr it seems that this PR: #8727, solves the issue. At least on my InkPad3. And they are requesting testers...

The problem has been fixed for me too (PB 628). Thank you!

**Comment by Serjls** [comment] 2022-01-29 04:11
Thank you, PB740 - sleep mode has started working, but night mode has stopped working.

**Comment by ichnilatis-gr** [comment] 2022-01-29 08:49
In fact, the changes of the file "koreader-pocketbook-inkview-rendering" fixes some problems but creates others:
Solves:
- No blank screen after waking up
- There is no blank screen during sleep mode, but it fades out as the Pocketbook system does.
- Immediate keyboard keys response

New problems:
- Night mode applies to images only
- Strange flashes when selecting items from the menu or pressing buttons. E.g. when you press the "close" button in a window, the window closes but the button remains blinking for a while.

If new problems could be solved, it would be perfect.
Thanks!

**Comment by hombretranquilo** [comment] 2022-01-29 10:41
@ichnilatis-gr night mode is working correctly again by changing line 44 of device.lua from canHWInvert = yes to canHWInvert = no.  At least on my PB740.

I am not a developer so maybe this is not the best way to solve the problem, but maybe this will help @rjd22 or other experienced developers to find the most convenient solution. 

Maybe the isNightModeChallenged option is also relevant to the problem, I don't know.

**Comment by Frenzie** [comment] 2022-01-29 11:29
> I am not a developer, so this may not be the best way to fix the problem

Doing it in hardware is much more efficient, so it should be faster, impossible to say how much exactly,[1] and you might conceivably notice decreased battery life.

[1] Could be 5-10 ms extra when lucky, could be 50-100 ms extra when not. Depends mainly on the speed of the CPU. If you don't actively notice I suppose it doesn't matter much regardless.

**Comment by hombretranquilo** [comment] 2022-01-29 11:38
> Doing it in hardware is much more efficient, so it should be faster, impossible to say how much exactly,[1] and you might conceivably notice decreased battery life.

that's not good news... if someone proposes a solution that preserves canHWInvert = yes, I can try it out.

**Comment by ichnilatis-gr** [comment] 2022-01-29 13:01
So, should we change line 44 or not?

**Comment by mh67** [comment] 2022-01-29 14:42
Hmmm... Seems this "fix" is a side effect of another issue only. At least on my InkPad 3...
But better than nothing, of course.

**Comment by Frenzie** [comment] 2022-01-29 14:44
It's not like `no` is in any way problematic, but in this case I would first look into a follow-up to https://github.com/koreader/koreader-base/pull/1451

**Comment by ichnilatis-gr** [comment] 2022-01-29 14:53
So I go back to the latest nightly version (without this change) and expect something better (i.e. if it is possible for the problems that appear to be fixed; see [above](https://github.com/koreader/koreader/issues/8187#issuecomment-1024869094))...

**Comment by ReaLx3m** [comment] 2022-01-29 16:01
Not an issue for me as i dont use it, but can confirm that with inkview Night Mode also doesnt work on Inkpad 3 Pro(PB740-2) on 6.5.1381 firmware.

**Comment by rjd22** [comment] 2022-01-29 17:15
I will be able to look into this in a week or so. Most likely we need to use a inkview function to invert the screen or need to disable hardware native inversion completely since inkview has less integration points for specific hardware calls.

**Comment by mh67** [comment] 2022-01-29 18:33
Tested a little bit more. Because I do not use the night-mode, I can say, I am satisfied - no serious problems. For me it is possible to use with this fix.

**Comment by LucyOne** [comment] 2022-01-29 18:40
I use nightmode almost all the time, a fix is definitely necessary for me. It's no good to replace one bug with another.

**Comment by rjd22** [comment] 2022-01-29 19:31
> In fact, the changes of the file "koreader-pocketbook-inkview-rendering" fixes some problems but creates others: Solves:
> 
>     * No blank screen after waking up
> 
>     * There is no blank screen during sleep mode, but it fades out as the Pocketbook system does.
> 
>     * Immediate keyboard keys response
> 
> 
> New problems:
> 
>     * Night mode applies to images only
> 
>     * Strange flashes when selecting items from the menu or pressing buttons. E.g. when you press the "close" button in a window, the window closes but the button remains blinking for a while.
> 
> 
> If new problems could be solved, it would be perfect. Thanks!

Would it be possible for you to make 2 separate tickets of these issues with examples and maybe a video for me? I will take a look next week.

**Comment by Frenzie** [comment] 2022-01-29 20:04
@rjd22 Night mode applies to images only is because we render them in reverse in night mode so they come out right. It's not an issue.

**Comment by rjd22** [comment] 2022-01-29 23:20
@Frenzie with the rendering trough inview the interface and books do not invert anymore when night mode is enabled. 

I never used it so I'm not sure this is correct behavior. But I would expect night mode to invert the interface and books too on pocketbooks.

**Comment by poire-z** [comment] 2022-01-30 00:21
He means "Night mode applies to images only" is not *the* issue: we invert them so once nightmode is appplied, they are inverted-inverted, so they look normal while the rest is nightmode'd. This is the expected behaviour.
Your only issue is that nightmode doesn't work yet - once it works, the image will be just as expected.
The solution for now might be just to set `canHWInvert=no`.

**Comment by NiLuJe** [comment] 2022-01-30 01:59
Yup, just flipping the HW inversion cap should do the trick (it might actually *already* be disabled on some PBs).

**Comment by rjd22** [comment] 2022-01-30 08:30
@NiLuJe Can you point me to the code of the HW rota cap? In essence the FullUpdate funtion acts as a full screen refresh so we might be able to make it work.

**Comment by ichnilatis-gr** [comment] 2022-01-30 12:20
> Would it be possible for you to make 2 separate tickets of these issues with examples and maybe a video for me? I will take a look next week.

Unfortunately I don't have the means to get a video of this problem.
I leave it to someone who will try to solve these problems to create the relevant issues with the appropriate titles.
I can only give a description of the "strange flashes" with an another example: When I tap on an option of the upper menu it goes to the next level of the menu but the text of the option I made stays briefly highlighted above it.

I will try to find a way to give you a video...

**Comment by poire-z** [comment] 2022-01-30 12:51
> As for the strange flashes. This might be a way of inkview dealing with ghosting. I might need a video to see what is happening since I don't notice this behavior on my device with the new code.

@rjd22 : be sure you have `Screen > EInk > [x] Flash buttons and menu items` enabled, to be able to witness these flashes and possible issues.
I think I witnessed what @ichnilatis-gr see when developping recently, https://github.com/koreader/koreader/pull/8629#issuecomment-1007974048 - but in your case, it's not a new dev issue. Flashing has some specific code paths (like frontent/ui/widget/button.lua) when "flash_ui" enabled, and they do some specific refreshes or wait/sleep - you might need to investigate how this works (I never dared to understand all this :) I let that to @NiLuJe :) so you can tweak the specific framebuffer other methods involved (like, from memory: yieldToEPDC, waitForVSync)

**Comment by NiLuJe** [comment] 2022-01-30 17:49
None of those will work if we don't have an actual reliable wait_for method, though ;).

**Comment by frank-w** [comment] 2022-05-29 08:51
Hi,

Have same issue and it looks like not related to standby.

Pocketbook inkpad color
Software u741.6.5.1684 (latest based on update function)
Koreader 2021.02-54

I get blank screen after waking up/bootup and if i open an previously opened book from startpage

**Comment by rjd22** [comment] 2022-05-29 08:58
@frank-w you're using a very old koreader. Please update to the latest version and you will also get free color support included ;)

**Comment by frank-w** [comment] 2022-05-29 09:24
Can i update koreader independ from pb firmware? How?

**Comment by rjd22** [comment] 2022-05-29 09:30
You can find how to install koreader on PocketBook on the following guide.

It's just plugging it into your computer and replacing some files:
https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices

**Comment by frank-w** [comment] 2022-05-29 12:07
thanks, thought koreader is the internal one and should be updated with firmware,

but yes, some time ago i installed this and coolreader app...wasn't aware that i had changed the default reader

got new version installed, thanks for it
