### ISSUE TITLE
calibre catalog prevents exit

### ISSUE THREAD

**Issue by bunglegrind** [koreader/koreader#4225] opened 2018-09-13 13:37 UTC
* KOReader version: v.2015.11-1800-g0924b57_2018-07-29
* Device: Kobo Aura One with KSM 0.9

#### Steps to reproduce

Preliminary step: Import tagged ebooks via calibre (just a couple);

1. In file manager go to search menu->find a book in calibre catalog->browse tags
2. Select one of the tags you have imported in koreader and open one of the related books
3. Open the reader menu->main menu->exit->exit

It does not exit, but instead koreader closes the book and the browse tags panel appears again.
Then, if you close the browse tag panel (ie, press the X on the top right) koreader exits to KSM.

**Comment by NiLuJe** [comment] 2018-09-13 13:53
(Leaky widget that doesn't close properly?)

**Comment by Frenzie** [comment] 2019-03-12 08:13
@bunglegrind Could you perhaps add some more info to the issue about how to set up this calibre catalog business (in calibre as well as KOReader)?

**Comment by bunglegrind** [comment] 2019-03-12 10:22
OK. I'm currently using Calibre 64-bit on Win7 Ultimate. 

Since I'm using KSM and not nickel, I've disabled the KoboTouch driver (see https://www.mobileread.com/forums/showthread.php?t=279299 ) and I'm connecting manually the device by clicking "connect/share->connect to folder" and then selecting the KOReader folder.

In my calibre library I've organized my ebooks (every kind of ebooks) with tags and they are automatically imported in KOReader when I send to device the ebooks. However, I can also force tags import by clicking "update cached metadata on device" on the device menu. 

In KOReader there's no particular setting. Just follow the steps I've described in the first post. 

Let me know if you need more info. ;)

**Comment by Frenzie** [comment] 2019-03-12 10:37
Ah, connect to folder under device/share.

Following your instructions calibre seems to have written a .metadata.calibre file, but the plugin says /metadata.calibre not found. This seems to be at least partially related to certain presumably Kobo-specific assumptions:

https://github.com/koreader/koreader/blob/85ac59ae0074c321861d57ccc1c3e52518e1d60e/frontend/apps/filemanager/filemanagersearch.lua#L78-L83

Setting that to something relevant in persistent.defaults.lua does the trick.

But if I then follow your steps regarding browse tags, the program does seem to exit properly. Is it possible that the main problem was fixed by some exit-related fixes? I do see it pop up because it was behind the reader, mind you, it's just not preventing exit.

Either way, the widget should be closed when opening a document. I'll take care of that.

**Comment by Frenzie** [comment] 2019-03-12 10:43
@bunglegrind I think this should about do it. Could you double check if it was still an issue and if so, if this fixes it?

```diff
diff --git a/frontend/apps/filemanager/filemanagersearch.lua b/frontend/apps/filemanager/filemanagersearch.lua
index b9451207..8f45771f 100644
--- a/frontend/apps/filemanager/filemanagersearch.lua
+++ b/frontend/apps/filemanager/filemanagersearch.lua
@@ -556,6 +556,7 @@ function Search:showresults()
                text = self.data[i][self.authors] .. ": " .. self.data[i][self.title],
                callback = function()
                    ReaderUI:showReader(book)
+                   UIManager:close(menu_container)
                end
             })
             i = i + 1
@@ -662,6 +663,7 @@ function Search:browse(option, run, chosen)
                    path = self.data[i][self.path],
                    callback = function()
                        ReaderUI:showReader(book)
+                       UIManager:close(menu_container)
                    end
                 })
             end
```

**Comment by bunglegrind** [comment] 2019-03-12 12:07
> Following your instructions calibre seems to have written a .metadata.calibre file, but the plugin says /metadata.calibre not found. This seems to be at least partially related to certain presumably Kobo-specific assumptions:

Ops. I completely removed (since I don't install KOReader everyday...) that I change SEARCH_LIBRARY_PATH  and SEARCH_LIBRARY_PATH2 to to "/mnt/onboard"
in defaults.lua

Sorry...

**Comment by bunglegrind** [comment] 2019-03-12 13:17
> 
> 
> @bunglegrind I think this should about do it. Could you double check if it was still an issue and if so, if this fixes it?
> 
> ```diff
> diff --git a/frontend/apps/filemanager/filemanagersearch.lua b/frontend/apps/filemanager/filemanagersearch.lua
> index b9451207..8f45771f 100644
> --- a/frontend/apps/filemanager/filemanagersearch.lua
> +++ b/frontend/apps/filemanager/filemanagersearch.lua
> @@ -556,6 +556,7 @@ function Search:showresults()
>                 text = self.data[i][self.authors] .. ": " .. self.data[i][self.title],
>                 callback = function()
>                     ReaderUI:showReader(book)
> +                   UIManager:close(menu_container)
>                 end
>              })
>              i = i + 1
> @@ -662,6 +663,7 @@ function Search:browse(option, run, chosen)
>                     path = self.data[i][self.path],
>                     callback = function()
>                         ReaderUI:showReader(book)
> +                       UIManager:close(menu_container)
>                     end
>                  })
>              end
> ```

I've installed latest version "Marsdiep" and the issue is still present. Then I've changed filemanagersearch.lua...and the issue is still present :(

**Comment by Frenzie** [comment] 2019-03-12 14:17
It's very strange that I'm not seeing it. All you're doing is this, right?

Find a book in calibre catalog → Browse tags → Click some tag → Click some book

**Comment by bunglegrind** [comment] 2019-03-12 20:41
> It's very strange that I'm not seeing it. All you're doing is this, right?
> 
> Find a book in calibre catalog → Browse tags → Click some tag → Click some book
...and then top-menu->exit->exit

and the widget is still there...

Moreover, I can see the calibre widget after I clicked on the ebook in the background. It's not closing at all

**Comment by Frenzie** [comment] 2019-03-12 20:54
> Moreover, I can see the calibre widget after I clicked on the ebook in the background. It's not closing at all

Yes, that's what I said I was seeing. :-) It was still open but it closed anyway.

Apparently what we've got here is a difference in closing behavior between the quit event generated by the SDL window and that from the KOReader menu.

This one closes everything:
https://github.com/koreader/koreader/blob/14c705f11bb5ca01ee07cadad1ec0a1c6a3cf2c9/frontend/device/input.lua#L354-L378

Whereas in this one doesn't:
https://github.com/koreader/koreader/blob/14c705f11bb5ca01ee07cadad1ec0a1c6a3cf2c9/frontend/apps/reader/modules/readermenu.lua#L248-L280

**Comment by bunglegrind** [comment] 2019-03-13 13:15
Ok, should I do any other tests?

**Comment by Frenzie** [comment] 2019-03-13 13:35
No, I now know how to reproduce it. But I need more time to figure out if there's something off about the exit function or not.

(Properly speaking I the widget should be fully closed when opening a book, but that `FileManager.instance:onClose()` might nevertheless not be the right call there.)

**Closed** 2019-04-28 18:10 UTC
Labels: bug

**Comment by bunglegrind** [comment] 2019-04-30 20:14
Great! It works now, thanks!
