### ISSUE TITLE
I can't build it on Fedora.

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#3116] opened 2017-08-21 11:35 UTC
```
[ 12%] Performing configure step for 'djvulibre'
configure: error: in `/home/zaoqi/koreader/base/thirdparty/djvulibre/build/x86_64-redhat-linux/djvulibre-prefix/src/djvulibre':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by Frenzie** [comment] 2017-08-21 11:44
Looks like a duplicate of #3069 (see https://github.com/koreader/koreader/issues/3069#issuecomment-321769322 in particular). I don't really have time to look into bumping MuPDF and no one's made a PR with the -Wnoerror flag in base yet.

**Comment by Frenzie** [comment] 2017-08-23 09:46
I'll close this as a duplicate, especially because the issue itself is as good as solved.

**Closed** 2017-08-23 10:06 UTC

**Comment by silberzwiebel** [comment] 2017-08-23 11:10
Oh, actually, this one has another cause that @Frenzie found in https://github.com/koreader/koreader/issues/3069#issuecomment-321610178
Solution: `sudo dnf install libstdc++-static` and re-try.
