### ISSUE TITLE
Couldn't install koreader last version 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#6698] opened 2020-09-23 11:14 UTC
The previous version (August), I couldn't install the koreader app downloaded straight from github.com, found it on fdroid installed and worked perfectly. 
Now the same problem with the (September) version couldn't install the apk downloaded straight from github.com but it's not updated yet on fdroid.. 
Ps. Play protect is TURNED OFF
EDIT: android 5.1.1, Samsung T-285
![Screenshot_2020-09-23-14-06-50](https://user-images.githubusercontent.com/70109540/94005164-8f5f3000-fda6-11ea-9da1-4f9daca46546.png)

**Comment by Frenzie** [comment] 2020-09-23 12:05
You can't install the one over the other. You have to stick to the same one or uninstall before switching. Unfortunately the Android error message is extremely unhelpful, but it's because the GH version is signed by us and the F-Droid version by F-Droid.

**Comment by Galunid** [comment] 2020-09-23 20:49
Duplicate of #6066

**Closed by Galunid** 2020-09-23 20:49 UTC
Labels: Android, duplicate, question

**Comment by Zeyadas** [comment] 2020-09-25 08:52
I'm sorry but am not a programmer and I don't know what "GH version" is.. I'll try to uninstall the old version and reinstall the newer on..

**Comment by Frenzie** [comment] 2020-09-25 10:37
GitHub! ;-)

**Comment by Zeyadas** [comment] 2020-09-25 10:54
Thanks, it worked,
Two more things. 
First it's the brightness toggle I noticed it's not in (e-ink) style - I don't know how to describe it but it's not the same. 
![Screenshot_2020-09-25-13-48-26](https://user-images.githubusercontent.com/70109540/94258779-10006680-ff36-11ea-871e-f8f8e6f3596e.png)
The second is I can't login to Evernote, the same old message. 
![Screenshot_2020-09-25-13-48-17](https://user-images.githubusercontent.com/70109540/94259119-9f0d7e80-ff36-11ea-8411-905b6e4de425.png)

(ignore the Arabic text)

**Comment by NiLuJe** [comment] 2020-09-25 12:07
First one is by design, it's the native widget.

Second one is probably the same old #6087

**Comment by Zeyadas** [comment] 2020-09-25 14:29
Thank you all for responding, the (widget) is working just fine, but I mentioned it to make the app (perfect).

**Comment by pazos** [comment] 2020-09-25 16:49
> Thank you all for responding, the (widget) is working just fine, but I mentioned it to make the app (perfect).

The ultimate look of the frontlight dialog will depend on SystemUI framework, so it will look a bit more like e-ink on a eink device with a customized framework, and will look like in the screenshot for most phones and tablets.

**Comment by Zeyadas** [comment] 2020-09-29 09:02
That was so helpful, thank you all.
It's a great app, used so many apps for epub files (Arabic documents) yours is the best.
Thank you again.
