### ISSUE TITLE
Build failing on Linux

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2049] opened 2016-05-29 16:31 UTC
I am on Debian Testing

thanks

/media/DRIVEA/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu/libzmq-prefix/src/libzmq/src/curve_server.cpp: In constructor ‘zmq::curve_server_t::curve_server_t(zmq::session_base_t*, const string&, const zmq::options_t&)’:
/media/DRIVEA/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu/libzmq-prefix/src/libzmq/src/curve_server.cpp:53:18: error: ignoring return value of ‘int sodium_init()’, declared with attribute warn_unused_result [-Werror=unused-result]
     sodium_init();
                  ^
  CXX      libzmq_la-io_object.lo
  CXX      libzmq_la-io_thread.lo
cc1plus: all warnings being treated as errors
Makefile:816: recipe for target 'libzmq_la-curve_client.lo' failed
make[7]: *** [libzmq_la-curve_client.lo] Error 1
make[7]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
Makefile:823: recipe for target 'libzmq_la-curve_server.lo' failed
make[7]: *** [libzmq_la-curve_server.lo] Error 1
make[7]: Leaving directory '/media/DRIVEA/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu/libzmq-prefix/src/libzmq-build/src'
Makefile:601: recipe for target 'all' failed
make[6]: *** [all] Error 2
make[6]: Leaving directory '/media/DRIVEA/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu/libzmq-prefix/src/libzmq-build/src'
Makefile:425: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/media/DRIVEA/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu/libzmq-prefix/src/libzmq-build'
CMakeFiles/libzmq.dir/build.make:115: recipe for target 'libzmq-prefix/src/libzmq-stamp/libzmq-build' failed
make[4]: *** [libzmq-prefix/src/libzmq-stamp/libzmq-build] Error 2
make[4]: Leaving directory '/media/DRIVEA/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libzmq.dir/all' failed
make[3]: *** [CMakeFiles/libzmq.dir/all] Error 2
make[3]: Leaving directory '/media/DRIVEA/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu'
Makefile:83: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/media/DRIVEA/BUILD/koreader/base/thirdparty/libzmq/build/x86_64-linux-gnu'
Makefile.third:395: recipe for target 'build/x86_64-linux-gnu/libs/libzmq.so.4' failed
make[1]: *** [build/x86_64-linux-gnu/libs/libzmq.so.4] Error 2
make[1]: Leaving directory '/media/DRIVEA/BUILD/koreader/base'
Makefile:91: recipe for target 'base/build/x86_64-linux-gnu/luajit' failed
make: *** [base/build/x86_64-linux-gnu/luajit] Error 2
Failed to build emulator!

**Comment by houqp** [comment] 2016-05-29 18:06
duplicate of https://github.com/koreader/koreader/issues/1788

**Closed by houqp** 2016-05-29 18:06 UTC
