### ISSUE TITLE
Progress Sync server dead again -is there an alternative?

### ISSUE THREAD

**Issue by dowiew** [koreader/koreader#2889] opened 2017-05-13 15:20 UTC
* KOReader version: 20170430
* Device: Android, Kindle

#### Issue
As reported in [#2877](https://github.com/koreader/koreader/issues/2877) the built-in sync server at https://vislab.bjmu.edu.cn:7200 has been dead for several days. It went back online for 2 days eventually but stopped working again. 
I tried to connect via a few proxy servers in various countries with no luck - not responding to any protocol, any port.
I don't have any linux server available so I can not install my own docker sync serever. It's annoying.
Am I the only user affected/interested? 
Is the Chinese server the only one available? Anybody has a custom server and can share?
#### Steps to reproduce
Just try to sync the reading progress.

**Comment by Frenzie** [comment] 2017-05-13 15:35
Is https://hzj-jie-ubuntu.westus.cloudapp.azure.com:7200 also down then?

**Comment by dowiew** [comment] 2017-05-13 22:31
Correct. I've been trying that one and the one mentioned in [#2178](https://github.com/koreader/koreader/issues/2178) - sync.koreader.rocks (it's actually the same, an alias) for 2 weeks. It's down.
I believe it's quite easy to determine - the sync url:7200 responds in a webbrowser (at least id did when worked). Now I'm just unable to connect.

**Comment by Hzj-jie** [comment] 2017-05-16 16:39
The sync server has died for a while, but I have not had time to take a look. :(
@HouQP, I recall we have discussed this before, do you mean that the sync server on the machine was deployed by me? If so I will restart it.

**Comment by dowiew** [comment] 2017-06-05 18:59
The sync server is down again. The 3rd day now. 
@Hzj-jie, please restart if it's your server...

**Comment by houqp** [comment] 2017-06-06 08:42
@dowiew can you give `https://sync.koreader.rocks:443` a try?

**Comment by dowiew** [comment] 2017-06-06 12:06
@houqp: it responds in a web browser but in KOReader I am unable to register an account ("Unknown server error"). The original server account login fails (the same error).

**Comment by dowiew** [comment] 2017-07-03 16:09
The built-in reading progress sync server just doesn't work. Has been alive only a few days for the last month. Dead for several days now.
The sync.koreader.rocks server seems to respond properly in a web browser but I'm unable to register/login in KOReader. @Hzj-jie or @houqp: is this your server? How can it be used?

**Comment by flxfxp** [comment] 2017-07-06 19:31
Got the same issue; I can reach the API via browser, but unknown error in KOReader

**Comment by Frenzie** [comment] 2017-08-23 10:58
I don't know how to fix it (without doing research), but this is the error I got when testing.
```
POST https://sync.koreader.rocks:443/users/create
sslv3 alert handshake failure
# 08/23/17-12:57:03  false {
    ["response"] = {
        ["request"] = {
            ["sink"] = function: 0x411b7a28,
            ["redirect"] = false,
            ["protocol"] = "tlsv1",
            ["mode"] = "client",
            ["headers"] = {
                ["accept"] = "application/vnd.koreader.v1+json",
                ["content-length"] = 68,
                ["content-type"] = "application/json",
                ["user-agent"] = "lua-Spore v0.3.1"
            },
            ["method"] = "POST",
            ["source"] = function: 0x411b7990,
            ["create"] = function: 0x411b7fd8,
            ["url"] = "https://sync.koreader.rocks:443/users/create",
            ["options"] = "all",
            ["verify"] = "none",
            ["env"] = {
                ["SERVER_PORT"] = "443",
                ["SERVER_NAME"] = "sync.koreader.rocks",
                ["HTTP_USER_AGENT"] = "lua-Spore v0.3.1",
                ["spore"] = {
                    ["params"] = {
                        ["password"] = "ae2b1fca515949e5d54fb22b8ed95575",
                        ["username"] = "testing"
                    },
                    ["caller"] = "register",
                    ["payload"] = "{\"password\":\"ae2b1fca515949e5d54fb22b8ed95575\",\"username\":\"testing\"}",
                    ["method"] = {
                        ["path"] = "/users/create",
                        ["method"] = "POST",
                        ["base_url"] = "https://sync.koreader.rocks:443",
                        ["expected_status"] = {
                            [1] = 201,
                            [2] = 402
                        },
                        ["required_params"] = {
                            [1] = "username",
                            [2] = "password"
                        },
                        ["payload"] = {
                            [1] = "username",
                            [2] = "password"
                        }
                    },
                    ["errors"] = ,
                    ["expected"] = {
                        [1] = 201,
                        [2] = 402
                    },
                    ["url_scheme"] = "https"
                },
                ["sporex"] = {},
                ["REQUEST_URI"] = "",
                ["PATH_INFO"] = "/users/create",
                ["REQUEST_METHOD"] = "POST"
            }
        },
        ["body"] = "",
        ["status"] = "sslv3 alert handshake failure"
    },
    ["reason"] = "sslv3 alert handshake failure not expected"
}
```

**Comment by Frenzie** [comment] 2017-08-23 11:07
Duplicate of #2178. Closing in favor of that one.

**Closed by Frenzie** 2017-08-23 11:07 UTC
Labels: bug
