### ISSUE TITLE
after base update，CJK font behave abnormal

### ISSUE THREAD

**Issue by frankyifei** [koreader/koreader#1538] opened 2015-05-30 10:14 UTC
Device: ubuntu emulater and Kindle PW1
1. 
Always shows a error message “# cannot register font <./fonts/droid/DroidSansFallbackFull.ttf>” on emulater with -d
2.
If in EPUB  I define an external Chinese font in its css，it everytime shows ??????.  I have to turn off embedded css and it will fall back to Droidsansfallback. It will never use the font defined in css, although I put them in koreader's font dir. I can only use these fonts when I turn off embedded css and choose them from menu. 
3.
Wether I define external font in CSS, choosing an non-Chinese font like freesans or noto sans will result in every chinese word shown as ??????.(with Embedded CSS option On). Previous version will fallback to Droidsansfallback. 
4.
change font or change font-weight in menu sometimes will hang up the program and in gnome-system-monitor it uses 100% CPU(actual 50% as I have dual core CPU). Actually it hangs up on kindle more frequently when I change settings related to fonts. 

I can not define font-face in css to use external font, but embedded fonts in Epub files work well.  In older version, I still can not define external font but it will fall back to droidsansfallback and keep all the styles. Now I have to turn off the embedded CSS. 
Plus: why cant I define external font in CSS ? any idea?

**Comment by NiLuJe** [comment] 2015-05-30 16:42
1. You might have some old stuff laying around/a broken/mismatched WD. Try to checkout everything from scratch again.

2. Caused by 1.

3. Caused by 1.

**Comment by frankyifei** [comment] 2015-05-31 12:16
I checked crengine, it only process url of embedded fonts. that's the reason of 2,3

**Comment by chrox** [comment] 2015-05-31 13:09
@frankyifei Our fork of crengine should be able to register external fonts definded in CSS, see this [patch](https://github.com/koreader/crengine/commit/3059d59ec9b165d63607826c489e6a4cce01ccb5).

**Comment by frankyifei** [comment] 2015-05-31 13:56
This does not work, even when I put  the font wqy-zenhei.ttc in koreader's fonts folder. I put a printf() under registerFont() in base/cre.cpp , it shows fontman has registered wqy-zenhei.tcc successfully. 
I also get the name of the font using to render the node by  font->getTypeFace().c_str() in lvrend.cpp renderFinalBlock(), it  shows Noto Sans. But style->get().font_name is correct as I define a font-face "hei".
this is how I define a font-face, I dont konw if it is the reason. It works well with calibre.
@font-face {
  src: local("文泉驿正黑"), local("Wenquanyi Zen Hei"),local("DroidSansFallBack");
  font-family: hei;
  }

and I tried this also did not work

@font-face {
  src: local("文泉驿正黑"), local("Wenquanyi Zen Hei"),local("DroidSansFallBack");
  font-family: hei;
  }

**Comment by chrox** [comment] 2015-05-31 22:31
Currently it does not support the "local" scheme but only "url" scheme with font file path(relative or absolute). So it may look like this:
```
@font-face {
src: url(res:///mnt/us/fonts/hei.ttf),
url(res://../../fonts/zw.ttf),
url(res://~/fonts/zw.ttf);
font-family: hei;
}
```

**Comment by frankyifei** [comment] 2015-06-05 03:02
I'm working on a patch to enable crengine to support "local" in CSS file. It is working now.
now it support this,
```
@font-face {
src: local("FBTShuSong-Medium"),local("Droid Sans FallBack");
font-family: song;
}
```

**Comment by chrox** [comment] 2015-06-05 13:09
Looks cool. I'll test it tomorrow and could you send a pull request to koreader/crengine?

**Comment by chrox** [comment] 2015-09-18 11:21
Already fixed in master branch. Close this now.

**Closed by chrox** 2015-09-18 11:21 UTC
