### ISSUE TITLE
Mhtml 

### ISSUE THREAD

**Issue by SVB-commits** [koreader/koreader#10608] opened 2023-06-24 09:27 UTC
Not showing mhtml files 
![Screenshot_20230624-145425](https://github.com/koreader/koreader/assets/82572267/9e3971fc-8833-4a8f-8c25-7d52d8d17a4b)

**Comment by Frenzie** [comment] 2023-06-24 09:35
Duplicate of #5921.

**Closed by Frenzie** 2023-06-24 09:35 UTC
Labels: enhancement
