### ISSUE TITLE
End of document action: Return to file browser

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3985] opened 2018-05-27 18:02 UTC
I´ve noticed that "Return to file browser" means: return to last place you were before you started the Reader.
For example: if you are in Folder A and then open a book (placed in Folder B) from History, and then finish the book, you end up in Folder A.

An alternative definition could be to (always) return to the place where the book is. Makes more sense for those who delete finished books. And for those who want to read next book in a series.

**Comment by cramoisi** [comment] 2018-05-28 05:30
@gerhaher : i did the test and I can't reproduce. I got a book A in "best of"; another B in "to read". opened B from "to read" directory, close it : return to the "to read" directory". After that, I opened from the history the book A which I know is in the "best of" directory. I skimmed it to the end, at the last page, I ask "return to the file browser", and I found myself in the "best of" directory, which is the book is...

**Comment by gerhaher** [comment] 2018-05-28 07:05
You are right.

My version was 1715. I updated to 1724 and now it seems to work that way.

Thanks!

The thread can be closed :)

**Closed** 2018-05-28 07:07 UTC
