### ISSUE TITLE
In scroll mode, the minibar hides the very last line of text

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#4650] opened 2019-02-24 08:29 UTC
* KOReader version: v2019-02-43-g1632acc_2019-02-16
* Device: Kobo Aura One

#### Issue
When I read a text file (maybe without final newling), the minibar appears on top of the last line.  I need to toggle the minibar to be able to read that last line

#### Steps to reproduce
Make sure the minibar is visible.  Open a text file, choose scroll mode on from the columns icon on the bottom menu, and scroll all the way down.

**Comment by poire-z** [comment] 2019-02-24 08:43
Scroll mode is a bit limited. But the other half of that last line half-cut should be visible on the next page (which indeed make it hard to read). Not much to do about that, except using that Overlap setting. Or just using page mode.
Some details and reasoning in https://github.com/koreader/koreader/issues/4533#issuecomment-459630636 , #3870, #4538

**Comment by Biep** [comment] 2019-02-24 18:59
When I get to the end of the file, and see all but the last line, and then try to scroll more, nothing happens.  When I click at the right side of the screen, I get the "End of book" menu.  When I set overlap (1 line), the whole page greys out when trying to page to the last line.  Without hiding the minibar there seems to be no way to see that line.

My use case is looking at code.  I want to be able to scroll, in order to see a full function at once, without having to flip forward and back.

**Comment by poire-z** [comment] 2019-02-24 19:31
Oh, I see, the _very very last_ line, indeed.

**Comment by Frenzie** [comment] 2019-02-24 19:45
I think PDF/DjVu may also have an issue like that. Not 100 % sure.

**Comment by poire-z** [comment] 2019-02-24 20:27
For cre, there seems to be a simple solution:
```c
/// set vertical position of view inside document
int SetPos( int pos, bool savePos=true, bool allowScrollAfterEnd = false);
```
https://github.com/koreader/crengine/blob/master/crengine/src/lvdocview.cpp#L2030-L2038

We call that from cre.cpp when setting the position in scroll mode:
https://github.com/koreader/koreader-base/blob/15becff11c1b23edbd3f8c74cd949fc0e219d115/cre.cpp#L871-L875
```c
-       doc->text_view->SetPos(pos);
+       doc->text_view->SetPos(pos, true, true);
```
seems to fix that (by somehow adding some kind of blank page after last book line, so you can scroll it up... up to the last to last page - but I guess that's better than not seeing it).

Or we can add a 4th parameter: some extra height to allow - and would we give it the size of the minibar.

**Comment by Frenzie** [comment] 2019-02-24 20:43
Adding a blank page seems a bit unexpected but it's probably better than hiding a line. :-)

**Comment by Biep** [comment] 2019-02-24 21:06
Wouldn't it be possible to add some blank image with the height of the minibar?  Or, very generally, decrease the screen height with the height of the minibar?  (Though that would require a rerendering whenever the bar is toggled.)

And just tor completeness' sake: it is not necessarily the case that the minibar hides only a single line.

**Comment by poire-z** [comment] 2019-02-24 21:32
The height of the minibar is taken into account in normal pages - what's hidden by it is shown on the next page, even with overlap disabled. But as your ending words shows, and from my other links, we can't do much to not cut a line in all-but-last book pages.

But this very last last line of book issue will be fixed in a few days, the solution is there and simple (described above).

**Comment by Biep** [comment] 2019-02-25 09:02
Great!
Which brings me to something else: when I look for updates, I only get the stable version offered - which would mean a regress.  I think it should be possible to put a checkmark somewhere and have the nightly installed.  Or am I just overlooking that possibility?

**Comment by Frenzie** [comment] 2019-02-25 09:24
You're offered an update? Could you please share the precise version numbers involved? (In writing or though a screenshot/picture.)

After that, in the settings (same submenu) you can choose between stable and unstable.

**Comment by Biep** [comment] 2019-02-25 09:49
Hmm.  I now get something else than before:
OTA update -> Check for update ==> OTA package is not available on Stable channel.
Never seen that before..  Yesterday I got something like "Current version xxx; Available version yyy; do you want to update?" - with yyy < xxx.
I found the setting for stable vs. development, but the only effect is that it now ways "OTA package is not available on Development channel.".
I am unable to reproduce my previous results.

**Comment by Frenzie** [comment] 2019-02-25 10:29
> OTA update -> Check for update ==> OTA package is not available on Stable channel.

That is what you're supposed to see, assuming you're on v2019.2 or higher.

> I found the setting for stable vs. development, but the only effect is that it now ways "OTA package is not available on Development channel.".

I OTA updated most or all days this past week, so it's definitely working. What version do you currently have? Is it possible that you forgot to restart so that you have an OTA update queued?

> And BTW, what does OTA mean? Are users supposed to know that abbreviation?

I already changed it to just "update" last week.

https://developers.google.com/android/ota

> would it make sense to remove the extra step "Settings", and simply have the server and channel options in the update submenu?

Maybe, maybe not. It's not a setting that's supposed to be especially accessible because development can and does break things.

**Comment by Biep** [comment] 2019-02-25 10:50
Yes, restarting solved the problem.  And now - having switched back to "stable"- I again get the regression option when checking for updates:

Do you want to update?
Installed version: 201902000087
Available version: 201902000000
Cancel  Update

> Maybe, maybe not. It's not a setting that's supposed to be especially accessible because development can and does break things.

True - but wouldn't a scare screen be better in that situation?  One with a "Show this again next time" check box?

**Comment by NiLuJe** [comment] 2019-02-25 11:25
Yeah, a switch from nightly to stable will offer you a downgrade, that bit makes sense AFAIR.

**Comment by Frenzie** [comment] 2019-02-25 11:29
Right, so you're purposefully using a nightly while checking for updates on the stable channel. That does seem to be the currently expected behavior. I'll add a little alternative message in place because I find that behavior somewhat useful.

> True - but wouldn't a scare screen be better in that situation? One with a "Show this again next time" check box?

I would find that annoying. What would make more sense is to take it out of there to a dedicated settings location (e.g., under Device).

**Comment by Biep** [comment] 2019-02-25 11:29
Fair - but it should be named a **downgrade** then.  Take the scenario of a non-nerd user who had an issue and was told to download the nightly, which he did.  If he doesn't take care checking the version numbers, he'll downgrade when thinking to upgrade.

**Comment by Biep** [comment] 2019-02-25 11:30
> I would find that annoying. What would make more sense is to take it out of there to a dedicated settings location (e.g., under Device).

Hence the check box.  You'ld uncheck it, and never see it again.

**Comment by Frenzie** [comment] 2019-02-25 11:46
@Biep 
> Hence the check box. You'ld uncheck it, and never see it again.

As a generic "advanced settings" checkbox, it works. Much less so as a feature-specific maintenance and usability nightmare. Anyway, that's wishlist material for all of us, see #1870 (although that specific issue is more of a leftover since we've had quite large menu reorganizations since).

**Closed** 2019-02-26 08:43 UTC
Labels: UX, bug

**Comment by Biep** [comment] 2019-02-28 20:32
> > I found the setting for stable vs. development, but the only effect is that it now ways "OTA package is not available on Development channel.".
> 
> I OTA updated most or all days this past week, so it's definitely working. What version do you currently have? Is it possible that you forgot to restart so that you have an OTA update queued?

I am having the same problem again (though now it says "Update information not available on Development channel"), and restarting, or exiting and starting again, or rebooting the Aura, doesn't make it go away.  My current version is v2019-02-87-g926150d_2019-02-24, so I think there should be a newer version available.

**Comment by Frenzie** [comment] 2019-02-28 20:51
Are you using a mirror?

**Comment by Biep** [comment] 2019-02-28 21:10
The people here have an Internet filter - but I am in the same place and situation where I was when restarting KOReader made the thing work.

**Comment by Frenzie** [comment] 2019-02-28 21:18
If you look in crash.log you'll should see a warning saying `cannot find update file`. The GUI message concludes that because no update file can be found none must be on the server, but that was only true when there were no OTA updates for the stable channel.

**Comment by Frenzie** [comment] 2019-02-28 21:22
That is, it now indicates network trouble — most likely on your end I'm afraid.

**Comment by Biep** [comment] 2019-02-28 21:23
Yes, this is the tail of crash.log:
```
02/28/19-21:32:29 INFO  setting zoom mode to contentwidth
source page (0,0) - (611,791)
source page bgcolor 192
source page (0,0) - (611,791)
source page bgcolor 192
source page (0,0) - (611,791)
source page bgcolor 192
02/28/19-21:32:40 WARN  cannot find update file 307
02/28/19-21:40:11 INFO  no dialog left to show
02/28/19-21:40:11 INFO  quitting uimanager
```

Hmm..

**Comment by Biep** [comment] 2019-02-28 21:31
Assuming for the moment you didn't add porn to the latest nightly, what problem could there be?
I just tried the browser in nickel, and I have internet access.

**Comment by Frenzie** [comment] 2019-02-28 21:36
See what `curl -I http://ota.koreader.rocks/koreader-kobo-latest-nightly.zsync` says. In particular, take note of where it's trying to redirect to.

```
$ curl -I http://ota.koreader.rocks/koreader-kobo-latest-nightly.zsync
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 28 Feb 2019 21:34:14 GMT
Content-Type: text/plain
Content-Length: 402119
Last-Modified: Thu, 28 Feb 2019 06:29:56 GMT
Connection: keep-alive
ETag: "5c777fe4-622c7"
Accept-Ranges: bytes
```

**Comment by Biep** [comment] 2019-02-28 21:40
I am afraid you are overestimating me.  I vaguely know curl is a download program, but I don't see anything redirective in the output you show there.  Or do you mean the server?

**Comment by Frenzie** [comment] 2019-02-28 21:43
My bad. :-) I showed you how it's supposed to look with a 200 OK. You're getting a 307 redirect instead, presumably to some kind of portal. (There probably isn't really anything we can do about that.)

**Comment by Biep** [comment] 2019-02-28 21:49
Ah, you mean a redirect in my log file.  So "307" means "redirect", but the log doesn't say to where.
Yes, once in a while the filter blocks an innocent page, so that could be the issue here.
This weekend I expect to have access to another Wifi.  Let's see what happens there..

**Comment by Biep** [comment] 2020-02-27 09:52
The *very last line* issue still stands.  Portrait, zoom to page width.
[pdf.zip](https://github.com/koreader/koreader/files/4260818/pdf.zip)

**Comment by NiLuJe** [comment] 2020-02-27 15:26
With what koreader version?

**Comment by Biep** [comment] 2020-02-27 17:13
Sorry:
* Kobo Aura One
* v2020.02-24-g182dc60_2020-02-26
