### ISSUE TITLE
Can't control brightness (frontlight) in koreader when it was off before koreader start.

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3360] opened 2017-10-15 09:15 UTC
* KOReader version: today's nightly-build 1343
* Device: inkbook Prime (android) 

#### Issue
Can't control brightness (frontlight) in koreader when it was off before koreader start.
When I turn on light and then start koreader I can control the light in koreader (here is only minor issue what when I turn it off in koreader, quit koreader, system still thinks its on - that's what it shows in top bar). 

#### Steps to reproduce
Turn on device, turn off frontlight, start koreader. Frontlight can be changed in koreader menu but in real it does not make any changes

**Comment by Frenzie** [comment] 2017-10-15 09:23
Could you test the effect of https://github.com/koreader/android-luajit-launcher/pull/64? On my devices that makes no difference and removes the issue where you don't get a picture until manually refreshing but if this is a recent regression that change would be responsible.

**Comment by mwoz123** [comment] 2017-10-15 09:42
Can you bump luajit version in koreader? So it'll be in next nightly. 
I don't remember how to do it.. 

BTW screen is not blank anymore  after koreader start ( #3325) so it must have been fixed before

**Comment by Frenzie** [comment] 2017-10-15 10:05
You would just change the file to add those lines back however you want. There's nothing to bump.

> BTW screen is not blank anymore after koreader start ( #3325) so it must have been fixed before

That was because of that change. If you look at https://github.com/koreader/koreader/issues/3325#issuecomment-335026897 you'll see I referred to the same issue.

**Comment by mwoz123** [comment] 2017-10-16 20:12
Ok I'll try to remember to test it once I found some time and run pc. But that might not be soon..  

I wish testing koreader on Android could be easier. 
BTW many thanks for x86 build. 


I've just noticed minor issue related to that.
 even when light was on before koreader start and can be controlled by koreader, koreader show incorrect value. Koreader initially show light is off but it's on.

**Comment by Frenzie** [comment] 2017-10-16 21:48
You could try if https://github.com/koreader/koreader/releases/tag/v2017.10.04-nightly has the same issue as an in between test, but it may not give absolute certainty.

> I wish testing koreader on Android could be easier.

Although I consider Android unfriendly, I'm actually slightly surprised to hear you say that. My frustration with the Android testing process led to #3297, which is actually easier than Kobo for me in some ways because the uploading has been automated away.

Of course it's much harder to quickly change a Lua file without recompiling, which is one of Lua's biggest advantages. On Kobo you can contribute with a text editor and nothing else. I could probably do something similar to the ADB upload with USBNet or wifi on Kobo if I wanted to but the process there isn't frustrating in the first place.

With the addition of #3353 I can even easily test multiple Android versions, all thanks to your explanation of how to use the emulator I might add. :-) Unfortunately the older ones that I'm most interested in don't work very well in the emulator but it's still a much wider range than my two Android 6 devices.

> I've just noticed minor issue related to that.
even when light was on before koreader start and can be controlled by koreader, koreader show incorrect value. Koreader initially show light is off but it's on.

In that case it might be unrelated.

**Comment by mwoz123** [comment] 2017-10-19 18:45
>Although I consider Android unfriendly, I'm actually slightly surprised to hear you say that. 

Sorry I was dreaming of a debugger. You brought me back to earth..

**Comment by Frenzie** [comment] 2017-10-19 18:55
That exists. I was hoping you'd be able to tell me how to run gdbserver and/or how to easily attach to it on Android. Also some parts of the Android CFLAGS might not be quite debuggy enough yet, but that'd be easy to change if desired (by adding a KODEBUG switch similar to https://github.com/koreader/koreader-base/pull/525). There's even a copy of gdbserver prebuilt for Android included in the APK.

There are some docs [here](https://source.android.com/devices/tech/debug/gdb).

**Comment by Frenzie** [comment] 2017-10-19 18:56
PS I like the Nemiver gdb GUI frontend.

**Comment by Frenzie** [comment] 2017-10-19 20:27
Another little Android thing. `adb shell`

```
shell@Z00A:/data/user/0/org.koreader.launcher/files $ cd ..
shell@Z00A:/data/user/0/org.koreader.launcher $ ls
opendir failed, Permission denied
shell@Z00A:/data/user/0/org.koreader.launcher $ run-as org.koreader.launcher
shell@Z00A:/data/data/org.koreader.launcher $ ls
cache
code_cache
files
lib
```

Now I know that the libs exist in files/libs as they should… but it doesn't quite explain why I'm getting this error on my Zenfone 2:
```
10-19 22:15:03.220  2313  2332 I KOReader: try to load module common/serialize.so
10-19 22:15:03.220  2313  2332 I KOReader: error: [string "dl.lua"]:38: error opening /data/user/0/org.koreader.launcher/files/common/serialize.so: dlopen failed: library "libluacompat52.so" not found
10-19 22:15:03.220  2313  2332 E luajit-launcher: Failed to run script: error loading module 'serialize' from file 'common/serialize.so':
10-19 22:15:03.220  2313  2332 E luajit-launcher: 	dlopen failed: library "libluacompat52.so" not found
```

```
shell@Z00A:/data/data/org.koreader.launcher/files/common $ ls
libluacompat52.so
libtffi_wrap.so
ltn12.lua
lua-ljsqlite3
mime
mime.lua
serialize.so
socket
socket.lua
ssl
ssl.lua
ssl.so
turbo
turbo.lua
turbovisor.lua
xsys.lua
```

```
shell@Z00A:/data/data/org.koreader.launcher/files/libs $ ls
libcrengine.so
libcrypto.so.1.0.0
libczmq.so.1
libdjvulibre.so.21
libfmq.so.1
libfreetype.so.6
libgif.so.7
libjpeg.so.8
libk2pdfopt.so.2
libkoreader-cre.so
libkoreader-djvu.so
libkoreader-lfs.so
liblept.so.4
liblodepng.so
libluacompat52.so
liblualongnumber.so
libmupdf.so
libpng16.so.16
libsqlite3.so
libssl.so.1.0.0
libtesseract.so.3
libturbojpeg.so
libwrap-mupdf.so
libz.so.1
libzmq.so.4
libzyre.so.1
```

Oh well, I'll make it print better library loading debug info another day.

/random musings

**Comment by mwoz123** [comment] 2017-10-28 20:02
Not sure if that's related to issue. 
@Frenzie I tried 1287 version as you wanted. 
It's also not working there. 

There's minor change. 
That was fixed - if you turn on light, turn on koreader, light gets off at koreader startup. 
All the rest seems the same. 
Starting with light on can control light in koreader,
Starting with light off, can't control the light in koreader. 

Any other ideas?

**Comment by Frenzie** [comment] 2017-10-28 20:48
Is USB debugging an option on this device? I would mimic what the script is trying with `adb shell settings put system screen_brightness 100` and such and see what happens.

**Comment by mwoz123** [comment] 2017-10-29 09:04
When light was already on, seems to be working fine - can control it (and it really changes device settings) :

`adb shell settings put system screen_brightness 0`

logcat:
>D/DisplayPowerState, setScreenBrightness(  353): mScreenBrightness:155         brightness:0
D/DisplayPowerState, BrightnessSetting(  353): brightness:0      after changed,brightness:255

`adb shell settings put system screen_brightness 100`
logcat:
> D/DisplayPowerState, setScreenBrightness(  353): mScreenBrightness:255         brightness:100
D/DisplayPowerState, BrightnessSetting(  353): brightness:100      after changed,brightness:155

**Comment by mwoz123** [comment] 2017-10-29 09:12
When it was off in top menu , those commands doesn't change the frontlight settings and I can see no entry in logcat for brightness

**Comment by mwoz123** [comment] 2017-10-29 09:27
device logcat after manually clilck enable frontlight in top bar:

>D/myShutdownService(  600): getAction():android.intent.action.BATTERY_CHANGED
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 57--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 53--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 54--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 48--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 50--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 0--
E/PowerManagerService-JNI(  353): jeffy, do set wake
E/libsuspend(  353): autosuspend_earlysuspend_wake
E/PowerManagerService-JNI(  353): jeffy, do set wake
E/libsuspend(  353): autosuspend_earlysuspend_wake
D/PowerManagerService(  353): resetIdle:true
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): cancelAlarms:
D/PowerManagerService(  353): resetIdle:true
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): cancel alarm:user_timeout_action
D/PowerManagerService(  353): set alarm:user_timeout_action, now:1509269033801, wake:1509269626795
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 57--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 0--
E/PowerManagerService-JNI(  353): jeffy, do set wake
E/libsuspend(  353): autosuspend_earlysuspend_wake
D/PowerManagerService(  353): cancelAlarms:
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): resetIdle:true
D/PowerManagerService(  353): cancel alarm:user_timeout_action
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): cancel alarm:user_timeout_action
D/PowerManagerService(  353): set alarm:user_timeout_action, now:1509269033924, wake:1509269626795
D/DisplayPowerState, setScreenBrightness(  353): mScreenBrightness:255         brightness:100
D/DisplayPowerState, BrightnessSetting(  353): brightness:100      after changed,brightness:155
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar
D/myShutdownService(  600): getAction():android.intent.action.BATTERY_CHANGED
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar
D/dalvikvm(  600): GC_CONCURRENT freed 1321K, 33% free 6627K/9844K, paused 3ms+4ms, total 41ms
E/PowerManagerService-JNI(  353): jeffy, do set idle, screen on:1
D/libsuspend(  353): ***kernel idle turn on***
D/libsuspend(  353): ***wifi setting button off***
E/libsuspend(  353): autosuspend_idle_enable
D/PowerManagerService(  353): mIdleTimer runnable:1509269098927
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): set alarm:idle_wake_action, now:1509269038928, wake:1509269098927
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar
D/myShutdownService(  600): getAction():android.intent.action.BATTERY_CHANGED
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar


logcat after manually clilck disable frontlight in top bar:

>D/myShutdownService(  600): getAction():android.intent.action.BATTERY_CHANGED
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 57--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 53--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 54--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 48--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 50--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 0--
E/PowerManagerService-JNI(  353): jeffy, do set wake
E/libsuspend(  353): autosuspend_earlysuspend_wake
E/PowerManagerService-JNI(  353): jeffy, do set wake
E/libsuspend(  353): autosuspend_earlysuspend_wake
D/PowerManagerService(  353): resetIdle:true
D/PowerManagerService(  353): cancelAlarms:
D/PowerManagerService(  353): resetIdle:true
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): cancel alarm:user_timeout_action
D/PowerManagerService(  353): set alarm:user_timeout_action, now:1509269127888, wake:1509269720886
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 57--
W/EventHub(  353): --dela--getEvents()--EventHub.cpp--key == 0--
E/PowerManagerService-JNI(  353): jeffy, do set wake
E/libsuspend(  353): autosuspend_earlysuspend_wake
D/DisplayPowerState, setScreenBrightness(  353): mScreenBrightness:155         brightness:0
D/DisplayPowerState, BrightnessSetting(  353): brightness:0      after changed,brightness:255
D/PowerManagerService(  353): cancelAlarms:
D/PowerManagerService(  353): resetIdle:true
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): cancel alarm:user_timeout_action
D/PowerManagerService(  353): set alarm:user_timeout_action, now:1509269128016, wake:1509269720885
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar
D/myShutdownService(  600): getAction():android.intent.action.BATTERY_CHANGED
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar
D/myShutdownService(  600): getAction():android.intent.action.BATTERY_CHANGED
I/EinkMode(  428): 3--------------------------EPD_PART
W/SurfaceFlinger(  103): Set flush mode
E/ViewRootImpl(  428): Skipped update region:StatusBar
E/PowerManagerService-JNI(  353): jeffy, do set idle, screen on:1
D/libsuspend(  353): ***kernel idle turn on***
D/libsuspend(  353): ***wifi setting button off***
E/libsuspend(  353): autosuspend_idle_enable
D/PowerManagerService(  353): mIdleTimer runnable:1509269193015
D/PowerManagerService(  353): cancel alarm:idle_wake_action
D/PowerManagerService(  353): set alarm:idle_wake_action, now:1509269133016, wake:1509269193015

I can't see nothing special here:(

**Comment by Frenzie** [comment] 2017-10-29 09:59
> My guess is we miss some kind of toggle ~ setEnabledFrontlight(true), before steering light level

It could be an InkBook specific one. But...

> Any other ideas?

Did you try the thing I actually suggested besides trying an old version?

**Comment by mwoz123** [comment] 2017-11-01 20:09
You’re talking about gdb debugging?

**Comment by Frenzie** [comment] 2017-11-01 20:27
No, that testing the old build has many more changes than just reversing koreader/android-luajit-launcher#64

It's likely to be the same of course, but there's your average user and there's you. ;-)

> My guess is we miss some kind of toggle ~ setEnabledFrontlight(true), before steering light level

If so, my guess would be more InkBook than Android. That being said, I don't see anything over here at a glance: https://github.com/artatechsoft/InkbookSDK

**Comment by mwoz123** [comment] 2017-11-02 07:36
Ok so I'll do test git koreader + from android-luajit I'll remove changes from commit https://github.com/koreader/android-luajit-launcher/pull/64/commits/0f30925295fa5d6cf5e7034b9ea6f59bc9cc3403? 
Or do you want older koreader?

**Comment by Frenzie** [comment] 2017-11-02 07:43
That's it as far as regression testing goes. Of course setScreenBrightness() is also where you'd quickly iterate some other tests based on API docs and StackOverflow.

**Comment by mwoz123** [comment] 2017-11-12 20:36
I asked Artatech if they could help but they said they won't share such knowledge:[

I also checked : https://play.google.com/store/apps/details?id=de.SmartDyne.Free.DisplaySystemSettings
Did find Artatech specific settings (e.g. "icon_3") but not related to screen brightness.
Only well known standard android: screen_brightness, screen_brightness_mode, screen_off_timeout.

I think those tests doesn't make much sense, as :
`adb shell settings put system screen_brightness 100`
(..)
>When it was off in top menu , those commands doesn't change the frontlight settings and I can see no entry in logcat for brightness.

so it doesn't seem an issue in our implementation as (when it's off) we're not able to control it even from commandline. When it's on we can change brightness level.

**Comment by Frenzie** [comment] 2017-11-12 21:52
Weird, don't they want people developing software for their device?

Have you tried certain specific values rather than something more or less random like `100`? (Admittedly I am responsible for suggesting that, but just to get started. :-P) Most notably `0`and `1`.

**Comment by pazos** [comment] 2019-01-21 22:09
Hey, I can reproduce this issue on another RK3026 device. The device uses the application BrightnessSet.apk to modify light values. Brightness set is just an activity with a floating window which calls specific framework classes embedded in android framework.jar.

**Comment by Frenzie** [comment] 2019-02-22 19:34
I'll close this for now, but of course PRs or information are always welcome.

**Closed by Frenzie** 2019-02-22 19:34 UTC
Labels: Android, bug, wontfix
