### ISSUE TITLE
Zoom to content width causes crash

### ISSUE THREAD

**Issue by marmistrz** [koreader/koreader#1560] opened 2015-06-17 09:57 UTC
I'm running version 2014.11-257-g63fb8af on PB622.

I opened a djvu scan and went into the landscape mode. Selected "zoom to fit page width" - zoom was ok. Selected "zoom to fit content width" - a crash occurs.

**Comment by chrox** [comment] 2015-09-18 11:30
Could you also provide a link to the document with which you found this problem? I cannot reproduce this bug.

**Comment by marmistrz** [comment] 2015-09-18 12:21
Oh, I don't remember. I'll test some and let you know.

**Comment by houqp** [comment] 2016-02-29 01:50
@marmistrz closing the ticket for now. please reopen it if you are still experiencing this issue.

**Closed by houqp** 2016-02-29 01:50 UTC
Labels: bug
