### ISSUE TITLE
Latest nightly build (2015.11.175) crashes all the time, returned to stable version

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#1857] opened 2016-02-28 21:40 UTC
* KOReader version: 2015.11.175
* Device: Kobo Aura H20

I tried latest nightly, hoping to use it as main version and enjoy latest features. But it crashes all the time for me. I change book (I'm trying to open relatively small epub file) and it crashes within seconds.

This is more as an information that latest nightly doesn't work, it's unusable, at least for me.

File crash.log is empty.

I returned to stable version, it works fine. Hope we soon will have this sorted out, so I can enjoy latest features.

**Comment by houqp** [comment] 2016-02-28 22:25
Confirmed, looking into it now.

**Comment by houqp** [comment] 2016-02-28 22:53
Hm... looks like /mnt/onboard somehow got mounted as a read-only filesystem.

**Comment by houqp** [comment] 2016-02-28 23:18
The filesystem went back to a read/write state after a reboot. I suspect it got corrupted while I was copying the new release through USB. If you can't see any crash.log, then it's likely you went into the same issue, i.e. ended up with a read-only file system. Have you tried rebooting the device after seeing the crash?

PS: I only have a Aura HD for testing.

**Comment by KenMaltby** [comment] 2016-02-28 23:28
Mounted? I thought the mounting took place in the system root (user/local/Kobo/udev/) long before any of the KOReader code is accessed.  Don't understand why KOReader would be remounting the internal uSD card or its user FAT partition.

**Comment by houqp** [comment] 2016-02-28 23:34
`/mnt/onboard` is mounted with the option `errors=remount-ro`, so if there is any filesystem error, the kernel will remount it as ro. So yes, it has nothing to do with koreader ;)

**Comment by KenMaltby** [comment] 2016-02-29 01:13
I hope the new remount of the /mnt/sd  isn't being thought of as a filesystem error by kobo's FW.  If so, it would have to relate to recent FW as I have been remounting /mnt/sd , just before calling reader.lua for a very long time now.  I am still on FW 3.0.5.  I also added the code, from the merge, and it works fine so far.  
 
Odd that you both would suffer a filesystem error installing the current nightly.

**Comment by Hzj-jie** [comment] 2016-02-29 08:23
Have you tried to enable 'auto refresh time' feature in status bar? On my device (kobo aura hd), koreader will crash in several seconds after I switch to another book with this feature on. And the error log contains only 'segmentation fault'. I haven't had a chance to look deeper inside the issue.

**Comment by AlanSP1** [comment] 2016-02-29 12:11
I didn't tried to reboot device. After crash I was back into KSM and just started koreader again, tried to switch book and I was back to KSM within seconds. Now with this information, that system was remounted as read only, this could make sense, including empty crash.log file.

On the other hand, just to mention, crash.log file was created, with time stamp of that time. I'm not sure what time exactly, I remembered to looks at crash.log later and I need computer to do so, so I looked at the file and its time stamp after I downgraded to stable version.

And yes, as @Hzj-jie mentioned, I did enabled "auto refresh time", this is one of the features I really wanted to enjoy. So, it can be that this feature has something to do with this.

Do you think that I should try again with latest nightly, reboot it? Also, try to turn on/off auto refresh time option? Or you can reproduce it by yourself and test it out and solve?

**Comment by Hzj-jie** [comment] 2016-02-29 13:51
I can still repro the issue with latest nightly build. But unfortunately I have not got the root cause yet.

**Comment by AlanSP1** [comment] 2016-02-29 14:20
It looks that "auto refresh time" for some reason, at least when opening new book with this option enabled crashes koreader.

**Comment by chrox** [comment] 2016-02-29 15:08
The latest nightly build seems alright on my kindle voyage with "auto refresh time" on.

**Comment by Markismus** [comment] 2016-02-29 16:01
I just tested version `v2015.11-183-g03d7b7d` for houpq and it works as I would expect.

**Comment by AlanSP1** [comment] 2016-02-29 16:11
As at least one other person ( @Hzj-jie has the same problem, with different device (Aura HD, I have H20)) has same problem and with the same error in file crash.log, I think this isn't only on my device.

@Hzj-jie still can reproduce it, as I am. Changing book with option on crashes our different devices, but with same message.

Also, I'm not using version 183, I'm using latest nightly 175, available here. I'll test what's going on with new nightly.

I'd really love to use "live clock", this is a feature I proposed, this is something I had on my Sony PRS 650.

As I see it works just fine on Kindle, maybe it's something specific with kobo aura hd and H2O?

**Comment by Markismus** [comment] 2016-02-29 18:32
You could install v. 183 via OTA and see whether it's fixed.

**Comment by Hzj-jie** [comment] 2016-03-01 02:59
Mine is 184 (built myself), which still has this issue. So I assume it's a Kobo specific issue.

**Comment by houqp** [comment] 2016-03-01 06:56
Interesting, I haven't tried running with live clock on. Will give it a try later...

**Comment by houqp** [comment] 2016-03-01 07:23
I am able to reproduce the crash now. The bug will crash the reader after you open one book, turn on auto refresh, then close the open and open another one.

My patch in https://github.com/koreader/koreader/pull/1864 should take care of it.

The segmentfault you are seeing though, it's a separate issue. It would nice if you can find a way to reproduce it and report back here (preferable in a new ticket) :)

**Comment by Hzj-jie** [comment] 2016-03-01 08:09
Qingping, I saw your change, but cannot quite get the point, why unschedule the event is important? Does it mean, UIManager:setDirty(self.view.dialog, "ui", self[1][1][1].dimen) will fail? i.e. self[1][1][1] should be nil after opening the second book.

**Comment by houqp** [comment] 2016-03-01 08:18
it calls `updateFooterPage`, which depends on what information you selected to show in footer, might call methods in readertoc. readertoc then tries to access `self.ui.document`, but at that point, `self.ui.document` is already nil. So you get a crash.

At least this is what the stacktrace in my crash.log says ;)

**Comment by Markismus** [comment] 2016-03-01 10:01
@houqp I had to open four books, but I could reproduce the crash, too.

**Comment by AlanSP1** [comment] 2016-03-01 12:14
It seems that @houqp solved crashing of live clock, but I'll need to have nightly here to test it on my device.

**Comment by houqp** [comment] 2016-03-06 01:43
closing for now. @AlanSP1 , please reopen this if you are still experiencing the crash.

**Closed by houqp** 2016-03-06 01:43 UTC
Labels: bug
