### ISSUE TITLE
crash with versions > 1800-g0924b57_2018-07-29

### ISSUE THREAD

**Issue by didierm** [koreader/koreader#4276] opened 2018-10-17 21:37 UTC
* KOReader version: koreader-android-arm-linux-androideabi-v2015.11-1868-gb8d9598_2018-10-06.apk
* Device: Icarus Illumina XL HD E785BK

#### Issue
Upgraded from release 1735-g14e7730_2018-06-02 to release 1868-gb8d9598_2018-10-06.
* After starting up, KOreader shows the book library, but crashes as soon as a random epub is opened.
* This also happens with a clean install.
* This also happens with the latest nightly build (1884-g53e7a0b_2018-10-16).
* This also happens with the earliest available nightly build (1844-g51382d5_2018-09-08).
* Downgrading to release 1800-g0924b57_2018-07-29 fixes the issue.

#### Steps to reproduce
* Install or upgrade to release 1868-gb8d9598_2018-10-06
* open an epub
* crash

##### `crash.log` (if applicable)
There is no `crash.log` generated ; a full logcat dump is to be found at https://pastebin.com/YdYit6R8 .

**Comment by pazos** [comment] 2018-10-17 22:40
seems a duplicate of #4254

**Comment by NiLuJe** [comment] 2018-10-17 22:58
Indeed it is, closing to centralize information ;).

**Closed by NiLuJe** 2018-10-17 22:58 UTC
Labels: Android, bug, duplicate
