### ISSUE TITLE
[Pocketbook] Blank screen after minimizing

### ISSUE THREAD

**Issue by marmistrz** [koreader/koreader#1559] opened 2015-06-17 09:55 UTC
I'm running version 2014.11-257-g63fb8af on PB622.
1. Launch koreader
2. Minimize it (home button)
3. Launch it back from the window list

The screen is blank until the menu is opened.

**Comment by pazos** [comment] 2020-08-19 20:35
Duplicate of #5140

**Closed by pazos** 2020-08-19 20:35 UTC
Labels: PocketBook, firmware, help-wanted
