### ISSUE TITLE
Can't connect on wifi

### ISSUE THREAD

**Issue by supersarma** [koreader/koreader#8591] opened 2021-12-26 09:46 UTC
Hello,

* KOReader version: 2021.12.1
* Device: Pocketbook Inkpad3 PB740 - version V740.6.2.462

#### Issue
The device is not able to connect on the wifi network 

#### Steps to reproduce
- Open KOreader
- Settings -> Network -> Network Info 
Message : 

```
eht0 HWaddr :94:99:01xxxxxxxx
IP:192.168.1.25
SSID:
No default Gateway to ping
```

"Wifi-connection" is checked. Also, I am not able de uncheck it.

Any idea how to fix it ?
Thank you.

**Comment by pazos** [comment] 2021-12-26 13:16
Duplicate of #4747

**Closed by pazos** 2021-12-26 13:16 UTC
Labels: PocketBook, duplicate
