### ISSUE TITLE
Display text vertically

### ISSUE THREAD

**Issue by Huahddd** [koreader/koreader#11572] opened 2024-03-19 15:50 UTC
Does koreader have any plans to support vertical text display? (Display effect as shown in the picture)

![屏幕截图 2024-03-19 234853](https://github.com/koreader/koreader/assets/142563515/8d91871a-616a-4188-af53-006b6f126041)

**Comment by offset-torque** [comment] 2024-03-19 16:08
Please see this related thread: [FR: Japanese vertical formatting (tategaki) support](https://github.com/koreader/koreader/issues/11469)

**Comment by pazos** [comment] 2024-06-01 16:12
Duplicate of #11469

**Closed by pazos** 2024-06-01 16:12 UTC
Labels: enhancement, duplicate
