### ISSUE TITLE
Cannot download cbz from calibre OPDS

### ISSUE THREAD

**Issue by pausa** [koreader/koreader#5582] opened 2019-11-09 13:25 UTC
* KOReader version: 2019.10
* Device: Kobo_daylight

#### Issue
When navigating my calibre library, i have no option to download CBZ files. Other ebook formats seem to work fine (epub, mobi). I noticed that calibre uses the mime applicaton/x-cbz.

I tried to download the file on my phone

Here an example of entry in the calibre catalog:

`
  <entry>
    <title>Kengan Ashura 01</title>
    <author>
      <name>Yabako Sandrovich</name>
    </author>
    <id>urn:uuid:538a609d-1859-4ed7-b2f2-de023736e661</id>
    <updated>2019-11-02T08:04:28+00:00</updated>
    <published>2019-10-29T22:27:18+00:00</published>
    <dc:date>2012-04-01T00:00:00+00:00</dc:date>
    <content type="xhtml">
      <div xmlns="http://www.w3.org/1999/xhtml">TAGS: manga<br/>
SERIES: Kengan Ashura [1]<br/></div>
    </content>
    <link rel="http://opds-spec.org/acquisition" href="/get/cbz/331/calibre" type="application/x-cbz" length="49068606" mtime="2019-10-29T22:27:19.404623+00:00"/>
    <link rel="http://opds-spec.org/cover" href="/get/cover/331/calibre" type="image/jpeg"/>
    <link rel="http://opds-spec.org/thumbnail" href="/get/thumb/331/calibre" type="image/jpeg"/>
  </entry>
`
#### Steps to reproduce
Add a CBZ in calibre. Try to download it with KOreader opds.

**Comment by Frenzie** [comment] 2019-11-09 16:35
Duplicate of #5478. Have you been able to find any time to work on it, @teroshan? :-)

**Closed by Frenzie** 2019-11-09 16:35 UTC
Labels: enhancement
