### ISSUE TITLE
KOReader 2018.11 "An die Freude" exit every time on boyue T80S eink

### ISSUE THREAD

**Issue by harisonyu** [koreader/koreader#4311] opened 2018-11-08 07:43 UTC
* KOReader version: KOReader 2018.11 "An die Freude"
* Device:BoYue T80S

#### Issue
when open books, App will exit every time, use "koreader-android-arm-linux-androideabi-v2018.11.1.apk"
#### Steps to reproduce
open random books
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by harisonyu** [comment] 2018-11-08 07:54
seems open pdf file is ok. when open epub app will crash and exit. I try to find log, but can't find it under /koreader

**Comment by pazos** [comment] 2018-11-08 17:15
duplicate of #4254

**Comment by NiLuJe** [comment] 2018-11-08 18:02
Indeed, closing to centralize efforts in #4254

**Closed by NiLuJe** 2018-11-08 18:02 UTC
Labels: Android, bug, duplicate
