### ISSUE TITLE
Light control and page refresh on Onyx Boox Note 3

### ISSUE THREAD

**Issue by rickythefox** [koreader/koreader#8624] opened 2022-01-06 21:09 UTC
* KOReader version: 
* Device: Onyx Boox Note 3

#### Issues
1. Page refresh works in the compatibility test client but not when turning pages in a book.
2. Frontlight control works in the compatibility test client but not from the main interface.
2.1 Frontlight control interface looks good in the compatibility test client but is messed up in the main interface.

#### Steps to reproduce
Video on Google Drive here:
https://drive.google.com/file/d/183166Vch3JBGgSTVS0sy_bQPOzGfl07-/view?usp=sharing

Logs below.

```
Device info:
Manufacturer: onyx
Brand: onyx
Model: note3
Device: note3
Product: note3
Hardware: qcom
Platform: sdm660


Test logs:
01-06 21:54:18.815 E/EPD     ( 6474): java.lang.ClassNotFoundException: android.view.View$EINK_MODE
01-06 21:54:18.842 V/NativeGlue( 6474): WindowFocusChanged: 0xd6f801e0 -- 0
01-06 21:54:19.023 V/NativeGlue( 6474): NativeWindowDestroyed: 0xd6f801e0 -- 0xe72b7808
01-06 21:54:19.133 V/NativeGlue( 6474): Stop: 0xd6f801e0
01-06 21:54:19.133 V/NativeGlue( 6474): SaveInstanceState: 0xd6f801e0
01-06 21:54:20.813 I/TestActivity( 6474): running lights test: Onyx (warmth)
01-06 21:54:22.751 V/Lights  ( 6474): Setting brightness to 202
01-06 21:54:23.319 V/Lights  ( 6474): Setting brightness to 162
01-06 21:54:25.460 I/TestActivity( 6474): running epd test: Freescale/NTX
01-06 21:54:25.476 W/reader.launche( 6474): Accessing hidden method Landroid/view/View;->postInvalidateDelayed(JIIIII)V (blacklist, reflection, denied)
01-06 21:54:25.478 E/EPD     ( 6474): java.lang.NoSuchMethodException: android.view.View.postInvalidateDelayed [long, int, int, int, int, int]
01-06 21:54:36.009 I/TestActivity( 6474): running epd test: Onyx/Qualcomm
01-06 21:54:36.021 E/EPD     ( 6474): java.lang.NoSuchMethodException: android.view.View.setWaveformAndScheme [int, int, int]
01-06 21:54:36.090 I/EPD     ( 6474): requested eink refresh, type: 98 x:0 y:0 w:1404 h:1872
```

**Comment by pazos** [comment] 2022-01-06 22:00
Duplicate of https://github.com/koreader/koreader/issues/8482

**Closed by pazos** 2022-01-06 22:00 UTC

**Comment by rickythefox** [comment] 2022-01-08 11:24
@pazos is 2.1 also handled or should I open a separate issue?

**Comment by Frenzie** [comment] 2022-01-08 11:30
It was added to the list of devices that use Onyx Qualcomm light controller, yes. Please open a new issue if it's not working in today's nightly.
