### ISSUE TITLE
Timer related features stopped working

### ISSUE THREAD

**Issue by claus-von-gmx** [koreader/koreader#11805] opened 2024-05-12 10:25 UTC
* KOReader version:2024.04-32
* Device: Pocketbook Inkpad 3 Pro, Pocketbook InkpadX

#### Issue Autoturn does only work with values 1sec or 2 sec. Any higher values don't trigger pageturns. 
Read Timer does't trigger anything, no matter what values I tried.

#### Steps to reproduce
Set Autoturn to i.e. 59 secs.
Set Read Timer to any values i.e. 5 min in the future. By the way, RT offers "Set Time" and " Set interval, but in both cases you have to enter a specific time "hh:mm", not the length of an interval

##### `crash.log` (if applicable)
No crash log generated

**Comment by pazos** [comment] 2024-05-12 12:14
Duplicate of #9493

**Closed by pazos** 2024-05-12 12:14 UTC
Labels: PocketBook
