### ISSUE TITLE
On screen keyboard is slow and unresponsive and skips out on letters (Android )

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5683] opened 2019-12-12 17:08 UTC
Noticed this more on Android (2017 fire 10 tablet)  than on my Paperwhite to be honest.  Here's a 30 second video I took to try to illustrate 

https://photos.app.goo.gl/EoRXsVtCPGGKX5cA6

Toward the end you can see I keep typing test and test over again and koreader seemingly ignoring valid input.  

This is using the 2019.11 build

**Comment by arooni** [comment] 2019-12-12 17:11
Also supporting Bluetooth keyboards might be a different way of addressing this #4673

**Comment by pazos** [comment] 2019-12-12 17:25
duplicate of #2241

**Closed by pazos** 2019-12-12 17:25 UTC
Labels: duplicate
