### ISSUE TITLE
Pdfs open black

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3061] opened 2017-08-09 00:14 UTC
* KOReader version:
http://build.koreader.rocks/download/nightly/v2015.11-1102-g7919026/koreader-android-arm-linux-androideabi-v2015.11-1102-g7919026.apk

* Device:
Samsung tablets, phones, Lineage Os 7.1, Lollipop etc

Hi
_
Whenever I open Pdfs on any of my Android devices, it initially starts with zero brightness, then I have to manually up the brightness. Nomatter what the saved settings are , this seems to be the case.

It also disables "auto brightness" of my devices.

**Comment by Frenzie** [comment] 2017-08-09 08:02
I think this is probably a duplicate of #3004. Any progress @Hzj-jie ? :-)

**Comment by gerroon** [comment] 2017-08-09 16:05
thanks, sounds like it.

**Comment by Frenzie** [comment] 2017-08-13 14:19
Closing then because of duplicate status.

**Closed by Frenzie** 2017-08-13 14:19 UTC
Labels: Android
