### ISSUE TITLE
KOReader 2023.10 "Ovis" Very buggy on Pocketbook era

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#11196] opened 2023-12-03 15:28 UTC
* KOReader version: KOReader 2023.10 "Ovis"
* Device: Pocketbook ERA

#### Issue

Gestures and touchscreen very erratic, does not respond to swipes and rarely allows text selection.
Crashes when trying to select a word (Message read something like "two finger gesture with spacing = 0")

#### Steps to reproduce
![IMG_0642](https://github.com/koreader/koreader/assets/48537231/6cf0c663-bfa5-413b-b00a-773f0fe5586f)

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/13539397/crash.log)

Se attached Crash log.

`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
[crash.log](https://github.com/koreader/koreader/files/13539400/crash.log)

</details>

**Comment by NiLuJe** [comment] 2023-12-03 19:58
```
./luajit: frontend/device/gesturedetector.lua:848: attempt to index field 'initial_tev' (a nil value)
stack traceback:
	frontend/device/gesturedetector.lua:848: in function 'state'
	frontend/device/gesturedetector.lua:225: in function 'feedEvent'
	frontend/device/input.lua:822: in function 'handleTouchEv'
	frontend/device/input.lua:1367: in function 'waitEvent'
	frontend/ui/uimanager.lua:1505: in function 'handleInput'
	frontend/ui/uimanager.lua:1560: in function 'run'
	./reader.lua:242: in main chunk
	[C]: at 0x00013f6d
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
```

Duplicate of #10950 & #11111

**Closed as completed by NiLuJe** 2023-12-03 19:58 UTC
Labels: bug, PocketBook, duplicate, firmware, help-wanted
