### ISSUE TITLE
Status bar auto refresh stops working after page turn

### ISSUE THREAD

**Issue by Evo589** [koreader/koreader#12853] opened 2024-12-05 21:23 UTC
* KOReader version: 2024.11
* Device: Pocketbook Inkpad Color 3

#### Issue
Auto refresh status bar stops working after page turn. If I go back to the file browser and open the book again, the status bar auto refresh starts working again.

#### Steps to reproduce
1. Open an eBook from the file browser.
2. Confirmed that the status bar auto refresh is working and the clock is updating every minute.
3. Do a page turn. Auto refresh stops working and the clock does not update anymore.

##### `crash.log` (if applicable)
[crash.log](https://github.com/user-attachments/files/18029847/crash.log)

**Comment by pazos** [comment] 2024-12-05 23:48
Duplicate of https://github.com/koreader/koreader/issues/9493

**Closed by pazos** 2024-12-05 23:48 UTC
Labels: PocketBook
