### ISSUE TITLE
Bug - CRASH: when enabling reflow for certain pdfs

### ISSUE THREAD

**Issue by PowerUser64** [koreader/koreader#10981] opened 2023-10-06 09:48 UTC
* KOReader version: v2023.08
* Device: Pixel 3a / Android 13

#### Issue
KOReader crashes when enabling reflow in this book and possibly others:
https://github.com/stiber/Signal-Computing/releases/download/1.5/Signal.Computing.pdf
#### Steps to reproduce
1. Open the book
2. Enable reflow
3. Profit

##### Crash log

[crash-org-koreader-launcher-06-10_02-25-45.zip](https://github.com/koreader/koreader/files/12829451/crash-org-koreader-launcher-06-10_02-25-45.zip)

**Comment by pazos** [comment] 2023-10-06 09:54
Duplicate of #10533

**Closed by pazos** 2023-10-06 09:54 UTC
