### ISSUE TITLE
Evernote can't login

### ISSUE THREAD

**Issue by Nanco300** [koreader/koreader#4000] opened 2018-06-06 21:14 UTC
* KOReader version: v2015.11-1735-g14e7730_2018-06-02
* Device: Kobo Glo

    Koreader menu --> Evernote --> Login
    Type login and password (or email and password)
    Login button.

When I try to connect to the Evernot the  Koreader closes, but I did recieve a mail after the attempt.

[evernote.log](https://github.com/koreader/koreader/files/2078180/evernote.log)

**Comment by NiLuJe** [comment] 2018-06-07 01:31
Duplicate of #3600

**Closed by NiLuJe** 2018-06-07 01:31 UTC
