### ISSUE TITLE
FR - Include some help within koreader, or as a bundled document

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#1932] opened 2016-03-29 14:27 UTC
* KOReader version: ALL
* Device: ALL

Reading this discussion and this comment https://github.com/koreader/koreader/pull/1917#issuecomment-201466485 I just realized how good it would be if we have some documentation available within koreader.

It could be written for power user, more people in that way would see all power behind koreader.

Of course, you don't need to write all from scratch, it could be in sync with wiki, but why not include it with koreader installation.

It could be an option, or it could be document (.epub, or something), whatever you find easier to maintain, but available within koreader on device.

**Comment by Hzj-jie** [comment] 2016-03-30 15:21
I am trying to build the wiki into epub directly. I can use wget to download all wiki pages, but leak of linux internal tools to convert html pages into epub.

**Comment by Frenzie** [comment] 2016-03-30 16:11
Duplicate of #1371

**Comment by houqp** [comment] 2016-03-30 16:58
Let's close this one and move the discussion to 1371

**Closed by houqp** 2016-03-30 16:58 UTC

**Comment by Markismus** [comment] 2016-03-30 17:00
Yep. Still, nice to see, that it's not only me. 

Another aspect of this is the development of the wiki. If we are able to make the wiki accessible to users of koreader, ---at first probably only with a link to the live wiki site where they can edit the wiki--- then it would encourage the development of a more transparent wiki. Now I usually use google to find the page in the wiki that I was looking for, since I somehow get lost just clicking through it. 

Ideally if the notes feature is developed, we could edit the wiki in koreader and send the changes directly from koreader. 

In that sense I do wonder whether conversion of the wiki to epub, notes in epub synced to what-was-the-name-of-that-server, downloaded and converted to a wiki edit proposition is a good workflow.

**Comment by Markismus** [comment] 2016-03-30 17:01
@houpq I was still typing!!

**Comment by houqp** [comment] 2016-03-30 18:25
Sorry ;P I quoted your reply to the original issue.
