### ISSUE TITLE
Djvu not working on Android 4.0.x

### ISSUE THREAD

**Issue by hiworld3** [koreader/koreader#5014] opened 2019-05-09 06:15 UTC
KOReader version: 2019.04
 Device: Boox max carta

saying "no reader engine for this file"
but the file is fine, could open it with other apps
Android 4.0.x is so buggy.. please fix..

**Comment by Frenzie** [comment] 2019-05-14 14:45
Do you know when DjVu support broke?

**Comment by Frenzie** [comment] 2019-05-14 14:51
Actually never mind, I can't reproduce. I only had a broken local build due to playing around with `pow`.

**Comment by hiworld3** [comment] 2019-05-27 11:09
I tried a bunch of djvu files, none of them can open, I ran adb to get the log

I'm really stupid I only know to ran, hope this is a ok log, I hope this adb is normal
adb logcat KOReader:V *:S <

[log.txt](https://github.com/koreader/koreader/files/3223479/log.txt)

**Comment by Frenzie** [comment] 2019-05-27 12:23
Higher up you said Android 4.0, but is it possible you're on 4.2?

> Cannot load library: reloc_library[1285]:  2010 cannot locate 'pow'...

In any case, that makes this a duplicate of #3493.

**Comment by hiworld3** [comment] 2019-05-27 12:35
Hi, I just recheck, mine is 4.0.4

should be same problem in all Android 4.x

**Comment by Frenzie** [comment] 2019-05-27 16:33
> should be same problem in all Android 4.x

No, that's most assuredly not the case.

**Closed** 2019-06-03 23:40 UTC
Labels: Android, bug, duplicate

**Comment by hiworld3** [comment] 2019-06-10 05:49
how is the situtation of this right now? maybe we should abandon the Android 4 devices now
i should order a kobo clara since it works better.

**Comment by Frenzie** [comment] 2019-06-10 11:00
If you subscribe to the original issue #3493 you'll remain apprised of any updates.
