### ISSUE TITLE
Android 10+: dictionary lookups don't work

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#6953] opened 2020-12-06 05:30 UTC
* KOReader version: 2020.11-42
* Device: Motorola G4 (sofia_retail) Android 10

#### Issue:
 Dictionary not working

#### Steps to reproduce: 

Install any nightly, from 2020.11-24

1. Do a dict lookup
2. It says "No definition found" as if there weren't any dictionaries installed/found.

But there is no problem on stable and Nightly .11-10.

**Comment by poire-z** [comment] 2020-12-06 07:52
(Works for me on today's nightly on my Android phone.)

**Comment by pazos** [comment] 2020-12-06 13:05
@CalbertAmu: please follow the bug template. Comment here and we can reopen.

**Comment by CalbertAmu** [comment] 2020-12-06 19:03
* KOReader version: 2020.11-42
* Device: Motorola G4 (sofia_retail) Android 10

#### Issue: Dictionary not working on nightlies

#### Steps to reproduce: 
Updated from the developmental.

It says "No definition found" as if there weren't any dictionaries installed/found.

This happened with v2020.11-24, .11-39 and 11-42

But there is no problem on stable and Nightly .11-10.


Maybe it's just my device. I don't know what else to provide. I restarted my phone, reinstalled.

**Comment by NiLuJe** [comment] 2020-12-06 19:06
Logs would probably be a good start, I imagine ;).

**Comment by CalbertAmu** [comment] 2020-12-06 19:18
crash.log isn't there in /koreader. Maybe because I uninstalled and reinstalled, idk.

Sorry, I'll just use an old nightly for now then

**Comment by NiLuJe** [comment] 2020-12-06 19:21
The proper procedure is built-in the issue template... hence not ignoring the issue template being The Way ;).

**Comment by pazos** [comment] 2020-12-06 20:12
Probably something fishy with your ROM, which is probably non-stock. We bumped API to Android11 a few weeks ago. It shouldn't cause issues on sane-ish Android 10 devices (which should fallback to pre29 behaviour with [this flag](https://github.com/koreader/android-luajit-launcher/blob/master/app/manifest/base.xml#L32)

Anyways, it could be any other thing. Without logs I can't say and guessing is not my forte.

> Sorry, I'll just use an old nightly for now then

I can't reproduce on Android 11 (moto g5s - LineageOS 18 | emulator), Android 10 (moto g6 - LineageOS 17.1 | Samsung Tab A7). So, until proven wrong (I will) there's nothing to fix :see_no_evil:

**Comment by CalbertAmu** [comment] 2020-12-06 21:02
It's probably motorola's additions to the OS.

In Terminal I cd to platform-tools
then ./adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F/.

12-06 15:59:04.282  2216  2346 I ActivityManager: Start proc 28975:org.koreader.launcher/u0a345 for activity {org.koreader.launcher/org.koreader.launcher.MainActivity}
12-06 15:59:04.427 28975 28975 I KOReader: [LightsFactory]: Using Generic Lights Controller
12-06 15:59:04.603 28975 28996 I KOReader: Check file in asset module: koreader-v2020.11-42-gc20ad8f_2020-12-05.7z
12-06 15:59:04.609 28975 28996 I KOReader: Skip installation for revision v2020.11-42-gc20ad8f_2020-12-05
12-06 15:59:04.919 28975 28996 I KOReader: Change directory to assets dir: /data/user/0/org.koreader.launcher/files -> /data/data/org.koreader.launcher/files
12-06 15:59:04.944 28975 28996 I KOReader: command chmod 755 ./sdcv returned 0
12-06 15:59:04.955 28975 28996 I KOReader: command chmod 755 ./tar returned 0
12-06 15:59:05.005 28975 28996 I KOReader:  platform thirdparty apps
12-06 15:59:05.005 28975 28996 I KOReader: -> Aard2 (itkach.aard2), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> Alpus (com.ngcomputing.fora.android), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> ColorDict (com.socialnmobile.colordict), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> Eudic (com.eusoft.eudic), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> EudicPlay (com.qianyan.eudic), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> Fora (com.ngc.fora), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> ForaPro (com.ngc.fora.android), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> GoldenFree (mobi.goldendict.android.free), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> GoldenPro (mobi.goldendict.android), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> Kiwix (org.kiwix.kiwixmobile), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> Mdict (cn.mdict), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: -> QuickDic (de.reimardoeffinger.quickdic), role: dict, available: false
12-06 15:59:05.005 28975 28996 I KOReader: Android 10 - Q (API 29) - flavor: rocks
12-06 15:59:05.051 28975 28996 I KOReader:  initializing for device sofia_retail
12-06 15:59:05.051 28975 28996 I KOReader:  framebuffer resolution: {
12-06 15:59:05.051 28975 28996 I KOReader:     ["h"] = 2184,
12-06 15:59:05.051 28975 28996 I KOReader:     ["w"] = 1080,
12-06 15:59:05.051 28975 28996 I KOReader: }
12-06 15:59:05.625 28975 28996 I KOReader:  opening file /storage/emulated/0/Books/Celine/Journey to the End of the Night - Louis-Ferdinand Celine.epub
12-06 15:59:05.897 28975 28996 I KOReader:  Loading plugins from directory: plugins
12-06 15:59:05.899 28975 28996 I KOReader:  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
12-06 15:59:05.901 28975 28996 I KOReader:  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
12-06 15:59:05.902 28975 28996 I KOReader:  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
12-06 15:59:05.903 28975 28996 I KOReader:  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
12-06 15:59:05.905 28975 28996 I KOReader:  Plugin  plugins/backgroundrunner.koplugin/main.lua  has been disabled.
12-06 15:59:05.926 28975 28996 I KOReader:  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
12-06 15:59:05.928 28975 28996 I KOReader:  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
12-06 15:59:05.965 28975 28996 I KOReader:  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
12-06 15:59:05.967 28975 28996 I KOReader:  Loading plugins from directory: /storage/emulated/0/koreader/plugins/
12-06 15:59:05.967 28975 28996 I KOReader:  RD loaded plugin batterystat at plugins/batterystat.koplugin
12-06 15:59:05.967 28975 28996 I KOReader:  RD loaded plugin coverimage at plugins/coverimage.koplugin
12-06 15:59:05.983 28975 28996 I KOReader:  RD loaded plugin gestures at plugins/gestures.koplugin
12-06 15:59:05.983 28975 28996 I KOReader:  RD loaded plugin qrclipboard at plugins/qrclipboard.koplugin
12-06 15:59:05.983 28975 28996 I KOReader:  RD loaded plugin readtimer at plugins/readtimer.koplugin
12-06 15:59:05.987 28975 28996 I KOReader:  RD loaded plugin statistics at plugins/statistics.koplugin
12-06 15:59:05.987 28975 28996 I KOReader:  RD loaded plugin systemstat at plugins/systemstat.koplugin
12-06 15:59:13.467 28975 28996 I KOReader:  event times are real clock time: no adjustment needed

**Comment by pazos** [comment] 2020-12-06 21:15
Thanks for the logs @CalbertAmu: please enable debug logs in KOReader (see https://github.com/koreader/koreader/issues/6901#issuecomment-731619684) and repeat the same log.

(Also please do a few dict lookups while you're logging)

**Comment by CalbertAmu** [comment] 2020-12-06 22:35
I enabled Debug logging on Koreader this time. I did some lookups, but since it acts like there isn't any installed, it didn't show any activity on the log.


12-06 17:30:03.011  2216  2346 I ActivityManager: Start proc 8824:com.microsoft.office.outlook/u0a285 for service {com.microsoft.office.outlook/com.evernote.android.job.v21.PlatformJobService}
12-06 17:30:06.430  2216  2346 I ActivityManager: Start proc 8987:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0i33 for  {com.microsoft.office.outlook/org.chromium.content.app.SandboxedProcessService0:0}
12-06 17:30:14.220  2216  2346 I ActivityManager: Start proc 9051:org.koreader.launcher/u0a346 for activity {org.koreader.launcher/org.koreader.launcher.MainActivity}
12-06 17:30:14.302  9051  9051 I KOReader: [LightsFactory]: Using Generic Lights Controller
12-06 17:30:14.408  9051  9073 I KOReader: Check file in asset module: koreader-v2020.11-42-gc20ad8f_2020-12-05.7z
12-06 17:30:14.410  9051  9073 I KOReader: Skip installation for revision v2020.11-42-gc20ad8f_2020-12-05
12-06 17:30:14.661  2216  7234 I ActivityManager: Killing 7739:com.google.android.apps.maps/u0a202 (adj 975): empty #17
12-06 17:30:14.662  2216  7234 I ActivityManager: Killing 6958:android.process.acore/u0a48 (adj 985): empty #18
12-06 17:30:14.662  9051  9073 I KOReader: Change directory to assets dir: /data/user/0/org.koreader.launcher/files -> /data/data/org.koreader.launcher/files
12-06 17:30:14.690  9051  9073 I KOReader: command chmod 755 ./sdcv returned 0
12-06 17:30:14.706  9051  9073 I KOReader: command chmod 755 ./tar returned 0
12-06 17:30:14.730  9051  9073 I KOReader:  platform thirdparty apps
12-06 17:30:14.730  9051  9073 I KOReader: -> Aard2 (itkach.aard2), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> Alpus (com.ngcomputing.fora.android), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> ColorDict (com.socialnmobile.colordict), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> Eudic (com.eusoft.eudic), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> EudicPlay (com.qianyan.eudic), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> Fora (com.ngc.fora), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> ForaPro (com.ngc.fora.android), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> GoldenFree (mobi.goldendict.android.free), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> GoldenPro (mobi.goldendict.android), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> Kiwix (org.kiwix.kiwixmobile), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> Mdict (cn.mdict), role: dict, available: false
12-06 17:30:14.730  9051  9073 I KOReader: -> QuickDic (de.reimardoeffinger.quickdic), role: dict, available: false
12-06 17:30:14.731  9051  9073 I KOReader: Android 10 - Q (API 29) - flavor: rocks
12-06 17:30:14.757  9051  9073 I KOReader:  initializing for device sofia_retail
12-06 17:30:14.757  9051  9073 I KOReader:  framebuffer resolution: {
12-06 17:30:14.757  9051  9073 I KOReader:     ["h"] = 2184,
12-06 17:30:14.757  9051  9073 I KOReader:     ["w"] = 1080,
12-06 17:30:14.757  9051  9073 I KOReader: }
12-06 17:30:15.143  9051  9073 I KOReader:  opening file /storage/emulated/0/Books/Celine/Death on the Installment Plan - Louis-ferdinand Celine.epub
12-06 17:30:15.241  9051  9073 I KOReader:  Loading plugins from directory: plugins
12-06 17:30:15.242  9051  9073 I KOReader:  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
12-06 17:30:15.242  9051  9073 I KOReader:  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
12-06 17:30:15.242  9051  9073 I KOReader:  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
12-06 17:30:15.243  9051  9073 I KOReader:  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
12-06 17:30:15.243  9051  9073 I KOReader:  Plugin  plugins/backgroundrunner.koplugin/main.lua  has been disabled.
12-06 17:30:15.252  9051  9073 I KOReader:  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
12-06 17:30:15.252  9051  9073 I KOReader:  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
12-06 17:30:15.271  9051  9073 I KOReader:  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
12-06 17:30:15.271  9051  9073 I KOReader:  Loading plugins from directory: /storage/emulated/0/koreader/plugins/
12-06 17:30:15.271  9051  9073 I KOReader:  RD loaded plugin batterystat at plugins/batterystat.koplugin
12-06 17:30:15.271  9051  9073 I KOReader:  RD loaded plugin coverimage at plugins/coverimage.koplugin
12-06 17:30:15.284  9051  9073 I KOReader:  RD loaded plugin gestures at plugins/gestures.koplugin
12-06 17:30:15.284  9051  9073 I KOReader:  RD loaded plugin qrclipboard at plugins/qrclipboard.koplugin
12-06 17:30:15.284  9051  9073 I KOReader:  RD loaded plugin readtimer at plugins/readtimer.koplugin
12-06 17:30:15.286  9051  9073 I KOReader:  RD loaded plugin statistics at plugins/statistics.koplugin
12-06 17:30:15.286  9051  9073 I KOReader:  RD loaded plugin systemstat at plugins/systemstat.koplugin
12-06 17:30:38.290  9051  9073 I KOReader:  event times are real clock time: no adjustment needed
12-06 17:31:43.838  9051  9073 I KOReader:  FM loaded plugin batterystat at plugins/batterystat.koplugin
12-06 17:31:43.848  9051  9073 I KOReader:  FM loaded plugin gestures at plugins/gestures.koplugin
12-06 17:31:43.848  9051  9073 I KOReader:  FM loaded plugin qrclipboard at plugins/qrclipboard.koplugin
12-06 17:31:43.848  9051  9073 I KOReader:  FM loaded plugin readtimer at plugins/readtimer.koplugin
12-06 17:31:43.850  9051  9073 I KOReader:  FM loaded plugin statistics at plugins/statistics.koplugin
12-06 17:31:43.850  9051  9073 I KOReader:  FM loaded plugin systemstat at plugins/systemstat.koplugin
12-06 17:32:05.332  9051  9073 I KOReader:  opening file /storage/emulated/0/Books/Celine/Journey to the End of the Night - Louis-Ferdinand Celine.epub
12-06 17:32:05.426  9051  9073 I KOReader:  RD loaded plugin batterystat at plugins/batterystat.koplugin
12-06 17:32:05.426  9051  9073 I KOReader:  RD loaded plugin coverimage at plugins/coverimage.koplugin
12-06 17:32:05.442  9051  9073 I KOReader:  RD loaded plugin gestures at plugins/gestures.koplugin
12-06 17:32:05.442  9051  9073 I KOReader:  RD loaded plugin qrclipboard at plugins/qrclipboard.koplugin
12-06 17:32:05.442  9051  9073 I KOReader:  RD loaded plugin readtimer at plugins/readtimer.koplugin
12-06 17:32:05.445  9051  9073 I KOReader:  RD loaded plugin statistics at plugins/statistics.koplugin
12-06 17:32:05.445  9051  9073 I KOReader:  RD loaded plugin systemstat at plugins/systemstat.koplugin
12-06 17:32:34.710  9051  9073 I KOReader:  no dialog left to show
12-06 17:32:34.710  9051  9073 I KOReader:  quitting uimanager
12-06 17:32:34.711  9051  9073 I KOReader: Stopping KOReader main activity
12-06 17:32:34.746  2216 12048 I ActivityManager: Process org.koreader.launcher (pid 9051) has died: fore TOP 
12-06 17:32:34.773  2216  2325 W ActivityManager: setHasOverlayUi called on unknown pid: 9051

**Comment by pazos** [comment] 2020-12-07 14:11
Nah. My fault. You need to enable debug logs **and** tell adb logcat you want them logged too.

Please use `adb logcat KOReader:V ActivityManager:* AndroidRuntime:* DEBUG:* audit:* *:F`

I included audit to log selinux issues. If that happens then we're f***d

**Comment by CalbertAmu** [comment] 2020-12-07 18:34
https://pastebin.com/rC34fdRa

**Comment by pazos** [comment] 2020-12-08 01:50
@CalbertAmu: Still nothing. But my previous comment was indeed wrong. To see if its selinux please execute

`adb logcat KOReader:* sh:* *:S`

In the Android 11 emulator it returns:

```logcat
(...)
12-08 02:43:30.543  6509  6532 V KOReader:  dict lookup word: audit
12-08 02:43:30.543  6509  6532 V KOReader:  dict stripped word: audit
12-08 02:43:30.545  6509  6532 V KOReader:  ImageWidget: _render'ing resources/info-i.png
12-08 02:43:30.545  6509  6532 V KOReader:  show widget: table: 0xb0717ff0
12-08 02:43:30.545  6509  6532 V KOReader:  setDirty nil from widget table: 0xb0717ff0 w/ NO region 
12-08 02:43:30.545  6509  6532 V KOReader:  setDirty via a func from widget table: 0xb0717ff0
12-08 02:43:30.548  6509  6532 V KOReader:  Explicit widgetRepaint: table: 0xd1635420 @ ( 541 , 798 )
12-08 02:43:30.549  6509  6532 V KOReader:  Explicit widgetRepaint: table: 0xd1635420 @ ( 541 , 798 )
12-08 02:43:30.549  6509  6532 V KOReader:  setDirty via a func from widget nil
12-08 02:43:30.549  6509  6532 V KOReader:  painting widget: table: 0xbc201620
12-08 02:43:30.550  6509  6532 V KOReader:  blitFrom 18 9 0 0 63 63
12-08 02:43:30.550  6509  6532 V KOReader:  blitFrom 999 9 0 0 63 63
12-08 02:43:30.556  6509  6532 V KOReader:  painting widget: table: 0xb045e570
12-08 02:43:30.556  6509  6532 V KOReader:  blitFrom 101 890 0 0 140 140
12-08 02:43:30.556  6509  6532 V KOReader:  _refresh: Enqueued ui update for region 0 1459 1080 461 
12-08 02:43:30.556  6509  6532 V KOReader:  _refresh: Enqueued partial update for region 105 580 870 299 
12-08 02:43:30.556  6509  6532 V KOReader:  _refresh: Enqueued partial update for region 89 580 902 462 
12-08 02:43:30.556  6509  6532 V KOReader:  _refresh: Enqueued partial update for region 89 580 902 462 
12-08 02:43:30.553  6613  6613 W sh      : type=1400 audit(0.0:132): avc: granted { execute } for name="sdcv" dev="dm-5" ino=133125 scontext=u:r:untrusted_app:s0:c153,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c153,c256,c512,c768 tclass=file app=org.koreader.launcher
12-08 02:43:30.557  6614  6614 W sh      : type=1400 audit(0.0:133): avc: granted { execute } for name="sdcv" dev="dm-5" ino=133125 scontext=u:r:untrusted_app:s0:c153,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c153,c256,c512,c768 tclass=file app=org.koreader.launcher
(...)
```

The two last lines are related to execute `sdcv` (one for internal data/dict and the other for external /sdcard/koreader/data/dict). As you see both were granted. I suspect your phone is rejecting both or, *at least*, the one from the sdcard.

**Comment by CalbertAmu** [comment] 2020-12-08 02:54
[koreader log](https://github.com/koreader/koreader/files/5656540/koreader.log)

**Comment by pazos** [comment] 2020-12-08 12:28
The "bug" is a new enforcement on selinux policies. Cannot be fixed by definition. There're two workarounds possible:

1. Revert to target API28 (probably needs to use the previous docker image, I dunno)
2. Move away from "sdcv" to a shared library approach that cannot trigger the W^X

1. Is probably easier to do. It will screw a few people on 2020.11 nightlies which won't be able to update normally (they need to uninstall apk -> install new apk)
2. Is the **only solution** on targetApi > 28 and a general enhancement even outside android. Note than moving sdcv to a shared library is a bit of pain because it relies on a bunch of libraries itself (glib, gettext ..). Something like @ezdiy suggested is probably the way to go: https://github.com/ezdiy/libsd

**Closed** 2020-12-08 21:41 UTC
Labels: Android, bug, firmware

**Comment by pazos** [comment] 2020-12-09 11:11
> It will screw a few people on 2020.11 nightlies which won't be able to update normally (they need to uninstall apk -> install new apk)

I didn't know that android allows targetSdk downgrades as long as the versionCode is newer. Cool!

@CalbertAmu: [v2020.11-45](http://build.koreader.rocks/download/nightly/v2020.11-45-g89e1c40_2020-12-08/) should fix your issue. Thanks for reporting!
