### ISSUE TITLE
FR: More progressive low brightness levels on Android

### ISSUE THREAD

**Issue by farvardin** [koreader/koreader#6337] opened 2020-06-30 14:31 UTC
On Android, the gap between "frontlight disabled" (still a bit visible) and "frontlight intensity set to 1" is very deep: at intensity 1, the light level is still too bright to read in the night. Intensity 2 is not much different from intensity 1. And frontlight disabled is not very confortable to read, as it's too dark.

The "night mode" could be a solution, but some people find it still too contrasted and don't like to read on a dark background.

The gradation of light intensity on Android could have more steps. And low numbers could be more progressive, to give more control on the light level (On my pocketbook, the light intensity is perfect though, I only mean on Android devices)

During daytime, it doesn't matter because it's not too bright, but in the night it can be unconfortable.

In comparison, other ebook readers such as fbreader are much more progressive in low light levels.

**Comment by pazos** [comment] 2020-06-30 15:10
Frontlight level is provided by hardware. Can't fix that.  Other programs use a black overlay and some alpha to simulate extra dimming. Duplicate of #5768

**Closed by pazos** 2020-06-30 15:10 UTC
Labels: enhancement
