### ISSUE TITLE
App Crashes on Open

### ISSUE THREAD

**Issue by ImranR98** [koreader/koreader#11019] opened 2023-10-18 03:04 UTC
* KOReader version: 2023.08
* Device: Pixel 8 Pro (GrapheneOS)

#### Issue

When I open the app it immediately crashes. I've granted it all permissions including to manage storage. It's possible GrapheneOS may be the issue here as I haven't been able to test this on stock Android, but I've disabled the extra security features for this app and I don't see why this app wouldn't work whereas all other apps do.

#### Steps to reproduce

Install the app, grant all permissions, and launch it.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
--------- beginning of main
10-17 22:57:30.149 V/NativeGlue(30781): Pause: 0xb400007c673d9470
10-17 22:57:30.219 I/reader.launcher(30837): Using CollectorTypeCC GC.
10-17 22:57:30.222 E/reader.launcher(30837): Not starting debugger since process cannot load the jdwp agent.
10-17 22:57:30.284 W/libc    (30837): Access denied finding property "ro.debuggable"
10-17 22:57:30.285 D/AndroidRuntime(30837): >>>>>> START com.android.internal.os.RuntimeInit uid 10198 <<<<<<
10-17 22:57:30.285 W/libc    (30837): Access denied finding property "ro.debuggable"
10-17 22:57:30.287 I/AndroidRuntime(30837): Using default boot image
10-17 22:57:30.287 I/AndroidRuntime(30837): Leaving lock profiling enabled
10-17 22:57:30.287 W/libc    (30837): Access denied finding property "odsign.verification.success"
10-17 22:57:30.287 W/libc    (30837): Access denied finding property "ro.debuggable"
10-17 22:57:30.289 W/org.koreader.launcher(30837): ART APEX data files are untrusted.
10-17 22:57:30.289 I/org.koreader.launcher(30837): Using CollectorTypeCC GC.
10-17 22:57:30.332 D/nativeloader(30837): InitDefaultPublicLibraries for_preload=1: libandroid.so:libaaudio.so:libamidi.so:libbinder_ndk.so:libc.so:libcamera2ndk.so:libdl.so:libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libicu.so:libicui18n.so:libicuuc.so:libjnigraphics.so:liblog.so:libmediandk.so:libm.so:libnativehelper.so:libnativewindow.so:libOpenMAXAL.so:libOpenSLES.so:libRS.so:libstdc++.so:libsync.so:libvulkan.so:libwebviewchromium_plat_support.so:libz.so
10-17 22:57:30.341 D/org.koreader.launcher(30837): Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
10-17 22:57:30.341 D/org.koreader.launcher(30837): I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt72l.dat
10-17 22:57:30.357 W/libc    (30837): Access denied finding property "ro.product.name_for_attestation"
10-17 22:57:30.357 W/libc    (30837): Access denied finding property "ro.product.brand_for_attestation"
10-17 22:57:30.357 W/libc    (30837): Access denied finding property "ro.product.model_for_attestation"
10-17 22:57:30.358 W/libc    (30837): Access denied finding property "ro.debuggable"
10-17 22:57:30.358 D/AndroidRuntime(30837): Calling main entry com.android.internal.os.ExecInit
10-17 22:57:30.358 D/Zygote  (30837): begin preload
10-17 22:57:30.358 I/Zygote  (30837): Calling ZygoteHooks.beginPreload()
10-17 22:57:30.372 I/Zygote  (30837): Preloading shared libraries...
10-17 22:57:30.373 E/org.koreader.launcher(30837): Unable to find pattern file or unable to map it for am
10-17 22:57:30.374 I/Zygote  (30837): Called ZygoteHooks.endPreload()
10-17 22:57:30.378 I/Zygote  (30837): Installed AndroidKeyStoreProvider in 4ms.
10-17 22:57:30.378 D/Zygote  (30837): end preload
10-17 22:57:30.383 W/System  (30837): No Compatibility callbacks set! Querying change 263076149
10-17 22:57:30.383 W/System  (30837): No Compatibility callbacks set! Querying change 263076149
10-17 22:57:30.383 W/System  (30837): No Compatibility callbacks set! Querying change 263076149
10-17 22:57:30.383 W/libc    (30837): Access denied finding property "qemu.sf.lcd_density"
10-17 22:57:30.383 W/libc    (30837): Access denied finding property "qemu.sf.lcd_density"
10-17 22:57:30.390 D/CompatibilityChangeReporter(30837): Compat change id reported: 171979766; UID 10198; state: DISABLED
10-17 22:57:30.390 D/CompatibilityChangeReporter(30837): Compat change id reported: 242716250; UID 10198; state: DISABLED
10-17 22:57:30.390 I/Typeface(30837): Preloading /system/fonts/Roboto-Regular.ttf
10-17 22:57:30.390 I/Typeface(30837): Preloading /system/fonts/RobotoStatic-Regular.ttf
10-17 22:57:30.392 D/CompatibilityChangeReporter(30837): Compat change id reported: 247079863; UID 10198; state: DISABLED
10-17 22:57:30.407 D/nativeloader(30837): InitApexLibraries:
10-17 22:57:30.407 D/nativeloader(30837):   com_android_art: libnativehelper.so
10-17 22:57:30.407 D/nativeloader(30837):   com_android_i18n: libicui18n.so:libicuuc.so:libicu.so
10-17 22:57:30.407 D/nativeloader(30837):   com_android_neuralnetworks: libneuralnetworks.so
10-17 22:57:30.407 D/nativeloader(30837): InitDefaultPublicLibraries for_preload=0: libandroid.so:libaaudio.so:libamidi.so:libbinder_ndk.so:libc.so:libcamera2ndk.so:libclang_rt.hwasan-aarch64-android.so:libdl.so:libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libjnigraphics.so:liblog.so:libmediandk.so:libm.so:libnativewindow.so:libOpenMAXAL.so:libOpenSLES.so:libRS.so:libstdc++.so:libsync.so:libvulkan.so:libwebviewchromium_plat_support.so:libz.so
10-17 22:57:30.407 D/nativeloader(30837): Configuring clns-1 for other apk /data/app/~~xwGd2NMkvmOiqL5_l_iQPg==/org.koreader.launcher-X0NsiHtuxqJ5KWsIMNdVyQ==/base.apk. target_sdk_version=30, uses_libraries=, library_path=/data/app/~~xwGd2NMkvmOiqL5_l_iQPg==/org.koreader.launcher-X0NsiHtuxqJ5KWsIMNdVyQ==/lib/arm64:/data/app/~~xwGd2NMkvmOiqL5_l_iQPg==/org.koreader.launcher-X0NsiHtuxqJ5KWsIMNdVyQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/org.koreader.launcher
10-17 22:57:30.407 D/nativeloader(30837): InitExtendedPublicLibraries: libedgetpu_dba.google.so
10-17 22:57:30.407 D/nativeloader(30837): Extending system_exposed_libraries: libedgetpu_dba.google.so
10-17 22:57:30.407 D/nativeloader(30837): InitVendorPublicLibraries: libOpenCL.so:libOpenCL-pixel.so:libedgetpu_client.google.so:libedgetpu_util.so:lib_aion_buffer.so:lib_jpg_encoder.so:libgxp.so
10-17 22:57:30.407 D/nativeloader(30837): InitProductPublicLibraries: 
10-17 22:57:30.410 V/GraphicsEnvironment(30837): Currently set values for:
10-17 22:57:30.411 V/GraphicsEnvironment(30837):   angle_gl_driver_selection_pkgs=[]
10-17 22:57:30.411 V/GraphicsEnvironment(30837):   angle_gl_driver_selection_values=[]
10-17 22:57:30.411 V/GraphicsEnvironment(30837): ANGLE GameManagerService for org.koreader.launcher: false
```
</details>

Note that most of the time the crash log is empty but I was able to get the above a couple of times.

Also worth noting that it did used to work on an older version of GrapheneOS on the Pixel 7.

**Comment by NiLuJe** [comment] 2023-10-18 04:56
Duplicate of #11009 #10998 #11017. This is fixed in current nightlies.

**Closed by NiLuJe** 2023-10-18 04:56 UTC
Labels: bug, Android, out-of-date, duplicate
