### ISSUE TITLE
Readersearch unit test broken

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#2746] opened 2017-04-09 18:34 UTC
* KOReader version: a51941c
* Device: busted

#### Issue
```
  Readersearch module search API for PDF documents should search backward ... ●

  Readersearch module search API for PDF documents should search forward ... ●

  Readersearch module search API for PDF documents should find the first occurrence ... ●

  Readersearch module search API for PDF documents should find the last occurrence ... 04/09/2017-02:31:33 PM WARN  wrong page number: 46!

04/09/2017-02:31:33 PM WARN  wrong page number: 48!

04/09/2017-02:31:33 PM WARN  wrong page number: 50!

●
```
Yet we get a pass. This might be related to #2489 having been introduced unnoticed, but it could also be something separate.

#### Steps to reproduce
See, e.g., the log for e5bcdee at https://s3.amazonaws.com/archive.travis-ci.org/jobs/220213760/log.txt

### Tracking it down
This error started showing up in f95ad00b9e4a1e3bed1f00b0c93afc3efa308b3f but since that's the introduction of logger it probably just means it went unreported until then.

Edit: ah, I now see [the context](https://github.com/koreader/koreader/blame/5bda44473d2e338ddb8f808790771b8411e159f7/frontend/apps/reader/modules/readerpaging.lua#L854) for the wrong page number warning. Maybe it's less harmful than I thought, but it'll require some investigation.

**Comment by houqp** [comment] 2017-04-10 04:59
Good catch. It's a bug exposed by the new logger. It definitely should not operate on an invalid page number. And as you mentioned, it's not a bug related to that specific search test case.

**Comment by poire-z** [comment] 2020-08-18 12:24
The message is now:
```
08/18/2020-11:50:46 AM WARN  page number too high: 46!
08/18/2020-11:50:46 AM WARN  page number too high: 48!
08/18/2020-11:50:46 AM WARN  page number too high: 50!
```
But I guess that's ok if the test make it go to page 50 on a 45-pages document.
(As nobody bothered about that test over the years, let's close it.)

**Closed by poire-z** 2020-08-18 12:24 UTC
Labels: bug

**Comment by Frenzie** [comment] 2020-08-18 14:49
I've always meant to check if it was harmful but I suppose it should be fine.
