### ISSUE TITLE
Words glued together in bookmarks

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#5521] opened 2019-10-22 16:43 UTC
* KOReader version: v2019.09.3.-42-ga934d2d_2019-09-27
* Device: kindle 3 paperwhite

#### please find on this link a zip file which contains
https://mega.nz/#!tZkAES4a!fQ1WWhq62sB8pTgc2awyVJlO1qy6hiLsI-T0Pi6NoRQ
- a pdf file
- its sdr file containing lots of bookmarks.
The same file has also been uploaded (see link below)

When proofreading, I have highlighted short sentences which were stored as bookmarks. If you look at these bookmarks, you'll see that many of them have words glued together. 

[cloque.zip](https://github.com/koreader/koreader/files/3757175/cloque.zip)

**Comment by Frenzie** [comment] 2019-10-22 16:57
To illustrate, here's a highlight from page 518:

```
                ["text"] = "douce invitation àla prière oùaurepos du soir."
```

And here's the same output from `pdftotext`:

```
Selon le vent, telle ou telle cloche semait dans
la campagne sa douce invitation à la prière ou au
repos du soir.
```

It seems to be related to accents and newlines.

**Comment by roger64** [comment] 2019-10-23 08:58
I forgot to mention this:

The joint PDF has been corrected (this is the published version). On the above example, the word "où" has been corrected to "ou". But, as signalled,  the three words "oùaurepos" have indeed been glued in the bookmark.

For this reason
- to see the glued words, consider first the joint sdr file. Choose anyone of them.
- to reproduce the bug, put aside the sdr file, open the PDF, look for the faulty sentence and highlight it. The glued words should be reproduced in the new sdr file.

There a lots of them.

**Comment by pazos** [comment] 2020-04-15 12:56
Label this as a duplicate of #6045, which has a better description of the issue (related to newlines)

**Closed by pazos** 2020-04-15 12:56 UTC
Labels: bug
