### ISSUE TITLE
Idea: "disable/enable touch screen" button 

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#4035] opened 2018-06-30 05:40 UTC
* KOReader version: all
* Device: devices with both touch screen and physical buttons? E. G. Inkbooks, Pocketbooks, 

#### Issue

Sometimes (e.g.when you have small child) it might be useful to disable touch screen and use only physical keys. 

We could remap one of the physical buttons e. G. "back button" (which we already do map) to disable /enable Touch screen. 
This could be option to replace default behavior on that button. 

BTW Inkbook has such option in its settings but it doesn't work with koreader.

**Comment by Frenzie** [comment] 2018-06-30 06:08
Duplicate of #3978. ;-)

**Closed by Frenzie** 2018-06-30 06:08 UTC
