### ISSUE TITLE
KOReader hangs after some time of inactivity on Samsung Galaxy S6 Lite

### ISSUE THREAD

**Issue by lectral** [koreader/koreader#12811] opened 2024-11-28 12:54 UTC
* KOReader version: v 2024.11
* Device: Samsung Galaxy S6 Lite

#### Issue
KOReader hangs after some time (seconds to minutes) of inactivity. Especially in dual column mode. It works without issues on Galaxy M51 (smartphone).

#### Steps to reproduce
1. Open book.
2. Wait a minute or two.
3. Observe Reload icon appearing in top left corner.
4. Application hangs and is not responding.

##### `crash.log` (if applicable)
[crash.log](https://github.com/user-attachments/files/17948175/crash.log)

### adb
In adb the last message before freeze is:
<details>
  <summary>adb.log</summary>

```
{com.google.android.googlequicksearchbox/com.google.android.apps.gsa.nga.engine.viss.NgaService}
11-28 13:29:25.498  5589  7682 I ActivityManager: DSS OFF for com.google.android.googlequicksearchbox
11-28 13:29:25.612 15362 15392 V KOReader: _stepRerenderingAutomation( nil ), currently  3
11-28 13:29:26.614 15362 15392 V KOReader: _stepRerenderingAutomation( nil ), currently  3
11-28 13:29:27.070  5589  7682 I ActivityManager: Process com.android.settings.intelligence (pid 13699) has died: cch+99 CACC(74,942)
11-28 13:29:27.072  5589  7682 W ActivityManager: Scheduling restart of crashed service com.android.settings.intelligence/.suggestions.SuggestionService in 1000ms for connection
11-28 13:29:27.615 15362 15392 V KOReader: _stepRerenderingAutomation( nil ), currently  3
11-28 13:29:28.117  5589  5654 I ActivityManager: Start proc 15892:com.android.settings.intelligence/u11a82 for service {com.android.settings.intelligence/com.android.settings.intelligence.suggestions.SuggestionService}
11-28 13:29:28.203  5589  7634 I ActivityManager: DSS OFF for com.android.settings.intelligence
11-28 13:29:28.617 15362 15392 V KOReader: _stepRerenderingAutomation( nil ), currently  3
11-28 13:29:28.618 15362 15392 V KOReader: _stepRerenderingAutomation( 4 ), currently  3
11-28 13:29:28.618 15362 15392 V KOReader: _stepRerenderingAutomation 3 > 4
11-28 13:29:28.619 15362 15392 V KOReader: _refresh: Enqueued ui update for region 0 0 64 64 dithering: false
11-28 13:29:28.619 15362 15392 V KOReader: setDirty ui from widget ReaderUI w/ region 0 0 64 64 dithering: nil
11-28 13:29:28.620 15362 15392 V KOReader: painting widget: ReaderUI
11-28 13:29:28.622 15362 15392 V KOReader: readerview painting "2000x1200+0+0" to 0 0
11-28 13:29:28.623 15362 15392 V KOReader: CreDocument: goto page 460 flow 0
11-28 13:29:28.636 15362 15392 V KOReader: ImageWidget: _render'ing resources/icons/mdlight/cre.render.reload.svg 64 64
11-28 13:29:28.638 15362 15392 V KOReader: renderSVG resources/icons/mdlight/cre.render.reload.svg 1.3333333333333 48 48 > 64 64 0 0
11-28 13:29:28.640 15362 15392 V KOReader: cache image|resources/icons/mdlight/cre.render.reload.svg|64|64|alpha
11-28 13:29:28.641 15362 15392 V KOReader: ImageWidget: initial offsets 0 0
11-28 13:29:28.642 15362 15392 V KOReader: blitFrom 0 0 0 0 64 64
11-28 13:29:28.652 15362 15392 V KOReader: triggering refresh {
11-28 13:29:28.652 15362 15392 V KOReader:   mode = "ui",
11-28 13:29:28.652 15362 15392 V KOReader:   region = "64x64+0+0"
11-28 13:29:28.652 15362 15392 V KOReader: } --[[table: 0x7335a0afc8]]
</details>
```

**Comment by Frenzie** [comment] 2024-11-28 13:19
Probably the same issue as https://github.com/koreader/koreader/issues/12099

As a workaround you can disable partial rendering.

**Comment by pazos** [comment] 2024-11-28 19:52
Duplicate of #12099

**Closed by pazos** 2024-11-28 19:52 UTC
Labels: Android, duplicate
