### ISSUE TITLE
absolute font-size values have no effect

### ISSUE THREAD

**Issue by agaAdams** [koreader/koreader#2331] opened 2016-11-11 10:00 UTC
* KOReader version: v2015.11-677-g312d045
* Device: KA1

#### Issue
I'm not really sure this is a bug. Maybe it's supposed to work like this. I have an .epub file with fonts-size set to absolute values: medium, x-small, small, etc.
In nickel those font sizes a rendered as expected. KOReader does not differentiate between them. Only when I set font-size to percentage values I get the expected result - i.e. different font sizes on screen.
Any idea what might be causing this?

**Comment by KenMaltby** [comment] 2016-11-11 13:50
Those who expect their Kobo devices to function as they do with the stock software, who think that is the only proper way for it to work, might be happier using that software.  I for one, don't expect, or want my addon/alternative reading software to do everything the way it is done within Nickel.  KOReader has a number of tools/settings/menu settings to effect fonts.  Much more than "small-medium-large".

**Comment by Frenzie** [comment] 2016-11-11 14:14
@Ken This is part of the CSS spec. I'd expect it to function.
https://developer.mozilla.org/en/docs/Web/CSS/font-size

CSS support in CR isn't great, but this is the most basic part of the spec.

**Comment by agaAdams** [comment] 2016-11-11 14:38
@KenMaltby I'm just curious to find out why it doesn't work. It is quite a basic part of CSS specs and lots of stylesheets in my books use it.
If I found out what the problem is, I could try to find a solution or a workaround.

**Comment by Frenzie** [comment] 2016-11-11 20:28
I can confirm that this simple testcase doesn't work as expected. (Btw, it's always a good idea to include one.)

```html
<!DOCTYPE html>
<p>medium</p>
<p style="font-size:x-large">x-large</p>
<p style="font-size:x-small">x-small</p>
```

**Comment by Frenzie** [comment] 2016-11-11 20:53
A quick search suggests a fix would probably go somewhere around here: https://github.com/koreader/crengine/blob/a09aac18672f5f9c57d87457afbac205001ed793/crengine/src/lvstsheet.cpp#L297-L309

(and also that I'll have to recompile the program because larger and smaller may already be working properly?)

**Comment by frankyifei** [comment] 2016-11-12 05:28
https://idpf.github.io/a11y-guidelines/content/style/reference.html
absolute font size is not recommended by epub standards.

**Comment by Frenzie** [comment] 2016-11-12 09:00
@frankyifei Not the same thing. They might be called "absolute" in the spec, but small is defined as 8/9 of medium (and large as 6/5 of medium, and so on), so it really makes no difference whether you call it `small`, `.89em` or `89%` even though the latter are "relative" values.

**Comment by frankyifei** [comment] 2016-11-12 11:00
ok, you are right that it is relative value

**Comment by houqp** [comment] 2016-11-13 00:29
Interesting, so why does the epub standard discourage use of `x-small, xx-small`?

**Comment by Frenzie** [comment] 2016-11-13 08:04
I'll just show by example and all should become clear. =) Just check how legible those sizes are on your screen: https://jsfiddle.net/8t4ce3a7/2/

PS Actually it's legible enough on my desktop monitor and it would also be on my Kobo Aura H2O due to sufficiently reasonable DPI. Also the DejaVu Serif my Fx defaults to is quite legible even at small sizes. But the fact that my eyesight is (still) good is besides the point. My father probably wouldn't be able to read x-small without a magnifying glass, let alone xx-small.
```
<!DOCTYPE html>
<p style="font-size:xx-small"><strong>xx-small:</strong> Et ea ratione et enim. Natus rerum explicabo eligendi dolorum. Quia ex est quas modi. Est doloribus minima nihil veniam iste culpa qui nesciunt. Voluptatem quis et voluptates fugit ut dolorem voluptas. Omnis nihil praesentium nisi eum odit minus.…</p>
<p style="font-size:x-small"><strong>x-small:</strong> Et ea ratione et enim. Natus rerum explicabo eligendi dolorum. Quia ex est quas modi. Est doloribus minima nihil veniam iste culpa qui nesciunt. Voluptatem quis et voluptates fugit ut dolorem voluptas. Omnis nihil praesentium nisi eum odit minus.…</p>
<p style="font-size:small"><strong>small:</strong> Et ea ratione et enim. Natus rerum explicabo eligendi dolorum. Quia ex est quas modi. Est doloribus minima nihil veniam iste culpa qui nesciunt. Voluptatem quis et voluptates fugit ut dolorem voluptas. Omnis nihil praesentium nisi eum odit minus.…</p>
<p style="font-size:medium"><strong>medium:</strong> Et ea ratione et enim. Natus rerum explicabo eligendi dolorum. Quia ex est quas modi. Est doloribus minima nihil veniam iste culpa qui nesciunt. Voluptatem quis et voluptates fugit ut dolorem voluptas. Omnis nihil praesentium nisi eum odit minus.…</p>
<p style="font-size:large"><strong>large:</strong> Et ea ratione et enim. Natus rerum explicabo eligendi dolorum. Quia ex est quas modi. Est doloribus minima nihil veniam iste culpa qui nesciunt. Voluptatem quis et voluptates fugit ut dolorem voluptas. Omnis nihil praesentium nisi eum odit minus.…</p>
```

**Comment by houqp** [comment] 2016-11-13 08:10
Ha I see. That's a really bad reading experience.

**Comment by houqp** [comment] 2016-11-13 08:11
But I think we should at least support medium and small?

**Comment by Frenzie** [comment] 2016-11-13 08:24
I'd say ideally support everything coupled with a minimum font-size, or in lieu of that support xx-small and x-small and just have them be the same size as small. Having xx-small and x-small display as medium would just be weird at best! =)

But yeah, this stuff is one of the most basic parts of the CSS spec. It was already [supported in IE3](http://endoframe.com/css/ie3#font-size). It's amazing that no one noticed until now.

**Comment by houqp** [comment] 2016-11-13 09:04
yeah, i like the minimum font-size approach.

**Comment by agaAdams** [comment] 2016-11-13 10:40
I like the way calibre does it when converting E-Books. It basically lets you set a base font size and scales the other font sizes appropriately.

**Comment by poire-z** [comment] 2018-10-16 20:56
Fixed with https://github.com/koreader/crengine/pull/236 , discussed in https://github.com/koreader/crengine/pull/142#issuecomment-427630601

**Closed by poire-z** 2018-10-16 20:56 UTC
Labels: bug, crengine
