### ISSUE TITLE
Progress sync plugin registration doesn't work - unknown server

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3158] opened 2017-09-02 07:03 UTC
* KOReader version:https://github.com/koreader/koreader/releases/tag/v2017.08.21-nightly
* Device: phone with android 7, Inkbook prime (android 4)

#### Issue

"Progress sync" plugin registration doesn't work. 
It says : "Unknown server error" 

Did server connection details change? 

#### Steps to reproduce. 
Open koreader. Try to register in "Progress sync"

**Comment by Frenzie** [comment] 2017-09-02 07:17
It's a duplicate of #2178 (so closing in favor of that one). Also see https://github.com/koreader/koreader/issues/2889#issuecomment-324294852

Besides a lack of time for the past two weeks I'm slightly unsure about trying to mess with this as I wouldn't want to cause any data loss. Supposedly if you generate a key with `-extensions ssl_client` (on the server side) then it should work.

**Closed by Frenzie** 2017-09-02 07:17 UTC
