### ISSUE TITLE
Some folders not found when compiling emulator inside a Debian under Windows 10 WS2

### ISSUE THREAD

**Issue by rfog** [koreader/koreader#6356] opened 2020-07-07 18:35 UTC
* KOReader version: compile emulator
* Device: N/A

#### Issue

/bin/bash: line 0: cd: koreader-emulator--debug/koreader/spec: No such file or directory
cd koreader-emulator--debug/koreader/spec/front/unit && test -e data || \
        ln -sf ../../test ./data
/bin/bash: line 0: cd: koreader-emulator--debug/koreader/spec/front/unit: No such file or directory
for f in reader.lua setupkoenv.lua frontend resources defaults.lua datastorage.lua l10n tools README.md COPYING; do \
        ln -sf ../../$f koreader-emulator--debug/koreader/; \
done
[*] Install plugins
cp -r plugins/. koreader-emulator--debug/koreader/plugins/.
cp: cannot create directory 'koreader-emulator--debug/koreader/plugins/.': No such file or directory
make: *** [Makefile:84: all] Error 1

#### Steps to reproduce

Follow instructions to build the emulator under Windows 10 WSL2 running a Debian from page https://github.com/koreader/koreader/blob/master/doc/Building.md

##### `crash.log` (if applicable)
-- Generating done
-- Build files have been written to: /home/rfog/koreader/base/thirdparty/lua-rapidjson/build/x86_64-linux-gnu-debug
make[2]: Entering directory '/home/rfog/koreader/base/thirdparty/lua-rapidjson/build/x86_64-linux-gnu-debug'
make[3]: Entering directory '/home/rfog/koreader/base/thirdparty/lua-rapidjson/build/x86_64-linux-gnu-debug'
make[4]: Entering directory '/home/rfog/koreader/base/thirdparty/lua-rapidjson/build/x86_64-linux-gnu-debug'
make[4]: Leaving directory '/home/rfog/koreader/base/thirdparty/lua-rapidjson/build/x86_64-linux-gnu-debug'
[100%] Built target lua-rapidjson
make[3]: Leaving directory '/home/rfog/koreader/base/thirdparty/lua-rapidjson/build/x86_64-linux-gnu-debug'
make[2]: Leaving directory '/home/rfog/koreader/base/thirdparty/lua-rapidjson/build/x86_64-linux-gnu-debug'
# set up some needed paths and links
install -d build/x86_64-linux-gnu-debug/{cache,history,clipboard,fonts} /home/rfog/koreader/base/build/x86_64-linux-gnu-debug/plugins/evernote.koplugin/thrift
ln -sf /home/rfog/koreader/base/thirdparty/kpvcrlib/cr3.css build/x86_64-linux-gnu-debug/data/
# setup Evernote SDK
cd /home/rfog/koreader/base/thirdparty/evernote-sdk-lua/build/x86_64-linux-gnu-debug/evernote-sdk-lua-prefix/src/evernote-sdk-lua && \
        cp -r *.lua evernote /home/rfog/koreader/base/build/x86_64-linux-gnu-debug/plugins/evernote.koplugin && \
        cp thrift/*.lua /home/rfog/koreader/base/build/x86_64-linux-gnu-debug/plugins/evernote.koplugin/thrift
test -e build/x86_64-linux-gnu-debug/rocks/share/lua/5.1/re.lua && chmod 664 build/x86_64-linux-gnu-debug/rocks/share/lua/5.1/re.lua || true  # hot fix re.lua permission
make[1]: Leaving directory '/home/rfog/koreader/base'
install -d koreader-emulator--debug/koreader
rm -f koreader-emulator--debug/koreader/git-rev; echo "v2020.06-40-g580b38e7_2020-07-05" > koreader-emulator--debug/koreader/git-rev
cp -f base/ev_replay.py koreader-emulator--debug/koreader/
[*] create symlink instead of copying files in development mode
cd koreader-emulator--debug/koreader && \
        ln -sf ../../base/build/-debug/* .
[*] install front spec only for the emulator
cd koreader-emulator--debug/koreader/spec && test -e front || \
        ln -sf ../../../../spec ./front
/bin/bash: line 0: cd: koreader-emulator--debug/koreader/spec: No such file or directory
cd koreader-emulator--debug/koreader/spec/front/unit && test -e data || \
        ln -sf ../../test ./data
/bin/bash: line 0: cd: koreader-emulator--debug/koreader/spec/front/unit: No such file or directory
for f in reader.lua setupkoenv.lua frontend resources defaults.lua datastorage.lua l10n tools README.md COPYING; do \
        ln -sf ../../$f koreader-emulator--debug/koreader/; \
done
[*] Install plugins
cp -r plugins/. koreader-emulator--debug/koreader/plugins/.
cp: cannot create directory 'koreader-emulator--debug/koreader/plugins/.': No such file or directory
make: *** [Makefile:84: all] Error 1

**Comment by Frenzie** [comment] 2020-07-07 19:19
I don't think there's a need to open separate issues. That's most probably a simple duplicate of #6354, and even if it turns out not to be literally the exact same issue it's not distinct in a particularly relevant manner. ;-)

**Closed by Frenzie** 2020-07-07 19:19 UTC

**Comment by rfog** [comment] 2020-07-08 08:13
This is different from #6354. See https://github.com/koreader/koreader/issues/6354#issuecomment-655363921

Please reopen.

**Comment by Frenzie** [comment] 2020-07-08 10:36
@rfog Separate issues for what's simply a WSL2 build failing just serve as noise.
