### ISSUE TITLE
在登录同步服务器的时候打开一本之前同步过的书会卡死然后崩溃出去

### ISSUE THREAD

**Issue by xsdjt** [koreader/koreader#10327] opened 2023-04-14 09:30 UTC
* KOReader version: [KOReader 2023.03 "Cherry Blossom"](https://github.com/koreader/koreader/releases/tag/v2023.03)
* Device: 安卓手机

#### Issue
打开书籍后等待一段时间或者注销同步服务器就不会出现卡死的现象

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment] 2023-04-14 20:07
> Opening a previously synced book while logged into the sync server will get stuck and crash out
> 
> Waiting for a while after opening a book or logging out of the sync server will not cause the jamming phenomenon

Likely a duplicate of <https://github.com/koreader/koreader/issues/10302>.

**Comment by xsdjt** [comment] 2023-04-20 20:06
Found a good way to sync folders across devices by using onedrive's cloud storage and then downloading the onesync software from the Google Store.

**Comment by Frenzie** [comment] 2023-04-20 20:08
I'll close this then (mainly due to duplicate status).

**Closed by Frenzie** 2023-04-20 20:08 UTC
Labels: duplicate, Plugin
