### ISSUE TITLE
Pen annotation support

### ISSUE THREAD

**Issue by krishrong** [koreader/koreader#5690] opened 2019-12-15 15:00 UTC
At present, there is an increase of larger screen e-reader(>=7.8 inch) with a pen for annotation in the market. I wonder that it is the proper time to start developing the pen-supporting annotation function.

**Comment by WaseemAlkurdi** [comment] 2019-12-15 16:06
@krishrong
I second this. I sorely miss that, even on a 6" Kindle.

**Comment by pazos** [comment] 2019-12-15 16:17
duplicate of #2633

**Closed by pazos** 2019-12-15 16:17 UTC
