### ISSUE TITLE
FR: Update clock when waking up

### ISSUE THREAD

**Issue by Jellby** [koreader/koreader#7643] opened 2021-05-07 06:57 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
When waking up the device (Kobo Aura) from sleep, the clock in the status bar is not updated until the next page turn.
In normal use it makes sense to update the clock on page turns only (maybe there's a setting for that), but it would make sense to update it on waking up too... at least if there was a "screensaver" so the whole screen is updated anyway.

**Describe the solution you'd like**
Update the clock (and battery status) on wake up. I guess that would mean updating the whole status bar, which should be OK unless the current book has been modified or removed, which would be calling for problems anyway.

**Comment by Frenzie** [comment] 2021-05-07 08:59
You're not using a version from ca. 2017 or 2018 by any chance? >_>

**Comment by Frenzie** [comment] 2021-05-07 09:01
Other than an extremely old version or a bug, maybe you've disabled "auto refresh" for some reason?

**Comment by Jellby** [comment] 2021-05-07 12:36
But auto refresh updates the status bar every minute (when the clock changes), and I don't want that. I still want to update only when turning pages AND when waking up.

**Comment by NiLuJe** [comment] 2021-05-07 12:39
It's orthogonal to auto-refresh, and should definitely happen on *recent* nightlies (as in, I fixed it a few days ago).

**Comment by Jellby** [comment] 2021-05-07 12:59
OK, that makes sense, I'm just using the latest stable.

**Comment by ichnilatis-gr** [comment] 2021-05-17 12:40
- KOReader version: 2021.4
- Device: Pocketbook Touch Lux 5 (PB628)

I have noticed that in my device "auto refresh" doesn't update the clock and buttery status in status bar every minute, but only when I turn pages. Is this normal?

**Comment by NiLuJe** [comment] 2021-05-17 15:29
> It's orthogonal to auto-refresh, and should definitely happen on _recent_ nightlies (as in, I fixed it a few days ago).

**Comment by ichnilatis-gr** [comment] 2021-05-18 09:17
Thank you.
Τo be more precise, I have v. 2021.04-48-gd303fdf_2021-05-08. Maybe the problem was fixed after that. I'll download a newer version.

**Comment by NiLuJe** [comment] 2021-05-18 16:16
Oh, wait, you're talking about a different thing, actually.

This issue was specifically about refreshing on resume, regardless of auto_refresh.

You appear to be having an issue with auto_refresh *itself* (which, err, hasn't been touched in a while, and I definitely can't reproduce any issue with it).

**Comment by NiLuJe** [comment] 2021-05-18 16:17
(In any case: verbose debug logs, the footer auto-refresh is awfully mouthy).

**Comment by ichnilatis-gr** [comment] 2021-05-19 08:15
You've right, I'm talking about auto-refresh of the status bar, without changing page. Is this possible?

**Comment by NiLuJe** [comment] 2021-05-19 16:20
That's what the auto_refresh horribleness (;p) is for. And it wortks on my end ;).

**Comment by Jellby** [comment] 2021-05-30 13:49
Hm... I have 2021.05, is it supposed to be working? Because it isn't. But the issue is still open, so I guess it's still not fixed/implemented? (I mean the clock update when waking up, not the auto-refresh.)

**Comment by NiLuJe** [comment] 2021-05-30 16:24
I don't recall if it landed in 2021.05, but probably?

It definitely works over here on master, and it's trivial enough that I don't see anything that could break it, short of a custom plugin breaking the Resume Event :?

**Comment by Jellby** [comment] 2021-05-30 16:39
I don't think I have any such plugin. The only related specialty I have is a 3 second delay between wake up and "screensaver" off (which works fine).

**Comment by NiLuJe** [comment] 2021-05-30 18:01
And I just double-checked that and it works fine, too ;).

**Comment by Jellby** [comment] 2021-06-29 18:41
It seems to be OK with 2021.06, so I guess this can be closed.

**Comment by Jellby** [comment] 2021-07-01 07:01
I spoke too soon, as it seemed to worked at least twice, but now it hasn't been. I first noticed while the device was charging. (First thing, it seems I have to wake it up so it can start charging, if I simply plug it in while sleeping it doesn't charge. Is this normal?) I left it charging and after ~30 min it went to sleep. I woke it up while still plugged and the time was not updated. Since then, the time doesn't update when waking up.

**Comment by NiLuJe** [comment] 2021-07-01 15:21
What are you using as an indication that it's "charging" or not?

**Comment by Jellby** [comment] 2021-07-01 15:32
> What are you using as an indication that it's "charging" or not?

So battery is 60% (according to the battery indicator in KOReader).
I plug the reader (with closed cover, presumably sleeping).
After a few hours I unplug it.
I open the reader, read a few pages, and the battery indicator still shows 60%.

If I plug it with the cover open and making sure the reader is awake, after a few hours the battery shows 100% as expected. At least this has worked every time I have consciously tried it.

**Comment by NiLuJe** [comment] 2021-07-01 15:36
The battery gauge is ridiculously useless on Kobos, so, possibly not a great indicator. What *should* be different is the "lightning" icon to denote charging.

**Comment by Jellby** [comment] 2021-07-01 16:34
Yeah, but I cannot really see the lightning icon while sleeping (with "screensaver" and closed cover). Anyway, that was an aside, this issue is about something else ;)

**Comment by NiLuJe** [comment] 2021-07-01 17:40
But it might very well be related: if something is wonky (which is often the case because sleepovers), we might very well never send an actual resume event, hence the lack of refresh ;).

**Comment by Jellby** [comment] 2021-07-01 18:02
You of course know the details better than I, but wouldn't the fact that screensaver is dismissed (and that I can use the reader normally) mean that at least some kind of resume event has been sent? I get the same problem of non-updated clock when sleeping/waking up with the hardware button (and never closing the sleepcover in between), by the way.

**Comment by NiLuJe** [comment] 2021-07-01 18:09
Possibly, unless something's chewing the event halfway through. Any custom plugins?

Hard to say what's happening without verbose debug logs, but I can't see anything wrong, and I definitely can't reproduce it anywhere.

**Comment by Jellby** [comment] 2021-07-01 18:29
No custom plugin that I know of. In "Plugin management" the following are enabled:
Auto suspend
Autoturn
Background runner
Battery statistics
Calibre
Cover browser
Gestures
Keep alive
Move to archive
OPDS
Profiles
Progress sync
QR from clipboard
Read timer
Reader statistics
SSH
Send to eBook
System statistics
Terminal
Text editor
Time sync
Tweak document settings

I guess that's mainly the default, because I don't think I need most of them.

Any way to enable debug logs that could help? Looking into `crash.log` I see this around one sleep/wake up event (typed in, not copy-pasted, there could be some mistake):

```
07/01/21-08:47:52 INFO  Kobo suspend: going to sleep . . .
07/01/21-08:47:52 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
07/01/21-08:47:54 INFO  Kobo suspend: waited for 2s because of reasons . . .
07/01/21-08:47:55 INFO  Kobo suspend: synced FS
07/01/21-08:47:55 INFO  Kobo suspend: asking for a suspend to RAM . . .
07/01/21-08:47:55 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
07/01/21-19:54:40 INFO  Kobo suspend: woke up!
07/01/21-19:54:40 INFO  Kobo resume: clean up after wakeup
07/01/21-19:54:40 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
07/01/21-19:54:47 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
07/01/21-19:54:52 INFO  WakeupMgr: scheduling wakeup in 259200
07/01/21-19:55:08 INFO  Kobo suspend: going to sleep . . .
```

**Comment by NiLuJe** [comment] 2021-07-01 18:46
In the FM, Tools > More Tools > Developer options; tick both & restart KOreader ;).

**Comment by Jellby** [comment] 2021-07-01 19:53
(How confusing that the menu is different in a book and in the file manager...)
OK, here's a verbose log around a sleep/resume. I hope that's enough, if not, I have the full `crash.log`: [crash_crop.log](https://github.com/koreader/koreader/files/6750476/crash_crop.log)

**Comment by NiLuJe** [comment] 2021-07-01 23:50
Huh, yeah, not seeing the refresh, but the Resume event looks sane...

So, let's try again w/ more debugging :)

```diff
diff --git a/frontend/apps/reader/modules/readerfooter.lua b/frontend/apps/reader/modules/readerfooter.lua
index d515ca6be..aec3b0d66 100644
--- a/frontend/apps/reader/modules/readerfooter.lua
+++ b/frontend/apps/reader/modules/readerfooter.lua
@@ -2249,6 +2249,7 @@ function ReaderFooter:refreshFooter(refresh, signal)
 end
 
 function ReaderFooter:onResume()
+    logger.dbg("ReaderFooter:onResume", self.view.footer_visible)
     -- Don't repaint the footer until OutOfScreenSaver if screensaver_delay is enabled...
     local screensaver_delay = G_reader_settings:readSetting("screensaver_delay")
     if screensaver_delay and screensaver_delay ~= "disable" then
@@ -2262,6 +2263,7 @@ function ReaderFooter:onResume()
 end
 
 function ReaderFooter:onOutOfScreenSaver()
+    logger.dbg("ReaderFooter:onOutOfScreenSaver", self._delayed_screensaver)
     if not self._delayed_screensaver then
         return
     end
```

**Comment by Jellby** [comment] 2021-07-02 16:06
Here you go. It doesn't seem to go into `ReaderFooter:onOutOfScreenSaver`: 
[crash_crop.log](https://github.com/koreader/koreader/files/6755744/crash_crop.log)

**Comment by NiLuJe** [comment] 2021-07-02 18:51
Just to double-check, you currently have the screensaver_delay set to 3s, correct?

Does this help?

```diff
diff --git a/frontend/apps/reader/modules/readerfooter.lua b/frontend/apps/reader/modules/readerfooter.lua
index d515ca6be..aec3b0d66 100644
--- a/frontend/apps/reader/modules/readerfooter.lua
+++ b/frontend/apps/reader/modules/readerfooter.lua
@@ -2249,6 +2249,7 @@ function ReaderFooter:refreshFooter(refresh, signal)
 end
 
 function ReaderFooter:onResume()
+    logger.dbg("ReaderFooter:onResume", self.view.footer_visible)
     -- Don't repaint the footer until OutOfScreenSaver if screensaver_delay is enabled...
     local screensaver_delay = G_reader_settings:readSetting("screensaver_delay")
     if screensaver_delay and screensaver_delay ~= "disable" then
@@ -2262,6 +2263,7 @@ function ReaderFooter:onResume()
 end
 
 function ReaderFooter:onOutOfScreenSaver()
+    logger.dbg("ReaderFooter:onOutOfScreenSaver", self._delayed_screensaver)
     if not self._delayed_screensaver then
         return
     end
diff --git a/frontend/ui/widget/screensaverwidget.lua b/frontend/ui/widget/screensaverwidget.lua
index 2d004241a..b71e92824 100644
--- a/frontend/ui/widget/screensaverwidget.lua
+++ b/frontend/ui/widget/screensaverwidget.lua
@@ -74,8 +74,6 @@ end
 
 function ScreenSaverWidget:onClose()
     UIManager:close(self, "full")
-    -- Will come after the Resume event (how much later depends on screensaver_delay).
-    UIManager:broadcastEvent(Event:new("OutOfScreenSaver"))
     return true
 end
 
@@ -85,6 +83,9 @@ function ScreenSaverWidget:onAnyKeyPressed()
 end
 
 function ScreenSaverWidget:onCloseWidget()
+    -- Will come after the Resume event (how much later depends on screensaver_delay).
+    UIManager:broadcastEvent(Event:new("OutOfScreenSaver"))
+
     UIManager:setDirty(nil, function()
         return "full", self.main_frame.dimen
     end)
```

**Comment by Jellby** [comment] 2021-07-02 20:02
Yes, 3s delay. Quick test with the new change seemed to work now, I'll report back tomorrow after I test a few more times.

**Comment by Jellby** [comment] 2021-07-03 06:40
OK, it's tomorrow now, the reader has slept and woken up a few times and the time has always been updated, so for now that seems to fix it.

**Closed** 2021-07-05 02:56 UTC
