### ISSUE TITLE
File manager

### ISSUE THREAD

**Issue by druss67** [koreader/koreader#1459] opened 2015-03-18 20:15 UTC
Is it possible to see all the files into the file manager ? I ticked the setting "Show hidden files" but I am not able to see all of them.

Regards
Druss

**Comment by houqp** [comment] 2015-03-20 09:07
I don't think this is configurable. Be default, koreader only shows the files that it can open. Why do you want to see files that cannot be opened by koreader?

**Comment by druss67** [comment] 2015-03-20 20:54
I have no file manager on my pocketbook and sometimes this is helpful to modify some .cfg files.

**Comment by chrox** [comment] 2015-03-21 04:38
The file manager provided by koreader can only list documents that koreader can open for reading and koreader cannot edit any document format. So not showing all files in the filemanager is by design. I'm closing this now.

**Closed by chrox** 2015-03-21 04:38 UTC

**Comment by Markismus** [comment] 2015-03-21 17:07
Of course you could duplicate the line for `txt`-files [here](https://github.com/koreader/koreader/blob/master/frontend/document/credocument.lua#L437) and change the extension to `cfg`.
Now koreader opens it as a text file with the coolreader engine and you can see it in filemanager.

This is a nice hack. I use it all the time for reading script-files. So yes there is a way. No, this is not a koreader feature.

**Comment by druss67** [comment] 2015-03-21 21:00
Ouah, thanks Markismus, it works. 
I am a little bit surprise that's nobody adapt an app like Midnight Commander or another file manager to the eReader in general. Sometimes, for testing, i would like to adapt some config file but I can't because I have no PC near me, and nothing on my eReader to do this.

**Comment by Markismus** [comment] 2015-03-21 22:33
On Kobo devices there is a notepad program as part of the Kobo Laucher installation. The restriction with that was that you will have to copy files to the directory of the notepad executable, edit them and move them back. Don't know whether that has been corrected yet.
