### ISSUE TITLE
Wikipedia cannot open Wi-Fi

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#6430] opened 2020-07-25 14:53 UTC
* KOReader version: 2020.07.1
* Device: Kobo Forma

#### Issue

This may be related to #6429

When tapping on Wikipedia search, the prompt to connect to Wi-Fi appears every time even if I have connected to Wi-Fi previously or not. If I select Connect, the message shows a successful connection to Wi Fi but nothing more happens. IF I try again to do a wikipedia search, the same box that asks to activate wi-fi appears. So the process begins again.

Might be a WiFi issue here, not specific to wikipedia.

#### Steps to reproduce

Connect to wi-fi
Go to wikipedia searh, tap on it.
It asks to connect wifi, although it is already connected.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by pazos** [comment] 2020-07-25 15:02
Duplicate of #6429

**Closed by pazos** 2020-07-25 15:02 UTC
