### ISSUE TITLE
Android: EOL versions and devices

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#10614] opened 2023-06-25 23:24 UTC
Keeps track of @benoit-pierre work to update the android toolchain.

https://github.com/koreader/koreader-base/pull/1620
https://github.com/koreader/android-luajit-launcher/pull/419
https://github.com/koreader/koreader/pull/10610

With these in we **remove support** for **Android 4.0 - Android 4.2** The new minimum supported version will be Jelly Bean MR2 (API18/Android 4.3)

@ users with affected devices:

Please make sure the next monthly/stable release (v2023.06) works as well as previous releases. That will be the last one supporting your device, unless there's a point release to fix a bug regression.

Please keep this ticket open as a hub for discussion *before* the commits above hit a monthly release :)

**Comment by pazos** [comment] 2023-07-23 16:46
@NiLuJe: I'm going to build a 2023.06.1 variant for https://github.com/koreader/koreader/issues/8482#issuecomment-1624416826 and let it stay for a while in the rare event of somebody reporting a working device with one of the supported drivers on EOL devices.

Which commits do I need to cherry-pick in order to avoid the kosync issue?

**Comment by NiLuJe** [comment] 2023-07-23 18:07
That'd be #10669 & #10697

**Comment by zxkmm** [comment] 2023-07-28 03:11
Hello :) It seems the last build (2023.06.01) for EOL devices has a bug on my BOOX C67ML-Carta:  
When Wi-Fi is on, all works and all good.    
When Wi-Fi is off, when press the file/library button aka the last button in top bar, it freezes the app.   
Not able to reproduce on 2023.06 tho.

**Comment by NiLuJe** [comment] 2023-07-28 16:52
That is precisely what we were discussing right above your message ;).

And, yes, 2023.06 is unaffected :).

**Comment by pazos** [comment] 2023-09-01 21:24
@linsui: the v2023.08 version has changed the build requirements. Now it requires **ndk23** instead of **ndk15**.

**Comment by linsui** [comment] 2023-09-02 03:06
Thanks, it has been fixed in https://gitlab.com/fdroid/fdroiddata/-/commit/51a901d47ea8c32fd33521f81476c739f8ffa2ca.

**Closed** 2023-09-19 12:32 UTC
Labels: Android, firmware, chore

**Comment by Gabriel85** [comment] 2023-10-11 02:23
I have a question: what are the long time plans for supporting legacy Android versions?

I just bought a new eReader with Android 4.4 and it would be a pity if it isn't supported anymore soon! I remember until a couple of years ago it was normal that new devices came out with even older Android versions and the usage time of an eReader should be at least 5 years, if not longer..

**Comment by NiLuJe** [comment] 2023-10-11 04:28
Until it starts to be a PITA to maintain, basically.

(Will likely be tied to NDK revisions).

**Comment by Gabriel85** [comment] 2023-10-11 16:02
Thank you for the reply, I was hoping for at least another 5 years.
Is there any technical reason why a newer toolchain must be used for an app
which isn't even in the Playstore?
And do you have any numbers about on which Android versions Koreader is
actually used? As far as I remember the majority of Android eReaders who
were sold in the last 10 years are on 4.4 or older. Just in the last years
it became common to use never Android versions. And I think the average
usage time of an eReader is over 7 years (for good reasons)!

And I haven't seen anything which runs on newer Android versions, which
deserves the name eReader. For me those are tablets with an eInk screen. 2
years ago I bought one of those and I send it back because of the horrible
battery life. Instead I bought a 4 year old model with Android 4.4 and
about 8 times less CPU power. The result: about 20% less effective speed in
Koreader and 3-5 times longer battery life! And this is why I bought last
week a larger one from the same generation, as long as they are still
available. Or maybe I should return it as long as I still can if it won't
be supported anymore soon?

So please don't forget us people who use and love Koreader for what it is:
the best reading app for actual (low-spec) eReaders! And not ePub app No.
1023 for Android. Thank you! ❤️

**Comment by Frenzie** [comment] 2023-10-11 16:59
@Gabriel85 
> Is there any technical reason why a newer toolchain must be used for an app
which isn't even in the Playstore?

The Play Store requirements aren't necessarily overly different from the requirements Google builds into Android itself. For example, on Android 14 you'll need `adb install --bypass-low-target-sdk-block etc` to install an app that targets anything lower than Android 7 (API level 24).

That specifically isn't a problem because [we already target API level 30](https://github.com/koreader/android-luajit-launcher/blob/ecead677cedc25a67b5024e45b3b621455629f6a/build.gradle#L2-L4) but eventually there will come a choice between e.g. Android 18 and Android 4.4.

But note that I didn't say it won't be five years. Only that I'm reasonably confident there won't be any choices for the next couple of years.

**Comment by pazos** [comment] 2023-10-11 18:30
> I have a question: what are the long time plans for supporting legacy Android versions?

Nobody knows, besides Google :p.

NDK now is recent enough and even in the future when we require a new one that doesn't support older android versions we can still build for them.

For instance, [Coolreader uses ndkr21](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.coolreader.fdroid.yml#L39), which doesn't support Android 4.0 and yet their minimumSdk is still Android 3.

The main reason to EOL legacy 4.0-4.2 was NDK **and** that we wouldn't like to have more maintenance burden.

Current NDK r25 has the minimum supported API on KitKat.

Also there's no clear incentive to bump minimumApi without killing a bunch of legacy devices.

All the fancy stuff (unversioned shared libraries that can be dloaded from the APK without uncompressing/duplicating them first) would require a bump to API23-25, IIRC, and that's not planned in the near future.

Maybe when we reach android 20 will be the time to deprecate android 6.

> That specifically isn't a problem because [we already target API level 30](https://github.com/koreader/android-luajit-launcher/blob/ecead677cedc25a67b5024e45b3b621455629f6a/build.gradle#L2-L4) but eventually there will come a choice between e.g. Android 18 and Android 4.4.

The targetSdk can be bumped to the last one (API33), but there's no good reason to do so for the moment.

**Comment by benoit-pierre** [comment] 2023-10-11 19:57
> All the fancy stuff (unversioned shared libraries that can be dloaded from the APK without uncompressing/duplicating them first) would require a bump to API23-25, IIRC, […]

Really? Because that's what I do on my meson branch.

**Comment by pazos** [comment] 2023-10-11 20:35
> > All the fancy stuff (unversioned shared libraries that can be dloaded from the APK without uncompressing/duplicating them first) would require a bump to API23-25, IIRC, […]
> 
> Really? Because that's what I do on my meson branch.

I wouldn't mind to be wrong :smile: 

Unversioned shared libraries, as in https://github.com/koreader/koreader-base/commit/bc82f605ce00eee09656ec6e2cfdbdb08ecf29b3 required a sane dlopen, that's not available on android 4.x.

As I stated in https://github.com/koreader/koreader-base/issues/1237 I'm happily unaware of most build system trickeries, so, like with the NDK bump, please make the magic happen :D

**Comment by Frenzie** [comment] 2023-10-11 20:36
> Really? Because that's what I do on my meson branch.

Doesn't necessarily mean it'll actually work on Android <6. ;-) Would be cool if it did though!

**Comment by NiLuJe** [comment] 2023-10-11 20:44
I seem to remember testing the DIY DT_NEEDED dlopen stuff on ICS, so, yeah, definitely borked as hell there ;).

**Comment by benoit-pierre** [comment] 2023-10-11 21:05
> Unversioned shared libraries, as in [koreader/koreader-base@bc82f60](https://github.com/koreader/koreader-base/commit/bc82f605ce00eee09656ec6e2cfdbdb08ecf29b3) required a sane dlopen, that's not available on android 4.x.
> 
> As I stated in [koreader/koreader-base#1237](https://github.com/koreader/koreader-base/issues/1237) I'm happily unaware of most build system trickeries, so, like with the NDK bump, please make the magic happen :D

Monolibtic mode FTW \o/

Also, `…/files/libs` is a symlink to the APK native libraries directory.

> Doesn't necessarily mean it'll actually work on Android <6. ;-) Would be cool if it did though!

Works with the emulator on x86 & ARM with API level 18 (Android 4.3 / Jelly Bean MR2).

**Comment by Gabriel85** [comment] 2023-10-12 05:52
> Note that Android 4.4 (KitKat) is already 10 years old!

Like the hardware of most proper eReaders. At least until recently, the kernels of Kobo and Pocketbook where about the same age. I think Pocketbook still uses a 3.0 kernel. And why not?

> The Play Store requirements aren't necessarily overly different from the requirements Google builds into Android itself. For example, on Android 14 you'll need `adb install --bypass-low-target-sdk-block etc` to install an app that targets anything lower than Android 7 (API level 24).

Oh that is new to me, but Android has at least until Android 13 excellent backwards compatibility. I am still using several apps which were targeted for Android 2.x. Even things like launchers or low level system tools still work surprisingly well, and certainly a normal app like Koreader should work practically forever (as long as there is a 64bit version).

> That specifically isn't a problem because [we already target API level 30](https://github.com/koreader/android-luajit-launcher/blob/ecead677cedc25a67b5024e45b3b621455629f6a/build.gradle#L2-L4) but eventually there will come a choice between e.g. Android 18 and Android 4.4.

I am wondering why do you target such a new version? There seems to me little benefit for that for an app which is not in the Playstore. For example if you would target API level 28, Koreader should be able to toggle Wifi ON/OFF again.

> For instance, [Coolreader uses ndkr21](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.coolreader.fdroid.yml#L39), which doesn't support Android 4.0 and yet their minimumSdk is still Android 3.

Yes that is what I mean! I am sure they are proud of that. And why not? Every Android 3 device is still perfectly fine for reading ebooks or comics. And as a Android 4.4 fan I can say there are still some maintained apps around with support for Android 4.x and 2.x, even on the Playstore. There is even an app which targets API level 39 and has min level of 1!

Another important thing is that phones from that area have unique advantages, like being smaller, having exchangeable batteries and even headphone jacks. For example my good old Xperia Ray, which I am running on 4.4, combines all of those, while being less than 1/3 of the size of a modern smartphone! I recently read on XDA that there are even still people around (or again) who are using it as daily driver.
They just don't make devices like that anymore...

**Comment by Frenzie** [comment] 2023-10-12 07:03
> I am wondering why do you target such a new version? There seems to me little benefit for that for an app which is not in the Playstore. For example if you would target API level 28, Koreader should be able to toggle Wifi ON/OFF again.

I think you may be mixing meanings of the word target.

But as I said, <https://developer.android.com/about/versions/14/behavior-changes-all> and its equivalent for every previous version of Android is not the Play Store.

> Another important thing is that phones from that area have unique advantages, like being smaller, having exchangeable batteries and even headphone jacks. For example my good old Xperia Ray, which I am running on 4.4, combines all of those, while being less than 1/3 of the size of a modern smartphone! 

The touchscreen on my Ray broke, only registering touches on the bottom half (or vice versa), so I put it with the recycling a couple of years ago. I thought it ran better on Android 2.3 and 6 though. ;-)

**Comment by pazos** [comment] 2023-12-30 20:04
In case somebody wants to build the last version for eol devices, I pushed

https://github.com/pazos/koreader/tree/android-eol
https://github.com/pazos/koreader-base/tree/android-eol
https://github.com/pazos/android-luajit-launcher/tree/android-eol

It comes handy in case there's a request for EPD/lights on a compatible but unsupported device.
