### ISSUE TITLE
Screen updated (slowly) in 6 portions on KA1

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5571] opened 2019-11-06 15:17 UTC
* KOReader version: v2019.10-33-gf1f75c5_2019-11-06/   
* Device: KA1

#### Issue
This behaviour might be of interest, my feeling is that it has become more common lately: https://drive.google.com/open?id=1zadDr7JMw3v8LpP7oPo8IldjbYArBqGi
And another one: https://drive.google.com/open?id=1U9nuBimBhBHsEyVRwx0J0VJcB1DHyR_y

Here is a cropped copy of the book in the first video: 
[Roberts, Andrew - Leadership in War.zip](https://github.com/koreader/koreader/files/3814631/Roberts.Andrew.-.Leadership.in.War.zip)

With 2 exceptions (one from 2014 and one from 2017), I think I've seen this happen only with newer books (published 2018 or 2019).  Though I haven't checked my whole library.

I tested my old Kobo Aura with some of these books and funny enough, it didn't behave like this at all - it produced the page fast, in one swoop.

**Comment by Frenzie** [comment] 2019-11-06 15:34
Might be KA1-specific? @NiLuJe knows the most about the relevant screen update stuff.

**Comment by NiLuJe** [comment] 2019-11-06 15:40
Huh. :D.

Is the base FW (nickel) up to date on your device?

That vaguely looks something stalling somewhere in the PxP/EPDC, which I'd naively suspect to be a kernel bug or weird epdc corner-case. The fact that you can't reproduce it on other devices would support that theory.

The "why" might be interesting, though, but only theoretically, understanding the reason probably won't help userland tools workaround it ;).

**Comment by NiLuJe** [comment] 2019-11-06 15:42
You could enable verbose debug logging (Tools > Developer options), the restart KOReader, and check whether we do actually only request a single refresh. I don't think there's anyway we could be the culprit here, especially since it happens both in CRe and in the UI, buuut, can't hurt to check ;).

**Comment by gerhaher** [comment] 2019-11-06 16:38
> Is the base FW (nickel) up to date on your device?

Now it is. :)
But same thing happens.

[crash.log](https://github.com/koreader/koreader/files/3815685/crash.log)

**Comment by NiLuJe** [comment] 2019-11-06 20:30
Yeah, we're sending a single update, and the kernel is struggling with it
for some reason ;).

**Comment by NiLuJe** [comment] 2019-11-06 20:31
On the off-chance it's a sneaky and weird power management issue, how are
you launching KOReader?

**Comment by gerhaher** [comment] 2019-11-06 21:09
KSM 09

**Comment by NiLuJe** [comment] 2019-11-06 21:19
I'd try with KFMon in case there are sneaky nickel shenanigans at play, bit
it's admittedly a long shot ;).

**Comment by gerhaher** [comment] 2019-11-07 08:15
Hmm, I don't think I want to bother myself with that. :)
But thanks anyway.

**Comment by Frenzie** [comment] 2019-11-11 20:40
I'll close this for now then since there's nothing we can do right now. Thanks for reporting!

**Closed by Frenzie** 2019-11-11 20:40 UTC
Labels: Kobo

**Comment by gerhaher** [comment] 2019-12-16 12:45
Some more info:

I tested some earlier releases of KOReader and found out that this appears for the first time with 2019.05. It wasn't there with 2019.04 or earlier.

Does that make any difference, regarding your initial analyse? 
@NiLuJe @Frenzie

**Comment by poire-z** [comment] 2019-12-16 13:01
There's been the introduction of image dithering. You can try enabling/disabling some of them in `File Browser > Tools > Developer options > ` HW dithering, SW dithering, C blitter - and see if some specific combinations cause or solve the issue.
There's also one thing in the bottom panel, right most icon: Image scaling fast|best.

**Comment by gerhaher** [comment] 2019-12-16 13:15
Oh yeah, nice!

I disabled SW dithering and now it's gone.

Thanks!

**Comment by NiLuJe** [comment] 2019-12-16 14:21
Huh. Now I'm curious. On mobile right now, I can't remember if you already
did, but you could you send me one of the affected images?

**Comment by gerhaher** [comment] 2019-12-16 14:30
> but you could you send me one of the affected images?

In first post I shared a cropped copy of one affected book.

**Comment by NiLuJe** [comment] 2019-12-16 18:09
Oh, right, I remembered the log, not the test book, thanks ;).

Well, I'm still quite puzzled :). I still can't reproduce it anywhere ^^.

And from the log, I can tell that it's not the SW dithering taking its sweet time for some reason (which wouldn't make much sense anyway, it's completely linear, the runtime depends on the amount of pixels on screen, not on *what* those pixels are), since we only send the refresh ioctl *after* rendering has completed.

So, yeah, no idea why the EPDC seems to choke on what would basically be "perfect" input (8bpp, already dithered to the right palette). o_O.

**Comment by NiLuJe** [comment] 2019-12-16 19:19
Another random test: Does it happen in the ImageViewer, too? (i.e., without opening the book first, Long Press > View Cover).

**Comment by gerhaher** [comment] 2019-12-16 20:06
> Does it happen in the ImageViewer, too?

It doesn't happen with the Andrew Roberts book above.

But it happens for example with these: 
[Rise and Kill - Ronen Bergman.zip](https://github.com/koreader/koreader/files/3969895/Rise.and.Kill.-.Ronen.Bergman.zip)
[Fryderyk Chopin_ A Life and Tim - Alan Walker.zip](https://github.com/koreader/koreader/files/3969896/Fryderyk.Chopin_.A.Life.and.Tim.-.Alan.Walker.zip)
[LJS - Bjorn Larsson.zip](https://github.com/koreader/koreader/files/3969897/LJS.-.Bjorn.Larsson.zip)

**Comment by NiLuJe** [comment] 2019-12-16 22:34
Hmm. Curiouser and curiouser ;). Still can't reproduce it ^^.

**Comment by NiLuJe** [comment] 2020-05-07 02:14
Forgot to xref: https://www.mobileread.com/forums/showpost.php?p=3983466&postcount=15

Confirmation that it's a known hardware-ish issue.
