### ISSUE TITLE
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}

### ISSUE THREAD

**Issue by nessotrin** [koreader/koreader#6000] opened 2020-03-23 22:24 UTC
* KOReader version: latest master branch - v2020.03.2
* Device: PB631/PB632 (Touch HD/ Touch HD2)

#### Issue
Constant and random crashes.  "Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}"
Book progress is lost every time. Koreader is completely unusable.

#### Steps to reproduce
Install any koreader version on the device.
Do anything inside koreader, including using the menu. You can read around 10 pages before it crashes. There is no correlation between what you do and when it happens.
Sometimes is crashes even before the GUI shows up when running with gdb.

##### `crash.log` & strace
[crash.log](https://github.com/koreader/koreader/files/4372155/crash.log)
[strace.txt](https://github.com/koreader/koreader/files/4372371/strace.txt)

I've attached GDB, but it doesn't seem to catch the fault. I made a custom build environment with updated headers and libraries for FW5.19 (including libinkview), but it didn't help.
Koreader never worked on my device (been trying for 2 years).

I can't give away the device, but I'm willing to help if given instructions. I have gdbserver and telnet access. (GDB over telnet hangs for some reason)

**Comment by NiLuJe** [comment] 2020-03-23 23:39
What do you mean, exactly, when you say that gdb can't catch the crash?

You can either attach to luajit at runtime, or simply run reader.lua via luajit under gdb, both approaches should work.

You may also try to let the kernel handle creating a coredump (you'll probably have to tweak the limits first and run KOReader in the same shell session. `ulimit -c unlimited` may not work in some crappy busybox sessions, in which case, simply use a large integer value.

**Comment by pazos** [comment] 2020-03-24 15:46
> I can't give away the device, but I'm willing to help if given instructions

Without the device just some random guesses (based on issues related to [SEGV_MAPERR](https://github.com/koreader/koreader/search?q=SIGSEGV%3A%3ASEGV_MAPERR&type=Issues)). 

You can try to [restrict JIT](https://github.com/koreader/koreader/blob/master/frontend/device/android/device.lua#L119) for your device &| try to [allocate a "big" chunk of memory for machine code](https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L15-L29)

**Comment by nessotrin** [comment] 2020-03-24 19:41
> > I can't give away the device, but I'm willing to help if given instructions
> 
> Without the device just some random guesses (based on issues related to [SEGV_MAPERR](https://github.com/koreader/koreader/search?q=SIGSEGV%3A%3ASEGV_MAPERR&type=Issues)).
> 
> You can try to [restrict JIT](https://github.com/koreader/koreader/blob/master/frontend/device/android/device.lua#L119) for your device &| try to [allocate a "big" chunk of memory for machine code](https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L15-L29)

I just tried both. It seems to help a little, but it doesn't fix the issue.

**Comment by nessotrin** [comment] 2020-03-24 20:09
> What do you mean, exactly, when you say that gdb can't catch the crash?
> 
> You can either attach to luajit at runtime, or simply run reader.lua via luajit under gdb, both approaches should work.
> 
> You may also try to let the kernel handle creating a coredump. You'll probably have to tweak the limits first and run KOReader in the same shell session. `ulimit -c unlimited` may not work in some crappy busybox versions, in which case, simply use a large integer value instead of unlimited.

Indeed, I got GDB to catch a segfault.
Ulimit wouldn't work (It does report being set to unlimited, but no coredump is produced), so I used GDB to make one. It's quite big (200M), should I upload it ?

I'd be great to build KOReader with debug symbols, but the wiki doesn't seem up to date. I know nothing about this code base, could somebody enlighten me ?

**Comment by Frenzie** [comment] 2020-03-24 22:20
Where in the wiki does it not seem up to date?

Instructions here: https://github.com/koreader/koreader/blob/master/doc/Building.md

**Comment by NiLuJe** [comment] 2020-03-24 22:57
@nessotrin: gcore may have a harder time creating usable dump than the kernel (especially on older kernels such as the one that's probably used there). Try setting `ulimit -c` to a stupidly large value instead of `unlimited` (Kobos have the same quirk).

IIRC, the kodev wrapper should be able to get you a debug build w/ symbols, I've relied on it on a few occasions.

**Comment by nessotrin** [comment] 2020-03-25 16:55
> Where in the wiki does it not seem up to date?
> 
> Instructions here: https://github.com/koreader/koreader/blob/master/doc/Building.md

That page doesn't say anything about a debug build.
The only thing I found : https://github.com/koreader/koreader-base/wiki/Remote-debugging-with-gdbserver

**Comment by Frenzie** [comment] 2020-03-25 17:19
Thanks, I'll update that page. The method described there annoyed me immensely a few years back so I gave builds with debug symbols their own folder. You can simply use a command like `kodev release --debug pocketbook`. The kodev script is self-documenting. ;-)

**Comment by Frenzie** [comment] 2020-03-25 17:22
PS The emulator defaults to debug.

**Comment by nessotrin** [comment] 2020-03-25 17:23
> @nessotrin: `gcore` may have a harder time creating an usable dump than the kernel (especially on older kernels such as the one that's probably used there). Try setting `ulimit -c` to a stupidly large value instead of `unlimited` (Kobos suffer from the same quirk, you just have to double-check that 'stupidly large' isn't actually too large to be ignored. IIRC, half INT32_MAX did the trick last time I checked).
> 
> IIRC, the kodev wrapper should be able to get you a debug build w/ symbols, I've relied on it on a few occasions.

I tried ulimit at different settings, no luck. Here's the kernel and busybox :
`Linux pocketbook 3.0.35+ #1 PREEMPT Thu Oct 31 13:23:18 EET 2019 armv7l GNU/Linux`
`BusyBox v1.26.2 (2019-09-24 21:41:24 EEST) multi-call binary.`

I found how to make a debug release with kodev.
**It could be helpful to mention in kodev's --help that you can get more informations on sub-categories.**
Something like "see kodev COMMAND --help for more information"

**Comment by Frenzie** [comment] 2020-03-25 17:35
I'd expect people to just read over that, but sure.

I guess I never thought about it because it's the same for Git.

**Comment by adnion** [comment] 2020-04-03 14:42
I very much hope that you can fix this issue. It's been around for ages. 
The stock reading app on PB631 can't even adjust the screen contrast. 
Please tell me if I can help somehow.
Good luck!

**Comment by NiLuJe** [comment] 2020-07-25 17:16
We're going to need a stacktrace and/or a strace log, much like we did to investigate the libcurl + inkview issues earlier (#5861).

**Comment by adnion** [comment] 2020-07-25 19:39
[crash.log](https://github.com/koreader/koreader/files/4976230/crash.log)
[crash_debug_verbose.log](https://github.com/koreader/koreader/files/4976236/crash_debug_verbose.log)
I can't get ssh to work for strace and the terminal emulator inside koreader crashes.
There are some tips to get ssh but it's hard
https://www.mobileread.com/forums/showthread.php?t=159636&page=7

**Comment by NiLuJe** [comment] 2020-07-25 19:56
I meant a gdb stacktrace, my bad (although a verbose crash.log will potentially also be helpful to cross-reference).

**Comment by adnion** [comment] 2020-07-25 20:06
I used 'ssh -T -v -p 2222 reader@1.1.1.1'
and got a connection. There is no input prompt but it works.
I ran 'strace -f -o log.txt /mnt/ext1/applications/koreader.app'
and got this
https://raw.githubusercontent.com/adnion/PB631-strace/master/log.txt

**Comment by adnion** [comment] 2020-07-25 20:13
Can you provide instructions for creating a gdb stacktrace?

**Comment by NiLuJe** [comment] 2020-07-25 20:55
It's detailed in the issue I linked to, IIRC.

**Comment by NiLuJe** [comment] 2020-07-25 21:08
Appears to be crashing later than usual though, so, beats me. Quite lilely still related to InkView and/or the "new" TC on FW 6 or whenever they happen to switch to Clang.

**Comment by adnion** [comment] 2020-07-25 21:24
Do you refer to https://github.com/koreader/koreader-base/wiki/Remote-debugging-with-gdbserver

**Comment by NiLuJe** [comment] 2020-07-25 21:29
Nope, I thought I'd mentioned gdb vs. an ulimit coredump in #5861, but apparently not. Must have bene in one of the othe,r numerous PB+InkView crash reports ;).

(Although, yeah, the wiki is probably a good start; but I'm more of a native on-device gdb guy myself, I've never actually used gdbserver).

**Comment by adnion** [comment] 2020-07-26 06:12
I found out there is a working gdb on the device by default, version GNU gdb (GDB) 7.12.1
I can call it using ssh. 
I tried 'gdb /mnt/ext1/koreader.app'
It says '(gdb) "/mnt/ext1/applications/koreader.app": not in executable format: File format not recognized'

**Comment by poire-z** [comment] 2020-07-26 07:01
koreader.app is a shell script.
I guess you can add gdb on this line:
https://github.com/koreader/koreader/blob/e23f68e5f76371bbb295ec5313c5e035221cda2c/platform/pocketbook/koreader.app#L47

`gdb ./reader.lua "${args}" >>crash.log 2>&1`
or (as reader.lua is also a script, and it may complain the same):
`gdb ./luajit ./reader.lua "${args}" >>crash.log 2>&1`

**Comment by adnion** [comment] 2020-07-26 07:02
I can't start gdb and koreader together.
But I can attach gdb to the running process like 'gdb -p 1111'
Attaching to process 1111
[New LWP 1111]
warning: Could not load shared library symbols for 11 libraries, e.g. ./libs/libkoreader-lfs.so.
I need a debug build :)

**Comment by adnion** [comment] 2020-07-26 07:46
@NiLuJe: Why do you prefer native on device gdb? It's painful with sh. Because the cursor keys don't work like they do in bash

**Comment by adnion** [comment] 2020-07-26 08:03
I pressed 'c' in gdb and clicked buttons until koreader terminates.
'Thread 1 "reader.lua" received signal SIGSEGV, Segmentation fault.
0x0001b540 in _start ()'

**Comment by poire-z** [comment] 2020-07-26 08:11
then type `bt` to possibly get a backtrace

**Comment by adnion** [comment] 2020-07-26 08:17
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
(gdb) bt
#0  0x0001b54c in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

I need that debug build but there is no compiler found although it should be downloaded automatically as stated here:
https://github.com/koreader/koreader/blob/master/doc/Building_targets.md#for-embedded-linux-devices
'/bin/bash: arm-pocketbook-linux-gnueabi-gcc: command not found'

**Comment by NiLuJe** [comment] 2020-07-26 16:13
That's because I build my own GDB with an actually usable CLI ^^.

Also, you don't necessarily need to run KOReader via gdb, you can instead run it in a shell with no modifications after simply allowing the kernel to generate coredumps on crash (`ulimit -c 2147483647`).

Then just run `gdb core luajit` from inside the koreader folder. Bonus points: on some older systems (i.e., these :D), the stacktrace will actually be more accurate that way ;).

----

That said, yeah, you'll need a debug build.

You had the right link, it's just slightly outdated because we don't have a PB maintainer. There's now a [koxtoolchain](https://github.com/koreader/koxtoolchain) PB TC available, because the PB SDK situation is... messy.

**Comment by Frenzie** [comment] 2020-07-26 18:06
You can use the PocketBook Docker image, see https://github.com/koreader/virdevenv 

That's `kopb`.

I'm sure @NiLuJe or I or whoever could also provide a build but it may not necessarily be much faster. ^_^

**Comment by adnion** [comment] 2020-07-26 19:11
I used koxtoolchain and built a debug koreader.
After copying it to the PB631 it segfaults on start.
Crashlog:
```
 [*] Version: v2020.07.1-14-ge23f68e5_2020-07-26
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
07/26/20-21:04:16 INFO  SoftwareVersion:  U631.5.20.1527
07/26/20-21:04:16 INFO  Blacklisting the C BB on this device
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
FB: computed size: 1671168
FB: id           : mxc_epdc_fb
FB: smem_len     : 1695744
FB: line_length  : 1088
FB: xres         : 1072
FB: xres_virtual : 1088
FB: yres         : 1448
FB: yres_virtual : 1536
FB: bpp          : 8
Atached mp shm: id 0 addr 2ab82000 size 21736
epdc_default_init
epdc_default_rotate: w=1072 h=1448 scan=1088 mem=1695744
attach_shm: mtfb key=251332013 size=1666724
Atached mtfb shm: id 100009 addr 2d526000 size 1666724
-------------------------
The task - koreader.app fb 0x2d526000
 xres=1072 yres=1448 scanline=1072 vdepth=8 orient=0
-------------------------
attach_shm: ref key=2130378752 size=1560832
Atached ref shm: id 8001 addr 2d704000 size 1560832
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800000; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 10000 0 0 0 10000
ffi.load: inkview
07/26/20-21:04:16 INFO  initializing for device PBTouchHD
07/26/20-21:04:16 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
./luajit: frontend/apps/reader/modules/readerdictionary.lua:10: module 'json' not found:
	no field package.preload['json']
	no file 'common/json.lua'
	no file 'rocks/share/lua/5.1/json.lua'
	no file 'frontend/json.lua'
	no file './json.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/json.lua'
	no file '/usr/local/share/lua/5.1/json.lua'
	no file '/usr/local/share/lua/5.1/json/init.lua'
	no file 'common/json.so'
	no file 'common/json.dll'
	no file '/usr/lib/lua/json.so'
	no file 'rocks/lib/lua/5.1/json.so'
	no file './json.so'
	no file '/usr/local/lib/lua/5.1/json.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	frontend/apps/reader/modules/readerdictionary.lua:10: in main chunk
	[C]: in function 'require'
	frontend/apps/reader/readerui.lua:31: in main chunk
	[C]: in function 'require'
	./reader.lua:274: in main chunk
	[C]: at 0x000142cd
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
```
Now I try to use the release version of koreader to start the ssh server and then use gdb to debug the debug version of koreader

**Comment by adnion** [comment] 2020-07-26 19:22
@NiLuJe I got a problem with 'ulimit' because i can't ssh into PB631 as root.
I have no permission to set the limit.
@poire-z ```gdb ./luajit ./reader.lua``` does not work it says ```...reader.lua is not a core dump: File format not recognized```

**Comment by Frenzie** [comment] 2020-07-26 19:25
Normally I'd run something like `gdb --args ./luajit reader.lua`.

**Comment by adnion** [comment] 2020-07-26 19:32
Thank you it works. I hope it helps somehow
[stacktrace.txt](https://github.com/koreader/koreader/files/4978258/stacktrace.txt)

**Comment by NiLuJe** [comment] 2020-07-26 19:45
Assuming the backtrace matches that last crash.log, it's just an incomplete build: you're missing rapidjson.

It may have failed to build, or it may be an incompatibility with LuaRocks on your host system, as we know that can be tricky.

Now, that *shouldn't* cause a crash (just break a few modules), so it's still entirely possible that the crash is still the one we're investigating ;).

**Comment by Frenzie** [comment] 2020-07-26 19:46
You might very well get a crash but a segfault seems rather unlikely. ;-)

**Comment by NiLuJe** [comment] 2020-07-26 19:46
Okay, and after looking at the trace, yep, it's most definitely what we're looking for. It's inside OpenSSL. We're using OpenSSL 1.1.1; InkView is using OpenSSL 1.0.0, that falls under the purview of InkView fucking things up like I thought it could ,p.

**Comment by NiLuJe** [comment] 2020-07-26 19:48
Oh, wait. I forgot that gdb interrupts on SIGILL, too.

You may actually want to enter `c`, to continue execution until it actually crashes on a segfault.

**Comment by adnion** [comment] 2020-07-26 20:35
Same build, but entered `c` until segfault. Then `bt`.
[trace.txt](https://github.com/koreader/koreader/files/4978408/trace.txt)

**Comment by NiLuJe** [comment] 2020-07-27 01:34
Hmm, that's not super-helpful, unfortunately, but smells like memory corruption, quite likely because of a library clash between us and InkView :S.

**Comment by EastEriq** [comment] 2020-09-10 22:24
Continuing discussion from https://www.mobileread.com/forums/showthread.php?p=4033366#post4033366

Testing #!./luajit -joff in reader.lua with the debug build attached by @pazos in that thread (an up to date build perhaps another day). Sloooow, but I'm unable to crash it!

**Comment by NiLuJe** [comment] 2020-09-10 22:58
It's (probably) not available on PB without flipping the proper device caps in https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua, as explained here:

https://github.com/koreader/koreader/blob/ffa9857ff18daa3e456ec4e3b171dbe0295ba603/frontend/device/pocketbook/device.lua#L44-L45

**Comment by EastEriq** [comment] 2020-09-10 22:59
Here finally I've been able to crash.
[crash.log](https://github.com/koreader/koreader/files/5205015/crash.log)

**Comment by NiLuJe** [comment] 2020-09-10 23:01
So, must nastier issues than a weird Lua bug, as suspected ;).

**Comment by EastEriq** [comment] 2020-09-10 23:03
But it took really a lot of fiddling to get there. Several books, jumping pages, playing with settings. Compared with a just couple of taps without -joff.

**Comment by NiLuJe** [comment] 2020-09-10 23:06
Unfortunately, Android has taught us that it's irrelevant: if it still crahses without the JIT, the JIT isn't the culprlit ;).

**Comment by NiLuJe** [comment] 2020-09-10 23:08
Do those specific models use a specific glibc, by chance?

Or a global ld.preload hack that might overload some basic stuff in a superbly buggy way?

**Comment by Uwe-B** [comment] 2020-09-11 06:04
I've made some backups of ebrmain&cramfs and uploaded it. Maybe that helps.
ebrmain:
https://yadi.sk/d/4gottJ5-LJDc1Q
and cramfs:
https://yadi.sk/d/HWWKN2G228VKvw

**Comment by Uwe-B** [comment] 2020-09-11 06:04
I've made some backups of ebrmain&cramfs and uploaded it. Maybe that helps.
ebrmain:
https://yadi.sk/d/4gottJ5-LJDc1Q
and cramfs:
https://yadi.sk/d/HWWKN2G228VKvw

**Comment by Uwe-B** [comment] 2020-09-11 06:05
I've made some backups of ebrmain&cramfs and uploaded it. Maybe that helps.
ebrmain:
https://yadi.sk/d/4gottJ5-LJDc1Q
and cramfs:
https://yadi.sk/d/HWWKN2G228VKvw

**Comment by Uwe-B** [comment] 2020-09-11 06:05
I've made some backups of ebrmain&cramfs and uploaded it. Maybe that helps.
ebrmain:
https://yadi.sk/d/4gottJ5-LJDc1Q
and cramfs:
https://yadi.sk/d/HWWKN2G228VKvw

**Comment by EastEriq** [comment] 2020-09-11 08:47
> Do those specific models use a specific glibc, by chance?
> 
> Or a global ld.preload hack that might overload some basic stuff in a superbly buggy way?

[Asked on mobileread](https://www.mobileread.com/forums/showthread.php?p=4033530)

**Comment by ezdiy** [comment] 2020-09-11 13:10
Can someone please list `info proc mappings` from gdb after it crashes? this is most likely just luajit trampling on some mapping (it tends to make few of unhealthy assumptions), or worse - luajits memory getting corrupted, which sets further allocs on fire. Also, if some nasty lib dependency were there, it would show too.

As for how to run gdb on the device, see https://www.mobileread.com/forums/showpost.php?p=4030129&postcount=6 (you don't need root for that, the internal sshd should suffice:

create ssh.app with:

```
#!/bin/sh
/sbin/dropbear -G "" -p 2222
```

Or just run do that in pbterm. You can then ssh in with `ssh -t reader@device` with empty password. -t means no tty. i'm not sure if putty has the option.

**Comment by EastEriq** [comment] 2020-09-11 14:36
> Can someone please list `info proc mappings` from gdb after it crashes? 

Here you go. [8-no_joff_openNewFile.txt](https://github.com/koreader/koreader/files/5209647/8-no_joff_openNewFile.txt)

> (you don't need root for that, the internal sshd should suffice:
> 
> create ssh.app with:
> ...

I rooted and enjoy it, no need, I just ssh in.
 
> @EastEriq It might be worth it to run koreader in chroot from slightly newer firmware. I suspect this happens on early versions of FW5 - the device is too old to receive newer updates of that fw line where the bug doesn't manifest.

I have the latest firmware officially available, and haven't read that it is possible to install a newer one intended for another model (e.g. 6.x for PB632). When you say chroot, chroot to which new dir anyway?

**Comment by NiLuJe** [comment] 2020-09-11 15:45
@ezdiy: Oh, yeah, it's definitely more something along the lines of FFI + something else doing something nasty, rather than purely an internal LuaJIT thingy , as the references to the early Android days implied ;).

In this specific case, my gut feeling would be the two different copies of OpenSSL, similarly to how the two libcurl copies blew up on PB.

**Comment by Uwe-B** [comment] 2020-09-14 08:07
I'm not a programmer but since the errors on my device backtraced with gdb allways start with:
0x0001e69c in lj_alloc_free (msp=0x2acd4008, ptr=<optimized out>)
    at lj_alloc.c:1400
1400    lj_alloc.c: No such file or directory.``
& that, if the Koreader crashes on the device, no changes in the Koreader settings are written nor the book status is updated, could it be same file operation?

**Comment by Uwe-B** [comment] 2020-09-14 08:07
I'm not a programmer but since the errors on my device backtraced with gdb allways start with:
0x0001e69c in lj_alloc_free (msp=0x2acd4008, ptr=<optimized out>)
    at lj_alloc.c:1400
1400    lj_alloc.c: No such file or directory.``
& that, if the Koreader crashes on the device, no changes in the Koreader settings are written nor the book status is updated, could it be same file operation?

**Comment by EastEriq** [comment] 2020-09-14 08:26
methinks, that is only gdb saying that it would gladly show the source line of lj_alloc.c if it could (e.g. something like https://github.com/LuaJIT/LuaJIT/blob/cc44642cf89198e39aa41067c4e1e9879a82c2f5/src/lj_alloc.c#L1400, don't know specifically which lj snapshot koreader is using), but since the source files is not there, it doesn't.
The fact that settings are not saved is likely simply because koreader crashes before it has a chance to.

**Comment by ezdiy** [comment] 2020-09-16 22:01
@EastEriq Unpack [luajit.zip](https://github.com/koreader/koreader/files/5235148/luajit.zip) and replace /applications/koreader/luajit

It's a vanilla luajit compiled for pocketbook, with extensive debug options enabled (it should detect something getting corrupted much earlier - if that's whats happening). It also uses the conservative (thread-safe) memory allocator.

```diff
--- a/src/Makefile
+++ b/src/Makefile
@@ -99,7 +99,7 @@ XCFLAGS=
 # enabled by default. Some other features that *might* break some existing
 # code (e.g. __pairs or os.execute() return values) can be enabled here.
 # Note: this does not provide full compatibility with Lua 5.2 at this time.
-#XCFLAGS+= -DLUAJIT_ENABLE_LUA52COMPAT
+XCFLAGS+= -DLUAJIT_ENABLE_LUA52COMPAT
 #
 # Disable the JIT compiler, i.e. turn LuaJIT into a pure interpreter.
 #XCFLAGS+= -DLUAJIT_DISABLE_JIT
@@ -128,7 +128,7 @@ XCFLAGS=
 # realloc usually doesn't return addresses in the right address range.
 # OTOH this option is mandatory for Valgrind's memcheck tool on x64 and
 # the only way to get useful results from it for all other architectures.
-#XCFLAGS+= -DLUAJIT_USE_SYSMALLOC
+XCFLAGS+= -DLUAJIT_USE_SYSMALLOC
 #
 # This define is required to run LuaJIT under Valgrind. The Valgrind
 # header files must be installed. You should enable debug information, too.
@@ -141,11 +141,11 @@ XCFLAGS=
 #
 # Turn on assertions for the Lua/C API to debug problems with lua_* calls.
 # This is rather slow -- use only while developing C libraries/embeddings.
-#XCFLAGS+= -DLUA_USE_APICHECK
+XCFLAGS+= -DLUA_USE_APICHECK
 #
 # Turn on assertions for the whole LuaJIT VM. This significantly slows down
 # everything. Use only if you suspect a problem with LuaJIT itself.
-#XCFLAGS+= -DLUA_USE_ASSERT
+XCFLAGS+= -DLUA_USE_ASSERT
 #
 ##############################################################################
 # You probably don't need to change anything below this line!
```

**Comment by NiLuJe** [comment] 2020-09-16 23:25
I'm pretty sure stuff will break in fun and interesting ways w/ `LUA52COMPAT` enabled. We should *probably* take care of that at one point, because I kinda like what this does ;).

**Comment by ezdiy** [comment] 2020-09-17 00:02
@NiLuJe Ye I enabled that out of habit (on assumption that everybody else does). Indeed this is likely to break os.execute, but for the issue at hand its harmless (I'm running it just fine, though not really doing anything os.exec to speak of).

**Comment by EastEriq** [comment] 2020-09-17 07:30
> @EastEriq Unpack [luajit.zip](https://github.com/koreader/koreader/files/5235148/luajit.zip) and replace /applications/koreader/luajit
> 
> It's a vanilla luajit compiled for pocketbook, with extensive debug options enabled (it should detect something getting corrupted much earlier - if that's whats happening). It also uses the conservative (thread-safe) memory allocator.

Will try in the following. What exactly to do to help? Use the debug compiled version of last week, or the latest non-debug nightly build as base? Run in gdb as usual and report bt, where and crash.log, or anything else? I still haven't tried to set up a build chain, and if I'd be happy if I can still avoid the trouble of it.

**Comment by ezdiy** [comment] 2020-09-17 08:27
@EastEriq Just run the debug copy of koreader but with luajit swapped. Gdb bt & info proc mappings dance if it crashes. I have some hopes this one will survive (provided it's an lj_alloc threading issue, it should be fixed). If that's the case we can just snowflake the luajit build for pocketbook and be done with it.

**Comment by Uwe-B** [comment] 2020-09-17 12:51
I just did that, hope it helps.
[_gdb_bt4(epub).txt](https://github.com/koreader/koreader/files/5239167/_gdb_bt4.epub.txt)

**Comment by ezdiy** [comment] 2020-09-17 13:12
Blah. At least that trace hints the crash happens instantly on book open, meaning closer to the source. One screenful of refresh is enough to crash, is that assumption correct. If it's waiting for a marker, blitbuffer code could be the culprit somehow.

Please also try with `export MALLOC_CHECK_=3` in the initial setting list, hopefuly it would compel malloc to fail even earlier.

**Comment by Uwe-B** [comment] 2020-09-17 13:28
Now this was unexpected, it crashed/ended without opening the book and bt was not doing anything at all. Have a look:
[_gdb_bt5(epub).txt](https://github.com/koreader/koreader/files/5239372/_gdb_bt5.epub.txt)

**Comment by NiLuJe** [comment] 2020-09-17 13:33
That was kind of what I was hinting at when I said to [try w/ the C blitter](https://github.com/koreader/koreader/issues/6000#issuecomment-690774991): at least we'd get a real backtrace if it was a blitting SNAFU ;).

**Comment by ezdiy** [comment] 2020-09-17 13:34
@Uwe-B that's normal when `LC_ALL` is missing. You need to use `export` so a subprocess gets the env variable (without export the var is tied to shell only).

**Comment by NiLuJe** [comment] 2020-09-17 13:37
FWIW, waiting for a marker is basically the last thing we do on a refresh, which means that an UIManager stack has been drained, stuff has been blitted, and the screen was asked to refresh already.

(It's basically a simple ioctl that blocks for a while).

**Comment by ezdiy** [comment] 2020-09-17 13:41
@NiLuJe Just commenting out https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L74 and setting `["dev_no_c_blitter"] = false,` in `settings.reader.lua` should do the trick, right?

I doubt the issue is with the marker wait itself, though one can test disable it too by setting:

```
ffi/framebuffer_mxcfb.lua:

    elseif self.device:isPocketBook() then
        require("ffi/mxcfb_pocketbook_h")

        self.mech_refresh = nil
        self.mech_wait_update_complete = nil
```

This could be a culprit in case something real fishy goes on with the ioctl (like kernel writing back beyond struct what we expect or w/e).

**Comment by NiLuJe** [comment] 2020-09-17 13:48
@ezdiy: See the post I linked to above for a proper switch, but, as a quick'n dirty patch, yeah, that'll do the trick ;).

----

There are indeed two generations of wait_for_complete ioctls, but you usually see the more complex on on *later* generations, not older ;).

i.e., https://github.com/NiLuJe/FBInk/blob/27fcd19fa30280fdb7931611b08a726c070711d6/eink/mxcfb-kobo.h#L262-L266 vs. just returning the marker as an u32.

**Comment by Uwe-B** [comment] 2020-09-17 13:52
I'll try it soon, just having some memory corruption on the internal sd which need to be cared before.

**Comment by Uwe-B** [comment] 2020-09-17 15:03
I did:
1) commenting out https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L74
&
2) changed setting ["dev_no_c_blitter"] = false, in settings.reader.lua
&
3) Edited:
ffi/framebuffer_mxcfb.lua:

    elseif self.device:isPocketBook() then
        require("ffi/mxcfb_pocketbook_h")

        self.mech_refresh = function() end
        self.mech_wait_update_complete = nil

Same output since I left that "export MALLOC_CHECK_=3" too.
Tried it later without this export MALLOC_CHECK_=3 , 
Doesn't seem to matter, my output.
[_gdb_bt6(epub).txt](https://github.com/koreader/koreader/files/5240029/_gdb_bt6.epub.txt)

**Comment by ezdiy** [comment] 2020-09-17 15:05
@Uwe-B You're still not setting env variables correctly (use export).

**Comment by Uwe-B** [comment] 2020-09-17 15:09
Oh yeah I'm stupid, doing it now.

**Comment by Uwe-B** [comment] 2020-09-17 15:17
[_gdb_bt7(epub).txt](https://github.com/koreader/koreader/files/5240112/_gdb_bt7.epub.txt)
Can't crash it. No chance.

**Comment by ezdiy** [comment] 2020-09-17 15:26
@Uwe-B Neat! And after you re-enable `self.mech_refresh = function() end`?

**Comment by Uwe-B** [comment] 2020-09-17 15:42
Does this help?
Ich changed this back to the previous settings:
 self.mech_refresh = function() end
 self.mech_wait_update_complete = nil
[_gdb_bt8(epub).txt](https://github.com/koreader/koreader/files/5240279/_gdb_bt8.epub.txt)

**Comment by ezdiy** [comment] 2020-09-17 15:44
@Uwe-B try the following lines *exactly*:

```
self.mech_refresh = refresh_pocketbook
self.mech_wait_update_complete = nil
```

(this is a combo where display stil works, but may still avoid crashes if wait_update is the culprit)

**Comment by Uwe-B** [comment] 2020-09-17 15:49
Thats exactly what I did the last minutes. No crash that I could produce!!!

**Comment by NiLuJe** [comment] 2020-09-17 15:55
Then you get to check with `mech_wait_update_complete` re-enabled, and if it still doesn't crash, you can try switching back to the Lua blitter, to cinch things up ;).

**Comment by ezdiy** [comment] 2020-09-17 15:56
Welp, finally narrowed it down. Now try whole pristine koreader from scratch (no gdb, no custom launch, no debug mode), and just change of `self.mech_wait_update_complete = nil` so we can be sure that's the fix. Then we can try to find a fix for the corruption in that routine.

@NiLuJe it seems like the collision field is written to, or even something beyond it. But only on kernels of peculiar devices.

**Comment by Uwe-B** [comment] 2020-09-17 16:13
Cool its working.
What I did:
Deflate koreader-pocketbook-v2020.08.1-62-gffa9857_2020-09-09 and replace KOreader on this device with the aformentioned version.
Just edited existing:
ffi/framebuffer_mxcfb.lua:
elseif self.device:isPocketBook() then
require("ffi/mxcfb_pocketbook_h")

- self.mech_wait_update_complete = pocketbook_mxc_wait_for_update_complete
+ self.mech_wait_update_complete = nil
Device Pocketbook 631+ (which has the same firmware as 631 but with warmlight.

**Comment by NiLuJe** [comment] 2020-09-17 16:26
@ezdiy: Huh. [Apparently](https://github.com/pocketbook/Platform_MX6/blob/master/Kernel_631/include/linux/mxcfb.h) the 631 kernel definitely supports both variants (or not, depending on how it's built), but we should *definitely* be calling the legacy variant.

Which, err, I imagine should just plain fail instead of crash weirdly if the kernrles aren't built w/ `MX50_IOCTL_IF` defined?

**Comment by NiLuJe** [comment] 2020-09-17 16:29
Oh. On the other hand, [older](https://github.com/pocketbook/Platform_MX6/blob/master/Kernel/include/linux/mxcfb.h) kernels use the old ioctl address w/ the "new" struct, so, mystery solved?

**Comment by NiLuJe** [comment] 2020-09-17 16:38
I'm going to build a proper franken-header + cdecl like on other platforms to make this kind of stuff slightly less crazy to debug...

**Comment by ezdiy** [comment] 2020-09-17 16:42
@NiLuJe I suppose it couldn't hurt just passing the two-field struct always (since the marker int is first in there), just to be on safe side?

**Comment by ezdiy** [comment] 2020-09-17 16:44
@Uwe-B If I'm not mistaken, this should work correctly with no crashes:

```
        self.mech_wait_update_complete = remarkable_mxc_wait_for_update_complete
```

**Comment by Uwe-B** [comment] 2020-09-17 16:59
> 
> 
> @Uwe-B If I'm not mistaken, this should work correctly with no crashes:
> 
> ```
>         self.mech_wait_update_complete = remarkable_mxc_wait_for_update_complete
> ```

Yep, couldn't crash it!

**Comment by autrimpo** [comment] 2020-09-17 17:29
I've had these crashes with Pocketbook Touch Lux 4 (627) after upgrading to the 6.0.1118 firmware as well. In my case, the crash would always happen immediatelly after starting Koreader. I just installed the 2020.09 release with the fix from 

> @Uwe-B If I'm not mistaken, this should work correctly with no crashes:
> 
> ```
>         self.mech_wait_update_complete = remarkable_mxc_wait_for_update_complete
> ```

and am happy to report that things seem to be working fine :)
Thank you to everyone involed!

**Comment by EastEriq** [comment] 2020-09-17 22:08
Sorry, been late to the party.

So I installed koreader-pocketbook-v2020.08.1-74-geecdf5b_2020-09-16 from the nightly builds; edited `/mnt/ext1/applications/koreader/ffi/framebuffer_mxcfb.lua` and only changed line 702 to `self.mech_wait_update_complete = nil`.

Confirm that all seems to work for long without crashing. Well, I see several quirks, like the frontlight not commanded, the green activity led always on, occasionally some redraw problem - but all pertain to different bug reports. Big difference. Thanks to all involved!

**Comment by ezdiy** [comment] 2020-09-18 12:27
@EastEriq Current workaround is essentialy disabling part of functionality. We need some detail about what really goes on on your device by observing what the official reader does. Open an epub in epub (v2) reader (long-tap and open-with, i think), and strace the fb2 reader for ioctls while tapping through pages:

```/mnt/secure # strace -T -i -e trace=ioctl -p `ps | grep eink-reader|grep firsttime|awk {'print $1'}`
Process 1000 attached - interrupt to quit
[a1645d7c] ioctl(4, 0x80044655, 0xaedbd594) = 0 <0.001507>
[a1645d7c] ioctl(4, 0x80204656, 0xaedbad08) = 0 <0.000082>
[a1645d7c] ioctl(4, 0x4004462f, 0xa3015dc4) = 0 <0.000081>
[a1645d7c] ioctl(4, 0x4004462f, 0xa3015dc4) = 0 <0.000709>
[a1645d7c] ioctl(4, 0x4004462f, 0xa3015dc4) = 0 <0.000802>
[a1645d7c] ioctl(4, 0x80044655, 0xaedbd594) = 0 <0.001509>
[a1645d7c] ioctl(4, 0x4004462f, 0xa3015dc4) = 0 <0.000790>
[a1645d7c] ioctl(4, 0x4004462f, 0xa3015dc4) = 0 <0.401787>
[a1645d7c] ioctl(4, 0x4004462f, 0xa3015dc4) = 0 <0.000088>
[a1645d7c] ioctl(4, 0x80044655, 0xaedbd594) = 0 <0.001684>
.....
```

**Comment by NiLuJe** [comment] 2020-09-18 12:35
I posted a strace build that should decode those ioctls in
https://github.com/koreader/koreader/pull/6669#issuecomment-694552233

**Comment by Uwe-B** [comment] 2020-09-18 19:49
I'll do my best to help out with testing if needed.

**Closed** 2020-09-19 17:05 UTC
Labels: PocketBook, bug, firmware, help-wanted
