### ISSUE TITLE
CREngine: no ligatures

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2824] opened 2017-04-28 18:45 UTC
#### Steps to reproduce

- Open an EPUB containing the word *fluffiness*.
- Set *Linux Libertine* as the document font.

You'll notice that the standard ligatures *fl* and *ffi* are not being used.

**Comment by Frenzie** [comment] 2017-04-28 18:47
Duplicate of #1378.

**Closed by Frenzie** 2017-04-28 18:47 UTC
