### ISSUE TITLE
FR: "Search Vocabulary Builder" option in Dictionary dialog

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12506] opened 2024-09-11 11:44 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
Sometimes, while looking up a word in the dictionary, we may want to see if we have already added that word to the Vocabulary Builder to avoid entering it twice. Now we need to exit the Dictionary, open the Vocabulary Builder, look up the word, select the word again in the text or wright it again in the Dictionary and add it to the Vocabulary Builder, if it has not already been added.

**Describe the solution you'd like**
Could there be an option (button) "Search Vocabulary Builder" in the Dictionary dialog?

@weijiuqiao what do you think about it?

Thanks!

**Comment by jonnyl2** [comment] 2024-09-11 12:34
And/or perhaps a check and a warning message, "This word has already been added, would you like to add it anyway?"?

**Comment by Steven630** [comment] 2024-09-11 14:58
Something like this for multiple contexts of a word (this is what I do after extracting info from my Kindle's VB):

![Screenshot_20240911_225609.jpg](https://github.com/user-attachments/assets/8bd4727e-43ec-4784-91c8-3d2632a8aeb3)

**Comment by weijiuqiao** [comment] 2024-09-11 15:04
Currently, when adding an existing word, the context is updated if there is new context, and it assumes the user has forgotten the word, so a 'forgot' operation is performed on the word.

**Comment by Steven630** [comment] 2024-09-11 15:13
> Currently, when adding an existing word, the context is updated if there is new context, and it assumes the user has forgotten the word, so a 'forgot' operation is performed on the word.

And would you please take a look at #12475 while you are here? I have updated the description. That PDF has a text layer, and VB had no problem extracting context from a single word(as opposed to multi-word phrases)in the same sentence of the same file. Clearly, this can be fixed.

**Comment by Steven630** [comment] 2024-09-16 01:02
Here is what ChatGPT suggests:

To implement your desired behavior—allowing multiple entries for the same word with different contexts and preventing duplicate entries with the exact same context—several modifications are needed. Below is an overview of the main areas that need changes:

1. Database Schema Changes:

Modify the vocabulary table to remove the UNIQUE constraint on the word column. This will allow multiple entries of the same word but with different contexts.

Ensure that new entries can be distinguished by their context. This means that the combination of word, prev_context, and next_context needs to be unique, rather than just the word itself.

Schema Changes:
```
CREATE TABLE IF NOT EXISTS "vocabulary" (
    "word"          TEXT NOT NULL,
    "title_id"      INTEGER,
    "create_time"   INTEGER NOT NULL,
    "review_time"   INTEGER,
    "due_time"      INTEGER NOT NULL,
    "review_count"  INTEGER NOT NULL DEFAULT 0,
    "prev_context"  TEXT,
    "next_context"  TEXT,
    "streak_count"  INTEGER NOT NULL DEFAULT 0,
    "highlight"     TEXT,
    PRIMARY KEY("word", "prev_context", "next_context")
);
```
This allows multiple entries for the same word with different contexts but prevents duplicates when the word and contexts are identical.

2. Changes to insertOrUpdate Logic:

You need to modify the insertOrUpdate function to ensure that duplicate entries with different contexts are treated separately.

Also, if the context is identical to an existing entry, do not create a new one. Use a query to check if an entry already exists with the same word, prev_context, and next_context.

Update Logic:
```
function VocabularyBuilder:insertOrUpdate(entry)
    local conn = SQ3.open(db_location)
    
    -- Insert title if it doesn't exist
    local stmt = conn:prepare("INSERT OR IGNORE INTO title (name) VALUES (?);")
    stmt:bind(entry.book_title)
    stmt:step()
    stmt:clearbind():reset()
    
    -- Check if the word with the exact same contexts already exists
    local exists_sql = [[SELECT 1 FROM vocabulary WHERE word = ? AND prev_context = ? AND next_context = ?;]]
    stmt = conn:prepare(exists_sql)
    stmt:bind(entry.word, entry.prev_context, entry.next_context)
    local exists = stmt:step() ~= nil  -- If there's a result, entry already exists
    stmt:clearbind():reset()
    
    if not exists then
        -- Insert new entry for the word with different contexts
        stmt = conn:prepare([[INSERT INTO vocabulary (word, title_id, create_time, due_time, review_time, prev_context, next_context, highlight)
                              VALUES (?, (SELECT id FROM title WHERE name = ?), ?, ?, ?, ?, ?, ?);]])
        stmt:bind(entry.word, entry.book_title, entry.time, entry.time + 300, entry.time,
                  entry.prev_context, entry.next_context, entry.highlight)
        stmt:step()
        stmt:clearbind():reset()
    end
    
    conn:close()
end

```
3. Adjust Selection Logic:

Ensure that when selecting or retrieving vocabulary items (such as in the _select_items function), you retrieve all entries for the same word, including those with different contexts.

Update Selection Logic:

```
function VocabularyBuilder:_select_items(items, start_idx, reload_time, search_text)
    local conn = SQ3.open(db_location)
    local sql
    if search_text then
        sql = string.format("SELECT * FROM vocabulary INNER JOIN title ON title_id = title.id WHERE word LIKE '%s' LIMIT 32 OFFSET %d", search_text, start_idx-1)
    elseif not reload_time then
        sql = string.format("SELECT * FROM vocabulary INNER JOIN title ON title_id = title.id AND filter = true ORDER BY due_time limit %d OFFSET %d;", 32, start_idx-1)
    else
        sql = string.format([[SELECT * FROM vocabulary INNER JOIN title
                              ON title_id = title.id AND filter = true
                              WHERE due_time <= ]] .. reload_time ..
                            " ORDER BY due_time desc limit %d OFFSET %d;", 32, start_idx-1)
    end

    local results = conn:exec(sql)
    conn:close()
    if not results then return end

    local current_time = os.time()

    for i = 1, #results.word do
        local item = items[start_idx+i-1]
        if item and not item.word then
            item.word = results.word[i]
            item.review_count = math.max(0, tonumber(results.review_count[i]))
            item.streak_count = math.max(0, tonumber(results.streak_count[i]))
            item.book_title = results.name[i] or ""
            item.highlight = results.highlight[i]
            item.create_time = tonumber(results.create_time[i])
            item.review_time = nil  -- use this field to flag change
            item.due_time = tonumber(results.due_time[i])
            item.is_dim = tonumber(results.due_time[i]) > current_time
            item.prev_context = results.prev_context[i]
            item.next_context = results.next_context[i]
        end
    end
end
```
Summary of Changes:

Database Schema: Modify the schema to allow multiple entries for the same word with different contexts by adjusting the primary key.

Insert Logic: Modify the insertOrUpdate function to insert separate entries if the context is different but prevent duplicates for the same context.

Select Logic: Adjust the select logic to retrieve all entries for a word, including those with different contexts.

This approach retains multiple contexts for the same word while preventing exact duplicates.

**Comment by weijiuqiao** [comment] 2024-09-18 13:23
It's not so simple. This method would result in multiple entries of the same word and would complicate cloud sync even more. Current just having the context updated seems not too bad?

**Comment by Steven630** [comment] 2024-09-18 13:42
> It's not so simple. This method would result in multiple entries of the same word and would complicate cloud sync even more. Current just having the context updated seems not too bad?

Thank you for considering it. The problem is that some words have different meanings (as the example of match shows). Having more context also helps building memory. So a simpler solution for now would be to combine the contexts. Kindle uses db file to store its native vocabulary builder and supports this feature(I guess they are first added as separate entries, then combined with some query method of the database):

![IMG_20240918_214109.jpg](https://github.com/user-attachments/assets/aca4268b-c638-48fe-94b4-80fa77c57d29)

**Comment by weijiuqiao** [comment] 2024-09-18 13:48
A possible solution is to separate the context fields into a different table in the db. Not sure how complex it would make the sync though.

**Comment by Steven630** [comment] 2024-09-18 14:18
> A possible solution is to separate the context fields into a different table in the db. Not sure how complex it would make the sync though.

Maybe Kindle just treats duplicates as separate entries and do a "combined" query of entries with the same "stem" when displaying all the contexts? ("sten" is the form without inflections, "word" is the form in the sentence)

Following is the schema of Kindle VB's db file:

Schema for table: WORDS
(0, 'id', 'TEXT', 0, None, 0)
(1, 'word', 'TEXT', 0, None, 0)
(2, 'stem', 'TEXT', 0, None, 0)
(3, 'lang', 'TEXT', 0, None, 0)
(4, 'category', 'INTEGER', 0, None, 0)
(5, 'timestamp', 'INTEGER', 0, None, 0)
(6, 'profileid', 'TEXT', 0, None, 0)

Schema for table: LOOKUPS
(0, 'id', 'TEXT', 0, None, 0)
(1, 'word_key', 'TEXT', 0, None, 0)
(2, 'book_key', 'TEXT', 0, None, 0)
(3, 'dict_key', 'TEXT', 0, None, 0)
(4, 'pos', 'TEXT', 0, None, 0)
(5, 'usage', 'TEXT', 0, None, 0)
(6, 'timestamp', 'INTEGER', 0, None, 0)

Schema for table: BOOK_INFO
(0, 'id', 'TEXT', 0, None, 0)
(1, 'asin', 'TEXT', 0, None, 0)
(2, 'guid', 'TEXT', 0, None, 0)
(3, 'lang', 'TEXT', 0, None, 0)
(4, 'title', 'TEXT', 0, None, 0)
(5, 'authors', 'TEXT', 0, None, 0)
Schema for table: DICT_INFO
(0, 'id', 'TEXT', 0, None, 0)
(1, 'asin', 'TEXT', 0, None, 0)
(2, 'langin', 'TEXT', 0, None, 0)
(3, 'langout', 'TEXT', 0, None, 0)
Schema for table: METADATA
(0, 'id', 'TEXT', 0, None, 0)
(1, 'dsname', 'TEXT', 0, None, 0)
(2, 'sscnt', 'INTEGER', 0, None, 0)
(3, 'profileid', 'TEXT', 0, None, 0)

Schema for table: VERSION
(0, 'id', 'TEXT', 0, None, 0)
(1, 'dsname', 'TEXT', 0, None, 0)
(2, 'value', 'INTEGER', 0, None, 0)

[Program finished]

**Comment by Steven630** [comment] 2024-09-22 13:59
For those of you who do not review words on VB and wish more than one context of the same word to be retained (either because you have the same words with different meanings or just for more contexts of the same usage), I was able to achieve this with the following modifications to du.lua file (koreader/plugins/vocabbuilder.koplugin/db.lua) with the help of ChatGPT. 

1. Database Schema Update
Remove the UNIQUE constraint on the word column and introduce a UNIQUE constraint on the combination of word, prev_context, and next_context.

```
CREATE TABLE IF NOT EXISTS "vocabulary" (
    "word"          **TEXT NOT NULL,**
    "title_id"      INTEGER,
    "create_time"   INTEGER NOT NULL,
    "review_time"   INTEGER,
    "due_time"      INTEGER NOT NULL,
    "review_count"  INTEGER NOT NULL DEFAULT 0,
    "prev_context"  TEXT,
    "next_context"  TEXT,
    "streak_count"  INTEGER NOT NULL DEFAULT 0,
    "highlight"     TEXT,
    PRIMARY KEY(**"word", "prev_context", "next_context"**)
);
```

2. Modify insertOrUpdate Logic
Insert a new record only if both the word and the context are different. Modify the SQL query so that it checks for the word and context combination.

```
function VocabularyBuilder:insertOrUpdate(entry)
    local conn = SQ3.open(db_location)
    
    -- Insert or ignore title
    local stmt = conn:prepare("INSERT OR IGNORE INTO title (name) VALUES (?);")
    stmt:bind(entry.book_title)
    stmt:step()
    stmt:clearbind():reset()
    
    -- Insert a new word entry if the word with the same context does not exist
    stmt = conn:prepare([[
        INSERT INTO vocabulary (word, title_id, create_time, due_time, review_time, prev_context, next_context, highlight)
        VALUES (?, (SELECT id FROM title WHERE name = ?), ?, ?, ?, ?, ?, ?)
        ON CONFLICT(word, prev_context, next_context) DO UPDATE 
        SET title_id = excluded.title_id,
            create_time = excluded.create_time,
            review_count = MAX(review_count-1, 0),
            streak_count = 0,
            due_time = ?,
            highlight = ifnull(excluded.highlight, highlight);
    ]])
    
    stmt:bind(entry.word, entry.book_title, entry.time, entry.time+300, entry.time,
              entry.prev_context, entry.next_context, entry.highlight, entry.time+300)
    stmt:step()
    stmt:clearbind():reset()
    
    conn:close()
end
```
Just modify the db.lua. You may have to delete the previous sqlite3 file (vocabulary_builder.sqlite3 under the setting folder) to avoid conflits of db structure. I did not change the part that displays the words (for fear of messing up), so a same word would have separate entries in the review display.(Incidentally, this has the benefit of deleting a single usage without losing all the contexts). This is not perfect, but fit for my purpose, which is to export these words to Anki.  If you look up the exact same word (same context, same position), the word would not be added again.

As the author of the plugin @weijiuqiao  said, a more elegant solution would be to put context fields into a different table in the database. But he might be too busy to update the code anytime soon. 

Looking forward to further improvements. I might open a new feature request if necessary.

**Comment by Frenzie** [comment] 2024-09-22 14:19
Also keep in mind you can't do OTA updates in that case because they'll overwrite the files.

Depending on your desires, it might be a better idea to name it e.g. vocabbuilder2 so it's self-contained, and to disable the bundled plugin.

**Comment by Steven630** [comment] 2024-09-22 14:53
> Also keep in mind you can't do OTA updates in that case because they'll overwrite the files.
> 
> Depending on your desires, it might be a better idea to name it e.g. vocabbuilder2 so it's self-contained, and to disable the bundled plugin.

Thank you for your reminder. Do you mean that I should change the plugin's folder name? Anything else to do? The next time I do OTA updates, I just disable the bundled VB?

**Comment by Frenzie** [comment] 2024-09-22 15:42
It will always remain disabled if you disable it. The files however will be overwritten.

**Comment by Steven630** [comment] 2024-09-22 16:42
So just changing the plugin's folder name and disable the default plugin in the setting is enough? Do I copy the folder before renaming and sort of create another plugin or just rename the original folder?

**Comment by Frenzie** [comment] 2024-09-22 16:44
Renaming the original folder is fine. Don't forget to also change this:
https://github.com/koreader/koreader/blob/776cc21f1d856363b862627a2de4fe436f9ee597/plugins/vocabbuilder.koplugin/_meta.lua#L3

**Comment by Steven630** [comment] 2024-09-22 21:25
> Renaming the original folder is fine. Don't forget to also change this:
> https://github.com/koreader/koreader/blob/776cc21f1d856363b862627a2de4fe436f9ee597/plugins/vocabbuilder.koplugin/_meta.lua#L3

"Name" should be the same as the first part of the folder name. Is that right?

No need to change the "full name" in _meta.lua or lines in the main.lua?

**Comment by Frenzie** [comment] 2024-09-23 06:42
It's better if the name matches for clarity.

The full name is so you know which is which in the UI, otherwise you'll have two that are indistinguishable.

**Comment by ichnilatis-gr** [comment] 2024-09-23 11:19
And to think I only asked for one button... :-)

**Comment by Steven630** [comment] 2024-09-23 11:25
> And to think I only asked for one button... :-)

Sorry for having digressed a bit. Don't you think that having more contexts for different usages makes sense? 😊

**Comment by ichnilatis-gr** [comment] 2024-10-26 12:46
So what is the outcome of all this? What stage have we reached? Perhaps we should add the button I asked for as a first step and then see the rest? Now (v. 2024.07-259) I see that when I add a word that already exists, it just changes the book of origin of the word, while the previous context remains, even when the search is done directly from the dictionary and not from a book. I personally don't like that. I want to know which book the context is really from

**Comment by ichnilatis-gr** [comment] 2024-12-10 10:04
Would the "Search Vocabulary Builder" option (button) in the Dictionary dialog I asked for be something easier, at least to start with?

**Comment by weijiuqiao** [comment] 2024-12-11 13:26
After #12885 is merged, when adding a duplicate word, there'll be a dialog showing existing context, and buttons to overwrite or cancel.

**Comment by Steven630** [comment] 2024-12-11 14:56
> Supporting multiple contexts of the same word seems to be the ultimate solution? I've been quite preoccupied this year so haven't got time to implement it yet. If someone's interested, a PR is welcomed.

Better leave this issue open before multiple contexts are supported.

**Comment by ichnilatis-gr** [comment] 2024-12-11 15:05
> After #12885 is merged, when adding a duplicate word, there'll be a dialog showing existing context, and buttons to overwrite or cancel.

Thank you for your time!

**Closed** 2024-12-16 19:10 UTC
Labels: enhancement

**Comment by ichnilatis-gr** [comment] 2025-01-06 13:48
Dear @weijiuqiao, thank you for your last fixes. 
Sorry to bother you again, but I would like to ask what option we have, if we want to keep both occurrences of a word in the Vocabulary Builder. If we want to keep the context of a word as a verb and as a noun (if it is looks the same in both cases).
Thank you.
