### ISSUE TITLE
> 1 mitnute loading time on PDF, Boox poke 4 lite

### ISSUE THREAD

**Issue by luutuankiet** [koreader/koreader#10130] opened 2023-02-16 17:04 UTC
* KOReader version: 2023.01
* Device: Onyx boox poke 4 lite, android 11

#### Issue
Hi, first of all much appreciated having Koreader around. Really enjoy its customization capabilities as compared to Boox's closed stock reader app.

I have trouble loading the particular pdf file below on my device. Upon selecting the file it would take around 1 minute, sometimes more on the loading dialog to open it.
I have no problem opening the same file on my android phone (galaxy note 9, android 10, same Koreader version) which took a snapping 5 seconds load. So I suspect this has something to do with the device.
For more info, some other reader app I've tested on the same file :
- Neoreader, Moonreader : snappy ~5 seconds
- Koreader, ReadEra : 1 minutes or more.

#### Steps to reproduce
- Select the file to open.

[The Data Warehouse Toolkit_ The Definitive Guide to Dimensional Modeling ( PDFDrive ).pdf](https://github.com/koreader/koreader/files/10758527/The.Data.Warehouse.Toolkit_.The.Definitive.Guide.to.Dimensional.Modeling.PDFDrive.pdf)

**Comment by NiLuJe** [comment] 2023-02-16 17:27
$20 says it's Onyx stuff putting the device in standby!

(Snark aside, we'll need verbose debug logs & a logcat to help).

**Comment by luutuankiet** [comment] 2023-02-16 18:18
My experience with Onyx has never been pleasant; I love their minimal device designs but the OS... I try to opt for 3rd party apps any way possible.

Please find the log file here : 
[crash.log](https://github.com/koreader/koreader/files/10759220/crash.log)

**Comment by pazos** [comment] 2023-02-17 11:20
That's an ANR in 
```02-17 01:07:12.444 I/reader.launche( 2006): Thread[6,tid=2019,WaitingInMainSignalCatcherLoop,Thread*=0xb40000713bf342c0,peer=0x132801b0,"Signal Catcher"]: reacting to signal 3```

But looks that's not related to queued input events. There's no way to know it as tombstones cannot be pulled from device on release builds unless you're root.

I agree with @NiLuJe and raise the bet to $50 :/

Probably a duplicate of https://github.com/koreader/android-luajit-launcher/issues/395

Did you update the firmware recently or got in recently on last version available?

**Comment by luutuankiet** [comment] 2023-02-17 11:26
if it helps I tested with same conditions on another device, Boox Leaf 2 and got the same lengthy loading time. But I'd assume it's the same case with this device; they are both released in 22'.

**Comment by mergen3107** [comment] 2023-02-17 12:00
In that case I am afraid you are affected by Onyx’es new crappy storage they started using on both devices (and Tab Ultra). See mobileread Onyx forum for details (about Leaf 2 and Tab Ultra)

**Comment by luutuankiet** [comment] 2023-02-17 12:49
i see. bummer i have to resort to the stock reader app for this one file. 
on another note on the file side, what kind of metadata in a pdf can remarkably affect loading speed? i might somewhat make ammendments to the pdf to keep it with koreader.

**Comment by mergen3107** [comment] 2023-02-17 13:59
For PDF, usually the OCR scan layers are the culprit, then watermarks, then the uneven-background scan pages. Try using Foxit Phatom PDF or such to reduce the weight of the scan.

**Comment by mergen3107** [comment] 2023-02-17 14:00
Also, KOReader has its own OCR and dewatermark engine (bottom menu). Make sure to set these OFF by default, then wipe the sdr folder next to the pdf file and try again.

**Comment by mergen3107** [comment] 2023-02-17 14:00
(But this will remove all bookmarks and notes too, so maybe make a backup first?)

**Comment by pazos** [comment] 2023-04-28 20:51
Fixed? Maybe?. Check your firmware updates :see_no_evil:

**Closed by pazos** 2023-04-28 20:51 UTC
Labels: Android, firmware, not our bug
