### ISSUE TITLE
Crash after Reflow pdf

### ISSUE THREAD

**Issue by TheFuzzStone** [koreader/koreader#10887] opened 2023-09-09 23:39 UTC
* KOReader version: 2023.08
* Device: Onyx Boox Page

#### Issue

The title.

#### Steps to reproduce

1. Open Koreader
2. Open any .pdf
3. Bottom menu -> Reflow On -> select any value -> tap on screen

Crashlog: 

[crashlog.txt](https://github.com/koreader/koreader/files/12566883/crashlog.txt)

**Comment by NiLuJe** [comment] 2023-09-10 04:16
Dupe of #10533 (and quite a few others).

**Closed by NiLuJe** 2023-09-10 04:16 UTC
Labels: Android, duplicate
