### ISSUE TITLE
Pocketbook InkPad3 freezes on Resume

### ISSUE THREAD

**Issue by Jarcis** [koreader/koreader#4646] opened 2019-02-23 00:46 UTC
Hi,

I'm currently trying to install and use the really nice KoReader at my new Pocketbook Inkpad3. It is working fine in most cases, but unfortunately it has problems to resume from sleep mode:
When you are reading and then you want to change back form the sleep-mode (triggered with the Power button), the first restart/resume from this mode is working fine, but after a second time to resume from the sleep, the KoReader isn't responding. You are still able to go to the HomeScreen with the Home Button and start a new KoReader Task, but the old one still listed in the task managers is like freezed.
Here a quick summary:
KoReader-> Power Button -> Sleep -> Power-Button -> KoReader -> Power Button -> Sleep -> Power Button -> KoReader (freezed)

This behaviour isn't limited to the sleep-mode, but also a change from KoReader to the Homescreen is reproducing the same issue:
Koreader-> Home -> Task Manager -> KoReader -> Home -> Task Manager -> KoReader (freezed)
 Do you know this issue? 
I've read about the auto-suspension in the PocketBook software at #3540 but as I've seen this plugin has been included already into the KoReader long ago.

I've also started the koreader in Debug Mode, but I can't see any error in the log file:

[crash.log](https://github.com/koreader/koreader/files/2896359/crash.log)

Maybe you can help me with this issue :)
Thank you.

Best Regards,
Jarek

**Comment by NiLuJe** [comment] 2019-02-23 01:15
Try again with a current version?

**Comment by Jarcis** [comment] 2019-02-23 01:19
I've tried it not only with the latest available release, but also with an older one and the newest nightly - still the same error. By changing the releases I've also reseted the device to defaults and formated the memory

**Comment by NiLuJe** [comment] 2019-02-23 01:21
It's a question of being able to better follow logs: none of us are running a three months release. If it happened to be working on an earlier version, that would be helpful, but otherwise that just makes the report somewhat less useful ;).

Speaking of logs, if you could attach them instead of inlining them, that would also help making this more readable on mobile devices ;).

**Comment by Jarcis** [comment] 2019-02-23 01:41
Yes you are right - sorry for that :(

I've tried the same procedure now with the latest stable release :)
[crash_latest.log](https://github.com/koreader/koreader/files/2896352/crash_latest.log)

and the latest nightly 
[crash_nightly.log](https://github.com/koreader/koreader/files/2896343/crash_nightly.log)

**Comment by Frenzie** [comment] 2019-02-23 09:18
> I've read about the auto-suspension in the PocketBook software at #3540 but as I've seen this plugin has been included already into the KoReader long ago.

It hasn't been merged, so I'm afraid it's not included. Unfortunately it's not really something any of us without PocketBook devices can look into, although I suppose that since the required work in base has indeed been included for a while one might be able to mostly test it on the emulator.

**Comment by ersi-dnd** [comment] 2019-02-23 20:05
On Inkpad 3, Koreader also freezes (either Koreader freezes or it freezes the Pocketbook's soft) when the microSD disconnects. My personal Inkpad 3 is pretty bad in this respect: the microSD is hardly ever detected upon bootup (sometimes it is, but mostly not) and it drops off a bit too often randomly during poweron.

**Comment by tob1az** [comment] 2019-02-25 22:19
I've faced the same issue on my InkPad 3. It is also reproducible on a Touch HD 3 device. Looks like Koreader event thread hangs up on waking from sleep after the second EVT_BACKGROUND. I've been trying to find a solution and finally fixed it by replacing the forked-off PocketBook event handler process with a detached thread. Unfortunately, debugging didn't really help and the real problem is still unknown. It doesn't seem to be related to the autosuspension though.

Anyway, I could prepare a fix.

**Comment by Frenzie** [comment] 2019-02-25 22:28
@tob1az That'd be great, thanks!

**Comment by Jarcis** [comment] 2019-02-26 18:13
Yes, that would be fantastic :)

Koreader is a great software.

**Comment by tob1az** [comment] 2019-02-27 22:04
Here's my local build for testing https://www.dropbox.com/s/k54plyfrj4svbl7/koreader-pocketbook-arm-obreey-linux-gnueabi-v2019.02-95-g163853a_2019-02-26.zip?dl=0

**Comment by Jarcis** [comment] 2019-02-28 09:20
Big thx for your efforts,

I will test it when i'm back at home and will report later

**Comment by lengyelimrezsolt** [comment] 2019-03-02 09:47
Dear @tob1az, I have tested it on my Inkpad3, v.5.19.660. It works really great, except that the app returns with an empty screen, and I have to open the menu or turn the page etc. for the text to appear. Big thanks for this solution anyway!

**Comment by Jarcis** [comment] 2019-03-02 09:50
Yes, also from me a big thx for your work - i'am currently testing it without any issues on resuming from sleep :)

**Comment by pepefil** [comment] 2019-03-02 11:06
Tested on my Inkpad3 during the last two days. The problem is solved. As @lengyelimrezsolt says, sometimes (page turn, changing fontsize or render quality on reflowed pdf's, stop the lookup dictionary and show the results, etc.) is needed press anywhere on the screen to force a refresh, I think. But these problems are related to (if not the same) #3875, #1949 and others already referenced issues.
Howevwer, this is a great improvement. Now koreader can be used in the Inkpad3 as main reader on Inkpad3.
Huge thanks @tob1az.

**Comment by tob1az** [comment] 2019-03-02 11:39
@pepefil @lengyelimrezsolt the issue you've mentioned are most likely caused by the lack of proper PB autosuspend feature support mentioned in #3561. There were several attempt to fix it in #3540, 3477. I also have some ideas how to deal with it. The easiest but not really correct workaround is to disable the autosuspension completely for Koreader. The downside is that it would drain the battery faster, however I guess we need some statistics on this matter. Probably, it's not that bad and could be accepted as a trade-off solution, maybe with a switch in the menu to turn it off.

A more proper way would be to disable it only temporarily while running some long background tasks like loading a book, but it would require a big amount of time to implement and test.

**Comment by pepefil** [comment] 2019-03-02 12:06
I've just read #3561, #3540, and #3477, seems a really complex issue. I not a developper, and maybe this is a silly question, but there is no easy way to disable autosuspension when KOreader is awake and enable it when is sleeping?
In any case, the trade-off solution you suggested seems really useful.
Thanks again for your time and endeavors, tob1az.

**Closed** 2019-03-02 17:45 UTC
Labels: PocketBook, bug, duplicate
