### ISSUE TITLE
PDF page scaling is bogus

### ISSUE THREAD

**Issue by dluciv** [koreader/koreader#6340] opened 2020-07-01 14:45 UTC
* KOReader version: 2020.06
* Device: Pocketbook 740

#### Issue

PDF pages only take part of the screen as shown on the photo.

![MVIMG_20200701_172709](https://user-images.githubusercontent.com/1835030/86257489-48580900-bbc2-11ea-8d02-b98c1e33f637.jpg)

Other formats and UI are scaled properly.

#### Steps to reproduce

Just open any PDF... But not sure this happens everywhere =).

![MVIMG_20200701_172901](https://user-images.githubusercontent.com/1835030/86257351-19419780-bbc2-11ea-95a4-caa832ee7d33.jpg)

This also happened with 2020.05.
Before 2020.06 Koreader updated itself 2 or 3 times.

**Comment by Frenzie** [comment] 2020-07-01 15:10
There's no such a thing as PDF page scaling — at least not in a way like you're implying. The page simply abides by zoom modes (zoom to fit page, zoom to fit page width/height, etc.) This could be zoom to fit page if the PDF in question has an awful lot of whitespace, in which case zoom to page or content _width_ would do the trick.

@NiLuJe Could such a thing be the result of an incorrect/mismatched bit depth or something?

**Comment by Frenzie** [comment] 2020-07-01 15:11
Looks to be this paper, which displays in a normal manner for me:
https://web.eecs.umich.edu/~weimerw/p/p34-hooimeijer.pdf

**Comment by dluciv** [comment] 2020-07-01 17:16
For me it happens to all PDFs now. DJVUs are shown perfectly at the same time.

If I know how to remove Koreader or at least its settings properly and completely, I can try to reinstall it and check if it helps.

**Comment by NiLuJe** [comment] 2020-07-01 17:40
@Frenzie: I wouldn't think so, PB is and has always been 8bpp.

@dluciv: You haven't told us which zoom & display settings you're using. My money would be on yet another weird reflow/column/crop issue?

**Comment by dluciv** [comment] 2020-07-01 17:55
@NiLuJe No, I use no reflow (actually this was main feature of Koreader before I figured out that vendor software can also use no reflow =)), and when I change cropping, the picture changes slightly, but I still have no success.

When I switch refllow on, however, it displays columns correctly (but I want the whole page, as I said above). When I switch reflow off back, it becomes weird again.

Actually this happens to any PDF for me right now.

**Comment by Frenzie** [comment] 2020-07-01 20:59
Could you provide us with the metadata.lua file from the .sdr folder associated with one of the affected documents (after playing around with the zoom/crop a bit)? Perhaps some setting will jump out.

**Comment by dluciv** [comment] 2020-07-05 10:58
Sure. Sorry for delay.

I have opened fresh file with Koreader and [here are the both PDF and `.sdr` froder with `metadata.pdf.lua`](http://dluciv.sdf.org/koreader_issue/)

**Comment by Frenzie** [comment] 2020-07-05 15:00
Good news, your settings immediately replicate the problem. A relevant setting that turns the problem on and off seems to be dewatermark. It's not quite clear to me from an initial examination in combination with which settings that actually results in the problematic behavior though. If I just open the document without your settings and turn on dewatermark there's no problem. It'll need a slightly more systematic approach to find the trigger conditions.

![Screenshot_20200705_165120](https://user-images.githubusercontent.com/202757/86535327-d6dccb00-bedf-11ea-9871-597b486bdf79.png)

**Comment by Frenzie** [comment] 2020-07-05 15:06
Commenting this line gets rid of the problem.
```
["kopt_quality"] = 1.5,
```

There seems to be some problem with the document resolution while not reflowing, possibly cache based. To trigger:

1. Turn on reflow.
2. Select a rendering quality of low or high.
3. Turn off reflow.
4. Turn on dewatermark.

The rendering quality setting will now affect the resolution of the picture, but the program won't deal with it properly. It's probably just a minor cache issue somewhere.

**Comment by Frenzie** [comment] 2020-07-05 15:08
In order, low, default, high:

<img src=https://user-images.githubusercontent.com/202757/86535642-0c82b380-bee2-11ea-9508-6fa84afdac49.png width=30%><img src=https://user-images.githubusercontent.com/202757/86535643-0d1b4a00-bee2-11ea-962b-0b9cefb9c8f6.png width=30%><img src=https://user-images.githubusercontent.com/202757/86535644-0db3e080-bee2-11ea-9fd7-c5e770a5fb7a.png width=30%>

**Comment by yparitcher** [comment] 2020-07-05 15:08
might be related to #5878

**Comment by Frenzie** [comment] 2020-07-05 15:10
@yparitcher Thanks! Yes, that's almost certainly the same issue, and hopefully easy to fix with the above steps to reproduce. I doubt I'll look at it myself the next few days, so feel free to have a go. ;-)

**Comment by dluciv** [comment] 2020-07-05 16:15
Thank you, this helped me a lot!

>     1. Turn on reflow.
>     2. Select a rendering quality of low or high.
>     3. Turn off reflow.
>     4. Turn on dewatermark.

**Comment by yparitcher** [comment] 2020-07-07 20:54
**not** a cache issue.

if i have defaults of rendering quality high and dewatermark on for pdf's
when i clear the cache and purge .sdr (brand new file).

I get this:
![Reader_2020-07-07_155256](https://user-images.githubusercontent.com/38916402/86841911-85b11080-c072-11ea-8640-73c7f7a5f0b7.png)

**Comment by Frenzie** [comment] 2020-07-07 20:59
@yparitcher I'm not sure why I wrote "cache," that's not really what I meant. I mean that in non-reflow mode it's clearly expecting the "real" resolution/bbox while it's getting the processed one.

**Comment by yparitcher** [comment] 2020-07-07 21:53
should be fixed in koreader/libk2pdfopt#38

**Closed** 2020-07-08 23:02 UTC
Labels: PocketBook, bug, help-wanted
