### ISSUE TITLE
Black bottom area when opening with Koreader

### ISSUE THREAD

**Issue by toty88** [koreader/koreader#10640] opened 2023-07-04 03:00 UTC
* KOReader version:  koreader-android-arm64-v2023.06.apk 
* Device: Onyx Boox Leaf 2 (2023-05-05_17-28_3.3.2_6745dfaa5 firmware)

#### Issue
If I open **_with Koreader_** from within my Library I get this black area/ribbon at the bottom:

https://imgur.com/a19nP4v

But If I go to Apps - Koreader and open a book from Books folder I don't see that black area!

Also if I first open any title from Library and then try to open any from inside Koreader I get that black area too, so I have to delete cache from the App to get it back to normal!

That black area occupies the function area when not inside Koreader (back button, memory clear button etc).

I guess it's the same bug as #2876 but that was from 2017! 
#### Steps to reproduce

Go to Library
Press and hold over any book
Select option Open With
Select Koreader

It's driving me nuts so any suggestion is appreciated!

**Comment by mergen3107** [comment] 2023-07-04 04:19
In Leaf 2 settings, can you turn off the bottom buttons?

**Comment by mergen3107** [comment] 2023-07-04 04:21
Also, if you have access to adb/terminal, try to make KOReader (org.koreader.launcher package) immersive_full (you need to look up instructions, they are straightforward).

**Comment by toty88** [comment] 2023-07-04 13:34
Hi mergen, thank you for your reply but Wouldn't immersive_full hide my status bar? I really don't want that!

**Comment by pazos** [comment] 2023-07-04 14:07
Can you reproduce on v2023.04?

**Comment by mergen3107** [comment] 2023-07-04 14:54
If you set immersive_full for one package, then it will be immersive full only when you have this package open. Otherwise, KOReader itself doesn’t have status bar and navigation bar, so this trick is to make sure KOReader doesn’t get confused.

**Comment by toty88** [comment] 2023-07-04 21:08
> Can you reproduce on v2023.04?

With v2023.04 works fine. Any major fix I'm loosing staying in this version? 

> If you set immersive_full for one package, then it will be immersive full only when you have this package open. Otherwise, KOReader itself doesn’t have status bar and navigation bar, so this trick is to make sure KOReader doesn’t get confused.

I haven't had the chance to test it. I directly went for downgrading versions!

**Comment by pazos** [comment] 2023-07-04 21:23
Thanks for the feedback!

Duplicate of #10591

**Closed by pazos** 2023-07-04 21:23 UTC
Labels: need more info, Android

**Comment by mergen3107** [comment] 2023-07-04 21:24
You can see the major stable release notes here: https://github.com/koreader/koreader/releases. 

I don’t think there’s anything big you are missing unless you find something useful for yourself.

**Comment by Denisuu** [comment] 2023-11-28 22:44
I have the same problem on my Onyx Leaf 2 ever since I updated to v2023.10

**Comment by mergen3107** [comment] 2023-12-09 00:38
I don't think any of the devs has Leaf 1, so you need to at least provide logs from KOReader (enable verbose logs in FM, then restart, then go to Help - Report a bug - then a file "crash.log" will show up in /koreader folder on the device), lovs from logcat/pidcat while running KOReader
