### ISSUE TITLE
Force ocr for Arabic cause app crash

### ISSUE THREAD

**Issue by mhmadaladin** [koreader/koreader#11473] opened 2024-02-17 17:04 UTC
* KOReader version: 2024.01
* Device: kindle paperwhite 3 jailbroken by languagebreak & kual coplate installed 

#### Issue
Koreader crash when trying to highlight any arabic sentence after activating force ocr option.
#### Steps to reproduce
1. I put ara traineddata version 3.04 together with cube & para ...etc in /koreader/data/tessdata directory. These files are from [here](https://github.com/tesseract-ocr/tessdata/tree/3.04.00)
2. i changed 2 lines in defaults.lua as per wiki & copied them to defaults.custom.lua as such
-- document languages for OCR
DKOPTREADER_CONFIG_DOC_LANGS_TEXT = {"English", "Arabic"},
DKOPTREADER_CONFIG_DOC_LANGS_CODE = {"eng", "ara"},    -- language code, make sure you have corresponding training data
3. i tried to replace arabic trainedata v.3.04 to v.4 but when long press any word a message said ocr data could not be found

##### `crash.log` (if applicable)
i''m not an expert so here's the whole file
[crash.log](https://github.com/koreader/koreader/files/14319602/crash.log)

**Comment by mhmadaladin** [comment] 2024-02-18 18:03
problem solved thank god, after some trials i discovered the issue, the cube files were installed as txt file, i removed the .txt extension then restared and it worked.

**Comment by Frenzie** [comment] 2024-02-18 21:46
I don't fully understand how that could've happened, but in that case I'll close it.

How did you extract them?

**Closed by Frenzie** 2024-02-18 21:46 UTC

**Comment by mhmadaladin** [comment] 2024-02-19 18:17
I don't think this is the problem now, after adding the right cube files there is no mention of it in the crash log,
i think this is the error in the crash log now
<details>
  <summary>crash.log</summary>

```
<02/18/24-22:25:21 INFO  Restoring user input handling 
Error in pixWordMaskByDilation: imin = 1 is too small
Error in pixConnComp: pixs not defined
Error in boxaSelectBySize: boxas not defined
Error in boxaSelectBySize: boxas not defined
Error in pixaCreateFromBoxa: boxa not defined
Error in boxaSort2d: boxas not defined
Error in pixaSort2dByIndex: pixas not defined
Error in pixaaFlattenToPixa: paa not defined
Error in pixaGetBoxa: pixa not defined
Error in pixWordMaskByDilation: imin = 1 is too small
Error in pixConnComp: pixs not defined
Error in boxaSelectBySize: boxas not defined
Error in boxaSelectBySize: boxas not defined
Error in pixaCreateFromBoxa: boxa not defined
Error in boxaSort2d: boxas not defined
Error in pixaSort2dByIndex: pixas not defined
Error in pixaaFlattenToPixa: paa not defined
Error in pixaGetBoxa: pixa not defined
Error in pixWordMaskByDilation: imin = 1 is too small
Error in pixConnComp: pixs not defined
Error in boxaSelectBySize: boxas not defined
Error in boxaSelectBySize: boxas not defined
Error in pixaCreateFromBoxa: boxa not defined
Error in boxaSort2d: boxas not defined
Error in pixaSort2dByIndex: pixas not defined
Error in pixaaFlattenToPixa: paa not defined
Error in pixaGetBoxa: pixa not defined
./luajit: frontend/document/koptinterface.lua:1232: attempt to index field 'box' (a nil value)
stack traceback:
	frontend/document/koptinterface.lua:1232: in function 'getTextFromPositions'
	frontend/apps/reader/modules/readerhighlight.lua:1379: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:254: in function 'handleEvent'
	frontend/ui/uimanager.lua:907: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1436: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1534: in function 'handleInput'
	frontend/ui/uimanager.lua:1578: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00013ebd>
```
</details>
any help is appreciated & thanks in advance.

**Comment by mhmadaladin** [comment] 2024-02-19 18:18
@Frenzie

**Comment by Frenzie** [comment] 2024-02-19 20:47
While I couldn't reproduce any crashes, I think we can safely conclude the OCR quality isn't very good for Arabic.

<img src=https://github.com/koreader/koreader/assets/202757/de8f1a87-8df2-4a40-bd0f-106957f16ee9 width=45%>

Possibly a duplicate of #10583.

**Comment by mhmadaladin** [comment] 2024-02-20 03:50
Yes OCR for Arabic is not very good, but after checking the post you mentioned and some other posts I think it's not for Arabic pdf only, I hope you solve this issue soon.

**Comment by mhmadaladin** [comment] 2024-02-22 06:08
After some usage I can confirm the problem is mainly after reflow, when highlighting any word even when force OCR is off the app crash, 

without reflow and force OCR is off I can highlight text pdf without problems.
@Frenzie

**Comment by Frenzie** [comment] 2024-02-22 08:08
Thanks for the update.
