### ISSUE TITLE
Last file/Open previous document seems broken

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#6201] opened 2020-05-28 10:45 UTC
* KOReader version: v2020.05-9-g0fb9113_2020-05-26/
* Device: KA1

#### Issue
After restarting KOReader and then Open previous document I got different results depending on how many books are on History page.

With 2 books: second book opens
With 3 books: first book opens (preferable behaviour according to me) 
With 4 books: fourth book opens
With 5-7 books: second book opens
With 8 books: eighth book opens
With 9-13 books: second book opens
With 14 books: fourteenth book opens

#### Steps to reproduce
1. With several books on History, restart Koreader
2. Close History page (I have Start with: History)
3. Open previous document

**Comment by poire-z** [comment] 2020-05-28 11:05
If I set `Start with: History`, and restart and start with History, when I close it, I'm in File browser where there is no "Open previous document" (just Open last).
So, I guess that your next step "Open previous document", you do it via a gesture ? Right?

If right, can you try checking that the strange behaviour you observe only happens with the gesture (only when in file browser? elsewhere) - and that it does not happen with the menu items Open last/previous?
(If not right: more detailed steps :) what are you in after closing History? How do you open previous document.)

**Comment by gerhaher** [comment] 2020-05-28 11:14
Ok, ok. It's Open last then. But in file browsers gesture manager it says 'Open previous document'. :-)

The behaviour is the same whether you use multi gesture or open last document from menu.

**Comment by poire-z** [comment] 2020-05-28 11:34
Can't reproduce (with 4 or 5 docs in history): I always get the last one opening.

Can you enable `Display mode > Other settings > Show filename in Open last/previous menu items` - so at least you see what filename it is supposed to open - and see if that shown filename is already wrong - or if it is right, stuff is happening later then?

Anyway, all this showing and opening should use what's in your settings.reader.lua `lastfile` setting - so you might want to look at what it is in between KOReader close/start.

Anyway, the strange behaviour you see might indicate we're using `pairs` instead of `ipairs` somewhere, iterating a non-array table like if it were an array - or vice versa :) but I can't see where this would be done.
After you open a document (whether it was the last or wrongly another), before you close it, it is first in history, and is it what you see in `Last: ` if you go back to File browser?
Is it really after a restart that all is messed up?

**Comment by poire-z** [comment] 2020-05-28 11:50
Might have found a `pairs` that should be `ipairs` :) but it's like that since 2016!

https://github.com/koreader/koreader/blob/0fb9113078bb727134a010178a1caedd79e47f8e/frontend/readhistory.lua#L84-L94

Can you try changing `pairs` on line 87  to `ipairs`, and see if that solves it?

There's another one on line 111.
But I'm not sure why this codes does that, when it could just do:
`f:write("return " .. dump(self.hist) .. "\n")`.
May be dump() requires a non-array table? I see it uses `pairs`

**Comment by gerhaher** [comment] 2020-05-28 12:04
> Can you enable `Display mode > Other settings > Show filename in Open last/previous menu items` - so at least you see what filename it is supposed to open - and see if that shown filename is already wrong - or if it is right, stuff is happening later then?

Already have that. It shows the book that is then actually opened (i.e. already wrong here)

> If there's really a thing, probably cause by #6128 from 20 days ago - could it be bogus since then - or do you feel this is newer?

I've tested KOReader 2020.04.1 and KOReader 2020.05 "May Storm" on my other device, a Kobo Aura. 
And the problem appears with May Storm

**Comment by gerhaher** [comment] 2020-05-28 12:10
> Is it really after a restart that all is messed up?

AFAIK, for the moment, yes.

**Comment by poire-z** [comment] 2020-05-28 12:12
Before you try the pairs > ipairs switch, make a backup of your history.lua before and problematic. I'd like to see how it looks.

**Comment by gerhaher** [comment] 2020-05-28 12:20
No change with ipairs switch

**Comment by gerhaher** [comment] 2020-05-28 12:24
Oh, wait.

I switch line 111 too and now it seems to work.

**Comment by poire-z** [comment] 2020-05-28 12:46
Have you kept a history.lua that was cause the issue?
If you can't share it, try to see how it differs from one that is made and works after the ipairs switch.
(I still can't reproduce it, and my history.lua with pairs or ipairs are identical :/ but i guess that by using `pairs` , we might not save everything, or load everything, or something...)

Anyway, I guess this is the proper way to do it:
```diff
--- a/frontend/readhistory.lua
+++ b/frontend/readhistory.lua
@@ -84,11 +84,11 @@ end
 function ReadHistory:_flush()
     assert(self ~= nil)
     local content = {}
-    for k, v in pairs(self.hist) do
-        content[k] = {
+    for _, v in ipairs(self.hist) do
+        table.insert(content, {
             time = v.time,
             file = v.file
-        }
+        })
     end
     local f = io.open(history_file, "w")
     f:write("return " .. dump(content) .. "\n")
@@ -108,7 +108,7 @@ function ReadHistory:_read()
     self.last_read_time = history_file_modification_time
     local ok, data = pcall(dofile, history_file)
     if ok and data then
-        for k, v in pairs(data) do
+        for _, v in ipairs(data) do
             table.insert(self.hist, buildEntry(v.time, v.file))
         end
     end
```
Here's the file if you want to use it for a while and confirm it keeps this issue fixed: [readhistory.lua.txt](https://github.com/koreader/koreader/files/4695551/readhistory.lua.txt)

**Comment by gerhaher** [comment] 2020-05-28 12:50
history.lua:
[beforehistory.zip](https://github.com/koreader/koreader/files/4695575/beforehistory.zip)
[afterhistory.zip](https://github.com/koreader/koreader/files/4695576/afterhistory.zip)

**Comment by poire-z** [comment] 2020-05-28 12:54
Thanks. No change in look, but the "before" is only 4 items while "after" has 8 items - I guess you added some while testing.
(Updated my test file above.)

**Comment by gerhaher** [comment] 2020-05-28 12:55
> I guess you added some while testing.

Correct.

**Closed** 2020-05-29 13:07 UTC
