### ISSUE TITLE
FR: Faster text previews

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#9547] opened 2022-09-22 09:50 UTC
This is a holidays' idea that probably is already discussed somewhere, but I didn't find anything on a fast search.
Well, here goes:
One of the main cons new users find in KOReader is the time it takes to apply the font appearance changes.
Every change ex. font size+1, size+2, size+3, size-2, ..., must compute all the book's text, again and again.
I know this is intentional and I agree with this.
The way I've done it, was to open a small file and find the defaults with that, but not many users do that, and I can also understand this.

My proposition is to use a sample of the book's text.
When the user changes something in the lower menu (that, in my opinion should also include the font selection even as a duplicate control), that change can be made visible using only the text in the current html (if its small enough) or the text from couple of pages before and after.
After a change like this, a simple 2 button pop-up with "Apply to document" and "Cancel" must open and stay open until the user closes it.
This pop-up must be modal, to prevent the user to interact with the text, but must let the user interact with the lower menu to make more changes or close it, so that she can see a full preview of the changes.

I know that this is a lot more complicated under the hood, but I think it's doable.
The reason that I don't put some code where my mouth is, it's my lack of lua knowledge (since I can't find a way to easily write code and see the results 😛 ).

Anyway, I leave this here as a placeholder for discussion..

**Comment by poire-z** [comment] 2022-09-22 10:29
But... you're always on holidays !
Duplicate of #9087.
Very complicated to do, and the current behaviour is not intentional, it is a technical restriction in crengine.
And most often, you need to see the full pages and browse a bit of them to appreciate the changes - so a smaller modal popup won't always help.

**Comment by noembryo** [comment] 2022-09-22 10:38
>But... you're always on holidays !
Not always, just a month.. 😉 
You're right, much better told ..
Sorry for the false alarm..

**Closed** 2022-09-22 10:39 UTC
Labels: enhancement
