### ISSUE TITLE
Android: Gestures for Warmth makes it zero

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#8070] opened 2021-08-13 21:28 UTC
* KOReader version: [test apk](https://github.com/koreader/koreader/issues/4551#issuecomment-898294641) (because current stable doesn't have my device properly included yet)
* Device: Onyx Boox Kon-Tiki 2 (Android 10, rooted)

#### Issue
In the test apk, which uses Onyx driver for e-ink screen, if I control Brightness and Warmth from the Top Menu - Frontlight, everything works as intended. pidcat also reports proper values from 0 to 255 for both.

However, if I use default Gestures "swipe up/down along the right edge", Warmth is immediately set to zero. This is also confirmed by pidcat. Brightness is fine though.

I tried to manually set other increments for gesture than default, like 1, 2 - does not matter.

**Comment by pazos** [comment] 2021-08-13 22:13
Pinging @Galunid

**Comment by Galunid** [comment] 2021-08-14 15:28
I'll see what I can do, but no promises, since it's not really fault with my lights controller (I run into this when I was making it, and gestures/frontlight code passed "0" as a value to set). I looked into this back then, but nothing jumped out

**Comment by pazos** [comment] 2021-08-16 15:40
> I'll see what I can do, but no promises, since it's not really fault with my lights controller

I wasn't implying that. Just pinged you since I thought you would be able to reproduce on your device.

Also pinging @zwim to know if he can reproduce on a Tolino. I guess he won't as the first driver for custom lights controller was written by him for its own device and he's very nit-picker about these kind of features :smile: 

Maybe makes sense to have a fakeController enabled on the android x86 emulator to be able to test integration with the frontend?. Otherwise I won't be able to test the behaviour.

**Comment by zwim** [comment] 2021-08-16 16:32
On my Tolinos the right swipe works as expected.

**Comment by Galunid** [comment] 2021-08-17 03:35
```diff
diff --git a/frontend/device/android/powerd.lua b/frontend/device/android/powerd.lua
index 475636aa..fd368595 100644
--- a/frontend/device/android/powerd.lua
+++ b/frontend/device/android/powerd.lua
@@ -1,3 +1,4 @@
+local logger = require("logger")
 local BasePowerD = require("device/generic/powerd")
 local _, android = pcall(require, "android")
 
@@ -48,7 +49,7 @@ end
 
 function AndroidPowerD:setWarmth(warmth)
     self.fl_warmth = warmth
-    android.setScreenWarmth(warmth / self.warm_diff)
+    android.setScreenWarmth(warmth * self.warm_diff / 100)
 end
```

Works as expected, and I believe it makes sense. I'm a bit lost why it used to work on tolino though, so I'll investigate a bit more to not break it there ^^

**Comment by mergen3107** [comment] 2021-08-17 04:20
@Galunid 
Thank you for your time!
I tested this patch. It reports correct values 0-255 this time around, however, the actual brightness is at 0 anyway.
Maybe I should double check something else? Looks like something is different on my platform.

**Comment by Galunid** [comment] 2021-08-17 14:25
@mergen3107 Can you try [this](https://gofile.io/d/UKnYBz) file? Remove whatever version you have installed first

**Comment by mergen3107** [comment] 2021-08-18 02:01
@Galunid 
Thank you for the file! 
Results are following:
1) e-ink driver was not recognized at all
2) left-edge swipes do not change Brightness and show values 0-100, whereas pidcat correspondingly shows 0-255.
3) right-edge swipes do nothing. Upon further look, Warmth is not even listed among gestures. I think this is because (1).

**Comment by mergen3107** [comment] 2021-08-18 03:15
I think this is because 2021.05 didn't have Kon-Tiki 2 added to the list of devices, which happened in this commit: https://github.com/koreader/koreader/commit/2222f25422487e726db6c793de85af356e5fd493

**Comment by Galunid** [comment] 2021-08-18 11:06
@mergen3107 Sorry about that, try [this one](https://gofile.io/d/JF29EL). For the record, I added the device config, but forgot to set it to use the onyx light controller in place of the default one. This one should run the latest master and android-luajit. It also added some logging and rounding to int, which *may* help with light not being applied. Let me know if it does the trick. **Remove any previous version, before installing this.** Thanks for your time trying those.

**Comment by mergen3107** [comment] 2021-08-18 20:28
@Galunid 
Thank you very much!
I can confirm that everything now works as expected!
The driver was detected and Brightness and Warmth both change on their respective edges.

**P.S.** I don't know whether this is intended or not, but both Brightness and Warmth in KOReader have absolutely no connection to System Brightness and Warmth. I did this:
- Before opening newly reinstalled KOReader, setup System lights to some levels.
- entered KOReader and started to adjust them with edge gestures
- both started initially from 0, however the actual controls worked. 
- KOReader remembers it own values for lights. So if I then toggle System brightness with Onyx Glowlight control - the light leves will be set to System ones (which are different). If I use KOReader's gestures again, it will override to what was in KOReader again. So at least it is consistent with itself.

This is not an issue per se, but it jumped out on me because AFAIK in Kindle the system brightness was in sync with KOReader's brightness.

**Comment by mergen3107** [comment] 2021-08-18 20:45
Also, the gesture "Toggle Frontlight" toggles only KOReader's Brightness, while Warmth stays the same. Shouldn't it toggle both at the same time?

**Comment by pazos** [comment] 2021-08-18 22:06
>  I don't know whether this is intended or not, but both Brightness and Warmth in KOReader have absolutely no connection to System Brightness and Warmth.

Is not intended but not our bug. We read and write directly from/to sysfs nodes.  If your vendor provides a broken environment and some of the most hacked android roms is not something easily fixable, at least for us.

OTOH android devices with the generic controller should work this way: in app brightness is an override of system brightness that only applies to the app when it is on the foreground. Restarting the app should pick the (updated or not) values of the system. That's the intended behaviour that will apply to 99'999999999% of android devices. Devices outside the norm have no intended behaviour so we can consider ourselves lucky if basic brightness/warmth controls work fine in-app 😄 

> Also, the gesture "Toggle Frontlight" toggles only KOReader's Brightness, while Warmth stays the same. Shouldn't it toggle both at the same time?

That was an undocumented behaviour based on how most devices work: on a kobo/cervantes et al is not possible to turn off the frontlight without turning off warmth lights. If that's not the case on your device you need to fix it your specific device implementation. 

> If that's not the case on your device you need to fix it your specific device 

This sentence also applies to any setting that works fine on a sane device (kobo/cervantes or compliant android device) but not on hacked up AOSP devices. Patches welcome but won't fix by default :)

**Comment by mergen3107** [comment] 2021-08-19 09:09
@pazos Thank you for details :)

**Closed** 2021-08-19 13:55 UTC
Labels: Android, firmware

**Comment by hius07** [comment] 2021-08-19 18:59
@mergen3107, can you turn on flash_ui and press `Auto` checkbutton in the frontlight dialog.
I doubt if its width is okay after Checkbutton multilines PR (I have no device with warmlight to check).
https://github.com/koreader/koreader/blob/611a5311b69b0633ed6dfc7202244f42f93a7d33/frontend/ui/widget/frontlightwidget.lua#L402

**Comment by mergen3107** [comment] 2021-08-20 03:11
@hius07 
It looks like I don't have `Auto` checkbox in the front light dialog. 
`flashh_ui` is the Top Menu - Gear - Screen - E-ink settings - `Flash buttons and menu items`, right?

**Comment by hius07** [comment] 2021-08-20 03:29
Yes, flash_ui it is.
Okay, thanks, waitng for somebody to complain about incorrect width of the `Auto` button.

**Comment by mergen3107** [comment] 2021-08-22 14:08
> If your vendor provides a broken environment and some of the most hacked android roms is not something easily fixable, at least for us.

I found Onyx SDK that has Frontlight Controller example:
https://github.com/onyx-intl/OnyxAndroidDemo/blob/master/app/src/main/java/com/onyx/android/demo/FrontLightDemoActivity.java

Can this help to make a better controller?

**Comment by pazos** [comment] 2021-08-22 14:10
> > If your vendor provides a broken environment and some of the most hacked android roms is not something easily fixable, at least for us.
> 
> I found Onyx SDK that has Frontlight Controller example:
> https://github.com/onyx-intl/OnyxAndroidDemo/blob/master/app/src/main/java/com/onyx/android/demo/FrontLightDemoActivity.java
> 
> Can this help to make a better controller?

Nope

**Comment by mergen3107** [comment] 2021-08-22 14:11
OK :(

Thank you!
