### ISSUE TITLE
Auto warmth and night mode not working on Onyx Poke3

### ISSUE THREAD

**Issue by SingingDwarf** [koreader/koreader#12397] opened 2024-08-22 19:18 UTC
* KOReader version: 2024.07
* Device: poke3
* Build: fdroid

#### Issue
Auto warmth and night mode no longer working.  Has been the case for the last few (5-6) releases.

#### Steps to reproduce
[☑](https://www.alt-codes.net/check-mark-symbols.php) **Auto warmth and night mode** enabled

[☑](https://www.alt-codes.net/check-mark-symbols.php) According to the sun's position
Location set correctly

Warmth and night mode settings

[☑](https://www.alt-codes.net/check-mark-symbols.php) Control: warmth
Solar noon: 0%
Sunset and sunrise: 0%
Darkest time of civil twilight: 15%
Darkest time of nautical twilight: 15%
Darkest time of astronomical twilight: 20%
Solar midnight: 20%

[☑](https://www.alt-codes.net/check-mark-symbols.php) Frontlight off during day: 5 min offset

Currently active parameters show that backlight should be on @ 15% between 20:40 and 22:19, when it increases to 20%, before switching to 15% at 04:28 and going off at 05:51.

**Comment by Frenzie** [comment] 2024-08-22 19:37
It does work properly when you set night mode and temperature manually?

**Comment by SingingDwarf** [comment] 2024-08-22 19:44
Just tested - Frontlight with KOReader does not work manually

**Comment by Frenzie** [comment] 2024-08-22 21:13
Presumably that means the auto part of the equation isn't particularly relevant. However, the actual driver hasn't functionally changed in years afaik.

**Comment by pazos** [comment] 2024-08-23 09:41
@SingingDwarf: yup, fw updates might break old methods. Hopefully some new methods might still work on your device.

Duplicate of https://github.com/koreader/koreader/issues/8482

**Closed by pazos** 2024-08-23 09:41 UTC
Labels: Android
