### ISSUE TITLE
Fix Ubuntu Touch build

### ISSUE THREAD

**Issue by padraic7a** [koreader/koreader#4961] opened 2019-04-22 13:08 UTC
* KOReader version: nightly/v2019.04-48-gff843e0_2019-04-20
* Device: BQ M10 running Ubuntu Touch (devel branch 20190420)

#### Issue
Koreader fails to start

#### Steps to reproduce
Download nightly version, install, attempt to start

##### `crash.log` (if applicable)
crash.log isn't available
excerpt from unity8.log below https://pastebin.com/QCq60Mgx

**Comment by Frenzie** [comment] 2019-04-22 13:28
Duplicate of #4960.

**Closed by Frenzie** 2019-04-22 13:28 UTC
Labels: duplicate
