### ISSUE TITLE
Android can't lookup dictionary

### ISSUE THREAD

**Issue by MartletH** [koreader/koreader#8255] opened 2021-09-24 11:42 UTC
* KOReader version: v2021.08
* Device: evk_6sl_eink
* OS: Android Kitkat, api 19 Build flavor: rocks

#### Issue
Can't lookup dictionary

#### Steps to reproduce
Press and hold any word this pops up
![Reader_2021-09-24_191929](https://user-images.githubusercontent.com/21070822/134667705-1f1dc97a-87c9-4b4b-bcd3-a73d00462e2c.png)

There're dictionaries available.
I guess the dict look up function is using a different path reference method.
* The 2nd picture suggests that koreader can manage dicts, while the look up function can't reference to them.
* Koreader have correct path in settings.
settings.reader.lua
```
    ["dicts_order"] = {
        ["/storage/sdcard0/koreader/data/dict/stardict-comn_dictd03_wn-2.4.2/comn_dictd03_wn.ifo"] = 1,
        ["/storage/sdcard0/koreader/data/dict/stardict-oxford-gb-2.4.2/oxford-gb.ifo"] = 3,
        ["/storage/sdcard0/koreader/data/dict/stardict-xhzd-2.4.2/xhzd.ifo"] = 2
```
![Reader_2021-09-24_192050](https://user-images.githubusercontent.com/21070822/134668142-9c56ffed-4fb2-4a0d-bad5-27df10b950ee.png)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:

Checked crash.log, below two lines might be the reason,
<details>
  <summary>crash.log</summary>

```
09-24 19:16:35.360 I/dalvikvm( 2730): Could not find method android.content.Context.getExternalMediaDirs, referenced from method androidx.core.content.FileProvider.parsePathStrategy
09-24 19:16:35.360 W/dalvikvm( 2730): VFY: unable to resolve virtual method 288: Landroid/content/Context;.getExternalMediaDirs ()[Ljava/io/File;
```
</details>

Full crash.log
[crash.log](https://github.com/koreader/koreader/files/7225338/crash.log)

**Comment by mergen3107** [comment] 2021-09-24 12:07
If you search for the same word manually, do you find it?

**Comment by MartletH** [comment] 2021-09-24 13:09
> If you search for the same word manually, do you find it?

I've tried to edit the word and search, still no result with same output. Is this count for manual?

**Comment by mergen3107** [comment] 2021-09-24 14:44
> Could not find method android.content.Context.getExternalMediaDirs

Are you by chance using an SD card? If so, I am afraid KOReader cannot use them properly.

**Comment by MartletH** [comment] 2021-09-24 15:07
> > Could not find method android.content.Context.getExternalMediaDirs
> 
> Are you by chance using an SD card? If so, I am afraid KOReader cannot use them properly.
> 

I'm Not using external SDcard, but the Android folder and koreader folder is not under emulated folder, it's in sdcard0 folder. Maybe the device has internal SD. 
Can we fix the look up function for this system?

**Comment by Markismus** [comment] 2021-09-24 19:41
On android (Onyx Boox Note Pro) I set my dictionary location to an arbritary folder. Further reading at [this closed issue.](https://github.com/koreader/koreader/issues/7513)

**Comment by MartletH** [comment] 2021-09-25 00:13
> Apparently, Koreader doesn't know where to look for your dictionaries. On android (Onyx Boox Note Pro) I set my dictionary location to an arbritary folder by creating a text file `defaults.persistent.lua` containing the line:
> ```
> STARDICT_DATA_DIR = "/storage/emulated/0/dicts"
> ```
> Obviously, you should change the directory to your _absolute_ dictionary path. I placed the file in `/storage/emulated/0/koreader`.
> 
> Further reading at [this closed issue.](https://github.com/koreader/koreader/issues/7513)

Thank you, I tried with below file, still no result.
defaults.persistent.lua
'''
STARDICT_DATA_DIR = "/storage/sdcard0/koreader/data/dict"
'''

I guess the dict look up function is using a different path reference method.
* The 2nd picture suggest that koreader can manage dicts, the look up function can't reference to them.
* Koreader have correct path in settings.
settings.reader.lua
'''
    ["dicts_order"] = {
        ["/storage/sdcard0/koreader/data/dict/stardict-comn_dictd03_wn-2.4.2/comn_dictd03_wn.ifo"] = 1,
        ["/storage/sdcard0/koreader/data/dict/stardict-oxford-gb-2.4.2/oxford-gb.ifo"] = 3,
        ["/storage/sdcard0/koreader/data/dict/stardict-xhzd-2.4.2/xhzd.ifo"] = 2
'''

**Comment by pazos** [comment] 2021-09-25 14:13
There's nothing on the logs that tell us what's happening. Those `dalvikvm` warnings about missing instructions are expected on legacy android versions. The VM on device doesn't know about them and just replace their opcodes by valid ones that do nothing. Anyways all of those methods that require a certain minSdk above 14 are well covered behind `if` conditionals.

Also: the method to retrieve the path on the external storage works. If that didn't happen the program won't run at all (will crash on a early boot when trying to setup a cache).

So the problem is somewhere else. My suggestion would be to use a 3rd party app as a dictionary (Aard2, goldendict, colordict...) and forget about all this. If you want to dig a bit more you'll need to enable verbose logs and use a program, like `pidcat`, that's able to grab all logs produced by a given pid. Use it with the package name: `pidcat org.koreader.launcher` (or `pidcat org.koreader.launcher.fdroid` if you're running that flavor)

**Comment by Markismus** [comment] 2021-09-25 21:09
Maybe you could try some known working dictionaries. I've optimized a few for Koreader amongst [these](https://e.pcloud.link/publink/show?code=kZDhJ7ZBRkwNE50R4hz731AWB2RAb2Gmg3X).

**Comment by MartletH** [comment] 2021-09-26 09:44
> 
> 
> Maybe you could try some known working dictionaries. I've optimized a few for Koreader amongst [these](https://e.pcloud.link/publink/show?code=kZDhJ7ZBRkwNE50R4hz731AWB2RAb2Gmg3X).

Tried with "Oxford English Dictionary 2nd Ed_KoreaderOptimized_Nov21th2020", not working.

**Comment by MartletH** [comment] 2021-09-26 11:22
> 
> 
> There's nothing on the logs that tell us what's happening. Those `dalvikvm` warnings about missing instructions are expected on legacy android versions. The VM on device doesn't know about them and just replace their opcodes by valid ones that do nothing. Anyways all of those methods that require a certain minSdk above 14 are well covered behind `if` conditionals.
> 
> Also: the method to retrieve the path on the external storage works. If that didn't happen the program won't run at all (will crash on a early boot when trying to setup a cache).
> 
> So the problem is somewhere else. My suggestion would be to use a 3rd party app as a dictionary (Aard2, goldendict, colordict...) and forget about all this. If you want to dig a bit more you'll need to enable verbose logs and use a program, like `pidcat`, that's able to grab all logs produced by a given pid. Use it with the package name: `pidcat org.koreader.launcher` (or `pidcat org.koreader.launcher.fdroid` if you're running that flavor)

Thank you, Goldendict works fine on my device.
I'm not trying ADB or root to that ebook, too slow. Maybe when someone/(me sometime) testing android app can get log for system mounting to sd storage (or at least not default "emulated" dir).

**Comment by pazos** [comment] 2021-09-26 11:39
> Maybe when someone/(me sometime) testing android app can get log for system mounting to sd storage (or at least not default "emulated" dir).

All of this was tested and works fine on the 100% of devices I'm aware of. There's a method on the `Environment` class called `getExternalStorageDirectory` that returns the primary storage path for the device (no matter if it is the internal partition or an sdcard and no matter where it is mounted). We use it in https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/MainApp.kt#L97.

E-ink devices are, most of the time, poorly implementations of the android platform and miss some methods. But they can't bork that specific method because it is used in +90% of play store apps that deal with user files.

Again, no idea of what's happening but my guess would be: this is **very** device specific and firmware specific. Maybe a borked `libcore` that makes symlinking fail?: https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt#L26-L32

Please bump the ticket if you're able to reproduce on a different device (eink or regular android device).

**Comment by MartletH** [comment] 2021-09-26 11:47
Goldendict works fine on this device.
Bump the ticket when we're able to reproduce this issue on another device.

**Comment by MartletH** [comment] 2021-09-26 11:53
> 
> All of this was tested and works fine on the 100% of devices I'm aware of. There's a method on the `Environment` class called `getExternalStorageDirectory` that returns the primary storage path for the device (no matter if it is the internal partition or an sdcard and no matter where it is mounted). We use it in https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/MainApp.kt#L97.
> 
> E-ink devices are, most of the time, poorly implementations of the android platform and miss some methods. But they can't bork that specific method because it is used in +90% of play store apps that deal with user files.
> 
> Again, no idea of what's happening but my guess would be: this is **very** device specific and firmware specific. Maybe a borked `libcore` that makes symlinking fail?: https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt#L26-L32
> 
> Please bump the ticket if you're able to reproduce on a different device (eink or regular android device).

Issue closed, BTW, `getExternalStorageDirectory`  should work fine on my device. Since I can manage the dicts, and 'settings.reader.lua' gets the correct file path. Just can't **lookup**.

**Comment by ilyats** [comment] 2022-07-02 08:40
Log
[log1.log](https://github.com/koreader/koreader/files/9032672/log1.log)

**Comment by pazos** [comment] 2022-07-02 09:02
@ilyats: thanks for the log but there's a bit of info not catched. Could you uninstall the APK, install it again and get the log of the first time you run the APK?.

**Comment by ilyats** [comment] 2022-07-02 10:08
[log-v10.log](https://github.com/koreader/koreader/files/9032793/log-v10.log) By the way, I built debug apk from sources. Is there something I should try with it?

**Comment by ilyats** [comment] 2022-07-02 10:19
Sorry, I forgot to turn on verbose logging. 
[log3.log](https://github.com/koreader/koreader/files/9032811/log3.log)

**Comment by pazos** [comment] 2022-07-02 11:14
It is also truncated. I need the logs of the first run after installation. Mainly to check if there's an exception at linking `sdcv`. Because the other possible cause: SELinux restricting the execution of `sdcv` doesn't happen on your logs.

Verbose logs and other changes you've made inside the program are kept between installations, unless you remove `/sdcard/koreader`.

You don't need to remove `/sdcard/koreader`. Just uninstall the apk, install it again and execute `pidcat org.koreader.launcher > first_run.log` **before** executing the program. Then attach the file.

> I built debug apk from sources. Is there something I should try with it?

Not really but debug logs already have verbose logs enabled by default. In case you want to catch logs with that you'll need to use `org.koreader.launcher.debug` instead of `org.koreader.launcher` in `pidcat`.

**Comment by ilyats** [comment] 2022-07-02 11:22
The last logs should have been first run.  Here is another log
[log4.log](https://github.com/koreader/koreader/files/9032924/log4.log)

**Comment by ilyats** [comment] 2022-07-02 11:24
There was new version of sdcv released at 24.06, maybe something went wrong there?

**Comment by ilyats** [comment] 2022-07-02 15:12
Sorry, the last log was not very informative :( pidcat stopped producing any result, restarting device and restarting ADB server did not help.

**Comment by ilyats** [comment] 2022-07-02 15:25
Here is log with the release version 2022.06-10 
[log5.log](https://github.com/koreader/koreader/files/9033206/log5.log)
And one with the debug package
[log6.log](https://github.com/koreader/koreader/files/9033208/log6.log)

**Comment by pazos** [comment] 2022-07-02 19:18
The one with the debug package is indeed a fresh install. Aand it doesn't show any exception.

Buuuuuut,

> There was new version of sdcv released at 24.06, maybe something went wrong there?

Not really with the PR but there's something fishy around `sdcv` and the android way of doing things.

Could you try https://github.com/koreader/koreader-base/pull/1495#issuecomment-1172923014 with both 2022.06 and last nightly (both as fresh installs)?. If none of them work then you might be having two problems at once. Hopefully that's not the case

**Comment by mendelct** [comment] 2022-07-03 18:57
I'm having the same issue:
KOReader Version: 2022.06-10
Device: Samsung s10
OS: Android S api 31
my previous version 05.1-51 did not have this issue.
If I did this correctly the attached log is the first run after installation. 
[run.log](https://github.com/koreader/koreader/files/9035346/run.log)
.

**Comment by ilyats** [comment] 2022-07-22 18:03
Dictionary search works again on Nova 3 Color as of v2022.06-40

**Comment by Frenzie** [comment] 2022-07-22 18:09
Yes, I reverted that patch for now in https://github.com/koreader/koreader/pull/9340 but please keep don't discuss that in this unrelated issue.

**Comment by pazos** [comment] 2024-01-04 12:09
I'm going to close this ticket, feel free to ping me if you still experience the issue on devices other than ` evk_6sl_eink`

**Closed by pazos** 2024-01-04 12:09 UTC
Labels: Android, firmware
