### ISSUE TITLE
Wifi doesnt work inside koreader but in original os

### ISSUE THREAD

**Issue by x3oo** [koreader/koreader#10572] opened 2023-06-12 22:01 UTC
* KOReader version: recent
* Device: Pocketbook inkpad 3 pro

#### Issue
Downloading news or dictionaries doesnt seem to work. The device does open webpages in its original browser but doesnt download anything inside koreader. it does ask me to activate wifi, which it does but after that nothing happens.
#### Steps to reproduce
Open koreader and try to download something. for example news or dictionaries. regardless if wifi is activated in original os beforehand.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content her
![wind-generation (1)](https://github.com/koreader/koreader/assets/1851074/ef061071-6a36-4c4e-b0e0-348f92c94be4)
e>
```
</details>

**Comment by pazos** [comment] 2023-06-12 22:17
Duplicate of #10183

**Closed by pazos** 2023-06-12 22:17 UTC
