### ISSUE TITLE
Latest KOReader from F-Droid crashes on startup

### ISSUE THREAD

**Issue by quantenzitrone** [koreader/koreader#11399] opened 2024-01-23 16:57 UTC
* KOReader version: v2024.01
* Device: SHIFT6m
* OS: Android 8.1.0

#### Issue

crashing

#### Steps to reproduce

open koreader

##### `crash.log`
<details>
  <summary>crash.log</summary>

```
--------- beginning of main
01-23 17:43:24.585 I/MainActivity(24094): loading libluajit
01-23 17:43:24.600 I/Assets  (24094): loading lib7z
01-23 17:43:24.607 I/Lights  (24094): Using Generic driver
01-23 17:43:24.684 I/Assets  (24094): Skip installation for revision v2024.01
01-23 17:43:24.685 I/dlopen  (24094): dl.dlopen - libs/libkoreader-lfs.so => /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
01-23 17:43:24.689 E/dlopen  (24094): error dlopen'ing /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so: dlopen failed: "/data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so" is 32-bit instead of 64-bit
01-23 17:43:24.689 E/KOReader(24094): error: [string "dl.lua"]:73: error dlopen'ing /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so: dlopen failed: "/data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so" is 32-bit instead of 64-bit
01-23 17:43:24.689 W/dlopen  (24094): could not find library /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
01-23 17:43:24.690 E/KOReader(24094): error: [string "dl.lua"]:167: could not find library /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
01-23 17:43:24.691 E/NativeThread(24094): Failed to run script: error loading module 'libs/libkoreader-lfs' from file 'libs/libkoreader-lfs.so':
01-23 17:43:24.691 E/NativeThread(24094): 	dlopen failed: "/data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so" is 32-bit instead of 64-bit
```
</details>

**Comment by quantenzitrone** [comment] 2024-01-23 17:11
there seem to be 3 different v2024.01 on F-Droid

2 from 2024-01-15 of which one is incompatible with my device

1 from 2024-01-22 that is "suggested" which crashes

the, compatible one of the older ones works tho

**Comment by offset-torque** [comment] 2024-01-23 17:51
Confirming on Android 11/arm64-v8a with the same crash log.

**Comment by Frenzie** [comment] 2024-01-23 18:03
How do you pick between arm64-v8a vs armeabi-v7a on F-Droid? I only see a choice of 2024.01, 2023.10, etc. I can't tell which of the two that is, even though my phone supports both.

In any case I use the regular 64-bit build from our own server.

**Comment by pazos** [comment] 2024-01-23 18:15
We don't control F-droid build process. You should report this to them so they can trigger a rebuild.

Unless you manage to reproduce the issue on one of the apks from github, of course.

**Comment by quantenzitrone** [comment] 2024-01-23 19:27
> How do you pick between arm64-v8a vs armeabi-v7a on F-Droid? I only see a choice of 2024.01, 2023.10, etc. I can't tell which of the two that is, even though my phone supports both.

F-Droid doesn't show the architecture, for that I used NeoStore. Both F-Droid and NeoStore hide unsupported versions by default, but it can be disabled in the settings.

**Comment by quantenzitrone** [comment] 2024-01-23 19:47
Can someone else open an issue on f-droids issue tracker? I don't have a gitlab.com account anymore due to their phone number requirement.

**Comment by Frenzie** [comment] 2024-01-23 20:41
> Both F-Droid and NeoStore hide unsupported versions by default, but it can be disabled in the settings.

It doesn't say which version is which, but though Help → Report a bug I saw that the suggested version was arm64, which works fine for me. I installed the arm version and that works too.

I have a Realme 7 Pro, Android 12.

**Comment by pazos** [comment] 2024-01-23 21:06
> Confirming crash with f-droid install, and that the build from github works, doesn't crash. Happily, the f-droid app's "issues" link points here, and here I found the fix. Thanks!

Both versions are mostly the same and the issues should be reproducible on both versions. The only thing that changes is the build environment. Pinging @linsui, maybe he can trigger a rebuild.

**Comment by licaon-kter** [comment] 2024-01-24 06:37
One can enable Expert mode in F-Droid Client and the expand Versions in Koreader app details.


On my Android 13 neither versions (armv7, arm64) crash on a fresh install.

Is this only about updated apps?

Can somebody test a fresh install?

**Comment by offset-torque** [comment] 2024-01-24 07:10
@licaon-kter 
Confirming that fresh install works. I uninstalled and reinstalled the crashing version. Everything is ok now.

**Comment by licaon-kter** [comment] 2024-01-24 09:03
I've installed v2023.08, start, open a file
Update to v2024.01, start, open a file, all ok no crash

I've installed v2023.10, start, open a file
Update to v2024.01, start, open a file, all ok no crash

what are the conditions for the crash? update from which version? which arch?

**Comment by licaon-kter** [comment] 2024-01-24 09:08
> Confirming crash with f-droid install, and that the build from github works, doesn't crash.

if you install fresh, since you need to do that anyway to switch from F-Droid to Github, you will not see the issue anyway

@pazos rebuild of what and how? 

@bet now reinstall from F-Droid, does it work fine?

@quantenzitrone does a fresh install work fine?

**Comment by licaon-kter** [comment] 2024-01-24 09:24
I've tried all sorts of combos, older arm64 update to newer arm64, older armv7 to newer arm64, older arm64 to newer armv7, to no avail

`dlopen failed: "/data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so" is 32-bit instead of 64-bit` sound to me like the Android package installer (not F-Droid lol) failed to clean up old libs before installing new updated ones or something. 

Looking inside the APKs said lib .so is as it should 32-bit for armv7 and 64-bit for arm64

**Comment by shuvashish76** [comment] 2024-01-24 15:10
Crashes for me updated from previous v2023.10 to v2024.01 (F-Droid). Using arm64-v8a.
Logs: 
[KO-crash.txt](https://github.com/koreader/koreader/files/14040036/KO-crash.txt)
Device details: Lenovo TB-8704X, android 9

**Comment by licaon-kter** [comment] 2024-01-24 15:17
@shuvashish76 what if you uninstall and reinstall?

**Comment by shuvashish76** [comment] 2024-01-24 15:21
Installed from GitHub (latest) - no crash
Fresh install v2024.01 (F-Droid) - no crash
Fresh install v2023.10 (F-Droid) - no crash
Update from v2023.10 to v2024.01 (F-Droid) - no crash

So basically it's a one time crash for me 🤷🏿, check if the longs are useful else I'll  install few more times & try to reproduce it

**Comment by licaon-kter** [comment] 2024-01-24 16:07
That was not my experience on Android 13, maybe it's a bug that was fixed after Android 11?

one interesting bit, the date of the APKs in F-Droid, armv7 is Jan 15 and arm64 is Jan 22, hence that's why many ended up with the armv7 version first and today they update to the arm64 one

**Comment by bet** [comment] 2024-01-24 16:51
The github build worked for me, but I wanted to get back to f-droid (for updates), so since there've been a couple of f-droid updates since the problem, I uninstalled the github build and reinstalled with the latest from f-droid, and it seems to be fine, hooray!

**Comment by pazos** [comment] 2024-01-24 18:10
@licaon-kter: thanks for your time!

> dlopen failed: "/data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so" is 32-bit instead of 64-bit sound to me like the Android package installer (not F-Droid lol) failed to clean up old libs before installing new updated ones or something.

It isn't the android package installer. These assets are uncompressed by our own code when there's a mismatch between the current installation and the assets bundled into the apk. The extractor works by overwritting all files in the APK bundle.

> rebuild of what and how?

nvm, it doesn't make sense if it cannot be reproduced on fresh installs.

I have no idea what happens here, but I wouldn't mind to stay ignorant as long as it is a matter of uninstalling and installing again.
It is weird it doesn't happen on our own flavor (and I cannot reproduced in fdroid flavor, updating from 2023.10 to 2024.1)

**Comment by Frenzie** [comment] 2024-01-24 18:23
I have upgraded in both directions in the past without issue.

**Comment by eighthave** [comment] 2024-01-24 19:40
Some ARM64 CPUs no longer support 32-bit, which is a new development https://www.androidauthority.com/arm-32-vs-64-bit-explained-1232065/

**Comment by Frenzie** [comment] 2024-01-24 19:46
Indeed, but that's a separate issue. ^_^

**Comment by projectgus** [comment] 2024-02-01 01:33
I think @shuvashish76 and @licaon-kter are on the money!  The seven days between the v2024.01 armeabi-v7a build and the arm64-v8a build is what triggers a crash when the armeabi-v7a v2024.01 build updated to arm64-v8a.

The android-luajit-launcher asset management unpacks new assets from the APK into the app's filesystem when it detects the git revision embedded in the APK has changed:
https://github.com/koreader/android-luajit-launcher/blob/89adc64607c8173f0583ea5b172c2d6de993762d/app/src/main/java/org/koreader/launcher/Assets.kt#L38

Both these APKs have version `v2024.01` (checked), so when F-Droid updated build 101331 (armeabi-v7a v2024.01) to build 101332 (arm64-v8a v2024.01), android-luajit-launcher didn't detect it as an update and kept the old 32-bit libraries in the app's local files.

**Comment by kolAflash** [comment] 2024-02-19 21:33
F-Droid issue: https://gitlab.com/fdroid/fdroiddata/-/issues/3174

**Comment by licaon-kter** [comment] 2024-02-19 21:39
@kolAflash and?

**Comment by licaon-kter** [comment] 2024-02-20 12:57
close this then :)

**Closed** 2024-02-20 15:09 UTC
Labels: bug, Android
