### ISSUE TITLE
Feature request - View source code file as text file

### ISSUE THREAD

**Issue by yunlhan** [koreader/koreader#4875] opened 2019-04-04 16:33 UTC
* KOReader version: v2019.3
* Device: Kobo Aura HD and Kindle touch 3G (K5)

#### Issue

This post is actually a feature request.

#### Steps to reproduce

At the moment if files are not supported according to their file extensions by KOReader, those files will not show up in KOReader File Browser. Say if I want to browse the source code of a github project, I check out the repo folder and copy the folder to Kobo and Kindle, fire up KOReader but from File Browser only text files `*.md` etc. can be seen. Is it possible for KOReader to open source code files like `*.c`, `*.js` etc. as text files so that we can read everything in the folder as we do on a desktop? 

Thank you.

**Comment by Frenzie** [comment] 2019-04-04 18:23
Fairly sure it's a duplicate, but yes, that'd be nice to have. :-)

**Comment by Thra11** [comment] 2019-05-26 17:09
I had a little play with this (See [branch](https://github.com/Thra11/koreader/tree/dirty-open-anything-as-text)). It kind-of-works, although it will happily try to open any file and should almost certainly have an option to enable the behaviour. It isn't amazing for reading source code at the moment, as it removes all the blank lines when it renders it (#5042)

**Comment by pazos** [comment] 2019-06-08 17:25
Duplicate of #3578

**Closed by pazos** 2019-06-08 17:25 UTC
Labels: duplicate, enhancement
