### ISSUE TITLE
Saving doc properties not working

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6691] opened 2020-09-21 16:17 UTC
* KOReader version: 2020.09
* Device: Kobo Forma

#### Issue

Not so much a bug report, but rather a question. When I try to modify doc settings with a script, the changes are not being applied. What am I doing wrong?

#### Steps to reproduce

1) In the plugin I use self.ui.doc_settings:saveSetting(setting, value) to save a setting. For example when trying to save the font size:
```` self.ui.doc_settings:saveSetting("font_size", 20) ````

2) Then I reload the current ebook with this code:
````
if self.ui and self.ui.menu then
                self.ui.menu:exitOrRestart(function()
                    UIManager:restartKOReader()
                end)
            end
````
But no font size changes have come into effect.

Adding this before reloading the ebook also doesn't help:

```` self.ui.doc_settings:flush() ````

**Comment by poire-z** [comment] 2020-09-21 16:41
> When I try to modify doc settings with a script

External script ? Or plugin ?
If external script, might be an error making the metadata.epub.lua invalid, and metadata.epub.lua.old would be used instead.

Now considering it's with a plugin:
> `self.ui.doc_settings:saveSetting("font_size", 20)`

First, try it with  `self.ui.doc_settings:saveSetting("this_is_my_test", 20)` and see if you see it saved.
If yes, it might just be that ReaderFont is saving it too, _after you_, overriding your value with its own managed one. In that case, just set the value directly to ReaderFont : `self.ui.font.font_size = 20` and it will save it for you.

**Comment by smartscripts-nl** [comment] 2020-09-21 18:13
Plugin...

**Comment by smartscripts-nl** [comment] 2020-09-21 18:16
There are some more settings I want to save to the Docsettings. I'm trying to write a plugin to restore predefined sets of lay-outs to the Docsettings. So font family, font gamma, font size etc. This way I hope to quickly change the lay-out of an ebook, without having to go through all the various corresponding settings in the footer menu.

**Comment by Frenzie** [comment] 2020-09-21 18:19
What are you missing from profiles and Dispatcher? It's probably better to improve those than to try something parallel. ^_^

**Comment by smartscripts-nl** [comment] 2020-09-21 18:33
Aha, thanks: I hadn't found out yet that it was possible to use Profiles for  lay-out options. But I am definitely missing an option here to set the display font for the current document. For the reset the Profiles seem to have everything I was looking for.

**Comment by smartscripts-nl** [comment] 2020-09-21 19:25
The possibility to enable or disable a cluster of custom styletweaks in one fell swoop through a profile would also be nice.

**Comment by yparitcher** [comment] 2020-09-21 22:13
> Aha, thanks: I hadn't found out yet that it was possible to use Profiles for lay-out options. But I am definitely missing an option here to set the display font for the current document and option for font gamma (Contrast). For the reset the Profiles seem to have everything I was looking for.

when i went through `creoptions` (the bottom menu in crengine) adding eveything to `dispatcher`, adding `font_gamma` would always crash, since it works now i added it in https://github.com/koreader/koreader/pull/6694

for changing fonts is more difficult:
a event callback to change the font is needed in `readerfont`, and also a function to return a list of fonts that `dispatcher` could show the user.

> The possibility to enable or disable a cluster of custom styletweaks in one fell swoop through a profile would also be nice.

this would require the same in `readerstyletweek`

if there are any other events i missed or settings that don't have an event please post them as i may have not got all of them.
I never got around to add all the settings in `koptoptions` (mupdf) as i could not figure out how they were triggered (not all of them use events)

_____

If you are looking to chose a style for a book the first time you open it, the `docsettingtweak` plugin might help, it allows setting any setting in `metadata.lua` directly with a custom value. it is applied per directory. (for if you have different types of books that need different fonts/languages etc. sorted by folder.)

**Comment by smartscripts-nl** [comment] 2020-09-21 22:42
Alas, #6694 doesn't work for me: it doesn't cause KOReader to crash, but it also doesn't change the setting for font_gamma. Whatever I tried, the only way to get font_gamma to change seems to be to manually enter it in the bottom menu.

**Comment by yparitcher** [comment] 2020-09-21 22:54
> Alas, #6694 doesn't work for me: it doesn't cause KOReader to crash, but it also doesn't change the setting for font_gamma. Whatever I tried, the only way to get font_gamma to change seems to be to manually enter it in the bottom menu.

there is a known bug that the toggle in the bottom menu does not update, but the setting is changed. see https://github.com/koreader/koreader/pull/6106#issuecomment-649077061

is the menu not updating or is the contrast also not changing?

**Comment by smartscripts-nl** [comment] 2020-09-21 22:58
The contrast is also not changing.

**Comment by smartscripts-nl** [comment] 2020-09-21 23:52
For now this works for me (in the profile I've activated several lay-out configurations, including font_gamma, and I've linked CopyLayout:onSetDisplayFontSouvenir() event handler:

````
function CopyLayout:setFont(face)
    self.ui.font.font_face = face
    self.ui.document:setFontFace(face)
end

function CopyLayout:setGamma(value)
    self.ui.document:setGammaIndex(value)
    self.ui.document.gamma_index = value
    self.ui.doc_settings:saveSetting("gamma_index", value)
end

function CopyLayout:onSetDisplayFontSouvenir()
    self:setGamma(30)
    self:setFont("Souvenir Lt BT")
    self:refresh()
end

-- seems to prevent a jump to last page after manually making bottom menu indicate correct font gamma:
function CopyLayout:refresh()
    self.ui:handleEvent(Event:new("RedrawCurrentView"))
end

````

Using this, I see last of all the message that font gamma has been set to 1.9. And then indeed the display in de bottom menu doesn't show this update of font gamma, but manually setting the correct value there doesn't change the font gamma, so it already had been set to 1.9. This seems to be the bug you mentioned.

**Comment by smartscripts-nl** [comment] 2020-09-21 23:57
I've also noticed that the Profile manager regularly "forgets" previously chosen settings. For example activating "dual pages" setting seems to be forgotten after every change for another setting that I make to the profile, of after a reload of KOReader.

**Comment by yparitcher** [comment] 2020-09-22 00:29
> CopyLayout

if you are hacking the backend you can just use the native methods for example:
`require ReaderFont` and change this function https://github.com/koreader/koreader/blob/221b71062a9c0d330b3b8d9ff5f54402d4a4be64/frontend/apps/reader/modules/readerfont.lua#L278 to a event `onSetFont`, and rename https://github.com/koreader/koreader/blob/221b71062a9c0d330b3b8d9ff5f54402d4a4be64/frontend/apps/reader/modules/readerfont.lua#L78 and you can call it safely from your code and it will take care of doing everything needed to refresh etc.

**Comment by yparitcher** [comment] 2020-09-22 00:30
> I've also noticed that the Profile manager regularly "forgets" previously chosen settings. For example activating "dual pages" setting seems to be forgotten after every change for another setting that I make to the profile, or after a reload of KOReader.

can't reproduce, can you try on an unaltered version of koreader to ensure your tweaks are not causing it?

**Comment by smartscripts-nl** [comment] 2020-09-24 15:07
> > I've also noticed that the Profile manager regularly "forgets" previously chosen settings. For example activating "dual pages" setting seems to be forgotten after every change for another setting that I make to the profile, or after a reload of KOReader.
> 
> can't reproduce, can you try on an unaltered version of koreader to ensure your tweaks are not causing it?

I can't reproduce anymore either. So I guess it was a temporary glitch, caused by my own code.

**Comment by poire-z** [comment] 2020-09-24 15:11
Closing as it's not really an issue for us to fix.
But continue asking questions in here when needed.

**Closed by poire-z** 2020-09-24 15:11 UTC
