### ISSUE TITLE
FR: [Adding w3m terminal web browser]

### ISSUE THREAD

**Issue by Lezcool** [koreader/koreader#10793] opened 2023-08-08 20:41 UTC
I think it will be a great idea and very helpful to add terminal web browser to the koreader.
I found a thread here: https://www.mobileread.com/forums/showthread.php?p=4309191
I guess it is not very difficult. Thank you.
@Frenzie

**Comment by pazos** [comment] 2023-08-08 20:51
Hi.

It is not very difficult and already covered elsewhere. So it is a win-win :)
Hopefully, if you're interested, the same individual that wrote the guide to do what you want to do is able to provide support if you struggle with one of the steps.

As for bundling it with the app: please no.

It isn't **just** because it is a pain to ship another binary, make sure it works on each platform, create wiki pages for it, cover on the user guide and maintain it ad-infinitum.

It isn't **just** because whatever the terminal browser we choose to ship will be followed by suggestions of another cool binaries that do other cool stuff, or opinions about better implementations of a binary we're already shipping.

It isn't **just** because it has nothing to do with the scope of the program.

**Comment by pazos** [comment] 2023-08-08 20:56
Duplicate of #9407

**Comment by NiLuJe** [comment] 2023-08-08 21:29
We probably have a very different definition of "convenient" ;o).

(TL;DR: My bote is very very very far into the way out-of-scope camp ^^)

**Comment by Lezcool** [comment] 2023-08-08 21:37
Actually, for me the (a little bit out of scope) text editor is what I use the most in koreader. lol

**Comment by Frenzie** [comment] 2023-08-08 21:43
> We probably have a very different definition of "convenient" ;o).

Depending on the website it can be quite convenient in Elinks or w3m. However… either I'm at home with a pc/laptop/phone close at hand, or I'm not in which case I have to grab my phone to turn on my hotspot by which time I might as well have already read it on my phone… so the use case doesn't quite exist 99% of the time. :-)

But that aside. The terminal emulator allows you to run just about anything from Alpine or Debian with ease, so it's really already included in that sense. I doubt there's much of an argument for anything else to be pre-included — Vim maybe? (RIP Bram) ;-)

**Comment by Lezcool** [comment] 2023-08-08 22:10
Maybe I am one of the few people who is easily distracted by mobile phones and computers, so when reading or thinking, I try to stay away from these devices.  Otherwise I might start doing other things as soon as I get my phone.  This makes the kobo with koreader installed the perfect device for me if basic web browsing is available.  Of course this is just based on personal experience, I'm not sure how many are like me.

**Comment by Frenzie** [comment] 2023-08-09 13:10
Sure, our position's just that following instructions like the ones linked is pretty simple while including it would be a maintenance burden.

Incidentally for Alpine this link might be of interest: https://wiki.alpinelinux.org/wiki/Alpine_Linux_in_a_chroot

I haven't tried it myself at this time, but it's extremely close to what I do with Debian. The big advantage of Alpine is that installing packages is much faster, and for use on a Kobo the larger selection of packages in the Debian repos might not even matter.

**Closed** 2023-08-11 20:09 UTC
Labels: enhancement, duplicate, out-of-scope
