### ISSUE TITLE
KOReader crashes after prolonged sleep on KA1

### ISSUE THREAD

**Issue by agaAdams** [koreader/koreader#2340] opened 2016-11-13 10:57 UTC
* KOReader version: v2015.11-681
* KSM v8
* Device: KA1, FW 4.1.7729

#### Issue
When I put the KA1 to sleep (button or sleep cover) for approx 20min or longer KOReader either crashes back to KSM8 or wakes up but does not recognise single taps:

##### First scenario:
- automatical Wifi connection restore after resume turned __ON__
- put KOreader for 20min to sleep
- KOreader wakes up
- no single tap actions on the screen are recognised
- long presses for highlighting/dictionary lookup works
- only way to restart is to power off through long button press

##### Second scenario
- automatical Wifi connection restore after resume turned __OFF__
- put KOreader for 20min to sleep
- after wake up KOReader crashes back to KSM

Here the crash.log, the first one with wifi restore ON, the second one without
```
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 11/13/16-09:00:22
[ko-input] Forked off fake event generator(pid:2982).
[11/13/16 @ 09:00:49] Kobo Suspend: Going to sleep . . .
[11/13/16 @ 09:00:49] Kobo Suspend: Asked the kernel to put subsystems to sleep
[11/13/16 @ 09:00:51] Kobo Suspend: Waited for 2s because of reasons...
[11/13/16 @ 09:00:51] Kobo Suspend: Synced FS
[11/13/16 @ 09:00:51] Kobo Suspend: Asking for a suspend to RAM . . .
[11/13/16 @ 10:28:35] Kobo Suspend: ZzZ ZzZ ZzZ? (0)
[11/13/16 @ 10:28:35] Kobo Suspend: Woke up!
wlarm_le: wl driver adapter not found
ifconfig: SIOCGIFFLAGS: No such device
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 11/13/16-10:32:34
[ko-input] Forked off fake event generator(pid:3306).
[11/13/16 @ 10:33:09] Kobo Suspend: Going to sleep . . .
[11/13/16 @ 10:33:09] Kobo Suspend: Asked the kernel to put subsystems to sleep
[11/13/16 @ 10:33:12] Kobo Suspend: Waited for 2s because of reasons...
[11/13/16 @ 10:33:12] Kobo Suspend: Synced FS
[11/13/16 @ 10:33:12] Kobo Suspend: Asking for a suspend to RAM . . .
sh: write error: Operation not permitted
[11/13/16 @ 10:33:12] Kobo Suspend: ZzZ ZzZ ZzZ? (1)
[11/13/16 @ 10:33:12] Kobo Suspend: Woke up!
Segmentation fault
```

**Comment by agaAdams** [comment] 2016-11-15 09:38
I updated to KOReader v2015.11-689 and although I get the same message in crash.log KOReader does not crash any more.
`wlarm_le: wl driver adapter not found
ifconfig: SIOCGIFFLAGS: No such device`

**Comment by houqp** [comment] 2016-11-15 09:46
`wlarm_le: wl driver adapter not found ifconfig: SIOCGIFFLAGS: No such device` is expected and not harmful. But there is no reason for us to not get rid of them. I don't recall anything from between 681 to 689 will cause a segfault. So it will might happen again. Did you restart the device after the upgrade?

**Comment by agaAdams** [comment] 2016-11-15 15:32
No, I did not. But I did restart it several times with the 681 build and could reproduce the crash.

**Comment by houqp** [comment] 2016-11-16 09:09
This is weird then. Closing this for now since you can't reproduce it. Please reopen it when it happens again.

**Closed by houqp** 2016-11-16 09:09 UTC
