### ISSUE TITLE
newsdownloader fails to download valid RSS feed

### ISSUE THREAD

**Issue by silberzwiebel** [koreader/koreader#3633] opened 2018-01-28 10:49 UTC
* KOReader version: v2018.01.10-nightly / v2015.11-1457-g7feea40.apk
* Device: inkbook prime (android based e-ink device)

#### Issue

The valid feed https://osbn.de/feed.rss won't be downloaded with NewsDownloader. It just says that the format is unsupported.
I've [tested the validity here](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fosbn.de%2Ffeed.rss) and there is only one recommendation to be a even more valid feed ;).
The [XKCD feed](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fxkcd.com%2Frss.xml) (for which NewsDownloader won't download the images and which is thus pretty useless, but this is another issue), has the same recommendation but it works with the NewsDownloader.

I had a look with `adb logcat` but no message related to the problematic feed was printed at all.

#### Steps to reproduce

Add the line
```
	{"https://osbn.de/feed.rss", limit = -1}
```

to your `feed_config.lua` and start news downloading. (I've also tested with http, no success.)

**Comment by Frenzie** [comment] 2018-01-28 11:37
It gives off an `unknown protocol` error. The error isn't captured in this line:

https://github.com/koreader/koreader/blob/b16c93bbe50c72130ef84b5bd508404c10f8426a/plugins/newsdownloader.koplugin/main.lua#L218

This is no surprise, for although the site *claims* to be using HTTPS there's not actually any encryption involved! So it's not the feed that's broken, but the server configuration.

**Comment by silberzwiebel** [comment] 2018-01-29 09:09
Thanks for the quick response :)

For the record: I tried to use the http URL also with no success.

Once there is a proper error message, will there also be a workaround the faulty server configuration?

**Comment by Frenzie** [comment] 2018-01-29 10:55
The error message thing is mostly tangential, except that it's annoying that a user doesn't get anything useful and that I had to add something like this:

```
bla, err = httpRequest({ url = url, sink = ltn12.sink.table(resp_lines), }) 
logger.dbg(err)
```

For this particular case it shouldn't take long to implement a workaround, but long-term I don't really want to deal with any of that stuff (redirects, different protocols, etc.) at all. 

I think including lua-http (wasn't available a few years ago) would be the most promising way to deal with various problems along these lines, instead of having to think up workarounds for various issues like these ourselves, but I haven't yet found the time or motivation.

**Comment by mwoz123** [comment] 2018-01-29 12:17
> I think including lua-http (wasn't available a few years ago) would be the most promising way to deal with various problems along these lines, instead of having to think up workarounds for various issues like these ourselves, but I haven't yet found the time or motivation.

Agree. That why I created https://github.com/koreader/koreader/pull/3618, but I can't make it a library (maybe after upgrade to upcomming Ubuntu 18.04 LTS will work), so I [decided to only externalize backend in this PR and prepare code for further engine selection](https://github.com/koreader/koreader/pull/3618#issuecomment-361092597).

>Edit: someone should probably more or less just copy this in a PR so that the specific error is displayed in the log:

I added @Frenzie 's code (mixed with code from https://github.com/koreader/koreader/issues/3596#issuecomment-358938843)

To PR https://github.com/koreader/koreader/pull/3618

But there's a problem with saving files, I believe it's around this line:
https://github.com/koreader/koreader/pull/3618/files#diff-17a7fb48fe6727b445dbfa79f04c4c55R50-51
as it creates 0b files with correct names.
Help appreciated.

**Comment by mwoz123** [comment] 2018-01-29 20:47
yes, this seems issue with http**S** not 301 redirects. 
unfortunately changing implementation to translator.lua way didn't fix the problem.

Probably will have to wait for lua-http backend PR.

**Comment by Frenzie** [comment] 2018-01-29 20:58
Well of course it wouldn't. You'd have to add in a simple fallback to use http.request instead of https.request, which works perfectly fine. Giving better error messages is just good practice.

**Comment by mwoz123** [comment] 2018-01-29 21:39
Unfortunately it's above my abilities in lua. 
Could you directly point what needs to be changed?
In the http methods in lua are still a mystery for me.

**Comment by mwoz123** [comment] 2018-01-29 21:51
> Edit: sorry, I was testing with the wrong feed config. http.request won't do HTTPS even when HTTPS is misconfigured to use no encryption. Whoops. :-P

ok. so it will wait for lua-http

**Comment by prog-amateur** [comment] 2018-02-15 13:41
Hi, I am interested about Koreader, mainly because of RSS and Calibre wireless sync. 
Just to be sure to understand the situation : at the moment, RSS feed is only possible with http URLs ? 
Thank you

**Comment by Frenzie** [comment] 2018-02-15 14:24
HTTPS works fine but redirects don't necessarily. That's fairly unlikely to be a problem for just the feed itself.

**Comment by mwoz123** [comment] 2018-02-15 14:44
Redirect (https://github.com/koreader/koreader/pull/3652) should work fine (nightly builds newer than 2018/02/01) if I'm not wrong the problem was HTTPS. 
Which should be solved when we have lua-http.

@prog-amateur if you're able to build lua-http as library I should be able to add it do NewsDownloader?

Please note that Atom also should work (not only RSS).

Kind of alternative is in progress:
https://github.com/koreader/android-send2ebook (android UI)
based on: 
https://github.com/mwoz123/send2ebook/ (core + commandline)

works this way:
share url -> convert to epub -> store to ftp -> receive in Koreader (1 more commit and I'll create koreader PR)

on Android on your browser choose "Share via" and then "Send2Ebook"
from commandline "send2ebook.sh/bat url_address"

**Comment by prog-amateur** [comment] 2018-02-18 15:54
Thank you very much. I will test it once my Kobo will come back from the dealer (back-light display issue). 
Is this program works on Linux ? I see a bat file, so I am not sure (I am not an expert sorry in advance). Thank you.

**Comment by mwoz123** [comment] 2018-02-20 09:43
> Is this program works on Linux ? I see a bat file, so I am not sure (I am not an expert sorry in advance). Thank you.

Works. Yesterday I fixed commandline version.For linux/unixes just use `send2ebook.sh` from [`commandline`](https://github.com/mwoz123/send2ebook/tree/master/commandline) :
> unix:
send2ebook.sh www.a_url.com
Can send many articles at once:
send2ebook.sh www.a_url.com www.another_url.eu www.other_url.com www.somethingelse.eu

quote from: https://github.com/mwoz123/send2ebook/#usage

ps: Just remember to edit [FtpConnection properties](https://github.com/mwoz123/send2ebook/blob/master/commandline/FtpConnection.properties). Maybe one time I or someone else will write GUI for it..

**Comment by Thra11** [comment] 2019-04-30 19:51
I tested the link in the first comment of this issue (using latest koreader from git), and it seems to have worked ok. Is it possible that the recent update to luasec-0.8 has fixed this? Or has the server for that particular feed changed since this issue was opened?

**Comment by Frenzie** [comment] 2019-04-30 20:08
@Thra11 It's still using regular HTTP on `https://`, so probably not. But I can confirm that it's working. Closing then.

**Comment by NiLuJe** [comment] 2019-04-30 20:08
IIRC, I remember @Frenzie mentioning that the redirect thing was indeed fixed, so it's quite possible?

**Closed** 2019-04-30 20:08 UTC
Labels: enhancement
