### ISSUE TITLE
set  [onyx color] mode

### ISSUE THREAD

**Issue by skypebj** [koreader/koreader#12164] opened 2024-07-15 04:37 UTC
koreader works fine on my reader, but I can't adjust the screen background brightness. In the test, the compatibility test mode
[tools--more tools--developer options--start compatibility test--test light--onyx color] can be conditional brightness. So, where can you set up to adopt this mode.

**Comment by skypebj** [comment] 2024-07-15 04:37
andriad 4.4

**Comment by pazos** [comment] 2024-07-15 17:37
Duplicate of https://github.com/koreader/koreader/issues/8482

**Closed by pazos** 2024-07-15 17:37 UTC
