### ISSUE TITLE
202407 version cannot open pdf and png in kindle8

### ISSUE THREAD

**Issue by brucehu666** [koreader/koreader#12700] opened 2024-11-02 11:05 UTC
* KOReader version: 202407
* Device: kindle8

#### Issue
after update, the pdf and png files cannot be opened.

#### Steps to reproduce
autoupdate and find this issue.

####
manually download the old version and manually unzip the zip file to a tmp folder and then overwrite to the /mnt/us/koreader  folder.
the issue is gone. 
I have to stay in old version now.

**Comment by benoit-pierre** [comment] 2024-11-02 11:15
Please provide `crash.log`.

**Comment by benoit-pierre** [comment] 2024-11-02 11:16
Also, maybe try the latest nightly.

**Comment by benoit-pierre** [comment] 2024-11-02 11:20
On a semi-related note, how about renaming the MµPDF label to MuPDF? The `µ` is annoying to type (4 keystrokes! the strain!).

**Comment by Frenzie** [comment] 2024-11-02 11:50
@NiLuJe You okay with losing the µ?

> The µ is annoying to type (4 keystrokes! the strain!).

Fwiw for me it's just Alt Gr. + m.

**Comment by mergen3107** [comment] 2024-11-02 13:57
`µ` itself sounds like "mü". `Mµ` never made sense to me because it sounds like "Mmü" :D

**Comment by NiLuJe** [comment] 2024-11-02 17:02
My OCD will survive without it, yeah ;).

(It's Shift + * on ISO FR, but I have absolutely no clue where it's hidden in the god-awful Apple AZERTY layout, so I can clearly believe it's behind some arcane gymnastics there).

**Comment by Frenzie** [comment] 2024-11-02 18:23
> `µ` itself sounds like "mü". `Mµ` never made sense to me because it sounds like "Mmü" :D

Not even. It's really just MmPDF. ;-P But agreed, it should be µPDF if you're going that way. Anyway, changing the tag…

**Comment by benoit-pierre** [comment] 2024-11-20 22:27
I'm going to assume this was already fixed in the nightlies, feel free to reopen if you can reproduce with v2024.11.

**Closed by benoit-pierre** 2024-11-20 22:27 UTC
Labels: MuPDF
