### ISSUE TITLE
Kobo Touch Random Input

### ISSUE THREAD

**Issue by SatyrTheTablecloth** [koreader/koreader#10590] opened 2023-06-17 07:37 UTC
* KOReader version: 2023.05.01
* Device: Kobo Touch, Software Version 4.35.20400

#### Issue
Wherever I touch on the Kobo Touch screen, it does not correspond to the correct place in KOReader.  Sometimes touching in the center will activate the top right corner, sometimes it's random.  I've had more luck with long presses but the issue seems to be screen calibration.

#### Steps to reproduce

Install KOReader on a 2011 Kobo Touch and see if the touch input is calibrated to the right place on the screen.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment] 2023-06-17 08:18
Possibly related to https://github.com/koreader/koreader/pull/9738, however the fact that you say "random" could also indicate hardware failure. A fairly typical issue is that the touch input is upside down compared to the display for some reason, requiring translation (or vice versa but the end result looks the same).

It might help to provide some verbose debug logs as requested by the issue template, unless @NiLuJe happens to have exactly the same model Touch lying around. ;-)

**Comment by SatyrTheTablecloth** [comment] 2023-06-17 11:18
the Kobo Touch itself works fine and I've never had any similar issues using it normally.  While trying to read a book on KOReader, on one of the few occasions I could even get that far, touching it in various places would always be interpreted as touching the top right corner.  How might I create a debug log?

**Comment by Frenzie** [comment] 2023-06-17 16:57
> If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with verbose debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both Enable debug logging and Enable verbose debug logging.
You'll need to restart KOReader after toggling these on.

**Comment by NiLuJe** [comment] 2023-06-17 17:15
I'll also need the *full* debug log to confirm the device identification, because https://github.com/koreader/koreader/issues/10107 might be at play here, too ;).

**Comment by SatyrTheTablecloth** [comment] 2023-06-19 06:22
The problem is, I can't actually navigate there.  Here's what I'm talking about
https://github.com/koreader/koreader/assets/43323122/0cf63916-fd6d-4e1d-aaca-b6309aee3872

**Comment by Frenzie** [comment] 2023-06-19 07:05
It's probably easiest to edit this to `./reader.lua -d "$@" >>crash.log 2>&1`

https://github.com/koreader/koreader/blob/64f778d97d26a267a48c5a0cd123ba15e7e3bdd4/platform/kobo/koreader.sh#L401

**Comment by Frenzie** [comment] 2023-06-19 08:45
To ./reader.lua **-d** "$@" >>crash.log 2>&1

**Comment by SatyrTheTablecloth** [comment] 2023-06-21 10:08
okay, did that.  Now how do I find the debug log it generates?

**Comment by Frenzie** [comment] 2023-06-21 11:20
.adds/koreader/ directory for Kobo

**Comment by SatyrTheTablecloth** [comment] 2023-06-23 10:03
Here is the crash log from the last time I used it
[crash.log](https://github.com/koreader/koreader/files/11847217/crash.log)

**Comment by NiLuJe** [comment] 2023-06-23 10:09
Okay, yeah, you actually have a Touch B (according the the input stream, at least), but it's detected as a Touch C, so this is definitely a duplicate of #10107.

The good news is that Kobo just released a FW update, and it should be fixed there, so, you can just update Nickel ;).

**Closed by NiLuJe** 2023-06-23 10:09 UTC
Labels: Kobo

**Comment by SatyrTheTablecloth** [comment] 2023-06-23 10:16
I just check it for updates but the last one was from 2022.  Was it just released?

**Comment by SatyrTheTablecloth** [comment] 2023-06-23 10:18
nevermind, I found it.  I should use the Kobo B one, right?

**Comment by NiLuJe** [comment] 2023-06-23 10:23
Yes (getting it wrong should be mostly harmless on a device so EoL it's not even funny, though ;)).

**Comment by SatyrTheTablecloth** [comment] 2023-06-23 10:31
now I can't seem to run KOReader, and have tried deleting the folder from the .adds directory and reinstalling it, but no dice.  The installer tells me it can't find a mounted Kobo, but it is indeed mounted

**Comment by NiLuJe** [comment] 2023-06-23 10:39
On which OS would that be?

(I just double-checked, and the USBMS scripts haven't changed, so nothing should be affecting this from the Kobo's side, anyway).

**Comment by SatyrTheTablecloth** [comment] 2023-06-23 11:16
KOReader 2023.05.01 and Kobo version 4.37.21533

**Comment by NiLuJe** [comment] 2023-06-23 11:41
I meant the host OS you're attempting to run the OCP install script on.

**Comment by SatyrTheTablecloth** [comment] 2023-06-23 11:49
Mac OS Ventura 13.4.1

**Comment by NiLuJe** [comment] 2023-06-23 14:36
I was afraid you were going to say that ;o).

I don't have access to modern macOS devices, so it's entirely possible diskutil (or some other lower layer of the darwing stack) changed behavior, breaking the script.

I haven't *heard* about any of that before, though, FWIW.

In any case, as far as you're concerned, you'll likely have to do it by hand instead of relying on the script.

**Comment by SatyrTheTablecloth** [comment] 2023-06-23 15:28
okay.  Could you point me in the right direction for how to do that?

**Comment by NiLuJe** [comment] 2023-06-23 15:29
If you got your hands on the OCP install script, you were in the right place, as they're right above it.

https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices
https://www.mobileread.com/forums/showthread.php?t=314220

**Comment by Frenzie** [comment] 2023-06-24 09:34
@NiLuJe 
> I don't have access to modern macOS devices, so it's entirely possible diskutil (or some other lower layer of the darwin stack) changed behavior, breaking the script.

Nope, output from diskutil is sane on 13.4.1.

```
KOBO_MOUNTPOINT="$(diskutil info -plist "KOBOeReader" | grep -A1 "MountPoint" | tail -n 1 | cut -d'>' -f2 | cut -d'<' -f1)"
```

Ultimately results in `/Volumes/KOBOeReader` (unless you have multiple plugged in or something).

You do need to give permission to the terminal though.

@SatyrTheTablecloth 
Could you post the output from `diskutil list`? Or at least the relevant part for the ereader.

**Comment by SatyrTheTablecloth** [comment] 2023-06-27 10:17
Last login: Tue Jun 27 12:15:45 on ttys000
danielschmidt@MacBook-Air ~ % diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *251.0 GB   disk0
   1:             Apple_APFS_ISC Container disk1         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk3         245.1 GB   disk0s2
   3:        Apple_APFS_Recovery Container disk2         5.4 GB     disk0s3

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +245.1 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD - Data     125.4 GB   disk3s1
   2:                APFS Volume Macintosh HD            9.1 GB     disk3s3
   3:              APFS Snapshot com.apple.os.update-... 9.1 GB     disk3s3s1
   4:                APFS Volume Preboot                 4.7 GB     disk3s4
   5:                APFS Volume Recovery                797.2 MB   disk3s5
   6:                APFS Volume VM                      2.1 GB     disk3s6

/dev/disk4 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +22.8 MB    disk4
   1:                  Apple_HFS Transmission            22.7 MB    disk4s1

/dev/disk5 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            KOBOSD                 *2.0 GB     disk5

/dev/disk6 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            DADSKOBO               *1.4 GB     disk6

**Comment by SatyrTheTablecloth** [comment] 2023-06-27 10:18
(KOBOSD is the SD Card in the Kobo, and DADSKOBO is the Kobo)

**Comment by Frenzie** [comment] 2023-06-27 10:56
That explains the script's failure to find it. It's looking for KOBOeReader. I'm not sure this is really detectable this way other than by checking everywhere for .kobo or something m

**Comment by NiLuJe** [comment] 2023-06-27 11:28
Yeah, renaming the partition label is definitely not supported ;).

**Comment by SatyrTheTablecloth** [comment] 2023-07-01 07:47
so I changed the name back, installed firmware update 4.37.21533 for Kobo Touch A/B, reinstalled KOReader and I have the same issue.  I wondered if my Kobo C firmware was the problem but it seems like it wasn't

**Comment by NiLuJe** [comment] 2023-07-01 13:22
What does your `.kobo/version` file look like?

Another verbose debug log would also be helpful.

As would the results of `ntx_hwconfig -s /dev/mmcblk0 2>/dev/null` (ideally in a proper SSH shell, but a snapshot of the Terminal plug-in ought to do).

**Comment by SatyrTheTablecloth** [comment] 2023-07-03 12:06
here's the version: Last login: Wed Jun 28 12:50:33 on console
/Volumes/KOBOEREADER/.kobo/version ; exit;
danielschmidt@MacBook-Air ~ % /Volumes/KOBOEREADER/.kobo/version ; exit;
/Volumes/KOBOEREADER/.kobo/version: line 1: N905B2132C8CE,2.6.35.3,4.35.20400,2.6.35.3,2.6.35.3,00000000-0000-0000-0000-000000000320: command not found

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...       2 completed.

[Process completed]

**Comment by NiLuJe** [comment] 2023-07-03 12:35
> 4.35.20400

Well, there you have it.

Turns out you *haven't* actually updated to 4.37, so your device is still flagged as a Touch C ;).

**Comment by SatyrTheTablecloth** [comment] 2023-07-19 12:39
Okay, I upgrade to 4.37: 

Last login: Sat Jul 15 10:03:23 on console
/Volumes/KOBOEREADER/.kobo/version ; exit;                                      
danielschmidt@MacBook-Air ~ % /Volumes/KOBOEREADER/.kobo/version ; exit;
/Volumes/KOBOEREADER/.kobo/version: line 1: N905B2132C8CE,2.6.35.3,4.37.21586,2.6.35.3,2.6.35.3,00000000-0000-0000-0000-000000000320: command not found

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...      20 completed.

[Process completed]
