### ISSUE TITLE
Crash when downloading Dictionaries on Pocketbook Touch Lux 4

### ISSUE THREAD

**Issue by TheBolshe** [koreader/koreader#12874] opened 2024-12-08 15:37 UTC
* KOReader version:  v2024.11 (Same issue happened with previous version)
* Device: Pocketbook Touch Lux 4 (Vivlio version V627.6.7.1974)

#### Issue

The app crashes when trying to download Dictionaries from the app

#### Steps to reproduce

Open the app, go to Download dictionaries, try to download one (i tried English-english Wikitionary and Italian-English Wikitionary), the app prompts to activate wifi, say yes, then the app crashes

##### `crash.log` (if applicable)
[crash.log](https://github.com/user-attachments/files/18052793/crash.log)

**Comment by NiLuJe** [comment] 2024-12-08 16:19
Duplicate of #9422

TL;DR: InkView pulls in a different version of OpenSSL, and forcefully initializes it on load. This breaks our own OpenSSL at runtime.

**Closed** 2024-12-08 16:19 UTC
Labels: bug, PocketBook, duplicate, firmware, can't fix

**Comment by benoit-pierre** [comment] 2024-12-08 16:24
Which version of OpenSSL is InkView using?

**Comment by NiLuJe** [comment] 2024-12-08 16:55
IIRC, unfortunately: "it depends" (on the exact FW version).

You'd have to collect a bunch of various inkview libs and check their deps to grasp the extent of the damage.

**Comment by benoit-pierre** [comment] 2024-12-09 17:56
I'm wondering if building a monolibtic version might help?

**Comment by benoit-pierre** [comment] 2024-12-09 17:58
For reference, the inkview library is pulling a lot of things:
```
SDK_6.3.0-6.5/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/local/lib/libinkview.so:
  SONAME    : libinkview.so
  NEEDED    : libpthread.so.0
  NEEDED    : libssl.so.1.0.0
  NEEDED    : libcrypto.so.1.0.0
  NEEDED    : libfreetype.so.6
  NEEDED    : libjpeg.so.8
  NEEDED    : libtiff.so.5
  NEEDED    : libpng12.so.0
  NEEDED    : libz.so.1
  NEEDED    : libcurl.so.4
  NEEDED    : libicuuc.so.58
  NEEDED    : libicui18n.so.58
  NEEDED    : libicuio.so.58
  NEEDED    : libdl.so.2
  NEEDED    : librt.so.1
  NEEDED    : libm.so.6
  NEEDED    : libhwconfig.so
  NEEDED    : libstdc++.so.6
  NEEDED    : libgcc_s.so.1
  NEEDED    : libc.so.6
  NEEDED    : ld-linux.so.3
```

**Comment by NiLuJe** [comment] 2024-12-09 19:59
> I'm wondering if building a monolibtic version might help?

There's still going to be two different OpenSSL `_init` fighting each other, but it can't really hurt to try, I guess ;).

**Comment by benoit-pierre** [comment] 2024-12-09 20:20
Well, then, if you're feeling adventurous @TheBolshe, [here is a version](https://send.vis.ee/download/7161aa1bf57a8d30/#oF8nynY7Uau79G8fBhRDag) to test.

**Comment by TheBolshe** [comment] 2024-12-10 16:24
> Well, then, if you're feeling adventurous @TheBolshe, [here is a version](https://send.vis.ee/download/7161aa1bf57a8d30/#oF8nynY7Uau79G8fBhRDag) to test.

It seems to happen only for some of them, i was able to dl a GNU dict just fine, but that was already the case with the previous version.

[crash.log](https://github.com/user-attachments/files/18082716/crash.log)

**Comment by benoit-pierre** [comment] 2024-12-10 16:35
Only [some dictionaries](https://github.com/koreader/koreader/blob/master/frontend/ui/data/dictionaries.lua) use a HTTPS url.

**Comment by TheBolshe** [comment] 2024-12-10 17:47
It crashed (i didn't get the crash log), then i tried to delete everything before copying your files instead of merging.
But the app was hanging on start. So i merged the latest release and it now crashes on launch

[crash.log](https://github.com/user-attachments/files/18083690/crash.log)

And whenever i overwrite with your version again, it hangs forever

**Comment by benoit-pierre** [comment] 2024-12-10 18:10
Ugh, forgot some calls in frontend, try [this version](https://send.vis.ee/download/e40c71e1051193bc/#Fn46Cpsgy2ITuNBO1mXaQw).

Please try from a clean slate (to avoid left-over shared objects in `koreader/common` & `koreader/libs`).

**Comment by benoit-pierre** [comment] 2024-12-10 22:23
Add
```lua
 ["debug"] = true,
```
to `koreader/settings.reader.lua`, or create it with this contents:
```lua
return {
 ["debug"] = true,
}

**Comment by TheBolshe** [comment] 2024-12-10 22:31
[crash.log](https://github.com/user-attachments/files/18086710/crash.log)

**Comment by TheBolshe** [comment] 2024-12-10 22:57
[crash.log](https://github.com/user-attachments/files/18087093/crash.log)

I redownloaded the latest release in case it can help to see why it's freezing

**Comment by lKENTl** [comment] 2024-12-10 23:20
> Ugh, forgot some calls in frontend, try [this version](https://send.vis.ee/download/e40c71e1051193bc/#Fn46Cpsgy2ITuNBO1mXaQw).
> 
> Please try from a clean slate (to avoid left-over shared objects in `koreader/common` & `koreader/libs`).

in my case this version crashes whole pocket book without start

**Comment by benoit-pierre** [comment] 2024-12-10 23:23
Is the stdbuf program available on pocketbook?

**Comment by lKENTl** [comment] 2024-12-10 23:50
I think no, I did not find it via terminal

**Comment by benoit-pierre** [comment] 2024-12-11 00:16
And logrotate?

**Comment by lKENTl** [comment] 2024-12-11 00:35
Did not find logrotate either

**Comment by benoit-pierre** [comment] 2024-12-11 00:43
OK, let's try [this version](https://send.vis.ee/download/6c2109694edeb2c3/#2iBDVoIQGI--rU82ojZZMA):
- from a clean slate, start it: behavior should be similar to v2024.11, try a problematic download, upload `crash.log` here
- add `["isolate_inkview"] = true,` to `koreader/settings.reader.lua`, try and upload `crash.log` again

**Comment by benoit-pierre** [comment] 2024-12-11 00:43
Make sure to update `koreader.app` too.

**Comment by lKENTl** [comment] 2024-12-11 08:18
[crash.log](https://github.com/user-attachments/files/18091754/crash.log)

**Comment by benoit-pierre** [comment] 2024-12-11 16:34
There's some leftover (unused) input code that pull in inkview as a dependency for the monolibtic library, let's get rid of it: try [this version](https://send.vis.ee/download/314fdc967ff00b67/#lXRqMW1t83SamshaopxLQA).

**Comment by lKENTl** [comment] 2024-12-12 15:55
Still crashes, but it seems to show a different message now.
[crash.log](https://github.com/user-attachments/files/18114157/crash.log)
Thank you very much for your help. For each version, I reset the device to its factory settings. Should I continue doing this?

**Comment by benoit-pierre** [comment] 2024-12-12 16:02
No need to reset to factory. Removing the koreader directory to avoid left-overs should be enough.

It looks like the log is truncated. Was that with or without `["isolate_inkview"] = true,` in `settings.reader.lua`?

**Comment by lKENTl** [comment] 2024-12-12 16:21
Yeap: 
[crash.log](https://github.com/user-attachments/files/18114499/crash.log)

**Comment by benoit-pierre** [comment] 2024-12-12 19:27
I'm not seeing inkview being loaded with `dlmopen` in your log.

Anyway try [this version](https://github.com/user-attachments/files/18116474/koreader-pocketbook-v2024.11-66-ge137c4ded_2024-12-12.zip) (trimmed so the Github attachment is allowed: no translations, Hungarian hyphenate pattern, and `NotoSansCJKsc` font). I've changed the approach and tweaked the startup script to reduce the number of `LD_DEBUG` related traces, enable debug logging automatically, and disable restarting on error.

Try it and report if it works at all. Upload `crash.log`.

Then for comparison, replace `koreader/libs/libwrap-inkview.so` with [this version](https://github.com/user-attachments/files/18116530/alt-wrap-inkview.zip) and test again. Upload `crash.log`.

**Comment by lKENTl** [comment] 2024-12-14 03:15
This time, KOReader crashed immediately (before I needed to perform any action with sync or downloading).
First log: [crash.log](https://github.com/user-attachments/files/18134028/crash.log)
Second log (with replaced `libwrap-inkview.so`: [crash.log](https://github.com/user-attachments/files/18134029/crash.log)

**Comment by benoit-pierre** [comment] 2024-12-14 12:41
Replace `ffi/inkview.lua` with [that version](https://github.com/user-attachments/files/18135820/inkview.lua.zip) and try again both variants of `libwrap-inkview.so`.

**Comment by lKENTl** [comment] 2024-12-14 18:24
Basic version, the app did not start: 
[crash.log](https://github.com/user-attachments/files/18137162/crash.log)
With replaced `libwrap-inkview.so` and verbose logging enabled. Crash after the same actions:
[crash.log](https://github.com/user-attachments/files/18137182/crash.log)

**Comment by benoit-pierre** [comment] 2024-12-14 19:33
OK, still no idea why the isolated version crash… From the last traces, it looks like inkview is calling some sort of telemetry library function `P7_Exceptional_Flush` (Cf. https://baical.net/p7.html). Do you have a `/mnt/ext1/pbcloud_tests_logs/` or `/P7.Dir=/mnt/ext1/tts_tests_logs/` directory with some logs?

For the second case, let's try without ASM/SIMD optimizations: replace `koreader/libs/libkoreader-monolibtic.so` with [this version](https://github.com/user-attachments/files/18137416/libkoreader-monolibtic.zip).

**Comment by lKENTl** [comment] 2024-12-14 20:46
The only log file I found is the following: `d:\system\usage_stat\journal.log`, do you need it?

Crashed on the start: 
[crash.log](https://github.com/user-attachments/files/18137653/crash.log)

**Comment by benoit-pierre** [comment] 2024-12-14 20:56
> The only log file I found is the following: `d:\system\usage_stat\journal.log`, do you need it?

No, never mind.

> Crashed on the start: [crash.log](https://github.com/user-attachments/files/18137653/crash.log)

That log shows you're back to the wrong `ffi/inkview.lua`.

Here's a [full release](https://github.com/user-attachments/files/18137681/koreader-pocketbook-v2024.11-66-ge137c4ded_2024-12-12.zip) with the right wrap-inkview / koreader-monolibtic libraries.

**Comment by lKENTl** [comment] 2024-12-14 21:17
It works! Thank you very much! Do you need anything else from me for testing or any similar tasks?

**Comment by benoit-pierre** [comment] 2024-12-14 22:02
Good question! :P

To recap:

- the inkview library pulls a boatload of shared libraries
- the DT_NEEDED entries of the SDK6 inkview library are correctly versioned
- we also make sure to use versioned library
- so we should not mix incompatible ABIs when loading libraries, except our libraries may be compiled with different features than inkview expects (like cURL, which we compile with OpenSSL support)
- if we compile a monolibitic koreader library, we can be sure that inkview will pull system libraries
- `ffi.load` uses `dlopen(…, RTLD_LOCAL)`, so there should be no issue with inkview loading for example version 1.0.0 of OpenSSL, while we use 1.1.1, unless someone promote one of those libraries by calling `dlopen(… RTLD_GLOBAL)` later
- the version above that works includes a number of changes, ultimately, I think disabling ASM/SIMD optimizations fix the build because we're hitting this [SSL bug](https://github.com/openssl/openssl/issues/14838) (I've confirmed building OpenSSL with `no-asm` remove the offending `_armv7_tick` ASM code)

So there's at least another version we should try: a pocketbook build with only ASM/SIMD optimizations disabled (without the monolibtic / wrap-inkview changes).

And it might be time to update OpenSSL too.

**Comment by benoit-pierre** [comment] 2024-12-14 22:20
Here's a [version](https://github.com/user-attachments/files/18137936/koreader-pocketbook-v2024.11-69-g8a0168685_2024-12-14.zip) for testing: master + base master with https://github.com/koreader/koreader-base/pull/2004 & https://github.com/koreader/koreader-base/pull/2005 + OpenSSL compiled with `no-asm`.

**Comment by lKENTl** [comment] 2024-12-14 23:55
Works perfectly!

**Comment by benoit-pierre** [comment] 2024-12-15 00:21
Great, thanks for testing! If you don't mind one last test: [this version](https://github.com/user-attachments/files/18138275/koreader-pocketbook-v2024.11-69-g8a0168685_2024-12-14.zip) uses OpenSSL 3.4.0.

**Comment by lKENTl** [comment] 2024-12-15 00:46
Still works perfectly, thank you:)

**Comment by benoit-pierre** [comment] 2024-12-15 00:50
Great! We'll go with that option then.

**Comment by NiLuJe** [comment] 2024-12-15 11:43
> * the version above that works includes a number of changes, ultimately, I think disabling ASM/SIMD optimizations fix the build because we're hitting this [SSL bug](https://github.com/openssl/openssl/issues/14838) (I've confirmed building OpenSSL with `no-asm` remove the offending `_armv7_tick` ASM code)

Did I forget to put in this patch in KOReader?

```diff
diff --git a/crypto/armcap.c b/crypto/armcap.c
index 58e54f0da2..9ba33b716e 100644
--- a/crypto/armcap.c
+++ b/crypto/armcap.c
@@ -178,6 +178,8 @@ void OPENSSL_cpuid_setup(void)
     if (sigsetjmp(ill_jmp, 1) == 0) {
         _armv7_neon_probe();
         OPENSSL_armcap_P |= ARMV7_NEON;
+        // Kindle Hack: We're on ARMv7, so nerf this to avoid spamming dmesg w/ undefined instructions...
+        /*
         if (sigsetjmp(ill_jmp, 1) == 0) {
             _armv8_pmull_probe();
             OPENSSL_armcap_P |= ARMV8_PMULL | ARMV8_AES;
@@ -199,14 +201,19 @@ void OPENSSL_cpuid_setup(void)
             OPENSSL_armcap_P |= ARMV8_SHA512;
         }
 #  endif
+        */
     }
 # endif
 
     /* Things that getauxval didn't tell us */
+    // Kindle Hack: Apparently, the kernel doesn't enable this part of the PMU for userland on the PW2's A9 (at least on FW 5.4.2).
+    // Thus this throws an (handled) SIGILL. Nerf for now, to avoid spamming dmesg with 'undefined instruction' logs.
+    /*
     if (sigsetjmp(ill_jmp, 1) == 0) {
         _armv7_tick();
         OPENSSL_armcap_P |= ARMV7_TICK;
     }
+    */
 
     sigaction(SIGILL, &ill_oact, NULL);
     sigprocmask(SIG_SETMASK, &oset, NULL);
```

**Comment by NiLuJe** [comment] 2024-12-15 11:44
Although, granted, moving to a modern OpenSSL *is* a much better solution ;o).
