### ISSUE TITLE
Freezing after update

### ISSUE THREAD

**Issue by BattlePants1** [koreader/koreader#4811] opened 2019-03-16 22:37 UTC
* KOReader version: Latest
* Device: Kobo Aura 2nd Edition (2017)

#### Issue
After doing an update koreader freezes after a few minutes, unusable

I went back the previous version and have no more issues, please fix this in the next update
#### Steps to reproduce
Update to latest version

**Comment by Frenzie** [comment] 2019-03-16 22:44
Duplicate of #4796. Could you please take a look at https://github.com/koreader/koreader/issues/4796#issuecomment-473449521 and further to see if toggling 8-bit on and off makes a difference for you. Note that it only takes effect after a restart.

**Closed by Frenzie** 2019-03-16 22:44 UTC
Labels: Kobo, bug, duplicate
