### ISSUE TITLE
FR: Add Bionic reading feature

### ISSUE THREAD

**Issue by fbkkr** [koreader/koreader#9117] opened 2022-05-20 17:16 UTC
**Ad**d **Bio**nic **read**ing **feat**ure

The below pictures explain themselves. Not sure if useful, but there is an API. [Documentation here](https://rapidapi.com/bionic-reading-bionic-reading-default/api/bionic-reading1/) 

**Additional context**
More at [https://bionic-reading.com/](https://bionic-reading.com/)
![FTDUN6aWQAA1kXr](https://user-images.githubusercontent.com/89525416/169579189-f21481e1-be95-48f8-9271-2982504dc76c.jpg)
![FTCjja2WAAATNS4](https://user-images.githubusercontent.com/89525416/169579194-fa06f808-ebfb-41b8-a5e3-1ee892156342.jpg)
[API](https://rapidapi.com/bionic-reading-bionic-reading-default/api/bionic-reading1/)

**Comment by Frenzie** [comment] 2022-05-20 17:23
Duplicate of #9109.

**Closed by Frenzie** 2022-05-20 17:23 UTC
Labels: enhancement
