### ISSUE TITLE
Touchscreen can't work

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#2314] opened 2016-11-03 12:03 UTC
* KOReader version: 666
* Device: kobo aura h2o

no touch.....only can swipe

 [*] Current time: 11/03/16-19:02:11
luajit: exec("lipc-wait-event") inside the child: No such file or directory
[11/03/16 @ 19:02:48] Kobo Suspend: Going to sleep . . .
[11/03/16 @ 19:02:48] Kobo Suspend: Asked the kernel to put subsystems to

**Comment by retrue** [comment] 2016-11-03 12:40
Same here
. KOReader version: 666
. Device: Kobo Mini
It worked well on the previous version available through OTA (2015.11-654).

**Comment by KenMaltby** [comment] 2016-11-03 13:14
Skipping any version numbered 666, just to be on the safe side.

**Comment by Brnoch** [comment] 2016-11-03 15:29
Same for me on my Kobo Glo HD.
Shall I reinstall koreader, or can we fix the problem (as the main menu doesn't appear, no way to make an OTA update)?

**Comment by houqp** [comment] 2016-11-03 21:37
This looks like a serious regression. I will try reproduce on my side after work. Can someone help confirm what's the last working version that does not have this issue? There are newer builds in http://build.koreader.rocks/download/nightly/.

@Brnoch You can just copy an old version of koreader to override the new one. If the touch is broken, you won't be able to do OTA anymore :( That's something we should come up with a solution too.

**Comment by retrue** [comment] 2016-11-03 22:15
Version 654 worked. I haven't tried the new ones yet and it is late. Tomorrow.
I reported this same issue weeks ago and it was solved [https://github.com/koreader/koreader/issues/2219](url) with commit #2220. Dunno if it is the same problem or a different one.

**Comment by hombretranquilo** [comment] 2016-11-03 23:59
Version 2015.11-663-g816d0a5 woks well. At least on Aura HD.

**Comment by houqp** [comment] 2016-11-04 03:57
I tried 666-g529d505 on my Aura HD, the touch screen is working as expected. But `luajit: exec("lipc-wait-event") inside the child: No such file or directory` should not show up in the log. I am taking a look.

**Comment by houqp** [comment] 2016-11-04 04:19
I introduced some refactoring in the core input module in 663, @retrue and @seacatwu , could you help identify if 663 and 658 are also affected?

**Comment by houqp** [comment] 2016-11-04 05:28
hm... this is very weird, I don't understand why it prints out `luajit: exec("lipc-wait-event")` for you. This string is not even in the 666 nightly build and it should only be included for kindle builds.

**Comment by houqp** [comment] 2016-11-04 07:04
if you can run the reader in debug mode, that would help with the debugging too. You can enable it by setting `debug = true` in `settings.reader.lua`

**Comment by retrue** [comment] 2016-11-04 07:48
I enabled debug and I include here the crash.log file. My device is a Kobo Mini.
[crash.log.txt](https://github.com/koreader/koreader/files/570852/crash.log.txt)

Up to November 1, the firmware used was 654. From November 3, the firmware used is 666.

**Comment by hombretranquilo** [comment] 2016-11-04 10:23
Maybe this helps. Version 666-g529d505.targz downloaded yesterday from http://vislab.bjmu.edu.cn/apps/koreader/ota/ has the touchscreen issue, but v2015.11-666-g529d505.zip downloaded today from http://build.koreader.rocks/download/nightly/ works well.

**Comment by seacatwu** [comment] 2016-11-04 10:57
@hombretranquilo  that's right.

**Comment by houqp** [comment] 2016-11-04 16:39
It's likely due to my input refactor introduced in 663 then. OTA is currently built differently compared to build.koreader.rocks. I don't have access to the OTA server, I will contact @chrox to figure out what's causing it.

**Comment by Brnoch** [comment] 2016-11-05 18:08
I just updated my kobo glo hd to the version 670. The problem is still the same on this version.

**Comment by Yaretzki** [comment] 2016-11-05 18:50
Same here
. KOReader version: 666 and 670
. Device: Kobo Glo HD
It worked well on the previous version 663

**Comment by houqp** [comment] 2016-11-05 20:13
There is no 670 in the new nightly build yet: http://build.koreader.rocks/download/nightly/

Are you guys using the OTA server? If so, please stop doing OTA update until we fix the OTA server.

**Comment by retrue** [comment] 2016-11-07 17:28
When will be the OTA server fixed?
build.koreader.rocks has not been updated either.

**Comment by houqp** [comment] 2016-11-07 18:18
build has been broken in the last 3 commits. I have fixed it with the latest commit and retriggered the build: https://gitlab.com/koreader/nightly-builds/pipelines/4894762

new builds should show up when this gitlab pipeline build is done.

new OTA server should be ready soon. it's functioning, but i need to test it myself tonight after work to make sure it's working as expected.

**Comment by houqp** [comment] 2016-11-08 05:27
Hi all, new OTA server is ready to serve at: http://ota.koreader.rocks:80/. It will become the default server once https://github.com/koreader/koreader/pull/2324 is merged. For now, you can manually change the ota_server setting to `http://ota.koreader.rocks:80/` in your reader.settings.lua.

**Comment by houqp** [comment] 2016-11-08 08:18
quick update: @chrox help setup a redirect from `http://vislab.bjmu.edu.cn:80/apps/koreader/ota/` to `http://ota.koreader.rocks:80/`. So using the default server should work now.

**Closed** 2016-11-08 08:18 UTC
