### ISSUE TITLE
Full Screen JPG files

### ISSUE THREAD

**Issue by DynamoRocket** [koreader/koreader#12440] opened 2024-08-31 16:26 UTC
* KOReader version: 2024.07
* Device: Android 10 Tablet

#### Issue
Certain JPG files are stretched to take up the full screen of the device. It doesn't matter what zoom settings are selected. I remember that a small handful of CBZs had this problem after reporting my last. The link I was given for the dev version didn't clear this issue up. I run into this a lot less than the cant open it bug I reported. Attached is a zip with 3 images that reproduce the issue.
[spicy.zip](https://github.com/user-attachments/files/16825385/spicy.zip)

#### Steps to reproduce
Open jpg file to check

**Comment by hugleo** [comment] 2024-08-31 17:38
I didn't look at that sample, but based on the description should it be a duplicate of https://github.com/koreader/koreader/issues/11304 ?

**Comment by Frenzie** [comment] 2024-08-31 18:18
Correct, it looks the same.
```
$ exiftool -XResolution -YResolution -ResolutionUnit 1.jpg
X Resolution                    : 1100
Y Resolution                    : 1650
Resolution Unit                 : inches
```

**Closed** 2024-08-31 19:25 UTC
Labels: duplicate
