### ISSUE TITLE
[Pocketbook] Display weirdness - white bars

### ISSUE THREAD

**Issue by marmistrz** [koreader/koreader#1562] opened 2015-06-17 09:59 UTC
I'm running version 2014.11-257-g63fb8af on PB622

When selecting a menu entry, the black color isn't solid - it has white horizontal stripes.

**Comment by Frenzie** [comment] 2020-08-21 06:07
Duplicate of https://github.com/koreader/koreader/issues/5114 which has more info.

**Closed by Frenzie** 2020-08-21 06:07 UTC
Labels: PocketBook, bug, firmware, help-wanted
