### ISSUE TITLE
Crash on long-press of Fulltext search results

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#12435] opened 2024-08-30 18:05 UTC
* KOReader version: 2024.07-135 
* Device: Kobo Aura H2O

#### Issue

Crash on long-press of any Fulltext search result.

#### Steps to reproduce

Perform a Fulltext search within a book and long-press on any of the listed results.

##### `crash.log` (if applicable)

<details>
  <summary>Crash 1</summary>

```
08/30/24-17:43:39 WARN  error in wrapped function: frontend/apps/reader/modules/readersearch.lua:642: attempt to index field 'next_text' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readersearch.lua:642: in function 'onShowFindAllResults'
	frontend/apps/reader/modules/readersearch.lua:616: in function 'findAllText'
	frontend/apps/reader/modules/readersearch.lua:250: in function <frontend/apps/reader/modules/readersearch.lua:249>
	[C]: in function 'xpcall'
	frontend/ui/trapper.lua:48: in function <frontend/ui/trapper.lua:45> 
./luajit: frontend/apps/reader/modules/readersearch.lua:684: attempt to call method 'getFullTocTitleByPage' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readersearch.lua:684: in function 'onMenuHold'
	frontend/ui/widget/menu.lua:541: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:911: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1438: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1538: in function 'handleInput'
	frontend/ui/uimanager.lua:1582: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00013e9d
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 08/30/24 @ 17:44:01)
Running FW 4.35.20400 on Linux 2.6.35.3-850-gbc67621+ (#3032 PREEMPT Mon Jan 9 13:37:40 CST 2017)
Attempting to restart KOReader . . .
!!!!

```
</details>

<details>
  <summary>Crash 2</summary>

```

./luajit: frontend/apps/reader/modules/readersearch.lua:684: attempt to call method 'getFullTocTitleByPage' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readersearch.lua:684: in function 'onMenuHold'
	frontend/ui/widget/menu.lua:541: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:911: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1438: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1538: in function 'handleInput'
	frontend/ui/uimanager.lua:1582: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00013e9d
!!!!
Uh oh, something went awry... (Crash n°1: 08/30/24 @ 17:39:19)
Running FW 4.35.20400 on Linux 2.6.35.3-850-gbc67621+ (#3032 PREEMPT Mon Jan 9 13:37:40 CST 2017)
Attempting to restart KOReader . . .
!!!!

```
</details>

**Comment by NiLuJe** [comment] 2024-08-30 21:30
Are you sure your install isn't mangled somehow?

The trace made so little sense that i tried to repro, and, err, I can't ;o).

**Comment by jonnyl2** [comment] 2024-08-30 22:02
Apparently it was! I did an update to nightly 138 the traditional way (copying the dir) and it is working now! I had been updating like that for several months, except for the last version (135) I used OTA. Could this have caused any issues?

**Comment by NiLuJe** [comment] 2024-08-31 00:15
It shouldn't, but it's an old device, so storage shenanigans could be a factor ;).

In any case, closing this one ;).

**Closed by NiLuJe** 2024-08-31 00:15 UTC
Labels: bug, invalid

**Comment by hius07** [comment] 2024-08-31 03:43
@poire-z can you give a look what does your cpp `findAllText` return when searching for the **last word of a book**? Looks like it takes `next_text` from other parts of the book (description or smth).

In any case I'll add a check for `nil` in prev and next text.

**Comment by poire-z** [comment] 2024-08-31 08:13
> can you give a look what does your cpp `findAllText` return when searching for the **last word of a book**? Looks like it takes `next_text` from other parts of the book (description or smth).

How can I reproduce and see it? Does that last word has to be followed by some punctuation or not ?
Looks like I can't reproduce, even with FB2 (where "description" is something, at the start of the book).
![image](https://github.com/user-attachments/assets/d1a33019-d067-4ae9-a2b2-2b737ea3dc1f)

**Comment by hius07** [comment] 2024-08-31 10:13
EPUB: it cycles to the beginning of the book.

![1](https://github.com/user-attachments/assets/ed7a9b9e-cba4-4859-95e0-ecc6115a8aac)
![2](https://github.com/user-attachments/assets/c94b8fb5-14f7-44bd-8a58-bf6ea68a0ac0)
![3](https://github.com/user-attachments/assets/5b124cf3-e8ce-4901-ac23-f67e275ff31a)
----------------
![4](https://github.com/user-attachments/assets/0a2f9870-3c11-41b2-a9bb-6ad1b4b7ebc7)
![5](https://github.com/user-attachments/assets/b917c941-0518-4113-8ce9-d707634e1faf)
![6](https://github.com/user-attachments/assets/fd6716a3-19b8-4039-a763-f6dadf7adfc5)

**Comment by poire-z** [comment] 2024-08-31 10:21
Ok, I need to input `Indiana.` (with the trailing period) to get the issue. `Indiana` without the period is fine.

**Comment by poire-z** [comment] 2024-08-31 13:02
A bit tedious as always with crengine xpointers and the prev/nextVisibleStuff...
I think this may solve the issue:
```diff
@@ -3924,7 +4190,8 @@ static int findAllText(lua_State *L) {
                     if ( nbWordsContext > 0 ) {
                         ldomXPointerEx prev = start;
                         for (int i=0; i<nbWordsContext; i++) {
-                            prev.prevVisibleWordStart();
+                            if ( !prev.prevVisibleWordStart() )
+                                break;
                         }
                         ldomXRange rp(prev, start);
                         lString32 prevText = rp.getRangeText('\n');
@@ -3932,9 +4199,18 @@ static int findAllText(lua_State *L) {
                         lua_pushstring(L, UnicodeToLocal(prevText).c_str());
                         lua_rawset(L, -3);

+                        // nextVisibleWordEnd() (used here and above) may end up on the root node
+                        // when at end of document, and we may wrap around to the start of the
+                        // document: we must stop and not consider it.
+                        // (No such issue with prev context, as it won't wrap around to end of document.)
                         ldomXPointerEx next = end;
+                        ldomXPointerEx tmp = end;
                         for (int i=0; i<nbWordsContext; i++) {
-                            next.nextVisibleWordEnd();
+                            if ( i == 0 && end.getNode()->isRoot() ) // reached when dealing with suffix
+                                break;
+                            if ( !tmp.nextVisibleWordEnd() ) // probably reached the root node
+                                break;
+                            next = tmp;
                         }
                         ldomXRange rn(end, next);
                         lString32 nextText = rn.getRangeText('\n');
```

**Comment by hius07** [comment] 2024-08-31 13:43
How do you think, shouldn't it stop on a chapter boundary and do not show the context from the next chapter?
On fb2 it even crosses the body's end and shows next_text from the Notes part.
Not a big issue though.

**Comment by poire-z** [comment] 2024-08-31 16:00
There's no real notion of chapter for crengine (there are DocFragments and FB2 body, but it's not really something we can detect/use easily, and on EPUB, publishers can create new DocFragments anywhere - and put multiple chapters in a same DocFragment).

The only easy thing we can do (because prevVisibleWordStart/nextVisibleWordEnd accept a `thisBlockOnly=true` parameter) is to limit this to a paragraph.
So we could get with using that:
![image](https://github.com/user-attachments/assets/382d916a-0e0e-4d36-b2e2-7b69dda43e1f)
(second one is near the end, 4th is at start of paragraph.)

But you would then get single words or small context for stuff in table cells:
![image](https://github.com/user-attachments/assets/af1de4e4-0477-4f00-921e-3ae21fc36d48)
![image](https://github.com/user-attachments/assets/ddf92dd2-8b23-4ab5-a1e6-2da769556363)
vs. curent (which is not really more readable):
![image](https://github.com/user-attachments/assets/37bab3a3-6fac-41a4-adbf-91410feca196)
