### ISSUE TITLE
Bookmarks, "cache" and PDF crash - segmentation fault

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#2216] opened 2016-08-11 05:39 UTC
I copied my old cache directory, because I thought the bookmarks might be there. 
Now the pdfs in history crash (related?)
The bookmarks are not there either, btw. Where are the epub bookmarks saved?

**Comment by houqp** [comment] 2016-08-11 05:54
All book settings are stored in the `.sdr` directory. So you can just copy that one. Cache are not supposed to be copied between devices. But it also should not cause a crash. Could you upload the cache and pdf file for us to reproduce the issue? Also were you able to see the crash log for the crash?

**Comment by hurzl** [comment] 2016-08-11 07:37
There is no such directory (again)

**Comment by hurzl** [comment] 2016-08-11 07:49
the crash log is "segmentation fault".

**Comment by chrox** [comment] 2016-08-11 07:55
Please complete your issue description first really. 
```
* KOReader version:
* Device:

#### Issue

#### Steps to reproduce
```

Even you described it in another issue, it's a requirement for others to investigate into your problem.

**Comment by chrox** [comment] 2016-08-11 08:04
Since I don't know on which device you got this problem, I can only guess that if you were in Kobo platform with KSM launcher did you happen to be using two or more koreader instances (each `koreader` folder might be one instance, and there is no data interchange including reader settings and bookmarks between koreader instances).

**Comment by Frenzie** [comment] 2017-04-01 13:20
I'm closing this now because there's insufficient information to do much of anything. Feel free to open a new issue (with a little more info if at all possible!) if the issue reoccurs.

**Closed by Frenzie** 2017-04-01 13:20 UTC
