### ISSUE TITLE
Android menu/pan/scroll performance

### ISSUE THREAD

**Issue by didierm** [koreader/koreader#4470] opened 2019-01-11 09:52 UTC
* KOReader version: v2019.01-2-gd02c340_2019-01-09
* Device: Samsung TM-813 (Android 7.1.2)

This is a continuation of the discussion in https://github.com/koreader/koreader/issues/4467#issuecomment-453000201.

#### Issue
Low pan/scroll performance when handling CBZ or PDF documents is detrimental to the user experience.

#### Steps to reproduce

* open CBZ

Settings : 
* Orientation : landscape
* Scroll Mode : on
* Switch zoom mode : Zoom to fit page width

1.  Due to the variable nature of comics pages layout, tapping to view the next part of the page often results in text bubbles and/or images being only partly visible, hence fluent scrolling up/down is a requirement to be able to follow the flow of the story.
The scrolling in KOReader is lacking, due to : 
- the actual scrolling lagging behind the tapping ;
- slow and jerky performance, both up and down.

2. Contrary to other apps (MuPDF Viewer, FBReader), tapping the screen to view the next part of the page (scroll mode) never aligns to the bottom of the page, but shows the upper part of the next page (stressing the importance of [1.]).

Attached a comparison of MuPDF, FBReader and KOReader, sampled from https://archive.org/details/avengers-004 (the videos have been reduced 50% in size to lower file sizes, resulting in slight resolution artefacts).

[CBZ_mupdf.mkv.gz](https://github.com/koreader/koreader/files/2749156/CBZ_mupdf.mkv.gz)
[CBZ_fbreader.mkv.gz](https://github.com/koreader/koreader/files/2749162/CBZ_fbreader.mkv.gz)
[CBZ_koreader.mkv.gz](https://github.com/koreader/koreader/files/2749168/CBZ_koreader.mkv.gz)

**Comment by poire-z** [comment] 2019-01-12 06:15
OK, that does not look that much worse that what I can witness on my phone :) So I guess it's not a regression and you see what everybody has been seeing.

Indeed, koreader is not as smooth as the others. I guess that could be explained by:
- koreader is not a native app, we run the common code thru luaJit, and the android simple port was made targetting the eInk android devices - might not be enough for the non-eInk fast android devices.
- we have our generic blitbuffer code that deals with various bitmaps depths (8, 16, 24, 32bits), rotation, viewports, croping - while the other apps may use native android stuff for that, and can do their thing the most direct way (app image buffer > android screen buffer) (might be just [that](https://github.com/ArtifexSoftware/mupdf/blob/master/platform/java/src/com/artifex/mupdf/fitz/android/AndroidDrawDevice.java) for mupdf viewer)
- that blitbuffer code is not optimized (https://github.com/koreader/koreader-base/pull/746#issuecomment-431884723 _a single memory segment copy could be done instead of millions of pixel copies_)
- this is even more noticable in scroll mode, where each pan provokes a full redraw - we didn't need much on eInk devices where the eink drawing is itself taking a few 100ms

Just some thoughts, no easy solution in sight :|

About your 2), I see that in page mode (scroll mode off), a tap aligns to page boundaries, before going to the next page - and scrolling with swipe/pan is disabled. I guess it scrolling could be enabled, and it would be limited to page boundaries - a tap would be needed to go to the next page.

Can you just confirm you get the same thing with a pure PDF file, and that it's not CBZ specific (I have no CBZ, but I notice that on PDF).

**Comment by didierm** [comment] 2019-01-12 13:42
> Can you just confirm you get the same thing with a pure PDF file, and that it's not CBZ specific (I have no CBZ, but I notice that on PDF).

The described laggy behaviour is manifest with both CBZ (see my link https://archive.org/details/avengers-004 for an example of a freely available comic) and PDF.

I am happy to use MuPDF, FBeader, Bubble, ... for CBZ/PDF, but ... KOReader is such a nice app. :)

**Comment by Frenzie** [comment] 2019-01-12 15:30
That video does look slightly worse than I'd expect. I suppose that at 2048 x 1536 ([source](https://www.samsung.com/us/mobile/tablets/all-other-tablets/sm-t813nzwexar-sm-t813nzwexar/)) that device has more pixels to push than a regular FullHD phone without sufficiently significant extra CPU power to make up for the difference.

Imo just tapping or swiping once instead of constant annoying panning is normally a nicer experience, but of course it'd be good to have the other panning-centric mode of operation more fluent as well. For me Bubble as "smooth" and KOReader for "calm" works out nicely, but there might be some comparatively "easy" optimizations to be made in dealing with memory segments as @poire-z said. That being said, I wonder if you can get into truly properly smooth territory without loading pages as textures on the GPU. The thing is, of course, that the program is based around a framebuffer implementation for E Ink devices.

**Comment by didierm** [comment] 2019-01-12 16:19
Well, as I already mentioned : panning is imo a requirement for comics, as more often than not, pictures and text are cut in the middle of the page (or whatever the height of the screen relative to the page size is). Both MuPDF Viewer and FBReader deal really well with this (i.e. very good tactile feedback ; and in scroll mode : halting at the end of the page after arbitrary panning, so after a tap, the next page is correctly aligned to the top of the screen again).

By no means should this be considered criticism at the address of KOReader ; merely a point of consideration, should you aspire absolute hegemony in the world of document readers.  :)

I am perfectly OK with using MuPDF, FBReader of Bubble for PDF/CBZ.

**Comment by Frenzie** [comment] 2019-01-25 19:41
@ZZZXXX0110 Could you please continue discussion here?

There are a few places where Android is slower on purpose because otherwise it becomes *extremely* slow while trying to allocate memory.

Example:
https://github.com/koreader/koreader/blob/620542b0556eade82b039a6b24a628e85a9acbd5/frontend/ui/rendertext.lua#L11-L13

So it's possible that you're either seeing that or suffering from a place where JIT isn't turned off.

**Comment by ZZZXXX0110** [comment] 2019-01-25 20:00
Sure! 
I see the same code in my rendertext.lua
Are you suggesting that there could be places where JIT somehow didn't get turned off despite being instructed so by the code?

I think this issue is perhaps related to https://github.com/koreader/koreader/issues/1416

**Comment by Frenzie** [comment] 2019-01-25 23:00
If anything I'm suggesting to try enabling JIT and to use the JIT blitbuffer instead of the C one. ;-) Unless, of course, you're seeing memory allocation problems.

> Are you suggesting that there could be places where JIT somehow didn't get turned off despite being instructed so by the code?

No, just that there could be places where it's not turned off.

**Comment by ZZZXXX0110** [comment] 2019-01-26 15:56
Drawing performance does seem to improved a lot after commenting out that line. There is still some delay in turning pages and going into file manager, but the performance with menus pages are noticeably better!

**Comment by Frenzie** [comment] 2019-01-26 18:48
@ZZZXXX0110 That confirms my suspicions based on your description, but it doesn't make much sense. For me LuaJIT FFI and compiled C are roughly in the same ballpark (tested in Valgrind so that it takes about 3 seconds for the menus to open ;-) ).

@pazos Have you already investigated or thought about doing a build with clang?

**Comment by pazos** [comment] 2019-01-26 19:55
> Have you already investigated or thought about doing a build with clang?

No, I had no idea if that was possible :thinking:

Anyways, the pan/scroll problem is not only a matter of the blitbuffer implementation. Our input stuff will make the experience non native even if we were using a GLSurface. We don't react to input events directly, we read them, translate them into generic linux input events and then they go through the gesture manager.

In short, I think that some improvements would be nice but don't hold my breath for "native experience". And we will never be native enough to compete with FBReader/MuPdf viewer in terms of pan/scroll performance. General menu/action responsiveness seems to be a per device issue.

**Comment by Frenzie** [comment] 2019-01-26 20:49
It's not that I personally want clang (or gradle, etc.) but Google has stopped updating Android gcc at 4.9 years ago because they want you to move over to clang. Anyway, I was thinking it may not be completely implausible that the gcc 8 I was pitting against JIT on my desktop generates more efficient assembly code than 4.9. That being said, if it were truly bad you'd think I'd have noticed something on my own ARM Android devices, so I still find this result surprising.

https://android.googlesource.com/platform/ndk/+/master/docs/ClangMigration.md
> The Android OS switched to clang several years ago. Future versions of the NDK will remove GCC, so the sooner you start testing your project with clang the better!

Since the program builds fine in clang it would likely already work with one or two relevant environment variables; I've just never tried it.

**Comment by ZZZXXX0110** [comment] 2019-02-01 04:01
Ok just realized this seems to cause the Night Mode to no longer work on Android :/

**Comment by ZZZXXX0110** [comment] 2019-02-01 22:05
> Can you give a nightly >= v2019.01.1-37 a try, without commenting any line?
> It includes [koreader/koreader-base#799](https://github.com/koreader/koreader-base/pull/799) - and the only thing I noticed on my phone is that the top menu opens a bit quicker. Might be it can have different effect depending on device's CPU/cache architecture...

Wooow the performance on the new nightly (actually v2019.01.1-45) is vastly improved!!! It's now working in full speed! Menu navigation pretty much has no lag at all! And Night Mode works!

**Comment by pazos** [comment] 2019-02-01 23:46
V2019.01.1-43 (from nightlies) works at full speed here too. I'm not sure if is just related to @poire-z blitbuffer changes or has something to do with switching to release builds.

**Comment by Frenzie** [comment] 2019-02-02 08:16
I think that's unlikely to have an actually noticeable impact, or even to be measurable outside of the margin of error, because only the NativeActivity/Java veneer was a debug build. Meanwhile it's LuaJIT and all the other libraries doing the heavy lifting. On the flipside, I suppose it's possible that this somehow slowed down drawing performance in, say, ANativeWindow. I'm willing to test, but I don't really know how.

**Comment by Frenzie** [comment] 2019-02-21 17:36
Since this has been reported to have seen some improvement, I'll close this specific issue. With #4580 as good as done the road will soon be open for more drastic experiments.

**Closed by Frenzie** 2019-02-21 17:36 UTC
Labels: Android

**Comment by Frenzie** [comment] 2019-02-26 22:09
Btw @didierm @ZZZXXX0110 it only just occurred to me to ask: did you actually go to Screen → E-ink settings → Use smaller panning rate?

**Comment by ZZZXXX0110** [comment] 2019-02-27 18:20
Of course I did, of course I tried every possible options before submitted
a bug report. Thankfully, this is now fixed in newer versions.

**Comment by ildar** [comment] 2019-08-15 02:42
@Frenzie ,
> go to Screen → E-ink settings → Use smaller panning rate

This is crucial for the 1st time user experience. Please make it default for normal screen users. Ask user on 1st start if unable to detect

**Comment by Frenzie** [comment] 2019-08-15 06:19
@ildar It is. See #4721.

**Comment by ildar** [comment] 2019-08-15 15:00
Emm, ok.
Just tested a bit and didn't see a difference.
BTW this patch with JIT doesn't work anymore.

**Comment by Frenzie** [comment] 2019-08-15 16:19
Could you please open a new bug report with pertinent information? It scrolls very smoothly for me on my Xperia Ray, Zenfone 2 (x86), and XA2.

**Comment by ildar** [comment] 2019-08-16 06:34
No. It appeared my mistake. Sorry.
I'm sitting trying to understand
https://github.com/koreader/koreader/commit/f3e0d44cc4cd12aec3acf38369edf4bc3516b5fc
.

**Comment by NiLuJe** [comment] 2019-08-16 12:42
@ildar: The TL;DR; being that Android is terrible. (It makes it hard to allocate a large block of contiguous memory in a controlled fashion, which is essential for a JIT compiler).
