### ISSUE TITLE
Build release kobo error

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1832] opened 2016-02-18 14:04 UTC
After downgrading libsodium ([see here](https://github.com/koreader/koreader/issues/1788#issuecomment-185682911)), I am able to `./kodev build` and `./kodev run`. However `./kodev release kobo` still crashes. [Build log](https://gist.github.com/5c8615acd7c357927dcb
). Crash lines:
```
/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/x86_64/glib-prefix/src/glib/gio/gresource-tool.c:32:20: fatal error: libelf.h: No such file or directory
 #include <libelf.h>
                    ^
compilation terminated.
make[9]: *** [gresource-gresource-tool.o] Error 1
make[8]: *** [all-recursive] Error 1
make[7]: *** [all] Error 2
make[6]: *** [all-recursive] Error 1
make[5]: *** [all] Error 2
make[4]: *** [glib-prefix/src/glib-stamp/glib-build] Error 2
make[3]: *** [CMakeFiles/glib.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/x86_64/glib-prefix/src/glib-build/lib/libglib-2.0.so.0] Error 2
make: *** [all] Error 2
```

I have libelf version 0.165-1 installed on 4.4.1-2-ARCH.

`./kodev run`  crashes identically, after `./kodev release kobo` without `make clean`. So I'll try `./kodev clean`, followed by `./kodev build` and `./kodev release kobo`. 

Nope, no joy. New error though:
```
...[100%] Built target lua-Spore
make[3]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/lua-Spore/build/x86_64'
make[2]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/lua-Spore/build/x86_64'
STRIP_FILES="\
	build/x86_64/sdcv \
	build/x86_64/tar \
	build/x86_64/zsync \
	build/x86_64/luajit \
	build/x86_64/libs/*.so*" ;\
arm-linux-gnueabihf-strip --strip-unneeded ${STRIP_FILES} ;\
touch -r ${STRIP_FILES}  # let all files have the same mtime
arm-linux-gnueabihf-strip:build/x86_64/sdcv: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/tar: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/zsync: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/luajit: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libcrengine.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libcrypto.so.1.0.0: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libczmq.so.1: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libdjvulibre.so.21: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libfmq.so.1: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libfreetype.so.6: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libgif.so.7: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libjpeg.so.8: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libk2pdfopt.so.2: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libkoreader-cre.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libkoreader-djvu.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libkoreader-lfs.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/liblept.so.3: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/liblodepng.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libmupdf.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libpng16.so.16: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libssl.so.1.0.0: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libtesseract.so.3: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libturbojpeg.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libwrap-mupdf.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libzmq.so.4: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libz.so.1: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/libs/libzyre.so.1: File format not recognized
find build/x86_64/common -name "*.so*" | \
	xargs arm-linux-gnueabihf-strip --strip-unneeded
arm-linux-gnueabihf-strip:build/x86_64/common/socket/score.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/common/ssl.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/common/libluacompat52.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/common/serialize.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/common/libtffi_wrap.so: File format not recognized
arm-linux-gnueabihf-strip:build/x86_64/common/mime/mcore.so: File format not recognized
Makefile:26: recipe for target 'all' failed
make[1]: *** [all] Error 123
make[1]: Leaving directory '/home/markismus/github/koreader/koreader/base'
Makefile:52: recipe for target 'all' failed
make: *** [all] Error 2


```

**Comment by NiLuJe** [comment] 2016-02-18 16:09
I definitely remember *something* missing from the third-party libs for glib to be happy.

I can't remember what exactly, and it never impacted me much because that was something I happen to have in my sysroot since I alreayd build glib for unrelated reasons.

But elfutils would definitely fit the bill, since I build it also ;).

**Comment by Markismus** [comment] 2016-02-18 16:44
I have elfutils and lib32-elfutils version 0.165-1. What version do you have?

**Comment by Markismus** [comment] 2016-02-18 16:44
Could I be missing some ARM specific  libraries?

**Comment by houqp** [comment] 2016-02-18 18:23
It's weird that the path is `/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/x86_64/glib-prefix/src/glib/gio/gresource-tool.c:32:20: fatal error: libelf.h`. It should not be x86_64 is you are compiling for kobo. I actually double checked on my system and there is no libelf.h. Can you try `make TARGET=kobo all` to see if you are getting the correct path?

**Comment by Markismus** [comment] 2016-02-18 19:11
```
$ make TARGET=kobo all
make -C base
make[1]: Entering directory '/home/markismus/github/koreader/koreader/base'
/usr/bin/ccache arm-linux-gnueabihf-gcc -Lbuild/x86_64/libs -O2 -ffast-math -pipe -fomit-frame-pointer  -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mthumb -mfloat-abi=hard -fno-finite-math-only -fno-stack-protector -U_FORTIFY_SOURCE -fPIC -DKOBO_PLATFORM -I/home/markismus/github/koreader/koreader/base/thirdparty/luajit/build/x86_64/luajit-prefix/src/luajit/src -shared -Wl,-E -Wl,-rpath,'$ORIGIN' -I/home/markismus/github/koreader/koreader/base/thirdparty/popen-noshell/build/x86_64/popen-noshell-prefix/src/popen-noshell  \
	-o build/x86_64/libs/libkoreader-input.so input.c /home/markismus/github/koreader/koreader/base/thirdparty/popen-noshell/build/x86_64/popen-noshell-prefix/src/popen-noshell/libpopen_noshell.a  \

install -d thirdparty/turbo/build/x86_64
cd thirdparty/turbo/build/x86_64 && \
	cmake -DCC="/usr/bin/ccache arm-linux-gnueabihf-gcc -O2 -ffast-math -pipe -fomit-frame-pointer  -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mthumb -mfloat-abi=hard -fno-finite-math-only -fno-stack-protector -U_FORTIFY_SOURCE -fPIC -DKOBO_PLATFORM -I/home/markismus/github/koreader/koreader/base/thirdparty/openssl/build/x86_64/openssl-prefix/src/openssl/include" \
	-DLDFLAGS="-Wl,-O1 -Wl,--as-needed -static-libstdc++ -lcrypto -lssl \
	 \
	 \
	-L/home/markismus/github/koreader/koreader/base/thirdparty/openssl/build/x86_64/openssl-prefix/src/openssl -Wl,-rpath,'libs'" -DMACHINE="x86_64" \
	/home/markismus/github/koreader/koreader/base/thirdparty/turbo && \
	make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64
make[2]: Entering directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64'
make[3]: Entering directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64'
make[4]: Entering directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64'
make[4]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64'
make[4]: Entering directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64'
[ 12%] Performing build step for 'turbo'
make[5]: Entering directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64/turbo-prefix/src/turbo'
make[6]: Entering directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64/turbo-prefix/src/turbo/deps/http-parser'
/home/markismus/github/koreader/koreader/base/thirdparty/openssl/build/x86_64/openssl-prefix/src/openssl/libcrypto.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:81: recipe for target 'library' failed
make[6]: *** [library] Error 1
make[6]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64/turbo-prefix/src/turbo/deps/http-parser'
Makefile:76: recipe for target 'all' failed
make[5]: *** [all] Error 2
make[5]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64/turbo-prefix/src/turbo'
CMakeFiles/turbo.dir/build.make:110: recipe for target 'turbo-prefix/src/turbo-stamp/turbo-build' failed
make[4]: *** [turbo-prefix/src/turbo-stamp/turbo-build] Error 2
make[4]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/turbo.dir/all' failed
make[3]: *** [CMakeFiles/turbo.dir/all] Error 2
make[3]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64'
Makefile:83: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/turbo/build/x86_64'
third.Makefile:445: recipe for target 'build/x86_64/common/libtffi_wrap.so' failed
make[1]: *** [build/x86_64/common/libtffi_wrap.so] Error 2
make[1]: Leaving directory '/home/markismus/github/koreader/koreader/base'
Makefile:52: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Markismus** [comment] 2016-02-18 19:16
I do see the following warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    MACHINE


-- Build files have been written to: /home/markismus/github/koreader/koreader/base/thirdparty/libzmq/build/x86_64
```
So could it be that I have still have old environment values that f*ck things up? Or am I using the wrong compiler for arm?
The relevant values for those are:
```
export MACHINE='x86_64'
export PATH="/usr/lib/ccache/bin/:/opt/gcc-linaro-arm-linux-gnueabihf/bin/:$PATH"
```

**Comment by Markismus** [comment] 2016-02-18 19:20
I've commented `export MACHINE` out and it's building. Thanks houqp!

**Comment by Markismus** [comment] 2016-02-18 19:26
Nope. Still hangs at the same place. Apparently ccache recompiles everything when you change an environment variable:
```
  CC       gio-querymodules.o
  CC       gvdb-builder.o
  CC       glib-compile-schemas.o
  CC       glib-compile-resources.o
  CC       gsettings-tool.o
  CC       gdbus-tool.o
  CC       gapplication-tool.o
  CC       gresource-gresource-tool.o
/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib/gio/gresource-tool.c:32:20: fatal error: libelf.h: No such file or directory
 #include <libelf.h>
                    ^
compilation terminated.
Makefile:3800: recipe for target 'gresource-gresource-tool.o' failed
make[9]: *** [gresource-gresource-tool.o] Error 1
make[9]: *** Waiting for unfinished jobs....
make[9]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib-build/gio'
Makefile:3997: recipe for target 'all-recursive' failed
make[8]: *** [all-recursive] Error 1
make[8]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib-build/gio'
Makefile:1788: recipe for target 'all' failed
make[7]: *** [all] Error 2
make[7]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib-build/gio'
Makefile:1216: recipe for target 'all-recursive' failed
make[6]: *** [all-recursive] Error 1
make[6]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib-build'
Makefile:858: recipe for target 'all' failed
make[5]: *** [all] Error 2
make[5]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib-build'
CMakeFiles/glib.dir/build.make:111: recipe for target 'glib-prefix/src/glib-stamp/glib-build' failed
make[4]: *** [glib-prefix/src/glib-stamp/glib-build] Error 2
make[4]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/glib.dir/all' failed
make[3]: *** [CMakeFiles/glib.dir/all] Error 2
make[3]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf'
Makefile:83: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf'
third.Makefile:235: recipe for target '/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib-build/lib/libglib-2.0.so.0' failed
make[1]: *** [/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib-build/lib/libglib-2.0.so.0] Error 2
make[1]: Leaving directory '/home/markismus/github/koreader/koreader/base'
Makefile:91: recipe for target 'base/build/arm-linux-gnueabihf/luajit' failed
make: *** [base/build/arm-linux-gnueabihf/luajit] Error 2
```

**Comment by Markismus** [comment] 2016-02-18 19:44
I'm upgrading the gcc-compiler to a new and different AUR package. 4.9-->5.3

**Comment by houqp** [comment] 2016-02-18 23:36
That MACHINE `CMake Warning` is actually a bug in CMake. The variable is used in every subproject to set up the path. If you set the variable externally via export, then it will override the correct one set in Makefile.

I changed it makefile to not read from preset environment variable.

NOTE: sorry I was using the web UI to edit the file and committed it directly to master branch by mistake. Protip: don't use github web UI to edit file when your coworker is standing behind you and shaking your chair...

**Comment by houqp** [comment] 2016-02-18 23:40
You can use https://github.com/koreader/virdevenv to do the kobo build if you need it right now. I will take a look at it tonight to see why it's complaining this on your machine. Packages installed in bootstrap script in virdevenv contains all the needed dependencies.

**Comment by houqp** [comment] 2016-02-19 03:49
@Markismus according to https://mail.gnome.org/archives/commits-list/2012-June/msg01722.html, there is an option to disable libelf support. Could you try adding that option to the following line and test?

https://github.com/koreader/koreader-base/blob/master/thirdparty/glib/CMakeLists.txt#L37

**Comment by Markismus** [comment] 2016-02-19 09:22
Line 37 is now: `set(CFG_OPTS "--with-libiconv=\"${WITH_LIBICONV}\" --with-threads=posix --prefix=${BINARY_DIR} --without-included-gettext --with-gettext=no --enable-shared=${ENABLE_SHARED} --disable-static --disable-libelf")`

It has an effect and of course a new error:
```
checking for zlibVersion in -lz... no
configure: error: zlib not found
CMakeFiles/sdcv.dir/build.make:105: recipe for target 'sdcv-prefix/src/sdcv-stamp/sdcv-configure' failed
make[4]: *** [sdcv-prefix/src/sdcv-stamp/sdcv-configure] Error 1
make[4]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/sdcv/build/arm-linux-gnueabihf'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sdcv.dir/all' failed
make[3]: *** [CMakeFiles/sdcv.dir/all] Error 2
make[3]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/sdcv/build/arm-linux-gnueabihf'
Makefile:83: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/markismus/github/koreader/koreader/base/thirdparty/sdcv/build/arm-linux-gnueabihf'
third.Makefile:287: recipe for target 'build/arm-linux-gnueabihf/sdcv' failed
make[1]: *** [build/arm-linux-gnueabihf/sdcv] Error 2
make[1]: Leaving directory '/home/markismus/github/koreader/koreader/base'
Makefile:52: recipe for target 'all' failed
make: *** [all] Error 2
```
I've got zlib 1.2.8-4  on my system, but I suppose this library should be for abihf?

**Comment by Markismus** [comment] 2016-02-19 09:23
@houqp  On what time zone are you anyway? I am at CET. Just having my first pauze in the day.

**Comment by houqp** [comment] 2016-02-19 18:05
That's weird, sdcv should be using the static zlib we compiled ourself, not the system one. Can you try do build it in verbose mode? Just run `VERBOSE=1 ./kodev build kobo`. In sdcv build log, you should be able to find the `LIBS` variable in configure step, which should look like the following:

```
 LIBS=\"      -
lpthread -lrt           */koreader/base/thirdparty/zlib/build/arm-linux-gnueabihf/zlib-prefix/src/zlib/libz.a            -static-libgcc -static-libstdc++\""
```
PS: I am in PST ;)

**Comment by Markismus** [comment] 2016-02-19 20:24
This generates:
```
$ cat build.log | grep "lpthread"
		-lpthread -lrt \
cd /home/markismus/github/koreader/koreader/base/thirdparty/sdcv/build/arm-linux-gnueabihf/sdcv-prefix/src/sdcv && sh -c "/home/markismus/github/koreader/koreader/base/thirdparty/sdcv/build/arm-linux-gnueabihf/sdcv-prefix/src/sdcv/configure --host=\"arm-linux-gnueabihf\" PKG_CONFIG_PATH=\"/home/markismus/github/koreader/koreader/base/thirdparty/glib/build/arm-linux-gnueabihf/glib-prefix/src/glib-build/lib/pkgconfig\" CXX=\"/usr/bin/ccache arm-linux-gnueabihf-g++\" CXXFLAGS=\"-O2 -ffast-math -pipe -fomit-frame-pointer  -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mthumb -mfloat-abi=hard -fno-finite-math-only -fno-stack-protector -U_FORTIFY_SOURCE -fPIC -I/home/markismus/github/koreader/koreader/base/thirdparty/zlib/build/arm-linux-gnueabihf/zlib-prefix/src/zlib\" LDFLAGS=\"-Wl,-O1 -Wl,--as-needed -static-libstdc++ -L/home/markismus/github/koreader/koreader/base/thirdparty/zlib/build/arm-linux-gnueabihf/zlib-prefix/src/zlib\" LIBS=\" 		-lpthread -lrt 		/home/markismus/github/koreader/koreader/base/thirdparty/zlib/build/arm-linux-gnueabihf/zlib-prefix/src/zlib/libz.a 		-static-libgcc -static-libstdc++\""
```

**Comment by houqp** [comment] 2016-02-19 20:54
I can see it exists in the directory though:  /home/markismus/github/koreader/koreader/base/thirdparty/zlib/build/arm-linux-gnueabihf/zlib-prefix/src/zlib/libz.a

It's libz.a, not zlib.a ;P 

I wonder why it's not finding it. As a dirty hack, you can try setting LIBS to `LIBS=\"${LDFALGS} ${LIBS}\"` in CMakeLists.txt. The LDFALGS should contains `-L/home/markismus/github/koreader/koreader/base/thirdparty/zlib/build/arm-linux-gnueabihf/zlib-prefix/src/zlib/`. Can you try to see if it helps?

**Comment by Markismus** [comment] 2016-02-19 21:22
Yes, I know. I updated the comment, but I suppose you read the initial post via email, right?

**Comment by Markismus** [comment] 2016-02-19 21:29
So I changed line 25 in ..../base/thirdparty/sdcv/CMakeLists.txt to:
```
set(CFG_OPTS "--host=\"${HOST}\" PKG_CONFIG_PATH=\"${PKG_CONFIG_PATH}\" CXX=\"${CXX}\" CXXFLAGS=\"${CXXFLAGS}\" LDFLAGS=\"${LDFLAGS}\" LIBS=\"${LDFLAGS} ${LIBS}\"")
```

Same error as before is generated.

**Comment by houqp** [comment] 2016-02-20 00:54
Hmm... No idea why it's not finding the library then :( What version of ARCH are you using? Let me try reproduce it on my side.

**Comment by Markismus** [comment] 2016-02-20 11:31
4.4.1-2-ARCH

**Comment by houqp** [comment] 2016-02-25 06:01
@Markismus , how did you get your xtoolchain? Did you built it from AUR or downloaded from somewhere else?

**Comment by Markismus** [comment] 2016-02-29 16:23
@houqp Sorry, missed this post! 

This is what I installed for arm-linux:
```sh
$ pacman -Qs arm-linux
local/arm-linux-gnueabihf-binutils 2.25.1-3
    A set of programs to assemble and manipulate binary and object files (arm-linux-gnueabihf)
local/arm-linux-gnueabihf-gcc 5.3.0-2
    The GNU Compiler Collection (arm-linux-gnueabihf)
local/arm-linux-gnueabihf-glibc 2.22-3
    GNU C Library (arm-linux-gnueabihf)
local/arm-linux-gnueabihf-linux-api-headers 4.1.4-1
    Kernel headers sanitized for use in userspace (arm-linux-gnueabihf)
```

**Comment by Markismus** [comment] 2016-02-29 20:00
I've reading through the [arch crosscompiling wiki](https://wiki.archlinux.org/index.php/Cross-compiling_tools_package_guidelines) and it clearly states to use `PATH=/usr/arm-linux-gnueabihf/bin/:$PATH`. I did use that line with the linaro crosscompile toolchain. However, not only is there no `bin` directory in `/usr/arm-linux-gnueabihf`, I also found the directory `/usr/x86_64-unknown-linux-gnu/arm-linux-gnueabihf`, which coincidently also has no `bin` directory. So I am a bit of a loss. 

The `unknown` part resulted most probably from commenting out the environment variable `MACHINE='x86_64'`.

**Comment by NiLuJe** [comment] 2016-02-29 23:26
Yup, confirmed the libelf issue.

Since I neuter pkg-config when building KOReader, it fails to find it..

````
  CCLD     gresource
/home/niluje/x-tools/arm-kindle5-linux-gnueabi/lib/gcc/arm-kindle5-linux-gnueabi/5.2.1/../../../../arm-kindle5-linux-gnueabi/bin/ld.gold: error: cannot find -lelf
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:141: error: undefined reference to 'elf_version'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:148: error: undefined reference to 'elf_begin'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:156: error: undefined reference to 'elf_kind'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:181: error: undefined reference to 'elf_getshdrstrndx'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:184: error: undefined reference to 'elf_getshdrnum'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:189: error: undefined reference to 'elf_getscn'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:193: error: undefined reference to 'gelf_getshdr'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:200: error: undefined reference to 'elf_strptr'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:409: error: undefined reference to 'elf_end'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:141: error: undefined reference to 'elf_version'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:148: error: undefined reference to 'elf_begin'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:156: error: undefined reference to 'elf_kind'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:181: error: undefined reference to 'elf_getshdrstrndx'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:184: error: undefined reference to 'elf_getshdrnum'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:189: error: undefined reference to 'elf_getscn'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:193: error: undefined reference to 'gelf_getshdr'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:200: error: undefined reference to 'elf_strptr'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:373: error: undefined reference to 'elf_end'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:141: error: undefined reference to 'elf_version'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:148: error: undefined reference to 'elf_begin'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:156: error: undefined reference to 'elf_kind'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:181: error: undefined reference to 'elf_getshdrstrndx'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:184: error: undefined reference to 'elf_getshdrnum'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:189: error: undefined reference to 'elf_getscn'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:193: error: undefined reference to 'gelf_getshdr'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:200: error: undefined reference to 'elf_strptr'
/home/niluje/Kindle/CrossTool/Build_KO/koreader/base/thirdparty/glib/build/arm-kindle5-linux-gnueabi/glib-prefix/src/glib/gio/gresource-tool.c:446: error: undefined reference to 'elf_end'
collect2: error: ld returned 1 exit status
````

(Note that it does find the headers because those are hardcoded in my CPPFLAGS).

**Comment by NiLuJe** [comment] 2016-02-29 23:37
That was my only build failure, though.

(Once I managed to unstupidify CMake by feeding it a proper CMAKE_TOOLCHAIN_FILE so that it doesn't get its wires crossed between the host & target arches/flags...)

**Comment by houqp** [comment] 2016-03-01 09:01
@Markismus , cool, I will give it a try on my arch vm. BTW, we have container build image now: https://github.com/koreader/virdevenv/tree/master/docker/ubuntu/baseimage. This should give you much faster speed (close to native) compared to the previous VM build image.

Thanks @NiLuJe for fixing the libelf issue! I wonder if we can do the same thing to just disable libffi.

I wasn't aware of CMAKE_TOOLCHINA_FILE before, looks like something we should use in the future to help make koreader-base's build setup smarter ;)

**Comment by houqp** [comment] 2016-03-02 02:39
Surprisingly, I was able to do cross-compile by just setting cmake options from Makefile. I do see some of the settings you have in TOOLCHAIN_FILE is missing from Makefile though, that's why I think we should do it probably using TOOLCHAIN_FILE. It should also make our Makefile cleaner. Right now I am literally passing that extra settings with every cmake call >_<

**Comment by NiLuJe** [comment] 2016-03-02 02:45
I'm also setting the *target* CFLAGS in my env, which is also probably why trying those with CMake using my *host*'s CC went kablooey without some handholding.

I imagine most non-Gentoo/Slackware people don't have CFLAGS always set in their envs, be they host or target related ;p.

... I'm going to bed, really. :D.

**Comment by houqp** [comment] 2016-03-02 08:26
Plus nixos, I am a huge fan of them ;)

**Comment by NiLuJe** [comment] 2016-03-02 15:20
Huh, wasn't aware of that one, it looks fun :).

**Comment by houqp** [comment] 2016-03-03 08:45
It gets the best of arch and gentoo plus its own fancy magic. I was blown away by their demo when I first saw it in pycon. Now I am using its package manager to manage both my ubuntu and OSX :)

**Comment by Markismus** [comment] 2016-03-06 10:19
I read that they use their own scripting language for package management. How accessible would that make it for someone, who doesn't directly see it as an obvious syntax?

**Comment by houqp** [comment] 2016-03-06 23:23
It has its own pure functional DSL to guarantee deterministic builds. If you are only using it like a binary distribution, i.e. arch or ubuntu, then you don't need to write your own package. You can just download and install whatever package that's available out there. If you are using it as a source distribution like Gentoo and want to tweak the compilation flags, then you will have to learn a DSL to manage your own packages anyway. I personally find their DSL easy to learn ;) Took me roughly the same time to get started compared to what gentoo offers.

**Comment by NiLuJe** [comment] 2016-04-12 02:49
Anyone still encountering any weird build issues?

**Comment by houqp** [comment] 2016-04-14 07:43
Still working on setting up toolchina in arch vm... Getting weird build issues with https://github.com/koreader/koxtoolchain in arch.

**Comment by NiLuJe** [comment] 2016-04-14 09:33
Yup, CT-NG is probably iffy on Arch since Arch ditched static libraries...
I haven't followed this closely, but last time it came up, it was a bit of
a mess...

**Comment by NiLuJe** [comment] 2016-04-14 09:38
Cf. https://github.com/crosstool-ng/crosstool-ng/issues/297

**Comment by chrox** [comment] 2016-06-30 14:30
Seems no progress, closing this now.

**Closed by chrox** 2016-06-30 14:30 UTC
Labels: bug
