### ISSUE TITLE
KOReader freezing on android

### ISSUE THREAD

**Issue by mendelct** [koreader/koreader#7344] opened 2021-02-24 21:49 UTC
* KOReader version:2021.02.38
* Device:Samsung s10

#### Issue
KOReader freezes when opening folders with more than two or three hundred files. The crash log below is from trying to open the file manager from within a book.
##### `crash.log` (if applicable)
02-24 15:32:00.009  1115  2151 D ActivityManager: Received BROADCAST intent 0xc07978f Key{broadcastIntent pkg=com.nullium.nicesimpleclock intent=act=com.nullium.nicesimpleclock.action.WIDGET_ALARM_UPDATE cmp=com.nullium.nicesimpleclock/.NiceSimpleClockWidgetOneTimesThreeProvider flags=0x0 u=0} requestCode=0 sent=0 from uid 1000
02-24 15:32:26.544  1115  2151 D ActivityManager: Received BROADCAST intent 0x5a6eba9 Key{broadcastIntent pkg=com.sec.android.app.launcher intent=act=com.samsung.action.EVERY_MINUTE_CLOCK_UPDATE flags=0x0 u=0} requestCode=0 sent=0 from uid 1000
02-24 15:33:00.001  1115  2151 D ActivityManager: Received BROADCAST intent 0xc07978f Key{broadcastIntent pkg=com.nullium.nicesimpleclock intent=act=com.nullium.nicesimpleclock.action.WIDGET_ALARM_UPDATE cmp=com.nullium.nicesimpleclock/.NiceSimpleClockWidgetOneTimesThreeProvider flags=0x0 u=0} requestCode=0 sent=0 from uid 1000
02-24 15:33:00.021  1115  2151 D ActivityManager: Received BROADCAST intent 0x5a6eba9 Key{broadcastIntent pkg=com.sec.android.app.launcher intent=act=com.samsung.action.EVERY_MINUTE_CLOCK_UPDATE flags=0x0 u=0} requestCode=0 sent=0 from uid 1000
02-24 15:33:20.033  1115  1560 I ActivityManager: Start proc 27758:com.samsung.android.game.gos/u0a184 for service {com.samsung.android.game.gos/com.samsung.android.game.gos.service.GameIntentService}
02-24 15:33:20.044  1115  1560 I ActivityManager: Start proc 27764:com.google.android.apps.turbo/u0a113 for broadcast {com.google.android.apps.turbo/com.google.android.apps.turbo.nudges.broadcasts.BatteryStatusChangedReceiver}
02-24 15:33:20.075  1115  7115 I ActivityManager: DSS OFF for com.samsung.android.game.gos
02-24 15:33:20.077  1115  7115 D ActivityManager: attachApplicationLocked() app=ProcessRecord{d78fadb 27758:com.samsung.android.game.gos/u0a184} app.isolatedEntryPoint=null instr2=null
02-24 15:33:20.096  1115  7115 I ActivityManager: DSS OFF for com.google.android.apps.turbo
02-24 15:33:20.097  1115  7115 D ActivityManager: attachApplicationLocked() app=ProcessRecord{2b558b6 27764:com.google.android.apps.turbo/u0a113} app.isolatedEntryPoint=null instr2=null
02-24 15:33:21.192  1115  8466 I ActivityManager: Killing 26302:com.samsung.storyservice/u150s5004 (adj 999): empty #37
02-24 15:33:21.195  1115  8466 I ActivityManager: Killing 26547:com.google.android.webview:webview_service/u150a196 (adj 999): empty #38
02-24 15:33:21.252  1115  8460 W ActivityManager: Scheduling restart of crashed service com.samsung.storyservice/.StoryService in 1000ms for connection
02-24 15:33:22.287  1115  1560 I ActivityManager: Start proc 27816:com.samsung.storyservice/u150s5004 for service {com.samsung.storyservice/com.samsung.storyservice.StoryService}
02-24 15:33:22.350  1115  8460 I ActivityManager: DSS OFF for com.samsung.storyservice
02-24 15:33:22.352  1115  8460 D ActivityManager: attachApplicationLocked() app=ProcessRecord{28d9769 27816:com.samsung.storyservice/u150s5004} app.isolatedEntryPoint=null instr2=null
02-24 15:33:22.462  1115  8460 I ActivityManager: Killing 26639:com.samsung.faceservice/u150s5004 (adj 999): empty #37
02-24 15:33:22.514  1115  8460 W ActivityManager: Scheduling restart of crashed service com.samsung.faceservice/.FaceService in 1000ms for connection
02-24 15:33:23.554  1115  1560 I ActivityManager: Start proc 27840:com.samsung.faceservice/u150s5004 for service {com.samsung.faceservice/com.samsung.faceservice.FaceService}
02-24 15:33:23.620  1115  8460 I ActivityManager: DSS OFF for com.samsung.faceservice
02-24 15:33:23.622  1115  8460 D ActivityManager: attachApplicationLocked() app=ProcessRecord{4242752 27840:com.samsung.faceservice/u150s5004} app.isolatedEntryPoint=null instr2=null
02-24 15:33:23.847  1115  8460 I ActivityManager: Killing 25773:com.sec.android.provider.badge/u0a14 (adj 999): empty #37
02-24 15:33:42.234  1115  8464 I ActivityManager: Killing 25794:com.sec.android.provider.badge/u150a14 (adj 999): empty #37
02-24 15:33:47.607  1115  1560 I ActivityManager: Start proc 27868:com.samsung.android.lool:TileService.Process/1000 for service {com.samsung.android.lool/com.samsung.android.sm.enhancedcpu.EnhancedCpuTile}
02-24 15:33:47.649  1115  8460 I ActivityManager: DSS OFF for com.samsung.android.lool
02-24 15:33:47.650  1115  8460 D ActivityManager: attachApplicationLocked() app=ProcessRecord{34d1ae5 27868:com.samsung.android.lool:TileService.Process/1000} app.isolatedEntryPoint=null instr2=null
02-24 15:33:57.590  1115 27901 I ActivityManager: dumpStackTraces pids={811=true, 1115=true, 1175=true, 1454=true, 2549=true, 2705=true, 3444=true, 3858=true, 4507=true, 4948=true, 5129=true, 7166=true, 7238=true, 7245=true, 7329=true, 7453=true, 7542=true, 7562=true, 7584=true, 7591=true, 7617=true, 7652=true, 7663=true, 7762=true, 7815=true, 7877=true, 8067=true, 8128=true, 8340=true, 8346=true, 8372=true, 8403=true, 8419=true, 8493=true, 8504=true, 8530=true, 8561=true, 8612=true, 8733=true, 8749=true, 8866=true, 9117=true, 9249=true, 9928=true, 10220=true, 10226=true, 14794=true, 14804=true, 14840=true, 15357=true, 15706=true, 16187=true, 17169=true, 17531=true, 17739=true, 19206=true, 20409=true, 21959=true, 22055=true, 22177=true, 22418=true, 23366=true, 23387=true, 23426=true, 23516=true, 23558=true, 23635=true, 23699=true, 23847=true, 23923=true, 23961=true, 24060=true, 24374=true, 24456=true, 24679=true, 24740=true, 24775=true, 24998=true, 25281=true, 25307=true, 26362=true, 26387=true, 26475=true, 26697=true, 26852=true, 26859=true, 26902=true, 27140=true, 27166=true, 27190=true, 27220=true, 27279=true, 27327=true, 27368=true, 27445=true, 27474=true, 27540=true, 27575=true, 27681=true, 27758=true, 27764=true, 27816=true, 27840=true, 27868=true, 28647=true, 30472=true, 30651=true, 30679=true, 31248=true, 31312=true, 31391=true, 31474=true, 31558=true, 31572=true, 32299=true} nativepids=[634, 764, 765, 766, 767, 925, 946, 1102, 1103, 1113, 1122, 1124, 1125, 1137, 1159, 7877]
02-24 15:33:58.047  1115 27901 I ActivityManager: Skipping next CPU consuming process, not a java proc: 25744
02-24 15:33:58.048  1115 27901 I ActivityManager: Skipping next CPU consuming process, not a java proc: 30
02-24 15:33:58.048  1115 27901 I ActivityManager: Skipping next CPU consuming process, not a java proc: 610
02-24 15:33:58.048  1115 27901 I ActivityManager: Skipping next CPU consuming process, not a java proc: 946
02-24 15:33:58.057  1115 27901 I ActivityManager: dumpStackTraces force pid=8128
02-24 15:33:58.057  1115 27901 I ActivityManager: dumpStackTraces force pid=9928
02-24 15:33:58.059  1115 27901 I ActivityManager: Dumping to /data/anr/anr_2021-02-24-15-33-58-058
02-24 15:33:58.059  1115 27901 I ActivityManager: Collecting stacks for pid 25744
02-24 15:33:58.172  1115 27901 I ActivityManager: Collecting stacks for native pid 634
02-24 15:33:58.259  1115 27901 I ActivityManager: Collecting stacks for native pid 764
02-24 15:33:58.339  1115 27901 I ActivityManager: Collecting stacks for native pid 765
02-24 15:33:58.440  1115 27901 I ActivityManager: Collecting stacks for native pid 766
02-24 15:33:58.492   766   766 F libc    : failed to wait for crash_dump helper: No child processes
02-24 15:33:58.604  1115 27901 I ActivityManager: Collecting stacks for native pid 767
02-24 15:33:58.655   767   767 F libc    : failed to wait for crash_dump helper: No child processes
02-24 15:33:58.778  1115 27901 I ActivityManager: Collecting stacks for native pid 925
02-24 15:33:58.910  1115 27901 I ActivityManager: Collecting stacks for native pid 946
02-24 15:33:59.044  1115 27901 I ActivityManager: Collecting stacks for native pid 1102
02-24 15:33:59.149  1115 27901 I ActivityManager: Collecting stacks for native pid 1103
02-24 15:33:59.234  1115 27901 I ActivityManager: Collecting stacks for native pid 1113
02-24 15:33:59.308  1115 27901 I ActivityManager: Collecting stacks for native pid 1122
02-24 15:33:59.534  1115 27901 I ActivityManager: Collecting stacks for native pid 1124
02-24 15:33:59.628  1115 27901 I ActivityManager: Collecting stacks for native pid 1125
02-24 15:33:59.757  1115 27901 I ActivityManager: Collecting stacks for native pid 1137
02-24 15:34:00.010  1115  2151 D ActivityManager: Received BROADCAST intent 0x5a6eba9 Key{broadcastIntent pkg=com.sec.android.app.launcher intent=act=com.samsung.action.EVERY_MINUTE_CLOCK_UPDATE flags=0x0 u=0} requestCode=0 sent=0 from uid 1000
02-24 15:34:00.024  1115  2151 D ActivityManager: Received BROADCAST intent 0xc07978f Key{broadcastIntent pkg=com.nullium.nicesimpleclock intent=act=com.nullium.nicesimpleclock.action.WIDGET_ALARM_UPDATE cmp=com.nullium.nicesimpleclock/.NiceSimpleClockWidgetOneTimesThreeProvider flags=0x0 u=0} requestCode=0 sent=0 from uid 1000
02-24 15:34:01.057  1115 27901 I ActivityManager: Collecting stacks for native pid 1159
02-24 15:34:01.442  1115 27901 I ActivityManager: Collecting stacks for native pid 7877
02-24 15:34:01.806  1115 27901 I ActivityManager: Collecting stacks for extra pid 14840
02-24 15:34:01.931  1115 27901 I ActivityManager: Collecting stacks for extra pid 1115
02-24 15:34:02.621  1115 27901 I ActivityManager: Collecting stacks for extra pid 4507
02-24 15:34:03.288  1115 27901 I ActivityManager: Collecting stacks for extra pid 4948
02-24 15:34:17.869  1115 27901 W ActivityManager: Dumping Java threads failed, initiating native stack dump.
02-24 15:34:19.944  1115 27901 W ActivityManager: Native stack dump failed!
02-24 15:34:19.944  1115 27901 E ActivityManager: Aborting stack trace dump (current extra pid=4948); deadline exceeded.
02-24 15:34:20.001  1115 27901 E ActivityManager: ANR in org.koreader.launcher (org.koreader.launcher/.MainActivity)
02-24 15:34:20.001  1115 27901 E ActivityManager: PID: 25744
02-24 15:34:20.001  1115 27901 E ActivityManager: Reason: Input dispatching timed out (2c19a21 org.koreader.launcher/org.koreader.launcher.MainActivity (server) is not responding. Waited 10007ms for MotionEvent)
02-24 15:34:20.001  1115 27901 E ActivityManager: Parent: org.koreader.launcher/.MainActivity
02-24 15:34:20.001  1115 27901 E ActivityManager: Load: 0.32 / 1.02 / 0.75
02-24 15:34:20.001  1115 27901 E ActivityManager: ------ Current CPU Core Info ------
02-24 15:34:20.001  1115 27901 E ActivityManager: - offline :
02-24 15:34:20.001  1115 27901 E ActivityManager: - online : 0-7
02-24 15:34:20.001  1115 27901 E ActivityManager: - AP Temp = 339
02-24 15:34:20.001  1115 27901 E ActivityManager:                              0           1           2           3           4           5           6           7
02-24 15:34:20.001  1115 27901 E ActivityManager: ------------------------------------------------------------------------------------------------------------------
02-24 15:34:20.001  1115 27901 E ActivityManager: scaling_cur_freq       1785600     1785600     1785600     1785600     1612800     1612800     1612800      825600
02-24 15:34:20.001  1115 27901 E ActivityManager: scaling_governor     schedutil   schedutil   schedutil   schedutil   schedutil   schedutil   schedutil   schedutil
02-24 15:34:20.001  1115 27901 E ActivityManager: scaling_max_freq       1785600     1785600     1785600     1785600     2419200     2419200     2419200     2841600
02-24 15:34:20.001  1115 27901 E ActivityManager: ------------------------------------------------------------------------------------------------------------------
02-24 15:34:20.001  1115 27901 E ActivityManager: ----- Output from /proc/pressure/memory -----
02-24 15:34:20.001  1115 27901 E ActivityManager: some avg10=0.00 avg60=0.00 avg300=0.00 total=67627568
02-24 15:34:20.001  1115 27901 E ActivityManager: full avg10=0.00 avg60=0.00 avg300=0.00 total=26844278
02-24 15:34:20.001  1115 27901 E ActivityManager: ----- End output from /proc/pressure/memory -----
02-24 15:34:20.001  1115 27901 E ActivityManager:
02-24 15:34:20.001  1115 27901 E ActivityManager: CPU usage from 0ms to 22419ms later (2021-02-24 15:33:57.526 to 2021-02-24 15:34:19.945):
02-24 15:34:20.001  1115 27901 E ActivityManager:   82% 14840/com.android.providers.media.module: 3% user + 79% kernel / faults: 796 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   14% 4507/com.microsoft.office.outlook: 8.5% user + 6.4% kernel / faults: 3620 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   14% 1115/system_server: 6.3% user + 8.4% kernel / faults: 11478 minor 1 major
02-24 15:34:20.001  1115 27901 E ActivityManager:   10% 4948/com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0: 6.6% user + 4.2% kernel / faults: 4067 minor 8 major
02-24 15:34:20.001  1115 27901 E ActivityManager:   7.5% 25744/org.koreader.launcher: 2.7% user + 4.7% kernel / faults: 4928 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.7% 1137/media.codec: 0.3% user + 0.3% kernel / faults: 31022 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   5.1% 946/surfaceflinger: 1.5% user + 3.6% kernel / faults: 315 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   2.5% 13823/kworker/u16:6: 0% user + 2.5% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   2.1% 837/android.hardware.sensors@2.0-service.multihal: 1.2% user + 0.9% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   1.9% 9776/kworker/u16:5: 0% user + 1.9% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   1.8% 25707/kworker/u16:2: 0% user + 1.8% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   1.6% 8346/com.google.android.gms.persistent: 1.3% user + 0.3% kernel / faults: 22 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 1159/media.swcodec: 0% user + 0.1% kernel / faults: 10744 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   1.1% 764/statsd: 0.9% user + 0.1% kernel / faults: 830 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   1.1% 7663/com.android.phone: 0.5% user + 0.5% kernel / faults: 503 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 1122/media.extractor: 0% user + 0% kernel / faults: 4278 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.8% 8419/com.sec.android.sdhms: 0% user + 0.7% kernel / faults: 100 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.6% 858/qrtr_rx: 0% user + 0.6% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.6% 28647/com.android.systemui: 0.4% user + 0.1% kernel / faults: 261 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.6% 12/rcuop/0: 0% user + 0.6% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.6% 30/rcuop/2: 0% user + 0.6% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.6% 609/logd: 0% user + 0.5% kernel / faults: 271 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.4% 9/rcu_preempt: 0% user + 0.4% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.4% 22/rcuop/1: 0% user + 0.4% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.4% 38/rcuop/3: 0% user + 0.4% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.4% 610/lmkd: 0% user + 0.3% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.3% 589/ueventd: 0.2% user + 0% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.2% 683/iod: 0% user + 0.2% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0% 7877/com.android.bluetooth: 0% user + 0% kernel / faults: 191 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 23516/com.samsung.android.app.telephonyui: 0.1% user + 0% kernel / faults: 460 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.2% 7803/argosd: 0% user + 0.1% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 1/init: 0% user + 0.1% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 46/rcuop/4: 0% user + 0.1% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 1746/rild: 0.1% user + 0% kernel / faults: 1 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 8122/irq/32-90b6400.: 0% user + 0.1% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0% 23923/com.android.providers.calendar: 0% user + 0% kernel / faults: 222 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0% 23961/com.samsung.android.calendar: 0% user + 0% kernel / faults: 195 minor
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 25028/logcat: 0% user + 0% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0% 54/rcuop/5: 0% user + 0% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 505/crtc_commit:133: 0% user + 0.1% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0.1% 611/servicemanager: 0% user + 0% kernel
02-24 15:34:20.001  1115 27901 E ActivityManager:   0% 925/audioserver: 0% user + 0% kernel / faults: 129 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0.1% 7584/com.sec.imsservice: 0% user + 0.1% kernel / faults: 109 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 7890/adbd: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 8125/irq/33-90cd000.: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0.1% 9117/com.google.android.googlequicksearchbox:search: 0% user + 0% kernel / faults: 65 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0.1% 25602/kworker/0:2: 0% user + 0.1% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0.1% 26164/kworker/u16:7: 0% user + 0.1% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0.1% 26850/kworker/3:1: 0% user + 0.1% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0.1% 27714/kworker/2:1: 0% user + 0.1% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 10/rcu_sched: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 62/rcuop/6: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 257/kgsl_worker_thr: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 731/auditd: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 733/tombstoned: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 765/netd: 0% user + 0% kernel / faults: 191 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 766/zygote64: 0% user + 0% kernel / faults: 15 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 899/vendor.samsung.hardware.thermal@1.0-service: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 1125/mediaserver: 0% user + 0% kernel / faults: 84 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 1772/qrtr_rx: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 3444/com.samsung.android.incallui: 0% user + 0% kernel / faults: 6 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 26820/kworker/1:0: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 30651/com.samsung.android.dialer: 0% user + 0% kernel / faults: 9 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 31558/com.digitalturbine.ignite.suspend.DataUsageRecorderService: 0% user + 0% kernel / faults: 14 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 13/rcuos/0: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 31/rcuos/2: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 47/rcuos/4: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 63/rcuos/6: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 70/rcuop/7: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 135/kauditd: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 634/vold: 0% user + 0% kernel / faults: 66 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 689/android.system.suspend@1.0-service: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 709/jbd2/sda31-8: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 767/zygote: 0% user + 0% kernel / faults: 14 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 833/android.hardware.graphics.composer@2.4-service: 0% user + 0% kernel / faults: 8 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 834/android.hardware.health@2.1-service-samsung: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 835/android.hardware.memtrack@1.0-service: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 1102/cameraserver: 0% user + 0% kernel / faults: 64 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 1103/drmserver: 0% user + 0% kernel / faults: 29 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 1113/installd: 0% user + 0% kernel / faults: 109 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 1124/media.metrics: 0% user + 0% kernel / faults: 51 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 3858/com.touchtype.swiftkey: 0% user + 0% kernel / faults: 3 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 6968/iptables-restore: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 7885/freecessmonitor: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 10226/com.sec.epdg: 0% user + 0% kernel / faults: 25 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 11298/eris: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 15666/kworker/u17:1: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 17531/com.hiya.star: 0% user + 0% kernel / faults: 6 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 23387/com.samsung.android.ipsgeofence: 0% user + 0% kernel / faults: 17 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 23426/com.verizon.messaging.vzmsgs: 0% user + 0% kernel / faults: 9 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 25921/kworker/u17:0: 0% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   0% 31474/com.LogiaGroup.LogiaDeck: 0% user + 0% kernel / faults: 21 minor
02-24 15:34:20.002  1115 27901 E ActivityManager: 20% TOTAL: 4.8% user + 14% kernel + 0% iowait + 0.5% irq + 0.2% softirq
02-24 15:34:20.002  1115 27901 E ActivityManager: CPU usage from 65ms to 482ms later (2021-02-24 15:33:57.590 to 2021-02-24 15:33:58.008) with 99% awake:
02-24 15:34:20.002  1115 27901 E ActivityManager:   80% 14840/com.android.providers.media.module: 3.3% user + 77% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     16% 22014/Thread-5: 6.7% user + 10% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     13% 1429/Thread-13: 0% user + 13% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     13% 5821/Thread-9: 0% user + 13% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     13% 14913/Thread-4: 0% user + 13% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     13% 24905/Thread-6: 0% user + 13% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     10% 14914/Thread-3: 0% user + 10% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     10% 24937/Thread-7: 0% user + 10% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   47% 1115/system_server: 8.3% user + 38% kernel / faults: 1006 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:     44% 27901/AnrConsumer: 5.5% user + 38% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     2.7% 2124/SensorService: 0% user + 2.7% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     2.7% 7103/Binder:1115_9: 2.7% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   8.8% 4507/com.microsoft.office.outlook: 5.8% user + 2.9% kernel / faults: 22 minor
02-24 15:34:20.002  1115 27901 E ActivityManager:     2.9% 4507/.office.outlook: 2.9% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   5.9% 4948/com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0: 2.9% user + 2.9% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     2.9% 5012/Chrome_ChildIOT: 0% user + 2.9% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     2.9% 5014/Compositor: 2.9% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   7.3% 25744/org.koreader.launcher: 3.6% user + 3.6% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     7.3% 27416/Thread-162: 3.6% user + 3.6% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   2.3% 30/rcuop/2: 0% user + 2.3% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   2.6% 610/lmkd: 0% user + 2.6% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   2.7% 946/surfaceflinger: 0% user + 2.7% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     2.7% 1054/TimerDispatch: 0% user + 2.7% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   3% 7663/com.android.phone: 3% user + 0% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:     3% 7663/m.android.phone: 0% user + 3% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   3% 7803/argosd: 0% user + 3% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   3.1% 8346/com.google.android.gms.persistent: 0% user + 3.1% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager:   3.2% 9776/kworker/u16:5: 0% user + 3.2% kernel
02-24 15:34:20.002  1115 27901 E ActivityManager: 22% TOTAL: 3.6% user + 18% kernel + 0.6% irq + 0.3% softirq
02-24 15:34:20.006  1115 27901 W ActivityManager: anr : org.koreader.launcher,15010578
02-24 15:34:20.006  1115 27901 D ActivityManager: Completed ANR of org.koreader.launcher in 22481ms, latency 0ms

**Comment by NiLuJe** [comment] 2021-02-24 21:58
Probably technically a duplicate of the usual ANR reports (especially on Samsung).

Don't recall if this applies to Samsung, but if you don't tap the screen, there's a vague chance that won't trip the ANR check.

Other than that, nothing much we could do. @pazos would explain it better, but we essentially behave like a game, which means Android doesn't like it we block the UI thread ;).

**Comment by pazos** [comment] 2021-02-24 22:12
Yup, it is a duplicate of https://github.com/koreader/koreader/issues/6981

And has the same workaround: **don't touch the screen**. We're single threaded and when doing stuff that takes more than 5 seconds android will flag us as not responding, even when the operation is taking place and will probably finish soon :tm: 

A better definition of what happens in https://github.com/koreader/koreader/issues/6981#issuecomment-752251104

Also: it is useful to know where users trigger ANRs because we have code in place to tell the app to ignore input completely until it is done doing its job. See https://github.com/koreader/koreader/issues/6981#issuecomment-752255904

**Closed by pazos** 2021-02-24 22:12 UTC
Labels: Android, can't fix

**Comment by mendelct** [comment] 2021-02-25 03:23
how long should it take for the file browser to load?
