### ISSUE TITLE
Koreader no more supported on Kindle 4 NT

### ISSUE THREAD

**Issue by GilDev** [koreader/koreader#3018] opened 2017-07-20 19:37 UTC
Just tried different releases of Koreader with KUAL on my K4NT, it appears that the last working release is nightly 20170308. Releases after that crashes when pushing the menu button. Maybe it has something to do with the “swipe to open menu” feature that got implemented at that time.

**Comment by Frenzie** [comment] 2017-07-20 19:45
Would it be possible to provide an error log?

**Comment by GilDev** [comment] 2017-07-20 20:23
Sure, where can I find that?

**Comment by Frenzie** [comment] 2017-07-20 20:33
Unfortunately I don't have a Kindle. Probably simply the KOReader folder?

**Comment by GilDev** [comment] 2017-07-20 20:38
Forgot to mention it automatically opens an help file when it is started, even when selecting “Start the filemanager” in KUAL's menu.
Otherwise you were right, here's `crash.log` after a press on the menu button with the help file loaded (because I can't load anything else):
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 07/20/17-22:36:39

07/20/17-22:36:40 ERROR cannot open translation file: l10n/en_US/koreader.po
07/20/17-22:36:40 INFO  initializing for device Kindle4
07/20/17-22:36:40 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
07/20/17-22:36:41 INFO  opening file ./help/quickstart-en-v2015.11-1054-g6870bc2.html
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_66_Medium_Italic.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_67_Cond_Medium.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_68_Cond_Medium_Italic.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_75_Bold.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_76_Bold_Italic.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_77_Cond_Bold.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_78_Cond_Bold_Italic.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/KindleBlackboxBoldItalic.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/KindleBlackboxItalic.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/KindleBlackboxRegular.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Kindle_MonospacedSymbol.ttf>
07/20/17-22:36:41 ERROR failed to register crengine font cannot register font <./fonts/host/Kindle_Symbol.ttf>
07/20/17-22:36:41 INFO  Loading plugins from directory: plugins
07/20/17-22:36:41 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
07/20/17-22:36:41 INFO  Plugin  plugins/kobolight.koplugin/main.lua  has been disabled.
07/20/17-22:36:42 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
07/20/17-22:36:42 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
./luajit: frontend/device/kindle/device.lua:41: module 'liblipclua' not found:
	no field package.preload['liblipclua']
	no file 'common/liblipclua.lua'
	no file 'rocks/share/lua/5.1/liblipclua.lua'
	no file 'frontend/liblipclua.lua'
	no file './liblipclua.lua'
	no file '/usr/local/share/luajit-2.1.0-beta2/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua/init.lua'
	no file 'plugins/batterystat.koplugin/liblipclua.lua'
	no file 'plugins/calibrecompanion.koplugin/liblipclua.lua'
	no file 'plugins/evernote.koplugin/liblipclua.lua'
	no file 'plugins/goodreads.koplugin/liblipclua.lua'
	no file 'plugins/keepalive.koplugin/liblipclua.lua'
	no file 'plugins/kosync.koplugin/liblipclua.lua'
	no file 'plugins/newsdownloader.koplugin/liblipclua.lua'
	no file 'plugins/perceptionexpander.koplugin/liblipclua.lua'
	no file 'plugins/readtimer.koplugin/liblipclua.lua'
	no file 'plugins/statistics.koplugin/liblipclua.lua'
	no file 'plugins/systemstat.koplugin/liblipclua.lua'
	no file 'plugins/terminal.koplugin/liblipclua.lua'
	no file 'plugins/timesync.koplugin/liblipclua.lua'
	no file 'plugins/zsync.koplugin/liblipclua.lua'
	no file 'common/liblipclua.so'
	no file 'common/liblipclua.dll'
	no file '/usr/lib/lua/liblipclua.so'
	no file 'rocks/lib/lua/5.1/liblipclua.so'
	no file './liblipclua.so'
	no file '/usr/local/lib/lua/5.1/liblipclua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file 'plugins/batterystat.koplugin/lib/liblipclua.so'
	no file 'plugins/calibrecompanion.koplugin/lib/liblipclua.so'
	no file 'plugins/evernote.koplugin/lib/liblipclua.so'
	no file 'plugins/goodreads.koplugin/lib/liblipclua.so'
	no file 'plugins/keepalive.koplugin/lib/liblipclua.so'
	no file 'plugins/kosync.koplugin/lib/liblipclua.so'
	no file 'plugins/newsdownloader.koplugin/lib/liblipclua.so'
	no file 'plugins/perceptionexpander.koplugin/lib/liblipclua.so'
	no file 'plugins/readtimer.koplugin/lib/liblipclua.so'
	no file 'plugins/statistics.koplugin/lib/liblipclua.so'
	no file 'plugins/systemstat.koplugin/lib/liblipclua.so'
	no file 'plugins/terminal.koplugin/lib/liblipclua.so'
	no file 'plugins/timesync.koplugin/lib/liblipclua.so'
	no file 'plugins/zsync.koplugin/lib/liblipclua.so'
stack traceback:
	[C]: in function 'require'
	frontend/device/kindle/device.lua:41: in function 'isSpecialOffers'
	frontend/device/kindle/device.lua:63: in function 'supportsScreensaver'
	frontend/apps/reader/modules/readermenu.lua:137: in function 'setUpdateItemTable'
	frontend/apps/reader/modules/readermenu.lua:239: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/ui/uimanager.lua:446: in function 'sendEvent'
	frontend/ui/uimanager.lua:42: in function '__default__'
	frontend/ui/uimanager.lua:722: in function 'handleInput'
	frontend/ui/uimanager.lua:767: in function 'run'
	./reader.lua:193: in main chunk
	[C]: at 0x0000bef1
```

**Comment by Frenzie** [comment] 2017-07-20 20:52
Pinging @robert00s.

This looks like it's caused by #2757.

**Comment by robert00s** [comment] 2017-07-23 19:06
@GilDev 
I prepare patch. Please unzip attached file device.lua.zip and copy file device.lua to your device to folder koreader/frontend/device/kindle
Please make a copy of existing file device.lua before replace file. 
Let me know if the patch works or not :)
[device.lua.zip](https://github.com/koreader/koreader/files/1168323/device.lua.zip)

**Comment by GilDev** [comment] 2017-07-24 17:35
Here's what I get with the patch:

![Kindle](https://cl.ly/1K1h3H1s3812/IMG_20170724_192406.jpg)

The main menu does not have titles as you can see, but submenus do have them. Also it still does not start in the file manager when choosing to start from the file manager.
It would be great to make it work on K4NT, but anyway it seems that Koreader is just huge in size and slow to operate compared to Liberator, which does multi-format reading and PDF reflowing.

**Comment by Frenzie** [comment] 2017-07-24 18:26
Did you exit uncleanly? It'll show the quickstart guide on first run. However, the quickstart guide postdates the 20170308 build you previously mentioned.

**Comment by GilDev** [comment] 2017-07-24 20:16
My bad, it opens the file manager the next times. The problem is just those menu's items that does not show up.

**Comment by Frenzie** [comment] 2017-07-25 07:57
Looks like a known issue, see mainly #1623 but also #1898. I'll close this (as the main OP issue has been solved) to keep the issues somewhat organized. :-)

**Closed by Frenzie** 2017-07-25 07:57 UTC
Labels: bug, Kindle
