### ISSUE TITLE
Can't login to Evernote - OAuth verifier not found

### ISSUE THREAD

**Issue by wilsonrljr** [koreader/koreader#6281] opened 2020-06-18 21:51 UTC
* KOReader version: v2020.06
* Device: Kobo Aura HD

#### Issue
Can't login to Evernote. When I try to login I got the following error message:

An error occurred while loggin in: plugins/evernote.koplugin/EvernoteOAuth.lua:351: OAuth verifier not found.

I do not use 2fa.
#### Steps to reproduce
Open any Epub -> Access Evernote menu -> Login to Evernote  -> Insert user and password and click to login.

**Comment by Frenzie** [comment] 2020-06-19 18:45
Pinging @Galunid.

Possibly related to https://github.com/koreader/koreader/issues/6087 and https://github.com/koreader/evernote-sdk-lua/pull/2

**Comment by Galunid** [comment] 2020-06-19 19:34
@wilsonrljr Could you try logging in again?

I tried, but I cannot replicate. I don't think https://github.com/koreader/evernote-sdk-lua/pull/2 could cause this. This happens after user got logged in and that pull request didn't modify any code related to `OAuth:allowAccess()`.
```lua
  if code ~= 302 then
    error("Unexpected response status on allowing access", code)
  end

  local location = self:parseResponse(loc)

  if not location['oauth_verifier'] then
    error("OAuth verifier not found")
  end
```

So `code == 302`, meaning in theory that request was alright. I'll try to add more logging to `EvernoteOAuth.lua`, because it's pretty much impossible to tell what's happening.
Perhaps it's related to Evernote releasing a path https://status.evernote.com/ around that time?

**Comment by wilsonrljr** [comment] 2020-06-19 21:31
Thank you for pointing out. It's working now. I logged in and logged out several times to check if the error would happen again, but each time the login was successful. Next time I will wait a while until I am sure the problem is not on Evernote's side.

**Comment by stanvv** [comment] 2020-07-02 08:29
I currently have the exact same issue with my Kobo Clara HD. Freshly installed Koreader (v2020.06), but cannot login to Evernote: _plugins/evernote.koplugin/EvernoteOAuth.lua:351: OAuth verifier not found_, not using 2fa

**Comment by JohanCodinha** [comment] 2020-07-02 12:11
Same issue on Kobo h2o with Freshly installed Koreader (v2020.06)

**Comment by stanvv** [comment] 2020-07-02 14:34
> Same issue on Kobo h2o with Freshly installed Koreader (v2020.06)

Created #6342

**Comment by stanvv** [comment] 2020-07-02 17:46
> @wilsonrljr #6342  Were you using two-factor authentication before trying to use the plugin? In my case (#6281), I was using 2fa before and I disabled it to use Evernote plugin. I have this problem when I tried to login in the same day, but after waiting a while I managed to login normally.

No I did use SSO (with Gmail) but disabled that (basically changed the password). Also, I tried a different, work-related account (no 2FA nor SSO), but also that didn't work

**Comment by Galunid** [comment] 2020-07-04 17:37
I spend a few hours trying to fix that, but I failed miserably. Unless there is someone else interested in investigating, it probably won't be fixed anytime soon.

For anyone wanting to investigate:
* Error is caused because user is never logged in(only redirected to login page)
* https://github.com/koreader/evernote-sdk-lua/commit/45d81cf11588e3c8f1c517395dde706ef5979313 should be reverted(trying to login to `OAuth.action` results in user getting redirected to `Login.action`)
* additional parameters when sending log in request
* Something else I couldn't quite pinpoint, possibly cookies/headers

**Comment by Frenzie** [comment] 2020-07-07 20:45
@Galunid #1401 may point at something similar to cookies/headers, namely the encryption. See https://github.com/koreader/evernote-sdk-lua/compare/fe9267ff3f0d179763199849935117982f733360...23766a0083484c5452ac88b4b555526f31a0ab78

https://github.com/koreader/evernote-sdk-lua/blob/5267d2a6c2505a8c33d4b99fec526afd910a23bd/EvernoteOAuth.lua#L188

Also note that https://github.com/koreader/evernote-sdk-lua/blob/5267d2a6c2505a8c33d4b99fec526afd910a23bd/EvernoteOAuth.lua#L205-L207 can be simplified thanks to some improvements in the libraries used, see https://github.com/koreader/koreader/pull/6334 A potential failure that might be caused by that would be failing to execute a redirect on HTTPS for example.

**Comment by Galunid** [comment] 2020-07-08 00:13
@Frenzie Actually the failure to follow redirection may be possible. So far, all login requests failed with http code 418, which according to Wikipedia means "I'm a teapot" and was April fools joke, but that doesn't really tell me much 😂

**Comment by charleshan** [comment] 2020-07-10 19:47
Also happening on Kindle v2020.06

**Comment by OussaydBanz** [comment] 2020-07-14 23:41
Hi everyone, 
Also happening on my kobo aura one

**Comment by Weeping-Willows** [comment] 2020-07-28 16:05
Have the same issue on my Kobo Forma, when I try to login, I get this message:
An error occurred while logging in: plugins/evernote.koplugin/EvernoteOAuth.lua:332:OAuth verifier not found

**Comment by vrmneto** [comment] 2020-07-29 17:22
Hello everyone

The same problem is happening with my kobo aura

**Comment by abdrau26** [comment] 2020-08-17 18:08
Same problem is happening with my Kobo Clara HD.

**Comment by josegaert** [comment] 2020-09-06 22:01
Same problem on Kobo Aura H2O :-)

**Comment by yanndubois** [comment] 2020-10-22 19:24
I'm getting the same error on my kobo aura edition 2 with koreader newly installed.
"An error occurred while logging in: plugins/evernote.koplugin/EvernoteOAuth.lua:332 OAuth verifier not found"

**Comment by Galunid** [comment] 2021-08-31 14:42
Evernote plugin got replaced with Exported plugin

**Closed by Galunid** 2021-08-31 14:42 UTC
Labels: bug, Plugin, help-wanted

**Comment by etusa** [comment] 2021-09-06 14:15
Is there ANY method that works to extract notes and highlights?   When connecting my Nook Glowlight Plus 7.8"  by USB, I can get access only to the folders LOST.DIR, Android, NOOK, and .adobe-digital-editions

**Comment by Galunid** [comment] 2021-09-06 21:55
There is [KoHighlights](https://github.com/noembryo/KoHighlights), and you can still use exporter plugin (as only Evernote support was removed, and exporting highlights still works)
