### ISSUE TITLE
page number markup breaks style

### ISSUE THREAD

**Issue by cornelisbb** [koreader/koreader#7346] opened 2021-02-25 08:55 UTC
* KOReader version: 2021.02
* Device: Kobo Clara HD

#### Issue

A book with the following code for pagenumbers:

`<a id="page_viii"/>`

breaks the style. At that position a linebreak is inserted and the fontsize changes (visible when the default size is e.g. 0.8em, so I think the font-size in css is ignored). In the next paragraph everything is ok again.

BTW: in the margin the pagenumber is shown, although not always at the same height as `<a id="page_XXX">` is.

#### Steps to reproduce

An example paragraphf:

`<p class="indent">Some text <a id="page_XXX">More text over many line.</p>`

The alina breaks at the location of the page number.

**Comment by poire-z** [comment] 2021-02-25 09:14
Can't reproduce: <kbd>![image](https://user-images.githubusercontent.com/24273478/109129836-5a8a4700-7751-11eb-9265-bda745aef13d.png)</kbd>
Neither if I fix your sample and add a closing / : <kbd>![image](https://user-images.githubusercontent.com/24273478/109130501-164b7680-7752-11eb-8663-f52ff9c5b507.png)</kbd>

There's probably more styling by the publisher that you did not give - and these additional styles are probably the cause of the issue. So look at them, probably not a KOReader issue. And you can probably fix the publisher bad styling with style tweaks.

> BTW: in the margin the pagenumber is shown, although not always at the same height as <a id="page_XXX"> is.

Yes, probably unrelated, these page numbers come from some other information in the EPUB.

Also unrelated to your issue, but for context about these kind of tags: #6894

**Comment by cornelisbb** [comment] 2021-02-25 09:48
I have seen this in more than one book and there nothing special in the stylesheet, so I have looked further and tried to remove the page-template.xpgt. This solved this issue.

I have not problem with removing this file, but in case you want to take a look I paste the content below:

<ade:template xmlns="http://www.w3.org/1999/xhtml"
xmlns:ade="http://ns.adobe.com/2006/ade"
xmlns:fo="http://www.w3.org/1999/XSL/Format">
<fo:layout-master-set>
<fo:simple-page-master master-name="single_column">
<fo:region-body margin-bottom="1.25em" margin-top="1.25em"
margin-left="1.25em" margin-right="1.25em"/>
</fo:simple-page-master>
<fo:simple-page-master master-name="two_column"
margin-bottom="1.25em" margin-top="1.25em" margin-left="1.25em"
margin-right="1.25em">
<fo:region-body column-count="2"
column-gap="10pt"/>
</fo:simple-page-master>
<fo:simple-page-master master-name="two_column_head"
margin-bottom="1.25em" margin-top="1.25em" margin-left="1.25em"
margin-right="1.25em">
<fo:region-before extent="8.3em"/>
<fo:region-body column-count="2" column-gap="10pt"/>
</fo:simple-page-master>
<fo:simple-page-master master-name="three_column"
margin-bottom="1.25em" margin-top="1.25em" margin-left="1.25em"
margin-right="1.25em">
<fo:region-body column-count="3"
column-gap="10pt"/>
</fo:simple-page-master>
<fo:simple-page-master master-name="three_column_head"
margin-bottom="1.25em" margin-top="1.25em" margin-left="1.25em"
margin-right="1.25em">
<fo:region-before extent="8.3em"/>
<fo:region-body column-count="3" column-gap="10pt"/>
</fo:simple-page-master>
<fo:page-sequence-master>
<fo:repeatable-page-master-alternatives>
<fo:conditional-page-master-reference
master-reference="three_column_head" page-position="first"
ade:min-page-width="80em"/>
<fo:conditional-page-master-reference
master-reference="three_column" ade:min-page-width="80em"/>
<fo:conditional-page-master-reference
master-reference="two_column_head" page-position="first"
ade:min-page-width="50em"/>
<fo:conditional-page-master-reference
master-reference="two_column" ade:min-page-width="50em"/>
<fo:conditional-page-master-reference
master-reference="single_column"/>
</fo:repeatable-page-master-alternatives>
</fo:page-sequence-master>
</fo:layout-master-set><ade:style> <ade:styling-rule selector=".title_box"
display="adobe-other-region" adobe-region="xsl-region-before"/>
</ade:style>
</ade:template>

**Comment by cornelisbb** [comment] 2021-02-25 10:44
I tried to make a test document that shows the problem by adding above template, but it does not have that problem. I have no idea where to look. I have a work around, so if you want to close this as works for me, I am fine with that.

**Comment by poire-z** [comment] 2021-02-25 10:57
This template must have no effect on this, as KOReader would not even use/parse it.

> I have no idea where to look

Just for the sake of knowing, select some text from before to after the break, then `View HTML` (see https://github.com/koreader/koreader/issues/5925#issuecomment-596078631).
Screenshots what's around the `<A/>` and paste ie here.
Then, in the bottom, look at the single or multiple CSS files, and look for the class involved and the style they set.

Or share the book, encrypted if not free.

**Comment by cornelisbb** [comment] 2021-02-25 21:55
I could not find how to make a screenshot on the ereader, so I made a photo. After the page attribute I see that autoboxing is used. The part in autoboxing is the culprit. There the style is not applied.

If necessary I can send you the book privately.

![IMG_20210225_224820332](https://user-images.githubusercontent.com/23739544/109224627-81ca2e00-77bc-11eb-98dc-00ba39252621.jpg)

**Comment by cornelisbb** [comment] 2021-02-25 22:08
BTW: screenshot is from another book, that does not have a page-template.xpgt.

**Comment by poire-z** [comment] 2021-02-25 22:23
It seems the `<P>` is really closed after the `<A/>`, like if there was:
```html
<p class=indent> [...] kansel [...] waarom ik <a id=page23/></p>
geen college [...]
```
The `<autoBoxing>` you see is just crengine wrapping the inline text `geen college [...]` into an internal element that will be a block element (an anonymous block element), because this inline text needs a container.

I'd say there's really this unwelcom **< /p>**  after `<a id=page23/></p>` in your EPUB internal HTML file. I don't see any reason for the code to add it itself.

**Closed** 2021-02-25 22:56 UTC
