### ISSUE TITLE
Tolino Epos 2 warmth lights not working anymore

### ISSUE THREAD

**Issue by rola25** [koreader/koreader#12706] opened 2024-11-04 13:15 UTC
* KOReader version: latest dev
* Device: Tolino Epos 2
Device info:
Manufacturer: rakuten kobo inc.
Brand: rakutenkobo
Model: tolino
Device: ntx_6sl
Product: ntx_6sl
Hardware: e80k00
Platform: imx6

#### Issue
warmth lights were working, but on newest Dev-Builds it doesn't work anymore. Perhaps it has to do something with root access - in the first versions I was asked to "su" when starting koreader to access the warmth sysclass, but now it doesn't ask for root access anymore.

#### Steps to reproduce
Just install newest version and test

test.log:
Test logs:
11-04 14:07:52.875 I/EPD     ( 5611): Using Tolino/NTX driver
11-04 14:07:52.875 I/Lights  ( 5611): Using TolinoNTX driver
11-04 14:07:52.875 I/TolinoNtxController( 5611): loading libioctl
11-04 14:07:52.885 D/dalvikvm( 5611): Trying to load lib /data/app-lib/org.koreader.launcher-2/libioctl.so 0x410daf10
11-04 14:07:52.885 D/dalvikvm( 5611): Added shared lib /data/app-lib/org.koreader.launcher-2/libioctl.so 0x410daf10
11-04 14:07:52.885 D/dalvikvm( 5611): No JNI_OnLoad found in /data/app-lib/org.koreader.launcher-2/libioctl.so 0x410daf10, skipping init
11-04 14:07:52.885 E/EPD     ( 5611): java.lang.ClassNotFoundException: android.view.View$EINK_MODE
11-04 14:07:52.885 I/TolinoNtxController( 5611): loading libioctl
11-04 14:07:52.885 D/dalvikvm( 5611): Trying to load lib /data/app-lib/org.koreader.launcher-2/libioctl.so 0x410daf10
11-04 14:07:52.885 D/dalvikvm( 5611): Shared lib '/data/app-lib/org.koreader.launcher-2/libioctl.so' already loaded in same CL 0x410daf10
11-04 14:07:52.885 I/TolinoNtxNoWarmthController( 5611): loading libioctl
11-04 14:07:52.885 D/dalvikvm( 5611): Trying to load lib /data/app-lib/org.koreader.launcher-2/libioctl.so 0x410daf10
11-04 14:07:52.885 D/dalvikvm( 5611): Shared lib '/data/app-lib/org.koreader.launcher-2/libioctl.so' already loaded in same CL 0x410daf10
11-04 14:08:03.095 I/TestActivity( 5611): running lights test: Tolino Ntx
11-04 14:08:03.125 W/System.err( 5611): java.io.FileNotFoundException: /sys/class/backlight/lm3630a_led/color: open failed: ENOENT (No such file or directory)
11-04 14:08:03.125 W/System.err( 5611):         at libcore.io.IoBridge.open(IoBridge.java:409)
11-04 14:08:03.125 W/System.err( 5611):         at java.io.FileInputStream.<init>(FileInputStream.java:78)
11-04 14:08:03.125 W/System.err( 5611):         at kotlin.io.FilesKt.readText$default(SourceFile:17)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.extensions.FileExtensionsKt.read(SourceFile:6)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.device.lights.TolinoNtxController.getWarmth(SourceFile:19)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.dialog.LightDialog.show$lambda$2(SourceFile:30)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.dialog.LightDialog.$r8$lambda$J4GqmHdddi58UZKq9ZQpDiuP1AM(SourceFile:1)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.dialog.LightDialog$$ExternalSyntheticLambda2.run(SourceFile:1)
11-04 14:08:03.125 W/System.err( 5611):         at android.app.Activity.runOnUiThread(Activity.java:4713)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.dialog.LightDialog.show(SourceFile:64)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.TestActivity.runLights(SourceFile:119)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.TestActivity.onCreate$lambda$3(SourceFile:20)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.TestActivity.$r8$lambda$29Py-22IBFcDdjyZelGcPfGyIRM(SourceFile:1)
11-04 14:08:03.125 W/System.err( 5611):         at org.koreader.launcher.TestActivity$$ExternalSyntheticLambda0.onClick(SourceFile:1)
11-04 14:08:03.125 W/System.err( 5611):         at android.view.View.performClick(View.java:4666)
11-04 14:08:03.125 W/System.err( 5611):         at android.view.View$PerformClick.run(View.java:18925)
11-04 14:08:03.135 W/System.err( 5611):         at android.os.Handler.handleCallback(Handler.java:733)
11-04 14:08:03.135 W/System.err( 5611):         at android.os.Handler.dispatchMessage(Handler.java:95)
11-04 14:08:03.135 W/System.err( 5611):         at android.os.Looper.loop(Looper.java:136)
11-04 14:08:03.135 W/System.err( 5611):         at android.app.ActivityThread.main(ActivityThread.java:5017)
11-04 14:08:03.135 W/System.err( 5611):         at java.lang.reflect.Method.invokeNative(Native Method)
11-04 14:08:03.135 W/System.err( 5611):         at java.lang.reflect.Method.invoke(Method.java:515)
11-04 14:08:03.135 W/System.err( 5611):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
11-04 14:08:03.135 W/System.err( 5611):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
11-04 14:08:03.135 W/System.err( 5611):         at dalvik.system.NativeStart.main(Native Method)
11-04 14:08:03.135 W/System.err( 5611): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
11-04 14:08:03.135 W/System.err( 5611):         at libcore.io.Posix.open(Native Method)
11-04 14:08:03.135 W/System.err( 5611):         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
11-04 14:08:03.135 W/System.err( 5611):         at libcore.io.IoBridge.open(IoBridge.java:393)
11-04 14:08:03.135 W/System.err( 5611):         ... 24 more
11-04 14:08:05.495 V/Lights  ( 5611): Setting warmth to 6 of 10
11-04 14:08:05.495 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:08:05.525 V/Lights  ( 5611): Setting warmth to 5 of 10
11-04 14:08:05.525 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:08:07.065 V/Lights  ( 5611): Setting warmth to 4 of 10
11-04 14:08:07.075 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:08:07.125 V/Lights  ( 5611): Setting warmth to 5 of 10
11-04 14:08:07.125 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:08:07.265 V/Lights  ( 5611): Setting warmth to 6 of 10
11-04 14:08:07.265 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:08:09.125 V/Lights  ( 5611): Setting brightness to 69
11-04 14:08:09.195 V/Lights  ( 5611): Setting brightness to 74
11-04 14:08:09.265 V/Lights  ( 5611): Setting brightness to 88
11-04 14:08:09.325 V/Lights  ( 5611): Setting brightness to 103
11-04 14:08:09.395 V/Lights  ( 5611): Setting brightness to 114
11-04 14:08:09.465 V/Lights  ( 5611): Setting brightness to 121
11-04 14:08:09.535 V/Lights  ( 5611): Setting brightness to 124
11-04 14:08:09.595 V/Lights  ( 5611): Setting brightness to 125
11-04 14:08:09.725 V/Lights  ( 5611): Setting brightness to 122
11-04 14:08:09.795 V/Lights  ( 5611): Setting brightness to 109
11-04 14:08:09.865 V/Lights  ( 5611): Setting brightness to 93
11-04 14:08:09.925 V/Lights  ( 5611): Setting brightness to 85
11-04 14:08:09.995 V/Lights  ( 5611): Setting brightness to 82
11-04 14:08:10.325 V/Lights  ( 5611): Setting brightness to 84
11-04 14:08:10.395 V/Lights  ( 5611): Setting brightness to 89
11-04 14:08:10.485 V/Lights  ( 5611): Setting brightness to 95
11-04 14:08:10.535 V/Lights  ( 5611): Setting brightness to 97
11-04 14:08:10.595 V/Lights  ( 5611): Setting brightness to 98
11-04 14:08:10.665 V/Lights  ( 5611): Setting brightness to 99
11-04 14:08:16.315 V/Lights  ( 5611): Setting warmth to 5 of 10
11-04 14:08:16.315 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:08:16.465 V/Lights  ( 5611): Setting warmth to 4 of 10
11-04 14:08:16.465 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:11:36.925 V/Lights  ( 5611): Setting warmth to 6 of 10
11-04 14:11:36.925 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:11:50.625 I/TestActivity( 5611): running epd test: Freescale/NTX
11-04 14:11:50.625 I/EPD     ( 5611): requested eink refresh, type: 34 x:0 y:0 w:1440 h:1785
11-04 14:11:53.365 I/TestActivity( 5611): running lights test: Tolino Ntx
11-04 14:11:55.235 V/Lights  ( 5611): Setting warmth to 2 of 10
11-04 14:11:55.235 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0
11-04 14:11:55.315 V/Lights  ( 5611): Setting warmth to 3 of 10
11-04 14:11:55.315 V/TolinoNtxController( 5611): /dev/ntx_io: ioctl ok, code 0

**Comment by NiLuJe** [comment] 2024-11-04 13:36
> in the first versions

Which ones?

(Or, to put it another, what was the last version that you remember working, and what was the first version that you remember breaking).

**Comment by rola25** [comment] 2024-11-04 13:41
koreader-android-arm-v2024.07-73-gcafa9c825_2024-08-08.apk worked ... I think v2024.07-1xx ... didn't work anymore

**Comment by mergen3107** [comment] 2024-11-05 18:27
This log (from KOReader) won't help much.

You need `pidcat` logs after connecting with adb

**Comment by mergen3107** [comment] 2024-11-05 18:35
> * Model: tolino
>       Device: ntx_6sl
>       Product: ntx_6sl
>       Hardware: e80k00
>       Platform: imx6

I don't know why it worked before at all because driver doesn't even know about `e80k00`:
```
        // Tolino Epos 2 also have warmth lights
        TOLINO_EPOS = BRAND.contentEquals(STR_KOBO)
            && MODEL.contentEquals(STR_TOLINO)
            && DEVICE.contentEquals(STR_NTX)
            && !HARDWARE.contentEquals("e60k00")
            && !HARDWARE.contentEquals("e60q50")
            && !HARDWARE.contentEquals("e60qv0")
            && !HARDWARE.contentEquals("e70k00")
```

**Comment by pazos** [comment] 2024-11-05 18:38
Duplicate of https://github.com/koreader/koreader/issues/8482

Please, @rola25, follow instructions there and report back your device. Thanks!

**Closed by pazos** 2024-11-05 18:38 UTC
Labels: Android
