### ISSUE TITLE
Koreader crashes on Kobo when opening menu after opening book when wifi is on

### ISSUE THREAD

**Issue by matejdro** [koreader/koreader#7656] opened 2021-05-09 07:37 UTC
* KOReader version: 2021.04
* Device: Kobo Glo HD (kobo_alyssum)

#### Steps to reproduce

1. Ensure wifi is turned on
2. Open file browser
3. Open any book
4. Immediately after opening the book, try to open main menu (by swiping down from the top edge of the screen

BUG: Koreader crashes

![IMG_20210509_092943](https://user-images.githubusercontent.com/507922/117564011-0fbe7100-b0aa-11eb-9ead-b6f4f1a65691.jpg)

Issue does not appear to happen if either Wifi is off or if you turn a book page before opening menu.

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/6447094/crash.log)

**Comment by Frenzie** [comment] 2021-05-09 07:55
I can't confirm on my H2O (which I don't think should make a difference), but I'm running the latest nightly. Did you fix some kind of gesture detection @NiLuJe ?

**Comment by poire-z** [comment] 2021-05-09 09:51
Just a note that I occasionally (twice a month) get a stacktrace like this one, intersectWith/notintersectWith and one of the thing being nil, on my Kobo in normal usage, in various contexts that I can never reproduce :)
I also get some when developping on the emulator, but it always ends up being because of coding errors (but always hard to pinpoint), than I can then fix.

I wonder if we should make these checks more robust and survive being given a `nil` - or if we should keep them crashing like that to force us finding out the bugs...

**Comment by NiLuJe** [comment] 2021-05-09 16:07
IIRC, I may have reproduced this (or something like) on the H2O once, with the "restore Wi-Fi on startup" option, and said restoration taking a shitload of time (which is fairly evident as a white screen for a while). If you generate input events during that time, stuff is processed in a weird order when the Wi-Fi stuff is done.

**Comment by NiLuJe** [comment] 2021-05-09 16:08
Yeah, basically, anything that deals with a `dimen` field that gets tripped *before* the widget has been drawn (at which point dimen is either nil or bogus).

**Comment by NiLuJe** [comment] 2021-05-09 16:14
There are a couple of approaches:

* I just mangled the handler in FLWidget:

https://github.com/koreader/koreader/blob/master/frontend/ui/widget/frontlightwidget.lua#L629-L634

* Possibly better, something like what TouchMenu does probably makes the issue impossible:

https://github.com/koreader/koreader/blob/310151fac9b516c66ce3198abbae4c337252e6a2/frontend/ui/widget/touchmenu.lua#L439-L444

**Comment by NiLuJe** [comment] 2021-05-09 23:42
Can't reproduce either, FWIW. It's vaguely possible the RD/FM teardown/instantiations made a difference here, because I can't quite see how this could trip on an undrawn widget here.

**Comment by matejdro** [comment] 2021-05-10 16:40
I can still reproduce on the `v2021.04-55-g1dd300d_2021-05-09/ ` with same stacktrace (albeit version says just `2021.04` - is there a way I can verify that I'm really running nightly?)

**Comment by Frenzie** [comment] 2021-05-11 08:06
I misread that. Definitely what @NiLuJe says: if the about says 2021.04 then you're *not* running the nightly.

**Comment by matejdro** [comment] 2021-05-12 12:37
After actually doing it properly, I can confirm that `v2021.04-60-gde6f2e8_2021-05-11` does not have the crash anymore. Thanks for your help.

**Comment by matejdro** [comment] 2021-05-14 11:50
It happened again with the `v2021.04-60-gde6f2e8_2021-05-11`. Same steps, but I cannot reproduce reliably.

[crash.log](https://github.com/koreader/koreader/files/6478526/crash.log)

**Comment by NiLuJe** [comment] 2021-05-14 15:54
Wasn't supposed to be fixed in -60, and -69 showed that we'd missed another bit anyway ;).

(c.f., #7683)

**Comment by matejdro** [comment] 2021-05-14 15:56
Right, I was just answering https://github.com/koreader/koreader/issues/7656#issuecomment-835944756.

**Comment by Frenzie** [comment] 2021-05-18 18:44
I believe this was fixed in #7683.

**Closed by Frenzie** 2021-05-18 18:44 UTC
Labels: bug
