### ISSUE TITLE
A better help

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2684] opened 2017-03-27 09:00 UTC
* KOReader version: 894
* Device: independent

#### Issue

I was shocked when I opened "help" function for the first time just now.

I would suggest we can use a PDF file (one per language or one with major languages) to describe the basic operations of KOReader.
Once the KOReader is first started, we can display the PDF instead of opening the file manager. Or at least try to show the help file at the top of file manager by controlling the initial folder and default sorting order.

I also suggest to allow the user to select the preferred language during the first start.

**Comment by Frenzie** [comment] 2017-03-27 10:41
Duplicate of #1371 except for the suggestion to open the help document instead of the file manager on first start?

**Comment by Hzj-jie** [comment] 2017-03-27 15:22
Oh, I recall that we have discussed this before.

**Comment by KenMaltby** [comment] 2017-03-27 15:37
I remember bringing up a "dismissible" Quick Start message, on first start, once.  I think the discussion went into having an extraction of the WiKi available.

**Comment by Frenzie** [comment] 2017-04-01 15:09
Closing in favor of the other issue.

**Closed by Frenzie** 2017-04-01 15:09 UTC
