### ISSUE TITLE
App crashed and freezing PW4

### ISSUE THREAD

**Issue by idirizzo** [koreader/koreader#6187] opened 2020-05-25 15:34 UTC
* KOReader version:2020.05
* Device:PW4

#### Steps to reproduce
Open pdf book. 
change Letter size
Tap exit in main menu

##### `crash.log` (if applicable)
has been  added
[crash.log](https://github.com/koreader/koreader/files/4677889/crash.log)

**Comment by NiLuJe** [comment] 2020-05-25 15:39
Dupe of #6117

**Closed by NiLuJe** 2020-05-25 15:39 UTC
Labels: Kindle, bug, duplicate, firmware, help-wanted
