### ISSUE TITLE
Android menu doesn’t disappear on Kindle Fire 5th generation

### ISSUE THREAD

**Issue by jncrft** [koreader/koreader#4998] opened 2019-05-04 11:10 UTC
* KOReader version: 4.19 (2019.04-27-g7e06db9_2019-04-14
* Device: Kindle Fire 7 5th generation [Fire OS 5.3.6.4 (626533320)]

#### Issue 

Android Menu at bottom won’t go away if you leave the program and come back to it. 

#### Steps to reproduce
Open Koreader on the Fire.  Use either the home button (circle) or switch app button (square).  Open Koreader either using the icon on the home screen or the app switcher.  The menu will be at the bottom, blocking the contents of the book. To get it to go away, you have to close Koreader, then reopen.  In previous versions under advanced settings you could choose full screen, but I don’t see any way to edit the text file that used to be used.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by pazos** [comment] 2019-05-04 14:35
duplicate of #4996

**Closed by pazos** 2019-05-04 14:35 UTC
Labels: Android, bug, duplicate
