### ISSUE TITLE
click top can not open menu

### ISSUE THREAD

**Issue by longforus** [koreader/koreader#2890] opened 2017-05-13 16:33 UTC
* KOReader version:koreader-nightly-20170430
* Device:kobo glo

#### Issue
i update my kobo glo koreader(one year a go a version ,i can not remeber version number) to koreader-nightly-20170430  reboot ... install success...can look welcome, but click screen top can not open menu   my god, saveing me

**Comment by Frenzie** [comment] 2017-05-13 16:46
It has been changed to slide down. :-)

**Comment by longforus** [comment] 2017-05-13 17:49
oh ，I have not found，thank you，new version is cool，You are really great，:-)

**Comment by Frenzie** [comment] 2017-05-13 18:45
You're welcome, closing now.

**Comment by gerroon** [comment] 2017-05-14 17:04
Please give us an option to go back to old method. This new way of bringing top  menu is super frustrating in my experience.

**Comment by Frenzie** [comment] 2017-05-14 17:31
On which device?

**Comment by embryo10** [comment] 2017-05-14 17:41
Although it works OK with the Glo, I don't like swiping that much..
It would be nice to have the option to use the DTAP_ZONE_MENU method.

**Comment by Eduardomb22** [comment] 2017-05-14 22:22
Sometimes, on kindle, the slide down doesn´t work. But I prefer this method. Better to highlight some text at top

**Comment by gerroon** [comment] 2017-05-15 00:52
I am on Android and the experience of swiping to bring the top menu is not pleasant at all

- swiping also brings system's task bar

- swiping also moves the page (I use scrolling page)

**Comment by a-kohout** [comment] 2017-05-16 21:37
@gerroon You don't have to swipe from the top if you change `DTAP_ZONE_MENU` to be taller.
A short vertical swipe anywhere inside that zone will work.
Also, a vertical swipe inside the menu zone shouldn't scroll, at least it doesn't do that on Kobo devices or in the Emulator.
Is that different on Android?

**Comment by gerroon** [comment] 2017-05-16 22:18
@a-kohout 


Do you use "on"  for Scroll Mode? If it is a single page naurally you wont notice any scrolling.

**Comment by Frenzie** [comment] 2017-05-16 22:22
@houqp made the default scroll zone smaller, not sure why.

But yes, scroll mode on. It doesn't scroll in the top of the screen.

**Comment by gerroon** [comment] 2017-05-16 22:30
@Frenzie 

Is the scroll area biggernow? That might be the root cause of my suffering with this new feature.

**Comment by a-kohout** [comment] 2017-05-16 22:50
@gerroon Yes, with scroll mode on (both epub and pdf) there is no scrolling for vertical swipes inside the menu zone. Only outside the menu zone.

**Comment by gerroon** [comment] 2017-05-16 23:15
Ok I will try a recent version then. Thanks for the hard work guys.

**Comment by gerroon** [comment] 2017-05-16 23:57
I am sorry to say this but this swipe thing works like shit on my C67ML.

Two issues

- Swiping does not bring any menu at all. It tries to bring something but it does not, no menus are visible on the screen


-It still moves the page a bit.


Please bring the old version back ;(

**Comment by Frenzie** [comment] 2017-05-17 05:11
@gerroon I meant the DTAP_ZONE_MENU is smaller by default, but I didn't object because it didn't seem to make a difference.

It definitely sounds like a refresh issue given your new info.

**Comment by chrox** [comment] 2017-06-02 04:18
Closed via #2932.

**Closed by chrox** 2017-06-02 04:18 UTC
