### ISSUE TITLE
After update to 2020.02 my screen is full of vertical lines

### ISSUE THREAD

**Issue by lucasrato** [koreader/koreader#5929] opened 2020-03-07 21:54 UTC
* KOReader version: 2020.02
* Device: Kindle Paperwhite 4

#### Issue

After update, my screen is full of vertical lines, as if the screen is failing (it's not the screen, since outside the KOReader it functions normally)

#### Steps to reproduce

Just open the KOReader. When seeing images it's easier to see the lines. Also, when the screen is turned off, I put it to show reading statistics, the bars are full of squares, a bar segmented, or like several bars one besides the other, not a single, continuous bar

**Comment by Frenzie** [comment] 2020-03-07 21:59
Sounds like a duplicate of #5928.

**Comment by lucasrato** [comment] 2020-03-07 22:06
> Sounds like a duplicate of #5884.
> 
> Edited to correct issue reference. GH autocomplete must've played tricks on me.

Yes! Indeed. I was searching for it but could not find so I created one, should I delete it/close it? (I'm new to github)

**Comment by Frenzie** [comment] 2020-03-07 22:09
In that case I'll close it, yes.

**Closed by Frenzie** 2020-03-07 22:09 UTC
Labels: Kindle, duplicate
