### ISSUE TITLE
Kobo Libra not connecting to Wifi Cellular Hotspot with an apostrophe

### ISSUE THREAD

**Issue by davidvelosa** [koreader/koreader#8175] opened 2021-09-03 19:30 UTC
* KOReader version: 2021.7- 2021.8
* Device: Kobo Libra

#### Issue

First off, thanks for everything Koreader Team! The app has been very useful for me since I installed it :)

Normally at home I don't have any issue with the Wifi, but when I decide to take my Kobo out with me, I get the next prompts when trying to connect to my cellphone network. The hotspot Device is an iPhone 7, I tried with and without VPN (since I usually have it turned on). Any solutions? Thanks!!

![image](https://user-images.githubusercontent.com/78831040/132056488-ce4f570f-f9f8-46ef-bfcf-763404e4a010.png)

With VPN turned on:

![image](https://user-images.githubusercontent.com/78831040/132056772-102fb65a-25e3-49e4-8c5e-ae611ba93f8d.png)

#### Steps to reproduce

Turn on Cellular Hotspot in the phone. In the kobo, search for wifi, type password, and connect

**Comment by mergen3107** [comment] 2021-09-03 19:37
What if you rename your network? It looks like the apostrophe is replaced by a fallback, or something. Try to rename it having only letters.

**Comment by NiLuJe** [comment] 2021-09-03 19:57
I don't *think* the issue is necessarily linked to UTF-8 (c.f., #5912), but it certainly doesn't hurt to try.

We'll also going to have to look at the crash.log to possibly see what's happening.

It certainly works just fine with an Android AP over here ;).

**Comment by davidvelosa** [comment] 2021-09-03 20:27
>What if you rename your network? It looks like the apostrophe is replaced by a fallback, or something. Try to rename it having only letters.

Kinda worked, with the only issue now is that it got pretty much frozen and had to restart the whole thing, lol. now updating everything

>FWIW, It certainly works just fine with an Android AP over here ;).

Is this a calling form the Dark Side? D: hahaha

Crash log below
[crash.log](https://github.com/koreader/koreader/files/7108340/crash.log)

**Comment by Frenzie** [comment] 2021-09-03 20:54
I don't want to bother testing it right now, but I had no trouble connecting to my phone as a hotspot last month on my H2O.

**Comment by davidvelosa** [comment] 2021-09-03 21:21
Apparently part of the problem was the apostrophe, it connected now on regular Wifi and VPN, thanks! :)

**Comment by NiLuJe** [comment] 2021-09-03 22:49
Yeah, we don't really log lj-wpaclient failures, I think :/.

On the upside, there was a trivial crash in there ;p (#8176).

**Comment by Frenzie** [comment] 2024-01-04 14:51
Closing, should be fixed by #11089.

**Closed by Frenzie** 2024-01-04 14:51 UTC
