### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [koreader/koreader#7924] opened 2021-07-02 07:54 UTC
* KOReader version: v2021.06
* Device:

#### Issue

```
  git checkout -b <new-branch-name>

HEAD is now at fd78df59b0... Prepare for 1.1.1k release
Submodule 'boringssl' (https://boringssl.googlesource.com/boringssl) registered for path 'boringssl'
Submodule 'krb5' (https://github.com/krb5/krb5) registered for path 'krb5'
Submodule 'pyca.cryptography' (https://github.com/pyca/cryptography.git) registered for path 'pyca-cryptography'
Cloning into '/home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/build/git_checkout/openssl/boringssl'...
Cloning into '/home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/build/git_checkout/openssl/krb5'...
Cloning into '/home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/build/git_checkout/openssl/pyca-cryptography'...
Submodule path 'boringssl': checked out '2070f8ad9151dc8f3a73bffaa146b5e6937a583f'
Submodule path 'krb5': checked out '890ca2f401924cdcb88f493950b04700bbe52db3'
Submodule path 'pyca-cryptography': checked out '09403100de2f6f1cdd0d484dcb8e620f1c335c8f'
[ 37%] Performing patch step for 'openssl'
* Applying /home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/openssl-1.1.0j-parallel_install_fix.patch . . .
patching file Configurations/unix-Makefile.tmpl
Hunk #1 succeeded at 96 (offset 19 lines).
* Applying /home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/openssl-origin-rpath.patch . . .
patching file Configurations/shared-info.pl
* Applying /home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/openssl-gcc-4.9-stdatomic.patch . . .
patching file include/internal/refcount.h
patching file include/internal/tsan_assist.h
[ 50%] No update step for 'openssl'
[ 62%] Performing configure step for 'openssl'

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

target already defined - android-arm (offending arg: .2.4203891/platforms/android-14/arch-arm)
make[4]: *** [openssl-prefix/src/openssl-stamp/openssl-configure] Error 255
make[4]: Leaving directory `/home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/build/arm-linux-androideabi'
make[3]: *** [CMakeFiles/openssl.dir/all] Error 2
make[3]: Leaving directory `/home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/build/arm-linux-androideabi'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/build/arm-linux-androideabi'
make[1]: *** [/home/vagrant/build/org.koreader.launcher/base/thirdparty/openssl/build/arm-linux-androideabi/openssl-prefix/src/openssl/libssl.so] Error 2
make[1]: Leaving directory `/home/vagrant/build/org.koreader.launcher/base'
Makefile:81: recipe for target 'all' failed
make: *** [all] Error 2
```
https://monitor.f-droid.org/builds/log/org.koreader.launcher/8409

Could you please take a look? Thanks!

**Comment by Frenzie** [comment] 2021-07-02 08:11
Pinging @pazos Did you change anything about the Android build recently besides the flavor thing?

The error sounds like Android might need to be added over here, but if so you'd think it should've been an issue for over 7 years…
https://github.com/koreader/koreader-base/blob/844ef1103a2a9eb17e6a9c0d0fbbf069a6d65f76/Makefile.third#L574

**Comment by pazos** [comment] 2021-07-02 13:26
>  Did you change anything about the Android build recently besides the flavor thing?

Nope. And the last change in openssl happened 3 months ago: https://github.com/koreader/koreader-base/commit/1d04e18b8d71172c2783199717e46bba22caf850

I have no idea

**Comment by NiLuJe** [comment] 2021-07-02 18:56
OpenSSL's build system is a *very* special snowflake, so without an actual look at the error log (wherever it's hidden, I don't remember off the top of my head, but since this mimics autotools, it might be config.log), it's hard to say what's upsetting it.

**Comment by pazos** [comment] 2021-07-02 19:13
I cannot reproduce. I'm able to build a f-droid release just fine. Anyways building koreader-base should be exactly the same in all flavors.

Something fishy happens here. At least the build error is the same as in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9318.

**Comment by linsui** [comment] 2021-08-17 11:24
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9318#note_652827133 Please fix that. Thanks!

**Comment by Frenzie** [comment] 2021-08-17 11:27
Thanks for looking into it. :+1:

**Comment by Frenzie** [comment] 2021-08-18 08:16
Should be fixed by https://github.com/koreader/koreader/pull/8096 if I understood the above correctly.

**Comment by linsui** [comment] 2021-08-18 08:17
Thanks!

**Closed by Frenzie** 2021-08-18 08:16 UTC
Labels: Android, help-wanted
