### ISSUE TITLE
Error with latest ota

### ISSUE THREAD

**Issue by albare** [koreader/koreader#4437] opened 2018-12-31 14:32 UTC
When I try yo upgrade yo the latest versión. Versión  finished in "33" is an error and a message to delete the caché. No problem with previous updates. My device is kobo H2O.

**Comment by Frenzie** [comment] 2018-12-31 14:47
Duplicate of #4429. We'll see if it persists after regenerating in a few days. :-)

**Closed by Frenzie** 2018-12-31 14:47 UTC
