### ISSUE TITLE
Kindle Scribe Support

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11046] opened 2023-10-27 22:51 UTC
So there is the new JB for Kindles ≤ 5.16.2.1.1

https://www.mobileread.com/forums/showthread.php?t=356872

Say, if I were to get my hands on Kindle Scribe, will I be able to help you get it running KOReader? :D

**Comment by NiLuJe** [comment] 2023-10-27 23:31
Dupe of #11045

**Closed by NiLuJe** 2023-10-27 23:31 UTC
Labels: Kindle
