### ISSUE TITLE
Generating thumbnails in Mosaic view very slow on LikeBook Mimas

### ISSUE THREAD

**Issue by ScrambleTheRamble** [koreader/koreader#5378] opened 2019-09-14 14:58 UTC
* KOReader version: V2019.09.03
* Device: Boyue LikeBook Mimas

#### Issue
When using 'Mosaic with cover images and uploading a number of comics the UI becomes slow and building up the cover images take a very long time.

Opening a document while the thumbnails are still refreshing doesn't work.

#### Steps to reproduce
Copy a number of comics to the HOME folder en switch to Mosaic with cover images

####
Details on the comics:
These are epubs generated from .cbz files to the exact device resolution (1404x1872) with Kindle Comic Converter

**Comment by Frenzie** [comment] 2019-09-14 15:43
What do you mean by a very long time? It's expected that it might take a couple of seconds per document.

**Comment by ScrambleTheRamble** [comment] 2019-09-14 15:45
> What do you mean by a very long time? It's expected that it might take a couple of seconds per document.

I'm talking several minutes, I had to switch back to basic view because it didn't seem to complete.

**Comment by Frenzie** [comment] 2019-09-14 16:06
As an aside, many of the comics I have on Humble Bundle look better in PDF because they have vector text.

It must be a device-specific issue I'm afraid. I downloaded half a dozen CBZs to test and they all rendered their front page in about a second, and it was properly interrupted when I opened one of them.

Perhaps it could be related to the Android JIT issue that exists on some devices, but really most data is handled by the libraries in this case…

**Comment by poire-z** [comment] 2019-09-14 16:18
The opening of the books, to fetch their covers, is done by another process in the background.
Either they are taking 100% cpu (dunno if you can check that?), or the device or koreader is sleeping/suspended (try to make some touch/swipe events to make it focused and not sleeping, and see if the covers appear faster).
Does it work faster/better with covers from other documents? Or document with no cover at all (as they go thru the same process of opening the document to look inside).

**Comment by ScrambleTheRamble** [comment] 2019-09-14 18:15
@Frenzie 

These are CBZ's converted to epub (i used these on my Kobo Aura ONE), not CBZ's. 

@poire-z 
I didn't notice the same issue with covers for other epubs (mostly tech books), I think the issue is more related to the resolution of the cover images themselves or the fact that these are epubs generated with Kindle Comic Converter. I'll download them as .epubs from humble bundle & compare.

**Comment by ScrambleTheRamble** [comment] 2019-09-14 18:58
@poire-z 

So I just downloaded all the Red Sonja comics from the last Humble Bundle in epub and after about 5 minutes it still needs to generate 12 thumbnails and only 24 are done so far. Device isn't going to sleep and the native reader does it in a matter of seconds.

So I guess it's not a KCC issue

**Comment by poire-z** [comment] 2019-09-14 19:18
(cpu ? what if you make touch events?)

So, to discriminate between background extraction vs just the book opening, can you set File browser to be in classic mode (no more covers), and then:
- hold on such a book, View book cover : is it faster/same?
- open another book: does it open fast/slow?
- with that opened book: Hamburger menu>Book information>Cover image: tap to display: fast/slow?

**Comment by Frenzie** [comment] 2019-09-14 19:18
@ScrambleTheRamble EPUB or CBZ doesn't make much of a difference.

> I think the issue is more related to the resolution of the cover images

Not unless it was a lot more than that.

You can try without the plugin (classic mode it's called I think?) and see how "show cover" works out.

**Comment by ScrambleTheRamble** [comment] 2019-09-15 12:02
> (cpu ? what if you make touch events?)
> 
> So, to discriminate between background extraction vs just the book opening, can you set File browser to be in classic mode (no more covers), and then:
> 
>     * hold on such a book, View book cover : is it faster/same?

The same, the bigger the .epub the longer it takes and one specific one (dreadstar, hublebundle) that's 177mb took over a minute to display it's book information page. Once there it only took a second or 2 to display the cover imge
 
>     * open another book: does it open fast/slow?

Godzilla Kingdom of monsters vol 1 (humblebundle) is 53mb, took a few seconds to display the book information page. mere seconds to view cover. 
> 
>     * with that opened book: Hamburger menu>Book information>Cover image: tap to display: fast/slow?

Fast for both documents. Does Koreader scan the whole epub to display it's 'Book information' pane and does that get stored in a cache?

**Comment by poire-z** [comment] 2019-09-15 12:57
> open another book: does it open fast/slow?

I mean: really open such a book (without looking at book information), just to see the plain simple opening duration.
How fast does it open?
Then, from this book opened, open another SMALL book from History: does it open fast/slow? (when opening a new book, the cache of the previous book - if any - is saved - this may also take a while.)

For Book information, we open the document, but we exit the processing at the point we have all the metadata.

For the cover extraction, we do use an alternate cache:
https://github.com/koreader/koreader/blob/2a93e428a53b874e8b717be67f430aabbfafefce/plugins/coverbrowser.koplugin/bookinfomanager.lua#L324-L342
because it helps. Dunno if saving the cache to this after cover extraction may cause IO writes and some delay.

Any chance to share such a book (maybe not a super huge one, but one that exhibits a +10s delay, should be enough to profile on the emulator and see where some time is spent (or see there's no issue on the emulator, and it's a device issue).
Don't you have any other reader/android phone to check how these same books do on them?

**Comment by hugleo** [comment] 2019-09-19 00:36
I have a likebook Mars device and put 150 files generated with KCC in a folder. (not epub format. I recreate in cbz format just with some filters like black/white, resolution, looks nice). What I notice:
- If I set the option sort by percent - unopened first - loads slow but accepted. However sometimes takes longer and looks like something is frozen. Then I press a key and files start loading ok.
- If I set the option sort by file then files loads ok. 

maybe dup of #4916

**Comment by pazos** [comment] 2019-10-13 18:39
@hugleo @ScrambleTheRamble: if your host computer is linux or mac then the output of `adb shell cat /proc/cpuinfo | grep bogomips | uniq` would help to understand if it's a matter of cpu power or a matter of specific rom issues.

If your host os is windows or you are doing your things only on mobile attaching here the output of /proc/cpuinfo does the same thing.

I just got a tablet with (in theory) the same processor power than the Mars/Mimas and I don't see problems with mosaics, so a minimum test case would be useful as well.

**Comment by Frenzie** [comment] 2019-10-13 19:27
@pazos 

> I just got a tablet with (in theory) the same processor power than the Mars/Mimas and I don't see problems with mosaics, so a minimum test case would be useful as well.

And in any case my H2O (2014) and Sony Ericsson Xperia Ray (2011, but faster than H2O) should be anywhere from slightly to heaps and bounds slower than even the lowest low end 2018 device. CPU power simply can't be an issue except in the sense of improperly clocking back to a low power state. (But even the most conservative governor wouldn't do that…)

**Comment by hugleo** [comment] 2019-10-13 23:01
no bogomips:

hugleo@test:~$ adb shell cat /proc/cpuinfo | grep bogomips | uniq
hugleo@test:~$ adb shell cat /proc/cpuinfo 
processor	: 0
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 3

processor	: 1
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 3

processor	: 2
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 3

processor	: 3
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 3

processor	: 4
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 3

processor	: 5
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 3

processor	: 6
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 3

processor	: 7
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 3

Hardware	: rockchip,rk3368
Revision	: 0000
Serial		: e574de199afdf036

**Comment by hugleo** [comment] 2019-10-13 23:28
Note @pazos at least for me the cover is not the problem.

Any display mode loads ok here, including cover with metadata.

The problem happens just if I enable a sort algorithm that uses metadata (Sort by percent), then the process is slow.

**Comment by pazos** [comment] 2019-10-14 00:30
> The problem just happens if I enable a sort algorithm that uses metadata (Sort by percent), then the process is slow.

Ok, good to know!  :+1: 

BTW, please do notice #5488 and do a backup before update (because I know you store books outside primary storage). Also with this changes if you set the sd card as the primary partition KO will have RW permissions on the entire sd while you can still access to both storage via usb - mtp.

**Comment by pazos** [comment] 2020-02-07 16:06
Closing as non-reproducible. Probably a firmware limitation or whatever. A test case is still welcome.

**Closed by pazos** 2020-02-07 16:06 UTC
Labels: Android, firmware
