### ISSUE TITLE
FR: Please add natural light/warm light support for Nook Glowlight Plus 7.8

### ISSUE THREAD

**Issue by github-koreader-shalott** [koreader/koreader#6469] opened 2020-08-03 12:40 UTC
I would like to add warm light support for the 2019 Nook Glowlight Plus 7.8 (and probably Nook Glowlight 3).

These devices seem to use the same frontlight and wamlight settings as the Cervantes 4 (https://github.com/koreader/koreader/blob/master/frontend/device/cervantes/device.lua#L110) so it seems like this would be quick and straightforward.

I'm not familiar with this codebase, but I imagine that adding support comprises adding a minimal frontend/device/nook/device.lua skeleton and adding appropriate tests for the device-family and device to refer to it.

Please let me know how I can help with this effort (e.g., providing device identification strings, etc); or if someone is willing to help me get started, I can work on it myself.  (I'm an experienced developer, but have no experience with Android...)

Thanks.

**Comment by pazos** [comment] 2020-08-03 13:11
@github-koreader-shalott: we need to write a controller for your specific lights. See the two available at https://github.com/koreader/android-luajit-launcher/tree/master/app/src/org/koreader/launcher/device/lights.

Mainly you need to document a bit how the device works. Which values are written and where. I would suggest reading https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/device/lights/TolinoWarmthController.kt as the starting point.

It is a mix of two things: it uses System settings to write brightness and a su shell to write warmth. That's because on Tolinos the warmth setting is limited to system apps.
On your device things might be different. You can try starting KOReader -> settings -> screen -> screen timeout and see if all the settings are currently enabled. If they're not we might want to grant permissions first. All that is already implemented so it is easy.

**Comment by github-koreader-shalott** [comment] 2020-08-03 13:39
Thanks for the quick response, and I'll take a look at the files you mentioned.

As I mentioned, this device uses the exact same /sys/ files and values (for both regular white frontlight and red warm-light) as the Cervantes 4, and the same warm-light files/values as Kobo Clara HD, which are already supported, so my hope is that the same controller can be reused.

Thanks.

**Comment by pazos** [comment] 2020-08-03 15:39
> As I mentioned, this device uses the exact same /sys/ files and values (for both regular white frontlight and red warm-light) as the Cervantes 4, and the same warm-light files/values as Kobo Clara HD, which are already supported, so my hope is that the same controller can be reused.

That's exactly the Tolino Warmth Controller in my previous post. The thing is which permissions are required to perform the actions. As android processes run on a virtual machine they need to be allowed to perform certain tasks (or run as su).

In the case of tolinos WRITE_SETTINGS permissions is not needed (is already granted because the system doesn't expect 3rd party apps) and while there's an interface to to set warmth using system settings it is limited to system applications, so you need to run that as root. If things are equal on Nooks you can repurpose the same code by:

- identifying your device based on a few platform strings: https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/device/DeviceInfo.kt#L168-L171

- add it the new definition to https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/device/LightsFactory.kt#L14

**Comment by pazos** [comment] 2020-08-04 21:01
@github-koreader-shalott: I'm closing this ticket as a duplicate of #5364. I am subscribed to this issue so feel free to ask here any question you have. The reason for closing is the same as the original tickets. It won't be fixed. Just things with an API can be fixed. 

Of course as #5364 says, PRs are very welcome, but they need to be done by people with one of these (not enough android) devices.

**Closed by pazos** 2020-08-04 21:01 UTC
Labels: enhancement

**Comment by github-koreader-shalott** [comment] 2020-08-06 06:57
Ah, that makes a lot more sense now.  Thanks!  I'll see what I can do on this.
