### ISSUE TITLE
Crash when login evernote

### ISSUE THREAD

**Issue by whmzsu** [koreader/koreader#6637] opened 2020-09-07 02:22 UTC
* KOReader version:2020.8
* Device:Moan w7 eink reader (Android 8.1)

#### Issue
**Crash when login evernote (China or internation region)**
#### Steps to reproduce
**open setting -> evernote->login->enter usrname and password -> press login ->Crash**
##### `crash.log` (if applicable)

**Comment by Galunid** [comment] 2020-09-07 04:58
Does it actually crash, or just doesn't work? If it crashes, please provide `crash.log`. Possibly duplicate of #6281

**Comment by whmzsu** [comment] 2020-09-07 12:33
Because there no crash.log. So I get the error message  by adb logcat , attach below

09-07 20:31:22.106  1868  2253 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)
09-07 20:32:13.652  4061  4074 E KOReader: error: [string "dl.lua"]:41: error opening /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so: dlopen failed: library "liblualongnumber.so" not found
09-07 20:32:13.655  4061  4074 E KOReader: [NativeThread]: failed to run script: error loading module 'libluabpack' from file 'plugins/evernote.koplugin/lib/libluabpack.so':
09-07 20:32:13.655  4061  4074 E KOReader:      dlopen failed: library "liblualongnumber.so" not found
09-07 20:32:13.656  4061  4074 E KOReader: [NativeThread]: Stopping due to previous errors
09-07 20:32:13.718  1868  1933 E InputDispatcher: channel '817c2d7 org.koreader.launcher/org.koreader.launcher.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-07 20:32:13.719  1714  1794 E SurfaceFlinger: Failed to find layer (SurfaceView - org.koreader.launcher/org.koreader.launcher.MainActivity#0) in layer parent (no-parent).
09-07 20:32:13.719  1714  1794 E SurfaceFlinger: Failed to find layer (Background for - SurfaceView - org.koreader.launcher/org.koreader.launcher.MainActivity#0) in layer parent (no-parent).
09-07 20:32:20.500  1868  1968 E libsuspend: Error opening /sys/class/tp_class/tp_device/sleep_mode: Permission denied
09-07 20:32:21.095  1868  3970 E ActivityManager: Sending non-protected broadcast com.moan.openwifi from system 1970:com.android.systemui/u0a20 pkg com.android.systemui

**Comment by Frenzie** [comment] 2020-09-07 12:50
Duplicate of #5882.

**Closed by Frenzie** 2020-09-07 12:50 UTC
Labels: Android, bug
