### ISSUE TITLE
Save last read page on device poweroff

### ISSUE THREAD

**Issue by mwozny123** [koreader/koreader#2036] opened 2016-05-19 20:12 UTC
* KOReader version: stable, nightly
* Device: Pocketbook, Kobo, probably all non-Kindle devices

#### Issue
When device system's going for powersave shutdown, Koreader doesn't save last read page.
(Bug extracted from https://github.com/koreader/koreader/issues/1990)

#### Steps to reproduce
Do some reading progress, wait idle till (system's battery saving) will shutdown device. 
Startup device, start koreader, last reading page won't be restored.

**Comment by mwozny123** [comment] 2016-06-05 16:56
Maybe at least "Save button" ? 

Now to not loose reading progress I've to quit Koreader, (even though I want to go back to reading in couple minutes)

This is horrible - (non-Kindle) devices that don't have a hibernate (deep sleep) option.

**Comment by houqp** [comment] 2016-06-05 18:51
Kobo and pocketbook already have the code to saves settings before suspend: https://github.com/koreader/koreader/blob/master/frontend/device/generic/device.lua#L124

IIRC, you have a pocketbook? The problem here is the system shutsdown the device instead of putting it into suspend mode. I wonder if there is a event emitted with the poweroff action. Do you have ssh access to the device to help verify this?

A temporary workaround for this is to set DAUTO_SAVE_PAGING_COUNT (in `defaults.persistent.lua`) to 1 so KOReader saves the setting every time you do a page turn.

**Comment by mwozny123** [comment] 2016-06-07 18:44
Yes, I'm running Pocketbook 626.
Thanks for workaround I'll try that.

As you wanted I've just installed, configured the sshd ([pbsshd_1.3_fwv5](http://www.mobileread.com/forums/showthread.php?t=159636)) on my PB, and successfully established connection:)
Please write how I can check the event;)

**Comment by hurzl** [comment] 2016-06-08 05:07
If you don't close the file the bookmarks are not saved either. I just lost a bunch of bookmarks because koreader got hung in the "goto" dialog and I had to reset the device. Same happens when the battery goes low.

**Comment by houqp** [comment] 2016-06-08 17:40
@mwozny123 i will get back to you tonight, you probably need to run koreader in debug mode and dump the output to somewhere.

@hurzl are you able to reproduce the freeze? The `DAUTO_SAVE_PAGING_COUNT` will also save bookmark settings. Maybe we should save the bookmark settings immediately instead of waiting for page turn events.

**Comment by hurzl** [comment] 2016-06-08 18:54
No, I can't reproduce that. I think DAUTO_SAVE_PAGING_COUNT should be 1 by default?
And I have no "defaults.persistent.lua" file.

So I guess this setting in koreader/defaults.lua will be overwritten with the next update?

**Comment by houqp** [comment] 2016-06-09 17:26
@mwozny123 , do you have `nohup` command in your ssh? If so, could try running the following command in koreader folder?

```bash
nohup ./luajit reader.lua -d ./ > koreader.logs
```

Then do whatever is necessary to make the device auto shutdown. After reboot, paste the content of `koreader.logs` somewhere :)

**Comment by houqp** [comment] 2016-06-09 17:28
@mwozny123 do you happen to have strace command in your pocketbook by any chance?
@hurzl yes, anything in `defaults.lua` will be overwritten after update. You can manually create the `defaults.persistent.lua` file. By default, `DAUTO_SAVE_PAGING_COUNT` is set to 6.

**Comment by hurzl** [comment] 2016-06-09 17:54
> By default, DAUTO_SAVE_PAGING_COUNT is set to 6.

For me it was "nil"

**Comment by mwozny123** [comment] 2016-06-09 18:58
@hurzl I also had it set to "nil"

@houqp it wasn't easy - [pbsshd_1.3_fwv5](http://www.mobileread.com/forums/showthread.php?t=159636) seems to not to support ssh only sftp connections (at least I couldn't connect). I'd to install [pbterm](http://users.physik.fu-berlin.de/~jtt/PB/) which is terminal size is bigger than pb screen and cannot change:/

Here's the log:
[kor-shutd.txt](https://github.com/koreader/koreader/files/307698/kor-shutd.txt)
I'd open Koreader, selected option "start with last read document", opened history -> opened last read file, waited till shutdown.

If needed I can generate more for comparison;)

ps: yes, I do have strace in /bin ;)

**Comment by houqp** [comment] 2016-06-10 06:57
There is no interesting event code in the output, the news is I saw a "Power off time has come..." message, so there is definitely a power off event somewhere. By default, we only log keyboard and touch events, the power off event probably has its own type. So let's add one more debug line before running the command again:

Add the following line after this line https://github.com/koreader/koreader/blob/master/frontend/device/input.lua#L531:

```lua
DEBUG("raw ev", ev)
```

With this patch, please help run the same command again and paste the result here, thanks :)

**Comment by houqp** [comment] 2016-06-10 06:59
@hurzl, sorry may bad, I confused it with count of page turn before full refresh config. So yeah, this is disabled by default...

**Comment by mwozny123** [comment] 2016-06-10 17:35
New log. 
There're couple RAW EV logged:
[koreaderShutdown-RawEv.txt](https://github.com/koreader/koreader/files/309469/koreaderShutdown-RawEv.txt)

Hope this one will be better if not I could use _strace_ command.

**Comment by houqp** [comment] 2016-06-10 19:29
That's good enough, I cross verified with the header in their SDK, type 22 is the exit event type. So we found the shutdown event, thanks @mwozny123 !

**Comment by houqp** [comment] 2016-06-14 07:11
@mwozny123 can you give the patch in https://github.com/koreader/koreader/pull/2081/files a try?

**Comment by mwozny123** [comment] 2016-06-16 20:30
Hi houqp. Thanks for change, but unfortunately it didn't work for me:(

I turn off DAUTO_SAVE_PAGING_COUNT and applied your patch, but it doesn't store last read page at battery save the power off. 

Could you reopen this issue? 

Should I provide the log? 
The same way as last time?

**Comment by houqp** [comment] 2016-06-17 01:50
@mwozny123 yes, could you paste the new log here?

**Comment by mwozny123** [comment] 2016-06-17 07:21
Strange. I've just: 
- connected using wifi to check that patch is on place, 
- added Debug Raw Events
- disconnected, 
- started Koreader from console (with nohup option), 
- move 3 pages ahead 
and next time I opened the Koreader last read page was save, and I swear yesterday it wasn't (started from systems menu, not console). 

So I confirm that's working from console. Let me just do one more test to confirm that's working from system's menu.
For sure I noticed that bookmark isn't saved when started from system menu. 1) But your change is just about last read page right?

Anyway there's a stacktrace at the bottom of log file. 2)Is it ok, that's there?

Here's a log without debug Raw Events. 
[koreaderSHUTD2.txt](https://github.com/koreader/koreader/files/319897/koreaderSHUTD2.txt)
Here's a log with Debug Raw Events:
[koreaderSHUTD3raw.txt](https://github.com/koreader/koreader/files/319903/koreaderSHUTD3raw.txt)



3)Btw are those logs enough to see why it's not using Koreader book cover, after shutdown?

BR
Marcin

ps: DAUTO_SAVE_PAGING_COUNT saves last read page -1.

**Comment by mwozny123** [comment] 2016-06-17 09:24
I do confirm. 
Save last read page DON'T work when started "normal" from systems menu. 

Save read page DO works when koreader is Started that the  in debug mode :
nohup ./luajit reader.lua -d ./ > koreader.logs

**Comment by houqp** [comment] 2016-06-18 07:15
The stack trace at the end is an unrelated bug. According to the log, there is a `closing document` line at the end, which means reader settings are saved successfully. The bookmark setting should be saved with the page progress too. If that's not the case, it's a bug. Can you confirm this is the case?

I am not sure how it works when you launch it through system menu, does it simply run https://github.com/koreader/koreader/blob/master/platform/pocketbook/koreader.app? If so, could you change `./reader.lua "$args" > crash.log 2>&1` to `./reader.lua -d "$args" > crash.log 2>&1` and upload the `crash.log` here?

**Comment by mwozny123** [comment] 2016-06-18 11:02
Save works only when Koreader's started with "nohup". 
Yes, system menu starts koreader.app (there was no "nohup" option). 

(After you patching) If we could add nohup to Koreader commandline (at least for Pocketbook) :
>/bin/nohup ./reader.lua "$args" > crash.log 2>&1
problem will be solved/workarounded.

Here's a log without nohup:
[crash.log.txt](https://github.com/koreader/koreader/files/321701/crash.log.txt)
Strange that no raw event has been logged even thought I still have 'DEBUG("raw ev", ev)' in my input.lua

**Comment by houqp** [comment] 2016-06-19 07:15
This is very strange, I have no idea why it is missing the event if it's started from koreader.app :(

> (After you patching) If we could add nohup to Koreader commandline (at least for Pocketbook) :
>
> /bin/nohup ./reader.lua "$args" > crash.log 2>&1
> problem will be solved/workarounded.

So you actually tried adding nohup to koreader.app? If it works, then I don't mind adding this to the the code base.

**Comment by mwozny123** [comment] 2016-06-19 14:54
Well,  to be honest I was too fast with this solution proposal. 

I added "/bin/nohup" to line 36 koreader.app test it but it didn't work. 

Directly from console command when I run nearly the same command it works. 
The problem might be that it's a sub process from koreader.app script?

Maybe this should be logged with some other debug the option?

**Comment by mwozny123** [comment] 2016-06-19 15:10
I just wanted to say that maybe "nohup" option causes that koreader process instead of being e.g. Killed is rather "more gently" asked to "terminate"? 
Maybe we should use another way (without nohup) to check raw event? 

From the other hand I wouldn't mind to use a nohup, but I don't know how to add it correctly to koreader.app script.

**Comment by houqp** [comment] 2016-06-20 08:17
> The problem might be that it's a sub process from koreader.app script?

Could be, to test this, you can replace nohub with `exec`: `exec ./reader.lua "$args" > crash.log 2>&1`. 

`./reader.lua` should be the same as `./luajit ./reader.lua`. I am not familiar with pocketbook framework, so maybe we missed something. It's hard for me to experiment without an actual device :P 

I don't know why it is only able to receive the event when started directly from a ssh session.

**Comment by mwozny123** [comment] 2016-06-20 19:00
koreader.app change to:
>exec ./reader.lua "$args" > crash_exec.log 2>&1

neither save page worked.
Here's a log for this.
[crash_exec.log.txt](https://github.com/koreader/koreader/files/324053/crash_exec.log.txt)
**Does the raw event exists on poweroff ?**

I've noticed that when I change the book, book's saved, but reading progress not.

>I don't know why it is only able to receive the event when started directly from a ssh session.

I don't start koreader from ssh. I'd installed Pbterm and so I run Koreader directly from Pbterm commandline (or from System menu[koreader.app])  at Pocketbook device.
But I think I shouldn't make difference?
I only use sftp to collect logs.

I'd also tried such setting in koreader.app:
>exec /bin/nohup ./reader.lua "$args" > crash_exec_nohup.log 2>&1

Log:
[crash_exec_nohup.log.txt](https://github.com/koreader/koreader/files/324091/crash_exec_nohup.log.txt)
neither save page worked.

**Comment by houqp** [comment] 2016-06-21 09:09
So it has nothing to do with being the child process. I am running out of idea then. Could you attach the output of strace for running koreader with and without pbterm?

**Comment by mwozny123** [comment] 2016-06-23 06:52
Well, around half of the logs were from Koreader started from Pocketbook (system) menu (e.g. last one), but with some patches (e.g. nohup, raw event debug etc)

To make a clear log I've updated (using OTA) to latest nightly.

So I have a clean installed Koreader (without changes in koreader.app, and without raw event debug).
Here's the log:
[crash.log.txt](https://github.com/koreader/koreader/files/329323/crash.log.txt)

Later I'll again patch the raw event debug and attach log.
Btw should I also add '-d' for debug to koreader.app
`./reader.lua -d "$args" > crash.log 2>&1` ?

**Comment by houqp** [comment] 2016-06-23 06:59
The log you attached is not from strace, could you prepend the `strace -f` command to `./reader.lua` to get the strace output? I would like to see the output for when it's launched from system menu and from pbterm.

> Btw should I also add '-d' for debug to koreader.app

Yes, please always have -d turned on :)

**Comment by mwozny123** [comment] 2016-06-23 19:36
Sorry I overlooked "strace" command.
Here's a log:
[Uploading crash-strace-rawEv-sysMenu.txt…]()

**Comment by houqp** [comment] 2016-06-25 07:33
Select syscall got interrupted, i wonder if it's because of SIGINT/SIGTERM sent from the framework during shutdown. The child process we forked that runs the main loop of inkview definitely caught the shutdown event. The error message from the stack trace ` interrupted!` is from LuaJIT's interrupt handler, so time to figure out what's the best way to handle these signals manually in LuaJIT.

**Comment by houqp** [comment] 2016-06-26 01:09
@mwozny123 I made a custom build to test the signal handling code, could you give it a try? download link: http://sfpptp.houqp.me:7980/koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-485-gbfa4bcd.zip

As always, please run it `strace -f` + `-d`, thanks :)

**Comment by mwozny123** [comment] 2016-06-26 19:16
Great work @houqp :) 
I did a bookmark, highlight text, and turn pages and it was saved after power off:)


FYI There's some NULLs e.g.:
`select(6, [5], NULL, NULL, NULLiv_poweroff_timer pid=136`
I don't know if that's expected or not, so attaching full log:
[crash.log.txt](https://github.com/koreader/koreader/files/333756/crash.log.txt)
but as I did 2 quick tests it works as expected.

If I had found a problem I would let you know, but it looks good for me;) 
Many thanks @houqp :+1:  :)

**Comment by houqp** [comment] 2016-06-26 19:42
Thanks @mwozny123 for testing, those NULLs are indeed expected :)

**Closed** 2016-06-27 00:24 UTC
Labels: bug, PocketBook
