### ISSUE TITLE
Crash on Launch - Android 14, Pixel

### ISSUE THREAD

**Issue by drewbitt** [koreader/koreader#11017] opened 2023-10-17 02:41 UTC
* KOReader version: v2023.08 via F-Droid
* Device: Pixel 8 Pro 

#### Steps to reproduce

Install via F-Droid

Launch and give file access

Crash. Segmentation fault

<details>
  <summary>crash.log</summary>

```
--------- beginning of crash
10-16 22:34:11.817 F/libc    (29782): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x74a33cc114 in tid 29875 (Thread-18), pid 29782 (launcher.fdroid)
10-16 22:34:11.847 F/libc    (29782): FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x773b22d018)
10-16 22:34:11.847 F/libc    (29782): FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x773b22d018)
10-16 22:34:11.947 F/DEBUG   (29891): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-16 22:34:11.947 F/DEBUG   (29891): Build fingerprint: 'google/husky/husky:14/UD1A.230803.022/10683547:user/release-keys'
10-16 22:34:11.947 F/DEBUG   (29891): Revision: 'MP1.0'
10-16 22:34:11.947 F/DEBUG   (29891): ABI: 'arm64'
10-16 22:34:11.947 F/DEBUG   (29891): Timestamp: 2023-10-16 22:34:11.854826163-0400
10-16 22:34:11.947 F/DEBUG   (29891): Process uptime: 9s
10-16 22:34:11.947 F/DEBUG   (29891): Cmdline: org.koreader.launcher.fdroid
10-16 22:34:11.947 F/DEBUG   (29891): pid: 29782, tid: 29875, name: Thread-18  >>> org.koreader.launcher.fdroid <<<
10-16 22:34:11.947 F/DEBUG   (29891): uid: 10434
10-16 22:34:11.947 F/DEBUG   (29891): tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
10-16 22:34:11.947 F/DEBUG   (29891): pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
10-16 22:34:11.947 F/DEBUG   (29891): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x00000074a33cc114
10-16 22:34:11.947 F/DEBUG   (29891):     x0  00000074a33dca70  x1  0000000000001000  x2  0000000000000001  x3  000000748e98ba68
10-16 22:34:11.947 F/DEBUG   (29891):     x4  0000000000000190  x5  00000075ca5507bc  x6  0000000000000001  x7  0000007472a801b4
10-16 22:34:11.947 F/DEBUG   (29891):     x8  0000000000000000  x9  0000000000000001  x10 0000000000000002  x11 000000773c5ad000
10-16 22:34:11.947 F/DEBUG   (29891):     x12 00000000000026e9  x13 0000000000002d7b  x14 0000000000000018  x15 0000000000000000
10-16 22:34:11.947 F/DEBUG   (29891):     x16 000000773c141c00  x17 000000773c127310  x18 00000074244bc000  x19 0000000000000000
10-16 22:34:11.947 F/DEBUG   (29891):     x20 000000773c5ad6e4  x21 00000074a33dca70  x22 0000000000001000  x23 00000074a33cc114
10-16 22:34:11.947 F/DEBUG   (29891):     x24 000000773c5ad000  x25 0000000000007a70  x26 0000000000000b7e  x27 000000000000051a
10-16 22:34:11.947 F/DEBUG   (29891):     x28 0000000000007000  x29 000000748e98bad0
10-16 22:34:11.947 F/DEBUG   (29891):     lr  000000773c1298f4  sp  000000748e98baa0  pc  00000074a33cc114  pst 0000000080001800
10-16 22:34:11.947 F/DEBUG   (29891): 7 total frames
10-16 22:34:11.947 F/DEBUG   (29891): backtrace:
10-16 22:34:11.947 F/DEBUG   (29891):       #00 pc 00000074a33cc114  <unknown>
10-16 22:34:11.947 F/DEBUG   (29891):       #01 pc 00000000000da8f0  /apex/com.android.runtime/lib64/bionic/libc.so (__cxa_finalize+144) (BuildId: a017f07431ff6692304a0cae225962fb)
10-16 22:34:11.947 F/DEBUG   (29891):       #02 pc 00000000000cca98  /apex/com.android.runtime/lib64/bionic/libc.so (exit+24) (BuildId: a017f07431ff6692304a0cae225962fb)
10-16 22:34:11.947 F/DEBUG   (29891):       #03 pc 0000000000002400  /data/app/~~gopD2VKdvqQyp5A4ZU9boA==/org.koreader.launcher.fdroid-W72NF8ikM4StPIjAI1RoYw==/lib/arm64/libluajit-launcher.so (android_main+400) (BuildId: 62394393a8c9c06b0b089763c77cf3904c0579d0)
10-16 22:34:11.947 F/DEBUG   (29891):       #04 pc 0000000000003a2c  /data/app/~~gopD2VKdvqQyp5A4ZU9boA==/org.koreader.launcher.fdroid-W72NF8ikM4StPIjAI1RoYw==/lib/arm64/libluajit-launcher.so (BuildId: 62394393a8c9c06b0b089763c77cf3904c0579d0)
10-16 22:34:11.947 F/DEBUG   (29891):       #05 pc 00000000000d6ccc  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: a017f07431ff6692304a0cae225962fb)
10-16 22:34:11.947 F/DEBUG   (29891):       #06 pc 000000000006ab00  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: a017f07431ff6692304a0cae225962fb)

```
</details>

**Comment by NiLuJe** [comment] 2023-10-17 03:53
Dupe of #10998 & #11009 (this is fixed in current nightlies).

**Closed by NiLuJe** 2023-10-17 03:53 UTC
Labels: bug, Android, out-of-date, duplicate
