### ISSUE TITLE
If using the WebDav provided by Cloudreve, it prompts "Empty folder".

### ISSUE THREAD

**Issue by Xuyiyang23333** [koreader/koreader#8030] opened 2021-07-27 07:27 UTC
* KOReader version: v2021.05
* Device: sp9832w_1h10_gofu_osll

#### Issue

My device is "口袋阅" which is an Android E-Ink reader sold in China, but I don't know its English name...
[Cloudreve](https://github.com/cloudreve/Cloudreve) is an open source cloud drive program, I use it for my personal cloud drive. If using the WebDav provided by Cloudreve, it prompts "Empty folder".

#### Steps to reproduce

Cloud Storage > Add new Cloud storage > webdav > Input a WebDav server provided by Cloudreve

This is a test website... I've uploaded an epub ebook on it.
Address: https://pan.yxyy.top/dav
Username: test@test.test
Password: rf14H7Yiw62FccsYpN85zadHVZgrCQVJ

**Comment by pazos** [comment] 2021-07-27 10:52
Duplicate of https://github.com/koreader/koreader/issues/7331

**Closed** 2021-07-27 10:52 UTC
Labels: duplicate
