### ISSUE TITLE
FR: [Improving sorting options]

### ISSUE THREAD

**Issue by 0zd3m1r** [koreader/koreader#11078] opened 2023-11-05 06:28 UTC
Can options such as Author, Tag, Date marked etc. be added to sorting by?

Also, can search options be combined? For example, both sorting by author and sorting by name.

**Comment by Galunid** [comment] 2023-11-05 09:03
`Top menu -> 5th icon (magnifier) -> Calibre metadata search -> Browse by ...` is about the best we have (and it's unlikely to change in the near future). I tried to look up tickets where this was discussed in more detail, but I couldn't find them (not that they aren't there).

**Comment by 0zd3m1r** [comment] 2023-11-05 16:43
> `Top menu -> 5th icon (magnifier) -> Calibre metadata search -> Browse by ...` is about the best we have (and it's unlikely to change in the near future). I tried to look up tickets where this was discussed in more detail, but I couldn't find them (not that they aren't there).

What I was talking about was the library view. Thank you.

**Comment by Galunid** [comment] 2023-11-05 19:54
Duplicate of #8472

**Closed by Galunid** 2023-11-05 19:54 UTC
Labels: enhancement, duplicate
