### ISSUE TITLE
Pocketbook: add support for gsensor

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#9427] opened 2022-08-10 20:28 UTC
Currently not supported and there're no plans to add support for it. Patches welcome.

u/rkomar provided helpful info in https://www.mobileread.com/forums/showpost.php?p=4247548&postcount=451

**Comment by rjd22** [comment] 2022-08-20 15:58
@pazos I've been researching this for quite some time and weren't able to get it working yet. I requested more information from the PocketBook Dev's on how to work the API but haven't gotten a reply from them yet.

Hopefully I might figure it out with some more time but I've been at it for about 5 to 6 hours now with no results yet ^^".

**Comment by pazos** [comment] 2022-08-20 17:21
Hey, @rjd22. Did you read the mobileread post I linked?. It contains various hints. Those events need to be added to the [pocketbook event handler](https://github.com/koreader/koreader-base/blob/master/input/input-pocketbook.h#L146-L218)

I understand it is not possible to change orientation from KO itself but a change on pb while KO is in the background should forward those `EVT.ORIENTATION` to all running apps, including us.

**Comment by rjd22** [comment] 2022-08-20 17:42
@pazos I read the post. I actually tested if Koreader was receiving orientation change events by logging the events at the start of the event handling (so the raw events of pocketbook itself).

Sadly I was unable to see events happening in the raw log that had to do with orientation changes.

The reason I wanted to work with input events is that having to poll the gyroscope will cause the device to stay active and block the ability to auto-suspend. IMO auto-suspend is a way more important feature than the gyroscope so I don't want to introduce a feature that stops it from working.

Pocketbook development is still quite new for me any I'm really inexperienced with this kind of software for specific hardware development. So it might be that I'm doing something wrong that is causing me to not being able to log these events. 

If someone is able to log them in Koreader and can give me a sample of the code, I'm willing to do the work to make the gyroscope work.

**Comment by rjd22** [comment] 2022-12-03 13:23
I want to further research this so I don't hope you mind me pinging you @pazos & @NiLuJe since you know a little more about the base KoReader internals. At this moment I want to start making the needed code to listen for the `EVT_ORIENTATION` pocketbook event.

I tried adding a debug statement on the following line (https://github.com/koreader/koreader-base/blob/master/ffi/input_pocketbook.lua#L49) to see if the event came along but didn't see it sadly.

Of course it might be that more supporting code is needed somewhere upstream like in the `input-pocketbook.h` but since I'm still learning I'm not sure if I'm looking at the right parts of code and what the recommended way it to make changes to the .h library and testing the changes.

Would you be willing to help me to get started on figuring out if the events are thrown and where this would start?

**Comment by NiLuJe** [comment] 2022-12-03 19:04
> input-pocketbook.h

Is no longer being used anywhere, unless you remove a global env that's set... I don't even remember where ;o).

**Comment by NiLuJe** [comment] 2022-12-03 19:08
I have no idea if we do any of this in the non-raw-input codepaths, for example: https://github.com/koreader/koreader-base/blob/c21be4047366dc6f72ecbc2b07eeb1f9342fcac7/ffi/input_pocketbook.lua#L141-L147 (and I'm in no position to check atm).

**Comment by rjd22** [comment] 2022-12-03 19:34
> > input-pocketbook.h
> 
> Is no longer being used anywhere, unless you remove a global var that's set... I don't even remember where ;o).

Hmm, do you know where I would need to start to debug to catch all input events?

**Comment by rjd22** [comment] 2022-12-03 20:33
After further looking it seems that events are indeed handled by attaching a event listener to Inkview main. I actually also found your global and the helpful comment of most likely @ezdiy .

The flag and the comment can be found here:

https://github.com/koreader/koreader/blob/f953f041eaf381fcf8986d2853d42027ad0e622c/frontend/device/pocketbook/device.lua#L16
https://github.com/koreader/koreader/blob/f953f041eaf381fcf8986d2853d42027ad0e622c/frontend/device/pocketbook/device.lua#L233

The switch is found here:
https://github.com/koreader/koreader-base/blob/c9555f7fdda737fd6970425d237174073d67d054/ffi/input.lua#L11

**Comment by rjd22** [comment] 2022-12-09 10:54
I got a answer from pocketbook that they know of the regression and a fix is incoming:

```
Dear Robert-Jan de Dreu,

Thank you for choosing PocketBook.
​
​Yes, that is a gap in inkview library, it doesn’t send this event to third-party apps,  we will fix it in the nearest firmware update. It will be done in firmware 6.7. We can send you a beta version of firmware 6.7 for testing. For what model do you need a beta version of 6.7 for testing?
```

**Comment by NiLuJe** [comment] 2022-12-09 14:41
Well, that's nice!

**Closed** 2022-12-23 18:25 UTC
Labels: enhancement, PocketBook
