### ISSUE TITLE
[kindle] Gray background in some widgets

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#3631] opened 2018-01-27 11:45 UTC
* KOReader version: after upgrade MuPDF to 1.12
* Device: Kindle PW3

#### Issue
On Kindle devices after upgrading MuPDF to 1.12 some widgets have gray background instead of transparent.
Widgets with problems: 
- Button widget with image
- Wikipedia widget

whole text and images are on gray background:
![img_20180127_122944791](https://user-images.githubusercontent.com/22982594/35471643-7d02657e-035f-11e8-9590-a58ab1840441.jpg)

Bottom button (prev/next/last/first):
![img_20180127_123050289](https://user-images.githubusercontent.com/22982594/35471653-9fc21898-035f-11e8-9c71-70340ca8c5a0.jpg)

**Comment by Frenzie** [comment] 2018-01-27 12:13
Likely a duplicate of https://github.com/koreader/koreader/issues/2606 (i.e., the same root cause)

**Comment by poire-z** [comment] 2018-01-27 12:24
Do you see it also on wikipedia intros when there is no image (we use a BB8 when no image, BBRGB32 when image)?
Can't see it on kobo, the emulator or android. So is this really kindle specific?
Could be kindle uses a RGB32 framebuffer bb, and we are blitting to out bbs that have some bad/undefinied alpha value, and Kindle would (unlike all other devices) somehow respects the alpha value, blending the bb on its own grey/black background?

**Comment by poire-z** [comment] 2018-01-27 12:38
Could you try this simple patch on your kindle, and check if it changes anything on the wikipedia with images case:
```lua
--- a/frontend/ui/widget/textboxwidget.lua
+++ b/frontend/ui/widget/textboxwidget.lua
@@ -336,7 +336,11 @@ function TextBoxWidget:_renderText(start_row_idx, end_row_idx)
         bbtype = Blitbuffer.TYPE_BBRGB32
     end
     self._bb = Blitbuffer.new(self.width, h, bbtype)
+  if bbtype == Blitbuffer.TYPE_BBRGB32 then
+    self._bb:fill(Blitbuffer.ColorRGB32(0xFF, 0xFF, 0xFF, 0xFF))
+  else
     self._bb:fill(Blitbuffer.COLOR_WHITE)
+  end
     local y = font_height
     for i = start_row_idx, end_row_idx do
         local line = self.vertical_string_list[i]
```
(if it gets better, tweak the last 0xFF to 0xcc, 0x88, just to see if that's this alpha value that is the cause of the grey background).

**Comment by robert00s** [comment] 2018-01-27 13:34
Unfortunately, no changes :(

**Comment by poire-z** [comment] 2018-01-27 13:35
Do you see it also on wikipedia intros when there is no image?

**Comment by robert00s** [comment] 2018-01-27 13:49
There is white background when there is no image so it is good.

**Comment by robert00s** [comment] 2018-01-27 13:54
I also notice that when this line 
https://github.com/koreader/koreader/blob/1e9457c9b408163126fdf59ecbbbd0acee06fffb/frontend/ui/widget/button.lua#L63
change to `false` the problem with gray background disappears. But of course buttons are smaller on my kindle

**Comment by robert00s** [comment] 2018-01-27 14:34
This may be problem with this function
https://github.com/koreader/koreader/blob/b16c93bbe50c72130ef84b5bd508404c10f8426a/frontend/ui/widget/imagewidget.lua#L165
but I'm not sure and have no idea how to fix it :(

**Comment by poire-z** [comment] 2018-01-27 14:50
Another patch to try (the chevron icons go thru this), just to pinpoint the problem:
```lua
--- a/ffi/mupdf.lua
+++ b/ffi/mupdf.lua
@@ -725,6 +725,7 @@ function mupdf.scaleBlitBuffer(bb, width, height)
         -- get corrupted if we blit them to a TYPE_BB8A, but are fine
         -- when blited to a TYPE_BBRGB32)
         converted_bb = BlitBuffer.new(orig_w, orig_h, BlitBuffer.TYPE_BBRGB32)
+        converted_bb:fill(BlitBuffer.ColorRGB32(0xFF, 0xFF, 0xFF, 0xFF))
         converted_bb:blitFrom(bb, 0, 0, 0, 0, orig_w, orig_h)
         bb = converted_bb -- we don't free() the provided bb, but we'll have to free our converted_bb
         colorspace = M.fz_device_rgb(context())
```
And another:
```lua
--- a/ffi/mupdf.lua
+++ b/ffi/mupdf.lua
@@ -725,7 +725,7 @@ function mupdf.scaleBlitBuffer(bb, width, height)
         -- get corrupted if we blit them to a TYPE_BB8A, but are fine
         -- when blited to a TYPE_BBRGB32)
         converted_bb = BlitBuffer.new(orig_w, orig_h, BlitBuffer.TYPE_BBRGB32)
-        converted_bb:blitFrom(bb, 0, 0, 0, 0, orig_w, orig_h)
+        converted_bb:alphablitFrom(bb, 0, 0, 0, 0, orig_w, orig_h)
         bb = converted_bb -- we don't free() the provided bb, but we'll have to free our converted_bb
         colorspace = M.fz_device_rgb(context())
         stride = orig_w * 4
```
And a 3rd: these 2 combined :)
```
--- a/ffi/mupdf.lua
+++ b/ffi/mupdf.lua
@@ -725,7 +725,8 @@ function mupdf.scaleBlitBuffer(bb, width, height)
         -- get corrupted if we blit them to a TYPE_BB8A, but are fine
         -- when blited to a TYPE_BBRGB32)
         converted_bb = BlitBuffer.new(orig_w, orig_h, BlitBuffer.TYPE_BBRGB32)
-        converted_bb:blitFrom(bb, 0, 0, 0, 0, orig_w, orig_h)
+        converted_bb:fill(BlitBuffer.ColorRGB32(0xFF, 0xFF, 0xFF, 0xFF))
+        converted_bb:alphablitFrom(bb, 0, 0, 0, 0, orig_w, orig_h)
         bb = converted_bb -- we don't free() the provided bb, but we'll have to free our converted_bb
         colorspace = M.fz_device_rgb(context())
         stride = orig_w * 4
```

**Comment by robert00s** [comment] 2018-01-27 18:48
@poire-z Thanks but unfortunately, no option helps :(

**Comment by poire-z** [comment] 2018-01-27 19:10
OK...
Could you (again) check:
- if you have this grey background with HTML dicts (if you have some - otherwise just temporarily change `sametypesequence=x` to `sametypesequence=h` in one of yours). The bb is directly given by MuPDF.
- on wikipedia pages, do you have this grey background for all images? or are there some pages with images that have proper whitebackground (depending of the image format or greyscale, we/Mupdf use/give different bbtype - check for country pages with flags, ancient personalities with greyscale pictures...), so if you sometimes get white background with some images, that would point to something (if yes, please give some sample wikipedia urls for both kind, and screenshot so i can see which images were displayed).

Also, do the above checks (and look at the chevrons - and book pages and other stuff, if things get worse) with this patch:
```lua
--- a/frontend/device/kindle/device.lua
+++ b/frontend/device/kindle/device.lua
@@ -20,6 +20,7 @@ end
 local Kindle = Generic:new{
     model = "Kindle",
     isKindle = yes,
+    hasColorScreen = yes,
 }

 function Kindle:initNetworkManager(NetworkMgr)

```

**Comment by robert00s** [comment] 2018-01-27 19:44
I don't have HTML dicts so I can't check that.
On Wikipedia pages I have grey background on all pages with images (I check about 100 examples). When pages are without pictures background is white.

After changing to
`hasColorScreen = yes`
I have still grey background at the chevrons. Book pages now are grey too :(

**Comment by poire-z** [comment] 2018-01-27 20:20
> Book pages now are grey too :(

OK, that's a hint!
With color enabled, we draw all book pages to a >8bits bb, just like we do for images (even when not color screen).
Do you get grey pages with all document formats? Because they each use a different kind of bb as their rendering destination:
- cre (epub): BBRGB16
- djvu: BBRGB24
- pdf: BBRGB32

Which have grey background and which have white (with `hasColorScreen = yes`)?

It will be hard to not use RGB32 for images, as it solves many problems.
I guess it's the final blitting to the kindle bb that will need something. May be it's just a matter of changing its bb format.
Could you see what this prints in your crash.log:
```lua
--- a/ffi/framebuffer_linux.lua
+++ b/ffi/framebuffer_linux.lua
@@ -108,6 +108,7 @@ function framebuffer:init()
                            0)
     assert(tonumber(ffi.cast("intptr_t", self.data)) ~= ffi.C.MAP_FAILED,
            "can not mmap() framebuffer")
+    print("vinfo.bits_per_pixel: "..vinfo.bits_per_pixel)
     if vinfo.bits_per_pixel == 32 then
         self.bb = BB.new(vinfo.xres, vinfo.yres, BB.TYPE_BBRGB32, self.data, finfo.line_length)
     elseif vinfo.bits_per_pixel == 16 then
```
(I get 16 on my Kobo, and I thought it was using BB8...)

If you get 8, could you try changing `TYPE_BB8` to `TYPE_BB8A` in:
```lua
    elseif vinfo.bits_per_pixel == 8 then
        self.bb = BB.new(vinfo.xres, vinfo.yres, BB.TYPE_BB8, self.data, finfo.line_length)
```
(dunno what this will do, it may crash)

**Comment by poire-z** [comment] 2018-01-27 21:14
Thanks.
That could explain why you see that on your kindle (8bits) and me not on my kobo (16bits), and that it's some RGBnn > BB8 conversion that is to be looked at.
Can't see on your pictures, but is the background still grey with the terrible TYPE_BB8A ?

It's strange you only see it these days. Are you sure you never had that before you upgraded to a nightly with MuPDF 1.12 (that you only did recently then? - or could it be some other commit since then? I think I did a few bb/imagewidget tweaks since MuPDF 1.12).
No kindle firmware upgrade could have triggered that?
Strange too that nobody else reported that before.

**Comment by poire-z** [comment] 2018-01-27 23:56
When I put in reader.lua (just after `require("setupkoenv")`):
```lua
bb = require("ffi/blitbuffer")
for _, z in pairs({
    bb.ColorRGB32(0xFF, 0xFF, 0xFF, 0xFF),
    bb.ColorRGB24(0xFF, 0xFF, 0xFF),
    bb.ColorRGB16(0xFFFF),
    bb.Color8A(0xFF, 0xFF),
    bb.Color8(0xFF),
}) do

print(z)
print(z:getColor8())
print(z:getColor8A())
print(z:getColorRGB16())
print(z:getColorRGB24())
print(z:getColorRGB32())
print("")
end
exit()
```
I get:
```
ColorRGB32(255, 255, 255, 255)
Color8(254)         so RGB32 => 8 is bad
Color8A(254, 255)         so RGB32 => 8A is bad
ColorRGB16(255, 255, 255)
ColorRGB24(255, 255, 255)
ColorRGB32(255, 255, 255, 255)

ColorRGB24(255, 255, 255)
Color8(254)         so RGB24 => 8 is bad
Color8A(254, 0)         so RGB24 => 8A is bad
ColorRGB16(255, 255, 255)
ColorRGB24(255, 255, 255)
ColorRGB32(255, 255, 255, 255)

ColorRGB16(255, 255, 255)
Color8(250)         so RGB16 => 8 is really bad
Color8A(250, 0)         so RGB16 => 8A is really bad
ColorRGB16(255, 255, 255)
ColorRGB24(255, 255, 255)
ColorRGB32(255, 255, 255, 255)

Color8A(255, 255)
Color8(255)
Color8A(255, 255)
ColorRGB16(255, 255, 255)
ColorRGB24(255, 255, 255)
ColorRGB32(255, 255, 255, 255)

Color8(255)
Color8(255)
Color8A(255, 0)
ColorRGB16(255, 255, 255)
ColorRGB24(255, 255, 255)
ColorRGB32(255, 255, 255, 255)
```
Can you confirm the grey background tou get is really this 254/0xFE, by changing in some widget (for example skimtowidget): `background = Blitbuffer.COLOR_WHITE` to `background = Blitbuffer. Color8(0xFE)`

**Comment by robert00s** [comment] 2018-01-28 11:55
Fantastic. Now it's working :)
After this change 
`return Color8(rshift(4898*self:getR() + 9618*self:getG() + 1869*self:getB(), 14))`
I have white background in all places on Kindle (chevron icons, buttons with icons, wikipedia with images etc).
Many thanks @poire-z.

**Comment by poire-z** [comment] 2018-01-28 13:20
Good :)
We might as well fix the RGB16 > BB8 conversion (`Color8(rshift(39190*r + 38469*g + 14942*b, 14))`)
```python
>>> def c(r,g,b): print (39190*r + 38469*g + 14942*b) >> 14
>>> c(31,63,31) # = white in rgb16
250

>>> 1.0*(255<<14) / (39190*31 + 38469*63 + 14942*31)
1.018597687412276
>>> 39190*1.018597687412276
39918.84336968709
>>> 38469*1.018597687412276
39184.434437062846
>>> 14942*1.018597687412276
15219.886645314227

>>> def c(r,g,b): print (39919*r + 39185*g + 15220*b) >> 14
>>> c(31,63,31)
255
>>> c(31,63,30)
254
>>> c(31,62,31)
252
>>> c(30,63,31)
252
# so, we don't get real white when 1 bit is off in any channel
>>> c(0,0,0) # black stays black
0
```
Just to confirm this is good, could you again enable `hasColorScreen = yes`, open an epub and confirm you have again a grey background (should be darker than the one you got with images and wikipedia).

And, change this (this patch includes the above RGB32 fix, you just need to change the fist -/+):
```lua
--- a/ffi/blitbuffer.lua
+++ b/ffi/blitbuffer.lua
@@ -281,10 +281,10 @@ function ColorRGB16_mt.__index:getColor8()
     local r = rshift(self.v, 11)
     local g = band(rshift(self.v, 5), 0x3F)
     local b = band(self.v, 0x001F)
-    return Color8(rshift(39190*r + 38469*g + 14942*b, 14))
+    return Color8(rshift(39919*r + 39185*g + 15220*b, 14))
 end
 function ColorRGB24_mt.__index:getColor8()
-    return Color8(rshift(4897*self:getR() + 9617*self:getG() + 1868*self:getB(), 14))
+    return Color8(rshift(4898*self:getR() + 9618*self:getG() + 1869*self:getB(), 14))
 end
 ColorRGB32_mt.__index.getColor8 = ColorRGB24_mt.__index.getColor8

```

**Comment by robert00s** [comment] 2018-01-28 13:49
When I enable `hasColorScreen = yes` background in epub is grey. After your patch 
`return Color8(rshift(39919*r + 39185*g + 15220*b, 14))` 
background is again white :)
So your patch works perfectly.

**Closed** 2018-01-28 20:01 UTC
Labels: Kindle, bug
