### ISSUE TITLE
Locks up when looking up certain words

### ISSUE THREAD

**Issue by emacsomancer** [koreader/koreader#3013] opened 2017-07-18 16:00 UTC
* KOReader version: latest for Kobo Aura HD
* Device: Kobo Aura HD

#### Issue
When I highlight the word 'ring' in a book, everything locks up and I have to long hold the toggle to force restart.  I was able to highlight other words without this issue.  (I'm using the Oxford English Dictionary, 2nd edn. if that makes a difference.) I tried three times and had exactly the same behaviour (i.e. locking up) each time.

#### Steps to reproduce
Highlight the word 'ring'.

**Comment by Frenzie** [comment] 2017-07-18 18:01
I assume sdcv does something unexpected. There's currently an upstream effort by @ecraven to integrate all the functionality we require so with any luck that'd take care of it.

**Comment by emacsomancer** [comment] 2017-07-18 22:58
I'm running the stable version of koreader. Is there any point to trying one of the 'nightly' builds?  Or anything I can do in terms of reporting? (logs files I can upload?)

**Comment by Frenzie** [comment] 2017-07-19 06:38
All of those are good. Also try looking up the word without selecting it to see if sdcv actually has anything to do with it.

**Comment by emacsomancer** [comment] 2017-07-21 15:18
I tried looking up 'ring' in the dictionary without selecting it, and, yes indeed, it hard locks (this time I had to reset it using the pinhole.)

**Comment by KenMaltby** [comment] 2017-07-21 15:33
Do you have any other dictionaries installed? You could try adding another to see if that loosens things up.

**Comment by emacsomancer** [comment] 2017-07-21 16:44
@KenMaltby - as a side question, is there a way to determine/control what order koreader accesses dictionaries in?

**Comment by Frenzie** [comment] 2017-07-21 16:57
Not in KOReader atm afaik, but upstream has added an option for that: https://github.com/Dushistov/sdcv/pull/11

**Comment by Hzj-jie** [comment] 2017-08-01 06:57
This can be improved by using background runner.

**Comment by Frenzie** [comment] 2017-08-11 14:45
Could you give this a try in the upcoming nightly? #3071 might've fixed it. Also that means the `-u` or `~/.sdcv_ordering` option will be available now, although it'd need some investigation as to whether a sensible GUI can be created for that.

**Comment by emacsomancer** [comment] 2017-08-12 19:20
@Frenzie  -In  v2015.11-1109-g06d7eea it still locks up when searching for "ring".  In v2015.11-1113-g16dd517 dictionaries don't seem to work at all - that is, it never finds entries for any word I search for or highlight.

@Hzj-jie - what is background runner?

**Comment by Frenzie** [comment] 2017-08-12 19:26
Sorry, I'll investigate it more later but for now I'll just revert it to the status quo. #3080

For an example with background runner see #3078

**Comment by Frenzie** [comment] 2018-03-06 20:15
The bumped binary is good now but for higher firmwares we might have to change to a more static build. But that's a duplicate of #3302.

**Closed by Frenzie** 2018-03-06 20:15 UTC
Labels: bug
