### ISSUE TITLE
(FR). Allow the percentage read calculation to be recalculated in cases with a long bibliography

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5604] opened 2019-11-17 21:30 UTC
Use case.  

I'm finishing up a book with a very long bibliography of more than 10 percent of the overall Koreader rendered pages.

It would be useful to be able to set An arbitrary end point for such books so that I know what the percentage read actually is.  I usually don't read the whole bibliography after finishing the book.  Also would be useful if pages left could be adjusted to the end of the actual book and not the end of available pages counting all parts of the book.

**Comment by robert00s** [comment] 2019-11-18 07:29
Duplicate of #3553.

**Comment by robert00s** [comment] 2019-11-18 12:22
How should we show in footer that we set custom pages (set an arbitrary end point)?
How to show progress bar? Only to checkpoint or for the whole book.

The one of solutions may be show total numbers of pages in bracket. 
![obraz](https://user-images.githubusercontent.com/22982594/69051662-3d6eb080-0a05-11ea-9118-f448330351b7.png)

But I don't know what to do with progress bar.

**Comment by arooni** [comment] 2019-11-20 22:47
the (arbitrary end point) is elegant IMHO.  i think nothing needs to be done with the progress bar.  if we could just get pages remaining and page progress and percentage read calculation that would be great.   

you're still located where the progress bar would indicate.  

just a thought in case not messing with the progress bar makes the implementation easier.

**Comment by hius07** [comment] 2021-11-07 09:05
Further discussion in https://github.com/koreader/koreader/issues/8254.

**Closed by hius07** 2021-11-07 09:05 UTC
Labels: enhancement
