### ISSUE TITLE
ReMarkable: Battery drains while KOReader running and sleeping

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#6028] opened 2020-04-07 12:24 UTC
* KOReader version: 2020.02
* Device: ReMarkable

#### Issue
A sleeping KOReader on reMarkable will drain the battery.

#### Steps to reproduce
1. Launch KOReader on a ReMarkable by long pressing the middle button.
2. Make KOReader go to sleep (e.g. set it to sleep after a time, then wait). It should still be showing KOReader, but with "Sleeping" in the middle of the page.
3. Leave it for a day or two*
4. Find that the battery is completely drained, needs to be charged for a few minutes before it will even turn on.

\* I assume you can do a shorter reproduce by checking the battery level, putting it to sleep for a bit, then checking the battery level again, but I haven't tried.

#### Observations
The reMarkable's own firmware will power off after a certain period of sleep: presumably KOReader running prevents this from happening by stopping the reMarkable firmware. This maybe suggests that the reMarkable's sleep isn't as low-energy as other devices (e.g. I can leave a Kobo eReader asleep for weeks without losing much charge).
Is is properly sleeping or just turning off some peripherals and then idling?

**Comment by Frenzie** [comment] 2020-04-07 12:29
Pinging @tcrs

**Comment by pazos** [comment] 2020-04-07 14:12
Actually we rely on `systemctl` to suspend the system. See https://github.com/koreader/koreader/search?q=systemctl+suspend&unscoped_q=systemctl+suspend

Probably stracing that call and see what's doing under the hood in the original FW is the right step to implement the same on KOReader.  Remarkable is just another freescale/ntx board so probably something like we do on [kobos](https://github.com/koreader/koreader/blob/master/frontend/device/kobo/device.lua#L597-L729) or [cervantes](https://github.com/koreader/koreader/blob/master/platform/cervantes/suspend.sh#L1-L15) is needed.

**Comment by Eeems** [comment] 2020-09-18 21:35
The reMarkable 1 isn't known to have good battery life when suspended from the main application either. I would expect the same results after leaving it suspended for a day or two in xochitl.

As for the automatic power off in xochtil, that only happens when xochitl itself is active. KOReader will likely have to implement its own automatic power off using a waketimer. @raisjnn might be able to provide more information on that front.

**Comment by gabyhk** [comment] 2020-09-20 12:47
This is a critical issue. And if @Eeems is right about the problem fundamentally being with the device, then there might not be much KOReader devs can do. This is fairly disheartening.

Battery life is indeed appalling. In a suspended state (sleeping) my reMarkable can lose over 30% of its battery in 9 hours. In roughly 30 hours it is completely drained. That is a far cry from the 1 week that was advertised – which independent reviewers have already corrected to less than 5 days.

**Comment by raisjnn** [comment] 2020-09-20 13:03
> Battery life is indeed appalling. In a suspended state (sleeping) my reMarkable can lose over 30% of its battery in 9 hours. In roughly 30 hours it is completely drained. That is a far cry from the 1 week that was advertised – which independent reviewers have already corrected to less than 5 days.

personal observation is about 0.8 - 1% drain per hour with wifi off and in sleep mode. (about 3-4 day of outdoor charge),  we are trying to figure out where the battery drain is coming from during sleep (and sacced a device for teardown to determine if it's hardware issue - we will know more in a few weeks)

**Comment by gabyhk** [comment] 2020-09-20 13:31
@raisjnn That sounds a lot better than my experience. I don't discard that this is a problem just with my unit. Thank you for working on this. Looking forward to hear what the results are from the device teardown.

On a more positive note. It sounds like @Eeems has already started working on this as well! https://github.com/koreader/koreader/pull/6681 That is excellent news.

#### Additional Information
I just noticed that I can still SSH into my device both through Wi-Fi and through USB even when KOReader is suspended. There is clearly one or more network services that remain active when they should not. I have to explicitly run `systemctl wlan0 down` and `iwconfig wlan0 txpower off` to ensure that KOReader displays `No default gateway to ping` and then it is not reachable through SSH when sleeping. However, even after doing that, SSH'ing through USB still works, so there is another service that I have not figured out how to turn off. I will report back if I find the answer to this.

**Comment by NiLuJe** [comment] 2020-09-20 13:32
What's the battery capacity?

For reference, on a Kobo, which does a simple suspend to RAM when sleeping, and uses a similar CPU, we see almost null drain (I'd say ~1% per day on a 1500mAh batt).

**Comment by NiLuJe** [comment] 2020-09-20 13:34
And since you mentioned USBNet, that *may* actively prevent suspend (as long as something is plugged in, that is).

(On Kobo, only the latest generation, on i.MX6SLL & i.MX6ULL chips will suspend properly while plugged in w/ USBNet active).

**Comment by gabyhk** [comment] 2020-09-20 13:38
@NiLuJe Per their website, the reMarkable 1 has a 3000 mAh battery and it should last 5-7 days with moderate use. Needless to say, that it does not seem like it gets to 5 days even when idle for anyone that has commented so far.

**Comment by raisjnn** [comment] 2020-09-20 13:39
@NiLuJe it's well known that rM has terrible sleep perf. I was expecting kobo levels of idle drain as well (weeks of idle) but its at days of idle instead.

@gabyhk: what you mentioned (being able to SSH in over wifi or USB) is a sign of the machine not being in low power state (aka sleeping). maybe try using `systemctl suspend` and waking it up in a few hours to see what battery drain looks like. 

i'm unfamiliar, but is koreader doing some power management too? (it sounds like yes). on rM, i don't think we want KOReader doing power management (going to suspend, managing wake timers, etc) and would either keep that in the launcher's purview or create a system service for dealing with it.

**Comment by raisjnn** [comment] 2020-09-20 13:40
re: USBNet preventing sleep: it sounds like the UI shows a "sleeping" text during gaby's tests, so if there are no bugs, then USBNet is not the problem here

**Comment by NiLuJe** [comment] 2020-09-20 13:46
That's what *should* be happening on a power button press:

https://github.com/koreader/koreader/blob/27fe0d7957fd48c375cdae48bc3bf30ceef1edeb/frontend/device/remarkable/device.lua#L113-L115

Now, one would need to check that it actually fires, to see if something's wonky on KOReader's side; and then whether systemd actually manages to do what it's supposed to ;).

**Comment by gabyhk** [comment] 2020-09-20 13:46
> @gabyhk: what you mentioned (being able to SSH in over wifi or USB) is a sign of the machine not being in low power state (aka sleeping). maybe try using `systemctl suspend` and waking it up in a few hours to see what battery drain looks like.

I can certainly give this a try, but isn't KOReader already running `systemctl suspend` when I press the power button?

**Comment by NiLuJe** [comment] 2020-09-20 13:47
Re: USBNet: you'd see the "Sleeping" tag regardless, but the kernel would fail to suspend.

The Kobo codepath has specific heuristics to deal with spurious wakeups, but that's admittedly another kettle of fish. Better check than a simple suspend behaves on its own.

I'd suggest checking the kernel/system logs, a suspend is fairly verbose in dmesg.

**Comment by raisjnn** [comment] 2020-09-20 13:49
> > @gabyhk: what you mentioned (being able to SSH in over wifi or USB) is a sign of the machine not being in low power state (aka sleeping). maybe try using `systemctl suspend` and waking it up in a few hours to see what battery drain looks like.
> 
> I can certainly give this a try, but isn't KOReader already running `systemctl suspend` when I press the power button?

you are right! something must be going on then if you press power button and the machine doesn't make it to suspend. i can only add the data point that `systemctl suspend` does work properly when invoked from other applications.

**Comment by NiLuJe** [comment] 2020-09-20 13:54
Should be on release.

**Comment by gabyhk** [comment] 2020-09-20 13:56
@NiLuJe @raisjnn Using the built-in Terminal Emulator feature from KOReader I ran `systemctl suspend`and that successfully suspends both USBNet and Wifi! Neither are reachable through SSH after that even when plugged in. The power button is definitely not doing that. We're onto something here.

**Comment by NiLuJe** [comment] 2020-09-20 14:17
Enabling debug logging in KOReader's dev options should help figuring out
what happens, it dumps keycodes events among other things.

**Comment by gabyhk** [comment] 2020-09-20 14:29
> Enabling debug logging in KOReader's dev options should help figuring out what happens, it dumps keycodes events among other things.
I apologize for the newbie question, but where does it dump this information. I have enabled that mode and restarted KOReader and I do not see such information.

**Comment by gabyhk** [comment] 2020-09-20 14:37
New finding: If I suspend the device by pressing the power button, only another press of that same button wakes up the device. If I suspend the device by long pressing a `suspend.sh` file (which contains `systemctl suspend`) then any button can wake up the device. This rather strange considering that we have already established that the latter is triggering a proper "sleep mode" while the former keeps USBNet and Wi-Fi on, thus killing the battery.

**Comment by tcrs** [comment] 2020-09-20 16:20
Just to add my experience here:
 - SSH connection definitely drops when connected over WiFi and pressing the power button to suspend (USB of reMarkable *not* connected to anything)
 - Battery life on suspend is poor for me, but comparable to when using xochitl
 - I didn't notice any difference in suspend  battery draw when explicitly disabling WiFi before suspend, although this was a very non-scientific test back when I was porting KOReader

This is the dmesg output I get from a suspend then resume:
```
[12918.973918] PM: Syncing filesystems ... done.
[12919.025748] PM: Preparing system for sleep (mem)
[12919.027026] Freezing user space processes ... (elapsed 0.567 seconds) done.
[12919.601530] Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
[12919.609855] PM: Suspending system (mem)
[12919.609859] Suspending console(s) (use no_console_suspend to debug)
[12920.128641] PM: suspend of devices complete after 518.493 msecs
[12920.128646] PM: suspend devices took 0.520 seconds
[12920.129149] PM: late suspend of devices complete after 0.492 msecs
[12920.129582] PM: noirq suspend of devices complete after 0.423 msecs
[12920.129962] PM: noirq resume of devices complete after 0.356 msecs
[12920.130360] PM: early resume of devices complete after 0.297 msecs
[12920.173866] Suspended for 272.029 seconds
[12920.173930] PM: resume of devices complete after 43.559 msecs
[12920.174320] PM: resume devices took 0.050 seconds
[12920.224362] PM: Finishing wakeup.
[12920.224365] Restarting tasks ... done.
[12939.538798] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
```

So Linux thought it was suspended.

I do find it quite annoying that the battery life is so poor when suspended - I have a Kobo Aura which lasts months on suspend! I did start looking at one point into what kernel modifications the Kobo kernel has. There is some custom code in there to shut more stuff down via a sysfs trigger (if I'm remembering correctly) - you can see in `frontend/device/kobo/device.lua` that the suspend function writes to `/sys/power/state-extended` to set up the custom Kobo suspend state and also `/sys/power/state` to do the standard Linux suspend-to-RAM. I never got very far working out what the kernel code was doing though.

**Comment by NiLuJe** [comment] 2020-09-20 17:44
@tcrs: Yeah, that (state-extended) flips an NTX global across the kernel named g_<insert real name here ;p> that does a few extra PM things.

I never really dug further than finding it was the culprit of sometimes failing to wakeup the IR grid on devices w/ one ;p.

**Comment by NiLuJe** [comment] 2020-09-20 17:46
@gabyhk: Assuming you've found the Debug checkbox already (Tools > More tools > Developer options > Enable debug logging), the output goes to a crash.log file in KOReader's folder (wherever that is on rM ^^).

**Comment by gabyhk** [comment] 2020-09-21 01:38
> * SSH connection definitely drops when connected over WiFi and pressing the power button to suspend (USB of reMarkable _not_ connected to anything)

@tcrs First things first. Thank you for doing the original reMarkable port! I wanted a 10-inch device to use KOReader and without your work I would not have had an option for my budget. My device is RM102. Perhaps you own a RM101 and that is partly responsible for the discrepancy. I suspect this is also the reason why https://github.com/koreader/koreader/issues/6676#issue-704502021 could not be reproduced by nathaniel.

> * Battery life on suspend is poor for me, but comparable to when using xochitl
> I do find it quite annoying that the battery life is so poor when suspended - I have a Kobo Aura which lasts months on suspend!

I cannot agree enough with these statements. I had a Kobo Forma and there is simply no comparison when it comes to battery life.

@NiLuJe I found the `crash.log`. I would have never found it myself. Thanks!

#### Latest Test
Following @raisjnn 's suggestion. I tested battery life when idle in two scenarios:

Suspending with the power button = battery consumption of **3.6% / hour**
Suspending with `systemctl wlan0 down` and `systemctl suspend` = battery consumption of **0.6% / hour**

Still not Kobo-like performance, but a massive improvement nonetheless.

**Comment by tcrs** [comment] 2020-09-21 16:03
> > * SSH connection definitely drops when connected over WiFi and pressing the power button to suspend (USB of reMarkable _not_ connected to anything)
> 
> @tcrs First things first. Thank you for doing the original reMarkable port! I wanted a 10-inch e-ink device to use KOReader and without your work I would not have had an option for my budget. My device is RM102. Perhaps you own a RM101 and that is partly responsible for the discrepancy. I suspect this is also the reason why [#6676 (comment)](https://github.com/koreader/koreader/issues/6676#issue-704502021) could not be reproduced by nathaniel.

I've just had a look and my device is an RM102. However I'm still on v2.0.2 of the firmware which is pretty old now, I assume you're on a newer version? I will update my device and see what happens.

**Comment by tcrs** [comment] 2020-09-21 16:09
> Suspending with `systemctl wlan0 down` and `systemctl suspend` = battery consumption of **0.6% / hour**

What command are you using to bring down the wifi? I think `systemctl wlan0 down` is a typo...

**Comment by pazos** [comment] 2020-09-21 16:11
> #### Latest Test
> Following @raisjnn 's suggestion. I tested battery life when idle in two scenarios:
> 
> Suspending with the power button = battery consumption of **3.6% / hour**
> Suspending with `systemctl wlan0 down` and `systemctl suspend` = battery consumption of **0.6% / hour**

Somehow expected. As we don't manage wifi we don't disable it (or interact with it in any other way) on suspend.

**Comment by raisjnn** [comment] 2020-09-21 16:16
does wifi actually affect battery life during suspend? i mentioned wifi because i keep it off usually (while awake), but unsure what effect it has during sleep

**Comment by Eeems** [comment] 2020-09-21 16:18
From @gabyhk's testing yes

> Suspending with the power button = battery consumption of 3.6% / hour
> Suspending with systemctl wlan0 down and systemctl suspend = battery consumption of 0.6% / hour

**Comment by NiLuJe** [comment] 2020-09-21 16:18
Suspend should definitely kill Wi-Fi ;).

**Comment by Eeems** [comment] 2020-09-21 16:19
> 
> Suspend should definitely kill Wi-Fi ;).

You said the `should` word. Now we have no idea what is actually happening ;P

**Comment by tcrs** [comment] 2020-09-21 16:27
I will see if I can get an strace of what xochitl is doing on suspend

**Comment by tcrs** [comment] 2020-09-21 17:59
I have updated to latest v2.3 firmware.
Disappointingly it is not at all obvious from the strace how xochitl triggers suspend at all.
When I am connected via SSH over WiFi, triggering suspend in xochitl by pressing the power button does not immediately disconnect me, but about 10 seconds later the connection drops. I can see if I resume after then the WiFi has to reconnect so it's definitely at least dissociating from the AP at least even if not actually powering down the chip.
Running `systemctl suspend` manually in an ssh shell immediately drops the connection, syslog output also clearly says that systemd is entering suspend which isn't in the syslog when xochitl enters suspend.
More investigation required.......

**Comment by pazos** [comment] 2020-09-21 18:55
> Suspend should definitely kill Wi-Fi ;).

It should, [or not](https://github.com/koreader/koreader/blob/master/frontend/device/generic/device.lua#L291-L295). BTW that function is only used on kobos now, so it can be moved to `device/kobo/device.lua`

> When I am connected via SSH over WiFi, triggering suspend in xochitl by pressing the power button does not immediately disconnect me (...)
> Running systemctl suspend manually in an ssh shell immediately drops the connection

Yeah, that happens on other stock fw (cervantes for sure, I think kobo too). There's a few seconds delay before actually suspend the system.

On these NTX boards issuing `echo mem >/sys/power/state` without the delay makes the whole suspend to fail. I wonder if the same happens on the Remarkable. Anyways, a good way to test that is to replace `systemctl suspend` with a script that does the same after 2 seconds. See for example https://github.com/koreader/koreader/blob/master/platform/cervantes/suspend.sh

**Comment by gabyhk** [comment] 2020-09-21 23:18
> I've just had a look and my device is an RM102. However I'm still on v2.0.2 of the firmware which is pretty old now, I assume you're on a newer version? I will update my device and see what happens.

I guess with that we have ruled out the device being the differentiating factor. I am on fw 2.2.0.48. Version 2.3 is not even available for me yet.

> What command are you using to bring down the wifi? I think systemctl wlan0 down is a typo...

Oh my… that's embarrassing. Yeah, I meant `ifconfig wlan0 down`. I run `iwconfig wlan0 txpower off` sometimes too, but NiLuJe is right `systemctl suspend` should make both commands redundant.

**Comment by tcrs** [comment] 2020-09-24 18:49
I'm interested the possibility of failing suspends. As you can see in the `dmesg` output I grabbed it looks like in that case my device really did suspend. Maybe it doesn't always though. I would be interested to see the `dmesg` output from your device after a suspend or two?

I didn't realise how suspend worked in KOReader - if I comment out the remarkable device.lua call to `systemctl suspend` it doesn't appear different from the KOReader UI. I wouldn't realise if it hadn't actually managed to suspend. I sort of assumed without much thought that the screensaver would clear if the device didn't suspend. Possibly we need some extra stuff to make sure it either happens or is obvious from the UI that it's not working. Ideally `systemctl suspend` would block until the suspend was complete, but it doesn't...

**Comment by Eeems** [comment] 2020-09-24 18:59
You could potentially do some magic with `/lib/systemd/system-sleep/` scripts like I am in oxide: https://github.com/Eeems/oxide/blob/master/assets/lib/systemd/system-sleep/tarnish
What I'm doing is I'm drawing the reMarkable suspend screen as part of that script, as well as restoring the previous screen on resume: https://github.com/Eeems/oxide/blob/master/applications/system-service/appsapi.h#L366-L424

**Comment by Eeems** [comment] 2020-09-24 19:03
Also, some learnings that I've had is that the reMarkable will wake from any of the buttons being pressed. And it seems that Xochitl handles "deep sleep" by just re-suspending if the button pressed wasn't the power button. Very much not ideal, but it's a better option than staying awake if one of the front buttons are pressed accidentally while in a bag.

**Comment by Frenzie** [comment] 2020-09-24 19:06
We implement similar things on Kobo in case those hacks are of any use as an example here. See for example:

https://github.com/koreader/koreader/blob/5345728cc462a85adde50367d76636dc54fce481/frontend/device/kobo/device.lua#L558-L590

**Comment by gabyhk** [comment] 2020-09-24 19:55
@tcrs Here is the `dmesg` after executing `systemctl suspend`:

```
[   69.907960] PM: Syncing filesystems ... 
[   69.921205] random: crng init done
[   69.952848] done.
[   69.952855] PM: Preparing system for sleep (mem)
[   69.956282] Freezing user space processes ... (elapsed 0.001 seconds) done.
[   69.964503] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
[   69.973160] PM: Suspending system (mem)
[   69.973163] Suspending console(s) (use no_console_suspend to debug)
[   70.271187] imx_epdc_fb 20f4000.epdc: PxP operation failed due to timeout
[   70.271194] imx_epdc_fb 20f4000.epdc: Unable to complete PxP update task.
[   70.581346] PM: suspend of devices complete after 607.900 msecs
[   70.581351] PM: suspend devices took 0.610 seconds
[   70.581851] PM: late suspend of devices complete after 0.489 msecs
[   70.582289] PM: noirq suspend of devices complete after 0.428 msecs
[   70.582557] PM: noirq resume of devices complete after 0.243 msecs
[   70.582906] PM: early resume of devices complete after 0.252 msecs
[   70.624223] Suspended for 3.770 seconds
[   70.624279] PM: resume of devices complete after 41.363 msecs
[   70.624665] PM: resume devices took 0.040 seconds
[   70.694603] PM: Finishing wakeup.
[   70.694606] Restarting tasks ... done.
```

And here is the `dmesg` after suspending by pressing the power button:
```
[   83.282453] PM: Syncing filesystems ... done.
[   83.333738] PM: Preparing system for sleep (mem)
[   83.337077] Freezing user space processes ... (elapsed 0.581 seconds) done.
[   83.926930] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
[   83.935569] PM: Suspending system (mem)
[   83.935572] Suspending console(s) (use no_console_suspend to debug)
[   83.997228] PM: suspend of devices complete after 61.232 msecs
[   83.997233] PM: suspend devices took 0.070 seconds
[   83.997744] PM: late suspend of devices complete after 0.499 msecs
[   83.998187] PM: noirq suspend of devices complete after 0.431 msecs
[   83.998561] PM: noirq resume of devices complete after 0.349 msecs
[   83.998960] PM: early resume of devices complete after 0.297 msecs
[   84.049242] Suspended for 2.659 seconds
[   84.049298] PM: resume of devices complete after 50.196 msecs
[   84.049691] PM: resume devices took 0.050 seconds
[   84.099493] PM: Finishing wakeup.
[   84.099496] Restarting tasks ... done.
```

**Comment by Eeems** [comment] 2020-09-24 20:00
According to the systemd-suspend documentation (https://www.freedesktop.org/software/systemd/man/systemd-suspend.service.html), using a script like I did should be considered a hack, and the correct way is to use the [inhibitor interface](https://www.freedesktop.org/wiki/Software/systemd/inhibit/). I haven't confirmed that this works on the reMarkable yet.

**Comment by gabyhk** [comment] 2020-09-24 20:07
@Eeems Have you been able to bring the `autosuspend timeout` and `autoshutdown timeout` options to the reMarkable through `oxide`? It's such an essential feature. I'm crossing my fingers so that your work with `oxide` helps us figure out how to enable the **auto suspend** plugin for the reMarkable port of KOReader.

**Comment by Eeems** [comment] 2020-09-24 20:18
> 
> 
> @Eeems Have you been able to bring the `autosuspend timeout` and `autoshutdown timeout` options to the reMarkable through `oxide`? It's such an essential feature. I'm crossing my fingers so that your work with `oxide` helps us figure out how to enable the **auto suspend** plugin for the reMarkable port of KOReader.

Automatic suspend is in oxide only currenlty, but will be systemwide later. As for auto shutdown: https://github.com/Eeems/oxide/issues/16

**Comment by gbyl** [comment] 2020-10-11 12:27
With @NiLuJe's commits I have measured consistently a power usage of around **1%/h on idle** (equivalent to roughly 4 days). Substantial improvement from the 3.6/4% I was seeing before. I don't imagine xochitl performing any better than this. We can probably close this issue now since this is likely as good a battery performace we are ever going to get on the RM1.

**Comment by Frenzie** [comment] 2020-10-11 12:35
Sounds a bit disappointing, but okay. ;-)

**Closed by Frenzie** 2020-10-11 12:35 UTC
Labels: reMarkable

**Comment by gbyl** [comment] 2020-10-11 15:14
@Frenzie I know, but it doesn't diminish the collective effort. Thanks to all of you, I no longer own a remarkable, but rather a [10-inch KOReader](https://i.imgur.com/G9buDFS.mp4) ;)

**Comment by Eeems** [comment] 2020-10-12 16:13
> Sounds a bit disappointing, but okay. ;-)

It's a known problem with the rM1. There has been some postulation that it's due to something not being soldered on the board that should be.

**Comment by gbyl** [comment] 2020-10-14 19:09
@Eeems I was wondering, do you have a link for that? I tried my best to google it and couln't find anything. I would like to read up more on this battery situation.

**Comment by Eeems** [comment] 2020-10-14 19:26
> 
> 
> @Eeems I was wondering, do you have a link for that? I tried my best to google it and couln't find anything. I would like to read up more on this battery situation.

I don't, it was just something that I believe @torwag mentioned in Discord.

**Comment by torwag** [comment] 2020-10-14 19:36
Hmmm can't remember that I said something like this. It is rather unlikely that they simply do not populate some missing components. Usually they simply overlooked something during the design as the usual design is most likely a copy over from some reference designs and those, are powered by external sources, do not really care much about power saving. So what could be missing is something to be able turn off peripherals.
