### ISSUE TITLE
FR: Customizable color mode, smoother scrolling, user-friendly book organization.

### ISSUE THREAD

**Issue by ABdo-0s** [koreader/koreader#12844] opened 2024-12-04 13:39 UTC
**Does your feature request involve difficulty completing a task? Please describe.**

Yes, there are a few aspects of the app that I find make completing tasks a bit difficult. For example, the lack of customizable color options, which would be helpful for users who prefer different visual styles, and the smoothness of the scrolling experience, which doesn't feel as smooth as it could be. Additionally, the organization of books could be improved to make it more user-friendly.

---

**Describe the solution you'd like**

1. **Color Mode Customization**: I would like the option to change the background and text colors via a color wheel for Android users and phone users. This would allow me to adjust the appearance of the app to my liking. Additionally, it should be possible to enable or disable this feature for e-ink device users to ensure compatibility.

2. **Smoother Scrolling**: I would appreciate a feature that smooths the scrolling experience, making it more fluid when navigating through content. Like the previous feature, it should also have an option to enable or disable it for e-ink users.

3. **Improved User-Friendly Theme**: It would be great to have a more streamlined way to organize books, like in Readera app. A unified place where all books are easily accessible and organized would make the app much more user-friendly.

---

**Describe alternatives you've considered**

For the color mode, an alternative could be offering a set of preset themes (light, dark, sepia) that users could select from. For smoother scrolling, an alternative would be to optimize the current web view for better performance. For the user-friendly theme, I have considered organizing the books in a separate Folder , but it’s Difficult and time consuming , it will be better to integrating it directly within the app.

---

**Additional context**

I believe these features would make the app more enjoyable for a broader range of users, particularly Android phone users, while also allowing it to be accessible to e-ink device users. By giving users more customization options, the app could cater to a variety of preferences, which would significantly improve the overall user experience.

**Comment by pazos** [comment] 2024-12-04 18:41
Hi, @ABdo-0s. Thanks for your feedback.

Please do not create tickets with different feature requests. Just create one ticket per feature request.

In this case:

2. Smooth scrolling isn't possible. What you think it's just "smooth scrolling" is a combination of GPU shadders with kinnect scrolling. Both features are impossible to implement in the current codebase.

3. That's a duplicate of https://github.com/koreader/koreader/issues/8472

So feel free to create a new ticket for `1`, if you deem it relevant.

**Closed by pazos** 2024-12-04 18:41 UTC
Labels: enhancement

**Comment by ABdo-0s** [comment] 2024-12-06 15:49
Thank you for the answer , sore about the different feature requests, I did not know that is forbidden.

**Comment by Frenzie** [comment] 2024-12-06 17:36
New ticket in https://github.com/koreader/koreader/issues/12858
