### ISSUE TITLE
Freeze when KOReader going to sleep

### ISSUE THREAD

**Issue by csanyikrisztian** [koreader/koreader#3936] opened 2018-05-07 18:18 UTC
* KOReader version: v2015.11-1654-g666c9f1_2018-04-12
* Device: Kobo Touch N905B

#### Issue
In KOReader I would like to send Kobo to sleep mode.
After I press the power button, it goes to sleep mode, a panel with this text appears.
When I try to wake up the device it freezes.

#### Steps to reproduce
1. Start KOReader
2. Press Power button
3. Try to wake up device

##### `crash.log` (if applicable)
```
 [*] Current time: 05/07/18-20:08:49
 [*] Version: v2015.11-1654-g666c9f1_2018-04-12

ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
05/07/18-20:08:49 INFO  initializing for device Kobo_trilogy
05/07/18-20:08:49 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
[ko-input] Forked off fake event generator(pid:942).
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
05/07/18-20:08:51 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
05/07/18-20:08:52 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
05/07/18-20:08:52 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
05/07/18-20:08:52 INFO  Plugin  plugins/kobolight.koplugin/main.lua  has been disabled.
ffi.load: z
ffi.load: sqlite3
ffi.load: libs/liblodepng.so
ffi.load: libs/libturbojpeg.so
ffi.load: libs/libgif.so.7
05/07/18-20:08:52 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin perception_expander at plugins/perceptionexpander.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
05/07/18-20:08:52 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
```

**Comment by Frenzie** [comment] 2018-05-07 20:12
> After I press the power button, it goes to sleep mode, a panel with this text appears.

By this text you mean something like `sleeping`?

Pinging @NiLuJe who touched this stuff a bit.

I'm not seeing any issues on my H2O v1 btw. Is there anything specific you do before pressing the power button?

**Comment by NiLuJe** [comment] 2018-05-07 20:25
Yeah, what test exactly, and what do you mean exactly by "it freezes"? Does the screen appear to wake up/update, does the frontlight get restored?

I don't recall anything wonky on my H2O either, FWIW.

**Comment by csanyikrisztian** [comment] 2018-05-07 20:42
@Frenzie Yes, when I push the power button to send the Kobo Touch to sleep an "info" panel pops up with "Sleeping".

@NiLuJe When I would like to wake it up there is no reaction. The screen remains in that state with the info panel "Sleeping". (No frontlight on Kobo Touch)

I can reproduce everywhere in the KOReader: in a book or in the filebrowser, etc.
When I start the nickel from the start menu I can send the reader to sleep and wake it up perfectly. That's why I think this is a KOReader issue.

**Comment by cramoisi** [comment] 2018-05-08 05:05
Freeze sometimes happens to me too after waking up the kobo (KA1) by opening the sleepcover.
Touch input seems to not respond for a while 1. sometimes it finally wakes up 2. sometimes I sleep it again wait 30 sec and wake it up again and it's ok. And there is nothing to see in the crash.log except the classic sleep/wake up cycle. @csanyikrisztian if you repush to the power button, did the device goes back to sleep or are you obliged to reboot to get hold on it ?

Some other times, when i wake it up and touch the screen, it says "frontlight off" when I disabled all the plugin related to touch control the frontlight (not only disabled, but removed from the install). Sometimes it change the size of the font.

All of that to say there is definitely something to do there :-)

**Comment by csanyikrisztian** [comment] 2018-05-08 07:42
@cramoisi repushing the power button after "sleep freeze" doesn't work. The only solution is to hold the power button for ~10secs to power off the Kobo. Power off happens without any change on the display and after that I can power on the Kobo. And this freezing happens every time I would like to send the Kobo to sleep.

**Comment by poire-z** [comment] 2018-05-08 08:16
Do you have wifi enabled when/before that happened?
(the only real freeze related to suspend I ever had on Kobo was when having the wifi module(s) loaded when asking the kernel to suspend)

**Comment by csanyikrisztian** [comment] 2018-05-08 09:44
KSM automatically enables wifi, but if I disable it in KSM or in KOReader the freeze happens when I send it to sleep.

Is there any way to prevent loading wifi module wifi at power on?

**Comment by Frenzie** [comment] 2018-05-08 10:16
> Do you have wifi enabled when/before that happened?
(the only real freeze related to suspend I ever had on Kobo was when having the wifi module(s) loaded when asking the kernel to suspend)

I typically have wifi enabled when suspending, ftr. Not necessarily as a user, but I probably do as much testing/development as reading on it. :-P

(I do most of my reading on paper, after all.)

**Comment by cramoisi** [comment] 2018-05-08 10:16
you have to configure KSM for that.
In KSM > toggle btw full and short menu (for getting the full if you don't
have it)
"tools" > "ksm diverse.msh" > "auto enable wifi off.sh"


2018-05-08 11:44 GMT+02:00 Krisztian CSANYI <notifications@github.com>:

**Comment by csanyikrisztian** [comment] 2018-05-08 10:36
@cramoisi Thanks you. I tried "auto enable wifi off.sh" and now I can send Kobo to sleep and wake it up perfectly. Thank you very much.

**Comment by NiLuJe** [comment] 2018-05-09 10:56
Does KSM export INTERFACE?

If not, see if reverting a3e16b3920d8eeb6eec3b3937b0f2f4b55d703fa helps?

**Comment by NiLuJe** [comment] 2018-05-09 11:01
I refrained from using ${INTERFACE} everywhere in my initial pass on the scripts because I wasn't sure it would *always* work.

It's one of the few vars we siphon from nickel when starting with nickel up, for instance. It's exported by rcS, true, but *late* (well after on-animator has run).

**Comment by Frenzie** [comment] 2018-05-09 11:15
KSM exports it, yes. It's possible it didn't 5 years ago though?

**Comment by cramoisi** [comment] 2018-05-09 11:37
@Frenzie your KSM instal is 5 years old ? =-)

**Comment by Frenzie** [comment] 2018-05-09 11:42
It could potentially be a factor in the OP's problem.

**Comment by NiLuJe** [comment] 2018-05-09 12:15
FWIW, just reproduced this when starting from within Nickel, with WiFi up (and WiFi was up in KOReader when going to sleep).

H2O, FW 4.8, KO 1703.

**Comment by NiLuJe** [comment] 2018-05-09 12:25
It really, really hung (had to pinhole reset it).

```
05/09/18-14:09:12 INFO  Kobo suspend: going to sleep . . .
05/09/18-14:09:12 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
05/09/18-14:09:14 INFO  Kobo suspend: waited for 2s because of reasons...
```

Might not entirely be accurate, depending on how badly it crashed, but that looks like a hand on suspend, and not on resume, at least.

**Comment by Frenzie** [comment] 2018-05-09 12:35
Hooray! (Sort of. But I can't reproduce it. :-P)

**Comment by NiLuJe** [comment] 2018-05-09 12:42
Okay, shot in the dark: Which FW version are you running @csanyikrisztian ?

If it's FW 4.8.x, I'm going to blame it on that, and wait for the next FW release. Kobo pulled it, so, hopefully they had a good reason and what we're seeing is a side-effect of that?

**Comment by csanyikrisztian** [comment] 2018-05-09 12:55
@NiLuJe The firmware version is: 4.8.10956 (daee2c4220, 4/17/18)

**Comment by NiLuJe** [comment] 2018-05-09 13:46
Haha!

... Unfortunately, now that I've double-checked, neither the kernel nor the modules appear to have been updated between FW 4.7 and 4.8, so that shouldn't matter. :(.

**Comment by NiLuJe** [comment] 2018-05-09 14:03
Shot in the dark, take two:

wifi_was_on is not set on my end, but wifi was actually on, so we never tried to kill wifi before suspend -> kablooey?

**Comment by csanyikrisztian** [comment] 2018-05-09 14:17
Wifi was enabled by default by KSM on power on. After I run "auto enable wifi off.sh" this freezing stuff solved.

**Comment by NiLuJe** [comment] 2018-05-09 14:48
PR #3939 seems to do the trick on my end :).

**Comment by NiLuJe** [comment] 2018-05-11 13:34
Could the other affected people try a nightly >= 1704 to see if we can close this for good?

(Pinging @csanyikrisztian & @Xorkle)

**Comment by Xorkle** [comment] 2018-05-11 13:49
Hello!

Has been working all day for me (woke it up just now)!

Can be closed on my end. Thank you very much everyone.

**Comment by csanyikrisztian** [comment] 2018-05-11 13:54
@NiLuJe I try today and give you feedback, little patience please :)

**Comment by NiLuJe** [comment] 2018-05-11 21:10
Fantastic! Thanks, everyone ;).

**Closed by NiLuJe** 2018-05-11 21:10 UTC
Labels: Kobo

**Comment by KarimElzeidy** [comment] 2021-07-18 21:00
I can confirm that this issue still exist on my kobo forma with Koreader v2021.03

**Comment by NiLuJe** [comment] 2021-07-18 21:43
That is an awfully old version, and awfully old issue, and also likely not at all what's happening on your end ;).

Please open a new issue, with full verbose debug logs attached.

I'm betting it's just a run of the mill Mk. 7 kernel faceplant we can do nothing about.
