### ISSUE TITLE
Wallabag articles remove from history (onClose event)

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#6046] opened 2020-04-13 15:16 UTC
* KOReader version: git 
* Device: all

#### Issue
News downloader and send 2 ebook removes after close article from history, so history does not contain a lot of small (usually single or couple pages), mainly read all at once articles; but wallabag does. 

I think it might be good to also clear onClose history from wallabag articles, or at least create option in settings to clear it on close document

#### Steps to reproduce

Download wallabag articles, open one, read it, open koreader file browser, open history -  last read wallabag article is there

**Comment by Frenzie** [comment] 2020-04-13 15:23
Duplicate of #5045.

**Closed by Frenzie** 2020-04-13 15:23 UTC
