### ISSUE TITLE
Latest two releases do not work on Tolino Epos 1

### ISSUE THREAD

**Issue by jeffersondarcy** [koreader/koreader#12842] opened 2024-12-04 11:24 UTC
* KOReader version: v2024.11, v2024.07
* Device: Tolino Epos 1 (Firmware v15), Android 4?

With v2024.11 UI completely unresponsive, with v2024.07 a screen with debug errors appears
v2024.04 works fine

The KOReader app on the Tolino Epos 1 (Firmware v15) becomes unresponsive in the latest release. The book loads and is displayed correctly, but the UI does not respond to touch inputs. In the second-to-last release, the app displays numerous debug logs with errors and does not function. A previously working version from 2022 was uninstalled before installing the recent versions.
Books with progress and other files were present on the reader, that's why the app loads with an opened book already, but the previous Koreader version was uninstalled via adb
v2024.04 is currently the most recent version working on my device

Unfortunately I did not preserve logs

**Comment by benoit-pierre** [comment] 2024-12-04 11:46
Try the nightly.

**Comment by jeffersondarcy** [comment] 2024-12-04 12:07
@benoit-pierre thanks, latest nightly seems to work https://build.koreader.rocks/download/nightly/v2024.11-44-gf5921eec2_2024-12-03/

**Comment by benoit-pierre** [comment] 2024-12-04 12:10
Duplicate of #12769.

**Closed by benoit-pierre** 2024-12-04 12:10 UTC
Labels: Android, duplicate
