### ISSUE TITLE
Kobo Aura One (KA1) is discharging fast on Koreader even being in sleeping mode.

### ISSUE THREAD

**Issue by silverlik** [koreader/koreader#2344] opened 2016-11-14 14:36 UTC
* KOReader version: last nightly on 10.11.2016 using without Startmenu8
* Device: Kobo Aura One (KA1)

#### Issue
KA1 loose charge during the day.
#### Steps to reproduce
1. Charge KA1 completely.
2. Start Koreader. Read or just let it sleep.
3. The same day or the next day it will say that charging is needed or battery will become low.

I read a bit and. Then I put it to sleep about 96% of battery. In 4 hours I open it again and saw 48% of battery. When I read in Nickel, it is not happened.

**Comment by AlanSP1** [comment] 2016-11-15 11:52
Did you read issue https://github.com/koreader/koreader/issues/2239 ?

There's still problem AFAIK with charging device that could cause false sleep. But, manually forcing it on and off should properly handle USB event. But I may be mistaken and we can have something new here.

**Comment by silverlik** [comment] 2016-11-15 12:24
It looks the same or resemble to #2239. I don't use Startmenu8 though, and cool reader does not cause battery draining. I have sleeping cover on reader, so I just close it, do not press button. I will try to force on/off to completely turn off device if it will help.

**Comment by AlanSP1** [comment] 2016-11-15 12:31
KSM8 doesn't affect suspend problems. And, for some reason, CR works fine from the start. But, try power on/off cycle after charging to see if it helps or not.

**Comment by houqp** [comment] 2016-11-16 08:01
USB hot-plug action interrupting suspend state bug should have already been fixed. The only remaining issue is your device will occasionally go into a false sleep mode and the only way to fix it is to exit and restart koreader as discussed in #2239. I will dig to the bottom of this issue in the following weeks.

Closing this since it's a duplicate of #2239.

**Closed by houqp** 2016-11-16 08:01 UTC
