### ISSUE TITLE
Linux version does not save font sizes and margins

### ISSUE THREAD

**Issue by Fmstrat** [koreader/koreader#4826] opened 2019-03-20 21:34 UTC
* KOReader version: v2019.03.1
* Device: Ubuntu 18.04 laptop

#### Issue
When using the bottom menu to set font sizes and margin, the settings are not saved. Restarting the reader resets those settings. The settings show up in the menu where I left them, but the fonts and margins are at their original default.

#### Steps to reproduce
In Ubuntu 18.04
- sudo apt install libsdl2-dev
- sudo apt install ./koreader-2019.03.1-amd64.deb
- After opening, drag up from the bottom and adjust the font size and margins
- Close KOReader
- Open KOReader
- Note the font size and margins are like they were when the app first started
- Drag up for menu
- Note that the settings make it seem like the larger font sizes and margins are selected, even though these settings are not applied.

**Comment by Frenzie** [comment] 2019-03-20 21:44
As an aside, surely there's no dependency on libsdl2-_dev_?

https://github.com/koreader/koreader/blob/2f65fb94eca02bbde5200eef36251cca2840857e/platform/debian/do_debian_package.sh#L41

> Note that the settings make it seem like the larger font sizes and margins are selected, even though these settings are not applied.

That sounds a whole lot more bothersome than not saved. ;-)

This doesn't seem to be something I can reproduce. This is after closing and reopening the version packaged in the Debubuntu package:
<img src=https://user-images.githubusercontent.com/202757/54721132-74807f80-4b61-11e9-9b95-6feff0b6ecc5.png width=40%>

**Comment by pazos** [comment] 2019-03-20 21:45
> sudo apt install libsdl2-dev

thanks! that is, in fact, a prerrequisite that I forgot to add to the debian package.

> When using the bottom menu to set font sizes and margin, the settings are not saved

I can't reproduce that. I think you are closing the window using the close button.

**Comment by Frenzie** [comment] 2019-03-20 21:46
@pazos But so am I.

**Comment by Fmstrat** [comment] 2019-03-20 21:46
@Frenzie It is, actually, but looks like @pazos pointed that out. Had to debug that one on my own ;)

> I can't reproduce that. I think you are closing the window using the close button.

Hrm.. Yes, yes I am. How should I be closing?

**Comment by Frenzie** [comment] 2019-03-20 21:47
Why is libsdl2-dev a prerequisite? That sounds like a bug, not like something to be added to the list of dependencies.

**Comment by pazos** [comment] 2019-03-20 21:53
> Why is libsdl2-dev a prerequisite? That sounds like a bug

it seems that libsdl2-2.0-0 is not linked to libSDL2.so unless libsdl2-dev is installed

Without it I get: `libSDL2.so: cannot open shared object file: No such file or directory`

**Comment by Fmstrat** [comment] 2019-03-20 21:54
> I can't reproduce that. I think you are closing the window using the close button.

OK, I can reproduce using the exit button in the menus, too. What's the best way to debug this for you?

**Comment by Frenzie** [comment] 2019-03-20 21:54
Alright, so the bug is that the program only looks for libSDL2.so.

Please don't work around it. :-)

**Comment by pazos** [comment] 2019-03-20 21:59
> OK, I can reproduce using the exit button in the menus, too. What's the best way to debug this for you?

You can get debug messages on your console running `koreader -d`

**Comment by Fmstrat** [comment] 2019-03-20 22:07
Please see the attached. `koreader.log` is the first run, and `koreader2.log` is the second. I did the same thing in each. Open, maximize, change settings.

Search through each for "margins" and you'll see they default to 70 at startup, then I change them to larger later. Hope this helps debug!
[koreader.log](https://github.com/koreader/koreader/files/2990302/koreader.log)
[koreader2.log](https://github.com/koreader/koreader/files/2990303/koreader2.log)

BTW, I also noticed that passwords are logged when using OPDS. Might want to consider masking those, especially if those are getting dumped to `logcat` in the Android app.

**Comment by Frenzie** [comment] 2019-03-20 22:12
It says `CRE WARNING: cached rendering is invalid (style hash mismatch): doing full rendering`. 

@poire-z could that be responsible?

**Comment by poire-z** [comment] 2019-03-20 22:17
Nope, that's the consequence: the cache was saved with book rendered with the user-set margins. On next load, the margins applied are no more the user-set ones, so saved style hash (with user-set margins) is different from current one (with default margins), so mismatch, so full rendering.

**Comment by poire-z** [comment] 2019-03-20 22:23
Between the 2 runs, you should look at the content of  /home/fmstrat/Books/Cory Doctorow - Walkaway.sdr/metadata.epub.lua : which margins are saved in it.
So we know if it's a save issue, or a load issue.

Also, there are tons of
```
03/20/19-18:02:56 DEBUG /home/fmstrat/.config/koreader/settings/multiswipes.lua  is invalid, remove.
03/20/19-18:02:56 DEBUG /home/fmstrat/.config/koreader/settings/multiswipes.lua.old.1  is invalid, remove.
03/20/19-18:02:56 DEBUG /home/fmstrat/.config/koreader/settings/multiswipes.lua.old.2  is invalid, remove.
03/20/19-18:02:56 DEBUG /home/fmstrat/.config/koreader/settings/lookup_history.lua.old.8  is invalid, remove.
03/20/19-18:02:56 DEBUG /home/fmstrat/.config/koreader/settings/lookup_history.lua.old.9  is invalid, remove.
03/20/19-18:02:56 DEBUG /home/fmstrat/.config/koreader/settings/wikipedia_history.lua  is invalid, remove.
03/20/19-18:02:56 DEBUG /home/fmstrat/.config/koreader/settings/wikipedia_history.lua.old.1  is invalid, remove.
```
So, I don't know, is this directory writable with enough freespace?

**Comment by Frenzie** [comment] 2019-03-20 22:24
Those are (presumably) some noise that needs fixing.

**Comment by Fmstrat** [comment] 2019-03-21 11:27
@Frenzie I don't believe this should be closed. The SDL issue has been fixed but I haven't had a chance to check the cached margin issue.

**Comment by Frenzie** [comment] 2019-03-21 12:05
I didn't, GH did. Apparently it thinks fixes comment means fixes issue too.

**Comment by pazos** [comment] 2019-08-11 15:52
@Fmstrat: could you still reproduce on latest stable?

**Closed** 2019-08-16 00:20 UTC
Labels: Desktop, need more info, out-of-date
