### ISSUE TITLE
toggle front light on / off in the status bar and frontlight auto-activation ?

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#4923] opened 2019-04-15 07:24 UTC
* KOReader version: 2019.04-25 ... 2019-04-13
* Device: KA1

1/ I updated to the last nightly yesterday. My status bar is set to display the frontlight intensity. I noticed that when I toggle the frontlight to on with a bottom left tap, the "off" in the status bar is not updated but It was before. Is this behaviour intended ?  The status bar update the value after a page turn.

2/ After a sleep and wake up I also noticed that the frontlight reactivates itself but even if it was off before I put the device to sleep... and the auto frontlight plugin is off...

Any idea ?

**Comment by cramoisi** [comment] 2019-04-15 07:34
my persistent says :  "KOBO_LIGHT_ON_START = -1"

**Comment by Frenzie** [comment] 2019-04-15 07:34
The second will be fixed by https://github.com/koreader/koreader/pull/4921#issuecomment-483035589. Pinging @NiLuJe about the status thing.

**Comment by cramoisi** [comment] 2019-04-15 07:37
@Frenzie : oh great !

**Comment by cramoisi** [comment] 2019-04-15 07:46
There is also something weird when I first boot koreader : I can't turn it on with a left bottom tap (the option is correctly set). Koreader keeps to say : the frontlight is off at each tap.

**Comment by Frenzie** [comment] 2019-04-15 07:54
Is that from KSM or Nickel?

**Comment by cramoisi** [comment] 2019-04-15 07:55
@ Frenzie : when I come from nickel using KFmon.

**Comment by cramoisi** [comment] 2019-04-15 08:01
After exiting koreader to nickel and relaunch koreader with kfmon, the setting in the frontlight menu are wiped : min Brightness is set to 0 so the toggle doesn't work. Once you manually change it, it's ok but it should keep the value and this value should be at least 1 if nothing set

**Comment by cramoisi** [comment] 2019-04-15 08:02
So I guess "KOBO_LIGHT_ON_START = -1" is broken (or there is no data found)

**Comment by Frenzie** [comment] 2019-04-15 08:18
There were some changes in #4871. That doesn't seem to feature in the diff though.

**Comment by cramoisi** [comment] 2019-04-15 11:43
yeah, and I forgot to record the build I was before update to last

**Comment by NiLuJe** [comment] 2019-04-15 14:03
What's the intended behavior with -1?

**Comment by NiLuJe** [comment] 2019-04-15 15:07
So, @cramoisi: What are your usual frontlight settings, in KOReader, to trigger that startup behavior?

**Comment by NiLuJe** [comment] 2019-04-15 16:32
Actually, the footer thing is not new, and it wasn't refreshing from the FL gesture control either ;).

**Comment by NiLuJe** [comment] 2019-04-15 16:36
Speaking of the FL gesture, it's now disabled in the FM. IIRC, that's new, was that an intended behavior, @Frenzie ?

(Not particularly complaining, as this is disabled on all my devices ;p).

**Comment by Frenzie** [comment] 2019-04-15 17:37
Umm, I never touched the plugin. :-)

**Comment by NiLuJe** [comment] 2019-04-15 17:48
I have no idea how it works, just though it might have been something to do with the multiswipe stuff, since I remember one commit mentioning inhibiting some stuff in the FM ;).

**Comment by cramoisi** [comment] 2019-04-15 18:21
@NiLuJe Sorry, I was afk :/ But you figured everything out I see

**Comment by cramoisi** [comment] 2019-04-15 18:22
(It was not a problem of exiting with light on or off. Did you were able to replicate the behaviour ? )

**Comment by cramoisi** [comment] 2019-04-15 19:07
@NiLuJe : the toggle thing is still non-functional after applying your PR

**Comment by cramoisi** [comment] 2019-04-15 19:10
1. Set my frontlight value to 50
2. Toggle on, toggle off
3. open a book, toggle on : it set from off (0) to 50
4. exit a book, exit koreader to nickel
5. launch koreader with KFMon, directly in the book
6. Toggle doesn't work
7. to the frontlight menu : the previous value set to 50 is now set to 0
8. Toggle set from 0 to 0, so it's always off

**Comment by Frenzie** [comment] 2019-04-15 19:32
I may have also noticed something odd with the frontlight not toggling until I manually set it to 1 but unless I'm in testing mode I mainly care about it being off.

**Comment by cramoisi** [comment] 2019-04-15 19:45
I did some test and the points 7 and 8 can't be replicated "manually" : setting a value in the frontlight menu re-enable the toggle functionality and even if you set 0 as a min value, the toggle will toggle from 0 to 1 (as it worked before). Also, the warmth setting is also reset :/ 

Setting  KOBO_LIGHT_ON_START = 0 leads to the same result

I only use the frontlight (set on 1) with left bottom tap when I woke up during the night to read when it's pitch-dark (easy to turn it on without much hassle) so if I need to turn on the light to set the damn thing or to remember if I did exit koreader before, it defeat the purpose of the whole thing :D

**Comment by NiLuJe** [comment] 2019-04-15 20:19
Okay, I can reproduce that *if*, and only if, I exit/restart KOReader with the FL off.

Although, if it is on, it doesn't actually pickup the correct value either, it stays as-is.

**Closed** 2019-04-15 22:04 UTC
Labels: Kobo, bug

**Comment by cramoisi** [comment] 2019-04-16 05:01
it doesn't change a thing for me :/ the toggle is still broken, and I got this even if I exit (or restart or reboot) with the FL manually set on a value.

**Comment by cramoisi** [comment] 2019-04-16 06:40
ok, somehow, it works after ota update ! thanks !
