### ISSUE TITLE
Hyphenation splits diacritics from cyrillic words

### ISSUE THREAD

**Issue by Vuizur** [koreader/koreader#8977] opened 2022-04-07 13:09 UTC
* KOReader version: 2022.03.1
* Device: Samsung Galaxy Tab A7

#### Issue
The issue can be seen in this screenshot (the word седьмо́м): 
![image](https://user-images.githubusercontent.com/29223849/162205012-bd233528-7d66-4597-9d53-be3b4bee4255.png)

The "cyrillic letter o" is split from its following "combining accute accent", which causes the accent to appear in the next line. It would be nice if the accent was instead kept on the letter.

**Comment by poire-z** [comment] 2022-04-07 13:33
Which hyphenation method/dict are you using ? (Typesetting menu, Typography > Hyphenation : Russian, Ukrainian, Bulgarian, Algorithmic ?)
Does this happen with all cyrillic books ?
I don't know if combining diacritics are commonly used, and if they are equivalent unicode single char for this o' - in which case it might be this particular book that we don't handle well.
Also, can you try with another hyphenation/typography language, including a non-cyrillic one like English, to see if it's an issue related to a specific dict.

In any case, can you try this book with an older KOReader, 2022.02 for example ?
I made some changes to character categorization recently, so I may have broken some things :/ I'd like to know if it's a new issue, or it if was already there before these changes...
ie. https://github.com/koreader/crengine/pull/468

**Comment by Vuizur** [comment] 2022-04-07 14:05
Typography rules are set to Russian. I think it does happen to all cyrillic books that have added stress marks. Added stress marks are not that common in books not aimed at learnears, but they are sometimes used in native books for disambiguation.
The acute accent does not exist in combination with the cyrillic letters as a precomposed character, for some reasons that is only the case for the grave accent. But I would say that the acute accent is more popular for marking stress.
All settings were set to Russian.
When I set the typography language to English, no words are being hyphenated. When I set it the hyphenation to algorithmic, the problem is much more common than on the standard Russian setting (lots of lonely stress marks).
I am 90% sure that the newest version broke it, I read a book with the older version and never noticed the error, and now it has the same problem.

**Comment by poire-z** [comment] 2022-04-07 14:51
OK :/
Can you check with current nightly ? https://build.koreader.rocks/download/nightly/ (or update channel dev via KOReader itself, not familiar with auto updates).
I made some other changes since 2003.01, related to char properties, https://github.com/koreader/crengine/pull/472

> I am 90% sure that the newest version broke it

I'd like a 100% certainty :) so, a test with an older stable.

**Comment by poire-z** [comment] 2022-04-07 17:14
OK, I can see the difference.
I think that the cause is that, before, these combining diacritics like U+0301 were considered word separators (because they had no specific flags). I made them being CH_PROP_MODIFIER so they can be considered part of a word. This was after the long hunt in #8843. I think this is still the right thing to do.
From https://github.com/koreader/crengine/commit/ed8fed64960779a0321a560f30a2d3cd3592b649 :
```diff
 // 0x0300:
-0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
-0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
-0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
-0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
-0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
-0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
-0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
-0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
+CH_PROP_MODIFIER, // 0300 (Mn) COMBINING GRAVE ACCENT
+CH_PROP_MODIFIER, // 0301 (Mn) COMBINING ACUTE ACCENT
+CH_PROP_MODIFIER, // 0302 (Mn) COMBINING CIRCUMFLEX ACCENT
+CH_PROP_MODIFIER, // 0303 (Mn) COMBINING TILDE
+CH_PROP_MODIFIER, // 0304 (Mn) COMBINING MACRON
```

Previously, being 0, they were considered a word separator, and, when hyphenating `седьмо́м`, it was getting 2 candidate words to try to hyphenate each independantly: `седьмо` and `м` - and you probably got some hyphenation inside `седьмо`.
Now, there is a single candidate: `седьмо'м`, and there is probably a rule in the russian hyph dict that allows a hyphenation after `мо` or `о`.
Or at least, there is no rule (haven't checked) that handle such combining diacritics, to prevent hyphenation before.

This is somehow a new issue that we are aware of, see https://github.com/koreader/crengine/pull/466#issuecomment-1059988914.
We need to solve it in a new way, we can't just revert to the previous situation.
If you tell me there's no precomposed о́ in Unicode, the idea of using NFC/NFKC normalization before hyphenation will not help (https://www.minaret.info/test/normalize.msp same results with your `седьмо́м`)...

Dunno if you can check if there's any such U+0301 in the utf8 Russian.pattern, but may be there is no, meaning our hyph dicts have no rule about combining diacritics (from the ones I've seen like French, we get the precomposed é è ô, but our accentuated characters are all available as precomposed).

We could force forbid/cancel hyphenation before a combining diacritic, but it feels not like the best solution, as the other rules would still be messed up (we would not allow hyphenation after it, or mathc any rule saying what happens between `о` and `м`...

May be an idea for such combining diacritics, when now getting the full real word, could be to strip them out (assuming no pattern file has support for them), remember the shiftings done, and try to hyphenate `седьмом`, and report back the shifting for the real hyphenation point.
Do you think in Russian, the hyphenation would be always the same without the diacritic or with ?

**Comment by Vuizur** [comment] 2022-04-08 08:51
Your attention to detail is impressive 👍. Now that you say it, the hyphenation did have the problem you mentioned previously and felt a bit "weird" when you focus on it.

> May be an idea for such combining diacritics, when now getting the full real word, could be to strip them out (assuming no pattern file has support for them), remember the shiftings done, and try to hyphenate седьмом, and report back the shifting for the real hyphenation point.
Do you think in Russian, the hyphenation would be always the same without the diacritic or with ?

I am sure it would always be the same. I think this approach is a good idea. I also can't imagine problems with it with other cyrillic languages 👍

**Comment by poire-z** [comment] 2022-04-09 11:07
Some preliminary attempt at fixing this, can you confirm these read well ?:
![image](https://user-images.githubusercontent.com/24273478/162569023-5d90f59c-1f50-4a43-87d2-bae557393728.png)
and with a better cyrillic font than the embedded one (because above, the diacriticized chars seem to come from a fallback font):
![image](https://user-images.githubusercontent.com/24273478/162569046-146c7bef-0760-4722-86a4-ff0ada3e5e8f.png)

(It will need more not fun tweaks: if you set left/right min hyphenation to 3, you don't want a a hyphen after the 3rd char if they are `м + о + U+0301 ` as it will look visually like 2 chars.)

**Comment by Vuizur** [comment] 2022-04-09 14:22
It looks great! I only checked the hyphenation for [готовность](https://ru.wiktionary.org/wiki/%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D1%8C), and it seems that in Wiktionary the hyphenation is different (one letter later). However, for other words that are hyphenated after a stressed character the hyphenation is correct, so your algorithm works correctly. 👍 It probably is an issue with the hyphenation dictionary or so (I don't know how it works).

**Comment by hius07** [comment] 2022-04-09 14:45
The same way of fixing is applicable for Ukrainian (dunno about Bulgarian).

**Comment by poire-z** [comment] 2022-04-09 19:33
> I only checked the hyphenation for [готовность](https://ru.wiktionary.org/wiki/%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D1%8C), and it seems that in Wiktionary the hyphenation is different (one letter later).
[...] It probably is an issue with the hyphenation dictionary or so (I don't know how it works).

Or a bug on my side :) When fixed, it gives this:
![image](https://user-images.githubusercontent.com/24273478/162587954-ed4f03ee-39f5-4be2-b03c-c32035a25292.png)

(You can also check with https://www.ushuaia.pl/hyphen/?ln=en : 
![image](https://user-images.githubusercontent.com/24273478/162588154-07b0f97e-68e4-41b0-9fd8-6d18acc0babb.png) )

This solution annoys me a bit though:
I can't think of any such word right now (giving some fictionnal example in parenthesis), but I think it's possible that some word would hyphenate differently whether it has a letter standalone (`me-tro`), or the same composed letter+accent (`mét-ro`). With this trick, we would hyphenate a word with letter+composing diacritic (`me'tro`) as with letter standalone (giving `mé-tro`)
I guess it's probably better than nothing, but the idea of using NFC composition could still be worthwhile (but more complicated than what I'm trying currently).

Also, we have some hyph dicts - even if only 3 - that contain such combining diacritics /  CH_PROP_MODIFIER:
```
Greek.pattern           78      0x1fbf Sk GREEK PSILI
Greek.pattern           59      0x1fbd Sk GREEK KORONIS
Latin.pattern           3781    0x0301 Mn COMBINING ACUTE ACCENT
Latin.pattern           284     0x035e Mn COMBINING DOUBLE MACRON
Latin.pattern           335     0x0361 Mn COMBINING DOUBLE INVERTED BREVE
Latin.pattern           55      0x0304 Mn COMBINING MACRON
Latin.pattern           43      0x0306 Mn COMBINING BREVE
Latin_liturgical.pattern 2      0x0301 Mn COMBINING ACUTE ACCENT
```
A quick look around in these files, and it seems they have composed chars, and so use these combining ones probably when there is no equivalent composed chars - so, proper books may contain these diacritics as there are no NFC quivalents.
With our trick, we would strip out these diacritics for hyphenation, and we would not match all these rules that contain them, so possibly doing wrong (or not the best) hyphenation.

Can you check with your russian books that contain these U+0301 if, for other accentuated characters where the composed char exists, they use it or still use combining diacritics?
(Hard time for me to try finding out accentuated cyrillic letters :) your [small letter io](https://www.fileformat.info/info/unicode/char/0451/index.htm) and [small letter short I](https://www.fileformat.info/info/unicode/char/0439/index.htm) looks like accentuated `e` and `N` to me :)
I'm not saying we shouldn't find a code solution for these, but if the book is proper and does use these combining diacritics only when no composed equivalent exists, may be the Russian hyph dict should be updated to contain these combinations (like probably the Latin and Greek ones were). Which could mean duplicated all the rules that contain `о` to have it replaced with `о́`, which would be ugly and expensive...

**Comment by NiLuJe** [comment] 2022-04-09 22:53
@poire-z: If I'm understanding what you're doing right, you might want to look at https://pypi.org/project/Unidecode/ for inspiration ;).

**Comment by poire-z** [comment] 2022-04-10 13:39
Well, Unidecode is surely too radical :) If we ever need to do some kind of stripping, we would just need NFC composition that utf8proc can do.
But I don't really want to transform anything, I just want to sweely skip (not killing them) some diacritics in a few places where they feel in the way :)

**Comment by poire-z** [comment] 2022-04-11 13:12
Hopefully fixed with https://github.com/koreader/crengine/pull/475.
(Although it's still not perfect - I tried to not break anything with Greek and Latin - but if Greek and Latin books would use the same kind of accentuation used in this Russian books, it could get messy.)

**Closed** 2022-04-14 18:43 UTC
