### ISSUE TITLE
Progress sync cannot input password field

### ISSUE THREAD

**Issue by dandelions** [koreader/koreader#7270] opened 2021-02-10 04:27 UTC
* KOReader version:2021.01.1 appimage
* Device: ubuntu20.04

#### Issue
when I open progress sync plugin,input username field,but i cannot input password field,the content i inputed is located in username field

**Comment by Frenzie** [comment] 2021-02-10 09:11
Duplicate of https://github.com/koreader/koreader/issues/7194. There are still some teething troubles to sort out with the direct typing form of input.

**Closed by Frenzie** 2021-02-10 09:11 UTC
Labels: bug, duplicate
