### ISSUE TITLE
Zsync is not working between Kindles & Android devices running KOReader

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#2223] opened 2016-08-17 12:40 UTC
that'll be very easy to push the books to the device

**Comment by Eduardomb22** [comment] 2016-08-17 12:45
Do u have a kindle or kobo?

**Comment by CyberAndrew** [comment] 2016-08-18 00:01
+1, smb (cifs) will be fine too.

**Comment by KenMaltby** [comment] 2016-08-18 00:37
How are you seeing this working?  USB to your device?  Telnet?  From a "cloud" source?  Not picturing how this would work.

**Comment by seacatwu** [comment] 2016-08-18 00:37
of course I have kpw,kpw3, kobo aura HD(broken)
DUOKAN on kpw provide ftp server, it's nice; usbnetwork is only can use.....

**Comment by seacatwu** [comment] 2016-08-18 00:39
I want to push the book and comics from my android phone which has external sd.

**Comment by KenMaltby** [comment] 2016-08-18 00:42
Why would KOReader be involved?

**Comment by Eduardomb22** [comment] 2016-08-18 00:45
@seacatwu u can set up a ftp server at android and use kterm with wget to access the ftp

**Comment by KenMaltby** [comment] 2016-08-18 00:49
If the phone can run KOReader and your kindles can, have you tried ZSync?

**Comment by seacatwu** [comment] 2016-08-18 00:54
I tried，but it not work. I mean Zsync

**Comment by KenMaltby** [comment] 2016-08-18 01:09
I am not sure how Kindles may handle it (ZSync), I can walk through how it works for KOReader on Kobo to KOReader on Android.  If there is anyone using ZSync between Kindles and Android, they might provide better advice.

**Comment by Eduardomb22** [comment] 2016-08-18 01:17
It is pretty easy to access with kterm and wget.

**Comment by lenisko** [comment] 2016-08-21 10:31
Idea with implementing FTP server as a plugin is not bad. But I doubt that anyone will pick this one.

**Comment by thotypous** [comment] 2016-08-21 12:42
You can copy files using SFTP (over ssh). It is as easy to use as FTP and is more secure.

 * Install the [USB Networking package](http://www.mobileread.com/forums/showthread.php?t=186645) in the Kindle.

 * See the `README_FIRST.txt` instructions inside the USB Networking package to learn how to configure a password or a ssh keypair for authentication.

 * Enable SSH over WiFi (edit `usbnet/etc/config`).

 * Connect your Android device and Kindle to the same wireless network. If you are on-the-go, you can set up the Android device as a WiFi hotspot and connect the Kindle to it.

 * Use an Android SFTP client to transfer the files, e.g. AndFTP.

**Comment by lenisko** [comment] 2016-08-21 13:41
SFTP is good alternative but.... it's slower & heavier for transferring files

**Comment by Eduardomb22** [comment] 2016-08-21 18:49
U can install kterm at kindle and use wget to access the ftp server into the android. I have it installed and I just enter the ip adress at kterm and it downloads the entire folder with wget. Pretty simple

**Comment by seacatwu** [comment] 2016-08-22 06:35
maybe it's hard for me. I mean wget....

**Comment by lenisko** [comment] 2016-08-22 11:12
@seacatwu there's few options:
1. Some day maybe you'll get FTP server on KOreader (easy one)
2. Configure SFTP for kindle (it's little harder but works fine. This one is slower than FTP but might not be noticeable with just epubs, mobis files)
3. Or... use @Eduardomb22 solution which is complicated comparing to SFTP.

**Comment by KenMaltby** [comment] 2016-08-22 11:52
So, is Zsync not working between Kindles & Android devices running KOReader? As long as we are only talking supported media files (ebook, pic, documents), it is an already functional part of KOReader.  It would be nice to have an easy wireless alternative to using the USB, for other, non-media, files as well.

Luck;
Ken

**Comment by seacatwu** [comment] 2016-08-22 23:12
Yes, Zsync is not working between Kindles & Android devices running KOReader.
I tried txt、pdf、zip, but it is not working.

**Comment by chrox** [comment] 2016-08-23 00:33
@seacatwu It should be a bug and I will look into this later.

**Comment by seacatwu** [comment] 2016-08-23 14:51
@chrox thank you

**Comment by pazos** [comment] 2020-03-10 00:02
Out of date issue, please open again if you find it useful, I cannot reproduce between android and cervantes

**Closed by pazos** 2020-03-10 00:02 UTC
Labels: bug, out-of-date
