### ISSUE TITLE
Crash when I try to search text

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#11493] opened 2024-02-25 12:07 UTC
* KOReader version: 2024.01
* Device: PocketBook 633 Color

#### Issue:
When I search for text to move forward to it in a book, that doesn't work, I have a crush bug here. 

##### `crash.log` 
![crash.log.txt](https://github.com/koreader/koreader/files/14396225/crash.log.txt)

I however paste a crush photo (Failed to upload photo 50 times) here:

stack traceback:
[C]: in function 'findText'
frontend/apps/reader/modules/readersearch.lua:371: in function 'search_func
frontend/apps/reader/modules/readersearch.lua: 184: in function <frontend/apps/reader/
modules/readersearch.lua:182>
frontend/apps/reader/modules/readersearch.lua: 352: in function onShowSearchDialog frontend/apps/reader/modules/readersearch.lua: 106: in function 'searchCallback
frontend/apps/reader/modules/readersearch.lua: 139: in function 'callback'
frontend/ui/widget/buttontable.lua:81: in function callback'
frontend/ui/widget/button.lua:472: in function 'handleEvent'
frontend/ui/widget/container/inputcontainer.lua: 262: in function 'handleEvent frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent
frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent
frontend/ui/widget/container/widgetcontainer.lua: 100: in function 'handleEvent" frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent
frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent
frontend/ui/uimanager.lua: 943: in function 'sendEvent'
frontend/ui/uimanager.lua:53: in function default
frontend/ui/uimanager, lua: 1436: in function 'handleInputEvent'
frontend/ui/uimanager.lua: 1534: in function 'handleInput
frontend/ui/uimanager, lua: 1578: in function 'run'
/reader.lua: 289; in main chunk
[C]: at 0x00013f6d
Process has been terminated by signal (SIGSEGV::SEGY MAPERRY
Segmentation fault

Please help me, tell me please how to fix this problem

**Comment by poire-z** [comment] 2024-02-25 13:24
Possible duplicate of #11409 ?
See if you have something like the screenshot on https://github.com/koreader/koreader/issues/11409#issuecomment-1912014787 on the last page of your book.

Please update your KOReader to a current nightly (or development channel in the update menu), and see if it is fixed.

**Comment by ZHANYLone** [comment] 2024-02-25 16:21
> Possible duplicate of #11409 ?
> See if you have something like the screenshot on https://github.com/koreader/koreader/issues/11409#issuecomment-1912014787 on the last page of your book.
> 
> Please update your KOReader to a current nightly (or development channel in the update menu), and see if it is fixed.

I updated the nightly version and it was fixed, thanks.

**Closed** 2024-02-25 16:49 UTC
