### ISSUE TITLE
cant select word in ocred two layer pdf

### ISSUE THREAD

**Issue by l126t** [koreader/koreader#4839] opened 2019-03-26 00:36 UTC
* KOReader version:V201903
* Device:kpw 2nd

#### Issue
If you try to select a word in two layer pdf, koreader will exit.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment] 2019-03-26 00:47
Potential duplicate of https://github.com/koreader/koreader/issues/4481

**Comment by l126t** [comment] 2019-03-26 02:48
Yes , It 's just identical to 4481.If I reflow page with option of English language , app work well,but with chinese will exit.

**Comment by NiLuJe** [comment] 2019-03-26 03:02
Thanks, closing this in favor of the earlier one, then ;).

**Closed by NiLuJe** 2019-03-26 03:02 UTC
Labels: duplicate, need more info
