### ISSUE TITLE
Battery "always" at same value

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1383] opened 2015-01-08 07:54 UTC
With the latest stable and nightly on my Kobo Aura the battery is always shown at 100%, for weeks.

It is clearly broken.

**Comment by hwhw** [comment] 2015-01-08 08:15
It did work before, I take it? Do you know what version you used when it still worked? There should not have been any changes to that specific code, though, so I'm curious...

**Comment by lightonflux** [comment] 2015-01-08 08:37
I think i have to specify the issue.

Since some version (will investigate further) koreader didn't always show 100% but only the value it read at start, so restarting koreader would change the battery display from 100% to 84%. So when i wasn't restarting korader it wouldn't change from 100%. 

At the moment my battery is really at 100% at least when i check with KSM. Looks that the room temperature makes a big difference in battery life. :)

I will do more testing and report later which versions are affected and if the problem is really koreader and not something below.

**Comment by Markismus** [comment] 2015-01-08 12:36
Kobo Aura H20 on v2014.11-13-gc041e7c remained at 85% for 2 days, exiting to filemanager changed battery to 79%, restarting to 78%. Can't upgrade: error while upgrading to v...-15-.... Battery at 73%. 

So at least the battery indicator still worked on the earlier version.

**Comment by WS64** [comment] 2015-01-08 21:34
I'm on v2014.11-3-g69b1cf9.
Battery values change all the time with that one on my Aura.

**Comment by chrox** [comment] 2015-01-18 03:21
I cannot reproduce this on KPW and PB840. 

Note that the battery capacity is not updated on every page turn by design. Usually the value is updated for every 10 page turns or a restart of the application. Is it possible that you didn't turn 10 pages or restart koreader app for weeks? If it's true, the behavior is expected.

**Comment by lightonflux** [comment] 2015-01-19 04:15
> If it's true, the behavior is expected.

Then that is probably the problem. I expected that koreader also updates the status when the device wakes up.

**Comment by chrox** [comment] 2015-01-19 05:07
That sounds reasonable. It will be fixed later.

**Closed** 2015-02-01 09:18 UTC
