### ISSUE TITLE
Landscape PDF - infinite waiting

### ISSUE THREAD

**Issue by Ebrehem** [koreader/koreader#1392] opened 2015-01-18 22:59 UTC
After changing the view from portrait to landscape, no touch can have any impact on koreader. It doesn't crash, but also doesn't do anything else. Sleep mode probably works, as the light is turning on and off. I can leave this state only by resetting the device. In landscape mode it has no problem with the document.

Unfortunately I can't upload the document to anywhere. I have cleared the cache file (I found only one outside cr3cache), but didn't help. I checked the crash log, it writes about inability to write.

Can it be the case, that it is too complicated and big and eats all the memory? (It is made from a powerpoint presentation of 140 pages, with graphics, tables, etc.).

**Comment by Ebrehem** [comment] 2015-01-18 23:04
Before going to sleep I decided to check again. PDF size is only 5.1 MB. Strange, in spite of reopening the document, cache is empty. Crash.log is 0 bytes. So no crash, but it simply doesn't work.

**Comment by hwhw** [comment] 2015-01-19 13:40
It's always a bit hard to say... A complex document in terms of having a big memory footprint is not always reflected in file size. Even a small file may need a considerable amount of memory. Especially troublesome are (semi-)transparent masks, I think.

**Comment by Ebrehem** [comment] 2015-01-20 07:54
In case of complicated PDF, should it not be broken also in the default portrait mode? (And it doesn't crash, it simply seems to be in and endless loop, though I have up after some minutes.) In portrait mode I was able to read the document (constantly adjusting margins), and it had normal response times, page turn max some seconds. In landscape mode the same - nothing works after I pressed Landscape button via touch. Sleep button seems working. Can it still be an issue with memory? What can I do to test it, without posting the document to anyone? (Unfortunately the PDFs I read are not public.)

**Comment by hwhw** [comment] 2015-01-20 08:13
Yes, probably, but impossible to tell without proper debugging. Well, in Landscape mode, it is rendered with a larger width - so it *does* make a difference. If it is to blame - I don't know.

This is only for a single PDF, right? If we can't reproduce, we can't properly debug, unfortunately.

**Comment by chrox** [comment] 2015-01-26 03:57
A Kindle Touch user also [reported](http://www.hi-pda.com/forum/redirect.php?goto=findpost&ptid=1078988&pid=29398628) that the device stopped responding to touch after change the screen to landscape mode with all releases after v2014.11-stable.

**Comment by chrox** [comment] 2015-03-31 01:45
I guess it's document specific and the document rendering eats too much memory on landscape mode. And since we cannot reproduce this and cannot fix it I will close this. Please feel free to reopen this if you find this issue on other documents that can be shared to us for debugging.

**Closed by chrox** 2015-03-31 01:45 UTC
