### ISSUE TITLE
Version 2020.10 Crashed when I exited from reading a book

### ISSUE THREAD

**Issue by red-riptide** [koreader/koreader#6793] opened 2020-10-14 18:56 UTC
1. Open a book and read
2. Exit from  reading via navigation or file list button
3. The reader will crash and show debug info about bad argument at blitbuffer.lua  987 line.

**Comment by gbyl** [comment] 2020-10-14 18:58
This has been fixed by the latest [nightly build](http://build.koreader.rocks/download/nightly/)

**Comment by red-riptide** [comment] 2020-10-14 19:01
Ok, thanks.

**Comment by gbyl** [comment] 2020-10-14 19:03
No problem. This is a duplicate of: https://github.com/koreader/koreader/issues/6790 and https://github.com/koreader/koreader/issues/6787

**Closed** 2020-10-14 19:11 UTC
Labels: duplicate
