### ISSUE TITLE
Window Blinks when closed during reading

### ISSUE THREAD

**Issue by du33169** [koreader/koreader#9439] opened 2022-08-15 15:59 UTC
* KOReader version: v2022.07
* Device: x86 Linux Laptop (Manjaro KDE)

### Issue

When closing a koreader window, it will blink once before fading out.
Occurs ONLY when any file is opened for reading。

It's hardly a bug but I can't tell it's normal.

### Steps to reproduce

1. start koreader (home page)
2. close it--no blink
3. start koreader again
4. open any file to read
5. close it--blink

|close from home page: no blink|close when reading: blink|
|---------|------|
| ![noblink](https://user-images.githubusercontent.com/46591250/184668794-fac16484-cdee-41cf-9e27-524f1379a25a.gif) | ![blink](https://user-images.githubusercontent.com/46591250/184668812-3f9830e2-6d36-4c9c-a1bf-75ac9f051c05.gif)|

(The terminal output/crash.log remained consistent in the two tests above)

**Comment by NiLuJe** [comment] 2022-08-15 18:05
IIRC, it's an SDL quirk with some drivers (let me guess.. nvidia? ^^).

**Comment by Frenzie** [comment] 2022-08-15 19:02
Nah, well, possibly an SDL quirk but not an Nvidia exclusive. But also a complete non-issue. ;-)

**Comment by offset-torque** [comment] 2022-08-16 10:23
> Nah, well, possibly an SDL quirk but not an Nvidia exclusive. But also a complete non-issue. ;-)

Yes and yes.
I can reproduce this on my KDE system with AMD open source drivers.
But yeah, I didn't even notice this until I saw this issue.

**Comment by NiLuJe** [comment] 2022-08-16 16:06
Cool, I rarely use the emulator, and vaguely remembered a weird nvidia-specific quirk on exit (and I'm on AMD now, so I can't really remember what said quirk was, but blinking stuff vaguely ringed a bell :D).

**Comment by Frenzie** [comment] 2022-08-16 16:27
PS Also definitely not an SDL quirk, unless you mean in the sense of the SDL abstraction within our own Device module.

**Comment by Frenzie** [comment] 2022-08-16 16:57
At some point while closing things init is called again. The flash of white is from https://github.com/koreader/koreader-base/blob/7fb47e46054ebf0499131db8f6fc006729795f3e/ffi/framebuffer_SDL2_0.lua#L23 which is there to prevent a flash of black or worse (weird broken effects).

This also happens in the file browser, but it simply closes faster so you can't see it.

This doesn't seem to happen on Kobo, so there's that.

**Comment by Frenzie** [comment] 2022-08-16 17:11
This works, and it looks like Device:saveSettings() is just a stub… there must've been some changes in the rest of the code since I wrote the original.
```diff
diff --git a/frontend/device/input.lua b/frontend/device/input.lua
index f6f04c09..a4cfbaff 100644
--- a/frontend/device/input.lua
+++ b/frontend/device/input.lua
@@ -540,14 +540,9 @@ function Input:handleKeyBoardEv(ev)
     -- quit on Alt + F4
     -- this is also emitted by the close event in SDL
     if self:isEvKeyPress(ev) and self.modifiers["Alt"] and keycode == "F4" then
-        local Device = require("frontend/device")
         local UIManager = require("ui/uimanager")
-
-        local save_quit = function()
-            Device:saveSettings()
-            UIManager:quit()
-        end
-        UIManager:broadcastEvent(Event:new("Exit", save_quit))
+        UIManager:broadcastEvent(Event:new("Close"))
+--         UIManager:broadcastEvent(Event:new("Exit"))
     end
 
     -- handle modifier keys
```

**Comment by NiLuJe** [comment] 2022-08-16 18:17
Huh, yeah, sounds good to me ;).

The `Exit` event seems to be tailored at stuff manually triggered, `Close` *should* do the job just fine, I don't recall if there's some widgets that could ignore it...

**Comment by Frenzie** [comment] 2022-08-16 20:09
The exit event only closes the program after you perform an action if there's a covering widget open, so close is necessary in any case. I suppose I could always stick an exit in a nextTick or some such but I didn't notice any issues with a quick test.

**Closed** 2022-08-17 07:19 UTC
