### ISSUE TITLE
Auto sleep function, battery discharges by accident presses

### ISSUE THREAD

**Issue by cuongtdc** [koreader/koreader#1604] opened 2015-08-26 10:13 UTC
Does anybody know how to enable the auto-sleep function in Koreader? 
Sometimes I press the power button by accident (for example when I put the ereader in my backpack) and it remains ON until battery goes 0 (because of the frontlight,...).

I guess it would be nice if we have the auto-sleep function in Koreader. like sleep after 10, 20, 30... mins if no action is performed, for instance

**Comment by Markismus** [comment] 2015-08-26 12:29
It is something that would need to be implemented. See #1356.

For now you could use a sleep cover or add a little neodymium magnet at the right place on the outside of your current cover. (You can find the right place by trial and error _after_ enabling "sleep cover" in Kobo Nickel's options.) When the cover is closed, the device is in standby.

I'm closing this issue because it is a duplicate of #1356.

**Closed by Markismus** 2015-08-26 12:29 UTC
