### ISSUE TITLE
KOReader reacts very slow on Inkpad 3 

### ISSUE THREAD

**Issue by trekk2810** [koreader/koreader#3875] opened 2018-04-14 11:27 UTC
* KOReader version: All versions with Inkpad 3 support
* Device: Inkpad 3

KOReader on Inkpad 3 is painfully slow when configuring. Changing fontsize or style takes minutes. Sometimes it seems to freeze, but maybe it is just soooo slow.

[crash.log](https://github.com/koreader/koreader/files/1910300/crash.log)

**Comment by Frenzie** [comment] 2018-04-14 11:41
Probably a duplicate of #3419 #3540 #3561. Apparently the PocketBook suspends at random. You can give @mk-f 's plugin from the PR a try but I don't know the details.

**Comment by trekk2810** [comment] 2018-04-14 16:14
Thx, Frenzi! I'll take a look.

**Comment by Frenzie** [comment] 2019-03-07 14:41
Presumably fixed by #4712. If not, please reopen or create a new issue.

**Closed by Frenzie** 2019-03-07 14:41 UTC
Labels: PocketBook
