### ISSUE TITLE
History as initial interface instead explore files

### ISSUE THREAD

**Issue by AliLozano** [koreader/koreader#2041] opened 2016-05-23 16:00 UTC
I recently installed Koreader in my kobo glo hd, I like the way it highlight compared with nickel, but I have some suggestions, for example could we use history as initial interface instead use the file explorer, is it posible?
Three changes: 

- Initial interface: History or Recent books (maybe with preview or book cover)
- Home button: Go to Initial interface(History)
- Remove history from pokeball (it's not intuitive)

I'm new and I don't know the project philosophy, I'm java and python developer I someone could explain me how can I make these changes, maybe I could make a pull request.

Thanks a lot.

**Comment by Frenzie** [comment] 2016-05-23 16:28
Probably a duplicate of #1313. I think @chrox is working on a new homescreen.

**Comment by houqp** [comment] 2016-05-23 17:35
@AliLozano reader menus are managed by https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readermenu.lua. Lua is a very simple lanaguage, much easier to learn than Java and Python ;P

As @Frenzie said, chrox is working on the new home screen, so the experience will be much improved after that work is merged to master.

**Comment by Frenzie** [comment] 2016-05-23 18:04
Dunno, Python is very easy. But yes, so is Lua.

**Comment by houqp** [comment] 2016-05-24 01:38
Python is probably easier to learn syntax wise for beginners. But if you go deeper, there are subtle black magics :) While Lua is much simpler in design. I was able to read through and understand the compiler and vm source code in a week. Pretty sure it's going to take much longer for Python :P LuaJIT, on the other hand, is a different story...

**Comment by AliLozano** [comment] 2016-05-24 04:33
Nice, I will review the code, learn and test, somebody knows when new home screen will be available?.

**Comment by houqp** [comment] 2016-05-24 04:47
I don't @chrox set a hard deadline for this. Like all of us, he is also only working on it in this sparing time :)

**Comment by chrox** [comment] 2016-06-30 13:55
This will be implemented in #1790. So closing this in favor of #1790.

**Closed by chrox** 2016-06-30 13:55 UTC
Labels: enhancement
