### ISSUE TITLE
Front light toggles off/off

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#4925] opened 2019-04-15 21:50 UTC
* KOReader version: v2019.04-27-g7e06db9_2019-04-14
* Device: Kobo Aura One

#### Issue
Toggling the front light stops working

#### Steps to reproduce
Switch the Brightness manager (cog wheel, taps and gestures, second item) off.
Set tap bottom left to light on/off.
Set brightness to 1% (the minimum).
Toggle the light off by tapping the bottom left corner.
Exit KOReader (into KSM)
Start KOReader
Now try to toggle the light on.  It will say "Light switched off" at each tap.

##### `crash.log` (if applicable)
N/A

**Comment by NiLuJe** [comment] 2019-04-15 22:02
Should be fixed w/ #4924 ;).

**Closed by NiLuJe** 2019-04-15 22:02 UTC
Labels: Kobo, bug

**Comment by Biep** [comment] 2019-04-17 10:16
Now it is worse: the light spontaneously switches on every few minutes, though the toggle doesn't switch - tapping lower left says "Switching frontlight on" (and it stays on), and retapping switches it off and says so - for a minute or so, after which it switches on again by itself.
Version v2019.04-27-g7e06db9_2019-04-14
(Hamburger -> Version shows this, with the last "4" on its own on a new line..)

**Comment by NiLuJe** [comment] 2019-04-17 13:15
Do you happen to have any of the frontlight plug-ins enabled?

**Comment by Biep** [comment] 2019-04-17 14:08
Not to my knowledge, or as far as I can see.  I didn't even know there were any.
The module that allows one to change brightness and colour by swiping vertically is switched off.

**Comment by NiLuJe** [comment] 2019-04-17 14:22
I'd suggest trying a clean install, because this makes no sense, and @cramoisi confirmed that the current OTA fixed it on his KA1 :/.

**Comment by Biep** [comment] 2019-04-17 15:33
OK.  Do you have the link for the nightly?
I suppose I simply delete koreader in .adds and then put the nightly there..

**Comment by NiLuJe** [comment] 2019-04-17 15:35
As ever, http://build.koreader.rocks/download/nightly/ ;).

You can simply rename your current folder for a quick swap, no need to delete everything (especially if you want to keep some settings around *after doing the tests* ;).

**Comment by Frenzie** [comment] 2019-04-17 15:35
http://build.koreader.rocks/download/nightly/

Today's: http://build.koreader.rocks/download/nightly/v2019.04-32-g558e71c_2019-04-16/koreader-kobo-arm-kobo-linux-gnueabihf-v2019.04-32-g558e71c_2019-04-16.zip

**Comment by Biep** [comment] 2019-04-17 15:37
Thanks!

**Comment by cramoisi** [comment] 2019-04-17 15:53
@Frenzie I've just noticed now that the directories of nightly are not sorted by date anymore :p

**Comment by Frenzie** [comment] 2019-04-17 15:59
They've never been. They're sorted by "stupid computer".

**Comment by cramoisi** [comment] 2019-04-17 16:03
ok then I think it's related to the folder name then. I was pretty sure I always download the last one to update so I didn't even notice they were up in the list (since the 10 I download my update from gitlab oO :D )

**Comment by houqp** [comment] 2019-04-18 05:04
anyone interested in making the download index page fancy?

https://github.com/aperezdc/ngx-fancyindex
https://www.nginx.com/resources/wiki/modules/fancy_index/
https://github.com/Naereen/Nginx-Fancyindex-Theme

**Comment by NiLuJe** [comment] 2019-04-18 05:06
Way ahead of you ;).

http://koreader.ak-team.com \o/

**Comment by houqp** [comment] 2019-04-18 05:28
That looks very nice, are you using nginx plugin?

**Comment by NiLuJe** [comment] 2019-04-18 05:35
It is fancy index (the fork w/ natural sorting, since a few days, when this
came up on gitter with @Frenzie), and one of the themes listed on GitHub.

I'll double check later today ;).

**Comment by Frenzie** [comment] 2019-04-18 06:57
And note that FancyIndex itself doesn't do proper sorting, only that fork.

**Comment by NiLuJe** [comment] 2019-04-18 17:14
Yup, the fork is [here](https://github.com/foghawk/ngx-fancyindex), I'm using [this theme](https://github.com/TheInsomniac/Nginx-Fancyindex-Theme), and [here's](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/NGINX/Tyrande/fancyindex.conf) my config.

**Comment by Biep** [comment] 2019-04-19 10:55
I have renamed the old KOReader and installed version v2019.04-32-g558e71c_2019-04-16.  Indeed the problem of the autoillumination seems to be resolved this way.
I did find some other issues, however:
* I cannot set the number of items per page in the file explorer.  That is, I can set it, but it has no effect: I always get 10 items.  Only if I start KOReader in Start with: last file mode I see the requested number of items for a second, before the view switches to 10 items again.
* I cannot read the last few lines of several documents (two attached) simply by paging: they remain "below the bottom of the last screen".  Tapping the top left corner twice changes the problem to tiling (the top of the screen reproduced below the end of the document).  All this in "Zoom to content width" mode.
[Mysticism and Mediation.pdf](https://github.com/koreader/koreader/files/3097866/Mysticism.and.Mediation.pdf)
[The Real Guide to Fake Barns_ A Catalogue of Gifts for your Epistemic Enemies.pdf](https://github.com/koreader/koreader/files/3097869/The.Real.Guide.to.Fake.Barns_.A.Catalogue.of.Gifts.for.your.Epistemic.Enemies.pdf)
* Often reading documents with unrecognised endnotes, and bookmarking the page with the current endnote, I switched the swipes for "Go to latest bookmark" (now E,W - jump to the end) and "Back to previous location" (now W,E - jump back).  However, both swipes take me to the bookmark now, despite the menu indicating the correct actions.  Assigning "Back to previous location" to NE,SW makes that one jump either to the bookmarked page, or (rarely) to seemingly random other pages.

Is this just me again, or are these genuine problems?

**Comment by NiLuJe** [comment] 2019-04-19 13:53
@Biep: The "items per page" setting only seems to affect the "Classic" (legacy) view. I don't recall if that's by design or a genuine bug, but at least that I can reproduce ;).

**Comment by gerhaher** [comment] 2019-04-20 09:51
> Now it is worse: the light spontaneously switches on every few minutes, though the toggle doesn't switch - tapping lower left says "Switching frontlight on" (and it stays on), and retapping switches it off and says so - for a minute or so, after which it switches on again by itself. 

This happen to me too. With latest nightly (v2019.04-44-g4371422_2019-04-19/ )

> I'd suggest trying a clean install, because this makes no sense, and @cramoisi confirmed that the current OTA fixed it on his KA1 :/.

> Indeed the problem of the autoillumination seems to be resolved this way.

So I disagree with the above. It's not fixed on my KA1 - after a clean installation.


If I disable the auto warmth feature, the problem disappears. Maybe @cramoisi & @Biep missed that?

**Comment by cramoisi** [comment] 2019-04-20 10:34
@gerhaher I don't use the auto warmth feat. I'll check asap

**Comment by cramoisi** [comment] 2019-04-20 10:53
@gerhaher : when I enable the auto warmth feat, the frontlight toggle to on at 1% (the value I set). I switch it to off with the bottom left tap and I tried make it enable itself (dark room, etc) without success. So on my side (and for now) everything is fine and as intended. I will read with the option enable all the afternoon and let you know if anything spooky happens.

**Comment by gerhaher** [comment] 2019-04-20 11:54
I think it works something like this for me:

1. If I toggle on the light, and then restart KOReader, and then toggle off light, the issue appears for me, i. e. the light will spontaneously switches on after a few minutes.

2. If I toggle off light and then restart KOReader, the issue is not there.

3. If I restart KOReader after the light has spontaneously switched on as in 1, the issue is not there.

**Comment by NiLuJe** [comment] 2019-04-20 13:12
Warmth is intrinsically tied to brightness on the
KA1, so that might actually make some sense, thanks for the details.

I'll look into it, but since I don't have a device that behaves that way,
it might be a tad trickier...

**Comment by cramoisi** [comment] 2019-04-20 13:54
@gerhaher I tried your 1 and read for 2 hours but didn't get any weird behaviour... If any of you have an idea...

**Comment by NiLuJe** [comment] 2019-04-20 14:44
I don't *think* KSM vs. KFMon should impact this (at least not directly).

But, what booting through KFMon ensures is that you have *sane* Nickel frontlight/warmth configs, and that's what we use & sync with the default KOBO_LIGHT_ON_START value ;).

**Comment by cramoisi** [comment] 2019-04-20 14:47
Yup  it's just I'm out of idea to replicate the thing and it seems the only difference is the way we get into Koreader

**Comment by NiLuJe** [comment] 2019-04-20 14:57
Without having looked at the code yet, given the fact that setting the warmth *has to* set the brightness on the KA1, the autowarmth plugin can *probably* cause the light to go on when it tries to, adjust the warmth.

I'll double check, and try to nerf it to only update the internal warmth tracking variable instead if the FL is off ;).

**Comment by NiLuJe** [comment] 2019-04-20 14:58
(On newer (Mk.7) devices, we can set the warmth without affecting the brightness).

**Comment by cramoisi** [comment] 2019-04-20 14:59
It did enable the brightness when you toggle auto to on (or off) but I have yet to make the thing adjusting anything

**Comment by NiLuJe** [comment] 2019-04-20 15:15
i.e., does this simple patch help?

```diff
diff --git a/frontend/device/kobo/powerd.lua b/frontend/device/kobo/powerd.lua
index 7f186742..bc8d8b18 100644
--- a/frontend/device/kobo/powerd.lua
+++ b/frontend/device/kobo/powerd.lua
@@ -281,7 +281,7 @@ function KoboPowerD:calculateAutoWarmth()
                          when = 180,
                          repeated = true,
                          executable = function()
-                             if self.auto_warmth then
+                             if self.auto_warmth and self:isFrontlightOnHW() then
                                  self:setWarmth()
                              end
                          end,
```

**Comment by NiLuJe** [comment] 2019-04-20 15:20
Scratch that, better fix:

```diff
diff --git a/frontend/device/kobo/powerd.lua b/frontend/device/kobo/powerd.lua
index 7f186742..52a5e960 100644
--- a/frontend/device/kobo/powerd.lua
+++ b/frontend/device/kobo/powerd.lua
@@ -240,7 +240,12 @@ function KoboPowerD:setWarmth(warmth)
         self:calculateAutoWarmth()
     end
     self.fl_warmth = warmth or self.fl_warmth
-    self.fl:setWarmth(self.fl_warmth)
+    -- Don't turn on legacy NaturalLight devices just for the sake of setting the warmth!
+    -- We can only set wamrth independently of brightness on devices with a mixer.
+    -- On others, calling setWarmth will actually set the brightness, too!
+    if self:hasNaturalLightMixer() or self:isFrontlightOnHW() then
+        self.fl:setWarmth(self.fl_warmth)
+    end
 end
 
 -- Sets fl_warmth according to current hour and max_warmth_hour
```

**Comment by gerhaher** [comment] 2019-04-20 16:54
> how does your kobo is configured ? tools / adv settings > "KOBO_LIGHT_ON_START" (last page)
> Mine is at -1 ; imho it should stay like that. KOBO_SYNC_BRIGHTNESS_WITH_NICKEL to false.

KOBO_LIGHT_ON_START = -2
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true

> Could you consider to switch to KFMon ? :D

No!   :-)

> If that does the trick

With that KOReader crashed for me. It happened when I toggled (using the frontlight dialog). 
It didn't crash when I toggled with tapping left corner.

However I saw no spontaneous switch light on.

**Comment by NiLuJe** [comment] 2019-04-20 17:03
Oh, right. I see it. self is powerd, not device. -_-".

**Comment by NiLuJe** [comment] 2019-04-20 17:04
Less crashy patch :D.

```diff
diff --git a/frontend/device/kobo/powerd.lua b/frontend/device/kobo/powerd.lua
index 7f186742..54e8f299 100644
--- a/frontend/device/kobo/powerd.lua
+++ b/frontend/device/kobo/powerd.lua
@@ -240,7 +240,12 @@ function KoboPowerD:setWarmth(warmth)
         self:calculateAutoWarmth()
     end
     self.fl_warmth = warmth or self.fl_warmth
-    self.fl:setWarmth(self.fl_warmth)
+    -- Don't turn the light back on on legacy NaturalLight devices just for the sake of setting the warmth!
+    -- That's because we can only set warmth independently of brightness on devices with a mixer.
+    -- On older ones, calling setWarmth *will* actually set the brightness, too!
+    if self.device:hasNaturalLightMixer() or self:isFrontlightOnHW() then
+        self.fl:setWarmth(self.fl_warmth)
+    end
 end
 
 -- Sets fl_warmth according to current hour and max_warmth_hour
```

**Comment by gerhaher** [comment] 2019-04-20 17:26
> Less crashy patch :D.

Yeah, seems fine. I see no issue for the moment. 

I will read more tonight. If I find anything I'll report tomorrow.

Cheers!

**Comment by Biep** [comment] 2019-04-20 18:52
With the clean install the front light doesn't switch on spontaneously anymore - but it does switch **off** spontaneously.
I reverted to nickel for a while, but there the light behaves normally, so I don't suspect a hardware failure.
Can anybody reproduce this?  It is exceedingly frustrating..

**Comment by Biep** [comment] 2019-04-20 19:06
> @Biep: The "items per page" setting only seems to affect the "Classic" (legacy) view. I don't recall if that's by design or a genuine bug, but at least that I can reproduce ;).

It is irritating - especially as jumping to a letter doesn't work anymore either (another bug).  That means lots of paging in order to find the entry I want.

**Comment by Biep** [comment] 2019-04-20 19:19
Seeing that autowarmth is mentioned - it has long been the case that when opening my KA1 it would take a minute or more before the warmth was suddenly set to the correct value for the time of the day.  Waking up or starting KOReader ought to set the warmth to the correct value.

**Comment by NiLuJe** [comment] 2019-04-20 20:55
Both startup & resume run a warmth calculation. I broke it, but I fixed it ;p.

**Comment by Biep** [comment] 2019-05-02 12:08
I still have the problem that toggling the light on will have it switch of automatically after 1-3 minutes.  Don't have my Kobo Aura One handy, but I updated a few days ago.

**Comment by NiLuJe** [comment] 2019-05-02 15:20
Ah. That's the other way around, then. I assume the interval corresponds to an autowarmth calculation?

**Comment by Biep** [comment] 2019-05-02 19:10
I guess so.  I have timed it with the clock in the status bar, and it seems compatible with a roughly one-minute rhythm.
KOReader doesn't know the light is off: the status bar keeps showing it as on, and I need to tap the toggle corner twice to switch it on again.

BTW: I'd really like to have the possibility to toggle both the light and night mode with a single tap.

**Comment by NiLuJe** [comment] 2019-05-02 19:37
Huh. That issue should be fixed.

How do you launch KOReader?
Did you tweak KOBO_LIGHT_ON_START?
What are your usual frontlight settings?
How exactly are you toggling it on?

**Comment by NiLuJe** [comment] 2019-05-02 19:44
Would this help, by chance?

```diff
diff --git a/frontend/device/kobo/powerd.lua b/frontend/device/kobo/powerd.lua
index 54e8f299..0d1e36a5 100644
--- a/frontend/device/kobo/powerd.lua
+++ b/frontend/device/kobo/powerd.lua
@@ -149,7 +149,7 @@ function KoboPowerD:init()
             -- Use setIntensity to ensure it sets fl_intensity, and because we don't want the ramping behavior of turnOn
             self:setIntensity(self:frontlightIntensityHW())
         else
-            -- Use setBrightnes so as *NOT* to set hw_intensity, so toggle will still (mostly) work.
+            -- Use setBrightness so as *NOT* to set hw_intensity, so toggle will still (mostly) work.
             self.fl:setBrightness(0)
             -- And make sure the fact that we started with the FL off propagates as best as possible.
             self.initial_is_fl_on = false
@@ -323,6 +323,10 @@ function KoboPowerD:turnOffFrontlightHW()
     --       we only sync the state of the main process with the final state of what we're doing in the forks.
     -- And update hw_intensity in our actual process ;).
     self.hw_intensity = self.fl_min
+    -- NOTE: And don't forget to update sysfs_light, too, as a real _setIntensity would via setBrightness
+    if self.fl then
+        self.fl.current_brightness = self.fl_min
+    end
     self:_decideFrontlightState()
     -- And let the footer know of the change
     if package.loaded["ui/uimanager"] ~= nil then
@@ -356,6 +360,10 @@ function KoboPowerD:turnOnFrontlightHW()
     --       we only sync the state of the main process with the final state of what we're doing in the forks.
     -- And update hw_intensity in our actual process ;).
     self.hw_intensity = self.fl_intensity
+    -- NOTE: And don't forget to update sysfs_light, too, as a real _setIntensity would via setBrightness
+    if self.fl then
+        self.fl.current_brightness = self.fl_intensity
+    end
     self:_decideFrontlightState()
     -- And let the footer know of the change
     if package.loaded["ui/uimanager"] ~= nil then
```

**Comment by Biep** [comment] 2019-05-05 12:54
> How do you launch KOReader?

From KSM

> Did you tweak KOBO_LIGHT_ON_START?

Not to my knowledge.

> What are your usual frontlight settings?

Toggling between Off and 1%
I switched off the thingie that allows one to set brightness and colour by swiping the sides, and then set the corner toggle on again.

> How exactly are you toggling it on?

Toggling by tapping the lower left corner.

What private information is stored by KOReader?  If I zip the folder and drop it here, would that help you?
I'd like to remove any passwords and the like that might be hidden in there beforehand, though..

**Comment by NiLuJe** [comment] 2019-05-05 14:25
Do you start koreader with the light on or off?

I don't have an Aura One, so sending me a copy of your settings wouldn't
help ;).

**Comment by NiLuJe** [comment] 2019-05-05 15:53
NOTE: Since you haven't touched `KOBO_LIGHT_ON_START`, it should start with Nickel's FrontLight/NaturalLight settings. So, what are those?

And which FW version are you running?

**Comment by Biep** [comment] 2019-05-05 18:47
The light is off when starting (in general - I once had a crash into KSM that left the light on, and it was still on when restarting KOReader).  I have natural light set through KOReader.
Don't have my e-reader here, so I cannot check for the exact settings.
What is FW?

**Comment by NiLuJe** [comment] 2019-05-05 20:24
FirmWare ;). It's in the device info section of Nickel's settings page.

That vaguely looks like you may not actually have Nickel frontlight
settings stored, which probably doesn't help...
