### ISSUE TITLE
[ANR]: KOReader isn't responding after changing font size

### ISSUE THREAD

**Issue by xversion1** [koreader/koreader#11073] opened 2023-11-04 04:24 UTC
* KOReader version: KOReader 2023.10 "Ovis"
* Device: Samsung Galaxy Tab S9 FE

#### Issue
KOReader is not responding after change fonts or fonts size and Paragraph spacing. I think it would be like this after changing any styles. There's page icon at the top-left, after this icon changes to {itsefl and Ouroboros arrows}, KOReader doesn't respond anymore, and the screen show pop-up: KOReader isn't responding with 2 options: Close app and Wait. Close app and reopen KOReader makes every changes gone.

#### Steps to reproduce
1. Open a epub file
2. Change font size, or font size and paragraph spacing
3. Wait until the icon at the top-left looks like a page with 2 bend arrows.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/13255801/crash.log)

**Comment by Frenzie** [comment] 2023-11-04 10:04
There's not much that can be done about that right now. Most documents will recalibrate in less than a second, but I guess you found a really big and heavy one.

Feel free to attach it using the ScrambleEbook plugin (if it's not public domain) so we can see if there's anything that could be done about it https://www.mobileread.com/forums/showthread.php?t=267998

**Comment by xversion1** [comment] 2023-11-04 11:10
> but I guess you found a really big and heavy one.

I thought so at first, so I tried on a few short ebooks but it just gave the same result. Like this attached one for example (no need to scamble, I made this ebook out of free public content)
[Handwriting Chinese characters_ The minimu - Harvey Dam.zip](https://github.com/koreader/koreader/files/13256432/Handwriting.Chinese.characters_.The.minimu.-.Harvey.Dam.zip)
Note that small or big heavy files all can be changed font/styles normally on my phone and my Kindle.

**Comment by Frenzie** [comment] 2023-11-04 11:53
I don't really see anything odd there at a glance (i.e., it's fast enough). Note that you can relatively easily trigger such a message on Android by tapping quickly; it's just that the whole situation is fairly unlikely to happen when something takes less than, say, 2 seconds.

**Comment by xversion1** [comment] 2023-11-04 12:59
> Note that you can relatively easily trigger such a message on Android by tapping quickly

I thought of this too so I just left the device there for very long time. In this case, when I came back and unlock it, KOReader just closed without any trace. Reopened it just saw all (style) adjustments back to default.

**Comment by mergen3107** [comment] 2023-11-04 13:46
Can you try partial rendering? Top menu: Gear - Partial rendering.

**Comment by xversion1** [comment] 2023-11-04 13:52
> Can you try partial rendering? Top menu: Gear - Partial rendering.

Could you be mỏe specific with the path. I didn't see Partial rendering in Top Menu --> Gear?

**Comment by mergen3107** [comment] 2023-11-04 13:56
@xversion1 
Sorry, missed a menu: Gear - **Document** - Partial rendering.

**Comment by xversion1** [comment] 2023-11-04 13:59
> @xversion1 Sorry, missed a menu: Gear - **Document** - Partial rendering.

It's already enabled by default.

**Comment by mergen3107** [comment] 2023-11-04 14:01
Ah, I see. Sorry, missed step 3 in your OP. I can't reproduce it on my Onyx Boox (Android 10). Can you try disabling partial rendering?

**Comment by xversion1** [comment] 2023-11-04 14:10
> Ah, I see. Sorry, missed step 3 in your OP. I can't reproduce it on my Onyx Boox (Android 10). Can you try disabling partial rendering?

Like I said, I have KOReader on several devices and only on Tab S9 this issue happens. No wonder you can't reproduce it on Boox (I have a Boox too). 
But hey, uncheck Enable Partial rendering works. It's even faster than Enable Partial rendering. I don't even see the page icon at the top-left appear, font and styles change, like, straightaway. 
Strange that I thought aren't Enable Partial rendering supposed to make thing work faster?

**Comment by mergen3107** [comment] 2023-11-04 14:20
Alright, @poire-z 
Can you please have a look? Seems like it hiccups on Partial Re-rendering

**Comment by Frenzie** [comment] 2023-11-04 14:41
> Strange that I thought aren't Enable Partial rendering supposed to make thing work faster?

For many documents (particularly on faster processors like presumably in this Tab S9) it's still a lot faster but not in a very perceptible manner because even the full document takes only half a second.

**Comment by hugleo** [comment] 2023-11-04 14:50
You can use logcat for that catch some logs.

adb logcat KOReader:* ActivityManager:* *:S

If you change the font and don't click in the document screen just yet and wait you will see log lines like:

11-04 11:35:19.845  1853  2831 W ActivityManager: Sending non-protected broadcast miui.extm.action.mark from system uid 1000 pkg android. Callers=com.android.server.am.ActivityManagerService.broadcastIntentLocked:14886 com.android.server.am.ActivityManagerService.broadcastIntentInPackage:15071 com.android.server.am.ActivityManagerService$LocalService.broadcastIntentInPackage:17640 com.android.server.am.PendingIntentRecord.sendInner:511 com.android.server.am.PendingIntentRecord.sendWithResult:309 
11-04 11:35:20.081  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 280044.441845
11-04 11:35:20.081  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 280044.441845
11-04 11:35:20.081  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 182.83071899414, time: 280044.441845
11-04 11:35:20.081  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 218.87005615234, time: 280044.441845
11-04 11:35:20.082  1516  1559 V KOReader: input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 280044.441845
11-04 11:35:20.082  1516  1559 V KOReader: slot 0 in tap state...
11-04 11:35:20.082  1516  1559 V KOReader: set up hold timer
11-04 11:35:20.083  1516  1559 V KOReader: AutoTurn: onInputEvent
11-04 11:35:20.161  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 280044.523682
11-04 11:35:20.161  1516  1559 V KOReader: input event => type: 3 (EV_ABS),
....

11-04 11:35:21.210  1516  1559 V KOReader: _stepRerenderingAutomation( nil ), currently  1
11-04 11:35:22.212  1516  1559 V KOReader: _stepRerenderingAutomation( nil ), currently  1
11-04 11:35:23.214  1516  1559 V KOReader: _stepRerenderingAutomation( nil ), currently  1
11-04 11:35:24.216  1516  1559 V KOReader: _stepRerenderingAutomation( nil ), currently  1
11-04 11:35:25.219  1516  1559 V KOReader: _stepRerenderingAutomation( nil ), currently  1

....

multiples _stepRerenderingAutomation lines will be in the log and as soon as you click on the document area you'll see lines like:


11-04 11:35:46.560  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 280070.920462
11-04 11:35:46.560  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 280070.920462
11-04 11:35:46.560  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 272.74746704102, time: 280070.920462
11-04 11:35:46.560  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1133.4888916016, time: 280070.920462
11-04 11:35:46.560  1516  1559 V KOReader: input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 280070.920462
11-04 11:35:46.561  1516  1559 V KOReader: GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_MONOTONIC
11-04 11:35:46.561  1516  1559 V KOReader: slot 0 in tap state...
11-04 11:35:46.561  1516  1559 V KOReader: set up hold timer
11-04 11:35:46.561  1516  1559 V KOReader: AutoTurn: onInputEvent
11-04 11:35:46.655  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 280071.019243
11-04 11:35:46.655  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: -1, time: 280071.019243
11-04 11:35:46.655  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 272.74746704102, time: 280071.019243
11-04 11:35:46.655  1516  1559 V KOReader: input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 
...

11-04 11:35:50.406  1516  1559 V KOReader: _refresh: Enqueued ui update for region 0 0 1080 58 dithering: true
11-04 11:35:50.407  1516  1559 V KOReader: setDirty ui from widget ReaderUI w/ region 0 0 1080 58 dithering: true
11-04 11:35:50.407  1516  1559 V KOReader: painting widget: ReaderUI
11-04 11:35:50.409  1516  1559 V KOReader: readerview painting "1080x2307+0+0" to 0 0

...

11-04 11:35:53.739  1516  1559 V KOReader: close widget: table: 0x6f64b110c8
11-04 11:35:53.752  1516  1559 V KOReader: Lower widget ReaderUI covers the full screen
11-04 11:35:53.760  1516  1559 V KOReader: attempted to close a nil widget
11-04 11:35:53.760  1516  1559 V KOReader: clear selection
11-04 11:35:53.760  1516  1559 V KOReader: closing reader
11-04 11:35:53.793  1516  1559 V KOReader: closing document
11-04 11:35:53.795  1516  1559 V KOReader: ReaderFooter: unschedule autoRefreshFooter
11-04 11:35:53.795  1516  1559 V KOReader: ReaderCoptListener.headerRefresh unscheduled
11-04 11:35:53.796  1516  1559 V KOReader: UIManager:allowStandby, counter decreased to 0
11-04 11:35:53.796  1516  1559 V KOReader: cre cache used: /storage/emulated/0/koreader/cache/cr3cache/Handwriting_-vey_Dam.epub.f8d0a490.1.cr3
11-04 11:35:53.797  1516  1559 V KOReader: AutoTurn: onCloseDocument
11-04 11:35:53.797  1516  1559 V KOReader: CoverImage: onCloseDocument
11-04 11:35:53.881  1516  1559 V KOReader: close widget: ReaderUI
11-04 11:35:53.958  1516  1559 V KOReader: DocSettings: Writing to /storage/emulated/0/Download/Telegram/Handwriting Chinese characters_ The minimu - Harvey Dam.sdr/metadata.epub.lua
11-04 11:35:54.026  1516  1559 V KOReader: AutoTurn: onCloseWidget
11-04 11:35:54.028  1516  1559 V KOReader: Tearing down ReaderUI table: 0x6f76d58298
11-04 11:35:54.028  1516  1559 V KOReader: show reader ui
11-04 11:35:54.083  1516  1559 V KOReader: ImageWidget: _render'ing resources/icons/mdlight/notice-info.svg 72 72
11-04 11:35:54.084  1516  1559 V KOReader: ImageWidget: initial offsets 0 0
11-04 11:35:54.084  1516  1559 V KOReader: show widget: table: 0x6f62094030
11-04 11:35:54.084  1516  1559 V KOReader: setDirty nil from widget table: 0x6f62094030 w/ NO region; dithering: nil
11-04 11:35:54.084  1516  1559 V KOReader: setDirty via a func from widget table: 0x6f62094030
11-04 11:35:54.084  1516  1559 V KOReader: _refresh: Enqueued ui update for region 0 0 1080 2307 dithering: false
11-04 11:35:54.090  1516  1559 V KOReader: triggering refresh {
11-04 11:35:54.090  1516  1559 V KOReader:   mode = "ui",
11-04 11:35:54.090  1516  1559 V KOReader:   region = "1080x2307+0+0"
11-04 11:35:54.090  1516  1559 V KOReader: } --[[table: 0x6f6206b6a8]]
11-04 11:35:54.119  1516  1559 V KOReader: close widget: table: 0x6f62094030
11-04 11:35:54.119  1516  1559 V KOReader: creating coroutine for showing reader
11-04 11:35:54.120  1516  1559 I KOReader: opening file /storage/emulated/0/Download/Telegram/Handwriting Chinese characters_ The minimu - Harvey Dam.epub
11-04 11:35:54.358  1516  1559 V KOReader: CreDocument: using cre call cache
11-04 11:35:54.362  1516  1559 I KOReader: Inhibiting user input
11-04 11:35:54.362  1516  1559 V KOReader: android.setIgnoreInput true
11-04 11:35:54.373  1516  1559 V KOReader: DocSettings: data is read from /storage/emulated/0/Download/Telegram/Handwriting Chinese characters_ The minimu - Harvey Dam.sdr/metadata.epub.lua
11-04 11:35:54.376  1516  1559 V KOReader: ImageWidget: _render'ing resources/icons/mdlight/book.opened.svg 58 58
11-04 11:35:54.376  1516  1559 V KOReader: ImageWidget: initial offsets 0 0
11-04 11:35:54.399  1516  1559 V KOReader: CreDocument: applied cr3.ini default settings.
...

Until you see the Cre engine things, you can see in the log to find out where it's hanging.

**Comment by poire-z** [comment] 2023-11-04 15:06
> Can you please have a look? Seems like it hiccups on Partial Re-rendering

Well, if you can't reproduce, I guess I can't either :)
No issue on a big document with partial rerendering on my phone. And I don't have a Galaxy Tab S9.
It's probably some Android mess/stuff, that you people are probably better at understanding than me.

**Comment by KrokusPokus** [comment] 2023-11-05 17:08
Just for the record, my Samsung Galaxy M21 phone has had the same issues with partial rendering since that feature was added.
(But then again, that device or OS occasionally has another issue (#9727) for me as well. Maybe Samsung's Android is just weird in some ways.)

**Comment by pazos** [comment] 2023-11-05 20:34
It is an ANR. From the logs:

```
11-04 11:04:58.749 I/KOReader( 3597): Restoring user input handling
11-04 11:05:05.130 I/KOReader( 3597): Inhibiting user input
[...]
11-04 11:05:05.333 I/KOReader( 3597): Restoring user input handling
11-04 11:05:42.661 I/reader.launcher( 3597): Thread[5,tid=3609,WaitingInMainSignalCatcherLoop,Thread*=0xb400006f4c164f50,peer=0x136c01e8,"Signal Catcher"]: reacting to signal 3
11-04 11:05:42.661 I/reader.launcher( 3597): 
11-04 11:05:42.907 I/reader.launcher( 3597): Wrote stack traces to tombstoned
```

AFAICT ANRs shouldn't happen without user input. Also I'm not sure how "restoring user input handling" is fired about 30s before the signal is emitted.

> Maybe Samsung's Android is just weird in some ways.

Yup, it is picky about input handling but that alone couldn't explain this ticket unless the ROM triggers its own input events. In that case yep, 30s is enough for the system to kill us, and **not** restoring the input handler while something is in the works might workaround that.

**Comment by pazos** [comment] 2024-09-15 21:51
duplicate of #12099

**Closed by pazos** 2024-09-15 21:51 UTC
Labels: Android, firmware
