### ISSUE TITLE
Kobo Touch Mark3 has trouble turning a page with tapping.

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#630] opened 2014-06-05 07:25 UTC
[On mobileread simonchik](http://www.mobileread.com/forums/showthread.php?p=2842283#post2842283) has posted his problem with installing koreader on the older Mark 3 Kobo Touch. 
He has done extensive testing and apparently he has a different hardware from other Mark 3 owners [such as tshering](http://www.mobileread.com/forums/showthread.php?p=2843886#post2843886) or a different way of touching the screen.

Because it is a nice case study and the Kobo Aura is also not behaving quite as you would like, we have delved into `gesturedetector.lua` and try to find a way to make it work for his hardware. First we'll try to change the parameters in `GestureDetector`.

Latest post by simonchik:
@markismus: about versions that 'work' on my kobo, I now have a clearer idea about what's happening: if I put my finger on the screen, I get 

```
# tev fed| 558 | 291854 | 342 | 307 | 1 | Evt 0
# in tap state...
# set up hold timer
# hold gesture detected in slot 0
# in hold state...
# tev fed| 558 | 405127 | 341 | 307 | 1 | Evt 0
# in hold state...
# tev fed| 558 | 504107 | 341 | 308 | 1 | Evt 0
# in hold state...
# tev fed| 558 | 688109 | 340 | 309 | 1 | Evt 0
# in hold state...
# tev fed| 558 | 872074 | 339 | 309 | 1 | Evt 0
# in hold state...
# tev fed| 559 | 27735 | 339 | 310 | 1 | Evt 0
# in hold state...
# tev fed| 559 | 225903 | 338 | 311 | 1 | Evt 0
# in hold state...
# tev fed| 559 | 749673 | 337 | 311 | 1 | Evt 0
# in hold state...
# tev fed| 560 | 4570 | 337 | 309 | 1 | Evt 0
# in hold state...
# tev fed| 560 | 13418 | 337 | 309 | -1 | Evt 0
# in hold state...
# hold_release detected in slot 0
```

which means that tev is populated with touch events from very close coordinates, as if I were moving my finger, except I'm not. There is no multitouch, no "two finger-tap" and so on, so I think the best think would be to put a threshold, like 5 points or so on this device, below which a touch event on hold state would be discarded?

**Comment by mezzarobba** [comment] 2016-05-15 12:05
It looks like the timestamps of input events are *not* relative to the Epoch and this breaks the timers used to detect gestures. So I tried switching to the “Alyssum protocol” (which appears to handle a similar issue):
```
--- a/frontend/device/kobo/device.lua
+++ b/frontend/device/kobo/device.lua
@@ -26,6 +26,7 @@ local KoboTrilogy = Kobo:new{
     model = "Kobo_trilogy",
     needsTouchScreenProbe = yes,
     touch_switch_xy = false,
+    touch_alyssum_protocol = true,
     hasKeys = yes,
 }
```
and that solved the problem for me. (Note that `adjustTouchAlyssum()` actually does more than we need on this model: as far as I understand, the part dealing with `ABS_MT_TRACKING_ID` is not used.)

**Comment by houqp** [comment] 2016-05-16 07:03
@mezzarobba you are running it on kobo touch right? Is this happening to all the kobo touch devices? I am surprised the default config is not set properly for so long.

**Comment by mezzarobba** [comment] 2016-05-16 07:58
Yes, I am running it on a Kobo Touch. The mobileread thread linked above suggests that this is not happening on all Touch models, and perhaps in fact only on those sold in France by fnac (that's what I have too).

**Comment by houqp** [comment] 2016-05-17 04:08
@mezzarobba what is the format for the timestamp you got before the patch? I wonder if there is a simple way to detect it. If not, forcefully apply the first half of adjustTouchAlyssum to all touch model should work too...

**Comment by mezzarobba** [comment] 2016-05-17 07:41
I can't check right now, but if I remember right it was similar to the examples posted earlier in this thread, i.e. fairly small numbers (of the order of magnitude of a few thousands) that may be seconds since boot or something like that.

**Comment by houqp** [comment] 2016-05-17 07:54
Will you be able to check it later? If we can confirm it's something like seconds since boot, then it's a simple fix and I can send a PR.

**Comment by mezzarobba** [comment] 2016-05-17 08:03
Yes, I can have a look this evening (UTC+0200).

**Comment by mezzarobba** [comment] 2016-05-17 19:43
It was indeed seconds since last boot.

**Comment by houqp** [comment] 2016-05-24 06:02
@mezzarobba , can you help test the patch in PR #2042

**Comment by mezzarobba** [comment] 2016-06-05 12:56
Sorry for taking so long to reply. I tested the last master (861e50c0) since it looks like the patch was merged in the meantime. And I can confirm that it works for me, _except_ that I had lots of trouble going past the initial orientation detection screen on a new installation. At first it didn't seem to work at all, even with very quick taps (while koreader correctly displayed its suspend/poweroff screen when I used to on/off button). I tried again after a hard reset, and this time a quick tap did the job.

**Comment by houqp** [comment] 2016-06-05 21:18
> Sorry for taking so long to reply. I tested the last master (861e50c) since it looks like the patch was merged in the meantime. And I can confirm that it works for me, except that I had lots of trouble going past the initial orientation detection screen on a new installation. At first it didn't seem to work at all, even with very quick taps (while koreader correctly displayed its suspend/poweroff screen when I used to on/off button). I tried again after a hard reset, and this time a quick tap did the job.

By reset you mean removing the reader setting? You should not need to do quick tap to make it work. If you are still able to reproduce it, feel free to upload the settings here, I will take a look :)

> Also: perhaps it would be (marginally) more robust to compare the timestamp with now() minus a few seconds than with a fixed date?

Good point. Except couple seconds might not be enough given the main UI loop might be blocked loading document before handling the event. I set it to 10 minute in: https://github.com/koreader/koreader/pull/2064

**Comment by mezzarobba** [comment] 2016-06-14 14:48
On dimanche 5 juin 2016 14:18:23 CEST Qingping Hou wrote:
> > Sorry for taking so long to reply. I tested the last master
> > (861e50c) since it looks like the patch was merged in the meantime.
> > And I can confirm that it works for me, except that I had lots of
> > trouble going past the initial orientation detection screen on a
> > new installation. At first it didn't seem to work at all, even with
> > very quick taps (while koreader correctly displayed its
> > suspend/poweroff screen when I used to on/off button). I tried
> > again after a hard reset, and this time a quick tap did the job.
>
> By reset you mean removing the reader setting?

No: I meant to reboot the reader using a paperclip (the on/off/suspend 
button was not enough, and I had no shell on the reader at the time I 
tried).

> You should not need to
> do quick tap to make it work. If you are still able to reproduce it,
> feel free to upload the settings here, I will take a look :)

I'm not too keen on reproducing the exact same situation: I am booting 
koreader directly, and I'd need to factory-reset my kobo if I couldn't 
pass that initial screen! But I can try to launch a fresh install of 
koreader from a shell one of these days and see what happens.

Thanks again for your work on this!

-- 
Marc

**Comment by Frenzie** [comment] 2018-12-26 10:11
I don't know anything about this issue as such, but from a quick glance around it sounds like that would defeat the purpose of the touch probe?

**Comment by NiLuJe** [comment] 2018-12-26 18:36
What's the issue, exactly, with dealing with the touch probe thingy?

(Because, yes, AFAIK, there are some variants that do not need the swap).

**Comment by mezzarobba** [comment] 2018-12-26 20:16
Nothing happens when I tap the screen. I assume that this is because probeEvEpochTime cannot yet do its job, but I have no proof.

I don't think the issue that made probeEvEpochTime necessary is limited to gestures. If I remember well, on my kobo, only very quick taps used to do anything back then. Now even these don't seem to work, but it is hard to tell for sure.

**Comment by NiLuJe** [comment] 2018-12-26 20:42
Napkin coding:

Try injecting the probeEvEpochTime before the probe, without forgetting to unset the flag so that it won't be injected again after the probe?

**Comment by NiLuJe** [comment] 2018-12-26 20:47
Something like:

```diff
diff --git a/frontend/device/kobo/device.lua b/frontend/device/kobo/device.lua
index 63495cd4..a8ded6ad 100644
--- a/frontend/device/kobo/device.lua
+++ b/frontend/device/kobo/device.lua
@@ -278,6 +278,15 @@ function Kobo:init()
     else
         -- if touch probe is required, we postpone EventAdjustHook
         -- initialization to when self:touchScreenProbe is called
+        -- Except we may need bits of EventAdjustHook for stuff to be functional, so,
+        -- re-order things in the most horrible way possible!
+        if self.touch_probe_ev_epoch_time then
+            self.input:registerEventAdjustHook(function(_, ev)
+                probeEvEpochTime(_, ev)
+            end)
+            -- And don't do it again during the real initEventAdjustHooks ;)
+            self.touch_probe_ev_epoch_time = nil
+        end
         self.touchScreenProbe = function()
             -- if user has not set KOBO_TOUCH_MIRRORED yet
             if KOBO_TOUCH_MIRRORED == nil then
```

**Comment by mezzarobba** [comment] 2018-12-27 08:41
I'm about to leave for a week, but I'll try out your suggestion when I get back. Thanks a lot!

**Comment by mezzarobba** [comment] 2019-01-04 20:30
> Something like:
> 
> ```diff
> diff --git a/frontend/device/kobo/device.lua b/frontend/device/kobo/device.lua
> index 63495cd4..a8ded6ad 100644
> --- a/frontend/device/kobo/device.lua
> +++ b/frontend/device/kobo/device.lua
> @@ -278,6 +278,15 @@ function Kobo:init()
>      else
>          -- if touch probe is required, we postpone EventAdjustHook
>          -- initialization to when self:touchScreenProbe is called
> +        -- Except we may need bits of EventAdjustHook for stuff to be functional, so,
> +        -- re-order things in the most horrible way possible!
> +        if self.touch_probe_ev_epoch_time then
> +            self.input:registerEventAdjustHook(function(_, ev)
> +                probeEvEpochTime(_, ev)
> +            end)
> +            -- And don't do it again during the real initEventAdjustHooks ;)
> +            self.touch_probe_ev_epoch_time = nil
> +        end
>          self.touchScreenProbe = function()
>              -- if user has not set KOBO_TOUCH_MIRRORED yet
>              if KOBO_TOUCH_MIRRORED == nil then
> ```

It works, except that I also needed to move up a bit the declaration of probeEvEpochTime. Thank you!

**Closed** 2019-01-08 01:59 UTC
Labels: Kobo
