### ISSUE TITLE
Cannot connect to e-reader via SSH

### ISSUE THREAD

**Issue by levkp** [koreader/koreader#11550] opened 2024-03-14 13:02 UTC
* KOReader version: v2023.10
* Device: PocketBook TouchHD (PB631)

#### Issue

I followed the [Connect to the e-reader via SSH](https://dmpop.github.io/koreader-compendium/16-ssh/) guide to establish an SSH connection between my laptop and my e-reader. First, I enabled login without password in KOReader, but I was still prompted to enter a password. I tried to input an empty string by pressing enter, but it was rejected.  

Then, I followed the steps for key authentication, and put both an RSA and ed25519 key in the `authorized_keys` file of KOReader:

<details>
  <summary><code>cat /run/media/levi/LEVI-PB/applications/koreader/settings/SSH/authorized_keys</code></summary>
<code>ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8ZudfAiq1QqBLLM613CGvg0fEEdA3/e7vlbdZafBNfPyAN8eou5TsJ4cMS0et0pupUDr4gqy4Jr4oVceRbloCgH612XY/L/SbEcSRoxEbEEtJxZ0+EARkLUzjHjYiinsqPCQ99fpZP5CS3HzhyCveaYcHjkQI3+WZINk9Hxero5uc1aEOdkJZLZSMwDEq4VNb8TDHnqVr8k+kkPErrEgf6TyyTbJ6xhm5cTXqDl4uC9uG8rwM2foqf7q3gHpL1UA4gGE6Ips+/j8vGwQp/CFGQJ8m6eUzDSY2kt5wgYOpvmNy0WyTk8KrjOo6KHrStJ5Fw7IJArH7b600H5Am8038SC/SpS9rfI38wtl7hHDzQjFK8vYbB17O4GdcjT5ykIciUk6MntKuS+Z2+GrxEMH69uh0M96UNiMBxj5gcAh3DfNoVcfac8HWUSoo7HO9LiCF40EVCACObnW/QLfdeqOZjIaMuvCOJMBSybeuGMDf3OmfnOchHDWlLH1qnb7hCR0= levi@thinkpad

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILr+tfXWWIBCdEQ1YXTBu2/EkVeD9y6YEUiaPwYOX9ZX levi@thinkpad</code>
</details>

I'm sure these are correct.
Here's the verbose output of the command I ran to try to get in with my RSA key:

<details>
  <summary><code>ssh -v -p 2222 -i ~/.ssh/id_touchhd 192.168.0.236</code></summary>
<code>
OpenSSH_9.3p1, OpenSSL 3.1.1 30 May 2023
debug1: Reading configuration data /home/levi/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data /home/levi/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: Connecting to 192.168.0.236 [192.168.0.236] port 2222.
debug1: Connection established.
debug1: identity file /home/levi/.ssh/id_touchhd type 0
debug1: identity file /home/levi/.ssh/id_touchhd-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.3
debug1: Remote protocol version 2.0, remote software version dropbear_2018.76
debug1: compat_banner: no match: dropbear_2018.76
debug1: Authenticating to 192.168.0.236:2222 as 'levi'
debug1: load_hostkeys: fopen /home/levi/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:f736zDwBYhw7HPAl/Nu7dAXUQNUumrGlV61AEWZ5lXU
debug1: load_hostkeys: fopen /home/levi/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '[192.168.0.236]:2222' is known and matches the ECDSA host key.
debug1: Found key in /home/levi/.ssh/known_hosts:8
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: get_agent_identities: bound agent to hostkey
debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
debug1: Will attempt key: /home/levi/.ssh/id_touchhd RSA SHA256:OuAADhrrFUKshFA2f7osx1ityi0lgoXqDvwtR38S06Q explicit
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: /home/levi/.ssh/id_touchhd RSA SHA256:OuAADhrrFUKshFA2f7osx1ityi0lgoXqDvwtR38S06Q explicit
**debug1: send_pubkey_test: no mutual signature algorithm**
debug1: Next authentication method: password
**levi@192.168.0.236's password:**</code>
</details>

I see `debug1: send_pubkey_test: no mutual signature algorithm` on the bottom that makes me think that RSA is not supported by the SSH server that KOReader is using? Sounds unlikely. Anyway, I tried with ed25519 too:

<details>
  <summary><code>ssh -v -p 2222 -i id_ed25519_touchhd 192.168.0.236</code></summary>
<code>
OpenSSH_9.3p1, OpenSSL 3.1.1 30 May 2023
debug1: Reading configuration data /home/levi/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data /home/levi/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: Connecting to 192.168.0.236 [192.168.0.236] port 2222.
debug1: Connection established.
debug1: identity file id_ed25519_touchhd type 3
debug1: identity file id_ed25519_touchhd-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.3
debug1: Remote protocol version 2.0, remote software version dropbear_2018.76
debug1: compat_banner: no match: dropbear_2018.76
debug1: Authenticating to 192.168.0.236:2222 as 'levi'
debug1: load_hostkeys: fopen /home/levi/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:f736zDwBYhw7HPAl/Nu7dAXUQNUumrGlV61AEWZ5lXU
debug1: load_hostkeys: fopen /home/levi/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '[192.168.0.236]:2222' is known and matches the ECDSA host key.
debug1: Found key in /home/levi/.ssh/known_hosts:8
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: get_agent_identities: bound agent to hostkey
debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
debug1: Will attempt key: id_ed25519_touchhd ED25519 SHA256:uMM/S4oKoJ26QTN1iwEgKrVobMlKS07Ec3DBifcg0LI explicit
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: id_ed25519_touchhd ED25519 SHA256:uMM/S4oKoJ26QTN1iwEgKrVobMlKS07Ec3DBifcg0LI explicit
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
**levi@192.168.0.236's password:** 
</code>
</details>

I don't get the same error here, though I'm still prompted to enter a password.

#### Steps to reproduce
I did some research, but it seems like I'm the only one with this problem.

Am I missing something? Could this be a device problem? Thanks for the help.

**Comment by pazos** [comment] 2024-03-14 13:57
Duplicate of #8370

**Closed by pazos** 2024-03-14 13:57 UTC
