### ISSUE TITLE
ko reader is now upside down again.

### ISSUE THREAD

**Issue by 133794m3r** [koreader/koreader#3518] opened 2017-11-25 05:41 UTC
* KOReader version:koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1370-g5ee6c01
* Device: kobo aura h20

#### Issue
screen is upside down again
#### Steps to reproduce
start the thing and you get upside down fun.

firmware of the device is  4.6.9995 (5c036c4fb5)
no idea why. But this is happening I'm on the second to latest firmware b/c the thing autoupdated me and I couldn't revert it fast enough.

**Comment by Frenzie** [comment] 2017-11-25 08:51
Not sure what you mean by again, but do you have the latest KSM updates installed?

**Comment by allati** [comment] 2017-11-25 13:48
For me such problems began since 4.6.9995. Rotation problem is discussed on KSM forum, but no solution is (yet?) available.

**Comment by 133794m3r** [comment] 2017-11-25 17:50
I meant it was previously fixed(via looking at the issues list) and now it's broken again. And yes I'm using KSM 8 first time using this thing I only needed it for the pdf reflow plugin so i can read some pdfs that are not formatted perfectly for such a smallish screen.

**Comment by KenMaltby** [comment] 2017-11-25 19:56
So it is not just an H2O2 (H2O second edition) issue?  Funny how the Kobo development effort seems to result in "updated" firmware that introduces odd problems for the existing 3rd party programs.  It didn't seem that way before Kobo's sale and new owners.

**Comment by 133794m3r** [comment] 2017-11-25 20:00
I'd say it's because their new owners are japanese and they probably are like a lot of japanese companies in that they are backwards when it comes to a lot of the western development practices(at least that's what gamedev people say anyway). Plus it's probably a "who cares" kinda thing the beta program is probably stripped way back now too b/c this is a bug that should've crept up during a beta test.

p.s. mine's a kobo affiliate reader bought directly from them but I'm on .9995 the latest updeate isn't available yet. I know that previous updates do strange things randomly.

**Comment by Frenzie** [comment] 2017-11-25 22:50
@133794m3r 
> I meant it was previously fixed(via looking at the issues list) and now it's broken again. And yes I'm using KSM 8 first time using this thing I only needed it for the pdf reflow plugin so i can read some pdfs that are not formatted perfectly for such a smallish screen.

I mean KSM 8 with the latest updates for newer firmware. (At least update 4 iirc.)

**Comment by rookah** [comment] 2017-12-01 22:03
I can confirm this is also happening on my H2O2 on latest firmware, latest KOReader release.

**Comment by Frenzie** [comment] 2017-12-02 09:48
It's been confirmed as a KSM issue.

https://www.mobileread.com/forums/showpost.php?p=3617069&postcount=886
> Thank you for telling. As you can see in the post above yours this is a known problem. The problem of the screen rotation is actually that of KSM and not of Koreader itself.

**Comment by Frenzie** [comment] 2018-03-07 20:12
@133794m3r Do you know if it's been fixed in KSM? Latest version here: https://www.mobileread.com/forums/showthread.php?t=293804

**Comment by NiLuJe** [comment] 2018-04-19 16:06
To me, it feels like they actually fixed the initial "upside-down" issue, and the workarounds in place in 3rd-party apps are now breaking it ;).

FWIW, I experienced said issue without KSM when restarting nickel on the 'wonky' FW, and now, I don't. Which is why I killed the workaround in bdb82d09c176bcb46197d9286a193748c5ce3e2e ;).

I'd suggest closing this as notourbug?

**Comment by Frenzie** [comment] 2018-04-19 16:10
Hm, I'm failing to spot rotation stuff in that commit?

**Comment by NiLuJe** [comment] 2018-04-19 17:31
@Frenzie : In the [nickel](https://github.com/koreader/koreader/commit/bdb82d09c176bcb46197d9286a193748c5ce3e2e#diff-ba4e47ecf18ddd8e90c2d4978872c839L4] restart script (and the matching bit at the bottom of the file).

**Comment by NiLuJe** [comment] 2018-07-07 00:29
After having spent wayt too much time cursing at Kobo's general broken handling of the basics of a Linux system, I can reliably say: not our bug ;).

**Closed by NiLuJe** 2018-07-07 00:29 UTC
Labels: Kobo
