### ISSUE TITLE
KOreader crashes when loading one particular book

### ISSUE THREAD

**Issue by everdred** [koreader/koreader#6413] opened 2020-07-22 05:36 UTC
* KOReader version:2020.07.1
* Device:Kobo Libra h2o

#### Issue
KOReader crashes when loading one particular book.

#### Steps to reproduce
Load this particular book manually (or have it be automatically loaded at startup because it was the latest book read, which results in a crashing loop until the device is restarted, the book is moved to another directory and KOReader is relaunched). 

It may be worth noting that the book has a .sdr directory with multiple bookmarks and highlights, probably last modified by KOReader 2020.06. I've never had this happen with past versions of KOReader, and I've tried a handful of other books and I can't find another one that reproduces this issue.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

```
Original fb rotation is set @ 0
Original fb bitdepth is set @ 32bpp
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Detected a Kobo Libra H2O (384 => Storm @ Mark 7)
Variable fb info: 1264x1680 (1280x1792), 32bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 5120 bytes
Device's expected Portrait orientation should be: 0 (Upright, 0°)!

Current rotation is already 0!

Switching fb to 8bpp @ rotation 0 . . .
Setting bitdepth to 8bpp
Setting grayscale to 1
Setting rotate to 0 (Upright, 0°)
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 0 (Upright, 0°)

Variable fb info: 1264x1680 (1280x3584), 8bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 1280 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 07/22/20-01:22:09
 [*] Version: v2020.07.1

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: blitbuffer
FB: computed size: 4587520
FB: id           : mxc_epdc_fb
FB: smem_len     : 9175040
FB: line_length  : 1280
FB: xres         : 1264
FB: xres_virtual : 1280
FB: yres         : 1680
FB: yres_virtual : 3584
FB: bpp          : 8
07/22/20-01:22:09 INFO  initializing for device Kobo_storm
07/22/20-01:22:09 INFO  framebuffer resolution: {
    ["h"] = 1680,
    ["w"] = 1264
}
[ko-input] Forked off fake event generator(pid:2956).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
PING 192.168.0.200 (192.168.0.200): 56 data bytes
64 bytes from 192.168.0.200: seq=0 ttl=64 time=5.460 ms

--- 192.168.0.200 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 5.460/5.460/5.460 ms
[Wed Jul 22 01:22:10 EDT 2020] restore-wifi-async.sh: Restarting WiFi
07/22/20-01:22:10 INFO  opening file /mnt/onboard/koreader-library/Neal Stephenson - Snow Crash.epub
07/22/20-01:22:10 ERROR failed to register crengine font: cannot register font <./fonts/ChareInk v1.1/ChareInk-Bold.ttf>
07/22/20-01:22:10 ERROR failed to register crengine font: cannot register font <./fonts/ChareInk v1.1/ChareInk-BoldItalic.ttf>
07/22/20-01:22:10 ERROR failed to register crengine font: cannot register font <./fonts/ChareInk v1.1/ChareInk-Italic.ttf>
07/22/20-01:22:10 ERROR failed to register crengine font: cannot register font <./fonts/ChareInk v1.1/ChareInk-Regular.ttf>
07/22/20-01:22:10 INFO  Loading plugins from directory: plugins
07/22/20-01:22:10 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
07/22/20-01:22:10 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
07/22/20-01:22:11 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin calibre at plugins/calibre.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin movetoarchive at plugins/movetoarchive.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin profiles at plugins/profiles.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
07/22/20-01:22:11 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
udhcpc: started, v1.31.1.kobo
udhcpc: sending discover
udhcpc: sending select for 192.168.0.146
udhcpc: lease of 192.168.0.146 obtained, lease time 43200
adding dns 192.168.0.200
[Wed Jul 22 01:22:11 EDT 2020] restore-wifi-async.sh: Restarted WiFi
CRE: document loaded, but styles re-init needed (cause: embedded fonts)
CRE: styles re-init needed after load, re-rendering
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 07/22/20 @ 01:22:15)
Running FW 4.22.15190 on Linux 4.1.15-00416-gfc725f43860b (#99 SMP PREEMPT Mon Apr 6 14:55:22 CST 2020)
Attempting to restart KOReader . . .
!!!!
```

**Comment by everdred** [comment] 2020-07-22 05:42
It's worth noting that the same epub file (but with a different .sdr directory) on the Android build of 2020.07.1 causes a crash as well.

**Comment by poire-z** [comment] 2020-07-22 05:43
Similar to #6394 - but it should have been fixed in 2020.07.1 :(

Can you share the book? Scrambled if necessary https://github.com/koreader/koreader/issues/6391#issuecomment-660523500

**Comment by poire-z** [comment] 2020-07-22 05:49
Anyway, if the cause is similar to the previous issue, one trick might be to disable embedded fonts for the first load, and later re-enable them.
- For previously opened books, by editing metadata.epub.lua and changing `["embedded_fonts"] = true,` to false.
- For newly opened books, by, in another book, long-press in bottom menu on Embedded fonts and make the default to be false - then open the new book - then press and long-press Embedded fonts to re-enable them.

**Comment by everdred** [comment] 2020-07-22 14:24
@poire-z Here's the scrambled epub; I'll also give your suggestions a try and report back. Thanks!

[Snow Crash - Neal Stephenson_scrambled.epub.zip](https://github.com/koreader/koreader/files/4960553/Snow.Crash.-.Neal.Stephenson_scrambled.epub.zip)

**Comment by poire-z** [comment] 2020-07-22 16:40
Thanks, reproduced.
Same reason as #6394 (same kind of book, embedded fonts in next-reads.xhtml), same crash at the same place.
I went with a quick and lazy fix, that worked only in some case but not all :/
Will have to go understanding what's happening deeper.

**Comment by everdred** [comment] 2020-07-22 17:12
I appreciate you looking into this. Also, just wanted to let you know that I tried your advice about disabling embedded-fonts option in the metadata file and the result is still the same, both on Android and Kobo.

**Comment by poire-z** [comment] 2020-07-22 18:36
OK :/ Indeed, we load the embedded fonts and decide we should re-render, even if Embedded Fonts are disabled...

**Comment by poire-z** [comment] 2020-07-23 18:56
Fix found ^ - will wait a few days to bump it into frontend and a nightly, in case something else comes up.
In the meantime, if you want to read that book, just removes from the epub the file `next-reads.xhtml`.

**Comment by everdred** [comment] 2020-07-23 19:45
Awesome news, I appreciate it! I'll give that epub tweak a try too.

**Closed** 2020-07-28 19:54 UTC
Labels: bug
