### ISSUE TITLE
koreader 2024.07 crashes at startup on Sony DPT-RP1

### ISSUE THREAD

**Issue by SteadyQuad** [koreader/koreader#12489] opened 2024-09-08 19:35 UTC
* KOReader version: 2024.07
*  Device: Sony DPT-RP1 (android 5.1, 32-bit armeabi-v7a)

#### Issue

After upgrading from koreader 2024.04 to 2024.07 (via the koreader update menu) and re-starting the koreader app, it crashes.

#### Steps to reproduce

re-install older 2024.04 version:

$ adb install -r -d /mnt/data/Downloads/DPT/android_apps/koreader-android-arm-v2024.04.apk 

--> start koreader --> app works

upgrade to 2024.07 via app update menu, or via:

$ adb install -r -d /mnt/data/Downloads/DPT/android_apps/koreader-android-arm-v2024.07.apk 

--> start koreader --> app crashes

##### `crash.log` (if applicable)

(could not access the menu, but I manually did set both ["debug"] and ["debug_verbose"] to true in settings.reader.lua)

`<details>
  <summary>crash.log</summary>

```
...
09-08 20:49:08.871 I/MainActivity(10509): loading libluajit
09-08 20:49:08.873 W/linker  (10509): libluajit.so: unused DT entry: type 0x6ffffef5 arg 0x134c
09-08 20:49:08.873 W/linker  (10509): libluajit.so: unused DT entry: type 0x6ffffffe arg 0x12ec
09-08 20:49:08.873 W/linker  (10509): libluajit.so: unused DT entry: type 0x6fffffff arg 0x3
09-08 20:49:08.890 W/ContextImpl(10509): Failed to ensure directory: /storage/external/Android/obb/org.koreader.launcher
09-08 20:49:08.893 W/ContextImpl(10509): Failed to ensure directory: /storage/external/Android/data/org.koreader.launcher/files
09-08 20:49:08.894 W/linker  (10509): libluajit-launcher.so: unused DT entry: type 0x6ffffef5 arg 0x6d4
09-08 20:49:08.894 W/linker  (10509): libluajit-launcher.so: unused DT entry: type 0x6ffffffe arg 0x6b4
09-08 20:49:08.894 W/linker  (10509): libluajit-launcher.so: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:08.896 V/NativeGlue(10509): User FIFO already exists at `/data/data/org.koreader.launcher/files/alooper.fifo`
09-08 20:49:08.896 I/Assets  (10509): loading lib7z
09-08 20:49:08.896 V/NativeThread(10509): waiting for activity
09-08 20:49:08.897 W/linker  (10509): lib7z.so: unused DT entry: type 0x6ffffef5 arg 0xc74
09-08 20:49:08.897 W/linker  (10509): lib7z.so: unused DT entry: type 0x6ffffffe arg 0xc54
09-08 20:49:08.897 W/linker  (10509): lib7z.so: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:08.908 I/EPD     (10509): Using Nook/NTX driver
09-08 20:49:08.910 I/Lights  (10509): Using Generic driver
09-08 20:49:08.917 V/Surface (10509): Using SurfaceView implementation
09-08 20:49:08.917 V/MainActivity(10509): native orientation: landscape
09-08 20:49:08.917 V/EventReceiver(10509): Filtering 3 events: 
09-08 20:49:08.917 V/EventReceiver(10509): android.intent.action.DOWNLOAD_COMPLETE
09-08 20:49:08.917 V/EventReceiver(10509): android.intent.action.ACTION_POWER_CONNECTED
09-08 20:49:08.917 V/EventReceiver(10509): android.intent.action.ACTION_POWER_DISCONNECTED
09-08 20:49:08.919 V/NativeGlue(10509): Start: 0x4ff5f9d0
09-08 20:49:08.919 V/NativeGlue(10509): Resume: 0x4ff5f9d0
09-08 20:49:08.920 V/Timeout (10509): onResume: updating system timeout: 0
09-08 20:49:08.921 V/Timeout (10509): onResume
09-08 20:49:08.923 V/NativeGlue(10509): InputQueueCreated: 0x4ff5f9d0 -- 0x4ef19dc0
09-08 20:49:08.928 D/Surface (10509): onAttachedToWindow()
09-08 20:49:09.047 V/NativeGlue(10509): NativeWindowCreated: 0x4ff5f9d0 -- 0x502a9088
09-08 20:49:09.047 V/NativeThread(10509): Activity window ready.
09-08 20:49:09.148 V/Surface (10509): surface changed {
09-08 20:49:09.148 V/Surface (10509):   width:  2200
09-08 20:49:09.148 V/Surface (10509):   height: 1650
09-08 20:49:09.148 V/Surface (10509):  format: TRANSPARENT
09-08 20:49:09.148 V/Surface (10509): }
09-08 20:49:09.148 V/NativeGlue(10509): NativeWindowResized: 0x4ff5f9d0 -- 0x502a9088
09-08 20:49:09.268 V/NativeGlue(10509): NativeWindowRedrawNeeded: 0x4ff5f9d0 -- 0x502a9088
09-08 20:49:09.312 I/Choreographer(10509): Skipped 38 frames!  The application may be doing too much work on its main thread.
09-08 20:49:09.364 V/NativeGlue(10509): NativeWindowRedrawNeeded: 0x4ff5f9d0 -- 0x502a9088
09-08 20:49:09.494 V/NativeGlue(10509): WindowFocusChanged: 0x4ff5f9d0 -- 1
09-08 20:49:09.494 V/NativeThread(10509): Activity gained focus.
09-08 20:49:09.496 V/NativeThread(10509): Launching LuaJIT assets
09-08 20:49:09.549 I/Assets  (10509): Skip installation for revision v2024.07
09-08 20:49:09.552 I/dlopen  (10509): dl.dlopen - libs/libkoreader-lfs.so => /data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so
09-08 20:49:09.553 V/dlopen  (10509):     dl.dlopen - needed => libluajit.so (1 of 2) <= /data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so
09-08 20:49:09.553 V/dlopen  (10509):     dl.dlopen - libluajit.so => /data/app/org.koreader.launcher-2/lib/arm/libluajit.so
09-08 20:49:09.554 V/dlopen  (10509):         dl.dlopen - needed => libm.so (1 of 3) <= /data/app/org.koreader.launcher-2/lib/arm/libluajit.so
09-08 20:49:09.554 V/dlopen  (10509):         dl.dlopen - libm.so => /system/lib/libm.so
09-08 20:49:09.554 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libm.so (system lib)
09-08 20:49:09.554 V/dlopen  (10509):         dl.dlopen - needed => libdl.so (2 of 3) <= /data/app/org.koreader.launcher-2/lib/arm/libluajit.so
09-08 20:49:09.555 V/dlopen  (10509):         dl.dlopen - libdl.so => /system/lib/libdl.so
09-08 20:49:09.555 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libdl.so (system lib)
09-08 20:49:09.555 V/dlopen  (10509):         dl.dlopen - needed => libc.so (3 of 3) <= /data/app/org.koreader.launcher-2/lib/arm/libluajit.so
09-08 20:49:09.555 V/dlopen  (10509):         dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:09.555 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:09.555 V/dlopen  (10509):     sys_dlopen - loading library /data/app/org.koreader.launcher-2/lib/arm/libluajit.so (in local namespace)
09-08 20:49:09.555 V/dlopen  (10509):     dl.dlopen - needed => libc.so (2 of 2) <= /data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so
09-08 20:49:09.555 V/dlopen  (10509):     dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:09.555 V/dlopen  (10509):     dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:09.555 V/dlopen  (10509): sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so (in local namespace)
09-08 20:49:09.556 W/linker  (10509): libkoreader-lfs.so: unused DT entry: type 0xf arg 0x29e
09-08 20:49:09.556 W/linker  (10509): libkoreader-lfs.so: unused DT entry: type 0x6ffffef5 arg 0x654
09-08 20:49:09.560 W/linker  (10509): libkoreader-lfs.so: unused DT entry: type 0x6ffffffe arg 0x634
09-08 20:49:09.560 W/linker  (10509): libkoreader-lfs.so: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:09.581 W/dlopen  (10509): could not find library rt.so.1
09-08 20:49:09.582 I/MainActivity(10509): New intent: Intent { cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher/.MainActivity }.action
09-08 20:49:09.645 I/dlopen  (10509): dl.dlopen - libs/libutf8proc.so.3 => /data/data/org.koreader.launcher/files/libs/libutf8proc.so.3
09-08 20:49:09.646 V/dlopen  (10509):     dl.dlopen - needed => libc.so (1 of 1) <= /data/data/org.koreader.launcher/files/libs/libutf8proc.so.3
09-08 20:49:09.647 V/dlopen  (10509):     dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:09.647 V/dlopen  (10509):     dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:09.647 V/dlopen  (10509): dl.dlopen - load_func -> /data/data/org.koreader.launcher/files/libs/libutf8proc.so.3
09-08 20:49:09.648 W/linker  (10509): libutf8proc.so.3: unused DT entry: type 0xf arg 0x28a
09-08 20:49:09.648 W/linker  (10509): libutf8proc.so.3: unused DT entry: type 0x6ffffef5 arg 0x494
09-08 20:49:09.648 W/linker  (10509): libutf8proc.so.3: unused DT entry: type 0x6ffffffe arg 0x474
09-08 20:49:09.648 W/linker  (10509): libutf8proc.so.3: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:09.782 W/dlopen  (10509): could not find library blitbuffer
09-08 20:49:09.782 I/dlopen  (10509): dl.dlopen - ./libs/libblitbuffer.so => /data/data/org.koreader.launcher/files/./libs/libblitbuffer.so
09-08 20:49:09.789 V/dlopen  (10509):     dl.dlopen - needed => libc.so (1 of 1) <= /data/data/org.koreader.launcher/files/./libs/libblitbuffer.so
09-08 20:49:09.789 V/dlopen  (10509):     dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:09.789 V/dlopen  (10509):     dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:09.789 V/dlopen  (10509): dl.dlopen - load_func -> /data/data/org.koreader.launcher/files/./libs/libblitbuffer.so
09-08 20:49:09.790 W/linker  (10509): libblitbuffer.so: unused DT entry: type 0xf arg 0x1be
09-08 20:49:09.790 W/linker  (10509): libblitbuffer.so: unused DT entry: type 0x6ffffef5 arg 0x418
09-08 20:49:09.790 W/linker  (10509): libblitbuffer.so: unused DT entry: type 0x6ffffffe arg 0x3f8
09-08 20:49:09.790 W/linker  (10509): libblitbuffer.so: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:09.809 V/KOReader(10509): fts: Preferred MONOTONIC clock source is CLOCK_MONOTONIC
09-08 20:49:09.809 V/KOReader(10509): fts: Preferred REALTIME clock source is CLOCK_REALTIME
09-08 20:49:09.809 V/KOReader(10509): fts: BOOTTIME clock source is supported
09-08 20:49:09.835 I/KOReader(10509): Android 1.6.50.14130 - Lollipop (API 22) - flavor: rocks
09-08 20:49:10.045 V/Timeout (10509): screen on: switching to true
09-08 20:49:10.046 V/Timeout (10509): add FLAG_KEEP_SCREEN_ON
09-08 20:49:10.056 I/KOReader(10509): initializing for device fpx_1010
09-08 20:49:10.056 I/KOReader(10509): framebuffer resolution: {
09-08 20:49:10.056 I/KOReader(10509):   h = 1650,
09-08 20:49:10.056 I/KOReader(10509):   w = 2200
09-08 20:49:10.056 I/KOReader(10509): } --[[table: 0x5cab2240]]
09-08 20:49:10.073 I/dlopen  (10509): dl.dlopen - libs/libwrap-mupdf.so => /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.083 V/dlopen  (10509):     dl.dlopen - needed => libfreetype.so.6 (1 of 8) <= /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.084 V/dlopen  (10509):     dl.dlopen - libfreetype.so.6 => /data/data/org.koreader.launcher/files/libs/libfreetype.so.6
09-08 20:49:10.085 V/dlopen  (10509):         dl.dlopen - needed => libc.so (1 of 1) <= /data/data/org.koreader.launcher/files/libs/libfreetype.so.6
09-08 20:49:10.085 V/dlopen  (10509):         dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.085 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.085 V/dlopen  (10509):     sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libfreetype.so.6 (in local namespace)
09-08 20:49:10.086 W/linker  (10509): libfreetype.so.6: unused DT entry: type 0xf arg 0x11ca
09-08 20:49:10.086 W/linker  (10509): libfreetype.so.6: unused DT entry: type 0x6ffffef5 arg 0x13fc
09-08 20:49:10.086 W/linker  (10509): libfreetype.so.6: unused DT entry: type 0x6ffffffe arg 0x13dc
09-08 20:49:10.086 W/linker  (10509): libfreetype.so.6: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:10.086 V/dlopen  (10509):     dl.dlopen - needed => libharfbuzz.so.0 (2 of 8) <= /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.087 V/dlopen  (10509):     dl.dlopen - libharfbuzz.so.0 => /data/data/org.koreader.launcher/files/libs/libharfbuzz.so.0
09-08 20:49:10.088 V/dlopen  (10509):         dl.dlopen - needed => libfreetype.so.6 (1 of 3) <= /data/data/org.koreader.launcher/files/libs/libharfbuzz.so.0
09-08 20:49:10.088 V/dlopen  (10509):         dl.dlopen - libfreetype.so.6 => /data/data/org.koreader.launcher/files/libs/libfreetype.so.6
09-08 20:49:10.089 V/dlopen  (10509):             dl.dlopen - needed => libc.so (1 of 1) <= /data/data/org.koreader.launcher/files/libs/libfreetype.so.6
09-08 20:49:10.096 V/dlopen  (10509):             dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.096 V/dlopen  (10509):             dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.096 V/dlopen  (10509):         sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libfreetype.so.6 (in local namespace)
09-08 20:49:10.096 V/dlopen  (10509):         dl.dlopen - needed => libm.so (2 of 3) <= /data/data/org.koreader.launcher/files/libs/libharfbuzz.so.0
09-08 20:49:10.096 V/dlopen  (10509):         dl.dlopen - libm.so => /system/lib/libm.so
09-08 20:49:10.096 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libm.so (system lib)
09-08 20:49:10.096 V/dlopen  (10509):         dl.dlopen - needed => libc.so (3 of 3) <= /data/data/org.koreader.launcher/files/libs/libharfbuzz.so.0
09-08 20:49:10.096 V/dlopen  (10509):         dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.096 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.096 V/dlopen  (10509):     sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libharfbuzz.so.0 (in local namespace)
09-08 20:49:10.097 W/linker  (10509): libharfbuzz.so.0: unused DT entry: type 0xf arg 0x198e0
09-08 20:49:10.097 W/linker  (10509): libharfbuzz.so.0: unused DT entry: type 0x6ffffef5 arg 0x7260
09-08 20:49:10.097 W/linker  (10509): libharfbuzz.so.0: unused DT entry: type 0x6ffffffe arg 0x7220
09-08 20:49:10.097 W/linker  (10509): libharfbuzz.so.0: unused DT entry: type 0x6fffffff arg 0x2
09-08 20:49:10.099 V/dlopen  (10509):     dl.dlopen - needed => libjpeg.so.8 (3 of 8) <= /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.100 V/dlopen  (10509):     dl.dlopen - libjpeg.so.8 => /data/data/org.koreader.launcher/files/libs/libjpeg.so.8
09-08 20:49:10.100 V/dlopen  (10509):         dl.dlopen - needed => libc.so (1 of 1) <= /data/data/org.koreader.launcher/files/libs/libjpeg.so.8
09-08 20:49:10.101 V/dlopen  (10509):         dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.101 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.101 V/dlopen  (10509):     sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libjpeg.so.8 (in local namespace)
09-08 20:49:10.101 W/linker  (10509): libjpeg.so.8: unused DT entry: type 0xf arg 0x1046
09-08 20:49:10.101 W/linker  (10509): libjpeg.so.8: unused DT entry: type 0x6ffffef5 arg 0x1190
09-08 20:49:10.101 W/linker  (10509): libjpeg.so.8: unused DT entry: type 0x6ffffffe arg 0x1170
09-08 20:49:10.101 W/linker  (10509): libjpeg.so.8: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:10.101 V/dlopen  (10509):     dl.dlopen - needed => libwebp.so.7 (4 of 8) <= /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.102 V/dlopen  (10509):     dl.dlopen - libwebp.so.7 => /data/data/org.koreader.launcher/files/libs/libwebp.so.7
09-08 20:49:10.109 V/dlopen  (10509):         dl.dlopen - needed => libsharpyuv.so.0 (1 of 3) <= /data/data/org.koreader.launcher/files/libs/libwebp.so.7
09-08 20:49:10.109 V/dlopen  (10509):         dl.dlopen - libsharpyuv.so.0 => /data/data/org.koreader.launcher/files/libs/libsharpyuv.so.0
09-08 20:49:10.110 V/dlopen  (10509):             dl.dlopen - needed => libm.so (1 of 2) <= /data/data/org.koreader.launcher/files/libs/libsharpyuv.so.0
09-08 20:49:10.110 V/dlopen  (10509):             dl.dlopen - libm.so => /system/lib/libm.so
09-08 20:49:10.110 V/dlopen  (10509):             dl.dlopen - skipping /system/lib/libm.so (system lib)
09-08 20:49:10.110 V/dlopen  (10509):             dl.dlopen - needed => libc.so (2 of 2) <= /data/data/org.koreader.launcher/files/libs/libsharpyuv.so.0
09-08 20:49:10.110 V/dlopen  (10509):             dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.110 V/dlopen  (10509):             dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.110 V/dlopen  (10509):         sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libsharpyuv.so.0 (in local namespace)
09-08 20:49:10.110 W/linker  (10509): libsharpyuv.so.0: unused DT entry: type 0xf arg 0xe4
09-08 20:49:10.110 W/linker  (10509): libsharpyuv.so.0: unused DT entry: type 0x6ffffef5 arg 0x35c
09-08 20:49:10.110 W/linker  (10509): libsharpyuv.so.0: unused DT entry: type 0x6ffffffe arg 0x31c
09-08 20:49:10.110 W/linker  (10509): libsharpyuv.so.0: unused DT entry: type 0x6fffffff arg 0x2
09-08 20:49:10.111 V/dlopen  (10509):         dl.dlopen - needed => libm.so (2 of 3) <= /data/data/org.koreader.launcher/files/libs/libwebp.so.7
09-08 20:49:10.111 V/dlopen  (10509):         dl.dlopen - libm.so => /system/lib/libm.so
09-08 20:49:10.111 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libm.so (system lib)
09-08 20:49:10.111 V/dlopen  (10509):         dl.dlopen - needed => libc.so (3 of 3) <= /data/data/org.koreader.launcher/files/libs/libwebp.so.7
09-08 20:49:10.111 V/dlopen  (10509):         dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.111 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.111 V/dlopen  (10509):     sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libwebp.so.7 (in local namespace)
09-08 20:49:10.111 W/linker  (10509): libwebp.so.7: unused DT entry: type 0xf arg 0x79d
09-08 20:49:10.111 W/linker  (10509): libwebp.so.7: unused DT entry: type 0x6ffffef5 arg 0xa74
09-08 20:49:10.112 W/linker  (10509): libwebp.so.7: unused DT entry: type 0x6ffffffe arg 0xa34
09-08 20:49:10.112 W/linker  (10509): libwebp.so.7: unused DT entry: type 0x6fffffff arg 0x2
09-08 20:49:10.112 V/dlopen  (10509):     dl.dlopen - needed => libwebpdemux.so.2 (5 of 8) <= /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.112 V/dlopen  (10509):     dl.dlopen - libwebpdemux.so.2 => /data/data/org.koreader.launcher/files/libs/libwebpdemux.so.2
09-08 20:49:10.112 V/dlopen  (10509):         dl.dlopen - needed => libwebp.so.7 (1 of 2) <= /data/data/org.koreader.launcher/files/libs/libwebpdemux.so.2
09-08 20:49:10.113 V/dlopen  (10509):         dl.dlopen - libwebp.so.7 => /data/data/org.koreader.launcher/files/libs/libwebp.so.7
09-08 20:49:10.113 V/dlopen  (10509):             dl.dlopen - needed => libsharpyuv.so.0 (1 of 3) <= /data/data/org.koreader.launcher/files/libs/libwebp.so.7
09-08 20:49:10.113 V/dlopen  (10509):             dl.dlopen - libsharpyuv.so.0 => /data/data/org.koreader.launcher/files/libs/libsharpyuv.so.0
09-08 20:49:10.114 V/dlopen  (10509):                 dl.dlopen - needed => libm.so (1 of 2) <= /data/data/org.koreader.launcher/files/libs/libsharpyuv.so.0
09-08 20:49:10.114 V/dlopen  (10509):                 dl.dlopen - libm.so => /system/lib/libm.so
09-08 20:49:10.114 V/dlopen  (10509):                 dl.dlopen - skipping /system/lib/libm.so (system lib)
09-08 20:49:10.114 V/dlopen  (10509):                 dl.dlopen - needed => libc.so (2 of 2) <= /data/data/org.koreader.launcher/files/libs/libsharpyuv.so.0
09-08 20:49:10.114 V/dlopen  (10509):                 dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.114 V/dlopen  (10509):                 dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.114 V/dlopen  (10509):             sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libsharpyuv.so.0 (in local namespace)
09-08 20:49:10.114 V/dlopen  (10509):             dl.dlopen - needed => libm.so (2 of 3) <= /data/data/org.koreader.launcher/files/libs/libwebp.so.7
09-08 20:49:10.115 V/dlopen  (10509):             dl.dlopen - libm.so => /system/lib/libm.so
09-08 20:49:10.115 V/dlopen  (10509):             dl.dlopen - skipping /system/lib/libm.so (system lib)
09-08 20:49:10.115 V/dlopen  (10509):             dl.dlopen - needed => libc.so (3 of 3) <= /data/data/org.koreader.launcher/files/libs/libwebp.so.7
09-08 20:49:10.115 V/dlopen  (10509):             dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.115 V/dlopen  (10509):             dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.115 V/dlopen  (10509):         sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libwebp.so.7 (in local namespace)
09-08 20:49:10.115 V/dlopen  (10509):         dl.dlopen - needed => libc.so (2 of 2) <= /data/data/org.koreader.launcher/files/libs/libwebpdemux.so.2
09-08 20:49:10.122 V/dlopen  (10509):         dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.122 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.122 V/dlopen  (10509):     sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libwebpdemux.so.2 (in local namespace)
09-08 20:49:10.123 W/linker  (10509): libwebpdemux.so.2: unused DT entry: type 0xf arg 0x24e
09-08 20:49:10.123 W/linker  (10509): libwebpdemux.so.2: unused DT entry: type 0x6ffffef5 arg 0x428
09-08 20:49:10.123 W/linker  (10509): libwebpdemux.so.2: unused DT entry: type 0x6ffffffe arg 0x408
09-08 20:49:10.123 W/linker  (10509): libwebpdemux.so.2: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:10.123 V/dlopen  (10509):     dl.dlopen - needed => libz.so.1 (6 of 8) <= /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.123 V/dlopen  (10509):     dl.dlopen - libz.so.1 => /data/data/org.koreader.launcher/files/libs/libz.so.1
09-08 20:49:10.124 V/dlopen  (10509):         dl.dlopen - needed => libc.so (1 of 1) <= /data/data/org.koreader.launcher/files/libs/libz.so.1
09-08 20:49:10.124 V/dlopen  (10509):         dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.124 V/dlopen  (10509):         dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.124 V/dlopen  (10509):     sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libz.so.1 (in local namespace)
09-08 20:49:10.125 W/linker  (10509): libz.so.1: unused DT entry: type 0xf arg 0x56f
09-08 20:49:10.125 W/linker  (10509): libz.so.1: unused DT entry: type 0x6ffffef5 arg 0xb38
09-08 20:49:10.125 W/linker  (10509): libz.so.1: unused DT entry: type 0x6ffffffe arg 0xb18
09-08 20:49:10.125 W/linker  (10509): libz.so.1: unused DT entry: type 0x6fffffff arg 0x1
09-08 20:49:10.125 V/dlopen  (10509):     dl.dlopen - needed => liblog.so (7 of 8) <= /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.125 V/dlopen  (10509):     dl.dlopen - liblog.so => /system/lib/liblog.so
09-08 20:49:10.125 V/dlopen  (10509):     dl.dlopen - skipping /system/lib/liblog.so (system lib)
09-08 20:49:10.125 V/dlopen  (10509):     dl.dlopen - needed => libc.so (8 of 8) <= /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.125 V/dlopen  (10509):     dl.dlopen - libc.so => /system/lib/libc.so
09-08 20:49:10.125 V/dlopen  (10509):     dl.dlopen - skipping /system/lib/libc.so (system lib)
09-08 20:49:10.126 V/dlopen  (10509): dl.dlopen - load_func -> /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so
09-08 20:49:10.126 W/linker  (10509): libwrap-mupdf.so: unused DT entry: type 0xf arg 0x1064
09-08 20:49:10.126 W/linker  (10509): libwrap-mupdf.so: unused DT entry: type 0x6ffffef5 arg 0x161c
09-08 20:49:10.126 W/linker  (10509): libwrap-mupdf.so: unused DT entry: type 0x6ffffffe arg 0x15bc
09-08 20:49:10.126 W/linker  (10509): libwrap-mupdf.so: unused DT entry: type 0x6fffffff arg 0x3
09-08 20:49:10.128 E/NativeThread(10509): Failed to run script: setupkoenv.lua:27: Not able to load dynamic library: libs/libwrap-mupdf.so
...
```
</details>

**Comment by benoit-pierre** [comment] 2024-09-08 19:40
Duplicate of #12482, #12348. Try the latest nightly.

**Closed by benoit-pierre** 2024-09-08 19:40 UTC
Labels: Android, duplicate

**Comment by benoit-pierre** [comment] 2024-09-08 19:44
Scratch that, you'll need the build linked at the end of #12348 for now.

**Comment by SteadyQuad** [comment] 2024-09-08 19:58
> Scratch that, you'll need the build linked at the end of #12348 for now.

Thanks, that dev build fixes the issue!
