### ISSUE TITLE
Segfaults with AppImage on Void Linux

### ISSUE THREAD

**Issue by emacsomancer** [koreader/koreader#4498] opened 2019-01-20 02:00 UTC
* KOReader version: KOReader 2019.01 "Public Domain 1923" (and also the prior 3 releases)
* Device: x86_64 laptop

#### Issue
AppImage segfaults
#### Steps to reproduce
Download AppImage, make executable, run via `./koreader...`
##### `crash.log` (if applicable)
When running via terminal, following is displayed:

```
 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 01/19/19-19:00:02
 [*] Version: v2019.01.1

01/19/19-19:00:02 WARN  cannot open translation file: l10n/en_GB:en_US/koreader.po
ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (assisted searchpath): ./libs/libSDL2.so
ffi.load: SDL
Segmentation fault
```

**Comment by Galunid** [comment] 2019-01-20 02:52
Possibly related to #4485?

**Comment by emacsomancer** [comment] 2019-01-20 03:42
Could be - it complained about SDL being missing before. But once SDL was installed, I got the above behaviour. It looks like https://github.com/koreader/koreader/pull/4488 properly bundles SDL into the AppImage?

**Comment by Frenzie** [comment] 2019-01-20 08:20
You can grab the latest AppImage from [here](https://gitlab.com/koreader/nightly-builds/-/jobs/148267166) (download job artifacts) to give it a try.

Besides that, in your case it looks like it's loading SDL, not SDL2. That should also work in theory. Could you run it with --debug to see at what point it crashes?

**Comment by Frenzie** [comment] 2019-02-21 17:38
@emacsomancer Could this be a duplicate of #4627? If it is, it might be fixed in tomorrow's nightly. And if it isn't, it'd be helpful if you could post the new log. :-)

**Comment by Frenzie** [comment] 2019-02-21 17:39
PS Nightlies available [here](http://build.koreader.rocks/download/nightly/).

**Comment by Frenzie** [comment] 2019-02-26 10:26
I will close this now. Please reopen with more info if necessary.

**Closed by Frenzie** 2019-02-26 10:26 UTC
Labels: AppImage, need more info
