### ISSUE TITLE
Filebrowser doesn't display .cbr files

### ISSUE THREAD

**Issue by Sopheus** [koreader/koreader#4520] opened 2019-01-28 03:15 UTC
* KOReader version: KOReader 2019.01 "Public Domain 1923"
* Device: Kobo Aura H2O (First edition)

#### Issue
Filebrowser doesn't display .cbr files

#### Steps to reproduce
Copy files, navigate to respective folder, observe the issue

**Comment by Sopheus** [comment] 2019-01-28 03:20
Attach

**Comment by Sopheus** [comment] 2019-01-28 03:37
https://drive.google.com/file/d/1H_zm5o9uHYCXszYZ8JAesJyjS0XsekxX/view?usp=sharing

**Comment by Sopheus** [comment] 2019-01-28 03:40
After I changed the extension to .cbz, I can see the file in File Browser, but unable to open it, getting "No reader engine for this file or invalid file" error.

**Comment by Sopheus** [comment] 2019-01-28 03:41
Wanted to add that I can open the .cbr files in Nickel

**Comment by Sopheus** [comment] 2019-01-28 07:53
Here is the file, which I unable to open in Koreader, but able in Nickel: https://drive.google.com/file/d/1H_zm5o9uHYCXszYZ8JAesJyjS0XsekxX/view?usp=sharing

**Comment by poire-z** [comment] 2019-01-28 11:31
Duplicate of #1517.
(There is no unrar support in KOReader - except some in crengine - but CBR would need MuPDF to be able to read RAR files.)

**Comment by KenMaltby** [comment] 2019-01-28 14:12
The RAR compressor will let you create a RAR file that uses the ZIP compression of the data, sometimes a comic book gets made a .cbr that is, actually zip compressed.  Not the case here apparently.

**Comment by cramoisi** [comment] 2019-02-07 13:18
@Sopheus Use nickel as it supports them. Or if you want to be koreader all along, you just have to change the extension of your cbr to rar ; then unrar the file, zip it and rename it to cbz :)

**Comment by Frenzie** [comment] 2019-02-21 15:44
Closing since it's a duplicate.

**Closed by Frenzie** 2019-02-21 15:44 UTC
Labels: duplicate
