### ISSUE TITLE
Hold word in dictionary crash

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader#10565] opened 2023-06-11 16:35 UTC
* KOReader version: 2023.05.1-2
* Device: kindle pw5

#### Issue

When holding on a specific word in a dictionary entry (to look it up) koreader crashes.
#### Steps to reproduce

Look up `אכלסין` with this [dictionary](https://kindleseforim.paritcher.com/files/Jastrow/Jastrow.zip). And try to hold the word `אֲלַכְסִין`.
##### `crash.log` (if applicable)

<details>
  <summary>crash.log</summary>

```
06/11/23-12:22:14 DEBUG slot 0 in hold state... 
06/11/23-12:22:14 DEBUG hold_release detected @ 183 537 
06/11/23-12:22:14 DEBUG dict lookup word: אכלסין nil 
06/11/23-12:22:14 DEBUG dict stripped word: אכלסין 
06/11/23-12:22:14 DEBUG UIManager:preventStandby, counter increased to 1 
06/11/23-12:22:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/notice-info.svg 83 83 
06/11/23-12:22:14 DEBUG ImageWidget: initial offsets 0 0 
06/11/23-12:22:14 DEBUG show widget: table: 0xb3802a38 
06/11/23-12:22:14 DEBUG setDirty nil from widget table: 0xb3802a38 w/ NO region; dithering: nil 
06/11/23-12:22:14 DEBUG UIManager:_standbyTransition -> PreventStandby 
06/11/23-12:22:14 DEBUG setDirty via a func from widget table: 0xb3802a38 
06/11/23-12:22:14 DEBUG painting widget: table: 0xb3802a38 
06/11/23-12:22:14 DEBUG blitFrom 154 782 0 0 83 83 
06/11/23-12:22:14 DEBUG _refresh: Enqueued ui update for region 139 742 958 164 dithering: false 
06/11/23-12:22:14 DEBUG triggering refresh {
  mode = "ui",
  region = "958x164+139+742"
} --[[table: 0xb3879540]] 
06/11/23-12:22:14 DEBUG refresh: ui-mode 139 742 958 164 nil 
06/11/23-12:22:14 DEBUG mxc_update: 958x164 region @ (139, 742) with marker 48 (WFM: 257 & UPD: 0) 
06/11/23-12:22:14 DEBUG showing quick lookup window 2 : אכלסין {
  {
    definition = "<san dir=ltr>\n<strong dir=\"rtl\">אכלסין</strong> , v. <a dir=\"rtl\" class=\"refLink\" href=\"/Jastrow,_אֲלַכְסִין.1\" data-ref=\"Jastrow, אֲלַכְסִין 1\">אֲלַכְסִין</a></span>",
    dict = "Jastrow",
    is_html = true,
    word = "אכלסין"
  } --[[table: 0xb37dc9b8]]
} --[[table: 0xb37dcac0]] 
06/11/23-12:22:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/appbar.menu.svg 50 50 
06/11/23-12:22:14 DEBUG ImageWidget: initial offsets 0 0 
06/11/23-12:22:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/close.svg 50 50 
06/11/23-12:22:14 DEBUG ImageWidget: initial offsets 0 0 
06/11/23-12:22:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/edit.svg 66 66 
06/11/23-12:22:14 DEBUG ImageWidget: initial offsets 0 0 
error: missing quote character
06/11/23-12:22:14 WARN  HTML loading error: ./ffi/mupdf.lua:78: MuPDF cannot open document from text: missing quote character (2) 
06/11/23-12:22:14 DEBUG close widget: table: 0xb3802a38 
06/11/23-12:22:14 DEBUG setDirty via a func from widget nil 
06/11/23-12:22:14 DEBUG Lower widget ReaderUI covers the full screen 
06/11/23-12:22:14 DEBUG setDirty nil from widget ReaderUI w/ NO region; dithering: nil 
06/11/23-12:22:14 DEBUG setDirty nil from widget table: 0xaebb9090 w/ NO region; dithering: nil 
06/11/23-12:22:14 DEBUG show widget: table: 0xb3863648 
06/11/23-12:22:14 DEBUG setDirty nil from widget table: 0xb3863648 w/ NO region; dithering: nil 
06/11/23-12:22:14 DEBUG setDirty via a func from widget table: 0xb3863648 
06/11/23-12:22:14 DEBUG UIManager:allowStandby, counter decreased to 0 
06/11/23-12:22:14 DEBUG painting widget: ReaderUI 
06/11/23-12:22:14 DEBUG readerview painting "1236x1648+0+0" to 0 0 
06/11/23-12:22:14 DEBUG CreDocument: goto page 6 flow 0 
06/11/23-12:22:14 DEBUG blitFrom 60 1620 0 0 8 8 
06/11/23-12:22:14 DEBUG painting widget: table: 0xaebb9090 
06/11/23-12:22:14 DEBUG blitFrom 109 334 0 0 50 50 
06/11/23-12:22:14 DEBUG blitFrom 1076 334 0 0 50 50 
06/11/23-12:22:14 DEBUG blitFrom 1062 433 0 0 66 66 
06/11/23-12:22:14 DEBUG painting widget: table: 0xb3863648 
06/11/23-12:22:14 DEBUG blitFrom 109 334 0 0 50 50 
06/11/23-12:22:14 DEBUG blitFrom 1076 334 0 0 50 50 
06/11/23-12:22:14 DEBUG blitFrom 1062 433 0 0 66 66 
06/11/23-12:22:14 DEBUG _refresh: Enqueued ui update for region 139 742 958 164 dithering: false 
06/11/23-12:22:14 DEBUG update_mode: Update refresh mode ui to flashui 
06/11/23-12:22:14 DEBUG _refresh: Enqueued flashui update for region 82 307 1071 993 dithering: false 
06/11/23-12:22:14 DEBUG triggering refresh {
  mode = "flashui",
  region = "1071x993+82+307"
} --[[table: 0xb553ecb8]] 
06/11/23-12:22:14 DEBUG refresh: ui-mode w/ flash 82 307 1071 993 nil 
06/11/23-12:22:14 DEBUG refresh: wait for submission of (previous) marker 48 
06/11/23-12:22:14 DEBUG mxc_update: 1071x993 region @ (82, 307) with marker 49 (WFM: 257 & UPD: 1) 
06/11/23-12:22:14 DEBUG refresh: wait for completion of marker 49 
06/11/23-12:22:15 DEBUG UIManager:_standbyTransition -> AllowStandby
Snip.. (touch input events)
06/11/23-12:22:18 DEBUG slot 0 in hold state... 
06/11/23-12:22:18 DEBUG hold_release detected @ 367 557 
./luajit: frontend/ui/widget/htmlboxwidget.lua:186: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
	[C]: in function 'pairs'
	frontend/ui/widget/htmlboxwidget.lua:186: in function 'getSelectedText'
	frontend/ui/widget/htmlboxwidget.lua:237: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:261: in function 'handleEvent'
	frontend/ui/uimanager.lua:886: in function 'sendEvent'
	frontend/ui/uimanager.lua:51: in function '__default__'
	frontend/ui/uimanager.lua:1415: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1513: in function 'handleInput'
	frontend/ui/uimanager.lua:1557: in function 'run'
	./reader.lua:295: in main chunk
	[C]: at 0x00014121
```
</details>

**Comment by poire-z** [comment] 2023-06-11 18:09
The crash seems caused by the classic error of using pairs() instead of ipairs() and meeting the non-array element `"size"=498`
https://github.com/koreader/koreader/blob/f7d633cc3d0efd273a875132ac2de4fb4754dd02/frontend/ui/widget/htmlboxwidget.lua#L185-L186
`lines` comes from https://github.com/koreader/koreader-base/blob/b932d1ed714774e5837d640e7cdb5ac120be5420/ffi/mupdf.lua#L567-L578

Probably also:
https://github.com/koreader/koreader/blob/f7d633cc3d0efd273a875132ac2de4fb4754dd02/frontend/ui/widget/htmlboxwidget.lua#L249

So, ok, switching to ipairs() solves the crash.
(I'll do as if I had not noticed that then, long-press on that last word of yours does not work :/ :)

**Comment by poire-z** [comment] 2023-06-11 18:34
> (I'll do as if I had not noticed that then, long-press on that last word of yours does not work :/ :)

It works if long-press on the first letter on the left of that word on the right:
![image](https://github.com/koreader/koreader/assets/24273478/a8cdea38-9d14-4405-8bc0-26a6ff111c43)

The info about the line returned by 

```lua
  {
    {
      word = "××¡××", -- the hebrew word on the left
      x0 = 3.814697265625e-06,
      x1 = 50.004001617431641, -- so, 47px wide
      y0 = 2.6999998092651367,
      y1 = 20.700000762939453
    } --[[table: 0x7ff28bb043b0]],
    {
      word = ",",
      x0 = 54.684001922607422,
      x1 = 59.508003234863281,
      y0 = -2.1420001983642578,
      y1 = 22.374000549316406
    } --[[table: 0x7ff28bb044c0]],
    {
      word = "v.",
      x0 = 64.188003540039063,
      x1 = 77.435997009277344,
      y0 = -2.1420001983642578,
      y1 = 22.374000549316406
    } --[[table: 0x7ff28bb045d0]],
    {
      word = "×Ö·×Ö°×¡Ö´××", -- the hebrew word on the right
      x0 = 82.116012573242188,
      x1 = 93.456016540527344, -- only 11px wide !!
      y0 = 2.6999998092651367,
      y1 = 20.700000762939453
    } --[[table: 0x7ff28bb046e0]],
    x0 = 3.814697265625e-06,
    x1 = 93.456016540527344,
    y0 = -2.1420001983642578,
    y1 = 22.374000549316406
  } --[[table: 0x7ff28bb042e8]],
```
It's still not as wide as it should be if I remove all the HTML and add another LTR word on the right:
```lua
    {
      word = "×Ö·×Ö°×¡Ö´××",
      x0 = 82.116012573242188,
      x1 = 93.456016540527344,
      y0 = 2.6999998092651367,
      y1 = 20.700000762939453
    } --[[table: 0x7fc7316d3bc0]],
    {
      word = "zzz",
      x0 = 136.80000305175781,
      x1 = 162.18000793457031,
      y0 = -2.1420001983642578,
      y1 = 22.374000549316406
    } --[[table: 0x7fc7313fa528]],
```
So, dunno if it's MuPDF or our code at https://github.com/koreader/koreader-base/blob/b932d1ed714774e5837d640e7cdb5ac120be5420/ffi/mupdf.lua#L491-L575 that is confused (because some of this stuff is RTL and we need to do something better for that case ?)

**Comment by yparitcher** [comment] 2023-06-11 19:50
I have noticed it is hard to select hebrew words sometimes, now i know why (and the workaround: try the leftmost letter)

We use the start of the first letter and the end of the last. Mupdf provides those positions, my guess is that the first hebrew letter starts at the **left** of the word and takes up one letter at the **right** of the word, then the letters go to the left, with the last letter starting one letter from the left and ending almost by the left of the word.
Think of how when pressing the right arrow between ltr-rtl text it goes one letter to theright then jumps to the right of the word then goes one letter to the left then jumps to the next word.

**Comment by offset-torque** [comment] 2023-06-12 07:46
@yparitcher 

> I have noticed it is hard to select hebrew words sometimes, now i know why (and the workaround: try the leftmost letter)

Do you think this workaround will be helpful for the users if it is mentioned in the guide ?
(Or this problem will be fixed soon and there is no need)

**Comment by yparitcher** [comment] 2023-06-12 12:53
This is only in a few places like the the dictionary, not in regular document text so i dont know if it is necessary.

**Closed** 2023-06-13 09:52 UTC
Labels: bug
