### ISSUE TITLE
Japanese support fails to finds the longest selection in half of the cases and only goes for one character

### ISSUE THREAD

**Issue by rtega** [koreader/koreader#9428] opened 2022-08-11 13:32 UTC
On version 2022.07 and before on android.

In the following example pasted from the source code in the epub file (it is Miyamoto Musashi by Yoshikawa to be found on aozora):

`<ruby><rb>年端</rb>〘<rt>としは</rt>〙</ruby>もゆかない小娘が、しかも夜、ただひとり月の下で、無数の死骸の中にかくれ、いったい、何を働いているのか。
`

The Japanese support plugin fails to select for the longest possible string of characters in the following words.

In these cases it selects only the first character
- 小娘
- 無数
- 死骸
- のか

In these cases it selects a subset but not the longest possible string:
- いった instead of いったい
- 働いてい instead of 働いている

It's been like this since I first tried it. Am I the only one seeing this behaviour?

@cyphar

**Comment by rtega** [comment] 2022-08-11 14:18
I tried only enabling one dictionary and disabling all but one dictionary. All to no avail. It exhibits the exact same behaviour.

**Comment by cyphar** [comment] 2022-08-11 21:30
That's very strange, I have never seen this behaviour in all of my testing nor personal use of this plugin. Since 青空 is public domain, can you give me the exact EPUB that you had an issue with (since my understanding is that different 青空文庫 websites generate the EPUBs differently)?

**Comment by rtega** [comment] 2022-08-11 22:03
Sure. The dictionary I'm using is apparently to big to upload so I can't send you this.

I'm seeing this on Kobo and android. Not in the emulator. I think I tried it with personally generated epubs from aozora and even from their htmls.

Maybe I'm doing something incredible wrong, but I can't see why it would work half of the time and the other half not.
[problem.tar.gz](https://github.com/koreader/koreader/files/9312398/problem.tar.gz)

**Comment by rtega** [comment] 2022-09-12 13:46
Can I help debugging this somehow? I looked at the logcat while I'm using the dictionary but I don't see anything suspicious.

**Comment by rtega** [comment] 2022-09-15 14:06
I updated to 2022.08 and still the same issue. I converted the text to txt and still the same issue.

**Comment by cyphar** [comment] 2022-09-16 02:46
Sorry, I've been on vacation and while I thought I'd have time to debug this, I didn't. I'll get back home in a few days and I'll try to reproduce and debug this issue then.

**Comment by rtega** [comment] 2022-09-16 06:36
Thanks!

**Comment by cyphar** [comment] 2022-09-18 01:34
I can't reproduce this in the emulator nor on my Android phone (trying to select the same text you mentioned in chapter 4). Are you sure that:

* The words you expect to be auto-selected have headwords in the dictionary? On Android you can't input kanji, but you can look them up by their reading and confirm that they are present.
* That you are not dragging the selection, changing the selected words? (On my tablet at least, visual feedback can be delayed, leading to strange effects.)

Have you had this issue on more than one Android device? I can try to reproduce this on my Android eReader later.

**Comment by rtega** [comment] 2022-09-18 11:12
Affirmative to both questions. 

`The words you expect to be auto-selected have headwords in the dictionary? On Android you can't input kanji, but you can look them up by their reading and confirm that they are present.
`
I can select the text manually as it should and get the results from the dictionary.
`That you are not dragging the selection, changing the selected words? (On my tablet at least, visual feedback can be delayed, leading to strange effects.)`
I thought that as well but no, it is entirely consistent: it always fails on the exact same words in the sentence.

I have the same issue on my kobo device and two android devices (an old samsung s5 and the current samsung S10+ on android 12).

Maybe there is some seemingly unrelated setting that's influencing the behavior?

**Comment by poire-z** [comment] 2022-09-18 11:55
Same behaviour in various kind of documents, and not only in the one document you're always testing with?
Be sure all the parts of the "word" you try/expect to be selected are in the same HTML node (select text around and `View HTML`) - text selection at HTML node boundaries may stop at that boundary - may happen also with western text (ie. when words are capitalized with spans, ie `<span>The <span style="font-size: 110%">G</span>overnment of blah blah</span>` will get it hard to select "Government".)

**Comment by NiLuJe** [comment] 2022-09-18 16:01
Since you've mentioned Kobo, if the file has been mangled into a Kobo ePub, there may be extra spans screwing with this ;).

**Comment by rtega** [comment] 2022-09-18 16:22
I checked on the node boundaries as well. That's not the problem either. I upload my files via ssh so this shouldn't be a problem.

**Comment by cyphar** [comment] 2022-09-19 01:17
What do you see in the logs? The Japanese plugin outputs a debug log entry like `japanese.koplugin: attempted X expansions up to Y` when doing word selection expansion which should tell you when the expansions stopped.

One thing I noticed is that `<ruby><rb>年端</rb>〘<rt>としは</rt>〙</ruby>` is a slightly weird usage of ruby tags and I managed to get koreader to search `年〘〙端` by manually selecting the text, but the autoselection still worked (and many of the words you had issues with did not have furigana).

**Comment by rtega** [comment] 2022-09-19 09:55
Ah, ok, I have to enable debug logging.

**Comment by rtega** [comment] 2022-09-19 12:09
[japplugin-snip.log](https://github.com/koreader/koreader/files/9598662/japplugin-snip.log)

This is the log with debug logging and verbose debug logging enabled. I get exactly the same results with different dictionaries. I can confirm by manually selecting the text that the headwords are in my dictionaries. My dictionaries have been generated with stardict-tools.

**Comment by rtega** [comment] 2022-09-19 12:38
Finally getting somewhere. It looks as though disabled dictionaries are influencing the process. I see references to dictionaries that should be disabled when I'm looking up. I removed all the dictionaries that I had installed and only enable the one I'm using and pronto: it works the way it should.

**Comment by rtega** [comment] 2022-09-19 12:54
It's getting even weirder: after removing all dictionaries and putting them back one by one I thought I had two that seem to be causing issues. After removing them and putting them back (exact same files in the exact same location) now everything seems to be working fine...

**Comment by NiLuJe** [comment] 2022-09-19 18:49
Nope, forget about it, it happens when sdcv segfaults ;).

Which makes this... a sneaky duplicate of #9515 ;).

So, same answer: try with today's nightly?

**Comment by rtega** [comment] 2022-09-22 14:27
I tried with the latest nightly which seems to fix this issue.

**Closed** 2022-10-02 16:46 UTC
Labels: Plugin
