### ISSUE TITLE
Cervantes 4 won't boot on 2021.03

### ISSUE THREAD

**Issue by tjaderxyz** [koreader/koreader#7491] opened 2021-04-02 18:21 UTC
* KOReader version: 2021.03
* Device: Cervantes 4

#### Issue
I updated my Cervantes 4 to the most recent stable release and I haven't been able to boot it since then. I don't know if it is related to issues #7472 and #7485, since I don't recall enabling the dev channel, so maybe something went wrong during my upgrade process.

Pressing the home button while the dots are shown only activates mass storage ([usbms.png](https://raw.githubusercontent.com/pazos/cervantes-safemode/master/images/usbms.png) instead of [usbnet.png](https://raw.githubusercontent.com/pazos/cervantes-safemode/master/images/usbnet.png)), no USB network device appears in the host computer.

Mass storage shares two partitions, in my case one of them has my books and one of them has nothing.

I have my device set to run KOReader on boot, so currently I have no way of getting shell access in order to investigate. The only way I can think of is using the boot from sdcard method explained in bq's page, but I don't have a sdcard reader handy and I'd have to learn how to make a bootable rootfs for it.

##### `crash.log` (if applicable)
I ran `find -name crash.log` in both partitions that I can access and found nothing.

**Comment by NiLuJe** [comment] 2021-04-02 18:46
Yep, dupe of #7485 ;).

**Closed by NiLuJe** 2021-04-02 18:46 UTC
