### ISSUE TITLE
"Change defaults file" not persistent.

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1365] opened 2014-12-17 13:33 UTC
As stated in #1231 the changes are saved, but lost after restarting. Not only the OCR arrays but also simple Gamma settings are not retained.

Is persistent.defaults.lua still saved in the koreader root? Would file access be a problem? crash.log is saved without a problem, though, as are history entries.

**Comment by chrox** [comment] 2015-01-18 04:00
I cannot reproduce this if I change variables that persistent defaults could handle, such as numeric or boolean values.

**Comment by chrox** [comment] 2015-03-31 02:42
Please recheck the disk consistency of your Kobo device. I cannot reproduce this on none of my Kindle, Android or PocketBook device. Close this now. Please feel free to reopen this if you find it's really a koreader problem.

**Closed by chrox** 2015-03-31 02:42 UTC
Labels: bug
