### ISSUE TITLE
Crash with auto night mode [Pocketbook]

### ISSUE THREAD

**Issue by dmalinovsky** [koreader/koreader#9438] opened 2022-08-15 13:29 UTC
I'm using the latest release of the Koreader, 2022.07, on Pocketbook Inkpad Color. I have Auto Night Mode enabled to activate depending on the location settings using "Darkest time of civil twilight". 

If I'm reading book via Koreader before the sunset, then put the reader to sleep and wake it up after the sun goes down, then Koreader crashes.  It happens every time when the auto night mode should turn on.

Here's the excerpt from the [crash.log](https://github.com/koreader/koreader/files/9337458/crash.log):

```
./luajit: plugins/autowarmth.koplugin/main.lua:310: attempt to compare nil with number
stack traceback:
        plugins/autowarmth.koplugin/main.lua:310: in function 'scheduleNextWarmthChange'
        plugins/autowarmth.koplugin/main.lua:132: in function 'leavePowerSavingState'
        plugins/autowarmth.koplugin/main.lua:141: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
        frontend/ui/uimanager.lua:1154: in function 'broadcastEvent'
        frontend/ui/uimanager.lua:1780: in function '_afterResume'
        frontend/ui/uimanager.lua:117: in function 'handler'
        frontend/ui/uimanager.lua:1606: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:1694: in function 'handleInput'
        frontend/ui/uimanager.lua:1744: in function 'run'
        ./reader.lua:275: in main chunk
        [C]: at 0x00013f5d
Segmentation fault
```

**Comment by pazos** [comment] 2022-08-15 13:31
Duplicate of #9434

**Closed by pazos** 2022-08-15 13:31 UTC
