### ISSUE TITLE
Kobo Aura. Change brightness to 100% and redraw fails

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1282] opened 2014-11-28 11:24 UTC
So when you change the brightness from 0% to 100% (in four steps) via the two finger gesture. Then the you have the screen redraw several times (half dotted screen + notifications) but at 100% most of the text gets greyish.

![img_20141128_121044](https://cloud.githubusercontent.com/assets/1377943/5227183/1b38fa20-76f8-11e4-8e9e-89d2f268addf.jpg)

Video: http://a.pomf.se/tgwinm.mp4

**Comment by NiLuJe** [comment] 2018-07-08 00:58
Almost four years old, and can't reproduce, closing :).

**Closed by NiLuJe** 2018-07-08 00:58 UTC
Labels: bug, need more info
