### ISSUE TITLE
Browse a PDF full of images, and swiping will crash the app

### ISSUE THREAD

**Issue by waxwax0099** [koreader/koreader#8036] opened 2021-07-29 06:49 UTC
* KOReader version: v2021.07
* Device:mi 10 pro

#### Steps to reproduce
1 Prepare a PDF that is full of screenshots, not text.
2 Lower right setting: 
       Force OCR-disable  
       Document Language-Chinese
3 Open the PDF, hold the finger in place for 3 seconds or more, then keep your finger pressed and slide a certain distance. 
4 And now, the APP will crash.

If I set the document language to English, it doesn't crash.
##### `crash.log` (if applicable
There is no useful log here, and it is different every time, and it is often empty.

**Comment by NiLuJe** [comment] 2021-07-29 08:24
Duplicate of the Chinese OCR issue (on mobile, annoying to cross ref properly).

**Comment by Frenzie** [comment] 2021-07-29 08:52
Duplicate of https://github.com/koreader/koreader/issues/4481 then. ;-)

**Closed by Frenzie** 2021-07-29 08:52 UTC

**Comment by waxwax0099** [comment] 2021-07-29 09:37
> Duplicate of #4481 then. ;-)

It's really this history bug, thank you.
