### ISSUE TITLE
[Bug] Wrong highlight position

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#2021] opened 2016-05-11 09:23 UTC
- KOReader version: checked since >=2015-11-stable until 2015-11-394
- Device: Kobo Glo HD
#### Issue

**1st example**:
Selection:
![highlight_1_1](https://cloud.githubusercontent.com/assets/17313916/15176229/60d83384-176a-11e6-92f0-33937e92b124.png)
Final highlight:
![highlight_1_2](https://cloud.githubusercontent.com/assets/17313916/15176237/69f5e092-176a-11e6-867c-e4f68f6c1960.png)

**2nd example**:
Selection:
![highlight_2_1](https://cloud.githubusercontent.com/assets/17313916/15176266/8c622190-176a-11e6-8ab3-3a2333328fc5.png)
Final hightlight:
![highlight_2_2](https://cloud.githubusercontent.com/assets/17313916/15176272/95e3c476-176a-11e6-9551-c086bb4fbc31.png)

*Problem maybe related with: #1944 and  #1283
EDIT: to add this new reference: #1252 that still happens

Regards.

O/T (with very little importance at least in theory): With the last OTA version (394), the name of the screenshots generated by koreader have changed their names from Reader_\* to Filemanager_\* , is it correct? I think that I generated the ss using/from the reader, not using/from the filemanager...

**Comment by djalma2k** [comment] 2016-05-11 20:41
Just for clarification. In the following example you can see that one highlight affect to the previous page. In the same page one have a correct position and the others haven't. And finally, it final position not always "jumps" the same number of lines (as if the problem was triggered by the book's syntax)
**3rd example**
![highlight_3_1](https://cloud.githubusercontent.com/assets/17313916/15195492/6aeb8d68-17c8-11e6-89f3-3bd4e88194b9.png)
![highlight_3_2](https://cloud.githubusercontent.com/assets/17313916/15195498/70102a38-17c8-11e6-8fc1-65bc8a426b88.png)

**Comment by djalma2k** [comment] 2016-05-11 22:55
An important thing, and it isn't showed in the previous screenshots, is that sometimes when you want to make the initial selection you have to press in the "final highlight" position, (that changes randomly and you have to guess where it is [trial-error problem] ).

**Comment by frankyifei** [comment] 2016-05-12 13:14
Just want to confirm, I found the padding and border width will affect the position of highlight position. for most of the books, it will not be an issue as they will not use a very large top or left padding. I found a solution for it and still testing.
Another thing that I found is that sometimes I highlighted one word, it will created another shadow area in same page. sometimes it will show the shadow area for every page.

**Comment by houqp** [comment] 2016-05-13 01:40
Yeah, definitely related to two other issues you linked.

**Comment by frankyifei** [comment] 2016-05-16 04:42
the padding and borders of a block will affect the position of a hightlighted area

**Comment by frankyifei** [comment] 2016-05-17 01:51
I think I found the reason why first page's highlights keep showing up in following pages. 
because first page's coordinates are always inside visible_able. And other page's hightlight will change to fit the screen. Then it will draw first page's highlights on every following page.
How to fix this?

**Comment by houqp** [comment] 2016-05-17 02:32
The code in readerview relies on crengine calculating the screen position rect for us, so we only draw the highlight if crengine thinks the highlight falls into the current screen. `getSinglePageRect` should not be called for this case since `self.ui.document.info.has_pages` should be false.

It might be a bug in `getWordBoxesFromPositions` from cre.cpp though. This is probably a regression caused by recent changes because I don't recall having this issue before and we have this highlighting feature for awhile.

**Comment by frankyifei** [comment] 2016-05-17 03:10
I monitored the boxes returned from getScreenBoxesFromPositions, and found it will change the position of a rect to screen coordinates when it is on that page and not change when on other page. For first page's highlight, it will not change on every page. this is from docToWindowRect, which called docToWindowPoint in lvdocview.cpp.

**Comment by frankyifei** [comment] 2016-05-17 03:16
And this is an old bug, I reset the cre to 2015-6 and build the emulator and still have this problem.

**Comment by houqp** [comment] 2016-05-17 04:02
Good call, i forgot it's only happening for the first page. Then it looks like an old crengine bug :(

For me, the highlight in the first page does change on other pages, except it has y set to 0, while for highlights in other pages, the y is set to a very large number that's outside of the screen.

**Comment by frankyifei** [comment] 2016-05-17 04:11
on page one 
```
# boxes {
	[1] = {
		["y"] = 113,
		["x"] = 110,
		["h"] = 44,
		["w"] = 121
	}
}
```
on page two
```
# boxes {
	[1] = {
		["y"] = 98,
		["x"] = 100,
		["h"] = 44,
		["w"] = 121
	}
}
```
one page three
```
# boxes {
	[1] = {
		["y"] = 98,
		["x"] = 100,
		["h"] = 44,
		["w"] = 121
	}
}
```

**Comment by frankyifei** [comment] 2016-05-17 04:16
how to set y of the boxes? can you set page one's highlight to a large number when is not on page one

**Comment by houqp** [comment] 2016-05-17 07:51
So after some more digging in cre.cpp, I found `ldomXRange(words[i]).getRect(wordRect)` is not returning the right `y` for first page highlights. In your case, it must be returning `98` for all other pages. `docToWindowRect` actually did not change the value of `y`.

We can definitely hack around this issue by treating page 1 as special case in `getWordBoxesFromPositions` like you said. But I would rather much prefer we fix the bug in crengine instead.

**Comment by frankyifei** [comment] 2016-05-18 11:17
Ok， i'm working on it.

**Comment by martinrotter** [comment] 2016-06-08 04:45
+1, I also experienced this bug just yesterday. :)

**Comment by Eduardomb22** [comment] 2016-07-12 18:37
I have this bug only with epubs

**Comment by poire-z** [comment] 2018-06-13 16:36
The small horizontal shifts should be fixed by https://github.com/koreader/crengine/pull/204 , available in current nightly.
I've never seen any such huge shifts as on the first screenshot, and there's been a few other highlight fixes these last months, so closing this.

**Closed by poire-z** 2018-06-13 16:36 UTC
Labels: bug, crengine
