### ISSUE TITLE
[Kobo] [framebuffer]: koreader doesn't work with FW 4.2.8432

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#2542] opened 2017-02-16 11:04 UTC
* KOReader version: any recent version
* Devices: Kobo Aura HD / Kobo Aura One / ...
* Ways to launch koreader: fmon, kfmon, advboot, shell

After upgrading to FW 4.2.8432 koreader doesn't start with crash.log:
`...`
` [*] Current time: 02/16/17-11:52:26`
`02/16/17-11:52:26 ERROR cannot open translation file: l10n/en_US/koreader.po`
`./luajit: ./ffi/framebuffer_linux.lua:60: unknown bpp value for the eink driver`
`stack traceback:`
	`[C]: in function 'error'`
	`./ffi/framebuffer_linux.lua:60: in function 'init'`
	`./ffi/framebuffer_mxcfb.lua:290: in function 'init'`
	`./ffi/framebuffer.lua:59: in function 'new'`
	`frontend/device/kobo/device.lua:127: in function 'init'`
	`frontend/device.lua:39: in main chunk`
	`[C]: in function 'require'`
	`frontend/ui/uimanager.lua:1: in main chunk`
	`[C]: in function 'require'`
	`./reader.lua:93: in main chunk`
	`[C]: at 0x00013e85`

_to make it work_

before run koreader:
fbset -geometry 1080 1440 1088 3072 16
echo 3 > /sys/class/graphics/fb0/rotate

after run koreader and before run nickel:
fbset -geometry 1080 1440 1088 3072 32
echo 1 > /sys/class/graphics/fb0/rotate

We should edit koreader.sh, because the current implementation is broken on new firmware (unless opened with KSM8), or add 32 bpp support in koreader.

**Comment by pazos** [comment] 2017-02-16 14:06
Easy peasy:

fbset -geometry 1080 1440 1088 3072 16
echo 3 > /sys/class/graphics/fb0/rotate 

** before ** start koreader

**Comment by Frenzie** [comment] 2017-02-16 15:09
I imagine this is a duplicate of  #2502 which has some investigations into supporting 32 bits. Until such time your workaround might not be a bad thing to add, but of course it can't be added to koreader.sh just like that. I suppose the simplest option would be something along these lines but perhaps checking against device names (`$PLATFORM`, is it?) would be better.

```
if $(fbset -s) -eq "1080 1440 1088 3072 32"
fbset -geometry 1080 1440 1088 3072 16
```

**Comment by pazos** [comment] 2017-02-16 15:47
Those values are device specific (in that case for Kobo Aura). Here is a [hackish device agnostic approach](https://github.com/koreader/koreader/files/780623/test.zip)

As for the rotation value it might change between devices, but I don't know

**Comment by Frenzie** [comment] 2017-02-16 16:12
Right, I suggested device specific values because those would've been tested and confirmed. Naturally a device-agnostic approach is better, but then again it's just a hack in lieu of 32-bit support… Btw, you can just stick a short script like that in using three backticks. Makes it easier to read. ;-)

```bash
#!/bin/sh

geometry=`fbset | grep geometry | sed 's/ /*/g' | xargs`

geom1=`echo $geometry | cut -d "*" -f2`
geom2=`echo $geometry | cut -d "*" -f3`
geom3=`echo $geometry | cut -d "*" -f4`
geom4=`echo $geometry | cut -d "*" -f5`
geom5=`echo $geometry | cut -d "*" -f6`

# before reader.lua
if [ $geom5 -eq 32 ]; then
    last_geom=`fbset | grep geometry | xargs`
    echo "switching to 16bpp mode"
    echo fbset -geometry $geom1 $geom2 $geom3 $geom4 16
fi

# after reader.lua (just in case we don't reboot and go back straight to nickel)
if [ $geom5 -eq 32 ]; then
    echo "returning to 32bpp mode"
    echo fbset -$last_geom
fi
```

Btw, if you take a look at the issue I referenced above perhaps you'd be able to assist somehow?

**Comment by pazos** [comment] 2017-02-17 13:12
@Frenzie thanks for the tip ;)

I'm an hobbie user here, so no clues for the 32 bit support thing. Sorry

**Comment by Frenzie** [comment] 2017-02-17 13:44
In the other bug @hwhw said he'll look at it, so we can safely consider this taken care of. :-) I'll close this issue in favor of the other.

**Closed by Frenzie** 2017-02-17 13:44 UTC

**Comment by pazos** [comment] 2017-02-17 14:46
@hwhw : oh, master! ;)
@Frenzie: please close #2515 too

**Comment by baskerville** [comment] 2017-02-17 20:48
Thanks for the workaround!

I've come up with a short patch:
```diff
diff --git a/platform/kobo/koreader.sh b/platform/kobo/koreader.sh
index 703d146..d914577 100755
--- a/platform/kobo/koreader.sh
+++ b/platform/kobo/koreader.sh
@@ -114,8 +114,11 @@ fi
 # we keep maximum 500K worth of crash log
 cat crash.log 2> /dev/null | tail -c 500000 > crash.log.new
 mv -f crash.log.new crash.log
+FB_BPP=$(cat /sys/class/graphics/fb0/bits_per_pixel)
+[ "$FB_BPP" -gt 16 ] && fbset -depth 16
 ./reader.lua "${args}" >> crash.log 2>&1
 RESULT=$?
+[ "$FB_BPP" -gt 16 ] && fbset -depth "$FB_BPP"
 
 if [ "${FROM_NICKEL}" = "true" ] ; then
 	if [ "${FROM_KFMON}" != "true" ] ; then
```
