### ISSUE TITLE
two successive blank pages rendered at page break in EPUB documents

### ISSUE THREAD

**Issue by bbgordon** [koreader/koreader#2047] opened 2016-05-26 15:42 UTC
- KOReader version: f5b0f0d
- Device: Kindle Voyage

I have an epub with `body { page-break-before: always; }`. KOReader now displays two page breaks between HTML files sometimes. I think this happens if content in the last page of the previous HTML file filled the full screen, like a full-page image or text that happened to run to the last line.
1. Go to title page with full-screen image.
2. Hit next page.
3. A completely blank page is shown.
4. Hit next page again.
5. The next HTML file's content is shown.

Through trial and error I found this was introduced between koreader-nightly-20160323 and  koreader-nightly-20160413 (i.e., 20160413 was the first release with the issue). In ADE and previous KOReader builds there is only one page break between the full-screen image and the next HTML file and no blank page gets shown.

The below patch reverts part of koreader/crengine@d232091ad6f36c76a17e74858a97fcc4261084c1 and makes the issue go away. It probably re-introduces whatever bug it was intended to fix, however. I don't understand enough about the code yet to tell.

```
diff --git a/crengine/src/lvrend.cpp b/crengine/src/lvrend.cpp
index 2500e35..b42dd66 100755
--- a/crengine/src/lvrend.cpp
+++ b/crengine/src/lvrend.cpp
@@ -1705,12 +1705,7 @@ int renderBlockElement( LVRendPageContext & context, ldomNode * enode, int x, in
                     // recurse all sub-blocks for blocks
                     int y = padding_top;
                     int cnt = enode->getChildCount();
-                    lvRect r;
-                    enode->getAbsRect(r);
-                    if (margin_top>0)
-                        context.AddLine(r.top - margin_top, r.top - 1, pagebreakhelper(enode,width));
-                    if (padding_top>0)
-                        context.AddLine(r.top,r.top+padding_top-1,pagebreakhelper(enode,width));
+                    if(measureBorder(enode,0)>0) context.AddLine(0,y,RN_SPLIT_BEFORE);//add line for top border
                     for (int i=0; i<cnt; i++)
                     {
                         ldomNode * child = enode->getChildNode( i );
@@ -1725,10 +1720,9 @@ int renderBlockElement( LVRendPageContext & context, ldomNode * enode, int x, in
                     fmt.setHeight( y + padding_bottom ); //+ margin_top + margin_bottom ); //???
                     lvRect rect;
                     enode->getAbsRect(rect);
-                    if(padding_bottom>0)
-                        context.AddLine(y+rect.top+1,y+rect.top+padding_bottom,RN_SPLIT_AFTER_AUTO);
-                    if(margin_bottom>0)
-                        context.AddLine(y+rect.top+padding_bottom+1,y+rect.top+padding_bottom+margin_bottom,RN_SPLIT_AFTER_AUTO);
+                    if(measureBorder(enode,2)>0)
+                        context.AddLine(y+rect.bottom,y+rect.bottom+padding_bottom,RN_SPLIT_AUTO);//add line for bottom border
+
                     if ( isFootNoteBody )
                         context.leaveFootNote();
                     return y + margin_top + margin_bottom + padding_bottom; // return block height
@@ -1776,10 +1770,6 @@ int renderBlockElement( LVRendPageContext & context, ldomNode * enode, int x, in
             enode->getAbsRect(rect);
             // split pages
             if ( context.getPageList() != NULL ) {
-                if (margin_top>0)
-                        context.AddLine(rect.top-margin_top,rect.top-1,pagebreakhelper(enode,width));
-                if (padding_top>0)
-                        context.AddLine(rect.top,rect.top+padding_top,pagebreakhelper(enode,width));
                 css_page_break_t before, inside, after;
                 //before = inside = after = css_pb_auto;
                 before = getPageBreakBefore( enode );
```

**Comment by djalma2k** [comment] 2016-05-26 18:17
It isn't exactly the same but this reminds me to #2017. Maybe it's related somehow...

**Comment by bbgordon** [comment] 2016-05-26 22:59
I can generate a minimal test case EPUB if needed.

Calibre does something similar to this, though it puts the page break on a class that's given for all body tags instead of the body tag itself. I haven't checked if it occurs for Calibre EPUBs.

**Comment by houqp** [comment] 2016-05-29 01:39
Thanks @bbgordon for the quality bug report! Yes, a minimal test case would be very nice to have. We can also use that to write a regression test for this regression.

**Comment by frankyifei** [comment] 2016-05-29 13:19
in default epub.css, there is a line for DocFragment, which looks like this `DocFragment{page-break-before:always}`
<body> is treated as a child node of each html file(DocFragment), so there is two compulsory page-break at the beginning of each html in your Epub. If you can try apply other css and tell us the results, that would be helpful.

**Comment by bbgordon** [comment] 2016-06-02 00:41
Ah, the DocFragment might be it! If I set render style to "clear all external styles" the blank page goes away.

To create a small test case I converted the below HTML with Calibre's `ebook-convert pagebreak.html pagebreak.epub` and renamed pagebreak.epub to .zip so I could attach it. All Calibre settings are defaults. I wasn't able to make a blank page appear in ADE, nor Calibre even when I resized the viewer window as small as it let me.

```
<html>
<head>
</head>
<body>
Text!
</body>
</html>
```

[pagebreak.zip](https://github.com/koreader/koreader/files/294602/pagebreak.zip)

**Comment by frankyifei** [comment] 2016-06-02 13:23
I guess you can edit epub.css, and change line 67 to this `div { display: block }`
for better format on some epubs I changed this and add 1px margin for every `<div>`, usually it will not cause problem. But here it adds 1 px to the bottom of the first page and the image in first page has already filled first page,so second page only contains 1px of bottom_margin from first page.

**Comment by bbgordon** [comment] 2016-06-02 23:51
Sorry, I mentioned the wrong issue in that pull request!

**Comment by poire-z** [comment] 2018-07-08 07:56
I think we can close this, because:
- I reverted the `div {margin: 1px}` mentionned at https://github.com/koreader/koreader/issues/2047#issuecomment-223289773 in https://github.com/koreader/crengine/pull/201 (details in https://github.com/koreader/koreader/pull/3992#issuecomment-394071949) which was indeed the culprit for some additional page break - hadn't seen that comment before, I hope I haven't break anything with that. @frankyifei ?
- some unwanted (it really depends on the book) page-break can now be avoided with one available Style tweak

**Closed by poire-z** 2018-07-08 07:56 UTC
Labels: bug, crengine
