### ISSUE TITLE
koreader crash when reading some webpage generated pdfs

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#5883] opened 2020-02-19 11:03 UTC
* KOReader version: v2020.02
* Device: Kobo Clara HD

#### Issue
I generated some pdfs from some webpage and read it in koreader. It often crashes with a bomb screen. Maybe 20 pdf files will have 1 pdf that will cause koreader to crash every time. 

#### Steps to reproduce
1. Open a webpage generated pdf
2. If you are unlucky, then the koreader will crash with a screen displaying a bomb and many other logs
3. I uploaded 1 pdf that will cause koreader to crash everytime. It has 6 pages, when you turn to page 5 or 6, it will crash.

[crash.log](https://github.com/koreader/koreader/files/4224660/crash.log)
[Breaking down programmatic, Episode 1 Demystifying the DSP (Part II) - MoPub Blog.pdf](https://github.com/koreader/koreader/files/4224663/Breaking.down.programmatic.Episode.1.Demystifying.the.DSP.Part.II.-.MoPub.Blog.pdf)

**Comment by Frenzie** [comment] 2020-02-19 11:36
From the crash.log:

```
warning: ... repeated 3 times ...
error: malloc of array (19209 x 26192 bytes) failed
./luajit: ./ffi/mupdf.lua:67: could not allocate pixmap: malloc of array (19209 x 26192 bytes) failed (1)
stack traceback:
	[C]: in function 'error'
	./ffi/mupdf.lua:67: in function 'merror'
	./ffi/mupdf.lua:895: in function 'render_for_kopt'
	./ffi/mupdf.lua:944: in function 'getPagePix'
	frontend/document/koptinterface.lua:358: in function 'renderOptimizedPage'
	frontend/document/koptinterface.lua:387: in function 'hintPage'
	frontend/apps/reader/modules/readerhinting.lua:11: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/apps/reader/modules/readerview.lua:86: in function 'action'
	frontend/ui/uimanager.lua:812: in function '_checkTasks'
	frontend/ui/uimanager.lua:1095: in function 'handleInput'
	frontend/ui/uimanager.lua:1181: in function 'run'
	./reader.lua:279: in main chunk
	[C]: at 0x000140c1
!!!!
```

I can't reproduce the issue on my H2O. Memory use is quite mild, so it seems unlikely that you'd be out of memory. Do you have any special settings enabled?

**Comment by poire-z** [comment] 2020-02-19 12:03
I once met that kind of crash, and fixed my case with https://github.com/koreader/koreader/commit/76f6b49731e3541b3e605dac96e659ed25b33e11.
So, may be this happens in some other conditions, and it would need another fix like this one in some other code path.
(But I'm not friend with koptinterface.lua :)

**Comment by NiLuJe** [comment] 2020-02-19 16:21
IIRC, there's a MuPDF bug where some dust-like tiny elements might get assigned a gigantic rectangle or something weird as hell like that that (that, I, err, might not recall entirely right :D) @baskerville had to workaround in Plato and/or its MuPDF build.

**Comment by NiLuJe** [comment] 2020-02-19 16:22
Or, I'm misremembering what @poire-z just quoted, which sounds eerily familiar :D. Yay, brain.

**Comment by NiLuJe** [comment] 2020-02-19 16:23
@Frenzie: 19209x26192 is more than enough to murder a 512MB device ;).

**Comment by baskerville** [comment] 2020-02-19 17:02
[This](https://www.mobileread.com/forums/showpost.php?p=3817613&postcount=390) might be relevant.

**Comment by Frenzie** [comment] 2020-02-19 18:26
@NiLuJe You're right of course, I was talking about my attempts to repro. For me it looks like nothing but a very undemanding PDF.

@baskerville Thanks, I'd already checked that however, since something like that was my first thought. :-)

```
pdfimages -list Breaking.down.programmatic.Episode.1.Demystifying.the.DSP.Part.II.-.MoPub.Blog.pdf 
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image       1     2  icc     3   8  image  yes       13  0    72    72   11B 183%
   1     1 smask       1     2  gray    1   8  image  yes       13  0    72    72   10B 500%
   1     2 image     144  4886  icc     3   8  image  yes       18  0    72    72  114K 5.5%
   1     3 smask     144  4886  gray    1   8  image  yes       18  0    72    72 66.6K 9.7%
   4     4 image     500   300  icc     3   8  image  yes       60  0    72    72  310K  70%
   5     5 image     500   300  icc     3   8  image  yes       70  0    72    72  343K  78%
```

**Comment by kingo132** [comment] 2020-02-20 08:15
> From the crash.log:
> 
> ```
> warning: ... repeated 3 times ...
> error: malloc of array (19209 x 26192 bytes) failed
> ./luajit: ./ffi/mupdf.lua:67: could not allocate pixmap: malloc of array (19209 x 26192 bytes) failed (1)
> stack traceback:
> 	[C]: in function 'error'
> 	./ffi/mupdf.lua:67: in function 'merror'
> 	./ffi/mupdf.lua:895: in function 'render_for_kopt'
> 	./ffi/mupdf.lua:944: in function 'getPagePix'
> 	frontend/document/koptinterface.lua:358: in function 'renderOptimizedPage'
> 	frontend/document/koptinterface.lua:387: in function 'hintPage'
> 	frontend/apps/reader/modules/readerhinting.lua:11: in function 'handleEvent'
> 	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
> 	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
> 	frontend/apps/reader/modules/readerview.lua:86: in function 'action'
> 	frontend/ui/uimanager.lua:812: in function '_checkTasks'
> 	frontend/ui/uimanager.lua:1095: in function 'handleInput'
> 	frontend/ui/uimanager.lua:1181: in function 'run'
> 	./reader.lua:279: in main chunk
> 	[C]: at 0x000140c1
> !!!!
> ```
> 
> I can't reproduce the issue on my H2O. Memory use is quite mild, so it seems unlikely that you'd be out of memory. Do you have any special settings enabled?

I tried again today after I clear the koreader cache. The crash is gone and I can't reproduce it. No matter how I adjust any option, the crash can not be reproduced.

**Comment by Frenzie** [comment] 2020-02-20 11:33
That's unfortunate. I'll close this then, but please add more info or open a new ticket if it should occur again.

**Closed by Frenzie** 2020-02-20 11:33 UTC
Labels: bug, need more info

**Comment by poire-z** [comment] 2020-02-20 13:03
I still think we should handle this gracefully, whether it's some extra large image/dpi inside the PDF (not the case here), or whether it's some bug (or expected behaviour of our code cropping to a small area and enlarging it), and avoid getting into this:
```
error: malloc of array (19209 x 26192 bytes) failed
./luajit: ./ffi/mupdf.lua:67: could not allocate pixmap: malloc of array (19209 x 26192 bytes) failed (1)
```
whether by avoiding it initially, or using pcall() and falling back to some other behaviour.

It'd be nice to have some newcomer willing to become friend with kopt & mudpf :)

**Comment by Frenzie** [comment] 2020-02-20 13:07
@poire-z Of course, but I have no idea what "this case" even is. Unless you're just talking about the hypothetical case of the highest DPI image ever.

**Comment by poire-z** [comment] 2020-02-20 13:48
Yes, we have no idea what "this case" is, but we know there is "a case" :)
(So, not just talking about that hypothetical case.)
Some wrap with pcall, and if error, a dump of the current setting/page size/screen size (everything we know) could help that newcomer figuring future issues out :)
