### ISSUE TITLE
Frontlight control not working

### ISSUE THREAD

**Issue by arkadywtf** [koreader/koreader#6115] opened 2020-05-03 19:16 UTC
* KOReader version: 2020.04.1
* Device: Inkbook PrimeHD; 2.3.0

#### Issue
I can not control brightness levels of the device within the app.
What is also interesting is that when the "Use system settings" is checked, the app seems to detect the brightness levels of the device correctly.

#### Steps to reproduce
Menu-> Frontlight -> adjust all from 0 to 100, and vice versa. Nothing happens.

**Comment by pazos** [comment] 2020-05-03 20:03
duplicate of #5364

**Closed by pazos** 2020-05-03 20:03 UTC
Labels: Android, duplicate, firmware
