### ISSUE TITLE
View mode: continous - pan moves lines much too fast

### ISSUE THREAD

**Issue by francwalter** [koreader/koreader#7413] opened 2021-03-15 08:07 UTC
* KOReader version: 2021.02
* Device: Xiaomi Mi A1 with Android 9

#### Issue

I just installed KOReader some days ago and I am experimenting and comparing it to other readers, especially to Moon+ Reader (Android) which is my actual favorite reader since long.
One of my most important features is the continous scrolling (not only page by page).
In KOReader this is the bottom menu (or setting) View mode: continous.

But the scrolling ist not at all useable on my device, it scrolls big parts and not only line by line, when I swipe down or up. 
The lines should be moved exactly as I move my finger but there is some acceleration with it so that I cannot swipe line by line at all. 
If I swipe up (or down) only a line (I use Font size 30) the text scrolls with speed up (or down), not at all keeping position of my finger.
I didn't find any fine adjusting for this scrolling, I would expect, that the swipe move would be exactly 1:1 in its movement and not 1:10 or more, no acceleration at all. 
Maybe my display has too high resolution (1080x1920)? I have to set Zoom (dpi) to 300 to show images in the right size. With Zoom (dpi): off they show in about a third of their real size.

I don't know if this is by intention, I couldnt believe it, so I guess it is a bug in this special environment (KOReader 2021.02 for Android on Android 9 at least).

Would be great if that feature were useable :)
Thanks!

frank

**Comment by Frenzie** [comment] 2021-03-16 11:24
Cf. https://www.mobileread.com/forums/showthread.php?t=337727

@poire-z What did you say the rationale was?

**Comment by poire-z** [comment] 2021-03-16 11:49
I don't know about any rationale about that, or if there wasn't any - I think it's an oversight with gestures start/duration/continuation.
But I just think the current behaviour, which might then not be voluntary, is quite nice - wrote about that at https://github.com/koreader/koreader/pull/4666#issuecomment-788978486

**Comment by francwalter** [comment] 2021-03-16 14:16
Ah, I am not the only one with that issue, that is a relief 😏 

No, if this is not a bug but a feature, than it is a feature that is very different from the feature I expect to have with continous view.
It might be nice to fast scroll through the whole book, but this is surely not for reading purpose. The movement is so fast, that it is impossible to get any clue of the passing text.

I want to use contionous view mode so that I have the line where I want to continue reading on the top. OK, I could use a bookmark but moving the text is faster (if it worked). I expect the behaviour of a swipe as in any scrollable text document on Android, where never I have any acceleration.

So if any developer could change the default behaviour to normal line moving (without any acceleration) and maybe keep the actual behaviour as a setting (e.g. "View Mode continuous: [  ] with acceleration"), this would be great!
Thanks.

**Comment by francwalter** [comment] 2021-04-30 09:58
No change here 😢 
I went back to Moon+ after a while testing KOReader, the main reason was this "bug" or UX-misunderstanding.
Anyway, after all it is a great reader (just not exactly for my needs).

**Comment by poire-z** [comment] 2021-04-30 10:47
(I wouldn't tag it at "wontfix", it just needs someone courageous to look at the panning code :)

**Comment by Frenzie** [comment] 2021-04-30 10:48
We could rename wontfix to "PRs welcome" rather than just having it on hover I suppose.

**Comment by Frenzie** [comment] 2021-04-30 10:50
Put another way, it doesn't mean "won't accept fix."

**Comment by poire-z** [comment] 2021-04-30 10:55
I get it :)
(And how I don't like some of you saying "PRs welcome" when it means "no interest working on that huge/tedious task" - because the day a PR comes by a newcomer on this tedious task, it will probably be a tedious rewiew/suggestion/rewrite task for us :)

I'd probably tag it as "high-hanging-fruit" (or "courageous-niluje-will-fix" :)

**Comment by poire-z** [comment] 2021-04-30 11:39
Something like this looks like the obvious way to get the expected behaviour:
```diff
--- a/frontend/apps/reader/modules/readerrolling.lua
+++ b/frontend/apps/reader/modules/readerrolling.lua
@@ -383,4 +383,12 @@ function ReaderRolling:setupTouchZones()
             handler = function(ges) return self:onPan(nil, ges) end,
         },
+        {
+            id = "rolling_pan_release",
+            ges = "pan_release",
+            screen_zone = {
+                ratio_x = 0, ratio_y = 0, ratio_w = 1, ratio_h = 1,
+            },
+            handler = function(ges) return self:onPanRelease(nil, ges) end,
+        },
     })
 end
@@ -547,4 +555,13 @@ function ReaderRolling:onPan(_, ges)
             distance_type = "distance_delayed"
         end
+        if ges.direction == "north" or ges.direction == "south" then
+            local pos_y = ges.pos.y
+            if self.prev_pos_y then
+                local dy = ges.pos.y - self.prev_pos_y
+                self:_gotoPos(self.current_pos - dy)
+            end
+            self.prev_pos_y = pos_y
+        end
+        --[[
         if ges.direction == "north" then
             self:_gotoPos(self.current_pos + ges[distance_type])
@@ -552,4 +569,5 @@ function ReaderRolling:onPan(_, ges)
             self:_gotoPos(self.current_pos - ges[distance_type])
         end
+        ]]--
     --this is only use when mouse wheel is used
     elseif ges.mousewheel_direction and self.view.view_mode == "page" then
@@ -559,4 +577,8 @@ function ReaderRolling:onPan(_, ges)
 end

+function ReaderRolling:onPanRelease(_, ges)
+    self.prev_pos_y = nil
+end
+
 function ReaderRolling:onPosUpdate(new_pos)
     self.current_pos = new_pos
```
Some (possibly minor) issues remain:
- initial distance (I guess to trigger pan) is ignored, so what you move is a bit off from your initial finger press
- doing it too quickly just put it back to initial scroll position - this is an issue that has been there for ages, not sure what's really happening there

**Comment by Frenzie** [comment] 2021-04-30 11:42
> doing it too quickly just put it back to initial scroll position - this is an issue that has been there for ages, not sure what's really happening there

Yes, that one's kind of annoying on Android. I don't really notice it on my H2O. Assuming it's the same as in paged media anyway.

**Comment by NiLuJe** [comment] 2021-04-30 12:55
> > doing it too quickly just put it back to initial scroll position - this is an issue that has been there for ages, not sure what's really happening there
> 
> Yes, that one's kind of annoying on Android. I don't really notice it on my H2O. Assuming it's the same as in paged media anyway.

c.f., https://github.com/koreader/koreader/issues/7487 ;).

**Comment by poire-z** [comment] 2021-04-30 14:12
This seems to solve the 2 above issues:
```diff
--- a/frontend/apps/reader/modules/readerrolling.lua
+++ b/frontend/apps/reader/modules/readerrolling.lua
@@ -384,2 +384,10 @@ function ReaderRolling:setupTouchZones()
         },
+        {
+            id = "rolling_pan_release",
+            ges = "pan_release",
+            screen_zone = {
+                ratio_x = 0, ratio_y = 0, ratio_w = 1, ratio_h = 1,
+            },
+            handler = function(ges) return self:onPanRelease(nil, ges) end,
+        },
     })
@@ -517,2 +525,9 @@ end
 function ReaderRolling:onSwipe(_, ges)
+    self.pan_prev_pos_y = nil
+    if self.pan_did_pan then
+        self.pan_did_pan = nil
+        -- We did some panning in a short amount of time, making
+        -- this pan detected as swipe: ignore this swipe.
+        return true
+    end
     local direction = BD.flipDirectionIfMirroredUILayout(ges.direction)
@@ -548,2 +563,19 @@ function ReaderRolling:onPan(_, ges)
         end
+        if ges.direction == "north" or ges.direction == "south" then
+            local pos_y = ges.pos.y
+            if self.pan_prev_pos_y then
+                local dy = ges.pos.y - self.pan_prev_pos_y
+                self:_gotoPos(self.current_pos - dy)
+                self.pan_prev_pos_y = pos_y
+                self.pan_did_pan = true
+            else
+                local initial_dy = Device.input.gesture_detector.PAN_THRESHOLD
+                if ges.direction == "south" then
+                    initial_dy = -initial_dy
+                end
+                self.pan_prev_pos_y = pos_y + initial_dy
+                self.pan_did_pan = false
+            end
+        end
+        --[[
         if ges.direction == "north" then
@@ -553,2 +585,3 @@ function ReaderRolling:onPan(_, ges)
         end
+        ]]--
     --this is only use when mouse wheel is used
@@ -560,2 +593,6 @@ end

+function ReaderRolling:onPanRelease(_, ges)
+    self.pan_prev_pos_y = nil
+end
+
 function ReaderRolling:onPosUpdate(new_pos)
```
Swipe (a short pan) doing panning works on Android because "smaller pan rate" is unchecked, so we get the first pan event, and more pan events. The above would ignore the swipe after 2 pan events.
On eInk, with "smaller pan rate" checked, we get only the first pan event: not enough to trigger a pan, so it will work as a swipe.
(Opening top & bottom menu with vertical swipes still works, as higher priority.)

This then becomes a bit related to #7595 : it would then be best to just kill any handling of vertical swipe, even in page mode, to avoid having some inconsistency depending on "smaller pan rate" and page|continuous mode. It would just do something when [x]smaller pan rate and continuous mode.

It's still a bit frustrating on Android that there is no acceleration or inertial effect, and you just scroll by the distance you moved your fingers: it takes a long time scrolling multiple pages :)

**Comment by NiLuJe** [comment] 2021-04-30 14:24
I seem to remember being able to reproduce the weird rubberbanding effect on a H2O, FWIW.

**Comment by NiLuJe** [comment] 2021-04-30 14:27
e.g., a long swipe from bottom to top nets me a `pan north` -> |swipe north` which effectively makes the page move and then move back ;p.

**Comment by poire-z** [comment] 2021-04-30 14:31
Yep, I was describing the behaviour with my patch above.
With current master, yes, the first pan would do some panning, and the next swipe would somehow reset it (for some reason I don't intuitively see, but don't wish to investigate :)

**Comment by poire-z** [comment] 2021-04-30 14:39
> I sometimes get an extra refresh, though ;).

Might be the full refresh every N page turns, when N small pos_y changes have been done ?

> It's still a bit frustrating on Android that there is no acceleration or inertial effect, and you just scroll by the distance you moved your fingers: it takes a long time scrolling multiple pages :)

Fun project for the mathematicaly inclined:
in the above, depending on the last or few last `dy` and/or time between them, compute some velocity/acceleration and scheduleIn() a few more `self:_gotoPos()` (like @NiLuJe did for frontlight off<>on progressively increasing/decresing levels on suspend/resume).

**Comment by NiLuJe** [comment] 2021-04-30 14:39
Short swipes are still weird, sometimes I get a relative pan in the *wrong* direction.

**Comment by poire-z** [comment] 2021-05-01 17:31
> Fun project for the mathematicaly inclined:

Had a bit of inertial fun, not much maths, but much koreader scheduling tricks. Still buggy with ugly attempts not fully working to solve some bugs, but works quite smoothly on Android (somehow, can't make it work on my emulator...):
```diff
--- a/frontend/apps/reader/modules/readerrolling.lua
+++ b/frontend/apps/reader/modules/readerrolling.lua
@@ -352,2 +352,3 @@ function ReaderRolling:setupTouchZones()
             handler = function()
+                if self:_cancelInertialScroll() then return end
                 if G_reader_settings:nilOrFalse("page_turns_disable_tap") then
@@ -362,2 +363,3 @@ function ReaderRolling:setupTouchZones()
             handler = function()
+                if self:_cancelInertialScroll() then return end
                 if G_reader_settings:nilOrFalse("page_turns_disable_tap") then
@@ -384,2 +386,10 @@ function ReaderRolling:setupTouchZones()
         },
+        {
+            id = "rolling_pan_release",
+            ges = "pan_release",
+            screen_zone = {
+                ratio_x = 0, ratio_y = 0, ratio_w = 1, ratio_h = 1,
+            },
+            handler = function(ges) return self:onPanRelease(nil, ges) end,
+        },
     })
@@ -517,2 +527,10 @@ end
 function ReaderRolling:onSwipe(_, ges)
+    self._pan_prev_pos_y = nil
+    if self._pan_has_scrolled then
+        self._pan_has_scrolled = nil
+        self:_scheduleInertialScroll()
+        -- We did some panning in a short amount of time, making
+        -- this pan detected as swipe: ignore this swipe.
+        return true
+    end
     local direction = BD.flipDirectionIfMirroredUILayout(ges.direction)
@@ -542,4 +560,90 @@ end

+function ReaderRolling:_scheduleInertialScroll()
+    if not self._inertial_scroll_action then
+        self.SCROLL_FRICTION = 0.2
+        self._inertial_scroll_action = function()
+            if self._pan_velocity then
+                if self._pan_scheduled_next_tick then
+                    self._pan_scheduled_next_tick = false
+                    UIManager:scheduleIn(self._pan_inertial_delay, self._inertial_scroll_action)
+                    return
+                end
+                self._pan_velocity = self._pan_velocity * math.pow(self.SCROLL_FRICTION, self._pan_inertial_delay)
+                local dist = math.floor(self._pan_velocity * self._pan_inertial_delay)
+                local did_scroll = self:_gotoPos(self.current_pos - dist)
+                self._pan_iterations = self._pan_iterations + 1
+                self._pan_scrolled_dist = self._pan_scrolled_dist + dist
+                if did_scroll and (dist >= 2 or dist <= -2) then
+                    UIManager.refresh_count = 0 -- avoid partial to full promotion
+                    self._pan_scheduled_next_tick = true
+                    UIManager:nextTick(self._inertial_scroll_action)
+                    return
+                end
+                UIManager:show(Notification:new{
+                    text = T("%1 iterations, %2 px scrolled", self._pan_iterations, self._pan_scrolled_dist),
+                })
+                self._pan_last_dy = nil
+                self._pan_velocity = nil
+                return
+            end
+            if self._pan_last_dy then
+                local delay = UIManager:getTime() - self._pan_last_tv
+                if delay:tonumber() > 0.3 then
+                    return -- static long enough before finger up
+                end
+                delay = self._pan_last_dt:tousecs()
+                if delay <= 1 then
+                    delay = 1
+                end
+                self._pan_velocity = self._pan_last_dy * 1000000 / delay
+                self._pan_inertial_delay = 0.02
+                self._pan_last_dy = nil
+                self._pan_iterations = 0
+                self._pan_scrolled_dist = 0
+                self._pan_scheduled_next_tick = false
+                UIManager:scheduleIn(self._pan_inertial_delay, self._inertial_scroll_action)
+            end
+        end
+    end
+    self._inertial_scroll_action()
+end
+
+function ReaderRolling:_cancelInertialScroll()
+    self._pan_last_dy = nil
+    self._pan_velocity = nil
+    if self._inertial_scroll_action then
+        return UIManager:unschedule(self._inertial_scroll_action)
+    end
+end
+
 function ReaderRolling:onPan(_, ges)
     if self.view.view_mode == "scroll" then
+        if ges.direction == "north" or ges.direction == "south" then
+            local pos_y = ges.pos.y
+            if self._pan_prev_pos_y then
+                if self.ui.gesture and self.ui.gesture.multiswipes_enabled and ges.distance_delayed == 0 then
+                    -- pan event before pan interval threshold: don't process it
+                    return true
+                end
+                local dy = pos_y - self._pan_prev_pos_y
+                self:_gotoPos(self.current_pos - dy)
+                UIManager.refresh_count = 0
+                self._pan_prev_pos_y = pos_y
+                self._pan_last_dy = dy
+                self._pan_last_dt = UIManager:getTime() - self._pan_last_tv
+                self._pan_last_tv = UIManager:getTime()
+                self._pan_has_scrolled = true
+            else
+                self:_cancelInertialScroll()
+                local initial_dy = Device.input.gesture_detector.PAN_THRESHOLD
+                if ges.direction == "south" then
+                    initial_dy = -initial_dy
+                end
+                self._pan_prev_pos_y = pos_y + initial_dy
+                self._pan_last_dy = nil
+                self._pan_last_tv = UIManager:getTime()
+                self._pan_has_scrolled = false
+            end
+        end
+        --[[
         local distance_type = "distance"
@@ -553,3 +657,4 @@ function ReaderRolling:onPan(_, ges)
         end
-    --this is only use when mouse wheel is used
+        ]]--
+    -- This is only use when mouse wheel is used
     elseif ges.mousewheel_direction and self.view.view_mode == "page" then
@@ -560,2 +665,7 @@ end

+function ReaderRolling:onPanRelease(_, ges)
+    self._pan_prev_pos_y = nil
+    self:_scheduleInertialScroll()
+end
+
 function ReaderRolling:onPosUpdate(new_pos)
@@ -947,3 +1057,3 @@ end
 function ReaderRolling:_gotoPos(new_pos, do_dim_area)
-    if new_pos == self.current_pos then return end
+    if new_pos == self.current_pos then return false end
     if new_pos < 0 then new_pos = 0 end
@@ -953,2 +1063,3 @@ function ReaderRolling:_gotoPos(new_pos, do_dim_area)
     if new_pos > max_pos then new_pos = max_pos end
+    if new_pos == self.current_pos then return false end
     -- adjust dim_area according to new_pos
@@ -979,2 +1090,3 @@ function ReaderRolling:_gotoPos(new_pos, do_dim_area)
     self.ui:handleEvent(Event:new("PosUpdate", new_pos, self.ui.document:getCurrentPage()))
+    return true
 end
```

The alternating nextTick/shecduleIn is to be able to get some event processed in between, so we can interrupt it, but that would work with the handler in there where I can can cancelInertialScroll. If I tap on the top or bottom, the menu appears but the reader keeps scrolling behind :)

@NiLuJe : how would you go (looking at `UIManager:handleInput()`) to be able to get my `self._inertial_scroll_action` cancelled on ANY event (`if input_events then`) so we don't have to handle it specifically.
I had various thoughts:
- give another param to scheduleIn() to say if it should be cancelled by an event - but many places to update as the later argument are actions arguments... so no go
- have an incremented event counter in UIManager, so that the action itself can handle all that (abort if this counter has changed since start). Thoughts?
- other idea ?

**Comment by NiLuJe** [comment] 2021-05-01 18:34
Possibly by moving the logic to GestureDetector and simply generating a completely different Gesture?

**Comment by NiLuJe** [comment] 2021-05-01 18:38
Otherwise I can possibly see that working by moving onyl bits of it to GestureDetector, registering the task in a new method that stores a reference to it in a table, a table that is cleared (and the task unscheduled) on clearState; as GestureDetector should already be clearing state on all meaningful events.

**Comment by poire-z** [comment] 2021-05-01 19:30
> Possibly by moving the logic to GestureDetector and simply generating a completely different Gesture?

That would be a tad more ambitious that what I had in mind :) Don't want to touch too much stuff for this little scrolling effect not many people would use.

> moving only bits of it to GestureDetector: registering the task via a new GestureDetector method that stores a reference to it in a table, a table that is cleared (and the task unscheduled) 

Feels simpler and safer. But I dunno if GestureDetector would be sufficient, I'd also like it to stop on button presses (paging buttons, or even the poweroff button going into suspend, to avoid having to plug stuff in onSuspend).
Initially thought about just handling "touch", as all gestures should start with a "touch" (that I guess we don't handle anywhere except in MovableContainer, so it must already be handled and send) - but thought it might better be even more generic (scroll would stop on usb plug :) but I don't mind - any other environmental events on some devices ? nothing like luminosity change triggering an event ?)

**Comment by NiLuJe** [comment] 2021-05-01 22:10
The only stuff that doesn't go through GestureDetector would be `KEY` events (buttons, power & cover included) and `MSC` (catch-all, usually gyro rotation, though).

**Comment by poire-z** [comment] 2021-05-06 06:52
Making some progress on this.

We'll have pan/scroll work normally on eInk & non-eInk, with restoring the original position if a pan has scrolled a bit and ended up being a top/bottom menu swipe, or a multiswipe (not a nice looking behaviour, but couldn't think of anything better).

We'll have "inertial scrolling" available on non-eInk devices, that do some more scrolling once you release your finger (with some friction to decrease it over time), unless you stopped moving for 0.3s before release.

I'd like to keep the old CRE scrolling behaviour as an option, but I need a name for it :) I would have called it "Continuous scrolling", but given that our "scroll" mode is itself called "continuous" (vs. "page") view, there would be some confusion.
Any idea for a name for this alternative scroll behaviour, when you scroll by the distance from your initial finger position at each step instead of just the distance from your finger at the previous step (so, you're controlling some kind of scroll speed with your finger) ? Like a up/down joystick controlling your car speed in a game. You can get the idea with an EPUB/FB2 in continuous mode on Android, it is the current behaviour.

**Comment by Frenzie** [comment] 2021-05-06 07:18
We have (roughly) the same behavior in skim mode btw.

**Comment by poire-z** [comment] 2021-05-06 14:45
https://github.com/koreader/koreader/blob/2c1cae64b61ba20abd9f7f5d6dac27abdadde35e/frontend/apps/reader/modules/readerview.lua#L615-L617

@NiLuJe : any real reason to keep doing "partial" (so full every 6 pans) when panning/scrolling? Can't we do ui/fast, and just a "partial" or "full" when done (I can now catch end of pan/scroll).

**Comment by NiLuJe** [comment] 2021-05-06 15:34
@poire-z: If you can do that, then that resolves that comment, so, yes please ;).

(Although, do experiment with it, there's a rather strong chance "fast" will look like crap in practice (IIRC, when I mangled stuff to test this back when that comment was written, that was with images, so it was especially terrible).)

**Comment by poire-z** [comment] 2021-05-06 15:44
> there's a rather strong chance "fast" will look like crap in practice 

Yes, it does, images are rather black&white when panning, which is fine for small images in wikipedia EPUBs - they would get nice back when done panning. Well, just a matter of switching it to "ui" if that looks too bad.

Any idea for a name for this alternative scroll behaviour described above ? Went with "Speedy scroll" until a better idea pops up.

**Comment by NiLuJe** [comment] 2021-05-06 15:45
inertial vs. constant scrolling?

**Comment by Frenzie** [comment] 2021-05-06 15:55
I believe the MacOS scrolling functionality is called accelerated scrolling.

**Comment by poire-z** [comment] 2021-05-06 17:36
It's not constant (rather, totally non-constant as you need to move to trigger a pan, so with a different distance than the one before).
Accelerated does not feel right, althought it's accelerated vs the other normal scrolling people expect.

Guess I'll go with `alt_scrolling` / `Alternative scrolling` :) until we find a better name. Could feel like a dance, one step forward, another one to go forward, one step backward to slow down... `Bossa-nova scrolling` :)

**Closed** 2021-05-19 21:55 UTC
Labels: UX, bug, help-wanted

**Comment by francwalter** [comment] 2021-05-20 08:51
Thanks a lot!
