### ISSUE TITLE
[Android] Status bar and bottom menu out of screen in vertical mode

### ISSUE THREAD

**Issue by Kiblyn11** [koreader/koreader#9557] opened 2022-09-23 13:50 UTC
* KOReader version: 2022.08
* Device: Pixel 6a

#### Issue

When reading a book in vertical mode the bottom menu is out of the screen and cannot be used.
Also the status bar is out of the screen as well.

### Screenshots

Vertical bottom overflow

![Screenshot_20220923-154428](https://user-images.githubusercontent.com/4669951/191975747-c5fc7600-fe93-40e7-9a46-3aa99027834e.png)

--

Horizontal OK

![Screenshot_20220923-154442](https://user-images.githubusercontent.com/4669951/191975259-d2fb1860-c746-4f0f-a8da-f952254e9db3.png)

**Comment by NiLuJe** [comment] 2022-09-23 17:44
Duplicate of #9446

**Closed by NiLuJe** 2022-09-23 17:44 UTC
