### ISSUE TITLE
KA1 Crashed with log

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#5469] opened 2019-10-11 01:55 UTC
KoboA1

<details>
 [*] Version: v2019.09.3-60-gb75fec4_2019-10-08

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: blitbuffer
FB: computed size: 5406720
FB: id           : mxc_epdc_fb
FB: smem_len     : 10813440
FB: line_length  : 1408
FB: xres         : 1404
FB: xres_virtual : 1408
FB: yres         : 1872
FB: yres_virtual : 3840
FB: bpp          : 8
10/10/19-21:43:07 INFO  initializing for device Kobo_daylight
10/10/19-21:43:07 INFO  framebuffer resolution: {
    ["h"] = 1872,
    ["w"] = 1404
}
[ko-input] Forked off fake event generator(pid:11700).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
10/10/19-21:43:07 INFO  opening file /mnt/onboard/.Books/--currently reading/Zorba the Greek - Nikos Kazantzakis.epub
10/10/19-21:43:07 ERROR failed to register crengine font: cannot register font <./fonts/Linux Biolinum for Kindle/Serif_Italic.ttf>
10/10/19-21:43:07 INFO  Loading plugins from directory: plugins
10/10/19-21:43:08 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
10/10/19-21:43:08 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
10/10/19-21:43:08 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
10/10/19-21:43:08 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
10/10/19-21:44:55 INFO  no dialog left to show
10/10/19-21:44:55 INFO  quitting uimanager
Restoring original fb bitdepth @ 16bpp & rotation @ 0
[FBInk] Detected a Kobo Aura One (373 => Daylight @ Mark 6)
Variable fb info: 1404x1872 (1408x3840), 8bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 1408 bytes

Switching fb to 16bpp @ rotation 0 . . .
Setting bitdepth to 16bpp
Setting grayscale to 0
Setting rotate to 0 (Upright, 0°)
Bitdepth is now 16bpp (grayscale: 0) @ rotate: 0 (Upright, 0°)

Variable fb info: 1872x1404 (1888x2816), 16bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 3776 bytes

</details>

**Comment by Frenzie** [comment] 2019-10-11 10:50
Could you be a bit more specific about what happened? I just see a clean exit.

```
10/10/19-21:44:55 INFO  no dialog left to show
10/10/19-21:44:55 INFO  quitting uimanager
```

**Comment by CalbertAmu** [comment] 2019-10-11 17:14
The kobo stopped when I tried to wake it up and then showed an ASCII bomb art which said it crashed, and to just tap to restart.

**Comment by NiLuJe** [comment] 2019-10-11 17:49
Did that actually correspond to the timestamp shown in the log excerpt you posted?

**Comment by CalbertAmu** [comment] 2019-10-12 03:49
![IMG_20191011_233805](https://user-images.githubusercontent.com/16507083/66694422-18a65100-ec81-11e9-90e1-28178aa8c440.jpg)

It happened three times now, and I took a picture of it.

**Comment by poire-z** [comment] 2019-10-12 14:17
Mhhh, just got the same crash, after I switched documents with a gesture (can't reproduce it):
```
10/12/19-16:07:35 INFO    opening took 1.805 seconds
./luajit: frontend/apps/reader/modules/readermenu.lua:189: attempt to index a nil value
stack traceback:
    frontend/apps/reader/modules/readermenu.lua:189: in function 'setUpdateItemTable'
    frontend/apps/reader/modules/readermenu.lua:375: in function '_getTabIndexFromLocation'
    frontend/apps/reader/modules/readermenu.lua:414: in function 'handler'
    frontend/ui/widget/container/inputcontainer.lua:251: in function 'handleEvent'
    frontend/ui/uimanager.lua:732: in function 'sendEvent'
    frontend/ui/uimanager.lua:201: in function '__default__'
    frontend/ui/uimanager.lua:1082: in function 'handleInputEvent'
    frontend/ui/uimanager.lua:1145: in function 'handleInput'
    frontend/ui/uimanager.lua:1191: in function 'run'
    ./reader.lua:266: in main chunk
    [C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash nÂ°1: 10/12/19 @ 16:07:37)
Aborting . . .
!!!! ! !!!!
```
(my readermenu.lua is a bit patched, so my line numbers are a bit ++, but they correspond to what's on the above screenshot)
That's with today's nightly. I never had that crash with a nightly from last weekend - and I did switch quite a few documents over the week :)

> 10/10/19-21:43:07 ERROR failed to register crengine font: cannot register font <./fonts/Linux Biolinum for Kindle/Serif_Italic.ttf>
Could that be the problem?

Nope, everybody gets that kind of line - not an issue.

**Comment by Frenzie** [comment] 2019-10-12 14:20
So something wrong with #5460? (Last change to that file.)

**Comment by Frenzie** [comment] 2019-10-12 14:35
@poire-z Can't reproduce btw.

**Comment by poire-z** [comment] 2019-10-12 14:47
Yep, I still can't reproduce it. Might be some scheduleIn/nextTick'ed stuff that happens to run at the bad moment, may be when between documents and everything is not yet set up.

**Comment by Frenzie** [comment] 2019-10-12 16:12
@CalbertAmu (Hard to write correctly, my fingers go for Albert Camus, lol.) Does it work correctly if you add a #table_len > 0?

Like so:

```lua
        if #table_len > 0 and self.menu_items.screensaver.sub_item_table[table_len].text == ss_book_settings.text then
```

I'm not sure it should actually be possible for that to be 0 though… weird.

**Comment by CalbertAmu** [comment] 2019-10-12 19:07
Hi Frenzie, where do I add it?  To readermenu.lua ?

**Comment by Frenzie** [comment] 2019-10-12 19:10
That would be line 180 of readermenu.lua as per your screenshot.

But if that works then you should probably have no working screensaver menu… I'm a bit confused atm.

**Comment by CalbertAmu** [comment] 2019-10-12 19:41
I just added it and restarted. Koreader immediately crashes with that screen, but now has a different line 180 than before. I cannot exit koreader. It's like a bootloop, just restarts and crashes. I put it in sleep for now, and will try to restart the device.

**Comment by poire-z** [comment] 2019-10-12 20:05
Small typo, just remove the `#` before `table_len`:
```lua
        if table_len > 0 and self.menu_items.screensaver.sub_item_table[table_len].text == ss_book_settings.text then
```

(It might still crash if the previous line fails if `sub_item_table` does not exist, but I guess that's what we want to know:
`        local table_len = #self.menu_items.screensaver.sub_item_table`
)

**Comment by CalbertAmu** [comment] 2019-10-12 20:13
I added it. No crashes so far

**Comment by CalbertAmu** [comment] 2019-10-14 22:04
First crash since the addition to line 180
<Detail>
![IMG_20191014_175900](https://user-images.githubusercontent.com/16507083/66785994-e37e4680-eeac-11e9-8a01-5629bd6cb239.jpg)
</Detail>

**Comment by poire-z** [comment] 2019-10-15 07:03
(@CalbertAmu : you will find these stack trace in the crash.log file on your device - copying that text as text will be more readable than your photographs :)

Last one is unrelated to your previous issue (at least in its effect). Looks like it's processing a Swipe south to close bottom menu, while the bottom menu has not yet been painted - or is being updated.
Do you remember what you were doing when that crash happened? (don't hesistate to tell a bit more to give your crash.log a bit of context :)

**Comment by Frenzie** [comment] 2019-10-15 20:53
@CalbertAmu Any effect on your screensaver menu?

**Comment by CalbertAmu** [comment] 2019-10-16 03:37
@poire-z thanks, and sorry I don't remember what I was doing. Maybe turning a page, or trying to hide the bottom menu by swiping.

@Frenzie No issues going to the screensaver menu. I found that it always crashes on the third option 'Use random image from folder as screensaver' when I put the device to sleep twice/ or when trying to load the second random picture.

**Comment by CalbertAmu** [comment] 2019-10-16 03:42
I don't know which part would be relevant

[crash.log](https://github.com/koreader/koreader/files/3732342/crash.log)

**Comment by poire-z** [comment] 2019-10-16 05:25
The same bits that appears on that bomb screen are found at the end of your crash.log.
Copying them here for reference:
1st type of crash:
```
10/10/19-11:28:11 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/10/19-21:42:53 INFO  Kobo suspend: woke up!
10/10/19-21:42:53 INFO  Kobo resume: clean up after wakeup
10/10/19-21:42:53 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
./luajit: frontend/apps/reader/modules/readermenu.lua:180: attempt to index a nil value
stack traceback:
    frontend/apps/reader/modules/readermenu.lua:180: in function 'setUpdateItemTable'
    frontend/apps/reader/modules/readermenu.lua:365: in function '_getTabIndexFromLocation'
    frontend/apps/reader/modules/readermenu.lua:386: in function 'handler'
    frontend/ui/widget/container/inputcontainer.lua:251: in function 'handleEvent'
    frontend/ui/uimanager.lua:674: in function 'sendEvent'
    frontend/ui/uimanager.lua:174: in function '__default__'
    frontend/ui/uimanager.lua:1016: in function 'handleInputEvent'
    frontend/ui/uimanager.lua:1077: in function 'handleInput'
    frontend/ui/uimanager.lua:1121: in function 'run'
    ./reader.lua:260: in main chunk
    [C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash nÂ°1: 10/10/19 @ 21:42:55)
```

2nd type of crash:
```
10/14/19-18:01:19 INFO  Kobo suspend: woke up!
10/14/19-18:01:19 INFO  Kobo resume: clean up after wakeup
10/14/19-18:01:19 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
./luajit: frontend/ui/geometry.lua:198: attempt to index local 'rect_b' (a nil value)
stack traceback:
    frontend/ui/geometry.lua:198: in function 'notIntersectWith'
    frontend/ui/geometry.lua:213: in function 'intersectWith'
    frontend/ui/widget/configdialog.lua:1272: in function 'handleEvent'
    frontend/ui/widget/container/inputcontainer.lua:259: in function 'handleEvent'
    frontend/ui/uimanager.lua:704: in function 'sendEvent'
    frontend/ui/uimanager.lua:174: in function '__default__'
    frontend/ui/uimanager.lua:1016: in function 'handleInputEvent'
    frontend/ui/uimanager.lua:1077: in function 'handleInput'
    frontend/ui/uimanager.lua:1121: in function 'run'
    ./reader.lua:260: in main chunk
    [C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash nÂ°1: 10/14/19 @ 18:01:35)
```

3rd type of crash:
```
10/15/19-23:27:05 INFO  Kobo resume: clean up after wakeup
10/15/19-23:27:05 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
10/15/19-23:27:09 INFO  WakeupMgr: scheduling wakeup for: 259200 1571455629
ifconfig: SIOCSIFADDR: No such device
10/15/19-23:27:11 INFO  Kobo WiFi: disabling WiFi
ifconfig: SIOCGIFFLAGS: No such device
10/15/19-23:27:12 INFO  Kobo resume: clean up after wakeup
10/15/19-23:27:12 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
10/15/19-23:27:14 INFO  WakeupMgr: scheduling wakeup for: 259200 1571455634
error: unknown image file format
10/15/19-23:27:15 INFO  failed rendering image (mupdf): ./ffi/mupdf.lua:67: could not load image data: unknown image file format (2)
./luajit: frontend/ui/widget/imagewidget.lua:224: attempt to index field '_bb' (a nil value)
stack traceback:
    frontend/ui/widget/imagewidget.lua:224: in function '_render'
    frontend/ui/widget/imagewidget.lua:294: in function 'getSize'
    frontend/ui/widget/container/framecontainer.lua:44: in function 'getSize'
    frontend/ui/widget/container/inputcontainer.lua:76: in function 'paintTo'
    frontend/ui/uimanager.lua:933: in function '_repaint'
    frontend/ui/uimanager.lua:1049: in function 'handleInput'
    frontend/ui/uimanager.lua:1121: in function 'run'
    ./reader.lua:260: in main chunk
    [C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash nÂ°1: 10/15/19 @ 23:27:16)
```

Are all your screensaver images valid ?

**Comment by CalbertAmu** [comment] 2019-10-16 06:36
I tried to check. I kept one image only in the folder. When using "use image as a screensaver" there is no issue. Crash only happens when using "use random image.." So I don't think images were invalid. They are all PNGs, and most screenshots

**Comment by poire-z** [comment] 2019-10-17 13:16
@CalbertAmu : your first crash should be fixed by #5499 - my investigation in https://github.com/koreader/koreader/pull/5460#issuecomment-543139751.
Could it be that you you too are switching a lot between documents? If yes, how do you usually do switch documents? Via the menu or via some gesture?
Anyway, should be fixed in tomorrow's nightly.

Dunno about your 2nd crash - but there's a small chance your 3rd crash, as it's screensaver related, might also be fixed.
If you use nightlies, can you report?

(Closing this issue to clear the milestone, re-open if you see again those other crashes, with a nightly from tomorrow or later, or with next stable.)

**Closed by poire-z** 2019-10-17 13:16 UTC
Labels: Kobo, bug, need more info

**Comment by CalbertAmu** [comment] 2019-10-17 14:46
Yes I am using gesture to switch between two documents. I switch often between two translations to compare them. 

I use nightlies. Thank you, I will report

**Comment by poire-z** [comment] 2019-10-18 07:20
> Also I noticed the number of items in the screensaver menu got reduced to 3

I guess that's *not* with the nightly that just came out 1/2 hour ago.
But no, it's not intentional: https://github.com/koreader/koreader/pull/5460#issuecomment-543139751: *I notice that when using a gesture to switch document, the Screensaver menu shrinks by 1 item every 2 document switches.*

Should be fixed in current nightly.

**Comment by CalbertAmu** [comment] 2019-10-18 08:06
v2019.09.3-82

Updated just now. It crashes every time when putting to sleep with the screensaver menu selected as 'use random image..'

**Comment by poire-z** [comment] 2019-10-18 08:12
It doesn't for me.
Look at your crash.log, and see if it's again your 3rd crash - otherwise share the crash.log bit.
If it's your 3rd crash (`could not load image data: unknown image file format (2)`), try to let in your screensaver random image directory just 2 images you're sure they are ok. If that works, try to pinpoint if you have bad images - and share such a bad one.

**Comment by CalbertAmu** [comment] 2019-10-18 18:14
I think this is the one:

`error: unknown image file format`
`10/18/19-04:03:07 INFO  failed rendering image (mupdf): ./ffi/mupdf.lua:67: could not load image data: unknown image file format (2)`
`./luajit: frontend/ui/widget/imagewidget.lua:224: attempt to index field '_bb' (a nil value)`

[crash.log](https://github.com/koreader/koreader/files/3745073/crash.log)


When I try to locate the screensaver folder through the ss menu I cannot find it. I have enabled the option to show hidden files in the file browser, but that only seems to apply it there, and I cannot find the folder through 'Choose screensaver directory'. 

I thought maybe koreader didn't find the folder because the 'adds' folder within which koreader and its screenshot folder are located is hidden with " . " in front of the folder name. I just copied the ss folder to the main directory and assigned that as the screensaver folder. No crashes so far with the same images. So i think the hidden folder may have been the problem, as it couldn't find it.

**Comment by poire-z** [comment] 2019-10-18 18:41
Except for the display issue with hidden folder (might be a bug), a hidden folder/folder with a dot in the whole path should not cause any issue (I have [`"screensaver_dir"] = "/mnt/onboard/.adds/screensaver",`).
So, not sure what happens and why, but good it seems ok.
Oh, but did it happen at the time you suspend? Or later when you resume? (from the previous log, I thought it happened on resume).

If it starts to happen again, try to add the following line between lines 319 and 320, after `local image_file = getRandomImage(screensaver_dir) :`

`logger.warn("screensaver image file used:", image_file)`
https://github.com/koreader/koreader/blob/7caa21a3fbb2b1cace7eee227f87650de9554a0e/frontend/ui/screensaver.lua#L311-L320

**Comment by CalbertAmu** [comment] 2019-10-18 18:49
I think it happened at suspend because it showed the crashscreen after I try to put it to sleep.

**Comment by melyux** [comment] 2022-06-11 23:13
> I tried to check. I kept one image only in the folder. When using "use image as a screensaver" there is no issue. Crash only happens when using "use random image.." So I don't think images were invalid. They are all PNGs, and most screenshots

I'm still getting this exact issue on the latest on Kobo Libra 2, same logs, same situation. Except it's a jpeg. Displays perfectly as a thumbnail when choosing a specific image, and works perfectly as well. Only when doing "random" (with it being the only image in the folder) does it crash in the exact same manner.

It's this image:
![image](https://user-images.githubusercontent.com/10296053/173207852-bb53df5a-54d6-49b4-abce-642b0d0e8d8d.jpeg)

**Comment by NiLuJe** [comment] 2022-06-12 01:18
Assuming y'all are on macOS, tomorrow's nightly might help (https://github.com/koreader/koreader/commit/299c34a49c3ad94c97f3b82787cd4876f682ffa1).

**Comment by melyux** [comment] 2022-06-12 02:11
Sexy! Thought it might be some hidden file. The crash log should ideally include the filename that caused it to crash for easier debugging probably

**Comment by melyux** [comment] 2022-06-16 18:35
Tried the nightly and confirm that it now works properly on this end, no crashing.
