### ISSUE TITLE
Screen cut in new phone with Miui 14 installed

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#10232] opened 2023-03-20 20:00 UTC
I recently got a new phone, a Xiaomi 12T Pro which was inmediatly updated to Miui 14

After installing KOReader it seems the screen is cut on the bottom:
![Screenshot_2023-03-20-22-56-38-490_org koreader launcher](https://user-images.githubusercontent.com/85340/226452094-79f7e615-e882-44c2-b475-5bc8a0f46c8e.jpg)

This does not happen in other devices with ColorOS or just Android. It is not a big deal since I barely read on the phone but I notify the problem.

Thanks

**Comment by NiLuJe** [comment] 2023-03-20 20:09
Duplicate of #9446

**Closed by NiLuJe** 2023-03-20 20:09 UTC
