### ISSUE TITLE
No apparent support for limited page refresh on boox nova air

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#8247] opened 2021-09-22 21:26 UTC
2021.09 release. (Android)

Boox nova air. 

Repro
On each page then  koreader performs a
Full page refresh

Desired behavior 
Limited or no full refreshs as it's very distracting when reading.

**Comment by pazos** [comment] 2021-09-22 22:44
Duplicate of #4551

Please post there if one of the available drivers works on your device.
Please follow instructions :)

**Closed by pazos** 2021-09-22 22:44 UTC
