### ISSUE TITLE
Dictionaries are not working anymore

### ISSUE THREAD

**Issue by gmadjara** [koreader/koreader#3612] opened 2018-01-17 05:53 UTC
* KOReader version : v2015.11-1457
* Device: KOBO H20 1st Gen

After update to the new nighty I cannot find working solution for dictionary result 'not showing'. All dictionaries are in the StarDict format with 3 files (.dz, .idx and .ifo).  Path> .adds/koreader/data/dict/

Under "Dictionary settings" -} "Installed dictionaries" dictionaries are listed correctly.

#### Steps to reproduce
When I try to find meaning for the word (long click), dictionary pop-up window is empty with "No definition found". 

Result is the same if you try to go through menu. "Dictionary lookup" } enter manually word } "No definition found". Seems like KOReader cannot read properly dictionary files anymore.

Thanks for any help which may lead to finding solution.

**Comment by Frenzie** [comment] 2018-01-17 08:21
Should be fxed in https://github.com/koreader/koreader/pull/3592

Could you perhaps perform an OTA update to verify?

**Comment by gmadjara** [comment] 2018-01-17 08:34
I did, update to the latest nighty build few minutes ago (OTA). The problem still persists. Not even single dictionary out of 10 currently available are showing results. It doesn't matter if its only 1 or 10 active, I've tried all combinations.

**Comment by Frenzie** [comment] 2018-01-17 11:18
Did you update your Kobo firmware? There's issue https://github.com/koreader/koreader/issues/3302. Kobo firmware 4.6.9960 and higher broke dictionary lookup, which is unrelated to any changes in KOReader itself.

I uploaded a working sdcv here: https://github.com/koreader/koreader/issues/3302#issuecomment-337700307

Unfortunately adjusting the nightly build toolchain is a lot more involved.

**Comment by gmadjara** [comment] 2018-01-17 12:48
Yes, I did update the Kobo FW recently. Anything I can do or modify to make it work again. Any easy solution. Thank you.

**Comment by Frenzie** [comment] 2018-01-17 14:28
Alright, closing as a duplicate of #3302. :-)

**Closed by Frenzie** 2018-01-17 14:28 UTC
Labels: bug, duplicate
