### ISSUE TITLE
FR: Respect Dark Mode during boot

### ISSUE THREAD

**Issue by ryanwwest** [koreader/koreader#11606] opened 2024-04-01 05:12 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
When opening KOReader on Android, it briefly shows a white screen with KOReader's icon in the center, then may show a completely blank white screen before the app is fully loaded. If the Android system is in dark mode, then you can set KOReader to dark mode as well, but this opening sequence can appear like a short burst of bright white light when reading at night which is uncomfortable. This might also happen occasionally when resuming from sleep.

**Describe the solution you'd like**
It would be nice to have the loading screen respect the app's chosen dark/light mode to avoid the short period of white screen.

**Additional context**
I imagine it might be difficult to look up the Lua night mode setting when the app is starting since the JIT compiler is probably in the process of being loaded, and there's a Java Shim used to set up the basics before it goes pure Lua. Maybe an alternative here could be look up the system's dark/light mode which Android, Mac, and some other OSs have, and use that as the loading screen background.

**Comment by pazos** [comment] 2024-04-01 17:31
Duplicate of #8868

**Closed by pazos** 2024-04-01 17:31 UTC
Labels: enhancement
