### ISSUE TITLE
New Android release?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2246] opened 2016-09-11 18:05 UTC
Hi

Can we please get a recent build for Android?

thanks

**Comment by KenMaltby** [comment] 2016-09-11 20:25
Have you tried the (Over The Air) OTA feature?

**Comment by houqp** [comment] 2016-09-11 21:20
OTA uses the same builds. @chrox should be able to help since he manages the build server.

**Comment by KenMaltby** [comment] 2016-09-11 22:12
The OTA sites show the latest as; 2015.11-594.
The Nightly Builds have the latest build as: 2015.11-587.

The nightly builds here do provide an .apk  which is easier to deal with, when downloading to your PC and "sideloading" the new version.  I assume that the Android version on the OTA sites are handled ok by the android version of KOReader.

**Comment by houqp** [comment] 2016-09-11 22:44
Interesting... I thought the nightly build upload was automated. Maybe it's not?

**Comment by KenMaltby** [comment] 2016-09-11 23:21
It appears to be for the OTA sites.  The .apk build/packaging may not be part of the automated building, in any case.

**Comment by gerroon** [comment] 2016-09-12 21:10
It does not work for me.

It syas there is a new build but then claims that there is an error asks me to delete to temporary files.

**Comment by gerroon** [comment] 2016-09-25 03:21
It would be nice to have  a new github release.


thnx

**Comment by houqp** [comment] 2016-09-28 05:43
I am working with @chrox to migrate the automated build script to the new server. I will keep you posted.

**Comment by houqp** [comment] 2016-09-30 07:48
I just got the build scripts from @chrox , will set it up during the weekend :)

**Comment by houqp** [comment] 2016-10-09 10:06
I figured it's probably not a good idea to build on our new server since it has limited CPU and disk space. So I am setting up automated build tasks in gitlab right now.

I did a test build with our new docker build image, can you give it a try? You need to rename the attached zip file to apk.

[koreader-android-arm-linux-androideabi-v2015.11-630-gc90f1f8.zip](https://github.com/koreader/koreader/files/518224/koreader-android-arm-linux-androideabi-v2015.11-630-gc90f1f8.zip)

**Comment by gerroon** [comment] 2016-10-09 17:50
@houqp

Thanx I will try it.

**Comment by houqp** [comment] 2016-10-09 22:43
I tweaked the build parameters a little bit now it has a higher pass rate in automated test platform, can you give the new build a try too?

[koreader-android-arm-linux-androideabi-v2015.11-631-9.9-gbb1be60.zip](https://github.com/koreader/koreader/files/518611/koreader-android-arm-linux-androideabi-v2015.11-631-9.9-gbb1be60.zip)

**Comment by gerroon** [comment] 2016-10-10 02:13
@houqp 
I will try. However it seems like I cant "upgrade" with these builds. Do they have different signatures? Why do not you name these packages differently so I can test them along the latest releases? 

I can uninstall and intall these but then I will have to reinstall with other releases. I think it will be easier if these test builds are named something like test.

**Comment by houqp** [comment] 2016-10-10 02:32
You can rename the package to any name as you want :) Could you tell me what's your "update" process? If I know what steps have been taken, I will able to reproduce on my side. AFAIK, there is no signatures involved in the build process.

The automated nightly build will be back in service in a week. I got most of the issues resolved today. And with the new docker images (https://github.com/koreader/virdevenv/tree/master/docker/ubuntu), anyone can produce the same build on their own machines with 3 commands :)

**Comment by gerroon** [comment] 2016-10-10 03:00
@houqp 

Well every package has to eb signed somehow on Android, if the signature changes Android refuses to install over when the package name is same.

I cant change the package name with the apk since I am not building it. Changing the file name is not the issue. I meant the actual package name /path that is used to install it on Android.

My update process, I just download the packages from github and install over manually.

**Comment by houqp** [comment] 2016-10-10 03:23
I meant how are you installing the app, did you use adb or just run the apk within android?

**Comment by houqp** [comment] 2016-10-10 03:30
Ha, I see. By default the build system builds a debug apk signed using debug key. I am not aware of release signing key. I will sync up with @chrox on that.

**Comment by KenMaltby** [comment] 2016-10-10 12:15
I never had any trouble installing KOReader .apks, that I had modified, by just signing them using "EasyApkDisassembler v1.3.2"

**Comment by gerroon** [comment] 2016-10-10 13:11
@houqp 
I just run the apk. 

I normally do not have any issue with installing the new releases with Koreader. However the releases you provided do not install over the previous Github releases.

**Comment by houqp** [comment] 2016-10-17 06:37
Quick update, the new nightly build system is working now. All future builds will be published on http://build.koreader.rocks/download/nightly

I will setup automation to upload new nightly builds into github and start setting up the new OTA server. I am still working with @chrox to figure out the apk signing issue.

**Comment by gerroon** [comment] 2016-10-18 02:37
@houqp 

thanks for the update

**Comment by houqp** [comment] 2016-10-25 08:56
I have confirmed with chrox that all previous builds were signed using debug key. Since that key will be expired in a year anyway, I created a new release key that will be used to sign all future android builds.

**Comment by Frenzie** [comment] 2016-11-20 11:44
I noticed there's been no release posted since August, so I uploaded the latest nightly (which in my testing seems quite decent and stable).

https://github.com/koreader/koreader/releases/tag/v2016.11.20-nightly

**Comment by Frenzie** [comment] 2017-04-01 16:10
The Android build automatically completes some of the time, which makes no sense (just build or fail already) but anyway, I'm closing this now. :-)

**Closed by Frenzie** 2017-04-01 16:10 UTC
Labels: Android
