### ISSUE TITLE
'Cannot open last file' critical bug (Android)

### ISSUE THREAD

**Issue by Neko-Kunshu** [koreader/koreader#9898] opened 2022-12-11 10:27 UTC
* KOReader version: v2022.11 (F-Droid)
* Device: Samsung Galaxy M51 SM-M515F/DSN (One UI 4.1, Android 12)

#### Issue
If 'Start with: last file' option is set and the book last used is deleted via means other than 
built-in KOReader file manager the app will display the 'Cannot open last file. This could be because it was deleted or because external storage is still being mounted. Do you want to retry?' dialogue window. If then 'OK' is chosen, nothing happens, but if 'Cancel' is chosen, then KOReader goes back to built-in file manager and, after a second or so, the app crashes. It then continuously repeats this behavior on app launch, until app is reinstalled.

#### Steps to reproduce
1. Set 'Start with:' option in KOReader built-in file manager to 'last file';
2. Open any EPUB file (behavior with other file types not tested, but is expected to be the same) and exit KOReader;
3. Use any means available to you OTHER than KOReader built-in file manager to delete both EPUB file chosen in step 1 and corresponding .sdr folder/file.
4. Open KOReader. 'Cannot open last file' dialogue window will be displayed. Select 'Cancel' - that's when unexpected behavior occurs.

**Comment by Frenzie** [comment] 2022-12-11 10:32
Duplicate of #9887.

**Comment by Neko-Kunshu** [comment] 2022-12-11 10:38
> Duplicate of #9887.

Should I delete the report then?

**Comment by Frenzie** [comment] 2022-12-11 13:45
I forgot to close it, but yes, it's not necessary to have two open. 

Anyway, thanks for the detailed report! This is exactly the way I like to see them (except for the duplicate part ;-) ).

**Closed** 2022-12-11 13:45 UTC
Labels: duplicate

**Comment by winstonma** [comment] 2023-02-20 02:22
Hi I just google this feature and went to this page. I tried to follow the step 1 in this page but I can't find the `Start with:` option inside koreader. Would you mind guiding me? This would be great. Thanks

**Comment by mergen3107** [comment] 2023-02-20 02:23
This setting is available only from File Manager’s Top menu (first tab)

**Comment by winstonma** [comment] 2023-02-20 02:28
Sorry could you tell me a bit more (screenshot would be helpful). I tried to enable this feature, google it and can't find a solution.

Currently everytime I open a file I need to flip to the 6th page of my book folder to open the file I want =(

**Comment by mergen3107** [comment] 2023-02-20 02:34
File Manager is where you select your books. Top menu: tap at the top part of that screen that says “KOReader”. Then go to menu’s first tab. The setting is there

**Comment by winstonma** [comment] 2023-02-20 02:36
😭 I just realize the `KOReader` in the file browser is a button. Dumb me

**Comment by mergen3107** [comment] 2023-02-20 02:56
It is not a button, it is just under the top menu tap zone :)
