### ISSUE TITLE
feature request: don't reopen last file in case of a crash

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#4929] opened 2019-04-16 14:27 UTC
If the last execution of koreader crashed, koreader should not reopen the last file no matter the settings. Otherwise it can produce an infinite loop of start-crash requiring manual user intervention editing the configuration files.

**Comment by Frenzie** [comment] 2019-04-16 14:39
True, however,

1. If it crashes, the settings won't be saved, including the last loaded file.
2. If there's a fault while loading a file, this will seldom result in a program crash because loading the document is protected by a pcall.

**Comment by Frenzie** [comment] 2019-04-17 19:00
This is something to consider because it could theoretically happen, but closing to keep things tidy since it's more or less a duplicate of #4928, fixed in #4931.

**Closed by Frenzie** 2019-04-17 19:00 UTC
