### ISSUE TITLE
Dictionary formatting

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#2783] opened 2017-04-17 18:02 UTC
* KOReader version:v2015.11-894-gd168db9
* Device: Kobo Glo HD

#### Issue
Any chance that some rudimentary formatting of the dictionary like bold and italic with `<b></b>` and `<i></i>` tags can be displayed in a future release? Currently these tags are ignored. They are used in many stardict dictionaries.

**Comment by alex125** [comment] 2017-04-23 19:31
Another thing that would help to display dictionary content a bit better would be an option to display the text in the dictionary window with text-align:left instead of text-align:justify. If the text is left-aligned, spaces at the beginning of a line (after a <BR>) can be used to always get the same indentation.

**Comment by Frenzie** [comment] 2017-04-23 19:49
This is actually a duplicate of #1776, so I'll close this issue in favor of that one. I think the suggestion there to use MuPDF sounds pretty good, but someone would need to have the time to do it.

**Closed by Frenzie** 2017-04-23 19:49 UTC

**Comment by poire-z** [comment] 2017-04-23 19:59
About text justification (see https://github.com/koreader/koreader/pull/2470), you can disable it by adding `["dict_justify"] = false` to settings.reader.lua (make a backup before editing it, a forgotten comma can make it reseted).
About bold and italic: the current implementation is character only, no html, single font, so implementing that would need quite some changes.
