### ISSUE TITLE
PDF page turn delay

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#3308] opened 2017-10-06 16:39 UTC
* KOReader version: 2015.11-1287
* Device: Kobo Glo (non HD) 

#### Issue
With this version, when the reader has to display the next page (physical PDF page) it takes a couple of seconds or more.
I'm using the scroll mode and manual crop.
It happens with the reflow on or off.
Trying the same books with the 2015.11-1152 shows no delay at all!
Is something changed with the buffering of the next (previous) page?
#### Steps to reproduce
Just open a pdf (I used different sizes like 2.8, 5.2 etc.)

**Comment by poire-z** [comment] 2017-10-06 16:53
There's been some changes related to image scaling and color rendering (which should not be enabled on your kobo).
Could you check how it does with the following versions:
v2015.11-1246-gc770d71 : just before scaling with mupdf work
v2015.11-1267-g7da2998 : just before any color rendering work

And in between changes, including your current 1287: test, clear caches (Tools > Dev Options > clear readers' cache > restart koreader > test with a few taps forward (to make cache for the new pages), a few tap backward (to encounter pages which are now cached and use them), and see if there's differences.

**Comment by embryo10** [comment] 2017-10-06 18:05
Can not find the "Tools > Dev Options > clear readers' cache > restart koreader > test" menu entry.
Is it disabled by default? Is it a command that I have to execute from a terminal somewhere?

I did delete the cache files manually between tests, though I don't think it really mattered since I opened the different versions using KSM's Koreader additions, that lets you choose what version you launch each time from it's own folder (and cache).
The results:
* v2015.11-1246 and v2015.11-1267 behave the same as the 2015.11-1152.
* There is no (noticeable) delay when advancing to a new (not cached) page and no delay when going back on a cached page.
* There is some delay when going back to a new (not cached) page.
* With the 2015.11-1287 there is a really strange behavior.
  * There is the delay I was talking about, but only every second new page.
  * There is no delay when going back to an old page and there is almost double the delay when going back to a new page.
I'll test more (after a few minutes) to find the version that this delay is introduced and report back..

**Comment by Frenzie** [comment] 2017-10-06 18:13
> Can not find the "Tools > Dev Options > clear readers' cache > restart koreader > test" menu entry.
Is it disabled by default?

No, but it's only in the file browser. :-)

**Comment by embryo10** [comment] 2017-10-06 19:20
I tested all the remaining versions, including the 2015.11-1287, and all were behaving properly.
One thing I did with all of them was that I did not create a db file.
So I copied my old db file to the new 2015.11-1287.
With that, there were delays with some pages (but not all the even ones).
I then deleted the file from my original 2015.11-1287 and everything returned to normal.
No more delays.

My problem now is that I don't have statistics anymore.
If I don't create the db file and try to see the Reading progress, Koreader crashes.
If I create an empty one, well, no statistics.
I did had statistics before the sqlite statistics, but I don't know how to get them back..
Any ideas?

**Comment by Frenzie** [comment] 2017-10-06 19:28
Pinging @robert00s

**Comment by robert00s** [comment] 2017-10-06 19:44
@embryo10 Do I understand correctly. Delays with some pages was with existing db file?
How big is your statistics.sqlite3?

**Comment by embryo10** [comment] 2017-10-06 19:49
916KB

**Comment by robert00s** [comment] 2017-10-06 20:24
Without this db - no delays
With this file - delay on some pages?

**Comment by embryo10** [comment] 2017-10-06 20:28
Yeap!

**Comment by robert00s** [comment] 2017-10-06 20:31
Can you send me (or share) statistics.sqlite3 and pdf for test?

**Comment by robert00s** [comment] 2017-10-06 20:39
robert.styla@gmail.com
But I can see at it tomorrow.

**Comment by robert00s** [comment] 2017-10-07 10:03
Thanks. I tested but I cannot reproduce your problem (on emulator and my Kindle). Maybe you have specific settings of pdf.
+ Is delay problem exist on another pdf?
+ Try disable statistics (Reading statistics -> Enable (uncheck)) and check is delay problem still exist
+ Try remove statistics for book with problem (Reading statistics -> Reset book statistics) and try again test
+ Send me folder Caleb Doxsey - Introducing Go.sdr

**Comment by embryo10** [comment] 2017-10-07 10:29
* Yes
* Disabling statistics fixed the delays
* Reset statistics _did not_ fix the delays
* Send

**Comment by robert00s** [comment] 2017-10-07 10:58
I still cannot reproduce the problem.
How do you change pages? Swipe from left from right to left or tap or swipe down to up? 
Can you send me your crash.log?

**Comment by embryo10** [comment] 2017-10-07 11:06
Taping only.
crash.log send...

**Comment by embryo10** [comment] 2017-10-07 11:33
Maybe its because Glo is an older device.
I wonder if there is an option to use the old statistics system instead?

**Comment by embryo10** [comment] 2017-10-09 16:50
Well, since there isn't any progress with this, I tried to copy the old `statistics.koplugin` folder from the 2015.11-1152 release to the 2015.11-1287, but when I select it in the menu koreader crashes.
What do I have to do to have the old plugin back?

**Comment by robert00s** [comment] 2017-10-09 18:52
Old plugin isn't now supported.
I don't think that your Kobo Glo is too old to support new statistics.
I prepare statistics with logger. Please replace existing statistics.plugin/main.lua with that. Try test for some time and notice me on which pages are the problem. Of course send me crash.log again :)
[main.lua.zip](https://github.com/koreader/koreader/files/1369551/main.lua.zip)

**Comment by embryo10** [comment] 2017-10-09 19:34
Trying the new main, produced no delays at all.
But now, I can not reproduce the delays anymore by putting back the old main.
What ever I do (with ether of the last two books) I don't have any delays.
Tried also from the beginning, nothing...
No clue at all.

So, I don't think there is a point to send you the crash.log anymore, is it?
I will use the reader and report back if the problem re-appears.
Thank you for your time and sorry for all the fuzz  :o(

**Comment by Frenzie** [comment] 2017-10-09 19:47
I'm glad the problem disappeared for you but I don't like that it just happened all by itself. I'll close this. Please reopen if the problem returns. :-)

**Closed by Frenzie** 2017-10-09 19:47 UTC
Labels: bug
