### ISSUE TITLE
PB 741 Crash

### ISSUE THREAD

**Issue by liberodark** [koreader/koreader#8875] opened 2022-03-06 22:02 UTC
* KOReader version: 2022.02
* Device: PB 741

#### Issue

I often have repeated crashes for the moment just in its last days I had 28. 

#### Step to reproduce

Just read manga and it randomly crashes. 

crash.log

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/05/22-15:02:48
 [*] Version: v2022.02

ffi.load: blitbuffer
ffi.load: inkview
03/05/22-15:02:49 INFO  SoftwareVersion:  U741.6.5.1684
Atached mp shm: id 0 addr a6f7a000 size 17616
attach_shm: mtfb key=251401915 size=8409872
Atached mtfb shm: id 5d8007 addr a3b26000 size 8409872
-------------------------
Starting task - koreader.app
flags: 0x00100080
gpid: 22203
fb=0xa3b26000 xres=1404 yres=1872 scanline=4224 vdepth=24 orient=0
-------------------------
attach_shm: mttempfb key=251308714 size=2665728
Atached mttempfb shm: id 8001 addr a389b000 size 2665728
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800000; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 0 10000 18720000 -10000 0
attach_shm: mtfb key=251401915 size=8409872
Atached mtfb shm: id 5d8007 addr a1d6c000 size 8409872
ffi.load: inkview
ffi.load: librt.so
ffi.load: inkview
ffi.load: inkview
03/05/22-15:02:49 INFO  initializing for device PBInkPadColor
03/05/22-15:02:49 INFO  framebuffer resolution: {
    ["w"] = 1404,
    ["h"] = 1872,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libutf8proc.so.2
03/05/22-15:02:50 INFO  opening file /mnt/ext2/Mangas/Blue Lock/Blue Lock T02.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
03/05/22-15:02:51 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
03/05/22-15:02:51 WARN  Error when loading plugins/terminal.koplugin/main.lua
03/05/22-15:02:52 INFO  setting zoom mode to pagewidth
03/05/22-19:33:30 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/05/22-19:33:52 INFO  opening file /mnt/ext2/Mangas/Blazer Drive/Blazer Drive T06.pdf
03/05/22-19:33:52 INFO  setting zoom mode to content
03/05/22-19:34:06 INFO  opening file /mnt/ext2/Mangas/Blazer Drive/Blazer Drive T06.pdf
03/05/22-19:34:06 INFO  setting zoom mode to content
03/05/22-19:59:34 INFO  opening file /mnt/ext2/Mangas/Blazer Drive/Blazer Drive T07.pdf
03/05/22-19:59:34 INFO  setting zoom mode to pagewidth
03/05/22-19:59:49 INFO  setting zoom mode to page
03/05/22-19:59:49 INFO  setting zoom mode to content
03/05/22-20:53:52 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/05/22-22:32:52 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/05/22-22:35:56 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/06/22-01:15:55 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/06/22-01:49:37 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/06/22-01:57:03 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/06/22-16:56:26 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/06/22-18:12:01 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
03/06/22-18:24:57 INFO  opening file /mnt/ext2/Mangas/Blazer Drive/Blazer Drive T08.pdf
03/06/22-18:24:57 INFO  setting zoom mode to pagewidth
03/06/22-18:25:11 INFO  setting zoom mode to page
03/06/22-18:25:11 INFO  setting zoom mode to content
03/06/22-22:48:46 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
./luajit: frontend/ui/uimanager.lua:1201: attempt to call field 'action' (a nil value)
stack traceback:
	frontend/ui/uimanager.lua:1201: in function '_checkTasks'
	frontend/ui/uimanager.lua:1622: in function 'handleInput'
	frontend/ui/uimanager.lua:1734: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00013f5d
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 03/06/22 @ 22:56:57)
Attempting to restart KOReader . . .
!!!!
```

Full crash.log : 
[crash.log](https://github.com/koreader/koreader/files/8193616/crash.log)

frontend/ui/uimanager.lua : 

https://github.com/koreader/koreader/blob/441036ed1f12e98a91b537e0d3c836edd662bab9/frontend/ui/uimanager.lua#L1182

**Comment by NiLuJe** [comment] 2022-03-06 23:36
Duplicate of #8638

**Closed by NiLuJe** 2022-03-06 23:36 UTC
