### ISSUE TITLE
[question / feature request] How to take an Inoreader account/OPML file and import to koreader?

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4513] opened 2019-01-25 21:24 UTC
* KOReader version: TBD have to jailbreak my kindle first
* Device: Kindle Paperwhite 4

So I see that there is apparently some kind of RSS downloader plugin built into KOreader (https://github.com/koreader/koreader/wiki/News-downloader) but the wiki doesn't seem to elaborate very much.

I'd *LOVE* to take my existing Inoreader account or an OPML from it if not possible and have it import all my RSS feeds from there into koreader.  Or perhaps selectively import it.  This would be great for the times I want to read something but don't feel like reading a book.

Unrelated, but somewhat related.. what's the generally accepted best way to save and read articles for later via koreader?  I know that there is Instapaper and pocket (i use both) + third party apps like wallabag.  What's the generally accepted way of doing it?

**Comment by pazos** [comment] 2019-01-25 22:15
> Unrelated, but somewhat related.. what's the generally accepted best way to save and read articles for later via koreader? I know that there is Instapaper and pocket (i use both) + third party apps like wallabag. What's the generally accepted way of doing it?

Duplicate of yourself in https://www.mobileread.com/forums/showthread.php?t=314635 :nerd_face: 

> So I see that there is apparently some kind of RSS downloader plugin built into KOreader (https://github.com/koreader/koreader/wiki/News-downloader) but the wiki doesn't seem to elaborate very much.

Fair point. Yeah, a manual is almost ready; https://github.com/koreader/koreader/pull/4139/files. You can get more info there. Maybe we can copy that info to the wiki? Are you interested?

> I'd LOVE to take my existing Inoreader account or an OPML from it if not possible and have it import all my RSS feeds from there into koreader. Or perhaps selectively import it. This would be great for the times I want to read something but don't feel like reading a book.

Why don't use calibre to fetch the news, format them as you like and send them to your book?.

**Closed** 2021-02-03 19:21 UTC
Labels: out-of-scope, question
