### ISSUE TITLE
Screensaver issues when launched via KPVBooklet (white screen or image overriden by default screensaver).

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#4605] opened 2019-02-17 03:02 UTC
* KOReader version: v2019.02-8
* Device: Kindle PW3, FW: 5.8.1, special offers disabled by amazon
#### Issue
When screensaver is set to:
* "Use book status as screensaver"
* "Use reading progress as screensaver"
* "Use message as screensaver"
* (possibly other image related options)
Kindle "draws" over it after ~2-3 seconds.
#### Steps to reproduce
Set screensaver to one of the above options and make the device go to sleep

**Comment by NiLuJe** [comment] 2019-02-17 04:13
Self ping so that I remember about this tomorrow ;).

Probably need to enable the aggressive awesome stopping on more FW versions.

**Comment by NiLuJe** [comment] 2019-02-18 00:29
Okay, can't reproduce over here, and the versions checks are early enough for 5.8.1.

So... *drumroll*, would you happen to be using KPVBooklet?

**Comment by Galunid** [comment] 2019-02-18 02:26
Yup, I use KPVBooklet, I just checked and can't reproduce when launched using KUAL.

**Comment by NiLuJe** [comment] 2019-02-18 03:06
Yeah, and I don't think we can do anything about the KPVBooklet behavior on those FW.

Closing in favor of the original report, #3287

**Comment by NiLuJe** [comment] 2019-02-18 03:18
(Made this one the primary issue, as #3287 was originally *NOT* entirely KPVBooklet specific, while this and #4413, #4435 are).

**Comment by NiLuJe** [comment] 2019-02-18 03:57
If you're exclusively using KOReader and/or don't care about default screensavers, I have a stupidly low-tech workaround in mind:

Use the ScreenSaver Hack, and set it up with a single image: a *completely* transparent image (in the right format, c.f., the screesaver's default overlay images).

**Closed** 2020-06-27 22:58 UTC
Labels: Kindle, bug, duplicate, firmware, wontfix
