### ISSUE TITLE
Hardware buttons don't work

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#5761] opened 2020-01-11 18:58 UTC
<details>
<summary>
<b>original message</b>
</summary>

<p> 

* KOReader version: v2019.12
* Device: Tolino Epos 2

#### Issue
Hardware buttons for turning the pages do not work in landscape mode, but they do in portrait mode.

</p>
</details>

**EDIT**

**answer for all devices:** koreader maps android keycodes to specific actions. See [defaults](https://github.com/koreader/koreader/blob/master/frontend/device/android/event_map.lua) following aosp/sdk/ndk standard keycodes.

If your device don't follow standard google keycodes (mainly because it is a e-ink reader poorly launch'd) you'll need to [override the keymap for your device](https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys)

To log the keycodes used by your device read the next post

**Comment by pazos** [comment] 2020-01-11 19:13
Can't reproduce on my tablet (using volume buttons as page buttons). We need logs:

- Start KOReader, go to filemanager
- Go to the tools menu -> developer options.
- Enable debug logs
- Get a specific log in both portrait & landscape: 

**on linux/mac**: `adb logcat KOReader:* *:S | grep "key event =>"`
**on windows**: `adb shell logcat KOReader:* *:S | grep "key event =>"`.
**Note:** Legacy versions of windows' adb would require:

```
adb shell
logcat KOReader:* *:S | grep "key event =>"
```

Logs are something like

```logcat

01-11 20:03:36.582 32486 32508 V KOReader:  key event => type: 1, code: 25(LPgFwd), value: 1, time: 1578769416.581970
01-11 20:03:36.925 32486 32508 V KOReader:  key event => type: 1, code: 25(LPgFwd), value: 1, time: 1578769416.925634
01-11 20:03:37.243 32486 32508 V KOReader:  key event => type: 1, code: 25(LPgFwd), value: 1, time: 1578769417.242855
01-11 20:03:37.372 32486 32508 V KOReader:  key event => type: 1, code: 25(LPgFwd), value: 0, time: 1578769417.372304
01-11 20:03:40.362 32486 32508 V KOReader:  key event => type: 1, code: 24(LPgBack), value: 1, time: 1578769420.362321
01-11 20:03:40.552 32486 32508 V KOReader:  key event => type: 1, code: 24(LPgBack), value: 0, time: 1578769420.552092
```

**Comment by elvvis** [comment] 2020-01-11 19:58
Here is the log file, entries for the landscape format begin in line 1301.
[log.txt](https://github.com/koreader/koreader/files/4049797/log.txt)

**Comment by pazos** [comment] 2020-01-11 20:29
@elvvis: could you please use the **specific command**, and just press one time each button in the same order for both portrait and landscape? Thanks!

I'm willing to help but the logs you're providing are not the logs that were requested.

**Comment by elvvis** [comment] 2020-01-11 20:38
> @elvvis: could you please use the **specific command**, and just press one time each button in the same order for both portrait and landscape? Thanks!
> 
> I'm willing to help but the logs you're providing are not the logs that were requested.

Sorry, i can‘t use the specific command, because there is no ‚grep‘ on windows.

**Comment by pazos** [comment] 2020-01-11 20:55
> **Note:** Legacy versions of windows' adb would require:
> 
> ```
> adb shell
> logcat KOReader:* *:S | grep "key event =>"
> ```

**Comment by elvvis** [comment] 2020-01-11 21:43
**portrait**:
V/KOReader( 4501):  key event => type: 1, code: 22(Right), value: 1, time: 1578778454.760083
V/KOReader( 4501):  key event => type: 1, code: 22(Right), value: 0, time: 1578778454.978017
V/KOReader( 4501):  key event => type: 1, code: 21(Left), value: 1, time: 1578778456.689365
V/KOReader( 4501):  key event => type: 1, code: 21(Left), value: 0, time: 1578778456.875**871

**landscape**:
V/KOReader( 4501):  key event => type: 1, code: 22(Right), value: 1, time: 1578778477.939645
V/KOReader( 4501):  key event => type: 1, code: 22(Right), value: 0, time: 1578778478.158157
V/KOReader( 4501):  key event => type: 1, code: 21(Left), value: 1, time: 1578778480.279840
V/KOReader( 4501):  key event => type: 1, code: 21(Left), value: 0, time: 1578778480.438948

**Comment by pazos** [comment] 2020-01-11 22:08
@elvvis: much better, thanks!

As you see they're both the same events in potrait and landscape. So I dunno why it works on portrait and not in landscape.

Anyways, you can override the event map using [this](https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#example-3-add-support-for-the-custom-keys-used-on-the-nook-glowlight-3-top-keys-as-page-back-and-bottom-keys-as-page-forward ) as a template and replacing values with the codes you provide.

That is: instead of left/right use LPgBack/LPgFwd. You can map these events as you like so both

```lua
return {
   [21] = "LPgBack",
   [22] = "LPgFwd",
}
```
and 

```lua
return {
   [21] = "LPgFwd",
   [22] = "LPgBack",
}
```

should work.

**Comment by elvvis** [comment] 2020-01-11 22:50
With customizing the key mappings and use of LPgBack/LPgFwd instead of left/right it works.

**Comment by pazos** [comment] 2020-01-12 00:51
> With customizing the key mappings and use of LPgBack/LPgFwd instead of left/right it works.

Cool. I labeled as won't fix as it cannot be fixed programatically. Android ereaders are just like cars but in cars the layout of the pedals is enforced by regulations and laws and nothing is enforcing these devices to follow google keycodes.

It can be workarounded but requires code per device or type of device (like the epd driver). If someone wants to do it feel free to modify https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/DeviceInfo.kt, add a new type of `BugDevice` and catch your model. So you can return an event map different from [defaults](https://github.com/koreader/koreader/blob/master/frontend/device/android/event_map.lua).

The workaround is simpler to do and easier to keep updated for borked devices (ie: keeping the wiki in sync with new reports).

Just like in #5364 we might want to stick with google best practices, allow PR for specific devices and keep the issue open to allow future duplicates.

I'll update the title and OP with the relevant info.

**Comment by Frenzie** [comment] 2020-02-05 20:42
@pazos Should this be closed?

**Comment by pazos** [comment] 2020-02-05 23:08
The issue is linked in https://github.com/koreader/koreader/wiki/Android-tips-and-tricks, so it should be ok to close it if we close future duplicates too.

**Comment by Frenzie** [comment] 2020-02-05 23:10
Alright, I'll close it then.

**Closed by Frenzie** 2020-02-05 23:10 UTC
Labels: Android, firmware, wontfix
