### ISSUE TITLE
Slow (1-4s) page turns every 5-15 pages

### ISSUE THREAD

**Issue by angerson** [koreader/koreader#7340] opened 2021-02-23 02:01 UTC
#### Device Details
- Device: Kobo Libra H2O (has page turn buttons)
- Koreader version: 2021.02 (and all previous versions)

#### Issue
Every once in a while, turning a page in KOreader takes 1-4 seconds. Usually incidents grow in frequency and length until I restart KOreader, at worst ~5 seconds each every 10-20 pages.

Weak points that I think I've noticed:

- Seemingly happens more often if RAM usage is very high
- Seems to be worse with complex fonts, *especially* EB Garamond (compared to Bookerly). I changed from Bookerly to EB Garamond and it started happening a lot more often.
- Usually happens just before a full screen refresh (black flash), or right after. Doesn't happen with every flashing refresh, though.
- I can't tell if it's related to page contents or not. Some pages seem to be more prone than others, if I scroll back and forth over them, but most of the time it just seems random.
- Doesn't seem to be related to dpi, page/continuous mode, Render mode, or font size
- Incidents seemed to go away for a while when I set Font Hinting `auto` -> `off` and Kerning `best` -> `off`, but then they came back just as badly.

Stats from last time it happened:
  - Book: 2.8MB, 1224 pages, epub, just text
  - Font: EB Garamond
  - Storage: 5.1G available of 6.7G
  - System Usage%: 1.16
  - Virtual Memory: 342MB
  - RAM usage: 132MB
  - Total Memory: 496MB
  - Free Memory: 134MB
  - Available Memory: 339.26MB

#### Reproduction
I can't guarantee this will reproduce, but try to read a long book with the smaller version of EB Garamond and turn the pages a lot.

**Comment by NiLuJe** [comment] 2021-02-23 02:15
Are those *single* page turns, are is that *a* page-turn in the middle of a series of page-turns?

(Or, for that matter, a series of *something* causing a refresh, e.g., if you have the footer set to auto-refresh).

**Comment by NiLuJe** [comment] 2021-02-23 02:19
Because, for the record: you can't expect *any* kind of latency guarantee during a continuous series of refresh. And the leeway between refreshes is *much* stricter on REAGL devices (as in, essentially: you don't have any leeway at all ^^. A REAGL update better stand on its own with nothing happening roughly a second before and after).

As a fun experiment, you'll notice that if you open a book, and right when it's refreshed the first page, you try to tap on the menu tapzone, the menu won't show up until a noticeable delay.
That wouldn't be the case on the same device when not using REAGL updates, the menu would popup instantly.

**Comment by NiLuJe** [comment] 2021-02-23 04:43
You can test that theory by disabling REAGL (and enjoy ghosting galore!)

```diff
diff --git a/ffi/framebuffer_mxcfb.lua b/ffi/framebuffer_mxcfb.lua
index 05998ac0..4527e544 100644
--- a/ffi/framebuffer_mxcfb.lua
+++ b/ffi/framebuffer_mxcfb.lua
@@ -802,7 +802,7 @@ function framebuffer:init()
             self.mech_refresh = refresh_kobo_mk7
             self.mech_wait_update_complete = kobo_mk7_mxc_wait_for_update_complete
 
-            self.waveform_partial = C.WAVEFORM_MODE_GLR16
+            self.waveform_partial = C.WAVEFORM_MODE_GL16
             self.waveform_fast = C.WAVEFORM_MODE_DU -- A2 is much more prone to artifacts on Mk. 7 than before, because everything's faster.
                                                     -- Nickel sometimes uses DU, but never w/ the MONOCHROME flag, so, do the same.
                                                     -- Plus, DU + MONOCHROME + INVERT is much more prone to the Mk. 7 EPDC bug where some/all
```

**Comment by angerson** [comment] 2021-02-23 06:06
>Are those single page turns standing on their own during normal reading, or is that a page-turn in the middle of a series of page-turns?

This happens while I'm reading normally, turning the page once every ten seconds or so. I think it happens at roughly the same rate when turning pages as soon as the next page is done rendering, so every two seconds or so. I haven't tested changing pages as quickly as possible, which would be just asking for trouble...

For the book I was reading, I changed the font and rebooted koreader to take the memory usage way down, but it's still happening a lot. I did some better testing by enabling a full refresh every page turn, and it still happened often, usually a couple times out of every ten pages.

Next I set the Full Refresh Rate to 'Never' and it didn't happen once in fifty pages, so it's at least related to that (no refresh at all isn't ideal, but it's better).

>A REAGL update better stand on its own with nothing happening roughly a second before and after...you try to tap on the menu tapzone, the menu won't show up until a noticeable delay

That makes sense! This seems different, though -- I timed a recent one, and after I clicked the turn button, and it took ~4 seconds before the page turned and the black flash happened.

What is the most useful kind of extra data I could provide? I'll test out disabling REAGL, and could also record a video, count occurences / timing, etc.

**Comment by NiLuJe** [comment] 2021-02-23 06:17
You mentioned changing fonts, so I assumed you were talking about ePubs. Is
that actually the case? (Because we don't pre-render anything in ePubs, so
the "as soon as the next page is done rendering" assumption is wrong ;).).

In which rotation are you reading?

FWIW, 4s sounds entirely ridiculous. Even 1s does. This kind of stuff
should take less than 100ms.

You might also want to check things with the device plugged in.

**Comment by NiLuJe** [comment] 2021-02-23 06:22
I definitely wouldn't say no to a video ;).

For reference, on a Forma, which should behave exactly the same:
https://www.mobileread.com/forums/showthread.php?p=4080193#post4080193

Digging that link up did remind me that someone else reported weird stuff
with a Libra, but that went nowhere.

**Comment by NiLuJe** [comment] 2021-02-23 06:25
Other than that, verbose debug logs always help ;).

(FM > Tools > More tools > Developer options; then restart KOReader).

**Comment by angerson** [comment] 2021-02-26 01:32
> (Disable REAGL with lua)

I applied the patch and restarted KOReader, but I didn't notice any differences. I also felt like there wasn't very much ghosting that I could see -- maybe I did it wrong? What should I look for, specifically?

> You mentioned changing fonts, so I assumed you were talking about ePubs. Is
that actually the case? ... In which rotation are you reading?

Yeah, I'm reading an epub in portrait mode with landscape mode disabled. I have no data for other file types.

> You might also want to check things with the device plugged in.

I tried this and I don't think it made a difference.

> (Video evidence)

Here's a video and a verbose debug log starting from where I opened the file. In the video, I held down the page button and got the same random pauses as I get with normal reading (i.e. I don't think this is the no-guarantees effect of turning pages as quickly as possible). Oddly, after the video ended there weren't any more for a long time.

https://user-images.githubusercontent.com/32465472/109241703-a60f1600-778e-11eb-8cbf-932807861f3a.mp4

[log_for_first_alix_harrow.log](https://github.com/koreader/koreader/files/6046800/log_for_first_alix_harrow.log)

Anything else I can do?

**Comment by NiLuJe** [comment] 2021-02-26 05:38
Note that this kind of experiment falls squarely into what I mentioned earlier, i.e.:

> Because, for the record: you can't expect _any_ kind of latency guarantee during a continuous series of refresh.

That said, it does corroborate your own feeling of it only happening around flashing updates.

Now, what happens after a flashing update is that we *ask* the kernel to wait until it's done processing said update. (The intent being: I don't want anything to mess with that refresh).
This is usually not a problem, and, given the context, usually means blocking for around 300ms.

Now, that operation happens to have a timeout set at 5s, after which point the kernel gives up.
Even in the direst of condition, this should pretty much *never* happen.

And yet...

```
02/24/21-15:53:53 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 20 (WFM: 2 & UPD: 1)
02/24/21-15:53:53 DEBUG refresh: wait for completion of marker 20
02/24/21-15:53:58 DEBUG input event => type: 0, code: 3(nil), value: 0, time: 1614210838.496067
```

Oh, 5s :}.

If you have shell access, you can check the kernel logs, and they should be full of warnings. I'd be fairly interested in those.

My usual approach to make this easier is to first send the kernel logs to the syslogs, by running `klogd`, because that way you get 'em timestamped, which helps cross-reference with our logs and the syslog, which you cna read via `logread`.
Kobo may or may not be building the klogd applet, so this may require my [bundle of tools](https://www.mobileread.com/forums/showthread.php?t=254214).

**Comment by NiLuJe** [comment] 2021-02-26 05:39
So, next set of questions:

* Which FW version are you running?
* How do you launch KIOReader?
* Do you have anything else custom running in the background?

**Comment by NiLuJe** [comment] 2021-02-26 05:42
Worth noting is also the fact that we stagger repeat events, so holding the key down will be slower than clicking it repeatedly. Not that it should matter much, because IIRC I tweaked the stagger to match... a flashing update timing ;p.

**Comment by poire-z** [comment] 2021-02-26 07:35
(Unrelated, but on that video and EPUB book, what's with these random line breaks? Words are broken/wrapped inside, without any hyphen showing... Was this EPUB processed to behave that way - by calibre or else ?)

**Comment by angerson** [comment] 2021-03-03 05:19
> what's with these random line breaks?

I think it's a problem with EB Garamond. It doesn't happen with any other fonts.

> Which FW version are you running?

4.26.16704 (0af09acc53, 2/10/21), very recent. It's happened with every previous version I've had on this device as well.

> How do you launch KOReader?

Through NickelMenu, set up with your [one-click installer](https://www.mobileread.com/forums/showthread.php?t=314220) (THANK YOU). I launch it as soon as I boot the device.

> Do you have anything else custom running in the background?

No, I've run the one-click installer (THANK YOU) and nothing else.

> Kernel logs

I took another video with normal page turns and klogd that captured a bunch of "incidents". Notes on this session:

- The video starts at about 8:05 pm.
- I didn't manage to capture it in the video, but right before I started, the whole menu was VERY slow. Maybe related? 
- I kept KOReader set to full-refresh every page since that seems to cause more incidents.
- I really had to tear up this video to get it on GitHub. >_< It should be OK since the clock is still readable.
- After the first few incidents, I move my thumb away whenever an incident happens.
- Incidents seemed to want to cascade unless I waited for a few extra moments after the page finally turned.

[crash.trimmed.log](https://github.com/koreader/koreader/files/6073686/crash.trimmed.log) (trimmed to the video range)
[logread.txt](https://github.com/koreader/koreader/files/6073687/logread.txt) (not trimmed, in case it's important)

https://user-images.githubusercontent.com/32465472/109755873-a8f97480-7b9b-11eb-94cb-08046db3c576.mp4

**Comment by NiLuJe** [comment] 2021-03-03 16:56
>     * I didn't manage to capture it in the video, but right before I started, the whole menu was VERY slow. Maybe related?
> 

I'm seeing a few other timeouts in the kernel logs before 20:05, so, quite possible (as the menus will flash).

>     * I kept KOReader set to full-refresh every page since that seems to cause more incidents.
> 

:+1:

>     * After the first few incidents, I move my thumb away whenever an incident happens.
> 

Thanks, that was helpful without sound ;).

>     * Incidents seemed to want to cascade unless I waited for a few extra moments after the page finally turned.
> 

Yep, that makes sense: if the kernel feels like it's already overwhelmed, piling on stuff will only snowball.
The question of *why* it feels overwhelmed when we don't really overwhelm it still stands :).

And on that note... I noticed a few timeouts *outside* of KOReader (e.g., in Nickel).

Can you reproduce that in Nickel? Because that would imply some kind of sneaky hardware failure ;).

If you *cannot*, I'd like to get a strace of Nickel on your device, on the off-chance it's aware of a device-specific quirk and doing things differently.

That *will* require [my bundle of tools](https://www.mobileread.com/forums/showthread.php?t=254214), and an SSH session (ideally over USBNet, but over Wi-Fi works, you just might have to force Wi-Fi on to avoid it cutting off).

e.g., over SSH, run

`strace -fittvyT -e trace=ioctl -p $(pidof nickel)`

And then just do stuff around Nickel, ideally mixing between navigating the Home/Library/Menus, and then actually using it to read something ^^.

**Comment by angerson** [comment] 2021-03-06 17:53
[terminal_output.txt](https://github.com/koreader/koreader/files/6095798/terminal_output.txt)

I finally managed to reproduce this in Nickel. I don't have a video but could probably get one if you want. There are a few timeouts here and I think all of them should correspond to when I set the refresh-period to once-per-ten-pages and then turned pages as quickly as possible: in some of those cases, after the refresh, the same timeout as in KOReader would happen.

- *Usually*, turning a page in Nickel's reader is pretty slow, it takes almost a whole second to flip the first one. But rapidly flipping pages really loads them as fast as possible (sometimes causing rendering overlaps). When that culminated in a page refresh, it would time out afterwards.
- Other times I'd try flipping pages as quickly as possible and Nickel would limit the speed to one or two seconds each. Then the timeout wouldn't happen.
- If I set Nickel to refresh every page, it throttles fast-page-turns. I couldn't get it to time out that way.

I installed KOReader in the first place partly because Nickel takes so long to turn pages. Maybe it's that way intentionally?

**Comment by angerson** [comment] 2021-03-06 17:55
Also, FWIW, after messing with Nickel for a while and then returning to KOReader, page turning was stable for a very long time (at least hundreds of pages). I can't figure out any pattern.

**Comment by NiLuJe** [comment] 2021-03-06 18:18
If you read plain ePubs, Nickel's performance is downright *terrible* (and it used to be even worse).

If you read Kobo ePubs, its performance is somewhat passable ;).

PDFs and CBZs are... not a fun experience, either ;).

**Comment by NiLuJe** [comment] 2021-03-06 18:20
As for the logs: I'm much more interested in Nickel's *strace* output than the kernel logs while Nickel is running ;o).

**Comment by angerson** [comment] 2021-03-09 17:32
[strace.txt](https://github.com/koreader/koreader/files/6110340/strace.txt)

Here's a Nickel strace. I used the menu for a short time to browse my books, opened the settings, clicked home (which failed?) and then started reading a book. I set the refresh rate to 10 pages and tried to turn as quickly as possible -- after the refresh it would sometimes hang for a second or two *if* I could get the pages to turn rapidly, but not as long as the full 5 second timeout in KOReader. Then I set the refresh rate to once per page and nothing happened, because page turning wouldn't go faster than once per second or two. 

Aside about the KoboTools: 

- The DL link on the thread is broken, but the one on the overview of all your tools isn't
- I couldn't figure out how to install the tools -- I didn't realize all I had to do was put KoboRoot in .kobo (thankfully, someone mentioned it later in the thread).
- I couldn't figure out how to get USBNet working after toggling it on (like the other user, my PC couldn't connect to 192.168.2.2), so I used tmux under wifi, which worked fine.

**Comment by NiLuJe** [comment] 2021-03-09 18:01
No timeouts indeed in that strace, but, something interesting nonetheless, so, a couple questions:

* Was that a ePub or a Kobo ePub? With significant image content?
* Was that a CBZ?
* Was that a fixed-layout (K)ePub?

If any of these were yes, try with a plain old KePub novel instead ;).

**Comment by angerson** [comment] 2021-03-11 03:43
Problem Exists Between Computer And Kobo? :)

All the books I've tested to get these results so far are standard epubs with almost no images. The one in first video has chapter header images, but that's all. 

[strace.kepub.txt](https://github.com/koreader/koreader/files/6120257/strace.kepub.txt)

Here's an strace of an ePub I converted to a kepub (with no images). It was able to turn pages very very quickly, and when I set the refresh rate to once per ten pages and clicked the page button as quickly as possible, it did time out for about five seconds right after the refresh, two out of ~four times.

**Comment by angerson** [comment] 2021-03-11 03:44
FWIW, I've never used anything except standard epubs with KOReader except for a couple of CBZs and PDFs that take a long time to turn the page for normal reasons.

**Comment by NiLuJe** [comment] 2021-03-11 04:33
Hmm, I'll have to double-check plain ePubs on the Forma tomorrow ;).

But, at least as far as KePubs are concerned, that's consistent with what I was expecting (i.e., we do roughly the same thing), and I'm indeed seeing a couple of timeouts.

That unfortunately strongly pushes the ball towards the "not our bug" and/or "weird hardware failure", until someone else with a Libra can provide similar results... :/.

**Comment by NiLuJe** [comment] 2021-03-11 04:41
That does give me stupid patch ideas, to try in this order:

1. Emulate the plain ePub behavior by stupidly requesting dithering all the time:

```diff
diff --git a/ffi/framebuffer_mxcfb.lua b/ffi/framebuffer_mxcfb.lua
index 05998ac0..dfb72843 100644
--- a/ffi/framebuffer_mxcfb.lua
+++ b/ffi/framebuffer_mxcfb.lua
@@ -515,6 +515,7 @@ local function refresh_kobo_mk7(fb, refreshtype, waveform_mode, x, y, w, h, dith
     -- TEMP_USE_AMBIENT, not that there was ever any other choice on Kobo...
     refarea[0].temp = C.TEMP_USE_AMBIENT
     -- Did we request HW dithering?
+    dither = true
     if dither then
         refarea[0].dither_mode = C.EPDC_FLAG_USE_DITHERING_ORDERED
         if waveform_mode == C.WAVEFORM_MODE_A2 or waveform_mode == C.WAVEFORM_MODE_DU then
```

OR

2. Faking the WAIT_FOR_UPDATE_COMPLETE stuff, since the refresh themselves appeared to mostly behave, IIRC.

```diff
diff --git a/ffi/framebuffer_mxcfb.lua b/ffi/framebuffer_mxcfb.lua
index 05998ac0..2d972797 100644
--- a/ffi/framebuffer_mxcfb.lua
+++ b/ffi/framebuffer_mxcfb.lua
@@ -1,5 +1,6 @@
 local bit = require("bit")
 local ffi = require("ffi")
+local ffiUtil = require("ffi/util")
 local BB = require("ffi/blitbuffer")
 local C = ffi.C
 
@@ -175,6 +176,11 @@ local function kobo_mk7_mxc_wait_for_update_complete(fb, marker)
     return C.ioctl(fb.fd, C.MXCFB_WAIT_FOR_UPDATE_COMPLETE_V3, mk7_update_marker)
 end
 
+-- Stub version that simply sleeps for 1ms (which is roughly twice the amount of time a real NOP WAIT_FOR_UPDATE_COMPLETE would take)
+local function stub_mxc_wait_for_update_complete()
+    ffiUtil.usleep(1000)
+end
+
 -- Pocketbook's MXCFB_WAIT_FOR_UPDATE_COMPLETE_PB... with a twist.
 local function pocketbook_mxc_wait_for_update_complete(fb, marker)
     -- Wait for a specific update to be completed
@@ -780,6 +786,8 @@ function framebuffer:init()
             isMk7 = true
         elseif self.device.model == "Kobo_storm" then
             isMk7 = true
+        elseif self.device.model == "Kobo_luna" then
+            isMk7 = true
         end
 
         if isREAGL then
@@ -807,6 +815,11 @@ function framebuffer:init()
                                                     -- Nickel sometimes uses DU, but never w/ the MONOCHROME flag, so, do the same.
                                                     -- Plus, DU + MONOCHROME + INVERT is much more prone to the Mk. 7 EPDC bug where some/all
                                                     -- EPDC flags just randomly go bye-bye...
+
+            if self.device.model == "Kobo_storm" then
+                -- Shitty WAIT_FOR_UPDATE_COMPLETE workaround on the Libra (#7340)
+                self.mech_wait_update_complete = stub_mxc_wait_for_update_complete
+            end
         end
     elseif self.device:isPocketBook() then
         require("ffi/mxcfb_pocketbook_h")
```

**Comment by NiLuJe** [comment] 2021-03-12 23:00
xref w/ https://www.mobileread.com/forums/showthread.php?p=4101823

Which adds another notch in the "wait for update is borked on the Libra" column, since the reporter mentions a very specific behavior ((flashing on image content][https://github.com/koreader/koreader/pull/6528]) that was introduced in a very narrow time-period (between (2020.08 & 2020.08.1)[https://github.com/koreader/koreader/compare/v2020.08...v2020.08.1)).

**Comment by angerson** [comment] 2021-03-13 00:32
Just to be sure: once I apply one of these patches, I have to restart KOReader for the changes to take effect, right?

**Comment by NiLuJe** [comment] 2021-03-13 00:42
Yup!

**Comment by angerson** [comment] 2021-03-13 01:20
Stupid Patch Idea 1 didn't work, but after applying Stupid Patch Idea 2, KOReader feels *super* snappy. I haven't noticed any slowdown *at all* in the few minutes I've been messing with it. Even the menu feels faster. It's awesome.

I think I can see the effects of the new timeout timeout: is that where the new content loads and then, in a second step, clears what was there before? The transition is obvious now, e.g. turning pages really fast generates a lot of garbled overlapping pages (not that it matters very much, since they clean themselves up).

Do you want me to do any more specific testing?

**Comment by angerson** [comment] 2021-03-13 01:22
As a more specific example, hyperlinks flicker when they render; they start black and then finish changing color an instant later.

**Comment by NiLuJe** [comment] 2021-03-13 02:08
The flash flashing is perfectly normal, what *might* be happening and is less "normal" (but somewhat expected with a fake WAIT_FOR_COMPLETE) is our good friend the so-called [papercut refresh glitch](https://github.com/koreader/koreader/issues/3130) ;).

**Comment by NiLuJe** [comment] 2021-03-13 02:09
> Stupid Patch Idea 1 didn't work

Yeah, that one's actually a good news in my book ^^.

**Comment by NiLuJe** [comment] 2021-03-13 02:10
As far as more testing goes, well, anything that flashes (e.g., opening/closing menus) and, well, flashing page-turns would be good things to test :).

**Comment by NiLuJe** [comment] 2021-03-13 02:14
What might also be happening if you really push it is different refreshes being bundled into one (but hopefully sanely) and/or dropped (but hopefully only old ones because they've been merge in a new one) or weirdly staggered for a while.

**Comment by NiLuJe** [comment] 2021-03-13 02:17
> As a more specific example, hyperlinks flicker when they render; they start black and then finish changing color an instant later.

That's perfectly normal, that's the expected behavior for W/B to GRAY update (c.f., the large gray toggle buttons in the bottom menu, for instance).

**Comment by angerson** [comment] 2021-03-13 20:07
> As far as more testing goes, well, anything that flashes (e.g., opening/closing menus) and, well, flashing page-turns would be good things to test :).

- Opened a few more normal epubs and paged / skimmed through them quickly and at normal reading speed
- Used the menus extensively inside and outside of the reader
- Searched within a book and cycled through pages
- Restarted KOReader a couple times
- Turned a bunch of pages with refreshes every page
- Read an epub that was entirely images (usually randomly slow, maybe related to that xref)
- Read a PDF

I've seen no unexpected delays. Before now, I was used to random amounts of delay when doing anything that could flash (e.g. swiping to load the menu while reading, reading PDFs, etc), and that seems to be gone. KOReader is now consistently fast. I'm blown away at how nice it is to use now.

> That's perfectly normal (and unrelated to the issue at hand), that's the expected behavior for a W/B to GRAY update (c.f., the large gray toggle buttons in the bottom menu, for instance).

Yep, I double-checked and you're right. I only noticed this and the other "slower" refreshes because everything else is faster.

**Comment by NiLuJe** [comment] 2021-03-14 18:17
I generally avoid doing that, but since it's been [reproduced on Nickel](https://github.com/koreader/koreader/issues/7340#issuecomment-796420232), too... ping @gtalusan ;).

To recap:

On the Libra, for no apparent reasons, completely innocuous WAIT_FOR_UPDATE_COMPLETE ioctls will fail with a full timeout (that's 5s on a Mk. 7 kernel).

While I've seen [a fair share of weird glitches](https://github.com/NiLuJe/FBInk/blob/21023a92d99e68429d1f7172b4791f2d31eaa384/fbink.c#L2433-L2445) on EPDCv2 devices (some [more easily worked-around](https://github.com/NiLuJe/FBInk/blob/21023a92d99e68429d1f7172b4791f2d31eaa384/fbink.c#L2454-L2458), and even [a few hangs](https://github.com/NiLuJe/FBInk/blob/21023a92d99e68429d1f7172b4791f2d31eaa384/fbink.c#L2459-L2465), that's a new one ;).

I've never seen it happen *anywhere* else, and especially not on a Forma (a device with which I *have* encountered a few hangs over the years, but I've never had a running shell and/or USBNet at the time to investigate).

**Closed** 2021-03-15 04:48 UTC

**Comment by angerson** [comment] 2021-03-15 19:57
Awesome. I installed March 15th's nightly and confirmed that the new behavior is the same. I'm happy to do any extra testing in the future.

Also, as I *think* is now expected, I've seen a couple of crashes (with the bomb screen). One was yesterday when I tried to do a USB transfer, and one has happened twice today when I opened the "Update" menu. Here's the [crash.log](https://github.com/koreader/koreader/files/6144017/crash.log) that includes the first instance of that "Update" crash. I've been reading for at least four hours since yesterday and it hasn't crashed during reading. It doesn't happen consistently when I open up the Update menu, either.

```
03/15/21-12:32:53 DEBUG in pan state...
./luajit: frontend/ui/timeval.lua:116: Subtract the first timeval from the latest, not vice versa.
stack traceback:
	[C]: in function 'assert'
	frontend/ui/timeval.lua:116: in function 'pre_guard'
	frontend/dbg.lua:41: in function '__sub'
	frontend/device/gesturedetector.lua:596: in function <frontend/device/gesturedetector.lua:590>
	frontend/device/gesturedetector.lua:131: in function 'feedEvent'
	frontend/device/input.lua:499: in function 'waitEvent'
	frontend/ui/uimanager.lua:1422: in function 'handleInput'
	frontend/ui/uimanager.lua:1470: in function 'run'
	./reader.lua:322: in main chunk
	[C]: at 0x00014131
!!!!
Uh oh, something went awry... (Crash n°1: 03/15/21 @ 12:32:55)
Running FW 4.26.16704 on Linux 4.1.15-00416-gfc725f43860b (#99 SMP PREEMPT Mon Apr 6 14:55:22 CST 2020)
Attempting to restart KOReader . . .
!!!!
```

This is after swapping from 2021.02 stable to 2021.02 065 (March 15th's nightly) so it might be unrelated.

**Comment by NiLuJe** [comment] 2021-03-15 21:00
Right, that's a combination of the Nia clock drift fix and existing code that doesn't handle the clock going backwards, it's something I was aware could be an issue but was hoping would silently fail instead of hard crashing ;p.

I'll look into it, thanks ;).

**Comment by NiLuJe** [comment] 2021-03-15 21:22
Well, it's a debug guard, so it will silently fail without debug enabled ;p.

**Comment by gilali** [comment] 2021-03-16 22:39
https://user-images.githubusercontent.com/80790904/111388109-0cf95e00-86af-11eb-901d-ac4da8ba93ac.mp4


https://user-images.githubusercontent.com/80790904/111388115-0ec32180-86af-11eb-869c-fd36651fb916.mp4


https://user-images.githubusercontent.com/80790904/111388124-0ff44e80-86af-11eb-839f-0a04714ef0d2.mp4

Hello, here's my tests in video.
Epub samples can be downloaded here : https://filesamples.com/formats/epub
Sway.epub and sample1.epub : full text
Alices Adventures in Wonderland.epub : text with images

Only v2020.08 & v2020;08.1 are significant : Since v2020.08.01, the bug is present, and not before.
Only Alices Adventures in Wonderland.epub is significant because other files do the same in each release.
Speed is OK since v2020.08, not after
Sorry for the poor video quality. I'm not an artist like angerson :)
Thank you for your help

**Comment by NiLuJe** [comment] 2021-03-16 23:07
@gilali: 2021.02-42 is too old, it doesn't feature the workaround ;).

**Comment by gilali** [comment] 2021-03-17 13:57
I'm happy. My Libra works like a charm.
From now, all pages turns faster than a real book. You fix it so fast, it's amazing.
But it is above all unexpected: My own poor workaround was a downgrade while you, you fixed it for real. You are a warrior.
Thank you
