### ISSUE TITLE
Some background image colors are inverted in sRGB colorspace(?) PDFs

### ISSUE THREAD

**Issue by kindfulkirby** [koreader/koreader#5422] opened 2019-09-24 16:57 UTC
* KOReader version: v2019.09.3 from F-Droid
* Devices: Onyx Boox Nova Plus, Kindle Fire 7 (2015)

And, just to be sure it wasn't already fixed or Android exclusive, it's the same on

* KOReader version: v2019.09.3-33 built from git today
* Device: Ubuntu 18.04 on x86 PC

#### Steps to reproduce

Download `CB71012_Horse-lords_of_Rohan_PDF_version_sRGB.pdf` from here: https://www.drivethrurpg.com/product/174675/The-One-Ring--Horselords-of-Rohan  
(I haven't been able to find any sRGB colorspace PDFs that are freely available, how do you even search for that?)  
Open it in Koreader.

##### Screenshots (taken on PC)

What it should look like (same file in Firefox on the same PC)

![rohan_correct](https://user-images.githubusercontent.com/9869658/65531390-0c3c9d00-defa-11e9-8b95-1799a56aef9c.jpg)

What it looks like

![rohan_broken](https://user-images.githubusercontent.com/9869658/65531420-1bbbe600-defa-11e9-98ee-90e88d7e90c8.png)

**Note that the (non-image) text is still the correct color!**

*Most* of the internal pages look correct, but a few have their background image inverted, too, making them impossible to read and breaking reflow.

The non-sRGB version of the file works fine, but is significantly larger, which made me choose the sRGB version to begin with.

**Comment by NiLuJe** [comment] 2019-09-24 17:00
That's going to be hard to track down without a testcase.

because what does that even mean? Mostly everything should be sRGB. What were the other choices? CMYK?

**Comment by NiLuJe** [comment] 2019-09-24 17:02
Barring that, if you can pinpoint a few misbehaving images, I'd gladly take the output of [i]identify -verbose[/i] ;).

**Comment by NiLuJe** [comment] 2019-09-24 17:07
Might also be helpful to check how it renders w/ MuPDF, bot the latest version, and what we're using (1.13.0).

**Comment by kindfulkirby** [comment] 2019-09-24 17:55
> That's going to be hard to track down without a testcase (and knowing exactly how those images are encoded).
> 
> Because what does that even mean: mostly everything should be sRGB. What were the other choices? CMYK?

I wish I knew! All I know that DriveThruRPG offers two PDFs for download, one with `_srgb` appended to the filename.

> Barring that, if you can pinpoint a few misbehaving images, I'd gladly take the output of identify -verbose on those ;).



> Might also be helpful to check how it renders w/ MuPDF, both the latest version, and what we're using (1.13.0).

Huh. MuPDF 1.12.0 (which is what is installed on Ubuntu 18.04, if https://packages.ubuntu.com/bionic/mupdf is to be believed) fails to render the image *at all*.

![rohan_evenmorebroken](https://user-images.githubusercontent.com/9869658/65535978-c89a6100-df02-11e9-9c0f-154d8483eb6f.png)

It outputs

```
error: Cannot convert between incompatible pixmaps
warning: Ignoring error during interpretation
error: Cannot convert between incompatible pixmaps
warning: Ignoring error during interpretation
error: Cannot convert between incompatible pixmaps
warning: Ignoring error during interpretation
mupdf: warning: Errors found on page. Page rendering may be incomplete.
```

In 1.13.0 (built from source) it renders perfectly, though… :question:

**Comment by Frenzie** [comment] 2019-09-24 18:24
> In 1.13.0 (built from source) it renders perfectly, though…

Aw, I was hoping it was just an upstream issue fixed in 1.14, for example. ;-)

**Comment by kindfulkirby** [comment] 2019-09-24 18:38
Found a freely available PDF with that bug!

You can download a free sample from here: https://www.drivethrurpg.com/product/186813/The-One-Ring--Erebor--The-Lonely-Mountain

Sadly the full version of this is available *only* in the mystery `_sRGB` version :(

I guess I can give the latest muPDF a try!

**Comment by kindfulkirby** [comment] 2019-09-24 18:48
Does KOReader use OpenGL? Because I compiled MuPDF without, for reasons of laziness.

**Comment by Frenzie** [comment] 2019-09-24 18:56
SDL tends to use OpenGL, so in that sense the desktop build does. But I'd say KOReader probably doesn't use SDL in a sense relevant to what you're asking.

I only see the problem on some of the pages btw.

**Comment by kindfulkirby** [comment] 2019-09-24 18:57
> SDL tends to use OpenGL, so the desktop build does. But I'd say KOReader probably doesn't use SDL in a sense relevant to what you're asking.

Okay!

> I only see the problem on some of the pages btw.

Oh yeah, sorry if that wasn't clear in my original bug report. It doesn't affect *every* page!

**Comment by Frenzie** [comment] 2019-09-24 19:06
There seems to be an smask in there. Maybe it's related to the problem? I don't have Adobe Acrobat at home so I can't really properly investigate these PDFs easily — or perhaps I rather don't quite know the tools.

**Comment by NiLuJe** [comment] 2019-09-24 19:51
Which page(s) render inverted in that sample? (I don't have a color KOReader build on hand ;p).

**Comment by kindfulkirby** [comment] 2019-09-24 20:03
Pages 1, 2 & 9.

**Comment by kindfulkirby** [comment] 2019-09-24 20:04
And you don't need color to see the effect, pages 2 and 9 would be completely unreadable on e-ink ;)

**Comment by NiLuJe** [comment] 2019-09-24 20:21
Have you checked? The rendering codepath is essentially completely different, so it may or may not exhibit this behavior ;).

**Comment by NiLuJe** [comment] 2019-09-24 20:27
At a quick glance, I'm not seeing anything obvious in the way those JPEGs are encoded (pulled 'em via pdfimages, from poppler)..

**Comment by Frenzie** [comment] 2019-09-24 20:29
@NiLuJe Plus extracting the JPEGs with pdfimages works just fine. Almost certainly something related to the PDF (the smask being my primary suspicious candidate at a quick glance).

**Comment by NiLuJe** [comment] 2019-09-24 20:32
@Frenzie: Yep, that's what I just tried, no issues with the images standalone or in a CBZ (at least on eInk) ;).

**Comment by Frenzie** [comment] 2019-09-24 20:34
Right, I meant the extracted JPEGs render fine, not that extracting them does (though that does too). :-P

**Comment by kindfulkirby** [comment] 2019-09-24 21:12
> Have you checked? The rendering codepath is essentially completely different, so in theory, it may or may not exhibit this behavior ;).

Yes, that's how I found the bug in the first place :grin:

**Comment by kindfulkirby** [comment] 2019-09-25 12:37
Workaround: Rewrite the PDF file with ghostscript.

`gs  -sOutputFile=output.pdf  -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE  -dBATCH -dAutoRotatePages=/None input.pdf`

:warning:  **WARNING**: PostScript is a complete programming language, and (if what I read is true) ghostscript will execute whatever commands it is given! **It *could* install a trojan or delete your hard drive!**  
Do **not** run this on PDFs from an untrusted source! If you have to do so, use a virtual machine!

(There is command line option to run only "safe" postscript, but apparently malware authors have found ways around this.)

Slight tangent: If you *are* doing this, and you want to display the resulting file only on an eink device, you may as well convert it to grayscale and reduce the filesize a bit, by adding `-sColorConversionStrategy=Gray  -dProcessColorModel=/DeviceGray` to the ghostscript command line.

**Comment by Frenzie** [comment] 2019-09-25 17:39
As an aside, that command produces this interesting notice:
```
   **** This file had errors that were repaired or ignored.
   **** The file was produced by: 
   **** >>>> Adobe PDF Library 9.0 / PDF PT 3.10 (pdf-tools.com) / PDF PT 3.10 (pdf-tools.com) <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.

   **** The rendered output from this file may be incorrect.
```
Also it lost half its weight despite containing the same images and rendering the same? (Setting aside the issue in KOReader's MuPDF.) Is it just slimmed down in fonts or is something more… suspicious… missing? I'll have to check another time.

**Comment by kindfulkirby** [comment] 2019-09-25 19:23
That's only in the samples, not in the paid-for files! That must be caused by the watermark.

**Comment by Frenzie** [comment] 2019-09-25 21:20
Just the warning or also the filesize? The "sample file" overlay (or whatever it said precisely) doesn't disappear with the GS treatment.

**Comment by kindfulkirby** [comment] 2019-09-26 00:09
The warning, I didn't look at filesize too closely.

**Comment by Lordcorvin1** [comment] 2019-10-05 11:45
Do you have Night mode on? I have same bug on Android when viewing pdf. Turning it off fixes the inverted colors

**Comment by kindfulkirby** [comment] 2019-10-14 10:02
No, I do not have Night Mode on.

The problem is that the colors of the background are inverted, but those of the text are not, meaning that the contrast between them is minimal, making the pages unreadable. Night mode inverts both, offering no solution.

**Comment by Frenzie** [comment] 2020-12-19 18:58
Fixed in #1203.

![Screenshot_2020-12-19_19-57-28](https://user-images.githubusercontent.com/202757/102697228-84485e80-4234-11eb-9fa6-2ac7f039965b.png)

**Comment by everdred** [comment] 2022-03-04 16:45
I have an unfortunately not-freely-available PDF that reproduces this issue in 2022.02. Any way I can use this to help?

**Comment by Frenzie** [comment] 2022-03-04 17:46
Thanks, but nothing further is needed. ^_^ The file I linked in https://github.com/koreader/koreader/issues/5422#issuecomment-748511842 suffices to reproduce the issue.

**Comment by rupaschomaker** [comment] 2023-05-19 13:22
I have a PDf that is showing this behavior on a Kobo Sage.    #6738 seems to be all about font handling, but I guess if mupdf is updated this will be fixed?

**Comment by Frenzie** [comment] 2023-05-19 14:04
Yes, it will come eventually.

**Comment by crash5** [comment] 2024-01-13 09:45
hi, any progress on this negative image thingy? :)

**Comment by Frenzie** [comment] 2024-01-13 13:44
Sort of. More pieces are ready than before.

**Comment by trentfisher** [comment] 2024-01-18 15:07
FYI, I am having this same problem on a Lenovo M10 android tablet.  What's interesting is that *some* pdfs from [LevelUp5e](https://enpublishingrpg.com/collections/level-up-advanced-5th-edition-a5e) show this image inversion, but others do not.  Specifically Monstrous Menagerie and Memories of Holdenshire are inverted, but the Adventurer's Guide and Trials and Treasures look fine.  I will check if the samples on DriveThruRpg have the same issues.

Is there anything I can look at in these files which might identify what is different between them cause this?

**Comment by Frenzie** [comment] 2024-01-18 15:56
Feel free to investigate, but it'll be fixed eventually (I know, I know, it's taking its sweet time) and a workaround is posted in <https://github.com/koreader/koreader/issues/5422#issuecomment-535001540>. So I'd try to make sure your motivation is primarily curiosity. Of course it's possible the fix is fairly simple to write or backport, in which case you're absolutely welcome to. ^_^

**Closed** 2024-06-01 11:22 UTC
Labels: bug, Upstream, MµPDF
