### ISSUE TITLE
"Status bar" covers text when viewing HTML files

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3556] opened 2017-12-22 13:12 UTC
* KOReader version: 2015-11-1411
* Device: Inkbook Prime (Android)

#### Issue
"Status bar" covers bottom text when viewing HTML files. PDF seems to be ok.

#### Steps to reproduce
Open Html file in koreader, enable status bar "all at once" it covers bottom text.

**Comment by Frenzie** [comment] 2018-01-17 19:49
Does this only occur in scroll mode or also paged? There doesn't tend to be any reason to use it in EPUB or HTML. Anyway, I can only reproduce it in scroll mode.

**Comment by mwoz123** [comment] 2018-01-17 20:09
yes, it seems it a bug only in "scroll mode". I didn't spot that previously.

**Comment by robert00s** [comment] 2018-01-17 20:57
I think that crengine doesn't respect top and bottom margin in scroll mode.

**Comment by Frenzie** [comment] 2018-01-18 08:59
I'm sure it does, but only per element. If scroll mode had pages it wouldn't be scroll mode. :-P

I imagine the problem is that we're giving crengine the whole screen to play with and then paint on top of it.

A fix might be as simple as passing the result of `Screen:getHeight() - statusbar_height` when it's enabled:

https://github.com/koreader/koreader/blob/775b7a364f4b0a1b82fc236d4aaa6513922f9904/frontend/document/credocument.lua#L99

You could still end up with a line that's divided somewhat awkwardly, but hey, that's when you scroll and it probably can't be avoided. It's just that right now you have some lines that can disappear completely.

**Comment by poire-z** [comment] 2018-07-05 14:04
Must have been fixed by #3870

**Closed by poire-z** 2018-07-05 14:04 UTC
Labels: UX, bug
