### ISSUE TITLE
sqlite crash on "Clear readers' caches" (can't repeat again)

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#5563] opened 2019-11-02 08:38 UTC
* KOReader version: v.2019.10
* Device: kobo clara hd

#### Issue
after OTA update I got v.2019.10, restarted koreader, got my settings reset / cleared / wiped, found myself in the file browser and started to explore menu items in the new version; I found "clear caches" and clicked it; koreader crashed with the image of the bomb and tail of crash log on the screen

#### Steps to reproduce
1) go to file explorer
2) top menu > 3rd menu item (wrench + screwdriver) > Developer options > Clear readers' caches
3) sqlite error with time bomb screen :)

##### `crash.log` (if applicable)
```
11/01/19-22:36:04 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
11/01/19-22:36:04 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
11/01/19-22:36:04 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
11/01/19-22:36:04 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
./luajit: common/lua-ljsqlite3/init.lua:28: ljsqlite3[busy] unable to close due to unfinalized statements or unfinished backups
stack traceback:
	[C]: in function 'error'
	common/lua-ljsqlite3/init.lua:28: in function 'err'
	common/lua-ljsqlite3/init.lua:198: in function 'E_conn'
	common/lua-ljsqlite3/init.lua:204: in function 'T_okcode'
	common/lua-ljsqlite3/init.lua:322: in function 'close'
	plugins/coverbrowser.koplugin/bookinfomanager.lua:184: in function 'closeDbConnection'
	plugins/coverbrowser.koplugin/bookinfomanager.lua:208: in function 'compactDb'
	plugins/coverbrowser.koplugin/main.lua:395: in function 'action'
	frontend/ui/uimanager.lua:752: in function '_checkTasks'
	frontend/ui/uimanager.lua:1035: in function 'handleInput'
	frontend/ui/uimanager.lua:1121: in function 'run'
	./reader.lua:260: in main chunk
	[C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash n°1: 11/01/19 @ 22:36:18)
Running FW 4.18.13737 on Linux 4.1.15-00084-gcd0d3a4 (#29 SMP PREEMPT Wed Nov 21 11:31:06 CST 2018)
Attempting to restart KOReader . . .
```

**Comment by poire-z** [comment] 2019-11-02 08:55
> plugins/coverbrowser.koplugin/bookinfomanager.lua:208: in function 'compactDb'

Well, that compactDb() function call that appears in your stack trace can only happen if you hit `Book info cache management > Compact cache database` - so your "steps to reproduce" and the info you gave might not be accurate :| Do you remember doing that?

Also noted as comment there:
https://github.com/koreader/koreader/blob/4462380048fb92788a017829e372b6f570038172/plugins/coverbrowser.koplugin/bookinfomanager.lua#L195-L208

So, may be if you have a large number of books and a big `koreader/settings/bookinfo_cache.sqlite3` (do you?), this can happen (but it should crash, may be leave you with this sqlite db screwed up - but it shouldn't screw your settings.reader.lua / .old)

**Comment by carmelocotonto** [comment] 2019-11-02 11:20
Hi, around this question, How can I compact databases sqlite3?. Is it good doing it?. My database is 20Mb

**Comment by poire-z** [comment] 2019-11-02 11:40
For the Cover/metadata cache db, `File browser > Display mode > Book info cache management > Compact cache database `.
(If your question is about general sqlite dbs, it's just one command to give it: VACUUM.)

> Is it good doing it?. 

It shouldn't hurt doing it, but it's not really needed unless your remove a lot of books and you want your 20Mb db to get smaller. Otherwise, empty space would be re-used as you add books, and your 20Mb db would stay 20Mb for a lot of time, until you get more books than you had before that big removal.
So, if you do it (you can) when you haven't removed a lot of books, you'll see a message at the end with the previous and current size, and there shouldn't be much difference and space gained.
Some more details in https://github.com/koreader/koreader/issues/3451#issuecomment-342158661

(The other sqlite db we use is the statistics plugin, and I don't think it ever gets data deleted, so it can only keep growing.)

**Comment by poire-z** [comment] 2020-01-01 21:05
Corrupted/empty settings on crash/freeze should hopefully no more happen - and losing settings and annotations should now be limited to losing 15mn of annotations & page progress (that one can reduce to 5mn via the menu), thanks to #5678 and #5687, available in next nightly.
So, closing. Re-open if that happens again.

**Closed by poire-z** 2020-01-01 21:05 UTC

**Comment by poire-z** [comment] 2020-08-28 17:42
Got twice this crash today on the emulator while changing some CoverBrowser settings (nb of items, display mode), sometimes when doing stuff, sometimes on koreader quit.
Can't reproduce it when I want to :)
Last one I got was also in 
```
"ljsqlite3[busy] unable to close due to unfinalized statements or unfinished backups"
[...]
	plugins/coverbrowser.koplugin/bookinfomanager.lua:186: in function 'closeDbConnection'
```
and googling that message gave me one result: this issue :)

Here's some bit about that in sqlite3.c:
```
/*
** Two variations on the public interface for closing a database
** connection. The sqlite3_close() version returns SQLITE_BUSY and
** leaves the connection option if there are unfinalized prepared
** statements or unfinished sqlite3_backups.  The sqlite3_close_v2()
** version forces the connection to become a zombie if there are
** unclosed resources, and arranges for deallocation when the last
** prepare statement or sqlite3_backup closes.
*/
SQLITE_API int sqlite3_close(sqlite3 *db){ return sqlite3Close(db,0); }
SQLITE_API int sqlite3_close_v2(sqlite3 *db){ return sqlite3Close(db,1); }
```
lua-ljsqlite3 only uses/provides the first version.

May be just wrapping `self.db_conn:close()` in a pcall() is enough (and dunno, trying 3 times after sleeping 1s - or even not, it would be retried by __gc() ) ?

**Comment by poire-z** [comment] 2020-08-28 17:56
Or just patch  lua-ljsqlite3 (we have it in tree, not from a repo):
```diff
--- a/thirdparty/lua-ljsqlite3/init.lua
+++ b/thirdparty/lua-ljsqlite3/init.lua
@@ -94,2 +94,3 @@ int sqlite3_open_v2(const char *filename, sqlite3 **ppDb, int flags,
 int sqlite3_close(sqlite3*);
+int sqlite3_close_v2(sqlite3*);
 int sqlite3_busy_timeout(sqlite3*, int ms);
@@ -320,3 +321,3 @@ function conn_mt:close() T_open(self)
   for _,v in pairs(conncb[self].final)  do v:free() end
-  local code = sql.sqlite3_close(self._ptr)
+  local code = sql.sqlite3_close_v2(self._ptr)
   T_okcode(self._ptr, code)
```
So we leave handling the closing and zombies to sqlite.

**Comment by NiLuJe** [comment] 2020-08-28 20:07
Quoting https://sqlite.org/c3ref/close.html:

> The sqlite3_close_v2() interface is intended for use with host languages that are garbage collected, and where the order in which destructors are called is arbitrary.

So, yeah, +1 ;).
