### ISSUE TITLE
Fragmented Arabic text in dictionary

### ISSUE THREAD

**Issue by roaminghawk** [koreader/koreader#9475] opened 2022-09-04 22:29 UTC
* KOReader version: 2022.08
* * Device: Boyue T62D with a custom firmware from the Onyx magicbook and on Android 12.

There is a bug introduced in version 2022.08 that was not there in earlier versions.
Arabic letters are connected together to make words, with the new bug the letters are fragmented and not joined together.

Correct translation:
![2022 07](https://user-images.githubusercontent.com/24497065/188335777-5d272857-de10-454d-90be-a39d7e8785e7.jpg)

Fragmented translation:
![2022 08](https://user-images.githubusercontent.com/24497065/188335780-daf75a35-90ed-46da-a761-53e911a387b8.jpg)

Affected dictionary:
[dict.zip](https://github.com/koreader/koreader/files/9485607/dict.zip)

I tried to change the fallback font, but it seems the bug is not dependent on the font.

**Comment by poire-z** [comment] 2022-09-05 00:00
This is an HTML dictionary, and I get the same ugly stuff with another HTML arabic dict.
Arabic text dicts and Wikipedia arabic are ok.
Nothing has changed on the frontend dictionary side between v2022.07 and v2022.08.
So, I guess it's base. MuPDF hasn't changed (except for adding webp images support).
The only possibly related thing I see is the upgrade of Harfbuzz (used for text shaping, so involved with rendering Arabic) from v3.0.0 to v5.1.0 - and may be our old MuPDF not coping with some changes in Harfbuzz :/
Would need some investigation on how/where MuPDF uses Harfbuzz, and see if that's the culprit.
And first a test with rollbacking HB to 3.0.0 to be sure it's really this the problem.
(I won't be able to investigate anything in the coming week.)

**Comment by poire-z** [comment] 2022-09-09 23:02
Ok, so the culprit is really the harfbuzz version, but also FreeSerif.
FreeSerif hasn't been updated since 2012 - and it used to work fine with harfbuzz 3.0.0.
But with Harfbuzz 5.1.0, FreeSerif renders badly, also with crengine:
![image](https://user-images.githubusercontent.com/24273478/189455638-25c79bb0-47ef-45e1-837a-d4387fd4abc3.png)

The HB people seems to disregard FreeSerif in past issues, closing with "font bug".
And there's been some fixes/enhancements in harfbuzz to arabic shaping since v3.0.0 - which must have broken FreeSerif, or using some bad opentype stuff in FreeSerif it wasn't using before.

I can somehow make it look better by disabling an opentype feature "required ligatures" with `-rlig`, which would give this:
![image](https://user-images.githubusercontent.com/24273478/189455917-f1298901-cab5-4154-826b-62598ae60cb4.png)

There is a little visual change I noticed, in yellow, vs what we had before:
![image](https://user-images.githubusercontent.com/24273478/189455986-a6ca169d-eca0-43ac-8975-8aaef427169b.png)

I don't read Arabic, so I don't know which is best (green I guess), and if the yellow is bearable.
@roaminghawk ? @zeyadas ?

We can't just switch to another font - with mupdf, we have the main font, then ONE fallback font (used for NotoSansCJK and Chinese), and ONE symbol font (where we put FreeSerif, for arabic, hebrew...)

**Comment by NiLuJe** [comment] 2022-09-10 00:05
@poire-z: I *can* actually update our Free* build from SVN, I hadn't noticed it had been this long ;).

(And, IIRC, at the time, they may have been fiddling with Arabic scripts...).

**Comment by poire-z** [comment] 2022-09-10 00:27
Why not.
It's really hard to know what happens on their front. I found nothing but the 2012 version - had to stuggle with their svn web site to get to the log to see what has been improved (I think they got it right with the "help not wanted" idea :)

What I see possibly related since your r4257:
r4261: Arabic: incorrect ligatures of mark shadda with mark kasra which should have been fatha.  Also similar cases fixed.
r4259: Arabic: improved connectors on a couple of combining forms.

**Comment by poire-z** [comment] 2022-09-10 00:31
Nope, your latest one didn't help (but is not worse, so go with the update :).

**Comment by poire-z** [comment] 2022-09-10 07:54
Instead of going forward in history, I tried going backward (because at a certain age, you know "it was better before" :).

https://github.com/koreader/koreader-fonts/commits/master/freefont

accfd84 from Mar 21, 2019 (1 787 596 bytes) [Regenerate FreeFont manually](https://github.com/koreader/koreader-fonts/commit/accfd84624b9bff35662b90ec5cd74fb00dc7f7e) works fine I think:
![image](https://user-images.githubusercontent.com/24273478/189474256-fede943a-7c63-4d57-a7ad-acfbd340b9eb.png)

c966858 from Aug 14, 2019 (1 662 032 bytes) [Update FreeFont r3997, built manually (Force Encoding > Unicode Full)](https://github.com/koreader/koreader-fonts/commit/c966858a016ce75b3b8d98c502d76c070c8806ae) begins to exhibit bad stuff (so do random picks from later commits):
![image](https://user-images.githubusercontent.com/24273478/189474439-a6b12ec0-75c9-4618-a4ca-a51ea05fe889.png)

I don't know if it's something upstream between rXXXX and r3997, or if it's your "built manually" process that changed in between, and may have missed something.

**Comment by NiLuJe** [comment] 2022-09-10 15:34
The build process should essentially be the same, I simply do what the build scropt does manually, skipping the autohinting.

**Comment by NiLuJe** [comment] 2022-09-10 15:35
The issue with going backwards is we might see some regression in missing glyphs, or maths-specific stuff, as there was a lot of work on that front, IIRC.

**Comment by poire-z** [comment] 2022-09-10 16:19
Can you remember/guess the revision you used for "accfd84 from Mar 21, 2019" ? So I can see what happened between these two.

**Comment by NiLuJe** [comment] 2022-09-10 16:54
Whatever was the tip of the trunk at that time, so probably circa r3988:

```
r3989 | Stevan_White | 2019-04-01 13:46:41 +0200 (Mon, 01 Apr 2019) | 3 lines

punctuation: improved positioning of hyphen and dashes.
	bug #56046: Sidebearing or kernig of hyphens.

------------------------------------------------------------------------
r3988 | Stevan_White | 2018-12-23 14:00:48 +0100 (Sun, 23 Dec 2018) | 2 lines

Latin, Greek: addition and adjustment of many positioning anchors.
```

**Comment by poire-z** [comment] 2022-09-10 18:11
I see nothing related in the commit messages from https://svn.savannah.gnu.org/viewvc/freefont?view=revision&revision=3997 back to 3988.
Also nothing related when inspecting the diffs between 3990, 3991, 3992, 3993, 3996 (no change to FreeSerif.sfd in other revs). Mostly some changes relative to "deva", indic stuff.
Also nothing when comparing directly FreeSerif3988.sfd against FreeSerif3997.sfd.

Can you try rebuilding r3988 with your current script?
From the diff I've seen I see nothing that amount for the 125KB loss between your 2 builds (1 787 596 bytes => 1 662 032 bytes) - so, may be some tables were lost ? :)

**Comment by roaminghawk** [comment] 2022-09-11 00:29
> I don't read Arabic, so I don't know which is best (green I guess), and if the yellow is bearable. @roaminghawk ? @Zeyadas ?
> 
> We can't just switch to another font - with mupdf, we have the main font, then ONE fallback font (used for NotoSansCJK and Chinese), and ONE symbol font (where we put FreeSerif, for arabic, hebrew...)

The green one is the correct one, but the yellow is bearable too. But if it's only for a dictionary. If an Arabic epub or an html you had that character all over the page it will be a little less bearable, but still bearable nonetheless.

**Comment by NiLuJe** [comment] 2022-09-11 05:51
I vaguely remember build scripts changes at one point, now that I think about it. Although I never really used the vanilla ones, because they attempted to use a truly horrendously old font forge version because of a... ligature issue (I think). I'll double-check all that, because I definitely always used fontforge master, as I've been running snapshots forever. And I vaguely recall checking that the actual bug had been fixed, and ff just hadn't tagged a release.

**Comment by poire-z** [comment] 2022-09-11 07:57
Looked again, and it seems it lost a few features (which I haven't seen removed en masse like that when I looked at the diffs):
```
$ otfinfo -i FreeSerifOlder.ttf
Version:             Version $Revision: 3988 $

$ otfinfo -i FreeSerifNewer.ttf.ttf
Version:             Version $Revision: 3996 $

$ otfinfo -f FreeSerifOlder.ttf
aalt    Access All Alternates
afrc    Alternative Fractions
c2sc    Small Capitals From Capitals
ccmp    Glyph Composition/Decomposition
cv01    Character Variants 1
cv02    Character Variants 2
cv03    Character Variants 3
cv04    Character Variants 4
dlig    Discretionary Ligatures
frac    Fractions
hist    Historical Forms
hlig    Historical Ligatures
kern    Kerning
liga    Standard Ligatures
lnum    Lining Figures
locl    Localized Forms
mark    Mark Positioning
mkmk    Mark to Mark Positioning
onum    Oldstyle Figures
ordn    Ordinals
pnum    Proportional Figures
rlig    Required Ligatures
sinf    Scientific Inferiors
smcp    Small Capitals
ss10    Stylistic Set 10
ss11    Stylistic Set 11
ss12    Stylistic Set 12
ss13    Stylistic Set 13
ss14    Stylistic Set 14
ss15    Stylistic Set 15
subs    Subscript
sups    Superscript
tnum    Tabular Figures
zero    Slashed Zero

$ otfinfo -f FreeSerifNewer.ttf
aalt    Access All Alternates
afrc    Alternative Fractions
c2sc    Small Capitals From Capitals
ccmp    Glyph Composition/Decomposition
cv03    Character Variants 3
dlig    Discretionary Ligatures
frac    Fractions
hist    Historical Forms
hlig    Historical Ligatures
kern    Kerning
liga    Standard Ligatures
lnum    Lining Figures
locl    Localized Forms
mark    Mark Positioning
mkmk    Mark to Mark Positioning
ordn    Ordinals
sinf    Scientific Inferiors
smcp    Small Capitals
subs    Subscript
sups    Superscript
tnum    Tabular Figures

$ otfinfo -t FreeSerifOlder.ttf
    284 BASE
1455433 CFF
     28 FFTM
   3720 GDEF
 161648 GPOS
  92044 GSUB
   8590 MATH
     96 OS/2
   7166 cmap
     54 head
     36 hhea
  52892 hmtx
      6 maxp
   5302 name
     32 post

$ otfinfo -t FreeSerifNewer.ttf
    284 BASE
1413830 CFF
     28 FFTM
   3016 GDEF
 151280 GPOS a bit smaller
  15590 GSUB quite smaller
   7804 MATH
     96 OS/2
  11506 cmap grew a bit
     54 head
     36 hhea
  52902 hmtx
      6 maxp
   5302 name
     32 post


```
Got the same smaller set with current `Version $Revision: 4257 $` and your recent `4273`.

**Comment by NiLuJe** [comment] 2022-09-11 16:07
Okay, somehow using the Makefile generates something different, so, wheee, magic!

**Comment by NiLuJe** [comment] 2022-09-11 16:11
Updated the builds in the koreader-fonts, they have the tables (most notable rlig, I imagine), so hopefully that should do it?

**Comment by poire-z** [comment] 2022-09-11 16:18
Yep, my cre sample and HTML dicts arabic results look fine again ! Thanks :)

**Closed** 2022-09-11 17:08 UTC
Labels: bug, MµPDF
