### ISSUE TITLE
A page from a pdf replaces some pages of other pdfs.

### ISSUE THREAD

**Issue by noobkouser** [koreader/koreader#6075] opened 2020-04-20 15:29 UTC
* KOReader version: v2020.04
* Device: Kobo_frost

#### Issue
When I open a pdf book, the device puts a page from another pdf among the pages of the book I am reading. This same page is replacing most of the pages of other pdf files. I don't encounter this problem in the default kobo system. 

#### Steps to reproduce
1. Open a pdf file, highlight, bookmark, make annotations. Close it.
2. Open another pdf file. Here you can see the pages are replaced.

#### `crash.log` (if applicable)
There is no crash log.
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by poire-z** [comment] 2020-04-20 15:53
Duplicate of #6070. Try upgrading to 2020.04.1

**Closed** 2020-05-04 11:44 UTC
Labels: bug, duplicate, out-of-date
