### ISSUE TITLE
No permissions requested by the app

### ISSUE THREAD

**Issue by leanhtai01** [koreader/koreader#8956] opened 2022-03-30 09:53 UTC
* KOReader version: 2022.03.1
* Device: Smartphone OPPO A95 - Model: CPH2365 - Android Version 11 CPH2365_11_A.09

#### Issue
No permissions requested by the app, so can not access any files

#### Steps to reproduce
1. Install KOReader
2. Open KOReader for the first time
3. KOReader ask for permission to manage files
4. Allow the permission
5. Switch back to KOReader (tried close and re-open too)
6. Can't access any files
7. Open "App info"
8. In Permissions section, it's show "No permission requested" (so can not modify any permissions)

#### Screenshot
![Screenshot_2022-03-30-16-35-27-73_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/49838853/160804364-35ac6c6e-acce-43f1-8b6c-59cdd6cbc716.jpg)

**Comment by Frenzie** [comment] 2022-03-30 14:19
If you're talking about the SD card that would be a duplicate of #8789, https://github.com/koreader/koreader/issues/4872, https://github.com/koreader/koreader/issues/5784. That can't be fixed.

**Comment by leanhtai01** [comment] 2022-03-30 14:21
@Frenzie No, I don't have any SD in my phone, just only internal storage.

**Comment by pazos** [comment] 2022-03-30 17:43
@leanhtai01: there's no problem or least not the one you're thinking about. You don't need to believe me, you can try yourself:

1. Uninstall the app.
2. Install the app.
3. Open the app.
4. After the "Please allow the app to manage all files dialog" **do not** grant that permission, just return back.
5. Repeat **3** and **4** the times you need until you're sure.

The app won't start **AT ALL** until it has granted the `MANAGE_ALL_FILES` permission.

**Closed** 2022-03-31 04:32 UTC
Labels: invalid, Android
