### ISSUE TITLE
KOReader loses position when I close it

### ISSUE THREAD

**Issue by beelzebielsk** [koreader/koreader#8013] opened 2021-07-23 01:02 UTC
* KOReader version: 2021.07
* Device: Onyx Boox Poke 2 (Android 9)

#### Issue

When I close KOReader while a book is open, things aren't saved. My position in the book, annotations I made, new bookmarks. I'm reading an EPUB if that helps. This is recent, maybe as of June. It was working fine before.

#### Steps to reproduce

- Open KOReader
- Open a book
- Do something (go to the next page, or make an note or new bookmark)
- Close KOReader through some outside means, like recent tasks view in Android, or restarting the device.
- Open KOReader again, choose the same book
- Note that whatever you did is gone

**Comment by beelzebielsk** [comment] 2021-07-23 02:09
Also, is it possible to downgrade KOReader w/o losing my notes and annotations? I tried to install an apk of an earlier version, that failed. I'm assuming now I'd have to uninstall KOReader and reinstall the earlier version. Will my annotations and things still be there? If not, is there a way to export and re-import them into KOReader?

**Comment by Frenzie** [comment] 2021-07-23 06:13
> Also, is it possible to downgrade KOReader w/o losing my notes and annotations?

Sometimes. Or rather, usually, but don't count on it.

They're in the .sdr folder created next to the file.

**Comment by beelzebielsk** [comment] 2021-07-23 18:16
@Frenzie Alright, thanks. I was worried that uninstalling might delete `.sdr` files, it doens't. So I was able to just uninstall my current version of KOReader and install an earlier version w/o the problem. 

For anyone who works on this, I'm using v2021.05 right now, which is saving my book progress correctly.

**Comment by poire-z** [comment] 2021-07-23 18:29
Probably a duplicate of #7724.

**Comment by Frenzie** [comment] 2021-07-23 19:33
> Alright, thanks. I was worried that uninstalling might delete .sdr files, it doens't.

That won't happen, but if upgraded to a newer version they could be incompatible.

**Comment by beelzebielsk** [comment] 2021-07-25 17:02
Just in case this helps, the bug in this issue seems to be a regression. Saving happens correctly in the 2021.04 version on my device. 2021.05 hangs a lot on my device, so I can't say whether it happens there or not. 2021.06 and 07 don't save the information.

**Comment by Fausto0609** [comment] 2021-08-11 05:39
I'm on Likebook Mars (Android 6) and 2021.07 gives me the same error

**Comment by mergen3107** [comment] 2021-08-11 21:32
If you close KOReader with KOReader’s Exit, does it save properly? If it does, then you should probably put a swipe/tap shortcut to close KOReader when you need, instead of force closing it. 

I have the same issue on Onyx Boox Kon-Tiki2. It is related to the fact that the Task Manager is implemented poorly by OEMs.

**Comment by beelzebielsk** [comment] 2021-08-11 22:00
@mergen3107 Yes, KOReader does save the book information correctly if I use its exit function (or just close the book and go to select a new one). I'd rather stay on v2021.04 and wait for a fix than use the gesture feedback.

**Comment by pazos** [comment] 2021-08-11 23:13
Duplicate of #7724

**Closed by pazos** 2021-08-11 23:13 UTC
Labels: bug, Android
