### ISSUE TITLE
Crashes on pdf reflow

### ISSUE THREAD

**Issue by amitbha** [koreader/koreader#9272] opened 2022-07-01 02:54 UTC
* KOReader version: 2022.06
* Device: Xiaomi Mi 9 SE

#### Issue
crash when operate with pdf reflow mode on

#### Steps to reproduce
1. open the pdf file
2. turn on `page reflow` and choose `Chinese language`
3. resize font to `1.3`
4. long tap the screen
5. ko crash

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/9024709/crash.log)
[test.pdf](https://github.com/koreader/koreader/files/9024716/test.pdf)

**Comment by poire-z** [comment] 2022-07-01 06:25
Probably similar to/duplicate of #4481.

**Closed** 2024-04-27 22:01 UTC
