### ISSUE TITLE
Wifi connection to Calibre times out after about 8 minutes

### ISSUE THREAD

**Issue by pdo-smith** [koreader/koreader#1530] opened 2015-05-19 16:38 UTC
The wifi connection between my Kobo Glo and Calibre times out after about eight minutes of inactivity.
But my netbook maintains the connection indefinitely.

I am using Ubuntu 1014 on a desktop PC where I run hostapd to use the PC as a wifi hotspot. This allows me to push books from Calibre to my Kobo Glo, wirelessly. That works really well, thanks guys. I also have a Windows 7 netbook communicating through the same wifi hotspot on my desktop PC.

The Kobo Glo loses its connection after about 8 minutes while the netbook maintains its connection indefinitely.

The following messages are in the syslog:

***Set up the link:
May 19 17:06:11 Viki hostapd: wlan0: STA 00:90:a2:d4:5f:56 RADIUS: starting accounting session 555B0B58-00000007
May 19 17:06:11 Viki hostapd: wlan0: STA 00:90:a2:d4:5f:56 WPA: pairwise key handshake completed (RSN)
May 19 17:06:18 Viki dnsmasq-dhcp[3211]: DHCPDISCOVER(wlan0) 00:90:a2:d4:5f:56 
May 19 17:06:18 Viki dnsmasq-dhcp[3211]: DHCPOFFER(wlan0) 192.168.12.133 00:90:a2:d4:5f:56 
May 19 17:06:18 Viki dnsmasq-dhcp[3211]: DHCPREQUEST(wlan0) 192.168.12.133 00:90:a2:d4:5f:56 
May 19 17:06:18 Viki dnsmasq-dhcp[3211]: DHCPACK(wlan0) 192.168.12.133 00:90:a2:d4:5f:56 

***Lose the link:
May 19 17:13:41 Viki hostapd: wlan0: STA 00:90:a2:d4:5f:56 IEEE 802.11: disassociated due to inactivity
May 19 17:13:42 Viki hostapd: wlan0: STA 00:90:a2:d4:5f:56 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)

I can recover by selecting 'Network | Wifi connection'
and then 'Calibre wireless connection | Connect'
after which it works again.

Questions:
1. Should it time out?
2. Alternatively, is there a setting problem?

It does seem to be a very short timeout interval.
(I'm using koreader-nightly-20150517)

**Comment by pdo-smith** [comment] 2015-05-19 18:51
Problem seems to be solved.
From hostapd config file:

# Station inactivity limit
#
# If a station does not send anything in ap_max_inactivity seconds, an
# empty data frame is sent to it in order to verify whether it is
# still in range. If this frame is not ACKed, the station will be
# disassociated and then deauthenticated. This feature is used to
# clear station table of old entries when the STAs move out of the
# range.
#
# The station can associate again with the AP if it is still in range;
# this inactivity poll is just used as a nicer way of verifying
# inactivity; i.e., client will not report broken connection because
# disassociation frame is not sent immediately without first polling
# the STA with a data frame.
# default: 300 (i.e., 5 minutes)
#ap_max_inactivity=300

I set ap_max_inactivity=3000 so that it only times out after 50 minutes, a much more reasonable time for my needs(writing, editing and testing epubs).

What seems to be happening is that once the Kobo goes into 'suspend' mode it stops replying to ACK requests from hostapd. When that happens it times out after ap_max_inactivity seconds.

**Comment by chrox** [comment] 2015-05-19 23:34
Interesting find. I'm closing this issue since the problem is solved.

**Closed by chrox** 2015-05-19 23:34 UTC
