### ISSUE TITLE
When switching away from Koreader and back to it on Amazon fire Android tablets status bar is obscured

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5462] opened 2019-10-08 18:21 UTC
Versión 2019.09.03

Steps 
Open Koreader
Use app switcher to switch away to another app (yes I know I should be a more focused reader )
Switch back
Status bar is obscured 

Images https://photos.app.goo.gl/YFfGEWHi7aQ945Zz8

**Comment by Frenzie** [comment] 2019-10-08 18:46
Thus far I've only been aware of the opposite problem. I'm not sure if it's still an issue, but on some versions of Android you get that effect on start and you need to switch back and forth to get rid of it. Getting it after switching is a new one. :-P

**Comment by pazos** [comment] 2019-10-08 20:48
> Use app switcher to switch away to another app (yes I know I should be a more focused reader )

@arooni: A more focused reader I don't know, but please focus or bug reports :smile: . Is this a duplicate of #4996 ?

In that case I will close this issue and reopen the old one as it has more useful info. Keep in mind that it seem to be an issue only affecting *some* borked Lollipop devices and it **cannot** be reproduced anywhere, so you need to test changes and stay on topic, so we hopefully can fix it instead of labeling "won't fix"

**Comment by pazos** [comment] 2019-10-12 18:23
pinging @arooni: are you still interested on this?

**Comment by arooni** [comment] 2019-10-12 22:18
@pazos 

Definitely I'm still intereted.  I read on the tablet during most meals.   Great point about that previous issue that I had forgotten I had opened. 

Just a question on etiquette, when you said in that original issue "open it if you can repro on latest stable".. I'm unable to see where in the UI I can re-open a bug.  I thought that's something only one of the project maintainers could do.

**Comment by Frenzie** [comment] 2019-10-12 22:20
In that case you could just add a reply and ask to reopen. ;-) Replying is not blocked, is it?

**Comment by arooni** [comment] 2019-10-12 22:26
Certainly not, just didn't know what the right protocol was :)

may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - davidparkinson.com <https://www.davidparkinson.com/>
twitter - @followdavid <https://twitter.com/followdavid>

**Comment by Frenzie** [comment] 2019-10-12 22:54
Opening a new issue is almost never wrong, provided it brings something new to the table. It's just that if you happen to know there's an old issue, you should at the very least mention it to save people time and effort.

**Comment by pazos** [comment] 2019-10-13 00:15
> Just a question on etiquette, when you said in that original issue "open it if you can repro on latest stable".. I'm unable to see where in the UI I can re-open a bug. I thought that's something only one of the project maintainers could do.

Sorry, I meant comment or ping me.

I will build a couple of apks for you to test. Probably we want to use legacy code on Lollipop and avoid visibility change tricks. Lets move conversation to #4996

**Closed by pazos** 2019-10-13 00:15 UTC
Labels: Android, firmware, need more info
