### ISSUE TITLE
Cannot choose among registered wifi networks

### ISSUE THREAD

**Issue by khariche** [koreader/koreader#6010] opened 2020-03-28 17:32 UTC
* KOReader version: 2020.03.2
* Device:Cervantes4

#### Issue
I cannot choose among available and registered wifi networks.
#### Steps to reproduce
I have two wifi networks at home. I cannot get the popup window for choosing which I want to connect to. Instead, when clicking on "Wi-Fi connection", Koreader chooses automatically.

**Comment by pazos** [comment] 2020-03-28 19:05
Yeah, it is actually a feature, not a bug. It was introduced in #4462

You can change that behaviour replacing
https://github.com/koreader/koreader/blob/4a5a2eb7084d9a6aba32eaf7258f1049a7d4aca3/frontend/device/cervantes/device.lua#L236

with `self:showNetworkMenu(complete_callback)`

**Comment by pazos** [comment] 2020-03-28 19:10
Current behaviour is actually cool, unless you registered just one of your two APs. In that case please do log to the other one. If both APs are actually saved then it is fine as it will connect based on signal.

**Comment by khariche** [comment] 2020-03-28 22:39
OK, thanks! By the way, is there any way to decide whether wifi stays on or not while suspended?

**Comment by pazos** [comment] 2020-03-29 00:00
> Is there any way to decide whether wifi stays on or not while suspended?

Nope, this is not android. While the device is suspended **everything** is suspended. Your battery can last months suspended, not just a few hours.

**Comment by khariche** [comment] 2020-03-29 22:41
Thank you for the info.

**Comment by khariche** [comment] 2020-04-02 13:26
Would it be possible to establish one of the available networks as favorite and try to connect to it automatically (without showing the menu), and try to connect to the other ones only when the first one is not available?

**Comment by pazos** [comment] 2020-04-02 15:05
> Would it be possible to establish one of the available networks as favorite and try to connect to it automatically (without showing the menu), and try to connect to the other ones only when the first one is not available?

@khariche: Nope. 

I would like to know why you need such a feature. Are you trying to connect to an AP with lower signal power? If that's true: why?

**Comment by pazos** [comment] 2020-04-04 17:42
Closing this ticket.

The first question is specific for the cervantes platform.
The rest of questions are not.

**Closed by pazos** 2020-04-04 17:42 UTC
Labels: Cervantes, documentation

**Comment by khariche** [comment] 2020-04-05 11:57
> > Would it be possible to establish one of the available networks as favorite and try to connect to it automatically (without showing the menu), and try to connect to the other ones only when the first one is not available?
> 
> @khariche: Nope.
> 
> I would like to know why you need such a feature. Are you trying to connect to an AP with lower signal power? If that's true: why?

Hi, thanks for the follow up. I have two networks at home, and I sync my files between the cervantes and my windows pc over ssh. As I have other appliances and devices like a printer etc, I prefer to use always one of the two networks, even if the signal is poorer, to avoid the hassle of having to change the network on each device. However, because I live in the countryside, sometimes, the main network, which is the fastest, becomes unavailable, and then I have to resort to the second one.
Thus the wish to be able to set a default network to connect to automatically, and only when it is down, choose a second one.

**Comment by pazos** [comment] 2020-04-05 15:10
setup the two APs as part of the same subnet and you'll be able to use network fresources from both of them.

**Comment by khariche** [comment] 2020-04-05 15:38
Thank you so much for the suggestion! I am not knowledgeable enough to handle this by myself, but have found this guide: https://www.hanselman.com/blog/ConfiguringTwoWirelessRoutersWithOneSSIDNetworkNameAtHomeForFreeRoaming.aspx
Is this pertinent - and the easiest approach- to it?

**Comment by pazos** [comment] 2020-04-07 14:33
Assuming only one internet provider the following scheme would work:

1. Internet router with IP 192.168.1.1/24.
2. Secondary AP with IP 192.168.1.254/24 and both gateway and dns pointing to 192.168.1.1.

In this scheme you can add as many AP's as you want. Each one will have a different ESSID. Network should work fine as is, as most neutered routers/aps are configured without NAT, so you'll only need to check that you can see your main router (and other devices hooked to it) from all of the secondary APs. Your main router will do NAT for network requests that go beyond your local network.

**Comment by khariche** [comment] 2020-04-17 13:25
Sorry for the delay, I have been busy lately... Thanks, but my setup happens to include two internet providers (each router is from a different provider).
Also, I would like each network to keep its SSID, in order to be able to choose manually one or the other at any given time.
Thanks.
