### ISSUE TITLE
OTA stopped working with Version 2024.04-209 (Pocketbook InkpadX, Inkpad3pro, PB631)

### ISSUE THREAD

**Issue by claus-von-gmx** [koreader/koreader#12139] opened 2024-07-05 15:14 UTC
* KOReader version: 2024.04-209
* Device: see title
[crash.log](https://github.com/user-attachments/files/16111245/crash.log)

#### Steps to reproduce
Search for update - update found - try to install update - CRASH
**Is there a possibility to fix this without a complete re-install of koreader?**
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
Time To Connect [59359][1933:05/07/24 16:54:16] netagent called with parameters < net info >
[1941:05/07/24 16:54:16] netagent called with parameters < ping >
07/05/24-16:54:17 INFO  Wi-Fi successfully restored (after 0.25 seconds)! 
[1042 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[1042 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[1042 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[1042 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[2614:05/07/24 16:54:46] netagent called with parameters < ping >
07/05/24-16:54:50 INFO  Inhibiting user input 
./luajit: frontend/ui/otamanager.lua:307: attempt to call method 'getZsyncFilename' (a nil value)
stack traceback:
	frontend/ui/otamanager.lua:307: in function '_buildLocalPackage'
	frontend/ui/otamanager.lua:338: in function 'zsync'
	frontend/ui/otamanager.lua:229: in function 'action'
	frontend/ui/uimanager.lua:1020: in function '_checkTasks'
	frontend/ui/uimanager.lua:1470: in function 'handleInput'
	frontend/ui/uimanager.lua:1590: in function 'run'
	./reader.lua:242: in main chunk
	[C]: at 0x00013f61
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
07/05/24-16:54:51 INFO  rerendering subprocess: parent gone, exiting 
</details>

**Comment by benoit-pierre** [comment] 2024-07-05 15:21
Duplicate of #12115. You'll have to [update manually](https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices#installation).

**Closed by benoit-pierre** 2024-07-05 15:21 UTC

**Comment by Commodore64user** [comment] 2024-07-05 19:30
I would suggest this ticket remains (temporarily) open so no new similar tickets are open by unaware testers.

**Comment by Frenzie** [comment] 2024-07-05 19:48
The issue only existed for a few days.

**Comment by Commodore64user** [comment] 2024-07-05 21:58
> The issue only existed for a few days.

Yes i know, i was thinking more about people who might not have updated yet and when they try in future will face problems.
