### ISSUE TITLE
Crashes when opening a file in the Text editor

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8951] opened 2022-03-26 10:55 UTC
* KOReader version: 2022.03
* Device: PB 628

#### Issue
Crashes occur when I try to open a new file in the text editor.
This problem does not occur when I open a file from recent.

[crash 23-3-2022.log.txt](https://github.com/koreader/koreader/files/8355212/crash.23-3-2022.log.txt)

**Comment by Frenzie** [comment] 2022-03-26 11:05
How do you try to open it exactly?

**Comment by ichnilatis-gr** [comment] 2022-03-26 11:06
Tapping on "New file".

**Comment by Frenzie** [comment] 2022-03-26 11:08
You mean you see a crash instead of this?
![Screenshot_2022-03-26_12-08-18](https://user-images.githubusercontent.com/202757/160236712-37e097f4-3793-40ca-83c1-df91d537a9a5.png)

**Comment by Frenzie** [comment] 2022-03-26 11:11
As an aside, from the regular user perspective this error wouldn't happen without debug logging enabled.

But how'd you get the wrong type… :-/
```
./luajit: frontend/ui/widget/textwidget.lua:180: Wrong text type (expected string)
stack traceback:
	[C]: in function 'assert'
	frontend/ui/widget/textwidget.lua:180: in function 'pre_guard'
	frontend/dbg.lua:64: in function 'updateSize'
	frontend/ui/widget/textwidget.lua:292: in function 'getSize'
	plugins/coverbrowser.koplugin/listmenu.lua:459: in function 'update'
	plugins/coverbrowser.koplugin/listmenu.lua:176: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	plugins/coverbrowser.koplugin/listmenu.lua:998: in function '_updateItemsBuildUI'
	plugins/coverbrowser.koplugin/covermenu.lua:102: in function 'updateItems'
	frontend/ui/widget/menu.lua:1152: in function 'switchItemTable'
	frontend/ui/widget/filechooser.lua:379: in function 'refreshPath'
	...
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1119: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1603: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1683: in function 'handleInput'
	frontend/ui/uimanager.lua:1734: in function 'run'
	./reader.lua:324: in main chunk
	[C]: at 0x00013f5d
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 03/23/22 @ 20:10:33)
```

**Comment by Frenzie** [comment] 2022-03-26 11:12
The problem isn't hidden in translation:
![Screenshot_2022-03-26_12-11-44](https://user-images.githubusercontent.com/202757/160236833-490c54bd-2615-4ea9-9987-60deb8b05e3f.png)

**Comment by ichnilatis-gr** [comment] 2022-03-26 11:14
Sorry, I made a mistake. The problem happens when I tap on "Open file".
Sorry!

**Comment by Frenzie** [comment] 2022-03-26 11:20
I'm afraid I can't reproduce any issues there either.

What happens for me:

1. Open file
2. Select a file by long-pressing
3. Click yes in this dialog
4. File is opened

<img src=https://user-images.githubusercontent.com/202757/160237011-863108f8-9b4e-4a2d-8f84-662d774db28a.png width=45%>

(Screenshot from desktop but it's the same on my Kobo.)

---

Could it be related to a filename or something? Although then presumably even just the regular file browser should crash.

**Comment by ichnilatis-gr** [comment] 2022-03-26 11:27
The crash happens when I tap on "Open file", not when I choose a file.

**Comment by Frenzie** [comment] 2022-03-26 11:33
@poire-z Any ideas?

**Comment by poire-z** [comment] 2022-03-26 12:02
So, the (two same) crash in the log seems to be the above traceback, involving coverbrowser.
So, `Open file` in the menu launches the "Long press to choose a file" filechooser instance, and it is it that crashes.
And it is either pages_str (which is initialized to "") or fileinfo_str (which is initialized to nil) that ends up being nil (so, not filled by the various if/else branches, or filled with nil).
Not sure which :) and can't reproduce, so hard to debug.
It might depend on some strange file (filename, extension, size) in the directory that is about to be opened.
@ichnilatis-gr : you will need to help us pinpoint where there is a problem.
Can you replace your plugins/coverbrowser.koplugin/listmenu.lua with this one: 
[listmenu.lua.txt](https://github.com/koreader/koreader/files/8355319/listmenu.lua.txt)

It should log stuff like:
```
03/26/22-12:57:27 WARN  zzz self.filepath /koreader/COPYING
03/26/22-12:57:27 WARN  zzz fileinfo_str false 34.5 kB
03/26/22-12:57:27 WARN  zzz pages_str false
03/26/22-12:57:27 WARN  zzz about to crash?
03/26/22-12:57:27 WARN  zzz nope
```
And may be we'll see more of what is happening.
Just paste these bits (rename/erase the filenames if you want to keep them private - unless the one that crashes has some specific name).

**Comment by ichnilatis-gr** [comment] 2022-03-26 12:11
The crash doesn't happen when I choose a file; nothing has changed in the files I want to edit. It happens as soon as I tap on the "Open file".

**Comment by poire-z** [comment] 2022-03-26 12:37
^ I got that.
As soon as you tap on "Open file", a filebrowser is being built to display the list of files in the last directory you used.  This is this that is crashing - before you get a chance to see a list of files to choose from.
Please do my above suggestion :)

**Comment by ichnilatis-gr** [comment] 2022-03-26 12:38
I'll try it.

**Comment by ichnilatis-gr** [comment] 2022-03-27 11:49
> @ichnilatis-gr : you will need to help us pinpoint where there is a problem. Can you replace your plugins/coverbrowser.koplugin/listmenu.lua with this one: [listmenu.lua.txt](https://github.com/koreader/koreader/files/8355319/listmenu.lua.txt)
> 
> It should log stuff like:
> 
> ```
> 03/26/22-12:57:27 WARN  zzz self.filepath /koreader/COPYING
> 03/26/22-12:57:27 WARN  zzz fileinfo_str false 34.5 kB
> 03/26/22-12:57:27 WARN  zzz pages_str false
> 03/26/22-12:57:27 WARN  zzz about to crash?
> 03/26/22-12:57:27 WARN  zzz nope
> ```
> 
> And may be we'll see more of what is happening. Just paste these bits (rename/erase the filenames if you want to keep them private - unless the one that crashes has some specific name).

I give you these lines from the new crash.log, after installing your listmenu.lua

```
03/27/22-14:43:48 WARN  zzz self.filepath /mnt/ext2/Ιστολόγια/The school/..
03/27/22-14:43:48 WARN  zzz fileinfo_str true
03/27/22-14:43:48 WARN  zzz pages_str false 
03/27/22-14:43:48 WARN  zzz about to crash?
```

**Comment by poire-z** [comment] 2022-03-27 12:09
> `The school/..`

Are these `..` in the logs, or is it you that truncated/hid some file name and replaced it with `..` ?
If it's there in the log, well, the problem is was above, because `..` is a directory, and we shouldn't go thru this code that is about real files.

So, it's fileinfo_str that is/ends up nil.
Could be solved by `local fileinfo_str = ""` instead of `local fileinfo_str`, but I'd like to know more about what's happening.
Here's another file to replace with, with more logs:
[listmenu.lua.txt](https://github.com/koreader/koreader/files/8357526/listmenu.lua.txt)

**Comment by ichnilatis-gr** [comment] 2022-03-27 13:31
> Are these `..` in the logs, or is it you that truncated/hid some file name and replaced it with `..` ?

They are in the log.

**Comment by ichnilatis-gr** [comment] 2022-03-27 13:38
That's the result

```
03/27/22-16:35:50 WARN  zzz self.filepath /mnt/ext2/Ιστολόγια/The school/..
03/27/22-16:35:50 WARN  zzz no mandatory: 
03/27/22-16:35:50 WARN  zzz bookinfo._no_provider:
03/27/22-16:35:50 WARN  zzz fileinfo_str true
03/27/22-16:35:50 WARN  zzz pages_str false 
03/27/22-16:35:50 WARN  zzz about to crash?
```

The `..` are in the log.

**Comment by poire-z** [comment] 2022-03-27 13:40
No problem in File browser when you try to navigate up and down these directories ?
```
/mnt/ext2/
/mnt/ext2/Ιστολόγια/
/mnt/ext2/Ιστολόγια/The school/
```

**Comment by ichnilatis-gr** [comment] 2022-03-27 13:42
No problem.

**Comment by poire-z** [comment] 2022-03-27 13:46
Here's another one: [listmenu.lua.txt](https://github.com/koreader/koreader/files/8357737/listmenu.lua.txt)
It should show before the crash and the other logs:
`03/27/22-15:44:30 WARN  /mnt/ext2/Ιστολόγια/The school/.. is directory`
but for you, it may show something else ? `symlink` may be ?

**Comment by ichnilatis-gr** [comment] 2022-03-27 13:52
```
03/27/22-16:50:47 WARN  /mnt/ext2/Ιστολόγια/The school of life/.. is
03/27/22-16:50:47 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
03/27/22-16:50:47 WARN  zzz self.filepath /mnt/ext2/Ιστολόγια/The school of life/..
03/27/22-16:50:47 WARN  zzz no mandatory: 
03/27/22-16:50:47 WARN  zzz bookinfo._no_provider:
03/27/22-16:50:47 WARN  zzz fileinfo_str true
03/27/22-16:50:47 WARN  zzz pages_str false 
03/27/22-16:50:47 WARN  zzz about to crash?
```

**Comment by ichnilatis-gr** [comment] 2022-03-27 13:54
Sorry, I have to go.
Thank you for your efforts.
I'll continue later.

**Comment by poire-z** [comment] 2022-03-27 13:58
OK.
So, the question is what could (on a Pocketbook) make `lfs.attributes("/mnt/ext2/Ιστολόγια/The school/..", "mode")` returns nil and not "directory" ...

**Comment by Frenzie** [comment] 2022-03-27 14:43
I think something like this should normally show the error message (not yet tested)
```lua
    local file_mode, err = lfs.attributes(self.filepath, "mode")
    logger.warn(self.filepath, "is", file_mode, "error:", err)
```

**Comment by poire-z** [comment] 2022-03-27 15:12
Good idea. So, here's another one: [listmenu.lua.txt](https://github.com/koreader/koreader/files/8357919/listmenu.lua.txt)

**Comment by ichnilatis-gr** [comment] 2022-03-27 15:57
Now it gives this.

```
03/27/22-18:54:55 WARN  zzz self.filepath /mnt/ext2/Ιστολόγια/The school/..
03/27/22-18:54:55 WARN  zzz no mandatory: 
03/27/22-18:54:55 WARN  zzz bookinfo._no_provider:
03/27/22-18:54:55 WARN  zzz fileinfo_str true
03/27/22-18:54:55 WARN  zzz pages_str false 
03/27/22-18:54:55 WARN  zzz about to crash?
```

**Comment by poire-z** [comment] 2022-03-27 16:05
We want to see what's before that :) Something like your previous:
```
03/27/22-16:50:47 WARN  /mnt/ext2/Ιστολόγια/The school/.. is
03/27/22-16:50:47 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf

```

**Comment by ichnilatis-gr** [comment] 2022-03-27 16:16
```
03/27/22-18:54:55 WARN  /mnt/ext2/Ιστολόγια/The school of life/.. is nil error: cannot obtain information from file '/mnt/ext2/Ιστολόγια/The school/..': No such file or directory
03/27/22-18:54:55 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
03/27/22-18:54:55 WARN  zzz self.filepath /mnt/ext2/Ιστολόγια/The school/..
03/27/22-18:54:55 WARN  zzz no mandatory: 
03/27/22-18:54:55 WARN  zzz bookinfo._no_provider:
03/27/22-18:54:55 WARN  zzz fileinfo_str true
03/27/22-18:54:55 WARN  zzz pages_str false 
03/27/22-18:54:55 WARN  zzz about to crash?

```
Is that enough or would you like the whole crash.log?

**Comment by poire-z** [comment] 2022-03-27 16:23
That's enough, thanks.
`'/mnt/ext2/Ιστολόγια/The school/..': No such file or directory`

Can you now navigate up and down with the file browser the directories I mentionned, as you did earlier, and show the same kind of log after you have done that ?

**Comment by ichnilatis-gr** [comment] 2022-03-27 16:45
I give you the whole file, as I don't understand exactly which lines you want.

[crash 27-3-2022 (2).log.txt](https://github.com/koreader/koreader/files/8358055/crash.27-3-2022.2.log.txt)

May I disable "debug logging"? There are too many lines in crash.log... :-)

**Comment by poire-z** [comment] 2022-03-27 17:00
Yes, you can disable it - it wasn't strictly need to understand this issue.

Well, same filepath, different behaviour :/
```
03/27/22-18:54:55 WARN  /mnt/ext2/¿¿¿¿¿¿¿¿¿/The school/.. is nil error: cannot obtain information from file '/mnt/ext2/¿¿¿¿¿¿¿¿¿/The school/..': No such file or directory
03/27/22-19:31:48 WARN  /mnt/ext2/¿¿¿¿¿¿¿¿¿/The School/.. is directory error: none

xxd of the 2 greek strings (that is displayed as ¿¿¿¿¿¿¿¿¿ on my latin1 terminal):
00000000: ce99 cf83 cf84 cebf cebb cf8c ceb3 ceb9  ................
00000010: ceb1 2f0a                                ../.
00000020: ce99 cf83 cf84 cebf cebb cf8c ceb3 ceb9  ................
00000030: ceb1 2f0a                                ../.
```
No idea.

**Comment by ichnilatis-gr** [comment] 2022-03-27 17:03
> Yes, you can disable it - it wasn't strictly needed to understand this issue.

I had enable it for another issue...

**Comment by Frenzie** [comment] 2022-03-27 17:57
> Well, same filepath, different behaviour :/

"Expected" given what we already knew, but that's mystifying.

**Comment by poire-z** [comment] 2022-03-27 18:19
Two things to try (just to get a chance to have more hints):

Remove (backup/copy them elsewhere, for yourself and in case this solves the issue, we'd want to see what's in there): `koreader/settings/text_editor.lua` and `text_editor.lua.old`.
Try again Open file and browse around. Works ? If yes, try to open a file in this `Ιστολόγια` directory; close it. Go again to that menu and Open file (it should try to read again the content of that directory). Works/crashes ?

If this does not help: backup your `koreader/history.lua` (just so you don't lose your history items because the items won't exist anymore), and try to rename your `Ιστολόγια` to something english/ascii: `abcde`. And see if this helps or not.

**Comment by NiLuJe** [comment] 2022-03-27 22:24
That would directly correlate to a `stat` call failing. I assume this is a vfat partition, so there's no chance of broken symlinks on the way?

Does a stat on `/mnt/ext2/Ιστολόγια` actually work? And, if so, why are we running an lfs.attribute on a `..` virtual entry in the first place?

**Comment by poire-z** [comment] 2022-03-27 23:20
> Does a stat on /mnt/ext2/Ιστολόγια actually work?

It seems to work in the full log. And even Ιστολόγια/.. does work when invoked from file browser.

> And, if so, why are we running an lfs.attribute on a .. virtual entry in the first place?

We get it from lfs.dir(), as it is an item in this directory, and we use it to build the <kbd>^ ../</kbd> top item. Seems to usually cause no issue :)

**Comment by NiLuJe** [comment] 2022-03-27 23:58
Hmm. Probably needs a strace, stat might be a wrapper that uses other, newer kernel facilities but... badly ;). (e.g., `*statat` stuff).

**Comment by ichnilatis-gr** [comment] 2022-03-29 14:14
>try to rename your `Ιστολόγια` to something english/ascii: `abcde`. And see if this helps or not

Before I remove the files `koreader/settings/text_editor.lua` and `text_editor.lua.old` etc., would it help if I deleted the "School" folder? It's nothing important.

**Comment by poire-z** [comment] 2022-03-29 14:24
> would it help if I deleted the "School" folder? 

No, it would not help, and we want to see how it behave later when you navigate/stop/re-open these directories - so don't trash them, or you would just push the issue under the carpet :)

**Comment by poire-z** [comment] 2022-03-29 15:33
So, can you go into the same configuration you had before by, in Text editor, Open file, being in the `The school` directory and seeing its content, and opening a file there.
Next time, you hit Open file, you should be in that directory - then just don't open anything and exit KOReader.
And give us the old text_editor.lua (+the .lua.old) you have backup'ed, and the new/current one. Hoping we will see a difference that can help us understand what happened before.

**Comment by ichnilatis-gr** [comment] 2022-03-29 16:41
[text_editor.lua.old.txt](https://github.com/koreader/koreader/files/8373395/text_editor.lua.old.txt)
[text_editor.lua.txt](https://github.com/koreader/koreader/files/8373397/text_editor.lua.txt)
[text_editor (2).lua.txt](https://github.com/koreader/koreader/files/8373398/text_editor.2.lua.txt)
[text_editor.lua (2).old.txt](https://github.com/koreader/koreader/files/8373399/text_editor.lua.2.old.txt)

Note that I had already opened another file before.
(Let me delete them after you download them)

**Comment by poire-z** [comment] 2022-03-29 16:53
Just downloaded all of them, you can remove them.

But I see no difference between them :/
But I see that all of them have:
`["last_path"] = "/mnt/ext2/Î~YÏ~CÏ~DÎ¿Î»Ï~LÎ³Î¹Î±/The school of life",`
`The school of life` - and not `The school` like we saw in your earlier crash logs.
Did/do you, now and before, only have the directory named `The school of life` in your Histology (in greek) directory ? And some truncation somewhere made it appear as `The school` in the log ?

Also, to be sure, you can try putting back your backup'ed text_editor.lua, and see if the issue appears again.
Puzzling.

**Comment by poire-z** [comment] 2022-03-29 18:20
Where ? In the log, only in the log? On the filesystem on your device ?
Anyway, this add some uneeded noise and uncertainty to continue investigating this :/
And as it works for you now, I guess we'll wait until it happen again.

(I checked that it does not crash if last_path points to something that doesn't exis, as it it has been renamed from elsewhere.)

**Comment by poire-z** [comment] 2022-03-29 19:35
Oh, there is a difference:
```
ichnilatis-text_editor.2.lua.txt:    ["last_path"] = "/mnt/ext2/Î~YÏ~CÏ~DÎ¿Î»Ï~LÎ³Î¹Î±/The School of Life",
ichnilatis-text_editor.lua.txt:      ["last_path"] = "/mnt/ext2/Î~YÏ~CÏ~DÎ¿Î»Ï~LÎ³Î¹Î±/The school of life",
```
School and Life with a starting uppercase in one, school and life fully lowercase in the other.
Dunno where this comes from (manual editing/renaming/put back?), and how uppercase/lowercase initial name and the fact that it works with an alternative case on FAT filesystems is handled by Luafilesystem or stat().

**Comment by NiLuJe** [comment] 2022-03-29 21:10
Stuff *should* be case-insensitive on vfat (e.g., `School` should point to `school` and vice-versa, and you shouldn't be able to create `School` if `school` exists, and vice-versa).

But that's in a perfect world. I wouldn't exclude a weird little bug somewhere ;).

**Comment by Frenzie** [comment] 2022-03-30 08:51
That does provide some ideas for things to try, like deleting folders and renaming them with only the case changed.

**Comment by ichnilatis-gr** [comment] 2022-03-30 11:52
The correct name, I mean the name of the folder, is with capitals. I didn't change them in the log.

**Comment by poire-z** [comment] 2022-03-30 19:49
It it possible that at some point in time, it was written (and so, displayed in KOReader) without capitals - and that at some later point, you corrected it (like, renaming "The school of life" to something else, then back to proper "The School of Life") ?

As in your old text_editor.lua, it was written "The school of life", so either it was met written like that (and ok, this is a super edgy edge case on all sides that something somewhere fails when capitalization changes). Or either it's some part of the code that does uncapitalization (which would surprise me, but if you swear you did not rename it, this needs some investigation).

**Comment by ichnilatis-gr** [comment] 2022-03-31 10:41
If I remember correctly, I wrote it in capital letters from the beginning.

**Comment by poire-z** [comment] 2022-06-11 11:32
Closing as edge-casey, possibly human-messupy, and hardly reproducible.
Re-open if this happens again.

**Closed by poire-z** 2022-06-11 11:32 UTC
Labels: bug, PocketBook, Plugin
