### ISSUE TITLE
Cannot open PDF from Telegram app on android in Koreader

### ISSUE THREAD

**Issue by Lemonnonioiiii** [koreader/koreader#10002] opened 2023-01-07 12:36 UTC
* KOReader version:
* Device: Boox Max Lumi 2

#### Issue
The PDF file I received in Telegram App cannot be opened directly in Koreader (it could be opened by for example Moonreader).
It redirects me to Koreader but says that "there is no engine supporting the file or the file is corrupted"
If I save the PDF in download files, I can open the file in Koreader without problem, so I think the file is fine.

#### Steps to reproduce
- Download a PDF file in Telegram
- Click the file in Telegram Chat window and choose "open in Koreader"
- Redirected to Koreader which says "there is no engine supporting the file or the file is corrupted"

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by mergen3107** [comment] 2023-01-07 12:46
Meanwhile try to save it in Telegram, then go to Total Commander or other file manager and try opening it from there.

**Comment by hius07** [comment] 2023-01-07 13:00
Seems to be a duplicate of https://github.com/koreader/koreader/issues/9787.

**Closed** 2023-01-07 16:49 UTC
Labels: Android, duplicate
