### ISSUE TITLE
Rendering issues w/ black letter fonts & OpenType typesetting rules

### ISSUE THREAD

**Issue by Moonbase59** [koreader/koreader#8715] opened 2022-01-23 17:44 UTC
* KOReader version: 2022.01
* Device: Linux Mint 20.3/Cinnamon (AppImage); Tolino Tab 8" (Android, KOReader.rocks version)

#### Issue

1. Example EPUB `Das Leben der Hochgrafin Gritta von Ratten - Bettina von Arnim.epub` **doesn’t use the embedded font(s)**, whereas other readers do (Calibre Viewer, Foliate, Tolino, …).
2. Example EPUB `Hormann, Matthias - Test Fraktur (101).epub` **doesn’t handle embedded OpenType typesetting rules correctly**. Other readers like _Foliate_ do mostly (except for using the correct glyphs when _letter-spacing_ is applied; this _might_ still be an error in the font).

#### Steps to reproduce
Try enclosed (free) EPUBs on KOReader (and maybe others). For the Fraktur Test, verify expected result using the "good" screenshot.

##### `crash.log` (if applicable)
—

#### Example EPUBs and screenshots
[Example EPUBs.zip](https://github.com/koreader/koreader/files/7920999/Example.EPUBs.zip)

![Das Leben der Hochgräfin Gritta von Rattenzuhausbeiuns - KOReader_001](https://user-images.githubusercontent.com/3706922/150690360-2037d2ac-3669-41df-afba-9a81f231e104.png)

![Das Leben der Hochgräfin Gritta von Rattenzuhausbeiuns  EPUB  — E-book viewer_001](https://user-images.githubusercontent.com/3706922/150690374-747ecf5d-a1d7-4704-884e-7bbe828b8217.png)

![Test Fraktur - KOReader_001](https://user-images.githubusercontent.com/3706922/150691327-aed638d3-aa5c-46d3-8663-6c0d0a09008a.png)

![Test Fraktur  EPUB  — E-book viewer_002](https://user-images.githubusercontent.com/3706922/150690628-dd060d28-0dbd-4e63-a413-1c502387f95c.png)

**Comment by poire-z** [comment] 2022-01-23 18:06
Issue 1 seems to be our embedded font stylesheet pre-parser getting confused by the top comment (so, a bug, to be fixed):
```css
/**************************************
* Author:  Ralf Gawlista (gawl@gawl.de)
* Version: 406
* Date:    2013-10-25
**************************************/
@font-face {
```
If you remove the long sequences of `******************` or just add a space after `/* **` and before `** */`.

**Comment by poire-z** [comment] 2022-01-23 18:56
About issue 2, no real idea.

Your fonts don't have much OpenType features:
```
otfinfo -f fonts/LOV.HammerUnziale.otf
liga    Standard Ligatures

otfinfo -f fonts/LOV.NeueDeutscheKurrent.otf
liga    Standard Ligatures

otfinfo -f fonts/LOV.UnicodeFraktur.otf
liga    Standard Ligatures
```
and "liga" is enabled by default in Kerning mode "best" (but not used in "fast", so you can switch between best and fast to get an idea of what "liga" brings).

In the stylesheet.css, there is:
```
em, strong {
        letter-spacing: 0.2em;
        font-style: normal;
        font-weight: normal;
  -ms-font-feature-settings: "liga" 0, "rlig", "ccmp" !important;
        -webkit-font-feature-settings: "liga" 0, "rlig", "ccmp" !important;
        font-feature-settings: "liga" 0, "rlig", "ccmp" !important;
}
```
which shouldn't affect the text you're pointing to as it targets only EM and STRONG.
Mentionning this (but it shouldn't be the cause for your issue): we don't support any form of `font-feature-settings:`. We only support a subset of `font-variant:`. All that's supported is listed at:
https://github.com/koreader/crengine/blob/d707f89559aa0a8d83f401cbd5e20f10b8998934/crengine/src/lvstsheet.cpp#L3203-L3279
https://github.com/koreader/crengine/blob/d707f89559aa0a8d83f401cbd5e20f10b8998934/crengine/src/lvfntman.cpp#L1508-L1600
If you ever need to have some of the font-feature-settings mentionned in a stylesheet, you could help yourself with style tweaks with things like:
`* { font-variant: no-common-ligatures historical-ligatures historical-forms }`
(but as none of the fonts in this epub seems to support them, it's of no use - I tried some, only disabling ligatures with no-common-ligatures changed things, but only in the cursive/italic font).

You could try the html+css+fonts in Firefox or Chrome (I think they use Harfbuzz, or maybe it's only on Linux) to see if it's a Harfbuzz issue, or the fonts having specific stuff other than OTF that the other software are better at handling.

**Comment by Moonbase59** [comment] 2022-01-24 00:22
Some more debugging needed, it seems (for me). Thanks for the `otfinfo` pointer, and cross-checking with Harfbuzz! I’ll try to find out more.

Would you think it is _generally_ the better idea to use `font-variant` instead of `font-feature-settings`? (And why?)

**Comment by poire-z** [comment] 2022-01-24 00:54
> Would you think it is generally the better idea to use font-variant instead of font-feature-settings? (And why?)

Generally, I have no idea:
font-variant is older, so probably more supported by various e-readers (and so KOReader).
font-feature-settings is more flexible, and supported by current browsers (and all reading apps based on recent browser engines)

But in the case of KOReader users, yes, it's a better idea, simply because KOReader supports (a subset of) font-variant and doesn't support `font-feature-settings` (and probably won't anytime soon, as it's quite complex to parse and it allows more combinations/tuning than font-variant, and would so need quite some rework of the datastructures required to support the variations).

**Comment by poire-z** [comment] 2022-01-24 00:56
> Re issue 1: Thanks, it’s readable again! The bug will get fixed nevertheless, I guess? Since other authors might use the same comment style…

Yes, I have fixed it, locally, it will reach KOReader in a few days - waiting in case you find more bugs :/

**Comment by Moonbase59** [comment] 2022-01-24 01:28
> waiting in case you find more bugs :/

Well, I’m not actively _hunting_ them bugs. It’s just that—when reading—sometimes I find things I remember working in other readers. Plus, I currently work on all this German black letter stuff. Actually, the planned e-book should only contain some excerpts from old German letters (in _Kurrent_ and/or _Fraktur_), but of course _perfectly rendered_ (and switchable to a "normal" Antiqua font for those who can’t read that)…

So now I opened yet another can of worms… ;-)

**Comment by poire-z** [comment] 2022-01-25 20:44
Issue 1 should be fixed in tomorrow's nightly.

**Comment by poire-z** [comment] 2022-04-14 10:42
Closing as issue 1 fixed, and issue 2 is obscure and may be not KOReader related. Re-open if more info showing we should care :)

**Closed by poire-z** 2022-04-14 10:42 UTC
