### ISSUE TITLE
Default for PDF navigate direction setting is not applied to the new opened documents.

### ISSUE THREAD

**Issue by omer-faruq** [koreader/koreader#9321] opened 2022-07-11 19:22 UTC
* KOReader version: 2022.06-18 
* Device: Kobo Forma

#### Issue
Default for PDF  navigate direction setting  is not applied to new opened documents.

#### Steps to reproduce

1- open a pdf and set pdf direction default  to second one (marked as "2"  in the below image)  , zoom-to as vertical multi column ( third option) and  column count 2  as default ( via long pressing them) 

![image](https://user-images.githubusercontent.com/85738646/178344121-6cb826c5-f01e-4434-aa04-d129d18df9bc.png)

2-  open a new pdf document 

3- check whether direction setting is applied ( it is not) 

it does display that the second direction setting as the active one ,  however when navigating  it behaves  as if  the first option is active.

**Comment by tpulha** [comment] 2022-08-17 15:52
Happening to me as well

**Comment by NiLuJe** [comment] 2022-08-17 18:41
This would be a good first issue for a new contributor, with a bit of guidance (because this is a bit of a mess, as there's two or three layers of indirection and legacy config keys handling in there).

Taking a look at the history would help, as I dealt with similar shenanigans in the past, and readerzooming probably hasn't seen much action since.

**Comment by hius07** [comment] 2022-12-17 08:46
It seems the bug has been fixed with Sep-Oct changes to ConfigDialog. Cannot reproduce now.

**Closed by hius07** 2022-12-17 08:46 UTC
Labels: bug, low-hanging-fruit, help-wanted

**Comment by omer-faruq** [comment] 2022-12-21 13:41
I installed the 2022.11-52-g99df7195_2022-12-19, unfortunately still can produce this error. newly opened documents are not use the default setting for this part .  ( I'm using Kobo Forma)

**Comment by NiLuJe** [comment] 2022-12-21 13:44
There's a lot of clunk in that code, as I mentioned earlier, so there might be behavioral differences depending on whether your setup includes old settings or... something.

(i.e., once would have to check if it's reproducible with a clean setup and a clean sidecar).
