### ISSUE TITLE
[feature request] newsdownloader html filtering

### ISSUE THREAD

**Issue by lich-tex** [koreader/koreader#6205] opened 2020-05-28 19:26 UTC
* KOReader version:
* Device:

#### Issue

As the epub converter usually takes a lot of elements of sites that are unwanted (i.e. headers, footers, even ads) I suggest it would be beneficial to use some form of filtering.

The one I use on desktop is [tedu's miniwebproxy](https://flak.tedunangst.com/post/miniwebproxy) and I does the task greatly and I think it is viable to port it to koreader for that purpose, its use could go beyond the news reader.

**Comment by pazos** [comment] 2020-05-28 20:46
duplicate of #6185

**Closed by pazos** 2020-05-28 20:46 UTC

**Comment by NiLuJe** [comment] 2020-05-28 20:50
That said, the mention of a proxy opens up an interesting avenue: support setting a proxy somewhere(unless we already do? Possibly via the semi-standard env var that I don't remember right now?) and leave the burden of actually setup a filtering proxy to the user.
