### ISSUE TITLE
FR: Display logical page numbers

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9827] opened 2022-11-24 09:30 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
Sometimes there are pdf files in which we have changed the format of page numbering. Thus, the preface of a book may have page numbers like i,ii,iii,iv.... and the chapters may have page numbers like 1,2,3....
Would it be possible for this difference in page numbering (i.e. logical page numbers) to be displayed in the status bar, table of contents etc., so as to make it easier to search a page based on the contents of the book?

Thank you!

**Comment by Frenzie** [comment] 2022-11-24 10:54
Duplicate of  #4245.

**Closed by Frenzie** 2022-11-24 10:54 UTC
Labels: enhancement
