### ISSUE TITLE
Crashes immediately on Pocketbook Basic Touch (624)

### ISSUE THREAD

**Issue by sdasda7777** [koreader/koreader#11344] opened 2024-01-12 20:22 UTC
* KOReader version: 2023.10
* Device: Pocketbook Basic Touch (624)

#### Issue
When I tried running koreader on my Pocketbook Basic Touch (624), it showed a message "Don't Panic! (Crash n°1 -> 42)". Afterwards the screen just flashed few times and returned to the applications list.

##### `crash.log` (if applicable)
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 01/12/24-12:58:00
 [*] Version: v2023.10

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
ffi.load: inkview
01/12/24-12:58:00 INFO  SoftwareVersion:  W624.4.4.1739 
ffi.load: inkview
Atached mp shm: id 0 addr 400bb000 size 17864
----------------> USING A2PLUS MODE <-----------------
attach_shm: mtfb key=251330805 size=518336
Atached mtfb shm: id 78009 addr 40869000 size 518336
-------------------------
The task - koreader.app have
 xres=600 yres=800 bpp=4 vdepth=8
-------------------------
ndepth:4 hqdepth:4 orientation:0
attach_shm: ref key=2130378752 size=480000
Atached ref shm: id 8001 addr 4098a000 size 480000
OpenTheme: /ebrmain/themes/Contrast.pbt
ts: loading default calibration values
attach_shm: mtfb key=251330805 size=518336
Atached mtfb shm: id 78009 addr 40b07000 size 518336
ffi.load: librt.so
ffi.load: inkview
ffi.load: inkview-compat
ffi.load (assisted searchpath): ./libs/libinkview-compat.so
./luajit: ./ffi/input_pocketbook.lua:21: ./libs/libinkview-compat.so: undefined symbol: InkViewMain
stack traceback:
	[C]: in function 'load'
	./ffi/input_pocketbook.lua:21: in main chunk
	[C]: at 0x0004b05d
	[C]: in function 'require'
	frontend/device/input.lua:12: in main chunk
	[C]: in function 'require'
	frontend/device/pocketbook/device.lua:188: in function 'init'
	frontend/device.lua:62: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x00013f6d
!!!!
Uh oh, something went awry... (Crash n°1: 01/12/24 @ 12:58:01)
Attempting to restart KOReader . . .
!!!!
```
[Repeats about 13 times]

**Comment by NiLuJe** [comment] 2024-01-12 20:30
Duplicate of #11172 (i.e., device/FW is way too old or weird).

Seems unfixable from our standpoint, but interested parties are free to poke around.

**Closed by NiLuJe** 2024-01-12 20:30 UTC

**Comment by sdasda7777** [comment] 2024-01-12 20:32
Ah, okay, thanks!
