### ISSUE TITLE
FR: Changes in OTA channels

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2796] opened 2017-04-21 14:28 UTC
* KOReader version: last nightly version
* Device: N/A

#### Issue
Currently there are two OTA channels: Stable and development.
- Stable: Doing some tests I checked the Stable channel and I tried all the 7 servers. I got a message saying that there is nothing in that channel. Last stable version is from a year and a half ago.
- Development: It installs the last nightly.

My suggestions:
- When chosing Stable channel, add the possibility to install the last stable version, even if it is older than the development version currently installed in the device. Of course, some caption message should be added to indicate that you are installing an older version.
- Forget and eliminate the Stable channel and replace the Development channel with two new channels: 
Last nightly (it would install the same version as the current Development channel) and Latest release (it would install the latest release published in this web). The Latest release version would be tested to avoid problems like the one that just happened with a plugin.
- Three channels, combining suggestion 1 and 2. That is: Stable, Latest release (beta), Last nightly (alpha).

**Comment by Frenzie** [comment] 2017-04-21 21:21
I think you missed "just get out a darn new stable out already!" :-)

> The Latest release version would be tested to avoid problems like the one that just happened with a plugin.

It wouldn't have helped in this case. I can't seem to reproduce that storagestatistics plugin issue as its presence makes no difference on my device.

**Comment by a-kohout** [comment] 2017-06-19 19:34
In light of #2974, #2973 and #2961 (where the build wouldn't even start) this suggestion makes a lot of sense.
The releases published on Github could go into a beta channel in addition to the nightly channel

> Last nightly (it would install the same version as the current Development channel) and Latest release (it would install the latest release published in this web). The Latest release version would be tested to avoid problems like the one that just happened with a plugin.

**Comment by protist** [comment] 2018-03-15 07:31
I'm also confused by the terminology. Are the "releases" considered more stable than the nightlies? I've been making that assumption, and hence sticking to the former, given there is no "darn new stable". 😁 (However, this means that updating is more tedious than OTA, of course.)

**Comment by Frenzie** [comment] 2018-03-15 09:15
In the latest release [here](https://github.com/koreader/koreader/releases/tag/v2018.03.14-beta) on GH I've made a first stab at clarifying it by calling it "beta" instead of "nightly". However, to actually do something automated with it (like a "channel") would definitely require more thought.

> Are the "releases" considered more stable than the nightlies?

They are. Nightlies only pass the unit tests while the releases on GH go through some degree of manual testing. In my case that entails regular use on Kobo + some basic tests on Android, but of course other people use the nightlies on their devices. We don't have an actual testing department or whatnot. ;-) But when I accidentally break something, I typically try to include a unit test along with the fix (e.g., #3729). In doing so that particular regression can never be accidentally introduced again.

In any case, the release on GH is quite literally the exact same as the nightly build in every way except that it's not automated. So if you see a new release on GH and the OTA update offers up the same version number, it's the same thing.

**Comment by protist** [comment] 2018-03-15 10:18
Thank you for that info. I'm subscribed to the RSS feed for the releases, so I'll just try to update OTA immediately after I get that notification. Otherwise the USB route is very fiddly, because of all the various settings I have to migrate as well. I'd love to see these "releases" on an OTA channel though! It'd be much simpler.

**Comment by NiLuJe** [comment] 2018-07-07 20:57
I'd maybe go so far as just dicth the stable channel altogether, because implementing the "betas" as a channel is going to be slightly tricky, as they're not actually hosted on the OTA servers ;).

RFC?

**Comment by Frenzie** [comment] 2018-12-12 11:42
I'll close this as implemented by [v2018.11](https://github.com/koreader/koreader/releases/tag/v2018.11). Also see https://github.com/koreader/koreader/issues/4292#issuecomment-434449114 for discussion.

**Closed by Frenzie** 2018-12-12 11:42 UTC
Labels: enhancement
