### ISSUE TITLE
"KOReader exited irregularly" when swiping to the left

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3731] opened 2018-03-08 13:58 UTC
* KOReader version: v2015.11-1546-gd0130ae
* Device: KA1

#### Issue
Every time I swipe to the left KOReader exits. Whether or not there are footnotes on the page.

This only happens with one of my epubs (AFAIK).

##### `crash.log` 
[crash.log](https://github.com/koreader/koreader/files/1793675/crash.log)

**Comment by poire-z** [comment] 2018-03-08 18:39
Thought I saw a .pdf in your previous crash.log, but if it's really an epub causing this, then:

Can you check with today's nightly or >= 1547 ?
There's been some fixes that could be related to what is done when you swipe left (if you have swipe to follow first/nearest link enable) between 1546 and 1547: https://github.com/koreader/crengine/pull/105 https://github.com/koreader/crengine/pull/107
If it still crashes, can you share the book in question, + page number where that happen if not on all.

Do you think you got theses crashes before the last 2 weeks (I pushed a few crengine changes, I'd be sad if that happened because of them) ?

**Comment by gerhaher** [comment] 2018-03-09 08:16
Thanks for your answer!

> Can you check with today's nightly or >= 1547 ?
> There's been some fixes that could be related to what is done when you swipe left (if you have swipe to follow first/nearest link enable) between 1546 and 1547: koreader/crengine#105 koreader/crengine#107

I've updated to 1547 now and nothing changed. I have "Swipe to follow nearest link" enabled. (If I disable it the problem disappears.)

> Do you think you got theses crashes before the last 2 weeks (I pushed a few crengine changes, I'd be sad if that happened because of them) ?

I started reading the book in question yesterday so I have no idea how it was before last 2 weeks.

> If it still crashes, can you share the book in question, + page number where that happen if not on all.

OK! More or less every page ASAIK.
[The Strange Death of Europe_ Im - Douglas Murray.zip](https://github.com/koreader/koreader/files/1796062/The.Strange.Death.of.Europe_.Im.-.Douglas.Murray.zip)

**Comment by cramoisi** [comment] 2018-03-09 09:02
Could it be related to the epub3 tag `<a epub:type="pagebreak" id="page259" class="calibre1"></a>` that are in the html files ?
You could replace them with `<span style=”page-break-before:always;” id="pageXXX" class="calibre1"></span>` and test the epub

**Comment by poire-z** [comment] 2018-03-09 09:35
I can reproduce the crash (it is happening also with a build from before my recent changes). I'll have a look at it. It could be related to links that don't exist, but it usually ignores them. Anyway, it shouldn't crash (nor require fixing the epub).

**Comment by gerhaher** [comment] 2018-03-09 09:54
I've changed the html-files and it seems to work now. 

Thanks cramoisi!

**Comment by cramoisi** [comment] 2018-03-09 10:00
thus, that doesn't solve the bug : it's just a patch for you to read ;)

**Comment by poire-z** [comment] 2018-03-09 11:50
Should be fixed in a coming nightly. Details in https://github.com/koreader/crengine/pull/120

**Closed** 2018-03-10 21:23 UTC
