### ISSUE TITLE
Feature request: Auto Next Page

### ISSUE THREAD

**Issue by kobomobo** [koreader/koreader#4984] opened 2019-04-30 18:07 UTC
* KOReader version: 2019.04
* Device: Kobo Clara HD

Believe or not, sometimes touch/click/swipe could be very annoying while reading non-stop. Automatically turn next page would be great. 

The interval time can be defined by typing/selecting seconds (or advanced idea : can be calculated according your mean time statistics per 1 page)

**Comment by Frenzie** [comment] 2019-04-30 18:12
Duplicate of #3019. But I'll tag that one help-wanted to indicate that it's a good place for someone to write a first plugin.

**Closed by Frenzie** 2019-04-30 18:12 UTC
Labels: Plugin, duplicate, help-wanted

**Comment by kobom** [comment] 2019-08-31 22:49
I think it's not duplicate of #3019.

I have serious accessibility problems with turning pages. Is it too hard to develop a next page command that runs at certain times? I don't understand software development. Please help us with accessibility.
