### ISSUE TITLE
Application not responding

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#6981] opened 2020-12-12 02:17 UTC
* KOReader version: latest 
* Device: Samsung S6 Tab 128GB (6GB of ram)

#### Issue

When opening koreader especially, but also when opening a book via file browser as well as navigating a book, koreader seems to crash often due to "application not responding".  

Occasionally the "wait" option presented works but often enough it does not seem to.  I expected this with my fire 10 tablet due to its meager 2gb of ram but I have no idea why I'm seeing it on this new tablet with 6gb of ram.  

#### Steps to reproduce

Open koreader; it seems to crash often on first open.  Also when opening a new book as well as sometimes going last/previous page.  

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F`.

apologies i ran this logcat without the filter for koreader previously; once i did use the command as written above i couldn't reproduce.  in the future i'll make sure i run that logcat to filter out the baloney

https://gist.github.com/arooni/aeeffcfdc7ceb72b1454f385394c660b

update; got it to crash with the filtered log
https://gist.github.com/arooni/ee8d578519fd9a8246c928cea4056aef

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

EDIT: I wonder if disabling battery optimizations would help?  i'm guessing android can be pretty aggressive in killing off processes that don't respond immediately.

**Comment by Frenzie** [comment] 2020-12-12 08:23
Are these books that open in under a second or two on your Kindle or are they generally problematic?

**Comment by pazos** [comment] 2020-12-12 11:14
@arooni: 

1. latest is not a version. :)
2. the logs are not filtered
3. the steps are a bit generic

>  I wonder if disabling battery optimizations would help? i'm guessing android can be pretty aggressive in killing off processes that don't respond immediately.

Nope. As I said you previously ANR has nothing to do with random things like memory available or battery optimizations. It gets triggered by queued events not consumed in 5 seconds. Why? I have no idea.

I have a SM-T500 tablet and wasn't able to trigger a ANR in normal conditions. I would suggest to start from 0.

1. backup /sdcard/koreader
2. delete the folder on the device (or rename it to any other name)
3. uninstall the program
4. install the [last nightly](http://build.koreader.rocks/download/nightly/v2020.11-52-g3142f98_2020-12-11/koreader-android-arm-v2020.11-52-g3142f98_2020-12-11.apk)
5. try to reproduce the issue. If you manage to do so, please enable debug logs in KOReader and attach **filtered logs** here.

**Comment by pazos** [comment] 2020-12-23 18:40
@arooni: ping

**Comment by arooni** [comment] 2020-12-25 00:40
hi!

sorry i will get back to this in the next couple of days.  holiday/christmas/family time means i'm not getting as much reading done as i'd like.  

many thanks!

**Comment by arooni** [comment] 2020-12-29 21:30
Here is another ANR: https://gist.github.com/arooni/1d1389623d5acdf5984b04b96bac7a4b ; 

Also I did run this command via bash ```adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F``` but it seems to include a lot of things not relevant.  Am I doing something wrong?

Going to test a few things and update this post when I have more.

**Comment by pazos** [comment] 2020-12-29 21:41
For this bug report you're fine with **enabling debug logs** and using `adb logcat KOReader:* ActivityManager:* *:S`.

ANRs happens when you touch the screen or press buttons while KO is doing **something that cannot be interrupted** and takes **about 5 seconds to complete**. One common action that can trigger an ANR is opening a new *big* e-pub for the first time and touching the screen while you see the "Opening that book" message.

There're no other reasons for ANRs I'm aware other that an unhandled configuration change, which shouldn't happen on a Samsung Tablet.

**Comment by arooni** [comment] 2020-12-29 21:45
> For this bug report you're fine with **enabling debug logs** and using `adb logcat KOReader:* ActivityManager:* *:S`.
> 
> ANRs happens when you touch the screen or press buttons while KO is doing **something that cannot be interrupted** and takes **about 5 seconds to complete**. One common action that can trigger an ANR is opening a new _big_ e-pub for the first time and touching the screen while you see the "Opening that book" message.
> 
> There're no other reasons for ANRs I'm aware other that an unhandled configuration change, which shouldn't happen on a Samsung Tablet.

Maybe the answer is I need to be more patient when booting up koreader or opening a new large epub.

**Comment by pazos** [comment] 2020-12-29 22:01
> Maybe the answer is I need to be more patient when booting up koreader or opening a new large epub.

Yup, that would help. But the opossite also helps. If you find that you're able to reproduce ANRs on certain conditions and you can relate them to your own input events we might end with a list of common tasks that can trigger ANRs on not so patient users :)

There's a possible workaround: ignore input events while doing blocking operations. It is already implemented for the kosync plugin: https://github.com/koreader/koreader/commit/835f9f62c6817a796d560c902e4806be42ef7c5a#diff-f8e023b41718bacd7a310fcd56ca8215de5dfddbc2bb24c3a1ef33067f14993c

It just happens it is a PITA to use it everywhere, but it is possible and would indeed avoid ANRs as input events won't be delivered to the activity.

**Comment by Frenzie** [comment] 2020-12-29 22:15
We could also experiment with reenabling Turbo for networking stuff, given it's been years of improvements and bug fixes since it was disabled because it caused potential issues back in 2014. NB I'm not particularly interested in experimenting with that myself atm; just throwing it out there.

**Comment by oldman63** [comment] 2021-01-02 15:03
Xiaomi Redmi Note 9 Pro
Android 10, MIUI 12
koreader 2020.12 and 2020.11 stable

After switching to Night Mode, the application slows down terribly!

Switching back to Daily mode (Night mode off) will work normally again.

**Comment by NiLuJe** [comment] 2021-01-02 15:36
@oldman63: This should be fixed in today's nightly ;).

**Comment by oldman63** [comment] 2021-01-02 17:00
Thank you!

**Comment by poire-z** [comment] 2021-12-09 17:38
Let's say this is solved by #8501 ? :)

**Closed** 2023-07-06 20:20 UTC
Labels: bug, Android
