### ISSUE TITLE
Koreader corrupts/removes book uuid metadata after device connect via usb after use of wireless 

### ISSUE THREAD

**Issue by kyxap** [koreader/koreader#12068] opened 2024-06-21 19:55 UTC
* KOReader version: [v2024.04-196-gfa4654cdf_2024-06-19/](https://build.koreader.rocks/download/nightly/v2024.04-196-gfa4654cdf_2024-06-19/)
* Device: [Kobo Clara BW](https://ca.kobobooks.com/products/kobo-clara-bw)

#### Steps to reproduce
- Remove root and subfolder metadata
- Send book via wireless connection
- Connect device via usb cable when calibre is open
- Wait till calibre recognize the device (Send button is displayed)
- Verify that `.metadata.calibre` is created in subfolder
```
[
    {
        "title": "Name",
        "authors": [
            "David Name",
        ],
        "lpath": "Name (311).epub",
        "series": null,
        "series_index": null,
        "tags": [
            "Philosophy",
            "Business & Economics",
            "History",
            "Sociology",
            "Politics",
            "Managerial",
            "Accounting"
        ],
        "size": 751214,
        "last_modified": "2024-06-21T12:25:14+00:00",
        "uuid": "d840bffc-c9b9-4043-8424-e4c2a4ff8854"
    }
]
```
- Unmount/Disconnect device
- Connect device via wireless
Expected: Device connected no issue
Actual: Device connected with error, no uploaded book found

Ui error:

```
calibre, version 7.12.0
ERROR: Error: Error communicating with device

Traceback (most recent call last):
  File "calibre\gui2\device.py", line 111, in run
  File "calibre\gui2\device.py", line 565, in _books
  File "calibre\devices\smart_device_app\driver.py", line 57, in _synchronizer
  File "calibre\devices\smart_device_app\driver.py", line 1316, in books
KeyError: 'uuid'
```

And when I look into the file, uuid is removed:
```
[
    {
        "series_index": null,
        "authors": [
            "David Name",
        ],
        "series": null,
        "lpath": "Namer (311).epub",
        "size": 751214,
        "tags": [
            "Philosophy",
            "Business & Economics",
            "History",
            "Sociology",
            "Politics",
            "Managerial",
            "Accounting"
        ],
        "last_modified": "2024-06-21T12:25:14+00:00",
        "title": "Name"
    }
]
```

I was thinking this is calibre bug and they said that calibre or/and calibre driver does not change any files on the book
https://bugs.launchpad.net/calibre/+bug/2070043

Note: for wireless sync im trying use forked version with some fixes: https://github.com/kyxap/koreader-calibre-plugin#readme 

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

```
<Paste crash.log content here>
```
</details>

**Comment by benoit-pierre** [comment] 2024-06-21 20:03
Duplicate of #12062.

**Closed** 2024-06-21 20:03 UTC
Labels: duplicate

**Comment by NiLuJe** [comment] 2024-06-22 06:44
Thanks for the extra details, though ;).

**Comment by kyxap** [comment] 2024-06-22 13:15
Im not sure if it's the same issue, I had that issue since I got device and started to use first night builds after the release. But I could be wrong :) And I can't test it with latest release
