### ISSUE TITLE
PocketBook can not access the Internet

### ISSUE THREAD

**Issue by kimabjorkede** [koreader/koreader#10651] opened 2023-07-06 12:20 UTC
* KOReader version: v2023.06
* Device: PocketBook Touch Lux 3

#### Issue
KOReader can not connect to the Internet.
I can connect to it via SSH locally, but even with the SSH password turned off, it still asks for a password.
#### Steps to reproduce
Try to use RSS, or Wallabag will give errors about not finding websites. I've tried both hostnames and IP-addresses.
##### `crash.log` (if applicable)
The media transfer is broken on my PocketBook, so it's hard to transfer files on and off it. And I don't have a MicroSD card adapter on me right now, so I'll just post pictures of the relevant parts. I'll upload the file later if necessary. 
![20230706_132015](https://github.com/koreader/koreader/assets/10121762/8ad270ff-b39f-4621-ab7f-598b15745abb)

![20230706_132032](https://github.com/koreader/koreader/assets/10121762/37fa7f6d-71b3-481c-be53-7fd4c834db1e)

**Comment by kimabjorkede** [comment] 2023-07-06 14:07
I got SSH working by using an `ecdsa` key instead of `ssh-rsa`.

**Comment by Frenzie** [comment] 2023-07-06 14:16
> I can connect to it via SSH locally, but even with the SSH password turned off, it still asks for a password.

Turned off doesn't quite exist. Empty is still a password.

**Comment by kimabjorkede** [comment] 2023-07-06 14:20
> > I can connect to it via SSH locally, but even with the SSH password turned off, it still asks for a password.
> 
> Turned off doesn't quite exist. Empty is still a password.

Yeah, I understood that now.
The SSH server is too outdated to understand `ssh-rsa`.

If I ping `google.com` via ssh, it translates the hostname into an IP-address, so that's working at least.
RSS and Wallabag still don't work, though.

**Comment by kimabjorkede** [comment] 2023-07-06 15:18
Continued testing shows that KOReader Sync Works (kinda) when logging in without setting a custom URL, and it discovering the server. If I type in the external IP of the server, KOReader asks me to turn on Wi-Fi, even though it's already on, and then it just doesn't do anything.

**Comment by NiLuJe** [comment] 2023-07-06 15:34
IIRC, the PB thing with WiFi is that it sorta works if you start KOReader with the WiFi on, and is completely unreliable otherwise.

Or... something. I just know that WiFi + PB == pain.

**Comment by kimabjorkede** [comment] 2023-07-06 15:38
I've started it with Wi-Fi on pretty much every time.
I don't think that's the issue.

For some reason, KOReader has started crashing when I run Wallabang.
![20230706_173621](https://github.com/koreader/koreader/assets/10121762/ee810b0b-5619-4dd4-b1fe-5568c7cd5599)

**Comment by NiLuJe** [comment] 2023-07-06 15:56
That one is *probably* the InkView vs. OpenSSL conflict, assuming yoiu tried to pull an HTPPS feed.

**Comment by kimabjorkede** [comment] 2023-07-08 17:03
```
07/08/23-18:56:33 INFO  Inhibiting user input 
07/08/23-18:56:33 INFO  Loading plugins from directory: plugins 
ffi.load: sqlite3
07/08/23-18:56:34 INFO  setting zoom mode to page 
07/08/23-18:56:35 INFO  Restoring user input handling 
ping: permission denied (are you root?)
07/08/23-18:57:54 INFO  Inhibiting user input 
07/08/23-18:57:55 INFO  Restoring user input handling 
07/08/23-18:58:00 INFO  Inhibiting user input 
07/08/23-18:58:00 INFO  unwrapped info: Loading news feed list… 
07/08/23-18:58:02 INFO  Restoring user input handling 
07/08/23-18:58:04 INFO  Inhibiting user input 
07/08/23-18:58:04 INFO  unwrapped info: Loading news feed list… 
07/08/23-18:58:05 INFO  Restoring user input handling 
[389:08/07/23 18:58:11] netagent called with parameters < wifi on >
[389:08/07/23 18:58:11] bringing up wifi
[module_on] Found USB dev "0bda:8179". Select WiFi module: "8188eu"
[423:08/07/23 18:58:13] netagent called with parameters < status -q >
[425:08/07/23 18:58:13] netagent called with parameters < connect >
Time To Connect [2190][436:08/07/23 18:58:15] netagent called with parameters < net info >
[448:08/07/23 18:58:15] netagent called with parameters < ping >
07/08/23-18:58:15 INFO  Inhibiting user input 
07/08/23-18:58:36 WARN  No HTTP headers: host or service not provided, or not known 
07/08/23-18:58:36 INFO  Restoring user input handling 
07/08/23-18:58:36 INFO  Inhibiting user input 
Process has been terminated by signal {SIGILL::<unknown>}
07/08/23-18:58:38 INFO  Restoring user input handling 
07/08/23-18:58:44 INFO  Inhibiting user input 
07/08/23-18:58:45 INFO  Restoring user input handling 
[520:08/07/23 18:58:46] netagent called with parameters < ping >
[537] Jul 08 18:59:00 Running in background
ping: permission denied (are you root?)
[541:08/07/23 18:59:16] netagent called with parameters < ping >
[545:08/07/23 18:59:46] netagent called with parameters < ping >
```

**Comment by kimabjorkede** [comment] 2023-07-08 17:16
![scr0002](https://github.com/koreader/koreader/assets/10121762/84fbc80b-8827-4014-8f19-60fa50b3434c)

**Comment by kimabjorkede** [comment] 2023-07-17 19:44
Sorry, I have to close this issue. This is still a problem, but my PocketBook is now dead. (Internal storage is corrupt because of a battery failure. The microSD card slot is dead and the microUSB connector is dead.)

**Comment by rjd22** [comment] 2023-07-19 08:45
Closing this issue for now since there is no actionable device to test this on.

**Closed** 2023-07-19 08:44 UTC
Labels: PocketBook, firmware, help-wanted

**Comment by foozzi** [comment] 2024-04-06 02:39
@rjd22 
same issues, can't do anything in internet

pocketbook InkPad4

```
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/05/24-22:26:48
 [*] Version: v2024.03.1

ffi.load: libs/libutf8proc.so.3
ffi.load: blitbuffer
ffi.load: inkview
04/05/24-22:26:49 INFO  SoftwareVersion:  U743g.6.8.2015 
ffi.load: inkview
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
Atached mp shm: id 0 addr a6f5a000 size 17624
attach_shm: mtfb key=251348143 size=2808848
Atached mtfb shm: id 9000b addr a3e68000 size 2808848
-------------------------
Starting task - koreader.app
flags: 0x00000080
gpid: 1199
fb=0xa3e68000 xres=1404 yres=1872 scanline=1408 vdepth=8 orient=0
-------------------------
attach_shm: mttempfb key=251308714 size=2665728
Atached mttempfb shm: id 8001 addr a3bdd000 size 2665728
Atached mqueue: id 8001
[hw_setglobalkeymask] gka0 = 4000000; gka1 = c800002; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 0 10000 0 10000 0
attach_shm: mtfb key=251348143 size=2808848
Atached mtfb shm: id 9000b addr a25c4000 size 2808848
ffi.load: librt.so
ffi.load: inkview
[1207 : ./luajit] (hw_nextevent)mq_receive ret -1 (Resource temporarily unavailable)
ffi.load: inkview
04/05/24-22:26:49 INFO  initializing for device PBInkPad4 
04/05/24-22:26:49 INFO  framebuffer resolution: {
  h = 1872,
  w = 1404
} --[[table: 0xa6aaf4d8]] 
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: sqlite3
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
04/05/24-22:26:51 INFO  UIManager: No dialogs left to show 
04/05/24-22:26:51 INFO  Tearing down UIManager with exit code: 0 
04/05/24-22:26:51 INFO  Loading plugins from directory: plugins 
04/05/24-22:26:52 WARN  Terminal: cannot open /dev/ptmx: Permission denied 
04/05/24-22:26:52 WARN  Terminal: Device doesn't meet some of the plugin's prerequisites 
[1207 : ./luajit] (hw_ban_suspend)BAN SUSPEND sec[5]
[1207 : ./luajit] (hw_ban_suspend)BAN SUSPEND sec[5]
[1207 : ./luajit] (hw_ban_suspend)BAN SUSPEND sec[5]
ping: permission denied (are you root?)
04/05/24-22:31:21 INFO  Inhibiting user input
```

**Comment by liskin** [comment] 2024-04-06 13:16
@foozzi can you try if https://github.com/koreader/koreader/pull/11601 or https://github.com/koreader/koreader/issues/10183#issuecomment-2021018043 helps?

**Comment by foozzi** [comment] 2024-04-06 16:00
> @foozzi can you try if #11601 or [#10183 (comment)](https://github.com/koreader/koreader/issues/10183#issuecomment-2021018043) helps?

I don't know, I will try it.

Anyway, will fixes be in the future release?

**Comment by liskin** [comment] 2024-04-06 16:24
> Anyway, will fixes be in the future release?

If I manage to get it reviewed and merged, it will. People testing the fix and saying it resolves the issue is somewhat likely to help get it merged 😉
