### ISSUE TITLE
FR: Chinese keyboard layout support

### ISSUE THREAD

**Issue by caiwangqin** [koreader/koreader#9421] opened 2022-08-09 06:26 UTC
![Screenshot_20220809_142048_org koreader launcher](https://user-images.githubusercontent.com/49549657/183579119-adc6a3d7-2e4a-4de1-918c-810ddcea0008.jpg)

Could you consider add Chinese pinyin keyboard layout, so than user can input Chinese characters for search, thank you very much!

**Comment by cyphar** [comment] 2022-08-09 22:09
Because the KOReader keyboard system requires you to implement the keyboard from scratch, we would need a native Chinese speaker (and someone familiar with how Chinese IMEs work) as well as have a freely licensed dictionary to use for character lookups. This is something we ideally would like for Japanese input as well (at the moment it's kana-only) but it would be just as difficult for Japanese as well -- I suspect a better solution would be to allow using the native keyboard (but I have been told this is not possible with KOReader's current architecture).

**Comment by caiwangqin** [comment] 2022-08-10 04:54
allow using the native keyboard would be great!

**Comment by pazos** [comment] 2022-08-10 10:47
Duplicate of #1938

@caiwangqin @cyphar : lets move conversation there :)

**Closed by pazos** 2022-08-10 10:47 UTC
Labels: enhancement
