### ISSUE TITLE
FR: Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [koreader/koreader#10532] opened 2023-06-03 08:20 UTC
Hi, please support the Android 13 Themed App Icons feature.

![Screenshot_2023-06-03-11-49-49-910_de mm20 launcher2 release](https://github.com/koreader/koreader/assets/23485114/f78f22bc-07c2-41a2-8132-dd4e0bc92015)

**Comment by pazos** [comment] 2023-06-03 11:22
Duplicate of https://github.com/koreader/android-luajit-launcher/issues/409 (also yours), which I transferred to the proper repo where changes need to be implemented.

Please double check for already opened tickets (double points if it's yours :)

**Closed by pazos** 2023-06-03 11:22 UTC
Labels: enhancement
