### ISSUE TITLE
Dictionary loses content

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#1234] opened 2014-11-23 13:22 UTC
Sometimes the dictionary does not find any words anymore.
Had this yesterday alone 2 times.
This is not an issue of the dictionary, the dictionary finds the same words after restart.
Koreader did not crash after that (as I thought) when I continued reading, but nothing could get the words back to the dictionary, not changing books or entering the File Manager. Just after a Koreader restart everything was fine again.
(I know there was an issue for this but since this just got closed I and I can't reopen issues I had to open a new one).

**Comment by chrox** [comment] 2015-04-01 11:11
Seems no progress. Close this now.

**Comment by WS64** [comment] 2015-04-01 13:27
Why close open issues without solution?

**Comment by hwhw** [comment] 2015-04-02 07:58
I guess it got under the truck when cleaning up (old/stale) issues. Feel free to re-open if it's still relevant.

**Comment by WS64** [comment] 2015-04-02 11:41
I'll check.
However, there is no "reopen" to see anywhere. I'll have to open a new issue in case it is not fixed.

**Comment by NiLuJe** [comment] 2015-04-02 11:50
Just to check that it can be done when you're a member of the org. ;p. Haven't actually checked the issue in question, feel free to re-close if fixed ;).

**Comment by chrox** [comment] 2015-04-06 10:43
Sorry for the late reply. I was on vacation these days. My point is that ordinary developers have limited mind capacity that could only hold up to 30 issues in their head at the same time. More issues than the limitation on the issue tracker will only distract the developers from solving the real important issues. 

Github provides the issue assignment mechanism to divide the issue list for individual developers so that each one could focus on their 30 issues. But this way doesn't apply to the koreader project because it's so loosely organized that no one is obligated to solve any one issue.

My workaround for the 30-issues-limitation issue is to close some less important or less active issues regularly so that we can focus on more important ones. And of course closed unresolved issues can be reopened by complaints from the OP which may lead to a discussion and regain the minimum activity for existence. Those forever closed unresolved issues are actually won't-fix issues that are buried into the software except someday there is a new issue opened for it.

My consideration for closing this one was that it's probably device specific because it cannot be reproduced in neither kindle or pocketbook or some other Kobo devices. And it probably is configuration specific on your (@WS64) device only, for example the sdcard may be mounted read only or you use a specific KSM version with specific configuration. Overall, it's not a generic problem on koreader so it's not important. As there was no follow-up for several months it could be closed.

**Comment by WS64** [comment] 2015-04-06 13:44
I don't think it is configuration specific, or, if it is, it applies to both my Kobo Mini and my Kobo Aura. I am not sure if it also applies to the Pocketbook since Koreader is still too unstable to be used there. (Especially way too slow when opening books, I can't wait 20 minutes for bigger books to open)
It might be solved though indeed, I could not reproduce it since the latest release, and usually it ALWAYS happened after 24 hours or so. Leave this issue open for a few more days and I will close it if it does not happen anymore.

**Comment by WS64** [comment] 2015-04-07 15:37
I'm sorry to report that this issue is not solved...
I again have reached the point where the dictionary does not find anything. I'll have to close Koreader completely and restart it to make it work again. Everything else works...

**Comment by chrox** [comment] 2016-07-01 16:09
No progress, closing this now. Please reopen this if you still have this problem with the latest nightly build.

**Closed** 2016-07-01 16:16 UTC
Labels: bug, Kobo
