### ISSUE TITLE
Implement basic wayland support

### ISSUE THREAD

**Issue by Estebiu** [koreader/koreader#9472] opened 2022-09-03 11:16 UTC
Koreader supports only the x11 at the time being, not the newer wayland one. This results in some problems and incompatibilities when running under with the xwayland compatibility tool.
For example, scaling on HiDPI displays results in blurry text and gestures aren't as smooth as they should. 
I've already tried setting "SDL_VIDEODRIVER=wayland" to use wayland as the backend for koreader but that doesn't work at all (but fixes the problems I had with osu!lazer, so SDL is working as intended).
So, please, add support to wayland when you have time. I would be extremely gratefull.

**Comment by Frenzie** [comment] 2022-09-03 11:20
Duplicate of #8630.

**Closed by Frenzie** 2022-09-03 11:20 UTC
Labels: enhancement, duplicate
