### ISSUE TITLE
Some eBooks are rendered with a "?" at each space. [Kobo Aura H2O]

### ISSUE THREAD

**Issue by UnicodeAlt255** [koreader/koreader#1706] opened 2015-11-05 23:54 UTC
I did not have this problem until I updated to version " koreader-stable-v2015.11 ". I was previously using an older, 2014 version.

This happened to only some books. I viewed the epubs in my device directly with an epub viewer and they seemed fine on Windows.

![img_20151105_154339](https://cloud.githubusercontent.com/assets/12755239/10985261/ad8a5696-83d4-11e5-98c2-6ff8ad61d42d.jpg)
![img_20151105_154230](https://cloud.githubusercontent.com/assets/12755239/10985265/b23dd9ec-83d4-11e5-9dc1-aecb921741b3.jpg)

**Comment by houqp** [comment] 2015-11-06 07:19
Was this working under 2014 version? It might be a encoding issue. Can you send us the file so we can try reproduce on our side?

**Comment by UnicodeAlt255** [comment] 2015-11-06 07:54
So far I've factory resetted and firmware updated, reinstalled KBStartMenu_08 and koreader-kobo-arm-linux-gnueabihf-v2015.11-stable, and even updated Calibre. 

I sent over the single file that I had problems with, using Calibre's "Send to device": "/mnt/onboard/.Library/Library/Fiction/Fantasy/ASOIAF - 03 - A Storm of Swords - George R. R. Martin.kepub.epub", and the first time I opened it up there were no problems. But on the second try it again showed a "?" for each space.

I've zipped the entire drive that shows up when I connect Kobo to my Windows 10 PC: 
https://mega.nz/#!fwsVlCxR!31d4GpRzdvtplvGiVp3NJdEqlVjPIHUM_u1-967ZA3o

**Comment by Markismus** [comment] 2015-11-06 11:08
I had this, too! It occurred when I used a font, that apparently didn't work well with the opened epub. I switched fonts and it was gone.

**Comment by KenMaltby** [comment] 2015-11-06 13:19
I wonder if a "kepub" feature is not being properly handled/ignored?  Perhaps turning Embedded Style Off and/or the "clear all external styles" settings might help.

**Comment by UnicodeAlt255** [comment] 2015-11-07 02:52
Not sure how to turn Embedded Style Off, but I've tried changing font and "clearing all external styles" and they didn't help. The only way I know of fixing this problem is by reinstalling koreader or resending the ebook through calibre. 
I think the fact that this problem occurs after opening it up one time without problems means something.

**Comment by frankyifei** [comment] 2015-11-09 13:07
try change your default font or disable css
This happens to my epubs sometimes. I think your epub defines some font that does not exist.

**Comment by trekk2810** [comment] 2015-11-10 19:57
I had this on my Glo HD. Changing the **font-size** in the book solved the issue. Changing the font-size back to default also brought the "?" back.

**Comment by UnicodeAlt255** [comment] 2015-11-11 07:45
Thanks trekk2810, that seems to work.

**Comment by frankyifei** [comment] 2015-11-12 07:55
It seems like the bug is in crengine's font size cache.

**Comment by UnicodeAlt255** [comment] 2015-11-12 09:02
I've already uploaded everything to Mega above, but here's a direct link to the epub only:
https://mega.nz/#!DoljQQaB!2-tipYvVgBYKLWubP8K2Nva0ADdbGY0ldRoVuHqrLxA

I'm concerned about sharing copyrighted material, so the link won't last long.

**Comment by frankyifei** [comment] 2015-12-22 06:27
I've reproduce this problem with one of my own book.  this font could solve the problem, put it in koreader/fonts/noto
[NotoSansCJK-Regular.zip](https://github.com/koreader/koreader/files/69346/NotoSansCJK-Regular.zip)

**Comment by chrox** [comment] 2016-02-04 04:47
Closing this now since it's already fixed.

**Closed by chrox** 2016-02-04 04:47 UTC
