### ISSUE TITLE
Hide UI when restroring Wi-FI connection on wake up

### ISSUE THREAD

**Issue by avsej** [koreader/koreader#6534] opened 2020-08-20 09:36 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
After recent Wi-Fi fix, koreader always draws a lot of UI boxes when restoring wireless connection when I resume device. It is really annoying.

**Describe the solution you'd like**
I'd like to have it like previously, when UI only shown when I'm actively select UI components. Like if I open OPDS browser, and there is no connection, then it should show all those message boxes.

Current solution is also bad, because when it cannot connect Wi-Fi, the message "Error connecting to the network" is not closed by timeout and staying until I tap somewhere.

New UX is really bad, because it make it harder to use koreader for its essential task: reading a book.

I would like that if I set "Restore Wi-Fi connection on resume" to ON, and "Action when Wi-Fi is off:" to "turn on", then no message boxes are shown at all when I resume the device. I'm resuming the device because I want to read a book, not because I want to check Wi-Fi connection.

**Comment by avsej** [comment] 2020-08-20 09:41
Now Wi-Fi on Cervantes is really broken, please roll it back to previous state when everything was working.

**Comment by avsej** [comment] 2020-08-20 09:44
It does not allow to put the device to sleep mode until the network disconnected, keep drawing all those weird UI windows on the screen saver, and when I turn it on again, it mess up with the state, tries to authenticate and disconnect until wpa_supplicant fails.

**Comment by avsej** [comment] 2020-08-20 09:56
Why there is no "keep it off" option for "Action when Wi-Fi is off"?? It keeps asking me for Wi-Fi when I exit to file browser? Why the networking became so broken in recent release?

**Comment by Galunid** [comment] 2020-08-20 10:08
`Network -> Action when Wi-Fi is off: prompt` should make it behave as it always have. Additionally disabling `Progress sync -> Auto sunc now and in the future` should prevent asking about wifi on closing document

**Comment by Galunid** [comment] 2020-08-20 10:18
Caused by https://github.com/koreader/koreader/pull/6489

**Comment by NiLuJe** [comment] 2020-08-20 11:12
(wifiAsyncRestore is UI-less on Kobo, might also be something worth looking into?).

**Comment by poire-z** [comment] 2020-08-20 11:21
> Now Wi-Fi on Cervantes is really broken, please roll it back to previous state when everything was working.
> Why the networking became so broken in _recent release_?

I guess because nobody using Cervantes regularly has been testing nightly builds.
So, help us avoid that in the future and please switch to the dev channel so you can report earlier, and avoid us releasing untested stuff on the non-kobo/kindle/android devices.

**Comment by avsej** [comment] 2020-08-20 11:27
I'm on the nightly builds and it seems like it has been broken just recently. I'm updating it every 1-2 days. The patch has been merged just 3 days ago, I don't think it was enough time to notice it.

**Comment by Frenzie** [comment] 2020-08-20 11:34
Reverted in https://github.com/koreader/koreader/pull/6535

**Closed by Frenzie** 2020-08-20 11:34 UTC
Labels: bug
