### ISSUE TITLE
Koreader crashes while checking up dictionaries

### ISSUE THREAD

**Issue by enigmasc** [koreader/koreader#11959] opened 2024-06-02 10:24 UTC
* KOReader version: v2024.04-134-g8977e5e12_2024-06-01
* Device: Kobo Touch

Koreader crashes when checking up words from dictionaries. At first it works just fine, but when I reach the third or the fourth dictionary, the bomb sign pops up and the program restarts. v2024.04-132-g8960f3d47_2024-06-01 has the same issue.

Help!

[crash.zip](https://github.com/user-attachments/files/15524941/crash.zip)

**Comment by benoit-pierre** [comment] 2024-06-02 16:30
Relevant portion of the log:
```
warning: html: cannot load image src='/images/mini-speaker.png'
./luajit: ./ffi/mupdf.lua:78: cannot access page tree: cannot find builtin font with name 'Symbol' (4)
stack traceback:
	[C]: in function 'error'
	./ffi/mupdf.lua:78: in function 'merror'
	./ffi/mupdf.lua:200: in function 'getPages'
	frontend/ui/widget/htmlboxwidget.lua:74: in function 'setContent'
	frontend/ui/widget/dictquicklookup.lua:853: in function 'update'
	frontend/ui/widget/dictquicklookup.lua:1043: in function 'changeDictionary'
	frontend/ui/widget/dictquicklookup.lua:970: in function 'changeToNextDict'
	frontend/ui/widget/dictquicklookup.lua:451: in function 'callback'
	frontend/ui/widget/buttontable.lua:81: in function 'callback'
	frontend/ui/widget/button.lua:472: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:915: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1446: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1546: in function 'handleInput'
	frontend/ui/uimanager.lua:1590: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x000140c
```

**Comment by benoit-pierre** [comment] 2024-06-02 22:04
That's a lot of dictionaries :P 
```
06/02/24-17:40:44 DEBUG Getting list of dictionaries 
06/02/24-17:40:44 DEBUG found 57 dictionaries 
```

Reproducible with:
```diff
 frontend/apps/reader/modules/readerdictionary.lua | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git i/frontend/apps/reader/modules/readerdictionary.lua w/frontend/apps/reader/modules/readerdictionary.lua
index 4e119b2fe..3986152ed 100644
--- i/frontend/apps/reader/modules/readerdictionary.lua
+++ w/frontend/apps/reader/modules/readerdictionary.lua
@@ -997,6 +997,15 @@ end
 
 function ReaderDictionary:showDict(word, results, boxes, link)
     if results and results[1] then
+        word = 'taiwan'
+        results = {
+            {
+                definition = "\n<b>Tai</b>‧<b>wan</b> /ˌtaɪˈwɑːn/<br>an island off the southeast coast of China. Population: 23,174,294 (2007). Taiwan, which was formerly called Formosa, has experienced rapid economic development since the 1950s and has many factories.<br><b>—Taiwanese</b> /ˌtaɪwəˈniːz◂/ <i> noun</i><i>, adjective</i>",
+                dict = "Longman Dictionary of Contemporary English",
+                is_html = true,
+                word = "Taiwan"
+            },
+        }
         logger.dbg("showing quick lookup window", #DictQuickLookup.window_list+1, ":", word, results)
         self.dict_window = DictQuickLookup:new{
             ui = self.ui,
```

**Comment by mergen3107** [comment] 2024-06-03 01:53
@benoit-pierre 
1) I was able to reproduce this on -134 nightly (installed via KOReader).
2) Then I did and rebuilt -136 including your fix above.

All good now!

I don't know how helpful it might be, but attached is the crash.log with me looking up for word `скамье` and going through 34 entries, most of which are just results of fuzzy search. 

[crashlog_with_fix_base1812.txt](https://github.com/user-attachments/files/15527904/crashlog_with_fix_base1812.txt)

**Comment by Frenzie** [comment] 2024-06-03 06:51
> Reproducible with:

Is it the IPA?

**Comment by benoit-pierre** [comment] 2024-06-03 07:00
> > Reproducible with:
> 
> Is it the IPA?

Nope, this little guy: `◂` (which incidentally is not in our "Symbol" font).

**Comment by NiLuJe** [comment] 2024-06-09 17:33
Ought to be fixed via https://github.com/koreader/koreader-base/pull/1815, bumped in https://github.com/koreader/koreader/commit/206de629d82904a078d16f129ec8638eb862d78d

**Comment by enigmasc** [comment] 2024-06-12 10:53
After updating to v2024.04-172-g9724dcdf4_2024-06-12, it's all good now. Thank you guys!

**Comment by mergen3107** [comment] 2024-06-12 13:14
It seems to be the same error as in the OP:
```
./luajit: ./ffi/mupdf.lua:78: cannot access page tree: cannot find builtin font with name 'Symbol' (4)
stack traceback:
	[C]: in function 'error'
	./ffi/mupdf.lua:78: in function 'merror'
	./ffi/mupdf.lua:200: in function 'getPages'
	frontend/ui/widget/htmlboxwidget.lua:74: in function 'setContent'
	frontend/ui/widget/dictquicklookup.lua:853: in function 'update'
	frontend/ui/widget/dictquicklookup.lua:1043: in function 'changeDictionary'
	frontend/ui/widget/dictquicklookup.lua:970: in function 'changeToNextDict'
	frontend/ui/widget/dictquicklookup.lua:451: in function 'callback'
	frontend/ui/widget/buttontable.lua:81: in function 'callback'
	frontend/ui/widget/button.lua:472: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:915: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1446: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1546: in function 'handleInput'
	frontend/ui/uimanager.lua:1590: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x000140cd
warning: UNHANDLED EXCEPTION!
argument error: cannot find builtin font with name 'Symbol'
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 06/12/24 @ 20:48:37)
Running FW 3.19.5761 on Linux 2.6.35.3-850-gbc67621+ (#617 PREEMPT Mon Apr 22 11:07:47 CST 2013)
Attempting to restart KOReader . . .
!!!!
```

**Closed** 2024-06-13 20:01 UTC
Labels: MµPDF

**Comment by enigmasc** [comment] 2024-06-14 21:29
Dictionary does not crash now, but some definitions are lost in search results. 
v.2024.04-121 gives me this: 
![2024-06-15_045504](https://github.com/koreader/koreader/assets/74174080/d045a8a8-dfe6-4603-9c9f-7e50b1fc4bce)
v2024.04-174 shows only first part:
![2024-06-15_045430](https://github.com/koreader/koreader/assets/74174080/83e6885e-8aa2-488e-97e6-82723e6198b4)

 
[stardict.zip](https://github.com/user-attachments/files/15844052/stardict.zip)

**Comment by benoit-pierre** [comment] 2024-06-14 21:33
Please, when you mention versions, don't truncate the most important part: the commit hash.

**Comment by enigmasc** [comment] 2024-06-14 21:40
Ok, it is koreader-kobo-v2024.04-174-ge3237ef8e_2024-06-13, and I was wrong about the missings results. They are still there, but display formats are not right.

**Comment by benoit-pierre** [comment] 2024-06-14 21:46
> Ok, it is koreader-kobo-v2024.04-174-ge3237ef8e_2024-06-13,

Thanks!

> and I was wrong about the missings results. They are still there, but display formats are not right.

Could be the same issue mentionned by @poire-z [here](https://github.com/koreader/koreader-base/pull/1586#issuecomment-2143459278) and [there](https://github.com/koreader/koreader-base/pull/1586#issuecomment-1640637412).

**Comment by benoit-pierre** [comment] 2024-06-14 21:52
And v.2024.04-121 is:
```bash
▸ git describe --tags "origin/master$(python -c "print('^' * $(($(git rev-list --count v2024.04..origin/master)-121)))")"`
```
I'm surprised there's no easier revspec format to do that.

**Comment by NiLuJe** [comment] 2024-06-14 22:07
> I'm surprised there's no easier revspec format to do that.

`~n`  (e.g., `~12`) is easier on humans, but it's not necessarily easier to generate programmatically ;p.

**Comment by NiLuJe** [comment] 2024-06-14 22:09
> > I'm surprised there's no easier revspec format to do that.
> 
> `~n` (e.g., `~12`) is easier on humans, but it's not necessarily easier to generate programmatically ;p.

Or... is it? ;D

`git describe --tags "origin/master$(printf '~%d' $(($(git rev-list --count v2024.04..origin/master)-121)))"`

**Comment by benoit-pierre** [comment] 2024-06-14 22:10
Here's the result definition for `taiwan`:
```html
<center>
  <font color=green size=+2>taiwan</font>
</center>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://臺\" style=\"text-decoration:none\">臺</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>&nbsp;Words&nbsp;</b>
        </td>
        <td align=left>
          <font size=-1 color=\"#999999\">8.</font> 臺灣 <font size=-1>[<i>tai<font color=#888888>2</font>wan<font color=#888888>1</font>
            </i>]</font>, n., Formosa, <font color=blue>Taiwan</font>.<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://坪\" style=\"text-decoration:none\">坪</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>N. </b>
        </td>
        <td align=left>
          <font color=green size=-1>
            <b>(2)</b>
          </font>
          <font size=+2>&nbsp;</font>A Japanese measure of area, used in <font color=blue>Taiwan</font>, = roughly 6×6 ft.;<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://幣\" style=\"text-decoration:none\">幣</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>N. </b>
        </td>
        <td align=left>Currency, coins: 日幣，英幣，新臺幣 Japanese, English, New <font color=blue>Taiwan</font> currency;<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://兄\" style=\"text-decoration:none\">兄</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>&nbsp;Words&nbsp;</b>
        </td>
        <td align=left>
          <font size=-1 color=\"#999999\">3.</font> 兄臺 (usu. 兄臺) <font size=-1>[<i>xiong<font color=#888888>1</font>tai<font color=#888888>2</font>
            </i>]</font>, n., (in letters to a man, court.) you: 兄臺何時來臺 when are you coming to <font color=blue>Taiwan</font>?<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://甲\" style=\"text-decoration:none\">甲</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>N. </b>
        </td>
        <td align=left>
          <font color=green size=-1>
            <b>(5)</b>
          </font>
          <font size=+2>&nbsp;</font>A unit of land measure in <font color=blue>Taiwan</font> equal to 0.96992 hectare.<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://胞\" style=\"text-decoration:none\">胞</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>N. </b>
        </td>
        <td align=left>山胞 aboriginal compatriots (in <font color=blue>Taiwan</font>).<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://新\" style=\"text-decoration:none\">新</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>Adj. </b>
        </td>
        <td align=left>新臺幣 (NT) new <font color=blue>Taiwan</font> currency;<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://之\" style=\"text-decoration:none\">之</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>Prep. </b>
        </td>
        <td align=left>used largely in mod. Chin. writing where there are several “of's”, 之 may replace 的 for variation or dropped: thus “the development of rural education of <font color=blue>Taiwan</font>” may be 今日臺灣（的）鄉村教育之發展 or 的發展;<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://斤\" style=\"text-decoration:none\">斤</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>N. </b>
        </td>
        <td align=left>
          <font color=green size=-1>
            <b>(2)</b>
          </font>
          <font size=+2>&nbsp;</font>A measure of weight equal to 16 ounces: 臺斤 <font color=blue>Taiwan</font> catty (＝600 grams);<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://拜\" style=\"text-decoration:none\">拜</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <b>&nbsp;Words&nbsp;</b>
        </td>
        <td align=left>
          <font size=-1 color=\"#999999\">1.</font> 拜拜 <font size=-1>[<i>bai<font color=#888888>4</font>bai<font color=#888888>4</font>
            </i>]</font>, n., (in <font color=blue>Taiwan</font>) religious festival.<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
<p>
<table width=98%>
  <tr>
    <td valign=top align=center width=10%>
      <b>
        <a href=\"bword://臺\" style=\"text-decoration:none\">臺</a>
      </b>
    </td>
    <td>
      <table border=1 width=100% background==/Img/Bg/parchm1b.jpg>
        <td width=15% align=center>
          <center>
            <font size=-1 color=#cc3366>&nbsp;1393</font>
            <font size=-1 color=#cc9966>C</font>
            <font size=-1 color=#cc3366>50&nbsp;</font>
            <br>
            <font size=-2 color=#999999>&nbsp;93.30/30&nbsp;</font>
          </center>
        </td>
        <td align=left>
          <font color=green size=-1>ㄊㄞˊ</font> <font >[<i>tai<font color=#888888>2</font>
            </i>]</font>. [Oft. used for phonetic value in place of<a href=\"bword://臺\" style=\"text-decoration:none\">臺</a>, such as<a href=\"bword://臺\" style=\"text-decoration:none\">臺</a>
            <a href=\"bword://灣\" style=\"text-decoration:none\">灣</a> <font color=blue>Taiwan</font>]<br>
        </td>
  </tr>
      </table>
    </td>
    </tr>
</table>
```

**Comment by benoit-pierre** [comment] 2024-06-14 22:10
> > > I'm surprised there's no easier revspec format to do that.
> > 
> > 
> > `~n` (e.g., `~12`) is easier on humans, but it's not necessarily easier to generate programmatically ;p.
> 
> Or... is it? ;D
> 
> `git describe --tags "origin/master$(printf '~%d' $(($(git rev-list --count v2024.04..origin/master)-121)))"`

It's easier, yes: `git describe --tags "origin/master~$(($(git rev-list --count v2024.04..origin/master)-121))"`

**Comment by benoit-pierre** [comment] 2024-06-14 22:12
This might be easier: `git rev-list --reverse v2024.04..origin/master | sed -n '121p'`

**Comment by Frenzie** [comment] 2024-06-14 22:19
That's what I was just about to say (give or take writing it as `head -n 121 | tail -n 1`).

**Comment by enigmasc** [comment] 2024-06-19 02:30
Anyone working on the dispaly issue?
