### ISSUE TITLE
FR: add icon in file browser for books already added to Favorite list

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#7699] opened 2021-05-16 14:25 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
I think, it can be implemented like icon (triangle at right bottom of the file detail row) for set bookmarks.

**Describe the solution you'd like**
Add "star" icon to file browser to books which are added to *Favorite list* so it is clear if they are in it. My idea for icon placement is on picture below.
![Koreader_favorite_icon suggestion](https://user-images.githubusercontent.com/29783895/118400233-0d878400-b661-11eb-8f01-56979596db16.jpg)

**Comment by poire-z** [comment] 2021-05-16 14:39
Duplicate of #6054.

**Closed** 2021-05-18 19:15 UTC
Labels: duplicate, enhancement
