### ISSUE TITLE
PocketBook Inkpad 3 Pro: Everything is weird and slow

### ISSUE THREAD

**Issue by kindfulkirby** [koreader/koreader#5550] opened 2019-10-31 06:02 UTC
* KOReader version: 2019.10
* Device: PocketBook Inkpad 3 Pro

#### Issue
When I open KOReader, I get the popup with the circled i and it says it's loading `./help/quickstart-en-v2019.10.html`.
Then nothing happens.
After a few minutes, the Inkpad's LED goes out, and a while later it turns off (as usual).

_Update_: KOReader shows up in the Inkpad's task manager, and when I use it to switch to KOReader, it just shows a blank screen.

#### Steps to reproduce

Open KOReader on Inkpad 3 Pro.

##### `crash.log`
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 10/31/19-06:08:29
 [*] Version: v2019.10

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
10/31/19-06:08:29 INFO  SoftwareVersion:  U740-2.5.20.1155
10/31/19-06:08:29 INFO  Blacklisting the C BB on this device
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
PB FB: smem_len    : 2637824
PB FB: line_length : 1872
PB FB: xres        : 1872
PB FB: xres_virtual: 1872
PB FB: yres        : 1404
PB FB: yres_virtual: 1404
PB FB: bpp         : 8
PB FB: xres_virtual -> 1888
PB FB: yres_virtual -> 1408
PB FB: line_length -> 1888
PB FB: yres_virtual => 1408
PB FB: line_length <- 1872
PB FB: xres_virtual <- 1872
PB FB: yres_virtual <- 1404
FB: computed size: 2637824
FB: id           : 
FB: smem_len     : 2637824
FB: line_length  : 1872
FB: xres         : 1872
FB: xres_virtual : 1872
FB: yres         : 1404
FB: yres_virtual : 1404
FB: bpp          : 8
Atached mp shm: id 0 addr a46c3000 size 21736
epdc_default_init
epdc_default_rotate: w=1872 h=1404 scan=1872 mem=2637824
attach_shm: mtfb key=251331668 size=2808852
Atached mtfb shm: id 98009 addr a4191000 size 2808852
-------------------------
The task - koreader.app fb 0xa4191000
 xres=1872 yres=1404 scanline=1872 vdepth=8 orient=1
-------------------------
attach_shm: ref key=2130378752 size=2635776
Atached ref shm: id 8001 addr a3477000 size 2635776
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800000; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 0 10000 18720000 -10000 0
ffi.load: inkview
10/31/19-06:08:29 INFO  initializing for device PBInkPad3Pro
10/31/19-06:08:29 INFO  framebuffer resolution: {
    ["h"] = 1872,
    ["w"] = 1404
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
10/31/19-06:08:30 INFO  opening file ./help/quickstart-en-v2019.10.html
10/31/19-06:08:30 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
ffi.load: z
ffi.load (assisted searchpath): ./libs/libz.so.1
ffi.load: sqlite3
10/31/19-06:08:30 INFO  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
10/31/19-06:08:30 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
10/31/19-06:08:30 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
10/31/19-06:08:30 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
10/31/19-06:08:30 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
10/31/19-06:08:30 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
10/31/19-06:08:30 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
10/31/19-06:08:30 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
10/31/19-06:08:30 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
10/31/19-06:08:31 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
[1114 : ./luajit] (iv_poweroff_timer)
Power off time has come...
```

**Comment by kindfulkirby** [comment] 2019-10-31 19:42
Well, on a whim I tried installing the previous version (2019.09) and it works!

… except it doesn't always react when I tap to flip to the next page, and twice now it completely froze the whole device, only a hard reboot brought it back. :(

Is there any way to check if the device itself is malfunctioning? ^^"

**Comment by NiLuJe** [comment] 2019-10-31 21:19
Can you double-check with the current nightly?

**Comment by kindfulkirby** [comment] 2019-11-01 08:22
Yeah, this whole thing make no sense. I tried a few other books yesterday (but not extensively) and they all worked, so the freezing might just be a broken book. I'll do some more thorough experiments later today.

**Comment by kindfulkirby** [comment] 2019-11-01 10:06
Okay, latest nightly *loads*, I can no longer get it to freeze, but it seems to only react to third tap now!
If I tap the page to turn it, the LED comes on but nothing happens, tap it again, same result, tap it a third time, the page turns (and only be one page). This is the same across most - if not all files.

It even takes three taps to get the menus to appear, but once in the menu it works normally, unless I try to change something in the page layout, in which case it takes anywhere between 10 and maybe 40 seconds for it to react to any further taps (might just be that it's very busy).

*After* opening the menu the page turning works fine, strangely enough!

**Comment by kindfulkirby** [comment] 2019-11-01 11:38
Right now it's every second tap. I've also tried the page-turn buttons, same result as tapping.

The log looks normal except for a lot of lines like

```
source page (0,0) - (611,791)
source page bgcolor 192
```

or

```
source page (0,0) - (2036,3055)
source page bgcolor 192
```

**Comment by kindfulkirby** [comment] 2019-11-01 11:48
Just now it was working only on every second tap (or page-turn button push, makes no difference), I tried a different file, and it worked normally until it froze and I had to do a hard reboot, here's the log of that:

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/01/19-12:41:53
 [*] Version: v2019.10-27-geb8795e_2019-11-01

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
11/01/19-12:41:53 INFO  SoftwareVersion:  U740-2.5.20.1155
11/01/19-12:41:53 INFO  Blacklisting the C BB on this device
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
PB FB: smem_len    : 2637824
PB FB: line_length : 1872
PB FB: xres        : 1872
PB FB: xres_virtual: 1872
PB FB: yres        : 1404
PB FB: yres_virtual: 1404
PB FB: bpp         : 8
PB FB: xres_virtual -> 1888
PB FB: yres_virtual -> 1408
PB FB: line_length -> 1888
PB FB: yres_virtual => 1408
PB FB: line_length <- 1872
PB FB: xres_virtual <- 1872
PB FB: yres_virtual <- 1404
FB: computed size: 2637824
FB: id           : 
FB: smem_len     : 2637824
FB: line_length  : 1872
FB: xres         : 1872
FB: xres_virtual : 1872
FB: yres         : 1404
FB: yres_virtual : 1404
FB: bpp          : 8
Atached mp shm: id 0 addr a4726000 size 21736
epdc_default_init
epdc_default_rotate: w=1872 h=1404 scan=1872 mem=2637824
attach_shm: mtfb key=251333438 size=2808852
Atached mtfb shm: id 128009 addr a41f4000 size 2808852
-------------------------
The task - koreader.app fb 0xa41f4000
 xres=1872 yres=1404 scanline=1872 vdepth=8 orient=1
-------------------------
attach_shm: ref key=2130378752 size=2635776
Atached ref shm: id 8001 addr a34da000 size 2635776
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800000; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 0 10000 18720000 -10000 0
ffi.load: inkview
11/01/19-12:41:53 INFO  initializing for device PBInkPad3Pro
11/01/19-12:41:53 INFO  framebuffer resolution: {
    ["h"] = 1872,
    ["w"] = 1404
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
11/01/19-12:41:54 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
ffi.load: z
ffi.load (assisted searchpath): ./libs/libz.so.1
ffi.load: sqlite3
11/01/19-12:41:54 INFO  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
11/01/19-12:41:54 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
11/01/19-12:41:54 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
11/01/19-12:41:54 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
11/01/19-12:41:54 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
11/01/19-12:41:54 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
11/01/19-12:41:59 ERROR failed to register crengine font: cannot register font <./fonts/nerdfonts/symbols.ttf>
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
11/01/19-12:42:03 INFO  opening file /mnt/ext1/_Books/RPGs/Legacy2E/Legacy-2E-Corebook.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
11/01/19-12:42:03 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
11/01/19-12:42:03 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
11/01/19-12:42:03 INFO  setting zoom mode to contentheight
warning: openjpeg warning: No incltree created.

warning: openjpeg warning: No imsbtree created.

warning: openjpeg warning: No incltree created.

warning: openjpeg warning: No imsbtree created.

warning: openjpeg warning: No incltree created.

warning: openjpeg warning: No imsbtree created.

warning: openjpeg warning: No incltree created.

warning: openjpeg warning: No imsbtree created.

warning: openjpeg warning: No incltree created.

warning: openjpeg warning: No imsbtree created.

warning: openjpeg warning: No incltree created.

warning: openjpeg warning: No imsbtree created.

warning: openjpeg warning: No incltree created.

warning: openjpeg warning: No imsbtree created.

warning: openjpeg warning: No incltree created.

warning: openjpeg warning: No imsbtree created.

source page (0,0) - (442,663)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
source page (0,0) - (338,518)
source page bgcolor 192
source page (0,0) - (312,528)
source page bgcolor 192
```

I am at a loss here, it seems almost random…

**Comment by NiLuJe** [comment] 2019-11-01 14:45
Does ePub books fare any better?

**Comment by Frenzie** [comment] 2019-11-01 15:03
Is this different than the known issue an approach like #3540 would be able to solve? (But needs a dev to finish.)

**Comment by kindfulkirby** [comment] 2019-11-01 15:42
Epubs seem to work fine, though things like changing font size or line spacing seem to freeze the UI for dozens of seconds, which might be normal? I always used built-in readers for epubs before, since they are usually good enough ^^"

Loading files also takes dozens of seconds.
In fact, I thought it might have crashed while loading a file, so I pressed the Home button, and it flashed wildly between the book cover (suddenly loaded!), the home screen, and an info box saying "Sleeping", showing each at least twice for a fraction of a second before finally settling on the home screen…

@Frenzie Not sure what the issue there is, exactly?

I'd love for someone else with an Inkpad 3 Pro to chime in, just to be sure I didn't get a lemon…

**Comment by poire-z** [comment] 2019-11-01 15:46
Isn't this the same old issue with Pocketbooks going into some sleep/suspend early (just halting CPU, not a real device suspend) that is talked about in #3540 and all the related issues linked in it?

**Comment by Frenzie** [comment] 2019-11-01 15:46
@kindfulkirby The issue is that the PB goes to some low energy state after a second or two regardless of current activity.

**Comment by kindfulkirby** [comment] 2019-11-01 15:48
I see, that makes sense, I guess!

So it seems there is no actual fix, yet?

**Comment by Frenzie** [comment] 2019-11-01 15:52
No currently active dev owns a PB device. Most of the required bits and pieces are there in the PR for anyone who'd like to take a stab at it.

**Comment by kindfulkirby** [comment] 2019-11-01 15:57
I don't think I've got the time and patience to fix this… not if I can just return the thing and buy a Kobo instead xD

**Comment by pazos** [comment] 2019-11-01 16:23
> I don't think I've got the time and patience to fix this… not if I can just return the thing and buy a Kobo instead xD

Yeah, that's faster and easier but you'll have a bad time with light distribution quality on newer Kobos. So be aware before buying. See https://www.reddit.com/r/kobo/comments/dpxfaz/i_purchased_5_libras_and_2_formas_and_all_of_them/

**Comment by kindfulkirby** [comment] 2019-11-01 16:34
That doesn't look *that* bad. But that's off topic, anyway.

**Comment by Markismus** [comment] 2019-11-22 15:08
I just got the Pocketbook Inkpad 3 Pro and I can confirm that KOReader 2019.11 "Cleft Cloak" crashes. However, I didn't install the system folder in which `koreader.app` is.

What works: starting koreader and opening the quickstart guide. Frontlight doesn't work from koreader, so you have to hit the home button and swipe down and work the frontlight from there. Going to the file manager works. However, opening a epub crashes the whole device. I had to press the power button for quite some time, which resulted in the frontlight disabling. (I assume the device turned off.) After that I pressed the power button again and the device started again.

I'll look into it after I am done [playing around the FEL mode and sunxi-tools](https://www.mobileread.com/forums/showthread.php?p=3915519#post3915519).

**Comment by Cellaris** [comment] 2020-08-04 21:01
> No currently active dev owns a PB device.

I have a PocketBook Touch HD 3 that I don't use. I could send it to a developer who is interested. I live in Spain.

**Comment by pazos** [comment] 2020-08-07 12:02
@Cellaris: thanks for the offer. That's very kind of your part :+1: 

I would like to take at stab at it but sadly I have not much free time these months. Maybe others tinkerers, like @NiLuJe, are interested?

If nobody wants it I could take a look. Not really interested in the device itself so I could return it or send it to another contributor once I finished with it.

**Comment by NiLuJe** [comment] 2020-08-07 23:16
I'm pretty much in the same boat as far as bandwidth / time available is concerned to delve into a new / unknown platform... ;/

**Comment by Cellaris** [comment] 2020-08-08 05:28
Personally I am used to the peculiarities of KOReader's operation on PocketBook devices. By avoiding doing a couple of things (forbidden to open books from KOReader's file browser and forbidden to continuously change read settings on large files), it can be used successfully on most books. The ordinary reading process executes it well. I have KOReader assigned as my default reading program on the Inkpad 3 and Touch HD 3, and I am rarely forced to use the native PocketBook program. But it clearly doesn't work smoothly, if you compare it to the Kobo or Android versions. 

Unfortunately I'm a computer illiterate and my only way to help is to make a device available to you. But I understand that you have enough things to take care of. If you find some time and some motivation, you have the device at your disposal (no need to return it, I have another PB Touch HD 3 that I use regularly).

**Comment by pazos** [comment] 2020-08-08 10:46
> Personally I am used to the peculiarities of KOReader's operation on PocketBook devices. By avoiding doing a couple of things (forbidden to open books from KOReader's file browser and forbidden to continuously change read settings on large files), it can be used successfully on most books. The ordinary reading process executes it well. I have KOReader assigned as my default reading program on the Inkpad 3 and Touch HD 3, and I am rarely forced to use the native PocketBook program. But it clearly doesn't work smoothly, if you compare it to the Kobo or Android versions.

I think that one is very easy to fix. You can try by yourself, by modifying `frontend/device/pocketbook/device.lua` with Notepad++ or any other good text editor:

```diff
diff --git a/frontend/device/pocketbook/device.lua b/frontend/device/pocketbook/device.lua
index 798afdf5..90f56de1 100644
--- a/frontend/device/pocketbook/device.lua
+++ b/frontend/device/pocketbook/device.lua
@@ -155,6 +155,10 @@ function PocketBook:init()
     os.remove(self.emu_events_dev)
     os.execute("mkfifo " .. self.emu_events_dev)
     self.input.open(self.emu_events_dev, 1)
+
+    local timeout = G_reader_settings:readSetting("pocketbook_screen_timeout") or 5 * 60 * 1000
+    self:setSuspendState(true, timeout)
+
     Generic.init(self)
 end
 
@@ -176,6 +180,11 @@ function PocketBook:setDateTime(year, month, day, hour, min, sec)
     end
 end
 
+function PocketBook:setSuspendState(enabled, ms)
+    local state = enabled and 1 or 0
+    require("ffi/input").setSuspendState(state, ms)
+end
```

> If you find some time and some motivation, you have the device at your disposal (no need to return it, I have another PB Touch HD 3 that I use regularly).

I want to spend a few hours with the device, but that doesn't mean I would want to become a pocketbook maintainer. If that's fine for you we can make a deal :smile:  (I still want to return the device when I finish with it, if you don't need it back I can send it to another contributor).

**Comment by Cellaris** [comment] 2020-08-08 12:35
> If that's fine for you we can make a deal 😄 

That's simple. If you give me a postal address, I'll send it to you next week. 

(I will try the changes in device.lua when I have a computer available. Thank you.)

**Comment by pazos** [comment] 2020-08-10 17:12
@Cellaris: I sent you a PM in mobileread.

**Comment by pazos** [comment] 2020-08-18 15:25
@Cellaris: I received the device this morning. Just had half an hour at launch to play with it.  First impression of the device: hardware is very good, software is a bit meh.

Tried to reproduce the issues of https://github.com/koreader/koreader/issues/5550#issuecomment-670827065 but I didn't manage yet to trigger the suspend behaviour "crash" opening books from KOReader.

Anyways, I left my computer building the toolchain and the program sources while I'm working and will play a bit tonight or tomorrow. 

Thanks! (and feel free to suggest ways of "crashing" the program or provide books that can achieve that crash :+1: )

**Comment by Cellaris** [comment] 2020-08-18 16:28
> @Cellaris: I received the device this morning. Just had half an hour at lunch to play with it. First impression of the device: hardware is very good, software is a bit meh.
> 
> Tried to reproduce the issues of [#5550 (comment)](https://github.com/koreader/koreader/issues/5550#issuecomment-670827065) but I didn't manage yet to trigger the suspend behaviour "crash" opening books from KOReader.
> 
> Anyways, I left my computer building the toolchain and the program sources while I'm working and will play a bit tonight or tomorrow.
> 
> Thanks! (and feel free to suggest ways of "crashing" the program or provide books that can achieve that crash 👍 )

With a 400/500 Kb ePub it is usually no problem. KOReader can be used successfully. Problems come with large files. A 6 MB ePub with images, cross references, notes... (for example, the complete works of some prolific author). In these cases, the problems do appear. KOReader versions for Kobo or Android also slow down its opening, but on PocketBook it often gets stuck. You have to touch the screen to get the process going again. The same happens when changing margins, font sizes, line spacing... 

The difference in performance can also be seen by opening an ePub from the PocketBook's home screen (firmware 6.0.x) or from its library (firmware 5.0.x), compared to opening it from KOReader's file browser. The opening time is significantly longer when opening the file from KOReader. 

And performance is also different depending on the PocketBook e-reader used. On the PocketBook Touch HD 3 it works relatively well, on the InkpPad 3 it is worse, and on the Touch HD 2 KOReader has numerous stability issues (the program closes when you touch the screen to change any settings). I can't talk about other more recent models (Touch Lux 4/5, InkPad Pro, InkPad X) because I don't have them physically. But their operation must be similar to that of the Touch HD 3 and InkPad 3.

**Comment by pazos** [comment] 2020-08-18 17:42
I'm afraid the device is not very hacker friendly so, If you don't mind, I would like to open it and solder a serial port that makes waay easier to debug power issues.

About the issues opening files from the FM, I didn't trigger any.

I tried with the complete collection of Tolkien in a single epub with high-res images (82MB). Opened in 1 minute the first time and almost instantly the rest of times. That's almost the same it takes for my BQ Cervantes 4. So probably is not the images nor the size, but other things might affect it (cross references, notes..). If you have a book that always made the device stuck please scramble it and send me a copy.

**Comment by Cellaris** [comment] 2020-08-18 19:21
> I'm afraid the device is not very hacker friendly so, If you don't mind, I would like to open it and solder a serial port that makes waay easier to debug power issues.

You can do whatever you want with the device.

**Comment by pazos** [comment] 2020-08-18 21:04
I think I found a way to fix (mostly) the suspend issue.

It is a bit rough at the moment and doesn't work on some scenarios (I need a couple of hours for serious tinkering, but that would need to wait until the weekend).

It will work for the first time and each time koreader goes to the background. If the timeout is reached (I hardcoded it to 5 minutes to test) device will be put into sleep. You can resume it by touching the screen but you'll need to press the home button and reopen it again to regain the new timeout (or press the power button a couple of times).

**Comment by pazos** [comment] 2020-08-19 19:55
Duplicate of #3561

**Closed by pazos** 2020-08-19 19:55 UTC
Labels: PocketBook, firmware, help-wanted
