### ISSUE TITLE
PDF rendering: unexpected image inversion

### ISSUE THREAD

**Issue by LiuShu3** [koreader/koreader#9927] opened 2022-12-18 02:55 UTC
PDF渲染问题：意外的图片反色
![screenshot](https://user-images.githubusercontent.com/75210788/208279042-63304c3c-48d7-48bc-8f23-8c5089fc15d3.png)
[科学 九年级下册.pdf](https://github.com/koreader/koreader/files/10253117/default.pdf)

**Comment by NiLuJe** [comment] 2022-12-18 05:49
Quite likely a duplicate of #5422 ;).

**Comment by Liushu3** [comment] 2022-12-18 12:16
> Quite likely a duplicate of #5422 ;).
MuPDF said “warning: ICC support is not available”

**Closed** 2024-06-01 11:22 UTC
