### ISSUE TITLE
[PocketBook 624] Output is blurred.

### ISSUE THREAD

**Issue by Matt-Soft** [koreader/koreader#4495] opened 2019-01-19 12:27 UTC
* KOReader version: KOReader 2019.01 "Public Domain 1923"
* Device: Pocketbook 624 SoftwareVersion: W624.4.4.1739

#### Issue
Like in title, display output is blurred.
 
![img_20190119_131803](https://user-images.githubusercontent.com/6839376/51426638-b8044f00-1bed-11e9-84c0-9825b61ce9d5.jpg)

#### Steps to reproduce

Run application.

##### `crash.log` (if applicable)
https://pastebin.com/xvnA6JTW

**Comment by Frenzie** [comment] 2019-01-19 12:48
Duplicate of #4476. It should already be fixed. Please try a recent nightly from http://build.koreader.rocks/download/nightly/. :-)

**Closed by Frenzie** 2019-01-19 12:48 UTC
