### ISSUE TITLE
Do you want to turn on Wi-Fi massage always appear after choosing a book. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#10706] opened 2023-07-16 17:50 UTC
* KOReader version: 1.6.2023
* Device: Samsung galaxy Tab T-295 with android version 11

#### Steps to reproduce start koreader app, choose a book, the massage appears 
![20230716_204017](https://github.com/koreader/koreader/assets/70109540/71542ea9-7bb5-439b-888a-3b7d1692e27b)

**Comment by hasezoey** [comment] 2023-07-16 18:33
likely the same issue i have at #10704

**Comment by NiLuJe** [comment] 2023-07-16 18:38
Yep, duplicate of #10704, closing in favor of the more descriptive one.

**Closed by NiLuJe** 2023-07-16 18:38 UTC

**Comment by Zeyadas** [comment] 2023-07-16 18:58
Solved, thank you guys.
