### ISSUE TITLE
Can't open one large epub file

### ISSUE THREAD

**Issue by DamienCassou** [koreader/koreader#3725] opened 2018-03-06 12:48 UTC
* KOReader version: 2015.11-1523-g78284e1
* Device:
  - pocket book touch lux 3
  - kobo aura hd

#### Issue

I have a 13Mb epub file that I can open on Calibre and Emacs but it won't open in koreader after 1 minute waiting with the text "Opening file foo.epub".

**Comment by Frenzie** [comment] 2018-03-06 13:00
Note that the latest nightly contains some fixes by @poire-z that might help. (Try it through OTA update or get it from http://build.koreader.rocks/download/nightly/v2015.11-1546-gd0130ae/ at the time of writing.)

E.g., https://github.com/koreader/crengine/pull/97#issuecomment-369733864 and https://github.com/koreader/koreader/pull/3720

For now I'll close it as a duplicate of https://github.com/koreader/koreader/issues/3459 :-)

**Comment by DamienCassou** [comment] 2018-03-06 13:01
I decided to wait some more and koreader finally opened it on the pocket book (I haven't tried on the kobo aura). The epub (26000 pages) is unusable though as turning each page takes two seconds.

**Closed by Frenzie** 2018-03-06 13:00 UTC

**Comment by DamienCassou** [comment] 2018-03-06 13:02
Thanks for your answer.

**Comment by Frenzie** [comment] 2018-03-06 13:04
> The epub (26000 pages)

Yeah, that's a known issue of sorts. Anything over a few thousand pages is… unusual. Out of curiosity, what's so large?

**Comment by DamienCassou** [comment] 2018-03-06 13:20
FYI, I've just updated with OTA and now koreader won't open it at all anymore (at least after 8 minutes).

> Out of curiosity, what's so large?

10 books, one after the other :-).

**Comment by Frenzie** [comment] 2018-03-06 13:29
Did you try clearing cache first?

Pinging @poire-z

**Comment by DamienCassou** [comment] 2018-03-06 13:31
> Did you try clearing cache first?

do you mean removing the `cache/` folder?

**Comment by Frenzie** [comment] 2018-03-06 13:48
Sure. You can also do it through Tools → Developer's options → Clear readers' caches.

**Comment by poire-z** [comment] 2018-03-06 13:54
Yes, clear caches. Look at your crash.log and you should see some CRE WARNINGs...
There is a setting that you need to manually add: see https://github.com/koreader/koreader/pull/3700 for details, also https://github.com/koreader/crengine/pull/102#issuecomment-370760277
You will probably need with such a big book to add a big value, like `"cre_storage_size_factor" = 10,` (don't forget the comma at end) .

It will not change much the long time taken on first opening, but it should speed up the next re-openings. You will still get page change lags, may be slightly shorter (usable or not, that's for you to decide:)

Tell us how it goes, which value you had to set.

**Comment by DamienCassou** [comment] 2018-03-11 16:10
I've just updated to the very latest version with OTA and managed to open the epub and navigate in it. I also tried to close it and opening it again. Navigation between pages and inside the table of contents is a bit slow but acceptable given the size of the book. Really good job. I didn't change

Thank you

**Comment by Eduardomb22** [comment] 2018-03-13 20:24
@DamienCassou https://github.com/koreader/koreader/pull/3740
It is up in the lastest nightly.

**Comment by DamienCassou** [comment] 2018-03-15 08:46
Yesterday evening I updated with OTA. I didn't see that much of a difference compared to what I felt in my previous comment. Going from a page to the next is still acceptable to me but not fast.
