### ISSUE TITLE
Turning off frontlight (Android)

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#7704] opened 2021-05-18 05:46 UTC
* KOReader version:2021.04-79
* Device:Boyue Likebook Muses FW v3.1.0 (Android 8.1-based)

#### Issue
When frontlight turned off or level set to 0, actual frontlight level is not changed.
#### Steps to reproduce
Set system frontlight setting to user-defined and set white and orange levels to 0 (or whatever), enable frontlight control in koreader, use frontlight gesture to set frontlight to a non-zero level (it changes level of white light.) Then turn frontlight off by a tap or set it to 0 by the gesture, and the level does not change. (The actual level does change when increasing level by the gesture or decreasing it to a non-zero value.) 
This problem exists for a long time, I haven't reported it before as it may well be a firmware issue. Also, it would be nice to have control of both white and orange lights.

**Comment by pazos** [comment] 2021-05-18 11:51
Duplicate of #5364, #5944, #6115, #6469

> Long story short: devices running non standard android lights won't be supported unless device owners port the needed bits to KOReader.

These days porting is easy, just have a look at https://github.com/koreader/android-luajit-launcher/tree/master/app/src/main/java/org/koreader/launcher/device/lights

**Closed** 2021-05-24 20:15 UTC
Labels: Android, duplicate, firmware, wontfix
