### ISSUE TITLE
64bit Arm Android version?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1771] opened 2016-01-10 17:48 UTC
HI

Is it possible to get 64bit Android versions of KOreader? I have a 64bit tablet and it does not start whatsoever (I do not even see luajit in logcat). I am suspecting that it is a cpu arch issue.

**Comment by Frenzie** [comment] 2016-01-10 18:12
Which tablet is it?

**Comment by gerroon** [comment] 2016-01-10 19:17
Lenovo A10

**Comment by Frenzie** [comment] 2016-01-10 20:43
But that doesn't seem to be 64-bit? http://shop.lenovo.com/us/en/tablets/lenovo/a-series/a10/#tab-tech_specs says it has an "MTK 8121 Quad Core ARM Cortex-A7 (1.30GHz 533MHz 1MB)", which is 32-bit. That aside, 32-bit software should work without issues on a 64-bit CPU. What specifically makes you think it's the CPU architecture?

**Comment by gerroon** [comment] 2016-01-11 00:04
Hi

Sorry this is the cpu.

http://pdadb.net/index.php?m=cpu&id=a8165&c=mediatek_mt8165

I think the Lollipop 5.0.1 from Lenovo is the 64bit version.

Anyway the reason I think it is an arc issue because all I get is a blank screen

This is all I have

I/luajit-launcher(15252): Application data directory /data/data/org.koreader.launcher/files
I/luajit-launcher(15252): Application library directory /data/app/org.koreader.launcher-1/lib/arm
I/luajit-launcher(15252): Screen size 1200x1848
I/luajit-launcher(15252): Screen brightness 30
I/luajit-launcher(15252): Check file in asset module: koreader-g16509e2.7z
I/luajit-launcher(15252): Skip installation for revision g16509e2
I/luajit-launcher(15252): Change directory to /data/data/org.koreader.launcher/files
I/luajit-launcher(15252): intent file path 
I/luajit-launcher(15252): run command chmod 755 ./sdcv
I/luajit-launcher(15252): try to load module libs/libkoreader-lfs.so
I/luajit-launcher(15252): ffi.load SDL2
I/luajit-launcher(15252): ffi.load SDL
W/luajit-launcher(15252): cannot blit: no window
I/luajit-launcher(15252): # initializing for device Android
I/luajit-launcher(15252): # framebuffer resolution: {
I/luajit-launcher(15252): 	["h"] = 1848,
I/luajit-launcher(15252): 	["w"] = 1200
I/luajit-launcher(15252): }
I/luajit-launcher(15252): ffi.load libs/libfreetype.so.6
I/luajit-launcher(15252): ffi.load libs/libmupdf.so
I/luajit-launcher(15252): ffi.load libs/libwrap-mupdf.so
I/luajit-launcher(15252): try to load module common/serialize.so
I/luajit-launcher(15252): # show home page
I/luajit-launcher(15252): # INFO: invalid widget for setDirty() stack traceback:
I/luajit-launcher(15252): 	frontend/ui/uimanager.lua:205: in function 'setDirty'
I/luajit-launcher(15252): 	frontend/apps/filemanager/filemanager.lua:235: in function 'restoreScreenMode'
I/luajit-launcher(15252): 	frontend/apps/filemanager/filemanager.lua:242: in function 'showFiles'
I/luajit-launcher(15252): 	/data/data/org.koreader.launcher/files/reader.lua:146: in main chunk
I/luajit-launcher(15252): 	[C]: in function 'dofile'
I/luajit-launcher(15252): 	/data/data/org.koreader.launcher/files/llapp_main.lua:43: in main chunk
I/luajit-launcher(15252): 	[C]: in function 'dofile'
I/luajit-launcher(15252): 	[string "launcher.lua"]:36: in function 'launch'
I/luajit-launcher(15252): 	[string "launcher.lua"]:39: in function 'run'
I/luajit-launcher(15252): 	[string "android.lua"]:1380: in main chunk
I/luajit-launcher(15252): # cache image|resources/icons/appbar.chevron.left.png||
I/luajit-launcher(15252): # cache image|resources/icons/appbar.chevron.right.png||
I/luajit-launcher(15252): # cache image|resources/icons/appbar.chevron.first.png||
I/luajit-launcher(15252): # cache image|resources/icons/appbar.chevron.last.png||
I/luajit-launcher(15252): # cache image|resources/icons/appbar.arrow.left.up.png||
I/luajit-launcher(15252): # show widget

**Comment by houqp** [comment] 2016-01-11 04:06
Luajit launcher is running, so it's not an arch issue. I think the cause is this line:

```
W/luajit-launcher(15252): cannot blit: no window
```

Looks like we need to wait for `APP_CMD_INIT_WINDOW` command before grabbing the window: http://grokbase.com/t/gg/android-ndk/123embz4gn/segmentation-fault-using-a-native-window-in-android

**Comment by gerroon** [comment] 2016-01-11 04:53
That makes sense. I hope that we get a build with that in place soonish. I have seen that exact error on my eink android ereaders as well (like boyue).

**Comment by gerroon** [comment] 2016-01-22 16:34
@houqp 

Any progress on this front https://github.com/koreader/koreader/issues/1771#issuecomment-170426868 ?

**Comment by houqp** [comment] 2016-01-25 02:24
@gerroon I have been travelling in Thailand since I made the comment. I can't test this until I get back home.

**Comment by houqp** [comment] 2016-02-26 17:45
@gerroon , I have started looking into this issue. Just found a bug in the build system that will crash the app on one of my test phone. Probably not related to your issue though since you are not experiencing a crash. But you can still give it a try after the automated build is out.

I also looked at my android log, it also has that `W/luajit-launcher(15252): cannot blit: no window` warning, but mine works just fine. So this might not be the cause of your blank screen. I will still try to get rid of it to see if it helps with your case.

**Comment by gerroon** [comment] 2016-02-27 05:27
@houqp 

I just tried the latest 155 release. I do not even get a proper log. All I get is "Android Application event 10 , 6 , 11, 1"

**Comment by houqp** [comment] 2016-02-27 20:23
The patch is not merged yet, will let you know when it's ready to test

**Comment by houqp** [comment] 2016-03-01 08:51
@gerroon , patch merged, you should be able to try it with the next android build.

**Comment by chrox** [comment] 2016-06-25 13:59
It seems this issue report is either invalid or duplicated to #1670, #1692.

**Closed by chrox** 2016-06-25 13:59 UTC
