### ISSUE TITLE
Suspend is not working on Cervantes 2013

### ISSUE THREAD

**Issue by ZapperDJ** [koreader/koreader#5083] opened 2019-06-16 17:08 UTC
KOReader version: 2019.06
* Device: Cervantes 2013

#### Issue
Whenever go to to Exit > Suspend on the KOReader menu, a message pops up with the text Sleeping and then KOReader exits
[crash-suspend.log](https://github.com/koreader/koreader/files/3294352/crash-suspend.log)

**Comment by pazos** [comment] 2019-06-16 17:23
Hi, moved this report to your other issue because both have the same solution. Closing this as a duplicate of #5084

**Closed by pazos** 2019-06-16 17:23 UTC
