### ISSUE TITLE
Random crashes after opening books

### ISSUE THREAD

**Issue by boredhominid** [koreader/koreader#9112] opened 2022-05-19 18:01 UTC
* KOReader version: v2022.03.1-63-g84dd58f9_2022-05-09
* Device: Kobo Libra H2O

#### Issue
Koreader crashes seconds after opening a book. It happened a couple of times in the last week or so. Bellow is the log for the most recent one.
#### Steps to reproduce
It seems to be at random 
##### `crash.log` (if applicable)
<details>
  <summary>crash.log</summary>

```
05/13/22-17:53:13 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
05/13/22-17:53:19 INFO  WakeupMgr: scheduling wakeup in 594
05/13/22-17:53:19 INFO  Kobo standby: asking to enter standby . . .
05/13/22-17:53:30 INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
05/13/22-17:53:32 INFO  Thumbnails cache: 12/500 (2.5 MB/10.6 MB)
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
05/13/22-17:53:37 INFO  WakeupMgr: scheduling wakeup in 596
05/13/22-17:53:37 INFO  Kobo standby: asking to enter standby . . .
05/13/22-17:54:05 INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
05/13/22-17:54:05 INFO  opening file /mnt/onboard/books/Frank Herbert's Dune Saga Collection_ Books 1 - 6 - Frank Herbert (2833).epub
GET https://sync.koreader.rocks:443/syncs/progress/71fca90c8a826d667e04f621b5c21966
host or service not provided, or not known
05/13/22-17:54:50 INFO  WakeupMgr: scheduling wakeup in 556
05/13/22-17:54:50 INFO  Kobo standby: asking to enter standby . . .
05/13/22-17:54:52 INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
05/13/22-17:54:55 INFO  WakeupMgr: scheduling wakeup in 596
05/13/22-17:54:55 INFO  Kobo standby: asking to enter standby . . .
05/13/22-17:54:58 INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
05/13/22-17:55:03 INFO  opening file /mnt/onboard/books/Complete Witcher, The - Andrzej Sapkowski (2835).epub
GET https://sync.koreader.rocks:443/syncs/progress/d62a9a8828816f6ebfe9cb8d541ede87
host or service not provided, or not known
./luajit: frontend/ui/uimanager.lua:1212: attempt to call field 'action' (a nil value)
stack traceback:
	frontend/ui/uimanager.lua:1212: in function '_checkTasks'
	frontend/ui/uimanager.lua:1643: in function 'handleInput'
	frontend/ui/uimanager.lua:1754: in function 'run'
	./reader.lua:324: in main chunk
	[C]: at 0x000140bd
!!!!
Uh oh, something went awry... (Crash n°1: 05/13/22 @ 17:55:08)
Running FW 4.32.19501 on Linux 4.1.15-00417-g0c800cffe1f9 (#102 SMP PREEMPT Mon Mar 29 09:24:11 CST 2021)
Attempting to restart KOReader . . .
!!!!
```
</details>

**Comment by NiLuJe** [comment] 2022-05-19 19:03
Does it happen without the sync stuff enabled?

**Comment by NiLuJe** [comment] 2022-05-19 19:05
(And/or without autostandby disabled, which is positively useless on your device anyway ;)).

**Comment by NiLuJe** [comment] 2022-05-19 19:09
And please enable debug logging, and see whether it still happens (or whether it crashes with a different trace).

**Comment by NiLuJe** [comment] 2022-05-19 19:13
Is there metadata parsing involved in the FM (e.g., new books in the folder) in the few instances where it crashed?

**Comment by boredhominid** [comment] 2022-05-20 13:09
> Does it happen without the sync stuff enabled?

That was my first thought but I couldn't trigger the crash in my quick testings. 

> (And/or with autostandby disabled, (it's positively useless on your device anyway ;))).

I think you have the Aura in mind because it works just fine on the Libra. 

> And please enable debug logging ([Tools] > More tools > Developer settings), and see whether it still happens (or whether it crashes with a different trace).

I've tried quickly and unsuccessfully to reproduce the crash (open a book, exit to file manager, open another book). It doesn't happen often, I'll try to get the debug log when/if it happens again.
 
> Was there metadata parsing involved in the FM (e.g., new books in the folder) in the few instances where it crashed?

No. 
 
A side note: I tried to check the log to see if there was old crashes that I didn't notice but the log is full of standby plugin info, basically 3 log entries for every wakeup/standby event, whitch add up to around 700/day. 
My log is about 70% of :
```
INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
INFO  WakeupMgr: scheduling wakeup in 597
INFO  Kobo standby: asking to enter standby . . .
```
Is there anyway to reduce the clutter? Is this a nightlies things only?

**Comment by NiLuJe** [comment] 2022-05-20 17:27
> > Does it happen without the sync stuff enabled?
> 
> That was my first thought but I couldn't trigger the crash in my quick testings.

So, working theory would put the blame somewhere in the kosync plugin, right?

> 
> > (And/or with autostandby disabled, (it's positively useless on your device anyway ;))).
> 
> I think you have the Aura in mind because it works just fine on the Libra.
> 

I never said it didn't work, I said that, on this device, it was at best a small power efficiency sidegrade, at the cost of a large UX downgrade ;).

> 
> A side note: I tried to check the log to see if there was old crashes that I didn't notice but the log is full of standby plugin info, basically 3 log entries for every wakeup/standby event, whitch add up to around 700/day. My log is about 70% of :
> 
> ```
> INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
> INFO  WakeupMgr: scheduling wakeup in 597
> INFO  Kobo standby: asking to enter standby . . .
> ```
> 
> Is there anyway to reduce the clutter? Is this a nightlies things only?

It's a "until the kinks are worked out" thing ;).

**Comment by boredhominid** [comment] 2022-05-20 19:29
After some opening/closing repetitions it crashed again with the same trace, here's the log of the last two openings a successful one followed by the one that caused the crash https://pastebin.com/tgBusuZr 

 > at best a very small power efficiency sidegrade, at the cost of a large UX downgrade ;).

Without standby I barely get 20 hrs of awake time, with it I managed to get 2 days. The UI lag is noticeable but not anoyingly noticeable so for me it's a good trade.
<details>
  <summary>battery stats</summary>

![Reader_2022-05-07_191826](https://user-images.githubusercontent.com/26527950/169597343-1a672099-4937-4ad3-9298-b7418929bc82.png)

</details>

**Comment by NiLuJe** [comment] 2022-05-20 23:13
Can you reproduce if you replace `frontend/ui/uimanager.lua` by [this version](https://github.com/NiLuJe/koreader/blob/master/frontend/ui/uimanager.lua)?

And if so, post the log (which is going to be *super* verbose, as it's dumping the full task object, which might include class instances).

**Comment by boredhominid** [comment] 2022-05-21 11:03
> Can you reproduce if you replace frontend/ui/uimanager.lua by [this version](https://github.com/NiLuJe/koreader/blob/master/frontend/ui/uimanager.lua)?

Koreader won't start with this version 
<details>
  <summary>crash.log</summary>

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/21/22-11:51:13
 [*] Version: v2022.03.1-63-g84dd58f9_2022-05-09

ffi.load: blitbuffer
05/21/22-11:51:13 INFO  initializing for device Kobo_storm
05/21/22-11:51:13 INFO  framebuffer resolution: {
    ["w"] = 1264,
    ["h"] = 1680,
}
[ko-input] Forked off fake event generator (pid: 10800)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libutf8proc.so.2
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=1.879 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.879/1.879/1.879 ms
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=4.160 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 4.160/4.160/4.160 ms
./luajit: frontend/ui/uimanager.lua:562: attempt to index local 'caller' (a nil value)
stack traceback:
	frontend/ui/uimanager.lua:562: in function 'schedule'
	frontend/ui/uimanager.lua:588: in function 'nextTick'
	./reader.lua:296: in main chunk
	[C]: at 0x000140bd
!!!!
Uh oh, something went awry... (Crash n°5: 05/21/22 @ 11:51:14)
Running FW 4.32.19501 on Linux 4.1.15-00417-g0c800cffe1f9 (#102 SMP PREEMPT Mon Mar 29 09:24:11 CST 2021)
Too many consecutive crashes, aborting . . .
!!!! ! !!!!
```
</details>

**Comment by NiLuJe** [comment] 2022-05-21 19:11
Oops. I've pushed new commits that should fix this, please try again (same link) ;).

**Comment by boredhominid** [comment] 2022-05-21 20:31
here is the log for the last two openings before crash https://pastebin.com/N0aqK0Wh

**Comment by boredhominid** [comment] 2022-05-21 20:53
here's another one that happened after the one I shared above https://pastebin.com/f94m9X0N

**Comment by NiLuJe** [comment] 2022-05-21 22:05
Okay, that's interesting :).

How are you switching between documents?

**Comment by boredhominid** [comment] 2022-05-21 22:35
> How are you switching between documents?
open book > swipe to show top menu > click file manager icon > open book

**Comment by NiLuJe** [comment] 2022-05-22 22:18
Okay, I *think* I got it.

Try replacing both
`frontend/ui/uimanager.lua` with [this](https://github.com/NiLuJe/koreader/blob/master/frontend/ui/uimanager.lua)
and
`plugins/autosuspend.koplugin/main.lua` with [that](https://github.com/NiLuJe/koreader/blob/master/plugins/autosuspend.koplugin/main.lua).

(It has to do with extremely unlucky timing, where the tap that closes either FM/RD happens to be one that wakes the device up from suspend, and a sneaky oversight in `tickAfterNext`, which meant that when tearing down the plugin, the bit of code that attempted to unschedule the pending `LeaveStandby` Event did not quite work, because the function doing that wasn't yet in the task queue, what was in it was the `nextTick` wrapper pushed by `tickAfterNext`).

**Comment by boredhominid** [comment] 2022-05-23 11:59
It seems to be fixed, thanks for everything.

**Comment by NiLuJe** [comment] 2022-05-23 12:21
For some strange reason I don't think I managed to quite repro crashes yesterday, but after today's testing on my end, I can at least confirm that the fix is indeed sound and plugging the logic hole I identified in your logs ;).

Thanks for playing along, as this had been reported a few times in the past, but without much feedback ;).

**Closed** 2022-05-25 21:36 UTC
Labels: bug
