### ISSUE TITLE
Customised Android version with screensaver

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#6630] opened 2020-09-03 15:41 UTC
Currently the Android version does not support the screensaver.
To create a customized version for me I need a little help, because I'm not very familiar with the sources.
I want to switch on the menu of the screensaver for the Android version and save a png in a defined directory when activating the screensaver.
In the tolino app a user-defined picture can be stored as a screensaver and so I could make the KOReader screensaver work with this workaround.
I will not commit this change, I will only use this version for myself.
Can anyone give me help for:
1. in which file can I activate the screensaver for Android?
2. in which file is the screensaver handled, so that I can create a png there?

Thanks for your support

**Comment by pazos** [comment] 2020-09-03 16:45
Duplicate of #5732

**Closed by pazos** 2020-09-03 16:45 UTC
Labels: enhancement
