### ISSUE TITLE
FR: Allow adding buttons to Filemanager's file_dialog (similar to addToHighlightDialog)

### ISSUE THREAD

**Issue by Billiam** [koreader/koreader#12823] opened 2024-11-30 17:53 UTC
**Does your feature request involve difficulty completing a task? Please describe.**

Currently, there's no way for a plugin to add buttons to the `FileManager` `file_dialog`. The coverbrowser plugin handles the need for additional buttons by calling the original dialog generating method to get the original button list, adding its own buttons, and then displaying a new dialog, but this approach isn't available to plugins that aren't implementing their own file lists.

**Describe the solution you'd like**

I'd like to see the file manager expose an `addToFileDialog` method, similar to `addToHighlightDialog` exposed by the readerhighlight module, and coverbrowser updated to use that instead.

This would allow plugins interested in updating the dialog to add their own buttons as needed, whether the user was using coverbrowser's display or the default.

**Comment by hius07** [comment] 2024-11-30 18:20
Duplicate of
https://github.com/koreader/koreader/blob/8297d17e54374fcb568e14b03a3a9ca94aac577e/plugins/coverbrowser.koplugin/covermenu.lua#L223-L226

**Comment by Billiam** [comment] 2024-11-30 19:02
Can a feature request be a duplicate of a 7 year old code comment in a plugin? :thinking:

**Comment by hius07** [comment] 2024-11-30 19:14
Thanks for sharing the Hardcover plugin btw.

**Comment by hius07** [comment] 2024-12-04 16:45
Additional buttons (actually, the last button row containing 1 or more buttons) can be added by the outer module:
```Lua
local FileManager = require("apps/filemanager/filemanager")
FileManager:addFileDialogButtons(row_id, row_func)
```
`row-id` - your id to remove the row if needed.

`row_func` gets 3 args:
1) filepath
2) is_file (boolean, we have different dialogs for files and folders)
3) book_props:
https://github.com/koreader/koreader/blob/58adb685d1a9b461d237bbb4069454cdf4fb1e38/frontend/apps/filemanager/filemanagerbookinfo.lua#L30-L38
+additional `display_title`

and should return button table row of usual buttons (text, enabled, callback ...).

Examples are in the CoverBrowser plugin main module.

**Closed** 2024-12-05 16:54 UTC
Labels: enhancement
