### ISSUE TITLE
FR: Disable internet services if there is no WiFi connection

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#7931] opened 2021-07-03 18:31 UTC
Hi

I setup bunch of services like Wallabag, sync server, Calibre etc These work great but KOReader stalls for a while during start up or after waking up if  WiFI is off. 

It would be nice if those services do not attempt any connections if the WiFi is off. 

I am using Boox Android 4, these devices d onot have great batteries so I personally keep wifi off unless I need to grab a book.

thanks

**Comment by pazos** [comment] 2021-07-03 19:29
> These work great but KOReader stalls for a while during start up or after waking up if WiFI is off.

This shouldn't happen, but Android 4 + Onyx + KOReader don't play well together. If you get logs I can give a look, to see if there's something fishy. A normal startup on modern devices should be about 100ms. Resuming from previous pause should be around 10ms.

> It would be nice if those services do not attempt any connections if the WiFi is off.

That's exactly what's happening now :)

> Disable internet services if there is no WiFi connection

That already happens. On other platforms (like kobo) there's also the network manager that turn off wifi after a period of time without usage. We can't do that on android.

**Comment by gerroon** [comment] 2021-07-03 20:13
Hi

I am seeing at least like 10 - 30  seconds stall, it is unresponsive for a while. This started happening after setting up these internal services. I set them up on 3 devices and all seem to ahve this issue.
Where can I find the Koreader logs on my Boox device?

Btw I tested this and it is an issue on a regular Android 11 Phone, so it does not seem to be Android 4 issue.

**Comment by gerroon** [comment] 2021-07-03 20:19
I set up


Calibre 

Wallabag

Joplin

Progress Sync

**Comment by pazos** [comment] 2021-07-03 20:19
Does this happen on 2021.04 or previous versions?

**Comment by Frenzie** [comment] 2021-07-03 20:39
The progress sync does some stuff automatically if it's enabled.

https://github.com/koreader/koreader/blob/a7bbf24f8730da543af0d161ba4ec24088596e44/plugins/kosync.koplugin/main.lua#L800-L802

**Comment by gerroon** [comment] 2021-07-03 20:42
> Does this happen on 2021.04 or previous versions?
> 
> It has nothing to do with the services you setup. Most of them just do stuff when you request it.

I am using koreader-android-arm-v2021.06-15-gc0386e5d_2021-06-30

**Comment by Galunid** [comment] 2021-07-03 20:44
`Top menu -> 4th icon -> Progress sync -> Auto sync now and future`. There was a discussion why progress sync doesn't check wifi stautus (blocking call), but I don't recall where.

**Comment by pazos** [comment] 2021-07-03 20:45
Nope. Please test older versions and see if the issue happens there. I suspect it won't happen at all, but I'm not able to reproduce your issues in any of my devices

**Comment by gerroon** [comment] 2021-07-03 20:54
> `Top menu -> 4th icon -> Progress sync -> Auto sync now and future`. There was a discussion why progress sync doesn't check wifi stautus (blocking call), but I don't recall where.

That was it. Disabling that makes KOReader responsive again.

**Comment by pazos** [comment] 2021-07-04 09:38
> > `Top menu -> 4th icon -> Progress sync -> Auto sync now and future`. There was a discussion why progress sync doesn't check wifi stautus (blocking call), but I don't recall where.
> 
> That was it. Disabling that makes KOReader responsive again. So that is the culprit I guess.

Apologies. I was under the impression that your bug was another android oddity like https://github.com/koreader/koreader/issues/7798

Please test that everything is fine the next few days and report if you experience another crash/app not responding dialog even with autosync disabled. If not we can do a network check on the progress sync plugin, at least in android, where the check doesn't block.

**Comment by Galunid** [comment] 2021-07-10 19:04
I'm going to close it, since the problem was related to something else, and it's already resolved.

**Closed by Galunid** 2021-07-10 19:04 UTC
Labels: Android

**Comment by newpavlov** [comment] 2023-07-31 16:54
I've encountered this issue after update to 2023.06.01 (F-Droid version). I never used the progress sync functionality, but it looks like it got enabled automatically after the update. With disabled Wi-Fi (and cellular network) on opening a book KOReader has frozen for ~30 seconds, opened the system network settings, and only then got unstuck after displaying Wi-Fi prompt.

I think it's a clear bug with the auto sync functionality. Network check should not freeze application or at the very least timeout should not be bigger than several seconds.

**Comment by NiLuJe** [comment] 2023-07-31 17:20
This has been fixed in current nightlies.
