### ISSUE TITLE
FR: [margin size customize when in auto crop  mode]

### ISSUE THREAD

**Issue by whmzsu** [koreader/koreader#7816] opened 2021-06-07 07:22 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
When in page auto crop mode , there are three choice of margin size , but some times the margin size is not big enough while choose "large" option.

**Describe the solution you'd like**
So can  there be custom margin size option  while in auto page crop mode  ??

**Comment by Frenzie** [comment] 2021-06-07 07:26
Duplicate of #7815. (Within 10 minutes? O.o)

**Closed by Frenzie** 2021-06-07 07:26 UTC
Labels: enhancement

**Comment by huronhorn** [comment] 2021-06-07 07:31
@Frenzie Lol 🤣
