### ISSUE TITLE
2019.4 Unable To Run on Sony DPT

### ISSUE THREAD

**Issue by sekkit** [koreader/koreader#4881] opened 2019-04-07 15:32 UTC
* KOReader version: 2019.4
* Device: sony DPT RP1

#### Issue
When run application, nothing shows up.
#### Steps to reproduce
Install on DPT RP1, start KOReader app.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment] 2019-04-07 15:38
What does installation mean on this device?

**Comment by pazos** [comment] 2019-04-07 17:21
Seems a duplicate of #4430. The device requires a wakelock to show stuff on the screen. That feature is available but disabled by default.

You can add the line to /sdcard/koreader/settings.reader.lua:

`["enable_android_wakelock"] = true,` just after `return {` and see if that fixes the problem.

**Comment by pazos** [comment] 2019-04-07 17:23
And, if you download latest einkTest.apk from releases, you can provide here info about how your device is recognized and we can have a whitelist of known borked devices.

**Comment by pazos** [comment] 2019-04-20 18:25
@sekkit: please provide the requested information in this issue. Thanks

**Closed by pazos** 2019-04-20 18:25 UTC
Labels: Android, duplicate

**Comment by hyhugh** [comment] 2019-04-27 07:34
> @sekkit: please provide the requested information in this issue. Thanks

Hey, I also have this device, I can confirm that all the buttons in the latest einTest.apk do nothing.
the device info provided in the einkTest.apk is attached below, please check. Thanks

```
Manufacturer: Sony
Brand: Sony
Model: DPT-RP1
Product: FPX_1010
Hardware: pxa1908
Platform: mrvl
```

**Comment by hyhugh** [comment] 2019-04-27 08:06
> > @sekkit: please provide the requested information in this issue. Thanks
> 
> Hey, I also have this device, I can confirm that all the buttons in the latest einTest.apk do nothing.
> the device info provided in the einkTest.apk is attached below, please check. Thanks
> 
> ```
> Manufacturer: Sony
> Brand: Sony
> Model: DPT-RP1
> Product: FPX_1010
> Hardware: pxa1908
> Platform: mrvl
> ```

and btw the sony source code can be found here
http://oss.sony.net/Products/Linux/dp/DPT-RP1.html
I'm looking into it trying to find the refresh screen api..

**Comment by pazos** [comment] 2019-04-29 23:51
@hyhugh thanks for the data!

> Marvell Armada PXA1908 SoC

Cool!!!

You can try the build of KOReader in https://github.com/koreader/android-luajit-launcher/pull/143#issuecomment-487107387 and report if it works. That build just changed how the underlying window is exposed to android, but somehow I think it will help on some devices :+1: 

The same for @OSIMLY, who had a similar problem running KOReader in a hanvon e960 plus

**Comment by hyhugh** [comment] 2019-05-02 11:09
> @hyhugh thanks for the data!
> 
> > Marvell Armada PXA1908 SoC
> 
> Cool!!!
> 
> You can try the build of KOReader in [koreader/android-luajit-launcher#143 (comment)](https://github.com/koreader/android-luajit-launcher/pull/143#issuecomment-487107387) and report if it works. That build just changed how the underlying window is exposed to android, but somehow I think it will help on some devices 👍
> 
> The same for @OSIMLY, who had a similar problem running KOReader in a hanvon e960 plus

Hi, I just tested that debug build on my device.. unfortunately full-screen flash is still not working.

from logcat i can see koreader is trying to refresh the full screen,  but the system is not responding to the request.

```
V/KOReader( 3757):  in pan state...
V/KOReader( 3757):  swipe southwest 707.27752368964 detected in slot 0
V/KOReader( 3757):  adjusted ges: swipe southwest
V/KOReader( 3757):  _refresh: Enqueued full update for region 0 0 1650 2200
V/KOReader( 3757):  setDirty full from widget nil w/ NO region
```

still thanks for letting me know the debug build exist haha .

**Comment by pazos** [comment] 2019-05-02 13:06
@hyhugh: so can you reproduce OP:

> KOReader version: 2019.4
Device: sony DPT RP1
Issue
When run application, nothing shows up.

**Comment by hyhugh** [comment] 2019-05-02 13:12
> @hyhugh: so can you reproduce OP:
> 
> > KOReader version: 2019.4
> > Device: sony DPT RP1
> > Issue
> > When run application, nothing shows up.

nah, koreader works normally after turining on `enable_android_wakelock`,
the only issue left is full-screen refreshing.

**Comment by pazos** [comment] 2019-05-02 22:19
> nah, koreader works normally after turning on enable_android_wakelock

That's cool and the expected behaviour. I wonder if it still works (without full screen refreshes) disabling the "enable_android_wakelock" thing in settings.lua (Or from the UI -> Settings-> Screen -> uncheck "keep screen on")

**Comment by hyhugh** [comment] 2019-05-03 05:02
> > nah, koreader works normally after turning on enable_android_wakelock
> 
> That's cool and the expected behaviour. I wonder if it still works (without full screen refreshes) disabling the "enable_android_wakelock" thing in settings.lua (Or from the UI -> Settings-> Screen -> uncheck "keep screen on")

I had some tests just now, i can confirm it works in pdf(i only tested it on pdfs) reader ui. but the old problem still exists in the file browser. i need to tap the screen to 'wake up' the device to refresh the screen(only in the file browser).

**Comment by pazos** [comment] 2019-05-04 23:51
@hyhugh: a test build for that device -> https://www.dropbox.com/s/5x8rb9dlcwzjwiz/koreader-android-arm-linux-androideabi-debug-v2019.04-64-sony.apk?dl=0

I'm interested in the following log: `adb logcat KOReader:D epd:I *:S`.

Thanks for all the feedback!

**Comment by pazos** [comment] 2019-05-10 19:12
@hyhugh @sekkit ^^

**Comment by hyhugh** [comment] 2019-05-11 10:07
> @hyhugh @sekkit ^^

Sorry i didn't notice the reply. I just had a quick test, The new test build crashes right after opening any pdf files. And for the keep-screen-on issue, i can confirm that there is no need to turn on keep-screen-on anymore in the file explorer.

The log is attached, please kindly check.

```
I/KOReader( 3323): [main thread]: starting KOReader
D/KOReader( 3323): App created
I/KOReader( 3323): Using Generic Android surface EPD Controller
D/KOReader( 3323): App resumed
D/KOReader( 3323): Surface created
D/KOReader( 3323): Surface changed {
D/KOReader( 3323):   format:	4
D/KOReader( 3323):   width:	1650
D/KOReader( 3323):   height:	2200
D/KOReader( 3323): }
I/KOReader( 3323): Loading KOReader using paths {
I/KOReader( 3323):   assets:	/data/data/org.koreader.launcher/files
I/KOReader( 3323):   library:	/data/app/org.koreader.launcher-1/lib/arm
I/KOReader( 3323):   storage:	/storage/emulated/0
I/KOReader( 3323): }
I/KOReader( 3323): Screen size: 1650x2200
D/KOReader( 3323): show progress dialog
I/KOReader( 3323): Check file in asset module: koreader-v2019.04-64-g65d72d02_2019-04-26.7z
I/KOReader( 3323): Skip installation for revision v2019.04-64-g65d72d02_2019-04-26
D/KOReader( 3323): dismiss progress dialog
I/KOReader( 3323): Change directory to assets dir: /data/data/org.koreader.launcher/files
I/KOReader( 3323): command chmod 755 ./sdcv returned 0
I/KOReader( 3323): command chmod 755 ./tar returned 0
I/KOReader( 3323): command chmod 755 ./zsync returned 0
D/KOReader( 3323): try to load module libs/libkoreader-lfs.so
D/KOReader( 3323): ffi.load SDL2
D/KOReader( 3323): ffi.load libSDL2-2.0.so
D/KOReader( 3323): ffi.load SDL
I/KOReader( 3323): Android 1.4.01.16100 - Lollipop (API 22) - flavor: rocks
D/KOReader( 3323): ffi.load blitbuffer
D/KOReader( 3323): ffi.load ./libs/libblitbuffer.so
I/KOReader( 3323):  initializing for device FPX_1010
I/KOReader( 3323):  framebuffer resolution: {
I/KOReader( 3323):     ["h"] = 2200,
I/KOReader( 3323):     ["w"] = 1650
I/KOReader( 3323): }
D/KOReader( 3323): ffi.load libs/libmupdf.so
D/KOReader( 3323): ffi.load libs/libwrap-mupdf.so
D/KOReader( 3323): ffi.load libs/libfreetype.so.6
D/KOReader( 3323): try to load module common/serialize.so
D/KOReader( 3323): try to load module rocks/lib/lua/5.1/lpeg.so
D/KOReader( 3323): try to load module common/socket/score.so
D/KOReader( 3323): try to load module common/mime/mcore.so
D/KOReader( 3323): try to load module common/ssl.so
I/KOReader( 3323):  Loading plugins from directory: plugins
I/KOReader( 3323):  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
I/KOReader( 3323):  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
I/KOReader( 3323):  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
I/KOReader( 3323):  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
I/KOReader( 3323):  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
I/KOReader( 3323):  Plugin  plugins/kobolight.koplugin/main.lua  has been disabled.
I/KOReader( 3323):  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
I/KOReader( 3323):  opening file /storage/emulated/legacy/dp_user_storage/document/02d71f8c-ea89-42cb-b210-96c5b8a14211/02d71f8c.pdf
D/KOReader( 3323): ffi.load libs/liblept.so.5
D/KOReader( 3323): ffi.load libs/libk2pdfopt.so.2
I/KOReader( 3323):  setting zoom mode to page
D/KOReader( 3323): Surface destroyed (KOReader crashes right after this line)
```

**Comment by pazos** [comment] 2019-05-11 23:42
> The new test build crashes right after opening any pdf files

It seems that something is raising an unhandled exception.

@hyhugh could you please attach the log of `adb logcat KOReader:V epd:I AndroidRuntime:E` ?

**Comment by hyhugh** [comment] 2019-05-12 07:35
Please check the log attached. Thanks.

```
V/KOReader( 4560): requesting eink update 1
V/KOReader( 4560): requesting eink refresh, type: EPD_FULL
E/AndroidRuntime( 4560): FATAL EXCEPTION: Thread-285
E/AndroidRuntime( 4560): Process: org.koreader.launcher, PID: 4560
E/AndroidRuntime( 4560): java.lang.NoSuchMethodError: No interface method setEpdMode(Landroid/view/View;Ljava/lang/String;)V in class Lorg/koreader/device/EPDController; or its super classes (declaration of 'org.koreader.device.EPDController' appears in /data/app/org.koreader.launcher-1/base.apk)
E/AndroidRuntime( 4560): 	at org.koreader.launcher.MainActivity.einkUpdate(MainActivity.java:218)
W/ActivityManager( 2149):   Force finishing activity 1 org.koreader.launcher/.MainActivity
D/KOReader( 4560): App paused
D/KOReader( 4560): wakelock: releasing ko-wakelock
```

```
--------- beginning of crash
E/AndroidRuntime( 3213): FATAL EXCEPTION: Thread-219
E/AndroidRuntime( 3213): Process: org.koreader.launcher, PID: 3213
E/AndroidRuntime( 3213): java.lang.NoSuchMethodError: No interface method setEpdMode(Landroid/view/View;Ljava/lang/String;)V in class Lorg/koreader/device/EPDController; or its super classes (declaration of 'org.koreader.device.EPDController' appears in /data/app/org.koreader.launcher-1/base.apk)
E/AndroidRuntime( 3213): 	at org.koreader.launcher.MainActivity.einkUpdate(MainActivity.java:218)
E/AndroidRuntime( 3258): FATAL EXCEPTION: Thread-220
E/AndroidRuntime( 3258): Process: org.koreader.launcher, PID: 3258
E/AndroidRuntime( 3258): java.lang.NoSuchMethodError: No interface method setEpdMode(Landroid/view/View;Ljava/lang/String;)V in class Lorg/koreader/device/EPDController; or its super classes (declaration of 'org.koreader.device.EPDController' appears in /data/app/org.koreader.launcher-1/base.apk)
E/AndroidRuntime( 3258): 	at org.koreader.launcher.MainActivity.einkUpdate(MainActivity.java:218)
E/AndroidRuntime( 3323): FATAL EXCEPTION: Thread-224
E/AndroidRuntime( 3323): Process: org.koreader.launcher, PID: 3323
E/AndroidRuntime( 3323): java.lang.NoSuchMethodError: No interface method setEpdMode(Landroid/view/View;Ljava/lang/String;)V in class Lorg/koreader/device/EPDController; or its super classes (declaration of 'org.koreader.device.EPDController' appears in /data/app/org.koreader.launcher-1/base.apk)
E/AndroidRuntime( 3323): 	at org.koreader.launcher.MainActivity.einkUpdate(MainActivity.java:218)
```

**Comment by pazos** [comment] 2019-05-14 22:52
My bad, I [wrongly added a file from a different branch](https://github.com/koreader/android-luajit-launcher/pull/144/files#diff-8bf9d99885bdc96a9e7b93575e45eb92). Reverting it now. I'm uploading a new test apk.

You should see a new setting under "gear" > "screen" > "eink" which allows you to change the number of pages to trigger the full screen update. It should work (or, at least, it shouldn't raise an error).

> And for the keep-screen-on issue, i can confirm that there is no need to turn on keep-screen-on anymore in the file explore

That's cool because it means the device now works without needing wakelocks. Please test again and see if switching "keep screen on" has any effect on program's behaviour.

**Comment by hyhugh** [comment] 2019-05-16 10:37
@pazos Hi,

I just had a quick test again. the exception below is raised when koreader is trying to do full-screen refresh. 

```
E/epd     ( 4882): java.lang.NullPointerException: null receiver
```
for the wakelock issue. I also had a quick test. everything seems to be fine in file explorer and pdf reader. but in the transition between file explorer and pdf reader, i still need to tap screen to 'wake up' the device, say koreader is always stuck on `Opening file ***` and then i need to tap screen to enter the pdf reader.

Thanks a lot for paying so much attention to such a unique device haha! 
and sorry about that since i'm not familiar with android and lua, cannot really help write a patch or so..

**Comment by pazos** [comment] 2019-05-17 21:02
> E/epd     ( 4882): java.lang.NullPointerException: null receiver

Good, I will fix that tomorrow! At least KOReader don't crash now :smile: 

> for the wakelock issue. I also had a quick test. everything seems to be fine in file explorer and pdf reader. but in the transition between file explorer and pdf reader, i still need to tap screen to 'wake up' the device, say koreader is always stuck on Opening file *** and then i need to tap screen to enter the pdf reader.

Ok, thanks for the feedback!

> Thanks a lot for paying so much attention to such a unique device haha!

The same patch should add support for other devices as well (once we get this working)


Again, thanks for the feedback!!

**Comment by pazos** [comment] 2019-06-05 00:11
@hyhugh sorry for the delay!

maybe [this build](https://www.dropbox.com/s/r5ifnjea90uwaiz/koreader-android-generic-epd.apk?dl=0)?
