### ISSUE TITLE
Brightness settings don't work on C67ML

### ISSUE THREAD

**Issue by c67** [koreader/koreader#5944] opened 2020-03-13 09:25 UTC
The brightness doesn't change when I swipe or use the brightness bar. Is the device compatible with this feature? 
![IMG_20200313_062226](https://user-images.githubusercontent.com/62135480/76607651-188dd400-64f3-11ea-8cfc-67e390c19a64.jpg)

![IMG_20200313_093700](https://user-images.githubusercontent.com/62135480/76621498-446a8300-650e-11ea-8300-9cd8acae16ab.jpg)

![IMG_20200313_093631](https://user-images.githubusercontent.com/62135480/76621515-4df3eb00-650e-11ea-9dc5-2f47d322b865.jpg)

**Comment by Frenzie** [comment] 2020-03-13 16:23
If the device uses standard Android light control in principle it should work.

**Comment by pazos** [comment] 2020-03-13 16:24
Duplicate of #5364  

Device is not compatible. It will never be unless a owner adds a workaround. For more info see https://github.com/koreader/koreader/issues/5364#issuecomment-531519202

**Closed by pazos** 2020-03-13 16:24 UTC
Labels: Android
