### ISSUE TITLE
FR: Tolino Epos 2 (Kobo Forma) auto-rotation based on gyroscope

### ISSUE THREAD

**Issue by mikebluu** [koreader/koreader#10391] opened 2023-05-04 20:44 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
The built-in Tolino reader uses the gyroscope to rotate the screen (although not instantly, but with a confirmation pop-up), switching the page turn buttons too. KOReader on the other hand does not have an auto-rotate setting, and even when I manually rotate the screen, the buttons are just as before, nothing changed.

**Describe the solution you'd like**
A switch somewhere in the rotation settings would allow me to use the gyroscope (with or without confirmation) to rotate the screen and switch the page turn buttons accordingly.

**Describe alternatives you've considered**
Maybe a gesture that would rotate the screen and switch the page turn buttons at the same time, but the gyro would then be useless.

**Additional context**
My device is rooted, I have access to ADB Shell, so I should be able to do (device-wise) everything that I'm asked to.

**Comment by pazos** [comment] 2023-05-04 20:56
Duplicate of #9483

**Closed by pazos** 2023-05-04 20:56 UTC
Labels: enhancement

**Comment by pazos** [comment] 2023-05-04 21:04
Hi, @mikebluu

gyro events are the same for all android devices.
We just need a contributor that cares enough to implement a common logic that bridges android with the rest of the platforms, because now they're incompatible as far as gyro events.

Please use the linked ticket instead of this one :)
