### ISSUE TITLE
fb2 tags in footnotes

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#6622] opened 2020-09-02 10:56 UTC
This is a followup to https://github.com/koreader/koreader/issues/6344#issuecomment-678768501.
The attached file shows some rare (in footnotes) fb2.css tags in footnotes.
[footnotes-test.fb2.zip](https://github.com/koreader/koreader/files/5161720/footnotes-test.fb2.zip)

Some conclusions:
`a`
Links are not supported in in-page (styled) and popup (not styled) footnotes.
Links work good in footnotes in the end of the book.

`date`
Because of `display: block` and `text-align: center` the footnote is centered **together with its number** in in-page footnotes and in the end of the book. It would be nice to return the number to the left margin if possible.

And finally, the following tags are not supported in the **popup footnotes** only:

Not shown
```
image
empty-line
```
Not styled
```
epigraph
poem
stanza
v
text-author
date
strike
big
```

**Comment by poire-z** [comment] 2020-09-02 12:04
> a
Links are not supported in in-page (styled) and popup (not styled) footnotes.
Links work good in footnotes in the end of the book.

This will be a "won't fix":
- in-page footnotes are mostly just "pictures" of slices of what's at end of book, put at the bottom of pages. Many things don't work in these, like text selection, dict lookup, and as you noticed: links. This would be too complicated to fix (in crengine and in frontend). (When I need to do a dict lookup of some word there, I just follow/jump to the footnote at end of book, do my stuff there, and jump back).
- in popup footnotes, well, that's too decoupled from the document to do anything about links.


> date
Because of display: block and text-align: center the footnote is centered together with its number in in-page footnotes and in the end of the book. It would be nice to return the number to the left margin if possible.

I guess that's not a bug in crengine. `display: run-in` (so, the footnote number) gets the text-alignment of what comes next. It can be `left`, `justify`, and it might look bad with `right` or `center`.
To avoid that, I guess it's just some fb2.css tweak to add.
Either by just not having `date { text-align: center; }` - does this have really some reason ?
Or by reseting it when in footnotes with:
`body[name="notes"] date, body[name="comments"] date { text-align: inherit; }`
(and possibly for other elements like that).

> the following tags are not supported in the popup footnotes only:

As suggested in the comment you link to, you may try to update `koreader/frontend/ui/widget/footnotewidget.lua` with styles for them, so they look good - now that you compiled them, shouldn't be too long (I'm off tomorrow for a week, so I hope you'll beat me on that :)
(It's possible `strike` is not supported by MuPDF. `date` and `big` are/might be HTML tags, so beware - `date` should probably stay inline in HTML.)

**Comment by hius07** [comment] 2020-09-02 12:44
> Either by just not having `date { text-align: center; }` - does this have really some reason ?

I see no reason to have it `center` in fb2.css.

**Comment by hius07** [comment] 2020-09-02 12:53
> you may try to update `koreader/frontend/ui/widget/footnotewidget.lua` with styles for them

Is it possible to arrange some kind of a 'link' with fb2.css for these non-html tags and not to hardcore them?

**Comment by poire-z** [comment] 2020-09-02 12:58
I guess it's for displaying nicely the stuff at beginning of FB2:
```xml
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
<description>
  <title-info>
    <genre>nonf_criticism</genre>
    <author>
[...]
    </annotation>
    <date>1968</date>
    <coverpage>
      <image l:href="#vt54_11.jpg"/>
    </coverpage>
    <lang>ru</lang>
    <translator>
[...]
```
So, may be the styling of all that should be set to only trigger when in there, like:
`description date { text-align: center }`
As for how `<date>` is used in the main text (it seems allowed by the specs as a child of `poem`) and how it should be styled, some other selectors could be added
```css
date { normal styling if any }
poem date { dunno if you want it left or right aligned or italic... }
```

> Is it possible to arrange some kind of a 'link' with fb2.css for these non-html tags and not to hardcode them?

Nope. These are mostly totally independant bits of code. So, they have to be added manually in footnotewidget.lua .

**Comment by hius07** [comment] 2020-09-02 13:52
One more point. `small` works, but `big` doesn't. Isn't it because we have a setting for font size in popup footnotes which implies some restrictions?

**Comment by poire-z** [comment] 2020-09-02 14:03
No, it's because (the version we use of) MuPDF has something for `small` but nothing for `big`...
https://gitlab.com/koreader/mupdf/-/blob/1.14.0/source/html/html-layout.c#L17-69
`"small{font-size:0.83em}"`
So, might want to add `small` and `big` with coherent values.

**Comment by Frenzie** [comment] 2020-09-02 14:11
`big` isn't in modern HTML ftr, that'd be for fb2 only.

**Comment by hius07** [comment] 2020-09-03 06:49
To summarize, I would propose the following changes:

In the **fb2.css**:
Insert new line 27:
`date { font-style: italic; margin-left: 5% }`
Change old line 119 to:
`description date { font-size: 80%; text-align: center }`

In the **footnotewidget.lua**:
Insert new lines after line 96 (styles in accordance with fb2.css):
```
epigraph { font-style: italic; }
stanza { font-style: italic;  }
v { text-align: left; text-align-last: -cr-right-if-not-first; hyphenate: none }
text-author { font-weight: bold; font-style: italic; }
date { font-style: italic; }
strike { text-decoration: line-through; }
small { font-size: 80%; }
big { font-size: 130%; }
```

I doubt if it's worth to think about showing images in popup footnotes as I haven't met fb2 books with images in footnotes.
In-page footnotes show images well though.

**Comment by poire-z** [comment] 2020-09-03 07:56
> In the footnotewidget.lua:

`text-align-last: -cr-right-if-not-first` won't work with MuPDF, so you can just have them aligned left or justified.

I think for `epigraph, stanza, v, text-author, date`, you'll want also `display: block` as I think unknown tags (to MuPDF) default to be considered inline.

(I'm off soon, and won't be able to integrate these - so may be in a week, unless someone else does it.)

> I doubt if it's worth to think about showing images in popup footnotes

Yep, and we don't do it (complicated) neither for dict results (that may contain images too).

**Comment by hius07** [comment] 2020-09-03 08:07
Thanks, corrected values
```
epigraph { display: block; font-style: italic; }
stanza { display: block; font-style: italic;  }
v { display: block; text-align: left; hyphenate: none }
text-author { display: block; font-weight: bold; font-style: italic; }
date { display: block; font-style: italic; }
strike { text-decoration: line-through; }
small { font-size: 80%; }
big { font-size: 130%; }
```

**Comment by Jellby** [comment] 2020-09-04 14:33
>     * in-page footnotes are mostly just "pictures" of slices of what's at end of book, put at the bottom of pages. Many things don't work in these, like text selection, dict lookup, and as you noticed: links. This would be too complicated to fix (in crengine and in frontend). (When I need to do a dict lookup of some word there, I just follow/jump to the footnote at end of book, do my stuff there, and jump back).

Would it be possible to have a popup menu on the inline footnote to "go to endnote", where presumably all these things will work? The idea is if I try to highlight, lookup, follow link, etc., it won't work, but it will give me both and indication that it's not "supposed" to work and the chance to go elsewhere and do what I want.

**Comment by pkb** [comment] 2020-09-06 02:50
> 
> `a`
> Links are not supported in in-page (styled) and popup (not styled) footnotes.
> 
Long time ago I was changing this (for my personal use :)) @poire-z has changed a lot since than. But [this](https://gist.github.com/pkb/cfaa5ae8ca292c99713fa38037fc3aae) simple patch makes links in footnotes kind of  work (it detects them a bit higher then they actually are :)) on QT CoolReader. Don't know if there is some specific in case of Koreader

**Comment by hius07** [comment] 2020-09-11 06:18
Since we are discussing popup footnotes here, not very nice word spacing:

![5](https://user-images.githubusercontent.com/62179190/92873362-9fbef480-f40f-11ea-9f65-9ebfe987d812.png)

**Comment by Frenzie** [comment] 2020-09-11 06:21
That's why I tend to prefer left-aligned, although that looks like a quite egregious example. Maybe MuPDF is just worse at it?

**Comment by Jellby** [comment] 2020-09-11 07:09
> Since we are discussing popup footnotes here, not very nice word spacing:

I guess those narrower spaces are coded differently, as &nbsp; probably? There are a couple more examples in the last footnote, after the one-letter words. I don't know if koreader does normally treat these spaces as non-adjustable, but that seems to be a common interpretation http://jkorpela.fi/chars/spaces.html My opinion is that that's wrong, non-breaking spaces should stretch normally, and when fixed-width spaces are desired other characters are available.

**Comment by hius07** [comment] 2020-09-11 07:22
> I guess those narrower spaces are coded differently, as   probably?

Great, that's the case! The spaces in the book are coded with &#32 and &#160. So no issue with MuPDF here.

**Comment by Frenzie** [comment] 2020-09-11 07:25
Otoh I believe non-breaking space and space are treated the same by our implementation in crengine; if you give me a minimal testcase I can quickly double check but I don't want to waste ten minutes creating one atm.

32 is a normal space; 160 is a non-breaking space.

**Comment by Frenzie** [comment] 2020-09-11 07:25
Actually it'd be easy to see by just hiding that popup footnote in the screenshot to show how crengine deals with the non-breaking spaces. ;-)

**Comment by hius07** [comment] 2020-09-11 07:32
> to show how crengine deals

It is in the upper parts of the pics (above the minibar). Crengine treats both kind of spaces the same.

**Comment by Frenzie** [comment] 2020-09-11 08:17
Ok, good. That's what I thought. I'd consider it a bug in MuPDF, but it may have been fixed already. Cf. https://github.com/koreader/koreader-base/pull/762

**Comment by poire-z** [comment] 2020-09-12 08:23
> The spaces in the book are coded with &#32 and &#160. So no issue with MuPDF here.

It is an issue with MuPDF: crengine does that right (stretching/shrinking space and nbsp the same), but MuPDF does not. Might be fixed in newer MuPDF indeed (or not).

**Comment by poire-z** [comment] 2020-09-12 08:40
> Long time ago I was changing this (for my personal use :)) @poire-z has changed a lot since then. But this simple patch still makes links in footnotes kind of work (it detects them a bit higher than they actually are :)) on QT CoolReader. Don't know if there is some specific in case of Koreader

I had a try.
If they are a bit higher, it's probably just a shift needed because of the footnote separator/margin.
Even if it would be nice to allow doing some dict lookup of text in these in-page footnotes, it causes MANY other ugly and hard to solve issues :) 

<kbd>![image](https://user-images.githubusercontent.com/24273478/92991184-59869580-f4e2-11ea-8a0d-310094442318.png)</kbd>
Here, I highlighted from `Peter` to `impérial`. It got the xpointers right. But as footnotes might not be ordered as in the document, and these 2 were indeed not, I have selected a whole bunch of text between these (footnotes 5, 6, 7, ... 27, 28, 29, 30 :)
Same kind of issue then when highlighting the current page main text, and selecting up to in the bottom (to go turn the page to continue selection on the main text in the next page): the footnote is transiently selected, which make the whole thing super slow.
And the highlights made in such footnotes are not drawn on the in-page footnotes (that's KOReader frontend code's job, and would be quite some work to have it working...)

So, may be that could be made an option to have it only work for single word selection and dict lookup.
But well...

> Would it be possible to have a popup menu on the inline footnote to "go to endnote", where presumably all these things will work? The idea is if I try to highlight, lookup, follow link, etc., it won't work, but it will give me both and indication that it's not "supposed" to work and the chance to go elsewhere and do what I want.

Haven't looked at that, but it feels not that easy.
We have these in-page footnotes text in the current page image, but not much reference to where they are. We might get x/y with added code similar to @pkb patch, but we'd need to guess the xpointer of this x/y, which would not be the real footnote target, which might be strange for multi-pages footnotes.
And there's still all the interaction with text selection extension.

But you can jump to it by taping/swiping around the footnote link in the main text - which is what I'm doing and feels natural once you have seen that no gesture works in the bottom part of a page :)
(So, I'm not to keen on doing any work on that.)
(Or may be, just onHold: if no result (blank area, or in-page footnote), get x/y as with @pkb patch and jump to that x/y, even if it's not the start of the footnote.)

**Closed** 2020-09-18 16:09 UTC
Labels: enhancement

**Comment by hius07** [comment] 2020-09-20 07:46
https://github.com/koreader/koreader/blob/27fe0d7957fd48c375cdae48bc3bf30ceef1edeb/frontend/ui/widget/footnotewidget.lua#L94
No, `strike`, `strikethrough` and `underline` doesn't work in popups. Maybe because of

https://github.com/koreader/koreader/blob/27fe0d7957fd48c375cdae48bc3bf30ceef1edeb/frontend/ui/widget/footnotewidget.lua#L77

**Comment by poire-z** [comment] 2020-09-20 07:49
> Maybe because 

Obviously :) But let's keep that so it will work the day we update to a MuPDF version that does support that.

**Comment by Frenzie** [comment] 2020-09-20 07:54
It doesn't? Curious, the default MuPDF styles contain all kinds of text-decoration references. For the future I suppose. :-)
