### ISSUE TITLE
The "Long press to select" screensaver folder/image doesn't work on Kindle Keyboard

### ISSUE THREAD

**Issue by aik099** [koreader/koreader#7512] opened 2021-04-06 20:15 UTC
* KOReader version: koreader-kindle-legacy-v2021.03
* Device: Kindle Keyboard WiFi

#### Issue

Some UI elements, like screensaver folder/file selection from the menu, isn't adapted for non-touch based device.

#### Steps to reproduce

1. be on the main screen before the book is opened
2. press the Menu button on the keyboard to open the top menu
3. select gear icon (2nd icon from the left)
4. inside the gear's icon menu choose the "Settings" sub-menu
5. try changing screensaver image, screensaver folder, select any other file/folder
6. a file browser is opened with 1st item says to use "Long press" action to make a selection
7. activating that the "Long press" file browser item doesn't do anything (e.g. select current folder)
8. activating the file itself via a 5-way joystick doesn't select it

I've attempted to make KOReader use the same screensavers as Kindle itself from the "linkss/screensavers" folder instead of the "screenshots" folder, which is empty (or doesn't exist).

**Comment by Frenzie** [comment] 2021-04-07 06:52
I'll close this as a duplicate of https://github.com/koreader/koreader/issues/3818. Help very much welcome! :-)

**Closed by Frenzie** 2021-04-07 06:52 UTC
Labels: NT, bug, duplicate, help-wanted
