### ISSUE TITLE
part of the screen is not refreshed when entering submenu sometimes

### ISSUE THREAD

**Issue by hombretranquilo** [koreader/koreader#1463] opened 2015-03-20 12:48 UTC
Top submenu tabs ("Calibre wireless connection", "OTA update", etc) are not shown properly on Aura HD. Usually icons disappear, and first text line is not shown, or is cut. Rarely tab looks fine.
![imag0055](https://cloud.githubusercontent.com/assets/8158703/6751732/d4e59ce6-cf07-11e4-880f-ca817b8bce46.jpg)

**Comment by chrox** [comment] 2015-03-21 04:44
I can reproduce this on Kindle Paperwhite 1 with firmware 5.4.4 but cannot reproduce it on PocketBook 840 firmware 5.4.

**Comment by hombretranquilo** [comment] 2015-04-15 21:15
I've updated from v2014.11-163 to v2014.11-181 and the issue just vanished. Thanks.

**Comment by chrox** [comment] 2015-04-16 00:58
Probably #1488 also fixes this.

**Comment by hwhw** [comment] 2015-04-16 08:16
OK, closing this for now then!

**Closed by hwhw** 2015-04-16 08:16 UTC
