### ISSUE TITLE
how to set fallback font, besides edit settings.reader.lua

### ISSUE THREAD

**Issue by frankyifei** [koreader/koreader#1609] opened 2015-08-31 10:31 UTC
* just want to know how to do it in gui? long tap fontlist only open a confirmbox to set default font

**Comment by Frenzie** [comment] 2015-08-31 10:34
There doesn't seem to be a GUI setting for that, unless I'm overlooking it.

**Comment by frankyifei** [comment] 2015-08-31 10:39
ok, just to confirm, I'm working on it.

**Comment by chrox** [comment] 2015-09-01 15:52
@frankyifei Did you notice that the font fallback mechanism in crengine is broken since
 https://github.com/koreader/koreader/commit/aff8ed1140e3e135578768f34e6e0569beaaf0f3 ? On my emulator all Chinese characters in EPUB documents are displayed as "?" unless I select the "Droid sans fallback" font manually.

**Comment by frankyifei** [comment] 2015-09-01 16:10
I noticed that if the active font is not Chinese, it will show '?'. But it's not a big problem. Crenegine will show '?' If it can't find that char code in the font. I think the problem is in credocument.lua. It should not be something wrong in crengine' code.

**Comment by chrox** [comment] 2015-09-02 11:38
But I would expect crengine use the fallback font "Droid Sans Fallback" to render Chinese glyphs that are missing in selected font such as the default "Noto serif" and it's the fallback mechanism until https://github.com/koreader/koreader/commit/aff8ed1140e3e135578768f34e6e0569beaaf0f3 . I bisected the recent commits and find the difference. The last working commit before the above mentioned commit works just as expected but the first working commmit after that has this bug. And it's really annoying to read pages of "?" for nearly all my Chinese document. I think this bug is the last barrier to publish a new stable version.

**Comment by frankyifei** [comment] 2015-09-02 13:16
I tried to set fallback font to other chinese font,like code2000 and other fonts works well. it just does not work with droid sans fallback. I dont know why.

**Comment by frankyifei** [comment] 2015-09-02 13:27
Another question, what is the font called DroidSansFallbackFull.ttf? this font seems not working with crengine. it always shows"# can not register font <./fonts/droid/DroidSansFallbackFull.ttf>"

**Comment by frankyifei** [comment] 2015-09-02 13:48
NotoSansCJK is working and contains more characters. why not use this font? if this font is too big, it is easy to delete some characters and make it smaller. it's about 16mb.

**Comment by chrox** [comment] 2015-09-03 01:46
Oh that's really good news. If it's the problem of "Droid sans fallback" I would really like to use another fallback font such as NotoSansCJK which is much better looking. Is it possible to make NotoSansCJK less than 10mb?

**Comment by NiLuJe** [comment] 2015-09-03 02:27
Wasn't that issue fixed after a full rebuild? I remember you mentioning something of that effect at the time, and while I can't vouch for the emulator (since lua/luarocks is being stupid on my box), but I *think* I checked on a Kindle and it worked fine there?

**Comment by frankyifei** [comment] 2015-09-03 03:07
not fixed even after  a full rebuild on emulator. But it works for my kindle.

**Comment by chrox** [comment] 2015-09-03 07:39
Yes, I can reproduce this bug only on the emulator, koreader on Kindle and Android seems fine. @frankyifei could you also send a PR to replace the  "droid sans fallback" with "noto sans cjk"?

**Comment by frankyifei** [comment] 2015-09-03 07:42
so do you want to edit the font to 10mb or just upload the origin one ?
I think I still need to change one or two files in frontend to match the change.

**Comment by Frenzie** [comment] 2015-09-03 08:05
But should it be smaller? For me personally I'm mostly just thinking about stuff like IPA, but I'm sure speakers of e.g. Arabic or Hebrew would appreciate support. I know that Noto Sans has glyphs for all of these things, but I'm not sure if and how all can be supported at once.

**Comment by frankyifei** [comment] 2015-09-03 11:08
I think it's possible to make a large font that contains all these characters.

**Comment by Frenzie** [comment] 2015-09-03 12:42
If [this page](http://openfontlibrary.org/en/font/noto-sans) is accurate, it seems to me that at the very least the regular Noto Sans/Serif characters are extremely desirable to have as fallback for the extended European characters (including IPA) and Cyrillic — besides, it's only a few hundred kB. Ideally I'd also like to see Arabic and possibly something like Tamil, but I guess that'd be making it too large — it might be worth investigating though. I'd also quite appreciate the kind of stuff supported by [junicode](https://en.wikipedia.org/wiki/Junicode), although I don't know if the Noto family does so, but I don't think such a relatively niche thing is even half as relevant as any of the others I mentioned. Above all, it seems that a single fallback font isn't a very great solution, but I guess we're stuck with what crengine gives. :)

**Comment by frankyifei** [comment] 2015-09-03 14:56
the file size is about 11mb, and includes Greek, Cyrillic, IPA, Arabic, Tamil. if that is good enough, i'll create a PR. I also edited frontend/ui/font.lua and /frontend/document/credocument.lua to match the change. The two Droidsansfallback font files will be deleted. new font and it license will be in resources/fonts/noto.

**Comment by chrox** [comment] 2015-09-03 15:37
Great, thanks for that.

**Comment by frankyifei** [comment] 2015-09-03 15:42
can you merge my last PR? so I can create a new one. Or should I just upload you can merge them at once?

**Comment by Frenzie** [comment] 2015-09-03 15:48
I don't know how accurate my perfunctory assessment of most important writing systems is, but that sounds great! Looking at the full archive I'm getting the impression that it wouldn't take more than another MB or maybe two to include *everything*[1] and that only the CJK files are over 15 MB each. Is that something we should consider?

[1] Well, I suppose, we probably don't need hieroglyphics and cuneiform, each of which is about 500 kB. :P

**Comment by frankyifei** [comment] 2015-09-03 15:50
I deleted CJK extensions and only left about 20000 glyphs. I think it's enough for normal reading.

**Comment by Frenzie** [comment] 2015-09-03 16:01
I mean everything as in Urdu, Javanese, Khmer, Bengali, Tibetan, Mongolian, Ethiopic, etc., including a few writing systems I've never even heard of (like Tagalog, although that one's apparently no longer in active use). I have no opinion on the extended Chinese glyphs, besides the observation that they seems to take up significantly more space than all of those other writing systems together.

**Comment by chrox** [comment] 2015-09-12 05:18
Close this now since this feature is in master branch.

**Closed by chrox** 2015-09-12 05:18 UTC

**Comment by seefood** [comment] 2015-10-12 15:28
But RTL is not rendering, so Hebrew, Arabic, Urdu etc won't display correctly.

**Comment by frankyifei** [comment] 2015-10-12 15:36
Crengine does not support right to left now

2015年10月13日星期二，Ira <notifications@github.com> 写道：

**Comment by Frenzie** [comment] 2015-10-12 16:19
@seefood Thanks for bursting my bubble. xD

What does this mean for the long-term? I have to say that superficially looking at desktop applications, e.g. FBReader and Calibre seem to look more promising than CoolReader as far as rendering EPUBs goes. Admittedly I use KOReader first and foremost for its PDF and DjVu support, with EPUB mostly as a convenience because for me it's generally good enough and certainly less trouble than switching apps.

**Comment by frankyifei** [comment] 2015-10-12 16:42
Fbreader is not so good. It does not have enough css support compared
with Coolreader. Many epubs will lost format in fbreader. Caliber is good
but not perfect. Redium is best for epubs.
I like reading epubs on my kindle, most of the time crengine will show the
format correctly. And If someone can bring calibre or Redium to kindle,
mobi will be useless for me.

2015年10月13日星期二，Frans de Jonge <notifications@github.com> 写道：

**Comment by Frenzie** [comment] 2015-10-12 18:16
I've never seen a table that looks presentable in cr.

On October 12, 2015 6:42:17 PM GMT+02:00, "Yifei(Frank) ZHU" <notifications@github.com> wrote:
>Fbreader is not so good. It does not have enough css support compared
>with Coolreader. Many epubs will lost format in fbreader. Caliber is
>good
>but not perfect. Redium is best for epubs.
>I like reading epubs on my kindle, most of the time crengine will show
>the
>format correctly. And If someone can bring calibre or Redium to kindle,
>mobi will be useless for me.
>
>2015年10月13日星期二，Frans de Jonge <notifications@github.com> 写道：
>
>> @seefood <https://github.com/seefood> Thanks for bursting my bubble.
>xD
>>
>> What does this mean for the long-term? I have to say that
>superficially
>> looking at desktop applications, e.g. FBReader and Calibre seem to
>look
>> more promising than CoolReader as far as rendering EPUBs goes.
>Admittedly I
>> use KOReader first and foremost for its PDF and DjVu support, with
>EPUB
>> mostly as a convenience because for me it's generally good enough and
>> certainly less trouble than switching apps.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/koreader/koreader/issues/1609#issuecomment-147450249>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/koreader/koreader/issues/1609#issuecomment-147457355

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by seefood** [comment] 2015-10-12 18:53
I was just shopping around for a reader that would work on a hacked android-running Kobo. I have several good readers for Android (I think all freeware, not Free Software sadly) that render Hebrew satisfyingly (correct direction and justification at the minimum). The problem is that I tried them on my old Nook, and the Android is so old (I think 1.6) that most of the apps didn't work with it, and the one that did (old version of Moon reader) rendered Hebrew fine in the menus but backwards in the actual text. That's when I broke down and started looking for a hackable alternative :)

I only built KOreader on my Ubuntu and ran it once with an ePub in Hebrew (basic text, didn't try anything fancy like rendering tables, epub3 or other exotics), and it didn't work. should it behave differently is built for Android?

**Comment by Frenzie** [comment] 2015-10-12 19:10
No, it'll behave the same.

On October 12, 2015 8:53:34 PM GMT+02:00, Ira <notifications@github.com> wrote:
>I was just shopping around for a reader that would work on a hacked
>android-running Kobo. I have several good readers for Android (I think
>all freeware, not Free Software sadly) that render Hebrew satisfyingly
>(correct direction and justification at the minimum). The problem is
>that I tried them on my old Nook, and the Android is so old (I think
>1.6) that most of the apps didn't work with it, and the one that did
>(old version of Moon reader) rendered Hebrew fine in the menus but
>backwards in the actual text. That's when I broke down and started
>looking for a hackable alternative :)
>
>I only built KOreader on my Ubuntu and ran it once with an ePub in
>Hebrew (basic text, didn't try anything fancy like rendering tables,
>epub3 or other exotics), and it didn't work. should it behave
>differently is built for Android?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/koreader/koreader/issues/1609#issuecomment-147490377

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Frenzie** [comment] 2015-10-12 19:48
Btw, why didn't you just try the Android build? It's a heck of a lot easier and faster than building the whole program on your PC. :P

**Comment by seefood** [comment] 2015-10-13 07:19
Well, I never built anything for Android, no SDK installed, and building it for Linux was 4 commandlines away, no need to copy over APK and such... it WAS the easier way, trust me :-)

You're right though. I've been using Linux 22 years and Android about 4, it's time I learn to build an APK :)

**Comment by Frenzie** [comment] 2015-10-13 07:34
Sorry, I meant the *preexisting* Android build. See [releases](https://github.com/koreader/koreader/releases). The Android build process is of course harder because like you said it involves an SDK and cross-compiling.
