### ISSUE TITLE
Onyx: Freeze after restoring from suspend

### ISSUE THREAD

**Issue by asim215** [koreader/koreader#7052] opened 2020-12-25 16:46 UTC
* KOReader version: 2020.12
* Device: Onyx Boox Kon-Tiki
* OS: Android Pie, api 28
* Build flavor: rocks

#### Issue
Koreader freeze after resume from suspend in landscape mode using pdf and epub files. It works in portrait mode.

#### Steps to reproduce
[youtube](https://youtu.be/NUtVwfYJLRM)

**Comment by pazos** [comment] 2020-12-25 16:59
@asim215: please follow bug report template. We need logs

**Comment by asim215** [comment] 2020-12-25 17:19
Sorry. Here:
[1.txt](https://github.com/koreader/koreader/files/5742224/1.txt)

**Comment by pazos** [comment] 2020-12-25 19:18
Thank you. I cannot reproduce here. Probably yet another crappy onyx bug.

Just need to know if it happens on other boox devices too. Pinging @Galunid.

It should be a matter of disabling Hw rotation on affected devices.

@asim215: In the mean time please run FM - tools - more tools - dev optioms - start eink test and copy/paste manufacturer, model, brand etc here, so we can label your device as affected by BUG ROTATION

**Comment by Galunid** [comment] 2020-12-26 01:22
I toggled 90/270 rotations on nova 2 and couldn't reproduce. My onyx firmware was 3.0. I can get something similar when I open lights dialog and suspend the device though.

**Comment by asim215** [comment] 2020-12-26 06:26
@pazos 
![IMG_20201226_092344.jpg](https://user-images.githubusercontent.com/7127165/103146535-13d19e00-475c-11eb-9489-a530537b0a1a.jpg)
It also happens if I set 90 rotation clockwise and 90 counterclockwise manually. Tap on corner in video toggle orientation.

**Comment by asim215** [comment] 2020-12-26 06:54
It somehow connected with onyx orientation. See below similar problem. Freeze in portrait after switching to landscape. Does it possible to read android orientation and set it for koreader? Maybe that will solve the problem for onyx.
[youtube](https://youtu.be/C8HUQruJrq8)

**Comment by pazos** [comment] 2020-12-26 12:44
A quick look at logs suggests that the app is not paused when the suspend button is pressed. I cannot say for sure. If you're able to install pidcat please enable debug logs (`filemanager` ->  `tools` -> `more tools` -> `dev options` -> `enable debug logs`) and paste here a full log obtained with `pidcat org.koreader.launcher`

On a normal android device the power button triggers the onPause() -> onStop() on the foreground app and the key event never reaches it. Also pressing the power button doesn't trigger a configuration change.

>  I can get something similar when I open lights dialog and suspend the device though.

I cannot reproduce this, too. Anyways I think it is a good idea to exit the dialog onPause. Lets see first if onPause is even triggered at all.

**Comment by asim215** [comment] 2020-12-26 13:49
@pazos 
Thank you for your guidance. I hope it will help:
[pidcat_debug.txt](https://github.com/koreader/koreader/files/5743154/pidcat_debug.txt)

**Comment by pazos** [comment] 2020-12-26 18:19
> Thank you for your guidance. I hope it will help:

It does, thanks!

See a normal lifecycle change from your logs (w/ [annotated app events](https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L1043-L1064)):

```
[TimeoutHelper] onPause
Android application event 13 # APP_CMD_PAUSE
Android application event 14 # APP_CMD_STOP
Android application event 12 # APP_CMD_SAVE_STATE
Android application event 7 # APP_CMD_LOST_FOCUS
Android application event 10 # APP_CMD_START
Android application event 6 # APP_CMD_GAINED_FOCUS
Android application event 11 # APP_CMD_RESUMED
 [TimeoutHelper] onResume
```
Now see what happens just at the end of the log (on a rotated state):

```
[TimeoutHelper] onPause
Android application event 13 # APP_CMD_PAUSE
Android application event 14 # APP_CMD_STOP
Android application event 12 # APP_CMD_SAVE_STATE
Android application event 8 # APP_CMD_CONFIG_CHANGED
```

Now, that last line doesn't make sense. The app is stopped, its state was saved. We didn't lost focus yet but whatever config change that happens here shouldn't be delivered to the app. APP_CMD_LOST_FOCUS should follow.

No idea how Onyx implemented its lockscreen, but that's not standard.

A proper way to handle this if we can reproduce elsewhere is **don't react to config changes when the app is stopped**. But if just happens on Onyx devices I would prefer to keep things as is and see what happens if there're no config changes (at least no native orientation changes).

**Comment by Galunid** [comment] 2020-12-26 19:25
I tried v2020.12 version on Nova 2. It works as expected. 
@pazos pidcat in case it helps [logs.txt](https://github.com/koreader/koreader/files/5743546/logs.txt)

**Comment by asim215** [comment] 2020-12-26 20:48
@pazos 
I did not see onResume after restore from suspend. So that method doesn't even reached and the problem in onPause?
@Galunid 
Interesting I don't see event #7 (APP_CMD_LOST_FOCUS). I suppose it was just cut from logs? Or doesn't presented there?

**Comment by asim215** [comment] 2020-12-27 15:32
Also when in landscape I go to Home Screen KOreader not active visually. And from that go to suspend. Resume happens with no problems. Then I switch to KOreader process in apps list. And it works fine, no freeze there. So I assume problem happens only while KOreader stays active in landscape and from that goes to suspend.

**Comment by pazos** [comment] 2020-12-27 15:40
Yup. That sounds like borked lock screen code. Onyx doesn't make their ereaders Android compatible. They just happens to behave well enough for the 99'9999999999999999999% of apps written against android Sdk. Since nobody uses the ANativeActivity framework other than games, probably KOReader is the only app affected by this bug.

It should be fixed with https://github.com/koreader/android-luajit-launcher/pull/282 (disable surface rotation, using sw rota instead) as this will ensure there're no config changes delivered to the app. Feel free to test if you wish, if not please wait a couple of days until it reaches a nightly.

**Comment by asim215** [comment] 2020-12-27 15:48
Also it happens only if screen orientation of Android doesn't correspond to one in KOreader. Here example of working when they correspond and freeze in portrait mode.
[youtube](https://youtu.be/kWS1C3ZKeB4)

**Comment by pazos** [comment] 2021-01-02 12:39
@asim215: please test http://build.koreader.rocks/download/nightly/v2020.12-72-g5756f1f_2021-01-02/koreader-android-arm-v2020.12-72-g5756f1f_2021-01-02.apk

**Comment by asim215** [comment] 2021-01-02 15:44
@pazos 
Unfortunately, it becomes worse. Because of software rotation, now to call the menu of the device I need to swipe from the original device rotation. So if a book in the landscape, to call menu can be from the portrait side. Now it is crushed more from suspend. It also throws at the home screen from koreader after resume.
Video example on [youtube](https://youtu.be/eZ9WADKLgUw).
I think to undo changes for hardware rotation will be better. And to way around freeze I can rotate the device to landscape, and after that, use koreader landscape without a freeze. But if they will not correspond they will still be lead to freezing.

**Comment by pazos** [comment] 2021-01-02 15:57
:( I will revert the SW rota. 

There's nothing I can do to fix a badly implemented device, I'm afraid.

**Closed** 2021-01-02 15:58 UTC
Labels: Android, firmware, not our bug

**Comment by asim215** [comment] 2021-01-02 16:09
Thank you for your time.
