### ISSUE TITLE
Glowlight setting for nook glowlight plus 7.8"

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#7196] opened 2021-01-24 09:42 UTC
Device: Nook glowlight plus 7.8"
Firmware: Android 4.4.2 (rooted)
Koreader version: 2021.01

Issue: there is no "glowlight" (orange led adjustment) option in the front light setting of Koreader.

I do know that if Kobo device which support orange led, Koreader will automatically have orange light option inside front light setting.

I would like to have this option, too.

Please kindly take a look.

Thank you.

**Comment by pazos** [comment] 2021-01-24 10:29
Please check closed issues before opening duplicates.

Duplicate of https://github.com/koreader/koreader/issues/6469

**Closed by pazos** 2021-01-24 10:29 UTC
Labels: enhancement
