### ISSUE TITLE
Turning on WiFi may hang the reader on Kobo

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#939] opened 2014-09-30 21:22 UTC
On Kobo Aura HD (haven't tested on others) clicking on "Wikipedia" button in the dictionary dialog with wifi turned off shows the prompt "Do you want to Turn on Wifi?" and if you click on "OK" then the reader hangs. Only a long hold on the power-off slide allows one to reboot from such situation.

Note: this happens if no WiFi networks are actually configured. I haven't tested it with a WiFi network configured.

**Comment by igrowheart** [comment] 2015-02-08 12:42
I have the same issue on KOBO H2O. 
The root cause is on the networkmgr.lua(line 25), the script is hard coded to execute on old folders. So if the platform name "ntx508" is changed, the script fails.
I changed the "ntx508" to "mx50-ntx" on my H2O and it works now.
https://github.com/koreader/koreader/blob/master/frontend/ui/networkmgr.lua

```lua
local function koboEnableWifi(toggle)
    if toggle == 1 then
        local path = "/etc/wpa_supplicant/wpa_supplicant.conf"
        os.execute("insmod /drivers/ntx508/wifi/sdio_wifi_pwr.ko 2>/dev/null")
        os.execute("insmod /drivers/ntx508/wifi/dhd.ko")
        os.execute("sleep 1")
        os.execute("ifconfig eth0 up")
        os.execute("wlarm_le -i eth0 up")
        os.execute("wpa_supplicant -s -i eth0 -c "..path.." -C /var/run/wpa_supplicant -B")
        os.execute("udhcpc -S -i eth0 -s /etc/udhcpc.d/default.script -t15 -T10 -A3 -b -q >/dev/null 2>&1")
    else
        os.execute("killall udhcpc wpa_supplicant 2>/dev/null")
        os.execute("wlarm_le -i eth0 down")
        os.execute("ifconfig eth0 down")
        os.execute("rmmod -r dhd")
        os.execute("rmmod -r sdio_wifi_pwr")
    end
end
```

Here is a script from kobo start menu for your reference:
wifi_enable_dhcp.sh
```sh
#!/bin/sh

#export PATH=$PATH:/sbin:/usr/sbin

#root=/mnt/onboard/.kobo/KoboLauncher/usbnet

lsmod | grep -q sdio_wifi_pwr || insmod /drivers/$PLATFORM/wifi/sdio_wifi_pwr.ko
lsmod | grep -q dhd || insmod /drivers/$PLATFORM/wifi/dhd.ko


sleep 2
ifconfig eth0 up
wlarm_le -i eth0 up

pidof wpa_supplicant >/dev/null || wpa_supplicant -s -i eth0 -c /etc/wpa_supplicant/wpa_supplicant.conf -C /var/run/wpa_supplicant -B

sleep 1

#if you need dhcp/dynamic uncomment next and comment the 'ip ad below'
/sbin/udhcpc -S -i eth0 -s /etc/udhcpc.d/default.script -t15 -T10 -A3 -b -q >/dev/null 2>&1 &

#ip ad add 192.168.2.101/24 dev eth0


#touch /var/log/lastlog
#$root/dropbear -p 22 -E -r $root/host.key.rsa -d $root/host.key.dss


```

**Comment by igrowheart** [comment] 2015-02-08 12:51
I have to say I love Koreader. It is much better on my KOBO H2O than nickel.

**Comment by Markismus** [comment] 2015-02-08 15:58
`PLATFORM` is assigned in `rcS` only?
`rcS` taken from Tshering's Start Menu v6:
```sh
PLATFORM=freescale
if [ `dd if=/dev/mmcblk0 bs=512 skip=1024 count=1 | grep -c "HW CONFIG"` == 1 ]; then
  CPU=`ntx_hwconfig -s -p /dev/mmcblk0 CPU`
  PLATFORM=$CPU-ntx
fi

if [ $PLATFORM == freescale ]; then
  if [ ! -s /lib/firmware/imx/epdc_E60_V220.fw ]; then
    mkdir -p /lib/firmware/imx
    dd if=/dev/mmcblk0 bs=512K skip=10 count=1 | zcat > /lib/firmware/imx/epdc_E60_V220.fw
    sync
  fi
elif [ ! -e /etc/u-boot/$PLATFORM/u-boot.mmc ]; then
  PLATFORM=ntx508
fi
```

So `PLATFORM` could be `freescale`, `ntx508` or the newer values `$CPU-ntx`, which apparently resolves to `mx50-ntx` for the H2O. 

Why is there no reference to the `freescale` WiFi drivers?

**Comment by Markismus** [comment] 2015-02-08 16:41
I think we should rather look at `scriptmenuwifi.sh` from Start Menu.

**Comment by Markismus** [comment] 2015-02-08 17:10
I replaced the 1st set of commands with Tshering's from `wifi_enable_dhcp.sh` and I replaced ntx508 with mx50-ntx. Both work but only when I have previously connected with Kobo Start Menu.

**Comment by igrowheart** [comment] 2015-02-10 05:30
Sorry that I just saw the update.
I updated ntx508 with mx50-ntx and it is working.
Thanks Markismus for the update.

**Comment by Markismus** [comment] 2015-02-10 15:58
Pull request #1423 should fix this. Does anyone still experience hangups?

**Comment by chrox** [comment] 2015-04-01 11:23
This issue seems to have been solved. Close this now.

**Closed by chrox** 2015-04-01 11:23 UTC
Labels: bug, Kobo
