### ISSUE TITLE
NEED Chinese input method required

### ISSUE THREAD

**Issue by asura1king** [koreader/koreader#6133] opened 2020-05-09 08:59 UTC
* KOReader version:2020.4
* Device:KOBO FROMA

Now there are many users from China, with a large number of annotation and search needs. However, the current version cannot support Chinese input, which is inconvenient to use and needs developer support.

**Comment by Frenzie** [comment] 2020-05-09 09:19
Please don't open duplicates. This is a duplicate of #1938 as was pointed out in #6132 yesterday.

**Closed by Frenzie** 2020-05-09 09:19 UTC
Labels: duplicate
