### ISSUE TITLE
Unable to build on apple silicon

### ISSUE THREAD

**Issue by tsao-chi** [koreader/koreader#9287] opened 2022-07-03 11:51 UTC
* KOReader version: 4f7ed7e7063625e441270d571cfd8cb3327b145a

#### Issue

unable to build on apple silicon

#### Steps to reproduce

Run commands in github actions workflow file
https://github.com/koreader/koreader/blob/master/.github/workflows/build.yml
```
          brew install ......

          export MACOSX_DEPLOYMENT_TARGET=11;
          export PATH="$(brew --prefix)/opt/gettext/bin:$(brew --prefix)/opt/gnu-getopt/bin:$(brew --prefix)/opt/bison/bin:$(brew --prefix)/opt/grep/libexec/gnubin:${PATH}";
          ./kodev release macos

```

See the error
```

[ 75%] Performing build step for 'luasec'
------------------------------
** Build for Mac OS X 10.11 **
------------------------------
ld: warning: ignoring file /Users/builder/Documents/koreader/base/thirdparty/openssl/build/arm64-apple-darwin21.5.0/openssl-prefix/src/openssl/libssl.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/builder/Documents/koreader/base/thirdparty/openssl/build/arm64-apple-darwin21.5.0/openssl-prefix/src/openssl/libcrypto.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
[ 87%] Performing install step for 'luasec'
------------------------------
** Build for Mac OS X 10.11 **
------------------------------
ld: warning: ignoring file /Users/builder/Documents/koreader/base/thirdparty/openssl/build/arm64-apple-darwin21.5.0/openssl-prefix/src/openssl/libssl.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/builder/Documents/koreader/base/thirdparty/openssl/build/arm64-apple-darwin21.5.0/openssl-prefix/src/openssl/libcrypto.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
[100%] Completed 'luasec'
[100%] Built target luasec
install_name_tool -change \
		`otool -L "build/arm64-apple-darwin21.5.0/common/ssl.so" | grep "libcrypto.1.1.dylib " | awk '{print $1}'` \
		libs/libcrypto.1.1.dylib \
		build/arm64-apple-darwin21.5.0/common/ssl.so
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input
make[1]: *** [build/arm64-apple-darwin21.5.0/common/ssl] Error 1
make: *** [base/build/arm64-apple-darwin21.5.0/luajit] Error 2
```

**Comment by tsao-chi** [comment] 2022-07-03 11:54
The problem is that ld ignored libcrypto.dylib so the output of `otool -L "build/arm64-apple-darwin21.5.0/common/ssl.so" | grep "libcrypto.1.1.dylib " | awk '{print $1}'` is empty

**Comment by pazos** [comment] 2022-07-03 12:10
Duplicate of https://github.com/koreader/koreader/issues/8797

Please use that ticket instead

**Closed by pazos** 2022-07-03 12:10 UTC
