### ISSUE TITLE
Numbering of definitions in dictionary pop-up misaligned (on KOA3)

### ISSUE THREAD

**Issue by superkryodev** [koreader/koreader#7946] opened 2021-07-08 13:52 UTC
* KOReader version: 2021.06 "Catkin"
* Device: Kindle Oasis 3

#### Issue
In the dictionary pop-up, the numbering of definitions is misaligned to the left leaving the numbers partly cut out (see the screenshot attached)
![Dictionay](https://user-images.githubusercontent.com/75697951/124933436-ccc24080-dffb-11eb-971e-a20c030b4468.png)

#### Steps to reproduce
Bring up the dictionary pop-up

**Comment by poire-z** [comment] 2021-07-08 14:44
I believe this has already been mentionned in some issue, but I can't find it :/
It's due to MuPDF handling of margins or indents with list items I think. Not sure it is our fault and we can fix it, or this specific dictionary of yours having bad CSS/HTML, which could be fixed with some CSS (https://github.com/koreader/koreader/wiki/Dictionary-support).

Pinging @Markismus who played a lot with HTML dicts and fixing them: does this remind you of something? Was it you or another user that had this issue?

**Comment by superkryodev** [comment] 2021-07-08 14:59
Thanks for responding quickly. Indeed I also suspected this but thought better check here before taking to https://github.com/BoboTiG/ebook-reader-dict which generates an updated wiktionary dump.

**Comment by poire-z** [comment] 2021-07-08 15:17
Well, it's probably not their fault or they to fix that.
MuPDF main job is not to render HTML :) so it has some quirks (for which they probably have some explanations). So, better fix that on our side or yours (ours if their dicts are popular).

For dictionary, we use this simple CSS:
https://github.com/koreader/koreader/blob/0e606251600021f5adda07755fa94f6c70b93818/frontend/ui/widget/dictquicklookup.lua#L734-L764

For footnote widgets, I spent more time on them, and ended up with some larger CSS:
https://github.com/koreader/koreader/blob/0e606251600021f5adda07755fa94f6c70b93818/frontend/ui/widget/footnotewidget.lua#L58-L127
You might meet something similar to what I wrote at lines 81-84 (of course, you can't remove the bullet/number, but may be some left padding/margin may help).

So, you'd need to look at these HTML dict outputs to see what it uses (UL/LI , DL/DT) and may be tweak the dictquicklookup CSS.

**Comment by superkryodev** [comment] 2021-07-08 17:58
> Can't really say without the HTML. :-)

Not sure it's sufficient, but the corresponding html code of the entry is
<w><p><a name="important"/><b>important</b> \ɪmˈpɔːtənt\<br/><br/><p>From Middle English <i>important</i>, from Medieval Latin <i>important-, importāns</i>.</p></br><ol><li>Having relevant and crucial value.</li><li><i>(obsolete)</i> Pompous; self-important.</li></ol></p></w>

while the code in the stardict .dict file is basically the same for the definitions
<p>: \ɪmˈpɔːtənt\</p>
<html><p>From Middle English <i>important</i>, from Medieval Latin <i>important-, importāns</i>.</p></br>
<ol><li>Having relevant and crucial value.</li><li><i>(obsolete)</i> Pompous; self-important.</li></ol>

I don't know how to avoid the html being rendered, hope you can see the underlying codes

**Comment by poire-z** [comment] 2021-07-08 18:39
I guess adding after these:
https://github.com/koreader/koreader/blob/0e606251600021f5adda07755fa94f6c70b93818/frontend/ui/widget/dictquicklookup.lua#L745-L753
something like:
```css
         ol, ul { 
             padding-left: 1em; 
        } 
```
or (killing some top and bottom margins, if that would look better)
```css
         ol, ul { 
             margin: 0 0 0 1em; 
        } 
```
or variations around that, may help.

MuPDF has for OL and UL: `margin: 1em 0; padding: 0 0 0 30pt`

**Comment by Frenzie** [comment] 2021-07-08 18:55
Traditionally `li` is regarded as the element that needs the margin-left.

**Comment by poire-z** [comment] 2021-07-08 19:01
May be its own `padding-left: 30pt` (values are TOP RIGHT BOTTOM LEFT, TRBL, TRouBLe as I remember that) is for that, but 30pt on our high dpi screen possible not scaled for DPI (if MuPDF is not informed of that) is too small ?

**Comment by superkryodev** [comment] 2021-07-08 19:13
@poire-z both suggestion solve the cut-off problem. Would be nice if a DPI dependent margin-left could be implemented for `li`. 

Thanks for the quick workaround

**Comment by poire-z** [comment] 2021-07-08 19:19
> Would be nice if a DPI dependent margin-left could be implemented for li.

But our fonts are scaled for DPI, so 1em (1 x font size) gets it scaled. Is 1em just right ? You could check with 0.5em or 1.5em. Also, try to see if it's still ok when the list item numbers go above 9 like 13 or 22.

Also, the 2nd one should reduce the vertical blank space, does it ? Any preference?
![image](https://user-images.githubusercontent.com/24273478/124978541-36f5d800-e032-11eb-99d8-162b9a7dad43.png)

**Comment by Frenzie** [comment] 2021-07-08 19:25
> May be its own padding-left: 30pt (values are TOP RIGHT BOTTOM LEFT, TRBL, TRouBLe as I remember that) is for that, but 30pt on our high dpi screen possible not scaled for DPI (if MuPDF is not informed of that) is too small ?

That's a good hypothesis.

If it's the cause, some part of https://github.com/koreader/koreader/pull/5282 can probably be adapted. It's too late today though.

@superkryodev Could you leave a link to the relevant Wiktionary export?

**Comment by superkryodev** [comment] 2021-07-08 19:34
> Also, the 2nd one should reduce the vertical blank space, does it ? Any preference?
I used the 2nd one with 2em which makes the list more clear but no effect on the top margin

**Comment by superkryodev** [comment] 2021-07-08 19:52
> @superkryodev Could you leave a link to the relevant Wiktionary export?

https://github.com/BoboTiG/ebook-reader-dict/releases/download/en/dict-en.zip

**Comment by Markismus** [comment] 2021-07-16 12:32
@poire-z Didn't run into (un-)ordered lists problems before. 

I probably would rather fix it with a custom css-file accompanying the dictionary or with a default css-file for unaccompanied dictionaries in the dictionary directory. 

This would enable or invite more people to tweak  their settings, instead of it being buried somewhere inside the code.

**Comment by poire-z** [comment] 2021-08-16 17:24
I think we can solve this issue with:
```diff
--- a/frontend/ui/widget/dictquicklookup.lua
+++ b/frontend/ui/widget/dictquicklookup.lua
@@ -751,7 +751,18 @@ function DictQuickLookup:getHtmlDictionaryCss()
         blockquote, dd {
             margin: 0 1em;
         }
+
+        ol, ul, menu {
+            margin: 0; padding: 0 1.7em;
+        }
     ]]
+    -- For reference, MuPDF declarations with absolute units:
+    --  "blockquote{margin:1em 40px}"
+    --  "dd{margin:0 0 0 40px}"
+    --  "ol,ul,menu {margin:1em 0;padding:0 0 0 30pt}"
+    --  "hr{border-width:1px;}"
+    --  "td,th{padding:1px}"
+    --
     -- MuPDF doesn't currently scale CSS pixels, so we have to use a font-size based measurement.
     -- Unfortunately MuPDF doesn't properly support `rem` either, which it bases on a hard-coded
     -- value of `16px`, so we have to go with `em` (or `%`).
@@ -761,6 +772,11 @@ function DictQuickLookup:getHtmlDictionaryCss()
     -- We also keep left and right margin the same so it'll display as expected in RTL.
     -- Because MuPDF doesn't currently support `margin-start`, this results in a slightly
     -- unconventional but hopefully barely noticeable right margin for <dd>.
+    --
+    -- For <ul> and <ol>, bullets and numbers are displayed in the margin/padding, so
+    -- we need a bit more for them to not get truncated (1.7em allows for 2 digits list
+    -- item numbers). Unfortunately, because we want this also for RTL, this space is
+    -- wasted on the other side...

     if self.css then
         return css .. self.css
```

**Closed** 2021-08-17 19:44 UTC
