### ISSUE TITLE
[RFC] On the whole user-plugin thingy...

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#6768] opened 2020-10-08 15:24 UTC
I was thinking of going with a `contrib` folder in the repo, which could include a `plugins` folder for, well, plugins, or platform folders for platform-specific scripts (e.g., https://github.com/koreader/koreader/issues/6399#issuecomment-681026114).

The code could either be in-repo, or added as submodules?

This would allow PRs to simply be steered toward that after initial review (i.e., either ""merge it", "drop it", or "move it to contrib").

Then you just document that globally and/or individually somewhere/somehow in docs and/or wiki.

Thoughts?

**Comment by ezdiy** [comment] 2020-10-08 15:46
I'd go even further, and just be a git URL registry the same way luarocks is. Red tape is what @smartscripts-nl perhaps felt a little discouraged by, and we should do our best to encourage people just doing stuff by removing maximum amount of it.

Ideally:

* User writes a plugin
* Adds his repo url into koreader *somehow*. Perhaps just opening PR "heres my repo, add it".  
Perhaps go even a lil bit riskey, and just parse it from "Plugin Registry" wiki page on build, making the stuff completely unattended.
* We don't care what the plugin does, editorial role is reduced to checking "its not malicious / likely not to damage devices".  
  Or in case of the bolder, unattended option there's implicit assumption there's a degree of accountability to edit github wikis.
* Hide those plugins behind - but visible - checkbox, first on plugin menu. On enable, flash infobox that there's absolutely zero QA whatsoever, and all issues should be directed at owner repo of any given plugin.

As for nuts and bolts, just fetching the wiki page and pulling git urls in a makefile from there should be enough. Later on somebody might come by and make it an online fetch/update feature, but given the current interest that's overkill.

**Comment by pazos** [comment] 2020-10-08 16:02
> User writes a plugin

self contained plugins are somehow limited:

- translations: they don't receive community translations from weblate, they need to provide their own and currently there's no mechanism to translate based on a different po file.

- integration with gestures

- platform limitations (at least **Android**): there's no way to install an user plugin in android on demand. Creating a new folder in internal files dir will crash the Java VM with err=13.  A good workaround is keeping user plugins in dataDir and add that to path and cpath. I guess we can do that for all platforms and keep bundled and user plugins separated.

- optional: put plugin files in a container (a zip file?) with a different mimetype and handle installation from the program.

**Comment by ezdiy** [comment] 2020-10-08 16:17
Yep, menu and gesture stuff is an ongoing issue for plugins to be self-contained and needs to be fixed if there's will to go anywhere with this. Letting people just spam ui with all that crap all the time via PR ain't really viable either, all that should be controllable by plugin to begin with.

It seems like an fairly easy stuff to implement from bird view, but am not all that familiar with koreader ui to tell for sure. I was certainly flabbergasted by [stuff like this](https://github.com/koreader/koreader/pull/6602/files#diff-5c2c491f25a859558eefa5a7ae260005R44) being essentially mandatory for menus, as the code for sorting_hint is broken in a place that's somewhat mysterious in terms of conveying what it actually does in legible manner. Adding gestures is perhaps similarly awkward.

>platform limitations (at least Android): there's no way to install an user plugin in android on demand. 

>zip files etc

Implementation detail. Indeed user plugins would need to live in separate folder anyway to have an easy distinguisher. That said, I'd consider online auto-update out of scope of this and just fetch directories from a list on build would suffice for now. The main point is removing red tape, not becoming an app store :)

**Comment by ezdiy** [comment] 2020-10-08 16:51
> translations

That sounds pretty awkward to tackle indeed. Either

1) point weblate to all the user repos we see, as we *can* know those upfront. Then spam all those translations bundled, same as the user plugin code is. this gets significantly more complex with the "app store" scenario, but that's a dragon waiting for its own knight in shining armor overall.
2) Just give up on translations koreader-wide TL for those. This fairly standard situations with systems that allow low-effort plugins. If such a plugin really wants to, they can TL internally by bringing in their own .po or even doing it ad-hoc. Not many would feel compelled to though, autodiscovery in weblate would be still desirable.

**Comment by Frenzie** [comment] 2020-10-08 17:55
> I was certainly flabbergasted by stuff like this being essentially mandatory for menus

Stuff like what, exactly? If you're talking about the menu order files, that's an absolute killer feature, very very very much on purpose. ;-) 

> as the code for sorting_hint is broken

Bug report please. ^_^

> point weblate to all the user repos we see somehow (is that doable?)

Nope, it has to be part of our org here. But also, there are certain standards to be met before you merge a string so as not to bother translators with unnecessary changes because of low quality strings, etc. So hard veto on anything like that regardless because that's wholly incompatible with a `contrib` folder where standards aren't met.

**Comment by poire-z** [comment] 2020-10-08 19:42
No real opinion, except an egoistic one: the less I have to bother, the happiest I will be.

Not knowing about what may use our code and be affected by the changes I may make, is fine.
I know about one: KOHighlights, and I have the reflex of thinking about it when changes in highlights or xpointers may affect it. It's a little burden but I'm fine with this one.

The more plugins out there that I _may_ get to know about, the more I'll be inclined to be nice and check them if my changes might break them. But I prefer not knowing and not feel guilty or have to slow down to get feedback.
My playground is KOReader core and current plugins - it's large enough.

As for @NiLuJe original post, there are 2 different things:
1) @NiLuJe nickel db sync, which is unnaffecting to our code (until we change History and metadata formats :), and I know will be kept updated and working
(But as it needs KoboStuff, any value being it standalone in a contrib/ repo on our side ? why not rewrite it in Lua and have it part of platform/kobo/ ?)
2) plugins like the recent ones - and I think we're thinking too much about them.

He has previously proposed a plugin, that I considered too specific and a bit too alien code-wise. He got that somehow ok, didn't insist. Well, kept as a private plugin: no issue, we don't override anything, user private plugins work well.
Lately, more plugins were proposed mostly because of the need to plug into dispatcher to get gestures. Still feeling too user specific, hard time politely rejecting them... (It's hard, but it takes a lot of time from us to review them and get them up to standards.)
But if a generic way to plug into dispatcher had been available, we might not have heard about them - and we'd all have been fine. So, I think we should just work on that :)

We could just keep a list of links to koplugins github pages, to advertize them a bit. But I don't think we have to get more concerned about them.

**Comment by yparitcher** [comment] 2020-10-08 20:14
I recently made a plugin for myself [here](https://github.com/yparitcher/chitas.koplugin) and just gitignored its folder and it works fine.

A `contrib` folder would be nice but plugins from there should not be required/loaded by default so they shouldn't be able to mess up a default install. ie. they should be more like use and maintain at your own risk.

as I did most of dispatcher, I plan on working (hopefully next week) on a way for other code (via a callback) to add items to it. I have an idea in mind, but have 2 difficulties: the caller would probably have to be loaded before `dispatcher` is initialized (profiles and gestures would have to be loaded last), also we have to deal with deleting/processing items that may no longer be valid (you add a gesture from a plugin then disable the plugin. What to do now?) as the items that are added at runtime only exist in the master table until the next restart of dispatcher.

**Comment by ezdiy** [comment] 2020-10-08 20:15
@Frenzie It's just one of those "things are just slightly wrong, why bother" bugs one is meh around but here you go - #6770 It isn't the menu code that is broken, just its use by plugin is. sorting_hint belongs to menuitem entry, not _meta, so existing plugins doing it wrong impacts devout copy pasters like me :)

**Comment by poire-z** [comment] 2020-10-08 20:29
> the caller would probably have to be loaded before dispatcher is initialized (profiles and gestures would have to be loaded last)

Don't know the details, but this sounds a bit hard, plugins being loaded last.
Can't these callback just update the data structures build at init ?
Or just have Dispatcher have a :reinit() that you would call when needed to start rebuilding all from scratch ?

> also we have to deal with deleting/processing items that may no longer be valid (you add a gesture from a plugin then disable the plugin. What to do now?) as the items that are added at runtime only exist in the master table until the next restart of dispatcher.

Just don't care about that case ? It will be shown in the list of action, it might emit some even that nothing will catch any more. No harm done :) 
(Or have this pluggable things required to have a is_alive() callback that should check/report of their current availability.)

**Comment by ezdiy** [comment] 2020-10-08 20:29
@yparitcher Glad to see someone giving it a try.

> add a gesture from a plugin then disable the plugin. What to do now?

Register gesturerange, fires an event if detected. No event listeners? Silently ignored. That said, plugins *should* nuke their ges_events/gesturerange on unload, the event pass is necessary for decoupling plugins from gestures - hardcoded as opposed to configurable gestures in particular.

This will need ges_events/grange refactor no matter how much you want to avoid it.

**Comment by yparitcher** [comment] 2020-10-08 20:41
> Don't know the details, but this sounds a bit hard, plugins being loaded last.
> Can't these callback just update the data structures build at init ?
> Or just have Dispatcher have a :reinit() that you would call when needed to start rebuilding all from scratch ?

The menus for gestures/proflies would also have to be rebuilt.

> Just don't care about that case ? It will be shown in the list of action, it might emit some even that nothing will catch any more. No harm done :)
> (Or have this pluggable things required to have a is_alive() callback that should check/report of their current availability.)


> Register gesturerange, fires an event if detected. No event listeners? Silently ignored. That said, plugins _should_ nuke their ges_events/gesturerange on unload, the event pass is necessary for decoupling plugins from gestures - hardcoded as opposed to configurable gestures in particular.

The problem is not with the event (it will be ignored) but with the menu. The gestures menu for example might show that there is a action associated with this gesture (none will not be checked) yet there will be no checked items as the item we stored is no longer a valid item. We might make this easier by putting them in a custom section that will show when a unrecognized item is in it.

**Comment by ezdiy** [comment] 2020-10-08 21:02
@yparitcher 
> The gestures menu for example might show that there is a action associated with this gesture (none will not be checked) yet there will be no checked items as the item we stored is no longer a valid item. 

If you want plugins just programming gesture manager -> action mapping it would go something

1. plugin registers action in Dispatcher. Dispatcher is a horrible horrible thing that needs to be redone to walk existing plugin widgets to seek out available actions on there for this to work at all.
2. plugin tells gesture.koplugin to get gesture->action dispatch for some default mapping
3. user may come in wire different gesture to different action as they deem fit
4. gesture.koplugin must be told by dispatcher whenever action becomes unavailable at any given time (ie plugin disappears, but may also withdraw it)

Ideally, gesture definitions would be entirely separate entities, but still user specifiable thing so a plugin my bring it along for its default, but it must be possible to map this gesture to different action, or map some other action to plugins action.

That is `hello.koplugin` acommpanied by `hello.ges.lua`. The latter is executed automatically to inject new gesture definitions "invented" by that plugin, perhaps (but anyone can use). Those would be loaded as *.ges.lua early in gesture recognition stuff, this decoupling simplifying stuff a little.

**Comment by poire-z** [comment] 2020-10-08 21:21
> If you want plugins just programming gesture manager -> action mapping it would go something
> [..]
> That is hello.koplugin acommpanied by hello.ges.lua (gesrange + heuristic if needed). The latter is executed automatically to inject new gesture definitions "invented" by that plugin

I don't think we want anything like that :)
Plugins provide available actions. They don't have to invent gestures, enough fantasy already.
Users invent gestures (or use our defaults).
Plugin registers to dispatcher.
Dispatcher makes actions available to gestures.koplugin, which makes them available in the menu so the user can associate them (even multiple ones) to a gesture of his choice.

**Comment by NiLuJe** [comment] 2020-10-08 21:23
>        (But as it needs KoboStuff, any value being it standalone in a contrib/ repo on our side ? why not rewrite it in Lua and have it part of platform/kobo/ ?)
>

That's mainly because I knew I could write it n Python without too much thinking, while I wasn't so sure of that in Lua ;p.

----

@ezdiy: As some additional context, @yparitcher wrote Dispatcher ;p.

**Comment by ezdiy** [comment] 2020-10-08 21:42
@poire-z 

> Plugins provide available actions. They don't have to invent gestures, enough fantasy already.

There are 2 places plugin wants to reach outside of scope - parametrized gesture, and dispatcher. The latter would suffice for vast majority of uses seen so far, but the former ain't all that out there - I could see a plugin that paints a custom widget longing for one.

**Comment by yparitcher** [comment] 2020-10-08 22:18
@ezdiy 

Let me explain in short the reason for dispatcher :)

originally there was gestures which was limited to one action (event) per gesture, and was not easily extensible. It was very confusing to add a new action as an option.

Dispatcher was made to abstract all the action (event) code. This acts as a module other code can call to access all actions available. while doing this it was fixed up to allow multiple actions per invocation and be easier to add new actions (but not yet at runtime).

The big gain is that this allows any code to access all actions for free. the led to the profiles plugin, to set a bunch of setting on one menu press, but can also be used in the future, for example if someone wanted a plugin to give the user a choice of events on suspend/resume.

Therefore any plugins will **only** have to be integrated with Dispatcher, and then both gestures and profiles will have them available. Currently Dispatcher assumes all actions are known at startup, but this is what we are trying to change.

The UI (menus) in gesture are actually drawn by dispatcher and are the same as in profiles leading to great code reuse.

and as @poire-z said the plugin and dispatcher should have no need to know what gesture is attached to the action. The plugin should not define a default. they just make it available and the user does the rest as he wishes

**Comment by Galunid** [comment] 2020-10-09 13:16
I think what @ezdiy said in https://github.com/koreader/koreader/issues/6768#issuecomment-705658513 makes the most sense.
> Perhaps go even a lil bit riskey, and just parse it from "Plugin Registry" wiki page - making the stuff completely unattended

This keeps "user plugins", user plugins i.e. there is no need for review, code may be wonky/not working, as long as users are aware, it's all good, we shouldn't really care. In case of "cooler"/"more popular" plugins, we offer merging them. I feel translation shouldn't be an issue here, since it'd be a lot of wasted effort to translate plugins nobody uses. If we "adopt" the plugin it gets translation.

Since @yparitcher plans to add callbacks to dispatcher, gestures shouldn't be an issue

We can of course provide some basic checks whether plugin is malicious, i.e. check for `os.execute`, `loadfile`, `loadstring` and "few" other things, to prevent the obviously dangerous stuff and approve those manually if need be. Of course that wouldn't guarantee the plugin is safe. It's up to the user whether they do trust the plugin provider.

I feel it's golden mean, between users not sharing plugins and getting a lot of pull requests to review.

**Comment by jperon** [comment] 2020-11-05 16:29
#6849 tries to address this:

> * platform limitations (at least **Android**): there's no way to install an user plugin in android on demand. Creating a new folder in internal files dir will crash the Java VM with err=13.  A good workaround is keeping user plugins in dataDir and add that to path and cpath.

The setting `extra_plugin_paths` was already present, I just had to add a menu for it and a default extra path in case default path wasn't writable.

**Comment by pazos** [comment] 2020-11-08 12:10
This issue is pretty much fixed :tada: 

Maybe we can update the sample/hello plugin to showcase the new hooks. The other thing that can be showcased is a self translated plugin, using a custom gettext object

**Comment by yparitcher** [comment] 2020-11-08 16:24
> This issue is pretty much fixed tada
> 
> Maybe we can update the sample/hello plugin to showcase the new hooks. The other thing that can be showcased is a self translated plugin, using a custom gettext object

The dispatcher hook is already in the doc / sample plugin.

What wasn't decided was how we should track user plugins, should we just have a list on the wiki and expect users to download them or maybe we should automagicly make them available.

**Comment by Hzj-jie** [comment] 2021-03-18 22:05
If a user plugin requires some core logic change, will it be rejected directly or handled case-by-case? I'd say in most of the cases user plugins are less commonly used, so one can easily say "no this is not a common use case we'd like to support". But koreader was never built with a set of public apis for plugins to integrate. Though lua is a very loosen language, too much hacks, like accessing "internal" states of an instance, is still a bad thing.

**Comment by Frenzie** [comment] 2021-03-18 22:16
It would likely be rejected if it was just a core logic hack for the benefit of the plugin, but that's just a long way of saying I can't imagine how it could be anything other than case by case.

Of course it's smarter to gauge for some feedback before investing a lot of time. ^_^

**Comment by poire-z** [comment] 2021-03-18 22:20
Depends on how generic the needed API feels, and how clean it can be implemented. See #6851 which added stuff so plugin can add their buttons to the highlight/selection button dialog.

**Comment by poire-z** [comment] 2021-08-15 00:57
I think we're done with this with https://github.com/koreader/contrib

**Closed by poire-z** 2021-08-15 00:57 UTC
Labels: enhancement
