### ISSUE TITLE
Boox Note can't be touch the screen

### ISSUE THREAD

**Issue by shuqian** [koreader/koreader#3738] opened 2018-03-11 11:57 UTC
* KOReader version:koreader-nightly-20180212 - koreader-android-arm-linux-androideabi-v2015.11-1523-g78284e1.apk
* Device:Boox Note (Android 6.0)

#### Issue
Boox Note can't be touch the screen，
except to change the A2 mode

![EZQiX.jpg](https://s1.ax2x.com/2018/03/11/EZQiX.jpg)

**Comment by Frenzie** [comment] 2018-03-11 12:05
Duplicate of #3567.

Imo whatever it is is a Boox issue but suggestions to work around it welcome. ;-)

**Closed by Frenzie** 2018-03-11 12:05 UTC
