### ISSUE TITLE
koreader on kobo aura one doesn't support arabic yet :( 

### ISSUE THREAD

**Issue by hgrain86** [koreader/koreader#5048] opened 2019-05-29 05:49 UTC
* KOReader version:
kobo aura one

koreader on kobo aura one doesn't support arabic yet :( 

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Thra11** [comment] 2019-05-29 11:46
Just to clarify, does this refer to:
a. Translating the UI so that the menus and dialogs can be shown in arabic, or
b. Rendering arabic documents correctly?
Or both?

**Comment by Frenzie** [comment] 2019-05-29 15:20
Duplicate of https://github.com/koreader/koreader/issues/1426.

**Comment by hgrain86** [comment] 2019-05-31 07:55
[image: photo_2019-05-31_06-02-22.jpg]

‫في الجمعة، 31 مايو 2019 في 5:58 ص تمت كتابة ما يلي بواسطة المفكر الصغير <‪
hgrain86@gmail.com‬‏>:‬

**Comment by hgrain86** [comment] 2019-05-31 08:33
both
when you open epub book in kobo aura one texts appears broken characters :(
thank u so much

‫في الأربعاء، 29 مايو 2019 في 5:21 م تمت كتابة ما يلي بواسطة ‪Frans de
Jonge‬‏ <‪notifications@github.com‬‏>:‬

**Comment by pazos** [comment] 2019-06-08 16:19
Closing as duplicate

**Closed by pazos** 2019-06-08 16:19 UTC
Labels: duplicate
