### ISSUE TITLE
multiple issues in the JSON exported highlights/notes

### ISSUE THREAD

**Issue by Edo78** [koreader/koreader#8633] opened 2022-01-08 20:50 UTC
* KOReader version: 2021.12.1
* Device: Kobo Clara HD

#### Issue

1. exporting the notes of more than 1 book create an invalid JSON because, instead of creating an array of objects, the exporter simply append multiple objects
2. the `author` is often wrong while in the metadata is right, it seems that it try to parse the filename failing (eg. the Lovecraft epub `Tutti i romanzi e i racconti (eNewton Classici) (Italian Edition) - Howard Phillips Lovecraft.epub` in the JSON has `"author": "eNewton Classici) (Italian Edition",`
3. exporting multiple time without removing the JSON file create a big mess because the everything is appended to the old file

#### Steps to reproduce
Just exporting notes from multiple books in JSON format should be enough to reproduce points 1 & 3 while looking at the `getTitle` function in `plugins/exporter.koplugin/clip.lua` should be enough to prove that the author is parsed in a wrong way.

**Comment by Edo78** [comment] 2022-01-12 16:05
I'm interested but I never wrote a single line of lua in mi life (lol, I just used a lot of L )

**Comment by pazos** [comment] 2022-01-31 15:33
> It should be trivial to fix for interested people. Just make an empty table and, for each book, insert highlights in a subtable. Finally use rapidjson to dump the whole table to a file

Now that I read the code it is a bit harder than I thought.

And TBH all the code is glued together like a spaghetti monster :/

Makes sense to refactor most of the code, so any exporter implements `exportOne` and `exportAll` (name as you want) functions.

I will probably look at it in the near future for local formats (json, html & text) and leave joplin and readwise mostly untouched.

**Comment by Edo78** [comment] 2022-01-31 17:12
Right now I worked around the problem and I created a [plugin](https://github.com/Edo78/obsidian-koreader-sync) per Obsidian to retrieve the data I need but it will be nice to see this issue solved.

**Comment by pazos** [comment] 2022-04-27 12:13
Your reported issues are going to be fixed in #8944.

The 2nd one is already a duplicate of https://github.com/koreader/koreader/issues/6974 and is going to be tracked there.

**Closed** 2022-05-06 20:44 UTC
Labels: bug, Plugin, help-wanted
