### ISSUE TITLE
Reflow isn´t woring at kindle ppw2

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#5327] opened 2019-09-05 22:22 UTC
* KOReader version: v2019.08-94-gcb2a3d9_2019-09-04
* Device: ppw2

Reflow isn´t working with any pdf. When I use reflow, koreader crashs and goes to the kindle SO.

                launching...

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 09/05/19-13:49:35
 [*] Version: v2019.08-94-gcb2a3d9_2019-09-04

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
SDL not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: SDL
ffi.load: blitbuffer
FB: computed size: 6684672
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 1088
FB: xres         : 1072
FB: xres_virtual : 1088
FB: yres         : 1448
FB: yres_virtual : 6144
FB: bpp          : 8
09/05/19-13:49:35 INFO  initializing for device KindlePaperWhite3
09/05/19-13:49:35 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[ko-input] Forked off fake event generator(pid:21542).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
09/05/19-13:49:36 INFO  opening file /mnt/us/documents/Direito TributÃ¡rio - Ricardo Alexandre - 2018.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
09/05/19-13:49:37 INFO  Loading plugins from directory: plugins
09/05/19-13:49:37 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
09/05/19-13:49:37 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
09/05/19-13:49:37 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
09/05/19-13:49:37 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
09/05/19-13:49:37 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
09/05/19-13:49:37 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
09/05/19-13:49:37 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
09/05/19-13:49:37 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
09/05/19-13:49:37 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
09/05/19-13:49:37 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
09/05/19-13:49:37 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
09/05/19-13:49:37 INFO  setting zoom mode to contentwidth
source page (0,0) - (595,842)
source page bgcolor 192
source page (0,0) - (469,761)
source page bgcolor 192
source page (0,0) - (474,765)
source page bgcolor 192
source page (0,0) - (471,762)
source page bgcolor 192
./luajit: frontend/document/document.lua:232: attempt to index local 'bbox' (a nil value)
stack traceback:
	frontend/document/document.lua:232: in function 'getPageArea'
	frontend/apps/reader/modules/readerview.lua:570: in function 'recalculate'
	frontend/apps/reader/modules/readerview.lua:781: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/apps/reader/modules/readerpaging.lua:961: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/configdialog.lua:879: in function 'onConfigEvents'
	frontend/ui/widget/configdialog.lua:921: in function 'action'
	frontend/ui/uimanager.lua:746: in function '_checkTasks'
	frontend/ui/uimanager.lua:1029: in function 'handleInput'
	frontend/ui/uimanager.lua:1115: in function 'run'
	./reader.lua:260: in main chunk
	[C]: at 0x00013ef9
lipc-wait-event exited normally with status: 0

**Comment by NiLuJe** [comment] 2019-09-05 22:23
Quite possibly a duplicate of #5323 ;).

On my end, I'm not *sure* it's 100% reproducible, FWIW.

**Comment by Frenzie** [comment] 2019-09-06 06:08
> fairly easily

If you say so. :-P

**Comment by Frenzie** [comment] 2019-09-07 14:56
@Eduardomb22 Since you're able to reproduce this issue reliably, could you please see if #5337 helps?

**Closed** 2019-09-07 15:15 UTC

**Comment by Eduardomb22** [comment] 2019-09-07 18:57
@Frenzie Thanks for the fix, it is working fine again =)

**Comment by Frenzie** [comment] 2019-09-07 19:32
@Eduardomb22 Thanks for confirming. I'll tag 2019.09.1.
