### ISSUE TITLE
PDF rearrangement on Android 13

### ISSUE THREAD

**Issue by Yi-Z0** [koreader/koreader#10587] opened 2023-06-16 09:19 UTC
* KOReader version: 2023.05.01 
* Device: Nubia Z50

#### Issue
Use PDF rearrangement feature  will trigger app crash

#### Steps to reproduce
Open a PDF document in image format (my document has 500MB), enable PDF rearrangement, and flip to the next page to obtain a crash error log

##### `crash.log` (if applicable)
--------- beginning of system
06-16 17:10:40.536 D/ActivityThread(21138): ***** performPauseActivity ActivityRecord{2e7c1a2 token=android.os.BinderProxy@ab8c16d {org.koreader.launcher/org.koreader.launcher.CrashReportActivity}} finished= false paused= false mFinished= false
--------- beginning of kernel
06-16 17:12:16.030 W/audit   (23327): audit_lost=22229 audit_rate_limit=5 audit_backlog_limit=64

[crash.log](https://github.com/koreader/koreader/files/11768512/crash.log)

**Comment by yukinotech** [comment] 2023-06-26 12:42
same problem when using PDF rearrangement

**Comment by NiLuJe** [comment] 2023-06-26 12:47
Quite likely a duplicate of #10150, #10501 & #10533, which I suspect will all (or most of it) magically go away with Clang...

**Closed** 2023-10-09 22:34 UTC
Labels: Android
