### ISSUE TITLE
Dropbox has abandoned Longterm API

### ISSUE THREAD

**Issue by ray-y17** [koreader/koreader#9096] opened 2022-05-12 18:07 UTC
Dear Developer:

Recently I tried to configure the Dropbox sync function of KOreader on my kindle. But I noticed that Dropbox has abandoned the long-term API and can only generate short-term API, which means one generated api would be expired only 4 hrs later. So it’s really hard to re-configure them frequently to keep it works. 

THX.

**Comment by Frenzie** [comment] 2022-05-12 18:11
Duplicate of https://github.com/koreader/koreader/issues/8571 If anybody wishes to pick it up, please do.

**Closed by Frenzie** 2022-05-12 18:11 UTC
Labels: duplicate
