### ISSUE TITLE
Changing style to "HTML Standard rendering" for epub hangs app

### ISSUE THREAD

**Issue by simon-20** [koreader/koreader#12472] opened 2024-09-06 07:25 UTC
* KOReader version: 2024.07
* Device: Samsung Note10+, Android 

#### Issue
When I change style to "HTML Standard rendering" in any epub, a series of icons appears in the top left corner, but when it reaches an icon with a small sync-like icon, it hangs.

#### Steps to reproduce
Open an epub (I've tried 5 different ones).
Top menu, second icon in, Style > HTML
Wait a few seconds.
App hangs

An example of this should be the second to last run on the attached log file below, but I couldn't figure out where sessions started and stopped, so didn't want to try trimming the log file down too much.

##### `crash.log` (if applicable)

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

[crash.log](https://github.com/user-attachments/files/16904293/crash.log)

**Comment by benoit-pierre** [comment] 2024-09-06 08:01
Partial rendering has been known to cause issues, can you reproduce after disabling it?

**Comment by poire-z** [comment] 2024-09-06 08:11
> Partial rendering has been known to cause issues

You mean on Android ? Or in general ?
If "in general", this is not known to me :) and should be fixed.
If Android specific, well, phew :)

**Comment by benoit-pierre** [comment] 2024-09-06 11:12
> > Partial rendering has been known to cause issues
> 
> You mean on Android ? Or in general ? If "in general", this is not known to me :) and should be fixed. If Android specific, well, phew :)

On Android, yes, although there's at least one instance of it causing issues on macOS too, IIRC.

**Comment by simon-20** [comment] 2024-09-08 10:41
> Partial rendering has been known to cause issues, can you reproduce after disabling it?
> 

Could you point me in the direction of where this setting is? 

I found a 'render mode' setting in one of the menus down at the bottom, it has four options including 'legacy' and 'web'--is one of these partial?

**Comment by benoit-pierre** [comment] 2024-09-08 10:52
With a document opened, 3rd top-menu from the left, "Document" → "Enable partial rendering".

**Comment by NiLuJe** [comment] 2024-09-08 18:09
For future reference: `[Hamburger]` > `Help` has a `Menu search` entry that will help you find (nearly) anything that's hidden away in the top menu ;).

**Comment by benoit-pierre** [comment] 2024-09-08 18:17
Ah! I was thinking that a GZDoom like "Option Search" feature would be useful. :P

It would be more useful if it was more easily discoverable, maybe a loop icon at the bottom of the menus? I never now which menu is the right one. Add the fact that some entries are only available in some contexts, and I'm always hunting for a particular entry.

**Comment by pazos** [comment] 2024-09-10 15:52
Not even on the entire android platform. It is always reported on samsung roms.

Duplicate of https://github.com/koreader/koreader/issues/12099

**Closed** 2024-09-15 21:46 UTC
Labels: bug, Android, duplicate, firmware

**Comment by simon-20** [comment] 2024-10-03 05:41
> With a document opened, 3rd top-menu from the left, "Document" → "Enable partial rendering".

Thank you. 

I realise you've closed this issue as a duplicate, which is fine.

But when it comes to this workaround, the problem is that this menu item doesn't appear for non-epubs. So I can't disable it without opening an epub, but as soon as I open an epub, the app hangs.

**Comment by Frenzie** [comment] 2024-10-03 06:10
How do you mean precisely? One of the previously opened epubs?

**Comment by hius07** [comment] 2024-10-03 07:50
It can be done manually: in the file koreader/settings.reader.lua set the key `cre_partial_rerendering` to `false`.

**Comment by simon-20** [comment] 2024-10-03 08:33
Great, thanks.
