### ISSUE TITLE
Backward search in book not working

### ISSUE THREAD

**Issue by sladflob** [koreader/koreader#6672] opened 2020-09-18 04:12 UTC
Using Fulltext Search, using either of the backward search buttons does nothing. Forward searching works as usual. This also happens if I enter the search via a long press while reading.

**Comment by poire-z** [comment] 2020-09-18 04:59
(Why not include your KOReader version as it was proposed to you in the issue template? So I wouldn't have to ask...) What KOReader version ?

Can't reproduce, works for me with current master and from 2 days ago.
You get that with all books? Or is it book specific ?

**Comment by sladflob** [comment] 2020-09-18 05:08
Sorry, I clicked on New Issue and didn't get the template and forgot to mention version. I just updated to the latest release, 2009.09. I tried it on a couple of books and had the same result, then I realised there were no earlier occurrences of the string I was searching for in the 2nd book. Checking more carefully it looks like it's just happening with one book, an ePub. It's a Project Gutenberg book so I assume it's ok to attach it to this issue.

**Comment by sladflob** [comment] 2020-09-18 05:09
[Raymond Chandler - The Big Sleep.zip](https://github.com/koreader/koreader/files/5243519/Raymond.Chandler.-.The.Big.Sleep.zip)

**Comment by poire-z** [comment] 2020-09-18 05:27
OK, thanks, I can reproduce it with this book.
Seems to happen when the book starts with a `<BR/>` (and also forward search >> fails when it ends with a `<BR/>`... )

```html
<body>
  <div>
    <br /> <!-- remove this and backward search works -->
    <b>* A Project Gutenberg Canada Ebook *</b><br />
[...]
    [End of <i>The Big Sleep</i>, by Raymond Chandler]
    <br /> <!-- add this and forward search fails -->
  </div>
</body>
```

**Comment by poire-z** [comment] 2020-09-18 07:18
Should be fixed by https://github.com/koreader/crengine/pull/379/commits/497c8a7136429c94bfbac20eb275394290c6e96c.

**Closed** 2020-09-18 17:34 UTC
