### ISSUE TITLE
many actions trigger violent freezes apparently intended to enable wifi (android)

### ISSUE THREAD

**Issue by elandorr** [koreader/koreader#10779] opened 2023-08-03 13:16 UTC
* KOReader version: 2023.06.1
* Device: android 10

#### Issue

Many actions apparently would want internet access, which I do not allow. I don't want any wifi near me, ever, period. Additionally, I do not want any unasked for network requests, ever, either.

For example, the document icon which I assume opens the file browser instantly, normally, causes a full device freeze for ~30 seconds, after which it opens the android setting to turn on wifi. If koreader hasn't crashed, it asks 'do you want to turn on wifi?'. No, I really don't.

#### Steps to reproduce

Have an android with disabled wifi, don't give koreader network permission, click around until it happens.

##### `crash.log` (if applicable)
No crash, if you let it freeze in peace and don't tap stuff (these taps all sum up in a cacophony of a million of em at once, after).

Aside, thank you for making this, it seems fantastic! The (forced due to e-ink origin) style of oldschool systems without flashy bullshit is very appealing. So far, every actually useful feature I could think of, you already implemented. I'll even give it a shot on a laptop. This wifi bug is hugely annoying on android, but I'm sure that's trivial to fix.

**Comment by Frenzie** [comment] 2023-08-03 14:54
That's an issue specifically and only in 2023.06.1, duplicate of #10678.

**Closed by Frenzie** 2023-08-03 14:54 UTC
Labels: duplicate

**Comment by Frenzie** [comment] 2023-08-03 14:58
PS That likely also applies to most of the comment in https://github.com/koreader/koreader/issues/10736#issuecomment-1663995278 because it doesn't randomly do that, only when you ask for it. Normally.

**Comment by NiLuJe** [comment] 2023-08-03 15:22
Yeah, that ties into a much older discussions about whether or not plugins should be enabled by default ;).

I think the consensus was keep them on by default, but try very very hard to steer users to the Plugin management screen ASAP via both the Quick Start Guide and the User Guide.
