### ISSUE TITLE
Annotation by stylus

### ISSUE THREAD

**Issue by dil070** [koreader/koreader#11560] opened 2024-03-17 07:55 UTC
Koreader is vital to kindle 
As for kindle scribe，annotation becomes split personality.You can annotate PDF trasferred to kindle scribe by Send To Kindle feature,but PDF can't be annotated if the file trasferred via USB cable.And I consulted the Amanzon costumer service if it is possible annotate on PDF transferred via USB,the answer is KEEP WAITING.

What makes scribe a real Scribe is annotaiton.But under some circumstances Send To kindle beccomes really annoying since it could fail in more ways than We think.

So could there be annotation feature in koreader,so we could use kindle scribe pen to annotate on pdf and many other formats.
By the way kindle scribe doesn't support to annotate epub mobi azw etc even if transferred to kindle by Send to kindle feature.So we need koreader to scribe on file by using stylus,even if it supports to annotate PDF only.

**Comment by dil070** [comment] 2024-03-17 09:28
If there is annotation feature in koreader I will Donate Regularly.Thanks a lot to the team

**Comment by pazos** [comment] 2024-03-17 19:33
Duplicate of #2633

**Closed by pazos** 2024-03-17 19:33 UTC
Labels: enhancement
