### ISSUE TITLE
Default Zoom Mode

### ISSUE THREAD

**Issue by NO-ob** [koreader/koreader#6367] opened 2020-07-09 20:49 UTC
* KOReader version: koreader-kindle-legacy-v2020.05.zip
* Device: kindle 4

#### Issue
Not sure how to set the default zoom mode as Zoom to fit content when reading a cbz file. I read that holding select on the menu item is supposed to ask if you want to set as default but holding the select button down does nothing. I didn't see the option to set this in the defaults.lua either

**Comment by NiLuJe** [comment] 2020-07-10 05:15
Hold callbacks are *probably* not implemented on Touch-less device, would be my first guess.

**Comment by Frenzie** [comment] 2020-07-10 06:14
Duplicate of https://github.com/koreader/koreader/issues/3818, also related https://github.com/koreader/koreader/issues/4029

**Comment by NO-ob** [comment] 2020-07-10 20:39
is it possible to bind the open keyboard button to set default as I dont think it has any function in koreader

**Comment by Frenzie** [comment] 2020-07-10 21:54
I'm not sure what open is? The list of keys seems to look like this:

https://github.com/koreader/koreader/blob/a376a52c3a052bd3b367c288cca6b81248f3870a/frontend/device/kindle/event_map_kindle4.lua#L6-L18

**Comment by yparitcher** [comment] 2020-07-12 02:23
open keyboard key 
![k4](https://user-images.githubusercontent.com/38916402/87237396-c20ea480-c3c3-11ea-9db2-38bfeab5b570.jpg)

is probably ` [29] = "ScreenKB",`

**Closed** 2023-07-06 19:37 UTC
Labels: enhancement, duplicate
