### ISSUE TITLE
Bottom of Screen Cut Off

### ISSUE THREAD

**Issue by SpookedByRoaches** [koreader/koreader#10022] opened 2023-01-12 06:11 UTC
* KOReader version:
* Device:

#### Issue
Bottom of screen is cutoff where sometimes the last line is also cutoff and the status bar never appears. I can only see the status bar when I rotate horizontally.

Vertically the screen is like this
![vertical](https://user-images.githubusercontent.com/38513225/211990335-d6d77c78-8067-40eb-99f2-8ea30f580fd4.png)

Horizontally you can see the status bar
![horizontal](https://user-images.githubusercontent.com/38513225/211990501-ba36ca6c-9c41-41d6-b269-428bf8ab2814.png)

#### Steps to reproduce
No steps since this happens throughout usage even in the file explorer.

##### `crash.log` (if applicable)

No crashes, but the best I can do is `ADB logcat | grep koreader > koreader.log` then opening the app
[koreader.log](https://github.com/koreader/koreader/files/10398679/koreader.log)

**Comment by NiLuJe** [comment] 2023-01-12 07:47
Android 13?

**Comment by SpookedByRoaches** [comment] 2023-01-12 12:10
> Android 13?

Oh yeah I forgot the device info
Pixel 6 Pro, 
Android 13, 
build number TQ1A.221205.01

**Comment by NiLuJe** [comment] 2023-01-12 18:05
Duplicate of #9446

**Closed by NiLuJe** 2023-01-12 18:05 UTC
