### ISSUE TITLE
OPDS-PS progress not syncing correctly (Kavita)

### ISSUE THREAD

**Issue by Fivefold** [koreader/koreader#9731] opened 2022-11-02 15:06 UTC
* KOReader version: 2022.10
* Device: Kobo Aura ONE
* Kavita version: 0.5.6.0 (in case it's relevant)

#### Issue

While page streaming works now thanks to #9650 and @bigdale123, I can't seem to be able to sync progress correctly. 

Everytime I open a book via OPDS-PS in koreader, it starts at the beginning. Page syncing to the kavita server actually works, so e.g. I go to page 5 on koreader, kavita saves progress at page 5 and I could continue reading on kavita itself via browser. But if I open the book again later on koreader it will start at page 1 and immediately sync that progress to kavita.

#### Steps to reproduce

This is the way I access the books on koreader:

1. Open menu by swiping from the upper border.
2. Change to search tab (magnifier symbol)
3. Choose 'OPDS catalog'
4. Choose my configured Kavita instance
5. Navigate to any book and select it
6. Choose 'Page stream' button

Is there a different, 'correct' way of accessing books via OPDS-PS?

**Comment by bigdale123** [comment] 2022-11-02 15:09
Technically yes, there is a way to pull progress from Kavita, however to setup a "progress puller", you'd need to write a different handler for each possible server (Kavita, komga, ubooquiti, etc.) Because they server progress on different endpoints. There is another feature I've added, called "Stream From Page", that should be included in the next release? I'll link the PR when I get back on my PC.

**Comment by Fivefold** [comment] 2022-11-02 16:48
This should be the PR: #9681. 

I propose keeping this open as a reference for the mentioned "progress puller" since the PR is only a workaround in that you still have to know the page to fetch to sync progress between devices.

**Comment by bigdale123** [comment] 2022-11-02 17:43
Yeah, stream from page was intended to be a hotfix, midterms were starting to ramp up but I wanted page streaming to be less of a pain to use. Still useful, but not what I wanted to do originally. My first thought was progress pulling, but after looking into it and seeing that it would probably take a bit of time to get working I decided to write something that does half the job untill I can get time to work on a real solution.

**Comment by NiLuJe** [comment] 2022-11-02 18:18
Ultimately this feels like a job best handled as a dedicated `Document` implementation, so you actually get seamless navigation (because, yeah, deferring to ImageViewer is kind of a kludge ;)).

**Comment by NiLuJe** [comment] 2022-11-02 19:27
Or, perhaps less drastically, a new subclass of `ImageViewer` with navigation supports, that would inherit the backend methods from the OPDS plugins.

**Comment by hius07** [comment] 2022-11-12 06:29
Closed via https://github.com/koreader/koreader/pull/9750.

**Closed by hius07** 2022-11-12 06:29 UTC
Labels: Plugin, OPDS
