### ISSUE TITLE
Chinese letter garbled on android q

### ISSUE THREAD

**Issue by weigeloveu** [koreader/koreader#5447] opened 2019-10-03 02:57 UTC
* KOReader version: v2019.09.3
* Device:
xiaomi 9
koudaiyue
#### Issue
The system of koudaiyue is Android go and xiaomi 9 is Android q. 
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by pazos** [comment] 2019-10-03 11:09
Duplicate of #5381

**Closed by pazos** 2019-10-03 11:09 UTC
Labels: Android, bug, duplicate
