### ISSUE TITLE
Onyx Boox Monte Cristo 3 bightness doesn't work

### ISSUE THREAD

**Issue by MartinezzzLV** [koreader/koreader#9568] opened 2022-09-28 15:32 UTC
* KOReader version: [KOReader 2022.08]
* Device: Onyx Boox Monte Cristo 3

#### Issue 
Android version. Brightness doesn't work. I've tried numerous times to make it work either through programmable taps or gestures, but the only thing that is working is the hardware button. I can change the brightness level only when I switch to 'desktop' and do it manually.

Any ideas on what might be an issue here?

**Comment by pazos** [comment] 2022-09-28 16:46
duplicate of https://github.com/koreader/koreader/issues/8482

**Closed by pazos** 2022-09-28 16:46 UTC
Labels: Android, duplicate
