### ISSUE TITLE
CSS: External style with "!important" does not override inline style

### ISSUE THREAD

**Issue by sts78** [koreader/koreader#1430] opened 2015-02-16 21:10 UTC
I have an ebook here, which has some horrible markup (Robert Merle - Madrapour). The epub has an epub.css (where I automatically append some custom CSS), but also a "style='text-indext:20px' " on every <p>.

One of my custom CSS at the end of each external CSS file is a 
p,div {text-indent:1.5em !important;}
which works wonderfully in a myriad of other books. But this ebook with its inline style denies my attempts to get my custom indentation.

BTW: This is not the only example of an epub, where the !important is ignored. I have another epub (Elisabeth Herrmann - Das Dorf der Mörder), where the font-family and the indentation is ignored. In this epub they are correctly set in the external CSS (<p class="x10a-GS">), but my appended custom CSS should override them:

.x10a-GS {
    color: #000;
    display: block;
    font-family: "Stempel Garamond LT Std", serif;
    font-size: 0.77419em;
    font-style: normal;
    font-variant: normal;
    font-weight: normal;
    line-height: 1.43;
    margin-bottom: 0;
    margin-left: 0;
    margin-right: 0;
    margin-top: 0;
    text-align: justify;
    text-decoration: none;
    text-indent: 11px
    }

[....]

p,div,span
{
    text-align: justify !important;
    font-family: "Lexia DaMa" !important;
    line-height: 1.3em !important;
}
Again: works in dozens of other books, but not here. Koreader shows 11px indentation and the ugly embedded font.

Is this a problem with my custom CSS? With Koreader? Or the CoolReader Engine?

**Comment by Frenzie** [comment] 2015-02-18 12:54
The problem is probably with CoolReader.

**Comment by AndreasTPC** [comment] 2017-06-28 20:53
This is a larger issue than just with inline styles.

I tried overriding <p> to set text-indent to 0, with !important, because I don't like indented first lines of paragraphs, and koreader does not respect the !important and just uses the style specified in the epub file. I checked the css in the epub file and inline styles are not being used, the paragraphs are all just <p class="something">paragraph here</p>, where the something class specifies a text-indent.

As a workaround until it can be fixed properly, maybe switch the order in which the internal and external css is parsed, so the external has the "final say"?

**Comment by Frenzie** [comment] 2018-04-19 20:11
@poire-z Pinging you since you've been playing around with all this stuff. ;-)

**Comment by poire-z** [comment] 2018-04-27 14:52
I'm not really familiar with !important.
Am I right in thinking that if in a css file, we have:
```
div { color: blue !important; }
.introduction { color: red; }
```
when deciding for style of `<div class="introduction">`, it should be blue ?
Would specificity https://www.w3.org/TR/CSS2/cascade.html#specificity change that?

(Let's forget for now about specificity, crengine has a slot for that, but no implementation)

More explicitely:
Are css selectors (let's say: with the same specificity) checked for and applied in the order they are declared in a stylesheet, and in the order of stylesheets inclusion if there are many?
```
div {color: blue !important}
[...]
div {color: red}
```
a `<div>` will be blue?

I haven't yet checked in the code how epub.css and internal stylesheet(s) are applied.

I have a book I want to read with huge stupid left margins, and internal styles like:
```
.dev { margin : 14% 0% 0% 0%; }
.chap .dev { margin : 17% 0% 0% 0%; }
.div_intro .dev { margin : 10% 0% 0% 0%; }
.defnotes { margin : 9% 0% 0% 0%; }
.appen .dev { margin : 25% 0% 0% 0%; }
```
I don't want (me and us) to have to override these explicite classNames (like the OP seems to have done with `.x10a-GS`)
So, if we later have the ability to append snippets to epub.css, would appending any **one of**
```
* {margin: inherit !important;}
* {margin: 0 !important;}
div {margin: inherit !important}
p {margin: 0 !important}
```
make the above stupid internal styles not applied ?

**Comment by Frenzie** [comment] 2018-04-27 15:07
> Would specificity https://www.w3.org/TR/CSS2/cascade.html#specificity change that?

!important is one of those things you normally shouldn't use because only higher specificity !important overrides !important

So yes, it should be blue in your example.

What's more relevant here however is the cascading order: https://www.w3.org/TR/CSS21/cascade.html#cascading-order

To me the per-spec order is just plain wrong, wrong, wrong. It should be:

1. User agent
2. Author
3. User
4. Author !important
5. User !important

But that aside. I think it's because Mozilla didn't do per-site (like you can do in Stylish) back in the day.

**Comment by Frenzie** [comment] 2018-04-27 16:50
That behavior is probably close enough to correct, except that !important should still be overwritten by other !important of the same or higher specificity.

**Comment by KenMaltby** [comment] 2018-04-27 17:37
Hmm,,, Publishers make use of such things in their ebooks so that they can't be over ridden by users, like me.  What would be of more interest to me is to have a way override the publisher's setting with my own.  The cascading idea is normally good for that, but someone had to give the publishers this.

**Comment by poire-z** [comment] 2018-04-27 18:31
That's what I wished we have.
But, to know what to add, we have to look at the publisher stylesheet to see what to override.
Once found, we can either add a "late user stylesheet", or, which should be the same: add these rules to the external styles (epub.css) with `!important` (whether we allow publisher `!important` to override ours is a choice to make, could be an option).
But once you know what to add after you looked at the publisher stylesheet, you may as well remove them in the publisher stylesheet :) That's what I've been doing till now.

What I wish we could do is just to not have to look at the publisher stylesheet inside the epub.
I'd like if we had another menu list with "css snippets", multiple checkboxes, that would generate some rules with !important that would be appended (dynamically) to the content of epub.css and fed to crengine.
I see for my use such snippets as:
- change link colors from gray to black (always on for me)
- avoid page breaks before (needed for some books to avoid blank page at chapter page)
- ignore publisher margins (that's the one I wonder if we can do it)
- ignore publisher line-height
- ignore publisher font-family (different from disable embedded fonts)

I'm sure many users could think of other such snippets.

**Comment by KenMaltby** [comment] 2018-04-28 03:04
Given CPU & Memory limitations of our current mobile devices I can't see a way to have the HTML & Epub documents examined for these and others then selectively disable some, even if the MI/AI could do the job.  Perhaps this could be more something calibre could do, for us.

**Comment by Frenzie** [comment] 2018-04-28 07:15
I doubt there's anything in CSS1 that's very taxing on CPU and memory. :-) Keep in mind IE3 probably already supported everything we're talking about, and that was designed to run (possibly a touch slowly) on something like a 20 MHz 386DX. And if not IE3, IE4 certainly supported it.

I'm not sure off the top of my head if crengine supports the universal selector `*` (CSS2), but that's probably about the most demanding thing you can use that doesn't appear terribly fancy on the face of it.

**Comment by poire-z** [comment] 2018-04-28 18:13
With #166, I managed to keep my links blue (on wikipedia epub that explicitely set them black), and to fix font sizes and margins in 2 books I edited css in in the past, by appending to epub.css:
```css
a { color: blue !important; }
body { margin: 0% 0% 0% 0% !important; font-size : 100% !important; }
```
(Curious that this body margin fixed some `div.text { margin: 14% 0% 0% 0% }`, as margin should not be inherited... )

Haven't yet managed to fix publisher line-height, without making KOReader Line space toggle inneficient, probably because it itself does that by setting line-height style.
Anyway, there's room for testing and finding stuff that helps.

**Comment by cramoisi** [comment] 2018-04-30 10:27
@poire-z rereading #3448 , I asked myself how to !important a non-rule. (like when you delete it form the publisher css). for the hyphen one, I think (-webkit-)hyphen:auto; should do the trick. As you said, in certain case, disabling the rule by forcing another will make the tuning option in KOReader useless

**Comment by poire-z** [comment] 2018-04-30 14:40
> As you said, in certain case, disabling the rule by forcing another will make the tuning option in KOReader useless

Haven't looked at it yet, but it could be these tuning options have crengine uses styles to do that tuning - so, somewhere in crengine, it should also use `!important` (or set the technical flags that are used for that) when applying the style, so it can overrides any of our `!important`.

**Comment by poire-z** [comment] 2018-05-01 12:08
Mhhhh. Please tell me there is a huge typo there, and that there is not such thing in css as `inherited`, and it should be `inherit` !
https://github.com/koreader/crengine/blob/228e8a1cec7678ccf74bed52bf53272c36596e76/crengine/src/lvstsheet.cpp#L305
https://github.com/koreader/crengine/blob/228e8a1cec7678ccf74bed52bf53272c36596e76/crengine/src/lvstsheet.cpp#L544
like it is for all the other properties, eg:
https://github.com/koreader/crengine/blob/228e8a1cec7678ccf74bed52bf53272c36596e76/crengine/src/lvstsheet.cpp#L689-L695

I've been fighting with adding stuff like:
`* { line-height: inherit !important; }`
which I couldn't make work.
But if I use:
`* { line-height: inherited !important; }`
it overrides publisher overhuge line-heights as I want it too.

**Comment by cramoisi** [comment] 2018-05-01 12:16
Yup, `inherit` is the right keyword. Inherited is somehow a typo because often used as a class name.

**Comment by Frenzie** [comment] 2018-05-01 12:53
@poire-z 
The keyword `inherit` indicates that a value should be inherited. So if crengine is checking for the keyword `inherited`… well, there's no such thing. Huge typo indeed. :-)

**Comment by poire-z** [comment] 2018-05-01 14:00
Thanks.
I'll fix it later or tomorrow when i'll get my mind clearer about this inheritance thing.

So, just to be sure everything is right (writting this as much for myself):

This lists the default values for a style, before we go applying stylesheet on it, and before we propagate inherited values from parent's style:
https://github.com/koreader/crengine/blob/228e8a1cec7678ccf74bed52bf53272c36596e76/crengine/include/lvstyles.h#L133-L163

Then, we apply stylesheets (the declaration from the selectors that match).

Then, there is this whole thing that deal with inheritance:
https://github.com/koreader/crengine/blob/228e8a1cec7678ccf74bed52bf53272c36596e76/crengine/src/lvrend.cpp#L2760-L2849
`UPDATE_STYLE_FIELD` simply copies the parent style to current node if the current style is `inherit`
`UPDATE_LEN_FIELD` too, but deals with values of unit `%` (% of value of parent) and `em` (value * font size of parent).
Then, some specifics for font-size and font-weight.
And then `spreadParent()` that seem to do the same as `UPDATE_STYLE_FIELD` but for lenght values (colors are internally lengths, no worry), so it copies the parent style to current node if the current style is `inherit`.

I've been a bit confused by this patch @Frenzie mentionned elsewhere:
https://github.com/blchinezu/pocketbook-coolreader/pull/55/files#diff-e55744b4bf59e4459d1afb4ab2dd6022
which, it seems, should only helps when such a value (initially `css_val_inherited`) become `css_val_unspecified` because it went thru parse_number() with an invalid value.
So, it should fix `<div style="line-height: tagada">` behaving as inherit (uses parent values as if there's never been a style there) instead of unspecified.
Strangely, the current code displays them correctly even without this patch (couldn't make a test case that shows the need for this patch).
Anyway, should an invalid value fallback to unspecified or inherit?

May be this patch was made out just to solve the fact that `letter_spacing` default value is `css_val_unspecified`:
https://github.com/koreader/crengine/blob/228e8a1cec7678ccf74bed52bf53272c36596e76/crengine/include/lvstyles.h#L149
and it should be `css_val_inherited`? (in which case, it should be just fixed in lvstyles.h).

Last question out of fatigue: should `!important` be inhetired ? :) I guess not.
```html
<div style="color: red !important">red
 <div style="color: green">green</div>
 <span style="color: blue">blue</span>
</div>
```
```html
<head>
 <style>
 div { color: red !important }
 </style>
</head>
<div>red
 <div style="color: green">red</div>
 <span style="color: blue">blue</span>
</div>
```

(koreader displays these just as firefox do, so I guess we're fine).

**Comment by poire-z** [comment] 2018-05-01 14:14
> As you said, in certain case, disabling the rule by forcing another will make the tuning option in KOReader useless

@cramoisi : have you seen others than Line spacing/line-height ?

**Comment by Frenzie** [comment] 2018-05-01 15:15
> I've been a bit confused by this patch @Frenzie mentionned elsewhere:

I mentioned it because of the interesting commit message, not because I had evaluated the code or the correctness of the behavior or anything like that. The only other two commits there that looked potentially interesting were these but I don't really know what they're about:

https://github.com/blchinezu/pocketbook-coolreader/commit/d9842c71f6870604c231dfc02519d4bf27942ebc
https://github.com/blchinezu/pocketbook-coolreader/commit/75468eea9afb70c482311ef7fd6b51ba48d911ac


> May be this patch was made out just to solve the fact that letter_spacing default value is css_val_unspecified:
https://github.com/koreader/crengine/blob/228e8a1cec7678ccf74bed52bf53272c36596e76/crengine/include/lvstyles.h#L149
and it should be css_val_inherited? (in which case, it should be just fixed in lvstyles.h).

Sounds about right. But does letter-spacing even do anything in crengine?

> Last question out of fatigue: should !important be inhetired ? :) I guess not.

I don't even know what that would mean. :-P

(Although it could be a way to implement it, I suppose. "Inherit" all !important properties from the one with !important.)

**Comment by cramoisi** [comment] 2018-05-01 15:37
> have you seen others than Line spacing/line-height ?

I wasn't really thinking about KOReader when I said that and the fact is no, the `font-size` and the `margin` are somewhat managed by crengine differently than by css so no, I don't see others

**Comment by cramoisi** [comment] 2018-05-01 15:44
> Last question out of fatigue: should !important be inhetired ? :) I guess not.

@Frenzie : 

`p { color:red !important;}`
`.q { color : black;}`

`<p>lorem lipsum <span class="q">blablah<span> blah</p>`

If !important is inherited q will be red, otherwise, black  ; but it's a extreme example.

**Comment by Frenzie** [comment] 2018-05-01 16:08
Well sure, you could say that `!important` replaces anything further down the cascade or higher in specificity with `property:inherit` instead of whatever its actual value is.

**Comment by poire-z** [comment] 2018-05-01 16:40
> But does letter-spacing even do anything in crengine?

Yes, it does, it adds the length specified there between letters.
https://stackoverflow.com/questions/5612302/which-css-properties-are-inherited
https://www.w3.org/TR/CSS21/propidx.html
says that letter-spacing should be inherited, so I guess we may as well fix it (if it caused the need for that coolreader pocketbook patch).
Other mismatches:
```
    , display( css_d_inherit ) // used internally with crengine own props, so not gonna touch that
    , text_decoration (css_td_inherit) // says "see prose", looks like inherit should be fine
    , vertical_align(css_va_inherit) // touchy in textfm.cpp
    , letter_spacing(css_val_unspecified, 0) // gonna fix that one
    , hyphenate(css_hyph_inherit)
    , border_collapse(css_border_seperate) // table support, not gonna touch that
```
Most are probably a bit touchy in the code, so I'm not going to change them. To be revisited if we see cases where it's wrong.

**Comment by Frenzie** [comment] 2018-05-01 17:15
Pardon, not higher in specificity.

**Comment by Frenzie** [comment] 2018-05-01 17:17
> Yes, it does, it adds the length specified there between letters.

I can't trigger any difference in line spacing in crengine by adjusting that property.

**Comment by poire-z** [comment] 2018-05-01 17:27
I think your crengine is not genuine :|

```html
<body>
This is some text with some long text to see how it wraps with some long text to see how it wraps with some long text to see how it wraps.
<div style="letter-spacing: 0.5em">
This is some text with some long text to see how it wraps with some long text to see how it wraps with some long text to see how it wraps.
</div>
</body>
```
<kbd>![image](https://user-images.githubusercontent.com/24273478/39484243-60757a12-4d75-11e8-9bf0-677c86e296b6.png)</kbd>

**Comment by Frenzie** [comment] 2018-05-01 18:27
```html
<!DOCTYPE html>
<html>
<body>
<div style="letter-spacing:10em">
asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf 
<div style="letter-spacing:asdfasdf">inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? inherit? </div>
</div>
</body>
</html>
```

**Comment by poire-z** [comment] 2018-05-01 18:45
It should work with lower values, 1em or 2em.
There seems to be some limitation to 50 screen pixels:
https://github.com/koreader/crengine/blob/0f7be729dc34798f74257fde06bc9bf0dd76a457/crengine/src/lvfntman.cpp#L1746-L1747

For the second part, is it just that when parse error, it becomes unspecified, and so does not inherit (the pocketbook patch is supposed to fix that) ?

**Comment by Frenzie** [comment] 2018-05-01 19:28
It's just my random testcase I wrote for the inheritance thing, point being even the basic use case doesn't work. ;-)

Anyway, that piece of code is freaking stupid if you ask me. Setting aside my opinion on that ridiculously low limit, a limit is supposed to act like `if value < limit then value = limit`, not like your `value = 0` now lulz roflcopter.

**Closed** 2018-05-01 22:16 UTC
Labels: crengine

**Comment by poire-z** [comment] 2020-05-27 23:27
Answering https://www.mobileread.com/forums/showthread.php?t=330276 here:

> I see that KoReader can have user created styles (in /styletweaks) .
When reading a book there may also be other stylesheets that will influence presentation. Such as, say, one called "book.css" within an EPUB, (the so-called "embedded style").
Then there is the inbuilt "epub.css".
I'm trying to understand in what order the various css stylesheets will be processed.

Order of how CSS are applied
1) the KOReader stylesheet set via `Style>` : epub.css, html5.css, fb2.css
2) snippets enabled in `Style tweaks>` are appended to that

This make the user-agent stylesheet.
Any property with `!important` among the previous ones are _super-important_ :) and won't be overriden by other properties with `!important` in the next stuff (https://github.com/koreader/koreader/issues/4196#issuecomment-451557035).

Then, if `Embedded styles: on` (bottom menu):
3) The book own stylesheets, linked by each DocFragment (internal html file in the EPUB). Each DocFragment may include a different set of css files. They apply only to itself.
4) Styles defined in the DocFragment `<html><head><style>`
5) Style defined as attribute of HTML elements (`<div style="font-weight: bold">...</div>`)

> Understanding this would explain why I was getting indented paragraphs on the first line of a chapter when I wasn't expecting it from the book's own styles. 

Probably because our epub.css sets `p { text-indent: 1.2em; }`.
html5.css doesn't, it's sometimes best to switch to it with recent books.
But you could also just test the styles tweaks in `Style tweaks> Paragraphs> Paragraph first-line indentation>`. More info in: https://github.com/koreader/koreader/wiki/Style-tweaks and #3944 and linked other issues.

**Comment by calverb** [comment] 2020-05-28 12:51
Yes, the problem was that epub.css did set the text-indent to 1.2em however my book's styles had not set an explicit indent for p .   Only the chapters first line was an unstyled p, subesequent ones I had set a text indent as 1.2em.

I've now created a style tweak to reset p to text-indent to 0 and activating it makes KoReader display as I expected.for what is actually a poorly coded book.

**Comment by poire-z** [comment] 2020-05-28 15:12
> for what is actually a poorly coded book

May be not. Some publishers expect to work starting with a stylesheet like web browsers (our html5.css might ressemble that) - and only provide styling when they need to diverge from it.

Web browsers have P without text-indent, and with top and bottom margins.

This might not be ideal for e-books. So, our epub.css is quite different, as it tries to do the best thing for books that have not been styled. It makes P have no top/bottom margins, and have some constant text-indent.

If you have some issues only with paragraphs, there is a style tweak than you can apply over epub.css to just fix them: `Style tweaks> Paragraphs> Generic web browser paragraph style` - which I'm pretty sure will be enough to get what you want with your book.
