### ISSUE TITLE
KOReader not relaunched after auto-shutdown during sleep on PB740

### ISSUE THREAD

**Issue by Valnamu** [koreader/koreader#5126] opened 2019-07-19 18:49 UTC
* KOReader version: koreader-pocketbook-arm-obreey-linux-gnueabi-v2019.05
* Device: Pocketbook 740 / Inkpad 3

##### `crash.log` (if applicable) no crash

is there any setting I could have missed ?
thanks

**Comment by Frenzie** [comment] 2019-07-19 20:19
For those of us without a PocketBook, could you clarify what happens?

**Comment by Valnamu** [comment] 2019-07-19 21:04
Hello
On the Pocketbook, when you are using the native reader, and the device goes to sleep, it "remembers" it was reading that book and that page, and when you wake up your device later, it automatically restart the reading at the very place you were.
[On a Kobo reader, you can have the same behaviour: when you wake it up, you are driven into the book you were reading. ]
That is the way I like to use my device.
But when I use KOreader, I presume the native reader is left "off" (not running), and the system doesnot seem to record which task it was executing when put to sleep, and so it cannot restart the reading (with KOreader) of the current book. Instead, the main page is shown.
You have to tap again the current book to reopen it (with KOreader) and be driven to the page you were reading (I had turned the "reopen last book"  option ON, both in KOreader and in the "system" parameters).
If I were reading a book with the native reader, then at wake-up  the device correctly reopens last book.
But not when the "current reader program" is KOreader.
Tell me if I was clear enough .
thanks

**Comment by Frenzie** [comment] 2019-07-20 09:52
On Kobo KOReader never closes nor restarts. If there's any restarting involved then we're either talking about powering down or there's some vocabulary confusion. Sleep is an extremely low power state that'll still deplete the battery after many months. That doesn't happen while powered down.

Looking at the `git blame` for device/pocketbook I suspect this is probably a duplicate of #3477.

**Comment by Valnamu** [comment] 2019-07-20 12:52
Hello Frans
It must be clear that my point is with Pocketbook, not with Kobo. I was only refering to the nice ability to reopen last book at wake-up...
Having read issue #3477 , I cannot validate the duplicate:
#3477 the device seems to loose / not update the current page # .
In my issue, the current page seems to be correctly updated, as when KOreader is (manually) launched again, it reopens the last book at last page.
Maybe I will be more understandable by saying my issue is : "at wake-up after sleeping while reading with KOreader, Pocketbook does not re-launch KOreader (or does not give it "focus"), while PB re-launch its native reader at wake-up after going to sleep while reading with its native reader  "
thanks

**Comment by Frenzie** [comment] 2019-07-20 13:00
How do you enter sleep?

**Comment by Valnamu** [comment] 2019-07-22 13:07
Hello Frans
Back home...
Your question (how entering sleep?) made me more curious.
Sleep mode is entered by either:
- long pressing home button to open task menu, then pressing "sleep" icon in the task menu
- or closing the cover
Sleep mode then displays the sleep screen (a hammock under a tree) .

I never did this before, but if I reopen the cover within a few minutes, Powerbook exits sleeping mode and reopen the page I was reading.

BUT, if I don't reopen cover, after a delay (probably 10 minutes, according to the setting of auto-shutdown delay...), Powerbook shuts down completely, and needs pressing power button to power on and restart (which I mistakenly thought being exiting sleep mode). It is THERE that my device does not reopen automatically last book if it was read with KOreader.

As I didn't realized that my device was indeed auto-shut down, my issue can then be reformulated as :
"at power-up, after (auto-)shutdown while reading with KOreader, Pocketbook does not re-launch KOreader, while PB re-launch its native reader at power-up after being (auto-)shutdown while reading with its native reader "

hope this can help...
thanks

**Comment by Valnamu** [comment] 2019-07-22 13:58
it seems not to be relaunched after every shutdown, be it auto or manual, during sleep or during reading...

**Comment by Frenzie** [comment] 2019-07-22 14:04
I'm not sure if it should be expected to in circumstances other than booting from what superficially appears like standby but I suppose that's for someone motivated who owns a PocketBook to figure out. :-)

**Comment by LucyOne** [comment] 2019-07-23 20:52
I have the same behaviour on my PB Touch HD 3. Also, when the device shuts down, it should display the book cover of the last opened book. But it only does this if the last book was opened with PB reader or Coolreader, not KOReader. Instead, what is left from KOReader is the label "sleeping" in the middle of the screen. It would be good to lose it when the device is completely shut down.

**Comment by pazos** [comment] 2020-08-19 20:34
Duplicate of #5140

**Closed by pazos** 2020-08-19 20:34 UTC
Labels: PocketBook, firmware, help-wanted

**Comment by j4w0r** [comment] 2020-09-02 13:33
It is not a duplicate of #5140 and should be reopened.

Scenario: koreader opened with some book, pocketbook goes to sleep, after some time (defined in PB power saving settings) it powers off, next you want to power on PB
current behaviour: PB launches system dash board
expected behaviour: PB launches koreader with last book

This scenario should be included in #6597.

**Comment by Frenzie** [comment] 2020-09-02 14:13
Pinging @ezdiy.

**Comment by ezdiy** [comment] 2020-09-02 19:20
@j4w0r It's what #6617 does.

You can test it in [latest snapshot](http://build.koreader.rocks/download/nightly/), along with the rest of the recent pocketbook fixups.
