### ISSUE TITLE
New Nook Model Screen Refresh

### ISSUE THREAD

**Issue by hcors** [koreader/koreader#5681] opened 2019-12-11 23:57 UTC
Hi, 

A few months back I helped test of the changes you all were doing for the Nook Glowlight to get the screen to do a refresh. Well there is a new model that seems to have a system that is identical. Would you all add the Model number to the Nook model check reference in the code from before, and I can test to see if it refreshes the page?

The new model is: BNRV700

Thanks!

**Comment by pazos** [comment] 2019-12-12 16:21
Follow the instructions in https://github.com/koreader/koreader/issues/4551#issue-406883935 and reply with the info in the same ticket, thanks!

Duplicate of #4551

**Closed by pazos** 2019-12-12 16:21 UTC
