### ISSUE TITLE
"Do you want to use an alternative table of content built from the document headings?"

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#4995] opened 2019-05-03 17:17 UTC
* KOReader version: v2019.04-77-gf3decdc_2019-05-02
* Device: Kobo Aura One

#### Issue
For some epubs when I try to open the TOC, it asks this:
"Do you want to use an alternative table of content built from the document headings?"

I can press cancel (nothing happens), then I try to open TOC again, and it works.

But, if I close the cover and wake it up, the prompt appears again.
It also appears when I exit and reopen the file, and try to open the TOC.
Or when switching between two files, with both having the same bug.

Is there a way to open the regular TOC by default, and never be prompted? I don't know if I missed the option for it somewhere.

I noticed this in the last ~4 nightlies

**Comment by Frenzie** [comment] 2019-05-03 17:41
I believe this means you're holding on the menu item rather than tapping it. Pinging @poire-z

**Comment by CalbertAmu** [comment] 2019-05-03 17:45
Maybe it has to do with how the publishers coded the ebook?

Most books do not have this problem, and for them the prompt only appears when i hold the TOC, but for some the prompt appears even with a single tap.

**Comment by poire-z** [comment] 2019-05-03 18:24
No, it really looks like this message is only triggered when holding on the "Table of contents" menu item. No chance to get this message anyway else (and I can't reproduce it). No way it can depends on the book itself.

You can try just modifying one line, line 466 of `frontend/apps/reader/modules/readertoc.lua`
```diff
--- a/frontend/apps/reader/modules/readertoc.lua
+++ b/frontend/apps/reader/modules/readertoc.lua
@@ -465,3 +465,3 @@ function ReaderToc:addToMainMenu(menu_items)
     if self.ui.document:canHaveAlternativeToc() then
-        menu_items.table_of_contents.hold_callback = function(touchmenu_instance)
+        menu_items.table_of_contents.hold_callback_DISABLED = function(touchmenu_instance)
             if self.ui.document:isTocAlternativeToc() then
```
and you should not get this message back. Just to confirm it's really your tap trigerring this hold_callback.

Why do you get it then? Dunno. Either you're a slow tap'er and you press the screen quite long, near the limit where a tap becomes a hold - and this menu being the top-left-most, may be you extend your finger in a way that triggers that.
Or there's some kind of touch event mismatch on your device (2 or 3 times a month, I get that kind of thing on my GloHD: my tap looks like a hold, some text is selected, sometimes multiple words, so it feels like a touch down was registered a long time before, and my tap gets the touch release...)
So, dunno, try rebooting/powering off your device...

No hold anywhere else? Doing that in the `Font>` menu should propose you to make the font a fallback or a default.

I see nothing related to TOC or Kobo touch in the last 4-5+ days commits that have made the last 4-5 nightlies.

Suggestion if you/we can't track that down: use a multiswipe gestures (I swithed to that for TOC, never went back to the menu). See https://github.com/koreader/koreader/releases/tag/v2019.03 for the default gestures.

**Comment by Frenzie** [comment] 2019-05-03 18:32
> Or there's some kind of touch event mismatch on your device (2 or 3 times a month, I get that kind of thing on my GloHD: my tap looks like a hold, some text is selected, sometimes multiple words, so it feels like a touch down was registered a long time before, and my tap gets the touch release...)

Come to think of it, there's an issue like that specifically about coming out of standby somewhere, but I can't find it right now.

Also somewhat related: #4842

**Comment by poire-z** [comment] 2019-05-03 18:45
You're probably thinking about #4431, where I commented about that rare issue of mine at https://github.com/koreader/koreader/issues/4431#issuecomment-455847181

**Comment by Frenzie** [comment] 2019-05-03 18:53
Oh, so it's closed as fixed by something that shouldn't affect it afaict but somehow does. That explains why I couldn't find it. :-)

**Comment by CalbertAmu** [comment] 2019-05-03 19:51
The multiswipe is what I will use from now on, because it doesn't give me the problem.

But I also edited that line just to check, and something strange happens. For the same three books where this was the problem: now when I tap the TOC, I have to tap it again for it to show (as if the prompt was invisible, and I clicked cancel on it).

I can send the three sample books if you want to test them.

**Comment by CalbertAmu** [comment] 2019-05-03 19:54
[Archive.zip](https://github.com/koreader/koreader/files/3143376/Archive.zip)

**Comment by poire-z** [comment] 2019-05-03 21:28
No issue with any of your 3 books on my Kobo (as expected).
You may try to clean koreader/cache/cr3cache/ - just to see, shouldn't have any impact.

Also, how do you make the top menu appear? With tap or swipe down? (I only tested Tap, can't test Swipe because of some personal hacks.)
Toc may be one of the few that have some Hold action in the direct top menu entrien. Another one is `Hanging punctuation` (showing some Make default popup). How does this one do?

**Comment by CalbertAmu** [comment] 2019-05-03 22:10
I make it appear with swipe only. Hanging Punctuation on or off didn't change anything.

But clearing the /cr3cache/ folder worked! Thank you

**Closed** 2019-05-03 22:15 UTC
Labels: crengine

**Comment by CalbertAmu** [comment] 2019-05-05 16:08
Updating nightly resets the line 466 back to the original:

menu_items.table_of_contents.hold_callback = function(touchmenu_instance)

but I'll be using gesture to open TOC.
