### ISSUE TITLE
Dictionary problem

### ISSUE THREAD

**Issue by effeerre75** [koreader/koreader#9515] opened 2022-09-13 20:12 UTC
* KOReader version: 2022.08
* Device: PocketBock PB627

I have a problem with the dictionary attached. When I search something nothing show up.
It was working fine until the version 2021.09.
Already tried to check LF / CRLF line endings as reported in #9455  using DOS2UNIX without any luck.

Thanks for the great work!

[vocabolario_ita.zip](https://github.com/koreader/koreader/files/9560463/vocabolario_ita.zip)

**Comment by poire-z** [comment] 2022-09-13 20:26
Works for me on the emulator:
![image](https://user-images.githubusercontent.com/24273478/190002005-a668540a-19b7-4ef7-a728-92c5a057e4ad.png)

Do other dicts work on your PB ?
And make sure it is checked in Dict settings > Manage dicts.

**Comment by effeerre75** [comment] 2022-09-13 20:50
Thanks for the fast reply!
Yes other dicts works, and is enabled in Dict settings.

**Comment by poire-z** [comment] 2022-09-13 20:52
What if you disable all other dicts, and use the menu item Dict lookup, and type "vivace" like I did ?

**Comment by effeerre75** [comment] 2022-09-13 20:57
![9FA0EDEE-E8B9-445A-9C80-1E033DB4BC74](https://user-images.githubusercontent.com/16226520/190007417-ed06b9db-2e85-4bcd-b8f5-194db38c1cab.jpeg)
![2670F5FF-2987-49B4-858D-9783F8B256FD](https://user-images.githubusercontent.com/16226520/190007448-95ca1da3-7476-4835-b9ea-a7e2326a9750.jpeg)

it say “non disponibile” that means not available

**Comment by poire-z** [comment] 2022-09-13 21:45
And if you disable this dict, and enable the other English_Italian dict, this other dict gives results ?!

> It was working fine until the version 2021.09.

This is not a typo? You have upgraded from 2021.09 to 2022.08 ? Might want to try intermediate versions, to see since which one the issues comes up.
Anyway, no other idea. Also no idea if it's something Pocketbook only (it works on my Kobo).

**Comment by NiLuJe** [comment] 2022-09-13 22:42
That's an interesting theory, I usually remember about how macOS *itself* (well, Finder) craps out `._` resource forks on FAT partitions, but I forgot that *archivers* punt all that crap in a dedicated `__MACOSX` folder, which I'm pretty sure we do *not* account for.

So it's entirely possible we're feding sdcv the __MACOSX folder instead of the actual dict folder.

(Note that I'm not quite sure how we deal with actual resource forks either on the dict front, FWIW).

**Comment by NiLuJe** [comment] 2022-09-14 03:54
Nope, not it, unpacking the zip, resource forks and all, works just fine on a Kobo.

**Comment by effeerre75** [comment] 2022-09-14 08:32
The archive was downloaded from the PB on a Mac and then zipped  and attached.
2021.09 it’s right not a typo.
2021.10 give me that problem if I remember correctly. Reversed back to 2021.09 since I was moving and not always have a connection.

**Comment by NiLuJe** [comment] 2022-09-14 17:57
If you could actually confirm that, it would be helpful, because the only vaguely dictionary related stuff in [2021.10](https://github.com/koreader/koreader/compare/v2021.09...v2021.10) is #8333, and that's unlikely to break anything ;o).

**Comment by effeerre75** [comment] 2022-09-14 18:46
Made some more test:
1. Removed the old version, downloaded and installed by hand the last version (2022.08), put the dictionary "vocabolario" in... it works! 😃 
2. Tryed to download "Italian-english" dictionary, it crashes with the bomb, after restart "vocabolario" doesn't work.
3. New clean install by hand. Installed "vocabolario" and "Italian-english" by hand: doesn't work, also selecting only one of the the two

attacched the "Italian-english" just for reference if needed.

[italian-english.zip](https://github.com/koreader/koreader/files/9569024/italian-english.zip)

**Comment by NiLuJe** [comment] 2022-09-14 19:21
@effeerre75: The crash.log would possibly be useful then ;).

**Comment by effeerre75** [comment] 2022-09-14 20:47
[crash.log.zip](https://github.com/koreader/koreader/files/9569868/crash.log.zip)

**Comment by poire-z** [comment] 2022-09-14 22:04
We see sdcv crashing:
```
[123 : ./luajit] (hw_wait_event)epoll_wait ret -1 : Interrupted system call
g_mkdir failed: No such file or directory
*** Error in `./sdcv': free(): invalid pointer: 0x000a6d3d ***
Aborted
[123 : ./luajit] (hw_wait_event)epoll_wait ret -1 : Interrupted system call
g_mkdir failed: No such file or directory
*** Error in `./sdcv': free(): invalid pointer: 0x000a6d3d ***
Aborted
[123 : ./luajit] (hw_wait_event)epoll_wait ret -1 : Interrupted system call
```

**Comment by NiLuJe** [comment] 2022-09-14 22:53
Always on the exact same pointer, which is... strange.

Check back tomorrow if it works any better after the sdcv update? ;o)

I'm *not* seeing an actual "bomb screen'" crash, though.

But I *do* see more sdcv weirdness at the end, like more sdcv segfaults, leading to truncated JSON output....

**Comment by NiLuJe** [comment] 2022-09-15 16:40
Does [today's nightly](http://build.koreader.rocks/download/nightly/v2022.08-24-g2fe2515a_2022-09-15/koreader-pocketbook-v2022.08-24-g2fe2515a_2022-09-15.zip) behave any better?

**Comment by effeerre75** [comment] 2022-09-16 10:42
out for work. I can test it on tuesday

**Comment by pazos** [comment] 2024-01-11 20:05
Closing old tickets labeled as "need more info" that are not updated anymore. Feel free to open new ones if you can reproduce on the latest release.

**Closed** 2024-01-11 20:06 UTC
Labels: need more info, PocketBook, help-wanted
