### ISSUE TITLE
Dictionary lookup stopped working on KA1

### ISSUE THREAD

**Issue by Kwuik** [koreader/koreader#3541] opened 2017-12-09 03:56 UTC
* KOReader version: v2015.11-1428-g8886e16
* Device: KA1 NOT Kobo Glo (there its working)

#### Issue
Dictionary search returning no results. (Wikipedia lookup ok)

#### Steps to reproduce

2 Dictionarys installed. (e.g. folder: KA1:\.adds\koreader\data\dict\stardict-English_German-2.4.2\)

Open book. 
Long touch for dictionary lookup. Query returns no results.

Worked until a while ago, not shure when stopped working. I am not using the feature that often.

In the menu both dictionarys are shown as installed. How can I find out why it's not working (no crashlog) and why is is it working with the same dictionarys and the same version of Koreader on my Kobo Glo?

**Steps already tried:** 
-reinstalling, 
-removing one dict, 
-placing the dict-files  in the main dict folder. 

(Interesting effect if files in dict folder and one dict still installed inside subfolder there is a nice bug: 
The menu shows the dict in the dict folder not that one in the subfolder and also shows if activated: (0/1) if deactivated (-1/1) 

Removed the subsfolder thereafter. Still doesn't work. Without programming background I ran out of ideas.

**Comment by Frenzie** [comment] 2017-12-09 08:20
Duplicate of #3302 (see workarounds there)

**Closed by Frenzie** 2017-12-09 08:20 UTC

**Comment by Kwuik** [comment] 2017-12-09 14:16
Thanks, the workaround with the sdcv works... Will it continue to work if I do an OTA update? Or do I have to copy the file everytime anew?

Thanks for the fast answer btw. And continue your good work.

**Comment by Frenzie** [comment] 2017-12-09 14:34
Unfortunately the OTA update will overwrite sdcv.

**Comment by Kwuik** [comment] 2017-12-09 16:30
Isn't it possible to include the updated file in the OTA-Realease somehow? Or write protect the file and the update won't overwrite it? couldn't there be any problems if it won't get updated?

(Btw. where can I ask more questions without spamming the issue section? mobileread-forum? e.g. what about the KA1 Nightlight... any progress... can a non programmer help somehow?)
