### ISSUE TITLE
Crash when viewing CBZ files with multible aspect ratio pages on Android

### ISSUE THREAD

**Issue by Gabriel85** [koreader/koreader#10993] opened 2023-10-11 02:07 UTC
* KOReader version: v2023.08
* Device: Tolino Epos 2 & Tolino Shine 3

#### Issue
Koreader gets killed by Android when viewing high resolution CBZ when switching to another page which has a different aspect ratio (e.g. from a portrait page to a landscape one). I suspect it is due some memory leak, since it only happens on low memory decices and not on my 6GB RAM phone. Before the crash the memory usage is normal (<100MB). Koreader has no problems displaying much higher resolution images, as long as they are all in the same aspect ratio.
It only happens with certain settings like auto-crop enabled or when the Fit is set to Height. It does not happen with standard settings with Fit set to Full. Also it does not happen with very low resolution images.
Maybe this is is also an issue on non-Android low memory devices, maybe somebody could check that? Overall this is a very annoying bug, since many CBZs have different aspect ratio pages.

#### Steps to reproduce

1. Open [test.cbr](https://github.com/koreader/koreader/files/12863959/test.zip) on an low memory device (e.g. 512MB)
2. enable either auto-crop or set Fit to page height
3. switch to next page

##### `crash.log`
<details>
  <summary>crash.log</summary>

```
--------- beginning of /dev/log/main
I/wpa_supplicant( 4199): [CTRL_IFACE]wlan0: <if-hidden>
V/KOReader( 4724): input event => type: 4 (EV_MSC), code: 9 (nil), value: 1, time: 10406.700333
V/KOReader( 4724): Android application event 9
I/wpa_supplicant( 4199): [CTRL_IFACE]wlan0: <if-hidden>
I/wpa_supplicant( 4199): [CTRL_IFACE]wlan0: <if-hidden>
I/wpa_supplicant( 4199): [CTRL_IFACE]wlan0: <if-hidden>
I/wpa_supplicant( 4199): [CTRL_IFACE]wlan0: <if-hidden>
I/wpa_supplicant( 4199): [CTRL_IFACE]wlan0: <if-hidden>
D/PhoneWindowManager( 2477): mPstate.get() = 1
D/InputManager-JNI( 2477): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
D/PhoneWindowManager( 2477): mPstate.get() = 1
D/InputManager-JNI( 2477): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
D/PhoneWindowManager( 2477): mPstate.get() = 1
D/InputManager-JNI( 2477): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
D/PhoneWindowManager( 2477): mPstate.get() = 1
D/InputManager-JNI( 2477): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
V/KOReader( 4724): key event => code: 93 (LPgFwd), value: 1, time: 10423.632000
V/KOReader( 4724): goto relative page: 1
V/KOReader( 4724): _refresh: Enqueued partial update for region 0 0 1440 1920 dithering: false
V/KOReader( 4724): setDirty partial from widget ReaderUI w/ NO region; dithering: nil
V/KOReader( 4724): _refresh: Enqueued partial update for region 0 0 1440 1920 dithering: false
V/KOReader( 4724): setDirty partial from widget ReaderUI w/ NO region; dithering: nil
V/KOReader( 4724): pan by 0 0
V/KOReader( 4724): set page position 0
V/KOReader( 4724): painting widget: ReaderUI
V/KOReader( 4724): readerview painting "1253x1920+0+0" to 0 0
V/KOReader( 4724): triggering refresh {
V/KOReader( 4724):   mode = "partial",
V/KOReader( 4724):   region = "1440x1920+0+0"
V/KOReader( 4724): } --[[table: 0x6f487ca0]]
V/MainActivity( 4724): requesting epd update, mode:2, delay:0, [x:0, y:0, w:1440, h:1920]
I/EPD     ( 4724): requested eink refresh, type: 2 x:0 y:0 w:1440 h:1920
V/KOReader( 4724): hinting page 3
I/wpa_supplicant( 4199): [CTRL_IFACE]wlan0: <if-hidden>
D/PhoneWindowManager( 2477): mPstate.get() = 1
D/InputManager-JNI( 2477): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
--------- beginning of /dev/log/system
D/PhoneWindowManager( 2477): mPstate.get() = 1
D/InputManager-JNI( 2477): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
D/PhoneWindowManager( 2477): mPstate.get() = 1
D/InputManager-JNI( 2477): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
D/PhoneWindowManager( 2477): mPstate.get() = 1
D/InputManager-JNI( 2477): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
I/WindowState( 2477): WIN DEATH: Window{42458a78 u0 cn.modificator.launcher/cn.modificator.launcher.Launcher}
I/ActivityManager( 2477): Process cn.modificator.launcher (pid 4056) has died.
I/wpa_supplicant( 4199): wlan0: WPA: Group rekeying completed with 2c:91:ab:21:3f:56 [GTK=CCMP]
I/ActivityManager( 2477): Process com.android.inputmethod.latin (pid 4070) has died.
I/WindowState( 2477): WIN DEATH: Window{415657c8 u0 InputMethod}
W/ActivityManager( 2477): Scheduling restart of crashed service com.android.inputmethod.latin/.LatinIME in 13418ms
I/WindowState( 2477): WIN DEATH: Window{415e2050 u0 SurfaceView}
I/ActivityManager( 2477): Process org.koreader.launcher (pid 4724) has died.
W/ActivityManager( 2477): Force removing ActivityRecord{4133be18 u0 org.koreader.launcher/.MainActivity t33}: app died, no saved state
I/WindowState( 2477): WIN DEATH: Window{41533f68 u0 org.koreader.launcher/org.koreader.launcher.MainActivity}```
</details>

**Comment by jonnyl2** [comment] 2023-10-11 07:28
>Maybe this is is also an issue on non-Android low memory devices, maybe somebody could check that? 

Tested on my 512MB Kobo Aura H2O and both pages rendered fine with auto-crop or fit to page height enabled. The memory usage in the status bar didn't even go up when turning to the 2nd page (52MB). 

On my Android phone, the memory usage went from ~130MB to >300MB, so can confirm this issue appears to be confined to Android.

**Comment by Frenzie** [comment] 2023-10-11 08:26
Duplicate of #10527.

**Comment by jonnyl2** [comment] 2023-10-11 08:54
>Duplicate of https://github.com/koreader/koreader/issues/10527.

That issue *did* affect Kobo though, while this one apparently does not.

**Comment by Frenzie** [comment] 2023-10-11 09:37
Autocrop/fit width/fit height is all the same. In some circumstances it tries to zoom in too much. On a 512 MB Android device pretty much anything is "too much" because it has no memory. By contrast, a 512 MB Kobo has hundreds of megabytes of available memory. Android needs 1 GB or maybe even 2 GB for that.

**Comment by Frenzie** [comment] 2023-10-11 09:45
I don't think it's quite as hopeless as @NiLuJe wrote ftr, though practically speaking that doesn't make a difference I'm afraid. ;-)

**Comment by Frenzie** [comment] 2023-10-11 15:25
> As far as I understand it, the memory footprint of the landscape page
should not be more than 2-3 times of the portrait one on this (low) zoom
level?

It's not.

**Comment by NiLuJe** [comment] 2023-10-11 18:15
And, as was mentioned above, memory pressure on Android will be *much* higher than on Kobo.

That Android basically functions at all on 512MB of RAM is a minor miracle to begin with ;).

**Comment by NiLuJe** [comment] 2023-10-11 19:11
Possibly because there's a processing pass involved, which means you, at least for a while, have *multiple* buffers in flight.

**Comment by pazos** [comment] 2023-10-11 19:17
> I think there should be 150MB available, it is just Android 4.4 and a very light version of it. But I installed some background services, I will get rid of them and try again.

I wouldn't hold my breath on this. The logs you attached contain:

```
I/ActivityManager( 2477): Process cn.modificator.launcher (pid 4056) has died.
I/ActivityManager( 2477): Process com.android.inputmethod.latin (pid 4070) has died.
I/ActivityManager( 2477): Process org.koreader.launcher (pid 4724) has died
```

That means that the framework killed both the launcher app and the input method before killing the application on the foreground. These three, in that order, are the most priority user processes.

From https://developer.android.com/topic/performance/memory-management


![lmk-process-order](https://github.com/koreader/koreader/assets/975883/92036cc7-e307-4d9a-9019-aa6f8e01addc)

**Comment by Frenzie** [comment] 2023-10-11 20:33
@Gabriel85 

Keep in mind the 150 MB number merely came from my Gimp illustration. ;-) It might be as low as around 60 MB depending on the color space of the JPEG and how MuPDF decides to decode it, which is probably closer to the truth. But if it's progressive for example that'll increase the memory requirements. My point that I also somewhat lost myself due to the sudden Gimp error message was that the image is twice the size of the other one. I had merely wanted to show the respective numbers for illustration.

**Comment by Gabriel85** [comment] 2023-10-11 22:49
> > I think there should be 150MB available, it is just Android 4.4 and a very light version of it. But I installed some background services, I will get rid of them and try again.

The official minimum RAM for Android 4.4 is 320MB, but at least one device came out with only 256MB. The actual need for the very basic services is less than 150MB. And I found about 100MB of not needed additional high priority services, like Magisk and some other stuff I had to install. And there is plenty of way to optimize it, like: zRAM, KSM, making the LMK less agressive, swapping, etc.

> That means that the framework killed both the launcher app and the input method before killing the application on the foreground. These three, in that order, are the most priority user processes.

That is normal, those get easily killed. Sometimes even on modern devices. And they must be killed first before the foreground app gets removed.

> Keep in mind the 150 MB number merely came from my Gimp illustration. ;-) It might be as low as around 60 MB depending on the color space of the JPEG and how MuPDF decides to decode it, which is probably closer to the truth. But if it's progressive for example that'll increase the memory requirements. My point that I also somewhat lost myself due to the sudden Gimp error message was that the image is twice the size of the other one. I had merely wanted to show the respective numbers for illustration.

That is definitly true, I made a censored version of the test file in the same resolution, but it ended up 1/3 smaller and it worked without issues.

With some quick optimisations, I got the zoom working, with 70MB RAM usage on the first page and only 60MB on the second one. Auto-crop although is still crashing. 
I think I can get the free RAM to 300MB, which hopefully is enough for any resonable sized image. And there is always the option of resizing them down to a more managable resolution.
I tested the complete book on my Tolino Shine 3, which has the same specs, but no extra apps installed with 250MB free RAM. And it went throu the entire book with cropping and zoom in less than 5 minutes, without issues and 150MB RAM usage on the last page. So yes: 512MB is enough, but just barely. In actual use it will crash sooner or later with high-res CBZs, but at least not reproducable.

Thanks guys for your help! You are great! 👍

By the way, maybe it would be an option to avoid using MuPDF for CBZ? CBZs are just zip-files with images, which get displayed in alphabetical order. The current archive viewer already can do most of it. So maybe MuPDF is a bit overkill for that?
I think CBZ gets more and more popular now, with all those new big devices and color screens. It also would make supporting CBR or other image formats easier.

**Comment by Frenzie** [comment] 2023-10-12 08:15
It might be overkill if we didn't have a MuPDF implementation for other reasons, but since we do anything else it does is more or less free. Pretty much all it does in this case is to provide a little API around image decoding that takes care of saying which page number it is.

**Comment by Gabriel85** [comment] 2023-10-13 09:11
Well I got the free memory to over 300MB on the Epos 2 and while it is enough to display the landscape page, I wasn't able to get it working with auto-crop.  I guess the problem is the big 8" 2.6 Megapixel screen, which seems to use up significantly more memory than the the 6" one of the Shine 3. It is hardly surprising, when 512MB RAM phones were common, they had 0.1MP screens..

But I tried out a Koreader build with an up-to-date MuPDF version and it displays the test-file without issues! And not only that, I was able to open a giant 1.5GB CBZ with much larger images. With this CBZ Koreader was not even able to create a preview image before. Plus it is a bit faster, too.
So maybe there is after all some sort of memory leak or at least never versions of MuPDF are more optimized.

Would it be possible to use a more recent version of MuPDF for Koreader? I think the current one is already 6 years old.

**Comment by Frenzie** [comment] 2023-10-13 09:15
That's a work in progress. ;-)

**Comment by benoit-pierre** [comment] 2023-10-13 11:04
> But I tried out a Koreader build with an up-to-date MuPDF version and it displays the test-file without issues!

Was it one of my builds? Because I also have a memory leak fix in k2pdopt that could have an impact.

**Comment by Gabriel85** [comment] 2023-10-14 04:50
> > But I tried out a Koreader build with an up-to-date MuPDF version and it displays the test-file without issues!
> 
> Was it one of my builds? Because I also have a memory leak fix in k2pdopt that could have an impact.

Yes! Thanks for doing them!
I wasn't using k2pdopt, unless that does the cropping. But whatever it was it didn't affect the permanent memory usage, just something about the caching of images during the processing. I estimate that it increases the memory demand with this test file by about 50MB on my device. With higher res pictures the difference could be even bigger.

But an up-to-date k2pdopt is highly appreciated, too. I always was impressed what it can do, but it just was never good enough for actual use with low quality scans. So I hope the most recent versions are a bit better.

**Comment by Frenzie** [comment] 2023-10-14 07:37
> I always was impressed what it can do, but it just was never good enough for actual use with low quality scans.

It'd probably look better with image quality high. The only problem is you may not have the memory for that. ;-)

**Comment by Gabriel85** [comment] 2023-10-14 08:28
haha, no! k2pdopt was made for Kindles and they still run on 256MB.
The problems are uneven font-sizes and the most annoying is missing letters and sometimes even whole words. But otherwise it is really impressive what it can do with some low quality/effort scan of some old book.

**Comment by Frenzie** [comment] 2023-10-14 13:03
K2pdfopt will have better results if you run it on your computer btw, 'cause you can more easily tune the settings and quickly generate the entire document optimized for your device.

**Closed** 2024-02-05 15:37 UTC
Labels: duplicate
