### ISSUE TITLE
is there a method to use a 3rd party keyboard on android?

### ISSUE THREAD

**Issue by luckyfatpig** [koreader/koreader#9561] opened 2022-09-26 03:16 UTC
koreader doesnt have a chinese keyboard, but im using it on android, is there a method to use a 3rd party keyboard on android?  maybe its a way to solve the problem?

**Comment by pazos** [comment] 2022-09-26 08:34
Duplicate of https://github.com/koreader/koreader/issues/7423

**Closed by pazos** 2022-09-26 08:34 UTC
Labels: enhancement, duplicate
