### ISSUE TITLE
[FR]: file sorting, mark book as read and other file attributes on read-only filesystem.

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#5222] opened 2019-08-18 07:10 UTC
* KOReader version: 2019.08
* Device: Android

Trying to mark a book as read does nothing. It does work fine on a Kobo, though.

**Comment by NiLuJe** [comment] 2019-08-18 13:11
Where are the books stored?

**Comment by pazos** [comment] 2019-08-18 14:42
> Where are the books stored?

If stored outside /sdcard it could be a duplicate of #4859

**Comment by pbienst** [comment] 2019-08-18 16:14
They are indeed on an external card, in a (big) directory handled by syncthing, that I cannot move to internal storage.

Is it an option that koreader creates the sidecar files in its own storage, and not where the books are?

**Comment by pazos** [comment] 2019-08-18 21:20
see this comment from @poire-z: https://github.com/koreader/koreader/issues/4859#issuecomment-479883834

**Comment by hugleo** [comment] 2019-08-22 23:19
Yes, koreader/history doesn't work for some cases but Koreader will be able to use .sdr files normally if you put your files in the following directory:

/External SD card/Android/data/org.koreader.launcher/

but **NOTE** if you uninstall Koreader then **REMEMBER** to remove your sdcard before because android will automatically remove the org.koreader.launcher folder including all your files. Updates are fine though.

**Comment by pazos** [comment] 2019-08-23 00:32
each android app has two paths: 

The first points to the *internal* app storage, somewhere in /data, which is always writable by the app but unacessible from other apps.

The second points to the ***external*** app storage, which is usually symlinked to /sdcard. This path needs permissions and the data stored here is accesible from other apps.

You can see these paths with: `adb logcat KOReader:V *:S | head -n 10`

```adb logcat
--------- beginning of /dev/log/main
--------- beginning of /dev/log/system
I/KOReader(26767): Application started
V/KOReader(26767): Application info {
V/KOReader(26767):   Flags: user, debuggable
V/KOReader(26767):   Paths {
V/KOReader(26767):     Assets: /data/data/org.koreader.launcher/files
V/KOReader(26767):     Library: /data/app-lib/org.koreader.launcher-1
V/KOReader(26767):     Storage: /mnt/sdcard
V/KOReader(26767):   }
```
Please store documents in the Storage path (needs runtime permission since API level 23).

**Comment by hugleo** [comment] 2019-08-23 00:53
Is that true only if you format the sdcard like internal memory. In that case you can't use the sdcard in others devices. But if you use the sdcard like a portable sdcard the only folder with write mode will be just the one with the application name like mentioned above.

**Comment by pazos** [comment] 2019-08-23 10:16
> But if you use the sdcard like a portable sdcard the only folder with write mode will be just the one with the application name like mentioned above. 

Yeah. Again: it is a workaround to be able to RW outside the primary storage path (which in your case is your mars "phone" storage).

**Closed** 2023-02-17 06:35 UTC
Labels: enhancement
