### ISSUE TITLE
Latest update of 6th of May crashes, reinstall works, change of font size still causes full hangs

### ISSUE THREAD

**Issue by peterstamps** [koreader/koreader#10397] opened 2023-05-06 11:55 UTC
Koreader Version 2023.04 On Samsung Android 13.
After Fdroid update Koreader crashes after Each start.
Full uninstall and install with reboots inbetween, solved the crashing.
BUT when changing the font size the App hangs and must be stopped manually.
Error occurs on each epub book.

**Comment by pazos** [comment] 2023-05-06 12:16
duplicate of #10395

Lets move conversation there

**Closed by pazos** 2023-05-06 12:16 UTC
Labels: Android
