### ISSUE TITLE
FR: Distinguish between highlight/invert/underline in bookmark browser and bookmark export

### ISSUE THREAD

**Issue by Atrate** [koreader/koreader#10543] opened 2023-06-05 07:27 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
When highlighting and bookmarking things in KOReader, I use highlights, inverts and underlines to bookmark things with different meanings (e.g. highlights for interesting things and inverts for really important ones). When I come back to such bookmarks, I usually do it through the KOReader bookmark browser and sometimes through exported bookmark files (like HTML), but they sadly do not distinguish between the highlight types in the main display.

**Describe the solution you'd like**
I'd find it very convenient if the bookmark browser and bookmark exports (except JSON as it *does* distinguish between types) distinguished between highlight styles (highlight/invert/underline).

**Describe alternatives you've considered**
Browsing the JSON with vim, enabling folding and searching for "invert", etc. Kind of cumbersome.

**Comment by hius07** [comment] 2023-06-05 07:56
Yes, duplicate of https://github.com/koreader/koreader/issues/10189.

It can be done but due to internal technical reasons this operation is rather expensive.

**Closed** 2023-06-05 07:57 UTC
Labels: enhancement
