### ISSUE TITLE
Highlight sync between multiple devices

### ISSUE THREAD

**Issue by StevenDelich** [koreader/koreader#12890] opened 2024-12-11 01:49 UTC
Something that would be amazing would be a way to synchronize highlights between like an ereader and phone at the press of a button, similar to how there is already that for both book progress and statistics. This is the one thing I can't find a good alternate solution for and having it built in would be perfect!

**Comment by pazos** [comment] 2024-12-11 02:08
Duplicate of https://github.com/koreader/koreader/issues/4587

**Closed by pazos** 2024-12-11 02:08 UTC
Labels: enhancement
