### ISSUE TITLE
[PB630] Hangs when click on File browser icon in main menu

### ISSUE THREAD

**Issue by mbab** [koreader/koreader#7521] opened 2021-04-09 08:06 UTC
crash.log
``` 
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/09/21-09:54:48
 [*] Version: v2021.03

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
04/09/21-09:54:48 INFO  SoftwareVersion:  W630.5.14.1049
Atached mp shm: id 0 addr 4007e000 size 21608
----------------> USING A2PLUS MODE <-----------------
attach_shm: mtfb key=251330849 size=835220
Atached mtfb shm: id 9800b addr 4220a000 size 835220
-------------------------
The task - koreader.app have
 xres=758 yres=1024 bpp=4 vdepth=8
-------------------------
ndepth:4 hqdepth:4 orientation:0
attach_shm: ref key=2130378752 size=778240
Atached ref shm: id 8001 addr 423c5000 size 778240
Atached mqueue: id 8001
OpenTheme: /mnt/ext1/system/themes/Line-OpenWith(Reader).pbt
Theme real name: Line-OpenWith(Reader)
ts: loading default calibration values
ffi.load: librt.so
ffi.load: inkview
ffi.load: inkview
04/09/21-09:54:48 INFO  initializing for device PBSense
04/09/21-09:54:48 INFO  framebuffer resolution: {
    ["w"] = 758,
    ["h"] = 1024,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
04/09/21-09:54:49 INFO  ./cache/fontinfo.dat [string "./cache/fontinfo.dat"]:1: unexpected symbol near '.' initializing it
04/09/21-09:54:52 INFO  Loading plugins from directory: plugins
04/09/21-09:54:52 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/09/21-09:54:52 INFO  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
04/09/21-09:54:52 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
04/09/21-09:54:52 INFO  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
ffi.load: libs/libzstd.so.1
04/09/21-09:54:52 INFO  FM loaded plugin autostandby at plugins/autostandby.koplugin
04/09/21-09:54:52 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
04/09/21-09:54:52 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/09/21-09:54:52 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
04/09/21-09:54:52 INFO  FM loaded plugin calibre at plugins/calibre.koplugin
04/09/21-09:54:52 INFO  CoverBrowser: setting default display modes
04/09/21-09:54:53 WARN  BookInfo cache DB schema updated from version 0 to version 20201210
04/09/21-09:54:53 WARN  Deleting existing ./settings/bookinfo_cache.sqlite3 to recreate it
04/09/21-09:54:53 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin opds at plugins/opds.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin profiles at plugins/profiles.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin qrclipboard at plugins/qrclipboard.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
04/09/21-09:54:53 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
04/09/21-09:55:06 INFO  event times are real clock time: no adjustment needed
04/09/21-09:55:08 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/DejaVuSans.ttf>
04/09/21-09:55:08 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/KINDLE Regular.ttf>
04/09/21-09:55:11 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/DejaVuSans.ttf>
04/09/21-09:55:11 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/KINDLE Regular.ttf>
04/09/21-09:55:14 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/DejaVuSans.ttf>
04/09/21-09:55:14 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/KINDLE Regular.ttf>
warning: type3 glyph doesn't specify masked or colored
04/09/21-09:55:25 INFO  opening file /mnt/ext1/SendToPb/Aprilis.epub
04/09/21-09:55:25 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/DejaVuSans.ttf>
04/09/21-09:55:25 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/KINDLE Regular.ttf>
04/09/21-09:55:25 INFO  RD loaded plugin autostandby at plugins/autostandby.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin calibre at plugins/calibre.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin coverimage at plugins/coverimage.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin gestures at plugins/gestures.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin movetoarchive at plugins/movetoarchive.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin opds at plugins/opds.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin profiles at plugins/profiles.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin qrclipboard at plugins/qrclipboard.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
04/09/21-09:55:25 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
04/09/21-09:55:55 ERROR failed to call event handler onReaderReady plugins/statistics.koplugin/main.lua:805: bad argument #2 to 'format' (number expected, got nil)
04/09/21-09:56:02 ERROR failed to call event handler onPageUpdate plugins/statistics.koplugin/main.lua:2167: attempt to compare nil with number
```

**Comment by hius07** [comment] 2021-04-09 08:20
Have you tried the latest nightly build? Seems to be fixed.

**Comment by mbab** [comment] 2021-04-09 09:26
#7471 helps with above errors in crash.log but now with issue.

**Comment by mbab** [comment] 2021-04-09 11:38
#7471 helps with last 2 errors from crash.log but not an iisue.

**Comment by NiLuJe** [comment] 2021-04-09 15:19
I have no idea what you were intending to say with that last sentence, so:

* Update to the nightly.
* Enable verbose debug logging (Tools > More tools > Developer options)
* Post *that* crash.log if you can actually reproduce a crash.

**Comment by mbab** [comment] 2021-04-10 07:12
[crash.log](https://github.com/koreader/koreader/files/6289387/crash.log)

**Comment by NiLuJe** [comment] 2021-04-10 15:05
Still not a crash ;). That looks like a sane-ish exit, but someone actually familiar with the PB platform will have to investigate.

**Comment by rjd22** [comment] 2022-06-25 19:36
A lot has changed now so most likely this will be fixed. Closing it for now.

**Closed by rjd22** 2022-06-25 19:36 UTC
Labels: PocketBook, firmware, help-wanted
