### ISSUE TITLE
Right to left Manga have an extra white page every second page

### ISSUE THREAD

**Issue by Svahnen** [koreader/koreader#3689] opened 2018-02-21 21:15 UTC
* KOReader version: v2015.11-1523-g78284e1
* Device: Kobo Aura 2nd gen

#### Issue
When reading manga that is made to turn right to left it turns left to right and every second page is an extra white page.
If i turn off all external css the extra white pages disappear and it starts to works like any normal left to right book.

#### Steps to reproduce
Create a epub in Kindle Comic Converter with "Manga mode" and try to read it in Koreader.
The same books work as intended in nickel (Kobos regular os/reader)

**Comment by Frenzie** [comment] 2018-02-22 07:54
The white page must be caused by some style like page-break-before:always, also see https://github.com/koreader/koreader/issues/2047 Not sure what that'd be doing in a bunch of pictures though.

The direction is probably http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-spine-elem

```xml
<spine page-progression-direction=”rtl” toc=”ncx”>
```

**Comment by Svahnen** [comment] 2018-02-24 16:04
if so, it seems like Koreader does not support RTL when using epub, the menu option to enable RTL that is present on other file formats like PDF and CBZ are also not showing

**Comment by Frenzie** [comment] 2018-02-24 16:23
Oh, why didn't you lead with that? :-P That seems to have been introduced in #2075, but indeed only for paged media. That means PDF and DjVu, but the MuPDF engine also does CBZ and various other file formats.

If you long-press on an EPUB you can open it with MuPDF. Then you'll have that RTL option, but reading EPUBs with MuPDF is not well-supported yet. It'll work, but the seams might show. However, for something as simple as a bunch of image files it just might work out perfectly.

I'll have to mull a little on how to prevent too much repetition here, but adding that particular option shouldn't be too hard. Getting the EPUB info from crengine and auto-ticking it would be slightly harder.

@poire-z @robert00s You guys interested by any chance?

**Comment by poire-z** [comment] 2018-02-24 20:48
You mean: have crengine get that `page-progression-direction` value around [there](https://github.com/koreader/crengine/blob/f7f08d93838d16da79e875ccea57a2f2d414301f/crengine/src/epubfmt.cpp#L901), so well well up in readerolling we can decide to show or not that `Read from right to left` menu?
And that menu item options is just to switch tap to go forward / tap to go back touch zones? (not sure why this code made its way into readerrolling - crengine has no support at all for RTL, I'd rather not falsly advertised that :).

Could be easier to just make that menu item available in the new `Document` submenu (so it's well away from the classical menus and does not bother LTR readers), and it's available for all kind of documents, even those that would not announce `page-progression-direction`, no ?

For the original issue about extra white page, there's the classical issue (https://github.com/koreader/koreader/issues/2394#issuecomment-282498326) with our default page-break css styles in our epub.css where opinions vary :) So, clearing external styles or chosing another css in the menu may be a solution.
Also see https://github.com/koreader/koreader/issues/3416#issuecomment-339008693 for an alternative css for books made of images, if that may help.

**Comment by Frenzie** [comment] 2018-02-24 21:41
> readerolling we can decide to show or not that Read from right to left menu?

No, I think an override should always be available. A potential change in crengine would just be about automatically activating it by default since that seems to be what people expect. It might also make sense to make that a global setting (e.g., LTR, RTL or Auto).

I don't really understand the hubbub. Since I'm left-handed I hold my reader in my right hand, which makes tap for next page the most easily available with my thumb, although just swiping each way works just as well. That way my left hand is available should I need to do something more precise. I'd think most of the population would therefore actually prefer the left side of the screen to go to the next page. I prefer my manga like Mushishi RTL rather than mirrored but I don't really see what that has to do with anything else.

I'm not quite sure why I added that to the top of the settings menu, but it might indeed make sense to put it in the Document submenu.

PS Read Mushishi. You won't regret it. :-P

**Comment by chihyang** [comment] 2018-02-25 05:04
Since my idea was just to find a quick way to read PDF/DjVu from right to left, I hoped to make least changes. I didn't consider about rendering of different documents or any other problem, rather I only made small changes to some existing configurations. Didn't expect interfering with Manga. :-P Unluckily I don't have time for further changes now. Maybe @poire-z  could help with that?

PS: it's really long since I updated Koreader last time. It's a big surprise to see so many new features added to it. Thanks all you guys!

**Comment by Frenzie** [comment] 2018-02-25 08:11
@chihyang Your change isn't interfering with anything, don't worry. :-)

**Comment by Svahnen** [comment] 2019-04-13 11:41
The White pages issue is gone when using cool reader engine, but there it still reads LTR and no option to change to RTL.
However in MuPDF White pages are still a problem, but there it's indeed possible to change manually to RTL

**Comment by Frenzie** [comment] 2019-08-30 13:28
Fixed by #5284.

**Closed by Frenzie** 2019-08-30 13:28 UTC
Labels: bug, crengine
