### ISSUE TITLE
Android Night Mode not working

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#6715] opened 2020-09-25 20:20 UTC
* KOReader version: v2020.09-20 ... 2020-09-24
* Device: sofia_retail (MOTO G power), android Q api 29

#### Issue
Night mode on android has stopped working since the last two developmental updates.

**Comment by NiLuJe** [comment] 2020-09-25 20:25
Duplicate of #6708

**Closed by NiLuJe** 2020-09-25 20:25 UTC
