### ISSUE TITLE
Text search in Greek pdf doesn't work properly

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#10538] opened 2023-06-04 13:48 UTC
* KOReader version: 2023.05
* Device: PB 628

#### Issue
Searching for text in Greek pdf does not return correct results. By entering the first letters of a word as the search term, the results include a series of consecutive words that each have a letter from the search.

I give you some pictures.

![Reader_2023-06-04_151301 (Medium)](https://github.com/koreader/koreader/assets/76203123/af2e0bf7-58ae-4221-9957-dfccbb905063)

![Reader_2023-06-04_151335 (Medium) (2)](https://github.com/koreader/koreader/assets/76203123/a49a7f93-8541-4c3d-8a32-322a2bfd50c8)

**Comment by poire-z** [comment] 2023-06-04 14:13
How do you reach this popup ? (and/or: what it its English title ? :)
![image](https://github.com/koreader/koreader/assets/24273478/20b279e3-6282-40e0-9ca9-13aa5e3f1e77)

When doing a text search, I get another kind of dialog:
![image](https://github.com/koreader/koreader/assets/24273478/d7b3eca3-5b23-427b-a1bd-21ff4b513794)
where things somehow work (somehow only, on a PDF, where the text layer may or may not be usable for search I suspect).

**Comment by hius07** [comment] 2023-06-04 15:06
The first screenshot is Search in dictionary, but the second is Fulltext search results.
It would be interesting to highlight the first paragraph of this page and look at the book metadata sdr file.

**Comment by ichnilatis-gr** [comment] 2023-06-06 13:55
Excuse me, I confused the first picture.
I give you an example from another scanned book in monotonic Greek along with its .sdr file.
![Reader_2023-06-05_202649 (Medium)](https://github.com/koreader/koreader/assets/76203123/cb9bb4f0-e38e-4742-b8e0-6367340dc704)


![Reader_2023-06-05_202706 (Medium)](https://github.com/koreader/koreader/assets/76203123/bd65177b-486d-4301-b81c-099eb8e4087a)

[Woodhouse C.M. - 1821 Ο πόλεμος της Ελληνικής Ανεξαρτησίας.sdr.zip](https://github.com/koreader/koreader/files/11665438/Woodhouse.C.M.-.1821.sdr.zip)

**Comment by hius07** [comment] 2023-06-07 11:07
I do not see any bad things in sdr, highlighted fragments taken from pboxes (by muPDF) are good.
So the issue can be in the search functions (which are our custom).
The problematic book is needed for investigation.

**Comment by hius07** [comment] 2023-06-07 11:36
Any problematic page would be enough (I do not promise I will take on it).

**Comment by poire-z** [comment] 2023-06-07 12:05
I/we can't reproduce the issue with a PDF greek book (one you probably shared with us in the past ![image](https://github.com/koreader/koreader/assets/24273478/d7da7067-b961-4a24-895d-5a5ab7b8427b)), so the issue is probably only with that specific book of yours. If you can extract a few pages, AND reproduce your issue with that extract, give us that extract. Otherwise, give us the book.

If you have the issue with ALL your Greek PDF books, including that Dostoyevky one with which I don't have that issue, then tell us.

**Comment by ichnilatis-gr** [comment] 2023-06-08 13:50
> I/we can't reproduce the issue with a PDF greek book (one you probably shared with us in the past ![image](https://user-images.githubusercontent.com/24273478/244051528-d7da7067-b961-4a24-895d-5a5ab7b8427b.png)), so the issue is probably only with that specific book of yours. If you can extract a few pages, AND reproduce your issue with that extract, give us that extract. Otherwise, give us the book.
> 
> If you have the issue with ALL your Greek PDF books, including that Dostoyevky one with which I don't have that issue, then tell us.

I encounter the same problem with Dostoevsky's book "Αδελφοί Καραμάζοβ - Α".

![Reader_2023-06-08_163718 (Medium)](https://github.com/koreader/koreader/assets/76203123/f3877297-ae2a-4d11-8b25-8a70a0380114)

![Reader_2023-06-08_163748 (Medium)](https://github.com/koreader/koreader/assets/76203123/8be56dc5-c819-4747-a6f2-7938d7e94b2d)


Here are the extracted pages from the two books: 

[Extracted pages from Woodhouse C.M. - 1821 Ο πόλεμος της Ελληνικής Ανεξαρτησίας.pdf](https://github.com/koreader/koreader/files/11688969/Extracted.pages.from.Woodhouse.C.M.-.1821.pdf)

[Extracted pages from Dostoyevsky Fyodor - Αδελφοί Καραμάζοβ Α.pdf](https://github.com/koreader/koreader/files/11688971/Extracted.pages.from.Dostoyevsky.Fyodor.-.pdf)

And the .sdr file of Dostoyevsky's book: 
[Dostoyevsky Fyodor - Αδελφοί Καραμάζοβ Α.sdr.zip](https://github.com/koreader/koreader/files/11688987/Dostoyevsky.Fyodor.-.sdr.zip)

**Comment by ichnilatis-gr** [comment] 2023-06-08 16:57
> Isn't it strange you hadn't noticed it before ? Or had you ?

It seems strange to me too... If I remember correctly, I think I could search for words in a scanned Greek text in the past.

> If you have some PDF with mostly Greek, but some Latin/English words in it, can you check if searching for bits of Latin/English words work ?

I did a search for an English text in Woodhouse's book (which has words in Latin letters) and there is no problem with it.

**Comment by poire-z** [comment] 2023-06-09 09:44
You can play with it, to see if at least  it makes things fine for you. Just replace your frontend/document/koptinterface.lua with this one:  [koptinterface.lua.txt](https://github.com/koreader/koreader/files/11704908/koptinterface.lua.txt) (remove the .txt extension).

It won't be merged as it is, it needs more thinking and testing with Chinese and other languages. Probably not soon as I'll be off for 2 weeks, unless somebody else take some interest in fixing this "search in PDF" old and strange code.

**Comment by poire-z** [comment] 2023-06-30 14:12
I think we could go with that:

```diff
--- a/frontend/document/koptinterface.lua
+++ b/frontend/document/koptinterface.lua
@@ -1337,18 +1337,22 @@ end
 local function all_matches(boxes, pattern, caseInsensitive)
     -- pattern list of single words
     local plist = {}
-    -- split utf-8 characters
-    for words in pattern:gmatch("[\32-\127\192-\255]+[\128-\191]*") do
-        -- split space seperated words
-        for word in words:gmatch("[^%s]+") do
-            table.insert(plist, caseInsensitive and word:lower() or word)
+    -- (as in util.splitToWords(), but only splitting on spaces, keeping punctuations)
+    for word in util.gsplit(pattern, "%s+") do
+        if util.hasCJKChar(word) then
+            for char in util.gsplit(word, "[\192-\255][\128-\191]+", true) do
+                table.insert(plist, char)
+            end
+        else
+            table.insert(plist, word)
         end
     end
+    local pnb = #plist
     -- return mached word indices from index i, j
     local function match(i, j)
         local pindex = 1
         local matched_indices = {}
-        if #plist == 0 then return end
+        if pnb == 0 then return end
         while true do
             if #boxes[i] < j then
                 j = j - #boxes[i]
@@ -1357,9 +1361,26 @@ local function all_matches(boxes, pattern, caseInsensitive)
             if i > #boxes then break end
             local box = boxes[i][j]
             local word = caseInsensitive and box.word:lower() or box.word
-            if word:match(plist[pindex]) then
+            local pword = plist[pindex]
+            local matched
+            if pnb == 1 then -- single word in plist
+                matched = word:find(pword, 1, true)
+            else -- multiple words in plist
+                if pindex == 1 then
+                    -- first word of query should match at end of a word from the document
+                   matched = word:sub(-#pword) == pword
+                elseif pindex == pnb then
+                    -- last word of query should match at start of the word from the document
+                    matched = word:sub(1, #pword) == pword
+                else
+                    -- middle words in query should match exactly the word from the document
+                    matched = word == pword
+                end
+            end
+            if matched then
                 table.insert(matched_indices, {i, j})
-                if pindex == #plist then
+                if pindex == pnb then
+                    -- all words in plist iterated, all matched
                     return matched_indices
                 else
                     j = j + 1
```
[koptinterface.lua.txt](https://github.com/koreader/koreader/files/11917089/koptinterface.lua.txt) => `frontend/document/koptinterface.lua` if you want to test it.

**Comment by ichnilatis-gr** [comment] 2023-07-03 11:23
It seems that it performs a case-sensitive search, regardless of whether the relevant option is selected.

**Comment by poire-z** [comment] 2023-07-03 11:40
Yep, looks like I removed too much from the original.
Here's one that should work better: [koptinterface.lua.txt](https://github.com/koreader/koreader/files/11936409/koptinterface.lua.txt)

**Comment by ichnilatis-gr** [comment] 2023-07-03 13:03
I'm sorry, I don't see any difference.

**Comment by poire-z** [comment] 2023-07-03 13:16
No sorry needed, thanks for testing and helping me fixing it :)

So, ok, Greekness again, and our Lua lower() not handling them - need to use `Utf8Proc.lowercase(util.fixUtf8(word, "?"))` like we do elsewhere.
Here's a 3rd try: [koptinterface.lua.txt](https://github.com/koreader/koreader/files/11937152/koptinterface.lua.txt)

**Comment by ichnilatis-gr** [comment] 2023-07-03 13:21
It works properly now! Thanks!

**Closed** 2023-07-04 07:03 UTC
