### ISSUE TITLE
KOReader doesn't seems to work on Pocket Book Touch HD (PB361)

### ISSUE THREAD

**Issue by ploum** [koreader/koreader#3312] opened 2017-10-06 21:42 UTC
* KOReader version: koreader-nightly-20171004
* Device: PB 631 (Pocket Book Touch HD)

#### Issue

Unable to launch koreader on PB 631.

#### Steps to reproduce

1. Follow the wiki to install Koreader (basically copying /system and /applications)
2. Books don't open anymore. Also, KOReader refuses to open from the application menu.

If I modify the extension.cfg to have multiple readers (CR3, eink-reader), then the "open with" menu shows koreader.app, which means it doesn't recognize it as an app (when the app is installer, the real name should be used and .app should not be displayed)

**Comment by mk-f** [comment] 2017-10-06 22:44
Please Post your ``crash.log``, it should be under ``applications/koreader/crash.log``

**Comment by ploum** [comment] 2017-10-06 23:00
[crash.log](https://github.com/koreader/koreader/files/1364077/crash.log)

**Comment by mk-f** [comment] 2017-10-06 23:39
Looks like a duplicate of https://github.com/koreader/koreader/issues/2276, you can try to change  ``koreader/frontend/device/pocketbook/device.lua`` according to https://github.com/koreader/koreader/issues/2276#issuecomment-268991273.

**Comment by Frenzie** [comment] 2017-10-07 07:48
@ploum 
Bonjour, êtes-vous ici à cause de moi? :-)

@mk-f I note that the Pocketbook stuff isn't using `/etc/devicename` yet. Or could there be something as simple as an environment variable floating around? On Kindle it's all rather complex:

https://github.com/koreader/koreader/blob/b7785753c6b55f7337934f08e6b764df287709b5/frontend/device/kindle/device.lua#L576-L626

I find the Kobo method a bit more elegant:

https://github.com/koreader/koreader/blob/b7785753c6b55f7337934f08e6b764df287709b5/frontend/device/kobo/device.lua#L295-L305

https://github.com/koreader/koreader/blob/b7785753c6b55f7337934f08e6b764df287709b5/frontend/device/kobo/device.lua#L515-L539

(except for that error throwing at the end — I'd rather try to paint something useful to the screen instead)

**Comment by mk-f** [comment] 2017-10-07 13:23
@Frenzie See [this commit][1].

@ploum Could you try with [this][1] ``koreader/frontend/device/pocketbook/device.lua`` and post the ``crash.log`` again? This will certainly still crash, but give me a DeviceName to work with.

[1]: https://github.com/mk-f/koreader/blob/668c7052556e6e6e339499e749ef6ac7a1640fa0/frontend/device/pocketbook/device.lua

**Comment by Frenzie** [comment] 2017-10-07 13:28
@mk-f I quite like that. Combined with some Kobo-like device init I figure that should do the trick. 👍

**Comment by mk-f** [comment] 2017-10-07 13:43
Thanks. The problem will be what to return for an unknown device. I aim to replace as much as possible with the ``libinkview``-api which hopefully works on all devices - for the remains (e.g. ``emu_events``) it's probably possible to probe for multiple paths.

**Comment by ploum** [comment] 2017-10-08 14:30
@Frenzie > I'm not sure I'm there because of you. Did we discuss on the Mobilereads forum or on Twitter?

**Comment by ploum** [comment] 2017-10-08 14:32
anyway, I will try suggestions here. I understand that no one in the dev team has a PB 631 so I'm willing to help by testing and sending crash logs :-)

**Comment by Frenzie** [comment] 2017-10-08 14:36
@ploum I've been a regular reader of your blog for a while and I recently left a comment about "zen" devices. ;-)

**Comment by ploum** [comment] 2017-10-08 15:14
@Frenzie > Excellent :-)   I bought a PB 631 in the quest of my perfect zen device ;-)

**Comment by ploum** [comment] 2017-10-16 10:00
@mk-f  > I confirm that modifying the device.lua works to launch KOReader from the app menu.

Some problems:

1. It doesn't work to open a book from the library (long press -> open with)
2. I have also an app called _koreader.

Both issues might not be related at all. Just to underline that it works globally and I'm willing to help testing on the PB361

**Comment by ploum** [comment] 2017-10-16 10:00
Not sure I should close this, I did it by mistake.

**Comment by mk-f** [comment] 2017-10-16 11:56
@ploum please use the [this](https://github.com/mk-f/koreader/blob/668c7052556e6e6e339499e749ef6ac7a1640fa0/frontend/device/pocketbook/device.lua) ``device.lua`` and post the crash.log here (please use the linked ``device.lua`` as it will spit out the correct device-name and fw-version).

**Comment by iamjustaguest** [comment] 2017-10-21 14:49
The requested crash.log. 

Relevant lines:
>INFO  SoftwareVersion:  U631.5.16.579
>INFO  DeviceModel:  PB631

[crash.log](https://github.com/koreader/koreader/files/1404183/crash.log)

**Comment by ploum** [comment] 2017-10-22 11:48
[crash.log](https://github.com/koreader/koreader/files/1404841/crash.log)

Latest crash in the log is with the newly provided device.lua

**Comment by mk-f** [comment] 2017-10-22 14:00
Please try with [this](https://github.com/mk-f/koreader/blob/1eb519d845439c2c4876228dbc2ff311f8512711/frontend/device/pocketbook/device.lua) ``device.lua``. Battery-Percentage will not work, ill do this in a later commit.

**Comment by iamjustaguest** [comment] 2017-10-22 14:17
crash.log with the new device.lua
Koreader starts and book opened.

[crash.log](https://github.com/koreader/koreader/files/1404959/crash.log)

**Comment by mk-f** [comment] 2017-10-22 14:50
thanks, that's good news. Maybe you can also test if the Battery-Percentage / Charging-Status works with [this](https://github.com/mk-f/koreader/blob/953084ca771bbb480ff8e19164c78492582e7dad/frontend/device/pocketbook/powerd.lua)``powerd.lua``?

**Comment by iamjustaguest** [comment] 2017-10-22 15:25
Statusbar shows battery status (currently 54%) and the + sign when charging with this powerd.lua

**Comment by mk-f** [comment] 2017-10-22 15:39
@iamjustaguest thanks for testing!

**Comment by ploum** [comment] 2017-10-22 16:04
Does it worth it that I test too or, when you ask for testing on the PB631, is one reply from @iamjustaguest or me enough?

**Closed** 2017-10-22 16:08 UTC
Labels: bug, PocketBook

**Comment by ploum** [comment] 2017-10-22 16:11
Wow, great! Thanks a lot :-)  Waiting for the fixe to be in a nightly build I can install.
