### ISSUE TITLE
KOReader 2024.07 "Outside" - Not working on Tolino Shine Color (same as Kobo Clara Color)

### ISSUE THREAD

**Issue by noiprocks** [koreader/koreader#12177] opened 2024-07-17 18:25 UTC
I have tried all different methods as described here in the wiki except the deprecated method: 

https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices

None of them works sadly. No reboot is initiated which should be triggered by koboroot.tgz I think.

Koreaner, plato and Kimono show up as book-icons in the library, but they don't launch the apps. They just open as a one page book. No Nickel-menu appears in the menu settings.

My tolino has the firmware version 5.0.178115.

In the configuration file (.kobo/Kobo/Kobo eReader.conf) I found a new setting, after typing "devmodeon" into the search bar of my device. It now shows the new setting:

[DeveloperSettings]
EnableDebugServices=true

In an earlier firmware typing "devmodeon" led to the new menu item "developer settings" in the menu "device info".

Does this mean we/my device now has real usb debugging settings?

Please let me know if I can assist, help or be a Guinea pig in some kind of way. I really want to get Koreader running on my device, so that I can finally read comics in a convenient way!

Thanks in advance for any tips or support!

**Comment by Frenzie** [comment] 2024-07-17 18:32
I think this is a duplicate of https://github.com/koreader/koreader/issues/12047

**Comment by noiprocks** [comment] 2024-07-17 18:53
I wanted to make a (new) thread specifically for the new release .. .should I close this one than and post my initial comment in #12047 ?

**Comment by noiprocks** [comment] 2024-07-17 18:57
joined #12047

**Closed** 2024-07-17 18:57 UTC
Labels: enhancement
