### ISSUE TITLE
Display first image as cover page

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#7770] opened 2021-05-28 13:40 UTC
There are epub books whose cover is not displayed in file browser (display modes with covers).
Could there be a fall back to the first image or first page if the book doesn't declare a cover, please?

Thank you!

**Comment by poire-z** [comment] 2021-05-28 14:04
Probably not:
- the first page of an EPUB can be directly the book text, and we're then better with the current author|title|filenam fake cover - and if there is a cover image, it's the publisher job to make it known via the classic metadata in the .opf (and may be it does on some of your books, and we just don't know yet about that alternative way)
- to display the first page, we'd need to render the book - and with crengine, that means rendering the full book, which may take some +100s seconds on some book

(Probably a duplicate of some other issue.)

**Comment by ichnilatis-gr** [comment] 2021-05-29 09:28
I understand that the reference to the first page was somehow nonsense and it's a difficult task.
Is it just as difficult for the first picture in the book to be displayed as a cover if the publisher hasn't set a cover in metadata? I have in my mind the Pocketbook library, where, unless a book cover is set, the first image appears as such.

**Comment by Frenzie** [comment] 2021-05-29 09:35
The first image could just as easily be some flourish.

**Closed** 2021-06-13 21:53 UTC
Labels: CREngine, can't fix, enhancement
