### ISSUE TITLE
Problem with pocketbook 4 touch Lux after firmware upgrade 

### ISSUE THREAD

**Issue by steliosgr1980** [koreader/koreader#7654] opened 2021-05-09 05:36 UTC
* KOReader version: **koreader-pocketbook-v2021.04** firm. ver. U627.6.3.559
20210311_135713
WW
* Device: **Pocketbook 4 touch Lux**

#### Issue
Orientation problem, koreader starts with wrong orientation but the worst is when i go to touch screen to change it is like to touch to another place on screen. I realize that i see 90 degreess orientation but is like have 0 degrees and its weird. I did stimulative 2 upgrades one in devices firmware and koreader.
The touch works perfectly outside koreader, and the problem starts after upgrade immediately. 

#### Steps to reproduce
I downgraded koreader , deleted, install it again but the problem persist.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/6446978/crash.log)

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>
  
```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment] 2021-05-09 06:17
Closing as a duplicate of https://github.com/koreader/koreader/issues/7614

**Closed by Frenzie** 2021-05-09 06:17 UTC
Labels: PocketBook, duplicate, firmware
