### ISSUE TITLE
Lack of Automatic Power Saving/Screen Lock

### ISSUE THREAD

**Issue by nuliukas** [koreader/koreader#1565] opened 2015-06-21 01:04 UTC
If I had to pick one single feature that I am missing the most on my Kobo Glo device, it would be the ability of KOReader to lock the screen/enter a power saving mode after a particular period of inactivity. 

This would be helpful in the following scenarios. First, entering a power saving mode (screen light off) would allow to save some precious battery power. Second, screen locking alone would help to avoid unintentional screen tapping after, say, one falls asleep while reading, which may lead to unpredictable and undesirable consequences.

**Comment by Frenzie** [comment] 2015-06-21 07:28
I'm closing this because it's a duplicate of #1356.

**Closed by Frenzie** 2015-06-21 07:28 UTC

**Comment by nuliukas** [comment] 2015-06-21 10:06
Why did you close it? Have you *actually* read it? My issue is the screen locking feature, with power saving or without it. (Preferably with.) I loathe the idea of my ebooks "being read" while the device is in my bag or on my bed sheets, just because I forgot to lock the screen manually.

**Comment by Frenzie** [comment] 2015-06-21 10:33
Take a breath. What exactly is it about automated standby that wouldn't fulfill your needs?

**Comment by nuliukas** [comment] 2015-06-21 11:15
In essence, its slow implementation. Looking at the bug report you mentioned, it seems like it is not being worked on actively.

Having said that, the (a) delayed locking of the screen *and* (b) turning off of the frontlight would perfectly suit my needs. I am not concerned with advanced power management that much (i.e. entering deep sleep states, if any, *und so weiter*).

I am not a developer and hence I have no clue how hard it is to implement this. Yet I suspect the implementation of the automatic suspend feature might require additional work. So, to put it clearly: Automatic Suspend > Lock Screen/Frontlight Off. However, should the former require a lot of work, the latter is more than desirable.

**Comment by Frenzie** [comment] 2015-06-21 11:50
> I am not a developer and hence I have no clue how hard it is to implement
this. Yet I suspect the implementation of the automatic suspend feature
might require additional work.

I see no reason to suppose so. The missing piece is the same either way.
Since waking up takes less than a second, I see no merit to the other
suggestions — especially a separate lock screen, which would in fact
require additional effort on top of the missing piece.

**Comment by chrox** [comment] 2015-06-21 13:43
This feature request is technically a duplicate of #1356 and need to be closed for better issue tracking. And I would suggest to implement a seperate power management service which is absent on Kobo platform. The service is started in the koreader launching script before the reader is lauched. And the only thing this service does is monitoring the next user touch event for a timeout of saying 10 minutes, if it's timeout it will trigger a suspend of the system. Then koreader won't respond to any touch events thus solves the problem of @nuliucas. And the reader logic won't be affected much if not at all.

**Comment by yogi81** [comment] 2024-12-25 19:59
@nuliukas you can try out a small plugin I have created which works nicely for me on kobo sage in combination with a koreader:
https://github.com/yogi81/screenlock_koreader_plugin
