### ISSUE TITLE
Progress sync is not syncing reading statistics. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#8160] opened 2021-08-31 17:31 UTC
* KOReader version: 8.2021 on both devices. 
* Device: first one is Samsung galaxy Tab A (T-285), second device is Samsung galaxy Tab A (T-295) 

#### Issue: I use both devices for reading (the t285 is for reading outside and the t295 inside) syncing progress is working perfectly between the devices, but it does not sync the reading statistics. 
So when I use the reading statistics (after syncing obviously) the (total time spent reading this book is not - summed -) and this finally will affect the time spent reading this book and the estimated time to read and the pages read (each device will calculate it's own statistics data separately). 
Device one:
![IMG_20210831_202016_993](https://user-images.githubusercontent.com/70109540/131547671-5a0ec47f-811b-4499-a7bf-557937585bbb.jpg)
![IMG_20210831_202011_913](https://user-images.githubusercontent.com/70109540/131547689-2ab00b35-93db-42e0-a7d5-83349d68f452.jpg)

Device two :
![Screenshot_2021-08-31-19-55-34](https://user-images.githubusercontent.com/70109540/131547780-15dc673e-68e4-44b9-9483-6b1ceaca85b9.png)
![Screenshot_2021-08-31-19-56-08](https://user-images.githubusercontent.com/70109540/131547798-ffb5eb29-a482-4d3d-99c1-6f20645a4b61.png)

See the pages read on device one is 115 and on device two is 131 so it's 246 pages total, and the current page/total pages is 267 (the difference is pages I skipped). 

I think it should sync up the whole book status (statistics) not only the page where I stopped reading on the device, or create a new plugin for that if it's not hard work.

**Comment by poire-z** [comment] 2022-01-21 21:53
Duplicate of #7058.

**Closed by poire-z** 2022-01-21 21:53 UTC
Labels: enhancement
