### ISSUE TITLE
ko reader becomes unresponsive after opening a complex pdf

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#2994] opened 2017-07-02 11:37 UTC
* KOReader version:latest nightly
* Device:kindle voyage

#### Issue
On opening a complex pdf , ko reader sometimes become slow and unresponsive.I am attaching the corresponding pdf file.
[lehs3ps.pdf](https://github.com/koreader/koreader/files/1117761/lehs3ps.pdf)

**Comment by Frenzie** [comment] 2018-03-06 20:22
I'm not sure to what extent we can call that a bug. It's a very heavy PDF; even my desktop takes a couple of seconds to load it at first. But after initial loading cache kicks in.

I'll close this for now, but there is something about sticking UI in a different thread on someone's mind in any case. :-)

**Closed by Frenzie** 2018-03-06 20:22 UTC

**Comment by Frenzie** [comment] 2018-03-06 20:24
Let's call it a duplicate of #2929.
