### ISSUE TITLE
[Android] crashes when PDF reflow=on

### ISSUE THREAD

**Issue by ildar** [koreader/koreader#10533] opened 2023-06-03 09:31 UTC
* KOReader version: 2023.05
* Device: AGM H3, Android 13 / LOS GSI

#### Issue
switching reflow=on for PDF file crashes the app

#### Steps to reproduce
open a PDF, set Перекомпоновка=вкл.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. Unfortunately the app's crash.log doesn't show the last lines (significant), so adb log: [FULL adb.logcat.txt](https://github.com/koreader/koreader/files/11642202/adb.logcat.txt)

<details>
  <summary>crash.log</summary>

```
...
06-03 15:04:06.853 21925 22456 I KOReader: Restoring user input handling
06-03 15:04:08.011 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:08.011 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:08.104 21925 22456 W KOReader: Running low on memory (~14%, ~567.40/3798 MiB), evicting half of the cache...
06-03 15:04:08.750 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:08.750 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:08.751 21925 22456 W KOReader: Running low on memory (~14%, ~565.55/3798 MiB), evicting half of the cache...
06-03 15:04:10.126 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:10.126 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:10.128 21925 22456 W KOReader: Running low on memory (~14%, ~565.90/3798 MiB), evicting half of the cache...
06-03 15:04:10.677 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:10.677 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:10.678 21925 22456 W KOReader: Running low on memory (~14%, ~557.67/3798 MiB), evicting half of the cache...
06-03 15:04:12.334 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:12.334 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:12.336 21925 22456 W KOReader: Running low on memory (~14%, ~565.19/3798 MiB), evicting half of the cache...
06-03 15:04:12.915 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:12.915 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:12.916 21925 22456 W KOReader: Running low on memory (~14%, ~564.52/3798 MiB), evicting half of the cache...
06-03 15:04:16.363 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:16.364 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:18.020 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:18.021 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:18.261 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:18.261 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:24.631 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:24.631 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:24.647 21925 22456 I KOReader: opening file /storage/emulated/0/Books/libgenesis/Formal Concept Analysis_ Mathematical Foundations - (5c17896c91ac6a8f6f543d6876c0ae4f).pdf
06-03 15:04:24.798 21925 22456 I KOReader: Inhibiting user input
06-03 15:04:24.813 21925 22456 E KOReader: Failed to initialize autowarmth plugin: plugins/autowarmth.koplugin/main.lua:87: attempt to compare nil with number
06-03 15:04:24.815 21925 21925 V Surface : surface changed {
06-03 15:04:24.815 21925 21925 V Surface :   width:  720
06-03 15:04:24.815 21925 21925 V Surface :   height: 1440
06-03 15:04:24.815 21925 21925 V Surface :  format: OPAQUE
06-03 15:04:24.815 21925 21925 V Surface : }
06-03 15:04:24.815 21925 21925 V NativeGlue: NativeWindowResized: 0xb40000710936bb70 -- 0xb4000071c93650a0
06-03 15:04:24.869 21925 22456 I KOReader: setting zoom mode to page
06-03 15:04:26.084 21925 21925 V Surface : surface changed {
06-03 15:04:26.084 21925 21925 V Surface :   width:  720
06-03 15:04:26.084 21925 21925 V Surface :   height: 1440
06-03 15:04:26.084 21925 21925 V Surface :  format: OPAQUE
06-03 15:04:26.084 21925 21925 V Surface : }
06-03 15:04:26.084 21925 21925 V NativeGlue: NativeWindowResized: 0xb40000710936bb70 -- 0xb4000071c93650a0
06-03 15:04:26.101 21925 22456 E IMGMapper: set:481 Failed to decode data for type SMPTE2086
06-03 15:04:26.102 21925 22456 E IMGMapper: set:481 Failed to decode data for type CTA861_3
06-03 15:04:26.225 21925 22456 W KOReader: Running low on memory (~14%, ~565.87/3798 MiB), evicting half of the cache...
06-03 15:04:26.966 21925 22456 I dlopen  : dl.dlopen - libc.so => /system/lib/libc.so
06-03 15:04:26.971 21925 22456 V dlopen  :     dl.dlopen - needed => ld-android.so (1 of 2) <= /system/lib/libc.so
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - ld-android.so => /system/lib/ld-android.so
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - skipping /system/lib/ld-android.so (system lib)
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - needed => libdl.so (2 of 2) <= /system/lib/libc.so
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - libdl.so => /system/lib/libdl.so
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - skipping /system/lib/libdl.so (system lib)
06-03 15:04:26.972 21925 22456 V dlopen  : dl.dlopen - load_func -> /system/lib/libc.so
06-03 15:04:26.973 21925 22456 E linker  : library "/system/lib/libc.so" ("/apex/com.android.runtime/lib/bionic/libc.so") needed or dlopened by "/data/app/~~WeHbZNvImOlLGI6NmkUR6w==/org.koreader.launcher.fdroid-pDhFadIDwgrTsN8sSzBTZQ==/lib/arm64/libluajit.so" is not accessible for the namespace: [name="(default)", ld_library_paths="", default_library_paths="/system/lib64:/system/system_ext/lib64", permitted_paths="/system/lib64/drm:/system/lib64/extractors:/system/lib64/hw:/system/system_ext/lib64:/system/framework:/system/app:/system/priv-app:/system/system_ext/framework:/system/system_ext/app:/system/system_ext/priv-app:/vendor/framework:/vendor/app:/vendor/priv-app:/system/vendor/framework:/system/vendor/app:/system/vendor/priv-app:/odm/framework:/odm/app:/odm/priv-app:/oem/app:/system/product/framework:/system/product/app:/system/product/priv-app:/data:/mnt/expand:/apex/com.android.runtime/lib64/bionic:/system/lib64/bootstrap"]
06-03 15:04:26.974 21925 22456 E NativeThread: Failed to run script: ffi/mupdf.lua:1047: attempt to index local 'pthread' (a nil value)
06-03 15:04:27.068 21925 21925 V NativeGlue: Pause: 0xb40000710936bb70
06-03 15:04:27.085 21925 22456 D libFrameRecord: unloaded from org.koreader.launcher.fdroid
06-03 15:04:27.233  1210  8775 I ActivityManager: Process org.koreader.launcher.fdroid (pid 21925) has died: fg  TOP
06-03 15:04:27.233  1210  1241 I libprocessgroup: Successfully killed process cgroup uid 10356 pid 21925 in 0ms
06-03 15:04:27.234   626   626 I Zygote  : Process 21925 exited cleanly (1)
06-03 15:04:27.286  1210  1232 W ActivityManager: setHasOverlayUi called on unknown pid: 21925
```
</details>

**Comment by NiLuJe** [comment] 2023-06-03 15:59
Well, that's... interesting.

What architecture is this running on, and is this an official build?

```
06-03 15:04:26.966 21925 22456 I dlopen  : dl.dlopen - libc.so => /system/lib/libc.so
06-03 15:04:26.971 21925 22456 V dlopen  :     dl.dlopen - needed => ld-android.so (1 of 2) <= /system/lib/libc.so
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - ld-android.so => /system/lib/ld-android.so
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - skipping /system/lib/ld-android.so (system lib)
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - needed => libdl.so (2 of 2) <= /system/lib/libc.so
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - libdl.so => /system/lib/libdl.so
06-03 15:04:26.972 21925 22456 V dlopen  :     dl.dlopen - skipping /system/lib/libdl.so (system lib)
06-03 15:04:26.972 21925 22456 V dlopen  : dl.dlopen - load_func -> /system/lib/libc.so
06-03 15:04:26.973 21925 22456 E linker  : library "/system/lib/libc.so" ("/apex/com.android.runtime/lib/bionic/libc.so") needed or dlopened by "/data/app/~~WeHbZNvImOlLGI6NmkUR6w==/org.koreader.launcher.fdroid-pDhFadIDwgrTsN8sSzBTZQ==/lib/arm64/libluajit.so" is not accessible for the namespace: [name="(default)", ld_library_paths="", default_library_paths="/system/lib64:/system/system_ext/lib64", permitted_paths="/system/lib64/drm:/system/lib64/extractors:/system/lib64/hw:/system/system_ext/lib64:/system/framework:/system/app:/system/priv-app:/system/system_ext/framework:/system/system_ext/app:/system/system_ext/priv-app:/vendor/framework:/vendor/app:/vendor/priv-app:/system/vendor/framework:/system/vendor/app:/system/vendor/priv-app:/odm/framework:/odm/app:/odm/priv-app:/oem/app:/system/product/framework:/system/product/app:/system/product/priv-app:/data:/mnt/expand:/apex/com.android.runtime/lib64/bionic:/system/lib64/bootstrap"]
06-03 15:04:26.974 21925 22456 E NativeThread: Failed to run script: ffi/mupdf.lua:1047: attempt to index local 'pthread' (a nil value)
```

**Comment by ildar** [comment] 2023-06-03 17:24
This is the unofficial build, so called GSI.
https://github.com/phhusson/treble_experimentations/wiki/
Previous builds worked fine, though I didn't test all the latest monthly
versions. But I'm pretty sure that e.g. 2022.12 worked.

**Comment by NiLuJe** [comment] 2023-06-04 03:15
I meant the KOReader build ;o).

But the arch question stands for both the target and the KOReader build, though.

**Comment by ildar** [comment] 2023-06-04 07:06
arch is arm64 , of  course.

**Comment by shikantaza1** [comment] 2023-06-05 07:26
I have the same problem.
It crashes on the following devices: 
- Pixel 5, CalyxOS, Android 13
- Onyx Boox Poke 5, Android 11
On an old Onyx Boox Pro with Android 8 it used to work.

**Comment by amitbha** [comment] 2023-06-05 07:45
#10150  The same old problem

**Comment by ildar** [comment] 2023-06-05 08:13
Looks similar. I am sorry if it's the dup.
Anyway, my logs can be useful, please look it through.

**Comment by poire-z** [comment] 2023-06-05 08:19
(Can't help with anything, but) just asking, because it had been a point before: this happens with any of the fdroid release and our github release ?  Each may have a different build system.

**Comment by Frenzie** [comment] 2023-06-05 09:27
Wrt 64 bit they probably have the same issue on Android. (Assuming the amd64 mentioned above is a typo for aarch64.)

**Comment by shikantaza1** [comment] 2023-06-05 12:26
> (Can't help with anything, but) just asking, because it had been a point before: this happens with any of the fdroid release and our github release ? Each may have a different build system.

I usually do only use F-Droid. But I just downloaded the latest version from github on my Pixel 5/CalyxOS: same problem, i.e. crash after switching to re flow and then trying to change the page displayed.

**Comment by shikantaza1** [comment] 2023-06-05 13:54
However, there is a difference between the Github and F-Droid versions: the Github version does not produce a crash report, whereas the F-Droid version does, see attachment.
[KOReaderCrash.txt](https://github.com/koreader/koreader/files/11653249/KOReaderCrash.txt)

**Comment by NiLuJe** [comment] 2023-06-05 17:28
> the F-Droid version does

Well... kinda. What you attached is entirely useless, for instance ;).

(Not your fault, Android is terrible).

**Comment by fierceX** [comment] 2023-06-09 03:24
I use the version on github for my Android device, which also has this problem, and it was fine before, at least in 2022.

Device：Hisense A9 Android 11

**Comment by NiLuJe** [comment] 2023-06-09 14:15
@fierceX: Which architecture? Did you happen to switch from the arm build to the arm64?

(Because there's a much older issue with reflow and/or OCR on CJK that's not directly related to the gcc arm64 crashes discussed here ;)).

**Comment by ildar** [comment] 2023-06-11 20:06
It seems that all arm64 builds in FDroid are affected. While all arm32 work
fine.
I just tried the 1st build for arm64 in FDroid (2023.01) and it crashes too.
plz check

**Comment by fierceX** [comment] 2023-06-12 03:34
@NiLuJe I'm not sure about the architecture I used before, but now I've re-downloaded and installed arm32, and rearrangement is available, which may really be caused by architecture changes.

**Comment by pmendes** [comment] 2023-07-27 00:26
Also happens on a Boox Tab Ultra C (Android 11). Both the Github and F-Droid versions crash. This is one of the most important features of this app (reflow pdf). Hope it gets fixed soon.

**Comment by pmendes** [comment] 2023-07-27 01:07
also crashes a Lenovo Tab  P11 Pro (Android 11)

**Comment by NiLuJe** [comment] 2023-07-27 11:51
Was vaguely hoping the la g upgrade would  magically fix it, but nope. Can repro here on arm64. Funnily enough, it'll only crash when paging, reflow will actually show jo fine for the current page.

I don't recall if the hinting process starts up immediately or not, so that might be a hint (i.e., the hinting thread).

**Comment by kik-btaski** [comment] 2023-10-02 02:47
Same arm64-v8a


https://github.com/koreader/koreader/assets/142499381/cbc522bb-a9d6-4b84-b7a5-0a2def2cd74d

**Comment by amitbha** [comment] 2023-10-02 06:35
> It seems that all arm64 builds in FDroid are affected. While all arm32 work fine. I just tried the 1st build for arm64 in FDroid (2023.01) and it crashes too. plz check

Confirmed.
arm32 fine.
arm64 crash.

**Comment by NiLuJe** [comment] 2023-10-02 19:17
That unfortunately depends on the device ;).

Some have entirely dropped  support for 32-bits ABIs (notably, Pixels).

**Comment by PowerUser64** [comment] 2023-10-06 10:08
I was able to reproduce this crash with this PDF:
[github.com/stiber/Signal-Computing/releases/download/1.5/Signal.Computing.pdf](https://github.com/stiber/Signal-Computing/releases/download/1.5/Signal.Computing.pdf)

**Comment by hugleo** [comment] 2023-10-06 16:01
One thing here is interesting:

When I enable reflow, the screen reflects the desired sizes.

As long as I keep the bottom menu config opened, the crash doesn't happen.

![IMG_20231006_121948](https://github.com/koreader/koreader/assets/4573505/f4507980-3181-4c37-b498-f96fe2bb2aa2)

I can even change the contrast, for example, with the reflow applied.

I got crash bug only when I click on the middle of screen to hide the bottom config menu. Sometimes the crash log contains even less information:

![IMG_20231006_121808](https://github.com/koreader/koreader/assets/4573505/897bf2b4-4ac5-4540-a57b-c2a4c000567a)

I'll put some log flags if I got some more time for this.

**Comment by NiLuJe** [comment] 2023-10-06 16:48
Yup, noticed the same thing (mentioned in another duplicate of this), which lead me to thinking there might be a threading issue, because bionic, but couldn't find conclusive evidence of that on paper...

(Haven't bothered debugging this).

**Comment by hugleo** [comment] 2023-10-07 01:31
I think I've found the culprit.

The issue is because it's loading the libc.so from the path /system/lib but for arm64 the correct path is /system/lib64.

I just changed the line in my path here (https://github.com/koreader/android-luajit-launcher/pull/433):

from
"/lib:/system/lib:/system/lib64:/lib/lib?.so:/system/lib/lib?.so:/system/lib64/lib?.so"
        
to:

"/lib:/system/lib64:/system/lib:/lib/lib?.so:/system/lib/lib?.so:/system/lib64/lib?.so"

This way the 64-bit library is loaded first and then there are no more crashes.

This should be fixed by @benoit-pierre's patch here (https://github.com/benoit-pierre/koreader/blob/bpierre/subprojects/packagefiles/luajit-launcher/android-x86_64.patch) which uses ffi.arch for a proper check.

**Comment by NiLuJe** [comment] 2023-10-07 05:06
Huh. That would track with my threading hunch, yeah.

What's different from the libc.so in /system/lib from the one in /system/lib64? Linker script with different dependencies? Or weird bionic black magic?

**Comment by hugleo** [comment] 2023-10-07 07:33
> Huh. That would track with my threading hunch, yeah.
> 
> What's different in the libc.so in /system/lib from the one in /system/lib64? Linker script with different dependencies? Or weird bionic black magic?

we fail here:

https://github.com/koreader/koreader-base/blob/4733fa06a48beb30d5e70b31358e9e537d87eca4/ffi/mupdf.lua#L954C1-L976C4

The function get_pthread() always returns null

        ok, cached_pthread = pcall(ffi.load, "libc.so")
        if ok then return cached_pthread end

ok = false for pcall ;-)

**Comment by benoit-pierre** [comment] 2023-10-07 07:50
So the system has both 32bits and 64bits libraries, and because of our custom loader, we try to load a 32bits version of libc.so?

What's the error (`cached_pthread`)?

**Comment by benoit-pierre** [comment] 2023-10-07 07:53
Anyway, the original report is for arm64, and my patch is for x64, or did you adapt it?

**Comment by benoit-pierre** [comment] 2023-10-07 09:05
I can reproduce on master and my branch, PR with updated patch [here](https://github.com/koreader/android-luajit-launcher/pull/441).

**Comment by NiLuJe** [comment] 2023-10-07 15:34
Oh, so it's as dumb as "it's 32bit" ;p.

We skip system libs from DT_NEEDED entries, but this is a ffi.load, so it explicitly goes through, and it tries to load a 32bit lib => kaboom.

:+1:

**Closed** 2023-10-09 22:33 UTC
Labels: bug, need more info, Android, firmware

**Comment by TheFuzzStone** [comment] 2023-11-06 09:27
I didn't see a fix for this bug here in the notes, but, it's gone.

Just updated the app from F-droif and reflow in .pdf now works fine!    (I have "Onyx Boox Page")

**Comment by Frenzie** [comment] 2023-11-06 10:22
Probably fairly hidden as part of https://github.com/koreader/koreader/pull/10990
