### ISSUE TITLE
Opening the options on PB HD 1 crashes koreader every time

### ISSUE THREAD

**Issue by Taranchul** [koreader/koreader#5704] opened 2019-12-23 09:39 UTC
* KOReader version: v2019.11
* Device: Pocketbook Touch HD 1 with firmware U631.5.20.1527 from 2019-11-07.

#### Issue
After working for 2-3 times right after a fresh installation, opening the options causes koreader to crash every time. Curiously, after opening another ebook, the options worked again, until they also crashed. After that, they crashed every time in both ebooks. I could reproduce this with several ebooks.

#### Steps to reproduce
Install koreader on a PB Touch HD 1 and, in an ebook, try to open the options via tap at the top center or swipe down from the top center.

##### `crash.log` (if applicable)
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 12/23/19-10:05:29
 [*] Version: v2019.11

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
12/23/19-10:05:29 INFO  SoftwareVersion:  U631.5.20.1527
12/23/19-10:05:29 INFO  Blacklisting the C BB on this device
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
FB: computed size: 1671168
FB: id           : mxc_epdc_fb
FB: smem_len     : 1695744
FB: line_length  : 1088
FB: xres         : 1072
FB: xres_virtual : 1088
FB: yres         : 1448
FB: yres_virtual : 1536
FB: bpp          : 8
Atached mp shm: id 0 addr 2ad8c000 size 21736
epdc_default_init
epdc_default_rotate: w=1072 h=1448 scan=1088 mem=1695744
attach_shm: mtfb key=251331943 size=1666724
Atached mtfb shm: id 12800c addr 2d68d000 size 1666724
-------------------------
The task - koreader.app fb 0x2d68d000
 xres=1072 yres=1448 scanline=1072 vdepth=8 orient=0
-------------------------
attach_shm: ref key=2130378752 size=1560832
Atached ref shm: id 8001 addr 2d882000 size 1560832
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800000; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 10000 0 0 0 10000
ffi.load: inkview
12/23/19-10:05:29 INFO  initializing for device PBTouchHD
12/23/19-10:05:29 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
12/23/19-10:05:29 INFO  opening file /mnt/ext1/Deutsch/Was sind psychische Storungen (Telepolis).epub
12/23/19-10:05:29 ERROR failed to register crengine font: cannot register font <./fonts/nerdfonts/symbols.ttf>
12/23/19-10:05:29 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
ffi.load: z
ffi.load (assisted searchpath): ./libs/libz.so.1
ffi.load: sqlite3
12/23/19-10:05:29 INFO  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
12/23/19-10:05:29 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
12/23/19-10:05:29 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
12/23/19-10:05:29 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
12/23/19-10:05:29 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
12/23/19-10:05:29 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
12/23/19-10:05:30 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
12/23/19-10:05:30 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
12/23/19-10:05:30 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
12/23/19-10:05:30 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
12/23/19-10:05:30 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
12/23/19-10:05:30 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
12/23/19-10:05:30 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
CRE: styles re-init needed after load, re-rendering
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
```

**Comment by iamjustaguest** [comment] 2019-12-26 13:01
Confirmed

I can say by deleting the corresponding sdr folder (history) of the book when koreader is closed, options coming up again.
But the side effect is you lose the reading-position and other settings.
When a new history is written by closing and reopening the same book, it crashes again when opening the options.

**Comment by NiLuJe** [comment] 2019-12-26 15:09
Huh. Does this happen with PDFs (or with the same ePub but opened via MuPDF?).

**Comment by Taranchul** [comment] 2019-12-27 10:16
Thanks for your comments. @NiLuJe I'll test that as soon as I can. I'm a little limited in my actions right now because of a heavy cold I'm having.

**Comment by iamjustaguest** [comment] 2019-12-27 11:37
I checked some PDFs and the problem doesn't appear with them.

Using MuPDF requires to open a epub via Filemanager with long press and choosing the engine?
I can't check.
Filemanager doesn't work too, immediate crash when tapping on it, Segmentation fault.
At least for me, can someone confirm?

Is there another way to open a epub with MuPDF?

**Comment by Taranchul** [comment] 2019-12-27 11:51
@iamjustaguest You should be able to set is as the default application for specific file types via the file **system/config/extensions.cfg**.

**Comment by Frenzie** [comment] 2019-12-27 12:23
You can use the MuPDF renderer through the sdr or global settings file. Can't explain atm. ;-)

**Comment by iamjustaguest** [comment] 2019-12-27 12:43
@Taranchul
Thanks for your help.
Can you open the filemanager included in kooreader, does it come up when you tap on the second icon on the right side in koreader options?
Or crash it on tapping?
So it happens here. Like to know if that it is only on my side.

**Comment by pazos** [comment] 2020-03-27 21:14
Closing in favor of #6000, because it exhibits the same error `Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}`

**Closed by pazos** 2020-03-27 21:14 UTC
Labels: PocketBook, bug, firmware, help-wanted
