### ISSUE TITLE
Pocketbook No wifi updating again

### ISSUE THREAD

**Issue by andruha40** [koreader/koreader#7613] opened 2021-04-27 18:18 UTC
* KOReader version:the latest stable
* Device:626 lux 3

No possibility to update through wifi connection.

**Comment by Frenzie** [comment] 2021-04-27 18:22
I'll close this as presumably a duplicate of https://github.com/koreader/koreader/issues/7608. Otherwise please provide details.

**Closed by Frenzie** 2021-04-27 18:22 UTC
