### ISSUE TITLE
Android: Keep lights on 

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#2748] opened 2017-04-10 13:09 UTC
First, congratulations for releasing an Android version.

However, on Android it usually doesn't make sense to have a menu item that says E-ink optimization. It makes much better sense to have settings to adjust backlight and to block it from dimming. Then again, some e-ink devices have indeed Android.

**Comment by Frenzie** [comment] 2017-04-10 13:25
You mean to keep the window active (like while watching a YouTube video)?

Looks like it should be fairly easy:

http://stackoverflow.com/a/2134602/2470572

```java
getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
```

https://github.com/koreader/android-luajit-launcher/blob/f2e4a77bfc8ed4e1fa152028b98532b50f893dba/src/org/koreader/launcher/MainActivity.java#L27-L29

I'd do it myself but Android development and debugging is beyond arduous. Ubuntu Phone (RIP) and Jolla/Sailfish are actually comprehensible.

**Comment by ersi-dnd** [comment] 2017-04-10 15:53
> You mean to keep the window active (like while watching a YouTube video)?

Yes, and like in (any/most) video players, in some webbrowsers and in Coolreader and EBookDroid.

But the placement of the menu item needs consideration. I found that there's that dialog under the Frontlight menu item that works to change the lights on my phone, but it doesn't keep the lights on. Perhaps that dialog needs a button or checkmark to prevent the screenlock.

**Comment by houqp** [comment] 2017-04-11 07:05
The eink option is there because there are couple eink reader that's based of on android ;) 

I am surprised the frontlight menu actually works on your phone. But it doesn't keep the lights on, you mean it turns the light off after the level is adjusted?

**Comment by ersi-dnd** [comment] 2017-04-12 08:51
@houqp 
> By it doesn't keep the lights on, you mean it turns the light off after the level is adjusted?

There is a normal timeout to save the screen and battery. Just don't touch it for a while and it turns itself off. Koreader has no setting to affect this timeout, but for example Coolreader and EBookDroid have. 

My phone is Galaxy Note 4, but I think most Androids work the same.

**Comment by houqp** [comment] 2017-04-12 08:53
Oh I see, it's a feature request, not a bug report ;) I will label this issue accordingly, thanks.

**Comment by houqp** [comment] 2017-04-12 08:54
Also looks like @Frenzie's code should work.

**Comment by Frenzie** [comment] 2017-10-11 13:29
@ersi-dnd What I wrote works; with that line inserted the screen stays on indefinitely. What do CoolReader and EBookDroid do exactly? 

I was thinking it might make more sense to simply add a few minutes to the timeout, but it looks like you can't easily do that.

https://stackoverflow.com/a/31765828/2470572

Toggling this setting from within KOReader including a timeout would probably be easier. Anyway, just not sure if sticking it in there by default just like that is quite the right idea. :-)

**Comment by ersi-dnd** [comment] 2017-10-11 14:30
@Frenzie 
> What do CoolReader and EBookDroid do exactly?

They have the option "Keep screen on" aka "Timeout : Never". It's not turned on by default. The user must select it.

 It's a good option to have in the app. Normally users want the phone to close itself soon enough when they put the phone aside, but reading apps are an exception - you'd put the phone on the table and look carefully at the page, maybe take notes on paper or memorize. YT and video apps are another exception, because videos tend to be longer than the screen timeout time, but they tend to have the option turned on by default

**Comment by Frenzie** [comment] 2017-10-11 14:50
@mwoz123 You interested? At the basis it shouldn't need much more than something like this (pseudo-code, obviously):

```java
setKeepScreenOn(final bool keep_on) {
if true
getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
else // false
getWindow().clearFlags(android.view.WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
```
I think it needs to run on the UI thread, much like brightness. Combined with a little checkbox entry in the Screen menu I think it should work.

**Comment by mwoz123** [comment] 2017-10-12 15:52
I can add this to android-luajit but probably not today.

**Comment by Frenzie** [comment] 2017-10-12 16:06
Alright, thanks!

As an aside, this morning I noticed the Android app GPS Test also presents these options to the user. (Settings in screenshot are the default.)
![screenshot_20171012-110930](https://user-images.githubusercontent.com/202757/31506404-9de668c6-af77-11e7-87ee-8b89944d21b2.png)

**Comment by mwoz123** [comment] 2017-10-13 10:50
I wish development could be done from phone without PC..
It was 2 min to code it in notepad, 15 min for git branching, pc startup etc:/

Once merged it can be implemented in Koreader.

**Comment by taohansen** [comment] 2018-11-14 20:43
I still don't see this option anywhere. I think I've checked all the menu options...

**Comment by TrungMC** [comment] 2019-01-01 13:50
Moon Reader has this feature. I find that I need this feature for the remote page turner. When the screen timeout (which seems very short), only touching the screen will wake it and turn the page.

**Comment by Frenzie** [comment] 2019-01-01 17:15
@pazos 's PR is almost ready to go. :-)

**Closed** 2019-01-10 21:57 UTC
Labels: Android, enhancement
