### ISSUE TITLE
Koreader doesn't start after v2019.08-43

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#5271] opened 2019-08-26 15:42 UTC
After the last two updates, my koreader at kindle can't start. Anyone knows how to fix it? It works fine at v2019.08-39

              launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 08/26/19-12:38:32
 [*] Version: v2019.08-51-gba8099f_2019-08-25

./luajit: frontend/util.lua:7: loop or previous error loading module 'gettext'
stack traceback:
	[C]: in function 'require'
	frontend/util.lua:7: in main chunk
	[C]: in function 'require'
	frontend/gettext.lua:199: in function 'changeLang'
	frontend/gettext.lua:362: in main chunk
	[C]: in function 'require'
	./reader.lua:32: in main chunk
	[C]: at 0x00013ef9

**Comment by Frenzie** [comment] 2019-08-26 15:49
Duplicate of https://github.com/koreader/koreader/issues/5269. I just fixed that like an hour ago. ;-)

**Closed by Frenzie** 2019-08-26 15:49 UTC
Labels: bug, duplicate
