### ISSUE TITLE
during evernote export; no way to cancel if process seems stuck; also export still crashing on latest nightly

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5790] opened 2020-01-23 19:34 UTC
* KOReader version: 2020 nightly (installed jan 23rd 2019);  2020-01-22
* Device: PW4

#### Issue
When trying to export the notes from one book only to evernote, i updated to a development release before realizing the fix for #5609 was already baked into the last stable release 12.2019.  

Anyways, here is the relevant portion from crash.log

```
[root@kindle koreader]# tail -f crash.log
01/23/20-13:30:19 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
01/23/20-13:30:19 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
./luajit: plugins/evernote.koplugin/main.lua:559: attempt to call method 'find' (a nil value)
stack traceback:
        plugins/evernote.koplugin/main.lua:559: in function 'exportClippings'
        plugins/evernote.koplugin/main.lua:452: in function 'exportCurrentNotes'
        plugins/evernote.koplugin/main.lua:259: in function 'action'
        frontend/ui/uimanager.lua:751: in function '_checkTasks'
        frontend/ui/uimanager.lua:1034: in function 'handleInput'
        frontend/ui/uimanager.lua:1120: in function 'run'
        ./reader.lua:279: in main chunk
        [C]: at 0x00013ef9
lipc-wait-event exited normally with status: 0

```

This has happened as well as the kindle locking up and me having to hold down the power button for 10+ seconds to get it to restart.

There doesn't seem to be a way to cancel the evernote export once it's been started.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by arooni** [comment] 2020-01-23 19:38
perhaps this also relevant:

```
evernote account info
11.7 KB (0%) remaining this month
Your monthly limit resets in 4 days

Monthly uploads: 60 MB
Note size limit: 25 MB
```

**Comment by NiLuJe** [comment] 2020-01-23 20:52
There's a bunch of those happening (find on an empty table or a nil instead of a string, IIRC).

Most prominently #4285

**Comment by Frenzie** [comment] 2020-06-30 15:42
Closing as a duplicate of #4285.

**Closed by Frenzie** 2020-06-30 15:42 UTC
Labels: Plugin, bug, duplicate, help-wanted
