### ISSUE TITLE
Stuck on "USBMS session in progress" screen after unplugging device

### ISSUE THREAD

**Issue by lhandf** [koreader/koreader#9930] opened 2022-12-18 16:50 UTC
* KOReader version: v2022.11
* Device: Kobo Clara 2E

#### Issue

I have had this device for a bit over a week now. I installed koreader the first day, and it's worked great all this time. However, I was transferring some books via USB, using Calibre with the Folder Device Interface. According to Calibre this completed successfully, but when I unplugged it, it remained stuck on the "USBMS session in progress." screen.

I've tried to follow factory reset instructions, and manual reset instructions to not avail. When I hold the power button, sometimes the LED lights up then starts blinking, and sometimes the backlight lights up. However, the same USBMS screen stays.

I'm not entirely sure how I could extract logs from this without taking it apart, however this is what I get when connecting it to my PC:

```
[1188821.811947] usb 1-4: new high-speed USB device number 83 using xhci_hcd
[1188821.949156] usb 1-4: config 1 interface 0 altsetting 0 bulk endpoint 0x81 has invalid maxpacket 64
[1188821.961154] usb 1-4: New USB device found, idVendor=18d1, idProduct=0d02, bcdDevice= 2.21
[1188821.961157] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[1188821.961158] usb 1-4: Product: USB download gadget
[1188821.961159] usb 1-4: Manufacturer: FSL
[1188821.961160] usb 1-4: SerialNumber: <string of digits>
[1188823.379789] usb 1-4: USB disconnect, device number 83
[1188829.150998] usb 1-4: new high-speed USB device number 84 using xhci_hcd
[1188829.267245] usb 1-4: Device not responding to setup address.
[1188829.474340] usb 1-4: Device not responding to setup address.
[1188829.682000] usb 1-4: device not accepting address 84, error -71
```

Any ideas on how to proceed?

**Comment by NiLuJe** [comment] 2022-12-18 18:32
Although that might not change anything on a Clara 2E, try to do that with WiFi enabled, to see if it's not simply the dreaded Libra 2/Nia/Clara 2E EPDC hang rearing its ugly head.

The tricky part is: if it is, we can't do anything about it. If it isn't, you need WiFi anyway to debug USBMS, so, kind of a catch-22 there ;o).

See [this post (as well as the linked entry)](https://github.com/koreader/koreader/issues/8896#issuecomment-1066202334) for how to get USBMS logs. This will *not* work with KOReader's SSH server.

**Comment by NiLuJe** [comment] 2022-12-18 18:36
Unless you actually meant that you can't get it to reboot *at all*? (You might need the device to be unplugged for the long-long-long-press on the power button to actually turn it off).

**Comment by lhandf** [comment] 2022-12-18 18:42
I've had it unplugged since I first posted the issue, still has the USBMS screen showing. I long-press the power button for over 30 seconds, nothing happens. I press on the button again, the LED flashes a few times, but nothing on the screen has changed.

I'll be happy to provide more details in general with the Clara 2E, if/when I can get it working again. I'm not even sure what the flashing LED usually means.

**Comment by lhandf** [comment] 2022-12-18 18:50
Actually, a bit of a new development. The backlight was lit, so I connected it via USB and it was mounted and detected by Calibre. However, the screen still shows the USBMS screen even though it appears koreader was entirely removed from the device (probably from one of my many attempts at a reset).

I'm a tad baffled by this and I'm not really sure what the best thing to try to get it off that screen is.

**Comment by NiLuJe** [comment] 2022-12-18 18:52
The long-press (a few seconds) turns the device *off*. That doesn't affect the screen's content at all, nor does it affect the power LED (unless it was on, at which point it runs off, but that's extremely unlikely ;p). The only visible trigger would be the frontlight, which would turn off.

Once the device is off, a shorter button press will power on the device. At which point: the power LED starts blinking. A couple seconds later, the screen flashes to *white* (LED still blinks). A few seconds later, the boot animation starts displaying (LED still blinks). Finally, LED stops blinking, and Nickel appears.

Depending on the device, there's a factory reset escape hatch, which usually requires booting with a few specific buttons pressed, or letting the device fail to boot a number of times in succession.
I don't have any personal experience with the exact procedure for the Clara 2E, so I can't really tell you if there's any specific gotchas to it.

**Comment by NiLuJe** [comment] 2022-12-18 18:53
If you connect it to a computer after the LED blinking, does it still enumerate?

**Comment by NiLuJe** [comment] 2022-12-18 18:56
Looking at the dmesg excerpts above, that might look like Freescale (NXP)'s download mode thingy, which is... unexpected. (I'm not familiar with the exact VID:PID combo, but that's certainly not the Kobo:Clara2E ones ;p).

There might be a way to trip it with a custom cable, which might hint at some sort of snafu with your cable :?

**Comment by lhandf** [comment] 2022-12-18 18:58
It's enumerated right now. When I look inside, it looks like the default (without koreader installed):

```shell
$ ls -a
.  ..  .adobe-digital-editions  driveinfo.calibre  .kobo  .kobo-images  metadata.calibre
```

However, the confusing part is the "USBMS session in progress" has never gone away since this I first encountered this issue. So I'm not sure if there's something I can do while I have it enumerated to force the screen to update or something.

**Comment by NiLuJe** [comment] 2022-12-18 19:00
Is that actually the proper contents in full, or just stuff that calibre might have put there thinking it looked like a Kobo?

What's the dmesg output on your host?

**Comment by lhandf** [comment] 2022-12-18 19:03
That's the entire contents (with files inside the folders). I'm pretty sure Calibre just added its files because it was open when I connected the device.

Here's the output from dmesg:
```
[1197479.508652] usb 1-4: new high-speed USB device number 125 using xhci_hcd
[1197479.658113] usb 1-4: New USB device found, idVendor=2237, idProduct=4235, bcdDevice= 4.01
[1197479.658118] usb 1-4: New USB device strings: Mfr=3, Product=4, SerialNumber=5
[1197479.658120] usb 1-4: Product: eReader-4.33.19730
[1197479.658122] usb 1-4: Manufacturer: Kobo
[1197479.658123] usb 1-4: SerialNumber: N50629C039080
[1197479.674141] usb-storage 1-4:1.0: USB Mass Storage device detected
[1197479.674251] scsi host6: usb-storage 1-4:1.0
[1197480.731402] scsi 6:0:0:0: Direct-Access     Linux    File-Stor Gadget 0401 PQ: 0 ANSI: 2
[1197480.731942] sd 6:0:0:0: Power-on or device reset occurred
[1197480.732282] sd 6:0:0:0: [sdb] 29633533 512-byte logical blocks: (15.2 GB/14.1 GiB)
[1197480.732564] sd 6:0:0:0: [sdb] Write Protect is off
[1197480.732566] sd 6:0:0:0: [sdb] Mode Sense: 0f 00 00 00
[1197480.732842] sd 6:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[1197480.748111]  sdb:
[1197480.748353] sd 6:0:0:0: [sdb] Attached SCSI removable disk```

**Comment by NiLuJe** [comment] 2022-12-18 19:20
Okay, that's an actually sane output, at least, unlike the OP ;).

What happens if you run `eject /dev/sdb` (when nothing's holding the partition busy)? (might need to be run as a privileged user, depending on how your distro sets up permissions for removable drives).

**Comment by NiLuJe** [comment] 2022-12-18 19:25
Random extra query: you didn't happen to have disabled the "USB connected" popups, in either Nickel or KOReader?

(I don't recall how it works in Nickel, but, IIRC, it involves poking at the config file manually. In KOReader, it's in [Gear] > Device > USB mass storage > Disable confirmation popup)

**Comment by lhandf** [comment] 2022-12-18 19:41
I did not disable it. I had the popup show up each time I plugged it in before and had to press it.

I closed Calibre and did `eject /dev/sdb`. It hasn't changed the display but it did light up the backlight after a moment.

**Comment by NiLuJe** [comment] 2022-12-18 19:47
Okay, try unplugging it, and doing a long power-press (a few seconds), until the frontlight turns off. Wait a few seconds, then try to power it back on?

**Comment by lhandf** [comment] 2022-12-18 19:57
When turning it back on the LED flashes and then the backlight lights up. Still stuck with the same screen. I'm starting to think it might need the battery to drain or to open it up and unplug the battery. That or it's borked hardware.

**Comment by NiLuJe** [comment] 2022-12-18 20:29
That's starting to look like it, yeah. I'm mildly confused if it *still* enumerates if you plug it back in, though...

**Comment by lhandf** [comment] 2022-12-18 21:26
Yeah I'm kind of out of ideas. Kinda silly to try to get it replaced with proof that the warranty was definitively broken stuck on it too :stuck_out_tongue:

**Comment by lhandf** [comment] 2022-12-18 22:08
Just to reiterate where it's at now:

- Screen has been showing the "USBMS session in progress." the entire time since I submitted this issue. No changes at all.
- When unplugged, long-pressing the button turns off the backlight.
- Turning it on again makes the LED start flashing for a bit, then there's a pause with no LED or backlight, then the backlight comes up again.
- When plugged in, doing a long-press and press results in the `USB download gadget` dmesg as shown in the first post above.

I know I managed to get it to properly enumerate a few times as well, but I haven't been able to do so consistently.

**Comment by NiLuJe** [comment] 2022-12-18 22:09
I'm not entirely sure anybody would care, but I understand the reasoning ;).

Note that, eInk being what it is, a battery drain will *not* affect the screen, it'd need to boot properly to reinit the screen to white.

**Comment by NiLuJe** [comment] 2022-12-18 22:11
The fact that it seems stuck in iMX downloader mode is... strange (if you asked me how one were to boot a Kobo in that mode, I couldn't actually answer you without looking it up, so, it magically happening just with a USB cable is unexpected). But thanks for the details, that's always helpful ;).

**Comment by pazos** [comment] 2024-01-11 20:02
Closing old tickets labeled as "need more info" that are not updated anymore. Feel free to open new ones if you can reproduce on the latest release.

**Closed by pazos** 2024-01-11 20:02 UTC
Labels: Kobo, need more info, firmware

**Comment by NiLuJe** [comment] 2024-01-11 22:18
Might be a dead screen, or a perfectly unseated flex cable, FWIW.

In any case, now that I have a Clara 2E myself, I can confirm that I did not murder it by simply plugging it in ;p.

**Comment by NiLuJe** [comment] 2024-01-11 23:16
On the upside, I realized that [charger type detection](https://github.com/koreader/KoboUSBMS/commit/35a101f947108b12a1a97324ce65f119dfa5a69b) was broken, so, yay, random fix ;p.
