### ISSUE TITLE
Blind highlights editing at the edge

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#5973] opened 2020-03-17 06:38 UTC
* KOReader version: 2020.03.02
* Device: Kindle PW3

#### (minor UX) Issue
I was pleased to find out that making a highlight across two pages is so convenient! After dragging to the next page, showed text shifts further a little to show highlighting pieces. 

However, editing such two-page highlight is not so obvious.

For example (in a fb2.zip book):
#### Steps to reproduce
1) Start highlighting from a bottom right corner on a page, drag to the next page. 
2) It will allow to select text on the second page just fine, and return to showing the first page. 
3) Now, tap this highlight, move the starting point to the right. 
4) It will de-select highlight area fine, but once it is beyond this page, it doesn’t turn to the next page. So further de-highlighting happens blindly, although correctly. 

Maybe it should detect where this highlight is interrupted by a page break? And then turn the page accordingly?

**Comment by pazos** [comment] 2020-03-18 23:32
Duplicate of #5004

**Closed by pazos** 2020-03-18 23:32 UTC
Labels: UX, duplicate

**Comment by poire-z** [comment] 2020-03-20 11:41
Not exactly a duplicate. This one was quite easy to fix, I'll PR a fix.
(#5004 is a lot more complex, and I'm not interested :)
