### ISSUE TITLE
Viewarea partly cut off on the lower end of the screen

### ISSUE THREAD

**Issue by Andreas-Coding** [koreader/koreader#9901] opened 2022-12-11 16:01 UTC
* KOReader version: 2022.10 (fdroid), 2022.11 (manual installation)
* Device: Fairphone 4 (Android 11)

#### Issue

![Screenshot from the file explorer](https://user-images.githubusercontent.com/56117677/206913770-60882356-2f95-43d0-b099-6a15e8d06e93.png)
![Screenshot from within the help file](https://user-images.githubusercontent.com/56117677/206913981-9835c069-ff7d-485f-a7b4-ea0cb32d81c2.png)

Part of the view isn't displayed.

It seams to me like the notch cut out isn't correctly detracted from the screen height on this device. This also affects all interactions with the app.

#### Steps to reproduce

Install KOReader in version 2022.10 on a Fairphone 4

**Comment by pazos** [comment] 2022-12-11 19:14
I'm afraid there's nothing we can do unless fixing https://github.com/koreader/koreader/issues/9446 automatically fixes this.

On android 13 the good news are: all devices are affected, so we can reproduce the issue and fix the bug. On android 9-12 all devices work, except the fairphone 4 :/

**Comment by Andreas-Coding** [comment] 2022-12-11 19:47
Thanks for linking 9446.
I've tried the suggested `/koreader/patches/10-screen-offset.lua` fix from there and it seamed to have worked with version 2022.11 from the github releases (haven't tested any other yet).
The offset I've found to be working is `39`.

You've mentioned there to be a fix for android 13. Is there an eta on when the update containing that fix will go live?

**Comment by NiLuJe** [comment] 2022-12-11 19:55
There's an *open issue*, there's no fix yet because none of the current contributors have access to an affected device (and that includes the emulator, because the x86_64 build is currently broken).

**Comment by Andreas-Coding** [comment] 2022-12-11 20:12
I see. Thank you for the information.
As is, I think I'll continue using the patches based fix and wait for the update and see if that too fixes my issue.

**Comment by rogalian** [comment] 2023-02-09 19:47
![Screenshot_20230209-190139_KOReader](https://user-images.githubusercontent.com/5140184/217912102-0b8dc4c0-bcfe-46fa-8d82-9e7d30b8aef0.png)

Same here, started happening after LineageOS went to 20 (Android 13). Poco X3 NFC (surya)

**Comment by pazos** [comment] 2023-02-10 09:31
@WX4300 @rogalian: you might want to keep an eye on https://github.com/koreader/koreader/issues/9446, which covers a related issue on android 13 and will be fixed eventually.

This one is for phones where the same stuff happens on previous android versions. Until now only the Fairphone seems affected. Not sure if we can fix it.

**Comment by pazos** [comment] 2023-07-06 20:19
@Andreas-Coding: feel free to try v2023.05 or v2023.06. Both implement the new method that works on android 13 (and screw something on previous versions). Please provide feedback if it works because we're going to revert the behaviour from 4.3 to 12, so we would need to add this specific device as a special snowflake :)

**Closed by pazos** 2023-07-06 20:19 UTC
Labels: wontfix, Android, firmware

**Comment by rogalian** [comment] 2023-07-07 05:59
Works here, thank you!
