### ISSUE TITLE
Quick gesture/multiswipe reference

### ISSUE THREAD

**Issue by crispinb** [koreader/koreader#12807] opened 2024-11-27 08:49 UTC
**Does your feature request involve difficulty completing a task? Please describe.**
Gestures are a great shortcut. One problem I have though is just remembering them, especially after customising a few multiswipes. 

**Describe the solution you'd like**
A page showing a quick visual overview of all available gestures. Displaying the page could be assignable to a gesture.

**Describe alternatives you've considered**
Rather than a new screen, which I can see would be a bit of work, it would alternatively be nearly as  helpful if the 'Taps and gestures -> Gesture Manager -> Multiswipes' menu display could be assigned to a gesture for quick reference. I hunted for a while assuming this might already be possible, but couldn't see how. I'm new to KOReader so forgive me if I've missed something relevant in the docs.

**Additional context**
N/A

**Comment by hius07** [comment] 2024-11-28 13:24
Duplicate of https://github.com/koreader/koreader/issues/7788.

**Comment by pazos** [comment] 2024-11-28 19:53
Duplicate of https://github.com/koreader/koreader/issues/7788.

**Closed by pazos** 2024-11-28 19:53 UTC
Labels: enhancement
