### ISSUE TITLE
Frontlight settings doesn't work on Inkook Prime (Android)

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#2661] opened 2017-03-20 08:36 UTC
* KOReader version: koreader-nightly-20170308
* Device: Inkook Prime (Android)

#### Issue
Frontlight changes doesn't work on Inkbook Prime (Android) .
Changing light with buttons nor bar has no effects.

#### Steps to reproduce
Open top menu -> Frontlight. Change settings with buttons or use bar.
Changes are not reflected.

**Comment by houqp** [comment] 2017-03-27 04:05
First step, someone need to help figure out how to interface with frontlight in inkbook prime.

**Comment by Hzj-jie** [comment] 2017-03-27 06:35
Oh, it does not use the regular Android way.

**Comment by mwoz123** [comment] 2017-03-27 20:49
I can help  but will need to know what to do?

**Comment by mwoz123** [comment] 2017-03-28 12:26
Would that be useful if I've started android  system, then play around with Frontlight, and next generate system log (with "report bug" from "developer options")? 

It's massive (around 3 MB) but should contain useful information?

**Comment by pazos** [comment] 2019-03-03 15:19
@mwoz123: you need to enable frontlight on your system firmware. Once fl is enabled you should be able to change its level. This is a known limitation on rk3026 devices.

**Comment by pazos** [comment] 2019-03-08 00:02
pinging @silberzwiebel about this, can you try to reproduce on your device?, thanks

**Comment by silberzwiebel** [comment] 2019-03-08 09:01
> @mwoz123: you need to enable frontlight on your system firmware. Once fl is enabled you should be able to change its level. This is a known limitation on rk3026 devices.

If you with "enable frontlight on your system firmware" mean that one needs to enable the frontlight from inkbook's default android toggle, then yes:
- If the frontlight is turned on with android's default toggle and koreader is started afterwards, koreader is able to change the frontlight (on/off as well as brightness levels). 
- If the frontlight is turned off from android's default toggle, koreader's frontlight settings have no effect whatsoever, the light remains off.

So, yes, I think it's a duplicate of #3360.

**Comment by pazos** [comment] 2019-03-08 16:24
@silberzwiebel, thanks!!

**Closed** 2019-03-08 16:25 UTC
Labels: Android, duplicate, firmware
