### ISSUE TITLE
Koreader crashes at launch after update 

### ISSUE THREAD

**Issue by mathitejeda** [koreader/koreader#11487] opened 2024-02-23 16:43 UTC
* KOReader version: 2024.01
* Device: redmi note 9 pro

#### Issue

After updating the app to the 2024.01 version it started to crash at launch. I tried to fix it by deleting cache but It keeps crashing.

#### Steps to reproduce

Launch the app

##### `crash.log` (if applicable)

```
<Paste crash.log content here>

--------- beginning of system
02-23 13:33:16.838 I/ForceDarkHelperStubImpl(30618): initialize for org.koreader.launcher.fdroid , ForceDarkOrigin
```

**Comment by benoit-pierre** [comment] 2024-02-23 16:54
Duplicate of #11399?

**Closed** 2024-02-23 16:59 UTC
Labels: Android, duplicate
